mapbox/mapbox-gl-native

platform/android/MapboxGLAndroidSDK/gradle.properties
=> Release Android v5.3.2

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java, platform/darwin/src/MGLMapSnapshotter.mm
Merges `release-agua` back to `master`
=> Merge release-agua back to master 

platform/default/asset_file_source.cpp, platform/default/default_file_source.cpp, platform/default/local_file_source.cpp, src/mbgl/storage/asset_file_source.hpp, test/storage/asset_file_source.test.cpp, test/storage/local_file_source.test.cpp
Port https://github.com/mapbox/mapbox-gl-native/pull/11040 to boba
=> [core] align implementations of local and asset file source

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md
Changelog update pod spec bump
=> [ios] Update changelog and bump pod spec to 4.0.0-beta.1

src/mbgl/style/parser.cpp, test/fixtures/style_parser/font_stacks.json, test/style/style_parser.test.cpp
Backport https://github.com/mapbox/mapbox-gl-native/pull/11055
=> [core] don't force downloading of Open Sans fonts

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
Closes #11082.
Capturing from external PR https://github.com/mapbox/mapbox-gl-native/pull/11083.
/cc @colinrtwhite
=> Log lack of permissions only if enabling location

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
=> Add style specification links to javadoc

platform/android/DISTRIBUTE.md, platform/android/src/example_custom_layer.cpp
Follow up from external PRs in https://github.com/mapbox/mapbox-gl-native/pull/11091 & https://github.com/mapbox/mapbox-gl-native/pull/10848
cc @olheimer @erolbaykal
=> Documentation typos

platform/android/CHANGELOG.md
Refs https://github.com/mapbox/mapbox-gl-native/issues/11098
=> Update changelog for v5.4.0

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyBearingTracking.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java, src/mbgl/gl/context.cpp
=> Release android v5.4.0

circle.yml, platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyBearingTracking.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java, platform/android/scripts/exclude-activity-gen.json, src/mbgl/gl/context.cpp
This PR cherry picks the changes made for v5.4.0 to the release-boba branch.
Note: https://github.com/mapbox/mapbox-gl-native/commit/1a2c316f951ad4d19b0eb89eba2559801deaa385 is already on release-boba
=> Cherry pick v5.4.0 to release-boba

include/mbgl/util/run_loop.hpp, include/mbgl/util/thread.hpp, platform/android/src/run_loop.cpp, platform/darwin/src/run_loop.cpp, platform/default/run_loop.cpp, platform/qt/src/run_loop.cpp, test/util/run_loop.test.cpp
Port https://github.com/mapbox/mapbox-gl-native/pull/11005 which reduces the likelihood of iOS data protection violations.
=> Backport: Prioritize thread pause()/resume() calls

src/mbgl/layout/symbol_projection.cpp
Fixes issue #10956.
/cc @ansis @tobrun
=> Cherry pick #10956 fix to boba

platform/android/MapboxGLAndroidSDK/proguard-rules.pro
=> Add optional location provider lost to proguard config

platform/android/CHANGELOG.md
=> Update changelog for v5.4.1

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/proguard-rules.pro, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRenderThread.java, platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml
Refs https://github.com/mapbox/mapbox-gl-native/issues/11162, this PR makes sure all changes that went into v5.4.1 will also be available in upcoming v6.0.0-beta.x releases.
=> Cherry pick 5.4.1 changes

include/mbgl/style/conversion/tileset.hpp, test/style/conversion/tileset.test.cpp
Cherry pick of #11176  for Agua patch.
=> TileJSON Bounds allows values inclusive of world extents

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md
=> [ios] Bump podspec to 3.7.4

platform/android/CHANGELOG.md
Cherrypick of changelog from release-boba so users can see the latest changelog directly on master. Refs #11188
=> Changelog for 6.0.0-beta.2

platform/android/MapboxGLAndroidSDK/proguard-rules.pro, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRenderThread.java, platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml, platform/darwin/src/MGLMapSnapshotter.mm, platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/ios/app/MBXSnapshotsViewController.m, platform/ios/app/MBXViewController.m, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/src/MGLCameraChangeReason.h, platform/ios/src/MGLLocationManager.m, platform/ios/src/MGLMapView.mm, platform/ios/src/MGLMapViewDelegate.h, platform/ios/src/MGLMapboxEvents.m, platform/ios/src/MGLTelemetryConfig.h, platform/ios/src/MGLTelemetryConfig.m, platform/ios/test/MGLMapViewDelegateIntegrationTests.swift, platform/ios/uitest/MapViewTests.m, platform/macos/CHANGELOG.md
Merges the latest changes in v3.7.4 back to master.
=> Merge release-agua back to master.

src/mbgl/programs/hillshade_prepare_program.hpp, src/mbgl/renderer/layers/render_hillshade_layer.cpp, src/mbgl/renderer/layers/render_hillshade_layer.hpp, src/mbgl/renderer/sources/render_raster_dem_source.cpp, src/mbgl/renderer/sources/render_raster_dem_source.hpp, src/mbgl/shaders/hillshade_prepare.cpp
ported from https://github.com/mapbox/mapbox-gl-js/pull/6103 
still need to update the gl-js sha when the above PR is merged 
cc @nickidlugash @ibesora
=> add maxzoom uniform to support external tilesets

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Events.java
- Initializes events when creating `Mapbox` instance
cc @boundsj @zugaldia @lilykaiser @electrostat @tobrun
=> [android] Initialize events when creating Mapbox instance

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
A quick, tiny release to address https://github.com/mapbox/mapbox-gl-native/issues/11225.
=> [ios] Bump podspecs for 3.7.5

platform/android/src/geojson/feature_collection.cpp, platform/android/src/geojson/line_string.cpp, platform/android/src/geojson/multi_polygon.cpp, platform/android/src/geojson/point.cpp
This should resolve #11212 but should be tested before it could be closed
=> [android] missing DeleteLocalRef

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java, platform/android/MapboxGLAndroidSDKTestApp/build.gradle, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/OrientationTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/action/WaitAction.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/BaseActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/widgets/CompassViewTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceTest.java, platform/android/gradle/dependencies.gradle, platform/android/src/file_source.cpp, platform/android/src/file_source.hpp
=> FileSource activation/deactivation tests

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
closes #11256 
cc @danesfeder @cammace
=> Decouple map padding from overlain views

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
=> Don't disable zoom button controller zooming with gesture disabled zoom

include/mbgl/style/conversion/data_driven_property_value.hpp, include/mbgl/style/expression/literal.hpp
=> Correctly parse constant expressions in dds style properties

platform/android/src/conversion/collection.hpp, platform/android/src/file_source.cpp, platform/android/src/map/camera_position.cpp, platform/android/src/map/image.cpp
This is a cherry-pick of https://github.com/mapbox/mapbox-gl-native/pull/11253
=> [android]  a couple missing DeleteLocalRef

circle.yml, platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/ImageSource.java, platform/android/src/conversion/collection.hpp, platform/android/src/example_custom_layer.cpp, platform/android/src/file_source.cpp, platform/android/src/map/camera_position.cpp, platform/android/src/map/image.cpp, platform/android/src/style/sources/image_source.cpp, platform/android/src/style/sources/image_source.hpp, src/mbgl/gl/context.cpp, src/mbgl/renderer/layers/render_custom_layer.cpp
=> Release android v5.5.0

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/ImageSource.java, platform/android/src/example_custom_layer.cpp, platform/android/src/style/sources/image_source.cpp, platform/android/src/style/sources/image_source.hpp, src/mbgl/gl/context.cpp, src/mbgl/renderer/layers/render_custom_layer.cpp
Re. #11262. Cherry picking to the `release-boba`.
=> [android] expose ImageSource coordinates setter (CP #11262 to boba), missing commits from 5.5.0

cmake/core-files.cmake, include/mbgl/style/expression/length.hpp, src/mbgl/style/expression/compound_expression.cpp, src/mbgl/style/expression/length.cpp, src/mbgl/style/expression/parsing_context.cpp
* https://github.com/mapbox/mapbox-gl-js/pull/6243
* https://github.com/mapbox/mapbox-gl-js/pull/6244
Fixes #11345.
=> Cross-port recent expression typing changes

platform/android/CHANGELOG.md
=> Updated changelog to reflect 5.5.0 and 6.0.0-beta.3 changes

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraAnimatorActivity.java
Test app was crashing when clicking home button in `CameraAnimatorActivity`.
=> Fix CameraAnimatorActivity home button

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java
This PR reworks the exposed match expression on the android binding to be compliant to what the style specification describes. More context in #11372. 
edit: need to fixup additional tabs in this PR
=> Rework match expression

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/FillExtrusionActivity.java, platform/android/gradle/dependencies.gradle, platform/android/src/geojson/conversion/geometry.hpp
take advantage of MAS 3.0-beta.3 changes,
ie fromLngLats() take double arrays now
Partially addresses https://github.com/mapbox/mapbox-java/issues/710
=> [android] take advantage of MAS 3.0-beta.3 changes 

platform/android/MapboxGLAndroidSDK/build.gradle, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
=> Downgrade to java 7

platform/android/README.md
pulled in https://github.com/mapbox/mapbox-gl-native/pull/11359 to run ci
=> Ckesc: Update README.md

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
/cc @fabian-guerra @lilykaiser
=> [ios] Release prep for ios-v3.7.6

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/GestureDetectorActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/ResourceUtils.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_gesture_detector.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/item_gesture_alert.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_gestures.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml
Closes #11406.
This activity can gradually expand as we add more features through [the gestures library](https://github.com/mapbox/mapbox-gestures-android) and `MapGestureDetector`.
=> Test activity for gestures manager

platform/android/MapboxGLAndroidSDK/proguard-rules.pro, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Events.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/telemetry/HttpTransportTest.java, platform/android/gradle/dependencies.gradle
- Fixes latest Events lib changes
👀 @electrostat @tobrun @LukasPaczos
=> Fix Events lib changes

platform/android/src/file_source.cpp
Release-boba equivalent of https://github.com/mapbox/mapbox-gl-native/pull/11480
=> Verify that optional has value before accessing it

platform/android/CHANGELOG.md
Refs #11484, this PR cherry picks the changelog update for v6.0.0-beta.4 to master.
=> Changelog for v6.0.0-beta.4

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties
refs https://github.com/mapbox/mapbox-gl-native/issues/11484
=> Release android v6.0.0 beta.4

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java, platform/android/src/http_file_source.cpp, platform/android/src/map/image.cpp
https://github.com/mapbox/mapbox-gl-native/pull/11350
https://github.com/mapbox/mapbox-gl-native/pull/11367
https://github.com/mapbox/mapbox-gl-native/pull/11364
https://github.com/mapbox/mapbox-gl-native/pull/11413
=> Cherry pick v5.5.1 changes

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/11505
=> String, number and bool with multiple values

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties
=> Release Android v5.5.1

platform/ios/ios.xcodeproj/project.pbxproj
Moved Mapbox framework from integration target to being embedded in the host app.
=> Fix for integration tests running on device.

platform/android/MapboxGLAndroidSDK/proguard-rules.pro
=> Fixup MAS 3.0.1 bump

platform/node/src/node_thread_pool.cpp
=> Remove unused lambda capture

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/11628.
=> Gesture event listeners lists documentation

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
=> Scale animation focal point

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/imagegenerator/SnapshotActivity.java, platform/android/src/image.cpp, platform/android/src/map_renderer.cpp, platform/android/src/map_renderer.hpp, platform/android/src/native_map_view.hpp, platform/android/src/offline/offline_manager.cpp, platform/android/src/offline/offline_region.cpp, platform/android/src/snapshotter/map_snapshotter.cpp, platform/android/src/text/local_glyph_rasterizer.cpp, src/mbgl/gl/program.hpp
Cherry picks the following PRs to `release-agua` for a potential 5.5.2 release:
- https://github.com/mapbox/mapbox-gl-native/pull/11583
- https://github.com/mapbox/mapbox-gl-native/pull/11585
- https://github.com/mapbox/mapbox-gl-native/pull/11358
- https://github.com/mapbox/mapbox-gl-native/pull/11608
- https://github.com/mapbox/mapbox-gl-native/pull/11599
=> Cherry-picks for v5.5.2 to release-agua

platform/ios/Integration Tests/MBGLIntegrationTests.m, platform/ios/Integration Tests/MGLMapViewIntegrationTest.h, platform/ios/Integration Tests/MGLMapViewIntegrationTest.m, platform/ios/ios.xcodeproj/project.pbxproj
Extracted from branch 11180-nil-shape-source - to add creating new tests.
=> Refactor integrations tests

platform/android/CHANGELOG.md
Cherry picking latest changelog to master
=> cherry-pick changelog for v5.5.2

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java
Refs https://github.com/mapbox/mapbox-gl-native/pull/11653
cc @anandthakker
=> Integration for round, ceil, floor and abs expressions

platform/android/gradle/dependencies.gradle
=> Bump telemetry to 3.0.0 stable

platform/android/CHANGELOG.md
=> Changelog release v6.0.0-beta.7/5.5.2

platform/android/gradle/dependencies.gradle
refs https://github.com/mapbox/mapbox-events-android/pull/119
=> Bump telemetry dependency to 3.0.1

platform/android/CHANGELOG.md
cherry-pick of https://github.com/mapbox/mapbox-gl-native/pull/11703 to master
=> CP Changelog entry for v6.0.0

platform/android/MapboxGLAndroidSDK/gradle.properties
refs https://github.com/mapbox/mapbox-gl-native/issues/11702
=> Bump snapshot version

platform/android/CHANGELOG.md
=> Changelog entry for v6.0.0

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
This PR abstracts the MapView from NativeMapView into a ViewCallback so we can plugin other view concepts (eg. this is needed for [flutter](http://flutter.io/) integration (refs #11465)).
cc @mapbox/maps-android
=> Flutter support: integrate view callback abstraction

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
This PR allows to configure the pixel ratio used by NativeMapView.
Related to #11465.
=> promote pixelratio to public API NativeMapView

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/ZoomFunctionSymbolLayerActivity.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/11799
=> Fix expression example that changes icon images dynamically

platform/ios/jazzy.yml, platform/macos/jazzy.yml
=> [ios, macos] Update migration guides in jazzy table

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java, platform/android/src/map_renderer.cpp, platform/android/src/map_renderer.hpp
=> Release android v5.5.3

circle.yml, platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java, platform/android/src/geometry/lat_lng_bounds.cpp, platform/android/src/map_renderer.cpp, platform/android/src/map_renderer.hpp
=> Release android v6.1.0

platform/darwin/src/MGLBackgroundStyleLayer.mm, platform/darwin/src/MGLCircleStyleLayer.mm, platform/darwin/src/MGLFillExtrusionStyleLayer.mm, platform/darwin/src/MGLFillStyleLayer.mm, platform/darwin/src/MGLHeatmapStyleLayer.mm, platform/darwin/src/MGLHillshadeStyleLayer.mm, platform/darwin/src/MGLLineStyleLayer.mm, platform/darwin/src/MGLRasterStyleLayer.mm, platform/darwin/src/MGLShapeSource.mm, platform/darwin/src/MGLStyleLayer.mm.ejs, platform/darwin/src/MGLSymbolStyleLayer.mm, platform/darwin/src/MGLVectorTileSource.mm, platform/darwin/src/NSCompoundPredicate+MGLAdditions.mm, platform/darwin/src/NSExpression+MGLAdditions.mm, platform/darwin/src/NSPredicate+MGLAdditions.h, platform/darwin/src/NSPredicate+MGLAdditions.mm, platform/darwin/src/NSPredicate+MGLPrivateAdditions.h, platform/darwin/test/MGLPredicateTests.mm, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/src/MGLMapView.mm, platform/ios/src/Mapbox.h, platform/macos/CHANGELOG.md, platform/macos/macos.xcodeproj/project.pbxproj, platform/macos/src/MGLMapView.mm, platform/macos/src/Mapbox.h
Fixes https://github.com/mapbox/mapbox-gl-native/issues/11751 depends on https://github.com/mapbox/mapbox-gl-native/pull/11610 to land.
=> [ios, macos] Make NSPredicate+MGLAdditions public.

platform/android/CHANGELOG.md
This PR updates the changelog on master to reflect the state in the release branches.
refs #11837 #11835
=> Update Android changelog

platform/android/gradle/dependencies.gradle
Cherry pick of https://github.com/mapbox/mapbox-gl-native/pull/11855
=> CP: Update telemetry to 3.1.0 

platform/android/gradle/dependencies.gradle
=> Update telemetry to 3.1.0

platform/android/CHANGELOG.md
Refs https://github.com/mapbox/mapbox-gl-native/issues/11857
=> Release Android v6.1.1

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
/cc @1ec5 @jmkiley @rclee @lilykaiser
=> [ios] Prepare ios-v3.7.8 release

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java
added more tests for LatLngBounds union() & intersect
fixed whatever was broken
=> [android] added more tests for LatLngBounds union() & intersect

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
This PR cherry picks the latest changes made to release-boba to master so downstream dependencies can use 7.0.0-SNAPSHOT with the same constructs as we now have on release-boba.
=> Cherry-pick latest to master

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md
/cc @1ec5 @fabian-guerra @lilykaiser
=> [ios] Prepare ios-v4.0.1 release

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Podspec bump to iOS v4.1.0-alpha.1
=> [ios] Bump podspect to 4.1.0-alpha.1.

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties
Refs. https://github.com/mapbox/mapbox-gl-native/issues/11990.
=> Release android v6.1.3

platform/android/CHANGELOG.md
(cherry picked from commit f9775e3)
=> Update changelog for Android v6.1.3

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Updating missing values in the javadoc.
/cc @cammace
=> Update onMapChange javadoc

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/CalledFromWorkerThreadException.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/BackgroundLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillExtrusionLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HeatmapLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HillshadeLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/RasterLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/Light.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/light.java.ejs, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CustomGeometrySource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/ImageSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterDemSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/Source.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/VectorSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ThreadUtils.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/annotations/IconTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/action/MapboxMapAction.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/BaseActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/annotations/IconTest.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/9896
=> UI thread checking

platform/android/src/file_source.cpp
Refs https://github.com/mapbox/mapbox-gl-native/issues/4972#issuecomment-392733888
=> Check access token in filesource initializer

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
https://github.com/mapbox/mapbox-gl-native/compare/ios-v4.0.1...705fdfc
=> [ios] Prepare ios-v4.0.2 release

platform/android/gradle/dependencies.gradle
https://github.com/mapbox/mapbox-java/issues/828
=> [android] changed version of mapbox-java to 3.2.0

Makefile, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/render/RenderTestActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/render/RenderTestStyleDefinition.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/12046
=> Ignore render tests from ignores.json

platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml, platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
Closes https://github.com/mapbox/mapbox-gl-native/issues/11924.
=> Cleanup public attributes

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/render/RenderTestDefinition.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/render/RenderTestStyleDefinition.java, platform/android/scripts/run-render-test.py
Refs #12062 
- integrate pixelratio in test definition
- show amount of executed and failed tests
=> Render test tweaks

platform/qt/src/qt_geojson.cpp
=> [qt] Fix asMapboxGLFeatureIdentifier iterator traversal

scripts/launch-c-xcode.in, scripts/launch-cxx-xcode.in
Backport https://github.com/mapbox/mapbox-gl-native/pull/12094 to Chai
=> Backport: Fix build with Xcode 10

circle.yml, platform/ios/app/MBXViewController.m, platform/ios/app/Main.storyboard
Cherry-picks #12102 and #12052 into `release-chai` for `ios-v4.1.0-beta.1`.
=> [ios] Chai cherry-pick: Xcode 9.4, iosapp layout fixes

cmake/test-files.cmake, src/mbgl/geometry/line_atlas.cpp, test/geometry/line_atlas.test.cpp
Address some parts of https://github.com/mapbox/mapbox-gl-native/issues/12113
=> Fix undefined behavior in LineAtlas::addDash

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
CP https://github.com/mapbox/mapbox-gl-native/pull/12116.
=> Ceil map dimensions

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java
Backports #12128 to release-chai
----
Closes #12101, this PR needs a CP to release-chai.
=> release-chai backport: Fix match stop conversion

src/mbgl/renderer/backend_scope.cpp
Fix a static variable initialization issue when dynamic loading Mapbox GL Native.
=> [core] Use a getter for the BackendScope static variable

platform/android/CHANGELOG.md
(cherry picked from commit ffb30bb)
=> CP changelog for 6.2.0-beta.2 to master

platform/ios/app/MBXViewController.m
Updated 2 predicates in `iosapp` to cast the values.
Fixes #12169
=> [ios] Updated predicates in iosapp

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
CP #12172 to the `release-chai`.
=> backport to chai: Dispatch camera start callback only when actually moving

platform/android/.gitignore, platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties, platform/android/scripts/release.py
CP #12126 to the `release-chai`.
=> chai backport: Remove support for Fabric 

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md, platform/macos/Mapbox-macOS-SDK-symbols.podspec, platform/macos/Mapbox-macOS-SDK.podspec
=> Cherry picked 2886aca (change logs and podspecs)

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md
=> [ios] Update changelogs and bump podspec.

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Image.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java, platform/android/src/map/image.cpp, platform/android/src/native_map_view.cpp, platform/android/src/native_map_view.hpp
closes #9847 (see images in #9847 for results).
=> add sdf support to addImage

include/mbgl/util/unique_any.hpp, test/util/unique_any.test.cpp
* Eliminate unnecessary temporary in VTableStack::move
* Make move consistent: it destructs the src, not the dest, which is always empty
* delete doesn't need a null guard
* Conversions to void* don't need a cast
Refs #11631.
=> [core] Fix stylistic issues in unique_any

cmake/node.cmake, package.json, platform/node/index.js
=> Restore compatibility with node-pre-gyp binary publishing

platform/android/scripts/metrics.sh, scripts/log_binary_size.sh
=> Fix binary size metrics for Android

platform/qt/include/qmapboxgl.hpp, platform/qt/src/qmapboxgl.cpp
Implement `QMapboxGL::getFilter()`
cc @Kilatsat @cmtoomey @brunoabinader
=> Add QtMapboxGL::getFilter() method

platform/linux/config.cmake, platform/macos/config.cmake
Fixes https://github.com/mapbox/mapbox-gl-native/issues/12223.
=> [build] GLFW version 2018-06-27-0be4f3f

platform/android/MapboxGLAndroidSDK/build.gradle, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java
Backports #12210 to release-chai
----
Closes #12198
=> release-chai backport: Range alpha between 0 and 1 for android int color conversion

platform/ios/ios.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, platform/macos/macos.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
https://stackoverflow.com/questions/49564513/new-file-created-in-xcode-9-3-wsname-xcworkspace-xcshareddata-ideworkspaceche
=> [macos, ios] Commit IDEWorkspaceChecks.plist files

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md
=> [ios] Updates the changelogs and bumps cocoapods

src/mbgl/style/expression/interpolate.cpp
* Merge type checking into match arms
* No need to use interpolator->match(...)
=> [core] Simplify parseInterpolate

cmake/core-files.cmake, include/mbgl/style/expression/find_zoom_curve.hpp, include/mbgl/style/expression/interpolate.hpp, include/mbgl/style/expression/interpolator.hpp, include/mbgl/style/function/camera_function.hpp, include/mbgl/style/function/composite_function.hpp, include/mbgl/style/function/convert.hpp, src/mbgl/style/expression/find_zoom_curve.cpp, src/mbgl/style/expression/interpolate.cpp, src/mbgl/style/expression/parsing_context.cpp
=> Interpolate refactor

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Podspec bump to 4.1.1 and changelog update.
=> [ios] v4.1.1 release

platform/android/CHANGELOG.md
This PR updates the changelog with latest releases.
=> Update changelog with latest releases

platform/glfw/glfw_view.cpp
Leftover from #12258.
Fixes #12276.
/cc @jfirebaugh @zugaldia
=> [glfw] Update route demo to use expressions DSL

circle.yml
=> [android] Consolidate release builds

platform/android/CHANGELOG.md
PR updates the changelog for the v6.3.0-alpha.2 release
=> update changelog for release v6.3.0-alpha.2

platform/macos/app/Base.lproj/MainMenu.xib, platform/macos/app/DroppedPinAnnotation.h, platform/macos/app/DroppedPinAnnotation.m, platform/macos/app/MapDocument.m
Cherry-picked #12289 (adding a File ‣ Import command to macosapp) from master into release-drink for macOS map SDK v0.9.0.
=> Import GeoJSON (release-drink)

platform/android/CHANGELOG.md
This PR updates the Android changelog for the v6.3.0-beta.1 release.
=> Update changelog v6.3.0 beta.1

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/VisibleRegionTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/12379.
=> Option to request the visible region restricted by the content padding

platform/android/CHANGELOG.md
This PR updates the changelog for the v6.3.0 release (needs a CP to release-drink).
=> Update changelog for v6.3.0 

platform/macos/app/Base.lproj/MainMenu.xib, platform/macos/app/DroppedPinAnnotation.h, platform/macos/app/DroppedPinAnnotation.m, platform/macos/app/MapDocument.m
Cherry-picked #12289 (adding a File ‣ Import command to macosapp) from master into release-drink for macOS map SDK v0.9.0. This is a reprise of #12359, which I erroneously targeted at master instead of release-drink.
=> Import GeoJSON (release-drink redux)

src/mbgl/style/conversion/tileset.cpp
=> fixed typo in error message

circle.yml
Fixes https://github.com/mapbox/mapbox-gl-native/pull/12434#issuecomment-406982990
- debug builds: don't run tests on firebase
- release: don't attempt to reference maven credentials
=> Fix circle-ci configuration for building forked PRs

platform/qt/README.md
=> [Qt] Fix link to Qt public API headers in README.md

CMakeLists.txt, appveyor.yml, src/mbgl/programs/segment.hpp
Small modifications to support compilation with MSVC 2017 and clang-cl on Windows
=> Support Windows compilation with msvc 2017 and clang 6

platform/android/gradle/dependencies.gradle
Refs https://github.com/mapbox/mapbox-java/issues/861
=> Update Java Services to v3.4.0

Makefile, cmake/node.cmake, package.json, platform/node/test/expression.test.js, platform/node/test/query.test.js, platform/node/test/render.test.js, platform/node/test/suite_implementation.js
Companion to https://github.com/mapbox/mapbox-gl-js/pull/6880.
=> Upgrade test/integration to ES6 modules

platform/android/CHANGELOG.md, platform/android/gradle/dependencies.gradle
Backport #12589 and #12591 to espresso.
=> Backport #12589 and #12591 to espresso

platform/android/gradle/dependencies.gradle
addresses https://github.com/mapbox/mapbox-java/issues/866
=> changed version of mapbox services to 3.4.1

include/mbgl/math/log2.hpp, mapbox-gl-native.pro, src/mbgl/renderer/buckets/symbol_bucket.cpp, src/mbgl/util/tile_cover.cpp
Cherry picked from https://github.com/mapbox/mapbox-gl-native/commit/fc0745a699a0ef60c080e9c2ff5eaecde9cb5306
=> Fix Android build

platform/qt/src/http_file_source.cpp
Cherry picked from https://github.com/mapbox/mapbox-gl-native/commit/8ae5ea953e413e12813ee94d34cd0cd14bce3d8a
=> Cherry pick: Use FollowRedirectsAttribute in network requests

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
=> MapboxMap typo fix for removeSource() docs

platform/default/sqlite3.cpp
=> [windows] Fix build on Windows

platform/default/asset_file_source.cpp, platform/default/local_file_source.cpp, src/mbgl/style/expression/is_constant.cpp, test/style/filter.test.cpp
Recut of https://github.com/mapbox/mapbox-gl-native/pull/12621 so that we can run all of the tests with credentials.
=> Fix out of range exception for string compare

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> Update for 4.0.5 

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/BackgroundLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CustomLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillExtrusionLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HeatmapLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HillshadeLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/RasterLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/Light.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/light.java.ejs, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/ImageSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterDemSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/Source.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/VectorSource.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/12491.
=> Hide peer constructors

platform/macos/jazzy.yml
Tail work from https://github.com/mapbox/mapbox-gl-native/pull/12540#discussion_r210140346
=> [macos] Rename Guides to Appendices

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Added #12257 to `release-boba`.
cc @lloydsheng
=> [ios] Cherry-pick 12257 into release-boba

platform/android/CHANGELOG.md
CP https://github.com/mapbox/mapbox-gl-native/pull/12643 to `master`.
=> Changelog for v6.4.0 (CP #12643)

platform/android/CHANGELOG.md
Update changelog with fixed security vulnerability
=> Update changelog with fixed security vulnerability

cmake/mbgl.cmake
=> [build] More diagnostics for npm install failures

include/mbgl/util/font_stack.hpp, package.json, scripts/clang-tools.sh, src/mbgl/renderer/renderer_impl.cpp, src/mbgl/style/conversion/tileset.cpp, src/mbgl/style/parser.cpp, src/mbgl/text/glyph_manager.cpp, src/mbgl/text/glyph_manager.hpp, src/mbgl/util/font_stack.cpp, test/fixtures/style_parser/text-font.info.json, test/style/conversion/tileset.test.cpp
updated with the latest prereleases
=> Node v4.0.0 pre.14

platform/android/CHANGELOG.md
Update changelog for release v6.5.0-alpha.1
=> Update changelog for release v6.5.0-alpha.1

platform/ios/CHANGELOG.md
Additional changelog updates not caught in https://github.com/mapbox/mapbox-gl-native/pull/12718.
=> [ios] Update changelog for v4.4.0-alpha.1 release

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/LatLngBoundsActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DoubleMapActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterReuseActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/fragment_double_map.xml
When doing manual QA, a couple of examples behaved different than before. 
This PR fixes the examples to behave as expected.
=> Update broken test app examples

platform/android/CHANGELOG.md
This PR updates the changelog for a v6.5.0-alpha.2 release
=> Update changelog for v6.5.0-alpha.2

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillExtrusionLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HeatmapLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HillshadeLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/RasterLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillExtrusionLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HeatmapLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HillshadeLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RasterLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs, platform/android/src/style/layers/layer.cpp, platform/android/src/style/layers/layer.hpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/12691
=> Add get source id to supported layer types

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/LibraryLoader.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapStrictMode.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapStrictModeException.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/IconFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpIdentifier.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/LocalRequestTask.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyValue.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java
This PR adds a `MapStrictMode` that throws an exception in circumstances that would fail silently otherwise and makes it easier to catch those issue while testing manually, or using instrumentation tests.
=> MapStrictMode testing tool

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyValue.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java
Backports #12769 to release-frappe
----
Closes https://github.com/mapbox/mapbox-gl-native/issues/12746
=> release-frappe backport: isExpression and getValue integration for new property values

platform/android/CHANGELOG.md
=> Update changelog for v6.5.0

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md, platform/macos/Mapbox-macOS-SDK-symbols.podspec, platform/macos/Mapbox-macOS-SDK.podspec
Updates changelogs and Podspecs for today's 4.4.0 release.
=> Update podspecs and changelogs for v4.4.0 final

package.json, platform/node/CHANGELOG.md
=> Cherry-pick node release updates from release branch

platform/android/MapboxGLAndroidSDK/gradle.properties
This PR bumps snapshot version to v6.6.0 on master.
=> Bump snapshot version to v6.6.0

cmake/glfw.cmake, platform/glfw/main.cpp
This can be a useful debugging tool.
=> [core] add --cache option to GLFW binary to specify the cache database

platform/darwin/test/MGLOfflineStorageTests.mm
Fixes a crash related to https://github.com/mapbox/mapbox-gl-native/pull/12911#issuecomment-422600110
=> [ios, macos] Fix offline database test crash.

scripts/generate-shaders.js, src/mbgl/shaders/background.cpp, src/mbgl/shaders/background_pattern.cpp, src/mbgl/shaders/circle.cpp, src/mbgl/shaders/clipping_mask.cpp, src/mbgl/shaders/collision_box.cpp, src/mbgl/shaders/collision_circle.cpp, src/mbgl/shaders/debug.cpp, src/mbgl/shaders/extrusion_texture.cpp, src/mbgl/shaders/fill.cpp, src/mbgl/shaders/fill_extrusion.cpp, src/mbgl/shaders/fill_extrusion_pattern.cpp, src/mbgl/shaders/fill_outline.cpp, src/mbgl/shaders/fill_outline_pattern.cpp, src/mbgl/shaders/fill_pattern.cpp, src/mbgl/shaders/heatmap.cpp, src/mbgl/shaders/heatmap_texture.cpp, src/mbgl/shaders/hillshade.cpp, src/mbgl/shaders/hillshade_prepare.cpp, src/mbgl/shaders/line.cpp, src/mbgl/shaders/line_gradient.cpp, src/mbgl/shaders/line_pattern.cpp, src/mbgl/shaders/line_sdf.cpp, src/mbgl/shaders/raster.cpp, src/mbgl/shaders/symbol_icon.cpp, src/mbgl/shaders/symbol_sdf.cpp
This is meant to
(1) Make it easier for new developers to find the source
(2) Make it easier to look at shader diffs when the GL JS pin changes
/cc @mapbox/gl-core
=> [docs] Include uncompressed shader source in .cpp comments

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md
=> [ios] Update changelogs and bump podspec to 4.5.0-alpha.1

platform/android/MapboxGLAndroidSDK/proguard-rules.pro, platform/android/MapboxGLAndroidSDKTestApp/proguard-rules.pro
This PR does a complete revision of our proguard configuration.
=> Proguard config revision

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraAnimationTypeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/ManualLocationUpdatesActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/BottomSheetActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CircleLayerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CustomSpriteActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java
This PR is a follow up to QA testing for alpha.1 release of v6.6.0:
- addresses a couple of memory leaks
- updates/fixes a couple of test app examples
- CustomSpriteActivity correct layer configuration
- CircleLayerActivity replaced removed content with clustering approach
- SymbolLayerActivity added selected state example
=> TestApp QA follow up

circle.yml, package.json, scripts/clang-tools.sh, scripts/environment.js
Backports #12958 to release-chai
----
=> release-chai backport: Compare clang-tidy with merge base instead of master

circle.yml, scripts/clang-tools.sh, scripts/environment.js
Backports #12958 to release-drink
----
=> release-drink backport: Compare clang-tidy with merge base instead of master

platform/darwin/test/MGLOfflineStorageTests.mm, platform/darwin/test/MGLStyleTests.mm, platform/ios/Integration Tests/MBGLIntegrationTests.m, platform/ios/Integration Tests/MGLStyleLayerIntegrationTests.m
=> [ios] Bump more test timeouts for Xcode 10 sluggishness

platform/darwin/src/MGLGeometry.h, platform/darwin/src/MGLGeometry_Private.h, platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md
Fixes #5583 
/cc @1ec5 @friedbunny @fabian-guerra
=> Moved MGLAltitudeForZoomLevel and MGLZoomLevelForAltitude to public API

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentOptions.java, platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml, platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
Closes https://github.com/mapbox/mapbox-gl-native/issues/12992.
=> Add configuration to change the animation duration multiplier when tracking location

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentConstants.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt
backports #13013 to `release-gazpacho`
=> backport #13013 to release-gazpacho

Makefile, circle.yml, platform/ios/CHANGELOG.md, platform/ios/DEVELOPING.md, platform/ios/scripts/check-events-symbols.sh, platform/macos/DEVELOPING.md
Cherry-pick #13008 to `release-gazpacho` for `ios-v4.5.0-beta.1`.
/cc @fabian-guerra @julianrex @rclee
=> [ios, build] Check symbol namespacing for mapbox-events-ios (release-gazpacho)

platform/android/CHANGELOG.md, platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md, platform/node/CHANGELOG.md, src/mbgl/algorithm/generate_clip_ids_impl.hpp, src/mbgl/renderer/renderer_impl.cpp, src/mbgl/renderer/tile_pyramid.cpp, test/algorithm/generate_clip_ids.test.cpp
Cherry-picks #12982 into `release-gazpacho` for `ios-v4.5.0-beta.1`.
=> cherry pick #12982 to release-gazpacho

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md
Fixes minor changelog issues and bumps podspec to 4.5.0-beta.1
=> [ios] release v4.5.0 beta.1 podspec bump and changelog updates.

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md
Cherry picks #13027 into release-gazpacho.
=> [ios] release v4.5.0 beta.1 podspec bump and changelog updates. (#13027)

platform/darwin/test/MGLOfflineStorageTests.mm, platform/ios/ios.xcodeproj/project.pbxproj, platform/macos/macos.xcodeproj/project.pbxproj
Cherry picks #13024 into `release-gazpacho`
=> [ios, macos] Enable offline merge test.

platform/ios/app/MBXViewController.m, platform/macos/app/MapDocument.m
Updated the Mapbox World Tour locations based on coordinates in OpenStreetMap.
Split out from #9319.
=> Mapbox World Tour 2018

platform/linux/config.cmake
Rebuild of https://github.com/mapbox/mapbox-gl-native/pull/12898
=> [linux] add map_snapshotter.*pp to linux core build

platform/android/README.md
Addresses comment from https://github.com/mapbox/mapbox-gl-native/issues/13054#issuecomment-428149600.
=> Fix readme to point to correct DEVELOPING.md in root

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Bumps podspec to 4.5.0, adds date to the changelog.
=> [ios] Bump podspecs to 4.5.0 and update changelog.

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java, platform/android/src/style/sources/geojson_source.cpp, platform/android/src/style/sources/geojson_source.hpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/12441, Refs #12726,
This PR contains the android integration of that #12726.
=> Supercluster.hpp 0.3.0 Android

platform/android/MapboxGLAndroidSDK/gradle.properties
Follow up from release 6.6.0 final, bumping snapshot version to 6.7.0
=> Bump snapshot version to 6.7.0

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java, platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml
This PR cherry-picks for a 6.6.1 release:
- https://github.com/mapbox/mapbox-gl-native/commit/1e71075b3f0084d581a0b3c2d45e5fabb9ad2ec1
- https://github.com/mapbox/mapbox-gl-native/commit/62af756ab8250e00a63776c2d32bf3123909eddb
- https://github.com/mapbox/mapbox-gl-native/pull/13121/commits/54659bbb8300fff090ad38264980e536d6cecfd7
=> Cherry pick for patch release v6.6.1

platform/android/CHANGELOG.md
PR updates changelog for v6.7.0-alpha.2 and v6.6.2
=> Changelog for v6.7.0-alpha.2 and v6.6.2

platform/android/gradle/dependencies.gradle
Fixes https://github.com/mapbox/mapbox-gl-native/issues/12904.
=> Bumped telemetry version to 3.5.1

platform/android/MapboxGLAndroidSDK/gradle.properties
Branch cut for release Horchata has happened, bumping snapshot on master to reflect this state.
=> Bump snapshot version to v7.0.0

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Adds changelog entries for #13006, #13105, and #13231.
/cc @ryanhamley @mourner @julianrex
=> [ios] Prepare for 4.6.0-beta.1

.gitmodules, cmake/benchmark.cmake, cmake/core.cmake, cmake/filesource.cmake, cmake/mason-dependencies.cmake, cmake/offline.cmake, cmake/render.cmake, cmake/test.cmake, cmake/vendor.cmake, include/mbgl/util/expected.hpp, platform/default/png_writer.cpp, platform/default/utf.cpp, src/mbgl/annotation/symbol_annotation_impl.hpp, src/mbgl/text/language_tag.cpp, src/mbgl/util/http_header.cpp, vendor/boost.cmake
Custom extract made using bcp based on 1.65.1
=> [build] Add vendored libboost

platform/android/CHANGELOG.md, platform/android/gradle/dependencies.gradle
Refs https://github.com/mapbox/mapbox-gl-native/issues/13257
=> Release Android v6.6.5

platform/android/gradle/dependencies.gradle
Refs https://github.com/mapbox/mapbox-gl-native/issues/13257
=> Update telemetry to v3.5.2

platform/darwin/src/MGLShapeOfflineRegion.mm, platform/darwin/src/MGLTilePyramidOfflineRegion.mm
Cherry picking https://github.com/mapbox/mapbox-gl-native/pull/13266 for v4.6.0
=> [ios] Changed event attributes to be JSON serialization friendly (CP #13266)

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/BaseActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/OnMapReadyIdlingResource.java
Backports #13265 to `release-horchata`
=> Backport #13265 to horchata

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/13277.
=> Null-check nativeMapView in case it's been destroyed

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapChangeReceiver.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapChangeReceiverTest.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/13285.
=> Log Java exception and fail silently instead of throwing a native exception in the map state callbacks

platform/android/gradle/dependencies.gradle
Closes https://github.com/mapbox/mapbox-gl-native/issues/13280
=> Update telemetry dependency for release-horchata

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Cherry pick of #13286 to `release-horchata` branch.
=> handle null getMapAsync invocations, deliver onMapReady once

platform/darwin/src/MGLStyle.mm
A leftover from https://github.com/mapbox/mapbox-gl-native/pull/13221
=> [mac] Fix wrong allocation at layerFromMBGLLayer

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Prepare for ios-v4.6.0

platform/android/CHANGELOG.md
This PR updates the changelog for v6.7.0 and prior 6.6.x releases.
cc @zugaldia
=> Update changelog for v6.7.0 and prior 6.6.x releases

platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md, platform/macos/Mapbox-macOS-SDK-symbols.podspec, platform/macos/Mapbox-macOS-SDK.podspec, scripts/changelog_staging/expression-string-coercion.json, scripts/changelog_staging/format-expression.json, scripts/changelog_staging/invalid-latlngbounds.json, scripts/changelog_staging/per-source-collision.json, scripts/changelog_staging/put-offline-resource.json, scripts/changelog_staging/queryrenderedfeatures-with-icon-rotate.json
Cherry-picked #13317 into the release-horchata branch.
=> macOS map SDK v0.12.0 (release-horchata)

platform/android/CHANGELOG.md, platform/android/gradle/dependencies.gradle
Cherry pick of #13330 to release-gazpacho for the v6.6.6 release
=> Update telemetry to 3.5.4, update changelog

platform/android/CHANGELOG.md, platform/android/gradle/dependencies.gradle
Refs https://github.com/mapbox/mapbox-gl-native/pull/13333/.
=> Bump telemetry to 3.5.4, update changelog for 6.6.7

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationLayerController.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/Light.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/light.java.ejs, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/BuildingFillExtrusionActivity.java
=>  Consolidate color conversion into color utils 

platform/android/gradle/dependencies.gradle
https://github.com/mapbox/mapbox-java/issues/919
=> bump mapboxServices to 4.1.0

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapStrictMode.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapChangeReceiver.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapChangeReceiverTest.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/13346.
=> Catch and re-throw throwables thrown inside map state callbacks

platform/darwin/src/MGLAttributionInfo.mm
Cherry-picks #13300 to the iOS 8 branch.
cc @lloydsheng
=> [ios] Address bad access exception in `MGLAttributionInfo` (#13300)

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Bumps podspecs and changelog for ios-v4.7.0-alpha.1
=> [ios] Release preparations for 4.7.0-alpha.1

appveyor.yml, platform/android/CHANGELOG.md, platform/android/gradle/dependencies.gradle
Backport #13331 and #13391 to `release-horchata`.
Also backports https://github.com/mapbox/mapbox-gl-native/pull/13355 and synchronizes `appveyor.yml` with `master`.
=> Backport #13331 and #13391 to horchata

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/attribution/Attribution.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/attribution/AttributionParseTest.java
Updates map feedback URL from
```
https://www.mapbox.com/map-feedback
```
to
```
https://www.mapbox.com/feedback
```
=> Update map feedback URL

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/types/Formatted.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/types/FormattedSection.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/BackgroundLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillExtrusionLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HeatmapLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HillshadeLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RasterLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs, platform/android/scripts/generate-style-code.js, platform/android/src/style/formatted.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/13173.
@ChrisLoer this PR also resolves the concerns from https://github.com/mapbox/mapbox-gl-native/pull/12985#discussion_r224602102, in preparation for https://github.com/mapbox/mapbox-gl-native/issues/13172 work.
=> Removing plain text getter for "text-field"

platform/ios/CHANGELOG.md
Reordered and added sections given that the change log has grown.
=> Reordered the 4.7.0 change log

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> Updated podspecs for 4.7.0-alpha.3

platform/android/MapboxGLAndroidSDK/src/main/res/values-fr/strings.xml, platform/darwin/resources/fr.lproj/Foundation.strings, platform/ios/resources/fr.lproj/Localizable.strings
"Rend meilleure les cartes Mapbox" is grammatically incorrect. "Make better" is better translated by "Améliorer".
=> [ios] Update French translation - telemetry

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Bump podspec to 4.7.0-beta.1.

circle.yml, platform/ios/scripts/deploy-packages-cn.sh, platform/ios/scripts/deploy-packages.sh, platform/ios/scripts/publish-cn.sh
I've updated this branch to use Github tags in order to trigger the publish process for future releases.
=> [ios] Release iOS 8-compatible branch via CircleCI

CHANGELOG.md
Updates name of Android line in the root change log file.
=> Android changelog name tweak

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterActivity.java
Backports #13508 to `release-horchata`.
/cc @langsmith
=> Backport #13508 to horchata

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/GeometryConstants.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngSpan.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/geometry/LatLngBoundsTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/VisibleRegionTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/LatLngBoundsForCameraActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_bounds.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/actions.xml, platform/android/src/geometry/lat_lng_bounds.cpp
Backports #13419 to `release-iowaska`
=> Backport #13419 to iowaska

platform/android/CHANGELOG.md
Backports https://github.com/mapbox/mapbox-gl-native/pull/13558 to `release-iowaska`
=> Backport #13558 to iowaska

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
- Updates podspecs
- No changelog changes at this time.
=> Release preparation for v4.7.0-beta.2

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Cherry-picks https://github.com/mapbox/mapbox-gl-native/pull/13562
=> Update podspecs for v4.7.0-beta.2 (#13562)

platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md
Added change log for https://github.com/mapbox/mapbox-gl-native/pull/13535
=> [core] Updated iOS/macOS change logs.

platform/android/gradle/dependencies.gradle
addresses https://github.com/mapbox/mapbox-java/issues/943
=> mas upgrade to 4.3.0

appveyor.yml, include/mbgl/map/map_observer.hpp, package.json, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapChangeReceiver.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapChangeReceiverTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/MapChangeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/RecyclerViewActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_recyclerview.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/item_map.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml, platform/android/build.gradle, platform/android/gradle/wrapper/gradle-wrapper.properties, platform/android/src/native_map_view.cpp, platform/android/src/native_map_view.hpp, platform/ios/src/MGLMapViewDelegate.h, platform/ios/test/MGLMapViewDelegateIntegrationTests.swift, platform/macos/src/MGLMapView.mm, platform/macos/src/MGLMapViewDelegate.h, platform/macos/test/MGLMapViewDelegateIntegrationTests.swift, scripts/changelog_staging/idle-event.json, src/mbgl/map/map.cpp
This PR cherry-picks:
- https://github.com/mapbox/mapbox-gl-native/commit/bb5b558f21c56872127540c7c5b0324d6286e505
- https://github.com/mapbox/mapbox-gl-native/pull/13513
- https://github.com/mapbox/mapbox-gl-native/pull/13397
- https://github.com/mapbox/mapbox-gl-native/pull/13393
=> Cherry pick changes for 6.8.0

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/CompassEngine.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/CompassListener.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentCompassEngine.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentConstants.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationLayerController.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/MapboxAnimatorSetProvider.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java, platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml, platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/CompassEngineTest.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinatorTest.kt, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationCameraControllerTest.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/styles.xml
Backports to `release-horchata`:
https://github.com/mapbox/mapbox-gl-native/pull/13569
https://github.com/mapbox/mapbox-gl-native/pull/13573/
https://github.com/mapbox/mapbox-gl-native/pull/13545/
https://github.com/mapbox/mapbox-gl-native/pull/13574
=> Backport location fixes to horchata

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/Style.java, platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_multi_map.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/fragment_dialog_map.xml
Backports https://github.com/mapbox/mapbox-gl-native/pull/13615 to `release-horchata`
=> Backport #13615 to horchata

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentCompassEngine.java
Cleanup for the mapbox logger abstraction.
=> Remove timber in favor of mapbox logger

platform/android/gradle/dependencies.gradle
Cherry picking from master https://github.com/mapbox/mapbox-gl-native/pull/13610
=> [android] mas bump to 4.3.0

platform/android/CHANGELOG.md
cherry-pick https://github.com/mapbox/mapbox-gl-native/pull/13634
=> 7.0.0-beta.2 changelog

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationCameraControllerTest.java
Fixes https://github.com/mapbox/mapbox-gl-native/issues/13590.
=> Cancel camera transitions only when set CameraMode is not None

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationCameraControllerTest.java
Backports #13662 and #13670 to `release-iowaska`.
=> Backport #13662 and #13670 to iowaska

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
Refs https://github.com/mapbox/mapbox-gl-native/pull/13592.
=> Fix location interval workaround initialization

platform/android/CHANGELOG.md
android v7.0.0 changelog update
Cherry picked https://github.com/mapbox/mapbox-gl-native/pull/13684
=> [android] changelog for v7.0.0

platform/android/CHANGELOG.md
updated changelog with v7.0.0  android release
=> [android] v7.0.0 changelog

platform/darwin/src/MGLStyle.h, platform/darwin/src/MGLStyle.mm, platform/darwin/test/MGLStyleTests.mm, platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md
=> [ios, macos] Renames MGLStyle.enablePlacementTransitions

platform/android/CHANGELOG.md
PR to update the changelog for the v7.1.0-alpha.1 release of the Android library.
=> Update changelog for android v7.1.0-alpha.1

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Changelog and podspec bump to v4.8.0
=> [ios] Podspec bump to v4.8.0 alpha.1

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineGeometryRegionDefinition.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionDefinition.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineTilePyramidRegionDefinition.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/13687.
=> Lift Parcelable inheritance to the OfflineRegionDefinition

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java
This PR adds a manual test for validating #13407. 
Validated that https://github.com/mapbox/mapbox-gl-native/pull/13667 is working correctly.
cc @pozdnyakov
=> Regression test for symbols flashing

platform/android/core-files.json, platform/ios/core-files.json
Adding files so they appear in the generated projects.
=> Add missing files

platform/android/CHANGELOG.md
This PR updates changelog for v7.0.1
=> Update changelog for v7.0.1

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_debug_mode.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
PR that brings changes required for release v7.0.1
=> Release v7.0.1

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/13208
=> Avoid leaking attribution dialog when context is being stopped

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java
Hi @langsmith - this URL's redirect actually will work, but figured I'd update it anyway while I was working in this repo!
=> [android] - Update link to API docs

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java
=> [android] fix debug activity not show fps

platform/android/CHANGELOG.md
This PR updates the changelog for the upcoming v7.1.0-alpha.2 release.
=> Update changelog for v7.1.0-alpha.2

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_debug_mode.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_debug.xml
Closes #13671, additionally updates the debug mode activity with an options menu to manually test this fix + moved the 30 fps and 60 fps buttons to this configuration.
=> Allow resetting fps listener, update debug mode menu options 

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Bumps podspecs to 4.8.0-alpha.2
=> [ios] Podspec bump to 4.8.0-alpha.2.

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationLayerController.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationModesActivity.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/13591.
=> Re-apply location component's "layer-below" when changed

platform/android/CHANGELOG.md
This PR updates the changelog for the v7.1.0-alpha.3 release.
=> Update changelog for v7.1.0-alpha.3

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/NativeMapViewTest.kt, platform/android/src/native_map_view.cpp, platform/android/src/style/transition_options.cpp, platform/android/src/style/transition_options.hpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/13767.
=> Rename required TransitionOptions field

platform/darwin/src/MGLLoggingConfiguration_Private.h, platform/ios/src/MGLMapView.mm, platform/macos/src/MGLMapView.mm
Adds missing logs to some methods.
=> [ios, macos] MGLMapView logging improvements.

platform/android/CHANGELOG.md
This PR updates the changelog to match the v7.1.0-beta.1 release. 
Requires a CP to release-java branch.
=> Update changelog for v7.1.0-beta.1

platform/android/CHANGELOG.md
CP of https://github.com/mapbox/mapbox-gl-native/pull/13778
=> CP update changelog for v7.1.0-beta.1

platform/darwin/resources/cs.lproj/Foundation.strings, platform/darwin/resources/cs.lproj/Foundation.stringsdict, platform/ios/CHANGELOG.md, platform/ios/app/Settings.bundle/cs.lproj/Root.strings, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/resources/cs.lproj/Localizable.strings, platform/ios/resources/cs.lproj/Localizable.stringsdict, platform/ios/resources/hu.lproj/Localizable.stringsdict, platform/macos/CHANGELOG.md, platform/macos/macos.xcodeproj/project.pbxproj, platform/macos/sdk/cs.lproj/Localizable.strings
Cherry picks #13782 into `release-java`
=> [ios, macos] Add Czech and Hungarian translations. (#13782)

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md
Bumps podspecs and updates changelogs.
=> [ios] Podspec bump to v4.8.0-beta.1

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/macos/CHANGELOG.md
Cherry picks #13785 into `release-java`
=> [ios] Podspec bump to v4.8.0-beta.1 (#13785)

platform/darwin/src/MGLComputedShapeSource.mm
Fix typo in error message in MGLComputedShapeSource.mm
=> [ios] Fix typo in MGLComputedShapeSource error message

platform/ios/DEVELOPING.md
Updates the code snippet instructions of `/platform/ios/DEVELOPING.md` to reflect the current process.
=> [ios][docs] update code snippet instructions

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/BitmapUtils.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/StyleBuilderTest.kt, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/StyleTest.kt
=> Add image support with drawable overload

circle.yml
Prioritize running benchmarks when building master.
=> Prioritize running benchmarks when building master 

platform/ios/scripts/document.sh
Temporal Fix for jazzy builds.
=> [ios] Fix jazzy building.

platform/android/gradle/android-nitpick.gradle
Refs https://github.com/mapbox/mapbox-gl-native/pull/13806.
Fixes wrong syntax for calling one task from another.
=> Run vendor submodule check

platform/android/CHANGELOG.md
Cherry-pick of https://github.com/mapbox/mapbox-gl-native/pull/13832
=> Cherry pick update changelog for v7.1.0

platform/darwin/scripts/style-spec-overrides-v8.json, platform/darwin/src/MGLLight.h, platform/darwin/src/MGLOfflinePack.h, platform/darwin/src/MGLShapeOfflineRegion.h, platform/darwin/src/MGLShapeSource.h, platform/darwin/src/MGLTilePyramidOfflineRegion.h, platform/darwin/test/MGLDocumentationExampleTests.swift, platform/ios/src/MGLMapView.h
Resolves #13112 
Adds codes snippets to the API docs for 5 classes that were deemed to need some additional clarity.
=> [ios][documentation] Add new code snippets

platform/darwin/scripts/style-spec-overrides-v8.json, platform/darwin/src/MGLLight.h, platform/darwin/src/MGLOfflinePack.h, platform/darwin/src/MGLShapeOfflineRegion.h, platform/darwin/src/MGLShapeSource.h, platform/darwin/src/MGLTilePyramidOfflineRegion.h, platform/darwin/test/MGLDocumentationExampleTests.swift, platform/ios/src/MGLMapView.h
Cherry-pick of #13579 for Release Java
=> [ios][documenation] add additional code snippets to API docs

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Bump podspec to 4.8.0.

platform/android/MapboxGLAndroidSDK/build.gradle, platform/android/gradle/android-nitpick.gradle, platform/android/gradle/dependencies.gradle
Backports #13847 to `release-java`.
=> Backport #13847 to release-java

platform/qt/app/mapwindow.cpp, platform/qt/src/qt_conversion.hpp
This PR solves #13831.
Since this is my first PR on this repository, I'm not sure that I followed the convention properly.
Please let me know if you find anything wrong.
By the way, I found that mapbox performs the type check for `QVariant` by comapring type name.
I recommend comparing `QVariant::userType()` and `qMetaTypeId<T>()` instead.
I didn't changed the type check for QMapbox::Feature here though, since it's out of scope for this PR.
=> Support feature collection for Qt platform

platform/ios/CHANGELOG.md, platform/ios/src/MGLMapView.mm
=> [ios] Fix the user location not getting displayed when setting tracking mode to followWithCourse and followWithHeading

platform/darwin/src/MGLOfflineStorage.mm, platform/darwin/test/MGLOfflineStorageTests.mm
Fixes a cache issue where multiple workflows are executed in a single circle ci machine.
=> [ios, macos] Update unit test bundle identifier.

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Release ios-v4.9.0-alpha.1

platform/android/CHANGELOG.md
This PR updates the changelog for the v7.2.0-alpha.1 release.
=> [android] Update changelog for v7.2.0-alpha.1

platform/ios/CHANGELOG.md, platform/ios/src/MGLMapView.mm
This implementation of the tilt gesture feels much better. It is inspired by Apple's implementation of the tilt gesture in the Maps application.
Fixes #2192.
=> [ios] Improvement of the tilt gesture

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Release ios-v4.9.0-alpha.2

platform/android/CHANGELOG.md
This PR updates the changelog for the v7.2.0-alpha.1 release.
=> [android] Update changelog for v7.2.0-alpha.2

include/mbgl/platform/gl_functions.hpp, platform/default/src/mbgl/storage/local_file_request.cpp, platform/qt/qt.cmake, src/mbgl/util/chrono.cpp, src/mbgl/util/compression.cpp
https://blog.kowalczyk.info/article/j/guide-to-predefined-macros-in-c-compilers-gcc-clang-msvc-etc..html
=> [build] Use the correct define on Windows

platform/darwin/src/MGLOfflinePack.h, platform/darwin/test/MGLDocumentationExampleTests.swift
Cherry-pick #13943 to `release-kombucha`.
/cc @jmkiley
=> [ios] Mock MGLOfflineStorage in MGLDocumentationExampleTests (kombucha)

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Release ios-v4.9.0-beta.1

platform/android/CHANGELOG.md
Changelog update for the 7.2.0-beta.1 release of the Maps SDK for Android.
=> [android] Android 7.2.0-beta.1 changelog update

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/modes/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/log/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/http/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/types/package-info.java
Fixes first checkbox of #13918
=> Add missing package-info.java files

src/mbgl/gl/attribute.hpp, src/mbgl/gl/context.hpp, src/mbgl/gl/draw_mode.hpp, src/mbgl/gl/vertex_buffer.hpp
=> Remove DrawMode from VertexVector/Buffer

platform/android/MapboxGLAndroidSDK/build.gradle, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/LibraryLoader.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/LibraryLoaderProvider.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/ModuleProvider.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/ModuleProviderImpl.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/loader/LibraryLoaderProviderImpl.java, platform/android/MapboxGLAndroidSDKTestApp/build.gradle, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java
Closes #13928 
- make ReLinker default library loader
- create library loader provider for modularisation
=> make ReLinker default library loader

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java, platform/android/MapboxGLAndroidSDKTestApp/build.gradle, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/GLSurfaceViewReopenTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/TextureViewReopenTest.kt, platform/android/gradle/dependencies.gradle, platform/android/src/map_renderer.cpp, platform/android/src/map_renderer.hpp
Backports #13976 to `release-kombucha`
=> Backport #13976 to kombucha

circle.yml, platform/ios/scripts/install-packaging-dependencies.sh, platform/ios/scripts/trigger-external-deploy-steps.sh
Cherry-picks #13986 to `release-kombucha`.
=> [ios, build] Trigger automated site and docs generation during releases (kombucha)

platform/qt/src/qmapboxgl.cpp
If access tokens are different, we cannot share the file source, because it will override the previously set access token.
=> [qt] Share the same file source only if using the same access token

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Cherry-pick #14005 to `release-kombucha` for the `ios-v4.9.0` release.
=> [ios] Prepare for ios-v4.9.0 release (kombucha)

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/StyleBuilderTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/13517.
=> Add plural style builder methods

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Release ios-v4.10.0-alpha.1

circle.yml
Triggers the iOS metrics tests after the s3 deployment step in `ios-release-template`
=> [ios] Trigger mobile metrics tests

platform/darwin/src/NSExpression+MGLAdditions.mm, platform/darwin/test/MGLExpressionTests.mm, platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md
Fixes a bug where multiple format attributes are passed but ignored.
=> [ios, macos] Fix a bug with multiple format expressions.

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/StyleTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/14080.
=> Set a blank style when an empty builder is provided

scripts/collect-coverage.sh
Fix the broken code cov script for coverage data collection and report generation.
=> [scripts] Fix code coverage script

platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Updated podspecs for v4.10.0-alpha.2.
cc/ @mapbox/maps-ios
=> [ios] Updated podspecs for v4.10.0-alpha.2

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/types/FormattedSection.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java, platform/android/src/style/formatted.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/14101.
=> [android] text-color option for formatted sections

platform/android/gradle/dependencies.gradle
Closes https://github.com/mapbox/mapbox-gl-native/issues/14133.
=> Bump telemetry version to 4.3.0

scripts/code-coverage.sh
Adds the commit SHA to the coverage report script.
=> [build] Add SHA to the iOS coverage report

platform/ios/CHANGELOG.md, platform/ios/app/MBXOrnamentsViewController.h, platform/ios/app/MBXOrnamentsViewController.m, platform/ios/app/MBXViewController.m, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/src/MGLMapView.h, platform/ios/src/MGLMapView.mm, platform/ios/src/MGLScaleBar.mm, platform/ios/test/MGLMapViewLayoutTests.m, platform/ios/test/MGLMapViewScaleBarTests.m
Cherry-pick PR https://github.com/mapbox/mapbox-gl-native/pull/13911
=> [ios] Cherry-pick PR #13911 to adding options to customize positions of mapview ornaments

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/offline/OfflineManagerTest.kt
Removes dependency of Espresso idling resource from OfflineManager tests.
=> Refactor idling resource from test

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14121
=> Add offline troubleshooting link to javadoc of OfflineManager

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java
Refs https://github.com/mapbox/mapbox-plugins-android/issues/886#issuecomment-474870285.
=> Clear the style object when the map is destroyed

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java
Backports https://github.com/mapbox/mapbox-gl-native/pull/14171 to `release-liquid`.
=> Backport #14171 to liquid

platform/android/CHANGELOG.md
CPs https://github.com/mapbox/mapbox-gl-native/pull/14173.
=> Changelog for 7.3.0-beta.1 (CP to liquid)

platform/darwin/src/NSExpression+MGLAdditions.mm, platform/darwin/test/MGLExpressionTests.mm
Cherry picks #14168 into `release-liquid`.
=> CP [ios, macos] Fix format expression parsing. (#14168)

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/MapFragmentActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/SupportMapFragmentActivity.java
Required for recreating the activity after orientation change.
=> call getMapAsync when restoring map fragment 

platform/darwin/src/NSExpression+MGLAdditions.mm, platform/darwin/test/MGLExpressionTests.mm, platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md
Cherry picks #14181 into `release-liquid`
=> CP - [ios, macos] Fix conditional expression parsing error. (#14181)

Makefile, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/scripts/package.sh, platform/ios/sdk-files.json
MMENSDateWrapper -> MMEDate
Add SKIP_DOCS flag to build pipeline for iOS
Cherry-picks #14194 to `release-liquid`.
=> Update to `mapbox-events-ios` release `v0.9.1` [release-liquid]

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/ios/src/MGLMapView.h, platform/ios/src/MGLMapView.mm
=> [ios] Podspecs for v4.10.0 beta.1

platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Bumped podspecs for v4.10.0-beta.1

Makefile, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/scripts/package.sh, platform/ios/sdk-files.json
MMENSDateWrapper -> MMEDate
Add SKIP_DOCS flag to build pipeline for iOS
=> Update to `mapbox-events-ios` release `v0.9.1`

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/GLSurfaceViewReopenTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/TextureViewReopenTest.kt
This PR improves UiAutomator reliability of being able to reopen the app.
=> Improve reliability of UiAutomator tests

platform/android/CHANGELOG.md
Refs https://github.com/mapbox/mapbox-gl-native/pull/14173
=> Fix formatting of the 7.3.0-beta.1 changelog

platform/android/CHANGELOG.md
CPs https://github.com/mapbox/mapbox-gl-native/pull/14186.
=> Backport #14186 to liquid

platform/android/MapboxGLAndroidSDK/gradle.properties
Update snapshot version on master after branch cut for release-liquid
=> Bump snapshot version to 7.4.0

platform/darwin/docs/guides/For Style Authors.md.ejs, platform/darwin/docs/guides/Predicates and Expressions.md, platform/darwin/src/MGLAttributedExpression.h, platform/darwin/src/MGLAttributedExpression.m, platform/darwin/src/NSExpression+MGLAdditions.mm, platform/darwin/test/MGLDocumentationExampleTests.swift, platform/darwin/test/MGLExpressionTests.mm, platform/ios/docs/guides/For Style Authors.md, platform/macos/docs/guides/For Style Authors.md
Cherry picks #14198 into `release-liquid`.
=> CP - [ios, macos] Support expressions in formatting parameters. (#14198)

ci.template
Remove unneeded permissions (https://github.com/mapbox/mapbox-gl-native/pull/14208)
=> Cherry-pick updates in ci.template permissions

platform/ios/Mapbox-iOS-SDK-symbols.podspec, platform/ios/Mapbox-iOS-SDK.podspec, platform/ios/scripts/document.sh, platform/ios/scripts/package.sh
Bump podspec to 4.5.0-cn.2 and update scripts
=> [ios] Bump podspec to 4.5.0-cn.2 and update scripts

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/offline/OfflineManagerTest.kt
We're seeing some unexpected timeouts when running `OfflineManagerTest`. This aims to provide some insight on which step we're hitting the issue.
=> Provide more information when the OfflineManager test times out

circle.yml, cmake/loop-darwin.cmake, platform/darwin/src/NSBundle+MGLAdditions.m, platform/darwin/test/MGLAttributionInfoTests.m, platform/darwin/test/MGLOfflineStorageTests.mm, platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m, platform/ios/Integration Tests/MGLCameraTransitionTests.mm, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/src/MGLMapView.mm, vendor/optional.cmake
Encompasses https://github.com/mapbox/mapbox-gl-native/pull/14229
Updates project to build with Xcode 10.2 / iOS SDK 12.2
=> [ios, core] Updates project for iOS SDK 12.2 / Always use vendored optional

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
=> CP: Don't call OnSurfaceCreated from the main thread

platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md
Adds change logs for https://github.com/mapbox/mapbox-gl-native/pull/14241
=> [ios, macos] Added missing changelog entries for #14241

ci.template, circle.yml, scripts/publish_github_stats.js
Sample output:
```json
{
"created_at": "2019-03-28",
"open_issues_total": 413,
"open_issues_total_android": 97,
"open_issues_total_core": 116,
"open_issues_total_from_non_members": 176,
"open_issues_total_gl_js_parity": 16,
"open_issues_total_ios": 201,
"open_pull_requests_since_last_month": 21,
"open_pull_requests_since_last_month_from_non_members": 3,
"open_pull_requests_total": 42,
"open_pull_requests_total_from_non_members": 13
}
```
=> [build] Metrics: publish Github Stats

scripts/publish_core_codecoverage.js
Add retry logic to fetch coverage report from codecov.io in case of timeout issue.
=> [scripts] Add retry logic to fetch coverage report

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14227.
=> Disable move gesture detector foreseeing the quickzoom

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14260
=> Add pixel dimension annotation to public UiSettings methods

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/PerformanceEvent.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/module/telemetry/PerformanceEventTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/telemetry/PerformanceMeasurementActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/categories.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml, platform/android/scripts/exclude-activity-gen.json
=> [android] updated PerformanceEvent

Makefile, circle.yml, cmake/loop-darwin.cmake, platform/darwin/src/NSBundle+MGLAdditions.m, platform/darwin/test/MGLAttributionInfoTests.m, platform/darwin/test/MGLOfflineStorageTests.mm, platform/ios/CHANGELOG.md, platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m, platform/ios/Integration Tests/MGLCameraTransitionTests.mm, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/src/MGLMapView.mm, platform/macos/CHANGELOG.md, scripts/clang-tools.sh, src/mbgl/renderer/layers/render_line_layer.cpp, src/mbgl/renderer/paint_property_binder.hpp, vendor/optional.cmake
=> CP [ios,macos] Release Liquid cherry picks

include/mbgl/map/map_observer.hpp, include/mbgl/renderer/renderer_observer.hpp, platform/darwin/src/MGLRendererFrontend.h, platform/default/src/mbgl/gl/headless_frontend.cpp, platform/glfw/glfw_renderer_frontend.cpp, src/core-files.json, src/mbgl/gfx/context.hpp, src/mbgl/gl/context.cpp, src/mbgl/gl/context.hpp, src/mbgl/map/map_impl.cpp, src/mbgl/map/map_impl.hpp, src/mbgl/renderer/image_atlas.cpp, src/mbgl/renderer/image_atlas.hpp, src/mbgl/renderer/image_manager.cpp, src/mbgl/renderer/image_manager.hpp, src/mbgl/renderer/image_manager_observer.hpp, src/mbgl/renderer/renderer_impl.cpp, src/mbgl/renderer/renderer_impl.hpp, src/mbgl/style/image_impl.hpp, src/mbgl/style/style_impl.cpp, src/mbgl/tile/geometry_tile.cpp, src/mbgl/tile/geometry_tile.hpp, src/mbgl/tile/geometry_tile_worker.cpp, src/mbgl/tile/geometry_tile_worker.hpp, test/renderer/image_manager.test.cpp
https://github.com/mapbox/mapbox-gl-native/pull/14253
=> cherry pick onStyleImageMissing to liquid

Makefile, circle.yml, scripts/clang-tools.sh
=> [ios] Update `mapbox-events-ios` to `v0.9.2` (#14288)

platform/ios/CHANGELOG.md, platform/ios/src/MGLMapView.mm
Cherry picks #14307 into `release-liquid`
=> [ios] Cherry picks - Enable/disable presentsWithTransaction to address #14232 (#14307)

platform/ios/app/MBXViewController.m, platform/ios/app/missing_icon.json, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/src/MGLMapView.mm, platform/ios/src/MGLMapViewDelegate.h, platform/ios/test/MGLMapViewDelegateIntegrationTests.swift
Cherry picks #14302 into `release-liquid`
=> CP [ios]  Add iOS bindings and example for missing icons event. (#14302)

src/mbgl/renderer/paint_property_binder.hpp
=> [core] Pass crossfade parameters by const reference

include/mbgl/style/conversion_impl.hpp, test/style/conversion/conversion_impl.test.cpp, test/test-files.json
Cherry picks #14352 into release-liquid
=> CP [core] Move should not call destructors

src/mbgl/gl/context.hpp, src/mbgl/gl/features.hpp
CP of #14298 to release-liquid
=> Cherry pick disable binary program shaders 

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/telemetry/PerformanceMeasurementActivity.java
Avoid memory leak by making ```static``` inner classes
=> [android] Avoid memory leak by making static inner classes

src/mbgl/renderer/image_manager.cpp, test/renderer/image_manager.test.cpp
https://github.com/mapbox/mapbox-gl-native/pull/14369
=> cherry-pick missing icon fix to release-liquid

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentConstants.java
Refs https://github.com/mapbox/mapbox-gl-native/issues/14129#issuecomment-479774234.
=> Expose LocationComponentConstants class

platform/ios/scripts/install-packaging-dependencies.sh
Updates to [jazzy 0.9.6](https://github.com/realm/jazzy/releases/tag/v0.9.6) and brings in theme changes from https://github.com/mapbox/jazzy-theme/pull/5.
/cc @captainbarbosa @1ec5
=> [ios, build] Update jazzy (0.9.6) and theme

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Updated podspecs for v4.11.0-alpha.2

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14396.
=> Activate the ConnectivityReceiver when starting the download

platform/ios/src/MGLMapView.mm, src/mbgl/gl/context.cpp
Speculative fix for a rare background crash that we're observing.
/cc @julianrex
=> Run glFinish when reducing memory

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/integration/QueryRenderedFeaturesBoxCountTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxCountActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java, src/mbgl/gl/context.hpp, src/mbgl/gl/features.hpp
This PR cherry picks all required changes for the v7.3.1 patch release.
=> Cherrypick for v7.3.1

platform/darwin/scripts/generate-style-code.js, platform/darwin/src/MGLSymbolStyleLayer.h, platform/darwin/src/NSExpression+MGLAdditions.mm, platform/darwin/test/MGLExpressionTests.mm
Cherry picks #14405 into `release-liquid`
=> CP [ios, macos] Fix MGLSymbolStyleLayer.text localization issue. (#14405)

platform/android/gradle/dependencies.gradle
Refs https://github.com/mapbox/mapbox-gestures-android/issues/64.
Closes https://github.com/mapbox/mapbox-gl-native/issues/14078.
=> Bump gestures library to v0.4.1

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/turf/PhysicalUnitCircleActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_physical_circle.xml
Forgot to push review comments, refs #14429
=> Circle with radius expressed in physical measurement 

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewMapRenderer.java, platform/android/src/map_renderer.cpp, platform/android/src/map_renderer.hpp
This PR cherry-picks required changes to release v7.3.2 from release-liquid-android.
=> Release v7.3.2

platform/android/CHANGELOG.md
Updates the changelog for the v7.3.2 release of the Mapbox Maps SDK for Android.
=> Update changelog for v7.3.2

platform/ios/CHANGELOG.md, platform/ios/src/MGLMapView.mm
Cherry-pick #14439 to `release-liquid`
=> [ios] CP #14439 - Ensure glFinish is called when going into the background, and block rendering in the background

platform/ios/CHANGELOG.md, platform/ios/src/MGLMapView.mm
Fixes #14442 
This PR does not change the logic to check if there's a user location annotation.
=> [ios] Consider anchored UIView callouts when deciding whether to enable presentsWithTransaction

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Prepare for iOS v4.10.0 release

platform/ios/CHANGELOG.md
Looks like #14406 made it into v4.10.0 😅
=> [ios] Update iOS Changelog on master

cmake/node.cmake, platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/AccountsManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUrl.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
Backports https://github.com/mapbox/mapbox-gl-native/pull/14493, https://github.com/mapbox/mapbox-gl-native/pull/14476 and https://github.com/mapbox/mapbox-gl-native/pull/14489 to `release-mojito`.
=> Backports for v7.4.0 beta.2

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentPositionManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationLayerController.java, platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml, platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationComponentOptionsTest.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationComponentPositionManagerTest.kt, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationModesActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/styles.xml
Closes https://github.com/mapbox/mapbox-gl-native/issues/14120.
Also, updates missing fields in the `LocationComponent's` `equals` and `hashcode` methods.
=> Clear up LocationComponent's z-index positioning docs and add "layer-above" option

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Preparation for v4.11.0-beta.1 release.

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Cherry picks #14503
Updates podspecs & change log
=> [ios] CP #14503 - Preparation for v4.11.0-beta.1 release

platform/android/gradle/dependencies.gradle
Closes https://github.com/mapbox/mapbox-gl-native/issues/14484.
=> Bump gestures library to v0.4.2

src/mbgl/renderer/layers/render_symbol_layer.cpp
Cherry pick https://github.com/mapbox/mapbox-gl-native/pull/14517 to release-mojito
=> [core] CP #14517 - Store type of renderable segment when sorting symbols by key

include/mbgl/storage/default_file_source.hpp, platform/default/include/mbgl/storage/offline_database.hpp, platform/default/src/mbgl/storage/default_file_source.cpp, platform/default/src/mbgl/storage/offline_database.cpp, platform/glfw/glfw_view.cpp, platform/glfw/glfw_view.hpp, platform/glfw/main.cpp, test/storage/offline_database.test.cpp
This adds an API to clear the existing database and re-initialize.
=> [core] Add clear cache API

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/DownloadRegionActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_pause_black_24dp.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_region_download.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml, platform/android/scripts/exclude-activity-gen.json
This PR adds a manual test for downloading an region headless. Was using this to look into some offline issues and thought it would be a great addition to the test app. The code is largely based on some sample code from a client + code from the offline plugin test app.
=> Offline manual test, headless region download

platform/ios/CHANGELOG.md, platform/ios/src/MGLMapView.mm
=> [ios] CP #14529 - Check for valid superview to avoid crash on iOS 9

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Cherry picks Mojito beta.2 #14556
=> [ios] CP #14556 - Update podspecs for 4.11.0-beta.2

platform/android/CHANGELOG.md
This PR updates the changelog for release v7.4.0-beta.3
=> [android] - update changelog for v7.4.0-beta.3

platform/darwin/include/mbgl/storage/reachability.h, platform/darwin/src/NSExpression+MGLAdditions.h, platform/darwin/src/NSExpression+MGLAdditions.mm, platform/darwin/src/reachability.m, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/resources/Base.lproj/Localizable.strings, platform/ios/resources/bg.lproj/Localizable.strings, platform/ios/resources/ca.lproj/Localizable.strings, platform/ios/resources/cs.lproj/Localizable.strings, platform/ios/resources/da.lproj/Localizable.strings, platform/ios/resources/de.lproj/Localizable.strings, platform/ios/resources/es.lproj/Localizable.strings, platform/ios/resources/fr.lproj/Localizable.strings, platform/ios/resources/gl.lproj/Localizable.strings, platform/ios/resources/he.lproj/Localizable.strings, platform/ios/resources/hu.lproj/Localizable.strings, platform/ios/resources/ja.lproj/Localizable.strings, platform/ios/resources/ko.lproj/Localizable.strings, platform/ios/resources/lt.lproj/Localizable.strings, platform/ios/resources/pt-BR.lproj/Localizable.strings, platform/ios/resources/pt-PT.lproj/Localizable.strings, platform/ios/resources/ru.lproj/Localizable.strings, platform/ios/resources/sv.lproj/Localizable.strings, platform/ios/resources/uk.lproj/Localizable.strings, platform/ios/resources/vi.lproj/Localizable.strings, platform/ios/resources/zh-Hans.lproj/Localizable.strings, platform/ios/resources/zh-Hant.lproj/Localizable.strings, platform/ios/src/MGLMapView.h, platform/ios/src/MGLMapView.mm, platform/ios/vendor/SMCalloutView/SMCalloutView.m
Follows on from #14453.
Primarily fixes the broken public API.
=> [ios] Static analysis fix tweaks - part 2

platform/android/CHANGELOG.md
=> Updates changelog entry for #14486

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/imagegenerator/SnapshotActivity.kt
Closes #14263, context https://github.com/mapbox/mapbox-gl-native/issues/14263#issuecomment-490860730
=> Add javadoc for onIdle with snapshot, update test app example

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/ImageMissingTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/14636.
/cc @alexshalamov @pozdnyakov
=> Split image missing test

platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
Refs https://github.com/mapbox/mapbox-gl-native/issues/14646#issuecomment-492146637.
=> Expose trackingGesturesManagement attribute

platform/android/MapboxGLAndroidSDK/gradle.properties
This PR updates snapshot version to 8.0.0
=> Update snapshot version to 8.0.0

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/FileUtils.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceMapTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceTestUtils.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/ChangeResourcesCachePathActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/MergeOfflineRegionsActivity.kt
Backports https://github.com/mapbox/mapbox-gl-native/pull/14601 to `release-mojito`.
/cc @Guardiola31337
=> Backport #14601 to mojito

platform/android/CHANGELOG.md
This PR updates the changelog in preparation for Android Maps SKD 7.4.0 release
=> [android] Changelog for v7.4.0 release

platform/android/CHANGELOG.md
This PR cherry picks Changelog changes #14677  in preparation for 7.4.0 release
=> [android] Changelog for 7.4.0 release

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Update podspec to v4.11.0.

platform/android/MapboxGLAndroidSDK/src/main/res/values-cs/strings.xml, platform/android/MapboxGLAndroidSDK/src/main/res/values-hu/strings.xml, platform/android/MapboxGLAndroidSDK/src/main/res/values-pl/strings.xml
Refs https://github.com/mapbox/mapbox-gl-native/pull/14665.
Pulls in all available Transifex translations for Android, including Polish and fixes for cs/hu.
/cc @hrach
=> Polish translation and fixes to Czech/Hungarian for Android

platform/android/MapboxGLAndroidSDK/gradle.properties, src/mbgl/gl/context.hpp, src/mbgl/gl/features.hpp
(cherry picked from commit 805b1402452da74042b995d693c48ee4b79ae337)
=> [Android] 6.8.2 Fix pbf crash issue

platform/android/CHANGELOG.md
PR to update the changelog for v8.0.0-beta.1
=> [android] - update changelog for v8.0.0-beta.1

platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
🍒 Cherry pick of https://github.com/mapbox/mapbox-gl-native/pull/14693
=> [ios] Podspec updates for v4.12.0-beta.1

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/AccountsManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUrl.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
This reverts commit 71fd1474804563265117acd9bff1f94e7a68c08a.
This needs a CP to release-mojito.
=> Revert "[android] new manifest flag to enable/disable sku tokens"

platform/android/CHANGELOG.md
This PR updates the changelog for the v6.8.2 release.
=> Update changelog for releasing v6.8.2

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/TileLoadingMeasurementUtils.java
This PR adds "connectionState" attribute tile loading measurements events.
The value for the recorded connection state are:
- none
- cellular
- wifi
=> [android] added connectivity state attribute to tile loading metric

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/GLSurfaceRecyclerViewActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/TextureRecyclerViewActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
=> Show multiple maps in a RecyclerView example

platform/darwin/src/MGLAccountManager.m, platform/darwin/src/MGLAccountManager_Private.h, platform/darwin/src/http_file_source.mm, platform/ios/app/Info.plist, platform/ios/src/MGLMapboxEvents.m
- Removes temporary conditional code added in #14467 (which was itself a follow-up to https://github.com/mapbox/mapbox-gl-native/pull/14421).
- Other small cleanups.
- Still waiting on text for a changelog entry, but that can come later.
/cc @julianrex @zugaldia
=> [ios] Enable SKU tokens for all requests

platform/darwin/src/MGLAccountManager.m, platform/darwin/src/MGLAccountManager_Private.h, platform/darwin/src/http_file_source.mm, platform/ios/app/Info.plist, platform/ios/src/MGLMapboxEvents.m
Cherry-picks #14578 to `release-nectar`.
=> [ios] Enable SKU tokens for all requests (release-nectar)

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Podspec & changelog bump for impending v5.0.0 release.
=> [ios] Podspec bumps for v5.0.0

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentOptions.java
CP https://github.com/mapbox/mapbox-gl-native/pull/14471 to origin.
=> CP #14471 to origin

platform/android/CHANGELOG.md
CP of https://github.com/mapbox/mapbox-gl-native/pull/14727
=> Update changelog for nectar final release

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK.podspec
Missing a character from Podspec specification 🙈
=> [ios] Add missing tick to Podspec specification

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK.podspec
Cherry picks https://github.com/mapbox/mapbox-gl-native/pull/14729.
=> [ios] Podspec typo fix & changelog edits (🍒 #14729)

src/mbgl/text/glyph.hpp, src/mbgl/text/shaping.cpp, test/test-files.json, test/text/shaping.test.cpp
Port of https://github.com/mapbox/mapbox-gl-js/pull/8255
=> [core] Prefer breaking lines at zero width space (ZWSP)

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/ImageSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterDemSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterSource.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/VectorSource.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CircleLayerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/HeatmapLayerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RealTimeGeoJsonActivity.java
=> Use URI instead of URL to enable asset loading

include/mbgl/storage/resource.hpp, platform/default/include/mbgl/storage/offline_download.hpp, platform/default/src/mbgl/storage/offline_download.cpp, src/mbgl/storage/resource.cpp, src/mbgl/tile/tile_loader_impl.hpp, test/storage/default_file_source.test.cpp, test/storage/offline_download.test.cpp, test/storage/online_file_source.test.cpp
Make the distinction if a resource is being requested for offline usage or if it will be used immediately.
=> [core] Introduce usage tag for resources

platform/android/CHANGELOG.md
This pr updates the Android changelog for the 8.1.0-alpha.1 `oolong` release
=> Changelog for 8.1.0-alpha.1

src/mbgl/renderer/bucket.hpp, src/mbgl/renderer/buckets/symbol_bucket.cpp, src/mbgl/renderer/buckets/symbol_bucket.hpp, src/mbgl/renderer/renderer_impl.cpp, src/mbgl/text/collision_index.hpp, src/mbgl/text/placement.cpp, src/mbgl/text/placement.hpp
* Update symbol dynamic vertex buffer only when needed
* Always use fresh transform state for symbol bucket vertices update
Fixes https://github.com/mapbox/mapbox-gl-native/issues/14806
=> [core] Fix symbol bucket dynamic vertices update

platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Bumps podspec to v5.1.0-alpha.2
=> [ios] Bump podspec to v5.1.0-alpha.2

bin/offline.cpp
The GeoJSON file can't be a FeatureCollection, it must be a single Feature GeoJSON, with simple geometry
=> improve offline cli help page

platform/android/CHANGELOG.md
This PR updates the changelog for release v8.0.1
=> Update changelog v8.0.1

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUrl.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/NativeHttpRequest.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/http/HttpRequestImpl.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxInjector.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/module/http/HttpRequestUrlTest.kt, platform/android/src/http_file_source.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/14819
Add resource usage to HttpRequest, add offline query parameter to HttpRequest.
This PR remains in draft until we have a PR open for iOS
cc @julianrex
=> Add resource usage to HttpRequest, add offline query param

platform/android/CHANGELOG.md
This PR updates the changelog for the 8.1.0-beta.1 release
=> [android] Update changelog for 8.1.0-beta.1

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Cherry picks #14920 into release-oolong
=> [ios] Bump podspec to v5.1.0-beta.1

platform/node/README.md
=> README typo, granualar to granular

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/utils/ColorUtilsTest.kt
Backports https://github.com/mapbox/mapbox-gl-native/pull/14954 to `release-oolong`.
=> Backport #14954 to oolong

platform/ios/app/MBXState.m, platform/ios/app/MBXStateManager.m
Fixes #14919 and follows-up on #14591 by addressing review comments I made after it was merged.
=> [ios] Address iosapp state manager tailwork

platform/android/CHANGELOG.md
Cherry pick of https://github.com/mapbox/mapbox-gl-native/pull/14973 and #14975 for the stable 8.1.0 release
=> [android] Updated Android changelog for stable 8.1.0 release

platform/android/CHANGELOG.md
This PR updates the changelog for 'v8.2.0-alpha.1'.
=> Update changelog for v8.2.0-alpha.1

circle.yml
Refs https://github.com/android-ndk/ndk/wiki/Changelog-r20
=> Update CI image with NDK r20

platform/default/src/mbgl/gfx/headless_frontend.cpp, render-test/runner.cpp
=> [core] Fix error handling in HeadlessFrontend::render()

Makefile
This PR add command in Makefile so that could trigger instrumentation tests on App center easily.
=> [android] Add command to run app center in Makefile

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/MapFragmentUtils.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/NestedViewPagerActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/ViewPagerActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/BottomSheetActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java
@LukasPaczos as discussed internally, this PR is adding a facility creation method to avoid adding null  as attribute parameter.
=> introduce MapboxMapOptions ease of use createFromAttributes

src/mbgl/renderer/render_layer.cpp
Reverts mapbox/mapbox-gl-native#14926
=> Revert "[core] Change severity of too many data-driven properties to "Info""

src/mbgl/renderer/layers/render_circle_layer.cpp, src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp, src/mbgl/renderer/layers/render_fill_layer.cpp, src/mbgl/renderer/layers/render_heatmap_layer.cpp, src/mbgl/renderer/layers/render_hillshade_layer.cpp, src/mbgl/renderer/layers/render_line_layer.cpp, src/mbgl/renderer/layers/render_raster_layer.cpp, src/mbgl/renderer/layers/render_symbol_layer.cpp, src/mbgl/renderer/paint_parameters.cpp, src/mbgl/renderer/render_layer.cpp, src/mbgl/renderer/render_layer.hpp, src/mbgl/renderer/render_source.hpp, src/mbgl/renderer/sources/render_image_source.hpp, src/mbgl/renderer/sources/render_tile_source.cpp, src/mbgl/renderer/sources/render_tile_source.hpp
This helps to avoid unneeded allocations.
=> [core] Share render tiles lists between layers

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
Refs https://github.com/mapbox/mapbox-gl-native/pull/15081.
=> Remove access token's nullability annotations to not impact Kotlin interop

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/mapbox_user_icon_shadow_0px_test.xml
Closes https://github.com/mapbox/mapbox-gl-native/issues/15026.
=> Ensure location shadow's gradient radius is greater than 0

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/15090.
=> Fix up "match" expressions docs with stop arguments

platform/ios/scripts/document.sh, platform/ios/scripts/install-packaging-dependencies.sh, platform/macos/scripts/document.sh
Edits Jazzy config to support https://github.com/realm/jazzy/pull/1077.
Requires https://github.com/mapbox/jazzy-theme/pull/9 to merge before merging.
cc @1ec5
=> [ios, macos] Update Jazzy theme

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotterTest.kt
Refs https://github.com/mapbox/mapbox-gl-native/issues/11669.
=> Ignore a flaky MapSnapshotter test until #11669 is resolved

circle.yml
This PR updates our release build with the same CI image as arm-v8 build.
=> Update CI image of the release job

platform/android/MapboxGLAndroidSDK/gradle.properties
bump snapshot version for the q release (v8.3.0).
=> Update snapshot version for the q release 

include/mbgl/style/layer_properties.hpp, src/mbgl/renderer/layers/render_background_layer.cpp, src/mbgl/renderer/layers/render_circle_layer.cpp, src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp, src/mbgl/renderer/layers/render_fill_layer.cpp, src/mbgl/renderer/layers/render_heatmap_layer.cpp, src/mbgl/renderer/layers/render_hillshade_layer.cpp, src/mbgl/renderer/layers/render_line_layer.cpp, src/mbgl/renderer/layers/render_raster_layer.cpp, src/mbgl/renderer/layers/render_symbol_layer.cpp, src/mbgl/renderer/render_layer.cpp, src/mbgl/renderer/render_layer.hpp, src/mbgl/renderer/renderer_impl.cpp
Backports #15092 to release-mojito.
=> [core][cp] Backport #15092 to mojito

include/mbgl/style/layer_properties.hpp, src/mbgl/renderer/layers/render_background_layer.cpp, src/mbgl/renderer/layers/render_circle_layer.cpp, src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp, src/mbgl/renderer/layers/render_fill_layer.cpp, src/mbgl/renderer/layers/render_heatmap_layer.cpp, src/mbgl/renderer/layers/render_hillshade_layer.cpp, src/mbgl/renderer/layers/render_line_layer.cpp, src/mbgl/renderer/layers/render_raster_layer.cpp, src/mbgl/renderer/layers/render_symbol_layer.cpp, src/mbgl/renderer/render_layer.cpp, src/mbgl/renderer/render_layer.hpp, src/mbgl/renderer/renderer_impl.cpp
Backports #15092 to release-nectar.
=> [core][cp] Backport #15092 to nectar

src/mbgl/renderer/sources/render_custom_geometry_source.cpp
Backports #15112 to release-oolong.
=> [core][cp] Backport #15112 to oolong

src/mbgl/renderer/sources/render_custom_geometry_source.cpp
Backports #15112 to release-mojito.
=> [core][cp] Backport #15112 to mojito

src/mbgl/renderer/sources/render_custom_geometry_source.cpp
Backports #15112 to release-nectar.
=> [core][cp] Backport #15112 to nectar

platform/android/MapboxGLAndroidSDKTestApp/src/main/assets/streets.json, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PressForMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/FragmentBackStackActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/DraggableMarkerActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewDebugModeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/raw/local_style.json, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/raw/sat_style.json
Fixes a bunch of minor issues in the test app and refreshes our local test styles.
=> 8.2.0 QA fixes for the test app

src/mbgl/renderer/render_orchestrator.cpp
Cherry-pick https://github.com/mapbox/mapbox-gl-native/pull/15172 to release-picklejuice
=> [core][cp] Cherry-pick #15172 to release-picklejuice

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/StyleTest.kt
Backports #15191 to `release-picklejuice`.
=> Backport #15191 to picklejuice

platform/android/CHANGELOG.md
Backports #15204 to `release-picklejuice`.
=> Backport #15204 to picklejuice

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
Aligns gesture velocity animations to label the animation start reason as `REASON_API_GESTURE`.
=> Align gesture animation reason

platform/android/CHANGELOG.md
This PR updates the changelog with all changes made to release-oolong for releasing v8.1.1.
=> Update changelog for release v8.1.1

platform/ios/CHANGELOG.md
=> [ios] Fix changelog entries from ios-v5.1.1 (oolong)

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Podspec & changelog updates for the ios-v5.0.2 patch release.
=> [ios] Podspec and changelog updates for v5.0.2

circle.yml, platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/GesturesUiTestUtils.kt, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapGestureDetectorTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/EspressoTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/mapbox_user_icon_shadow_0px_test.xml
This PR cherry picks changes needed for doing a 8.1.1 patch release to release-oolong:
- mapbox/mapbox-gl-native#15093 
- mapbox/mapbox-gl-native#15099 
- mapbox/mapbox-gl-native#15103
=> Cherry-pick changes to release-oolong

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Patches release-mojito to 4.11.2 (attempt 2)
=> Update Podspecs and changelog for 4.11.2 release

platform/ios/CHANGELOG.md
Updates change log for recent patch releases.
/cc @fabian-guerra @captainbarbosa
=> [ios] Updates changelog to reference 4.11.2, 5.0.2, 5.1.2

platform/android/CHANGELOG.md
This PR updates the changelog for a v8.0.2 patch release of `release-nectar` .
=> [android] Update changelog for v8.0.2 patch release

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
- Bumped podspecs for v5.3.0-alpha.1
- Checked Changelog.md
cc @friedbunny
=> [ios] Release 5.3.0-alpha.1

platform/android/gradle/artifact-settings.gradle, platform/android/gradle/gradle-bintray.gradle
CP https://github.com/mapbox/mapbox-gl-native/pull/15137 to nectar
=> [android] update Bintray's package name

platform/android/.gitignore, platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/StyleTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/NoStyleActivity.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml
Closes https://github.com/mapbox/mapbox-gl-native/issues/14751
=> Load a style without an URI or JSON

src/mbgl/renderer/buckets/line_bucket.cpp
Port of https://github.com/mapbox/mapbox-gl-js/pull/8275/commits/655559f387191044f1027339b78c55c25e587d41
=> [core] Increase round join approximation precision

platform/ios/src/MGLMapView.h
=> [ios] Document how scale bar visibility is determined

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] Release v5.3.0 alpha.2

platform/ios/CHANGELOG.md, scripts/check-ci-job-skippability.js
Some minor edits to the iOS changelog, mainly to try out https://github.com/mapbox/mapbox-gl-native/pull/15305.
/cc @jmkiley
=> [ios] Minor style edits to changelog

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Bumped podspecs and changelog.
=> [ios] Release v5.3.0-alpha.3

include/mbgl/util/color.hpp, platform/node/src/node_expression.cpp, platform/node/test/ignores.json, src/mbgl/util/color.cpp
Updated expression test expectation in https://github.com/mapbox/mapbox-gl-js/pull/8640
=> [core][node] Serialize formatted expression's text-color option

circle.yml
Refs https://github.com/mapbox/mapbox-gl-native/pull/15305.
=> Do not skip tag-initiated builds

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CustomGeometrySourceTest.kt, platform/android/src/style/sources/custom_geometry_source.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/12551.
Refs https://github.com/mapbox/mapbox-gl-native/pull/12517#pullrequestreview-142911111.
=> Check if the CustomGeometrySource's java peer is valid when the thread is shutting down

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRenderThread.java
I'm noticing a race condition where `getSurfaceTexture` from https://github.com/mapbox/mapbox-gl-native/issues/13601#issuecomment-512679367 could return `null`:
`TextureView` is attached -> render thread is started -> `onSurfaceTextureAvailable` is delivered on the **main thread** https://github.com/mapbox/mapbox-gl-native/blob/58d773472274e06cab65a55842ce9ba5a6a7e140/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRenderThread.java#L70-L78 -> **render thread** acquires the lock, decides to initialize the context, releases the lock https://github.com/mapbox/mapbox-gl-native/blob/58d773472274e06cab65a55842ce9ba5a6a7e140/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRende …
=> Synchronize TextureView EGL context creation

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/15300
=> Update javadoc on style image missing

platform/ios/app/MBXViewController.m, platform/ios/src/MGLScaleBar.mm
Fixes #15197 
Following the fix set out by @julianrex in https://github.com/mapbox/mapbox-gl-native/issues/15197#issuecomment-521087541
I would like to do some more testing around the observer for locale change.
=> [ios] Fix bug where scale bar shows 0 mm instead of 0

platform/android/CHANGELOG.md, platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md
Adds a changelog for https://github.com/mapbox/mapbox-gl-native/pull/15416.
=> [core] add missing changelog for symbol fading issue

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> Release iOS v5.3.0-beta.2

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> CP Release iOS v5.3.0-beta.2 

platform/android/CHANGELOG.md
CP https://github.com/mapbox/mapbox-gl-native/pull/15458 to `queso`.
=> Changelog for v8.3.0-beta.1

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java
Caught in https://circleci.com/gh/mapbox/mapbox-gl-native/321828.
=> Initialize CameraPositionActivity listeners after the style is loaded

platform/android/CHANGELOG.md, platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md, platform/node/CHANGELOG.md
Add changelog for pr https://github.com/mapbox/mapbox-gl-native/pull/15456
=> Add changelog for fix of mixed SDF+non-SDF icon rendering in one layer

platform/android/CHANGELOG.md, platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md, platform/node/CHANGELOG.md, src/mbgl/layout/symbol_instance.cpp, src/mbgl/layout/symbol_instance.hpp, src/mbgl/layout/symbol_layout.cpp, src/mbgl/layout/symbol_layout.hpp, src/mbgl/renderer/buckets/symbol_bucket.cpp, src/mbgl/renderer/buckets/symbol_bucket.hpp, src/mbgl/renderer/layers/render_symbol_layer.cpp, src/mbgl/renderer/layers/render_symbol_layer.hpp, src/mbgl/text/placement.cpp, test/gl/bucket.test.cpp, test/text/cross_tile_symbol_index.test.cpp
=> Cherry-pick  #15456 [core] fix mixed sdf + non-sdf icon rendering in one layer

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java, platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsAttrsTest.kt, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_camera_position.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_gesture_detector.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/arrays.xml
Cherry-pick of https://github.com/mapbox/mapbox-gl-native/commit/309f566800502f3314bc527c68ba6f41917d500e
=> Add font array attribute configuration for local ideograph font

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Updated the podspecs and changelog for v5.3.0.
=> [ios] Prepare v5.3.0 release

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Cherry-picks changes from master.
=> [ios] Prepare v5.3.0 release (#15516)

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java, platform/android/src/style/android_conversion.hpp
closes https://github.com/mapbox/mapbox-gl-native/issues/15532
=> Avoid converting float to long in android_conversion.hpp

platform/ios/CHANGELOG.md
* Adds a changelog entry for #15562.
* Small edits to the changelog.
=> [ios] Add changelog entry for #15562

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
cc @jmkiley for change log tweaks.
=> [ios] Update pod specs and change log for ristretto alpha.1

.gitignore, platform/linux/README.md
This PR fixes a couple of trivial problems found when building Mapbox GL Native on Linux.
=> Miscellaneous fixes

platform/default/src/mbgl/util/format_number.cpp
Use the old API for number formatting.
=> [core] Fix build with old ICU versions

platform/android/CHANGELOG.md, platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md, platform/node/CHANGELOG.md
=> [Core] Update ChangeLog of Integer Overflow fix of pr #15560 

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/offline/OfflineDownloadTest.kt
closes https://github.com/mapbox/mapbox-gl-native/issues/15324, this seems to be a valid solution as https://github.com/mapbox/mapbox-gl-native/issues/15324#issuecomment-522941173 indicates that the offline download wasn't timing out because of a malfunction, it was just not finished yet. This PR also adds logging on percentage complete and does a cleanup of the nullability of offline region callbacks.
=> Increase timeout of offline download test

platform/ios/CHANGELOG.md
Updates change log and fixes indent issues in log for `5.4.0-alpha.1`
=> [ios] Fix change log typos and re-order

platform/ios/src/MGLMapView.mm
Cleans up some difficult to follow code in `-[MGLMapView validateLocationServices]` to clarify the two possible paths — iOS 11+ (which only asks for `WhenInUse`) and iOS <=10 (which may have had to ask for `Always`, if that’s all that was available).
/cc @julianrex @alfwatt
=> [ios] Refactor way location permissions are requested

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/BulkMarkerActivity.java
=> [android] Fix leaked window in test app's BulkMarkerActivity.

platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
EDIT: No change log updates required.
=> [ios] Update podspecs for 5.4.0-alpha.2

platform/ios/CHANGELOG.md
Removes duplicate items, and `master` section
=> [ios] Update change log.

platform/darwin/src/MGLTypes.h, platform/ios/src/MGLMapView+OpenGL.mm
@m-stephen this PR to your branch adds an error for the iOS 12.2 bug we've seen in the past.
=> [ios] report error if rendering takes > 1 second.

src/mbgl/style/layers/symbol_layer_impl.hpp
Recursively traverse expression tree. Backport from gl-js https://github.com/mapbox/mapbox-gl-js/pull/8068/commits/8cf090ac79cb7591c56a3351825ceda9bf76bb3f#diff-3bf55cc98fb2dce959e7c453e7f1cbeb. Render tests https://github.com/mapbox/mapbox-gl-js/pull/8761
=> [core] Fix for FormatSectionOverrides::hasOverride

platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterSwiftTests.swift, platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterTest.m
Also adds some additional asserts.
=> [ios] Fixed test name (since validAccessToken has been removed)

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
cherry pick of https://github.com/mapbox/mapbox-gl-native/pull/15642 to release-queso.
=> MapSnapshotter.withApiBaseUri function

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> Prepare for Maps SDK for iOS v5.3.1

platform/android/CHANGELOG.md
This PR updates the changelog for a v8.3.1 patch release of release-queso.
=> [android] Updated changelog for 8.3.1 patch release-queso

platform/android/CHANGELOG.md, platform/ios/CHANGELOG.md, platform/macos/CHANGELOG.md, platform/node/CHANGELOG.md, src/mbgl/tile/geometry_tile_data.cpp
Cherry-picks #15560 and #15586.
cc @julianrex @tobrun @zugaldia
=> Cherry-pick #15560 to release-queso

circle.yml
But also mark them as FIXME. Motivation here is we know they are failing and are working on fixing them.
We want to keep them running meanwhile, but not making the pull request show as CI failed.
=> [build] Force failing sanitizer bots to pass

src/mbgl/geometry/feature_index.cpp, src/mbgl/geometry/feature_index.hpp, src/mbgl/renderer/bucket.hpp, src/mbgl/renderer/buckets/symbol_bucket.cpp, src/mbgl/renderer/buckets/symbol_bucket.hpp, src/mbgl/renderer/render_orchestrator.cpp, src/mbgl/renderer/render_orchestrator.hpp, src/mbgl/renderer/render_tree.hpp, src/mbgl/renderer/renderer.cpp, src/mbgl/text/placement.cpp, src/mbgl/text/placement.hpp
Update buckets methods do not mutate placement, placement methods do not mutate buckets.
Tag #14638
=> [core] Fix Placement constness

test/util/timer.test.cpp
A few unit tests exercising a couple of more possible timer cancellation scenarios.
The goal is to cover all the quirks asio::high_resolution_timer cancellation may produce.
1. Timer is cancelled after it's expired but before the runloop is called
2. Timer is cancelled at around the moment of it's processing inside runloop
=> [test] Add unit tests for mbgl::util::Timer covering timer cancellation around the time of its expiration

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> Release ristretto beta.1 prep

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Cherry picks https://github.com/mapbox/mapbox-gl-native/pull/15684
=> [ios] Cherry pick #15684: Release ristretto beta.1 prep

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterActivity.java, platform/android/src/map/camera_position.cpp
=> [android] Fix the crash when CameraPosition padding is set.

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java, platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/AttributionDialogManagerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterActivity.java, platform/android/src/map/camera_position.cpp
This pr cherry picks https://github.com/mapbox/mapbox-gl-native/pull/15623 and https://github.com/mapbox/mapbox-gl-native/pull/15699 to the `release-ristretto` branch.
=> [android] cherry pick of snapshot padding (15623) and feedback form (15699) to ristretto

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Updated pod specs for ristretto.
No changelog edits required.
=> [ios] Update podspecs for v5.4.0 release

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
=> [ios] CP #15716 - Update podspecs & changelog for v5.4.0 release

README.md
CP of https://github.com/mapbox/mapbox-gl-native/pull/15707
=> [CP] license fix to release-ristretto

README.md
CP of https://github.com/mapbox/mapbox-gl-native/pull/15707
=> [CP] license fix to release-queso

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Bumps Podspec & changelog for iOS v5.5.0-alpha.1
=> [ios] Podspec & changelog updates for v5.5.0-alpha.1

circle.yml
Temporarily disable collection of iOS code coverage (see #15747)
=> [ios] Disable iOS code coverage script

cmake/expression-test.cmake, cmake/render-test.cmake, expression-test/expression_test_runner.cpp, expression-test/test_runner_common.cpp, expression-test/test_runner_common.hpp, next/expression-test/CMakeLists.txt, next/render-test/CMakeLists.txt, render-test/runner.cpp
Related to mapbox/mapbox-gl-native-team#37
=> [tests] Share common code between test runners

platform/ios/CHANGELOG.md, platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec, platform/ios/Mapbox-iOS-SDK-stripped.podspec, platform/ios/Mapbox-iOS-SDK.podspec
Podspec and changelog changes for ios-v5.5.0-alpha.2.
=> [ios] Podspec & changelog updates for v5.5.0-alpha.2

circle.yml
Remove bots that already taken care by the `next` buildsystem.
=> [build] Remove redundant builds

platform/android/CHANGELOG.md
This PR updates the changelog for 8.5.0-alpha.2
=> update changelog for 8.5.0-alpha.2

circle.yml
:wave: moving releases to https://github.com/mapbox/mapbox-gl-native-android
=> Remove snapshot and release builds, disable broken metric script

circle.yml
Update CI jobs to [Xcode 11.1](https://circle-macos-docs.s3.amazonaws.com/image-manifest/v1226/index.html).
=> [build] Update to Xcode 11.1

platform/android/src/async_task.cpp, platform/android/src/timer.cpp
Prevent occasional crashes during downloading big number (thousands) of offline regions.
=> [android] Check flag before runnable task invocation

next/platform/ios/ios.cmake
Adds ARC flag to the mgl-core library.
=> [ios] Add ARC config to the new build system.

next/CMakeLists.txt, next/platform/ios/ios.cmake
=> [ios] Set xcode properties for cmake.

circle.yml
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15847
/cc @tmpsantos @mapbox/static-apis @chloekraw
=> Fix node linux publishing

platform/qt/src/qmapboxgl.cpp
=> [qt] Make image source url update possible

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillExtrusionLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs, platform/android/scripts/generate-style-code.js
This PR adds 'image' method to Android Expression dsl class and updates unit tests that use images.
=> [android] Update unit tests that use resolvedImage type

next/CMakeLists.txt, platform/android/src/test/render_test_collator.cpp, platform/darwin/src/MGLAccountManager.h, platform/darwin/src/MGLConversion.h, platform/darwin/src/MGLStyleValue_Private.h
Make compilation more pedantic.
=> [build] Enable more warnings on the next build

platform/darwin/src/http_file_source.mm
Moves host checks into separate utility method and adds checks for cn domains.
cc @zugaldia
=> [ios] Refactors host checks

next/CMakeLists.txt
Refs https://github.com/mapbox/mapbox-gl-native-android/pull/74.
=> Do not fail on tautological-constant-compare error

platform/android/src/native_map_view.cpp, platform/android/src/native_map_view.hpp
This PR provides Android binding integration of https://github.com/mapbox/mapbox-gl-native/pull/15891.
=> Bulk conversion of geographic coordinates to screen coordinates

circle.yml, next/CMakeLists.txt
Also show `unsigned-integer-overflow` errors.
=> [build] Do not halt UBSAN on errors

render-test/render_test.cpp
Fixes https://github.com/mapbox/mapbox-gl-native/issues/16035
=> [test runner] Report absolute path to the results html file

circle.yml
Upload diffs when the sanity bot complains about some wrong formatting of the code or buildsystem.
=> [build] Upload nitpick artifacts

circle.yml
Make it a step of the Linux configuration, since it only makes sense for Linux.
=> [build] Remove "wrapper" parameter

next/CMakeLists.txt, platform/android/src/native_map_view.cpp, platform/android/src/test/render_test_runner.cpp, src/mbgl/style/collection.hpp, src/mbgl/style/sources/geojson_source.cpp, test/actor/actor.test.cpp, test/actor/actor_ref.test.cpp, test/renderer/image_manager.test.cpp, test/tile/tile_cache.test.cpp
And make the build fail in case we reintroduce them.
=> [build] Fix -Wshadow warnings

platform/qt/src/http_file_source.cpp, platform/qt/src/http_file_source.hpp
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/123
=> [qt] Fix usage of QNetworkReply after deletion

src/mbgl/layout/symbol_layout.cpp
CP of https://github.com/mapbox/mapbox-gl-native/pull/16080 for release-tequila.
cc @julianrex
=> Cherrypick 16080

platform/android/src/style/layers/layer.hpp
This PR promotes visibility of Layer::releaseCoreLayer from protected to public.
=> Make Layer::releaseCoreLayer public

.gitmodules
Not needed after the render tests are using the offline cache.
=> [build] Remove uneeded submodules

circle.yml, platform/darwin/src/http_file_source.mm, platform/darwin/test/MGLResourceTests.mm
iOS equivalent of https://github.com/mapbox/mapbox-gl-native-android/pull/148
cc @julianrex
=> [ios, macos] Include SKU token for offline requests

circle.yml, platform/darwin/src/http_file_source.mm, platform/darwin/test/MGLResourceTests.mm
Cherry-pick #16130 and disable doc generation for `ios-release`.
=> [ios, macos] Include SKU token for offline requests (#16130)

src/mbgl/storage/file_source_manager.cpp
Cherry picks https://github.com/mapbox/mapbox-gl-native/pull/16161 to 2020.01-release-unicorn
=> [cp][core] Use std::list instead of std::map for factory instance

CHANGELOG.md
Changelog for  maps-v1.0.1 patch release
=> [core] Prepare changelog for maps-v1.0.1 (2020.01-release-unicorn) patch release

.gitmodules, next/platform/android/android.cmake, next/test/CMakeLists.txt, platform/android/src/run_loop.cpp, platform/android/src/run_loop_impl.hpp, platform/android/src/test/test_runner.cpp, test/android/app/build.gradle, test/android/app/src/main/AndroidManifest.xml, test/include/mbgl/test/util.hpp, test/storage/main_resource_loader.test.cpp
Fixes: mapbox/mapbox-gl-native-team/issues/167
=> [test] Enable HTTP server on Android

README.md
Fix submodule update command in the readme.
=> fix submodule update command

circle.yml, platform/darwin/src/http_file_source.mm, platform/darwin/test/MGLResourceTests.mm
Reverts mapbox/mapbox-gl-native#16133
cc @chloekraw
=> Revert "[ios, macos] Include SKU token for offline requests (#16130)"

CHANGELOG.md
Changelog for maps-v1.2.0 release
=> [core] Prepare changelog for maps-v1.2.0 (2020.02-release-vanillashake) release

include/mbgl/map/bound_options.hpp, src/mbgl/map/map.cpp, src/mbgl/map/transform.cpp, src/mbgl/map/transform.hpp, src/mbgl/map/transform_state.cpp, src/mbgl/map/transform_state.hpp, test/map/map.test.cpp, test/map/transform.test.cpp
Fixes: mapbox/mapbox-gl-native-team#101
=> [core] Add min and max pitch options

CHANGELOG.md
Updates changelog in sync with 1.2.1 release
=> Update changelog for 1.2.1 release

CHANGELOG.md
=> [core] Prepare changelog for maps-v1.3.0 (2020.02-release-vanillashake) release

circle.yml, codecov.yml
Collect code coverage metrics and upload them to codecov.io: https://codecov.io/gh/mapbox/mapbox-gl-native
Also add a nightly build that collects coverage metrics from the master branch and uploads the  results to S3.
Fixes mapbox/mapbox-gl-native-team/issues/92
=> [build] Add code coverage metrics

CHANGELOG.md, platform/default/src/mbgl/util/run_loop.cpp, src/mbgl/geometry/line_atlas.cpp
Cherry-pick  #16249 and #16255 to v1.3.0
=> [CP]  #16249 and #16255 to v1.3.0

CHANGELOG.md, src/mbgl/geometry/line_atlas.cpp
Cherry-pick #16249 to 2020.02-release-vanillashake (1.2.2)
=> Cherry-pick #16249 to 2020.02-release-vanillashake (1.2.2)

render-test/parser.cpp, render-test/runner.cpp
=>  [render test runner] Enable pixel ratio in tile mode

include/mbgl/util/run_loop.hpp
Addressing review comments that arrived after the PR was merged.
=> [core] Follow-up on the platform integration callback PR

platform/android/src/snapshotter/map_snapshotter.cpp
Cherry-pick #16308 to maps-v1.4.0
=> [cp] Update map_snapshotter.cpp (#16308)

CHANGELOG.md
Update change log for the maps-v1.4.1 release
=> Update change log for the maps-v1.4.1 release

CHANGELOG.md
Release maps v1.4.1
CP changelog from master.
=> Release maps v1.4.1

circle.yml, scripts/ci-circleci-start-pipeline.py
Allows you to trigger a pipeline in another repository.
=> [build] Add tool for monitoring CircleCI jobs

.clang-tidy, circle.yml, include/mbgl/util/feature.hpp, platform/default/src/mbgl/map/map_snapshotter.cpp, platform/default/src/mbgl/storage/online_file_source.cpp, platform/default/src/mbgl/storage/sqlite3.cpp, platform/default/src/mbgl/text/local_glyph_rasterizer.cpp, platform/default/src/mbgl/util/monotonic_timer.cpp, platform/glfw/glfw_view.cpp, platform/glfw/test_writer.cpp, scripts/ci/Dockerfile, src/mbgl/geometry/line_atlas.cpp, src/mbgl/layout/symbol_projection.cpp, src/mbgl/map/map.cpp, src/mbgl/programs/symbol_program.cpp, src/mbgl/renderer/buckets/line_bucket.cpp, src/mbgl/renderer/buckets/line_bucket.hpp, src/mbgl/renderer/buckets/symbol_bucket.cpp, src/mbgl/renderer/buckets/symbol_bucket.hpp, src/mbgl/style/conversion/get_json_type.cpp, src/mbgl/style/expression/coercion.cpp, src/mbgl/style/expression/compound_expression.cpp, src/mbgl/style/expression/in.cpp, src/mbgl/style/property_expression.cpp, src/mbgl/text/shaping.cpp
Also add it to warnings as errors list so they don't come back.
=> [core] Fix clang-tidy modernize-* warnings 

CHANGELOG.md, platform/android/src/snapshotter/map_snapshotter.cpp, platform/android/src/snapshotter/map_snapshotter.hpp, platform/android/src/style/sources/custom_geometry_source.cpp, platform/android/src/style/sources/custom_geometry_source.hpp, platform/android/src/style/sources/geojson_source.cpp, platform/android/src/style/sources/geojson_source.hpp, platform/android/src/style/sources/image_source.cpp, platform/android/src/style/sources/image_source.hpp, platform/android/src/style/sources/raster_dem_source.cpp, platform/android/src/style/sources/raster_dem_source.hpp, platform/android/src/style/sources/raster_source.cpp, platform/android/src/style/sources/raster_source.hpp, platform/android/src/style/sources/source.cpp, platform/android/src/style/sources/source.hpp, platform/android/src/style/sources/unknown_source.cpp, platform/android/src/style/sources/unknown_source.hpp, platform/android/src/style/sources/vector_source.cpp, platform/android/src/style/sources/vector_source.hpp
So that users can modify properties of an existing layer / source objects
Draft PR for native-android https://github.com/mapbox/mapbox-gl-native-android/pull/292
=> [android] Expose getLayer, getSource and Observer interface for snapshotter

CHANGELOG.md
Update change log for the maps-v1.5.0 release
=> Update change log for the maps-v1.5.0 release

platform/darwin/src/native_apple_interface.m
Remove debug leftover added by 9009089a93.
=> [darwin] Remove debug leftover

src/mbgl/gl/context.cpp
Cherry pick https://github.com/mapbox/mapbox-gl-native/pull/16349 to release-v1.5.0
=> [cp] Fix assert on gfx resource cleanup

CHANGELOG.md
Ref: mapbox/mapbox-gl-native-team/issues/271
=> Update change log for the maps-v1.5.1 release

CMakeLists.txt
mkdir build && cd build && cmake .. -DMBGL_WITH_WERROR=OFF
=> [build] Add option to disable -Werror

render-test/metadata.hpp, render-test/parser.cpp, render-test/render_test.cpp, render-test/runner.cpp, render-test/runner.hpp
This pull request enables label cut-off and duplication check in the render tests runner.
=> [render tests][tile mode] Automatic labels cut off detection

test/style/style.test.cpp
Adds a regression test for #16391.
=> Add regression test for #16391

circle.yml, metrics/binary-size/linux-gcc8/metrics.json, scripts/ci/Dockerfile, scripts/ci/etc/apt/sources.list
Disco has reached EOL and apt-get fails.
=> [build] Move to Ubuntu Eoan

src/mbgl/renderer/layers/render_location_indicator_layer.cpp, src/mbgl/renderer/layers/render_location_indicator_layer.hpp
=> Fix memleak in  RenderLocationIndicatorLayer

render-test/render_test.cpp
Was broken after logging got moved to its own thread.
=> [render-test] Fix logging

src/mbgl/renderer/layers/render_location_indicator_layer.cpp
=> Add missing cast for unsigned long to int conversion

CHANGELOG.md
=> Update changelog and add 1.6.0 rc.1 label

platform/node/CMakeLists.txt
=> [node] Blacklist Node ABI 83

platform/default/src/mbgl/text/bidi.cpp, src/mbgl/util/convert.cpp
Using GCC 9 from Ubuntu 20.04.
=> Fix compilation issues on GCC 9

CHANGELOG.md
Updated the changelog to reflect the maps-v1.6.0-rc.2 release.
/cc @chloekraw @tmpsantos
=> Mapbox GL Native v1.6.0-rc.2

.github/CODEOWNERS
Require a member of the gl-native team to review a PR
=> [repo] Update code owners

scripts/ci-circleci-start-pipeline.py
The API now replies with a 200 when the request is successful.
=> [build] Fix script that trigger downstream jobs

src/mbgl/renderer/layers/render_location_indicator_layer.cpp, src/mbgl/util/bounding_volumes.cpp, src/mbgl/util/geometry_util.hpp, src/mbgl/util/mat3.hpp, src/mbgl/util/tile_cover.cpp
Fix: https://github.com/mapbox/mapbox-gl-native/issues/16376
=> Fix 'missing braces' compilation errors

CHANGELOG.md
=> Update changelog for the maps-1.6.0 release

platform/darwin/src/http_file_source.mm
=> [darwin] Restore platform check for sku token

circle.yml, platform/linux/linux.cmake, platform/macos/macos.cmake
Remove Android and iOS benchmark runners
=> [build] Remove benchmark runners

scripts/nitpick/submodule-pin.js
=> [build] s/master/main on GL JS
