mapbox/mapbox-gl-native

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java

[android] fixed center calculation for LatLngBounds with zero span

---

platform/darwin/src/MGLStyleValue_Private.h
platform/darwin/src/NSExpression+MGLAdditions.h
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm

Renamed `+[NSExpression mgl_expressionWithJSONObject:]` to `+[NSExpression expressionWithMGLJSONObject:]` in Objective-C and thus `NSExpression.mgl_expression(withJSONObject:)` to `MGLExpression(mglJSONObject:)` in Swift.
Fixes #11612.
/cc @fabian-guerra @jmkiley

Rename expression initializer to be more Swiftian

---

platform/ios/CHANGELOG.md
platform/ios/DEVELOPING.md
platform/ios/INSTALL.md
platform/ios/README.md

Support for iOS 8 is being deprecated in `ios-v4.0.0` and will be removed in a future version — so let’s warn folks.

[ios] Note plans to drop iOS 8

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLAnnotationView.mm

Changes the default value of `MGLAnnotationView.scalesWithViewingDistance` to `NO`, which removes various inescapable overhead and improves out-of-box performance (FPS) by:
- 7% when `pitch = 0`
- 18% when `pitch = 30`
I measured this on iPhone X, 6s, and iPad Pro 10.5 running iOS 11.3/11.4b1 using a cobbled together ~3000 annotation, blank map style, camera movement benchmark — see the [`fb-bench-view-annotations`](https://github.com/mapbox/mapbox-gl-native/compare/release-boba...fb-bench-view-annotations) branch for details.
This change is prompted by the fact that annotation views do not generally perform well (even on top-of-the-line devices) and we need all the help we can get to maintain a smooth frame rate, otherwise the sync between annotation views and the map can become …

[ios] Change MGLAnnotationView.scalesWithViewingDistance default value to NO

---

platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm
platform/darwin/src/NSPredicate+MGLAdditions.mm
platform/darwin/test/MGLPredicateTests.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11013
Add the following operators to `NSExpression`.

[ios, macos] Add predicate like expressions to NSExpression

---

platform/ios/Mapbox.playground/Contents.swift
platform/ios/Mapbox.playground/timeline.xctimeline

- Removes support for Swift 2.x, which we no longer need (as we require Xcode 8.x).
- Updates for Swift 3.2 — namely, `@objc` in a couple places.
/cc @1ec5 @jmkiley @captainbarbosa

[ios] Update playground for Swift 3.2+

---

platform/node/src/node_map.cpp
platform/node/src/node_map.hpp
platform/node/test/js/map.test.js
src/mbgl/style/layers/background_layer.cpp
src/mbgl/style/layers/circle_layer.cpp
src/mbgl/style/layers/fill_extrusion_layer.cpp
src/mbgl/style/layers/fill_layer.cpp
src/mbgl/style/layers/heatmap_layer.cpp
src/mbgl/style/layers/hillshade_layer.cpp
src/mbgl/style/layers/layer.cpp.ejs
src/mbgl/style/layers/line_layer.cpp
src/mbgl/style/layers/raster_layer.cpp
src/mbgl/style/layers/symbol_layer.cpp

CP #11399 to the release branch.
This setup includes node bindings for render tests that will start working when https://github.com/mapbox/mapbox-gl-native/pull/11671 lands.

Update layer immediately when changing its max/min zoom level (CP #11399)

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/docs/guides/Predicates and Expressions.md
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/darwin/test/MGLPredicateTests.mm
platform/ios/docs/guides/For Style Authors.md
platform/macos/docs/guides/For Style Authors.md

[ios, macos] Remove mgl_ prefix from built-in expressions variables.

---

platform/darwin/docs/guides/Predicates and Expressions.md
platform/darwin/src/MGLVectorStyleLayer.h
platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm
platform/darwin/src/NSCompoundPredicate+MGLAdditions.mm
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/src/NSPredicate+MGLAdditions.mm
platform/darwin/test/MGLCircleStyleLayerTests.mm
platform/darwin/test/MGLDocumentationExampleTests.swift
platform/darwin/test/MGLExpressionTests.mm
platform/darwin/test/MGLFillExtrusionStyleLayerTests.mm
platform/darwin/test/MGLFillStyleLayerTests.mm
platform/darwin/test/MGLHeatmapStyleLayerTests.mm
platform/darwin/test/MGLLineStyleLayerTests.mm
platform/darwin/test/MGLPredicateTests.mm
platform/darwin/test/MGLStyleLayerTests.mm.ejs
platform/darwin/test/MGLSymbolStyleLayerTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

[ios, macos] NSPredicate expression filters.

---

platform/darwin/src/MGLStyle.h
platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm

Follows up on #11205 and removes a couple stragglers that are deprecated as of v3.7.6.
- Converts a warning to an exception (`MGLUserLocationAnnotationTypeException`), as promised.
- Rewords the style class unavailability message.
- Removes the `styleID`, `bundledStyleURLs`, and `metersPerPixelAtLatitude:` implementations.
/cc @1ec5 @jmkiley

[ios] Remove more deprecated bits for release-boba

---

platform/darwin/src/MGLAccountManager.h
platform/darwin/src/MGLAccountManager_Private.h
platform/darwin/src/MGLMapSnapshotter.h
platform/darwin/src/MGLNetworkConfiguration.h
platform/darwin/src/MGLOfflineStorage.h
platform/darwin/src/MGLRasterTileSource.h
platform/darwin/src/MGLRendererConfiguration.h
platform/darwin/src/MGLStyle.h
platform/darwin/src/MGLVectorTileSource.h
platform/darwin/test/MGLDocumentationExampleTests.swift
platform/ios/CHANGELOG.md
platform/ios/Mapbox.playground/Contents.swift
platform/ios/docs/guides/Info.plist Keys.md
platform/ios/scripts/script_resources/MapboxDemo/MapboxDemo/ViewController.swift
platform/ios/src/MGLTelemetryConfig.h
platform/macos/CHANGELOG.md
platform/macos/docs/guides/Info.plist Keys.md

Fixes #6778. This improves our Swift interface _in an unavoidably breaking way_ while mostly having no effect on Obj-C usage.
For example, before → after:
- `MGLStyle.streetsStyleURL()` → `MGLStyle.streetsStyleURL`
- `MGLOfflineStorage.shared()` → `MGLOfflineStorage.shared`
- `MGLAccountManager.setAccessToken("foo")`  → `MGLAccountManager.accessToken = "foo”`
This also updates a variety of internal/undocumented classes in a similar way — this doesn’t really matter while we’re using Obj-C, but future-proofs potential Swiftification.

[ios, macos] Convert various class methods to class properties

---

platform/darwin/src/MGLGeometry.h
platform/darwin/src/MGLGeometry.mm
platform/darwin/src/MGLGeometry_Private.h
platform/darwin/src/MGLOpenGLStyleLayer.h
platform/darwin/src/MGLOpenGLStyleLayer.mm

`CATransform3D`'s matrix is internally typed as `CGFloat`, which we were implicitly casting to from `double`. The `-Wc++11-narrowing` flag disallows implicit narrowing casts, so this PR makes it explicit.
Text of the errors:
> non-constant-expression cannot be narrowed from type 'std::__1::array<double, 16>::value_type' (aka 'double') to 'CGFloat' (aka 'float') in initializer list [-Wc++11-narrowing]
This manifested only in `Release` builds, so it wasn’t caught initially by CI or manual testing in `Debug`. The cast-everything fix is what Xcode suggested and seems like the least invasive approach, but perhaps @asheemmamoowala has suggestions about a better path.
In any case, this needs to be addressed before we put out any release, as it fails the build.
/cc @1ec5 @fabian-guerra @julianrex …

[ios] Fix type narrowing issue with MGLOpenGLStyleLayer projection matrix

---

platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillExtrusionStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLHeatmapStyleLayer.h
platform/darwin/src/MGLHillshadeStyleLayer.h
platform/darwin/src/MGLLight.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.h

Duplicated color-typed style property declarations to discuss NSColor instead of UIColor on macOS. This is how things used to be before #10726.
Fixes #11573.
/cc @friedbunny @jmkiley

Replace UIColor with NSColor in documentation

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/src/NSExpression+MGLAdditions.h
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/ios/app/MBXViewController.m
platform/ios/docs/guides/For Style Authors.md
platform/macos/docs/guides/For Style Authors.md

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11016.
This PR adds convenience initializers and properties that helps developers transition from the strongly typed `MGLStyleValue` class.
/cc @1ec5

[ios, macos] Add NSExpression convenience constructors and helper methods.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java

Indicating that `match` expression can fail without falling back to the default value.
/cc @anandthakker

Match expression doc tweaks

---

platform/darwin/src/MGLStyle.h
platform/ios/src/MGLMapView.h

Follows up on #11651. Re-adds `MGLStyle.localizesLabels`, makes it unavailable, and includes a message pointing developers at its replacement.
/cc @1ec5

[ios] Provide MGLStyle.localizesLabels unavailability notice

---

src/mbgl/layout/symbol_instance.cpp
src/mbgl/layout/symbol_projection.cpp

Fixes issue #11729. Close relative of issue #10956 -- in fact, I suspect fixing #10956 just shifted more people to encountering #11729 which for some reason we haven't figured out yet didn't generate intelligible stack traces. 😞 
It is possible for us to receive Glyphs from the server that are valid, but have an invalid bitmap. In that case, the glyphs will be present in the `GlyphMap` used for shaping, but not present in the `GlyphPositions` used in `getGlyphQuads`. `SymbolInstance::hasText` looked at the shaping instead of the actual quads.
`symbol_projection.cpp` should never try to project a label without any quads, but we'll also try to make it so that it doesn't crash if it does.
/cc @friedbunny @ksummerill @ansis @cmxyzx

Don't crash on placing symbols with 0 renderable glyphs

---

CMakeLists.txt

Defaulting to having `-Werror` has value and we should keep it that way.
But most applications that do this also allow developers to disable `-Werror`. This ability to disable is important when developing against a new compiler that might trigger multiple new warnings across the codebase. We want to allow the developer fixing those warnings (or reporting them) to see all the warnings, as warnings, without the build failing on each. Otherwise significant time is lost before one can see them all.
So, this PR introduces the ability to turn warnings back to warnings, while keeping the default intact.

Allow disabling -Werror

---

platform/darwin/docs/guides/Predicates and Expressions.md
platform/darwin/docs/theme/assets/css/jazzy.css.scss
platform/darwin/src/NSExpression+MGLAdditions.h
platform/darwin/src/NSExpression+MGLAdditions.mm

This is a smorgasbord of improvements related to predicate and expression documentation.
Consolidated the NSExpression categories into a single category, with marks to separate different tasks. Documented the `NSExpression(MGLAdditions)` category so that it shows up in the jazzy documentation.
Corrected various factual inaccuracies in the “Predicates and Expressions” guide. Moved some explanation from the predicates section to the expressions section. Added sections for all the other expression types we support.
Reorganized the custom function documentation as a series of sections with headers and definition lists instead of a monolithic table. Linked references to custom functions. Added format string examples for all custom functions. Each custom function definition cross-references the …

Revamp predicate and expression guide

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/docs/guides/Predicates and Expressions.md
platform/darwin/src/NSExpression+MGLAdditions.h
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/ios/CHANGELOG.md
platform/ios/docs/guides/For Style Authors.md
platform/macos/CHANGELOG.md
platform/macos/docs/guides/For Style Authors.md

[ios, macos] Rename featureProperties to featureAttributes.

---

platform/android/build.gradle

Refs. https://github.com/mapbox/mapbox-gl-native/issues/11708.
In order to prevent pushes to the repo that include snapshot artifact references, let's disable the snapshot repository handle in the test app which will cause builds that use snapshots to fail.

Remove snapshot repository reference

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h

Deprecated method `-[MGLMapView metersPerPixelAtLatitude:]` had its implementation removed in 4.0.0 (#11681) but was not marked as unavailable, so this does that.
/cc @julianrex

[ios] Mark -metersPerPixelAtLatitude: as unavailable

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/11733.
Refs. https://github.com/mapbox/mapbox-gl-native/issues/11758.

Unwrap LatLngBounds for the shortest path when requesting camera

---

platform/ios/ios.xcodeproj/xcshareddata/xcschemes/CI.xcscheme
platform/ios/src/MGLMapView.mm
platform/ios/test/MGLAnnotationViewTests.m
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/src/MGLMapView.mm
platform/macos/test/MGLAnnotationTests.m

The drifting of the camera seen in the `WebAPIDataExample` of `ios-sdk-examples` was triggered by the following conditions:
1. The annotation was selected BEFORE it had been added. This causes https://github.com/mapbox/mapbox-gl-native/issues/11476
2. The annotation view was created with `-initWithFrame:` rather that one of the provided initializers. This defaults the `enabled` to `NO`, contrary to the header docs.
3. There are content insets (e.g. a navigation bar).
This PR adds tests to capture this situation (it's slightly different on macos), and the associated fixes.

Fix for camera movement when selecting visible annotations

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java

Stops can be used with other expressions, updating javadoc to reflect that.

Improve stop javadoc to include interpolate

---

benchmark/util/tilecover.benchmark.cpp
cmake/benchmark-files.cmake
cmake/core-files.cmake
include/mbgl/util/projection.hpp
platform/default/mbgl/storage/offline.cpp
src/mbgl/renderer/layers/render_background_layer.cpp
src/mbgl/util/tile_cover.cpp
src/mbgl/util/tile_cover.hpp
src/mbgl/util/tile_cover_impl.cpp
src/mbgl/util/tile_cover_impl.hpp
test/util/tile_cover.test.cpp
test/util/tile_range.test.cpp

The existing scanline-based tile cover implementation blocks when computing large rectangles. When extended to polygonal regions, this would further impact the performance and block interactivity in end-user applications.
This PR implements a streaming tile cover algorithm. An edge table-like data structure is created for all geometry, and then a modified scan-line is used for each tile row. Each row requires just one scan-line 
while accumulating the x-extents for each edge within that row. 
Usage:
```
mbgl::util::TileCover tc(LatLngBounds::world(), zoom);
while(tc.hasNext()) {
UnwrappedtileID tile = *tc.next();
...
};
```
cc @ivovandongen @mourner

[core] Implement TileCover for polygonal regions

---

platform/qt/app/mapwindow.cpp
platform/qt/app/mapwindow.hpp
platform/qt/src/qmapboxgl.cpp

Previously all QMapboxGL objects were sharing the same cache created by the
first instantiated object. Now it will share the cache only if it points to
the same path.
Fixes #11766

[qt] Only share a FileSource if it points to the same path

---

INSTALL.md
platform/ios/DEVELOPING.md
platform/ios/INSTALL.md
platform/linux/README.md
platform/macos/DEVELOPING.md
platform/macos/INSTALL.md
platform/node/DEVELOPING.md
platform/node/README.md
platform/qt/README.md

I've seen several issues where users followed platform-specific install docs, but were unaware of additional prerequisites spelled out in the top-level INSTALL.md. So let's try making each platform's installation documentation self contained.

[docs] Make per-platform installation docs self-contained

---

src/mbgl/text/cross_tile_symbol_index.cpp

Fixes issue #11811 (too much CPU time spent in CrossTileSymbolIndex).
I saw some discussion of discouraging `auto` if the type isn't present on the same line, so in this case the line would be: `const std::map<OverscaledTileID,TileLayerIndex>&`. I could go either way on that idea, but a quick sampling of the 1397 occurrences of `auto (.*) =` in the ios project show that we'd have to add a lot of type info to start following that guideline.
I think the best opportunity for catching something like this is whole SDK automated performance testing (@tobrun has an Android-specific proposal at https://github.com/mapbox/mapbox-gl-native/issues/10917)
/cc @ansis @jfirebaugh @anandthakker

[core] Don't copy TileLayerIndexes on every frame.

---

README.md

The link was pointing to the old version of our sdk before we moved it under the Mapbox namespace. This updates the link to point to the correct package under the Mapbox namespace.
**cc** @lilykaiser

Updated link for react native npm package

---

.tx/config
platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/res/values-ko/strings.xml
platform/darwin/resources/ko.lproj/Foundation.strings
platform/darwin/resources/ko.lproj/Foundation.stringsdict
platform/ios/CHANGELOG.md
platform/ios/framework/Settings.bundle/ko.lproj/Root.strings
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/ko.lproj/Localizable.strings
platform/ios/resources/ko.lproj/Localizable.stringsdict
platform/macos/CHANGELOG.md
platform/macos/macos.xcodeproj/project.pbxproj

Added a Korean localization of the Android and iOS map SDKs from Transifex, courtesy of @tan-tran-ea. (Thanks!)
Also mapped `pt_PT` to `pt-rPT` for European Portuguese on Android, so `tx` stops putting the localization files in the wrong place.
/ref mapbox/mapbox-navigation-android#888
/cc @tobrun @friedbunny

Add Korean localization

---

platform/darwin/src/MGLOfflinePack.mm

`MBGLOfflineRegionObserver` is owned by the offline database thread, and might be destroyed by the time the `dispatch_async` completes. Instead of implicitly capturing `this`, capture a copy of the `MBGLOfflinePack` weak pointer.
Speculatively fixes #6092.

[ios, macos] Avoid implicit capture of MBGLOfflineRegionObserver this pointer

---

platform/darwin/src/MGLOfflinePack.mm
platform/ios/CHANGELOG.md

Cherry picks #11821, adding a changelog entry.

[ios, macos] Avoid implicit capture of MBGLOfflineRegionObserver this pointer (agua)

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/ios/docs/guides/For Style Authors.md
platform/macos/docs/guides/For Style Authors.md

Fixes a broken link to the Predicates and Expressions guide in the Style Authors guide.

[ios, macos] Fix broken link to predicates and expressions guide.

---

src/mbgl/geometry/feature_index.cpp
src/mbgl/geometry/feature_index.hpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/layout/symbol_layout.hpp
src/mbgl/renderer/buckets/symbol_bucket.cpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/placement.cpp
test/gl/bucket.test.cpp
test/text/cross_tile_symbol_index.test.cpp

Native version of mapbox/mapbox-gl-js#6548.
Port of mapbox/mapbox-gl-js#6550.
Prevents symbols that share the same layout properties from colliding against each other.
Fixes issue #11764.
Bump GL JS pin to get regression test.
Rename "bucketName" -> "bucketLeaderID" to make it clearer what it represents.
/cc @ansis @jfirebaugh @ryanbaumann

[core] Only run placement for first layer per SymbolBucket

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Besides bumping podspecs, this brings the `ios-v4.0.0` entries into the `release-agua` changelog... for chronological consistency and to inform devs that progress marches on.
/cc @fabian-guerra @julianrex @jmkiley @lilykaiser

[ios] Prepare ios-v3.7.7 release

---

src/mbgl/gl/attribute.cpp
src/mbgl/gl/attribute.hpp
src/mbgl/gl/context.cpp
src/mbgl/gl/context.hpp
src/mbgl/gl/program.hpp
src/mbgl/gl/vertex_array.cpp
src/mbgl/gl/vertex_array.hpp
src/mbgl/programs/program.hpp
src/mbgl/programs/symbol_program.hpp
src/mbgl/renderer/layers/render_background_layer.cpp
src/mbgl/renderer/layers/render_circle_layer.cpp
src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
src/mbgl/renderer/layers/render_fill_layer.cpp
src/mbgl/renderer/layers/render_heatmap_layer.cpp
src/mbgl/renderer/layers/render_hillshade_layer.cpp
src/mbgl/renderer/layers/render_line_layer.cpp
src/mbgl/renderer/layers/render_raster_layer.cpp
src/mbgl/renderer/layers/render_symbol_layer.cpp
src/mbgl/renderer/render_layer.cpp
src/mbgl/renderer/render_layer.hpp
src/mbgl/renderer/render_tile.cpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/sources/render_image_source.cpp

With data driven styling, we are dynamically computing shaders with a varying number of vertex attributes. One caveat of that is that the minimum mandated number for vertex attributes in the OpenGL ES 2.0 spec is only 8, [as we discovered](https://github.com/mapbox/mapbox-gl-native/issues/8183). Most modern GPUs have a higher limit than that, but there are some older mobile GPUs that only supply the bare minimum (see https://github.com/mapbox/mapbox-gl-native/issues/9331). @jfirebaugh reworked this in https://github.com/mapbox/mapbox-gl-native/pull/9433 to limit the number of vertex attributes we're using.
We're [throwing](https://github.com/mapbox/mapbox-gl-native/blob/ee3073e2416c2e3405ab3b6ed51f48514c95d363/src/mbgl/gl/attribute.cpp#L9) with a "too many vertex attributes" error in this …

Don't crash when attribute count is exceeded

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

This addresses https://github.com/mapbox/mapbox-gl-native/issues/11756.

Use center property (instead of frame) when repositioning annotation views

---

platform/darwin/src/MGLGeometry.h
platform/darwin/src/MGLGeometry_Private.h
platform/darwin/src/MGLMultiPoint.mm
platform/darwin/src/MGLOverlay.h
platform/darwin/src/MGLPointCollection.mm
platform/darwin/test/MGLGeometryTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11377

[ios, macos] Fix overlay bounds that span the antimeridian.

---

platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11757

[ios, macos] Add support for subscripting in expressions.

---

circle.yml

Use XCode 9.3.0 in `macos-debug-qt5` CI build.
Fixes #11661.

[build] Bump macos-debug-qt5 xcode to 9.3.0

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/docs/guides/Predicates and Expressions.md
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/ios/CHANGELOG.md
platform/ios/docs/guides/For Style Authors.md
platform/ios/src/UIColor+MGLAdditions.mm
platform/macos/CHANGELOG.md
platform/macos/docs/guides/For Style Authors.md
platform/macos/src/NSColor+MGLAdditions.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11011

[ios, macos] Add to-rgba expression operator.

---

platform/darwin/src/MGLNetworkConfiguration.h
platform/darwin/src/MGLNetworkConfiguration.m
platform/ios/src/MGLAPIClient.m

This PR generalizes #11845 so that it only takes effect if the application has opted into api.mapbox.cn for the Maps API via the `MGLMapboxAPIBaseURL` Info.plist key. For all other applications, the behavior is the same as in v3.7.7.
/cc @rclee @friedbunny

Use China telemetry endpoint with China API endpoint

---

platform/android/MapboxGLAndroidSDKTestApp/build.gradle

This PR allows to build the release apk with a debug configuration. This unblocks running commands as: `BUILDTYPE=Release make android` so we don't need to provide a real signing configuration.
cc @ChrisLoer

Build release with debug signing

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLAnnotationView.mm

Fixes an issue where `MGLAnnotationView.rotatesToMatchCamera = YES` would wipe out any other transforms that were being applied to that annotation view’s layer, such as via `.scalesWithViewingDistance`.
This bug was hinted at [in a comment during the original PR](https://github.com/mapbox/mapbox-gl-native/pull/9147/files#r123204521), but ultimately lost in the shuffle. Prompted by, but unrelated to, https://github.com/mapbox/mapbox-gl-native/issues/11756.
/cc @julianrex @1ec5

[ios] Fix MGLAnnotationView.rotatesToMatchCamera clobbering other transforms

---

platform/default/mbgl/storage/offline_database.cpp
platform/default/mbgl/storage/offline_database.hpp
platform/default/sqlite3.cpp
platform/default/sqlite3.hpp
platform/qt/src/sqlite3.cpp
test/storage/offline_database.test.cpp
test/storage/sqlite.test.cpp

Fixes #10796.
Unfortuntely, it's difficult to avoid all exceptions, because `sqlite3_open_v2` does not reliably return `SQLITE_NOTADB` if the file is not a database. However, this should avoid cases where developers misinterpret the `SQLITE_CANTOPEN` exception as a crash, which is the common case.

Avoid exceptions for flow control during database creation

---

platform/ios/CHANGELOG.md

This doesn’t do much, except bring in historic commit hashes and a couple changelog entries.
/cc @tobrun @1ec5

Merge release ios-v3.7.8 into master

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/11809. When dividing two integers and assigning it to a float, you are still rounding the output of division. This is expected for our SDK, to workaround this, you can cast one argument to a float so the other is casted automatically.
Context: [4.2.4](http://docs.oracle.com/javase/specs/jls/se7/html/jls-4.html#jls-4.2.4) and [15.17](http://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.17)

Avoid rounding pixelratio of addImage

---

platform/ios/CHANGELOG.md
platform/ios/INSTALL.md
platform/ios/scripts/package.sh

Reverts the removal of `i386` slices from our framework in #10962/`ios-v4.0.0`. This is because CocoaPods effectively forces pods to package `i386` in all of their dependencies (e.g., https://github.com/mapbox/mapbox-navigation-ios/pull/1394).
This puts us back at the `ios-v3.7.x` state, where we strip `i386` from dSYMs only (#10781).
/cc @bsudekum @1ec5 @akitchen @fabian-guerra

[ios, build] Re-add support for 32-bit simulators (i386)

---

platform/qt/include/qmapbox.hpp
src/mbgl/style/expression/compound_expression.cpp

- MinGW has to explicitly know that is building a static library.
- Android doesn't have 'round' on the std:: namespace when using g++.

[qt] Fix build when building the Qt Location plugin

---

platform/darwin/src/MGLVectorTileSource.mm
platform/darwin/src/MGLVectorTileSource_Private.h
platform/darwin/test/MGLStyleTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Respect English in the Preferred Languages setting even if other Mapbox Streets source–supported languages are listed too. Also removed some dead code that is no longer called as of #11651.
Fixes #11906.
/cc @friedbunny @bsudekum

Fix English priority during label localization

---

platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillExtrusionStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLHeatmapStyleLayer.h
platform/darwin/src/MGLHillshadeStyleLayer.h
platform/darwin/src/MGLLight.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLRasterStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.h

Jazzy formats numbers followed by periods at the start of a line as lists. This changed even non-1 numbers to 1.

[ios, macos] Moved numbers away from start of lines in documentation

---

src/mbgl/renderer/buckets/fill_extrusion_bucket.cpp

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11909. 
This check had been written incorrectly anyway — it should be checking to see whether the already-calculated `edgeDistance` + the new edge's distance overflow an `int16_t`. Since `edgeDistance` is now a `std::size_t` I _think_ this should be fixed now, based on my conversations with @danpat today…

Fix always-true numeric_limits check in FillExtrusionBucket

---

appveyor.yml
platform/qt/qt.cmake

AppVeyor started complaining about missing package configurations:
```
CMake Error at platform/qt/qt5.cmake:1 (find_package):
By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Qt5Core", but
CMake did not find one.
Could not find a package configuration file provided by "Qt5Core" with any
of the following names:
Qt5CoreConfig.cmake
qt5core-config.cmake
Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
"Qt5Core_DIR" to a directory containing one of the above files.  If
"Qt5Core" provides a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
platform/qt/qt.cmake:107 (include)
platform/qt/config.cmake:4 (include)
CMakeLists.txt:138 …
```

[build] Use Qt 5.6.3 instead of 5.7 in AppVeyor

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java

This PR revisits our public api to add null ability annotations where possible. This is required to improve our SDK integration when consumed from kotlin.

add nullability annotations to public api 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/MapFragmentActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/SupportMapFragmentActivity.java

Google made a u-turn at i/o this year when it comes to advising to use fragments to build an UI. Since they are now considered first class citizens this PR adds the ability to get a callback when the MapView has been created. Users have reached out in the past to get a reference to the underlying mapview when using our fragments, the callback in this PR makes it easier for them.

Expose MapView created callbacks on MapFragment 

---

platform/android/CHANGELOG.md

This PR releases Android v6.2.0-alpha + updates changelog.

Release Android v6.2.0-alpha.1

---

platform/android/CHANGELOG.md
platform/android/gradle/dependencies.gradle

This PR bumps our telemetry dependency to v3.1.1.

Bump telemetry to v3.1.1

---

appveyor.yml
circle.yml
platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/gradle/dependencies.gradle
platform/qt/qt.cmake

This PR cherry picks #11942 and releases a stable new version of the SDK on Maven.

Release Android v6.1.2

---

platform/android/CHANGELOG.md
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
src/mbgl/storage/resource.cpp
src/mbgl/util/token.hpp
src/mbgl/util/url.cpp
test/util/token.test.cpp

I.e. preserve unknown tokens in URLs rather than replacing them with an empty string.
Fixes #11787.

[core] Align URL token replacement behavior with GL JS

---

src/mbgl/style/conversion/tileset.cpp
test/style/conversion/tileset.test.cpp

Fixes #11963.
cc @ian29 @kkaefer

Clamp TileJSON.bounds latitudes to [-90, 90]

---

platform/node/src/node_map.cpp

This happens when the render finished on the thread, and the user cancels a request in the same event loop iteration. There's an assert in Nan that catches this for Debug builds, but won't prevent it for release builds.
In addition to possibly invoking undefined behavior when we try to call an empty callback, or try to access empty image data, there's a heinous memory leak. Here's what happens when we call `Unref()` twice as part of `renderFinished`:
refcount changes during a render with the above mentioned race condition that leads to `renderFinished` being called twice:
```
initial: 0
Ref() -> 1, calls ClearWeak()
Unref() -> 0, calls MakeWeak()
Unref() -> -1
```
next render:
```
initial: -1 (!)
Ref() -> 0, calls ClearWeak()
Unref() -> -1   ==> MakeWeak() is not called!
```
From now on, …

[node] prevent race condition for renderFinished

---

platform/node/src/node_map.cpp

Merging https://github.com/mapbox/mapbox-gl-native/pull/11948 conflicted with https://github.com/mapbox/mapbox-gl-native/pull/11913
/cc @tobrun

[node] fixup bad merge

---

src/csscolorparser/csscolorparser.cpp

Brings in https://github.com/mapbox/css-color-parser-cpp/commit/325ad381167163a14c1480b3fe3b4384e9f08b01

[core] fix hang when parsing very large angles for hue in hsl colors

---

src/mbgl/util/io.cpp

Apparently, MSVC2015+ has issues with `std::ifstream` when the default type `std::ios::in` is used for blob data. Enforcing `std::ios::binary` should fix that.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/11971.

[core] Use std::ios::binary format in std::ifstream

---

include/mbgl/tile/tile_id.hpp
src/mbgl/renderer/render_tile.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/renderer/tile_pyramid.hpp
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/cross_tile_symbol_index.hpp
src/mbgl/tile/tile.hpp

fix https://github.com/mapbox/mapbox-gl-native/issues/11878
This fixes:
- symbol flickering when crossing the antimeridian
- tile flickering when crossing the antimerdian
I pushed the `glfw-app` changes I used to test the flickering to [port-antimeridan-fix-debug](https://github.com/mapbox/mapbox-gl-native/tree/port-antimeridian-fix-debug)
@ChrisLoer

fix symbol flickering across antimeridian

---

platform/ios/src/MGLMapView.mm

Fixes an issue where an assert in `-updateCalloutView` (added in #11731) would be triggered when interacting with the user location annotation’s callout view. 
This removes _some_ duplicate callout view positioning logic in `-updateUserLocationAnnotationViewAnimatedWithDuration:`, which has the side effect of fixing an occasional delayed jump off to the side by the callout when selecting a moving user location annotation.
Animated changes to the position of the user location annotation view still need to be directly tied to updating its callout view (otherwise the two can become out of sync), so those still happen simultaneously in an animation block.
/cc @julianrex @1ec5

[ios] Use standard callout positioning for unanimated user location changes

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterLocalStyleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml
platform/android/scripts/exclude-activity-gen.json
platform/android/src/snapshotter/map_snapshotter.cpp
platform/android/src/snapshotter/map_snapshotter.hpp
platform/darwin/src/MGLMapSnapshotter.mm
platform/default/mbgl/map/map_snapshotter.cpp
platform/default/mbgl/map/map_snapshotter.hpp

Closes #11974 , this PR adds the ability to use a local style.json file as style for a map snapshotter. This option is needed to port our node render tests to Android in https://github.com/mapbox/mapbox-gl-native/issues/10047.
@LukasPaczos would you be able to review the java code?
@ChrisLoer would you be able to review the core code? (I'm not satisfied with current optional setup, is there a way to make this cleaner? variant or other c++ construct?)

Style JSON configuration on map snapshotter

---

cmake/test-files.cmake
include/mbgl/style/conversion/property_value.hpp
test/style/conversion/property_value.test.cpp

Closes #11940
Needs backport to `release-boba`

Accept constant expressions in non-dds properties

---

platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11874

[ios, macos] Fix keypath expressions, json object is parsed incorrectly for nested keypaths.

---

platform/ios/CHANGELOG.md
platform/ios/vendor/SMCalloutView/SMCalloutView.m

Avoid selecting callout when tapping in blank space. Refs #11875
~This is currently enabled via a define `CHECK_CALLOUT_SHAPE_FOR_HIT_TEST`. We need to consider whether we use a runtime flag instead, or we remove the define/ifdef completely.~

Provide custom hit test for callout views

---

src/mbgl/gl/context.cpp
test/api/custom_layer.test.cpp

For Qt, we're using `MBGL_CHECK_ERROR` as a way to link all OpenGL functions against the `QOpenGLFunctions` object instead of the plain library functions. This adds this wrapper to two missing functions.

Wrap glGetString in `MBGL_CHECK_ERROR` too

---

cmake/test-files.cmake
include/mbgl/style/conversion/property_value.hpp
test/style/conversion/property_value.test.cpp

Backports #11960 to release-boba
----
Closes #11940

release-boba backport: Accept constant expressions in non-dds properties

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLScaleBar.mm

- Added a new "random world tour" to iOS for testing/profiling purposes
- Render MGLScaleBarLabel on demand caching the resulting UIImages for use as scale bar labels
~Edit: No changelog entry yet~
Edit 2: Updated with screenshots of Instruments running the `randomWorldTour` example on an iPhone X, specifically looking at CPU and memory usage (not FPS).
**Before**: In the following image, I'm filtering symbols for `drawTextInRect` which was only used by `MGLScaleBarLabel`. You can see, in this test, taking up a total of 14% of the CPU - significant for such a small on-screen item. You can also see that allocations take up a good chunk of this too (and if we filter on `malloc` - that actually goes up further).
**After**: Filtering on `drawTextInRect` and then `MGLScaleBar`, the effect is …

Updated MGLScaleBar to use rendered UIImages instead of MGLScaleBarLabel

---

src/mbgl/tile/custom_geometry_tile.cpp

Fixes #11957.
When a tile has no features `CustomGeometryTile::setTileData` marks it as `TileNecessity::optional`, before calling `GeometryTile:setData`. This call to `setData` triggers parse and layout on the `GeometryTileWorker` and the worker will subsequently update the tile, which requests a new render frame. In the next frame, the tile is marked as `TileNecessity::Required` again, triggerring a reload of the tile data and subsequent repeat layout of the empty feature data - creating a never-ending loop.
The fix here is to mark the tile as `loaded` and `renderable` instead of `optional`. This way the tile skips layout (and placement) and does not incur future reloads until evicted fro the tile cache. 
Verified the fix on iOS, macOS, and Android. CPU consumption drops back to 0 and …

Set Tile loaded/rendered instead of marking tile as optional.

---

CMakeLists.txt
cmake/test.cmake
test/src/mbgl/test/util.cpp
test/src/mbgl/test/util.hpp

When `WITH_NODEJS=OFF` is set, we are refraining from trying to run `npm install`, but we were still trying to build the node module and run unit tests that require the Node.js server

[build] disable parts of the build that require node when WITH_NODEJS=OFF is set

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/MapboxConfigurationException.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/4972

Remove requirement of having an access token

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/11158.

Raw expression support

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java

This PR fixes an issue where literals passed as property arguments were generating nulls. For example, `PropertyFactory.iconImage(Expression.literal("image"))`.

Allow literal property arguments

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12021

Fix literal wrapping in comparison expressions

---

platform/ios/scripts/deploy-packages.sh

Follow-up to #11997. The release notes templating script uses npm packages, but the deployment script does `make distclean` and wipes out installed/cached packages. So, manually install these packages ourselves (instead of relying on them being implicitly installed by one of our `make` commands).

[ios, build] Install npm packages before deploying

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java

- Make internal/native methods private
- Add descriptions, example.
- Push users towards expected configuration options of Size/Style/Camera
- Specify in docs "don't modify options while snapshot is in progress" (see issue #11825)
- Specify in docs that starting a snapshot while one is in progress is an error
- Emphasize that "region" for the most part clobbers "camera position" (it's not just the target that can change)
- Update `MapboxMap#snapshot` with a suggestion to use `MapSnapshotter` instead.
The motivation here is that I've been doing some `MapSnapshotter` concurrency debugging, and just from looking at the docs I had a hard time figuring out how the Android wrapper was meant to be used. This PR is mainly just a bunch of small tweaks related to things that confused me.
Their …

[android, docs] Clean up MapSnapshotter javadoc.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
platform/android/src/snapshotter/map_snapshotter.cpp
platform/android/src/snapshotter/map_snapshotter.hpp
platform/default/mbgl/map/map_snapshotter.cpp
platform/default/mbgl/map/map_snapshotter.hpp

We added styleJson support to map snapshotter in #11976 but we didn't create any setters/getters for setting a new style json when reusing the same snapshotter object.

add style json setter/getter to map snapshotter

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Telemetry.java

closes https://github.com/mapbox/mapbox-gl-native/issues/12012, this PR exposes the required configurations on Telemetry that are needed for end-developers rolling their own attribution screen. They need to allow end users to opt-in/opt-out of telemetry collection.

expose enableOnUserRequest and disableOnUserRequest 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/11908.
Said NPE could've only happened if a user interacted with the Activity containing the map before the first frame is rendered.

Ensure that camera is invalidated before generating telemetry event

---

platform/ios/src/MGLMapView.mm

This switches our tap gesture recognizer handling methods to look for [`UIGestureRecognizerStateRecognized `](https://developer.apple.com/documentation/uikit/uigesturerecognizerstate/uigesturerecognizerstaterecognized?language=objc), rather than `.Ended`. `.Recognized` is defined to be the same as `.Ended`, but using the former is semantically nicer.
Besides some minor refactoring, this fixes a minor issue where the two-finger single tap (zoom out) gesture was checking for a nonexistent `.Began` state. Tap gestures have no `.Began`/`.Ended` states; they can only be `.Possible` or `.Recognized`. 
Note: the substantive changes are mainly in 5358c38, but I split this into two commits (that I’ll squash) so that those changes can be reviewed without the indentation changes of the second …

[ios] Use 'Recognized' state for tap gesture handlers

---

Makefile
platform/android/.gitignore
platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/LocalRequestTask.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/render/RenderTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/SnapshotterIdlingResource.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/FeatureOverviewActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/render/RenderTestActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/render/RenderTestDefinition.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/render/RenderTestSnapshotter.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/render/RenderTestStyleDefinition.java
platform/android/scripts/exclude-activity-gen.json
platform/android/scripts/run-render-test.py

Continuation of #10045, Closes https://github.com/mapbox/mapbox-gl-native/issues/10047.
This PR enables running the node render test suite on Android:
Example run can be seen [here](https://www.youtube.com/watch?v=jKcg6ygWcqY), executing these tests can be done with:
```bash
make run-android-render-test-arm-v7
```
When running the render tests the following happens
- copies test files from `mapbox-gl-js/test/integration/*` to app assets folder
- builds application and  executes `RenderTest.java` instrumentation test
- pulls images from device and compares results with [PixelMatch](https://github.com/mapbox/pixelmatch)
The following items are open, thinking about tackling them in separate PRs:

Node render test suite on Android

---

platform/default/mbgl/storage/offline_database.cpp
platform/default/mbgl/storage/offline_database.hpp
platform/default/mbgl/storage/offline_download.cpp
platform/default/mbgl/storage/offline_download.hpp
test/storage/offline_database.test.cpp

Fixes #11217
Closes #10252
Alternative to #11235 using batching of resource update/inserts.
Somewhat slower: +/- 30 seconds on Pixel XL 2, 130 seconds on Galaxy Nexus. Higher memory consumption; had to keep the batch size relatively small to avoid running out of memory on old devices.

Offline download batches

---

platform/darwin/src/MGLMapSnapshotter.mm
platform/ios/CHANGELOG.md
platform/ios/Integration Tests/MGLMapViewIntegrationTest.h
platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterTest.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/CHANGELOG.md

I took a stab at making the changes @julianrex and I have been discussing for fixing issue #11827.
- Biggest change: when we apply the watermark on a background thread, don't capture self (turn most of the related instance methods into class methods)
- Don't call mbglMapSnapshotter->snapshot from a user-provided queue, since it's an asynchronous call anyway and starting it on the user's queue requires capturing self.
The design goal here is that we should not be passing shared pointers/references across thread boundaries. Because `startWithQueue` allows users to provide their own queue for handling the completion, we have to assume that anything on that queue can run on another thread (even though the more common `startWithCompletion` will run on the main/UI thread). When we capture a …

Fix MGLMapSnapshotter concurrency bugs (issue #11827).

---

circle.yml

This PR splits Android release builds into 3 jobs:
- `android-build-release`, builds a release version of each ABI and a release flavor of the TestApp with each push to the repo (unless below are run).
- `android-release-snapshot`, runs only on `master` and `release-` branches publishing the snapshot. We could make the regex `release-.*` instead of declaring the branches explicitly, but I feel like it's a bit unsafe and someone could accidentally pollute the snapshot repo.
- `android-release-tag`, runs only for `android-v.*` tags and publishes the release artifact to maven staging repo. This job also inserts the right version name into `MapboxGLAndroidSDK/gradle.properties` file based on the tag. Following current practice, all Android release tags need to start with `android-v` where …

Automate tag release

---

src/mbgl/renderer/renderer_impl.cpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp

fix #11795 
Since placements will be committed even if they do not need the full fade duration to fade features in, we need the new `fadeStartTime` to keep track of how long we still need to fade. This is important because if we fade too long we will trigger another placement and never stop
rendering.
I think the important thing that needs to be reviewed is that the logic that prevents infinite rendering is sound.

always commit placement to fix #11795

---

platform/darwin/src/MGLMapSnapshotter.mm
platform/ios/CHANGELOG.md
platform/ios/Integration Tests/MGLMapViewIntegrationTest.h
platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterTest.m
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/CHANGELOG.md

[ios, macos] CP 11831 into release-chai

---

src/mbgl/style/conversion/filter.cpp
test/style/filter.test.cpp

* Fix crash due to mixing legacy filters and expressions
In some cases, (invalid) nested filters that used a mix of legacy filter
syntax and expression syntax caused a crash due to a failure to
propagate parsing errors from deeper within the filter expression.
These errors went undetected in part because these conversion functions
returned unique_ptr<Expression> values (or vectors thereof), using
{nullptr} to represent a parsing error, but the core expression classes
expect unique_ptr<Expression> that are never null.
This changes over to using expression::ParseResult (aka
optional<unique_ptr<Expression>>), to represent conversion failure
the same way we do in the rest of the expression system.
* Fix clang 3.8 / gcc 4.9 issue

[core] Fix crash due to mixing legacy filters and expressions (#12065)

---

circle.yml

[Container details.](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-422/index.html)

[ios, build] Bump CircleCI to Xcode 9.4

---

platform/ios/app/MBXViewController.m
platform/ios/app/Main.storyboard

Extends the map view in iosapp underneath the home indicator on iPhone X (i.e., into the safe area). Also fixes the two-map debug mode to do the same, while refactoring it out of the menu set up.
_Finally._ 😅 

[ios] Support safe area in iosapp

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedSymbolLayerActivity.java

The `AnimatedSymbolLayerActivity` (see https://github.com/mapbox/mapbox-gl-native/pull/10905) was accidentally removed in https://github.com/mapbox/mapbox-gl-native/pull/11923. Adding it back to the TestApp.

Added AnimatedSymbolLayerActivity back to the TestApp

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java

When computing map's dimensions passed to the core we are accounting for the pixel ratio. These calculations can result in non-integer values which we cast to `int` and effectively allow for minimum available zoom be low enough for the viewport to span beyond 360 degrees. This PR fixes the beforementioned issue by always rounding the map dimensions up.

Ceil map dimensions

---

scripts/launch-c-xcode.in
scripts/launch-cxx-xcode.in

Xcode 10 no longer exposes `DEVELOPER_DIR` to the compiler launcher. We'll have to extract the location of Xcode's developer dir from `$PATH` :(
Fixes  https://github.com/mapbox/mapbox-gl-native/issues/12084
We should backport this to all release branches.

Fix build with Xcode 10

---

platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapboxEvents.m

* [ios] Add custom delay 
Adds a custom delay to the events library initialization. This is only active when using certain profile configurations.
* [ios] events library version update to v0.4.1
* Update Events Library to include missing MGL_EXPORT
* Add MMEEventsService files to Events Lib Submodule
* Change delayTime type to int64_t

[ios] Add custom events library start-up delay (#12088)

---

src/mbgl/renderer/renderer_impl.cpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp

Since placements will be committed even if they do not need the full
fade duration to fade features in, we need the new `fadeStartTime` to
keep track of how long we still need to fade. This is important because
if we fade too long we will trigger another placement and never stop
rendering.

[core] always commit placement to fix #11795

---

platform/darwin/src/MGLVectorTileSource.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Fixes #12063 (same bug as #7399)

Fixed NSLocale.languageCode crash in iOS 9.3

---

platform/ios/CHANGELOG.md

Podspec bump and changelog updates.

[ios] Update changelog for v4.1.0-beta.1

---

platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapboxgl.cpp

Exposes a function that reads all entries from `mbgl::style::getLayers()` and returns a list containing their respective IDs.

[Qt] Add QMapboxGL::layerIds()

---

cmake/test-files.cmake
src/mbgl/geometry/line_atlas.cpp
test/geometry/line_atlas.test.cpp

Backports #12114 to release-chai
----
Address some parts of https://github.com/mapbox/mapbox-gl-native/issues/12113

release-chai backport: Fix undefined behavior in LineAtlas::addDash

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java

Closes #12101, this PR needs a CP to release-chai.

Fix match stop conversion

---

platform/android/.gitignore
platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties
platform/android/scripts/release.py

Android equivalent of https://github.com/mapbox/mapbox-gl-native/pull/12106.
cc: @mapbox/maps-android

[android] Remove support for Fabric

---

platform/darwin/src/NSProcessInfo+MGLAdditions.m
platform/macos/CHANGELOG.md

Cast a wider net when trying to detect the helper process that builds the Interface Builder designable when MGLMapView is displayed in a storyboard or XIB. Detecting the helper process is important because it keeps mbgl and the telemetry subsystem from initializing and causing the designable to time out or raise an exception. In Xcode 10, the helper process has been renamed on each platform:
Platform SDK | Xcode 9 | Xcode 10
----|----|----
iOS | IBDesignablesAgentCocoaTouch | IBDesignablesAgent-iOS
macOS | IBDesignablesAgent | IBDesignablesAgent-macOS
tvOS | IBDesignablesAgentAppleTV | IBDesignablesAgent-tvOS
(tvOS is mentioned here because of #9319.)
I left out the iOS changelog blurb because this fix by itself doesn’t address #10072 or #10573.
/cc @friedbunny @fabian-guerra

Look more widely for IBDesignablesAgent

---

LICENSE.md
Makefile
platform/android/LICENSE.md
platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/build.gradle
platform/android/scripts/generate-license.py

Closes https://github.com/mapbox/mapbox-gl-native/issues/11854.
This PR adds `android-license` make target which generates `platform/android/LICENSE.md` based on all dependencies' POM files. This file is then referenced from the top level `LICENSE.md`.

Android licenses make target

---

platform/qt/qt.cmake
platform/qt/src/qmapboxgl_map_renderer.cpp
platform/qt/src/qmapboxgl_map_renderer.hpp
platform/qt/src/qmapboxgl_scheduler.cpp
platform/qt/src/qmapboxgl_scheduler.hpp

Render threads won't have a scheduler, so we create one that is
shared by all the maps rendering at this thread. The bad side
effect of this is that we need to wake up the render thread
to process events.
Mapbox GL should get rid of processing events on the render
thread. This solution is a workaround.

Use a shared scheduler on threads without a default scheduler

---

platform/android/gradle/dependencies.gradle

CP https://github.com/mapbox/mapbox-gl-native/pull/12156 to `release-chai`.

backport to chai: Telemetry bump to v3.1.3

---

platform/android/LICENSE.md
platform/android/scripts/generate-license.py

Refs. https://github.com/mapbox/mapbox-gl-native/pull/12139. Fixes [`platform/android/LICENSE.md`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/LICENSE.md) formatting.

Android licenses formatting

---

platform/darwin/src/NSProcessInfo+MGLAdditions.m
platform/macos/CHANGELOG.md

Cherry-pick of #12140 to the release-chai branch for iOS map SDK v4.1.0 and macOS map SDK v0.8.0.
/cc @julianrex

Look more widely for IBDesignablesAgent (release-chai)

---

platform/android/src/run_loop_impl.hpp

The `nextRunnable` member is not initialized. While we explicitly set it in most cases before using it, we could trigger undefined memory access in this scenario:
* `addRunnable(x)`
* no call to `processRunnables()` meanwhile
* `removeRunnable(x)`
If the uninitialized `nextRunnable` happens to point to the same memory as `runnable->iter`, we're calling `++nextRunnable` on undefined memory.

Initialize RunLoop::Impl::nextRunnable iterator

---

src/mbgl/util/http_header.cpp

This removes a build warning on iOS: `Unknown warning group '-Wtautological-constant-compare', ignored`
/cc @tobrun

Added check for `-Wtautological-constant-compare` prior to ignore.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java

When the DefaultFileSource goes away while a request is in progress that loads from the local file system with `local://`, we could be invoking `nativeOnResponse()` on an invalid object.

Android: make sure the object is still valid before calling nativeOnResponse()

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12165.

Dispatch camera start callback only when actually moving

---

bin/offline.cpp
bin/render.cpp
platform/default/mbgl/storage/offline_database.cpp
platform/default/mbgl/storage/offline_download.cpp
platform/glfw/main.cpp
src/mbgl/style/expression/coercion.cpp
test/storage/offline_database.test.cpp
test/style/style.test.cpp
test/style/style_layer.test.cpp

Polymorphic types shouldn't be caught by value, as the warning message says. Catch them by constant reference instead.

[core] Fix GCC8's new -Wcatch-value warnings

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java

This PR fixes the need of using reflection to lookup the class by passing it as an argument instead. Some bytecode optimizers had trouble interpreting these lines. While it breaks semver, I think the severity justifies the cause.

Remove reflection lookup for MarkerViewAdapter initialization

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java

Range alpha between 0 and 1 for android int color conversion

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/macos/CHANGELOG.md

- Cherry-picks the `ios-v4.0.3` changelog from #12205.
- Adds changelog entries for #12072 and #12176.
/cc @kkaefer @mollymerp @1ec5 @julianrex

[ios] Update changelog and podspecs for ios-v4.2.0-alpha.1

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Bitcode symbol map files (`bcsymbolmap`) are used in conjunction with dSYMs to symbolicate crashes. CocoaPods doesn't yet automatically preserve `bcsymbolmap` files when it is installing vendored pods, so this PR stops CocoaPods from discarding these files.
CocoaPods also does not add `bcsymbolmap` files to an app's `xcarchive`, so the developer needs to do this themselves, typically as an install-only build script phase — see https://github.com/mapbox/mapbox-gl-native/issues/8463#issuecomment-400040165 for general instructions.
- This partially addresses https://github.com/mapbox/mapbox-gl-native/issues/8463, but a full solution will make the inclusion of dSYMs and `bcsymbolmaps` automatic for all integration methods (or obviate that need).
- …

[ios] Preserve bcsymbolmap files when using CocoaPods

---

src/mbgl/style/expression/is_constant.cpp
test/style/filter.test.cpp

Legacy filters aren't part of the style specification, but you can generate them by parsing a legacy filter in a stylesheet, and obtaining the parsed Filter and serializing it.

Fix crash when trying to parse legacy filters

---

platform/node/src/node_map.cpp
platform/node/test/js/map.test.js

This change disambiguates this error condition with a different error with the same error message at https://github.com/mapbox/mapbox-gl-native/blob/789baf4c1f252071bf58e689e050b34eb2656363/src/mbgl/map/map.cpp#L157-L160

Change error message with invalid render usage

---

platform/linux/README.md

This PR updates the Linux docs section to reflect Ubuntu 18.04 packages availability:
- increases the version number for `libllvm`
- removes the need to add an external ppa repo for `cmake`, which is now part of the distro.

[linux] Documentation update to reflect Ubuntu 18.04 packages

---

circle.yml

- Adds a new `ios-release` CircleCI build that builds in Release mode and runs the iOS tests.
- Renames the previous tag-based package-deploy build from `ios-release` to `ios-release-tag`.
The new build takes about 12-13 minutes cold, which is 2 minutes slower than its Debug counterpart and puts it in the middle of the pack time-wise. So far it’s only building `x86_64` (for Simulator), so it’s not useful (yet?) for binary size metrics (#12212) or a nightly (#10551).
/cc @kkaefer @jfirebaugh @julianrex

[ios] Add per-commit ios-release CircleCI build

---

platform/ios/README.md
platform/macos/README.md

#11437 replaced Bitrise with CircleCI for iOS and macOS continuous integration. This PR updates the readmes for both platforms to match the repository’s main readme.

Update build status buttons

---

platform/darwin/src/MGLVectorTileSource.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Added Japanese and Korean to the list of languages for which the Mapbox Streets source has dedicated name fields, which are used for automatic label localization.
Fixes #12283.

Automatically localize labels into Japanese, Korean

---

circle.yml
platform/ios/scripts/document.sh

Fixes the `ios-release` build (🤞), which was failing after #12292 with ccache permissions issues:
```
ccache: error: Failed to create temporary file for /Users/distiller/.ccache/tmp/async_task.stdout: Permission denied
Command /Users/distiller/project/build/ios/launch-c failed with exit code 1
```
/cc @jfirebaugh @asheemmamoowala @ChrisLoer

[ios, build] Postpone jazzy install for ios-release build

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraAnimateTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraEaseTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraForTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraMoveTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/TestConstants.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/espresso/DeviceIndependentTestActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_camera_test.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_espresso_test.xml

Closes https://github.com/mapbox/mapbox-gl-native/issues/7221

Create device independent tests for camera position testing

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/OnMapReadyIdlingResource.java

Closes #10998 , this PR moves the invocation in of `getMapAsync` in `OnMapReadyIdlingResource` to the main thread. Our tests where suffering from an occasional race condition (1 out 7000 executions) where the style could have been loaded but due to thread switching this was missed when calling getMapSync from the other thread. Will need to do some additional tests run to confirm but I'm hoping proposed code will fix the root cause.
cc @mapbox/android as this file has been used in different projects

avoid race condition when calling getMapAsync from OnMapReadyIdlingResource

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraAnimateTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraEaseTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraForTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraMoveTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/TestConstants.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/espresso/DeviceIndependentTestActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_camera_test.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_espresso_test.xml
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

Closes https://github.com/mapbox/mapbox-gl-native/issues/12238
Todo:

add bearing and tilt to getCameraForLatLngBounds

---

cmake/core-files.cmake
include/mbgl/style/color_ramp_property_value.hpp
include/mbgl/style/conversion/color_ramp_property_value.hpp
include/mbgl/style/layers/heatmap_layer.hpp
include/mbgl/style/layers/layer.hpp.ejs
platform/android/src/style/conversion/property_value.hpp
platform/darwin/src/MGLHeatmapStyleLayer.mm
platform/darwin/src/MGLStyleLayer.mm.ejs
platform/darwin/src/MGLStyleValue_Private.h
scripts/generate-style-code.js
src/mbgl/style/conversion/make_property_setters.hpp
src/mbgl/style/conversion/property_setter.hpp
src/mbgl/style/layers/heatmap_layer.cpp
src/mbgl/style/layers/heatmap_layer_properties.hpp
src/mbgl/style/layers/layer.cpp.ejs
src/mbgl/style/layers/layer_properties.hpp.ejs
src/mbgl/style/paint_property.hpp

Based on patch from @lbud (Lauren Budorick).
Give `HeatmapColorPropertyValue` a more generic name,
since the same value type will be used for both `heatmap-color`
and `line-gradient` properties.

Rename `HeatmapColorPropertyValue` to `ColorRampPropertyValue`

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshot.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterMarkerActivity.java
platform/android/src/graphics/pointf.cpp
platform/android/src/graphics/pointf.hpp
platform/android/src/snapshotter/map_snapshot.cpp
platform/android/src/snapshotter/map_snapshot.hpp
platform/android/src/snapshotter/map_snapshotter.cpp
platform/darwin/src/MGLMapSnapshotter.h
platform/darwin/src/MGLMapSnapshotter.mm
platform/default/mbgl/map/map_snapshotter.cpp
platform/default/mbgl/map/map_snapshotter.hpp
platform/ios/CHANGELOG.md
platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterTest.m
platform/macos/CHANGELOG.md

Closes https://github.com/mapbox/mapbox-gl-native/issues/11365

Add LatLngforScreenCoordinate to snapshotter API

---

platform/android/CHANGELOG.md
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/node/CHANGELOG.md
src/mbgl/text/placement.cpp

Fixes issue #12294: unused debug vertices would pile up in buckets over course of tile's lifetime.
The `feature.alongLine` check should be superfluous, but I kept it in there as a way to validate assumptions.
I can't think of a great place to attach a test for this, since there's no change to behavior other than holding onto extra items in the `dynamicVertices` vector. I manually tested before the change to make sure I could reproduce the unbounded growth (although the growth was not dramatic enough to really be noticeable in the memory profiler: after spinning a tile around for a minute, I found I had a couple thousand unused collision vertices, maybe a couple tens of KB of memory?). After the change, I verified that the vertices weren't being created in non-debug mode, and that they …

[core] Only update collision debug data if debug mode is on

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

- _Collates_ the changelog. 👀
- Adds a new changelog entry for #12263.
- [Changes since `ios-v4.2.0-alpha.1`.](https://github.com/mapbox/mapbox-gl-native/compare/ios-v4.2.0-alpha.1...ec472cb)

[ios] Prepare ios-v4.2.0-alpha.2 release

---

platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/DraggableMarkerActivity.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_draggable_marker.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml
platform/android/build.gradle
platform/android/gradle/dependencies.gradle

Refs #2450.
Adds an example of how to build a class that is responsible for handling dragged symbols and disptaching callbacks with the drag state.
Also, adds Kotlin dependencies to the test app.

Draggable marker example

---

cmake/node.xcscheme

This is now the same as the Run action. Previously, you had to manually select the Node executable when launching in Profiling mode.

Add Node as executable for profiling action

---

platform/darwin/src/MGLTileSource.h

Similiar to #10821, jazzy was complaining that `MGLTileSourceOptionDEMEncoding` was declared twice.
In #11568, @1ec5 moved this declaration to `MGLRasterDEMSource.h`, but somehow it snuck back in to `MGLTileSource.h` (during some merge, I suppose). In this PR, I’ve kept the original placement in `MGLTileSource.h` (with all of the other `MGLTileSourceOption`s) and transferred the more detailed documentation there.
/cc @1ec5 @mollymerp

[ios, macos] Remove duplicate MGLTileSourceOptionDEMEncoding declaration

---

platform/macos/CHANGELOG.md

There’s no v0.7.2 release of the macOS map SDK, and the macOS changelog fell out of sync with the iOS one following #12327.

Fact-check and reorganize macOS changelog

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/geometry/GeoJsonConversionTest.java
platform/android/src/geojson/geometry_collection.cpp

closes #12343 
fix jni method lookup of GeometryCollection accessor geometries, add regression test.
cc @osana

fix jni method lookup of GeometryCollection accessor

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12316, validated with a unit test and we don't actually need to make the List of LatLng to be unique in the bounds builder. The `LatLngBounds.fromLatLngs` is able to take this in account.

Remove unique LatLng validation of LatLngBounds builder

---

platform/ios/CHANGELOG.md
platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m
platform/ios/Integration Tests/MGLMapViewIntegrationTest.h
platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm

Addresses #11829 
This PR adds the offset to the annotation rect checking in `-[MGLMapView annotationTagAtPoint:persistingResults:]` (and associated changes).

Update annotation view touch handling (with offsets)

---

platform/ios/scripts/metrics.sh

Use the `strip` command before recording binary size metrics for the iOS framework — this is the same command [we use when packaging stripped release builds](https://github.com/mapbox/mapbox-gl-native/blob/3710ef8810bdab2d2e7f261c3b5c5e4053a279c9/platform/ios/scripts/package.sh#L169-L177) and results in a closer approximation of actual in-app size.
Follows up on #12282.
```
37M	build/ios/pkg/dynamic/Mapbox-stripped
9.4M	build/ios/pkg/dynamic/Mapbox-stripped-arm64
8.7M	build/ios/pkg/dynamic/Mapbox-stripped-armv7
9.4M	build/ios/pkg/dynamic/Mapbox-stripped-x86_64
```
```
19M	build/ios/pkg/dynamic/Mapbox-stripped
4.9M	build/ios/pkg/dynamic/Mapbox-stripped-arm64
4.5M	build/ios/pkg/dynamic/Mapbox-stripped-armv7
5.1M	build/ios/pkg/dynamic/Mapbox-stripped-x86_64
```

[ios, build] Strip symbols before recording size metrics

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/geometry/GeoJsonConversionTest.java
platform/android/src/geojson/geometry_collection.cpp

Backports #12344 to release-chai
----
closes #12343 
fix jni method lookup of GeometryCollection accessor geometries, add regression test.
cc @osana

release-chai backport: fix jni method lookup of GeometryCollection accessor

---

include/mbgl/util/projection.hpp
platform/glfw/glfw_view.cpp
test/util/projection.test.cpp

Captured while testing https://github.com/mapbox/mapbox-gl-native/pull/12310 - but also reproducible in upstream master in some circumstances (e.g. when the width is much higher than height).
Projecting round -90.0 degrees using the [WebMercator projection algorithm](https://en.wikipedia.org/wiki/Web_Mercator#Formulas) produces undefined behavior because `log(0)` is undefined - in [C++ documentation for log](https://en.cppreference.com/w/cpp/numeric/math/log):
> If the argument is ±0, -∞ is returned and FE_DIVBYZERO is raised.
Thus, we need to constrain the latitude to be clamped between the WebMercator minimum and maximum latitude values.

Harden projection

---

circle.yml

- Renames Node and Qt builds to follow the `<platform>-<optional-descriptor>-<buildtype>` naming convention — e.g., `macos-debug-qt5` is now `qt5-macos-debug`.
- ~Fixes #12073 by splitting out Maven credential generation into an alias.~
... though the diff may appear to indicate otherwise, there are no substantive changes here — just renames and moves.
/cc @LukasPaczos @brunoabinader @jfirebaugh

Clean-up CircleCI config; consistify build naming

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/docs/guides/Predicates and Expressions.md
platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/src/NSPredicate+MGLAdditions.mm
platform/darwin/test/MGLPredicateTests.mm
platform/ios/CHANGELOG.md
platform/ios/docs/guides/For Style Authors.md
platform/macos/CHANGELOG.md
platform/macos/docs/guides/For Style Authors.md
src/mbgl/style/conversion/filter.cpp

The `[c]` and `[d]` options are now supported within comparison predicates for case and diacritic insensitivity, respectively. Along the way, the mbgl code that detects expressions in filters had to be updated to allow a collator as the third argument to a comparison expression.
Fixes #12269. Working towards #11786.
/cc @ChrisLoer @fabian-guerra @anandthakker

Convert between predicate options and collator expressions

---

platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

#11866 assumes the arguments to an `MGL_MATCH` expression are all expressions. But for use cases like https://github.com/mapbox/mapbox-gl-native/issues/11830#issuecomment-401914223, it feels natural to insert a raw object instead of a constant-value expression containing that object. This change allows either an expression or a non-expression as an argument to a match expression. There probably are other places where we’re assuming that arguments are wrapped in expressions, but this is the most likely one to trip up a developer.

Allow unwrapped arguments in match expressions

---

platform/ios/ios.xcodeproj/project.pbxproj

The dynamic, static, and test targets in ios.xcodeproj now share the same references to mbgl static libraries. The static target’s references had gone stale, resulting in this error when building the static scheme:
```
Build input file cannot be found: '/path/to/mapbox-gl-native/platform/ios/build/Debug-iphoneos/libmbgl-core.a'
```
This change doesn’t fix the more serious errors when building the dynamic+static scheme in #12339.
/cc @friedbunny @jfirebaugh

Deduplicate library dependency references

---

platform/macos/app/Base.lproj/MainMenu.xib
platform/macos/app/DroppedPinAnnotation.h
platform/macos/app/DroppedPinAnnotation.m
platform/macos/app/MapDocument.m

Added an Import command to macosapp’s File menu for adding the contents of one or more GeoJSON files to the map. [simplestyle-spec](https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0/) formatting is applied to layers via a handful of expressions. Dropped pins include any details provided through simplestyle-spec properties.
Fixes #5483.
/cc @bsudekum @captainbarbosa

Import GeoJSON

---

circle.yml

Brings back the nightly iOS dynamic framework upload — see #8337 for background and documentation.
This piggy-backs on the existing `ios-release` job, running it in a new `nightly` workflow that’s triggered daily at midnight (US Pacific time, apparently) on the `master` branch.
CircleCI’s [preset environmental variables](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables) don’t include a direct way to tell if a job was triggered by a schedule, so I’ve repurposed `CIRCLE_COMPARE_URL` (which is empty for scheduled jobs, but filled for PRs, merges, and tags).
Refs #10551
/cc @kkaefer @jfirebaugh @julianrex

[ios, build] Upload nightly iOS release build on CircleCI

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Second of two PRs — this cherry-picks #12366 into `release-drink`.
/cc @jmkiley @fabian-guerra

[ios] Update podspecs for ios-v4.2.0-beta.1 (release-drink)

---

circle.yml

CircleCI's cron jobs run on UTC, while their containers are set to US-Pacific. This change pushes back the `nightly` workflow from 12AM UTC (5PM PDT) to 5AM UTC (10PM PDT).

[ios] Adjust iOS nightly build to run later

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Capturing from an end-user:
> mapGestureDetector is set during onSurfaceCreated() whereas onTouchEvent only checks if nativeMapView != null which is false after onGlobalLayout(). onGlobalLayout() occurs before onSurfaceCreated() and its possible that a touch event can happen in the middle. Therefore, onTouchEvent should also check that mapGestureDetector != null which onGenericMotionEvent does already.

Validate if gesture detector is able to handle gesture

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/BulkMarkerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java

add convenience method for destroyed state on MapView which can be used to determine if an asynchronous result should be set on map.

MapView#isDestroyed

---

include/mbgl/style/expression/value.hpp
src/mbgl/style/expression/value.cpp

Use a single template function for each of {to,from}ExpressionValue, always dispatching to ValueConverter.
Remove unused ValueConverter::ExpressionType typedefs.

[core] Simplify Value conversions

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/geometry/GeoJsonConversionTest.java

Closes #12345 , this PR ensures the convert method is called on the related c++ files and as result makes sure that the java related method is executed from JNI.

add geojson regression tests for java method look up from JNI

---

platform/android/gradle/dependencies.gradle

Was hitting IDE compilation issues on both macOS as Linux:
> Please select an Android SDK
Capturing form the comments in [this](https://stackoverflow.com/a/50119113/1281750) SO post that we need to bump our kotlin dependency to `1.2.51` instead of `1.2.50`. While I was at it validated if other dependencies could be bumped (okhttp and Timber).

Bump kotlin, timber and okhttp dependencies

---

cmake/filesource.cmake
platform/default/mbgl/storage/offline_database.cpp
platform/default/mbgl/storage/offline_schema.hpp
platform/default/mbgl/storage/offline_schema.js

Removes special casing in some situation, and use template syntax in the generation script.

Make the offline DB schema a regular include file

---

src/mbgl/util/tile_cover_impl.cpp
src/mbgl/util/tile_cover_impl.hpp
test/util/tile_cover.test.cpp

Fixes #11870.
The `create_bound_towards_maximum` and `create_bound_towards_minimum` methods responsible for creating a Bound from a local y-minima to a local y-maxima treated all input vectors of points as a ring. This was only valid for polygons(!!) but worked for lines if they met certain pre-conditions.
The example lines used in #11870 show that lines don't always start at a local y-minima. (i.e. a line can go from south to north)
From a given starting point, it is only necessary to iterate points until a point changes direction on the y-axis. This fix drastically simplifies the `create_bound_towards_`* methods. 
Also added comments describing the streaming tile cover algorithm.

Fix TileCover for LineStrings

---

platform/android/build.gradle

Bumps latest gradle tools version to match Android Studio 3.1.3 (potentially need to update ci-image)

Bump used gradle tools version

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12404.
`MapEventFactory`'s constructor requires a `Context` provided by the `MapboxTelemetry`. Below change ensures that the telemetry is initialized before creating the event.
This might not resolve the crash from #12404 itself if the `Mapbox#getInstance` wasn't called beforehand, but at least it will throw the right exception.
/cc @electrostat

Harden map events creation

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

backport of https://github.com/mapbox/mapbox-gl-native/pull/12405 to `release-drink`

[android] harden map events creation (backport to drink)

---

platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapboxEvents.m

Cherry-picks #12088 to `release-node-v4.0.0` to fix iOS CI failures. This branch already had the necessary submodule commit (via 8e47cccac3649d2f531d60cbc93753ca3bc8dc76), but was missing the accompanying iOS project changes.
/cc @kkaefer @rclee

Cherry-pick iOS events symbol visibility fix to `release-node-v4.0.0`

---

CMakeLists.txt
cmake/benchmark.cmake
cmake/core.cmake
cmake/filesource.cmake
cmake/glfw.cmake
cmake/loop-darwin.cmake
cmake/mbgl.cmake
cmake/node.cmake
cmake/offline.cmake
cmake/render.cmake
cmake/test.cmake

(Factored this out from a larger refactor)
This is only visible in IDEs like Xcode:

Organize CMake targets in folders for IDEs

---

platform/android/src/run_loop.cpp

`runnable->iter = runnables.end()` assumes that `::end()` is a `static` or `constxpr` and thread-safe. This is likely to be true for most of the implementations. That said we cannot rely on undefined behavior and we should assume the worse case scenario.

[android] Fix possibly race on undefined behavior

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Always reset `_changeDelimiterSuppressionDepth` will lead to "Unbalanced change delimiter suppression/unsuppression".
The issue will happen when a gesture not ended and another gesture triggered.
I've encountered this issue while debuging, here is the log:
```
2018-06-14 14:39:25.633152+0800 MapboxLab[27249:10009823] From: handlePinchGesture:, _changeDelimiterSuppressionDepth++, value=1
2018-06-14 14:39:25.664658+0800 MapboxLab[27249:10009823] From: touchesBegan, _changeDelimiterSuppressionDepth=0, value=0
2018-06-14 14:39:26.066514+0800 MapboxLab[27249:10009823] From: handlePinchGesture:, _changeDelimiterSuppressionDepth--, value=-1
```
/cc @chriswu42

[iOS] Fix unbalanced change delimiter

---

platform/android/CHANGELOG.md

Cherry pick of https://github.com/mapbox/mapbox-gl-native/pull/12425, couln't use backport tool as it resulted in conflicts. This stems from me updating the changelog only on release-drink with last beta release.

Cherry pick: Update changelog for v6.3.0

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Moves the changelog entry for #12148 out of `ios-v4.2.0`, as it missed this release.

[ios] Prepare ios-v4.2.0 release (master)

---

platform/macos/CHANGELOG.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec

Updated the changelog and CocoaPods podspecs for macOS map SDK v0.9.0 to coincide with the release of iOS map SDK v4.2.0.

Mapbox Maps SDK for macOS v0.9.0

---

src/mbgl/programs/program.hpp
src/mbgl/programs/programs.hpp
src/mbgl/renderer/layers/render_circle_layer.cpp
src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
src/mbgl/renderer/layers/render_fill_layer.cpp
src/mbgl/renderer/layers/render_heatmap_layer.cpp
src/mbgl/renderer/layers/render_line_layer.cpp
src/mbgl/renderer/layers/render_symbol_layer.cpp
src/mbgl/renderer/paint_parameters.cpp
src/mbgl/renderer/paint_parameters.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp

Since https://github.com/mapbox/mapbox-gl-native/pull/9185 we started generating DDS-specific program objects to work around some OpenGL implementations that were slow with constant vertex attributes. When reusing a map object with many different styles, this leads to the generation of many permutations of Program objects that are retained indefinitely. This patch adds a retention duration which is 100 frames in continuous mode, and 20 frames for static frames.

Remove unused generated OpenGL programs

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

This PR exposes the core map object on native_map_view

Expose getMap

---

cmake/mbgl.cmake

Add some diagnostics to get a better handle on #12250. (Of course, as soon as you add logging, the problem disappears. 🤷‍♂️ )

[build] See what happened when `npm install` fails

---

scripts/check_binary_size.js

We can't run the checks without potentially exposing the Github App private key to malicious PRs.
https://github.com/mapbox/mapbox-gl-native/pull/12434#issuecomment-406714517

[build] Disable binary size checks for fork PRs

---

platform/android/gradle/gradle-javadoc.gradle

replace deprecated javaCompile with getJavaCompiler()

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java

This PR fixes invalid accestoken validation.

Correct accesstoken validation

---

include/mbgl/style/filter.hpp
platform/qt/src/qmapboxgl.cpp
src/mbgl/style/conversion/filter.cpp
test/style/filter.test.cpp

As a follow up to #12226 , hold on to the original input for legacy filters and pass it back in `Filter::serialize()`. This prevents internally converted filter expressions from being exposed via `QMapboxGL::getFilter()`
refs: #12264 
cc @anandthakker @kkaefer

[core] Keep original input for legacy filters

---

scripts/environment.js

Walk backward through the history (maximum of 10 commits) until finding a commit on either `master` or `release-*`; assume that's the base branch.
This ensures that the size checks report the difference to the base even if you haven't opened a PR yet (as they did here).

[build] Attempt to determine a likely base branch without a PR

---

include/mbgl/style/types.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Property.java
platform/android/scripts/generate-style-code.js
platform/android/src/style/conversion/types_string_values.hpp
platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLSymbolStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.mm
platform/darwin/test/MGLSymbolStyleLayerTests.mm
platform/node/test/ignores.json
src/mbgl/layout/symbol_layout.cpp
src/mbgl/programs/symbol_program.cpp
src/mbgl/programs/symbol_program.hpp
src/mbgl/renderer/layers/render_symbol_layer.cpp
src/mbgl/renderer/layers/render_symbol_layer.hpp
src/mbgl/style/types.cpp
src/mbgl/text/collision_feature.cpp
src/mbgl/text/get_anchors.cpp
src/mbgl/text/get_anchors.hpp
src/mbgl/text/quads.cpp

Fixes #12300.
Removes unused "maxCameraDistance" shader uniforms (these have been obsolete since the switch to viewport collision detection and render-time line-label layout).
Also changes collision detection behavior for line labels with width less than 1/2 of a collision circle (previously, such labels wouldn't show).
Using an unmerged pin of GL JS for tests.
`text-max-angle/line-center` is currently failing because one extra label is showing up -- I haven't dug into why yet.
/cc @ansis @nickidlugash

Port `symbol-placement: line-center` to native

---

package.json

This removes the `"preinstall": "npm install node-pre-gyp",`. This is not needed and also might cause problems with some `npm` versions. So it should be removed.
I was originally added as part of moving away from putting `node-pre-gyp` in the `bundledDependencies`. But neither of these workarounds are needed with recent node > 4.
Refs https://github.com/mapbox/node-pre-gyp/issues/260#issuecomment-407222286

Remove 'preinstall'

---

src/mbgl/algorithm/covered_by_children.hpp
test/algorithm/covered_by_children.test.cpp

Another spin-off from https://github.com/mapbox/mapbox-gl-native/pull/12310 - I discovered that the `coveredByChildren` algorithm returns `true` if at least one child is entirely covered by its grandchildren. 
Because we are limiting the number of tiles in #12310, some edge cases were causing the lower zoom tiles to disappear - notice that symbols still appear because their rendering is unaffected by clip IDs.
On the screenshots below, notice how the uppermost tile is not rendered (only its symbols), and its absence of depth buffer color:
| original | depth buffer |
| --- | --- |
| ![screenshot from 2018-07-11 22-28-52](https://user-images.githubusercontent.com/76133/42595776-f8ce87d6-855b-11e8-8088-d1d1808a20f2.png) | ![screenshot from 2018-07-11 …

[core] coveredByChildren is false if at least one child is uncovered

---

include/mbgl/style/conversion/data_driven_property_value.hpp
include/mbgl/style/conversion/property_value.hpp
include/mbgl/style/expression/array_assertion.hpp
include/mbgl/style/expression/at.hpp
include/mbgl/style/expression/boolean_operator.hpp
include/mbgl/style/expression/case.hpp
include/mbgl/style/expression/coalesce.hpp
include/mbgl/style/expression/compound_expression.hpp
include/mbgl/style/expression/error.hpp
include/mbgl/style/expression/expression.hpp
include/mbgl/style/expression/interpolate.hpp
include/mbgl/style/expression/is_constant.hpp
include/mbgl/style/expression/let.hpp
include/mbgl/style/expression/literal.hpp
include/mbgl/style/expression/match.hpp
src/mbgl/style/expression/assertion.cpp
src/mbgl/style/expression/boolean_operator.cpp
src/mbgl/style/expression/case.cpp
src/mbgl/style/expression/coalesce.cpp
src/mbgl/style/expression/coercion.cpp
src/mbgl/style/expression/collator_expression.cpp
src/mbgl/style/expression/equals.cpp
src/mbgl/style/expression/find_zoom_curve.cpp
src/mbgl/style/expression/interpolate.cpp
src/mbgl/style/expression/is_constant.cpp
src/mbgl/style/expression/length.cpp
src/mbgl/style/expression/match.cpp
src/mbgl/style/expression/parsing_context.cpp
src/mbgl/style/expression/step.cpp

Replacing all `dynamic_cast` usages in expressions code with a strategy enumerator plus `static_cast` obtained benchmark results up to 27% faster:
Benchmark | Time | CPU | Time Old | Time New | CPU Old | CPU New
-- | -- | -- | -- | -- | -- | --
Parse_CameraFunction/1 | -22.47% | -22.41% | 4343 | 3367 | 4369 | 3390
Parse_CameraFunction/2 | -21.24% | -21.08% | 4959 | 3906 | 4979 | 3929
Parse_CameraFunction/4 | -22.06% | -21.72% | 6510 | 5074 | 6503 | 5090
Parse_CameraFunction/6 | -24.25% | -23.88% | 7880 | 5969 | 7873 | 5993
Parse_CameraFunction/8 | -23.66% | -23.45% | 9230 | 7046 | 9224 | 7062
Parse_CameraFunction/10 | -27.79% | -27.50% | 10453 | 7549 | 10448 | 7574
Parse_CameraFunction/12 | -27.85% | -27.63% | 11652 | 8408 | 11649 | 8431
Evaluate_CameraFunction/1 | 2.43% | 2.73% | 56 | 58 …

[core] Replace expressions RTTI with enums + static cast

---

platform/darwin/src/MGLComputedShapeSource.h
platform/darwin/src/MGLGeometry.h
platform/darwin/src/MGLGeometry.mm
platform/darwin/src/MGLGeometry_Private.h
platform/darwin/src/MGLOfflineStorage.h
platform/darwin/src/MGLRasterDEMSource.h
platform/darwin/src/MGLRasterTileSource.h
platform/darwin/src/MGLShapeSource.h
platform/darwin/src/MGLStyleValue.h
platform/darwin/src/MGLTileSource.h
platform/darwin/src/MGLTypes.h
platform/darwin/src/NSExpression+MGLAdditions.h
platform/darwin/src/NSExpression+MGLPrivateAdditions.h
platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView_Private.h

Fixes #12079.
Here’s my (potentially incorrect) understanding of this fix: `MGLMapPointForCoordinate()` was `extern`-defined in a C header, but implemented in an Obj-C++ source file and mangled as a C++ symbol. `FOUNDATION_EXTERN` is C++-aware and will force C-style symbol mangling, which fixes the undefined symbol issue in consumer Obj-C projects (#12079).
You can verify the change in symbol mangling using `nm`:
_Before:_
```
00000000000d3b21 T __Z24MGLMapPointForCoordinate22CLLocationCoordinate2Dd
```
_After:_
```
00000000000a0c01 T _MGLMapPointForCoordinate
```
This PR also:
- Moves `MGL_EXPORT` for two private methods to `MGLGeometry_Private.h`, rather than defining them with the implementation.
- Adds internal docs for `MGLPointRounded()` and removes obsolete iOS 7 compatibility.
/cc …

[ios] Improve geometry method definitions

---

platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/ios/CHANGELOG.md

Aiming to fix this issue https://github.com/mapbox/mapbox-gl-native/issues/12164 and compatible with [name fields of Mapbox Streets v8](https://www.mapbox.com/vector-tiles/mapbox-streets-v8/#common-fields).

[iOS] Add fallbacks for name fields

---

circle.yml

Follow up from https://github.com/mapbox/mapbox-gl-native/pull/12457, 
Circle-CI variables are unset and not empty as I wrongly assumed.

Validate if circle-ci var is unset

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

Add minimal touch target to marker click detection

---

circle.yml

Third time the charm, we are running into some CI issues for PRs coming from forks. While solution in https://github.com/mapbox/mapbox-gl-native/pull/12489 worked for [this](https://github.com/mapbox/mapbox-gl-native/blob/master/circle.yml#L401) step, it failed for the [next](https://github.com/mapbox/mapbox-gl-native/blob/master/circle.yml#L414) step in this [build](https://circleci.com/gh/mapbox/mapbox-gl-native/134890?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). Seeing that the only difference is the usage of `shell: /bin/bash -euo pipefail` I opted to remove it from the configuration.

[android] - unbound variable with external PR

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml

Closes https://github.com/mapbox/mapbox-gl-native/issues/10990, this PR exposes a color int configuration on MapboxMapOptions that is used as foreground color during map startup. Only when the style has loaded, we will show the render surface. This results in removing the black flash as shown in #10990.

Remove black surface during map start up

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/VisibleRegionTest.kt

VisibleRegion on rotated map over antimeridian 
closes #12135 , #12463

VisibleRegion on rotated map

---

DEVELOPING.md
cmake/mason-dependencies.cmake
include/mbgl/style/expression/compound_expression.hpp
src/mbgl/gl/context.hpp
src/mbgl/style/expression/interpolate.cpp
src/mbgl/style/expression/match.cpp
src/mbgl/style/expression/step.cpp
src/mbgl/tile/geometry_tile_data.hpp
test/api/recycle_map.cpp

This PR includes the changes that are needed for building mapbox-gl-native on Qt QNX 7( [Mapbox Qt bug](https://bugreports.qt.io/browse/QTBUG-59685) ). It also updates the mason modules geometry, geojsonvt and vector-tile to latest to get the fixes that are needed for QNX 7 compiler. 
Reason for the errors: QNX 7 compiler (i.e qcc based GCC 5.4.0 with libc++ from LLVM) has a limited c++11 feature support and causing the following compilation errors: 
```
1)
qt5/qtlocation/src/3rdparty/mapbox-gl-native/src/mbgl/tile/geometry_tile_data.hpp:37:45: error: 'template<class _InputIterator> mbgl::GeometryCollection::GeometryCollection(_InputIterator, _InputIterator, const allocator_type&)' inherited from 'std::__1::vector<mbgl::GeometryCoordinates>'
using std::vector<GeometryCoordinates>::vector; …
```

Fix compilation errors on QNX 7

---

include/mbgl/style/expression/compound_expression.hpp
include/mbgl/style/expression/is_constant.hpp
src/mbgl/style/expression/compound_expression.cpp
src/mbgl/style/expression/find_zoom_curve.cpp
src/mbgl/style/expression/is_constant.cpp
src/mbgl/style/expression/parsing_context.cpp

I think it should be possible to eliminate `SignatureBase` and its virtual methods and just have:
```c++
struct Signature {
std::string name;
type::Type result;
variant<std::vector<type::Type>, VarargsType> params;
EvaluationResult (*evaluate)(const EvaluationContext&,
const std::vector<std::unique_ptr<Expression>>&);
};
```
But it's a tricky problem that I didn't manage to crack yet.

Shave some binary size in CompoundExpression implementation

---

cmake/core-files.cmake
include/mbgl/style/conversion/color_ramp_property_value.hpp
include/mbgl/style/conversion/constant.hpp
include/mbgl/style/conversion/custom_geometry_source_options.hpp
include/mbgl/style/conversion/data_driven_property_value.hpp
include/mbgl/style/conversion/function.hpp
include/mbgl/style/conversion/property_value.hpp
src/mbgl/style/conversion/color_ramp_property_value.cpp
src/mbgl/style/conversion/constant.cpp
src/mbgl/style/conversion/coordinate.cpp
src/mbgl/style/conversion/custom_geometry_source_options.cpp
src/mbgl/style/conversion/filter.cpp
src/mbgl/style/conversion/function.cpp
src/mbgl/style/conversion/geojson_options.cpp
src/mbgl/style/conversion/layer.cpp
src/mbgl/style/conversion/light.cpp
src/mbgl/style/conversion/position.cpp
src/mbgl/style/conversion/property_setter.hpp
src/mbgl/style/conversion/source.cpp
src/mbgl/style/conversion/tileset.cpp
src/mbgl/style/conversion/transition_options.cpp

* `return {}` → `return nullopt`
* `error = { "..." }` → `error.message = "..."`

[core] Tweak conversions to reduce binary size

---

platform/node/DEVELOPING.md

Main change here is to remove a caveat about macOS binaries -- those are now built automatically by CI, just like Linux binaries. Also removed some links to outdated code.

Update documentation for node publishing process

---

src/parsedate/parsedate.cpp
src/parsedate/parsedate.hpp

We're using a modified version of cURL's `parsedate` function. This PR updates it to use the most recent version.

Update parse_date from cURL 7.61.0

---

circle.yml

[Container details.](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-430/index.html)

[ios, build] Bump CircleCI to Xcode 9.4.1

---

platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapboxgl.cpp

This should enable immediate client side feedback on whether a given paint/layout property has been successfully applied.

[Qt] QMapboxGL::set{Paint,Layout}Property should return bool

---

src/mbgl/renderer/tile_pyramid.cpp

It doesn't make sense to prefetch GeoJSON tiles because there aren't any network calls associated with loading tiles from geojson-vt, and prefetching causes overdraw flickering to be much worse which is affecting users. 
Related to https://github.com/mapbox/mapbox-gl-native/issues/11877#issuecomment-402486813
@1ec5 @LukasPaczos I took a quick look and didn't see any, but are there docs/examples I need to update reflecting this change?

[core] don't prefetch tiles for geojson sources

---

platform/ios/CHANGELOG.md

Updates Events submodule to include a CLLocationManager crash fix.
ref: https://github.com/mapbox/mapbox-events-ios/pull/55

[iOS] Update Events submodule with crash fix

---

platform/qt/app/mapwindow.cpp
platform/qt/qt.cmake
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_p.hpp

Enables (optionally) passing a style property value as a JSON string in QMapboxGL's `setPaintProperty` and `setLayoutProperty`. Added example usage in the Qt demo app.

[Qt] Accept JSON as property value

---

platform/ios/scripts/release-notes.js
platform/ios/scripts/release-notes.md.ejs

Follows up on #11997 to add support for pre-releases in our generated GitHub release notes.
This eliminates the manual updating of URLs in release notes for pre-releases, but not the manual curation of pre-release-to-pre-release notes to remove irrelevant changelog entries.
If you want to test this out, run `./platform/ios/scripts/release-notes.js` and it will print the current release notes for `ios-v4.3.0-alpha.2`.
/cc @fabian-guerra @julianrex @captainbarbosa

[ios, build] Support pre-releases in templated release notes

---

package.json
platform/android/scripts/metrics.sh
platform/ios/scripts/metrics.sh
scripts/publish_binary_size.js

[build] Push binary size history to S3

---

Makefile
platform/qt/README.md
platform/qt/qnx.cmake
platform/qt/qt.cmake

This adds CMake toolchain for QNX platform. By using this toolchain, we can compile Mapbox GL Plugin for Qt on QNX platform.

[Qt] Add CMake toolchain for QNX platform

---

include/mbgl/style/expression/expression.hpp
src/mbgl/style/expression/compound_expression.cpp
src/mbgl/style/expression/expression.cpp

More generic name as the same class member is to be used by the
linear gradient properties.

Rename `EvaluationContext::heatmapDensity` to `colorRampParameter`

---

scripts/environment.js

Follows-up on #12446. The search for a branch containing the previous hash could return multiple matches on separate lines if, for instance, a newly-cut release branch were identical to master. Since the branches are effectively the same, it should be safe to only return the first match.
See [this failure on the `release-espresso` cut](https://circleci.com/gh/mapbox/mapbox-gl-native/139158) and [this failure on a separate `master`-based branch after the cut](https://circleci.com/gh/mapbox/mapbox-gl-native/139188).
/cc @jfirebaugh @julianrex @LukasPaczos

[build] Fix CI failure when master and release branch are identical

---

scripts/environment.js

Cherry-picks #12569 to `release-espresso` to fix the build.
/cc @julianrex @fabian-guerra @jfirebaugh

[build] Fix CI failure when master and release branch are identical (release-espresso)

---

src/mbgl/util/logging.cpp

Use an explicit std::string to distinguish from unnecessary use of const char* overload.
cc @jfirebaugh @kkaefer

[core] Use correct Log::record overload.

---

src/mbgl/util/logging.cpp

Cherry pick https://github.com/mapbox/mapbox-gl-native/pull/12571 for the release.

[core] Use correct Log::record overload. (release-espresso)

---

src/mbgl/util/http_header.cpp
test/storage/headers.test.cpp

This reverts commit 990b3b11b9427ffd86f693d3f4c3dd351891e5d0 as it seems that `std::regex` usage has increased binary size, per comments [here](https://github.com/mapbox/mapbox-gl-native/pull/12475#issuecomment-411446157).

Revert "[core] Replace Boost.Spirit with std::regex in CacheControl::parse

---

scripts/check_binary_size.js

In addition to the GitHub “Checks” binary size stats, also print that information to the CI log, e.g.,
```
iOS armv7: +1.21 kB 0.032% (3.84 MB) (3839952 bytes)
iOS arm64: +1.3 kB 0.031% (4.15 MB) (4145944 bytes)
iOS x86_64: +1.31 kB 0.029% (4.45 MB) (4452864 bytes)
iOS Dynamic: +1.3 kB 0.008% (16.7 MB) (16728856 bytes)
```
~_(Also temporarily includes #12569, so tests run/pass.)_~

[build] Print binary size stats to CI logs, too

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Cherry-picks #12579 to `release-espresso`.

[ios] Updated podspecs and changelog (release-espresso)

---

platform/macos/macos.xcodeproj/project.pbxproj

Fixed a build warning caused by a nonexistent library search path in the Debug configuration:
```
ld: warning: directory not found for option '-L/path/to/mapbox-gl-native/platform/macos/cmake/Debug'
```
This change just removes the setting. I don’t recall why it was necessary in the first place, but everything still seems to work, and the iOS targets don’t need this setting. 🤷‍♂️
/cc @GretaCB @kkaefer

Remove bogus library search path

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm

Improves Swiftiness of `MGLMapView.decelerationRate` by allowing type-omission, à la `mapView.decelerationRate = .fast`.
In the past we’ve decided that Swift-only interface changes do not warrant semver major bumps. Swift users that have this property set will see a fix-it with something like:
> error: 'MGLMapViewDecelerationRateNormal' has been renamed to ‘MGLMapViewDecelerationRate.normal'
/cc @julianrex @fabian-guerra @captainbarbosa @1ec5

[ios] Add MGLMapViewDecelerationRate typed enum

---

platform/darwin/src/MGLComputedShapeSource.h
platform/darwin/src/MGLComputedShapeSource.mm
platform/darwin/src/MGLForegroundStyleLayer.mm
platform/darwin/src/MGLOfflinePack.h
platform/darwin/src/MGLOfflinePack.mm
platform/darwin/src/MGLOfflineStorage.h
platform/darwin/src/MGLOfflineStorage.mm
platform/darwin/src/MGLShape.mm
platform/darwin/src/MGLSource.mm
platform/darwin/src/MGLStyle.h
platform/darwin/src/MGLStyle.mm
platform/darwin/src/MGLStyleLayer.h
platform/darwin/src/MGLStyleLayer.mm
platform/darwin/src/MGLStyleLayer_Private.h
platform/darwin/src/MGLTilePyramidOfflineRegion.mm
platform/darwin/src/MGLTileSource.mm
platform/darwin/src/MGLTypes.h
platform/darwin/src/MGLTypes.m
platform/darwin/src/MGLVectorStyleLayer.m
platform/darwin/src/NSBundle+MGLAdditions.h
platform/darwin/src/NSBundle+MGLAdditions.m
platform/darwin/test/MGLOfflinePackTests.m
platform/darwin/test/MGLOfflineRegionTests.m
platform/darwin/test/MGLStyleTests.mm
platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm

Fixes #7258 by converting stringly-typed exception names into `MGLExceptionName`-typed constants. This doesn’t attempt to document the exceptions, but that could happen in the future.
/cc @1ec5 @fabian-guerra @julianrex @captainbarbosa

[ios] Standardize exception definitions

---

platform/darwin/src/MGLTypes.h

Removes `typedef`s added in #6923 for Xcode 7 compatibility — we currently require Xcode 8 (for app integration) or Xcode 9 (to build the SDK), so this can be removed.
~_(Also temporarily includes #12569, so tests run/pass.)_~
/cc @1ec5 @julianrex @fabian-guerra

[ios] Remove Xcode 7 compatibility typedefs

---

platform/qt/src/http_file_source.cpp

Or else some sources that have been moved permanently will fail with error 301

[qt] Use FollowRedirectsAttribute in network requests

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CustomGeometrySource.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CustomGeometrySourceTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GridSourceActivity.java
platform/android/src/native_map_view.cpp
platform/android/src/style/sources/custom_geometry_source.cpp
platform/android/src/style/sources/custom_geometry_source.hpp
platform/android/src/style/sources/source.cpp
platform/android/src/style/sources/source.hpp

Fixes https://github.com/mapbox/mapbox-gl-native/issues/12516.

Shutting down thread pool of the CustomGeometrySource when the source is destroyed

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/geometry/LatLngBoundsTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12549, 
This PR uses unconverted bearing values from core when calculating bounds. 
Requires cherry pick to release-espresso branch.

Use unconverted bearing value for latlngbounds calculation

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/node/CHANGELOG.md

Oops, forgot to include these with #12337.
/cc @fabian-guerra @tobrun @ansis

[docs] Changelog entries for symbol-placement: line-center

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CustomGeometrySourceTest.kt

Closes https://github.com/mapbox/mapbox-gl-native/issues/12618.
This PR temporarily disables a couple of `CustomGeometrySource` tests until https://github.com/mapbox/mapbox-gl-native/issues/12551 is resolved.

[android] temporarily disable CustomGeometrySource tests

---

platform/android/CHANGELOG.md
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/node/CHANGELOG.md
src/mbgl/text/placement.cpp

Fixes issue #12483.
Port of https://github.com/mapbox/mapbox-gl-js/pull/7041.
I don't know a good way to write automated tests for this on the native side since we do our render tests in "still mode" which skips this logic. @RomainQuidet would you be interested in trying out this branch to see if it addresses your problem? (Also since it looks like you're also rendering the map with GL JS you could test against the GL JS PR)
/cc @ansis

[core] Don't default-show text/icons that depend on the placement of a paired icon/text

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/geometry/LatLngBoundsTest.java

Backports #12616 to release-espresso
----
Closes https://github.com/mapbox/mapbox-gl-native/issues/12549, 
This PR uses unconverted bearing values from core when calculating bounds. 
Requires cherry pick to release-espresso branch.

release-espresso backport: Use unconverted bearing value for latlngbounds calculation

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_textureview_transparent.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/raw/no_bg_style.json

Map style wasn't loading because the style JSON had an erroneous comma in it.  Was exploring this because of https://github.com/mapbox/mapbox-android-demo/pull/820
**Before:**
**After:**

Fix to textureview transparent background testapp activity

---

platform/default/asset_file_source.cpp
platform/default/local_file_source.cpp
src/mbgl/style/expression/is_constant.cpp
test/style/filter.test.cpp

Backports #12630 to release-espresso
----
Recut of https://github.com/mapbox/mapbox-gl-native/pull/12621 so that we can run all of the tests with credentials.

release-espresso backport: Fix out of range exception for string compare

---

platform/android/CHANGELOG.md
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/node/CHANGELOG.md
src/mbgl/annotation/annotation_manager.cpp
test/api/annotations.test.cpp

Fixes issue #12472.
This commit doesn't address the underlying issues that come from symbolAnnotationTree using a slightly lower precision coordinate system than the annotations themselves. Instead, it just puts a small padding around each tile when it queries for tile data, so that symbols right at the tile boundary will be included in both tiles. The rendering/querying code will take care of only displaying one instance.
The padding is in global coordinates, so at higher zoom the padding will be larger in tile units -- this is consistent with precision loss also being greater at higher zoom.
I initially wanted to address this issue by converting the `symbolAnnotationTree` to use a global integer coordinate system that would be consistent with tile unit coordinates up to our max …

[core] Fix querying for annotations near tile boundaries at high zoom.

---

circle.yml

Refs #12485 
This PR stores the release so file with debugging information as circle-ci artifact so we are able to run ndk-stack on them if we receive a bugreport with a native crash.

Store release so files with debugging information

---

circle.yml

Backports #12628 to release-espresso
----
Refs #12485 
This PR stores the release so file with debugging information as circle-ci artifact so we are able to run ndk-stack on them if we receive a bugreport with a native crash.

release-espresso backport: Store release so files with debugging information

---

platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView+IBAdditions.mm

Replaced one more exception name string with a formal symbol as a followup to #12583.

Canonicalize another exception name

---

platform/macos/jazzy.yml

Cherry picks https://github.com/mapbox/mapbox-gl-native/pull/12634 into `release-espresso`

[macos] Rename Guides to Appendices

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Copyedited the changelog entries for iOS map SDK v4.3.0 and macOS map SDK v0.10.0.
/cc @julianrex @captainbarbosa

Copyedit iOS, macOS changelogs

---

platform/macos/docs/pod-README.md

Fixes a typo with the macOS documentation which suggested the pod required was `Mapbox-iOS-SDK` instead of the correct `Mapbox-macOS-SDK`.

[macos] Fix pod name within docs

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Updated change log to reflect security fix introduced in https://github.com/mapbox/mapbox-gl-native/pull/12571

[ios, macos] Update change logs prior to release of v4.3.0

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec

Cherry-picks #12651 into `release-espresso` for ios `4.3.0` and macos `0.10.0`

[ios, macos] Update podspecs for 4.3.0 and 0.10.0 releases. (CP #12651)

---

platform/ios/app/MBXViewController.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapView_Experimental.h

Adds new properties on `MGLMapView` for average frame rate, average frame render duration, and instantaneous frame render duration (useful for producing graphs and benchmarks).
These measurements happen once per frame and therefore shouldn’t be enabled by default. I went with a simple private `BOOL` that’s settable at run-time, but we should profile this to make sure it’s not impacting regular performance. If it is, I’d suppose a compile-time flag would be more appropriate (but less convenient, as external apps would need custom builds).
I also added `MGLMapView_Experimental.h`, which declares read-only properties for `iosapp` but isn’t included as a public header in the SDK.
This is the first time we’re added anything feature flag'y in the iOS SDK, so we should probably discuss …

[ios] Add experimental frame rate measurements to MGLMapView

---

include/mbgl/util/font_stack.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/style/parser.cpp
src/mbgl/text/glyph_manager.cpp
src/mbgl/text/glyph_manager.hpp
src/mbgl/util/font_stack.cpp
test/fixtures/style_parser/text-font.info.json

[core] Evict unused font stacks from GlyphManager

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java

Fixes https://github.com/mapbox/mapbox-gl-native/issues/12049 by obtaining file directories paths on a worker thread as early as possible and caching them.
We are still hitting violations inside the `LibraryLoader` but I'm not sure we'll be able to handle those.

Obtain paths to file directories on a worker thread

---

cmake/mbgl.cmake

Fixes https://github.com/mapbox/mapbox-gl-native/issues/12668

Set GCC_GENERATE_DEBUGGING_SYMBOLS in Xcode

---

src/mbgl/layout/symbol_layout.cpp
src/mbgl/text/collision_index.cpp
src/mbgl/text/collision_index.hpp
src/mbgl/text/placement.cpp

Fixes issue #12461.
- Only implement "avoid edges" in MapMode::Tile since it's no longer relevant in Static or Continuous mode.
- New: Force "avoid edges" to "true" for line labels, since in tile mode they'll always clip poorly at tile boundaries.
- Remove unused "withinPlus0/inside" logic.
In terms of performance, for continuous-rendered maps that don't care, this is an extra boolean-ish check for each symbol at placement time -- should be pretty negligible. For tiled maps, there's an extra check against the tile boundaries but it doesn't involve much extra projection and it might even be a performance win in that it will allow more collision-detection to early-exit near tile boundaries.
Open questions:
cc @ansis @ian29 @lilykaiser

Re-implement "avoid edges" for MapMode::Tile

---

platform/darwin/src/MGLComputedShapeSource.mm
platform/darwin/src/MGLShapeCollection.mm
platform/darwin/src/MGLShapeSource.mm
platform/ios/CHANGELOG.md

Closes https://github.com/mapbox/mapbox-gl-native/issues/11287 by throwing a single warning if any `MGLShapeCollection` contains a shape conforming to `MGLFeature` protocol, as attributes are not copied over into `MGLShapeCollection`s.

[ios, macos] Warn if MGLShapeSource is initialized with MGLShapeCollection

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapViewDelegate.h
platform/ios/test/MGLMapViewDelegateIntegrationTests.swift
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm
platform/macos/src/MGLMapViewDelegate.h
platform/macos/test/MGLMapViewDelegateIntegrationTests.swift

To Do: 
~- [x] Account for MGLShapeCollection, which does not inherit from `MGLMultiPoint`.~ This is not necessary. 
Fixes #10539

Add enabled property to MGLShape

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_runtime_style.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/actions.xml
platform/android/src/android_renderer_frontend.cpp
platform/android/src/android_renderer_frontend.hpp

Closes #12586
- When `AndroidRendererFrontend::update()` called multiple times in a single loop, `updateAsyncTask->send()` will perform nothing, thus `MapRenderer::update()`/`requestRender()` will be coalesced.
- I also added a simple test case to Runtime Style demo. With this change, "Bring water to front" action no more causes flickering.

[android] Make AndroidRendererFrontend to request render once per event loop (#12586)

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/GeoJsonSourceTests.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java
platform/android/src/style/sources/geojson_source.cpp
platform/android/src/style/sources/geojson_source.hpp

Refs https://github.com/mapbox/mapbox-gl-native/issues/8484.
When updating the `GeoJsonSource`, one of the most resources consuming work is the conversion between Android features and `mbgl` ones.
To make the UX better when updating big data sets, this PR introduces `GeoJsonSource#setGeoJsonAsync` which performs the conversion on a worker thread and the returns back to the core flow and notifies the listener when that flow is finished with `OnGeoJsonSourceLoadedListener#onGeoJsonSourceLoaded` at the point where the synchronous method would return.
Examples of improvements:
|   | UI thread time | Overall time | Time saved |
| --- | --- | --- | --- |
| `LineString` geometry ~80k points | 1662ms | 2866ms | **~42%** |
| `FeatureCollection` ~50k features | 204ms | 1169ms | **~83%** |
The trend …

Converting GeoJsonSource features asynchronously

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/src/MGLShapeSource.h
platform/darwin/src/MGLShapeSource.mm
platform/darwin/test/MGLShapeSourceTests.mm
platform/ios/CHANGELOG.md
platform/ios/docs/guides/For Style Authors.md
platform/macos/CHANGELOG.md
platform/macos/docs/guides/For Style Authors.md

Exposes access to
https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-geojson-lineMetrics

[ios, macos] Introduce `MGLShapeSourceOptionLineDistanceMetrics`

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewTransparentBackgroundActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_textureview_transparent.xml

This PR exposes a styleJson configuration MapboxMapOptions and MapView attributes. 
This is usefull for when a user wants to package an their style json in their app.

StyleJson configuration on MapboxMapOptions

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Follow up from https://github.com/mapbox/mapbox-gl-native/pull/11447, where a new offline region definition was introduced. This PR updates the `MapView#setOfflineRegionDefinition(OfflineRegionDefinition definition)` to take this new type into account.

Update MapView OfflineRegionDefintion initialize

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12268 by adding `"collator"` and `"resolved-locale"` expressions support.
This PR also adds an `ExpressionMap` class that can be used to parse future expression that are represented as maps/dictionaries/JsonObjects.

[android] "collator" and "resolved-locale" expressions support

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/attribution/AttributionParser.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/attribution/AttributionParseTest.java

Refs https://github.com/mapbox/mapbox-gl-native/pull/12696#issue-209917037

Replace hardcode telemetry settings string by resources variant

---

circle.yml

These jobs have a low incidence of unique meaningful failures and are mostly just informational, so running them less often frees up relatively scarce CircleCI macOS concurrency while preserving much of their value. This’ll also reduce the impact of occasionally flaky builds, such as #11038.
After merge, `ios-sanitize`, `ios-sanitize-address`, and `ios-static-analyzer` builds will be stop being “required” for GitHub PRs.
/cc @mapbox/maps-ios @kkaefer @jfirebaugh

[build] Run lower-value iOS CircleCI builds as nightlies

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Bumped the podspecs and updated the changelog for 4.4.0-alpha.1
Also included missing 4.0.4 and 4.0.5 changelog entries cc @friedbunny

[ios] Bump podspecs; update changelogs for 4.4.0-alpha.1

---

platform/ios/scripts/document.sh

Alters the `document.sh` script to require the installation of node modules before generating release notes.

[ios] Install node modules in document.sh

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CustomGeometrySource.java
platform/android/src/style/sources/custom_geometry_source.cpp
platform/android/src/style/sources/custom_geometry_source.hpp

Fixes #12508.
Unfortunately, I wasn't able to manufacture any examples that would visualise race conditions, but while testing, I noticed that [converting features](https://github.com/mapbox/mapbox-gl-native/compare/12508-custom-geomerty-source-race?expand=1#diff-4daf8924d97ae9614980001e12d9e450R115) is the operation that takes the longest when setting new tile data. Adding the check if the request has been canceled meanwhile might resolve most race cases.

Check if the custom geometry request has been canceled while converting features

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineGeometryRegionDefinition.java

Refs https://github.com/mapbox/mapbox-gl-native/pull/11447.
Keeps `OfflineGeometryRegionDefinition` fields and constructor from being obfuscated/minified.
/cc @ivovandongen

Keep OfflineGeometryRegionDefinition fields and constructor

---

src/mbgl/text/language_tag.cpp

Removes warning "unknown warning group '-Wtautological-constant-compare', ignored" on iOS build

Added pragma to remove iOS build warning 

---

circle.yml
scripts/notify-slack.sh

This PR adds Slack notifications in the `#apple` channel (`C0ACM9Q2C`) when:
- Nightly iOS builds (added in #12689) fail.
- Release deployment jobs start/finish.
This re-uses the existing Slack webhook (as the `SLACK_WEBHOOK_URL` envvar), so not specifying `SLACK_CHANNEL` will send a message to the default notification channel (`#gl-bots`).
Here’s the general message format:
I’m still interested in implementing @jfirebaugh’s more inclusive GitHub notifications (https://github.com/mapbox/mapbox-gl-native/pull/12689#issuecomment-414733684) at some point — Slack notifications just happened to dovetail with other asks (and are relatively simple to implement).
- https://api.slack.com/docs/message-formatting
- https://api.slack.com/docs/message-attachments
- …

[build] Add Slack notifications for important iOS builds

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Updates the iOS changelog and associated Podspecs for v4.4.0-alpha.2.
Changes since 4.4.0-alpha.1: https://github.com/mapbox/mapbox-gl-native/compare/ios-v4.4.0-alpha.1...master

[ios] Bump podspecs & update changelog for 4.4.0-alpha.2

---

circle.yml

Follows-up on #12750 — when I moved the Slack notification configuration to a checked-in script, I forgot to move the `checkout` step for `ios-release-tag` above the “start” notification.

[build] Fix ios-release-tag slack notification

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/ios/docs/guides/For Style Authors.md
platform/macos/docs/guides/For Style Authors.md

The aftermarket expression for stepping functions is called `mgl_step:from:stops:`, not `mgl_step:withMinimum:stops:`.

Fix typo in “Information for Style Authors” guide

---

.tx/config
platform/android/MapboxGLAndroidSDK/src/main/res/values-es/strings.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values-vi/strings.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values-zh-rCN/strings.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values-zh-rHK/strings.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values-zh-rTW/strings.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml

This pr adds telem window language support for traditional Chinese characters if an Android device is set to the Hong Kong or Taiwan region
Related
- https://github.com/mapbox/mapbox-gl-native/pull/12696
- https://github.com/mapbox/mapbox-gl-native/issues/12708
- https://github.com/mapbox/mapbox-gl-native/pull/12707
cc @macro-shen @chriswu42 @suntony @springmeyer @jmkiley @lloydsheng @1ec5 @jcsg

Adding Traditional Chinese character strings.xml files for HK & Taiwan support

---

platform/android/src/logger.cpp

This method seems to be called in a loop, leading to a local reference table overflow if not explicitly deleted.
See https://github.com/mapbox/mapbox-gl-native/pull/12716#pullrequestreview-150462731

[android] Explicitly delete local JNI references

---

platform/android/build.gradle

AS 3.1.4 was released a couple weeks back, time to bump the gradle tools version.

Bump gradle tools for AS 3.1.4

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/NativeHttpRequest.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/log/Logger.java
platform/android/MapboxGLAndroidSDKTestApp/build.gradle

Closes https://github.com/mapbox/mapbox-gl-native/issues/12779

Add Keep annotations to abstract components

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java

Fixes #12803.
In a `ViewPager` setup, once created fragment doesn't need to be detached when its view is destroyed, meaning, that the out-of-view fragment is re-attached on orientation change but its view is not created, therefore the `MapView` is null. Also, when the fragment is attached, the `onSaveInstanceState` will be called resulting in the `NPE`.

Check if the map is destroyed before saving state in a fragment

---

circle.yml

Closes #10883. The `android-debug-arm-v7` build is our longest-running CI job, largely because it runs tests on Firebase’s device farm (which can take anywhere from 10 to 30 minutes). For Android or core commits we’ve decided this is acceptable, but for changes that don’t touch the Android platform these tests constitute a significant time penalty for no benefit.
To that end:
- Add `[skip firebase]` anywhere in your commit message to avoid running Firebase tests for that commit.
- Firebase tests are automatically skipped if the commit message includes `[ios]`, `[macos]`, some combination thereof, or `[darwin]`.
- Only skips if included in the most recent commit message.
/cc @mapbox/maps-ios @mapbox/maps-android

[build] Skip Android device tests via commit message

---

platform/android/src/style/sources/geojson_source.cpp
platform/android/src/style/sources/geojson_source.hpp

Otherwise it may be prematurely deleted.
Fixes #12712. We may want a different long term fix, but this should adequately address the issue for the upcoming release.

[android] Retain a shared thread pool reference

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Cherry-picked #12792 into the release-frappé branch for iOS map SDK v4.4.0 and macOS map SDK v0.11.0.

Copyedit changelog (release-frappé)

---

platform/ios/framework/Settings.bundle/ar.lproj/Root.strings
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/ar.lproj/Localizable.stringsdict

Added Arabic translations of iOS accessibility strings and the iOS example settings bundle from Transifex.
/ref #12607
/cc @captainbarbosa @RazanQ

Add Arabic settings, accessibility translations

---

platform/darwin/test/MGLMapViewTests.m
platform/ios/CHANGELOG.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/src/MGLMapView.h
platform/macos/src/MGLMapView.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11609.
From initial testing it looks like the port of @1ec5's code from https://github.com/mapbox/mapbox-gl-native/pull/11265 seems to do the trick, but I have a little bit more work to do to make sure this is solid.
Here is a current sample of the result in the `iosapp` test project, where the black line is the antimeridian:

Allow -[MGLMapView convertCoordinateBounds:toRectToView:] to span antimeridian

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java

correct latlngbounds exception message

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/DraggableMarkerActivity.kt
platform/android/scripts/generate-test-code.js

Closes https://github.com/mapbox/mapbox-gl-native/issues/12806, this PR updates the sanity activity test generation script to be Kotlin compatible.
You below can see it generates the DraggableMarkerActivity test correctly.
Due to https://github.com/mapbox/mapbox-gl-native/issues/12712, I will have to disable this test for now though.

Kotlin sanity activity test generation

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/LibraryLoader.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapStrictMode.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapStrictModeException.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/IconFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpIdentifier.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/LocalRequestTask.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyValue.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java

backports #12772 to `release-frappe`

[android] MapStrictMode implementation [frappe-backport]

---

platform/android/src/style/sources/geojson_source.cpp
platform/android/src/style/sources/geojson_source.hpp

Backports #12810 to release-frappe
----
Otherwise it may be prematurely deleted.
Fixes #12712. We may want a different long term fix, but this should adequately address the issue for the upcoming release.

release-frappe backport: [android] Retain a shared thread pool reference

---

platform/darwin/src/MGLMapSnapshotter.h
platform/darwin/src/MGLMapSnapshotter.mm
platform/darwin/src/MGLTypes.h
platform/ios/CHANGELOG.md
platform/ios/Integration Tests/MGLMapViewIntegrationTest.h
platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterSwiftTests.swift
platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterTest.m
platform/ios/Integration Tests/integration-Bridging-Header.h
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/CHANGELOG.md

The completion block passed to `-[MGLMapSnapshotter startWithQueue:completionHandler:]`  should be called regardless of whether the snapshot has finished or not.
This change adds that (along with some tests), calling the completion block with an `NSError` if the snapshot process has not completed. (Alternatively, an exception could be raised and was considered.)
This should hopefully make cases like https://github.com/mapbox/mapbox-gl-native/issues/12336 clearer as to what is happening.

Calls snapshotter (Obj-C) completion block on dealloc if snapshot hasn't finished.

---

platform/android/CHANGELOG.md

PR updates the changelog for v6.5.0-beta.1 release of the Mapbox Maps SDK for Android.

Update changelog for v6.5.0-beta.1

---

platform/android/CHANGELOG.md

Backports #12821 to release-frappe
----
PR updates the changelog for v6.5.0-beta.1 release of the Mapbox Maps SDK for Android.

release-frappe backport: Update changelog for v6.5.0-beta.1

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Changelog entry edits & Podspec updates for v4.4.0-beta.1 of the Maps SDK for iOS.

[ios] Update Podspecs & changelog for v4.4.0-beta.1

---

platform/ios/framework/Settings.bundle/ar.lproj/Root.strings
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/ar.lproj/Localizable.stringsdict

Cherry-picked #12793 into the release-frappé branch for iOS map SDK v4.4.0.

Add Arabic settings, accessibility translations (release-frappé)

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Cherry picks mapbox/mapbox-gl-native#12827 to `release-frappe`.

Cherry pick changelog to release-frappe

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraAnimateTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraEaseTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraMoveTest.java

We recently started to get some spurious/flaky tests runs on firebase related to our camera tests. I believe the change in coalescing updates might be source in combination of us relying on time tests. While we work on callback based tests, let's ignore these tests to unblock other platforms.

Disable flaky camera tests

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/egl/EGLConfigChooser.java

Closes #12829, this update our EGLConfigChooser with an updated isEmulator check. This seem to improve performance of running a map on a emulator (compliant of this in https://github.com/mapbox/mapbox-gl-native/issues/12629#issuecomment-413474282).

Update isEmulator check

---

src/mbgl/text/placement.cpp

Fixes issue #12683.
I tested the case this change was meant to address manually in a sample app that laid out a grid of `allow-overlap: true` symbols across the map. We don't have a good mechanism for automated testing of symbol fading on the native side, although when I do a port to GL JS I plan to write a test that will exercise the JS version of this logic.
cc @ansis @mkrussel77

[core] Mark allow-overlap symbols visible even outside of collision grid

---

include/mbgl/style/expression/interpolator.hpp

Fixes issue #12812.
Using `util::interpolationFactor` handles the case where inputLevels.min == inputLevels.max, so it returns an interpolation factor of "0" instead of dividing by 0.
@nickidlugash, can you build this branch, try it out with your style, and make sure you get the results you expect?
@jfirebaugh, does this look right to you? I'll start work on a regression test for this on the gl js side...

[core] Fix cubic-bezier interpolation for zooms outside stop range.

---

include/mbgl/style/expression/interpolator.hpp
platform/android/CHANGELOG.md
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/node/CHANGELOG.md

CP fix to #12812 and add changelog entries. This PR doesn't bump the GL JS pin for tests on the `release-frappe` branch, so we're depending on manual testing done by @nickidlugash and I.
We want to get this out in `release-frappe` because the next core-styles release is blocked on it.
/cc @julianrex @tobrun @jfirebaugh

[core] Cherry pick cubic-bezier fix

---

platform/android/CHANGELOG.md
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/node/CHANGELOG.md
src/mbgl/text/placement.cpp

Also adds changelog entries.
The equivalent to this change has a regression test on GL JS (see https://github.com/mapbox/mapbox-gl-js/pull/7244), but we don't have a good way to do automated tests for this on native since we can't control the clock during render tests.
/cc @ansis @julianrex @tobrun @lilykaiser

[core] CP "Mark allow-overlap symbols visible even outside of collision grid"

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12711.

[android] "is-supported-script" expression support

---

include/mbgl/style/layers/symbol_layer.hpp
include/mbgl/style/types.hpp
platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Property.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/src/style/layers/symbol_layer.cpp
platform/android/src/style/layers/symbol_layer.hpp
platform/darwin/scripts/style-spec-overrides-v8.json
platform/darwin/src/MGLSymbolStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.mm
platform/darwin/test/MGLSymbolStyleLayerTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/node/CHANGELOG.md
src/mbgl/layout/symbol_layout.cpp
src/mbgl/style/conversion/constant.cpp
src/mbgl/style/conversion/function.cpp
src/mbgl/style/conversion/property_value.cpp
src/mbgl/style/expression/value.cpp
src/mbgl/style/layers/symbol_layer.cpp
src/mbgl/style/layers/symbol_layer_properties.hpp
src/mbgl/style/types.cpp

- Adds symbol-sort-by-y symbol layout property to style spec
- See discussion in https://github.com/mapbox/mapbox-gl-js/issues/7076
- https://github.com/mapbox/mapbox-gl-js/pull/7219 will need to be merged before this

[core] Port symbol-z-order symbol layout style spec property

---

platform/macos/INSTALL.md

This is a followup to #11776 that updates the macOS map SDK’s install-from-source documentation to note the correct build requirements.
/cc @nickidlugash @riastrad @friedbunny

macOS 10.10, Xcode 8 no longer supported

---

README.md

The Cordova & Xamarin plugins have been deprecated. This PR updates the README's`hybrid applications` table to reflect this fact.

[docs] Remove Deprecated Framework Links

---

cmake/sqlite.cmake

The sqlite3 source code has a lot of implicit fallthroughs in case
statements. They are documented with comments but even though gcc
provides options to use these comments to suppress the warnings, that's
not always reliable. For instance, it may fail if an #ifdef follows the
comment or if the comment is within a block scope used for a case.
With gcc version '(Ubuntu 7.3.0-16ubuntu3) 7.3.0' I get warnings similar
to the below:
```
../../../vendor/sqlite/src/sqlite3.c: In function ‘sqlite3_db_status’:
../../../vendor/sqlite/src/sqlite3.c:20251:10: error: this statement may fall through [-Werror=implicit-fallthrough=]
op = SQLITE_DBSTATUS_CACHE_WRITE+1;
```
So disable the implicit falltrhough warnings for that library. Note that
-Wno-error=implicit-fallthrough is not used to keep the build …

[build] Disable implicit fallthrough warnings for sqlite3

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/StringUtils.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/string/UppperLowerCaseTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/render/RenderTestActivity.java
platform/android/config.cmake
platform/android/core-files.txt
platform/android/scripts/run-render-test.py
platform/android/src/jni.cpp
platform/android/src/string_util.cpp
platform/android/src/text/collator.cpp
platform/android/src/text/collator_jni.hpp
platform/android/src/unaccent.cpp

This PR is the first step to remove nunicode from the Mapbox Maps SDK for Android. Removing this c++ library would result in decreasing the overal binary size of the SDK. 
In this PR, we are replacing the nunicode uppercase and lowercase invocations by wiring through jni to leverage the android platform specific `java/lang/String#toUpperCase()` and `jave/lang/String#toLowerCase()` instead.
Note though, we can't remove nunicode yet as it's used for collator expressions (https://github.com/mapbox/mapbox-gl-native/issues/12268). 
@ChrisLoer would it be possible to move that implementaton to [Collator.java](https://developer.android.com/reference/java/text/Collator) in the same way as this PR does for upperCasing/lowerCasing?

Remove nunicode from android binding

---

platform/ios/jazzy.yml
platform/macos/jazzy.yml

[Cherry picks](https://git-scm.com/docs/git-cherry-pick) the commit from https://github.com/mapbox/mapbox-gl-native/pull/12853 to the `release-frappe` branch in preparation of Wednesday's ios-v4.4.0 stable release.

[ios, macos, docs] Move MGLShapeOfflineRegion to offline section 🍒 cherry pick

---

platform/ios/app/MBXViewController.m

I evidently forgot to PR this back in February, but: add a fall-through single-tap to iosapp that toggles the visibility of the navigation bar.

[ios] Add fall-through single tap to iosapp

---

platform/android/CHANGELOG.md

This PR updates the changelog to match the state on `release-frappe` branch.

Update changelog for v6.5.0

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

Closes #12846, Android binding integration of #12842. Configuration of this is done through the constructor of the map object. This is reflected on the Android side by introducing a configuration as part of MapboxMapOptions and an equivalent xml attribute.
I'm not integrating this configuration in the testapp as we don't expose an example that would benefit from this configuration, I manually verified with a debugger that state is correctly initialized. 
cc @ChrisLoer

Add binding integration for cross source collision

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/macos/CHANGELOG.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec

Cherry picking https://github.com/mapbox/mapbox-gl-native/pull/12875 to the `release-frappe` branch.

[ios, macos] Update Podspecs & changelog for 4.4.0 🍒 [cherry pick]

---

package.json
platform/node/CHANGELOG.md

I think we're on track to publish a v4.0.0 package today along with the other SDK releases. 🎉 I will tag and publish once this PR is merged.

[node] v4.0.0

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Cherry-picked cc75530c79e769a989bd2c6d9723aa5e8eec4c6e from #12882 to the release-frappe branch for macOS map SDK v0.11.0.

Fix changelog syntax errors (release-frappé)

---

platform/darwin/src/NSProcessInfo+MGLAdditions.m
platform/macos/CHANGELOG.md

Cast an even wider net than #12140 when trying to detect the helper process that builds the Interface Builder designable when MGLMapView is displayed in a storyboard or XIB. Detecting the helper process is important because it keeps mbgl and the telemetry subsystem from initializing and causing the designable to time out or raise an exception. The helper process has once again been renamed on each platform, according to the Xcode 10 GM seed release notes:
> Some binaries used by Interface Builder have been renamed for better consistency. Instead of
“Interface Builder Cocoa Touch Tool”, “Interface Builder WatchKit Tool”, and “IBAppleTVTool”, they
are now called “IBAgent-[platform]”. (35400833)
Platform SDK | Xcode 9 | Xcode 10 beta 1 | Xcode 10 GM seed
----|----|----|----
iOS | …

Look even more widely for IB designables agent

---

platform/ios/CHANGELOG.md

Updates EventsSDK to patch a crash that happens with offline use.
https://github.com/mapbox/mapbox-events-ios/pull/68

[iOS] Update events library

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Bumps versions for `ios-v4.4.1`, edits the changelog entry for https://github.com/mapbox/mapbox-gl-native/pull/12889, and moves the changelog entry for #12825 (as it wasn’t included in `ios-v4.4.0`).

[ios] Update changelog and podspecs for ios-v4.4.1

---

cmake/mbgl.cmake

Since commit bded6c65d59b ([build] use plain text files for file lists
to simplify integration with other build systems) adding new source
files would not cause cmake to be re-ran since it doesn't automatically
track the plain text files. Fix that by explicitly adding those files to
CMAKE_CONFIGURE_DEPENDS.

[build] Run cmake again when source file lists changes

---

src/mbgl/gl/context.cpp
src/mbgl/gl/context.hpp

Crashes were reported when running debug builds on top of ANGLE. This PR disables said extension on that platform and refactors the vertex array object while at it.
/cc @kkaefer @brunoabinader

Disable debugging extension in ANGLE and refactor vertex array object extension initialization

---

circle.yml

These jobs have constant output and don't need the default 10 minute timeout, so failing sooner (in the event of an npm outage/bug such as #12250, for example) is advantageous for us.
I did this for builds I was familiar with, but other platforms could potentially also benefit from this.
/cc @tobrun @kkaefer @julianrex

[build] Reduce CircleCI timeouts for iOS/macOS builds

---

circle.yml

The `ios-release` build can take longer than 2 minutes to link the framework, so this bumps the no-output-timeout to 5 minutes for that build. Follows up on #12899.
Also fixed links in the release deployment Slack notifications.
/cc @julianrex

[ios, build] Bump timeout for ios-release to 5m; fix Slack link

---

platform/darwin/resources/Base.lproj/Foundation.strings
platform/darwin/src/MGLOfflineStorage.h
platform/darwin/src/MGLOfflineStorage.mm
platform/darwin/test/MGLOfflineStorageTests.mm
platform/default/mbgl/storage/offline_database.cpp
platform/ios/CHANGELOG.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/Base.lproj/Localizable.strings
platform/macos/CHANGELOG.md
platform/macos/macos.xcodeproj/project.pbxproj

[ios, macos] Offline regions merge.

---

src/mbgl/renderer/paint_property_binder.hpp

fix https://github.com/mapbox/mapbox-gl-native/issues/12835

prevent crash when expression evaluates to default, no pattern

---

platform/android/CHANGELOG.md

https://github.com/mapbox/mapbox-gl-native/pull/12920 was merged during the preparation of the release and is missing from the changelog.

Update 6.6.0-alpha.1 changelog to reflect ProGuard changes

---

src/mbgl/gl/context.cpp

Commit 1c53dc9ca8d9 ([core] Refactor vertex array object extension
initialization) changed where the GL renderer string is checked in order
to prevent the vertex array extension initialization in certain
platforms and in doing so made the logging of that string more frequent,
once per context initialization instead of at most once per process.
This is a lot more verbose, specially when running unit tests, so make
sure that string is logged at most once as it was previously.

[core] Don't log GL renderer string on every context initialization

---

src/mbgl/algorithm/update_renderables.hpp
test/algorithm/update_renderables.test.cpp

We optimize our updateRenderable algorithm by breaking ascent when we've already checked a certain tile. So far, we've compared the UnwrappedTileIDs, but they don't include the overscale component. When ascending through overscaled tile IDs, we've stopped the ascent too early, when we should've kept the search going. This resulted in tiles not getting rendered even though they were available.

Don't break ascent in the overscaled tile phase

---

platform/default/sqlite3.cpp

Switch from lambda expression to a named function to prevent this crash on Android:
cc @kkaefer @LukasPaczos

Fix Android crash on SQLite log warning

---

platform/macos/app/Assets.xcassets/Layers/background.imageset/Contents.json
platform/macos/app/Assets.xcassets/Layers/heatmap.imageset/Contents.json
platform/macos/app/Assets.xcassets/Layers/hillshade.imageset/Contents.json

Avoid flipping the background, heatmap, and hillshade icons in macosapp’s Layers sidebar in right-to-left languages.

Avoid flipping some layer icons

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/BaseActivityTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/OnMapReadyIdlingResource.java

We recently seen an increased report of flaky instrumentation tests on CI. This PR changes the way instrumentation tests are initialised by using `findViewById` instead of reflection. The reflection usage for this use-case stems from being able to reflect on the MapboxMap field and was later replaced with MapView for speed. A simpler, more robust way to get MapView can be done with use findViewById instead. This should solve the flaky tests on CI.

Replace reflection setup in instrumentation tests

---

platform/default/mbgl/storage/offline_download.cpp
test/storage/offline_download.test.cpp

When creating a offline region, we've previously only requested the sprite image for the specified resolution. This lead to offline packs not being usable on devices that have a different pixel ratio. We're now requesting both 1× and 2× sprites. Some devices use even higher or fractional pixel ratios. However, we only ever use 1× and 2× sprite images in our requests.

Always request 1× and 2× sprite images for portability

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationCameraControllerTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12953.
Port of https://github.com/mapbox/mapbox-plugins-android/pull/694.

Invalidate camera mode in LocationComponent for gestures initiated changes only if necessary

---

circle.yml
scripts/clang-tools.sh
scripts/environment.js

Backports #12958 to release-frappe
----

release-frappe backport: Compare clang-tidy with merge base instead of master

---

circle.yml
scripts/clang-tools.sh
scripts/environment.js

Backports #12958 to release-espresso
----

release-espresso backport: Compare clang-tidy with merge base instead of master

---

circle.yml

Extends the `[skip firebase]` syntax added in #12776 to the recently added `android-gnustl-arm-v7` CircleCI job from #12192.
/cc @tobrun @kkaefer

[android, build] Add firebase skipping to android-gnustl-arm-v7

---

platform/ios/Integration Tests/MGLCameraTransitionTests.mm
platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterTest.m
platform/ios/ios.xcodeproj/project.pbxproj

This PR moves the check for a "pending test" out of the body of the test, instead running the check before `setup` gets called.
For this to work, it requires that pending tests have the suffix `PENDING`. `xcpretty` also picks this up: pending tests will be distinguished by a `⧖` and `[PENDING]` in the build log on CI.
This should help reduce the number of false positive timing-related test fails (e.g. see https://circleci.com/gh/mapbox/mapbox-gl-native/162451).
I've left the macro in place since it's currently being used by non-integration tests too.

Move "pending test" check into `invokeTest`

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcher.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java

Closes #12260.
This PR eliminates the unnecessary `canceled->idle->started` camera callback loops that occurred during gestures execution by clearing the message queue when movement is restarted and by dispatching `cancel` callback only during the start of first gesture execution and `idle` only during the finish of last.

Remove unnecessary camera callbacks loops

---

platform/android/gradle/dependencies.gradle

Fixes https://github.com/mapbox/mapbox-gl-native/issues/12460.
Updates telemetry dependency from 3.1.5 to 3.2.1.

Update telemetry dependency to 3.2.1

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java

Closes #12724.
The issue surfaced with the introduction of the `GLSurfaceView` - whenever activity containing a surface is paused, the surface releases the EGL context and forces the surface to be recreated upon coming back to the activity, which forces us to redraw the tiles.
This PR sets the `PreserveEGLContextOnPause` flag which tries to hold on to the EGL context when activity is paused, but only if the hardware allows for it. From documentation:
> Whether the EGL context is actually preserved or not depends upon whether the Android device that the program is running on can support an arbitrary number of EGL contexts or not. Devices that can only support a limited number of EGL contexts must release the EGL context in order to allow multiple applications to share the GPU.
Before: …

Preserve GLSurfaceView's EGL context on pause

---

Makefile
platform/ios/DEVELOPING.md
platform/ios/INSTALL.md
platform/ios/scripts/deploy-packages.sh
platform/ios/scripts/package.sh
platform/ios/scripts/publish.sh

- Fixes #12841 by ceasing to publish the static framework in release deployments.
- Deprecates `make ipackage` (and company) in favor of `make iframework` with arguments.
- Improved logging during deployments — less verbosity, more details about file sizes.
It’s still possible to build the static framework by invoking `make iframework FORMAT=static` (and, indeed, it currently appears to succeed).
/cc @mapbox/maps-ios @1ec5

[ios, build] Packaging script improvements

---

circle.yml

Tests are still occasionally timing-out with the Xcode 10 canary job (#12911) so we can’t quite update all of the CI jobs yet, but I’d like to try publishing `ios-v4.5.0-alpha.2` and nightlies/snapshots with Xcode 10 to get some app-integration testing going elsewhere.

[ios, build] Build releases with Xcode 10.0

---

platform/darwin/src/MGLFoundation.h
platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

This PR addresses #12740 and #5489.
Moving UIKit position updates prior to rendering and enabling `CAEAGLLayer.presentsWithTransaction` (introduced in iOS 9) appears to have addressed both these issues.
Running through Instruments show performance hasn't changed dramatically (perhaps even slightly improved), but I'd like to see some additional testing. My main concern is does the user puck behave the same as it used to (not "is it lagging")?
(I'd like to see some additional improvements to how core performs updates, but this is beyond the scope of this fix/PR.)

[ios] Fix for user puck jittering (and annotations lagging)

---

platform/ios/Mapbox-iOS-SDK-static-part.podspec
platform/ios/ios.xcodeproj/project.pbxproj

Fixed build errors in the dynamic+static scheme and `make ipackage` by ensuring that both the dynamic and static targets have the same `DEFINES_MODULE` build setting.
Fixes #11794. Fixes #12339.

Declare that the static framework defines a module

---

platform/darwin/src/MGLRendererConfiguration.h
platform/darwin/src/MGLRendererConfiguration.mm
platform/ios/CHANGELOG.md
platform/ios/docs/guides/Info.plist Keys.md
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/docs/guides/Info.plist Keys.md
platform/macos/src/MGLMapView.mm

[ios, macos] Add crossSourceCollissions property.

---

platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_map_renderer.cpp
platform/qt/src/qmapboxgl_p.hpp

In some scenarios, an update (or a series of) could happen _before_ the renderer frontend is ready, causing the [update parameters to be lost](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/qt/src/qmapboxgl.cpp#L1820). Usually, this is not a problem because after the renderer is ready, further updates are handled just fine, but in cases where there are no more pending updates left, the view is left in a blank state.
To address that, we need to temporarily buffer the last update parameter prior to handling it over to the renderer frontend. We only need the last update parameter as it is self-contained and does not depend on previous updates.

[Qt] UpdateParameters should always be available when rendering

---

platform/darwin/test/MGLOfflineStorageTests.mm

Disables the offline merging test until a fix for the database size is in place.

[ios, macos] Disable offline merge test.

---

platform/darwin/src/MGLMapCamera.h
platform/darwin/src/MGLMapCamera.mm
platform/darwin/src/MGLMapSnapshotter.h
platform/darwin/test/MGLDocumentationExampleTests.swift
platform/darwin/test/MGLMapCameraTests.m
platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/app/MapDocument.m
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/src/MGLMapView.mm

MGLMapCamera can now be expressed in terms of viewing distance. `+[MGLMapCamera cameraLookingAtCenterCoordinate:fromDistance:pitch:heading:]` incorrectly treated the distance as an altitude. Due to backwards compatibility concerns, this method can’t be fixed in place until the next semver-major release. Instead, separate `+cameraLookingAtCenterCoordinate:correctlyFromDistance:pitch:heading:` and `+cameraLookingAtCenterCoordinate:altitude:pitch:heading:` methods have been added, and the original method has been deprecated to head-off continuing confusion.
A `viewingDistance` property has been added to MGLMapCamera. This property is computed from the `altitude` and `pitch` properties, so there isn’t any parallel state to keep track of. The benefit of this approach over #12938 is that there …

Fix MGLMapCamera initialization and viewing distance calculations

---

platform/ios/CHANGELOG.md
platform/ios/Integration Test Harness/Info.plist
platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m
platform/ios/Integration Tests/MGLMapViewIntegrationTest.h
platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
platform/ios/Integration Tests/MGLTestLocationManager.h
platform/ios/Integration Tests/MGLTestLocationManager.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapViewDelegate.h
platform/ios/test/MGLMapViewDelegateIntegrationTests.swift

This PR makes three changes:
- Fixes https://github.com/mapbox/mapbox-gl-native/issues/12203 / https://github.com/mapbox/mapbox-gl-native/pull/11342 by providing a new delegate method that enables the developer to a CGPoint where the user location annotation should be anchored, relative to the map view’s origin after applying the its content insets.
- Deprecates `-[MGLMapView setUserLocationVerticalAlignment:]` and the associated `MGLAnnotationVerticalAlignment` enumeration.
- Exposes `-[MGLMapView updateUserLocationAnnotationView]` and `-[MGLMapView updateUserLocationAnnotationView:animated:]` to programmatically force the user location annotation to update.

[ios] Add delegate method to specify the user location annotation’s position

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt

Closes https://github.com/mapbox/mapbox-gl-native/issues/13004.

Move camera and puck immediately when starting to track and displacement is big

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentOptions.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml

Backports #13011 to release-gazpacho
----
Closes https://github.com/mapbox/mapbox-gl-native/issues/12992.

release-gazpacho backport: Add configuration to change the animation duration multiplier when tracking location

---

src/mbgl/style/parser.hpp
src/mbgl/style/style_impl.cpp
test/style/style.test.cpp

GL Native parses the style transition contents but does not use its value. This change applies the parsed transition, if any, with a fallback to the default transition duration value otherwise.

[core] Read style's transition from parser

---

platform/android/CHANGELOG.md
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/node/CHANGELOG.md
src/mbgl/algorithm/generate_clip_ids_impl.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/tile_pyramid.cpp
test/algorithm/generate_clip_ids.test.cpp

fix #12981 
need to add unit test and possibly render tests

[core] fix flickering caused by incorrect ClipIDs

---

platform/darwin/test/MGLOfflineStorageTests.mm
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/macos.xcodeproj/project.pbxproj

Re-enables the offline merge test. Deletes the previous `barcelona.db` test database.

[ios, macos] Enable offline merge test.

---

platform/ios/src/MGLMapView.mm

Follows-up on https://github.com/mapbox/mapbox-gl-native/pull/12907 and ignores the new warnings from our self-deprecated `MGLMapView.userLocationVerticalAlignment`. 😉 

[ios] Ignore deprecation warnings for MGLMapView.userLocationVerticalAlignment

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

Reverse order of prioritising shape vs marker click handling

---

platform/ios/src/MGLMapView.mm
platform/ios/src/UIDevice+MGLAdditions.m

Fixes #13037. On iOS 10+, `CADisplayLink.preferredFramesPerSecond` uses `0` to indicate “use native refresh rate to determine maximum frames per second”. This property isn’t available in iOS 9, so it’s necessary to avoid passing in `0` on the legacy code path.
Also added support for device-variable FPS in Simulator.

[ios] Fix divide-by-zero when setting FPS on iOS <10

---

platform/ios/src/MGLMapView.mm
platform/ios/src/UIDevice+MGLAdditions.m

Cherry-picks into `release-gazpacho` for `ios-v4.5.0`.
- #13051 — Fix divide-by-zero when setting FPS on iOS <10.
- #13029 — Ignore deprecation warnings for `MGLMapView.userLocationVerticalAlignment`.

[ios] Release gazpacho cherry-picks of #13051 & #13029

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TelemetryDefinition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/gradle/dependencies.gradle

This PR adds a new event to the SDK in the offline manager to help inform offline usage. Please note that it's still a WIP - not all fields are finalized, and tests are missing.
https://github.com/mapbox/mapbox-events-android/pull/193 is required for this PR to land (and build).
/cc: @mapbox/maps-android

[android] Offline event

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapChangeReceiver.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapChangeReceiverTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/MapChangeActivity.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

PR introduces separate callbacks for all the map change events instead of wiring them through the same OnMapChange callback. This avoids iterating all registered listener and limits the invocations of those callbacks for non-related events.
This PR also aligns naming of callbacks to match core naming more closely:
>  old: region is changing vs new: camera is changing 
Todo:
Replaces obsolete closed PR in https://github.com/mapbox/mapbox-gl-native/pull/9498.

Replace OnMapChange with specific callbacks

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java

This PR avoids printing the exception message as:
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.BaseBundle.getBoolean(java.lang.String, boolean)' on a null object reference
at com.mapbox.mapboxsdk.storage.FileSource.getCachePath(FileSource.java:88)
at com.mapbox.mapboxsdk.storage.FileSource$FileDirsPathsTask.doInBackground(FileSource.java:165)
at com.mapbox.mapboxsdk.storage.FileSource$FileDirsPathsTask.doInBackground(FileSource.java:155)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at …
```

Avoid printing exception for valid code execution path

---

platform/android/MapboxGLAndroidSDK/proguard-rules.pro

Closes https://github.com/mapbox/mapbox-gl-native/issues/13088.
See inline comment in code for context. 
cc @klblk @jrgonzalezg

Include mapbox sdk services proguard configuration

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12473, removed catch clause as noted in the issue: 
>  `(T)` is reduced to `(Layer)` at Runtime and it just makes the compiler happy, but changes nothing.  Therefor the catch block will never run.  This method removes some need for the callers to cast, but it will not protect them from CastClassExceptions.
The cast class exception is expected, provides same developer experience as with similar constructs in other libraries as for example ButterKnife.

Remove obsolete catch block in getLayerAs

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java
platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml

Plausible fix for https://github.com/mapbox/mapbox-gl-native/issues/13099, capturing from [this](https://stackoverflow.com/questions/35819290/invalid-drawable-tag-vector#36015208) SO post.  Still need to test this on an Android 4.4 device, don't have access to one atm.

Use appcompat configuration to support vector drawables

---

platform/android/CHANGELOG.md

This PR updates the changelog for the two releases going out today:
- 6.7.0-alpha.1
- 6.6.1

Update changelog for 6.7.0-alpha.1 and 6.6.1

---

include/mbgl/storage/default_file_source.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/src/offline/offline_manager.cpp
platform/android/src/offline/offline_manager.hpp
platform/darwin/src/MGLOfflineStorage.h
platform/darwin/src/MGLOfflineStorage.mm
platform/darwin/test/MGLOfflineStorageTests.mm
platform/default/default_file_source.cpp
scripts/changelog_staging/put-offline-resource.json

This is an attempt at addressing issue https://github.com/mapbox/mapbox-gl-native/issues/13022 by directly exposing the `DefaultFileSource::put` method to the iOS/Android Offline functionality. This PR borrows heavily from @halset's https://github.com/mapbox/mapbox-gl-native/pull/12217, but is smaller in scope in that it's not trying to do bulk insertions (which can now be accomplished with the "mergeOfflineRegion" functionality).
This is a kind of awkward fit with `MGLOfflineStorage` and `OfflineManager` because at least the way we present the interface they're not directly related to the ambient cache (even though under the hood they're managing the same database). But it also felt like overkill to add a whole set of extra "ambient cache" wrapper classes.
@tobrun, I haven't figured out …

Add 'putResourceForURL' for pre-warming ambient cache

---

platform/darwin/test/MGLDocumentationExampleTests.swift
platform/darwin/test/MGLDocumentationGuideTests.swift
platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
platform/ios/test/MGLMapViewLayoutTests.m

5 second timeouts have been intermittently failing on CI for me an others, and it looks like we already use 10 seconds in many places. My concern in making this change is that we're obscuring some regression in loading time, but because the CI network/compute environment is so variable, CI timeouts are probably not a super-effective way to catch performance regressions anyway?
/cc @friedbunny @fabian-guerra @chaupow

[tests, darwin] Standardize on 10 second timeout for map loading

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Release bumps and changelog for `ios-v4.6.0-alpha.1`, plus some corrections of older changelogs.

[ios] Release preparations for 4.6.0-alpha.1

---

include/mbgl/storage/online_file_source.hpp
include/mbgl/storage/resource.hpp
platform/default/mbgl/storage/offline_download.cpp
platform/default/online_file_source.cpp
src/mbgl/storage/resource.cpp
src/mbgl/tile/tile_loader_impl.hpp
test/storage/default_file_source.test.cpp
test/storage/offline_download.test.cpp
test/storage/online_file_source.test.cpp

Working towards targeting https://github.com/mapbox/mapbox-gl-native/issues/12655:
> This issue covers prioritizing all regular requests, i.e. all requests necessary to show the current map view, above offline download request. This should resolve the issue outlined in #11461.
- Add a priority-aware logic to favour "regular" requests over offline requests
- currently implemented by adding two queues in `OnlineFileSource` 
- Set requests made by `OfflineDownload` to low priority
- currently realised by adding a `bool isLowPriority` flag to `Resource`
- currently, offline requests set their resources to low priority by calling `setLowPriority()` [here](https://github.com/mapbox/mapbox-gl-native/pull/13019/files#diff-96708c3e34c0b762818fdb34f5ebe873R56). Would it be better to set the …

[Waiting for review][core] Deprioritize offline downloads

---

platform/darwin/src/MGLOfflineRegion_Private.h
platform/darwin/src/MGLOfflineStorage.mm
platform/darwin/src/MGLShapeOfflineRegion.mm
platform/darwin/src/MGLTilePyramidOfflineRegion.mm

Part II of https://github.com/mapbox/mapbox-gl-native/issues/12751.
Integrates the new offline event into the Mapbox Maps SDK framework, logging an event when a new region is added with`[MGLSharedOfflineStorage addPackForRegion:withContext:completionHandler:]`.
This PR also bumps `mapbox-events-ios` to the current https://github.com/mapbox/mapbox-events-ios/commit/61fca377e82b4cfb5e99feea1f465eff1dabbf4e commit on `master` in order to take advantage of the corresponding new event class and constants.

[ios] Log event when offline pack is created

---

circle.yml

My changes in https://github.com/mapbox/mapbox-gl-native/pull/12496/files have regressed and were added again when restructuring the circle configuration file. having `shell: /bin/bash -euo pipefail` results in running into an unbound variable issue when we try to check if a circle ci variable is availble for an external PR (we don't allow running firebase for those).

Remove shell command when activating google cloud 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

This PR removes our view tree observer setup on the MapView initialisation code. This concept was used in the past to make sure the view was measured and that calls to getWidth and getHeight returned not 0 values. With the introduction of async rendering however we introduced the following:
```java
private void onSurfaceCreated() {
hasSurface = true;
post(new Runnable() {
@Override
public void run() {
// Initialise only when not destroyed and only once
if (!destroyed && mapboxMap == null) {
MapView.this.initialiseMap();
mapboxMap.onStart();
}
}
});
```
Which has the same effect as the ViewTreeObserver setup. It will postpone our setup so components as UiSettings and similar can be initialised with a valid height/width. This change unblocks showing a MapView in a RecyclerView when the item …

Remove view tree observer

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyValue.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/types/Formatted.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/types/FormattedSection.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillExtrusionLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HeatmapLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs
platform/android/MapboxGLAndroidSDKTestApp/src/main/assets/streets.json
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java
platform/android/core-files.txt
platform/android/src/conversion/constant.cpp
platform/android/src/jni.cpp
platform/android/src/style/formatted.cpp
platform/android/src/style/formatted.hpp
platform/android/src/style/formatted_section.cpp
platform/android/src/style/formatted_section.hpp
platform/android/src/style/position.cpp

Refs https://github.com/mapbox/mapbox-gl-native/pull/12624, exposes `format` expression on Android.
Setting the `text-field` using the expression, or plain text, works as expected, however, getting the `text-field` property back from core reveals a couple of issues:
- Plain text is returned as expected.
- Any expression, other than `format`, is returned wrapped by `format` expression. This includes tokens (which are beforehand converted from plain text to expressions and this is expected).
- When value is passed initially as the `format` expression, it's being returned as `String`, which is expected because of [this implementation](https://github.com/mapbox/mapbox-gl-native/pull/12624/files#diff-dc7d81f6247193e64e085c48fc54e29cR33).
Currently, above issues cause a bunch of tests to fail. …

Format expression Android bindings

---

include/mbgl/util/geo.hpp
scripts/changelog_staging/invalid-latlngbounds.json

Fixes https://github.com/mapbox/mapbox-gl-native/issues/12797
The thinking here is that 180 and 360 are special values that do not need to be wrapped. In the case of #12797 `unwrapForShortestPath` was causing a bug because `-180` was being converted to `180` and confining the viewport to the antimeridian when it should have been possible to scroll horizontally around the world. 
TODO:

[core] Avoid wrapping longitude values of exactly 180 and 360 (#12797)

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/LocalRequestTask.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/NativeHttpRequest.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/log/Logger.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/log/LoggerDefinition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CustomGeometrySource.java
platform/android/gradle/dependencies.gradle

Java 8 removal

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CustomGeometrySource.java

[android] Change CustomGeometrySource() signature to be Kotlin friendly

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java

Refs https://github.com/mapbox/mapbox-gl-native/issues/12275. We are deprecating the support for `ZoomButtonsController` and it's going to be completely dropped with the next semver major release.

Deprecated ZoomButtonsController support

---

include/mbgl/style/layer.hpp
include/mbgl/style/layers/background_layer.hpp
include/mbgl/style/layers/circle_layer.hpp
include/mbgl/style/layers/custom_layer.hpp
include/mbgl/style/layers/fill_extrusion_layer.hpp
include/mbgl/style/layers/fill_layer.hpp
include/mbgl/style/layers/heatmap_layer.hpp
include/mbgl/style/layers/hillshade_layer.hpp
include/mbgl/style/layers/layer.hpp.ejs
include/mbgl/style/layers/line_layer.hpp
include/mbgl/style/layers/raster_layer.hpp
include/mbgl/style/layers/symbol_layer.hpp
include/mbgl/util/immutable.hpp
platform/android/src/style/layers/layer.cpp
platform/android/src/style/layers/layers.cpp
platform/node/src/node_map.cpp
platform/qt/src/qmapboxgl.cpp
src/mbgl/style/layer.cpp
src/mbgl/style/layers/background_layer.cpp
src/mbgl/style/layers/circle_layer.cpp
src/mbgl/style/layers/custom_layer.cpp
src/mbgl/style/layers/fill_extrusion_layer.cpp
src/mbgl/style/layers/fill_layer.cpp
src/mbgl/style/layers/heatmap_layer.cpp
src/mbgl/style/layers/hillshade_layer.cpp
src/mbgl/style/layers/layer.cpp.ejs
src/mbgl/style/layers/line_layer.cpp
src/mbgl/style/layers/raster_layer.cpp
src/mbgl/style/layers/symbol_layer.cpp
src/mbgl/style/style_impl.cpp

The `style::Layer` class now exposes all the properties contained at `style::LayerImpl`.
This allowed to drop `style::Layer::accept()` method usage, avoid the repeated generated code
and thus save some binary size.
This patch is a part of the layers modularization effort.

Consolidate `style::Layer` properties API

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapChangeReceiver.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/utils/StyleChangeIdlingResource.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/BulkMarkerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/MapFragmentActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/SupportMapFragmentActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewDebugModeActivity.java

Fixes a small regression introduced by the https://github.com/mapbox/mapbox-gl-native/pull/13133 - when requesting a new style before the drawing surface is initialized, before, we were relying on `NativeMapView` being created after the view hierarchy is established, which means, that calls like [`mapView#setStyleUrl`](https://github.com/mapbox/mapbox-gl-native/blob/7a9461a8d439458b18656ecfb839923adc5f0e9b/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java#L79) done in the `#onCreate` would add the style to the `MapboxMapOptions`, because `NativeMapView` was still `null`. Now, we are initializing the `NativeMapView` immediately, which means that calling `mapView#setStyleUrl` would start loading the style instantly …

Fix OnMapReady delivery when a new style is requested before the map is initialized

---

platform/android/build.gradle

While working on setting up android maps sdk with android studio (v.3.2) i ran on the gradle config problem producing the following: 
```
Failed to resolve: support-v4
Open File
Failed to resolve: extensions
Open File
Failed to resolve: support-vector-drawable
Open File
Failed to resolve: livedata-core
Open File
Failed to resolve: runtime
Open File
Failed to resolve: common
Open File
Failed to resolve: viewmodel
Open File
Failed to resolve: monitor
Open File
Failed to resolve: extensions
Open File
Failed to resolve: support-vector-drawable
Open File
Failed to resolve: livedata-core
Open File
Failed to resolve: runtime
Open File
Failed to resolve: common
Show in File
Failed to resolve: viewmodel
Open File
```
I was able to resolve this problem by switching the order in which repositories …

[android] Fix order in which repos are being synced

---

circle.yml

Follows-up on #12993 to re-add the “Show ccache statistics” step to CircleCI jobs.
/cc @kkaefer

[build] Show ccache stats on CircleCI again

---

platform/darwin/src/MGLLoggingConfiguration.h
platform/darwin/src/MGLLoggingConfiguration.m
platform/darwin/src/MGLLoggingConfiguration_Private.h
platform/ios/app/MBXAppDelegate.m
platform/ios/core-files.txt
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/ios/src/Mapbox.h
platform/macos/core-files.txt
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/src/MGLMapView.mm
platform/macos/src/Mapbox.h

Logging is a tool that has been sub-utilized in the iOS maps sdk. The current pr is an effort to improve the communication between the developers and the SDK.
The goals for this PR are:
~~- [ ] Enable performance measure.~~
The current API introduces `MGLLogging` as a singleton class with two configurable properties: `loggingLevel` which will be utilized as a reference point to enable logging, this property allows different levels of verbosity where each level includes previous so then the highest level of verbosity comes when is set to `MGLLoggingLevelFault`, and `handler` which is a block handler for the messages. In case that developers wants to connect their current logging infrastructure they will have to set this property with their respective implementation.

Mapbox maps SDK for iOS custom logging.

---

platform/macos/app/Assets.xcassets/Layers/fill-extrusion.imageset/Contents.json
platform/macos/app/Assets.xcassets/Layers/fill-extrusion.imageset/fill-extrusion.pdf
platform/macos/app/StyleLayerIconTransformer.m
platform/macos/app/resources/fill-extrusion.svg

The Layers sidebar in macosapp now adorns fill extrusion layers with 3D boxes instead of whitespace.
Fixes #11755.

Add icon for fill extrusion layers to macosapp

---

platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Equate the nullary (`FOO(…)`) and unary (`FOO:(…)`) forms of vararg-style aftermarket expression functions such as `MGL_FUNCTION` when converting them to JSON objects.
Fixes #13026.

Fix crash on nullary vararg expression function

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Fixes https://github.com/mapbox/mapbox-gl-native/issues/13207.

Deliver onMapReady only at the end of the initialization block

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PressForMarkerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/MaxMinZoomActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesPropertiesActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QuerySourceFeaturesActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/DynamicInfoWindowAdapterActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/InfoWindowActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationMapChangeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DoubleMapActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/DraggableMarkerActivity.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/ZoomFunctionSymbolLayerActivity.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12011.

Option to consume map clicks, consuming location clicks

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java
platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_ab_back.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_camera_position.xml

Closes https://github.com/mapbox/mapbox-gl-native/issues/13217, Cherry picks solution from https://github.com/mapbox/mapbox-gl-native/pull/13219 + adds a simple example to harden against regressions and replaces tinting by ImageViewCompat equivalent. 
cc @philemonmerlet

Add Fragment Activity setup to testapp, fix app compat requirement

---

platform/ios/INSTALL.md
platform/ios/scripts/release-notes-github.md.ejs

Fixes #6235. It’s now possible to consume pre-release builds via both CocoaPods and Carthage.

[ios] Update pre-release installation instructions

---

.github/stale.yml

It was not suppose to comment when marking issues as stale, but rather just close them.
There is not staleComment, the correct is markComment.

[build] Fix stale bot

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineGeometryRegionDefinition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionDefinition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineTilePyramidRegionDefinition.java

[android] consolidated OfflineRegionDefinitions

---

platform/ios/core-files.txt
platform/ios/ios.xcodeproj/project.pbxproj

Updates submodule to the latest release. https://github.com/mapbox/mapbox-events-ios/releases/tag/v0.7.0
I don't think a changelog addition is necessary.

[iOS] Update mobile events submodule

---

platform/macos/src/MGLMapView.mm

This is a followup to #13212 that fixes an issue where the `mbgl::CameraOptions`’ heading was misinterpreted as going counterclockwise instead of clockwise. I had removed the redundant negative sign from the iOS implementation but accidentally left it in the macOS implementation.
/cc @julianrex @friedbunny

Fix sign flip in programmatic camera rotation

---

include/mbgl/style/layer.hpp
include/mbgl/style/layers/background_layer.hpp
include/mbgl/style/layers/circle_layer.hpp
include/mbgl/style/layers/fill_extrusion_layer.hpp
include/mbgl/style/layers/fill_layer.hpp
include/mbgl/style/layers/heatmap_layer.hpp
include/mbgl/style/layers/hillshade_layer.hpp
include/mbgl/style/layers/layer.hpp.ejs
include/mbgl/style/layers/line_layer.hpp
include/mbgl/style/layers/raster_layer.hpp
include/mbgl/style/layers/symbol_layer.hpp
src/mbgl/style/conversion/layer.cpp
src/mbgl/style/layer.cpp
src/mbgl/style/layers/background_layer.cpp
src/mbgl/style/layers/circle_layer.cpp
src/mbgl/style/layers/fill_extrusion_layer.cpp
src/mbgl/style/layers/fill_layer.cpp
src/mbgl/style/layers/heatmap_layer.cpp
src/mbgl/style/layers/hillshade_layer.cpp
src/mbgl/style/layers/layer.cpp.ejs
src/mbgl/style/layers/line_layer.cpp
src/mbgl/style/layers/raster_layer.cpp
src/mbgl/style/layers/symbol_layer.cpp

This patch introduces the initial implementation of
- A `LayerFactory` abstract class that creates `style::Layer` instances of
a certain layer type (line, hillshade, round, ..)
- A singleton `LayerManager` class, which is responsible for initializing
the `LayerFactory` instances and forwarding the `create()` calls to the
corresponding factory.

Introduce the style::Layer factory classes

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Cherry-pick #13248 to `release-horchata` for `ios-v4.6.0-beta.1`.
/cc @julianrex

[ios] Prepare for 4.6.0-beta.1 (release-horchata)

---

CMakeLists.txt
appveyor.yml

clcache is similar to ccache but for microsoft compilers. Using it should result in faster builds.

Use clcache to speed up windows builds

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraAnimateTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraEaseTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraMoveTest.java

Refs https://github.com/mapbox/mapbox-gl-native/pull/12822.
Reworks camera tests to use cancelable callback instead of delay loops.

Re-enable camera tests

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/TestConstants.java

Because our camera animation tests are mainly performed on high zoom levels, we need to increase the acceptable delta of the final camera position to decrease not-meaningful test failures. The precision of the transformation should not be a concern on the Android side of the test suite.

Increase result's delta in camera animation tests

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CustomGeometrySource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CustomGeometrySourceOptions.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/12009.

Improved CustomGeometrySource constructor typing

---

platform/darwin/src/MGLShapeOfflineRegion.mm
platform/darwin/src/MGLTilePyramidOfflineRegion.mm

This PR changes the `styleURL` event attribute value to a `NSString` (or `NSNull`)  to avoid a JSON serialization crash in https://github.com/mapbox/mapbox-events-ios/blob/ffda849352a85aa3fd72cda046d37b5db6693e8c/MapboxMobileEvents/MMEAPIClient.m#L220

Changed event attributes to be JSON serialization friendly.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/BaseActivityTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/OnMapReadyIdlingResource.java

This PR fixes a rare case scenario that when `MapView#getMapAsync` would be called precisely between style loaded callback and surface creation, then, `null` would've been delivered in the `OnMapReady` callback. This was causing unclear test timeouts, improved that with an assertion instead.
/cc @tmpsantos

Deliver OnMapReady only if MapboxMap is not null

---

package.json

`createInstallationToken` endpoint (used for publishing the binary size checks) had a breaking change and this update uses the new endpoint

update octokit version

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Fixes https://github.com/mapbox/mapbox-gl-native/issues/13287.
Targets `release-horchata` only, as the API has been already removed on `master`.

Reintroduce OnMapChange invocation

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/BackgroundLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillExtrusionLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HeatmapLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HillshadeLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RasterLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs

Fixes https://github.com/mapbox/mapbox-gl-native/issues/13284.

Verify if `text-field` is not null before performing compatibility operations

---

platform/darwin/src/MGLAttributionInfo.mm

This PR addresses a bad access exception with `MGLMapSnapshotter` on iOS 8. Per [Apple docs](https://developer.apple.com/documentation/foundation/nsattributedstring/1524613-initwithdata):
> The HTML importer should not be called from a background thread (that is, the options dictionary includes NSDocumentTypeDocumentAttribute with a value of NSHTMLTextDocumentType). It will try to synchronize with the main thread, fail, and time out. Calling it from the main thread works (but can still time out if the HTML contains references to external resources, which should be avoided at all costs). The HTML import mechanism is meant for implementing something like markdown (that is, text styles, colors, and so on), not for general HTML import.
I've only seen this issue on iOS 8 so far, but will open …

[iOS] Move creation of attributed string to global queue

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapChangeReceiver.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapChangeReceiverTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/BackgroundLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillExtrusionLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HeatmapLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HillshadeLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RasterLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs

Backports #13291 and #13290 to `release-horchata`.

Backport #13291 and #13290 to horchata

---

src/mbgl/util/url.cpp
test/util/url.test.cpp

Noticed that toLowerHex does not produce low case hex sequences, therefore, some of the benchmark tests are failing, as the [cache database](https://github.com/mapbox/mapbox-gl-native/blob/master/benchmark/fixtures/api/cache.db) contains lower case sequences.

[core] Change toLowerHex to produce lower hex sequences

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/13279, noted two issues:
- `getMapAsync(null)`, while this isn't a valid construct it can still occur when consuming the library from Java.
- calling `mapboxMap#setStyleJson` from OnMapReady resulted in a stackoverflow which cause was invoking OnMapReady constantly with each `setStyleJson` invocation. 
Wasn't able to quickly write regressions tests around this as our test harness is already in a resumed state.

Handle null getMapAsync invocations, deliver onMapReady once

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java

Resolves #12830 by updating the API ref docs' code snippet examples. I manually copy/pasted each Expression method's code snippet into an activity to make sure that there were no errors, missing parenthesis, or conflicts. There were 158 methods to check. This was....not fun. Anyways, should be good to go here @mapbox/maps-android

Android Expression javadoc code snippet tweaks

---

platform/android/CHANGELOG.md

Cherry-pick of https://github.com/mapbox/mapbox-gl-native/pull/13308 to release branch.

Update changelog for v6.7.0 and prior 6.6.x releases

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Cherry-picks #13312 to `release-horchata` for `ios-v4.6.0`.

[ios] Prepare for ios-v4.6.0 (release-horchata)

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/OnMapReadyCallback.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/OnMapReadyIdlingResource.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewsInRectangleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraAnimationTypeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraAnimatorActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/GestureDetectorActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/MaxMinZoomActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/ScrollByActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/espresso/DeviceIndependentTestActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/espresso/EspressoTestActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/MapFragmentActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/SupportMapFragmentActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/imagegenerator/SnapshotActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/DynamicInfoWindowAdapterActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationMapChangeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationModesActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/ManualLocationUpdatesActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/BottomSheetActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/LatLngBoundsForCameraActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GradientLineActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewDebugModeActivity.java

This PR adds `@NonNull` to the `OnMapReady` parameter. This improves consumption of the SDK in Kotlin by removing the nullity on MapboxMap (eg. mapboxMap? becomes mapboxMap). This change breaks client builds if they use Kotlin so this is a semver change.

Annotate onMapReady with @NonNull

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec
scripts/changelog_staging/expression-string-coercion.json
scripts/changelog_staging/format-expression.json
scripts/changelog_staging/invalid-latlngbounds.json
scripts/changelog_staging/per-source-collision.json
scripts/changelog_staging/put-offline-resource.json
scripts/changelog_staging/queryrenderedfeatures-with-icon-rotate.json

Prepared for macOS map SDK v0.12.0. (Belatedly) copyedited the changelog entries for iOS map SDK v4.5.0–v4.6.0 and macOS map SDK v0.12.0. Deleted the changelog entry staging folder in preparation for the I releases.

macOS map SDK v0.12.0

---

platform/darwin/src/MGLOfflineStorage.h
platform/darwin/src/MGLOfflineStorage.mm
platform/darwin/test/MGLOfflineStorageTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Renamed `-[MGLOfflineStorage putResourceWithUrl:data:modified:expires:etag:mustRevalidate:]` to `-[MGLOfflineStorage preloadData:forURL:modificationDate:expirationDate:eTag:mustRevalidate:]` to conform to [Cocoa naming guidelines](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html) in Objective-C and [Swift API design guidelines](https://swift.org/documentation/api-design-guidelines/) in Swift.
/ref #13119
/cc @fabian-guerra @ChrisLoer

Rename ambient cache prewarming method

---

platform/macos/CHANGELOG.md

Some headers were incorrectly at level 1, resulting in a jazzy docset cover page that included blurbs from too many releases. I applied this change locally before generating the docset in 49cd236fed4a7e0e960f039d53ad041b4d4286db.
/cc @fabian-guerra @friedbunny

Fix syntax errors in macOS changelog

---

appveyor.yml

And stop breaking the build every time AppVeyor updates Qt on their
images.

[qt][build] Use the latest version of Qt available on AppVeyor

---

platform/darwin/src/MGLAttributionInfo.mm

Continues discussion from https://github.com/mapbox/mapbox-gl-native/pull/13298 in order to add the fix to `master`. 
This PR addresses a bad access exception with `MGLMapSnapshotter` on iOS 8. Per [Apple docs](https://developer.apple.com/documentation/foundation/nsattributedstring/1524613-initwithdata):
> The HTML importer should not be called from a background thread (that is, the options dictionary includes NSDocumentTypeDocumentAttribute with a value of NSHTMLTextDocumentType). It will try to synchronize with the main thread, fail, and time out. Calling it from the main thread works (but can still time out if the HTML contains references to external resources, which should be avoided at all costs). The HTML import mechanism is meant for implementing something like markdown (that is, …

[ios] Address bad access exception in `MGLAttributionInfo`

---

circle.yml

Migrate to new Docker images built in https://github.com/mapbox/mbgl-ci-images/pull/31
This is a preparatory PR for moving some checks to newer compilers and testing multiple node versions.

Use updated docker images

---

include/mbgl/storage/online_file_source.hpp
platform/android/src/http_file_source.cpp
platform/darwin/src/http_file_source.mm
platform/default/http_file_source.cpp
platform/default/mbgl/storage/offline_download.cpp
platform/default/mbgl/storage/offline_download.hpp
platform/default/online_file_source.cpp
platform/qt/src/http_file_source.cpp
src/mbgl/storage/http_file_source.hpp
test/src/mbgl/test/fake_file_source.hpp
test/src/mbgl/test/stub_file_source.hpp
test/storage/offline_download.test.cpp
test/storage/online_file_source.test.cpp

Working towards https://github.com/mapbox/mapbox-gl-native/issues/13130
> Proposal
> Instead of a static function in HTTPFileSource the number of concurrent requests should be a member variable in either FileSource or OnlineFileSource.

[core] Refactor the number of concurrent http requests when downloading files

---

platform/darwin/src/MGLLoggingConfiguration.m
platform/darwin/test/MGLAttributionInfoTests.m
platform/ios/CHANGELOG.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/CHANGELOG.md
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/src/MGLMapView.mm

~~The iOS map SDK’s bundle identifier is now `com.mapbox.MapboxGL`, whether in the form of a static or dynamic framework. This is also consistent with the macOS map SDK. The previous bundle identifier, `com.mapbox.sdk.ios`, was unusual in that it named the platform.~~
The iOS and macOS map SDKs now share the same bundle identifier, `com.mapbox.Mapbox`, for consistency with the product name and module name that they already share in common. The logging subsystems added in #13235 also have this same identifier. The previous bundle identifier on iOS, `com.mapbox.sdk.ios`, was unusual in that it named the platform. Meanwhile, the previous bundle identifier on macOS, `com.mapbox.MapboxGL`, would’ve collided with iosapp’s bundle identifier to produce an error on installation.
Split out from …

Harmonize iOS, macOS map SDK bundle identifiers

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Closes https://github.com/mapbox/mapbox-gl-native/issues/11415.
Currently when a camera animation is triggered programmatically, if the `zoomEnabled` / `pitchEnabled` / `scrollEnabled` / `rotateEnabled` are all set to `NO`/`FALSE`, user interaction causes the transition to stop. This PR reverses that decision, so that a programmatic camera transition will continue if the above four properties are set to `NO`/`FALSE`

[ios] Don't pause camera animations if zoom/pitch/rotate/scroll are disabled

---

.github/CODEOWNERS

This may be short-lived, but still could be useful - and I think it's worth an experiment. I've kept it deliberately light too.
I didn't assume to add an Android/Qt/etc sections - but feel free to add.
/cc @chloekraw @1ec5

Enable CODEOWNERS for iOS/macOS/Darwin directories.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/BackgroundLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillExtrusionLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HeatmapLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HillshadeLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/RasterLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillExtrusionLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HeatmapLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs

Fixes https://github.com/mapbox/mapbox-gl-native/issues/13404.

Getting a constant layer filter fix

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java

Fixes an issue where the alpha value of the `ColorInt` -> `String` conversion would be converted with a system locale instead of the fixed one.

Use locale sensitive DecimalFormat for color alpha conversion

---

platform/darwin/src/MGLMapSnapshotter.h
platform/darwin/src/MGLMapSnapshotter.mm
platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapView_Private.h

Addresses #13120 (random crashes on app termination), by tearing down the underlying core C++ objects when receiving `UIApplicationWillTerminateNotification`.
This PR also saves the state of the `camera`, `debugMask` and `styleURL` during tear-down, so that they can be used when saving state (e.g. in `iosapp`
https://github.com/mapbox/mapbox-gl-native/blob/f4e5d842cbe15915a8854525ca928a914ba29eef/platform/ios/app/MBXViewController.m#L290)
In addition, this PR changes accesses to the underlying `mbgl::Map` to go via a method (`-(mbgl::Map &)[MGLMapView mbglMap]`) that raises an exception if the map is `NULL`.
This PR does *not* introduce `UIStateRestoring` conformance (see https://github.com/mapbox/mapbox-gl-native/issues/3660), but could be viewed as a prelude to that work.

[ios] Added teardown of core objects when receiving UIApplicationWillTerminateNotification

---

Makefile

Long time due PR, to improve feedback given by unit test while running it though:
> make run-android-unit-test
This PR adds the info flag so output goes from:
to:
cc @mapbox/android as this is useful for other android projects with running unit tests on CI.

use --info argument to show details during test run

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyValue.java

Hard to track down value/expression issues currently when they are not being named.

[android] Add specific name logging in failure scenarios of PropertyValue

---

include/mbgl/style/transition_options.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp

This PR:
- Lets property evaluation transitions use the transition duration, if set, with fallback to the default value (300ms) otherwise;
- Lets label placement transitions use the transition duration, if set, with fallback to the default value (300ms) otherwise;
- Exposes a boolean flag that allows manual override of label placement transitions, allowing the client to disable transitions for that particular case.
@ChrisLoer @ansis please review.

Let placement transitions use the transition duration, if set, and allow disabling them entirely

---

platform/android/CHANGELOG.md
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
src/mbgl/storage/resource.cpp
test/storage/resource.test.cpp

Fixed an issue where the `{prefix}` token in tile URL templates was evaluated incorrectly when requesting a source’s tiles. The prefix ended up being one character long, even though it should be two characters long ([compare with GL JS](https://github.com/mapbox/mapbox-gl-js/blob/cedefd66f6519f20b9f73a1389e02afa868ca39f/src/source/tile_id.js#L37)):
https://github.com/mapbox/mapbox-gl-native/blob/53bbf9d6991c1eddfa141ddcfb4b7252874e46ec/platform/darwin/docs/guides/Tile%20URL%20Templates.md.ejs#L100-L102
This appears to have been an attempt to use the `std::string` fill constructor, but it ended up creating a one-character-long string consisting of [␂](https://en.wikipedia.org/wiki/^B) and attempting to overwrite the null terminator, which resulted in a one-character-long prefix and a tile …

Fix too-short {prefix} evaluation

---

platform/darwin/src/MGLFoundation.h
platform/darwin/src/MGLFoundation_Private.h
platform/darwin/src/MGLRendererConfiguration.h
platform/darwin/src/MGLRendererConfiguration.mm
platform/darwin/test/MGLRendererConfigurationTests.mm
platform/ios/CHANGELOG.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/CHANGELOG.md
platform/macos/macos.xcodeproj/project.pbxproj

Addresses #13155 - adds support for setting `MGLCollisionBehaviorPre4_0` via `NSUserDefaults.standardUserDefaults`.
Setting via `NSUserDefaults` takes priority over the value in the application's Info.plist file.

[ios] Adds support for MGLCollisionBehaviorPre4_0 in NSUserDefaults

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterActivity.java
platform/android/src/snapshotter/map_snapshotter.cpp
platform/android/src/snapshotter/map_snapshotter.hpp
platform/darwin/src/MGLMapSnapshotter.mm
platform/default/mbgl/map/map_snapshotter.cpp
platform/default/mbgl/map/map_snapshotter.hpp
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

The core part of this PR exposes a "local ideograph font family" option on `MapSnapshotter` and passes it through to the underlying renderer.
The darwin implementation picks up the `localFontFamilyName` that's already read out of the application bundle by `MGLRendererConfiguration`. I tested this manually in the macosapp, using a breakpoint to ensure that local fonts were being used during snapshot generation.
The Android implementation is more of a guess: I added `localIdeographFontFamily` as an option in `MapSnapshotter::Options` and hooked it up to the underlying core snapshotter. This seemed closest to the way the rest of the configuration works, but it is unfortunate that it requires the user to pay attention and set the value every time they create a `MapSnapshotter`. This might be …

[darwin, android, core] Expose "local ideograph font family" in map snapshotters

---

src/mbgl/tile/vector_tile_data.cpp
test/tile/vector_tile.test.cpp

As pointed out by @amatissart [here](https://github.com/mapbox/mapbox-gl-native/pull/13349#issuecomment-441398537), the semantics for obtaining a vector tile feature data has changed after geometry.hpp replaced its optional usage. This makes `VectorTileFeature::getValue()` always return a value (using null_value_t when a value is not found) instead of a `nullopt`. Because we use a [`operator-bool`-based check](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/expression/compound_expression.cpp#L344) for evaluating "has", it is now always returning true for vector tile sources.
Unfortunately we did not catch this as all our expression tests are run using GeoJSON sources.
/cc @julianrex @osana as this is a regression fix for both `ios-v4.7.0-alpha.{1,2}` and …

[core] Fix VectorTileFeature::getValue() semantics after geometry@v1.0.0

---

include/mbgl/map/camera.hpp
src/mbgl/map/transform.cpp
test/map/transform.test.cpp

CameraOptions' anchor point is useful when zooming, rotating or pitching, as makes sure the location below the given screen coordinate always stays visible. Because it moves the map center internally, it cannot be used together with the camera center, which also moves the map center.
This means that these values are mutually exclusive. If both values are set, the anchor gets ignored.
Also took the opportunity to clean up `Transform` codebase, removing redundant functions that could be replaced with `{ease,jump}To`.
/cc @asheemmamoowala @1ec5 for review.
Fixes #13338

Camera's center and anchor points are mutually exclusive

---

.github/CODEOWNERS
platform/ios/docs/guides/Info.plist Keys.md

Updated to reference support for `MGLCollisionBehaviorPre4_0` via `NSUserDefaults.standardUserDefaults`.
See https://github.com/mapbox/mapbox-gl-native/pull/13426.
Also adds @mapbox/docs to the CODEOWNERS file for the docs paths.

Updated Info.plist docs.

---

platform/darwin/docs/guides/Predicates and Expressions.md

Closes #13113 
This PR adds a link to the `NSExpression(MGLAddition)` documentation from the `Predicates and Expressions` guide. This small change is to improve the discoverability of the `NSExpression(MGLAddition)` documentation, which often goes overlooked because it sits in a generic 'other categories' section of the documentation.

[ios][documentation] link expression guide to NSExpression(MGLAdditions)

---

benchmark/util/tilecover.benchmark.cpp
include/mbgl/map/camera.hpp
include/mbgl/map/map.hpp
platform/glfw/glfw_view.cpp
platform/ios/src/MGLMapView.mm
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
test/map/transform.test.cpp
test/style/source.test.cpp
test/util/tile_cover.test.cpp

A follow-up to #13445, this PR refactors `Transform` to reduce its API surface.

Transform cleanup

---

platform/ios/app/MBXFrameTimeGraphView.h
platform/ios/app/MBXFrameTimeGraphView.m
platform/ios/app/MBXViewController.m
platform/ios/app/Main.storyboard
platform/ios/ios.xcodeproj/project.pbxproj

~WIP~ hackasprint project. Adds a frame duration graph view to iosapp, similar to Android’s built-in [Profile GPU Rendering graph](https://developer.android.com/studio/profile/inspect-gpu-rendering).
- **Grey line**: the render budget — varies based on maximum target frame rate.
- **Green bar**: <75% of the render budget.
- **Orange bar**: >75% of the render budget, but still within the target.
- **Red bar**: the frame render time exceeded the budget.

[ios] Add frame duration graph view for performance debugging

---

CMakeLists.txt
bin/offline.cpp
circle.yml
cmake/mbgl.cmake
cmake/sqlite.cmake
cmake/test.cmake
package.json

- GCC 6 => 8
- Clang 4 => 7
- Combine Address and Undefined sanitizers to reduce build count

Use newer compiler versions for some builds

---

include/mbgl/style/layer.hpp
platform/android/src/style/layers/layer_manager.cpp
platform/darwin/src/MGLStyleLayerManager.mm
platform/default/layer_manager.cpp
src/mbgl/annotation/annotation_manager.cpp
src/mbgl/annotation/annotation_manager.hpp
src/mbgl/map/map.cpp
src/mbgl/renderer/renderer.cpp
src/mbgl/renderer/renderer_impl.cpp

At the moment, the annotations implementation in the `mapbox-gl-native` core is creating concrete layer instances apart from `LayerManager/LayerFactory` code path.
So, annotations must be disabled if the `LayerManager` implementation does not provide line, fill or symbol layers (those, used by the annotations).
Note: in future, annotations implementation will be moved from the core to the
platform SDK level(see https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation) and `LayerManager` won't need to disable it.
Tagging https://github.com/mapbox/mapbox-gl-native/issues/13276

[core] LayerManager can disable annotations

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Annotation.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/ArrowDirection.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BasePointCollection.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Bubble.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BubbleLayout.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BubblePopupHelper.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Icon.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/IconFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Polygon.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/PolygonOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Polyline.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/PolylineOptions.java

[android] deprecated annotations package

---

platform/darwin/src/MGLGeometry_Private.h
platform/darwin/src/MGLMapSnapshotter.mm

Follows-up on #13235. Abstracts platform-specific `NSStringFromSize()`/`NSStringFromCGSize()` to `MGLStringFromSize()` — this fixes an “unused variable” warning in `MGLMapSnapshotter` in Release builds.

[darwin] Add platform-agnostic MGLStringFromSize() method

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java

resolve https://github.com/mapbox/gl-internal/issues/1026
This PR fix the issue that when devs use MapSnapshotter in Android sdk, it will not send turnstile event.

[Android] Send turnstile event while create MapSnapshotter instance

---

platform/android/gradle/dependencies.gradle

Targeting `release-horchata` as this changes are not compatible with `master` that is already using telemetry `v4.x`.

Telemetry bump 3.5.6

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterActivity.java
platform/android/src/snapshotter/map_snapshotter.cpp
platform/android/src/snapshotter/map_snapshotter.hpp
platform/darwin/src/MGLMapSnapshotter.mm
platform/default/mbgl/map/map_snapshotter.cpp
platform/default/mbgl/map/map_snapshotter.hpp
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Backports https://github.com/mapbox/mapbox-gl-native/pull/13427 and https://github.com/mapbox/mapbox-gl-native/pull/13475 to `release-horchata`

Backport changes for 6.7.2 to horchata

---

include/mbgl/tile/tile_id.hpp
scripts/changelog_staging/tile-is-child.json
test/tile/tile_id.test.cpp

Fixes issue #13478. Port of https://github.com/mapbox/mapbox-gl-js/pull/7644.
On the native side, we already checked wrap values in `UnwrappedTileID::isChildOf` -- I've tried to think of reasons we might have intentionally avoided checking in `OverscaledTileID`, but I can't think of any yet.
cc @kkaefer @ansis

[core] OverscaledTileID::isChildOf should check wrap values.

---

codecov.yml

This changes the default threshold to 1% (from `0%`) for when to fail a build due to negative coverage changes.
The reasoning here is that some tests are unreliable (more on this at #13324) and are causing %0.1 fluctuations in coverage for PRs which should not impact coverage (like #13357 and #13360). This change is a stopgap measure to avoid developer pain, until the cause of the unreliability can be understood and mitigated.
/cc @jmkiley 
Docs for adjusting thresholds at https://docs.codecov.io/docs/commit-status

Adjust coverage tracking threshold

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/net/ConnectivityReceiver.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java

Pushes a forced connectivity state, that can be used to block outgoing communication in offline scenarios, immediately to core instead of bundling it with system connectivity updates. This led to a couple of requests being sent out if the style was loaded from a local resource, regardless of the forced offline state.

Immediately notify core about forced connectivity state

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/types/Formatted.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/types/FormattedSection.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs
platform/android/scripts/generate-style-code.js
src/mbgl/style/expression/formatted.cpp

Closes https://github.com/mapbox/mapbox-gl-native/issues/13172.
Exposes `PropertyFactory#textField(Formatted)` property setter. A Java `Formatted` object is passed as an array that's converted to a core `Formatted` object.

Formatted "text-field" property setter

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterActivity.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/13501

Expose endpoint change option for snapshotter

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Copyedited and reorganized the iOS and macOS changelogs. Both changelogs have experienced bad merges (which were automatic merges in each case, not hand-merges). Some sections don’t have enough blurbs yet to warrant separate sections. Please ensure that I haven’t accidentally removed anything from these changelogs.

Copyedit and reorganize iOS, macOS changelogs

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-stripped.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Cherry picks  the podspec bump for `ios-v4.7.0-beta.1` (https://github.com/mapbox/mapbox-gl-native/pull/13511) into release-iowaska.

cp podspec bump to release-iowaska

---

platform/darwin/src/MGLMapSnapshotter.mm

Snapshotter (i.e. https://www.mapbox.com/android-docs/maps/overview/snapshotter) is part of the Maps SDK and should be sending turnstile events before usage on both iOS and Android (Snapshotter requests need the same access token we use for regular tile requests).
We should add turnstile events for Snapshotter.

[iOS] Add turnstile events for Snapshotter

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

[android] returning null instead of the Source object in the MapboxMap#removeSource when it fails

---

platform/darwin/src/MGLVectorTileSource.mm
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/macos/CHANGELOG.md

Addresses the simple automatic localization case from #11867.
This enables automatic localization of Mapbox Streets source v8 and the forthcoming Streets v11 style, but does not yet implement a solution to the relocalization issues explained in https://github.com/mapbox/mapbox-gl-native/issues/12164#issuecomment-404974778 — that’ll be handled as tail work, tracked by #11867.
/cc @1ec5

Update automatic Streets localization for v8/v11 data/styles

---

platform/darwin/src/MGLStyle.mm
platform/darwin/src/NSString+MGLAdditions.m
platform/darwin/test/MGLNSStringAdditionsTests.m
platform/ios/src/MGLMapAccessibilityElement.mm
platform/ios/src/NSOrthography+MGLAdditions.m

Updates VoiceOver accessibility style layer checks for [Streets-v8 field names](https://www.mapbox.com/vector-tiles/mapbox-streets-v8/#changelog), per #11867.
/cc @1ec5

[ios, macos] Add Streets-v8 field names to accessibility checks

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java

Closes #12798, with the addition of symbol placement, fading of symbols was added. 
Adding a filter configuration on the unclustered layer resolves the issue from #12798.
cc @langsmith as we have other examples downstream that can be updated

Update clustering example with filter configuration 

---

src/mbgl/annotation/render_annotation_source.cpp
src/mbgl/renderer/render_source.cpp

This patch disables creation of `RenderAnnotationSource` instances
and thus saves extra 4Ki on Android when `LayerManager::annotationsEnabled`
is `false`.

[core]Disable RenderAnnotationSource when annotations are disabled

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/BaseLayerTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/NativeMapViewTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/VisibleRegionTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/BackgroundLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillExtrusionLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HeatmapLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HillshadeLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RasterLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

Refs https://github.com/mapbox/mapbox-gl-native/issues/13418
This PR introduces a way to perform unit tests on JNI/core integration. 
It runs instrumented unit tests without using a view hierarchy/activity/espresso:
- adds basic map tests
- refactors generated layer tests

Instrumented unit tests, add map tests, refactor gen layer tests

---

platform/android/src/style/layers/layer_manager.cpp
platform/android/src/style/layers/layer_manager.hpp

`LayerManagerAndroid` can add layer types that are enabled only for JSON style.
It allows to save binary size - JNI glue code for these layer types won't be
added to the binaries.
tagging #13276

[android] Enable core-only layers

---

include/mbgl/map/map_observer.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapChangeReceiver.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapChangeReceiverTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/MapChangeActivity.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp
platform/ios/src/MGLMapViewDelegate.h
platform/ios/test/MGLMapViewDelegateIntegrationTests.swift
platform/macos/src/MGLMapView.mm
platform/macos/src/MGLMapViewDelegate.h
platform/macos/test/MGLMapViewDelegateIntegrationTests.swift
scripts/changelog_staging/idle-event.json
src/mbgl/map/map.cpp

'didEnterIdle' fires whenever render completes and no repaint is scheduled.
Fixes issue #13469
Potential issues:
- This logic doesn't know anything about animations that are being driven by the SDK instead of through the core transition logic. In practice I think this probably won't be a huge issue because if the SDK is running an animation, it will keep triggering placement, which will keep the renderer from entering idle.
- Potentially confusing to add an extra event, since we've already got "didFinishRendering/fullyRendered" and "didFinishLoadingMap". However, I think the name "idle" is a pretty good description of this event, and matches up better with what users have expected to get from the other events.
cc @tobrun @julianrex @ansis

[core, darwin, android] Add onDidBecomeIdle to MapObserver.

---

src/mbgl/text/placement.cpp

Fixes issue #13506.
- Setting the value to zero caused divide-by-zero errors
- ~~Small non-zero values worked, but were unexpectedly expensive (because of requiring frequent collision detection)~~
~~Although this commit reverts the configurable duration, it leaves the "enablePlacementTransitions" flag intact.~~
cc @ansis @tmpsantos @brunoabinader

[core] Handle transition duration of 0ms for symbols

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_debug_mode.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

iOS already added an [API](https://github.com/mapbox/mapbox-gl-native/pull/12501) to let devs set FPS. It is essential in scenarios cpu load is heavy, so it will be better if we could add one on Android side.
I have tested it by myself, it can change the fps roughly, still need some discussions on it.

[Android] Add setPreferredFramesPerSecond for MapView

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/OnLocationCameraTransitionListener.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationCameraControllerTest.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationModesActivity.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/13243.

CameraMode transition animation and result listeners

---

platform/android/MapboxGLAndroidSDK/gradle.properties

Extracted snapshot version update from https://github.com/mapbox/mapbox-gl-native/pull/13536 as that is blocked by https://github.com/mapbox/mapbox-gl-native/pull/12972

Set snapshot version to 7.1.0

---

src/mbgl/text/placement.cpp

>[core] Avoid divide-by-zero when transition duration is 0..
Fixes issue #13506 -- transition duration of 0 would cause symbol flickering.
cc @mapbox/maps-ios @ChrisLoer

Backport #13535 to iowaska

---

include/mbgl/renderer/renderer.hpp
include/mbgl/util/geojson.hpp
src/mbgl/renderer/render_source.hpp
src/mbgl/renderer/renderer.cpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp
src/mbgl/renderer/sources/render_geojson_source.cpp
src/mbgl/renderer/sources/render_geojson_source.hpp
src/mbgl/style/sources/geojson_source_impl.cpp
src/mbgl/style/sources/geojson_source_impl.hpp
test/api/query.test.cpp
test/fixtures/supercluster/places.json

New API allows to query additional information about rendered features.
Implementation of https://github.com/mapbox/mapbox-gl-native/pull/12726#issuecomment-435542608
Based on  PR https://github.com/mapbox/mapbox-gl-native/pull/12726 made by @tobrun
This PR adds supercluster extension that is implemented in geojson render source and provides access to getLeaves, getChildren and getClusterExpansion zoom methods.

[core] Add queryFeatureExtension API

---

platform/darwin/src/MGLMapSnapshotter.mm

This moves the turnstile event for `MGLSnapshotter` from the `MGLSnapshot` initializer to the `MGLSnapshotter` initializer.

[darwin] Send turnstile event for MGLSnapshotter in initializer

---

platform/darwin/src/MGLMapSnapshotter.mm
platform/darwin/src/MGLVectorTileSource.mm
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm
platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapAccessibilityElement.mm
platform/macos/CHANGELOG.md

Cherry picks:
- [darwin] Send turnstile event for MGLSnapshotter in initializer #13549
- Update automatic Streets localization for v8/v11 data/styles #13481 
- [ios] Add Streets-v8 field names to accessibility checks #13525

[ios] Release v4.7.0 beta.2 preparation

---

platform/darwin/src/MGLBackgroundStyleLayer.mm
platform/darwin/src/MGLCircleStyleLayer.mm
platform/darwin/src/MGLFillExtrusionStyleLayer.mm
platform/darwin/src/MGLFillStyleLayer.mm
platform/darwin/src/MGLHeatmapStyleLayer.mm
platform/darwin/src/MGLHillshadeStyleLayer.mm
platform/darwin/src/MGLLight.mm
platform/darwin/src/MGLLight.mm.ejs
platform/darwin/src/MGLLineStyleLayer.mm
platform/darwin/src/MGLRasterStyleLayer.mm
platform/darwin/src/MGLStyle.mm
platform/darwin/src/MGLStyleLayer.mm.ejs
platform/darwin/src/MGLStyleValue_Private.h
platform/darwin/src/MGLSymbolStyleLayer.mm
platform/darwin/src/MGLTypes.h

This PR originally intended to fix #13408 but after the feedback I decided to split the functionality into laying the ground to migrate from struct to a class (this PR), and adding a property to expose placement transition.

[ios, macos] Standardize MGLTransition struct creation.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentCompassEngine.java

`compassUpdateNextTimestamp` was only getting updated for `TYPE_ROTATION_VECTOR` sensor. Because of this, compass readings from all other sensors are processed at very fast rate (we saw close to 10 times per second).

Fixed compass update time not getting updated

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/NativeMapViewTest.kt

Closes #13554, we aren't destroying the NativeMapView as part of the tests, this patches things up for now by not executing any tests that would involve loading a style. Long term I'm looking into a different setup for these kind of tests.

Remove style load test from instrumented unit tests

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/CompassEngine.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/CompassListener.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentCompassEngine.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationLayerController.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/CompassEngineTest.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt

Register compass sensor listener only if provided data is consumed by the location layer or location camera. The idea here is to remove the overhead of creating new compass animators when they are ultimately ignored.
/cc @BharathMG

Register compass sensor listener only if necessary

---

platform/darwin/src/MGLFeature.mm
platform/darwin/src/MGLFeature_Private.h
platform/darwin/test/MGLFeatureTests.mm
platform/ios/CHANGELOG.md
platform/ios/Integration Tests/MGLShapeSourceTests.m
platform/macos/CHANGELOG.md

Enforce non-nullable semantics for MGLFeature.attributes, to avoid construction of invalid mbgl::Feature properties from nil NSDictionary object and align with public SDK property definition.
Integration test "testShapeSourceWithLineDistanceMetrics" is added to verify that MGLFeature is correctly converted.
Fixes issue #13378

[ios, darwin] Make MGLFeature.attributes non-nullable and add integration test

---

platform/android/src/map_renderer.cpp
platform/android/src/native_map_view.cpp
platform/android/src/snapshotter/map_snapshotter.cpp

Closes #13554, to be CP'ed to release-iowaska
**update:** found root cause in https://github.com/mapbox/mapbox-gl-native/pull/13572 but I believe this is still valid to be merged. Calling get and checking state on a weakreference is what you would expect from using a weakreference.

Validate if WeakReference is valid

---

platform/darwin/src/MGLStyle.h
platform/darwin/src/MGLStyle.mm
platform/darwin/test/MGLStyleTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Fixes https://github.com/mapbox/mapbox-gl-native/issues/13408 and https://github.com/mapbox/mapbox-gl-native/pull/13035

[ios, macos] Add enablePlacementTransitions to MGLStyle.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinatorTest.kt
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationCameraControllerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt

Closes https://github.com/mapbox/mapbox-gl-native/issues/13014.
The threshold value has been chosen experimentally, so please test it out and let me know what you think. 
The idea is to transition the camera without animation if there is a lot of relative camera distance (and unloaded tiles) to cover in between. This means, that the higher the `distance / zoom level` ratio, the more travel the camera will need to perform. Zoom level is expressed here as the projected meters per pixel.
Currently targeted at https://github.com/mapbox/mapbox-gl-native/pull/13523 to avoid conflicts but I'm going to re-target when https://github.com/mapbox/mapbox-gl-native/pull/13523 lands.

Immediate location animation based on map's projection

---

appveyor.yml

New version of VS 2017 image contains VS v15.9.4 that doesn't work anymore with LLVM 6.0.0. This PR upgrades LLVM to version 7.0.0

[build] Upgrade LLVM to 7.0.0 for AppVeyor Visual Studio 2017 v15.9.x bot

---

platform/darwin/src/MGLConversion.h
platform/darwin/test/MGLPredicateTests.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Fixes https://github.com/mapbox/mapbox-gl-native/issues/13527

[ios, macos] Fix number conversions when expressions cast to large numbers.

---

cmake/filesource-files.txt
platform/default/include/mbgl/storage/local_file_request.hpp
platform/default/src/mbgl/storage/asset_file_source.cpp
platform/default/src/mbgl/storage/local_file_request.cpp
platform/default/src/mbgl/storage/local_file_source.cpp

Use exception free util::readFile instead of util::read_file for LocalFileSource and AssetFileSource implementations.
Fixes: #9244

[core] Use util::readFile for Local and Asset file sources

---

platform/ios/scripts/release-notes-github.md.ejs

Fixes the broken Cocoapods/Carthage links in Github release notes.

[ios] Update release notes template for correct Cocoapods/Carthage links

---

platform/android/src/style/layers/layer_manager.hpp
platform/darwin/src/MGLStyleLayerManager.h
platform/darwin/src/MGLStyleLayerManager.mm

`LayerManagerDarwin` can add layer types that are enabled only for JSON style.
It allows to exclude the SDK wrappers for these layers from the project and decrease binary size.
tagging #13276

[mac, ios] Enable core-only layers

---

circle.yml

This PR schedules a benchmark run in mobile-metrics when a merge occurs to master.

Invoke benchmark trigger from CI

---

platform/darwin/src/MGLStyle.h
platform/default/include/mbgl/util/default_styles.hpp
platform/ios/CHANGELOG.md
platform/ios/Integration Tests/MGLStyleURLIntegrationTest.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/CHANGELOG.md
test/util/mapbox.test.cpp

See https://github.com/mapbox/mapbox-gl-native/issues/13553
/cc @LukasPaczos @tmpsantos @1ec5 @nickidlugash

Updates default styles to streets v11, etc.

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-stripped.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Updates podspecs & changelog for release.

Release v.4.7.0 stable prep

---

appveyor.yml
circle.yml
platform/darwin/src/MGLFeature.mm
platform/darwin/src/MGLFeature_Private.h
platform/darwin/src/MGLStyle.h
platform/darwin/test/MGLFeatureTests.mm
platform/default/mbgl/util/default_styles.hpp
platform/ios/CHANGELOG.md
platform/ios/Integration Tests/MGLShapeSourceTests.m
platform/ios/Integration Tests/MGLStyleURLIntegrationTest.m
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-stripped.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/CHANGELOG.md
test/util/mapbox.test.cpp

Picks:
- Make MGLFeature.attributes non-nullable and add integration test #13543
- Updated iOS/macOS change logs. #13564
EDIT:
- Upgrade LLVM to 7.0.0 for AppVeyor Visual Studio 2017 v15.9.x bot #13583 
- Release v.4.7.0 stable prep (podspecs / changelog) #13602

Stable release v.4.7.0 cherry-picks

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/13566.
Brings back the initial implementation where we are waiting for a style to load before dismissing the foreground color. I needed to increase initial frames drawn from 2 to 3 in order to get consistent results.

Dismiss the foreground color only when the style is loaded

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java

This pr adds missing mentions of the `Style` parameter object to the javadocs for the `LocationComponent`'s `activateLocationComponent()` methods. These docs will help guide folks who are wondering what this new `Style` object is about.
Based on https://github.com/mapbox/mapbox-gl-native/pull/13588

[Android] Added Style object parameter mention to LocationComponent methods

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/CompassEngine.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentCompassEngine.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/TransformTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraAnimateTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraEaseTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraForTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraMoveTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/ScrollByActivity.java

Removes remaining deprecated methods and deprecates annotation related methods found in the `MapboxMap`.

Cleanup deprecated methods for 7.0.0

---

include/mbgl/map/map_observer.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapChangeReceiver.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapChangeReceiverTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/MapChangeActivity.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp
platform/ios/src/MGLMapViewDelegate.h
platform/ios/test/MGLMapViewDelegateIntegrationTests.swift
platform/macos/src/MGLMapView.mm
platform/macos/src/MGLMapViewDelegate.h
platform/macos/test/MGLMapViewDelegateIntegrationTests.swift
scripts/changelog_staging/idle-event.json
src/mbgl/map/map.cpp

Tailwork of cherry pick for 6.8.0, we need to make sure that all changes in release-horchata are found in release-iowaska as well. Only missing commits from https://github.com/mapbox/mapbox-gl-native/pull/13608 is: https://github.com/mapbox/mapbox-gl-native/pull/13513

Cherrypick idle event to release-iowaska

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java
platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml

Refs https://github.com/mapbox/mapbox-gl-native/issues/13553.
This introduces breaking changes in layer/sources names in the listed core style, more about the `streets-v8` source [here](https://www.mapbox.com/vector-tiles/mapbox-streets-v8/).
Includes updates to:
`streets-v11`
`outdoors-v11`
`light-v10`
`dark-v10`
`satellite-streets-v11`

Update core styles based on the streets-v8 source

---

src/mbgl/style/layers/background_layer.cpp
src/mbgl/style/layers/circle_layer.cpp
src/mbgl/style/layers/fill_extrusion_layer.cpp
src/mbgl/style/layers/fill_layer.cpp
src/mbgl/style/layers/heatmap_layer.cpp
src/mbgl/style/layers/hillshade_layer.cpp
src/mbgl/style/layers/layer.cpp.ejs
src/mbgl/style/layers/line_layer.cpp
src/mbgl/style/layers/raster_layer.cpp
src/mbgl/style/layers/symbol_layer.cpp
test/style/source.test.cpp

Use `mapbox::eternal::hash_map` in `...Layer::setPaintProperty()` and  `...Layer::setLayoutProperty()` methods to decrease code size, binary size and improve performance.

Use eternal map in style:Layer implementations

---

platform/android/CHANGELOG.md

Backports https://github.com/mapbox/mapbox-gl-native/pull/13619 to `release-horchata`.

Backport #13619 to horchata

---

Makefile

[android] - remove render test definitions from assets

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Adds changelog entry for #13525.
Adds missing code ticks.

[ios, macos] Updated change log entries that missed being updated prior to 4.7.0

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec

Cherry-picked #13603 and #13635 in preparation for macOS map SDK v0.13.0.

macOS map SDK v0.13.0 (release-iowaska)

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/Style.java
platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml

This pr reverts changes made in https://github.com/mapbox/mapbox-gl-native/pull/13615, which had bumped the style URLs to v10/v11. This pr is the same as https://github.com/mapbox/mapbox-gl-native/pull/13643 (now closed), but targets the `release-horchata` branch in preparation for an easier `6.8.1` release.
More info can be found at https://www.mapbox.com/vector-tiles/mapbox-streets-v8/

[android] Revert core styles URLs back to streets-v7 source

---

platform/android/gradle/dependencies.gradle

This pr bumps the [Mapbox Android telemetry library](https://github.com/mapbox/mapbox-events-android) dependency to 3.5.7 . This pr targets `release-horchata` because in [@LukasPaczos ' pr which bumped it to `3.5.6`](https://github.com/mapbox/mapbox-gl-native/pull/13486), he said:
> Targeting `release-horchata` as this changes are not compatible with `master` that is already using telemetry `v4.x`.

[android] Telemetry bump to 3.5.7

---

bin/offline.cpp
include/mbgl/storage/offline.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineGeometryRegionDefinition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionDefinition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineTilePyramidRegionDefinition.java
platform/android/src/offline/offline_region_definition.cpp
platform/darwin/src/MGLOfflineRegion.h
platform/darwin/src/MGLShapeOfflineRegion.mm
platform/darwin/src/MGLTilePyramidOfflineRegion.mm
platform/darwin/test/MGLOfflineRegionTests.m
platform/darwin/test/MGLOfflineStorageTests.mm
platform/default/src/mbgl/storage/offline.cpp
platform/default/src/mbgl/storage/offline_download.cpp
platform/ios/app/MBXOfflinePacksTableViewController.m
platform/macos/app/Base.lproj/MapDocument.xib
platform/macos/app/MapDocument.m
scripts/changelog_staging/no-offline-cjk.json
src/mbgl/text/glyph_range.hpp
test/storage/offline.test.cpp
test/storage/offline_database.test.cpp
test/storage/offline_download.test.cpp

This is a proof-of-concept for a fix to issue #11561 -- for small offline packs, the size of the pack is dominated by the space taken up by CJK glyphs, even though many or most people won't use them:
- For maps intended for CJK audiences, we typically recommend using local CJK glyph generation, so it's not necessary to cache the glyphs in an offline pack.
- For offline maps intended for non-CJK audiences, it is likely that the offline region covers an area in which there are no or very few CJK glyphs, so there's a good chance it's OK to exclude them.
For a z1/z2 offline region of Satellite Streets, it looks like excluding CJK glyphs brings the bundle size down from ~90MB to ~12MB.
Currently the code defaults to the existing behavior of including the glyphs. We should consider defaulting …

Optionally exclude CJK glyphs from offline downloads

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

While testing https://github.com/mapbox/mapbox-gl-native/issues/13560. I'm noticing that a fragment can call onSaveInstanceState when it's in the fragment backstack. This means that the view and underlying NativeMapView have already been destroyed and we shouldn't talk to NativeMapView to save state. This PR caches the debug value so it can be restored on orientation change without NativeMapView involvement.

Save debug cache state vs map state

---

platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm

Follow on from https://github.com/mapbox/mapbox-gl-native/pull/13513
This PR adds the `mapViewDidBecomeIdle` method to iOS, and fixes the selector check in the macOS version.

[ios, macos] Added missing mapViewDidBecomeIdle for iOS. Fixed typo.

---

src/mbgl/geometry/feature_index.cpp

fix #11357
Different rings for the same feature were being assigned different indices. This assigns the same index to all features. -js already has the correct behaviour.
cc @mb12 @ChrisLoer

[core] fix deduping rings in querying, #11357

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterReuseActivity.java

closes https://github.com/mapbox/mapbox-gl-native/issues/13674 by moving towards using the builder.

Fix random bounds generation in test app bounds activity

---

package.json
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterActivity.java
platform/android/src/snapshotter/map_snapshotter.cpp
platform/android/src/snapshotter/map_snapshotter.hpp
platform/darwin/src/MGLMapSnapshotter.mm
platform/default/mbgl/map/map_snapshotter.cpp
platform/default/mbgl/map/map_snapshotter.hpp
platform/ios/CHANGELOG.md

This PR cherry-picks #13427 into the iOS 8 branch.
cc @lloydsheng @chriswu42

[ios] Cherry-pick #13427 - Expose "local ideograph font family" in map snapshotters

---

platform/darwin/src/MGLMapSnapshotter.mm

This PR cherry-picks #13476 into the iOS 8 branch.
cc @chriswu42

[ios] Cherry-pick #13476 - Add turnstile events for Snapshotter

---

platform/darwin/src/MGLStyle.h
platform/darwin/src/NSExpression+MGLAdditions.h

Updates the documentation in `MGLStyle.h` and `NSExpression+MGLAdditions.h` to point to the new `mapbox-streets-v8` instead of `mapbox-streets-v7`.
I checked this for Android too but couldn't find anywhere where `mapbox-streets-v*` was being referenced within inline documentation.
There are a few places where `mapbox-streets-v7` is used for testing purposes, but I've left those alone for now.
Note to future releaser: No changelog entry required for this change.

[ios, macos] Update code comments to mapbox-streets-v8

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm

Fixes: #13055
Also:
- renames related variables/parameters for clarity (e.g. `moveOnscreen` -> `moveIntoView`)
- Adds `-[MGLMapView selectAnnotation:moveIntoView:animateSelection:]` to the public header, but marked as undocumented.

Fixes a bug where the animated parameter of -[MGLMapView selectAnnotation:animated:] was ignored.

---

platform/ios/CHANGELOG.md

Backports iOS change log entries from https://github.com/mapbox/mapbox-gl-native/pull/13650
/cc @friedbunny @fabian-guerra

[ios] Updates the change log with 4.7.1 changes.

---

platform/darwin/test/MGLSDKTestHelpers.swift
platform/ios/ios.xcodeproj/project.pbxproj

Migrated tests and the playground to Swift 4.2, resolving the following build warnings:
```
Warning Group
:-1: Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "test" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu. (in target 'test')
Swift Conversion Group
Conversion to Swift 4.2 is available
```
/cc @friedbunny @fabian-guerra

Migrate tests, playground to Swift 4.2

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

To avoid confusion for developers integrating, I'm suggesting to throw a runtime exception when an too early invocation of `setMaximumFps` occurs. Otherwise not setting this configuration might get unnoticed.

Throw exception when setting an maxfps while the mapRenderer isn't created yet

---

platform/ios/Integration Tests/MGLStyleLayerIntegrationTests.m

🚧 Do not merge until API documentation changes land 🚧
This PR updates links to the API docs to match the new URL structure.
cc @mapbox/docs

[ios] - Update links to new API doc format

---

platform/darwin/src/MGLRasterTileSource.h
platform/darwin/src/MGLStyle.h

🚧 Do not merge until API documentation changes land 🚧
This PR updates links to the API docs to match the new URL structure.
cc @mapbox/docs

[macos] - Update links to new API doc format

---

src/core-files.json
src/mbgl/programs/background_program.hpp
src/mbgl/programs/circle_program.hpp
src/mbgl/programs/fill_extrusion_program.hpp
src/mbgl/programs/fill_program.hpp
src/mbgl/programs/heatmap_program.hpp
src/mbgl/programs/hillshade_program.hpp
src/mbgl/programs/line_program.hpp
src/mbgl/programs/program.hpp
src/mbgl/programs/programs.cpp
src/mbgl/programs/programs.hpp
src/mbgl/programs/raster_program.hpp
src/mbgl/programs/symbol_program.hpp
src/mbgl/renderer/layers/render_background_layer.cpp
src/mbgl/renderer/layers/render_circle_layer.cpp
src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
src/mbgl/renderer/layers/render_fill_layer.cpp
src/mbgl/renderer/layers/render_heatmap_layer.cpp
src/mbgl/renderer/layers/render_hillshade_layer.cpp
src/mbgl/renderer/layers/render_line_layer.cpp
src/mbgl/renderer/layers/render_raster_layer.cpp
src/mbgl/renderer/layers/render_symbol_layer.cpp
src/mbgl/renderer/render_static_data.hpp

Programs code for a certain layer type is encapsulated within
a dedicated `<layer type>Programs` class, inherited from
the generic base `LayerTypePrograms` class.
`mbgl::Programs::get<layer type>Programs()` lazily initializes the
layer type-specific programs code using pointer to the base class,
which allows LTO to remove this code from binaries (if the corresponding
`get<layer type>Programs()` method can never be invoked).
Tagging https://github.com/mapbox/mapbox-gl-native/issues/13276

[core] Split layer type specific code in mbgl::Programs

---

src/mbgl/style/conversion/stringify.hpp
src/mbgl/style/layers/layer_properties.hpp.ejs
src/mbgl/style/layers/line_layer_properties.hpp
src/mbgl/style/layers/symbol_layer_properties.hpp

Some compilers don't include the symbol if there's no definition of the constexpr string. Instead of providing one, we're switching to constexpr functions similar to how jni.hpp does it.

Return constexpr strings from functions to avoid ODR compile failures

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Avoid null pointer when quickly closing activity for attribution click handling.
Refs CI failure: https://console.firebase.google.com/project/android-gl-native/testlab/histories/bh.1470d2ab45df6f1f/matrices/5309687223697427015

Avoid null pointer when quickly closing activity

---

src/mbgl/layout/symbol_layout.cpp
src/mbgl/renderer/buckets/symbol_bucket.cpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/renderer/layers/render_symbol_layer.cpp

Obviates unnecessary lookups, improves readability.

[core] SymbolBucket: use single map for paint properties data

---

platform/default/src/mbgl/storage/online_file_source.cpp

When network status is changed to online, all unqueued requests may be processed in nondeterministic. order (unordered_set). Therefore, low-priority request may be made active, while other are put to priority queue. This introduces flakiness for the unit test.
Fixes: #13371

[core] Notify requests about network reachability in priority order

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapView.mm

Fixed an issue where an MGLMapView targeting an external display via CarPlay would freeze, ignoring both programmatic changes and user gestures, whenever the main device’s screen fell asleep automatically or the user manually locked the screen.
MGLMapView has to tiptoe around a hard prohibition against OpenGL rendering when the application recedes into the background or enters background mode, exhibited in crashes such as #1198 and #1460. However, if an application integrates the navigation SDK and is connected to CarPlay, the application will stay active even when the screen is locked.
This PR also includes a change to iosapp to show a map view on any connected external display and keep it synchronized with the map on the main display. This iosapp feature only works with AirPlay, not …

Prevent map view on external display from sleeping in background

---

.gitmodules
Makefile
circle.yml
platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/build.gradle
platform/android/gradle/dependencies.gradle
platform/android/gradle/gradle-update-vendor-modules.gradle
platform/android/settings.gradle

Closes https://github.com/mapbox/mapbox-gl-native/issues/13598.
Closes https://github.com/mapbox/mapbox-gl-native/issues/13728.
TODO:

Android libraries vendorization

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/attribution/Attribution.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/attribution/AttributionParser.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/attribution/AttributionParseTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/13715. it now generates attribution correctly:

Snapshot attribution

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.kt
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/TransformTest.kt

Fixes https://github.com/mapbox/mapbox-gl-native/issues/13735.
This PR also moves `Transform` unit tests out of `MapboxMapTest`.

Do not invoke #onCancel when animation is scheduled from #onFinish

---

src/mbgl/renderer/render_layer.cpp
src/mbgl/renderer/render_source.hpp
src/mbgl/renderer/sources/render_geojson_source.cpp
src/mbgl/renderer/sources/render_raster_dem_source.cpp
src/mbgl/renderer/sources/render_raster_source.cpp
src/mbgl/renderer/sources/render_vector_source.cpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/renderer/tile_pyramid.hpp

Thus we obviate unneeded extra sorting of render tiles at each render layer.

[core] TilePyramid has sorted render tiles

---

platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm

Fixes a bug where `MGLMapView.visibleAnnotations` was calling `-visibleFeaturesInRect:` rather than `-visibleAnnotationsInRect:`.

[macos] Fixes MGLMapView.visibleAnnotations

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java

Avoid leaking compassView context through animator

---

platform/android/src/jni.cpp

Add the ability to remove both the snapshotter and offline code with pre-processor flags. This saves about 31kb in final APK if they are not being used.

[Android] Allow offline and snapshotter to be disabled.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/LibraryLoader.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/Source.java

This PR does addresses two items:
- avoid recursive loading and the printed warning 
- add library loading to classes that can be used as peer objects

Avoid recursive loading, add library loading to peer objects.

---

platform/android/src/style/layers/layer_manager.cpp
platform/darwin/src/MGLStyleLayerManager.mm
platform/default/src/mbgl/layermanager/layer_manager.cpp

Add two pre-processor flags for each layer that allow you to control how they will be compiled into your application. By default all layers are added and there is no change to how the SDK is currently compiled in master. This will give people who use compile the SDK by source to choose which layers they want in their build process without the need for maintaining any additional code.
```
LAYER_{LAYER_NAME}_DISABLE_ALL
```
Removes the layer completely from your application
```
LAYER_{LAYER_NAME}_DISABLE_RUNTIME
```
Adds the layer but only to the core. The goal with calling this flag RUNTIME was to allow it to both be used by Andriod and iOS so the flags would match.

Ability to choose which Layers to compile

---

src/mbgl/algorithm/generate_clip_ids.hpp
src/mbgl/algorithm/generate_clip_ids_impl.hpp
src/mbgl/algorithm/update_tile_masks.hpp
test/algorithm/generate_clip_ids.test.cpp
test/algorithm/update_tile_masks.test.cpp

The tile sorting can be now removed from the algorithms, which
calculate tile mask and clip ids, because their client code
provides tiles being already sorted (in `TilePyramid`).
This patch brings significant improvements to the Tile-related
performance tests results, for example the `TileMaskGeneration`
benchmark test runs 33 times faster with these changes applied.

[core] Remove tile sorting from the clip and mask algorithms

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/Source.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.java
platform/android/gradle/dependencies.gradle

Reverts #13753 (re-adds 16718b0) and addresses failing test by changing the mock setup based on the suggestions made [here](https://stackoverflow.com/questions/26318569/unfinished-stubbing-detected-in-mockito).

Bring back 16718b0 and change unit test mock setup

---

CMakeLists.txt
circle.yml
platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/build.gradle
platform/android/config.cmake
platform/android/gradle/dependencies.gradle
platform/android/gradle/wrapper/gradle-wrapper.properties
vendor/optional.cmake

`<experimental/optional>` is not available anymore in newer versions of libc++, according to libc++'s TS deprecation policy: https://libcxx.llvm.org/TS_deprecation.html. This unblocks support for the Android NDK 18: https://github.com/mapbox/mapbox-gl-native/pull/12972#issuecomment-424639470

Use vendored version of <experimental/optional>

---

platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java
platform/android/gradle/dependencies.gradle

ReLinker is useful to improve reliability for native library loading on older Android versions. It's also useful for identifying causes for `UnsatisfiedLinkError` errors. 
For example:
> System.loadLibrary(name);
java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
> ReLinker.loadLibrary(context, name);
Loading the library normally failed: java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libc++_shared.so" needed by "libmapbox-gl.so"; caused by library "libc++_shared.so" not found

Use ReLinker as default library loader for the test app

---

platform/android/MapboxGLAndroidSDK/build.gradle

We already had some end-users reports on this (eg. https://github.com/mapbox/mapbox-gl-native/issues/13151). Those users were unable to build a release variant of the library due to unused arguments in our vendor packages. I'm now hitting the same issue in mobile-metrics. This PR enforces using `-Qunused-arguments`, not solely for ccache enabled build environments.

Ignore unused arguments for all configurations

---

platform/ios/CHANGELOG.md
platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m
platform/ios/Integration Tests/MGLMapViewIntegrationTest.h
platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/ios/vendor/SMCalloutView/SMCalloutView.m
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm
platform/macos/test/MGLAnnotationTests.m

This PR follows on from https://github.com/mapbox/mapbox-gl-native/pull/13689, and extracts bug fixes from the stale https://github.com/mapbox/mapbox-gl-native/pull/12970.
There was a "bug" where annotations without callouts would be moved when partially on-screen:
https://github.com/mapbox/mapbox-gl-native/pull/13727/files#diff-20502b6bc02986a4398d0da84b2d4b94L4638
This changes limits the partially-on-screen movement to cases where annotations have callouts (and this behavior can be overridden by changing the margins returned by `marginInsetsHintForPresentationFromRect:`).
Needs:
/cc @chloekraw

[ios] Partially offscreen annotations (without callouts) are no longer moved on-screen

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

[ios] Fix wrong coordinates bounds when setting direction.

---

platform/android/gradle/gradle-javadoc.gradle

Starting with Android Studio 3.3.0, we will receive a warning when we perform a gradle sync:
> WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'. It will be removed at the end of 2019. For more information, see https://d.android.com/r/tools/task-configuration-avoidance. To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Capturing  a solution from [here](https://github.com/vanniktech/gradle-android-javadoc-plugin/pull/67/files#diff-7f9dfd224d08fdd544b6417324258085R143). We need to replace the following:
```
source = variant.getJavaCompiler().source	
```
with
```
source = variant.sourceSets.collect { it.java.sourceFiles }.inject { m, i -> m + …
```

Remove deprecated javacompile

---

platform/darwin/resources/cs.lproj/Foundation.strings
platform/darwin/resources/cs.lproj/Foundation.stringsdict
platform/ios/CHANGELOG.md
platform/ios/app/Settings.bundle/cs.lproj/Root.strings
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/cs.lproj/Localizable.strings
platform/ios/resources/cs.lproj/Localizable.stringsdict
platform/ios/resources/hu.lproj/Localizable.stringsdict
platform/macos/CHANGELOG.md
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/sdk/cs.lproj/Localizable.strings

Adds Czech and Hungarian translations.

[ios, macos] Add Czech and Hungarian translations.

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraAnimatorActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/ViewPagerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/OfflineUtils.java

Fixes https://github.com/mapbox/mapbox-gl-native/issues/13675.
Also:
- fixes `CameraAnimatorActivity` leaks
- fixes `ViewPagerActivity` style not loading after rotation
- returns empty string instead of null in offline examples
- fixes zoom precision in the GeoJSON cluster example

Test app fixes 7.1.0 QA

---

platform/android/README.md

Update project readme with buck source file ignore config

Update project readme with buck source file ignore config

---

platform/android/src/style/layers/layer_manager.cpp
platform/darwin/src/MGLStyleLayerManager.mm

In the layer manager implementations `addLayerTypeCoreOnly()`
should be called with core-only modules.

[android, darwin] Fix core-only layer creation

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/GestureDetectorActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_gestures.xml

Closes https://github.com/mapbox/mapbox-gl-native/issues/13759.

Separate quick zoom gesture option

---

platform/darwin/docs/theme/assets/css/jazzy.css.scss
platform/darwin/docs/theme/templates/deprecation.mustache
platform/darwin/docs/theme/templates/doc.mustache
platform/darwin/docs/theme/templates/task.mustache
platform/darwin/src/MGLShape.h
platform/darwin/src/MGLStyle.h
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapViewDelegate.h

Follow-up to #13819 — updated our jazzy theme to support deprecated/unavailable methods and such (mostly by copy/pasting https://github.com/realm/jazzy/pull/1041). Also edited some syntax in the docs for better auto-linking/highlighting by jazzy.
/cc @1ec5 @fabian-guerra @captainbarbosa

[darwin, docs] Add jazzy styling for deprecated/unavailable methods

---

circle.yml
platform/darwin/docs/theme/assets/css/jazzy.css.scss
platform/darwin/docs/theme/templates/deprecation.mustache
platform/darwin/docs/theme/templates/doc.mustache
platform/darwin/docs/theme/templates/task.mustache
platform/darwin/src/MGLShape.h
platform/darwin/src/MGLStyle.h
platform/ios/scripts/document.sh
platform/ios/scripts/install-packaging-dependencies.sh
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapViewDelegate.h

Cherry-picks jazzy improvements from #13819 and #13827 to `release-java`.

Cherry-pick jazzy improvements to release-java

---

platform/android/CHANGELOG.md

This PR updates the changelog for the final release of v7.1.0 of the Mapbox Maps SDK for Android.

Update changelog for v7.1.0

---

platform/qt/include/qmapbox.hpp
platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapbox.cpp
platform/qt/src/qmapboxgl.cpp

For our use case QVector is more efficient and will
do less memory allocations.
Fixes: #13830

[qt] Use QVector instead of QList

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TelemetryDefinition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/PerformanceEvent.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java

added performance event for measuring latency and tracing download failures

[android] added performance event 

---

src/mbgl/style/expression/match.cpp

We used `const std::pair<T, std::shared_ptr<Expression>>`, but the actual type is `const std::pair<const T, std::shared_ptr<Expression>>` which resulted in an implicit copy

[core] change loop variable type to auto

---

src/mbgl/layout/pattern_layout.hpp
src/mbgl/renderer/bucket.hpp
src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
src/mbgl/renderer/layers/render_fill_extrusion_layer.hpp
src/mbgl/renderer/layers/render_fill_layer.cpp
src/mbgl/renderer/layers/render_fill_layer.hpp
src/mbgl/renderer/layers/render_line_layer.cpp
src/mbgl/renderer/layers/render_line_layer.hpp

PatternLayout can directly access layer's `evaluated` field.

[core] Remove paintProperties() method from some render layers

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/gradle/android-nitpick.gradle
platform/android/gradle/dependencies.gradle

Refs https://github.com/mapbox/mapbox-gestures-android/issues/59.
Closes https://github.com/mapbox/mapbox-gl-native/issues/13844.
This PR also adds an explicit fetch for release tags of vendor repositories.

Fetch tags during nitpick, bump gestures library to v0.4.0

---

platform/android/CHANGELOG.md

Backports https://github.com/mapbox/mapbox-gl-native/pull/13853 to `release-java`.

Backport #13853 to java

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/TransitionOptions.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/NativeMapViewTest.kt
platform/android/src/native_map_view.cpp
platform/android/src/style/conversion/transition_options.cpp
platform/android/src/style/transition_options.cpp
platform/android/src/style/transition_options.hpp

Closes https://github.com/mapbox/mapbox-gl-native/issues/13402.

Expose symbol placement transition duration option

---

circle.yml

We recently updated the mobile-metrics downstream CI configuration. We invoke this as part of our merge to master flow. This PR updates to the renaming done in that PR.

Update downstream circle-ci job name

---

platform/ios/scripts/install-packaging-dependencies.sh

Makes #13874 a bit more resilient by avoiding us having to care about specific sqlite3 gem versions. This has the effect of passing the flag to every gem installed for jazzy, but that _should_ be innocuous.
Follow-up to #13819.
/cc @julianrex

[ios, build] Make jazzy sqlite3 installation version agnostic

---

platform/ios/CHANGELOG.md
platform/ios/scripts/release-notes.js

Improves the error case when you forget to change the changelog `master` section to reflect the version you’re trying to release, as I did in #13884. Now, you’ll get a recovery suggestion:
> Could not find a release section satisfying 4.9.0-alpha.1 in platform/ios/CHANGELOG.md — did you forget to rename the "master" section to 4.9.0?
Also, updates the changelog so we can release `ios-v4.9.0-alpha.1`. 😅

[ios, build] Changelog fixes for 4.9.0

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.kt

Experimental feature, opted to expose API on MapboxMap as it makes sure that the pointer has been initialized.

Add experimental pointer

---

platform/android/CHANGELOG.md

This PR updates the changelog for v7.1.2 release of the Mapbox Maps SDK for Android.

Update changelog for v7.1.2

---

platform/android/CHANGELOG.md

This pr removes two duplicates which snuck their way into the CHANGELOG when I was doing the alpha.1 release

[android] Removing duplicates from changelog for 7.2.0-alpha.1 

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

See https://github.com/mapbox/mapbox-gl-native/issues/13895
Since we don't provide a view controller or hooks for `-[UIViewController viewWillTransitionToSize:withTransitionCoordinator:]` we call ` [[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications]` to detect device rotation.
However, we do not currently take into account the application's (and view controller's) supported interface orientations. And as such, `layoutSubviews` is called on each device rotation (even if the UI doesn't change).
This ~experimental~ branch/PR adds those checks:
From the Apple documentation for `UIViewController.supportedInterfaceOrientations`:
> When the user changes the device orientation, the system calls this method on the root view controller or the topmost presented view controller …

Check supported interface orientations into account when rotating device/view layout

---

platform/qt/include/qmapbox.hpp
platform/qt/src/qmapbox.cpp
platform/qt/src/qmapboxgl.cpp

There are 3 methods in QMapboxGL which can be static method.
QMapboxGL::metersPerPixelAtLatitude
QMapboxGL::projectedMetersForCoordinate
QMapboxGL::coordinateForProjectedMeters
Add these functions into QMapbox namespace as global functions.
The methods in QMapboxGL are kept for backward compatibility.

[qt] add global projection functions

---

platform/android/src/async_task.cpp
platform/android/src/run_loop.cpp
platform/android/src/run_loop_impl.hpp
platform/android/src/timer.cpp

Fixes #13669
When hitting the tile limit for offline downloads the filesource thread deadlocks. The callback of the http requests triggers the clearing of all outstanding http request (including the one hitting the limit) and then a lock is requested for a second time in the cancel method called from the http request destructor.
In this case, cancel should not request a lock again, but just set the native pointer to 0.

Fix deadlock in http request on hitting tile limit

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/attribution/AttributionParseTest.java
platform/android/gradle/dependencies.gradle

Bumps dependencies and adjust master to correct snapshot version.

Dependencies bump, snapshot version update

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

Users have reported an issue, where fetching current camera position from 
`OnCameraIdleListener#onCameraIdle` after gesture execution would not be up to date. For example, below calls to `map.getCameraPosition().zoom` might've resulted in slightly different values after zooming in/out.
```
map.addOnCameraIdleListener(() -> {
new Handler().postDelayed(() -> Log.i("Test", "Delay at " +  map.getCameraPosition().zoom), 32);
Log.i("Test", "Idled at " +  map.getCameraPosition().zoom);
});
```
During any gesture execution, we were invalidating the camera position only when the frame has been rendered, which is not guaranteed to happen before `#onCameraIdle` is delivered. We should invalidate before delivering that event to ensure consistency.

Invalidate the camera position when gesture finishes

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/SurfaceHolderCallbackAdapter.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRenderThread.java
platform/android/src/map_renderer.cpp
platform/android/src/map_renderer.hpp

[android] hook into surface holder to cleanup renderer on the right thread before the surface is destroyed

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/NativeMapViewTest.kt

With the addition of onDestroy to the test + https://github.com/mapbox/mapbox-gl-native/pull/13926, we shouldn't be hitting the issue of https://github.com/mapbox/mapbox-gl-native/issues/13554 anymore.

Bring back style loading test to native map

---

platform/default/src/mbgl/storage/sqlite3.cpp
platform/ios/app/MBXOfflinePacksTableViewController.m
vendor/icu.cmake

Closes #12606 (by removing the non-actionable note). Also silences/fixes some warnings.
/cc @tmpsantos @kkaefer

[core, ios] Clean up some comments and warnings

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationLayerController.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/StaleStateManager.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.kt

Fixes a regression introduced by https://github.com/mapbox/mapbox-gl-native/pull/13749 where the location layers would re-appear after applying a style with a "layer-below" option, even if the component is disabled.

Keep location component's layers hidden when new style with the "layer-below" option is applied

---

platform/darwin/src/MGLOfflinePack.h
platform/darwin/test/MGLDocumentationExampleTests.swift

Mock `MGLOfflineStorage` in `MGLDocumentationExampleTests`, otherwise we risk starting long-running offline pack downloads that could interfere with other tests. This may fix flakiness we’ve been seeing recently with `MGLOfflineStorageTests`.
/cc @fabian-guerra @riastrad @julianrex

[ios] Mock MGLOfflineStorage in MGLDocumentationExampleTests

---

platform/qt/src/qmapboxgl.cpp
platform/qt/src/qt_conversion.hpp

`QColor::name()` produces `#rrggbb` format where alpha is missing.
Use `rgba(...)` string instead when convert `QColor` to mapbox style.
Note: `QColor::name(QColor::HexArgb)` produces `#aarrggbb` format string,
but mapbox does not support this format apparently.

[qt] fix missing alpha channel for `QColor`

---

platform/android/gradle/android-nitpick.gradle

`android-nitpick` CI job is failing sporadically because the submodule update returns non-zero value which crashes Gradle's execute block. I'm not seeing any other solution for now besides ignoring that.
/cc @tmpsantos @rclee

Ignore android-nitpick's non-zero exit value when updating submodules

---

circle.yml
platform/android/gradle/android-nitpick.gradle
platform/android/gradle/gradle-update-vendor-modules.gradle

We've recently seen `android-nitpick` jobs failing because of uninitialized submodules. This PR tries to initialize the submodules as a CI step (which has been working reliably for all other tests) in addition to the init calls from Gradle (for local development).

Initialize vendor submodules as a CI step

---

metrics/binary-size/index.html

Partner PR to https://github.com/mapbox/mapbox-gl-native/pull/13505 to introduce the `iOS/dynamic` variant to the [binary size chart](http://mapbox.github.io/mapbox-gl-native/metrics/binary-size/) on `gh-pages`.

Add iOS/dynamic variant to binary size chart

---

platform/android/CHANGELOG.md

Cherry pick of https://github.com/mapbox/mapbox-gl-native/pull/13968 for 7.2.0-beta.1 release

[android] Android 7.2.0-beta.1 changelog update cherrypick

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/GLSurfaceViewReopenTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/TextureViewReopenTest.kt
platform/android/gradle/dependencies.gradle
platform/android/src/map_renderer.cpp
platform/android/src/map_renderer.hpp

When using the GLSurfaceView  with setPreserveEGLContextOnPause set to true, the onContextCreated from GLSurfaceView#Renderer is never called when resuming an activity. In this case, MapRenderer#onSurfaceChanged will just assume the EGL context is still alive and create a new Renderer and RenderBackend.
@tobrun Thanks for the test case!
Fixes #13417

[android] fix surface creation after app backgrounding  for surfaceview

---

platform/darwin/src/MGLOpenGLStyleLayer.h
platform/darwin/src/MGLOpenGLStyleLayer.mm
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapView_Private.h
platform/macos/src/MGLMapView.mm
platform/macos/src/MGLMapView_Private.h

Added a property to MGLOpenGLStyleLayer that contains the map view’s underlying OpenGL rendering context.
Fixes #12945.

Expose MGLMapView OpenGL context to OpenGL style layers

---

ci.template
platform/android/scripts/metrics.sh
platform/ios/scripts/metrics.sh
scripts/publish_binary_size.js

This PR alters the CircleCI scripts to publish the binary sizes of the Android and iOS Maps SDKs to a central location on AWS S3.

[build] Log Android/iOS binary sizes to S3

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/StyleLoadTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CustomGeometrySourceTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/GeoJsonSourceTests.java

Refs https://github.com/mapbox/mapbox-gl-native/pull/13913 and replaces all remaining hardcoded delays in favor of the `onIdle` event. This should resolve the flakiness of the tests like https://circleci.com/gh/mapbox/mapbox-gl-native/235346.

Replace remaining hardcoded delays with the idle event

---

circle.yml
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/13987. Refs https://github.com/mapbox/mapbox-gl-native/pull/13974.
Generally, an attempt of loading the native library during unit tests should fail and be caught [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/loader/LibraryLoaderProviderImpl.java#L39), however, if the `MapboxTest` has run beforehand, it'd have provided a static, mocked `Context` for this instance of the JVM and allow an attempted native library load during all following tests which as expected fails to provide a valid directory path resulting in an `NPE` inside of the `ReLinker` implementation.

Clear singleton instance of Mapbox after running unit tests

---

scripts/publish_binary_size.js

Follow up to https://github.com/mapbox/mapbox-gl-native/pull/13505 to adjust the format of the time stamps used when logging metrics data.

[build] Add more granular timestamps for binary metrics collection

---

.gitignore
include/mbgl/util/geo.hpp
platform/glfw/glfw_view.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/util/geo.cpp
test/map/transform.test.cpp

This PR fixes the constraint behavior when crossing the antimeridian, but also:
- Fixes an issue that caused panning to be set to false when the longitude value that was equal to its wrapped one e.g. when doing a full round over the globe;
- Constrain axes separately in LatLngBounds: this fixes an issue when the bounds crosses the antimeridian and only latitude needed to be constrained;
This PR is an alternative to #13906.
Closes #13672, follow up from #13871
/cc @tobrun

LatLngBounds: Fix constrain when crossing antimeridian

---

circle.yml
platform/ios/scripts/install-packaging-dependencies.sh
platform/ios/scripts/trigger-external-deploy-steps.sh

Adds a script to the `ios-release-tag` CI job that triggers an external CI job on our documentation repo (that then builds the docs there).

[ios, build] Trigger automated site and docs generation during releases

---

platform/darwin/src/MGLRendererConfiguration.h
platform/darwin/src/MGLRendererConfiguration.mm
platform/ios/CHANGELOG.md

Without set `localIdeographicFontFamily` would slowdown maps containing CJK fonts. We should switch "localIdeographicFontFamily" default to "on".

[ios] Make PingFang as the default local font family

---

platform/android/README.md

This pr updates the Android README file. There was a dead link and other info needed updating.
This pr also finishes https://github.com/mapbox/mapbox-gl-native/pull/9372 . Once https://github.com/mapbox/android-docs/issues/123 lands, we can update the link to API javadocs in this repo's Android README file.
cc @colleenmcginnis

[android] Android README link and writing updates

---

platform/android/CHANGELOG.md

Adds stable 7.2.0 version changes to Android changelog. Part of today's stable 7.2.0 release.

[android] Update to changelog with stable 7.2.0 changes

---

platform/android/CHANGELOG.md

Cherrypicks https://github.com/mapbox/mapbox-gl-native/pull/14003 into `kombucha` branch for the stable `7.2.0` release of the Maps SDK for Android.

[android] Cherrypick for changelog update for stable 7.2.0 release

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-stripped.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Prepare for ios-v4.9.0 release

---

platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm

`-[UIScreen displayLinkWithTarget:selector:]` states that the selector 
> [...] must have the following signature: `- (void)selector:(CADisplayLink *)sender;`
This PR changes the method's signature to match. In addition, the integration test helper method has been updated.

CADisplayLink method now takes a parameter as required.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.kt

Closes https://github.com/mapbox/mapbox-gl-native/issues/13560.
After investigating the potential map leak it turns out that calls to the `MapView` from a fragment that's in a backstack can be justified in order to save state. Because the system is not going to dispatch save state calls when the view is being destroyed, the only chance to save state for a fragment that contains a map can be when it's already been replaced during a transition.
The only thing we need to ensure is that during saving state process there are no calls to the native peer, because the renderer can already be destroyed, which has already been done in https://github.com/mapbox/mapbox-gl-native/pull/13638, this PR adds a test for that case.

Verify no native method is called when saving state

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java

This pr adds the ability to check whether all `UiSettings` gestures are enabled or not at a certain time. In building some examples, I would've liked to be able to easily check whether _all_ gestures are enabled. It's a pretty specific use case, so no worries if we don't want to add to this SDK because of method count or whatever.

[android] Adding areAllGesturesEnabled() boolean retreival method to UiSettings class

---

platform/qt/src/qmapboxgl.cpp

Otherwise we will have a URL pointing to different servers and potentially different data.

[qt] Also use the base API URL as key for sharing the cache.

---

platform/darwin/src/MGLOpenGLStyleLayer.h

Follow up to https://github.com/mapbox/mapbox-gl-native/pull/13978
This silences the OpenGL deprecation warnings that occurs in projects pulling in the SDK.
e.g.
```
While building module 'Mapbox' imported from /Users/julianrex/Development/<project>/<custom MGLMapView subclass>:1:
In file included from <module-includes>:1:
In file included from /Users/julianrex/Development/<project>/Carthage/Build/iOS/Mapbox.framework/Headers/Mapbox.h:52:
/Users/julianrex/Development/<project>/Carthage/Build/iOS/Mapbox.framework/Headers/MGLOpenGLStyleLayer.h:31:33: warning: 'EAGLContext' is deprecated: first deprecated in iOS 12.0 - OpenGLES API deprecated. (Define GLES_SILENCE_DEPRECATION to silence these warnings) [-Wdeprecated-declarations]
@property (nonatomic, readonly) EAGLContext *context;
```

Mute warnings about OpenGL deprecation.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentActivationOptions.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationComponentActivationOptionsTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationComponentActivationActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationFragmentActivity.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationMapChangeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationModesActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/ManualLocationUpdatesActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_location_layer_activation_builder.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml

This pr adds a builder to activate the `LocationComponent` and resolves https://github.com/mapbox/mapbox-gl-native/issues/13931.

[android] Adding builder pattern for LocationComponent activation

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm

Closes: #9438 
We got a loading issue report from our customer.
I've added a boolean-typed prefetchesTiles property to MGLMapView to fix this issue.
Could you help to review these codes? @1ec5 @friedbunny

Add option to prefetch low-resolution tiles

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/FragmentBackStackActivity.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_backstack_fragment.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml
platform/android/scripts/exclude-activity-gen.json

Closes https://github.com/mapbox/mapbox-gl-native/issues/13967
This PR fixes the issue of not being able to restore a backstacked map fragment. The source of the issue stems from clearing out the OnMapReadyCallback as part of OnDestroyView, this is not correct and should only happen as part of OnDestroy. OnDestroyView can be called multiple times in a fragment life time, removing the callback makes reused fragment unusable as the callback isn't fired anymore.
Looked into adding a regression test but we need androidX for that, follow up ticket in https://github.com/mapbox/mapbox-gl-native/issues/14034. 
For now I'm punting on the manual test added.

Clear callbacks as part of OnDestroy 

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/fragment/MapDialogFragmentTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/MapInDialogActivity.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/14025, next to fixing the sample code, I added a test to catch regressions.

Fix dialog fragment setup, add regression test

---

include/mbgl/math/wrap.hpp
test/map/transform.test.cpp

In `util::wrap()`, when `x` is between `[min, max)`, or when `x` equals to `max`, the returned floating point was slightly modified because of the intrinsics of calculating the remainder value when using `std::fmod`. By early checking these, we can assure that for such cases the returned value is precise. This causes a lot of Transform unit tests to being able to use `ASSERT_DOUBLE_EQ` instead of `ASSERT_NEAR` again.

[core] util::wrap(): std::fmod is not lossless

---

Makefile
circle.yml

Fixes #13322 and reverts #13327.
This PR tries to optimize container resources for CircleCI builds:
- Builds that didn’t specify a [`resource_class`](https://circleci.com/docs/2.0/configuration-reference/#resource_class) have been changed to 2 jobs to match the the default `medium` resource class (for fast-running builds, such as `nitpick`) or were bumped to `large` (e.g., `linux-clang4-*`).
- Android builds have been upgraded to `xlarge` resource class, which is 8 CPU and 16 GB RAM.
/cc @kkaefer @tmpsantos @tobrun

[build] Adjust CircleCI resource classes and job counts

---

README.md

Most of the hybrid libraries have already been removed. Of the remaining libraries, the React Native SDK is the most actively maintained, but it’s transitioning away from Mapbox stewardship: https://github.com/mapbox/react-native-mapbox-gl/issues/1238#issuecomment-461585880. [This OpenStreetMap Wiki article](https://wiki.openstreetmap.org/wiki/Mapbox_GL) has a fuller listing of GL-based libraries enjoying varying degrees of maintenance. (It would also be possible to link to a mapbox-gl-native wiki page, but this existing page is more maintainable.)
/cc @chloekraw @zugaldia @nitaliano

Remove hybrid library table from readme

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/IconFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LayerBitmapProvider.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/ImageSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/BitmapUtils.java
platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/AnimatedImageSourceActivity.java

This PR should enable running the map in the activities that extend from `android.app.Activity` on KItKat and below.
I have verified the behavior on Android versions `9.0` and `4.3` and encountered no issues.

Get vector drawables using AppCompatResources and set them programmatically

---

platform/darwin/test/MGLAttributionInfoTests.m
platform/darwin/test/MGLMapViewTests.m
platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
platform/ios/ios.xcodeproj/xcshareddata/xcschemes/dynamic.xcscheme
platform/ios/test/MGLMapViewLayoutTests.m
platform/ios/test/MGLMapViewScaleBarTests.m

Enable Xcode 10’s [“Randomize execution order”](https://useyourloaf.com/blog/xcode-10-random-and-parallel-tests/) setting for tests, so that we might be alerted to tests that mistakenly rely on shared state from the default deterministic order of execution.
May (or may not) rely on #13943 being fixed first.

[ios] Enable test run-order randomization

---

package.json
platform/node/index.js
platform/node/test/js/cancel.test.js
platform/node/test/js/map.test.js
platform/node/test/js/request.test.js

Looks like `node-clang39-release` and `node-gcc8-debug` bots were failing because we mix ES5 / ES6 module syntax. This PR attempts to use ES6 syntax wherever possible.

[core] Use ES6 import / export syntax for node test harness

---

include/mbgl/map/map.hpp
include/mbgl/map/projection_mode.hpp
platform/node/src/node_map.cpp
src/core-files.json
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
test/map/map.test.cpp
test/map/transform.test.cpp

Instead of having individual APIs for setting axonometric and skew options, create ProjectionMode struct that holds all the relevant options for Axonometric rendering and introduce setter/getter on the Map for those options.

[core] consolidate Axonometric rendering API

---

Makefile
circle.yml
platform/android/README.md
platform/android/build.gradle
platform/android/gradle/dependencies.gradle
platform/android/gradle/gradle-bintray.gradle

Changes the Maps SDK `SNAPSHOT` repository to `https://oss.jfrog.org/artifactory/oss-snapshot-local/`.
/cc @mapbox/android

Publish SNAPSHOTs to oss.jfrog.org

---

platform/qt/src/qmapboxgl.cpp

We were returning the FileSource, it could have expired already. We _need_ to check if the lock() on the weak pointer worked before returning.

[Qt] Fix race when locking a FileSource

---

package.json
platform/node/index.js
platform/node/test/expression.test.js
platform/node/test/js/cancel.test.js
platform/node/test/js/map.test.js
platform/node/test/js/request.test.js

Instead of forcing ES6 module syntax, at this point, it is less disruptive to fix expression tests to use ES5 import syntax.

[core, node] Use es5 syntax for imports in expressions tests

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentNotInitializedException.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt

Updates the docs and throws a `LocationComponentNotInitializedException` if the component is accessed before activation.

Throw an exception if the component is accessed before the activation

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/14013.
Fixes a regression introduced in https://github.com/mapbox/mapbox-gl-native/pull/13791.

Fix quick-zoom + double-tap gestures combo regression

---

platform/android/MapboxGLAndroidSDKLint/src/main/java/com/mapbox/mapboxsdk/lint/MapboxIssueRegistry.kt

Refs https://github.com/mapbox/mapbox-gl-native/issues/14078.
Fixes:
> jetified-mapbox-android-sdk-7.2.0.aar/.../lint.jar: Lint found an issue registry (com.mapbox.mapboxsdk.lint.MapboxIssueRegistry) which did not specify the Lint API version it was compiled with.
This means that the lint checks are likely not compatible.

Explicitly declare MapboxIssueRegistry's lint version

---

include/mbgl/map/camera.hpp
platform/darwin/test/MGLMapViewTests.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/ios/test/MGLMapViewDirectionTests.mm
platform/macos/src/MGLMapView.mm

Fixes #14073 by re-adding the 0-to-360° wrapping for `MGLMapView.direction` that was removed in #14017. Without this wrapping, we’d get ±180° from core, which results in invalid `CLLocationDirection` for the negative half of the rotational spectrum.
This is a two line fix that adds a variety of tests to confirm that the iOS rotation gesture and compass rotation are correct.
/cc @brunoabinader @1ec5

[darwin] Fix direction wrapping

---

platform/node/src/node_map.cpp
platform/node/src/node_map.hpp

The relationship between `NodeMap` and `NodeFileSource` has changed from is-a to has-a. This enables the file source to be reconstructed when canceling a render request and clears the path to refactor `FileSource`.

[node] Change Map/FileSource relationship to composition

---

platform/ios/scripts/deploy-packages.sh

Removes a holdover `clean` step from the days when we built the SDK releases by hand (_uphill both ways and so on_). This should reduce the release build time by a bit (and subsequent rebuilds by a lot), now that it’s able to take advantage of ccache and cached dependencies.
/cc @julianrex

[ios, build] Remove unnecessary clean step from release packaging

---

include/mbgl/map/map_observer.hpp
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm
platform/node/src/node_map.cpp
platform/node/src/node_map.hpp
platform/qt/src/qmapboxgl_map_observer.cpp
platform/qt/src/qmapboxgl_map_observer.hpp
src/mbgl/map/map_impl.cpp
test/src/mbgl/test/stub_map_observer.hpp

Using different exception pointers to specify the loading failure makes
an awkward API. Most users rethrow the exception only to figure out what
type of error happened so it can be reported properly. So replace the
exception pointer with a enum an string description of the failure.

[core] Don't use exceptions in MapObserver::onDidFailLoadingMap

---

platform/android/README.md

This pr updates the Android README to use https://docs.mapbox.com/android/api/map-sdk, which now serves as a permalink to Maps SDK API reference documentation.

[android] Updated Android readme links and writing

---

include/mbgl/storage/default_file_source.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/FileUtils.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/ChangeResourcesCachePathActivity.kt
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_change_resources_cache_path.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml
platform/android/scripts/exclude-activity-gen.json
platform/android/src/file_source.cpp
platform/android/src/file_source.hpp
platform/default/include/mbgl/storage/offline_database.hpp
platform/default/src/mbgl/storage/default_file_source.cpp
platform/default/src/mbgl/storage/offline_database.cpp
test/storage/offline_database.test.cpp

CPs https://github.com/mapbox/mapbox-gl-native/pull/13707 and changes the reinitialization flow to reset the database instead of the whole `FileSource`.
Again, thanks a lot for the contribution @arnekaiser!

Feature: Change path of the resources cache db (CP #13707)

---

benchmark/api/render.benchmark.cpp

There were two PRs that are in mergeable state, yet, had dependencies between each other, therefore, introduced build break on master for benchmark target.

[core] Remove fileSource from render.benchmark.cpp

---

scripts/publish_binary_size.js

It appears that https://github.com/mapbox/mapbox-gl-native/pull/14057 inadvertently broke [`publish_binary_size.js`](https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/publish_binary_size.js) by introducing a new element to [`runs`](https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/publish_binary_size.js#L100) array:
```json
{
"name": "Doxygen coverage",
"conclusion": "SUCCESS",
"title": "6.27%",
"summary": "There is doxygen documentation for 6.271072151045178% of the public symbols (93 out of 1483)"
}
``` 
This addition causes [`run.name.match(/Size - (\w+) ([\w-]+)/)`](https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/publish_binary_size.js#L107) to fail, so this PR ensures that when we're attempting to match against platform/arch, that we're only …

[android, ios] Fix error in binary size collection script

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml

This PR moves texture view debug activity to the top of activities, this to improve execution time of UiAutomator tests.

move TextureView to basic category for UiAutomator scrolling

---

include/mbgl/map/bound_options.hpp
include/mbgl/map/map.hpp
include/mbgl/util/constants.hpp
include/mbgl/util/geo.hpp
platform/android/src/native_map_view.cpp
platform/glfw/glfw_view.cpp
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm
platform/qt/src/qmapboxgl.cpp
src/core-files.json
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp
src/mbgl/util/geo.cpp
test/api/annotations.test.cpp
test/map/map.test.cpp
test/map/transform.test.cpp

Simplify the map api by grouping different bounds related options into `BoundOptions`.
(based on @nagineni's #14059 )

Introduce BoundOptions

---

include/mbgl/style/expression/format_section_override.hpp

So that default value owned by the FormatSectionOverride, can be evaluated based on required context parameters. Therefore, FormatSectionOverride does not need to validate evaluation context.
Even though [PropertyExpression.FormatSectionOverride ](https://github.com/mapbox/mapbox-gl-native/blob/master/test/style/property_expression.test.cpp#L154) is covering such cases, unit test was only failing on debug arm builds, e.g., `make run-android-core-test-arm-v8-PropertyExpression.FormatSectionOverride`.

[core] Forward evaluation context directly to evaluated property

---

circle.yml

We have 2 android jobs running our instrumentation tests. This PR changes the device used for running instrumentation tests on firebase to an different one. This should help us harden against regressions where OS version is important (eg. vector drawable support).

Change firebase device for running gnustl instrumentation tests

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationLayerController.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/14111.

Cache location layer IDs in a set instead of a list

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentConstants.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/14129.

Expose LocationComponent's layer IDs

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/docs/guides/Predicates and Expressions.md
platform/darwin/src/MGLAttributedExpression.h
platform/darwin/src/MGLAttributedExpression.m
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLDocumentationExampleTests.swift
platform/darwin/test/MGLExpressionTests.mm
platform/ios/docs/guides/For Style Authors.md
platform/ios/src/UIColor+MGLAdditions.h
platform/macos/docs/guides/For Style Authors.md
platform/macos/src/NSColor+MGLAdditions.h
platform/macos/src/NSColor+MGLAdditions.mm

[ios, macos] Add text-color support to format expressions.

---

platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm

Fixes a parsing issue when a non-constant expression is passed as `MGLAttributedExpression` parameter.

[ios, macos] Fix format expression parsing.

---

scripts/code-coverage.sh

Refs https://github.com/mapbox/mapbox-gl-native/pull/14145.
Fixes the code coverage report time to follow ISO 8601 and corrects the resulting file formatting.

Correct the code_coverage time to follow ISO 8601
