- include/mbgl/storage/offline.hpp
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Fixes a bug that causes offline packs created prior to #11055 to be marked as `MGLOfflinePackStateInactive` on iOS/macOS.
/cc @tobrun
> [core] Change definition of "complete" so offline packs created before #11055 can complete.

- include/mbgl/storage/offline.hpp
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Cherry picks:
Change definition of "complete" so offline packs created before #11055 can complete. (#14188)
> Cherry picks #14188: [core] Change check in "complete()" for offline packs

- platform/darwin/src/NSExpression+MGLAdditions.mm
- platform/darwin/test/MGLExpressionTests.mm
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Fixes a parsing issue when conditional nested expressions are passed as parameters of `expressionForConditional`.
cc @riastrad
> [ios, macos] Fix conditional expression parsing error.

- ci.template
Permissions removed are no longer needed by CI.
> remove unneeded permissions

- platform/darwin/docs/guides/For Style Authors.md.ejs
- platform/darwin/docs/guides/Predicates and Expressions.md
- platform/darwin/src/MGLAttributedExpression.h
- platform/darwin/src/MGLAttributedExpression.m
- platform/darwin/src/NSExpression+MGLAdditions.mm
- platform/darwin/test/MGLDocumentationExampleTests.swift
- platform/darwin/test/MGLExpressionTests.mm
- platform/ios/docs/guides/For Style Authors.md
- platform/macos/docs/guides/For Style Authors.md
This adds compatibility with JS to support expressions as formatting parameters. Originally the `MGLAttributedExpression` attributes dictionary supported raw constant values, this pr changes that to support only expressions.
> [ios, macos] Support expressions in formatting parameters.

- include/mbgl/map/map_options.hpp
- include/mbgl/storage/resource_options.hpp
- platform/darwin/src/MGLMapSnapshotter.mm
- platform/darwin/src/MGLOfflineStorage.mm
- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
- platform/qt/src/qmapboxgl.cpp
- src/mbgl/map/map_options.cpp
- src/mbgl/storage/resource_options.cpp
It seems we need the reference in `with*` methods - otherwise the last with() call moves the pointer to a rvalue that immediately goes out of scope :disappointed: 
Partially reverts the fluent interface signature change for setters in mapbox/mapbox-gl-native#14189.
> [core] Fix signature of fluent interface setters

- platform/android/gradle/android-nitpick.gradle
- platform/android/scripts/validate-license.py
Closes #14163.
If you forget to update the LICENSE.md for PRs that should have updated it then CI will fail with:
```error
ValueError: An error occurred while validating the license generation. 
Changes were detected to the license generation output 
but weren't committed. Run make android-license and 
commit the changeset to make this validation pass.
> Task :MapboxGLAndroidSDK:androidNitpick FAILED
FAILURE: Build failed with an exception.
```
> Validate license generation with nitpick on CI

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
This just adds the word `not` in front of `fully rendered` in the Javadoc comment for the `OnDidFinishRenderingMapListener` method.
> [android] Quick typo fix for OnDidFinishRenderingMapListener method

- src/mbgl/map/map.cpp
- test/map/map.test.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/13917.
> Harden fetching camera for bounds when padding is excessive

- Makefile
`open` opens the project with the default application specified in Finder, `xed` opens the project with the selected toolchain (`xcode-select -p`) which seems more appropriate.
cc @mapbox/maps-ios
> [ios, macos] Open project using selected toolchain

- src/mbgl/renderer/layers/render_line_layer.cpp
- src/mbgl/renderer/paint_property_binder.hpp
Got this crash in [a node render test](https://circleci.com/gh/mapbox/mapbox-gl-native/252082):
```
Thread 1 (Thread 0x7f2058cf3780 (LWP 5322)):
#0  0x00007f2057100428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f205710202a in __GI_abort () at abort.c:89
#2  0x00007f20570f8bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7f20549ea722 "initialized()", file=file@entry=0x7f20549ea700 "/src/vendor/optional/optional.hpp", line=line@entry=550, function=function@entry=0x7f20549eb6e0 <std::experimental::optional<mbgl::ImagePosition>::operator*()::__PRETTY_FUNCTION__> "T& std::experimental::optional<T>::operator*() [with T = mbgl::ImagePosition]") at assert.c:92
#3  0x00007f20570f8c82 in __GI___assert_fail (assertion=0x7f20549ea722 …
```
> Crash when rendering lines with missing patterns

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
Follow up from https://github.com/mapbox/mapbox-gl-native/pull/14127, closes https://github.com/mapbox/mapbox-gl-native/issues/14224.  We shouldn't call `MapRenderer#OnSurfaceCreated` from the `SurfaceHolderCallback`. This callback is invoked on the main thread and is invoked in pair with the already existing one on the render thread (this was a misassumption made in #14127 that this wasn't invoked in pairs).
This solves the root crash of 
> JNI DETECTED ERROR IN APPLICATION: thread Thread[1,tid=12787,Native,Thread*=0x77ea6c2a00,peer=0x73a481c8,"main"] using JNIEnv* from thread Thread[60,tid=12894,Runnable,Thread*=0x77cccb3000,peer=0x12dcaaa0,"GLThread 12903"]
2019-03-26 20:35:03.152 12787-12787/com.mapbox.mapboxsdk.testapp A/zygote64: java_vm_ext.cc:534]     in call to DeleteGlobalRef …
> Don't call OnSurfaceCreated from the main thread

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
When looking into #14244, I noticed that we are requesting an unnecessary render. Since https://github.com/mapbox/mapbox-gl-native/pull/9576 this is no longer required.
> Remove request render from MapboxMap#onStart

- platform/android/CHANGELOG.md
Backports https://github.com/mapbox/mapbox-gl-native/pull/14256 to `release-liquid`.
> Backport #14256 to liquid

- ci.template
- circle.yml
- scripts/publish_core_codecoverage.js
This collects code coverage ratio from codecov.io for a given commit hash, and upload it to the S3 bucket.
> [core] Add code coverage metrics for core

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxTest.java
We were hitting thread id assertion crash in https://github.com/mapbox/mapbox-gl-native/pull/14170. The source of this is that the filesource is created on the UIThread instead of the main thread.
> Fix thread assertion while running instrumentation test

- src/mbgl/style/expression/value.cpp
- src/mbgl/style/layers/symbol_layer_impl.hpp
- test/style/style_layer.test.cpp
Before this change, symbol layer was only checking whether top level 'text-field' layout property expression is FormatExpression and if it has paint property overrides. This change takes into account that 'text-field' might have nested expressions, thus, requires traversal over child expressions.
Fixes: #14254
Render test: https://github.com/mapbox/mapbox-gl-js/pull/8093
> [core] Traverse expression tree when checking for property overrides

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/integration/BaseIntegrationTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/integration/FragmentBackStackTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/integration/GLSurfaceViewReopenTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/integration/TextureViewReopenTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/widgets/AttributionTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_backstack_fragment.xml
Been running large pool tests on firebase to make sure our testsuite supports all devices:
- refactor to launchmode single instance as this doesn't work for pre 6 and post 9 android os versions
- ignore telemetry dialog test, after multiple iterations, not able to make this run reliably on all devices
- use description selector instead of text as some devices make text uppercase when used in a button
> Support running instrumented tests on more devices

- platform/glfw/main.cpp
Remove unused code that was accidentally added in 7af00a4.
> [glfw] Remove unused map object

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngTest.java
Closes #14216, now that we use Turf as part of the Mapbox Maps SDK for Android in [#11447](https://github.com/mapbox/mapbox-gl-native/pull/11447/files#diff-4be1069e6893cf052bcebaa75621dd96R13). I feel we should use Turf whenever possible (vs writing the goespatial math ourselves). Validated that this PR produces non-NaN values for the use-case described in #14216 and added a test for it.
> LatLng#distanceTo with TurfMeasurement#distance

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationCameraControllerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/GestureDetectorActivity.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14246.
The issue was twofold:
- we were resetting the gestures manager, and because of that recreating the internal listeners, with each component's options update
- we kept the scale/rotation focal points in a listeners' fields and re-validating them only during the start or progress of a gesture, however, when we've reset the gestures manager right between gesture's progress and finish methods, the focal point wouldn't have been initialized and resulted in an `NPE`
> Use a valid gestures focal point when resetting a manager

- circle.yml
I noticed today that I wasn't able to build the offline CLI (`make offline`) on the `release-liquid` branch (separate ticket coming for the specific error). It seems that we currently don't have any CI rules testing that this script correctly builds. This PR adds a new build step to one of the Linux jobs to fix that.
> [linux] Add a new run step to build the offline CLI

- src/mbgl/style/expression/value.cpp
- src/mbgl/style/layers/symbol_layer_impl.hpp
- test/style/style_layer.test.cpp
Before this change, symbol layer was only checking whether top level 'text-field' layout property expression is FormatExpression and if it has paint property overrides. This change takes into account that 'text-field' might have nested expressions, thus, requires traversal over child expressions.
> CP - [core] Traverse expression tree when checking for property overrides

- platform/android/LICENSE.md
- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/BitmapUtils.java
- platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml
Remove support v7 library. Tested on Redmi2(Android 4.4), no issue found for compassView and attribution.
> Remove support v7

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcher.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/14020.
We are dispatching our own camera callbacks when using Android Animators, and even though we are canceling those correctly, we can run into a situation where there are already callbacks scheduled when the map is being destroyed.
This PR also fixes the formatting of the `MapboxMapTest.kt` file.
> Clear camera callbacks' message queue when the map is destroyed

- circle.yml
Changes the `android-gnustl-arm-v7` to run instrumentation tests using HTTC One and API 19.
> Change the firebase device for arm-v7 test run to htc_m8

- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/renderer/layers/render_symbol_layer.hpp
- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/renderer/renderer_impl.cpp
Obviate few extra calls from the renderer impl parts initializing symbol layers.
> [core] Simplify render symbol layer initialization

- src/mbgl/programs/line_program.cpp
- src/mbgl/programs/line_program.hpp
- src/mbgl/renderer/buckets/line_bucket.cpp
- src/mbgl/renderer/buckets/line_bucket.hpp
- src/mbgl/renderer/layers/render_line_layer.cpp
- src/mbgl/renderer/layers/render_line_layer.hpp
- src/mbgl/style/layers/layer.cpp.ejs
- src/mbgl/style/layers/layer_properties.hpp.ejs
- src/mbgl/style/layers/line_layer.cpp
- src/mbgl/style/layers/line_layer_properties.hpp
This patch removes the `RenderLinePaintProperties` by
making `LineFloorwidth` part of the `style::LinePaintProperties`.
It normalizes paint properties evaluation for the line layer.
Tag https://github.com/mapbox/mapbox-gl-native/issues/13812
> [core] Remove RenderLinePaintProperties

- include/mbgl/map/map_observer.hpp
- include/mbgl/renderer/renderer_observer.hpp
- platform/darwin/src/MGLRendererFrontend.h
- platform/default/src/mbgl/gl/headless_frontend.cpp
- platform/glfw/glfw_renderer_frontend.cpp
- src/core-files.json
- src/mbgl/gfx/context.hpp
- src/mbgl/gl/context.cpp
- src/mbgl/gl/context.hpp
- src/mbgl/map/map_impl.cpp
- src/mbgl/map/map_impl.hpp
- src/mbgl/renderer/image_atlas.cpp
- src/mbgl/renderer/image_atlas.hpp
- src/mbgl/renderer/image_manager.cpp
- src/mbgl/renderer/image_manager.hpp
- src/mbgl/renderer/image_manager_observer.hpp
- src/mbgl/renderer/renderer_impl.cpp
- src/mbgl/renderer/renderer_impl.hpp
- src/mbgl/style/image_impl.hpp
- src/mbgl/style/style_impl.cpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/geometry_tile_worker.cpp
- src/mbgl/tile/geometry_tile_worker.hpp
- test/renderer/image_manager.test.cpp
ports https://github.com/mapbox/mapbox-gl-js/pull/7987
This adds a `onStyleImageMissing` method to `MapObserver` that gets called with the id of each missing icon. Missing images can be provided by calling `Style#addImage` from within the listener. If an image is not added it is skipped and tile parsing continues.
```cpp
virtual void onStyleImageMissing(const std::string&)
```
how the listener is called:
- `ImageManager` calls `Renderer::Impl#onStyleImageMissing` with id and callback
- `Renderer::Impl#onStyleImageMissing` calls the observer set by `RendererFrontend` with id and callback
- the platform's `RendererFrontend` calls the `Map::Impl#onStyleImageMissing` on the map thread with id and callback
- `Map::Impl#onStyleImageMissing` calls `MapObserver#onStyleImageMissing` with *just the …
> add onStyleImageMissing to allow dynamically loaded or generated images

- Makefile
- circle.yml
- scripts/clang-tools.sh
This PR changes `clang-tools.sh` so that it no longer always compares against `master`. The script will use `CIRCLE_TARGET_BRANCH`, if it is available (which is exported from https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/environment.js). h/t @friedbunny 
This should help reduce `clang-tidy` fails on release branches.
A variant of this has been tested on the `release-liquid` branch.
> [core] Adds target branch parameter to clang-tools.sh

- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/InstrumentationApplication.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/InstrumentationRunner.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14237.
The common factor in the https://github.com/mapbox/mapbox-gl-native/issues/14237 was leak canary freezing the app to collect the data, which caused the test to extend the "wait-for-idle" timeout and assert, even though the map was blank.
I wasn't able to reproduce the issue locally, so we can reopen https://github.com/mapbox/mapbox-gl-native/issues/14237 if this PR doesn't fix it. In any case, we should disable leak canary during instrumentation tests anyway.
> Disable leak canary during instrumentation tests

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
The permissions are only required when the location component's being enabled, not during activation.
@langsmith would it make sense to adjust the examples in the docs and the demo app?
> Clean up location permissions annotation

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
Moved from: https://github.com/mapbox/mapbox-gl-native/pull/14264
This is a potential work around for for the slowdown reported in https://github.com/mapbox/mapbox-gl-native/issues/14232. This may not address the associated crash.
As @jmkiley [notes in that issue](https://github.com/mapbox/mapbox-gl-native/issues/14232#issuecomment-477804091) the cause appears to be the introduction of `CAEAGLLayer.presentsWithTransaction` in https://github.com/mapbox/mapbox-gl-native/pull/12895 to synchronize OpenGL and UIKit views.
> [ios] Enable/disable presentsWithTransaction to address #14232

- platform/ios/app/MBXViewController.m
- platform/ios/app/missing_icon.json
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLMapViewDelegate.h
- platform/ios/test/MGLMapViewDelegateIntegrationTests.swift
Adds iOS bindings for #14253. 
cc @julianrex @ansis
> [ios]  Add iOS bindings and example for missing icons event.

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
- platform/macos/CHANGELOG.md
Bumps cocoapods spec to v4.10.0-beta.2, updates changelogs.
> [ios] Cocoapods bump to v4.10.0-beta.2

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
- platform/macos/CHANGELOG.md
Cherry picks #14323 into `release-liquid`
> [ios] Cocoapods bump to v4.10.0-beta.2 (#14323)

- circle.yml
- platform/darwin/test/MGLExpressionTests.mm
- platform/ios/ios.xcodeproj/project.pbxproj
- Updates (most of) our CI infrastructure to [Xcode 10.2](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes?language=objc) for `release-mojito`.
- Removes the temporary `ios-debug-xcode-10.2` CircleCI job from #14241.
- Also accepts some updates, including Swift 5.0, and cleans up some other little things.
> [darwin] Update to Xcode 10.2

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Due to the ongoing v4.10.0 push, this is a “light” release with nothing to report in the changelog.
> [ios] Bump to ios-v4.11.0-alpha.1

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/14337.
To keep the current functionality of having `MapboxMap#getStyle` getters that can be invoked at an arbitrary point in time and await style loaded event, we need to separate the list of tthose getters from the listener passed with the setter.
> Clear previous style loaded listener when setting a new style

- src/mbgl/renderer/renderer_impl.cpp
- src/mbgl/tile/geometry_tile.cpp
This PR is doing two things:
* Merges initialization of render items and render sources within single loop, so that sources will have the layers paint properties all evaluated before the update (this is required for the work on https://github.com/mapbox/mapbox-gl-native/issues/13812 )
* Performance improvements:  around 5% improvements for `API_renderStill_reuse_*` benchmark tests.
> [core] Refactor renderer implementation

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
This change is meanly because of https://github.com/mapbox/mapbox-gl-native/pull/14068 which is now throwing an exception if the component is not activated yet. This getter should help users to identify if the component is not activated to prevent usage and therefore exceptions.
To fix that issue in 7.3.0 (called in onDestroy of my fragment):
```kotlin
mapView?.getMapAsync { mapboxMap ->
try {
mapboxMap.locationComponent.isLocationComponentEnabled = false
} catch (e: Exception) {
//do nothing - this needed because mapbox is throwing exception if the location
//is not activated yet. But currently there is no getter to identify this state.
}
}
```
In my case I don't want to request the location permission when the app is starting. Without permission I cannot activate the locationComponent …
> (Android) Added getter for the field isComponentInitialized

- CONTRIBUTING.md
- platform/android/tests/README.md
This pr cleans up some outdated mentions of the Android Maps SDK.
> [android] Small naming tweaks to mentions of Android Maps SDK

- platform/android/src/gl_functions.cpp
Not all GL implementations are following the `glShaderSource` signature specified by Khronos for GLES 2.0.
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glShaderSource.xml
> [android] Fix build with mismatching glShaderSource signature

- include/mbgl/style/conversion_impl.hpp
- test/style/conversion/conversion_impl.test.cpp
- test/test-files.json
Fixes #14348 
- Remove unnecessary temporary and move construct new object
- Remove explicit invocation of the destructor
> [core] Move should not call destructors

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Cherry picking https://github.com/mapbox/mapbox-gl-native/pull/14355 to `release-liquid`.
> [ios] Podspec & changelog update for ios-v4.10.0-beta.3 (CP #1435)

- platform/default/src/mbgl/util/thread_local.cpp
- platform/qt/src/thread_local.cpp
- src/mbgl/util/thread_local.hpp
Introduce type-agnostic base class so we don't need to explicitly specialize for the types we use.
> Refactor ThreadLocal backend

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/http/HttpRequestImpl.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/http/HttpRequestUtil.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxInjector.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/module/http/HttpRequestUtilTest.kt
Capturing from @osana that for some use-cases we need to be able to allow resetting a custom http client. This custom client configuration is static and will remain active until the app is killed. To support all kind of use-cases, allowing to reset is a requirement.
> Allow resetting a custom OkHttp client to the default impl

- src/mbgl/renderer/image_manager.cpp
- test/renderer/image_manager.test.cpp
This fixes a significant bug that I introduced while cleaning up https://github.com/mapbox/mapbox-gl-native/pull/14253. And more importantly, this adds test coverage that should have been included in the original PR.
The cleanup introduced a bug where the onStyleImageMissing observer method was only called before the sprite has been loaded. This fixes that.
> fix firing onStyleImageMissing after sprite has loaded

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java
Checks for the missing configuration right away. Previously, when `Mapbox#geInstance` wasn't called before the view's inflation, the app would crash with the `UnsatisfiedLinkError`:
```
2019-04-08 16:15:43.759 16541-16541/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.mapbox.mapboxsdk.testapp, PID: 16541
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.mapboxsdk.testapp/com.mapbox.mapboxsdk.testapp.activity.maplayout.SimpleMapActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.mapbox.mapboxsdk.maps.MapView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at …
```
> Check for Mapbox#INSTANCE when initializing the MapView

- src/mbgl/renderer/renderer_impl.cpp
- src/mbgl/tile/geometry_tile.cpp
This simplifies the code and make it slightly more performant.
Also, this change enables initialization the `RenderTile.used`
field from inside the source (currently done in render layers).
Tag https://github.com/mapbox/mapbox-gl-native/issues/13812
> [core] Pass only visible render layers to source in renderer

- platform/android/CHANGELOG.md
This PR updates the changelog for the v7.4.0-alpha.2 release of the Mapbox Maps SDK for Android.
> [android] Update changelog for v7.4.0-alpha.2 

- platform/macos/app/Base.lproj/MapDocument.xib
Fixed the “Include CJK characters” checkbox’s outlet connection in the Add Offline Pack sheet of macosapp. Added constraints to the checkbox and resolved other Auto Layout warnings introduced in #13607 by updating frames.
Fixes #14389.
/cc @fabian-guerra @captainbarbosa
> Fix offline pack CJK checkbox in macosapp

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
The PR fixed https://github.com/mapbox/mapbox-gl-native/issues/12897
> [ios] Fix issue wrong position of attribution dialog after rotation 

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14398.
Ignores equal updates to not alter the `FileSource's` counter.
> Ignore equal offline region's download state updates

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/integration/QueryRenderedFeaturesBoxCountTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxCountActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java
Closes #14394, this PR hardens querying the map when the underlying surface is being recreated. With 7.3.0, we changed the lifespan of the renderer to match the surface (instead of the MapView). This change resulted in that the API found on our core renderer isn't usable directly after resuming an Activity. Checking if we have a surface solves that but this is something we need to revisit in the long run in a cleaner way.
This PR adds a regression test, additional javadoc explaining the issue and the actual fix. 
> Query when renderer is being recreated

- src/mbgl/renderer/renderer_impl.cpp
Fixes https://github.com/mapbox/mapbox-gl-native/issues/14402
Running benchmark tests locally does not show regressions.
> [core] Order render items properly across several sources

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/Light.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/light.java.ejs
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/Source.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ThreadUtils.java
Closes #14287, possible solution alternatively the static lazy initialization can be replaced if we can ask users to provide their BuildConfig.DEBUG value through Mapbox.getInstance.
> Only perform thread checking in debug builds

- platform/android/CHANGELOG.md
PR updates changelog to reflect v7.3.1 release of the Mapbox Maps SDK for Android.
> Update changelog for v7.3.1 release

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
Attaching a ViewCallback to get the bitmap content of overlain elements is optional/nullable. 
This PR takes nullability of the ViewCallback in account for snapshot creation.
> [android] - allow snapshot generation without overlain view content

- platform/darwin/test/MGLExpressionTests.mm
- platform/ios/CHANGELOG.md
- platform/ios/src/UIColor+MGLAdditions.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/NSColor+MGLAdditions.mm
Fixes https://github.com/mapbox/mapbox-gl-native/issues/14329
Left: `MGLSymbolStyleLayer.textHaloColor` set to `[UIColor colorWithRed:1 green:1 blue:1 alpha:1]`
Right: `MGLSymbolStyleLayer.textHaloColor` set to `[UIColor colorWithRed:1 green:1 blue:1 alpha:0.4]`
> [ios, macos] Premultiply color values for mgl_color

- platform/darwin/test/MGLExpressionTests.mm
- platform/ios/CHANGELOG.md
- platform/ios/src/UIColor+MGLAdditions.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/NSColor+MGLAdditions.mm
Cherry picking https://github.com/mapbox/mapbox-gl-native/pull/14406 to `release-liquid`.
> [ios, macos] Premultiply color values for mgl_color (🍒#14406)

- platform/android/LICENSE.md
- platform/android/gradle/dependencies.gradle
This PR updates mapbox-java to [v4.6.0](https://github.com/mapbox/mapbox-java/releases/tag/v4.6.0).
> Update mapbox java to v4.6.0

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapChangeReceiver.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/ImageMissingTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java
- platform/android/src/android_renderer_frontend.cpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
closes #14319, refs core integration in https://github.com/mapbox/mapbox-gl-native/pull/14253 and iOS integration in https://github.com/mapbox/mapbox-gl-native/pull/14302.
> Add style image missing binding integration

- platform/darwin/scripts/generate-style-code.js
- platform/darwin/src/MGLSymbolStyleLayer.h
- platform/darwin/src/NSExpression+MGLAdditions.mm
- platform/darwin/test/MGLExpressionTests.mm
Fixes #14393 introduced in https://github.com/mapbox/mapbox-gl-native/pull/14094
Localization was not performed due to the introduction of `MGLAttributedExpression` object. At localization time there was not a proper converter for format expressions, returning the same expression thus avoiding localization.
> [ios, macos] Fix MGLSymbolStyleLayer.text localization issue.

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxCountActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/FragmentBackStackActivity.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewDebugModeActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/NavUtils.java
We recently added `singleInstance `to the AndroidManifest for testing the resume of certain activities. This setup breaks expected app nav experience of the test app. This PR overrides the back behavior of those activities to restore this.
> Provide default nav experience for singleInstance activity

- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/turf/PhysicalUnitCircleActivity.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_physical_circle.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/categories.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml
Example of using `TurfTransformation#circle()`, closes https://github.com/mapbox/mapbox-gl-native/issues/4312. 
The progress bar allows to update the steps precision parameter.
> Circle with radius expressed in physical measurement 

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MarkerContainer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/ShapeAnnotationContainer.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/AnnotationManagerTest.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.kt
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/StyleTest.kt
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/TransformTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/BaseLayerTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/NativeMapViewTest.kt
Cleanup of codebase to program against `NativeMap` interface instead of `NativeMapView` class.
> Program against NativeMap

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
This PR partly addresses https://github.com/mapbox/mapbox-gl-native/issues/13821.
This PR should be considered a stepping-stone towards a larger PR: https://github.com/mapbox/mapbox-gl-native/pull/14222 (that is still on-going). 
* Now takes snapshot in resign active (to avoid GL `display` being called in background)
* Fixes a couple of checks for `_rendererFrontend`
* Blocks rendering (called from `updateFromDisplayLink:`) if in the background (and background rendering not supported).
This PR does not fix the bug where `updateFromDisplayLink` can be called in the background (that's in scope of #14222).
In addition, `updateFromDisplayLink` is currently called from inactive states (e.g. between resigning and entering the background) - this is something we may want to stop doing.
/cc …
> [ios] Ensure glFinish is called when going into the background, and block rendering in the background

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewMapRenderer.java
- platform/android/src/map_renderer.cpp
- platform/android/src/map_renderer.hpp
Closes #14422, Follow up from https://github.com/mapbox/mapbox-gl-native/pull/14395. This PR unifies state management around having a render surface created. Instead of maintaining it in 2 places NativeMapView + MapRenderer. This PR moves it fully to MapRenderer instead. This solves the issue from #14422.  Validated that both setups work correctly for quering with both TextureView as GLSurfaceView. Running tests on mutliple devices on firebase didn't show any issues.
> Unify has surface state handling

- src/mbgl/util/i18n.cpp
This pro-forma change updates the script detection files to reflect changes in [Unicode 12](http://www.unicode.org/Public/12.0.0/ucd/Blocks.txt) and 12.1. Note that vertical orientation properties have been folded into the Unicode Character Database and UTR #50 has been discontinued.
This is a port of mapbox/mapbox-gl-js#8158. Previously #13651.
/cc @ansis @asheemmamoowala
> Update script detection for Unicode 12.1

- platform/android/LICENSE.md
- platform/android/MapboxGLAndroidSDK/.gitignore
- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/MapBaseEvent.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/MapClickEvent.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/MapDragendEvent.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/MapEventFactory.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/MapLoadEvent.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/MapState.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/OfflineDownloadEndEvent.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/OfflineDownloadStartEvent.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/PhoneState.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/module/telemetry/MapEventFactoryTest.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/module/telemetry/SchemaTest.java
- platform/android/build.gradle
- platform/android/gradle/android-nitpick.gradle
- platform/android/gradle/dependencies.gradle
- platform/android/gradle/download-schema.gradle
- platform/android/scripts/validate-license.py
Remove map event creation code from the mapbox-events-android library and add it to map sdk.
Waiting for new version of telemetry sdk after this [PR](https://github.com/mapbox/mapbox-events-android/pull/373) is merged.
> [Android]Add MapEventFactory

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/TileLoadingMeasurementUtils.java
This PR uses [OkHttp Network Interceptor ](https://github.com/square/okhttp/wiki/Interceptors) to measure the time it takes to serve tile requests in the TestApp.
The following measurements are collected:
requestUrl (without token)
responseCode
elapsedMS
device metadata
Here is a log while running with staging token  (added via metadata to Android manifest):
Here is a log while running with production telemetry endpoint (staging token removed from manifest)
Note that due to a [bug](https://github.com/mapbox/mapbox-gl-native/issues/14376) there is no output logging post events to production endpoint.
> [android] Measure TileLoading performance (elapsedMS & responseCode)

- platform/android/LICENSE.md
- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/AccountsManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapboxAccounts.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUrl.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/AccountsManagerTest.java
- platform/android/gradle/dependencies.gradle
This PR proposes a new `AccountsManager` object, instantiated within the regular `Mapbox` object, that manages the state and rotation of SKU tokens. SKU tokens are added to Mapbox API requests only.
It relies on Android's `SharedPreferences` for storage, and proposes a centralized `MapboxConstants.MAPBOX_SHARED_PREFERENCES` to be shared with `FileSource` values.
Before being able to merge this PR we need to add two extra dependencies:
/cc: @friedbunny
> [android] Introduce AccountsManager to support SKU tokens in API requests

- platform/android/CHANGELOG.md
This PR updates the changelog for the v7.4.0-beta.1 release of the Mapbox Maps SDK for Android.
> [android] update changelog for 7.4.0-beta.1 release

- platform/android/CHANGELOG.md
Backports https://github.com/mapbox/mapbox-gl-native/pull/14441 to mojito.
> Backport 14441 to mojito

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/AccountsManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUrl.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
Equivalent of https://github.com/mapbox/mapbox-gl-native/pull/14467 for Android.
/cc: @julianrex
> [android] Enable/Disable SKU token handling

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionError.java
While working on some offline related tickets, noticing that OfflineRegionError is not implementing toString and shows hashcode while using it as a string. This PR makes sure we can see the error code and error message.
> Add toString, hashcode and equals to OfflineRegionError.

- platform/darwin/src/MGLLocationManager.h
- platform/ios/CHANGELOG.md
Fixes #14447 
`MGLLocationManager` protocol is not swift friendly. Optional properties does not work well. This pr changes the properties for explicit setters/getters, although in ObjC there would be no difference; in swift it will require the direct invocation of each.
> [ios] Make MGLLocationManager protocol swift friendly.

- platform/darwin/src/MGLLocationManager.h
- platform/ios/CHANGELOG.md
Cherry picks #14477 into `release-mojito`
> [ios] Make MGLLocationManager protocol swift friendly. (#14477)

- src/mbgl/renderer/image_manager.cpp
- src/mbgl/renderer/image_manager.hpp
- src/mbgl/renderer/renderer_impl.cpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- test/renderer/image_manager.test.cpp
This PR provides basic resource cleanup mechanism for the `ImageManager` class.
Client can perform resource cleanup by invoking [`Renderer::reduceMemoryUse()`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/renderer/renderer.hpp#L58)
preferably, when rendering engine is idle, e.g., when [`onDidBecomeIdle`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/map/map_observer.hpp#L49) callback is called.
> [core] Release unused ImageManager's reources via reduceMemoryUse API

- package.json
- scripts/check_binary_size.js
- scripts/publish_binary_size.js
- scripts/publish_doxygen_coverage.js
Implements [octokit/plugin-retry.js](https://github.com/octokit/plugin-retry.js) for our various scripts' GitHub API usage.
There [have been occasions](https://circleci.com/gh/mapbox/mapbox-gl-native/243765) where GitHub gives us a bogus error code and fails our CI job, so retrying a few times ([three, to be precise](https://github.com/octokit/plugin-retry.js/blob/f44fc3878542e8a0b5be4e03d7bf63ffb684f0f8/lib/index.js#L11)) might end up saving us a failed job in times of bad internet weather.
This currently runs up against a deprecation in the latest octokit/rest release series, which is annoying ~and should be fixed before we merge this~.
```
{ Deprecation: [@octokit/rest] octokit.authenticate() is deprecated. Use "auth" constructor option instead.
at authenticate …
```
> [build] Retry failed GitHub API requests

- src/mbgl/renderer/layers/render_symbol_layer.cpp
This PR changes container type that allows to store segments with same sort key and also sorts text and icon segments differently, so that if segments have same sort-key, icon would take precedence over text.
Render test: https://github.com/mapbox/mapbox-gl-js/pull/8198
Fixes: #14508
Fixes: #14509
> [core] Store type of renderable segment when sorting symbols by key

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/MergeOfflineRegionsActivity.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/FileUtils.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/14485, refs https://android.jlelse.eu/android-weakreferences-how-not-to-5522bb325935/.
> Don't weak reference FileUtils callback

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionStatus.java
This PR aligns `complete/isComplete logic` between core in [offline.hpp](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/storage/offline.hpp#L156) vs android binding in [OfflineRegionStatus](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionStatus.java#L86). I have seen cases where the completed resource count exceeds the required resource count. When that happens, `OfflineRegionStatus#isComplete()` kept returning false while core returned true for `OfflineRegionStatus#complete()`. 
Still need to validate why the completed resource count is going above the required but aligning the isComplete logic seems like a valid short term solution.
> Use same complete/isComplete logic as core

- platform/android/build.gradle
- platform/android/gradle/wrapper/gradle-wrapper.properties
This PR updates to android gradle tooling v3.4.0 and gradle v5.1.1. 
Closes https://github.com/mapbox/mapbox-gl-native/issues/14154
> Bump gradle tooling for AS 3.4

- platform/android/gradle/dependencies.gradle
Backports https://github.com/mapbox/mapbox-gl-native/pull/14524 to `release-mojito`.
> Backport #14524 to mojito

- platform/android/gradle/dependencies.gradle
Initial commit to update Mapbox Java SDK version to 4.7.0-alpha.1 for testing.
If successful the same PR will be used to update to 4.7.0 final release (that will follow the pre-release).
> [android] Mapbox Java SDK bump to 4.7.0

- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/renderer/renderer_impl.cpp
This is the partial revert of https://github.com/mapbox/mapbox-gl-native/commit/8faf47ab5edcbdf6a72e10c57320f72fdec8fbf8
Zoom check at `RenderLayer::needsRendering()` was too strict, which prevented adding tile buckets for the layers whose `minZoom` was just slightly bigger than `zoomHistory.lastZoom` (e.g. lastZoom: 11.9522, min zoom: 12).
Fixes: https://github.com/mapbox/mapbox-gl-native/issues/14523
> [core] Less strict rules for adding render layers to sources

- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/renderer/renderer_impl.cpp
This is the partial revert of 8faf47a
Zoom check at `RenderLayer::needsRendering()` was too strict, which prevented adding tile buckets for the layers whose `minZoom` was just slightly bigger than `zoomHistory.lastZoom` (e.g. lastZoom: 11.9522, min zoom: 12).
Fixes: #14523
> [core] [CP] Less strict rules for adding render layers to sources

- platform/android/MapboxGLAndroidSDK/gradle.properties
We are currently building v7.4.0-SNAPSHOT builds on both release-mojito as master. 
Master needs a bump to v7.5.0 to match the upcoming release-n.
> Update snapshot version to v7.5.0

- vendor/variant-files.json
This PR updates variant to version 1.1.6 which includes [a change](https://github.com/mapbox/variant/pull/171) to reduce the number of static analyzer warnings in iOS, and addresses the bulk of warnings reported in https://github.com/mapbox/mapbox-gl-native/issues/7668.
There have been a number of [changes since 1.1.4](https://github.com/mapbox/variant/compare/v1.1.4...v1.1.6) so this will require testing. I have tested iOS unit and integration tests and `iosapp` and all seems well.
@artemp says:
> the `sizeof(variant<...>)` will change potentially as `index_type` is now 32-bit integer by default if I remember correctly
> [core] Update to variant 1.1.6

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
Checks for a valid superview before installing constraints. This avoids a crash on iOS 9.
The crash was reproduced with `ios-sdk-examples` on an iPad running iOS 9.3. (And this PR was tested on the same.)
/cc @lloydsheng @chloekraw
> [ios] Check for valid superview to avoid crash on iOS 9

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
* Updates pod specs.
* Adds change log entry for #14527. We will want to remove this before stable release since this bug was introduced in `ios-v4.11.0-alpha.2`.
> [ios] Update podspecs for 4.11.0-beta.2

- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Podspec bumps for v4.12.0-alpha.1.
I didn't end up finding any commits [between v4.11.0-beta.2 and v4.12.0-alpha.1](https://github.com/mapbox/mapbox-gl-native/compare/ios-v4.11.0-beta.2...master) that warranted a changelog entry.
> [ios] Update Podspecs for v4.12.0-alpha.1

- platform/ios/DEVELOPING.md
- platform/ios/app/MBXAppDelegate.h
- platform/ios/app/MBXAppDelegate.m
- platform/ios/app/MBXViewController.m
- platform/ios/app/insert_access_token.sh
- platform/ios/benchmark/MBXBenchAppDelegate.h
- platform/ios/benchmark/MBXBenchAppDelegate.m
- platform/ios/benchmark/MBXBenchViewController.mm
- platform/ios/ios.xcodeproj/project.pbxproj
This PR alters the way a Mapbox access token is set for the `iosapp` target.
Previously, this was copy/pasted into the text field of a `UIAlertController`. Because the iOS simulator has been finicky about copy/pasting and manually typing in an access token is not ideal, this step now emulates how access tokens are set in [`ios-sdk-examples`](https://github.com/mapbox/ios-sdk-examples/blob/master/Examples/insert-mapbox-token.sh), where a token is set in a `mapbox_access_token` text file and then is added to the Info.plist via a run script phase at runtime.
> [iosapp] Move token setting to build script

- platform/android/CHANGELOG.md
- platform/android/build.gradle
- platform/android/gradle/wrapper/gradle-wrapper.properties
This PR:
- updates the changelog for release v7.5.0-alpha.1,
- reverts bumping gradle tooling (see context in https://github.com/mapbox/mapbox-gl-native/issues/14563)
> Release v7.5.0-alpha.1

- include/mbgl/style/sources/custom_geometry_source.hpp
- platform/glfw/glfw_view.cpp
- platform/glfw/glfw_view.hpp
- src/mbgl/style/custom_tile_loader.cpp
- src/mbgl/style/custom_tile_loader.hpp
- src/mbgl/style/sources/custom_geometry_source.cpp
`CustomGeometrySource` should keep strong reference to shared thread pool that is used by `CustomTileLoader`.
Access to `CustomTileLoader`'s data members must be synchronized, since they are accessed / modified from multiple threads in the thread pool.
Fixes: #14411
> [core] Keep shared_ptr to thread pool in CustomGeometrySource

- platform/ios/toolchain.cmake
To quieten warnings like
```
CMake Warning (dev) at /Users/distiller/project/platform/ios/toolchain.cmake:92 (set):
implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
/Users/distiller/project/build/ios/CMakeFiles/3.14.1/CMakeSystem.cmake:6 (include)
/Users/distiller/project/build/ios/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at /Users/distiller/project/platform/ios/toolchain.cmake:96 (set):
implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
/Users/distiller/project/build/ios/CMakeFiles/3.14.1/CMakeSystem.cmake:6 (include)
/Users/distiller/project/build/ios/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
This warning is for …
```
> [ios] Uppercase'd "string" to remove cmake warning

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.h
- platform/ios/src/MGLMapView.mm
`-[MGLMapView setVisibleCoordinates:count:edgePadding:direction:duration:animationTimingFunction:completionHandler:]` interprets a negative `direction` as maintaining the current direction instead of rotating to due north.
Fixes #14574.
> Interpret negative direction as unchanged when setting visible coordinates

- circle.yml
CircleCI will soon deprecate Xcode 9.3.0. More details [here](https://discuss.circleci.com/t/removing-support-for-xcode-versions-9-0-0-9-3-0-and-9-4-0/30084).
Moving the project from 9.3.0 to 9.3.1 should have no impact on the CircleCI jobs, and it will help avoid problems due to Xcode 9.3.0 image deprecation. Plus it will help the project to hit fewer Xcode bugs.
> [build] Upgrade from Xcode 9.3.0 to 9.3.1 on CircleCI

- platform/darwin/src/MGLFeature.h
Removed references to MGLStyleValue and MGLInterpolationMode, which were removed in the runup to v4.0.0, from MGLFeature documentation comments.
/cc @mapbox/maps-ios @samfader
> Remove references to MGLStyleValue from MGLFeature documentation

- platform/darwin/src/MGLOfflineStorage.h
- platform/darwin/src/NSExpression+MGLAdditions.h
Clang now supports an additional argument to the [`deprecated`](http://clang.llvm.org/docs/AttributeReference.html#deprecated) attribute that results in a fix-it suggestion, similar to the `renamed:` argument to the `@availability()` attribute in Swift:
This PR upgrades a couple deprecation warnings to use the new syntax. Some occurrences could not be upgraded, because it looks like fix-it suggestions only work correctly when a member is merely renamed, not moved to another class.
> Include fix-it suggestions in deprecation warnings

- src/mbgl/renderer/buckets/symbol_bucket.cpp
- src/mbgl/renderer/buckets/symbol_bucket.hpp
- src/mbgl/text/placement.cpp
Symbols are placed accordingly to their viewport Y order,
if the style `symbol-z-order` is set to `viewport-y`.
This improves rendering of symbol layers, where icons are allowed
to overlap but not text.
> [core] Placement order matches viewport-y sort

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14581.
> Remove missing image log

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/ImageMissingTest.kt
- src/mbgl/style/style_impl.cpp
This patch unblocks tiles rendering if a sprite request has failed, it also enables `onStyleImageMissing` API call for the missing image.
Fixes #14582
> [core] Failed sprite requests do not block tiles rendering

- platform/android/build.gradle
- platform/android/gradle/gradle-bintray.gradle
- platform/android/gradle/wrapper/gradle-wrapper.properties
Closes #14563, the issue stems from bumping gradle to 5.0 which generates a different aar file name as it did with 4.x. Working snapshot build can be seen [here](https://circleci.com/gh/mapbox/mapbox-gl-native/273617).
> Update to gradle 5.1, fix release to bintray

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationCameraControllerTest.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationModesActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_location_mode.xml
Closes https://github.com/mapbox/mapbox-gl-native/issues/14539.
This PR adds an option to provide custom transition duration, zoom, bearing and tilt values for the location tracking transition animation.
> Option to provide custom values for location camera transition

- src/mbgl/renderer/image_manager.cpp
- src/mbgl/renderer/image_manager.hpp
- test/renderer/image_manager.test.cpp
Before this change, `ImageManger`'s 'done' callback for `onStyleImageMissing` observer notification that was created on a renderer thread, could be called from a different thread, therefore, it's not thread safe. For example, on Android platform, callback was invoked from UI thread. This change makes callback to be scheduled on originating thread.
Fixes: #14496
> [core] Schedule invocation of onStyleImageMissing completion callback on the same thread

- platform/ios/src/MGLMapView.mm
Removes obsolete telemetry events that fired whenever users interacted with the map. I didn’t measure it, but I’d guess this may marrrrrrginally improve responsiveness on slow devices.
With the removal of these events here (the only apparent client of them), I would imagine support for them should also be removed upstream in `mapbox-events-ios` — @rclee?
/cc @zugaldia @mapbox/mobile-telemetry @alfwatt @angelanavarro @tobrun
> [ios] Remove obsolete telemetry gesture events

- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/module/telemetry/SchemaTest.java
Quick patch to fix broken builds that are relying on a online resource that recently was updated. 
Longterm looking into another alternative to make this more stable.
> Remove skuId from schema test

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinatorTest.kt
Fixes a bug where the animator coordinator wasn't choosing the shortest path for the layer bearing animation.
Issue example:
> Normalize previous rotation values of the location animator

- include/mbgl/actor/actor_ref.hpp
- platform/default/src/mbgl/map/map_snapshotter.cpp
- platform/default/src/mbgl/storage/default_file_source.cpp
- platform/default/src/mbgl/storage/online_file_source.cpp
- src/mbgl/renderer/image_manager.cpp
So that the lambdas calling these methods do not have to be mutable.
> [core] Make ActorRef methods const

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/FileUtils.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceMapTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceTestUtils.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/ChangeResourcesCachePathActivity.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/MergeOfflineRegionsActivity.kt
Fixes https://github.com/mapbox/mapbox-gl-native/issues/14485 and fixes https://github.com/mapbox/mapbox-gl-native/issues/14297.
Refs https://github.com/mapbox/mapbox-gl-native/pull/14589#issuecomment-489646621.
This PR aims to remove weak references overuse during the offline database merge and resources path change operations. This could lead to the callback reference during any step of the process to be garbage collected if not kept on the client side and result in a no-op.
The initial idea of keeping weak references to the callbacks was to ensure that we are not outliving the hosting activity, which might've been passed with the callback reference. However, the callback is not required to be depending on the hosting activity and it can (and should) be wrapped in a weak reference on …
> Keep strong references to the FileSource/OfflineManager operations callbacks

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewMapRenderer.java
Only allow invoking OnLowMemory with an active renderer. 
Closes #14603
> Harden AndroidRendererFrontend::reduceMemoryUse 

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- src/mbgl/renderer/image_manager.cpp
- src/mbgl/renderer/image_manager.hpp
- src/mbgl/style/style_impl.cpp
- test/renderer/image_manager.test.cpp
This PR cherry-picks the following items to `release-mojito`:
- https://github.com/mapbox/mapbox-gl-native/pull/14620
- https://github.com/mapbox/mapbox-gl-native/pull/14605
- https://github.com/mapbox/mapbox-gl-native/pull/14600
> Cherry-pick to release-mojito

- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Synchronized the macOS changelog with the iOS changelog. Removed some entries about internal changes or iOS-only changes. Recategorized entries.
> Copyedit macOS changelog

- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
coordinatePointMatrix is always used with getZoom():
Projection::worldSize(scale) / std::pow(2, z) is computed as
scale * util::tileSize / std::pow(2, z)
scale is equal to std::pow(2, z).
____________________________________=>
Projection::worldSize(scale) / std::pow(2, z) => util::tileSize.
> Refactor: coordinatePointMatrix skip recomputation

- circle.yml
- platform/darwin/scripts/check-public-symbols.js
- platform/darwin/scripts/update-examples.js
Update CircleCI builds to Xcode 10.2.1 — [container specs.](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-594/index.html)
/cc @julianrex
> [build, darwin] Update CircleCI to Xcode 10.2.1

- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/renderer/tile_pyramid.cpp
- src/mbgl/text/cross_tile_symbol_index.cpp
A RenderTile is already never created for a not renderable tile, guarantied by the checks in `updateRenderables()`.
However, the client code had plenty of `isRenderable()` checks in the render path, which complicated the code and affected rendering performance.
This patch removes the unneeded checks from the client code and puts an assertion to `TilePyramid::addRenderTile()`.
Preparation work for https://github.com/mapbox/mapbox-gl-native/issues/14638
> [core] RenderTile shall never be created for a not renderable tile

- include/mbgl/storage/file_source.hpp
- src/mbgl/map/map_impl.cpp
- src/mbgl/renderer/renderer_impl.cpp
- src/mbgl/renderer/tile_parameters.hpp
- src/mbgl/renderer/update_parameters.hpp
- src/mbgl/text/glyph_manager.cpp
- src/mbgl/text/glyph_manager.hpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/tile_loader.hpp
- src/mbgl/tile/tile_loader_impl.hpp
- test/style/source.test.cpp
- test/text/glyph_manager.test.cpp
- test/tile/custom_geometry_tile.test.cpp
- test/tile/geojson_tile.test.cpp
- test/tile/raster_dem_tile.test.cpp
- test/tile/raster_tile.test.cpp
- test/tile/vector_tile.test.cpp
Avoid unnecessary glyph manager presence check in `Renderer::Impl::()`.
Also, this patch makes `GeometryTile` and `TileLoader` keep strong reference to `FileSource`. Thus, we fix a potential bug: if `Renderer` outlives the `Map` it will hold a stale reference to the `FileSource` instance.
> [core] Create glyph manager at renderer construction time

- platform/android/build.gradle
- platform/android/gradle/gradle-bintray.gradle
- platform/android/gradle/wrapper/gradle-wrapper.properties
Refs https://github.com/mapbox/mapbox-navigation-android/pull/1895#issuecomment-491446694.
Until we find a permanent fix, reverting the gradle/gradle plugin update resolves the issue.
> Revert gradle 5.1/plugin 3.4.0 upgrade

- platform/android/gradle/dependencies.gradle
This PR bumps Mapbox Java SDK to 4.8.0
addresses https://github.com/mapbox/mapbox-java/issues/1024
> [android] Mapbox Java SDK bump to 4.8.0

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/GestureDetectorActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/FragmentBackStackActivity.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/ViewPagerActivity.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DoubleMapActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/DownloadRegionActivity.kt
Fixes below issues:
- Rotating `ViewPager` activity on pages 4-5 changes their style to satellite.
- Re-enabling velocity animators doesn't take rotation into account.
- Backstack Map Fragment example returns straight to features overview instead of popping a fragment.
- Double Map Activity unresponsive after rotation.
- DownloadRegionActivity doesn't deactivate file source when the download is finished.
> QA 7.5.0-alpha.2

- Makefile
- circle.yml
In my personal workflow, I use `make android-check` before opening a PR to validate if no code changes are requested by our static code analysis tools. With some recent PRs, I was able to make `make android-check` succeed but CI was failing over `make run-android-nitpick`. For ease of use, I'm suggesting to include running `nitpick` as part of `android-check`.
> Add nitpick validation to make android-check

- platform/ios/src/MGLMapViewDelegate.h
The newCamera parameter available in the `shouldChangeFromCamera:` delegate is described as if it becomes a modifiable new camera object - this is not entirely true, and this update to the documentation describes how it works a bit more clearly.
cc @captainbarbosa @fabian-guerra
> [ios, macos] clarified documentation for newCamera param of the shouldChangeFromCamera delegate

- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/module/telemetry/SchemaTest.java
A new schema has been published and has broken the test. Opting to ignore this test so it doesn't' happen again (refs #14630). We are discussing upstream how to handle this differently on the schema repo..
> Ignore telemetry schema size test for map load

- platform/darwin/src/MGLNetworkConfiguration.m
- platform/darwin/src/MGLNetworkConfiguration_Private.h
- platform/darwin/src/http_file_source.mm
Renames performance metrics variable names accordingly to Android.
`elapsed_time` -> `elapsedMS`
`resource` -> `requestUrl`
Adds new variables:
`wifiOn`
`responseCode`
> [ios] Rename performance metrics variable names.

- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
I didn't see any changelog differences between [`release-nectar` and `master`](https://github.com/mapbox/mapbox-gl-native/compare/release-nectar...master), since we cut the branch today.
> [ios] Podspec updates for v4.12.0-beta.1

- platform/android/MapboxGLAndroidSDK/gradle.properties
`release-nectar` release branch has been cut, need to update snapshot version to reflect `release-o`.
> Bump snapshot version to 8.1.0

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
This PR aligns our `Snapshot` callback wrapping to be conform to `MapChangeReceiver`. Without this construct if an end developer would throw an exception inside  `SnapshotReadyCallback#onSnapshotReady` it would show this as a native crash with `java pending exception`. This is not great as the developer will think the library is responsible and the shown crash doesn't contain any actionable information. This PR addresses this and will show a clear exception message.
> Wrap snapshot jni callback with try-catch

- src/mbgl/renderer/paint_property_binder.hpp
Add check for optional pattern dependencies and don't bind empty vertex buffers if pattern positions are missing.
Fixes: #14518
> [core] Check if pattern dependencies or pattern positions are missing

- src/mbgl/text/cross_tile_symbol_index.cpp
Tag https://github.com/mapbox/mapbox-gl-native/issues/14708
> [core] CrossTileSymbolIndex::pruneUnusedLayers() does not create extra containers

- src/mbgl/gl/attribute.cpp
- src/mbgl/gl/attribute.hpp
- src/mbgl/gl/context.cpp
- src/mbgl/gl/context.hpp
- src/mbgl/gl/program.hpp
Remove re-linking programs as redundant.
It costs (cheaper to link once than twice) and (subjective) is not that common GL API
usage pattern, although perfectly legal and permitted.
Initial idea, behind the removed code, was to enable work on optimization
that would reduce number of attrib setup calls in case when VAO is not
available (as described in #9433).
As such optimization is not implemented, and it is arguable if it makes sense
to do it now, we can remove re-linking.
Related to closed PRs #9433 and PR #11583.
I have [measured the time spent just on relinking](https://gist.github.com/astojilj/29bd5a5c5dc0b2d9f29ecb660da07fbf) using release build on iPhone SE (A9, same as iPhone 6S):
- 1st run after reboot or installation
Total 37.14ms, average per program:1.86ms
- reopening
Total: …
> Remove re-linking programs approach

- benchmark/benchmark-files.json
- benchmark/storage/offline_database.benchmark.cpp
- platform/default/include/mbgl/storage/offline_database.hpp
- platform/default/src/mbgl/storage/offline_database.cpp
- test/storage/offline_database.test.cpp
Add new APIs for invalidating tiles, effectively forcing Mapbox GL Native to check with the servers if the tiles are valid before using them. This is more efficient then deleting tiles, because in case of valid tiles, they won't get downloaded.
Fixes #4376.
> [core] Add API for invalidating tiles

- benchmark/api/query.benchmark.cpp
- benchmark/api/render.benchmark.cpp
- bin/render.cpp
- platform/android/core-files.json
- platform/default/include/mbgl/gfx/headless_backend.hpp
- platform/default/include/mbgl/gfx/headless_frontend.hpp
- platform/default/include/mbgl/gl/headless_backend.hpp
- platform/default/src/mbgl/gfx/headless_backend.cpp
- platform/default/src/mbgl/gfx/headless_frontend.cpp
- platform/default/src/mbgl/gl/headless_backend.cpp
- platform/default/src/mbgl/map/map_snapshotter.cpp
- platform/ios/core-files.json
- platform/linux/config.cmake
- platform/macos/core-files.json
- platform/node/src/node_map.cpp
- platform/qt/qt.cmake
- test/api/annotations.test.cpp
- test/api/api_misuse.test.cpp
- test/api/custom_geometry_source.test.cpp
- test/api/custom_layer.test.cpp
- test/api/query.test.cpp
- test/api/recycle_map.cpp
- test/gl/context.test.cpp
- test/map/map.test.cpp
- test/map/prefetch.test.cpp
- test/text/local_glyph_rasterizer.test.cpp
- test/util/memory.test.cpp
Refactor out HeadlessFrontend and HeadlessBackend gl independent code to gfx.
Define gl::HeadlessBackend as subclass, instantiated by gfx::HeadlessBackend static factory method.
Overriding the factory enabled.
GL dependent tests are still using gl::HeadlessBackend directly (not through gfx).
> [core] Refactor HeadlessFrontend/Backend: GL separation and factory

- include/mbgl/map/map_observer.hpp
- include/mbgl/renderer/renderer_observer.hpp
- include/mbgl/util/constants.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapChangeReceiver.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/RemoveUnusedImagesTest.kt
- platform/android/src/android_renderer_frontend.cpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- src/mbgl/map/map_impl.cpp
- src/mbgl/map/map_impl.hpp
- src/mbgl/renderer/image_manager.cpp
- src/mbgl/renderer/image_manager.hpp
- src/mbgl/renderer/image_manager_observer.hpp
- src/mbgl/renderer/renderer_impl.cpp
- src/mbgl/renderer/renderer_impl.hpp
- test/renderer/image_manager.test.cpp
This PR introduces following changes:
- Defines constant for ImageManager's cache size `DEFAULT_ON_DEMAND_IMAGES_CACHE_SIZE` that is equal to ~100 8kB sprites.
- Adds `bool onCanRemoveUnusedStyleImage(const std::string&)` method to `MapObserver` interface that is invoked in two cases: OOM and when cumulative size of unused images in the cache goes over `DEFAULT_ON_DEMAND_IMAGES_CACHE_SIZE` limit.
- Android implementation and unit tests
By default, map will remove ***unused images** if application returns `true` from `onCanRemoveUnusedStyleImage` method.
***Unused images**: are images whose requesting tile is destroyed. Map will notify about unused images only if image was provided through `onStyleImageMissing(id)` => `addImage(id)`.
```java
// Android example …
```
> [core][android] Provide API to control eviction of cached images

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Cherry pick https://github.com/mapbox/mapbox-gl-native/pull/14717 for the impending v5.0.0 release.
> [ios] Podspec & changelog updates for v5.0.0 (🍒#4717)

- include/mbgl/platform/thread.hpp
- include/mbgl/util/thread.hpp
- platform/android/src/run_loop.cpp
- platform/android/src/run_loop_impl.hpp
- platform/android/src/thread.cpp
- platform/darwin/src/nsthread.mm
- platform/default/src/mbgl/util/thread.cpp
- platform/qt/src/thread.cpp
- src/core-files.json
- src/mbgl/util/thread_pool.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/14048.
This PR adds a possibility to listen to thread's lifecycle within the thread pool and changes the Android's shared thread pool implementation to attach each of the threads in the pool to the JVM. This way, we are not constantly attaching/detaching JVM to those threads which was forcing GC runs.
> Android specific thread pool that keeps threads attached to JVM

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/types/FormattedSection.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/BackgroundLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ExpressionTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillExtrusionLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HillshadeLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LightTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/light.junit.ejs
- platform/android/scripts/generate-style-code.js
- platform/android/src/conversion/constant.cpp
- src/mbgl/util/color.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/14130.
Fixes the color string round tripping which makes all the places where the string is used compliant with the `rgba` color option from [the spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/#types-color). All other color string types will be converted to `rgba` when being fetched back from the core and we don't have a good mechanism in place to fight that.
String alpha value will be rounded to 2 decimal points.
> Return color string values in the [0-255] range

- platform/macos/CHANGELOG.md
- platform/macos/Mapbox-macOS-SDK-symbols.podspec
- platform/macos/Mapbox-macOS-SDK.podspec
Updated the changelog and CocoaPods podspecs for macOS map SDK v0.14.0. There’s no need to increase the major version at this time, because the pricing model hasn’t changed for this SDK.
> macOS map SDK v0.14.0

- platform/macos/CHANGELOG.md
- platform/macos/Mapbox-macOS-SDK-symbols.podspec
- platform/macos/Mapbox-macOS-SDK.podspec
Cherry-picked #14737 from master into release-nectar.
> macOS map SDK v0.14.0 (release-nectar)

- src/mbgl/layout/symbol_projection.cpp
- src/mbgl/layout/symbol_projection.hpp
- src/mbgl/renderer/bucket.hpp
- src/mbgl/renderer/buckets/symbol_bucket.cpp
- src/mbgl/renderer/buckets/symbol_bucket.hpp
- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/renderer/layers/render_symbol_layer.hpp
- src/mbgl/renderer/renderer_impl.cpp
- src/mbgl/renderer/upload_parameters.hpp
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
`RenderSymbolLayer` does not have to update dynamic vertices of its buckets, this logic is moved to placement (which is already updates opacity vertices).
* fixes #14715 - as assignes `usesVariablePlacement` per bucket
* simplifies the code in `RenderSymbolLayer` (the `RenderSymbolLayer::upload()`	is now omitted).
* symbol buckets are not modified after orchestration finishes - aligned with #14638
> [core] SymbolBucket updates complete at placement stage

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationCameraControllerTest.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.kt
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/StyleTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/14538.
Whenever any of the `MapboxMap#moveCamera`, `MapboxMap#easeCamera`, `MapboxMap#animateCamera`, `MapboxMap#scrollBy`, `MapboxMap#resetNorth`, `MapboxMap#setFocalBearing` is invoked, or the compass is clicked, the location component is going to break location tracking and set the camera mode to `CameraMode#NONE`.
/cc @mapbox/navigation-android
> Break location camera tracking when a developer invoked animation starts

- include/mbgl/util/thread.hpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/14747.
Releases the thread's underlying `Object` before detaching the thread.
I'm currently unable to include a regression test because when the `MapSnapshotter` is run as part of the instrumentation test, the renderer doesn't return the snapshot and freezes. Test app examples work fine. This seems like a separate issue, it is the case even when checking out the code before https://github.com/mapbox/mapbox-gl-native/pull/14450, investigating now.
/cc @tobrun
> Limit thread's scope to release the Object before detaching the thread

- include/mbgl/storage/default_file_source.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceStandaloneTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceTestUtils.kt
- platform/android/src/file_source.cpp
- platform/android/src/file_source.hpp
- platform/default/src/mbgl/storage/default_file_source.cpp
- test/storage/default_file_source.test.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/14334.
I've initially made `DefaultFileSource::setResourceCachePath` synchronous and managed threading on the java side, but now that I think about it, it might be cleaner to use a callback and do the threading on the core side.
> Resume file source to complete resources cache path change

- platform/ios/Integration Test Harness/Assets.xcassets/AppIcon.appiconset/Contents.json
- platform/ios/ios.xcodeproj/project.pbxproj
Fixes #7620 by specifying a default development team for signing the various test iOS apps that exist in this project. This will make bisecting and day-to-day testing easier.
(Also, one harmless Xcode project bump to an icon resource.)
> [ios, build] Specify Mapbox development team for project iOS apps

- platform/android/build.gradle
- platform/android/gradle/gradle-bintray.gradle
- platform/android/gradle/wrapper/gradle-wrapper.properties
Closes #14646, current configuration results in pom packaging instead of aar packaging when used with updated gradle tools and wrapper. More context about this in https://github.com/wupdigital/android-maven-publish/issues/26#issuecomment-411410958. Example working snapshot build:  `com.mapbox.mapboxsdk:mapbox-android-sdk:8.2.0-20190528.072626-4`
> Update maven publishing script to enable aar packaging 

- circle.yml
NodeJS v6 is no longer available [on homebrew](https://formulae.brew.sh/formula/node), so, at @kkaefer’s suggestion, bump to v8. Refs #14650, #14651.
> [build, node] Bump macos CI job to Node 8 & Xcode 10.2.1

- platform/darwin/src/MGLRasterTileSource.h
- platform/darwin/src/MGLStyle.h
- Update ~Mapbox Maps API~ to Mapbox Raster Tiles API, per the recent renaming.
- Also update another link to avoid a redirect.
/cc @HeyStenson @1ec5
> [ios] Update Raster Tiles API name and link

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14136.
Additionally, changes the default zoom rate by 35% based on community feedback. I'd really appreciate any additional feedback on this change (https://github.com/mapbox/mapbox-gl-native/commit/b03c1510352fabd5e6d37d7386237d7c4d2c7c2f) @mapbox/maps-android.
> Option to change the zoom rate. Decrease the default zoom rate by 35%

- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
- platform/android/gradle/native-build.gradle
Closes https://github.com/mapbox/mapbox-gl-native/issues/8886.
`.so` file content of debug build of `.aar` before change:
`.so` file content of debug build of `.aar` after change:
`.so` files of test app after change:
Todo:
> Move building example custom layer to testapp

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
- platform/macos/CHANGELOG.md
Bumps the podspec to `v5.1.0-alpha.1` and updates the changelog.
> [ios] Bump podspec to v5.1.0-alpha.1

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/AccountsManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/AccountsManagerTest.java
- platform/android/gradle/dependencies.gradle
This PR builds on top of https://github.com/mapbox/mapbox-gl-native/pull/14404 and adds support for external SDK clients to be able to manage the tokens on their side disabling the default implementation and returning the token from `SharedPreferences` i.e. the external SDK is responsible for managing the state, rotating and storing (using the proper keys defined in `AccountsManager`) the tokens.
This is an initial proposal, please let me know what you think.
cc @akitchen @frederoni
> [android] Add support for external SDK clients tokens management

- src/mbgl/programs/fill_extrusion_program.cpp
- src/mbgl/programs/fill_extrusion_program.hpp
- src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
fill-extrusion-vertical-gradient is of "property-type": "data-constant" and it shouldn't be computed through property binders.
Compared to the state in #14784, render test now produces proper result.
Fixes: #14784
> [core] Fix: fill-extrusion-vertical-gradient was ignored. #14784

- platform/ios/src/MGLMapView.mm
Allows changing camera when user duplicates content insets.
Related to previous patch and comment:
https://github.com/mapbox/mapbox-gl-native/pull/14664#pullrequestreview-243004376
Thanks @1ec5
> [ios] Content insets border case fix and comment.

- platform/android/gradle/gradle-bintray.gradle
Closes https://github.com/mapbox/mapbox-gl-native/issues/14818.
I've built a release version and published a `SNAPSHOT` to verify the changes. It resolves and builds without any issues. I've also pushed the release to Bintray staging and the correct files were showing up.
> Do not try to package duplicate files in the publication

- platform/darwin/src/MGLGeometry_Private.h
- platform/darwin/src/NSExpression+MGLAdditions.mm
- platform/darwin/src/NSValue+MGLStyleAttributeAdditions.mm
- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.h
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.h
- platform/macos/src/MGLMapView.mm
> [ios] Fix content insets with custom edge padding.

- platform/android/CHANGELOG.md
`8.1.0-alpha.1` release had to be redone because of https://github.com/mapbox/mapbox-gl-native/pull/14822. This pr updates the changelog.
> [android] Update changelog for 8.1.0-alpha.1

- platform/ios/src/MGLAnnotationView.mm
`setCoordinate:` isn't available to regular `MGLAnnotation` (as `coordinate` is `readonly` there), only `MGLPointAnnotation` — so include the latter’s header to avoid “undeclared selector” warnings [here](https://github.com/mapbox/mapbox-gl-native/blob/0bebafadd88f9eed0a3b6c1bf74eb87e2d054ded/platform/ios/src/MGLAnnotationView.mm#L323).
This happened after #14763, though I didn’t dig into why.
> [ios] Fix undeclared selector warning in MGLAnnotationView

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/GeoJsonSourceTests.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14565.
I have noticed, that the only possible scenario when the crash from https://github.com/mapbox/mapbox-gl-native/issues/14565 can occur is when the collection is cleared while it's being converted to an array on our worker thread:
https://github.com/mapbox/mapbox-gl-native/blob/316584fabc4dacaa53e7a208a88f5f87e6f243b0/platform/android/src/geojson/feature_collection.cpp#L14
`ArrayList#toArray` builds an array with a fixed size, adding a `null` padding if necessary, therefore I think, that the collection has to be cleared on one thread, right when the `ArrayList#toArray` is copying the list on the other (after setting the resulting array's size and before finishing copying all of the elements, which creates the `null` padding). …
> Copy features array before passing them to core

- platform/ios/CHANGELOG.md
- platform/ios/Integration Tests/MBGLIntegrationTests.mm
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLMapView+Impl.h
- platform/ios/src/MGLMapView+OpenGL.h
- platform/ios/src/MGLMapView+OpenGL.mm
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLMapView_Private.h
When `MGLMapViewOpenGLImpl` initializes it's `GLKView`, Renderable size is set to `GLKView`'s framebuffer size. Unfortunately, `GLKView`'s framebuffer size is unknown until it is ready, i.e., when `GLKViewDelegate`'s draw method is called.
This PR adds `virtual void layoutChanged()` method to `MGLMapViewImpl`  that should be called when map's UIView is laid out, so that `Renderable` size can be calculated from the `UIView` bounds.
Fixes: #14807
> [ios] Calculate size of a MGLMapViewOpenGLImpl renderable from MGLMapView bounds

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/geometry/GeoJsonConversionTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/ImageMissingTest.kt
Two small patches improving test stability:
- increase timeout of image missing test
- use GeoJsonSource instead of CustomGeometrySource
closes #14801 
closes https://github.com/mapbox/mapbox-gl-native/issues/14852
> Improve test stability 

- platform/android/gradle/dependencies.gradle
This pr bumps the Telemetry dependency to  [`4.5.1`](https://github.com/mapbox/mapbox-events-android/issues/414) for the Maps SDK.
> [android] Bumping Android telemetry to 4.5.1

- platform/android/CHANGELOG.md
This pr updates the Android changelog for the 8.1.0-alpha.2 `oolong` release
> [android] updated changelog for 8.1.0-alpha.2

- platform/android/src/style/value.hpp
`mbgl::android::Value` move assignment operator is implicitly deleted.
> [android] Fix compilation warning with updated clang

- platform/default/src/mbgl/gl/headless_backend_osmesa.cpp
HeadlessBackend seems to be part of the mbgl::gl namespace. Since OSMesaBackendImpl is only in the mbgl namespace this code does not compile.
Since this file is in the mbgl/gl folder I think it makes sense to just put the whole thing in the mbgl::gl namespace.
> [core] Fix namespace issue with OSMesa

- src/parsedate/parsedate.cpp
Rename curlx_sltosi to mbgl_curlx_sltosi to avoid collision when liking with libcurl statically.
> [core] Renamed to avoid collision with libcurl

- benchmark/parse/tile_mask.benchmark.cpp
- include/mbgl/tile/tile_id.hpp
- src/mbgl/algorithm/update_tile_masks.hpp
- src/mbgl/annotation/render_annotation_source.cpp
- src/mbgl/annotation/render_annotation_source.hpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_source.hpp
- src/mbgl/renderer/render_tile.cpp
- src/mbgl/renderer/render_tile.hpp
- src/mbgl/renderer/sources/render_image_source.hpp
- src/mbgl/renderer/sources/render_raster_dem_source.cpp
- src/mbgl/renderer/sources/render_raster_dem_source.hpp
- src/mbgl/renderer/sources/render_raster_source.cpp
- src/mbgl/renderer/sources/render_tile_source.cpp
- src/mbgl/renderer/sources/render_tile_source.hpp
- src/mbgl/renderer/tile_pyramid.cpp
- src/mbgl/renderer/tile_pyramid.hpp
- src/mbgl/tile/tile.hpp
- test/algorithm/update_tile_masks.test.cpp
Tile pyramid is no longer operating with `RenderTiles` and does not perform rendering operations: upload, finish render. 
Rationals: render tiles belong to rendering, and tile pyramid belongs to orchestration.
tag #14638
> [core] Refactor tile pyramid

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMap.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/LatLngBoundsForCameraActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_bounds.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/actions.xml
- platform/android/src/native_map_view.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/14875
Fixes issue noted in #14875 and adds a manual test for it.
> Fix reset behavior for setLatLngBoundsForCameraTarget

- platform/android/LICENSE.md
- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/loader/LibraryLoaderProviderImpl.java
- platform/android/gradle/dependencies.gradle
This PR changes our library loader from relinker to soloader. We initially switched to relinker based on advice given by Google in their NDK changelog. Now with getting feeedback as  https://github.com/mapbox/mapbox-gl-native/issues/14888 and https://github.com/mapbox/mapbox-gl-native/issues/14428. Let's move forward using [soloader](https://github.com/facebook/SoLoader) from Facebook. It should be more stable.
Closes #14428 
Closes #14888
> Change library loader to soloader

- platform/darwin/src/MGLAccountManager.m
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/test/MGLAccountManagerTests.m
~`performSelector` doesn't support return values.~ `methodForSelector` doesn't seem to return any values. We can use NSInvocation’s `getReturnValue`, Swift’s `Selector.takeUnretainedValue()`, `performSelector`, or `-[NSObject valueForKeyPath:]`, which is the approach I went with here.
cc @friedbunny
> [ios] Fix external sku token getter

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14897
Regression of #14804
> Allow null updates to GeoJsonSource#setGeoJson

- platform/android/gradle/dependencies.gradle
This pr removes `mapboxJavaServices` from the Android dependency file. It's not used anywhere in this repo.
> [android] Remove mapboxJavaServices dependency

- platform/darwin/src/http_file_source.mm
- platform/darwin/test/MGLResourceTests.mm
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/macos/macos.xcodeproj/project.pbxproj
Fixes #14820
Also added tests for both iOS & macOS. 
Currently macOS does not add `sku` or `offline` query parameters. We will need to consider this alongside https://github.com/mapbox/mapbox-gl-native/issues/14835.
> [ios, macos] Added offline query parameter (for iOS)

- platform/ios/benchmark/MBXBenchViewController.mm
- platform/ios/ios.xcodeproj/project.pbxproj
- src/mbgl/gfx/context.hpp
- src/mbgl/gl/context.cpp
- src/mbgl/gl/context.hpp
- src/mbgl/renderer/renderer_impl.cpp
https://github.com/mapbox/mapbox-gl-native/pull/14383 add a `glFlush` call to `performCleanup`. However, that function gets called after every frame. This PR adds a `reduceMemoryUsage` call and moves the `glFlush` call to it so that it only gets called when the app goes to the background, or gets a memory warning.
/cc @julianrex
> Fix rendering performance regression

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- src/mbgl/geometry/feature_index.cpp
The bug was caused by an issue with the `sortIndex` calculation, i.e. after a polygon geometry was added to the feature index, its inner rings happened to have the same sort indexes as the features added at the next calls |=> the features added after the polygon were dropped from the `query()` result.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/14722
> [core] Fix queryRenderedFeatues bug

- platform/ios/app/MBXState.h
- platform/ios/app/MBXState.m
- platform/ios/app/MBXStateManager.h
- platform/ios/app/MBXStateManager.m
- platform/ios/app/MBXViewController.m
- platform/ios/ios.xcodeproj/project.pbxproj
This PR refactors how `iosapp` saves the current map when the application's state changes. Instead of registering values within `NSUserDefaults` inside `MBXViewController`, we'll now make use of a `[MBXStateManager sharedManager]` singleton, which will become responsible for saving/restoring/resetting the state of the map.
> [iosapp] Introduce map state manager

- benchmark/storage/offline_database.benchmark.cpp
- include/mbgl/storage/default_file_source.hpp
- platform/default/include/mbgl/storage/offline_database.hpp
- platform/default/src/mbgl/storage/default_file_source.cpp
- platform/default/src/mbgl/storage/offline_database.cpp
- test/storage/offline_database.test.cpp
This new API will really remove the tiles and shrink the database by calling `VACUUM`, which can be potentially slow.
Fixes #14549
> [core] Add API for clearing tiles from the ambient cache

- platform/android/CHANGELOG.md
Cherry pick of https://github.com/mapbox/mapbox-gl-native/pull/14916 for 8.1.0-beta.1 release
> [android] Android 8.1.0-beta.1 changelog update cherrypick

- platform/darwin/docs/guides/Working with GeoJSON Data.md
This PR contains a small grammatical fix for [this iOS guide](https://docs.mapbox.com/ios/api/maps/5.0.0/working-with-geojson-data.html).
@friedbunny in addition to the grammar, is the content I added here correct?
> [iOS, docs] Fixes grammatical issue in GeoJSON guide

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Bumps the podspec to v5.1.0-beta.1
> [ios] Bump podspec to v5.1.0-beta.1

- .gitignore
- platform/ios/DEVELOPING.md
- platform/macos/DEVELOPING.md
- scripts/config.xcconfig.in
This allows developers to optionally set compiler flags without including for everyone.
This will allow us to experiment with different options locally (for example, `warnings-as-errors` as briefly discussed here: https://github.com/mapbox/mapbox-gl-native/pull/14453#issuecomment-486430908), before deciding whether to enable for all.
The `developer.xcconfig` file is gitignore'd and should remain so.
> [ios, macos] Optionally include a developer xcconfig file in generated config.xcconfig file.

- Makefile
- platform/ios/DEVELOPING.md
Adds a `MORE_SIMULATORS` option to our `make ios-test` commands that enables more device types and iOS versions. 
Example usage: `make ios-test MORE_SIMULATORS=YES`
- This is useful only locally or on actual Mac hardware and doesn’t address #10708 — cloud CI providers like CircleCI do not provide the resources necessary to execute parallel simulators in a reliable or performant way.
- If you run this now, there are many failing tests. This is a starting point — we must go through the test failures and fix them.
- Use the new `make ios-install-simulators` command to install the necessary simulators. This uses [xcversion](https://github.com/xcpretty/xcode-install).
- Bumps our default test simulator device from iPhone 6 to iPhone 8. Xcode 11 and iOS 13 will drop support for iPhone 6, while …
> [ios, build] Add MORE_SIMULATORS option to iOS make commands

- src/mbgl/renderer/render_layer.cpp
So it can be filtered by the SDKs using a Log::Observer.
> [core] Change severity of too many data-driven properties to "Info"

- circle.yml
This PR allows to symbolicate native stacktraces we get on Firebase.
> Store shared libraries as CI artefact

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/utils/ColorUtilsTest.kt
Refs https://github.com/mapbox/mapbox-android-demo/issues/1090.
Follow up from https://github.com/mapbox/mapbox-gl-native/pull/14233.
Colors components coming from the core can be sporadically be represented with floating point numbers due to the color parser imprecision. We still should accept and floor those.
> Accept floating numbers during core->platform color conversion

- benchmark/storage/offline_database.benchmark.cpp
- include/mbgl/storage/default_file_source.hpp
- platform/default/include/mbgl/storage/offline_database.hpp
- platform/default/src/mbgl/storage/default_file_source.cpp
- platform/default/src/mbgl/storage/offline_database.cpp
- platform/glfw/glfw_view.cpp
- platform/glfw/glfw_view.hpp
- platform/glfw/main.cpp
- test/storage/offline_database.test.cpp
- API for resizing the ambient cache.
- Make it possible to disable the ambient cache.
- Performance benchmarks.
- Fix tile deletion and invalidation not affecting resources that are not tiles.
> [core] Add more cache management APIs

- platform/android/CHANGELOG.md
This pr removes a duplicate entry for https://github.com/mapbox/mapbox-gl-native/pull/14890 in the Android CHANGELOG.
https://github.com/mapbox/mapbox-gl-native/pull/14890 was already listed in the CHANGELOG's `8.0.1` section.
> [android] Removed duplicate soloader changelog line

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/LocationModesActivity.java
Adds `CameraMode.NONE_COMPASS` and `CameraMode.NONE_GPS` to the Android test app's `LocationModesActivity` to visualize what those two modes actually look like.
> [android] Added CameraMode.NONE_COMPASS and CameraMode.NONE_GPS to LocationModesActivity

- Makefile
- platform/ios/DEVELOPING.md
Follow-up to #14903, adding the ability to specify specific iOS version(s) and skip/exclusively run specific tests.
To run the static analyzer on iOS 12 and 11, but only running `MGLOfflineStorageTests` tests:
```
make ios-static-analyzer IOS_LATEST=YES IOS_11=YES ONLY_TESTING=test/MGLOfflineStorageTests
```
> [ios, build] Add more specific iOS simulator flags for make commands

- platform/default/src/mbgl/storage/offline_database.cpp
- test/storage/offline_database.test.cpp
- The SQL query used for checking if the tile was already in the cache was wrong.
- Tiles being refereed by two or more regions were not always counted as one.
- Despite making one extra query, benchmarks are showing 8% performance improvement, because we are narrowing the query results by adding one extra filter.
Fixes #13437.
> [core] Fix offline regions reporting the wrong number of tiles

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactoryTest.kt
PR fixes behavior of `CameraUpdateFactory#newLatLngBounds` to also allow creating a bounds with bearting/tilt configuration.
> CameraUpdateFactory#newLatLngBounds with camera tilt and bearing

- platform/darwin/test/MGLOfflineStorageTests.mm
Fixes #14928, where `-[MGLOfflineStorageTests testAddFileContent]` failed when run in parallel on multiple simulators.
That issue appears to have been caused by directly moving fixtures around from the build folder to inside the user’s simulator folders, which caused exceptions when multiple simulators expected a stable directory/file structure.
Since our fixtures are copied into the test bundle already, manually moving and setting permissions on them should be unnecessary. These tests have shown past instability (#12999, https://github.com/mapbox/mapbox-gl-native/pull/12911#issuecomment-422600110, #12913), but I’m hoping we can rely on a more conventional way of supplying test fixtures.
(These tests were originally added in #12791.)
I also wrapped subsections of `testAddFileContent` in …
> [ios] Simplify -[MGLOfflineStorageTests testAddFileContent]

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
- Bumped podspecs for `ios-v5.1.0` final release.
- Added changelog entries for #14808, #14696, and #14386 (which was in `ios-v5.0.0`).
> [ios] Prepare for ios-v5.1.0 release

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Cherry-pick of #14967 for `release-oolong` and `ios-v5.1.0`.
> [ios] Prepare for ios-v5.1.0 release (release-oolong)

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14598.
Because the double tap event can be canceled and stop delivering events whenever `ACTION_CANCEL` or `ACTION_POINTER_DOWN` is dispatched, we need to make the `#onScaleEnd` callback responsible for re-enabling the move detector as well.
> Ensure to re-enable move when quickzoom finishes

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/http/HttpRequestImpl.java
Backports #14965 and #14971 to `release-oolong`
> Backport #14965 and #14971 to oolong

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/http/HttpRequestImpl.java
Refs https://github.com/mapbox/mapbox-gl-native/issues/14910, while it doesn't resolve the issue it should make the system library crash when performing an SSL handshake less frequent.
> Limit concurrent request for Android 4.4 and below to 10

- platform/android/CHANGELOG.md
Updates the Android changelog for the stable `8.1.0` release (`oolong`)
> [android] Updated Android changelog for stable 8.1.0 release (oolong)

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
Fixes #14886, where the tilt gesture didn’t end when a user lifted one of their two fingers.
> [ios] Require two fingers for duration of tilt gesture

- platform/android/CHANGELOG.md
This pr updates the Android changelog with information about a rare crash that we found via instrumented testing.
> [android] Updated Android 8.1.0 changelog with kitkat crash info

- platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m
- platform/ios/Integration Tests/MGLCameraTransitionTests.mm
This PR fixes some annotation selection integration tests that were failing because of differences in device screen size - the sizes of the annotation vs the callout meant that some callout views would be wholly contained with the parent views, where others wouldn't (when the annotation was moved on-screen).
The tests assumed that the callout views were wider than the annotation, which wasn't the case with large screens. To minimize changes, I have reduced the width of the annotation, and tested across current simulators.
This fixes https://github.com/mapbox/mapbox-gl-native/issues/13744 and should address @friedbunny's comment here: https://github.com/mapbox/mapbox-gl-native/pull/14381#pullrequestreview-248474183
> [ios] Fix failing annotation selection integration tests

- platform/darwin/test/MGLMapViewTests.m
- platform/ios/CHANGELOG.md
- platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m
- platform/ios/src/MGLMapView.h
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.h
- platform/macos/src/MGLMapView.mm
Added variants of several animated MGLMapView methods that accept completion handlers. This change does exacerbate the proliferation of camera-related methods in MGLMapView to a degree, but it’s in keeping with the principle that asynchronous operations should have completion handlers. Developers should use these methods instead of the camera-related MGLMapViewDelegate methods for more readable and less buggy code. Eventually, we may be able to call the delegate methods only in response to a user gesture or location update, in keeping with Cocoa best practices.
The specific methods added are:
* `-[MGLMapView setVisibleCoordinateBounds:edgePadding:animated:completionHandler:]`
* `-[MGLMapView setContentInset:animated:completionHandler:]` (iOS)
* `-[MGLMapView …
> Add completion handlers to animated MGLMapView methods

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinatorTest.kt
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/14938.
Wrong icon rotation was persisting after switching from `GPS` to `NORMAL`/`COMPASS` render mode because the `GPS` mode animator was still running after the mode has been switched and was overwriting the updated rotation.
> Reset location layer animators when render mode changes

- circle.yml
This PR changes the Firebase Test Lab device to Nexus 7 with API level 21. 
API 19 has become unreliable for CI usage, more context in and closes https://github.com/mapbox/mapbox-gl-native/issues/14910.
> Change Firebase test lab device to Nexus 7

- platform/darwin/test/MGLClockDirectionFormatterTests.m
- platform/darwin/test/MGLCompassDirectionFormatterTests.m
- platform/darwin/test/MGLCoordinateFormatterTests.m
- platform/darwin/test/MGLNSStringAdditionsTests.m
- platform/ios/test/MGLMapAccessibilityElementTests.m
Better surface that certain tests require an English locale to pass, ticketed at #14908.
Also made `MGLNSStringAdditionsTests` ignore the current device locale.
/cc @1ec5 @fabian-guerra
> [darwin] Add warning about certain tests requiring en_US locale

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapInstrumentationTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/VisibleRegionTest.kt
- platform/android/src/native_map_view.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/14985.
The issue does not originate from the `LocationComponent` directly, but from the fact that we were not invalidating the camera when the padding was set.
Before:
After:
> Invalidate camera when setting a padding

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/log/Logger.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/log/LoggerTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/14616, refs [this](https://github.com/mapbox/mapbox-gl-native/issues/14616#issuecomment-505201112) comment.
All log invocations on core are wired through `Logger#log(severity, tag, message)`. This PR allows to configure a certain log level and all `Logger#x` and `Logger#log`  will adhere to this level.  
cc @chloekraw @tmpsantos
> Add setVerbosity to Logger, add LogLevel IntDef

- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/AppCenter.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/integration/BaseIntegrationTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/BaseLayerTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/NativeMapViewTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/BaseTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/fragment/MapDialogFragmentTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/ImageMissingTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/RemoveUnusedImagesTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/offline/OfflineManagerTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/offline/OfflineUtilsTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/render/RenderTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceMapTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceStandaloneTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/storage/FileSourceTestUtils.kt
- platform/android/gradle/dependencies.gradle
According [docs](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/espresso) of MicroSoft AppCenter lib, we need Import AppCenter packages and insert `ReportHelper` declaration into all test classes, so that all instrumentation test could run on AppCenter on multiple devices.
> [android] Add MicroSoft AppCenter lib.

- platform/darwin/src/run_loop.cpp
In the deconstructor of run_loop.cpp there is an assert that checks to make sure the Scheduler is null before setting it to null. In some rare scenarios where the app is being put into the background or closed the Scheduler can be null before the deconsturctor is called. This can cause an unnecessary crash. Since the goal here is to just set the Scheduler to null either way, it should not matter what the state of the Scheduler is before the function call.
> Remove assert from deconstructor of run_loop.cpp

- cmake/sqlite.cmake
GCC 8.0 now implements the same `cast-function-type` warning present in CLang.
Reference: https://gcc.gnu.org/gcc-8/changes.html
> [build] GCC 8.0 now implements 'cast-function-type'

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java
This PR brings back the regression test introduced with https://github.com/mapbox/mapbox-gl-native/pull/13705. 
This was removed while adding new features. 
cc @pozdnyakov
> bring back manual opacity regression test

- platform/node/src/node_map.cpp
- platform/node/src/node_map.hpp
- platform/node/src/node_request.cpp
- platform/node/src/node_request.hpp
Might solve https://github.com/mapbox/mapbox-gl-native/issues/12252
> Fixes problems associated with node 10 and NAN

- platform/ios/CHANGELOG.md
- platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m
- platform/ios/app/MBXViewController.m
- platform/ios/src/MGLMapView.h
- platform/ios/src/MGLMapView.mm
- platform/ios/test/MGLAnnotationViewTests.m
- platform/macos/src/MGLMapView.h
- platform/macos/src/MGLMapView.mm
Deprecates various `MGLMapView` methods and replaces them with completion hander versions being added in #14381.
This follows our best practices for deprecation, as outlined in https://github.com/mapbox/mapbox-gl-native/pull/14560#issuecomment-493261502.
This will need changelogging and currently targets the #14381 branch — we should figure out the changelog when we merge that and retarget this PR.
/cc @1ec5 @julianrex
> [ios, macos] Deprecate methods in favor of new completion handler versions

- platform/darwin/src/MGLAccountManager.h
- platform/darwin/src/MGLOfflineStorage.h
- platform/darwin/src/MGLStyle.h
- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.h
Removes previously deprecated methods and properties that had been marked as `unavailable` at least a year ago in #11205 (and usually several years ago).
- `-[MGLMapView metersPerPixelAtLatitude:]`: https://github.com/mapbox/mapbox-gl-native/pull/3393
- `MGLMapView.bundledStyleURLs`: https://github.com/mapbox/mapbox-gl-native/pull/2746
- Paint classes: https://github.com/mapbox/mapbox-gl-native/pull/8953
- And others.
Also updates some `MGLOfflineStorage` documentation to use the current key names.
> [ios] Remove previously deprecated unavailable methods and properties

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
- Bumps versions for `ios-v5.2.0-alpha.1` (`release-p`).
- Adds a changelog entry for #14958 and rearranges things a bit.
> [ios] Release ios-v5.2.0-alpha.1

- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
The versions I bumped to in #15012 had a period instead of a dash between the numbers and pre-release string, which meant that their framework binary URLs were incorrect
Because we no longer recommend people directly use (most of) these podspecs and since CocoaPods prevented us from pushing to `trunk`, the impact of this mistake is minimal and I don’t believe we’ll need to re-tag or rebuild the release.
> [ios] Fix ios-v5.2.0-alpha.1 podspec versions

- include/mbgl/storage/resource_options.hpp
I have warnings-as-errors enabled for iOS builds, and this line fired:
`Parameter 'Whether' not found in the function declaration` on
https://github.com/mapbox/mapbox-gl-native/blob/0ca8ea6f169149cd414a65f40d0f7bdd40f3cca3/include/mbgl/storage/resource_options.hpp#L109
This change was introduced in https://github.com/mapbox/mapbox-gl-native/pull/14941
> [core] Minor change to silence documentation warning on iOS.

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/offline/CacheTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/offline/OfflineManagerTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/DeleteRegionActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/storage/CacheManagementActivity.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_cache_management.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml
- platform/android/scripts/exclude-activity-gen.json
- platform/android/src/offline/offline_manager.cpp
- platform/android/src/offline/offline_manager.hpp
- platform/android/src/offline/offline_region.cpp
- platform/android/src/offline/offline_region.hpp
Follow up from https://github.com/mapbox/mapbox-gl-native/pull/14925
Checklist:
> Cache management API

- include/mbgl/style/layer_properties.hpp
- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/renderer/paint_property_binder.hpp
- src/mbgl/renderer/render_orchestrator.cpp
- src/mbgl/renderer/tile_pyramid.cpp
- src/mbgl/style/layers/background_layer_properties.cpp
- src/mbgl/style/layers/background_layer_properties.hpp
- src/mbgl/style/layers/circle_layer_properties.cpp
- src/mbgl/style/layers/circle_layer_properties.hpp
- src/mbgl/style/layers/fill_extrusion_layer_properties.cpp
- src/mbgl/style/layers/fill_extrusion_layer_properties.hpp
- src/mbgl/style/layers/fill_layer_properties.cpp
- src/mbgl/style/layers/fill_layer_properties.hpp
- src/mbgl/style/layers/heatmap_layer_properties.cpp
- src/mbgl/style/layers/heatmap_layer_properties.hpp
- src/mbgl/style/layers/hillshade_layer_properties.cpp
- src/mbgl/style/layers/hillshade_layer_properties.hpp
- src/mbgl/style/layers/layer_properties.cpp.ejs
- src/mbgl/style/layers/layer_properties.hpp.ejs
- src/mbgl/style/layers/line_layer_properties.cpp
- src/mbgl/style/layers/line_layer_properties.hpp
- src/mbgl/style/layers/raster_layer_properties.cpp
- src/mbgl/style/layers/raster_layer_properties.hpp
- src/mbgl/style/layers/symbol_layer_properties.cpp
- src/mbgl/style/layers/symbol_layer_properties.hpp
- src/mbgl/style/properties.hpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/tile.hpp
Use layer data-driven properties constants mask to verify that the given layer properties are compatible with the existing buckets. 
Thus, the updated paint properties can applied for rendering even before the tile re-layout completes.
Fixes: #14939
> [core] Tile updates the contained layer properties based on constants mask

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView+Impl.h
- platform/ios/src/MGLMapView+Impl.mm
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLMapViewDelegate.h
- platform/ios/src/MGLMapView_Private.h
- platform/ios/test/MGLMapViewDelegateIntegrationTests.swift
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView+Impl.h
- platform/macos/src/MGLMapView+Impl.mm
- platform/macos/src/MGLMapView.mm
- platform/macos/src/MGLMapViewDelegate.h
- platform/macos/src/MGLMapView_Private.h
- platform/macos/test/MGLMapViewDelegateIntegrationTests.swift
> [ios] Add removeStyleImage to MGLMapView

- platform/node/CHANGELOG.md
- platform/node/src/node_map.cpp
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15054.
/cc @riastrad
> [node] Parse 'sdf' option when adding an image

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/offline/OfflineDownloadTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotterTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/BaseTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterMarkerActivity.java
This PR adds two instrumentation tests around our MapSnapshotter and Offline Download API. Due to https://github.com/mapbox/mapbox-gl-native/issues/14760, I'm running the snapshotter code inside the Activity and verifying the result from the test.
> MapSnapshotter and offline download test

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Added changelog entries for #15009 and #15027.
/cc @jmkiley
> [ios] Prepare ios-v5.2.0-alpha.2 release

- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/test/MGLMapViewPitchTests.m
Part of #14091 — adds tests for `MGLMapView` pitch setting and for the tilt gesture recognizer.
> [ios, build] Add tests for MGLMapView pitch setting and tilt gesture

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- src/mbgl/annotation/render_annotation_source.cpp
- src/mbgl/annotation/render_annotation_source.hpp
- src/mbgl/geometry/feature_index.cpp
- src/mbgl/geometry/feature_index.hpp
- src/mbgl/renderer/render_orchestrator.cpp
- src/mbgl/renderer/render_orchestrator.hpp
- src/mbgl/renderer/render_source.hpp
- src/mbgl/renderer/sources/render_image_source.cpp
- src/mbgl/renderer/sources/render_image_source.hpp
- src/mbgl/renderer/sources/render_raster_dem_source.cpp
- src/mbgl/renderer/sources/render_raster_dem_source.hpp
- src/mbgl/renderer/sources/render_raster_source.cpp
- src/mbgl/renderer/sources/render_raster_source.hpp
- src/mbgl/renderer/sources/render_tile_source.cpp
- src/mbgl/renderer/sources/render_tile_source.hpp
- src/mbgl/renderer/tile_pyramid.cpp
- src/mbgl/renderer/tile_pyramid.hpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/tile.cpp
- src/mbgl/tile/tile.hpp
This PR adds following changes:
- Reserves size of a filtered render layers container based on number of previously rendered layers
- Provides hashed container of RenderLayer* items to qRF path to remove few linear lookups
- Queries rendered features only from layers / sources that were provided via qRF API
```diff
--- /home/shalamov/github/mapbox-gl-native/master.json
+++ /home/shalamov/github/mapbox-gl-native/head.json
@@ -1,6 +1,6 @@
{
"context": {
-    "date": "2019-06-17 13:18:49",
+    "date": "2019-06-17 17:24:14",
"executable": "./mbgl-benchmark",
"num_cpus": 8,
"mhz_per_cpu": 1901,
@@ -30,296 +30,296 @@
"benchmarks": [
{
"name": "API_queryRenderedFeaturesAll_median",
-      "iterations": 2,
-      "real_time": 2.9258846699667627e+08,
-      "cpu_time": 2.9092940099999988e+08,
+ …
```
> [core] Few performance fixes for RendererImpl

- platform/glfw/glfw_view.cpp
- platform/glfw/glfw_view.hpp
- src/mbgl/renderer/renderer.cpp
> [core] Return the missing gl backend guard to Renderer::reduceMemoryUse()

- src/mbgl/map/transform.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/15072.
This PR reverts the required pixel distance to match what's been there before https://github.com/mapbox/mapbox-gl-native/pull/9199, unless we'd like to split the target and zoom interpolation thresholds?
> Decrease the minimum pixel distance required to interpolate during camera animation

- circle.yml
We don’t need/want homebrew to clean its packages every time we spin up a CI job, so opt-out of this behavior.
[Homebrew docs:](https://github.com/Homebrew/brew/blob/a81dfe0e3025231531bebe19cdd02be10bc96897/docs/Manpage.md#install-options-formula)
> Unless `HOMEBREW_NO_INSTALL_CLEANUP` is set, brew cleanup will be run for the installed formulae or, every 30 days, for all formulae.
> [build] Opt out of homebrew cleanup on CI

- platform/android/gradle/dependencies.gradle
This PR updates okhttp to latest stable version that supports pre lollipop.
> Update okhttp to latest stable version that support pre lollipop

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Podspec and changelog updates for [changes since `ios-v5.2.0-alpha.2`.](https://github.com/mapbox/mapbox-gl-native/compare/ios-v5.2.0-alpha.2...32321d4)
> [ios] Prepare ios-v5.2.0-alpha.3 release

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/MapboxConfigurationException.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TelemetryDefinition.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry/TelemetryImpl.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxTest.java
- platform/android/src/file_source.cpp
Closes https://github.com/mapbox/mapbox-gl-native/issues/15063.
Changes in this PR:
- Throw a configuration exception when Mapbox services are accessed with an invalid access token, which previously resulted in a caught NPE and a blank map (https://github.com/mapbox/mapbox-gl-native/issues/15063).
- Recreate telemetry service when a new, valid access token is supplied. From what I can see, we'd be sending telemetry events with a wrong token otherwise. If an invalid one/`null` is provided, telemetry will be stopped.
- Allow setting a `null` access token in the runtime, just like we allow during initialization.
> Reinitialize token dependent components when a new one is provided

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/GesturesUiTestUtils.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapGestureDetectorTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/15091.
Additionally, ports and extends gestures UI tests recently introduced to the gestures library. Those tests currently target all recent quick zoom/double tap regressions.
> Allow map panning after quick zoom is disabled but a phantom gesture is executed

- include/mbgl/style/layer_properties.hpp
- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/renderer/layers/render_background_layer.cpp
- src/mbgl/renderer/layers/render_circle_layer.cpp
- src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
- src/mbgl/renderer/layers/render_fill_layer.cpp
- src/mbgl/renderer/layers/render_heatmap_layer.cpp
- src/mbgl/renderer/layers/render_hillshade_layer.cpp
- src/mbgl/renderer/layers/render_line_layer.cpp
- src/mbgl/renderer/layers/render_raster_layer.cpp
- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/renderer/render_orchestrator.cpp
Before this change render passes were assigned for the whole layer at properties evaluation stage.
This caused problems, as layer render data are bound to the tile and these data might differ from tile to tile, depending on which tile has been updated by the tile worker and which has not been yet updated.
This change takes into consideration the actual render passes required for each tile and combines them for the layer render passes. Naturally, this change also introduces render pass check for each render layer in `RenderLayer::render()` implementations.
Fixes #15085
> [core] Synchronize render passes and render tiles

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapGestureDetectorTest.kt
This PR improves move gesture detector management:
- whenever disabled in `#gestureBegin`, ensure to re-enable in the `#gestureEnd`
- whenever disabled for double tap, ensure to re-enable when gesture finishes or is canceled
> Ensure that move detector is enabled if double-tap is interrupted

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/renderer/sources/render_custom_geometry_source.cpp
Otherwise, the remaining stale tiles cannot be updated.
fixes #15111
> [core] RenderCustomGeometrySource should clear tiles after style update

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
To changelogs:
Fixed incorrect center coordinate after pinch regression caused by edge insets fix (#14664).
While working on #14664, missed to understand the logic used in
```
CLLocationCoordinate2D centerCoordinate = _previousPinchCenterCoordinate;
mbgl::EdgeInsets padding { centerPoint.y, centerPoint.x, self.size.height - centerPoint.y, self.size.width - centerPoint.x };
self.mbglMap.jumpTo(mbgl::CameraOptions()
.withCenter(MGLLatLngFromLocationCoordinate2D(centerCoordinate))
.withPadding(padding));
```
Replacing this code by moveBy achieves the required translation.
Fixes #14977 and fixes #15082.
> [ios] Fix incorrect center coordinate after pinch gesture

- package.json
- platform/node/CHANGELOG.md
Still to do:
cc @mapbox/maps-api @mapbox/gl-native
> [node] prepare node-v4.2.0 release

- platform/darwin/src/MGLNetworkConfiguration.m
- platform/ios/CHANGELOG.md
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/test/MGLNetworkConfigurationTests.m
Fixes #14982, and replaces #15029 in @fabian-guerra's absence.
EDIT: #14982 is a crash in `-[MGLNetworkConfiguration startDownloadEvent:type:]` caused because `NSMutableDictionary` is not thread-safe and we have concurrent read/writes. This PR uses a concurrent dispatch queue (to allow concurrent reads) but with `dispatch_barrier_async` to ensure that writes/deletes are synchronous.
Using GCD is a common solution, though we will need to monitor performance.
/cc @chloekraw
> [ios] Adds thread safe access to MGLNetworkConfiguration events dictionary

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotterTest.kt
closes https://github.com/mapbox/mapbox-gl-native/issues/14760, the issue itself was solved already. This PR brings back the testcase we initially wanted to support as integration test.
> Create map snapshot inside testcase

- platform/darwin/src/MGLMapSnapshotter.h
- platform/darwin/src/MGLOfflineRegion.h
- platform/darwin/src/MGLRasterTileSource.h
- platform/darwin/src/MGLShapeOfflineRegion.h
- platform/darwin/src/MGLTilePyramidOfflineRegion.h
- platform/darwin/src/MGLVectorTileSource.h
- platform/ios/CHANGELOG.md
- platform/ios/Integration Tests/MGLStyleLayerIntegrationTests.m
- platform/ios/src/MGLMapView.h
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView+IBAdditions.h
- platform/macos/src/MGLMapView.h
Background: We're changing instances of `map ID` to be the more accurate term `tileset ID` across all Mapbox documentation. @1ec5 also found a number of instances where the docs in this repo refer to `a style's map ID`, which is more accurately a [style URL](https://docs.mapbox.com/help/glossary/style-url/).
Per https://github.com/mapbox/mapbox-gl-native/issues/14551, this PR:
- Updates `map ID` to `tileset ID` where necessary
- Updates `style's map ID` to `style URL` where necessary
@captainbarbosa or @1ec5 to review, please! 🙏
> [ios, macos] Change "map ID" to "tileset ID"

- platform/darwin/src/MGLSymbolStyleLayer.h
- src/mbgl/text/placement.cpp
Port of https://github.com/mapbox/mapbox-gl-js/pull/8473
> Favor previous anchor only when still in the `text-variable-anchor` options

- platform/android/gradle/artifact-settings.gradle
- platform/android/gradle/gradle-bintray.gradle
With the recent Bintray changes that enabled snapshots for various other projects, I claimed and merged external package created by the Bintray bot to our `mapbox-android-sdk` package. This resulted in an unwanted name change.
Until we can rename the package back to `mapbox-android-sdk`, we need to use the currently set `com.mapbox.mapboxsdk:mapbox-android-sdk`.
Project's maven group and artifact IDs remain unchanged of course.
> Update Bintray's package name

- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/test/MGLMapViewCompassViewTests.mm
- platform/ios/test/MGLMapViewDirectionTests.mm
- platform/ios/test/MGLMapViewZoomTests.m
- Adds `MGLMapViewZoomTests`, which exercise `MGLMapView.zoomLevel` and its friends.
- Adds a regression test for #15097 — see `-[MGLMapViewZoomTests testPinchGestureOffCenter]`.
- Note that this test will fail until #15097 is merged and this PR rebased.
- Reorganizes some of the newly-added compass tests, moving some things out of the direction tests.
- Adds center coordinate checks to some direction/rotation gesture tests.
/cc @julianrex @astojilj
> [ios] Add MGLMapViewZoomTests and clean-up other gesture tests

- platform/darwin/src/MGLOfflineStorage.h
- platform/ios/CHANGELOG.md
* Adds changelog entry for #14978 
* Moves changelog entry pertaining to #14176 
* Addresses #15140 by fixing a typo.
> [ios] Add changelog entry for Cache Management API

- platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/text/collision_index.cpp
Viewport center offset usage was wrongly submitted in #14664. It was part of alternative approach that used enlarged viewport. Existing and added tests were not sufficient to spot the regression, since the collision check padding is usually larger than the center offset x and y. Annotation picking has tolerance of only 10 pixels but no annotation integration test was using content insets.
Usage of offset is not needed because `posMatrix` in e.g. `CollisionIndex::projectPoint(const mat4& posMatrix, const Point<float>& point)` already incorporates center offset (projection matrix) and the code in current master was just offsetting all by the value.
Modified [ios] MGLAnnotationViewIntegrationTests.testSelectingAnnotationWithCenterOffset to use different insets. It verifies the fix.
Fixes …
> [core] Fix collision with content insets

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
> [ios] Prepare ios-v5.2.0-beta.1 release

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotterTest.kt
We've caught a timeout during the `MapSnapshotter` test - https://circleci.com/gh/mapbox/mapbox-gl-native/301451. We should also log an error, in case there's one returned from the core.
> Fail MapSnapshotter test in case of an error returned from core

- platform/android/CHANGELOG.md
Backports https://github.com/mapbox/mapbox-gl-native/pull/15142 to `release-picklejuice`.
> Backport #15142 to picklejuice

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotterTest.kt
Backports https://github.com/mapbox/mapbox-gl-native/pull/15147 to `release-picklejuice`.
> Backport #15147 to picklejuice

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
- Updates `release-oolong` to [Mapbox Events v0.9.5](https://github.com/mapbox/mapbox-events-ios/releases/tag/v0.9.5), which includes an important telemetry bug fix.
- Backports https://github.com/mapbox/mapbox-gl-native/pull/15077.
- Bumps versions for a `ios-v5.1.1` patch release.
> [ios] Prepare ios-v5.1.1 patch release with telemetry fix (oolong)

- include/mbgl/storage/offline.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
- platform/darwin/src/MGLOfflineStorage.h
This PR updates `include/mbgl/storage/offline.hpp`, `platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java`, and `platform/darwin/src/MGLOfflineStorage.h` to remove references to increasing the offline tile limit. @brsbl to review for wording, and @friedbunny to review for whether I did this correctly, please! 🐰
> [docs] Remove references to increasing offline tile limit

- include/mbgl/style/layer_properties.hpp
- src/mbgl/renderer/layers/render_background_layer.cpp
- src/mbgl/renderer/layers/render_circle_layer.cpp
- src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
- src/mbgl/renderer/layers/render_fill_layer.cpp
- src/mbgl/renderer/layers/render_heatmap_layer.cpp
- src/mbgl/renderer/layers/render_hillshade_layer.cpp
- src/mbgl/renderer/layers/render_line_layer.cpp
- src/mbgl/renderer/layers/render_raster_layer.cpp
- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/renderer/renderer_impl.cpp
Backports #15092 to release-oolong.
> [core][cp] Backport #15092 to oolong

- src/mbgl/renderer/render_orchestrator.cpp
Change in https://github.com/mapbox/mapbox-gl-native/pull/15065/commits/3ffc14a3250e5c4eb7dcaf0d1cc0e95c9de3c014
was a typo while addressing review nit: while it doesn't affect rendering it could affect performance.
Because of the potential performance impact, It is important to get it to current beta releases (added beta blocker label). I'm incorporating it to backports of #15065 to nectar and oolong.
Edit: added render test https://github.com/mapbox/mapbox-gl-js/pull/8515 to verify that this isn't causing rendering regression. Performance impact would be coming from moving all layers from fill pass to translucent pass (while still rendering properly).
Related to: #14844, #14779, #15039
> Fix wrong #15065 nit fix

- include/mbgl/style/layer_properties.hpp
- src/mbgl/renderer/layers/render_background_layer.cpp
- src/mbgl/renderer/layers/render_circle_layer.cpp
- src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
- src/mbgl/renderer/layers/render_fill_layer.cpp
- src/mbgl/renderer/layers/render_heatmap_layer.cpp
- src/mbgl/renderer/layers/render_hillshade_layer.cpp
- src/mbgl/renderer/layers/render_line_layer.cpp
- src/mbgl/renderer/layers/render_raster_layer.cpp
- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/renderer/renderer_impl.cpp
- src/mbgl/renderer/sources/render_custom_geometry_source.cpp
mapbox/mapbox-gl-native#15155 and mapbox/mapbox-gl-native#15157 backported some necessary fixes to `release-mojito`, but unfortunately we need to finish up https://github.com/mapbox/mapbox-gl-native/pull/15161 before proceeding with these cherry-picks.
/cc @pozdnyakov @alexshalamov @julianrex
> Temporarily revert two cherry-picks to release-mojito

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
- Updates `release-mojito` to [Mapbox Events v0.9.3-patch.1](https://github.com/mapbox/mapbox-events-ios/commit/85e038ce8eb2b508e5d2b14428dbdd0e7daeebf4), which includes an important telemetry bug fix.
- Bumps versions for a `ios-v4.11.1` patch release.
> [ios] Prepare ios-v4.11.1 patch release with telemetry fix (mojito)

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
- platform/ios/scripts/install-packaging-dependencies.sh
- Updates `release-liquid` to [Mapbox Events v0.9.5](https://github.com/mapbox/mapbox-events-ios/releases/tag/v0.9.5), which includes an important telemetry bug fix.
- Bumps versions for a `ios-v4.10.1` patch release.
> [ios] Prepare ios-v4.10.1 patch release with telemetry fix (liquid)

- include/mbgl/style/layer_properties.hpp
- src/mbgl/renderer/layers/render_background_layer.cpp
- src/mbgl/renderer/layers/render_circle_layer.cpp
- src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
- src/mbgl/renderer/layers/render_fill_layer.cpp
- src/mbgl/renderer/layers/render_heatmap_layer.cpp
- src/mbgl/renderer/layers/render_hillshade_layer.cpp
- src/mbgl/renderer/layers/render_line_layer.cpp
- src/mbgl/renderer/layers/render_raster_layer.cpp
- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/renderer/renderer_impl.cpp
- src/mbgl/renderer/sources/render_custom_geometry_source.cpp
Undoes the temporary reversion of #15155 and #15157 in #15184. Waiting for #15161 to merge and `ios-v4.11.1` to be released.
/cc @pozdnyakov @alexshalamov @julianrex
> Un-revert two cherry-picks to release-mojito

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/renderer/sources/render_raster_dem_source.cpp
- src/mbgl/renderer/sources/render_raster_dem_source.hpp
- src/mbgl/renderer/sources/render_raster_source.cpp
- src/mbgl/renderer/sources/render_raster_source.hpp
- src/mbgl/renderer/sources/render_tile_source.cpp
- src/mbgl/renderer/sources/render_tile_source.hpp
- src/mbgl/renderer/sources/render_vector_source.cpp
- src/mbgl/renderer/sources/render_vector_source.hpp
- src/mbgl/style/sources/raster_source.cpp
- src/mbgl/style/sources/raster_source_impl.cpp
- src/mbgl/style/sources/raster_source_impl.hpp
- src/mbgl/style/sources/vector_source.cpp
- src/mbgl/style/sources/vector_source_impl.cpp
- src/mbgl/style/sources/vector_source_impl.hpp
Before:
After:
Before this change, render sources were invalidating their tiles on each style update, when the new tile set was not yet available (tile set for a source is fetched in a separate request) and it caused flickering. Now updates without available tilesets are ignored.
The flickering was introduced with https://github.com/mapbox/mapbox-gl-native/commit/88c0914e53bc70d2cb3afc78506a30386cfc92b1 , it is now partially reverted for the Continuous map mode. 
For other map modes, tiles are still cleaned preventing from render tests being flaky, which was the issue fixed by https://github.com/mapbox/mapbox-gl-native/commit/88c0914e53bc70d2cb3afc78506a30386cfc92b1
> [core] Fix flickering on style change

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/StyleTest.kt
Refs https://github.com/mapbox/mapbox-plugins-android/pull/999#issuecomment-513293296.
Whenever a style was changed and there were active, runtime added layers and sources, we were removing them in the wrong order causing a warning log.
> Remove layers first when clearing the style

- platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m
- platform/ios/src/MGLMapView.mm
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/text/collision_index.cpp
[core][cp] Backport #15097 and #15130 to oolong release.
Cherry-pick s cleanly apply.
> [core][cp] Backport #15097 and #15130 to oolong release

- src/mbgl/layout/symbol_instance.cpp
- src/mbgl/layout/symbol_instance.hpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/layout/symbol_layout.hpp
- src/mbgl/renderer/buckets/symbol_bucket.hpp
- src/mbgl/text/placement.cpp
- test/text/cross_tile_symbol_index.test.cpp
When long line segments are rendered, engine could create thousands of symbol instances for the same label that is repeated along the line for different anchors (e.g., road labels / shields).
This PR introduces code that shares symbol quads between symbol instances and releases aux data structures once vertex buffers are created.
Partially fixes issue #15022
> [core] Release quad data after vertex buffers are created

- benchmark/src/mbgl/benchmark/stub_geometry_tile_feature.hpp
- src/mbgl/annotation/annotation_tile.cpp
- src/mbgl/annotation/annotation_tile.hpp
- src/mbgl/geometry/feature_index.cpp
- src/mbgl/layout/pattern_layout.hpp
- src/mbgl/layout/symbol_feature.hpp
- src/mbgl/renderer/layers/render_circle_layer.cpp
- src/mbgl/renderer/layers/render_line_layer.cpp
- src/mbgl/style/expression/expression.cpp
- src/mbgl/tile/geojson_tile_data.hpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile_data.cpp
- src/mbgl/tile/geometry_tile_data.hpp
- src/mbgl/tile/geometry_tile_worker.cpp
- src/mbgl/tile/vector_tile_data.cpp
- src/mbgl/tile/vector_tile_data.hpp
- test/gl/bucket.test.cpp
- test/src/mbgl/test/stub_geometry_tile_feature.hpp
- test/util/merge_lines.test.cpp
`mbgl::GeometryCollection` can potentially contain significant amount of data, however before this change we had several places where `GeometryCollection` instances were unnecessarily copied causing extra allocations, which affected the performance. In particular, `queryRenderedFeatures` API performance was affected (see https://github.com/mapbox/mapbox-gl-native/pull/15183).
> [core] Avoid geometry collections copying

- platform/darwin/src/MGLNetworkConfiguration.m
- platform/ios/CHANGELOG.md
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/test/MGLNetworkConfigurationTests.m
Cherry picks #15113 to release-oolong for `ios-v5.1.2`.
/cc @chloekraw
> [ios] Cherry picks #15113 - Adds thread safe access to MGLNetworkConfiguration events

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
- Updates for today’s `ios-v5.2.0` release.
- Adds last week’s patch releases to the `master` changelog, since those commits happened directly on release branches.
/cc @julianrex
> [ios] Prepare ios-v5.2.0 release

- include/mbgl/storage/offline.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
- platform/darwin/src/MGLOfflineStorage.h
- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Cherry-picks #15164 and #15210 to `release-picklejuice` for `ios-v5.2.0`.
/cc @julianrex
> [ios] Prepare ios-v5.2.0 release (picklejuice)

- circle.yml
Our framework release builds take some time and it’s safe to trigger external deploy steps while we wait for the framework deploy here to finish, so let’s do that. This will reduce the lag time between kicking off a release build and the ios-sdk docs being available for review.
> [ios, build] Trigger external deploy jobs before long-running build tasks

- src/mbgl/renderer/render_orchestrator.cpp
- src/mbgl/renderer/tile_pyramid.cpp
This PR filters out invisible layers before quering features
(rather than after, like it happened before).
With this change `API_queryRenderedFeaturesAll` performance test
passes almost two times faster.
Fixes: #15207
> [core] Optimize Query Rendered Features API

- src/mbgl/layout/symbol_feature.hpp
- src/mbgl/style/expression/compound_expression.cpp
- src/mbgl/style/expression/expression.cpp
- src/mbgl/tile/geojson_tile_data.hpp
- src/mbgl/tile/geometry_tile_data.cpp
- src/mbgl/tile/geometry_tile_data.hpp
- src/mbgl/tile/vector_tile_data.cpp
- src/mbgl/tile/vector_tile_data.hpp
- test/tile/vector_tile.test.cpp
This PR provides similar optimization as https://github.com/mapbox/mapbox-gl-native/pull/15201 but for feature properties. It improves performance of `GeometryTileWorker::parse()` up to 35% on iOS (thanks to @julianrex for measurements!).
Also, this PR contains simplification and optimization of the `ToGeometryCollection` class (thanks to @alexshalamov for pointing out the issue!).
> [core] Avoid feature properties copying

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Bumps podspec and updates changelog for release-oolong 5.1.2
> [ios] Release oolong v5.1.2

- src/mbgl/renderer/layers/render_raster_layer.cpp
- src/mbgl/renderer/render_layer.cpp
- test/map/map.test.cpp
It shall consider that image data might not be available until
the source loads it.
Fixes: #15216
> [core] Fix assertion at RenderRasterLayer::prepare()

- platform/ios/ios.xcodeproj/project.pbxproj
#14542 added `insert_access_token.sh` for iosapp, but it also accidentally began to be copied into Mapbox.framework and iosapp’s bundle, which is not what we want.
> [ios, build] Stop copying iosapp token script into framework

- src/mbgl/renderer/render_orchestrator.cpp
Before this change, `RenderOrchestrator::filteredLayersForSource` shrank inside
`createRenderTree()`, which potentially might have affected rendering performance.
> [core] Shrink filteredLayersForSource inside reduceMemoryUse()

- circle.yml
Mitigates codecov.io instability (https://github.com/mapbox/mapbox-gl-native/issues/15095) by not allowing it to fail required CI jobs. This switches to something closer to their [recommended bash script invocation](https://docs.codecov.io/docs/about-the-codecov-bash-uploader).
/cc @jmkiley @springmeyer
> [build] Don't allow codecov to fail a CI job

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapGestureDetectorTest.kt
`MapGestureDetector` tests appeared to be flaky, especially on older devices.
> Harden MapGestureDetector tests

- cmake/vendor.cmake
Prevents double insertion of mapbox-base target in some circumstances.
> [build] Do not include mapbox-base if target already exists

- src/mbgl/util/grid_index.cpp
- src/mbgl/util/grid_index.hpp
- test/util/grid_index.test.cpp
This PR fixes int overflow issue for GridIndex with large width / height dimensions.
> [core] Fix int overflow issue in GridIndex

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14271 and unblocks https://github.com/mapbox/mapbox-gl-native/pull/14269.
Turns out that because the `TypedArray` doesn't support default values for `Object`s, we were overwriting a default local ideographs font family with a `null`.
/cc @pozdnyakov @chloekraw
> Ensure default local ideographs font family is not overwrote

- platform/android/gradle/artifact-settings.gradle
- platform/android/gradle/gradle-bintray.gradle
To release from oolong, we need the correct bintray package name.
> [android] update Bintray's package name

- circle.yml
- platform/ios/scripts/deploy-to-cocoapods.sh
- platform/ios/scripts/install-packaging-dependencies.sh
Partially addresses #15214 by automating CocoaPods deployment as part of our release/~snapshot~ CI jobs.
- ~[ ] Update `Mapbox-iOS-SDK-snapshot-dynamic.podspec` version and URL to make them unique for every push to `mapbox-public`.~ Going to do this later as part of revamping how we bump versions for podspecs/etc.
> [ios, build] Automatically deploy to CocoaPods

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineGeometryRegionDefinition.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineTilePyramidRegionDefinition.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/14201.
/cc @ChrisLoer :)
> Do not include CJK ideographs in the offline packs by default

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/15246.
When all location layer animations were reset, due to the mode change, we were recalculating the time of the animation, while we should be taking the remaining duration. Frequent recalculation requests resulted in a really short animation duration. The recalculation should be limited to a moment when an actual location update is fed to the animator coordinator.
> Save location animation timestamp only when fed

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationCameraController.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationLayerController.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationCameraControllerTest.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.java
Camera/Render mode updates can be streamed from various different stateless sources and we should make sure to skip an update to a mode that's already set. This keeps the callbacks tidy and does not perform unnecessary work.
> Do not reinitialize camera/render mode if it hasn't changed

- platform/android/CHANGELOG.md
This PR updates the android changelog for releasing `v8.3.0-alpha.1`.
> Update changelog for the v8.3.0-alpha.1 release

- platform/android/CHANGELOG.md
This PR updates the changelog for a `v8.2.1` patch release of `release-picklejuice` . 
https://github.com/mapbox/mapbox-gl-native/pull/15265 is the one addition to this patch release.
> Update changelog for release v8.2.1

- circle.yml
Updates to [Xcode 10.3](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-903/index.html) on CircleCI.
/cc @julianrex
> [ios, build] Update to Xcode 10.3 on CircleCI

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java
This PR cherry picks changes needed for doing an 8.2.1 patch release to `release-picklejuice`: 
- Save location animation timestamp only when fed: https://github.com/mapbox/mapbox-gl-native/pull/15265
- Changelog update: https://github.com/mapbox/mapbox-gl-native/pull/15272
> [android] Cherry-pick changes for release-picklejuice v8.2.1 patch release

- platform/android/CHANGELOG.md
This PR updates the changelog for a v7.4.1 patch release of `release-mojito` .
> [android] Update changelog for v7.4.1 patch release

- platform/android/CHANGELOG.md
Follow up to https://github.com/mapbox/mapbox-gl-native/pull/15274. This pr updates the changelog by adding an additional pr that needs to go into the `7.4.1` patch release of `release-mojito`.
> [android] Additional changelog item to v7.4.1 mojito patch release section

- include/mbgl/util/projection.hpp
- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
- src/mbgl/map/transform_state.cpp
- test/map/transform.test.cpp
- test/util/tile_cover.test.cpp
Patch partly fixes #15163 in a way that it doesn't allow loading tens of thousands of tiles and attempt  to show area above horizon:
1. Limit pitch based on edge insets. It is not too bad - current limit of 60 degrees stays active until center of perspective is moved towards the bottom, to 84% of screen height. The plan is to split removal of 60 degrees limit to follow up patch.
2. Fix max Z calculation in getProjMatrix. TransformState::getProjMatrix calculation of farZ was complex with possibility to lead to negative z values. Replacing it with simpler, precise calculation:
``` furthestDistance = cameraToCenterDistance / (1 - tanFovAboveCenter * std::tan(getPitch())); ```
Mapping diagram to code:
fD: furthestDistance,
c: cameraToCenterDistance,
small phi: getPitch()
Addresses: #15163
> [core] Limit pitch based on edge insets. Fix max Z calculation in getProjMatrix.

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/mapbox_user_icon_shadow_0px_test.xml
This PR cherry picks changes needed for doing an 8.0.2 patch release to release-nectar:
I get nasty core merge conflicts when I tried to cherry-pick mapbox/mapbox-gl-native#15065 and mapbox/mapbox-gl-native#15092. @LukasPaczos , you can look into solving the conflicts? 
When I tried to cherry-pick https://github.com/mapbox/mapbox-gl-native/pull/15112, I got 
Seems that https://github.com/mapbox/mapbox-gl-native/pull/15112 was already brought into the `release-nectar` branch? I didn't see it in the 8.0.1 release. The advice in threads like https://stackoverflow.com/a/50052479/6358488 didn't help on my local machine.
> [android] Cherry-pick changes for release-nectar v8.0.2 patch release

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/Utils.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/mapbox_user_icon_shadow_0px_test.xml
This PR cherry picks changes needed for doing a 7.4.1 patch release to `release-mojito`:
@LukasPaczos , I'm seeing similar cherry pick issues as the ones described in https://github.com/mapbox/mapbox-gl-native/pull/15276. 
Merge conflicts when I try to bring mapbox/mapbox-gl-native#15092 (`git cherry-pick fa5646d112259758cee9fba0564a067376d0756`) into this pr:
When I try to bring mapbox/mapbox-gl-native#15112 (`git cherry-pick ff7fb5e46de275c8ceb4c2280edc020cff8b126e`) into this pr, I get the same change-has-already-been-brought-in message as in https://github.com/mapbox/mapbox-gl-native/pull/15276:
> [android] Cherry-pick changes for release-mojito v7.4.1 patch release

- circle.yml
- src/mbgl/renderer/sources/render_tile_source.cpp
- test/style/source.test.cpp
Before this change, the `RenderTileSetSource` implementation
ignored update calls for the sources whose description was not yet
loaded and it lead to missing of relayout requests.
> [core] Fix render tile set source update

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java
This pr fixes an Android test app crash in `CameraPositionActivity` if the latitude slider sets a latitude value less than -90 or more than 90. Discovered during manual QA of `8.3.0-alpha.1`.
> [android] Adding latitude value check for test app CameraPositionActivity

- circle.yml
The CocoaPods deployment may not finish before the CI job ends, since it’s (unfortunately) somewhat long-running and `background: true` [evidently means](https://circleci.com/gh/mapbox/mapbox-gl-native/310161) that a step can be cancelled:
```
* Pushing release to CocoaPods trunk…
Setting up CocoaPods master repo
Cloning spec repo `master` from `https://github.com/CocoaPods/Specs.git` (branch `master`)
$ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git --progress -- master
Cloning into 'master'...
remote: Enumerating objects: 1659, done.        
remote: Counting objects: 100% (1659/1659), done.        
remote: Compressing objects: 100% (1612/1612), done.        
remote: Total 3341155 (delta 705), reused 8 (delta 3), pack-reused 3339496        
Receiving objects: 100% …
```
> [ios, build] Make CocoaPods CI deployment synchronous

- src/mbgl/renderer/buckets/line_bucket.cpp
Port for https://github.com/mapbox/mapbox-gl-js/pull/8275
Fixes #14838
> [core] A more accurate algorithm for approximating round line joins

- src/mbgl/renderer/buckets/symbol_bucket.cpp
- src/mbgl/renderer/buckets/symbol_bucket.hpp
- src/mbgl/text/collision_feature.cpp
- src/mbgl/text/collision_feature.hpp
- src/mbgl/text/collision_index.cpp
- src/mbgl/text/collision_index.hpp
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
This PR does two things:
* Prevents collision index from using of uninitialized variables
* Decreases the `CollisionBox` size by 40 bytes. Considering the huge amount of `CollisionBox` instances (one instance per glyph for along-line placed symbols) it saves more than 2 MB on maximum zoom level, if the map is showing a city center with a lot of labels. Tagging #15022
* Fixes constness at `Placement::placeBucket` - now it does not mutate the given bucket. Tagging #14638
> [core] Collision box improvements

- platform/darwin/src/http_file_source.mm
We were capturing the reference to an object that could go away when the request was canceled. However, the lambda could still be invoked by NSURLSession, creating a race condition with a resulting crash when the response to a tile request was 404 Not Found.
This fixes https://github.com/mapbox/mapbox-gl-native/issues/14325 and https://github.com/mapbox/mapbox-gl-native/issues/9814
> macOS/iOS: Fix rare crash when downloading tiles that returned a 404

- platform/node/test/ignores.json
- src/mbgl/renderer/layers/render_background_layer.cpp
- src/mbgl/renderer/layers/render_fill_layer.cpp
Follow the approach from mapbox-gl-js for enabling opaque pass for background layer (same as for fill layer).
Fix combinations/heatmap-translucent--background-opaque render test.
> [core] Enable opaque pass for background layer. fix heatmap+backgroud test

- render-test/linux-ignores.json
- render-test/mac-ignores.json
- render-test/parser.cpp
- render-test/runner.cpp
Platform specific ignore files.
Use the same tolerance as in node render tests. 
Two render tests failing only with mbgl-render-tests are added to platform
specific ignores. The tests are not regressions, but a few pixels over the tolerance. We'll need to figure out what's the reason.
This is to be extended with fill-extrusion-pattern tests failing only on mac bot.
Patch#2 ignores flaky line-pattern/opacity test on Linux only - related to: #15320
> mbgl-render-test runner - use the node render test tolerance. Platform specific ignore list.

- render-test/linux-ignores.json
Mark as flaky on Linux:    
fill-opacity/zoom-and-property-function-pattern,
fill-pattern/literal,
fill-pattern/opacity,
fill-pattern/zoomed,
line-translate/literal,
Addresses: #15322, #14423, #14870, #14768, #14859
> Mark render tests flaky on Linux only

- test/storage/offline_database.test.cpp
Disables the intermittently failing `OfflineDatabase.MaximumAmbientCacheSize` test while #14966 awaits attention.
/cc @tmpsantos
> [core] Disable flaky OfflineDatabase.MaximumAmbientCacheSize test

- platform/android/src/run_loop.cpp
- platform/android/src/run_loop_impl.hpp
Do not flood the RunLoop with wake up calls, potentially causing writes to the socket to block when internal pipe buffer goes over the limit defined by the system (usually 65536).
Also, write calls are syscalls and will cause a context switch.
Fixes #14740
/cc @alexshalamov that found the issue.
> [android] Do not try to wake up the RunLoop if a wake is already pending

- platform/android/CHANGELOG.md
This pr updates the Android changelog for the `queso` 8.3.0-alpha.2 release
> [android] Updated changelog for 8.3.0-alpha.2 release

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
Captured screen video could be compared against videos #15144.
Final version (reusing fly to calculation for constant movement) as in https://github.com/mapbox/mapbox-gl-native/files/3460613/Archive.zip
Version after first patch:
Linear interpolation over zoom looks more natural, as the rate of change looks constant to user: for every zoom change of 1, view displays 2 times wider area.
Problem if using scale could be described by this graph:
http://www.mathopenref.com/graphfunctions.html?fx=log(x)&xh=1000000&xl=0&yh=20&yl=0
Horizontal axis: scale, vertical axis: zoom:
When linearly interpolating over scale, zoom changes very slowly when zoomed in. When zooming out (values of scale towards 0), as reported in #15144, it feels like a sudden zoom out.
The transition could be further improved, …
> [core] easeTo: linear interpolation over zoom instead of scale

- circle.yml
- platform/darwin/test/MGLDocumentationExampleTests.swift
- platform/darwin/test/MGLDocumentationGuideTests.swift
- platform/darwin/test/MGLSDKTestHelpers.swift
Adds `ios-debug-xcode11` and `ios-static-analyzer-nightly-xcode11` jobs to CircleCI, [currently running](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-781/index.html) Xcode 11b2.
/cc @julianrex
> [ios, build] Add CI jobs running Xcode 11 betas

- circle.yml
- package.json
- scripts/check-ci-job-skippability.js
Adds a script that checks a pull request’s changed files for relevant changes, then potentially quickly passes certain CI jobs.
- Primarily, this is intended for changelog-only edits — [the entire CI run will pass in ~2 minutes](https://circleci.com/workflow-run/2a2da878-3f7c-4f17-aff2-eb2a7a846980).
- ... but it also will, for example:
- Skip iOS CI jobs if only code in `platform/android/**` changed.
- Skip iOS and Android CI jobs if only code in `platform/glfw` changed.
- Changes to core (e.g., `src/**`) will always trigger a full run of every CI job.
- Only iOS, macOS, and Android jobs can be skipped by changes to another platform’s code. The only scenario where all jobs can be skipped is if only `ALWAYS_SKIPPABLE_FILES` are changed (i.e., non-build text files).
- `master` and …
> [build] Skip CI jobs if there are no relevant changed files

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/FontUtils.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/utils/FontUtilsTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterActivity.java
This PR matches logic from https://github.com/mapbox/mapbox-gl-native/pull/14862 and makes https://github.com/mapbox/mapbox-gl-native/pull/15225 obsolete. Proposed change allows developers to pass in a array of string for localideographfamily and we will check if we can find a valid font and pass that to core. If not, fallback on `sans-serif`. 
Note: I'm currently not satisfied with taken approach, it uses reflection to lookup valid fonts from `TypeFace`. Sadly, there isn't an API on the Android SDK to do this cleanly. LMK if you are aware of any.
> Add fallback support to local ideograph font families

- platform/android/CHANGELOG.md
The `8.3.0-alpha.2` release went out but https://github.com/mapbox/mapbox-gl-native/pull/15330 was added to `master` while I was in the middle of the release process and never saw it until it was too late to add it to the changelog in https://github.com/mapbox/mapbox-gl-native/pull/15334.
https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v8.3.0-alpha.2 includes #15330, so the Android changelog needs to be updated. This pr updates the changelog.
> [android] Added #15330 to the 8.3.0-alpha.2 changelog

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
The engine is trying to place the text first, and allows collision only if there is no position without a collision.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15357
> [core] Enable variable label placement for allowed text overlap

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_backstack_fragment.xml
This pr makes two small tweaks to the Android test app:
1. The zoom level `TextView` in `DebugModeActivity.java` is now updated as the camera moves, rather than only when it stops.
2. Text was being blocked by the button in the fragment backstack example.
> [android] Test app tweaks from 8.3.0-alpha.2 QA

- scripts/environment.js
This fixes [a CI failure](https://circleci.com/gh/mapbox/mapbox-gl-native/314620) when a branch (without a PR) was built that had more than 10 commits between its `head` and merge-base. Performance-wise, this may add a few hundred milliseconds in the worst case... but it’ll succeed.
/cc @julianrex
> [build] Look further back for branch merge base

- src/mbgl/text/placement.cpp
Collision text boxes must be always cleared while symbol instances are placed.
> [core] Clear collision text boxes between symbol placement iterations

- platform/android/LICENSE.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
- platform/android/MapboxGLAndroidSDK/src/main/res/values/dimens.xml
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
- platform/android/gradle/dependencies.gradle
Closes https://github.com/mapbox/mapbox-gl-native/issues/14776. Closes https://github.com/mapbox/mapbox-gl-native/issues/14775.
- Bumps gestures library to `v0.5.0`, which includes our custom scale gestures detector, dropping the dependency on the compat one and bringing minor improvements, see https://github.com/mapbox/mapbox-gestures-android/issues/39 and https://github.com/mapbox/mapbox-gestures-android/pull/73.
- Disables the rotation gesture detector if a scale gesture has been recognized first to prevent unwanted rotation. This behavior is adjustable through the `UiSettings`.
- Improves the responsiveness of scale and rotation gestures, while at the same time better separates them and judges which gesture should be executed first based on the relative gesture speed (linear or …
> Bump gestures library to v0.5.0, refine thresholds and velocity animations

- Makefile
In #5527 @tmpsantos added a memory test. But this test was removed from being run on CI in 692fe1f3f because it is not longer included in the `make test-node` target.
I'm assuming that the removal was inadvertent, so this PR re-establishes the test to run on CI.
/cc @kkaefer @mapbox/api-gl
> Add back memory test to CI

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/MathUtils.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapGestureDetectorTest.kt
Closes https://github.com/mapbox/mapbox-gl-native/issues/15219.
Using finger's Y axis position allows for a linear zoom additions/deductions during the quick-zoom changes. This is in contrast to the previously used scale factor, which is based on the current span (distance from the origin) to previous span ratio and increases the closer the finger is to the origin of a gesture because the values are smaller.
The scale ratio based changes are also reliant on series of motion events' values and because the Android framework can skip some events, going back and forth during a quick-zoom might not have resulted in the same transformation. This was reproduced by the round-tripping test introduced in this commit.
> Execute quickzoom scale change based on the Y axis delta change

- src/mbgl/style/conversion/filter.cpp
- test/style/filter.test.cpp
The `convertLegacyFilter` function did not have convertible value type check, therefore, rapidjson was asserting when value was used as an array.
Fixes: #15388
> [core] Check type of a convertible value when constructing legacy filter

- platform/default/src/mbgl/storage/sqlite3.cpp
- test/src/mbgl/test/sqlite3_test_fs.cpp
I compiled with `-fsanitize=address,leak` and noticed two leaks when running the unit tests:
```
2: Direct leak of 176 byte(s) in 1 object(s) allocated from:
2:     #0 0x4c6cc3 in __interceptor_malloc /build/llvm-toolchain-8-F3l7P1/llvm-toolchain-8-8/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146:3
2:     #1 0x7f945bd817d5 in sqlite3MemMalloc /src/build/../vendor/sqlite/src/sqlite3.c:22262:7
2:     #2 0x7f945bc5bb86 in mallocWithAlarm /src/build/../vendor/sqlite/src/sqlite3.c:26094:7
2:     #3 0x7f945bc35357 in sqlite3Malloc /src/build/../vendor/sqlite/src/sqlite3.c:26124:5
2:     #4 0x7f945bc35260 in sqlite3_malloc /src/build/../vendor/sqlite/src/sqlite3.c:26142:21
2:     #5 0x7f945b6687e8 in mbgl::test::SQLite3TestFS::SQLite3TestFS() …
```
> [core][test] fix leaks from sqlite usage

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/renderer/layers/render_background_layer.cpp
- src/mbgl/renderer/layers/render_circle_layer.cpp
- src/mbgl/renderer/layers/render_custom_layer.cpp
- src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
- src/mbgl/renderer/layers/render_fill_layer.cpp
- src/mbgl/renderer/layers/render_heatmap_layer.cpp
- src/mbgl/renderer/layers/render_hillshade_layer.cpp
- src/mbgl/renderer/layers/render_line_layer.cpp
- src/mbgl/renderer/layers/render_raster_layer.cpp
- src/mbgl/renderer/layers/render_symbol_layer.cpp
This PR puts `impl()` functions definitions into a nameless namespace
to provide internal linkage and to make sure that appropriate cast function
is invoked.
The problem was discovered by sanitize bot https://circleci.com/gh/mapbox/mapbox-gl-native/316959
> [core] Fix layer impl cast in render layer implementations

- platform/android/CHANGELOG.md
#15398 didn't make it into `8.3.0-alpha.3` and git merged changelogs poorly.
> Move #15398 out of `v8.3.0-alpha.3` changelog

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/text/glyph_manager.cpp
- src/mbgl/tile/geometry_tile_data.cpp
Detected by the bot being setup at https://github.com/mapbox/mapbox-gl-native/pull/15385.
> [core] Fix use after std::move detected by clang-tidy

- platform/ios/INSTALL.md
Fixes #15377 by updating our CocoaPods installation documentation. Follow-up to #15027 and #15227.
/cc @captainbarbosa @long1eu
> [ios, docs] Update CocoaPods installation instructions

- src/mbgl/renderer/image_manager.cpp
- test/renderer/image_manager.test.cpp
https://github.com/mapbox/mapbox-gl-native/pull/14253 add an `ImageVersionMap` to  the `ImageManager`, but doesn't clear data from it when the associated image is removed.
> Remove version info in ImageManager when removing an image

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/FontUtils.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/utils/FontUtilsTest.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/15378. This PR consists out of 2 proposals. Either we disable font look up completely for pre lollipop devices (https://github.com/mapbox/mapbox-gl-native/commit/601992da762979dabb4af8366f53e7a65f892e32) or we provide our own default device fonts based on https://github.com/aosp-mirror/platform_frameworks_base/blob/master/graphics/java/android/graphics/Typeface.java#L1154-L1156 as shown in commit https://github.com/mapbox/mapbox-gl-native/commit/606db647521ae2f2978b5828ade185ebb006d723.
> Font fallback

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- platform/node/CHANGELOG.md
- platform/node/test/ignores.json
- src/mbgl/layout/symbol_instance.cpp
- src/mbgl/layout/symbol_instance.hpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/layout/symbol_layout.hpp
- src/mbgl/programs/symbol_program.cpp
- src/mbgl/renderer/buckets/symbol_bucket.cpp
- src/mbgl/renderer/buckets/symbol_bucket.hpp
- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/text/placement.cpp
- src/mbgl/text/quads.cpp
- src/mbgl/text/quads.hpp
- src/mbgl/text/shaping.cpp
- src/mbgl/text/shaping.hpp
- test/text/cross_tile_symbol_index.test.cpp
- test/text/quads.test.cpp
There are multiple issues related to `icon-text-fit` when it is used in combination with `text-variable-anchor` and `text-writing-mode`
- Collision feature box for an icon has wrong size
- Collision feature should be shifted together with text box
- Collision debug box for an icon should be shifted together with text
- Vertically oriented text box might be of different size, thus vertical icon might be needed
Fixes: #15346
Adresses: https://github.com/mapbox/mapbox-gl-js/issues/8583
> [core] Fix issues for use-cases when icon-text-fit is combined with text-variable-anchor

- src/mbgl/renderer/render_orchestrator.cpp
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
Zooming out can make symbols overlap quickly. After zooming out quickly the area previously covered by the viewport has a lot of colliding labels while the surrounding area has no labels. This difference produces an unwanted effect:
This reduces that effect by:
- reducing the fade duration while zooming out
- doing placement more frequently while zooming out
ports https://github.com/mapbox/mapbox-gl-js/pull/8628/files
In -js we're still trying to figure out whether this introduces jankiness. I've only tested this in the glfw app on -native and it seems to work as smoothly as master. Placement is faster on -native so this should be an ok change. 
To test, zoom in to a dense area and then zoom out as quickly and suddenly as possible. The main thing to check is that it doesn't introduce …
> [core] make symbols fade out faster while zooming out

- platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.m
- platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.mm
- platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLMapView_Private.h
WIP - needs some cleanup, but ok for an initial review.
Adds integration tests to check annotation selection after rotating or zooming the map (not via a gesture).
> [ios] Added annotation selection tests with rotation & scaling of the map

- platform/android/CHANGELOG.md
- platform/android/gradle/dependencies.gradle
Closes https://github.com/mapbox/mapbox-gl-native/issues/15409.
> Bump gestures library to v0.5.1

- platform/darwin/src/MGLOfflineStorage.h
- platform/darwin/src/http_file_source.mm
- platform/darwin/test/MGLResourceTests.mm
- platform/ios/CHANGELOG.md
- Stops adding SKU tokens to offline requests. (Follow-up to https://github.com/mapbox/mapbox-gl-native/pull/14857.)
- Updates tests and docs.
- Android counterpart is over in https://github.com/mapbox/mapbox-gl-native/pull/15363.
/cc @chloekraw @zugaldia @brsbl @philogb @julianrex
> [ios] Updates for offline pricing

- platform/darwin/test/MGLTileSetTests.mm
Silences the failure seen in https://github.com/mapbox/mapbox-gl-native/issues/13386#issuecomment-523240292 — I have not yet investigated the veracity/impact of the failure, but I’d like to stop failing tests in the meantime.
/cc @1ec5
> [ios] Update MGLTileSetTests.testTileSetFromTileURLTemplates for Xcode 11

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUrl.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/module/http/HttpRequestUrlTest.kt
This pr separates the Maps SDK SKU from offline tile requesting. If offline is `true`, `offline=true` will be appended to the request URL. If `false`, the SKU token is appended instead.
This pr is needed because offline requests are counted as billable Vector Tile API requests. They're Raster Tile API requests if satellite imagery is being fetched. More documentation about this, to come soon.
> [android] Updating HttpRequestUrl to separate offline requests from Maps SKU

- platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.mm
- platform/ios/Integration Tests/MGLMapViewIntegrationTest.h
- platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
This PR fixes #15256 and random failures.
- Test failures on iOS 9 - due to `UIWindow` deallocation - and map view display not being called.
- Random fails waiting for rendering (needed call to `setNeedsRerender`)
> [ios] Fix integration tests failing on iOS 9 

- platform/darwin/src/MGLAccountManager.m
- platform/darwin/src/MGLAccountManager_Private.h
- platform/darwin/src/http_file_source.mm
- platform/ios/app/MBXState.h
- platform/ios/app/MBXState.m
- platform/ios/app/MBXViewController.m
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLMapboxEvents.h
- platform/ios/src/MGLMapboxEvents.m
- Renames a bunch of `NSUserDefaults`/`Info.plist` key variable names to better indicate their purpose. (Note: this does **not** change the underlying key names, since that would break compatibility — this is purely a refactor.)
- Replaces remaining uses of raw strings as key names.
- Removes obsolete telemetry logging options from iosapp, since these have been superseded by the standalone events library.
/cc @jmkiley @captainbarbosa @julianrex
> [ios] Refactor some variable names and clean-up iosapp

- platform/ios/CHANGELOG.md
Updates the changelog to use iOS property names.
cc @friedbunny
> [ios] Fix changelog for v5.3.0-beta.1

- src/mbgl/renderer/sources/render_geojson_source.cpp
- src/mbgl/tile/geojson_tile.cpp
- src/mbgl/tile/geojson_tile.hpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/geometry_tile_worker.cpp
- src/mbgl/tile/geometry_tile_worker.hpp
Before this change, GeoJSON tiles data were updated before the
corresponding layers were applied, therefore `GeometryTileWorker`
parsed new data with the outdated layers.
It caused the following render test failure:
`mbgl-render-test text-max-width/unlimited regressions/mapbox-gl-native#9976 --recycle-map`
Now a GeoJSON tile, which needs re-layout, is not parsed until the valid layers
are set.
Fixes #15420
> [core] Fix GeoJSON tiles update

- platform/android/MapboxGLAndroidSDK/gradle.properties
[release-queso](https://github.com/mapbox/mapbox-gl-native/tree/release-queso) branch was cut, time to prepare master for `release-ristretto`.
> Update snapshot version number to 8.4.0

- src/mbgl/style/layers/fill_layer_impl.cpp
Otherwise, pattern properties update is not taken in action.
This caused the following render tests failure:
`build/mbgl-render-test runtime-styling/layer-add-fill regressions/mapbox-gl-js#3107 --recycle-map`
> [core] Fill layer pattern change must cause re-layout

- platform/ios/src/MGLMapView.h
Partially addresses https://github.com/mapbox/mapbox-gl-native/issues/14607 (doesn't solve it, but documents currently expected behavior).
> [ios, macos] Clarify best practices when using -[setCenter:animated:]

- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/util/tile_coordinate.hpp
- src/mbgl/util/tile_cover.cpp
- src/mbgl/util/tile_cover.hpp
- test/util/tile_cover.test.cpp
Remove unecessary tile coordinate unproject -> project  step.
Unproject+clamp+project isn't always a noop and this was the issue leading to wrong cover calculation in high pitch values.
Unit test added that exposes the issue.
Fixes: https://github.com/mapbox/mapbox-gl-native/issues/15442
> [core] Fix tileCover / TileCoordinate fromScreenCoordinate(#15442)

- platform/ios/app/MBXState.m
- platform/ios/app/Main.storyboard
- Fixes an extra format argument in `-[MBXState debugDescription]` from #15431.
- Fixes a couple Interface Builder warnings about misplacement and invalid button style.
/cc @jmkiley @captainbarbosa
> [ios] Fix a few minor warnings in iosapp

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/ios/test/MGLMapViewPitchTests.m
> [ios] Improve tilt gesture recognizer detection.

- platform/ios/CHANGELOG.md
- platform/ios/Integration Tests/MGLMapViewPendingBlockTests.m
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLMapView.mm
~Draft PR to experiment with pending completion blocks.~
Without this several annotation selection integration tests were failing:
This is because the completion blocks introduced in https://github.com/mapbox/mapbox-gl-native/pull/14381 are called *before* the annotation view's positions have been updated.
I think the user's expectation will be that when the completion block has been called, that the annotations are in their correct and updated position.
This same mechanism could be use for camera/region changes, but we need to investigate @pozdnyakov's https://github.com/mapbox/mapbox-gl-native/pull/15086 first.
@friedbunny would love your thoughts here.
> [ios] Added "pending" completion blocks

- cmake/render-test.cmake
- render-test/allocation_index.cpp
- render-test/allocation_index.hpp
- render-test/main.cpp
- render-test/metadata.hpp
- render-test/parser.cpp
- render-test/parser.hpp
- render-test/runner.cpp
- render-test/runner.hpp
Before peeking the proposed approach, other approaches have been tried out (e.g. various memory stats system APIs like `getrusage()`, `malloc_info()`,  `/proc/self/stat`), but unfortunately, none of them gave stable results on repeated tests runs.
Example usage (zoom-visibility/below):
```
"operations": [
[ "wait" ],
[ "probeMemoryStart" ],
[ "probeMemory", "start" ],
[
"setZoom",
0.9
],
[
"wait"
],
[ "probeMemory", "after setZoom 0.9" ],
[
"setLayerZoomRange",
"circle",
1,
2
],
[
"wait"
],
[ "probeMemory", "end" ],
[ "probeMemoryEnd" ]
]
```
cc @tmpsantos
> [test runner] Introduce API to measure memory usage

- Makefile
This PR reorders our `make android-check` command so kotlin static code anylisis is executed first, followed by java code analysis and finally by the license validation.
> [android] reorder android-check make command

- platform/android/.gitignore
Android Studio v3.5.0 introduces fine grained memory control. Configurations for this are saved in a project wide `gradle.properties` file in the root of the android project:
```
#
#
#Tue Aug 20 22:13:23 EEST 2019
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
```
Since this configuration is developer specific and we aren't using the file for any other purpose. I'm proposing to ignore this file.
> Ignore project wide gradle.properties file

- include/mbgl/renderer/renderer.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
- platform/android/src/map_renderer.cpp
- platform/android/src/map_renderer.hpp
- platform/android/src/snapshotter/map_snapshotter.cpp
- platform/android/src/snapshotter/map_snapshotter.hpp
- platform/darwin/src/MGLMapSnapshotter.mm
- platform/darwin/src/MGLRendererConfiguration.h
- platform/darwin/src/MGLRendererConfiguration.mm
- platform/default/include/mbgl/gfx/headless_frontend.hpp
- platform/default/include/mbgl/map/map_snapshotter.hpp
- platform/default/src/mbgl/gfx/headless_frontend.cpp
- platform/default/src/mbgl/map/map_snapshotter.cpp
- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
- platform/qt/src/qmapboxgl_map_renderer.cpp
- src/mbgl/programs/program_parameters.cpp
- src/mbgl/programs/program_parameters.hpp
- src/mbgl/renderer/render_static_data.cpp
- src/mbgl/renderer/render_static_data.hpp
- src/mbgl/renderer/renderer.cpp
- src/mbgl/renderer/renderer_impl.cpp
- src/mbgl/renderer/renderer_impl.hpp
- test/gl/context.test.cpp
- test/text/local_glyph_rasterizer.test.cpp
Binary shader support has been removed in commit c2f974f2a573 ([core]
Remove binary shader support). This left-over parameter is not used
anywhere anymore.
> [core] Remove programCacheDir parameter from ProgramParameters

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
- platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsAttrsTest.kt
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_camera_position.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_gesture_detector.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/arrays.xml
Follow up from #15255, this PR enables setting a StringArray resource reference and adds integration of this into MapboxMapOptions. Additionally if a user want to disable localideograph completely, they can use the newly introduced flags.
> Add font array attribute configuration 

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraAnimatorActivity.java
Test app issue caught during QA:
```
Process: com.mapbox.mapboxsdk.testapp, PID: 5443
com.mapbox.mapboxsdk.MapStrictModeException: Map detected an error that would fail silently otherwise: You're calling `cancelTransitions` after the `MapView` wa
at com.mapbox.mapboxsdk.MapStrictMode.strictModeViolation(MapStrictMode.java:25)
at com.mapbox.mapboxsdk.maps.NativeMapView.checkState(NativeMapView.java:126)
at com.mapbox.mapboxsdk.maps.NativeMapView.cancelTransitions(NativeMapView.java:217)
at com.mapbox.mapboxsdk.maps.Transform.cancelTransitions(Transform.java:201)
at com.mapbox.mapboxsdk.maps.Transform.moveCamera(Transform.java:109)
at com.mapbox.mapboxsdk.maps.MapboxMap.moveCamera(MapboxMap.java:422)
at com.mapbox.mapboxsdk.maps.MapboxMap.moveCamera(MapboxMap.java:408)
at …
```
> Cancel CameraAnimatorActivity joint example when the map is destroyed

- render-test/main.cpp
- render-test/parser.cpp
- render-test/parser.hpp
This change adds filter command line option to render test runner,
so that test can be filtered by providing regular expression, for instance:
`mbgl-render-test -f .*hillshade.*`
Fixes: #15504
> [test-runner] Add filtering option to test-runner

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationLayerController.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/location/LocationLayerControllerTest.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/15499.
Regression introduced in https://github.com/mapbox/mapbox-gl-native/pull/15266.
> Invalidate foreground icon sources even when location layer is hidden

- platform/darwin/src/MGLOfflineStorage.h
clarifying in docs that:
- the offline limit is set by default to 6,000 tiles
- biling for offline tile requests has changed
> [docs] [ios] update offline to reflect billing changes

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Style.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/StyleTest.kt
This prevents unnecessary layers blink when the same components are re-added after the style reload.
Before:
After:
/cc @Guardiola31337
> Do not clear native layers and sources when style is reloading

- platform/android/CHANGELOG.md
- platform/default/include/mbgl/storage/offline_database.hpp
- platform/default/include/mbgl/storage/offline_download.hpp
- platform/default/src/mbgl/storage/offline_database.cpp
- platform/default/src/mbgl/storage/offline_download.cpp
- platform/ios/CHANGELOG.md
- test/storage/offline_database.test.cpp
Marking offline region resources "used" is on the hot code path for offline region download.
Previously, the engine attempted to update the database separetely for each resource and it caused a huge performance impact, especially when some tiles were already loaded.
Now, offline region resources are marked in batches (200 items at once).
Consider the time mesaurements of the `mbgl-offline` tool execution (Linux x64, release build):
`time ./mbgl-offline --north 41.4664 --west 2.0407 --south 41.2724 --east 2.2680 --output barcelona.db`
without patch:
1st time:
```
real      0m9,505s
user      0m3,315s
sys       0m0,378s
```
2nd time (tiles are already loaded):
```
real      0m9,480s
user      0m0,403s
sys       0m0,645s
```
with the patch:
1st time:
```
real      0m7,399s
user      0m2,994s …
```
> [core] Mark used offline region resources in batches

- bin/offline.cpp
- include/mbgl/storage/offline.hpp
- platform/default/src/mbgl/storage/offline_download.cpp
- test/storage/offline_download.test.cpp
This is useful for tracking down the required amount of tiles for a given offline region.
> [core] Add requiredTileCount to OfflineRegionStatus

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
This pr makes adjustments to Javadoc methods comments within the Maps SDK for Android's `OfflineManager` class.
> [android] Javadoc changes to clarify OfflineManager methods

- .github/stale.yml
Stalebot automatically closes issues after six months (#13153), but this generates unnecessary noise and effort as the team continually reopens still-valid issues, so this PR exempts `ios`- and `macos`-tagged issues from such closures.
> [meta] Exempt items on milestones or in projects from stalebot

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLScaleBar.mm
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15452 by changing the text color before being drawn into the `CGContext`.
> [ios] Allow MGLScaleBar to support dark mode on iOS 13

- src/mbgl/style/sources/custom_geometry_source.cpp
- src/mbgl/style/sources/raster_source.cpp
- src/mbgl/style/sources/vector_source.cpp
- src/mbgl/style/style_impl.cpp
- test/storage/sync_file_source.test.cpp
- test/test-files.json
When no network requests have to be made because the TileJSON metadata is included inline in a style, we never triggered a `onSourceLoad` call. This PR adds calls.
We found this by way of https://github.com/mapbox/mapbox-gl-native/issues/15514. Here's what happened:
- We are moving the addition of the new `Source` object to the `sources` collection in the style to _before_ we call `loadDescription`. In that call, however, we are mutating the implementation and updating `baseImpl`. Now, the `impl` pointer in the collection is out of date with the updated `impl`. If we never schedule a `onSourceLoadeded`, we never call `sources.update(...)` if no other sources are loaded, so the change is not picked up.
- This only happened when the TileJSON was specified inline, if we loaded it from the …
> Always call onSourceLoaded observers

- CMakeLists.txt
- Makefile
- circle.yml
- cmake/expression-test.cmake
- expression-test/expression_test_logger.cpp
- expression-test/expression_test_logger.hpp
- expression-test/expression_test_parser.cpp
- expression-test/expression_test_parser.hpp
- expression-test/expression_test_runner.cpp
- expression-test/expression_test_runner.hpp
- expression-test/main.cpp
- platform/darwin/src/string_nsstring.mm
The new native expression test runner allows to run expression tests without node bindings and adds shuffling option.
Fixes: #15454
> [core] Add native expression test runner

- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qt_image.cpp
Because the version is represented in hex, 0x051000 is not the same
as Qt 5.10, which means that the deprecated code will be enabled
for versions smaller than 5.16.
> [qt] Fix Qt version comparison

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/TransformTest.kt
This PR cherrypicks an external contributed PR from #15528.
The commits of this PR should be squashed when merging. 
cc @philemonmerlet
> Cherrypick #15528

- platform/android/CHANGELOG.md
This PR updates the android changelog for releasing v8.4.0-alpha.1 (`ristretto`)
> [android] Update changelog for the v8.4.0-alpha.1 release

- platform/ios/src/MGLMapView.h
- platform/macos/src/MGLMapView.h
Fixes the documentation for which method to call when using an animatable content inset.
> [ios, macos] Fix content inset documentation.

- platform/ios/src/MGLMapView.mm
This removes the feature flag added in #14929 and addresses #6562.
I have set the threshold to `3` which feels comfortable to me, but other people should test this out.
> [ios] Remove feature flag for rotation threshold

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- platform/node/CHANGELOG.md
- src/mbgl/tile/geometry_tile_data.cpp
Fix an issue that potential integer overflow would happen with high zoom level.
> [core] Fix Integer overflow when converting tileCoordinates to LatLon

- platform/android/LICENSE.md
- platform/android/gradle/dependencies.gradle
This pr bumps the Maps SDK for Android's Java SDK dependency to `4.9.0-alpha.1` as part of [the eventual `4.9.0` release](https://github.com/mapbox/mapbox-java/issues/1070).
> [android] Bumped Java SDK dependency to 4.9.0-alpha.1

- platform/android/build.gradle
- platform/android/gradle/wrapper/gradle-wrapper.properties
Android Studio 3.5 stable [has been released](https://twitter.com/AndroidDev/status/1163865806654124040). This PR updates build tools to match that AS version + updates gradle wrapper to the [highest available stable version](https://services.gradle.org/distributions/).
> Update android build tools and gradle wrapper to latest stable version

- platform/darwin/test/MGLClockDirectionFormatterTests.m
- platform/darwin/test/MGLCompassDirectionFormatterTests.m
- platform/darwin/test/MGLCoordinateFormatterTests.m
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/CI.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/dynamic.xcscheme
- platform/ios/test/MGLMapAccessibilityElementTests.m
- platform/macos/macos.xcodeproj/xcshareddata/xcschemes/CI.xcscheme
- platform/macos/macos.xcodeproj/xcshareddata/xcschemes/dynamic.xcscheme
- platform/macos/macos.xcodeproj/xcshareddata/xcschemes/macosapp.xcscheme
Fixes #14908 by setting `en_US` as the default test locale, regardless of the simulator or device settings.
This is configured in the various schemes:
/cc @1ec5 @julianrex
> [darwin] Use en_US as default test locale/language

- test/storage/offline_download.test.cpp
New unit test checks that Offline usage flag is not set for invalidated offline region resource requests.
Fixes: #15490
> [core] Add unit test to verify that Offline usage tag is not set

- platform/android/CHANGELOG.md
This PR updates the Android changelog for releasing v8.4.0-alpha.2 (`ristretto`)
> [android] Updated changelog for 8.4.0-alpha.2 release

- include/mbgl/map/map_observer.hpp
- platform/android/CHANGELOG.md
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView+Impl.h
- platform/ios/src/MGLMapView+Impl.mm
- platform/macos/src/MGLMapView+Impl.h
- platform/macos/src/MGLMapView+Impl.mm
- platform/qt/src/qmapboxgl_map_observer.cpp
- platform/qt/src/qmapboxgl_map_observer.hpp
- src/mbgl/map/map_impl.cpp
- src/mbgl/renderer/tile_pyramid.cpp
- test/map/map.test.cpp
- test/src/mbgl/test/stub_map_observer.hpp
- test/storage/offline_download.test.cpp
> [core] Set fading tiles flag at TilePyramid::updateFadingTiles()

- package.json
- platform/node/CHANGELOG.md
- platform/node/DEVELOPING.md
Wanted to get #15389 in a release 🙌  This branch is based off state from 08/15/2019 ([this commit](https://github.com/mapbox/mapbox-gl-native/commit/5f477e310b286d1bb8c5d238376d45ec58aa3fc4)).
One of the render tests fails locally:
```bash
* failed tilejson-bounds/overwrite-bounds
```
> [node][release] prep v4.3.0

- include/mbgl/storage/resource.hpp
- include/mbgl/util/bitmask_operations.hpp
- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/core-files.json
- src/mbgl/layout/symbol_instance.hpp
- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_orchestrator.cpp
- src/mbgl/renderer/render_pass.hpp
- src/mbgl/text/cross_tile_symbol_index.cpp
- src/mbgl/text/cross_tile_symbol_index.hpp
- src/mbgl/text/glyph.hpp
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
Before this change, just loaded buckets could not be placed until the new placement was created in a 300 ms period, and it caused a latency in symbols appearance.
Now buckets load initiates new placement, so that newly added symbols get placed immediately.
Before:
After:
(Transition duration is set to 1 s for better visibility)
Another positive impact is that a `Placement` instance does not have to set opacity for the symbols, which it did not place.  So, `updateBucketOpacities()` call now does not mutate the placement, tagging #14638
> [core] Fix placement for updated buckets

- platform/android/CHANGELOG.md
This pr is a follow up to https://github.com/mapbox/mapbox-gl-native/pull/15609. It fixes the linked text in the 8.4.0-alpha.2 section.
> [android] Adjusted changelog to fix since section

- platform/ios/Integration Tests/Camera Tests/MGLCameraTransitionTests.mm
- platform/ios/Integration Tests/MGLMapViewIntegrationTest.h
- platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
- platform/ios/Integration Tests/MGLStyleURLIntegrationTest.m
- platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterSwiftTests.swift
- platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterTest.m
This PR adds a non-default `XCTestSuite` for `MGLMapViewIntegrationTest` based integration tests. This 
- removes the need for manually adding `validAccessToken` (which is removed) to tests that require an access token. Instead, add 🔒to the method name
- also skips "pending" tests - this adds the benefit of not adding a ✅ next to tests that are being skipped (whereas before it looked like they were passing).
> [ios] Add custom XCTestSuite for integration tests

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLCompassButton.mm
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLScaleBar.mm
Cherry-picks #15524, #15547, and #15583 fixes for iOS 13 to `release-queso`, to be made available in a future `ios-v5.3.1` release.
Once these changes merge and `ios-v5.3.1` happens:
1. The original `release-ristretto` changelog entries should be removed (presuming `ios-v5.3.1` comes out before `ios-v5.4.0`).
2. These changelog entries should be backported to `master`/`release-ristretto`.
/cc @julianrex
> [ios] iOS 13 cherry-picks for ios-v5.3.1 (queso)

- platform/ios/Mapbox.playground/Contents.swift
- platform/ios/Mapbox.playground/contents.xcplayground
Storing `CLLocationCoordinate2D` objects as variables seems to cause exceptions in Swift playgrounds. I am just setting those coordinates directly for now.
> [ios] Small fixes to the Swift Playground 

- platform/darwin/src/MGLMapSnapshotter.h
- platform/darwin/src/MGLMapSnapshotter.mm
- platform/ios/CHANGELOG.md
- platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterTest.m
- platform/macos/CHANGELOG.md
~Adds the ability to include an image overlay on an `MGLMapSnapShot` by specifying an array of overlays within `MGLMapSnapShotOptions`.~
Adds a new method to `MGLMapSnapShotter` which provides the `CGContext` of the snapshot to the developer for further customization.
> [ios] Introduce overlays to MGLMapSnapshotter

- platform/ios/Integration Tests/MGLMapViewIntegrationTest.h
- platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
Follows on from https://github.com/mapbox/mapbox-gl-native/pull/15477; this PR allows individual tests that require an access token to be run. Previously the access token wouldn't be set up as `defaultTestSuite` is not call in the individual case.
> [ios] Add support for running tests (that require an access token) individually.

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/location/LocationComponentTest.kt
Fixes an unexpected behavior where `zoomWhileTracking` and `tiltWhileTracking` animations were ignored for the duration of the camera transition.
This could result in scenarios like:
```
1) set the camera tracking mode with a duration of 750ms
2) immediately call `zoomWhileTracking` with a duration of 1000ms
Zoom animation is ignored for 750ms and then resumes with a jump to 75% completion.
```
```
1) set the camera tracking mode with a duration of 750ms
2) immediately call `zoomWhileTracking` with a duration of 500ms
Zoom animation is completely ignored.
```
Changelog entry candidate:
```
Fixes an unexpected behavior that occurred while calling `zoomWhileTracking` and `tiltWhileTracking` animations during the `CameraMode` change transition. Those animations are now ignored and print …
```
> Ignore location tracking mode based animations when the camera is transitioning

- include/mbgl/style/sources/vector_source.hpp
- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- platform/node/CHANGELOG.md
- src/mbgl/style/conversion/source.cpp
- src/mbgl/style/sources/vector_source.cpp
Fix: #15501
The pre-condition is  we try to download an offline pack from an URL source, and the source's maxzoom(let's say zoom level 17) is higher than the maxzoom(let's say zl12) we downloaded for the offline pack.
Next we try to use the offline pack from a style that having the same URL source plus a `maxzoom` option zl12, the final rendering result is different from JS.
The problem is the ignorance of `maxZoom` option in style, which leads to wrong setting of the `zoomRange` in tileSet, zl17 is set instead of zl12. If we need the map to be overscaled to zl14, the renderable TileID should be overscale Zoom 14 plus canonical Zoom12.
However, zl17 as the max zoom in `zoomRange` is higher than zl14, zl14 is not taken as overscaled. With offline database of maxzoom 12, there is no way to …
> [Core] Fix wrong `maxzoom` setting of tileSet when using URL source

- platform/darwin/src/MGLMapSnapshotter.h
- platform/ios/app/MBXAnnotationView.h
- platform/ios/app/MBXAppDelegate.m
- platform/ios/app/MBXCustomCalloutView.h
- platform/ios/app/MBXCustomLocationViewController.m
- platform/ios/app/MBXEmbeddedMapViewController.m
- platform/ios/app/MBXOfflinePacksTableViewController.m
- platform/ios/app/MBXOrnamentsViewController.m
- platform/ios/app/MBXSnapshotsViewController.m
- platform/ios/app/MBXState.h
- platform/ios/app/MBXStateManager.m
- platform/ios/app/MBXUserLocationAnnotationView.h
- platform/ios/app/MBXViewController.m
- platform/ios/benchmark/MBXBenchAppDelegate.m
- platform/ios/benchmark/MBXBenchViewController.mm
- platform/ios/framework/Info.plist
Reinstates the bundle identifier lost in #15385. Also fixes some minor build warnings.
See also https://github.com/mapbox/mapbox-gl-native/pull/15646
> [ios, macos] Tail work from 15385

- platform/darwin/src/MGLSDKMetricsManager.m
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15526.
Speculative fix based on what variables could be nil. Most APIs are marked as "non null", so I've added fallbacks for the others.
> [ios] Ensure potential variables that might be nil have a fallback.

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
cherry-pick of external contributed PR in https://github.com/mapbox/mapbox-gl-native/pull/15635
cc @Guillaume-TagHeuer
> [android] fix: MapSnapshotter.withApiBaseUri function

- platform/darwin/src/MGLRasterTileSource.mm
Re-adds tileSize rounding lost in https://github.com/mapbox/mapbox-gl-native/pull/15644
> [ios] (Re)add tilesize rounding.

- circle.yml
This pr brings in @mourner's work at https://github.com/mapbox/earcut.hpp/commit/0d0897a9dc462edf6396aedb335ddeb4aa302b78 into the submodule on `master`.
> [build] Updated earcut.hpp submodule file

- platform/android/CHANGELOG.md
This PR cherry picks the Android changelog update to `master` for the `8.3.1` patch release to `release-queso`.
Delivering https://github.com/mapbox/mapbox-gl-native/pull/15660 to the `queso` branch is the reason for the patch release.
> [android] Updated changelog for 8.3.1 queso earcut patch release

- platform/ios/CHANGELOG.md
- platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
- platform/ios/Mapbox-iOS-SDK-stripped.podspec
- platform/ios/Mapbox-iOS-SDK.podspec
Updated the changelog and podspecs for v5.3.2.
> Prepare for Maps SDK for iOS v5.3.2

- platform/android/CHANGELOG.md
Backports https://github.com/mapbox/mapbox-gl-native/pull/15672 to `qeuso`.
> Changelog for v8.3.2

- platform/android/CHANGELOG.md
This PR updates the changelog for the 8.4.0-beta.1 `ristretto` release
> [android] Updated Android changelog for 8.4.0-beta.1 ristretto release

- platform/android/CHANGELOG.md
This pr is a cherrypick of https://github.com/mapbox/mapbox-gl-native/pull/15682 as part of the `8.4.0-beta.1` (`ristretto`) release of the Mapbox Maps SDK for Android.
> [android] Cherry pick updated Android changelog for 8.4.0-beta.1 ristretto release

- platform/ios/CHANGELOG.md
- Rewords entries to be specific to the iOS platform.
- Fixes some method/property names so that jazzy can link them.
- Rearranges some entries into different subheadings.
/cc @julianrex
> [ios] Copyedit changelog for ios-5.4.0

- platform/ios/CHANGELOG.md
Cherry-pick changelog edits from #15687 to `release-ristretto`.
/cc @julianrex
> [ios] Copyedit changelog for ios-5.4.0 (release-ristretto)

- platform/macos/config.cmake
This is to fix #15358
Rebased https://github.com/mapbox/mapbox-gl-native/pull/15373
> Add layer_manager.cpp to mbgl-offline on macOS

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/AttributionDialogManagerTest.java
Resolves #9090 by constructing the feedback url with referrer(package name), style owner, style id, access token and camera position information(Longitude, Latitude, zoom level, bearing and tilt).
There is one parameter missing since we don't currently have a SDK version API in our Android SDK, so couldn't add the sdk version info to the query parameter. I have created another ticket #15632 to keep track of it.
> [android] Migrate Android SDK to GL JS–powered feedback form

- platform/android/MapboxGLAndroidSDK/gradle.properties
This PR updates master bracnh to start releasing snapshot builds for `release-sangria`. We will continue to publish snapshot builds for `release-ristretto` from the `release-ristretto` release branch.
> Update snapshot version for release-sangria

- platform/android/.gitignore
This PR updates the .gitignore to not track .cxx directories. A recent change (buildsystem PR? or android tooling version change?) has resulted in using .cxx diretories as temp build folders for our C++ code (the old .NativeBuild directory). We can safely ignore these.
> Update gitignore to not track .cxx directories

- platform/android/gradle/dependencies.gradle
Resolves https://github.com/mapbox/mapbox-gl-native/issues/15689 by bumping the Maps SDK's Java SDK dependency to stable 4.9.0.
Java SDK `4.9.0` release ticket: https://github.com/mapbox/mapbox-java/issues/1070
Changes:
- https://github.com/mapbox/mapbox-java/releases/tag/v4.9.0-alpha.1
- https://github.com/mapbox/mapbox-java/releases/tag/v4.9.0
> [android] Bumped Java SDK dependency to stable 4.9.0

- platform/android/gradle/dependencies.gradle
This pr cherrypicks https://github.com/mapbox/mapbox-gl-native/pull/15700 to the`release-ristretto` branch.
> [android] Cherry pick of Java SDK bump to 4.9.0, to ristretto (#15700)

- circle.yml
- platform/ios/scripts/install-packaging-dependencies.sh
- Updates existing Xcode 10.3 builds to Xcode 11.0 (which is [still GM1](https://circle-macos-docs.s3.amazonaws.com/image-manifest/v1136/index.html), but should be updated to stable quite soon — we shouldn’t build a release with this PR until GM2/stable is available).
- Keeps two Xcode 10.3 builds around for a little while, to ensure we’re compatible during this transition.
- Updates to jazzy [0.11.1](https://github.com/realm/jazzy/releases/tag/v0.11.1).
- Updates to Ruby 2.6.x, which is more modern and allows us to remove some build workarounds for jazzy. (See [these CircleCI docs](https://circleci.com/docs/2.0/testing-ios/#using-custom-ruby-versions) for more information.)
> [build] Update CircleCI to Xcode 11, ruby 2.6, jazzy 0.11.1

- platform/android/CHANGELOG.md
This pr updates the Android changelog as part of the `8.4.0` (`ristretto`) release of the Maps SDK for Android.
> [android] Updated Android changelog for 8.4.0 stable release (ristretto)

- platform/android/CHANGELOG.md
This pr cherry-picks https://github.com/mapbox/mapbox-gl-native/pull/15713 to the `ristretto` branch in preparation for the stable `8.4.0` release of the Maps SDK for Android.
> [android] Updated changelog for 8.4.0 stable release (cp to ristretto)

- expression-test/expression_test_parser.cpp
- include/mbgl/style/conversion.hpp
- include/mbgl/style/conversion_impl.hpp
- include/mbgl/style/expression/formatted.hpp
- include/mbgl/style/light.hpp
- include/mbgl/style/light.hpp.ejs
- include/mbgl/util/traits.hpp
- src/mbgl/style/expression/formatted.cpp
- src/mbgl/style/layers/background_layer.cpp
- src/mbgl/style/layers/circle_layer.cpp
- src/mbgl/style/layers/fill_extrusion_layer.cpp
- src/mbgl/style/layers/fill_layer.cpp
- src/mbgl/style/layers/heatmap_layer.cpp
- src/mbgl/style/layers/hillshade_layer.cpp
- src/mbgl/style/layers/layer.cpp.ejs
- src/mbgl/style/layers/line_layer.cpp
- src/mbgl/style/layers/raster_layer.cpp
- src/mbgl/style/layers/symbol_layer.cpp
- src/mbgl/style/light.cpp
- src/mbgl/style/light.cpp.ejs
- test/map/map.test.cpp
This PR enables fetching layer layout properties from the universal getter API `GetProperty()`, similar API is added to get light properties.
Having a similar method for getting both layout an paint layer properties decreases API surface and saves binary size.
> [core] Universal getter for layer layout and light properties

- include/mbgl/style/conversion_impl.hpp
- test/map/map.test.cpp
The output of Layer::getProperty is a mapbox::base::Value which is
equivalent to JSON. When setting the value of an enum property via JSON
its value would be a string, so it would be natural to return a string
too.
Also, the numbers generated depend on the enum definition. They are not
part of the style spec.
> [core] Return enum layer property values as string

- README.md
Corrects the main project README to say that we’re licensed under the two-clause BSD license (and not the three-clause variant). There are no changes to the actual license.
Looking back to 2014, it seems that @kkaefer [originally added a three-clause BSD license](https://github.com/mapbox/mapbox-gl-native/commit/3f9337b74c8d384f2635d0a6adc33869169300fc), but then @incanus [removed the last clause](https://github.com/mapbox/mapbox-gl-native/commit/b34229dc0ff021955ab0bd283f24d68e24f77a1b) a couple months later. This was before the project was available publicly.
The removed clause was:
> - Neither the name "Mapbox" nor the names of its contributors may be used to
>    endorse or promote products derived from this software without specific prior
>    written permission.
/cc @kathleenlu09 …
> [docs] Correct license typo in project README

- circle.yml
- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/renderer/tile_pyramid.cpp
- test/style/source.test.cpp
If the render source does not need rendering, we set necessity for its tiles to `optional`, and thus suppress network requests on tiles expiration.
> [core] Suppress network requests for invisible tiles

- platform/node/test/ignores.json
- src/mbgl/renderer/paint_property_binder.hpp
port https://github.com/mapbox/mapbox-gl-js/pull/8818
Previously the interpolation factor could be out of the range 0 to 1 which could result in rendering errors. 
I've skipped the render test because -native doesn't have a way to stop sources from loading new tiles. I started trying to add this but bailed because it doesn't seem like it's worth the effort. I opened https://github.com/mapbox/mapbox-gl-native/issues/15737 to document this.
> [core] fix opacity interpolation for composition expressions

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/NativeMapViewTest.kt
The projected meters per pixel calculation is not dependent on the pixel ratio but rather the tile size, therefore, the division when fetching the value is not necessary.
> Remove projected meters per pixel and pixel ratio relation

- benchmark/api/render.benchmark.cpp
- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/renderer/render_orchestrator.cpp
- src/mbgl/renderer/render_orchestrator.hpp
`RenderOrchestrator` holds a vector of ordered rendered layers, in order to minimize calling of `getRenderLayer()`, which could be quite expensive as it calculates hash of the layer Id.
This change improves orchestration performance in particular for the styles that have multiple sources.
The `API_renderStill_multiple_sources` benchmark runs  approximately 30% faster with the changes applied (x64 Linux desktop).
> [core] Orchestration performance for styles with multiple sources

- platform/android/src/file_source.cpp
- platform/android/src/mapbox.cpp
- platform/android/src/mapbox.hpp
This check is needed for mbgl-benchmark target, as it does not require Mapbox
instance, nor Android asset manager.
/cc @zmiao
> [android] Check if Mapbox instance exists before creating default file source

- include/mbgl/actor/mailbox.hpp
- include/mbgl/actor/scheduler.hpp
- include/mbgl/util/run_loop.hpp
- platform/android/src/map_renderer.cpp
- platform/android/src/map_renderer.hpp
- platform/android/src/map_renderer_runnable.cpp
- platform/android/src/map_renderer_runnable.hpp
- platform/qt/src/qmapboxgl_scheduler.cpp
- platform/qt/src/qmapboxgl_scheduler.hpp
- src/mbgl/actor/mailbox.cpp
- src/mbgl/util/thread_pool.cpp
- src/mbgl/util/thread_pool.hpp
- test/actor/actor.test.cpp
So that it is possible to schedule normal `std::function` and use `mapbox::base::WeakPtr`.
Fixes  https://github.com/mapbox/mapbox-gl-native-team/issues/76
> [core] Decouple Scheduler interface from actor model

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLScaleBar.h
- platform/ios/src/MGLScaleBar.mm
- platform/ios/test/MGLMapViewLayoutTests.m
- platform/ios/test/MGLMapViewScaleBarTests.m
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15356 and layout when the device is rotated.
EDIT: The PR as it stands also rounds the corners of the scale bar - let me know what you think
Before:
After:
> [ios] Fix layout of Scale bar components

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
This is needed to allow looking up this file from JNI code.
Refs https://github.com/mapbox/mapbox-gl-native/pull/15712/files
> Keep Mapbox.java when obfuscating code 

- platform/darwin/src/MGLMapSnapshotter.h
- platform/darwin/src/MGLMapSnapshotter.mm
- platform/darwin/src/MGLMapSnapshotter_Private.h
- platform/ios/CHANGELOG.md
- platform/ios/Integration Tests/Snapshotter Tests/MGLMapSnapshotterTest.m
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/sdk-files.json
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15695, by adding the same point & coordinate methods as `MGLMapSnapshot`
EDIT: Here's a test from iOS, drawing a line from coordinates for London<->Paris
macOS:
> [ios] Adds pointForCoordinate/coordinateForPoint to MGLMapSnapshotOverlay

- platform/ios/CHANGELOG.md
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLMapView.h
- platform/ios/src/MGLMapView.mm
- platform/ios/test/MGLMapViewContentInsetTests.m
- platform/ios/test/MGLMapViewGestureRecognizerTests.mm
- platform/ios/test/MGLMapViewPitchTests.m
- platform/ios/test/MGLMockGestureRecognizers.h
- platform/ios/test/MGLMockGestureRecognizers.m
This PR Fixes the following issues:
#14827 due to the fact that each bug fix adds its corresponding tests.
#12143 Removes the dependency of the now deprecated `UIViewController. automaticallyAdjustsScrollViewInsets`.
The property `automaticallyAdjustsScrollViewInsets` it's been deprecated and moved to `UIScrollView` the fix I made adds `automaticallyAdjustContentInset` as part of the `mapView` that will control this behavior. If set to `YES` the `contentInset` will be equal to the view's safeArea (on iOS 11+) or top/bottom layout guides (iOS < 11) if set to `NO` it will use any value as long as it's not negative.
> [ios] Fixes an issue that caused the ornaments ignore contentInset property.

- platform/darwin/src/MGLImageSource.mm
- platform/darwin/src/MGLRasterTileSource.mm
- platform/darwin/src/MGLVectorTileSource.mm
Investigated, fixes https://github.com/mapbox/mapbox-gl-native/issues/15732
Since attribution methods can be called via user interaction (without a mechanism to try/catch), this cases were switched to asserts.
I did not change the Assert name at this time (mostly because I struggled to find a good name! - perhaps `Prohibit`?)
> [ios, macos] Changed exception to assert and nil return

- src/mbgl/actor/scheduler.cpp
- src/mbgl/util/thread_pool.cpp
- src/mbgl/util/thread_pool.hpp
This commit refactors `utils::ThreadPool` into a template       
`ThreadedScheduler` class and provides aux type aliases.
So that it is possible to obtain a sequenced schedule,where
all the scheduled tasks are guarantied to be executed        
consiquently.
The sequenced lightweight scheduler is required by both the
orchestration thread (https://github.com/mapbox/mapbox-gl-native/issues/14638) and the refactored `FileSource` implementation.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/77
> [core] Introduce SequencedScheduler and ParallelScheduler

- LICENSE.md
> include mapbox-events-ios LICENSE.md

- circle.yml
Temporarily disable metrics.sh step, which is failing the release builds.
See https://github.com/mapbox/mapbox-gl-native/issues/15751
/cc @tobrun
> [ios] Skip Record Size/metrics.sh step in release workflows

- render-test/parser.cpp
- render-test/parser.hpp
- render-test/runner.cpp
Before this change, the found paths to the expected images erroneously included the path to the `metrics.json` file (if this file was present) leading to raising of an unhandled exception.
> [test runner] Fix finding of expected images paths

- package.json
- platform/node/CHANGELOG.md
This PR is for the v5.0.0 node release.
I chose a new major version since https://github.com/mapbox/mapbox-gl-native/pull/15748 has the possibility of being a breaking change for any downstream developers that might be depending on the source-compile fallback that was removed in https://github.com/mapbox/mapbox-gl-native/pull/15748.
/cc @mapbox/static-apis @mapbox/gl-native
> v5.x node release

- include/mbgl/actor/scheduler.hpp
- include/mbgl/util/run_loop.hpp
- platform/android/src/map_renderer.hpp
- platform/qt/src/qmapboxgl_scheduler.hpp
- src/mbgl/util/thread_pool.hpp
- test/actor/actor.test.cpp
This PR introduces `Scheduler::makeWeakPtr()` returning a weak pointer
> [core] Introduce Scheduler::makeWeakPtr()

- circle.yml
- include/mbgl/actor/scheduler.hpp
- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/actor/scheduler.cpp
- src/mbgl/renderer/image_manager.cpp
- src/mbgl/renderer/image_manager.hpp
- test/renderer/image_manager.test.cpp
This commit coalesces the repeated `onStyleImageMissing` calls
for the same image.
It also simplifies the image manager code.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15497
> [core] Coalesce requests for the same missing image

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
- platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/camera/CameraPositionTest.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/15780.
This avoids relying on Parcel's util methods that do not handle null arrays gracefully.
> Manually write and read camera's padding array to parcel

- circle.yml
Fixes failed triggering of metrics, due to timeouts waiting for a password (which we don't need due to having an access token).
> [ios, android] Update curl command to indicate there is no password

- circle.yml
After query and render test results were merged, new location is `/src/mapbox-gl-js/test/integration/index.html`
> [render-test] Update location of render / query test html page

- circle.yml
- platform/default/include/mbgl/storage/offline_schema.hpp
- platform/default/include/mbgl/storage/offline_schema.js
- platform/default/include/mbgl/storage/offline_schema.sql
Add inline documentation of each column of the offline database schema and a general ideal of how GL Native is using each field.
> [offline] Document the offline database schema

- platform/darwin/src/MGLSDKMetricsManager.m
- platform/ios/CHANGELOG.md
Fix for a crash seen on iOS 9 on simulator. Bug introduced (ironically) in https://github.com/mapbox/mapbox-gl-native/pull/15645
> [ios] Fix for iOS 9 crash (seen in simulator)

- cmake/render-test.cmake
- next/CMakeLists.txt
- next/platform/linux/linux.cmake
- next/platform/macos/macos.cmake
- next/render-test/CMakeLists.txt
- platform/default/src/mbgl/render-test/main.cpp
- render-test/include/mbgl/render_test.hpp
- render-test/render_test.cpp
This pr is an enabler for running the Render Test Runner on Android. We need to link the render-test library to a native activity android app, which is used for running the render tests.
> [test-runner] make render-test a shared lib

- src/mbgl/renderer/image_manager.cpp
- src/mbgl/renderer/image_manager.hpp
- test/renderer/image_manager.test.cpp
Before this change, repeated request for an already obtained image was erroneously treated as pending, and it prevented from the tiles load completion.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/85
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15822
> [core] Fix image requests for already obtained images

- circle.yml
We have a flaky test that is hanging on the bots and we need to find out which one.
> [build] Make output of the tests verbose

- next/CMakeLists.txt
Prevents `mapbox-base` from being re-added if target already exists.
> [build] Only add mapbox-base if target is not set

- platform/qt/src/qmapboxgl.cpp
It is useful to have image source URL updated in some cases in the Qt platform.
Hopefully we can get this into Qt SDK soon so opening a MR against `qt-staging`. Will open a MR against master when this one will be reviewed and accepted. Let me know if the workflow is different.
> [qt] Make image source url update possible

- include/mbgl/util/monotonic_timer.hpp
- next/platform/android/android.cmake
- next/platform/ios/ios.cmake
- next/platform/linux/linux.cmake
- next/platform/macos/macos.cmake
- next/platform/qt/qt.cmake
- platform/android/core-files.json
- platform/default/include/mbgl/gfx/headless_backend.hpp
- platform/default/include/mbgl/gfx/headless_frontend.hpp
- platform/default/include/mbgl/gl/headless_backend.hpp
- platform/default/src/mbgl/gfx/headless_frontend.cpp
- platform/default/src/mbgl/gl/headless_backend.cpp
- platform/default/src/mbgl/map/map_snapshotter.cpp
- platform/default/src/mbgl/util/monotonic_timer.cpp
- platform/ios/core-files.json
- platform/linux/config.cmake
- platform/macos/core-files.json
- render-test/metadata.hpp
- render-test/parser.cpp
- render-test/render_test.cpp
- render-test/runner.cpp
- render-test/runner.hpp
- src/core-files.json
- src/mbgl/gl/context.cpp
- src/mbgl/gl/context.hpp
- test/gl/context.test.cpp
- test/text/local_glyph_rasterizer.test.cpp
Test runner now supports continuous map rendering and fps tracking along a given camera path. Goal of this new rendering test is to imitate typical user gestures (aka map transformations) like panning and keep track of the average and minimum fps during the operation. This should provide us an opportunity to compare rendering performance trends on different areas of the map.
> [render-test] Implement fps benchmarking tests

- src/mbgl/text/placement.cpp
port https://github.com/mapbox/mapbox-gl-js/pull/8803/files
When deciding the placement position it was only checking whether there were text collisions. If there was an icon collision then it would hide the icon (and by default, the text with it) instead of trying a different position.
If icon-text-fit is used it now checks whether the icon fits before accepting a placement position.
> [core] fix collisions with icon-text-fit and variable placement

- next/platform/linux/linux.cmake
- next/platform/macos/macos.cmake
- render-test/parser.cpp
- render-test/parser.hpp
- render-test/render_test.cpp
- render-test/runner.cpp
- render-test/runner.hpp
Currently render-test-runner does not support configurable path when processing the recourses, we use hard coded path configured via CMake `TEST_RUNNER_ROOT_PATH` . This blocks running the test-runner in case the executable is moved to other locations,  or running the test-runner on android, in which case the resources will be stored in sdcard. Beside, extra user specified ignores.json path or expectation path could also be passed via CLI.
> [render-test] Add configurable rootPath, ignorePath via CLI arguments

- circle.yml
- scripts/ci/Dockerfile
This version includes gcloud, needed to run android firebase tests.
> [build] Bump CI docker image

- src/mbgl/text/placement.cpp
to prevent clipped labels in rendered image tiles.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/90
> [core] avoid edges for labels that use text-variable-anchors

- src/mbgl/renderer/image_manager.cpp
- src/mbgl/renderer/image_manager.hpp
- test/renderer/image_manager.test.cpp
This PR reverts https://github.com/mapbox/mapbox-gl-native/pull/15778 and https://github.com/mapbox/mapbox-gl-native/pull/15825
Fixes: https://github.com/mapbox/api-gl/issues/1404
> [core] Revert coalescing requests to the client for missing images

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/renderer/image_manager.cpp
- src/mbgl/renderer/image_manager.hpp
- test/map/map.test.cpp
- test/renderer/image_manager.test.cpp
This PR fixes https://github.com/mapbox/mapbox-gl-native/issues/15497 in a different way comparing to  the reverted https://github.com/mapbox/mapbox-gl-native/pull/15778: instead of coalescing requests we just do not treat requests for already requested images as pending (i.e. waiting to be dispatched to the client).
This is a safer approach, which obviates regressions like mapbox/api-gl#1404 (caused by the missing `rendererFrontend.update()` calls) - a dedicated unit test is added to verify the behavior.
> [core] No pending requests for already requested images. 

- include/mbgl/util/feature.hpp
- platform/android/src/geojson/feature.cpp
- platform/android/src/geojson/feature.hpp
- platform/darwin/src/MGLComputedShapeSource.mm
- platform/darwin/src/MGLFeature.mm
- platform/darwin/src/MGLFeature_Private.h
- platform/darwin/src/MGLShapeSource.mm
- platform/qt/src/qt_geojson.cpp
- platform/qt/src/qt_geojson.hpp
- render-test/parser.cpp
Move the fields from geometry.hpp/feature.hpp to GL Native as they are not part of the GeoJSON specification.
The related feature.hpp PR is here: https://github.com/mapbox/geometry.hpp/pull/67
> [core,android,darwin,qt] Add fields related to feature-state

- src/mbgl/geometry/line_atlas.cpp
- src/mbgl/geometry/line_atlas.hpp
- src/mbgl/renderer/layers/render_line_layer.cpp
- src/mbgl/renderer/render_orchestrator.cpp
- test/geometry/line_atlas.test.cpp
This moves the LineAtlas from a shared texture that contained SDF dash patterns to use individual textures.
Previously, the texture space was limited to a texture of 512 pixels height. Dash patterns were never removed (and are still never removed as of this patch), which means that this texture could fill up for styles that use a lot of different dash patterns. In particular, dash patterns for lines with a round line cap take up 15 pixels of texture height, limiting the amount of unique dash patterns to 34. While this was probably enough for rendering a single style, we quickly exhausted this number when reusing the Map object to render different styles.
Instead of a global shared texture, we're now creating individual textures for every dash pattern. These textures are still cached so …
> Use individual textures for line dash patterns

- include/mbgl/style/sources/geojson_source.hpp
- platform/android/CHANGELOG.md
- platform/android/src/style/sources/geojson_source.cpp
- platform/android/src/style/sources/geojson_source.hpp
- src/mbgl/style/sources/geojson_source.cpp
- src/mbgl/style/sources/geojson_source_impl.cpp
- src/mbgl/style/sources/geojson_source_impl.hpp
Composing tiles from the GeoJSON features is an expensive  operation that might block UI thread on updating the `GeoJsonSource`  with the new data.
This change moves tile composing to the background thread and thus  unblocks the UI thread.
Fixes: https://github.com/mapbox/mapbox-gl-native-team/issues/87
Tag: https://github.com/mapbox/mapbox-gl-native/issues/8484
>  [android] Convert GeoJSON features to tiles in background

- render-test/manifest_parser.cpp
Allows to run tests with regexp, for example:
`./mbgl-render-test-runner --manifestPath=../render-test/linux-manifest.json --filter='.*icon-offset.*'`
> [render-test] Fix regex match for render-test testFilter input

- include/mbgl/actor/scheduler.hpp
- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/style/sources/geojson_source.cpp
- src/mbgl/util/thread_pool.hpp
- test/util/async_task.test.cpp
Unblocks the UI thread on heavy GeoJSON tiles parsing operation.
The auxiliary `Scheduler::scheduleAndReplyValue` API and a unit test  have been added.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/98
>  [core] Parse GeoJSONSource description in background

- platform/default/include/mbgl/storage/offline_database.hpp
- platform/default/src/mbgl/storage/offline_database.cpp
- fixes missing exception handlers (e.g. runtim error from the `initialize()` method)
- introduces generic exception handling mechanism to reduce the repeated code
Follow-up: https://github.com/mapbox/mapbox-gl-native/pull/15899#discussion_r344214097
> [core] Improve OfflineDatabase error handling

- cmake/render-test.cmake
```
Undefined symbols for architecture x86_64:
"mbgl::ProxyFileSource::getRequestCount()", referenced from:
TestRunner::runOperations(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, TestMetadata&, RunContext&) in runner.cpp.o
"mbgl::ProxyFileSource::isTrackingActive()", referenced from:
TestRunner::runOperations(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, TestMetadata&, RunContext&) in runner.cpp.o
"mbgl::ProxyFileSource::setTrackingActive(bool)", referenced from:
TestRunner::runOperations(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, TestMetadata&, RunContext&) in runner.cpp.o
TestRunner::run(TestMetadata&) in runner.cpp.o …
```
> Fix linking error in render-test

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/renderer/sources/render_geojson_source.cpp
- test/style/source.test.cpp
Before this change, the GeoJSON source cleared tile pyramid
at any style transition and it caused flickering.
Now, in Continuous mode, we keep the existing tiles until the
new GeoJSON data is available, thus providing smart
style transitions without flickering.
In other modes (Static, Tile) clear the tile pyramid in order
to avoid render tests being flaky.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/104
> [core] Avoid GeoJSON source flickering on style transitions

- render-test/metadata.hpp
- render-test/runner.cpp
This deals with two types of warnings which fail the build given the default `-Werror` flag.
```
../../render-test/runner.cpp:937:17: error: variable 'transitionFinished' used in loop condition not modified in loop body [-Werror,-Wfor-loop-analysis]
for (; !transitionFinished; frames++) {
^~~~~~~~~~~~~~~~~~
```
```
../../render-test/runner.cpp:38:7: warning: field 'numBuffers' will be initialized after field 'numDrawCalls' [-Wreorder]
: numBuffers(stats.numBuffers),
^
../../render-test/runner.cpp:40:7: warning: field 'numFrameBuffers' will be initialized after field 'numTextures' [-Wreorder]
numFrameBuffers(stats.numFrameBuffers),
^
../../render-test/runner.cpp:43:7: warning: field 'memVertexBuffers' will be initialized after field 'memTextures' [-Wreorder] …
```
> Fix compile of render-test with clang-8

- include/mbgl/storage/default_file_source.hpp
- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/offline/CacheTest.kt
- platform/android/src/offline/offline_manager.cpp
- platform/android/src/offline/offline_manager.hpp
- platform/android/src/offline/offline_region.cpp
- platform/android/src/offline/offline_region.hpp
- platform/default/include/mbgl/storage/offline_database.hpp
- platform/default/src/mbgl/storage/default_file_source.cpp
- platform/default/src/mbgl/storage/offline_database.cpp
- test/storage/offline_database.test.cpp
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/102
> [core][android]Decouple offline storage vacuum and the deleteRegion API

- circle.yml
> [ci] No firebase skip for commits touching paths other than darwin-specific

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/renderer/sources/render_geojson_source.cpp
> CP #15907 to sangria

- src/mbgl/style/collection.hpp
- src/mbgl/style/style_impl.cpp
- src/mbgl/style/style_impl.hpp
- test/style/style.test.cpp
And use it for style sources and images, so that we do not unnecessarily remove and re-add  sources and images if their order has been modified  in the updated style object.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/108
> [core] Introduce style::CollectionWithPersistentOrder

- next/test/CMakeLists.txt
- src/mbgl/tile/tile_cache.cpp
- test/test-files.json
- test/tile/tile_cache.test.cpp
CP of https://github.com/mapbox/mapbox-gl-native/pull/15927
> [CP][core] Fix of incorrect resizing of TileCache

- src/mbgl/renderer/render_tile.hpp
**Problem**
Compile error occurs on MacOS Catalina (with Clang 11.0)
> In file included from mapbox-gl-native/src/mbgl/layout/symbol_projection.cpp:3:
> /Users/roman.kuznetsov/Dev/Projects/mapbox-vision/thirdparty/mapbox-gl-native/src/mbgl/renderer/render_tile.hpp:29:17: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
>    RenderTile& operator=(RenderTile&&) = default;
>                ^
> mapbox-gl-native/src/mbgl/renderer/render_tile.hpp:32:11: note: move assignment operator of ‘RenderTile’ is implicitly deleted because field ‘tile’ is of reference type ‘mbgl::Tile &’
>    Tile& tile;
>          ^
> 1 error generated.
**Reason**
As long as RenderTile contains reference to object (mbgl::Tile &) explicit default move …
> [core] Remove default move operator for RenderTile

- platform/android/CHANGELOG.md
- platform/ios/CHANGELOG.md
- src/mbgl/style/collection.hpp
- src/mbgl/style/style_impl.cpp
- src/mbgl/style/style_impl.hpp
- test/style/style.test.cpp
And use it for style sources and images, so that we do not unnecessarily remove and re-add sources and images if their order has been modified in the updated style object.
CP of https://github.com/mapbox/mapbox-gl-native/pull/15941
> [CP][core] Introduce style::CollectionWithPersistentOrder

- circle.yml
- next/CMakeLists.txt
- scripts/ci/Dockerfile
- scripts/valgrind.sup
Memory Sanitizer requires all the dependencies, including libstdc++ to be compiled with Memory Sanitizer, otherwise we will get tons of false positives.
> [build] Run Valgrind instead of Memory Sanitizer

- circle.yml
- render-test/android/app/build.gradle
This new added CircleCi job will build `RenderTestRunn android app` and run a simple instrumentation test on Firebase. The purpose of this test is to open the app and run all the render test cases that wrapped together with the app. The test app will write the render test result into a *.html page, which will show  all the render test case running results.
> [render-test] Config CircleCi to run RenderTestApp on Firebase with Pixel4

- include/mbgl/storage/default_file_source.hpp
- platform/android/CHANGELOG.md
- platform/default/src/mbgl/storage/default_file_source.cpp
- platform/default/src/mbgl/storage/online_file_source.cpp
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- test/storage/default_file_source.test.cpp
Fixes: #15925
Fixes: mapbox/mapbox-gl-native-team#106
> Make requests for expired resources lower priority than requests for new resources

- render-test/render_test.cpp
- render-test/runner.cpp
- render-test/runner.hpp
This allows injection of memory, gfx and network probes before and after operations that are defined in render test are run.
Example: `./mbgl-render-test-runner --manifestPath=./render-test/linux-manifest.json --filter=text-field --probe=memory --probe=gfx --probe=network`
`UPDATE_METRICS=true` to update expected metrics
`UPDATE_METRICS=true ./mbgl-render-test-runner --manifestPath=./render-test/linux-manifest.json --filter=text-field --probe=memory --probe=gfx --probe=network`
> [test-runner] Add render test runner options for injecting probes

- src/mbgl/geometry/line_atlas.cpp
In https://github.com/mapbox/mapbox-gl-native/pull/15862, we introduced individual textures for line dash patterns to eliminate atlas overflows. Unfortunately, this broke dashed lines that had round caps (dashed lines with straight caps still rendered correctly). Line pattern textures for round caps were now using 256×15 pixel textures.
The [OpenGL ES 2.0 spec, section 3.8.2](https://www.khronos.org/registry/OpenGL/specs/es/2.0/es_full_spec_2.0.pdf) states:
> Calling a sampler from a fragment shader will return `(R,G,B,A) = (0,0,0,1)` if any of the following conditions are true:
> - […]
> - A two-dimensional sampler is called, the corresponding texture image is a non-power-of-two image […], and either the texture wrap mode is not `CLAMP_TO_EDGE`, or the minification filter is neither …
> [core] fix rendering of dashed lines with round caps

- next/CMakeLists.txt
Add an option to include platform specific implementation sources
to `mbgl-core`.
> [build] Add an option to include platform specific implementation

- src/mbgl/renderer/sources/render_geojson_source.cpp
- test/style/source.test.cpp
In tile and static mode always clear tiles when data changes in order to avoid render tests being flaky.
https://circleci.com/gh/mapbox/mapbox-gl-native/374489?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> [core] Clear tiles when GeoJSON data changes

- circle.yml
- render-test/manifest_parser.cpp
- render-test/manifest_parser.hpp
- render-test/render_test.cpp
- render-test/runner.cpp
- render-test/runner.hpp
- Move probe related command line arguments to manifest, example:
```json
"probes": ["probeGFX", "probeNetwork", "probeMemory"],
"metric_path": "metrics/linux"
```
- Use manifest file name as a postfix for a result page
- Move injected probes 'begin' section before map object creation
- Generalize artifact storing shell script
> [test-runner] Move probe related command line args to manifest 

- platform/android/README.md
- platform/ios/README.md
Per @samfader 's suggestion, this pr adds a blurb to this repo's Android README with a notice that our Maps SDK for Android work has been moved to https://github.com/mapbox/mapbox-gl-native-android
> [android] README update about work being moved to new repo

- render-test/render_test.cpp
- render-test/runner.cpp
- render-test/runner.hpp
Added the following command line argument:
```
-u[update], --update=[update]     Test results update mode.
Supported values are: "default", "platform", "metrics"
```
> [test runner] Enable test results update from cmd line

- include/mbgl/actor/scheduler.hpp
- src/mbgl/actor/scheduler.cpp
- test/util/async_task.test.cpp
The newly introduced `Scheduler::GetSequenced()` returns sequenced schedulers from the cache limited to 10 instances, preventing from spawning too many threads.
Required for https://github.com/mapbox/mapbox-gl-native/pull/15953#issuecomment-559035519
> [core] Introduce Scheduler::GetSequenced() API

- metrics/tests/binary-size/android-arm64-v8a/metrics.json
- metrics/tests/binary-size/android-arm64-v8a/style.json
- metrics/tests/binary-size/android-armeabi-v7a/metrics.json
- metrics/tests/binary-size/android-armeabi-v7a/style.json
- metrics/tests/binary-size/android-x86/metrics.json
- metrics/tests/binary-size/android-x86/style.json
- metrics/tests/binary-size/android-x86_64/metrics.json
- metrics/tests/binary-size/android-x86_64/style.json
- render-test/runner.cpp
- render-test/tests/file-size/pass-size-is-same/metrics.json
- render-test/tests/file-size/pass-size-is-same/style.json
Useful because for platform such as Android, we want to measure the size of the library inside the APK, which is usually compressed.
> [render-test] Add support for measuring compressed file size

- include/mbgl/style/sources/geojson_source.hpp
- platform/android/src/style/sources/geojson_source.cpp
- platform/android/src/style/sources/geojson_source.hpp
- platform/darwin/src/MGLShapeSource.mm
- platform/darwin/src/MGLShapeSource_Private.h
- platform/darwin/test/MGLShapeSourceTests.mm
- src/mbgl/style/conversion/source.cpp
- src/mbgl/style/sources/geojson_source.cpp
- src/mbgl/style/sources/geojson_source_impl.cpp
- src/mbgl/style/sources/geojson_source_impl.hpp
- test/api/query.test.cpp
- test/style/source.test.cpp
- fix wrapping of the parameters in supercluster map/reduce lambdas (Previously, local variables were wrapped by reference).
- share the `GeoJSONOptions` instances using `Immutable<GeoJSONOptions>` - avoid extra copying
> [core] Fix supercluster lambdas capturing

- include/mbgl/style/sources/geojson_source.hpp
- src/mbgl/renderer/sources/render_geojson_source.cpp
- src/mbgl/style/sources/geojson_source_impl.cpp
- src/mbgl/tile/geojson_tile.cpp
- src/mbgl/tile/geojson_tile.hpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/geometry_tile_worker.cpp
- src/mbgl/tile/geometry_tile_worker.hpp
- test/tile/geojson_tile.test.cpp
Call `mapbox::geojsonvt::GeoJSONVT::getTile()` in a background thread, so that the rendering thread is not blocked.
**Before:**
**After:**
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/87
> [core] Calculate GeoJSON tile geometries in a background thread

- metrics/tests/binary-size/android-arm64-v8a/metrics.json
- metrics/tests/binary-size/android-x86_64/metrics.json
- next/platform/android/android.cmake
Chromium is using it for a while on ARM.
https://codereview.chromium.org/1153143004/patch/20001/30002
> [android] Use icf=all

- platform/glfw/glfw_gl_backend.cpp
Apparently GLFW is implicitly calling glViewport on macOS but not on Linux. Force setting the viewport instead of assuming a value.
> [glfw] Fix map not resizing on Linux

- include/mbgl/style/sources/geojson_source.hpp
- src/mbgl/style/sources/geojson_source.cpp
Otherwise, the construction of the `Immutable<Source::Impl>` in background thread might never yeld.
> [core] Retain thread pool in GeoJSONSource

- src/mbgl/gl/context.cpp
Blacklist in order to avoid crashes in a driver (Android 5.1.1)
Fixes: #15709
Verified on Vivo V3 HW (Android 5.1.1)
> [core] Blacklist VAO extension for Adreno (TM) 4xx GPUs

- render-test/runner.cpp
If there are multiple file size probes in a test file, it is better to report all failures instead of first failed probe.
> [test-runner] Log all 'probeFileSize' failures

- include/mbgl/storage/default_file_source.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
- platform/android/src/offline/offline_manager.cpp
- platform/android/src/offline/offline_manager.hpp
- platform/android/src/offline/offline_region.cpp
- platform/android/src/offline/offline_region.hpp
- platform/default/include/mbgl/storage/offline_database.hpp
- platform/default/src/mbgl/storage/default_file_source.cpp
- platform/default/src/mbgl/storage/offline_database.cpp
- test/storage/offline_database.test.cpp
Fixes mapbox/mapbox-gl-native-team#102
> [core][android] Introduce OfflineManager.runPackDatabaseAutomatically(boolean) API

- include/mbgl/actor/scheduler.hpp
- next/CMakeLists.txt
- src/mbgl/actor/scheduler.cpp
- test/actor/actor.test.cpp
- test/util/async_task.test.cpp
Thus we enforce client to retain the returned `Scheduler` objects.
> [core] Introduce Pass<> class and use it for Scheduler

- include/mbgl/style/layer.hpp
- include/mbgl/style/layers/background_layer.hpp
- include/mbgl/style/layers/circle_layer.hpp
- include/mbgl/style/layers/custom_layer.hpp
- include/mbgl/style/layers/fill_extrusion_layer.hpp
- include/mbgl/style/layers/fill_layer.hpp
- include/mbgl/style/layers/heatmap_layer.hpp
- include/mbgl/style/layers/hillshade_layer.hpp
- include/mbgl/style/layers/layer.hpp.ejs
- include/mbgl/style/layers/line_layer.hpp
- include/mbgl/style/layers/raster_layer.hpp
- include/mbgl/style/layers/symbol_layer.hpp
- platform/android/src/style/layers/layer.cpp
- platform/android/src/style/layers/layer.hpp
- platform/node/src/node_map.cpp
- platform/node/src/node_map.hpp
- platform/qt/src/qmapboxgl.cpp
- render-test/runner.cpp
- src/mbgl/style/conversion/layer.cpp
- src/mbgl/style/layers/background_layer.cpp
- src/mbgl/style/layers/circle_layer.cpp
- src/mbgl/style/layers/custom_layer.cpp
- src/mbgl/style/layers/fill_extrusion_layer.cpp
- src/mbgl/style/layers/fill_layer.cpp
- src/mbgl/style/layers/heatmap_layer.cpp
- src/mbgl/style/layers/hillshade_layer.cpp
- src/mbgl/style/layers/layer.cpp.ejs
- src/mbgl/style/layers/line_layer.cpp
- src/mbgl/style/layers/raster_layer.cpp
- src/mbgl/style/layers/symbol_layer.cpp
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/105
> Merge style::Layer::set{Layout,Paint}Property

- next/platform/linux/linux.cmake
- platform/android/src/test/render_test_runner.cpp
- render-test/android-manifest-probe-memory.json
- render-test/linux-manifest-probe-memory.json
- render-test/manifest_parser.cpp
- render-test/manifest_parser.hpp
- render-test/render_test.cpp
Command line option is still available and allows to override filter that is defined in a manifest file.
> [test-runner] Allow to define filter inside manifest file

- include/mbgl/map/map.hpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/glfw/glfw_view.cpp
- platform/glfw/glfw_view.hpp
- platform/qt/app/mapwindow.cpp
- platform/qt/include/qmapboxgl.hpp
- platform/qt/src/qmapboxgl.cpp
- src/mbgl/map/map.cpp
This function was mostly used by the Android API, which is no longer necessary (we can still implement it using the map debug accessor and modifier).
> [core] Move logic from Map::cycleDebugOptions to GLFW example app

- src/mbgl/text/collision_index.cpp
- src/mbgl/text/collision_index.hpp
- src/mbgl/text/placement.cpp
When rendering image tiles using MapMode::Tile we need to avoid clipped labels at tile boundaries. Clipped labels happen when one tile decides a label can be shown and the other tile decides that it collides with something and needs to be hidden.
When rendering overscaled image tiles (rendering z17 image tiles for a vector tile source that only goes up to z16) we should use all the data from the tile instead of just the data that fits within the image tile.
This increases the padding to 1024 for MapMode::Tile which should be enough to completely include all the data two zoom levels past the data source's max zoom level. Beyond that, 1024 *should* be enough of a padding to make clipped labels unlikely.
An alternative would be to calculate the max zoom levels of all the sources used and …
> [core] increase padding in CollisionIndex for MapMode::Tile

- cmake/glfw.cmake
- metrics/tests/binary-size/linux-gcc8/metrics.json
- metrics/tests/binary-size/macos-xcode11/metrics.json
- next/platform/glfw/CMakeLists.txt
- platform/glfw/glfw_view.cpp
- platform/glfw/glfw_view.hpp
- platform/glfw/main.cpp
- platform/glfw/test_writer.cpp
- platform/glfw/test_writer.hpp
Press F1 to create a render test for the current view.
The test will be created at the base folder (current if nothing is provided) + /NNNN (the next free entry).
> [glfw] Add static render test creator

- next/test/CMakeLists.txt
- src/mbgl/geometry/anchor.hpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/layout/symbol_layout.hpp
- src/mbgl/renderer/buckets/symbol_bucket.hpp
- src/mbgl/text/check_max_angle.cpp
- src/mbgl/text/collision_feature.cpp
- src/mbgl/text/collision_feature.hpp
- src/mbgl/text/get_anchors.cpp
- test/test-files.json
- test/text/calculate_tile_distances.test.cpp
- test/text/get_anchors.test.cpp
- test/text/quads.test.cpp
Erroneous signed to unsigned implicit conversion was used  when PlacedSymbol(s) were created in SymbolLayout and signed values were used as indexes in a few other places.
> [core] Don't use signed int type for anchor segment

- platform/node/test/ignores.json
- update mapbox-gl-js
- add ignores for all render tests added in -js since the last update
> update mapbox-gl-js 

- circle.yml
- next/CMakeLists.txt
- next/benchmark/CMakeLists.txt
- next/bin/CMakeLists.txt
- next/platform/android/android.cmake
- next/platform/glfw/CMakeLists.txt
- next/platform/linux/linux.cmake
- next/platform/macos/macos.cmake
- next/platform/node/CMakeLists.txt
- next/platform/qt/qt.cmake
- next/render-test/CMakeLists.txt
- next/test/CMakeLists.txt
Previously we had UndefinedBehavior mixed with other sanitizers, in special implicit conversions and overflows. Also, run the sanitizers in Release configuration, so they will run faster. -O1 is just needed for perfectly nice stack traces.
Also, moving the flags to an interface will prevent them to leak to our external dependencies.
> [build] Better isolate compiler flags

- include/mbgl/style/light.hpp
- include/mbgl/style/light.hpp.ejs
- platform/glfw/test_writer.cpp
- platform/glfw/test_writer.hpp
- render-test/metadata.hpp
- render-test/parser.cpp
- render-test/parser.hpp
- render-test/render_test.cpp
- render-test/runner.cpp
- render-test/runner.hpp
- src/mbgl/style/light.cpp
- src/mbgl/style/light.cpp.ejs
So that the list of operations once parsed, could be applied several times. This is crucial functionality for the comprehensive tile mode support in the test runner  (https://github.com/mapbox/mapbox-gl-native-team/issues/94)
> [test runner] Split test operations parsing and execution

- CHANGELOG.md
We need to start collecting core specific changelog entries. This PR adds changelog with entries since the last release (Android 8.5.0-alpha.2)
> [core] Create gl-native changelog with entries since the last release

- render-test/metadata.hpp
Otherwise they are left uninitialized and cause GFX metrics failures.
> [test runner] Explicitly initialize TestContext POD members

- .gitignore
- metrics/next-android-render-test-runner/render-tests/icon-image/token/metrics.json
- metrics/next-android-render-test-runner/render-tests/text-field/token/metrics.json
- metrics/next-linux-clang8-release/render-tests/icon-image/token/metrics.json
- metrics/next-linux-clang8-release/render-tests/text-field/token/metrics.json
- metrics/next-linux-gcc8-release/render-tests/icon-image/token/metrics.json
- metrics/next-linux-gcc8-release/render-tests/text-field/token/metrics.json
- metrics/next-macos-xcode11-release/render-tests/icon-image/token/metrics.json
- metrics/next-macos-xcode11-release/render-tests/text-field/token/metrics.json
This explains why these tests were not being rebaselined...
> [metrics] Remove **/token from .gitignore

- src/mbgl/map/map.cpp
- test/map/map.test.cpp
Submit external contribution: https://github.com/mapbox/mapbox-gl-native/pull/16061.
Include padding when testing camera scale in cameraForLatLngBounds:
Repurpose LatLngBoundsToCameraWithBearingAndPitch to test scaling and camera setup, both with and without padding.
Padding test (LatLngBoundsToCameraWithExcessivePadding) is not testing scaling code path in cameraForLatLngBounds. This adds the test for it and makes the test less permissive. See mapbox/mapbox-gl-native-ios#59.
> Correct padding management in cameraForLatLngBounds

- platform/default/src/mbgl/storage/offline_download.cpp
- test/storage/offline_download.test.cpp
Otherwise, the stale buffer data are processed again at the
repeated load. It is causing various problems like missing load
completion notification or crashes (if the previously used observer
instance has been deleted).
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/127
> [core] Offline download must clear batch buffer at load interrupt

- include/mbgl/map/map.hpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/default/src/mbgl/storage/offline_download.cpp
- platform/glfw/glfw_view.cpp
- platform/glfw/glfw_view.hpp
- platform/qt/app/mapwindow.cpp
- platform/qt/include/qmapboxgl.hpp
- platform/qt/src/qmapboxgl.cpp
- src/mbgl/map/map.cpp
- test/storage/offline_download.test.cpp
This PR cherry-picks 1 PR:
- https://github.com/mapbox/mapbox-gl-native/pull/16073
and reverts: 
- https://github.com/mapbox/mapbox-gl-native/commit/1e2cd1e086c3053f1cea075d7641b7f56cc7dfbf
We need to revert this commit for this release as it was breaking the public api downstream https://github.com/mapbox/mapbox-gl-native-android/issues/103. We will address this api breakage by next release cycle.
> Cherry pick fixes to release-tequila 

- src/mbgl/layout/symbol_layout.cpp
The style specification stipulates that `text-size` values must be positive
(https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-size).
However, a zero value could be passed to the engine (e.g. as a result of
an expression). This PR handles it and thus avoids an assertion hit in `shaping.cpp`.
The render test : https://github.com/mapbox/mapbox-gl-js/pull/9133
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/129
> [core] Handle zero text size

- src/mbgl/style/parser.cpp
- src/mbgl/style/parser.hpp
This removes the `sourcesMap` member of `mbgl::style::Parser` because I noticed that it is a private member that is not used in any meaningful way (that I can see) in the implementation.
So, if I'm right that it is basically unused code, this should reduce memory usage needs for style parsing.
> Remove 'sourcesMap' on style parser

- circle.yml
- next/CMakeLists.txt
- next/benchmark/CMakeLists.txt
- next/platform/android/android.cmake
- next/render-test/CMakeLists.txt
- next/test/CMakeLists.txt
Moved the Android flags to the compilation options interface and removed build options we are not using and go back to CMake defaults.
We can still build debug just fine, it is a CMake default.
> [build] Make the configuration simpler

- next/render-test/CMakeLists.txt
- render-test/manifest_parser.cpp
- render-test/manifest_parser.hpp
- render-test/render_test.cpp
Not in use and we should use -f instead. Achieves the same goal.
> [render-test] Removed unused positional argument

- include/mbgl/map/map.hpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- src/mbgl/map/map.cpp
- test/map/map.test.cpp
refs https://github.com/mapbox/mapbox-gl-native-android/issues/81 
This PR adds Android jni binding for `getVisibleCoordinateBound`. 
This PR also addes `Map::latLngBoundsForCameraUnwrapped(const CameraOptions& camera)` to  handle the rotated map and the case when the region is across the dateline.
> [android][core] Add `Map::latLngBoundsForCameraUnwrapped` and jni binding for `getVisibleCoordinateBounds`.

- src/mbgl/style/sources/geojson_source_impl.cpp
- src/mbgl/util/thread_pool.hpp
Before this change, the `GeoJSONVTData` instance was retained at the scheduled
lambda, which run on the worker thread represented by the `GeoJSONVTData::scheduler`
class member:
```
std::weak_ptr<GeoJSONVTData> weak = shared_from_this();
scheduler->scheduleAndReplyValue(
[id, weak, this]() -> TileFeatures {
if (auto self = weak.lock()) {
return impl.getTile(id.z, id.x, id.y).features;
}
return {};
},
fn);
```
It caused program termination in case `self` turned to be the last reference to `this`,
as the `std::thread` destructor was called from the thread it represented.
Now, only the `GeoJSONVTData::impl` class member is retained.
Fixes: https://github.com/mapbox/mapbox-gl-native/issues/16101
> [core] Fix GeoJSONVTData ownership and life cycle

- circle.yml
This PR adds a CI bot that validates if downstream code is still build-able for a given PR. 
> Note that this setup is only in place until we find a general better way of testing downstream projects (eg. trigger a CI bot downstream and monitor execution from a bot in this repo). 
We will not make this bot required,  this should solely serve as a trigger to notify the downstream team of breaking API changes. 
cc @mapbox/gl-native @julianrex @zugaldia @chloekraw
> Add CI bot that validates downstream API breakage

- src/mbgl/style/sources/geojson_source_impl.cpp
- src/mbgl/util/thread_pool.hpp
CP https://github.com/mapbox/mapbox-gl-native/pull/16106 to `release-tequila`
> [cp][core] Fix GeoJSONVTData ownership and life cycle

- circle.yml
- next/platform/ios/ios.cmake
- Adds `native_apple_interface.m` to the `ios.cmake` file. 
- Updates the `next-ios-xcode11-release` CircleCI job to use Xcode rather than Ninja.
cc @captainbarbosa @julianrex
> [ios] Add native_apple_interface to ios.cmake

- circle.yml
Avoid restoring next-sanity-checks ccache since it will cause unarchive error for newly added macos jobs.
> [build] Avoid restoring next-sanity-checks ccache with MacOS environment

- CHANGELOG.md
- include/mbgl/renderer/renderer.hpp
- platform/android/src/map_renderer.cpp
- platform/darwin/src/MGLRendererFrontend.h
- platform/default/src/mbgl/gfx/headless_frontend.cpp
- platform/glfw/glfw_renderer_frontend.cpp
- platform/qt/src/qmapboxgl_map_renderer.cpp
- src/mbgl/layout/symbol_instance.hpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/renderer/bucket.hpp
- src/mbgl/renderer/buckets/symbol_bucket.cpp
- src/mbgl/renderer/buckets/symbol_bucket.hpp
- src/mbgl/renderer/render_orchestrator.cpp
- src/mbgl/renderer/render_orchestrator.hpp
- src/mbgl/renderer/renderer.cpp
- src/mbgl/text/collision_index.cpp
- src/mbgl/text/collision_index.hpp
- src/mbgl/text/cross_tile_symbol_index.cpp
- src/mbgl/text/cross_tile_symbol_index.hpp
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
- test/text/cross_tile_symbol_index.test.cpp
Before this change cross tile symbol indexing was a performance bottle neck, for the overscaled tiles in particular. This pull request optimizes the cross tile symbol indexing code path:
- find matches only among the buckets that have the same leader Id.
- for overscaled tiles, index only the symbols inside the viewport
- multiple minor optimizations and code simplifications
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/133
> Cross tile index performance

- src/mbgl/layout/symbol_layout.cpp
A const reference is enough here.
> [core] remove std::vector copy step in SymbolLayout::anchorIsTooClose

- CHANGELOG.md
- include/mbgl/actor/mailbox.hpp
- platform/default/src/mbgl/storage/main_resource_loader.cpp
- src/mbgl/actor/mailbox.cpp
- src/mbgl/storage/main_resource_loader.hpp
If there are pending requests that are completed after main scheduler is destructed, worker threads may try to push messages to destructed scheduler's queue.
This PR also moves main resource loader to dedicated thread with own scheduler.
> [core] Use weak scheduler inside mailbox

- include/mbgl/style/sources/geojson_source.hpp
- src/mbgl/style/sources/geojson_source.cpp
- src/mbgl/style/sources/geojson_source_impl.cpp
Thus avoiding spawning new threads on `setGeoJSONData()` calls.
> GeoJSONSource is re-using the existing scheduler

- include/mbgl/storage/database_file_source.hpp
- metrics/next-binary-size/linux-clang8/metrics.json
- next/test/CMakeLists.txt
- platform/default/src/mbgl/storage/database_file_source.cpp
- test/storage/database_file_source.test.cpp
- test/test-files.json
Added pause / resume functionality to database file source.
> [core] Add pause and resume to database filesource implementation

- CMakeLists.txt
- next/CMakeLists.txt
We've faced the issue when very simple code snippet works in unexpected way if compile with RTTI enabled and link against gl-native:
```
#include <iostream>
int main() {
try {
throw std::invalid_argument("foo");
} catch (const std::exception& ex) {
std::cerr << "Exception handled as expected" << std::endl;
} catch (...) {
std::cerr << "WUT? std::invalid_argument handled in ... block" << std::endl;
}
return 0;
}
```
If I compile it with RTTI enabled and link against gl-native it will output `WUT? std::invalid_argument handled in ... block`. My experiments show that it works as expected if both gl-native and my executable are built with either RTTI enabled or disabled. 
I made a simple project demonstrating this issue:
[gl-native-rtti-demo.zip](https://github.com/mapbox/mapbox-gl-native/file …
> [build] Add WITH_NO_RTTI CMake option to be able to build gl-native with RTTI if needed

- circle.yml
The iOS test bot is failing because auth is failing.
> [build] Remove baseline bot dependency on iOS tests

- CHANGELOG.md
- src/mbgl/storage/file_source_manager.cpp
Factory 'get' method can be invoked recursively and stable iterators are required to guarantee safety.
> [core] Use std::list instead of std::map for factory instance

- include/mbgl/style/property_expression.hpp
- src/mbgl/style/property_expression.cpp
New method can be used for aggregating property expressions from
multiple properties(layers) into single match / case expression.
> [core] Add getSharedExpression to property expression

- CHANGELOG.md
- src/mbgl/storage/file_source_manager.cpp
Cherry pick https://github.com/mapbox/mapbox-gl-native/pull/16161 to release-unicorn branch.
> [cp][core] Use std::list instead of std::map for factory instance

- platform/default/src/mbgl/i18n/number_format.cpp
numberformatter.h is not included with next/vendor/icu, so we can't use mbgl-vendor-icu, and must look for a system ICU. This is fine, however the file platform/default/src/mbgl/i18n/number_format.cpp does not handle newer version of ICU (since toString() was deprecated and removed, requiring toString(status) ).
This fixed support for newer version of ICU, no longer using the deprecated (and later removed) API call. Though in future, the vendor ICU should have numberformatter added to it.
> Made number format work for newer versions of ICU

- CHANGELOG.md
- include/mbgl/storage/database_file_source.hpp
- platform/default/include/mbgl/storage/offline_database.hpp
- platform/default/src/mbgl/storage/database_file_source.cpp
- platform/default/src/mbgl/storage/offline_database.cpp
- test/storage/offline_database.test.cpp
This PR exposes `DatabaseFileSource` property, which allows to re-open the offline database in read-only mode and thus improves the performance for the set ups that do not require the offline database modifications. Example of usage:
```
auto fileSource = mbgl::FileSourceManager::get()->getFileSource(
mbgl::FileSourceType::Database, resourceOptions);
fileSource->setProperty(READ_ONLY_MODE_KEY, true);
```
Tag https://github.com/mapbox/mapbox-gl-native-team/issues/169
> Expose READ_ONLY_MODE_KEY property for DatabaseFileSource

- CHANGELOG.md
- include/mbgl/style/image.hpp
- include/mbgl/style/style.hpp
- metrics/binary-size/android-armeabi-v7a/metrics.json
- metrics/binary-size/linux-gcc8/metrics.json
- platform/android/src/native_map_view.cpp
- platform/darwin/src/MGLStyle.mm
- src/mbgl/map/map_impl.cpp
- src/mbgl/sprite/sprite_loader.cpp
- src/mbgl/sprite/sprite_loader.hpp
- src/mbgl/sprite/sprite_loader_observer.hpp
- src/mbgl/sprite/sprite_parser.cpp
- src/mbgl/sprite/sprite_parser.hpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style_impl.cpp
- src/mbgl/style/style_impl.hpp
- test/renderer/image_manager.test.cpp
- test/renderer/pattern_atlas.test.cpp
- test/sprite/sprite_loader.test.cpp
- test/sprite/sprite_parser.test.cpp
- test/style/style.test.cpp
This change enables attaching images to the style with batches and avoids massive re-allocations. Thus, it improves UI performance especially at start-up time.
Tag https://github.com/mapbox/mapbox-gl-native-team/issues/169
> [core] Loading images to style optimization

- CHANGELOG.md
- include/mbgl/style/property_expression.hpp
- metrics/android-render-test-runner/render-tests/within/layout-text/metrics.json
- metrics/ignores/platform-all.json
- metrics/ios-render-test-runner/render-tests/within/layout-text/metrics.json
- metrics/linux-clang8-release/render-tests/within/layout-text/metrics.json
- metrics/linux-gcc8-release/render-tests/within/layout-text/metrics.json
- src/mbgl/layout/pattern_layout.hpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/layout/symbol_layout.hpp
- src/mbgl/renderer/buckets/fill_bucket.cpp
- src/mbgl/renderer/buckets/line_bucket.cpp
- src/mbgl/renderer/buckets/line_bucket.hpp
- src/mbgl/renderer/possibly_evaluated_property_value.hpp
- src/mbgl/style/properties.hpp
This pr implement usage of `within` expression with layout property. Currently the usage is: [`within`, `geoJSONObj`]. It returns true if the feature is inside the geometry boundary that defined by `geoJSONObj`.  `geoJSONObj` should be inlined.
Following example shows how to set different text contents based on the feature's geometry location. 
```
{
"id": "text",
"type": "symbol",
"source": "points",
"layout": {
"text-field": ["case", ["within", {
"type": "Polygon",
"coordinates": [
[
[0, 0],
[0, 5],
[5, 5],
[5, 0],
[0, 0]
]
]
}], "In", "Out"],
"text-font": [
"Open Sans Semibold",
"Arial Unicode MS Bold"
],
"text-size": 10
},
"paint" : {
"text-color": "red"
}
}
```
> Enable `within` Expression with layout property

- test/map/map.test.cpp
In Map.PrefetchDelta* unit tests, tile request counter might be updated from multiple threads (default loader + cusom tile loader pool), therefore, counter must either guarded by mutexes or be atomic.
> [core] Use atomic int in Map.PrefetchDelta* unit tests

- CHANGELOG.md
- src/mbgl/sprite/sprite_loader.cpp
**What happened:**
The excessive `onSpriteLoaded()` notifications were caused by the trick inside `OnlineFileRequest::completed()` implementation, which causes receiving of two file source updates pointing to the *same* data in case _the network response is `notModified` and the local storage has the sprite sheet already stored inside_.
In the `SpriteLoader` implementation, it resulted in 2 extra `parseSprite()` calls and 2 extra `onSpriteLoaded()` notifications.
Then, the excessive `onSpriteLoaded()` notifications affected style images and all the unnecessarily added image dupes (btw, the amount of these dupes `= 2 * number of style images`) were treated by the `RenderOrchestrator` as *updated* images.
Further, `RenderOrchestrator` called `ImageManager::updateImage()` for the updated …
> [core] Fix excessive onSpriteLoaded() notifications

- CHANGELOG.md
- platform/default/src/mbgl/storage/main_resource_loader.cpp
- src/mbgl/sprite/sprite_loader.cpp
- test/storage/main_resource_loader.test.cpp
In cases when cached resource is useable, yet don't have an expiration timestamp, we provided data to the requester from the cache and the same data was returned once 304 response was received from the network.
> [core] Don't provide multiple responses with the same data for 304 replies

- CHANGELOG.md
- metrics/android-render-test-runner/render-tests/line-dasharray/zero-length-gap/metrics.json
- metrics/binary-size/linux-clang8/metrics.json
- metrics/ignores/platform-all.json
- metrics/ios-render-test-runner/render-tests/line-dasharray/zero-length-gap/metrics.json
- metrics/linux-clang8-release/render-tests/line-dasharray/zero-length-gap/metrics.json
- metrics/linux-gcc8-release/render-tests/line-dasharray/zero-length-gap/metrics.json
- src/mbgl/geometry/line_atlas.cpp
- src/mbgl/geometry/line_atlas.hpp
Port of bug-fix on line-dasharray from gl-js.
For background, refer:
- https://github.com/mapbox/mapbox-gl-js/issues/9213
- https://github.com/mapbox/mapbox-gl-js/pull/9246
Closes https://github.com/mapbox/mapbox-gl-native/issues/16181
> Port line-dasharray fix from gl-js

- src/mbgl/layout/symbol_instance.hpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/layout/symbol_layout.hpp
- src/mbgl/renderer/buckets/symbol_bucket.cpp
- src/mbgl/renderer/buckets/symbol_bucket.hpp
- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
- test/gl/bucket.test.cpp
- test/text/cross_tile_symbol_index.test.cpp
Cherry pick `[core] sort symbols using symbol-sort-key before placement` (#16023) to release sangria.
-  [x] unit-tests pass
-  [x] cherry picked render tests from https://github.com/mapbox/mapbox-gl-js/pull/9054 pass locally
> [cp][core] sort symbols using symbol-sort-key before placement

- platform/android/src/map_renderer.cpp
- platform/android/src/map_renderer.hpp
Android renderer creates mailbox that is owned by the scheduler that is required by the mailbox itself. Construction should be split, so that scheduler is fully constructed and it's weakPtr can be created.
No changelog required, since the file is not used in core.
> [android] Don't construct weak sheduler in renderer's custructor

- platform/qt/src/qmapboxgl.cpp
GCC complains about this variable being potentially not initialized.
> [qt] Fix compilation error

- CHANGELOG.md
- CMakeLists.txt
- include/mbgl/style/expression/within.hpp
- metrics/android-render-test-runner/render-tests/within/paint-line/metrics.json
- metrics/ios-render-test-runner/render-tests/within/paint-line/metrics.json
- metrics/linux-clang8-release/render-tests/within/paint-line/metrics.json
- metrics/linux-gcc8-release/render-tests/within/paint-line/metrics.json
- src/mbgl/style/expression/within.cpp
- src/mbgl/util/geometry_within.cpp
- src/mbgl/util/geometry_within.hpp
- test/style/property_expression.test.cpp
This pr will enable using `within` expression with features that contain `LineString` geometry type.
Fix: https://github.com/mapbox/mapbox-gl-native-team/issues/188
> [core] Support `line within polygon` in `within` expression

- platform/android/src/style/sources/source.cpp
- platform/android/src/style/sources/source.hpp
refs: [https://github.com/mapbox/mapbox-gl-native-android/issues/181](https://github.com/mapbox/mapbox-gl-native-android/issues/181)
This PR adds Android jni binding for `Source.setPrefetchZoomDelta` and `Source.getPrefetchZoomDelta`
> [android] add jni binding for source zoom delta

- CHANGELOG.md
- include/mbgl/storage/database_file_source.hpp
- include/mbgl/storage/file_source.hpp
- include/mbgl/storage/online_file_source.hpp
- platform/default/include/mbgl/storage/offline_download.hpp
- platform/default/src/mbgl/storage/offline_download.cpp
- render-test/file_source.cpp
- test/src/mbgl/test/stub_file_source.cpp
- test/src/mbgl/test/stub_file_source.hpp
- test/storage/offline_download.test.cpp
- test/storage/online_file_source.test.cpp
Downloaded resources are put in the buffer and inserted in the database in batches.
Before this change, the buffer was flushed only at the network response callback
and thus it never got flushed if the last required resources were present locally
and did not initiate network requests -> it caused freezing.
Now the buffer is flushed every time the remaining resources container gets empty.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/195
> [core] Fix offline region download freezing

- CHANGELOG.md
- CMakeLists.txt
- bin/cache.cpp
- bin/offline.cpp
- include/mbgl/actor/scheduler.hpp
- include/mbgl/storage/file_source.hpp
- include/mbgl/storage/file_source_manager.hpp
- include/mbgl/storage/online_file_source.hpp
- include/mbgl/util/pass_types.hpp
- platform/android/src/file_source.cpp
- platform/android/src/file_source.hpp
- platform/android/src/offline/offline_manager.cpp
- platform/android/src/offline/offline_region.cpp
- platform/darwin/src/MGLOfflineStorage.mm
- platform/darwin/src/MGLOfflineStorage_Private.h
- platform/default/src/mbgl/storage/file_source_manager.cpp
- platform/glfw/main.cpp
- platform/qt/src/qmapboxgl.cpp
- render-test/file_source.cpp
- src/mbgl/map/map.cpp
- src/mbgl/storage/file_source_manager.cpp
- test/CMakeLists.txt
- test/map/map.test.cpp
- test/src/mbgl/test/fake_file_source.hpp
- test/storage/database_file_source.test.cpp
- test/storage/main_resource_loader.test.cpp
- test/storage/online_file_source.test.cpp
- test/util/pass.test.cpp
> [core] FileSource API improvements

- CHANGELOG.md
- platform/ios/ios.cmake
Reverted part of #16158, reducing the minimum deployment target back from iOS 12.0 to iOS 9.0.
Fixes #16241.
/cc @mapbox/gl-native @mapbox/maps-ios
> Restore support for iOS 9–11 by default

- CHANGELOG.md
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
min and max pitch method will be added to android sdk. This pr add the jni binding for them. The related pr in map sdk: https://github.com/mapbox/mapbox-gl-native-android/pull/199
> [android] Add jni binding for min and max pitch

- CHANGELOG.md
- platform/default/src/mbgl/storage/offline_download.cpp
- platform/default/src/mbgl/storage/online_file_source.cpp
- test/storage/offline_download.test.cpp
If error `404` turns up during offline regions loading, the behavior is changed in the following way:
- Offline download does not hang
- The error message contains URL protocol and host
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/186
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15819
Fixes https://github.com/mapbox/mapbox-gl-native/issues/15932
> Improve behavior on getting error 404 during offline regions loading

- CHANGELOG.md
- src/mbgl/geometry/line_atlas.cpp
Fix using of invalid iterators.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/201
> [core] Fix iterators in addRegularDash()

- CHANGELOG.md
- platform/default/src/mbgl/util/run_loop.cpp
The `runOnce()` call during run loop destruction might cause `invoke()` calls.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/16250
> [default] Fix possible crash at RunLoop::wake()

- src/mbgl/renderer/layers/render_heatmap_layer.cpp
It triggers Metal depth stencil validation error since depth test is enabled with no depth attachment.
> Disable depth in heatmap offscreen rendering.

- circle.yml
- metrics/linux-gcc8-debug-coverage-nightly-style.json
Use the same test manifest for the development and nightly
coverage CI builds. Add manifest for the nightly build by
creating a symbolic link to the existing manifest.
> [test] Add test manifest for the nightly build

- src/mbgl/layout/symbol_instance.hpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/renderer/bucket.hpp
- src/mbgl/renderer/buckets/symbol_bucket.cpp
- src/mbgl/renderer/buckets/symbol_bucket.hpp
- src/mbgl/renderer/layers/render_symbol_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
- Encapsulate placement code handling symbols sort ranges inside `SymbolBucket`
- Get rid of `LayerPlacementData::firstInBucket` - simplification
- Split `LayerPlacementData` and `BucketPlacementData` - improvements to `RenderLayer` API
Tag https://github.com/mapbox/mapbox-gl-native-team/issues/132
> [core] Refactor symbol sort key handling

- CHANGELOG.md
- platform/android/src/style/android_conversion.hpp
The `within` expression need its parameter be an Object(map in android) and  then convert it to a Geojon object.
`toGeoJSON` method in `android_conversion.hpp` can't handle Object before and it seems not easy to convert an Object to string and then convert the string to GeoJSON object. So I put the whole json body of Polygon into the Object with key `json`. Maybe this's not a good idea, it will be nice if a better solution could be brought up。
Related pr in android sdk: https://github.com/mapbox/mapbox-gl-native-android/pull/198
> [android] Update toGeoJSON in android_conversion.hpp

- CHANGELOG.md
- platform/android/src/style/layers/fill_layer.cpp
- platform/android/src/style/layers/fill_layer.hpp
- platform/android/src/style/layers/layer.cpp.ejs
- platform/android/src/style/layers/line_layer.cpp
- platform/android/src/style/layers/line_layer.hpp
This PR add jni binding for line-sort-key and fill-sort-key that was add into core sdk in https://github.com/mapbox/mapbox-gl-native/pull/15839
The related android pr: https://github.com/mapbox/mapbox-gl-native-android/pull/209
> [android] Add jni binding for line-sort-key and fill-sort-key

- platform/default/src/mbgl/i18n/number_format.cpp
- platform/linux/linux.cmake
This has been causing too many build problems and it is a major source of complains because of different ICU interfaces.
> [default] Build a no-op number formatter for old ICUs

- CHANGELOG.md
- include/mbgl/style/expression/within.hpp
- src/mbgl/style/expression/within.cpp
- src/mbgl/util/geometry_within.cpp
- test/style/property_expression.test.cpp
- Fix error within decision when point is on Polygon line
- This patch will allow different geojson variants to be used as arguments of within expression, like 
```
{
"type": "Feature",
"geometry": {
"type": "Point",
"coordinates": [
-199.68749999999997,
33.137551192346145
]
}
}
```
```
{
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": {},
"geometry": {
"type": "Point",
"coordinates": [
-34.80468749999999,
32.24997445586331
]
}
}
]
}
```
```
{
"type": "Point",
"coordinates": [
-199.68749999999997,
33.137551192346145
]
}
```
> [core] Fix within expression

- circle.yml
- metrics/macos-xcode11-debug-coverage-nightly-style.json
Collect coverage from development builds and add a nightly build to collect metrics.
This gives us coverage for [platform/darwin](https://codecov.io/gh/mapbox/mapbox-gl-native/compare/dc510e44c085e87233b628a995b6957ad9c0ab9b...fb2c7f58dbfff05ab25472f7730e883e96d05d94/tree/platform).
> [build] Collect code coverage from macOS builds

- CHANGELOG.md
- metrics/android-render-test-runner/render-tests/tile-mode/streets-v11/metrics.json
- metrics/ignores/platform-all.json
- metrics/ios-render-test-runner/render-tests/tile-mode/streets-v11/metrics.json
- metrics/linux-clang8-release/render-tests/tile-mode/streets-v11/metrics.json
- metrics/linux-gcc8-release/render-tests/tile-mode/streets-v11/metrics.json
- src/mbgl/text/collision_index.cpp
- src/mbgl/text/collision_index.hpp
- src/mbgl/text/placement.cpp
Tile mode placement algorithm now checks if bounding boxes for both label text and icon are intersecting the edges of the tiles.
Before, it checked only text bounding boxes and thus label icons might have got cut off.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/200
> [core] [tile mode] placement algorithm must consider icons bounding boxes

- CMakeLists.txt
Users will add more dependencies and the script will break the build.
> [build] Do not do license check on core only builds

- CMakeLists.txt
- platform/android/android.cmake
- vendor/curl.cmake
The buildsystem will look for an extra path to include if available. This will allow to extend GL Native.
> [build] Minor build changes to enable extra modules

- platform/ios/ios.cmake
Disabled ccache on iOS, partially rolling back mapbox/mapbox-gl-native@7a9f8027ac1aa93c5e073d4fe138414059125fa8 from mapbox/mapbox-gl-native#16158, due to the iOS map SDK build failure reported in https://github.com/mapbox/mapbox-gl-native-ios/pull/199#issuecomment-596021296.
/cc @mapbox/gl-native @mapbox/maps-ios
> Disable ccache on iOS

- CHANGELOG.md
- platform/ios/ios.cmake
Cherry-picked #16289 into the 2020.02-release-vanillashake branch for a v1.3.1+ios release to unblock iOS map SDK v5.8.0-alpha.1. This commit will be tagged as maps-v1.3.1+ios, using a semver convention to indicate that it’s binary- and source-equivalent to v1.3.1 but is built differently.
/ref mapbox/mapbox-gl-native-ios#199
/cc @mapbox/gl-native @mapbox/maps-ios
> v1.3.1+ios

- CHANGELOG.md
- src/mbgl/text/placement.cpp
The tests were added at https://github.com/mapbox/mapbox-gl-js/pull/9397
Fixes: https://github.com/mapbox/mapbox-gl-native/issues/16291
> [core][tile mode] Fix assertion at `line-center` placement handling

- include/mbgl/util/run_loop.hpp
- test/util/run_loop.test.cpp
Platform integration callback for platforms that do not have full run loop integration or don't want to block at the Mapbox GL Native loop. It will be called from any thread and is up to the platform to, after receiving the callback, call RunLoop::runOnce() from the same thread as the Map object lives.
> [core] Add a callback for platform RunLoop integration

- metrics/android-render-test-runner/render-tests/filter/in/metrics.json
- metrics/ios-render-test-runner/render-tests/filter/in/metrics.json
- metrics/linux-clang8-release/render-tests/filter/in/metrics.json
- metrics/linux-gcc8-release/render-tests/filter/in/metrics.json
- src/mbgl/style/conversion/filter.cpp
Resolves #16262 
`mbgl::style::conversion::isExpression()` always returns false for expression `in`, this PR fix this issue.
The test in added in android test app in this pr: https://github.com/mapbox/mapbox-gl-native-android/pull/218
I'm not sure where should add test cases for this change, @alexshalamov any suggestions for it?
> [core] Fix using `in` expression with `filter`

- src/mbgl/text/placement.cpp
A mistype from https://github.com/mapbox/mapbox-gl-native/commit/05657e9573cdb01242a4e8365817be3f8bb62618
> [core] Fix crash at Placement::getSymbolPlacement()

- circle.yml
- scripts/ci/Dockerfile
Allow building with OpenGL ES 2.0 headers on Linux.
> [build] Bump docker

- platform/android/src/snapshotter/map_snapshotter.cpp
In snapshotter, it will call `snapshotter->setStyleJSON` for both style json mode and url mode.
This pr fix this issue.
> Fix wrong method call in  map_snapshotter.cpp

- src/mbgl/style/conversion/source.cpp
While reviewing the code in `src/mbgl/style/conversion/source.cpp ` I noticed an used variable. 
Perhaps gl-native should be being built with `-Wunused-variable`?
In the meantime here is a fix for the variable that was unused, which may help efficiency slightly by reducing the # of times the optional is accessed and by avoiding taking a copy of the string.
> Cleanup source conversion code

- include/mbgl/style/expression/within.hpp
- metrics/binary-size/android-x86/metrics.json
- src/mbgl/style/expression/within.cpp
- src/mbgl/util/geometry_within.cpp
- src/mbgl/util/geometry_within.hpp
- test/style/property_expression.test.cpp
Fix: https://github.com/mapbox/mapbox-gl-native/issues/16301
> [core] Use TileCoordinates instead of LngLats for `within` calculation

- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- test/map/transform.test.cpp
This change adds a latLngToScreenCoordinate overload, to retrieve
the projected vec4 in additional to the ScreenCoordinate object,
that is useful to detect whether the projected latLng is in front
or behind the camera.
The change also adds an additional, optional argument to getProjMatrix,
to retrieve a projection matrix centered around 0,0, instead of around
the current map center. This is necessary to minimize numerical error
in floating point math when projecting float coordinates with a float
matrix4 over a large domain.
> Add additional transformState getters

- CMakeLists.txt
- LICENSE.mbgl-core.md
- bin/CMakeLists.txt
- bin/cache.cpp
- expression-test/CMakeLists.txt
- include/mbgl/actor/mailbox.hpp
- include/mbgl/actor/scheduler.hpp
- include/mbgl/platform/settings.hpp
- include/mbgl/storage/file_source.hpp
- include/mbgl/style/conversion_impl.hpp
- include/mbgl/style/layer.hpp
- include/mbgl/style/source.hpp
- include/mbgl/style/transition_options.hpp
- include/mbgl/util/feature.hpp
- platform/android/android.cmake
- src/mbgl/annotation/annotation_manager.hpp
- src/mbgl/renderer/tile_parameters.hpp
- src/mbgl/renderer/update_parameters.hpp
- vendor/mapbox-base.cmake
Update mapbox-base to tag [v1.2.0](https://github.com/mapbox/mapbox-base/releases/tag/v1.2.0)
Fixes: https://github.com/mapbox/mapbox-gl-native-team/issues/233
> Bump mapbox-base to v1.2.0

- test/CMakeLists.txt
- vendor/cpp-httplib.cmake
This way it will not get warnings by linters and -Werror.
> [test] Include cpp-httplib as a system library

- platform/android/src/text/local_glyph_rasterizer.cpp
Refs downstream https://github.com/mapbox/mapbox-gl-native-android/pull/289 and https://github.com/mapbox/mapbox-gl-native-android/issues/31#issuecomment-590023046
> Use RGB values for local glyph generation

- CHANGELOG.md
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/renderer/render_orchestrator.cpp
- src/mbgl/renderer/render_orchestrator.hpp
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
Place tile intersecting labels first, across all the layers.  Thus, we reduce the amount of label cut-offs in Tile mode.
Before, labels were arranged within one symbol layer (one bucket), which was not enough for several symbol layers being placed at the same time.
Partial fix for https://github.com/mapbox/mapbox-gl-native-team/issues/223
> [core][tile mode] Reduce cut-off labels

- include/mbgl/storage/database_file_source.hpp
- platform/default/src/mbgl/storage/database_file_source.cpp
It is used as const and also fixes a build issue on iOS:
```
Non-const lvalue reference to type ‘mbgl::OfflineRegion’ cannot bind
to a temporary of type ‘typename remove_reference<OfflineRegion &>::type’
(aka ‘mbgl::OfflineRegion’)
```
> [core] Use const& for the OfflineRegion object

- platform/darwin/include/mbgl/interface/native_apple_interface.h
- platform/darwin/src/http_file_source.mm
- platform/darwin/src/native_apple_interface.m
This PR adds a `sessionForNetworkManager:` optional method to `MGLNativeNetworkManager`; this enables a mechanism for the platform SDK (and the app) to provide an `NSURLSession`.
Tests are being added to the iOS SDK.
Note that `native_apple_interface.h` needs better documentation - currently `MGLNativeNetworkManager` and `MGLNativeNetworkDelegate` should be considered undocumented.
cc @mapbox/maps-ios
> Add NSURLSession delegation to http_file_source.mm

- CHANGELOG.md
- src/mbgl/style/expression/within.cpp
- src/mbgl/util/geometry_within.cpp
- test/style/property_expression.test.cpp
Fix: https://github.com/mapbox/mapbox-gl-native/issues/16326
Parallel fix in gl-js: https://github.com/mapbox/mapbox-gl-js/pull/9440
> Fix `within` expression issue with geometry crossing the 180th Meridian

- .gitmodules
- test/android/app/build.gradle
- vendor/curl.cmake
Remove submodule vendor/curl-android-ios that was increasing the repository size significantly. Add new mapbox-gl-native-curl submodule which is much smaller in size and contains pre-built curl/openssl libraries built with the cmake included in this PR.
The cmakefile has the option to use prebuilt libraries (default), or build them from sources.
Fixes: mapbox/mapbox-gl-native-team#231
> [android] Use prebuilt curl and openssl libraries

- circle.yml
- platform/ios/ios.cmake
Now ccache can be optionally enabled. Enable it for CI builds.
By default it is disabled due to issues in some environments.
> [build] Enable ccache for iOS CI builds

- CHANGELOG.md
- src/mbgl/gl/context.cpp
A resource leak assertion in `gl::Context::~Context()` is evaluating false in scenarios where graphics context has been marked as lost. In these cases the underlying system handles resource cleanup and the assertion should not be checked.
This change fixes the issue https://github.com/mapbox/mapbox-gl-native-android/issues/300
> Fix assert in gfx resources cleanup

- src/mbgl/style/layers/background_layer.cpp
- src/mbgl/style/layers/circle_layer.cpp
- src/mbgl/style/layers/fill_extrusion_layer.cpp
- src/mbgl/style/layers/fill_layer.cpp
- src/mbgl/style/layers/heatmap_layer.cpp
- src/mbgl/style/layers/hillshade_layer.cpp
- src/mbgl/style/layers/layer.cpp.ejs
- src/mbgl/style/layers/line_layer.cpp
- src/mbgl/style/layers/raster_layer.cpp
- src/mbgl/style/layers/symbol_layer.cpp
The code should be human readable but it is more important if the code in the generator itself is easier to understand.
> [build] Disable clang-format for generated code

- CHANGELOG.md
- include/mbgl/util/logging.hpp
- src/mbgl/util/logging.cpp
- test/src/mbgl/test/fixture_log_observer.cpp
Fixes: mapbox/mapbox-gl-native-team/issues/224
> Move logging off the main thread

- .clang-tidy
It is warning about protected members which are not a big deal.
> [build] Remove misc-non-private-member-variables-in-classes check

- CHANGELOG.md
- src/mbgl/renderer/buckets/hillshade_bucket.cpp
Fixes: https://github.com/mapbox/mapbox-gl-native-ios/issues/240
Approach copied from RasterBucket::upload - they both use SharedBucketTileRenderData.
I don't have render test for this: it is a bit tricky since neighboring DEM tiles should not be available in the same time (otherwise this cannot be reproduced).
When dem tiles are loaded, border in neighboring tiles is updated, too leading to bucket re-upload. if std::move moved indices / vertices previously, they are empty and we get crash.
Re-upload requires that only DEM texture is re-uploaded, not the quad vertices and indices.
Verified running macosapp.
> Hillshade bucket fix for mapbox-gl-native-ios #240

- circle.yml
Now that we have clang-tidy with more checks enable,
make sure the code is tidy before we can move forward
with the pipeline.
Also cascade macOS bots, which are way slower after
basic compilation is done on Linux.
> [build] Cascade some bots so we trigger less jobs

- CHANGELOG.md
- include/mbgl/style/source.hpp
- platform/android/src/style/sources/source.cpp
- platform/android/src/style/sources/source.hpp
- src/mbgl/algorithm/update_renderables.hpp
- src/mbgl/annotation/render_annotation_source.cpp
- src/mbgl/renderer/sources/render_custom_geometry_source.cpp
- src/mbgl/renderer/sources/render_geojson_source.cpp
- src/mbgl/renderer/sources/render_raster_dem_source.cpp
- src/mbgl/renderer/sources/render_raster_source.cpp
- src/mbgl/renderer/sources/render_vector_source.cpp
- src/mbgl/renderer/tile_pyramid.cpp
- src/mbgl/renderer/tile_pyramid.hpp
- src/mbgl/style/source.cpp
- src/mbgl/style/source_impl.cpp
- src/mbgl/style/source_impl.hpp
- test/algorithm/update_renderables.test.cpp
- test/style/source.test.cpp
The new property sets a limit for how much parent tile can be overscaled.
When a set of tiles for a current zoom level is being rendered and some of the ideal tiles that cover the screen are not yet loaded, parent tile could be used instead. This might introduce unwanted rendering side-effects, especially for raster tiles that are overscaled multiple times.
/cc @mapbox/maps-android @mapbox/maps-ios @mapbox/core-sdk
/cc @asheemmamoowala
> Add source property to limit parent's tile overscale factor

- CHANGELOG.md
- include/mbgl/renderer/renderer.hpp
- src/mbgl/renderer/render_orchestrator.cpp
- src/mbgl/renderer/render_orchestrator.hpp
- src/mbgl/renderer/renderer.cpp
- src/mbgl/text/collision_index.cpp
- src/mbgl/text/collision_index.hpp
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
- test/map/map.test.cpp
The following methods are added to the `Renderer` class in implemented in the Tile map mode:
- `collectPlacedSymbolData()`
enables or disables collecting of the placed symbols data
- `getPlacedSymbolsData()`
if collecting of the placed symbols data is enabled, returns the
reference to the `PlacedSymbolData` vector holding the collected data.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/232
> [core][tile mode] Introduce API to collect placed symbols data

- scripts/ci/Dockerfile
It could be made even smaller by splitting Android and Linux builds, but so far CircleCI is handling it fine. The idea is to clear the cache per docker layer instead of clearing it in the end, otherwise clearing the cache has no effect.
> [build] Make the docker image smaller

- src/mbgl/renderer/buckets/hillshade_bucket.cpp
Cherry-pick #16362 `Hillshade bucket fix for mapbox-gl-native-ios #240` to release-v1.5.0
> [cp] Hillshade bucket fix for mapbox-gl-native-ios #240 to 1.5.0

- CMakeLists.txt
- src/mbgl/algorithm/update_renderables.hpp
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/renderer/layers/render_background_layer.cpp
- src/mbgl/renderer/tile_pyramid.cpp
- src/mbgl/util/bounding_volumes.cpp
- src/mbgl/util/bounding_volumes.hpp
- src/mbgl/util/mat3.hpp
- src/mbgl/util/tile_cover.cpp
- src/mbgl/util/tile_cover.hpp
- test/CMakeLists.txt
- test/algorithm/update_renderables.test.cpp
- test/src/mbgl/test/mock.hpp
- test/util/bounding_volumes.test.cpp
- test/util/tile_cover.test.cpp
This pull request implements a more versatile logic for finding visible tiles on the screen. Intersection tests have been extended to 3D space by using bounding volumes for tiles and camera instead of projecting everything to zero elevation plane. Tile pyramid is traversed depth-first while preserving distances to tiles allowing an easy support for a level-of-detail. Even though the distance based lod is supported by this implementation, **this PR has no visible effect for the user**. Level of detail logic is deactive when pitch is <= 60 degrees.
The native implementation follows the javascript one (https://github.com/mapbox/mapbox-gl-js/pull/8975) with few exceptions:
1. Certain edge cases (false positives) were found in the tests. These cases (<1%) are culled by more precise …
> Refactor tile coverage to support level of detail

- test/style/expression/expression.test.cpp
- test/style/style_parser.test.cpp
Reason: gmock supports better syntax for defining mock methods.
> [build] Bump googletest to 1.10.0

- CHANGELOG.md
- src/mbgl/text/placement.cpp
The `symbolIntersectsTileEdges()` util in `mbgl::TilePlacement` now considers icon shift for the variable symbols with enabled `icon-text-fit` setting, thus providing more accurate results.
Render test: https://github.com/mapbox/mapbox-gl-js/pull/9513
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/213
> [core][tile mode] Fix variable placement + icon-text-fit

- platform/default/src/mbgl/map/map_snapshotter.cpp
Snapshotter will not fire onStyleImageMissing when image is missing because map_snapshotter not implement this function.
This pr add the implementation to let the out observer receive this event.
Test pr in android repo: https://github.com/mapbox/mapbox-gl-native-android/pull/317
> [android] Fix onStyleImageMissing callback in Snapshotter not fired 

- CHANGELOG.md
- src/mbgl/style/style_impl.cpp
This fixes an issues where calling `removeImage` would crash if the image was not present and the original images list was not empty.
> When removing an image use the correct list ptr for presence verification

- .gitmodules
This PR removes modules that are not used anymore from .gitmodules. Some automatic build systems, such as OBS, fail to fetch sources when the modules are declared in .gitmodules, but are not used in practice.
As far as I can see, these modules are not specified in the source tree.
> [build] Drop unused modules from .gitmodules

- metrics/binary-size/macos-xcode11/metrics.json
- test/api/api_misuse.test.cpp
Use single threaded fixture log to avoid unit test flakiness.
Fixes: https://github.com/mapbox/mapbox-gl-native-team/issues/336
> Use single threaded fixture log

- metrics/ignores/platform-ios.json
Remove the ignore after https://github.com/mapbox/mapbox-gl-native/issues/16401 is done.
> [build] Ignore location indicator on iOS until we port to ::gfx

- CHANGELOG.md
- include/mbgl/style/layer.hpp
- src/mbgl/style/layer.cpp
- test/style/conversion/layer.test.cpp
- test/style/style_layer.test.cpp
- Add setter for 'source' property
- Test generic setters via setProperty method
> Add generic setter for Layer's 'source' property

- src/mbgl/layout/symbol_layout.cpp
The current implementation of `SymbolLayout::addFeature` can segfault on an invalid LineString (containing a `Line` with no members). This skips adding invalid geometries (i.e., LineStrings) when encountered.
This is a trivial bug to verify based on reading the code. I'm happy to add a test case, if someone can point me to the right place.
> Fix segfault resulting from an invalid geometry.

- metrics/ignores/platform-ios.json
After that, it will be more portable.
> [metrics] Ignore location indicator on iOS until we move to gfx::

- .clang-tidy
- src/mbgl/style/expression/expression.cpp
- src/mbgl/util/io.cpp
Sadly they will make clang-tidy a lot slower, but they are useful to catch hard to find bugs.
> [build] Enable clang-analyzer checks

- src/mbgl/gl/custom_layer.cpp
This will make the case of an empty name in the LayerTypeInfo effectively an error, that can be logged.
> Add name "custom" to Custom Layer's typeInfoCustom

- platform/default/src/mbgl/storage/asset_file_source.cpp
- platform/default/src/mbgl/storage/database_file_source.cpp
- platform/default/src/mbgl/storage/local_file_source.cpp
- platform/default/src/mbgl/storage/main_resource_loader.cpp
- platform/default/src/mbgl/storage/online_file_source.cpp
- src/mbgl/gl/program.hpp
- src/mbgl/gl/renderer_backend.cpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/style/conversion/layer.cpp
- test/src/mbgl/test/stub_file_source.cpp
Fix warning-as-erros from GCC 9 related to either redundant or non-optimal moves.
> [core] Fix -Werror={pessimizing,redundant}-move from GCC 9

- include/mbgl/platform/time.hpp
- include/mbgl/util/chrono.hpp
- platform/android/android.cmake
- platform/default/src/mbgl/platform/time.cpp
- platform/ios/ios.cmake
- platform/linux/linux.cmake
- platform/macos/macos.cmake
- platform/qt/qt.cmake
- src/mbgl/util/http_header.cpp
Some platforms might require special permissions or custom APIs to access the current time of the day.
> [core] Add platform abstractions for utils::now()

- CHANGELOG.md
- include/mbgl/storage/resource.hpp
- include/mbgl/style/source.hpp
- platform/default/src/mbgl/storage/online_file_source.cpp
- src/mbgl/annotation/render_annotation_source.cpp
- src/mbgl/renderer/sources/render_custom_geometry_source.cpp
- src/mbgl/renderer/sources/render_geojson_source.cpp
- src/mbgl/renderer/sources/render_raster_dem_source.cpp
- src/mbgl/renderer/sources/render_raster_source.cpp
- src/mbgl/renderer/sources/render_vector_source.cpp
- src/mbgl/renderer/tile_pyramid.cpp
- src/mbgl/renderer/tile_pyramid.hpp
- src/mbgl/style/custom_tile_loader.hpp
- src/mbgl/style/source.cpp
- src/mbgl/style/source_impl.hpp
- src/mbgl/tile/raster_dem_tile.cpp
- src/mbgl/tile/raster_dem_tile.hpp
- src/mbgl/tile/raster_tile.cpp
- src/mbgl/tile/raster_tile.hpp
- src/mbgl/tile/tile.hpp
- src/mbgl/tile/tile_loader.hpp
- src/mbgl/tile/tile_loader_impl.hpp
- src/mbgl/tile/vector_tile.cpp
- src/mbgl/tile/vector_tile.hpp
- src/mbgl/util/http_timeout.cpp
- test/map/map.test.cpp
- test/storage/online_file_source.test.cpp
- test/style/source.test.cpp
The `Source::setMinimumTileUpdateInterval(Duration)` method sets the minimum tile update interval, which is used to throttle the tile update network requests.
The corresponding `Source::getMinimumTileUpdateInterval()`  getter is added too.
Default minimum tile update interval value is `Duration::zero()`.
Tag https://github.com/mapbox/mapbox-gl-native-team/issues/335
> [core] Introduce Source::setMinimumTileUpdateInterval API

- circle.yml
- scripts/check_benchmark_results.sh
- Increase the benchmark runner timeout to 30 minutes on Android and iOS
- Increase benchmark threshold to 15%
> Android and iOS benchmark changes

- platform/ios/ccache.cmake
iOS ccache wrapper scripts should be in the top level of the CMake build tree.
> [build] Fix the output path of the iOS ccache scripts

- CHANGELOG.md
- include/mbgl/storage/resource.hpp
- include/mbgl/style/source.hpp
- platform/default/src/mbgl/storage/database_file_source.cpp
- src/mbgl/renderer/tile_pyramid.cpp
- src/mbgl/style/source.cpp
- src/mbgl/style/source_impl.hpp
- src/mbgl/tile/raster_dem_tile.cpp
- src/mbgl/tile/raster_dem_tile.hpp
- src/mbgl/tile/raster_tile.cpp
- src/mbgl/tile/raster_tile.hpp
- src/mbgl/tile/tile.hpp
- src/mbgl/tile/tile_loader.hpp
- src/mbgl/tile/tile_loader_impl.hpp
- src/mbgl/tile/vector_tile.cpp
- src/mbgl/tile/vector_tile.hpp
- test/map/map.test.cpp
- test/storage/database_file_source.test.cpp
- test/storage/main_resource_loader.test.cpp
- test/storage/online_file_source.test.cpp
- test/style/source.test.cpp
The tile data from the volatile sources are not stored in local storage, i.e. they are not cached.
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/335
> [core] Add style::Source::setVolatile()/isVolatile() API

- src/mbgl/util/bounding_volumes.cpp
- src/mbgl/util/mat3.hpp
Move common vec3 math operations defined in `bounding_volumes.cpp` to `mat3.hpp` for shared use. These functions are required in the 3D camera development https://github.com/mapbox/mapbox-gl-native/pull/16419.
> Add common vector math operations to mat3.hpp

- CHANGELOG.md
- platform/darwin/src/http_file_source.mm
Happily accept the data in an NSURLResponse that isn’t an NSHTTPURLResponse as long as the file is a local file URL. I left the existing else statement in place just in case, but we could probably remove that error to fix other non-HTTP protocols like smb:.
Fixes #16427.
> Fix error receiving local file URL response

- platform/qt/src/http_request.cpp
Users might want to add image sources from a Qt application using base64 encoded image using the `data` URL scheme. This is supported by Qt but HTTP status code is not present. This adds a special case to the `HTTPRequest::handleNetworkReply`.
I could not think of any other scheme that could be reasonably used here. HTTP and `file://` seem to report the status code properly.
Will also provide MR to master when this one is accepted. Let me know if this should be done to master first.
> [qt] Ignore status code with 'data' scheme URLs

- CHANGELOG.md
- metrics/binary-size/macos-xcode11/metrics.json
- src/mbgl/text/placement.cpp
- src/mbgl/text/placement.hpp
This PR fixes label priority issues in the Tile mode. It does the following:
- strictly arranges all the intersecting labels accordingly to the style-defined priorities
- fixes placement order of the variable labels.
_Before this change, all variable labels that could potentially
intersect tile borders were placed first, breaking the style
label placement priority order. Now, all the variable labels, which
do not actually intersect the tile borders, are placed accordingly 
to the style-defined priorities_
Fixes https://github.com/mapbox/mapbox-gl-native-team/issues/338
> [core][tile mode] Labels priority fixes

- platform/darwin/src/http_file_source.mm
This PR removes the check for whether `accountType` is equal to `0`. 
@julianrex
> [darwin] Remove `accountType` check

- CHANGELOG.md
- CMakeLists.txt
- include/mbgl/map/camera.hpp
- include/mbgl/map/map.hpp
- include/mbgl/util/geo.hpp
- include/mbgl/util/vectors.hpp
- platform/glfw/glfw_view.cpp
- platform/glfw/glfw_view.hpp
- src/mbgl/map/map.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/util/camera.cpp
- src/mbgl/util/camera.hpp
- src/mbgl/util/mat3.hpp
- src/mbgl/util/mat4.hpp
- src/mbgl/util/quaternion.cpp
- src/mbgl/util/quaternion.hpp
- test/CMakeLists.txt
- test/map/transform.test.cpp
- test/util/camera.test.cpp
This pull request is the first iteration of a "real" 3D camera API that gives the user more precise controls of the camera entity itself by exposing direct properties like position and orientation. The difference to the current viewport API is that instead of applying transformations to the map the user has (a limited) access to the underlying camera object that is orbiting around the map center point at a certain distance. Implementation follows standard conventions and is a typical way of controlling the camera in any 3D engine/software.
Both interfaces, the old and the new, are interchangeable and fully compatible with each other: changes made to the transformation via one API is immediately reflected to the other one.
- Same constraints apply to both APIs. Pitch is limited to 60 …
> Add 3D camera API

- src/mbgl/renderer/layers/render_raster_layer.cpp
When panning at high zoom levels with the raster map, the map will jitter.
This pr fixes this issue.
> [core] Fix raster map jittering during panning

- platform/qt/src/http_file_source.cpp
Since 5.9 RedirectPolicyAttribute is preferred, and from 6.0 the
behavior of NoLessSafeRedirectPolicy is the default.
So updated the ifdefery to match this.
> Update Qt redirection handling
