mapbox/mapbox-gl-native

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/CoordinateBounds.java

[android] #2880 - CoordinateBounds correction equals method

---

src/mbgl/annotation/annotation_manager.cpp
src/mbgl/annotation/annotation_manager.hpp
src/mbgl/annotation/annotation_tile.cpp
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/map/geometry_tile.hpp
src/mbgl/map/raster_tile_data.cpp
src/mbgl/map/source.cpp
src/mbgl/map/source.hpp
src/mbgl/map/tile_worker.cpp
src/mbgl/map/tile_worker.hpp
src/mbgl/map/vector_tile_data.cpp
src/mbgl/map/vector_tile_data.hpp
src/mbgl/util/worker.cpp
src/mbgl/util/worker.hpp

Monitor annotation tiles

---

platform/ios/MGLMapView.mm

Deferring the UIActionSheet’s initialization eliminates some console spew about potential undefined behavior.
Fixes #2475.

Create UIActionSheet on demand

---

src/mbgl/renderer/painter_symbol.cpp

Refs https://github.com/mapbox/mapbox-gl-native/pull/942, fixes https://github.com/mapbox/mapbox-gl-native/issues/2264.
Ignores animation and fade duration when rendering SDFs in `MapMode::Still`.
/cc @bsudekum @brunoabinader

patch Painter::renderSDF to fix missing labels

---

scripts/ios/package.sh

`make ipackage` now performs a Bitcode-enabled archive build for devices, making it possible to archive a Bitcode-enabled application that links against the Mapbox iOS SDK.
@incanus, can you verify that the resulting static library contains all the expected symbols? I did notice some additional missing symbol warnings in the `CreateUniversalBinary` step, such as the one below, but I think those are the same things we try to suppress when calling `libtool` with the `-no_warning_for_no_symbols` flag:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/mxn/hub/mapbox-gl-native/build/mbgl.build/Release-iphonesimulator/core.build/Objects-normal/x86_64/libmbgl-core.a(camera.o) has no symbols
```
/ref #2332
/cc …

Force Bitcode in make ipackage

---

platform/ios/MGLAccountManager.m
platform/ios/MGLMapView.mm

Just in case browser weirdness or a tendency to triple-click-select is causing some cases of #2012.
Ordinarily we’d want this kind of logic down in mbgl, but I think it belongs up here too because:
* The access token is stored as an instance variable of MGLAccountManager, and I think that ivar should have the correct value too.
* The inspectable style URL string gets transformed into an NSURL in `-[MGLMapView setStyleURL__:]`. NSURL demands RFC 1738/2732 well-formedness, so if the string has leading whitespace, the transformation will fail and you’ll wind up w/ no URL (and the default style).

Strip whitespace and newlines from access token and style URL

---

platform/default/sqlite_cache.cpp

When a database file gets corrupted, or compression fails, we're currently throwing an error, which doesn't get caught.

Catch compression errors

---

src/mbgl/renderer/gl_config.cpp
src/mbgl/renderer/gl_config.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_circle.cpp
src/mbgl/renderer/painter_clipping.cpp
src/mbgl/renderer/painter_debug.cpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/renderer/painter_raster.cpp
src/mbgl/renderer/painter_symbol.cpp

There's still some GL state that we're managing directly in the painter object; in particular the program, line width and viewport. We should move those to the GLConfig object.

Move remaining GL state into GLConfig object

---

test/ios/MapViewTests.m

This PR fixes the pretty consistent test failures in #2920 by introducing additional waits. We now wait a bit in `-beforeEach` (because style and tile loading contributes to sluggishness while rotating), then wait for the map to rotate, then wait for the compass to fade using view-based animation.
The wait in `-beforeEach` is hard-coded at 500 ms, which is good enough on my machine, but it remains to be seen whether it’s good enough for the CI machines. Ideally I would’ve waited for a `-mapViewDidFinishRenderingMap:fullyRendered:` callback, but it incorrectly fires after style loading but before tile loading (#2775).
/cc @friedbunny @incanus

Wait for style loading, then rotation, then compass fading

---

platform/ios/MGLMapView.mm

Fixes #2634.
@incanus, I left the dimming on if it looks like the delegate is going to respond to the tap (thereby treating it like a button). If you disagree, I can turn off the dimming in that case too.

Disable callout view dimming when tap is a no-op

---

package.json
platform/node/CHANGELOG.md
platform/node/README.md
platform/node/src/node_map.cpp

Fixes #2846
For consistency with GeoJSON and mapbox-gl-js

swap array order to [lng, lat] for render option center

---

platform/default/thread.cpp

Looks like Linux has the `SCHED_IDLE` define in `linux/sched.h`, so we need to include that when building for Linux prior to including `sched.h`.

Include <linux/sched.h> on Linux

---

Makefile
package.json
platform/node/src/node_file_source.hpp
platform/node/src/node_log.hpp
platform/node/src/node_map.hpp
platform/node/src/node_mapbox_gl_native.cpp
platform/node/src/node_request.hpp

Fixes #2938
Adds `node-gyp` to dev-dependencies to support `make xnode` on Node v0.10.x
Ignores `-Wnested-anon-types` around `v8.h` includes.

Fix 'make xnode' to configure HOST_SLUG.gypi

---

linux/main.cpp
macosx/main.mm
platform/default/image.cpp
platform/default/sqlite_cache.cpp
src/mbgl/util/stopwatch.cpp

There are some usages of `Log::*` that don't pass a literal character string as the first argument, but we're feeding it into printf.

Fix all Log::* usages

---

src/mbgl/renderer/gl_config.hpp
src/mbgl/renderer/painter.cpp

We should not depend on a previous GL state, but set all required GL values instead. Flagging a GL value as dirty means that the next time it is set (via `operator=`) we'll call the respective GL setter commands independent whether the cached value is the same.
/cc @kkaefer @jfirebaugh @tmpsantos @adam-mapbox

[core] Replace GL save/restore values mechanism with dirty flag

---

src/mbgl/map/map_context.cpp

I could easily reproduce this on 179917ccb670d62125754a6b519aa3c89f16d25f by launching the Linux app and pressing `s` (change style) fast. Eventually it crashes. This has probably something to do with trying to render after cleaning up the style.
/cc @kkaefer 
```
#0  0x00000000004aee94 in mbgl::Painter::render (this=0x7f23600033c0, style=..., state_=..., frame_=...)
at ../../src/mbgl/renderer/painter.cpp:158
158	                item.bucket->upload();
#1  0x0000000000462bb2 in mbgl::MapContext::renderSync (this=0x7f2369a18cc0, state=..., frame=...) at ../../src/mbgl/map/map_context.cpp:250
#2  0x000000000042871c in operator() (this=0x7f2360575438) at /usr/include/c++/4.9/functional:2439
#3  operator() (this=0x7f2360575430) at /usr/include/c++/4.9/future:1241
#4 …
```

Crash when changing styles too fast

---

src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter_circle.cpp
src/mbgl/renderer/painter_clipping.cpp
src/mbgl/renderer/painter_debug.cpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/renderer/painter_raster.cpp
src/mbgl/renderer/painter_symbol.cpp

While debugging shared GL context, we found out that some GL values were not being properly reset when needed (eg. when _depth_ or _stencil_ tests were enabled, or blend was enabled).
/cc @kkaefer

GL values should be reset upon need

---

src/mbgl/layer/background_layer.cpp
src/mbgl/layer/fill_layer.cpp
src/mbgl/layer/line_layer.cpp
src/mbgl/style/function.cpp
src/mbgl/style/function.hpp
src/mbgl/style/property_parsing.cpp
src/mbgl/style/property_parsing.hpp

We shouldn't overload transition duration to mean the duration of the cross-fade when moving between stops. If we want to allow styles to override the default 300ms fade duration, it should be a dedicated property like `raster-fade-duration`.
I don't think any styles use this functionality -- if they did, they were broken for `MapMode::Still` rendering.
:eyes: @kkaefer @ansis

[core] Remove the ability to change cross-fade durations via transition

---

CHANGELOG.md
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp

The final frame is self-destructing – it destroys the frame and finish functions – so technically we’re no longer `inTransition()`. Yet there still needs to be an update after that final frame.
Also, this PR removes a redundant IsChanging notification that was being sent from the final frame of the transition. It would’ve come after the finish function’s DidChange notification.
Fixes #2946.

Update after final frame of transition

---

gyp/platform-ios.gypi
platform/ios/MGLAccountManager.m
platform/ios/MGLCategoryLoader.h
platform/ios/MGLCategoryLoader.m
platform/ios/NSBundle+MGLAdditions.h
platform/ios/NSBundle+MGLAdditions.m
platform/ios/NSProcessInfo+MGLAdditions.h
platform/ios/NSProcessInfo+MGLAdditions.m
platform/ios/NSString+MGLAdditions.h
platform/ios/NSString+MGLAdditions.m

This should reduce our binary size as well as obviate the need for the `-ObjC` linker flag.

fixes #2966: remove -ObjC linker flag & bring in categories via other means

---

ios/Mapbox-iOS-SDK.podspec

This should be super simple, but let's CI it just to make sure it works everywhere.

fixes #2961: download payload over HTTPS

---

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Annotation.java

[android] Make Annotation.getId() suitable for public use.

---

CHANGELOG.md
platform/ios/MGLMapView.mm

Avoid piling up lots of deactivated constraints. Also avoid trying to deactivate constraints that have already been removed from the view hierarchy due to a change in view controllers.
Fixes #2020.
@incanus, would you mind testing on an iOS 7.x device, just in case? Thanks!

Remove constraints instead of deactivating them

---

ios/docs/install_docs.sh
scripts/ios/install.sh
scripts/ios/package.sh

This change removes a git command that requires a network connection from the ipackage target. It was used to ensure that CI has a tag to version the appledoc documentation with, so the same command has been added to install.sh, where a network connection is otherwise expected.
Along for the ride, I’ve also updated some references to the old build documentation.
Fixes #2320; fixes #2871.
/cc @adam-mapbox @incanus

Fetch tags on install, not ipackage

---

CHANGELOG.md
ios/Mapbox-iOS-SDK.podspec

Per https://github.com/mapbox/mapbox-gl-native/issues/1870#issuecomment-132417161.
ref CocoaPods/CocoaPods#3573

Replace deprecated podspec flag

---

CHANGELOG.md
platform/ios/MGLMapView.mm

Leave GLKView rendering on when app is inactive, to get nice smooth transitions between sizes when using multitasking on iPad (iOS 9).
Fixes #2158. Incorporates #2309.
/cc @bwhtmn @incanus

Improve transitions in iOS 9 multitasking

---

include/mbgl/map/map.hpp
src/mbgl/map/map.cpp

We should expose default fade duration to public Map API. This allows clients to e.g. disable label fade transitions by setting their duration to zero.
/cc @incanus @jfirebaugh @kkaefer @tmpsantos

Expose default fade duration

---

include/mbgl/map/map.hpp
include/mbgl/util/geo.hpp
include/mbgl/util/vec.hpp
platform/android/jni.cpp
platform/ios/MGLMapView.mm
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/storage/default_file_source.cpp

This PR fixes the following static analyzer warnings introduced by 5a24ac6 for #2994 and 4d5c633 for #2727:
```
/path/to/mapbox-gl-native/src/mbgl/storage/default_file_source.cpp
/path/to/mapbox-gl-native/src/mbgl/storage/default_file_source.cpp:328:29: The result of the '<<' expression is undefined
/path/to/mapbox-gl-native/src/mbgl/storage/default_file_source.cpp:328:29: The result of the '<<' expression is undefined
/path/to/mapbox-gl-native/src/mbgl/storage/default_file_source.cpp:333:25: The result of the '<<' expression is undefined
/path/to/mapbox-gl-native/src/mbgl/storage/default_file_source.cpp:333:25: The result of the '<<' expression is undefined
/path/to/mapbox-gl-native/src/mbgl/map/transform.cpp
/path/to/mapbox-gl-native/src/mbgl/map/transform.cpp:328:9: Value stored to …
```

Fix static analyzer warnings

---

platform/ios/MGLMapView.mm

Set the refresh interval to 60 frames per second, which performs well on a 64 GB iPhone 6. We can blacklist specific hardware models that fail to keep up as we come across them in testing, but I think this is a good starting point.
Fixes #3005.
/cc @adam-mapbox @incanus @friedbunny

Set refresh interval to 60fps

---

platform/ios/NSBundle+MGLAdditions.m

If you package the static library, the resource bundle, and the headers into a faux-framework `Mapbox.framework`, this is needed in order to actually locate the resource bundle, since frameworks are copied as a build phase into the app bundle, but `[NSBundle bundleWithClass:[MGLMapView class]]` returns that app bundle due to linking behavior.

provide resource bundle search for premade frameworks

---

Makefile
ios/framework/Info.plist
ios/framework/modulemap
ios/framework/umbrella
scripts/ios/framework.sh

The idea is to just leave this in the `Makefile` for now, but still only distribute static libraries directly (plus CocoaPods install), not framework bundles.

static framework target for iOS

---

include/mbgl/ios/MGLAccountManager.h
include/mbgl/ios/MGLAnnotation.h
include/mbgl/ios/MGLGeometry.h
include/mbgl/ios/MGLMapCamera.h
include/mbgl/ios/MGLMapView+IBAdditions.h
include/mbgl/ios/MGLMapView.h
include/mbgl/ios/MGLMultiPoint.h
include/mbgl/ios/MGLOverlay.h
include/mbgl/ios/MGLPointAnnotation.h
include/mbgl/ios/MGLPolygon.h
include/mbgl/ios/MGLPolyline.h
include/mbgl/ios/MGLShape.h
include/mbgl/ios/MGLStyle.h
include/mbgl/ios/MGLUserLocation.h
platform/ios/MGLMapboxEvents.h
platform/ios/MGLMultiPoint_Private.h
platform/ios/MGLUserLocation_Private.h
platform/ios/NSBundle+MGLAdditions.h
platform/ios/NSString+MGLAdditions.h

Due to https://github.com/mapbox/mapbox-gl-native/commit/0a8d9a3b6d686c1fce9dc48014d1b13fdd58cdb3, we recursively import `Mapbox.h` and we shouldn't do this. Instead, we should bring in any Apple Foundation imports directly, our own superclasses / category-extended classes if necessary, and forward-declare the rest. 
/cc @1ec5

more clearly indicate Foundation imports to avoid recursion

---

include/mbgl/map/map.hpp
include/mbgl/map/mode.hpp
include/mbgl/util/geo.hpp
platform/android/jni.cpp
platform/ios/MGLMapView.mm
platform/ios/MGLMultiPoint.mm
src/mbgl/annotation/annotation_manager.cpp
src/mbgl/map/map.cpp
src/mbgl/map/map_context.cpp
src/mbgl/map/map_context.hpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
test/ios/MapViewTests.m
test/miscellaneous/transform.cpp
test/style/resource_loading.cpp

Currently we constrain the map boundaries only in the vertical axis. We should have the option to constrain also in horizontal axis, which would disable the possibility to infinitely pan the map horizontally, but also fixes an issue where annotations start disappearing once we reach the map horizontal boundaries.
/cc @mapbox/gl @mapbox/mobile

Constrain map on both axis

---

CHANGELOG.md
include/mbgl/ios/MGLMapView.h

With #630 and #2627, the map loading notifications should be being sent from core MBGL, which means that the `mapViewWillStartLoadingMap:` & `mapViewDidFinishLoadingMap:` delegate methods that already exist in `MGLMapViewDelegate` should be ready for use.
/cc @incanus @1ec5

Test and document `willStartLoading` & `didFinishLoading` delegate methods

---

platform/ios/MGLMapView.mm

Any MGLMapView method that can programmatically move the map’s viewport, with or without animation, needs to explicitly send a didChange notification. Otherwise, mbgl will trigger notifications, but not necessarily in the right order. This includes the programmatic rotation that occurs due to tracked heading changes.
This PR also fixes a bug in which setting the direction programmatically would fail to boot the user out of course-tracking mode.
/ref #2948
/cc @friedbunny @incanus

Ensure proper delegate callbacks for resetNorth

---

src/mbgl/map/map_context.cpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp

Fixes #3037
cc @incanus -- I stuck this on the 3.0.0 milestone / branch. It should be fairly safe but I'd be fine with waiting too.

[core] Avoid calling AnnotationManager::updateStyle until the style is loaded

---

test/miscellaneous/token.cpp
test/test.gypi

Ported `replaceTokens()` tests [from GL JS](https://github.com/mapbox/mapbox-gl-js/blob/d37fc014635e1cc640c92f06b9993e1dd6b05899/test/js/util/token.test.js) in anticipation of a forthcoming PR implementing mapbox/mapbox-gl-style-spec#104.

replaceTokens() tests

---

include/mbgl/ios/MGLMapView.h

A hack atop the hack added in #2632. Pre-declare `styleURL__` with an attribute that prevents it from appearing in code completion suggestions, while leaving it available to Interface Builder, which is unable to parse attributes.
/cc @incanus @friedbunny

Discourage code usage of styleURL__ property

---

include/mbgl/ios/MGLMapView+IBAdditions.h
include/mbgl/ios/MGLMapView.h

Replaced #3088 with a better fix that relies on conditional compilation. It also happens to be semantically correct. The previous attempt produced these linker warnings:
```
ld: warning: instance method 'setStyleURL__:' in category from /Users/mxn/Library/Developer/Xcode/DerivedData/…/Build/Products/Debug-iphonesimulator/libmbgl-platform-ios.a(MGLMapView.o) overrides method from class in /Users/mxn/Library/Developer/Xcode/DerivedData/…/Build/Products/Debug-iphonesimulator/libmbgl-platform-ios.a(MGLMapView.o)
ld: warning: instance method 'styleURL__' in category from /Users/mxn/Library/Developer/Xcode/DerivedData/…/Build/Products/Debug-iphonesimulator/libmbgl-platform-ios.a(MGLMapView.o) overrides method from class in /Users/mxn/Library/Developer/Xcode/DerivedData/…/Build/Products/Debug-iph …
```

Fix linker warnings about overridden styleURL__

---

scripts/ios/framework.sh

This needs some more testing, but this shaves off ~20MB on the "stripped" static binary we're producing already with `make ipackage-strip`. We should make sure it doesn't bust anything, but also work on this and other ways to reduce our footprint, especially for folks who don't care about debugging symbols anyway and want to use our framework as if it were closed source. 
Refs https://github.com/mapbox/mapbox-gl-native/issues/898
Also, from @1ec5: 
> There’s a `SEPARATE_STRIP` build setting in Xcode that invokes `strip`.
> 
> It’s off by default.
> 
> Instead, `COPY_PHASE_STRIP` and `STRIP_INSTALLED_PRODUCT` default to on.
> 
> `STRIP_INSTALLED_PRODUCT` only strips the product when you build for archive, something that we should already be doing via `DEPLOYMENT_POSTPROCESSING`.
> 
> Are …

reduce framework binary size with more stripping

---

platform/default/image.cpp
platform/default/sqlite3.cpp
src/mbgl/util/compression.cpp
src/mbgl/util/uv.cpp

GCC5 and later complains about unused variables in the files altered by this PR. Selectively disabling the warning solves the issue and leaves the forcing function of the variables untouched.

Fix GCC5 complaining about -Wunused-variable.

---

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java

Fixes #3104
Also changed to zoom in on center of map when quickzooming, which is how Google Maps does it.

Don't double-tap zoom when quickzooming on Android

---

CHANGELOG.md
include/mbgl/ios/MGLMapView.h
include/mbgl/map/camera.hpp
platform/ios/MGLMapView.mm
src/mbgl/map/transform.cpp

Added transition frame and finish functions to `CameraOptions`. Added equivalent Objective-C blocks as completion handlers on the three main entry points to `easeTo()` in MGLMapView.
Fixes #1581. Depends on #3086.
/cc @incanus @friedbunny

Completion handlers for animated MGLMapView methods

---

android/MapboxGLAndroidSDKTestApp/src/main/res/values/developer-config.xml

developer-config.xml gets generated on build time with the token set for the env var MAPBOX_ACCESS_TOKEN. Because the file was checked to the git repo, it was not being regenerated and thus, crashing the test app accusing no token set.

[android] Remove autogenerated file from tree

---

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
docs/BUILD_IOS_OSX.md
docs/DEVELOP_ANDROID_LINUX.md
docs/DEVELOP_ANDROID_OSX.md
docs/DEVELOP_IOS_OSX.md
docs/DEVELOP_OSX.md
include/mbgl/ios/MGLMapView.h

Replaced https://www.mapbox.com/account/apps/ with https://www.mapbox.com/studio/account/tokens/. The old URL redirects to a Mapbox Studio page not specifically about access tokens.
/cc @friedbunny @danswick

Update links to access token manager

---

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java
android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java
android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowActivity.java
android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowAdapterActivity.java

Closes #3115 and #3121 
@zugaldia

3115 multiple infowindows + leave open while panning

---

src/mbgl/annotation/annotation_manager.cpp
src/mbgl/annotation/annotation_manager.hpp
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/map/map_data.hpp
src/mbgl/map/source.cpp
src/mbgl/map/source.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
src/mbgl/style/style_parser.cpp
src/mbgl/style/style_parser.hpp
src/mbgl/style/style_update_parameters.hpp
test/miscellaneous/style_parser.cpp

The introduction of `StyleCascadeParameters` and `StyleCalculationParameters` proved to be very useful refactorings. This does the same for the parameters to `Source::update`. It also addresses the comment [here](https://github.com/mapbox/mapbox-gl-native/commit/d55aa7929cb10d40a58b6b7a8ed73bddd4f0a407#commitcomment-14692834).
:eyes: @brunoabinader

[core] Introduce StyleUpdateParameters

---

include/mbgl/map/map.hpp
include/mbgl/platform/default/glfw_view.hpp
platform/default/glfw_view.cpp
src/mbgl/annotation/annotation_manager.cpp
src/mbgl/annotation/annotation_manager.hpp
src/mbgl/layer/symbol_layer.cpp
src/mbgl/layer/symbol_layer.hpp
src/mbgl/map/map.cpp
src/mbgl/map/map_context.cpp
src/mbgl/map/map_context.hpp
src/mbgl/map/map_data.hpp
src/mbgl/map/tile_worker.cpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/sprite/sprite_atlas.cpp
src/mbgl/sprite/sprite_atlas.hpp
src/mbgl/style/style.cpp
test/miscellaneous/map_context.cpp
test/sprite/sprite_atlas.cpp

@kkaefer @jfirebaugh @incanus 
Comments about thread safety, etc. welcome.

Separate annotation sprite atlas from the style, proposed fix for #1488

---

android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowConcurrentActivity.java
android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow_concurrent.xml
android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_drawer.xml
android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

To illustrate the behavior of multiple InfoWindows visible at a time (https://github.com/mapbox/mapbox-gl-native/issues/3115).

Added sample InfoWindowConcurrentActivity

---

platform/ios/MGLMapboxEvents.m

This doesn't solve our problems directly, but does make things clearer (I think) and avoid doing anything with CT on the simulator anyway, as I think that can be unpredictable. Basically I was seeing crashes from the root of #3112 on device, and I think on simulator because of weird behavior of CT there (so, not related directly).
/cc @friedbunny @1ec5

refs #3112: cleanups around Core Telephony runtime

---

CHANGELOG.md
docs/BUILD_IOS_OSX.md
platform/ios/MGLMapboxEvents.m

For v3.0.1, we're removing the possibility of using CoreTelephony.framework entirely as the optional linking proved to be buggy. When build and packaging improvements land soonish, we'll revisit this.
Fix #3112, ref #2581
/cc @incanus, @1ec5

[ios] fix CoreTelephony crash (by removing it)

---

package.json
src/mbgl/geometry/line_buffer.cpp
src/mbgl/geometry/line_buffer.hpp
src/mbgl/layer/line_layer.cpp
src/mbgl/layer/line_layer.hpp
src/mbgl/renderer/line_bucket.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/shader/line.vertex.glsl
src/mbgl/shader/line_shader.hpp
src/mbgl/shader/linepattern.vertex.glsl
src/mbgl/shader/linepattern_shader.hpp
src/mbgl/shader/linesdf.vertex.glsl
src/mbgl/shader/linesdf_shader.hpp

We should support offsetting lines as a paint property. The difference to `line-translate` is that it offsets the overall line, while this feature is about an offset perpendicular to the line.

Offset lines

---

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java

[android] add 's' to 'assets/' in setStyleUrl() docs

---

platform/ios/MGLMapboxEvents.m

To make data introspection more useful, we should know what state the app was in (`UIApplicationState`).
@bleege @friedbunny @1ec5 @camilleanne @mick @lxbarth

record app fg/bg/inactive state in telemetry

---

ios/Mapbox-iOS-SDK.podspec
ios/docs/pod-README.md

Replaced the term “Cocoa bindings” in documentation because this library is for iOS, not OS X. Cocoa bindings are a [completely different technology](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CocoaBindings/Concepts/WhatAreBindings.html) than what we’re developing, although the OS X port I’m making in #3135 does support Cocoa bindings.
/cc @incanus @friedbunny @mapbox/support

Abandon Cocoa bindings on iOS

---

src/mbgl/layer/background_layer.cpp
src/mbgl/layer/background_layer.hpp
src/mbgl/layer/circle_layer.cpp
src/mbgl/layer/circle_layer.hpp
src/mbgl/layer/fill_layer.cpp
src/mbgl/layer/fill_layer.hpp
src/mbgl/layer/line_layer.cpp
src/mbgl/layer/line_layer.hpp
src/mbgl/layer/raster_layer.cpp
src/mbgl/layer/raster_layer.hpp
src/mbgl/layer/symbol_layer.cpp
src/mbgl/layer/symbol_layer.hpp
src/mbgl/map/tile_worker.cpp
src/mbgl/map/tile_worker.hpp
src/mbgl/map/vector_tile_data.cpp
src/mbgl/style/layout_property.hpp
src/mbgl/style/paint_property.hpp
src/mbgl/style/style_layer.cpp
src/mbgl/style/style_layer.hpp
src/mbgl/util/worker.cpp
src/mbgl/util/worker.hpp
test/style/style_layer.cpp
test/test.gypi

With https://github.com/mapbox/mapbox-gl-native/commit/bafbf6c04b1bfd5da84411f52a72e26783f3bcb7, label placement is very slow. Label placement occurs when the map is rotated or tilted (but not on zoom or pan). It's slow because we're creating a copy of the StyleLayer* objects on essentially every frame when rotating.

Make redoPlacement faster

---

.travis.yml

Android tests are now run on Bitrise, so we can remove them from Travis builds.
This enables https://github.com/mapbox/mapbox-gl-native/issues/3165
/cc @zugaldia @bleege @tobrun

Remove Android tests from Travis

---

.travis.yml
scripts/set_compiler.sh

We should use ccache to get faster incremental compiles.
Should be as simple as changing the `CXX` variable
Caveat: Travis doesn't cache build artifacts on OS X :cry: 
Caveat: Android NDK r10e [uses shell scripts](https://code.google.com/p/android/issues/detail?id=182301) in place of `clang++` executables, but they don't contain a shebang, so `ccache` fails to invoke them (`failed: Exec format error`).

Use ccache

---

package.json
src/mbgl/renderer/painter_line.cpp

As per https://github.com/mapbox/mapbox-gl-style-spec/issues/386, we're reversing the direction of line-offset.
Master ticket: https://github.com/mapbox/mapbox-gl/issues/3#issuecomment-162607343

Reverse line-offset

---

Makefile
scripts/main.mk
scripts/node/create_node_scheme.sh
scripts/node/create_npm_scheme.sh
scripts/node/node.xcscheme

Our Xcode scheme currently uses `npm` to invoke the test suite, but that breaks debugging because npm runs as a subcommand (and seemingly doesn't `execv`). Instead, we should execute the script directly to enable breakpoints in Xcode.

Make Xcode run the test-suite directly to enable debugging

---

include/mbgl/ios/MGLMapView.h
include/mbgl/map/map.hpp
platform/ios/MGLMapView.mm
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp

@1ec5 @jfirebaugh @incanus @bleege @mapbox/mobile 
Open for suggestions about the API on MGLMapView.

Implementation of flyTo.

---

platform/default/glfw_view.cpp
platform/default/headless_view.cpp
src/mbgl/renderer/gl_config.cpp
src/mbgl/renderer/gl_config.hpp
src/mbgl/renderer/painter.cpp

We're currently setting the OpenGL viewport for every frame. Instead, we should move this to the bindings since they know best when the viewport will change. This would also allow bindings to render the map into a specific area of the screen, rather than grabbing the full screen. In particular, there's no relation between the dimensions of the map (which must match the viewport dimensions or the map will be distorted) and the size of the OpenGL context/backbuffer.

Do not alter OpenGL viewport

---

test/miscellaneous/variant.cpp

Fix an issue where the test result can be affected depending on the current locale settings of the machine running the tests.

[tests] Force classic locale on toString tests

---

android/MapboxGLAndroidSDKTestApp/build.gradle

[android] #3238 inconsistent package name

---

src/mbgl/map/transform.cpp

Improves compatibility as some old std libs don't have them on the std:: namespace.

[core] Use global namespace on some <cmath> functions

---

android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/CoordinateChangeActivity.java
android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_animate_coordinates.xml
android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_infowindow_adapter.xml
android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_infowindow_concurrent.xml
android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_tilt.xml
android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_animate_coordinate.xml
android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_drawer.xml
android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

[android] #3270 - add sample activity for animated coordinate change

---

ios/Mapbox-iOS-SDK.podspec

Reapplied 56ea347c49cfbeec9cf1dca5726b9eb322ebd1ec for #3199, half of which got lost in a merge. (Somehow, the podspec change got lost, but the readme correction persisted.)
/cc @incanus

Abandon Cocoa bindings on iOS (redux)

---

CHANGELOG.md
platform/ios/MGLMapView.mm

This PR backports a lot of annotation-related improvements from the OS X port in #3135, reprising a large chunk of #1496. MGLMapView now maps “annotation tags” (Cocoa-speak for numeric annotation IDs, by analogy with view tags, tooltip tags, etc.) to context objects that pair annotations with their identifiers. Previously, MGLMapView mapped the annotation objects themselves to context objects that contained annotation IDs, but this caused most operations involving annotations to be rather expensive: since mbgl tracks annotations by ID, most of the time you know the ID and need either the annotation or some piece of metadata about it.
Tapping now selects annotations more reliably. Tapping near the top of a large annotation image now selects that annotation. An annotation image’s alignment …

Refactored iOS annotation selection

---

package.json
src/mbgl/renderer/painter.cpp
src/mbgl/style/style.cpp

#2024 results in mis-rendered styles where a background layer is used to implement a semi-transparent overlay on top of other layers.

don't use glClear optimization for layers that aren't the bottommost

---

include/mbgl/platform/default/headless_view.hpp
platform/default/headless_display.cpp
platform/default/headless_view.cpp
platform/node/src/node_map.cpp
platform/node/src/node_map.hpp

Refs #3179
- In platform/node/src/util/async_queue.hpp:
- Punting on this per https://github.com/mapbox/mapbox-gl-native/issues/3179#issuecomment-162964129
- In platform/node/src/node_log.cpp:
- In platform/node/src/node_map.cpp:
- In platform/default/headless_display.cpp
- In platform/default/headless_view.cpp
```
error: 'const' type qualifier on return type has no effect
```
- Not quite sure what can throw or how to best implement this...
/cc @daniel-j-h

node code review cleanup

---

scripts/osx/run.sh

Building osxapp means building the SDK, so building the SDK independently is wasteful.
Fixes #3313.

Only build osxapp on Travis

---

include/mbgl/map/map.hpp
include/mbgl/platform/default/glfw_view.hpp
include/mbgl/util/geo.hpp
include/mbgl/util/mat4.hpp
platform/default/glfw_view.cpp
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/shader/sdf.vertex.glsl
src/mbgl/shader/sdf_shader.hpp
src/mbgl/util/mat4.cpp

We should support rendering the map in other orientations, e.g. so you can embed a map that is upside down, or rotated by 90 degrees.

Render map in other orientations

---

platform/osx/src/MGLMapView.mm

Mark debug mask as restorable on OS X

---

CHANGELOG.md
include/mbgl/ios/MGLMapView.h
include/mbgl/map/camera.hpp
include/mbgl/osx/MGLMapView.h
ios/app/MBXViewController.mm
platform/ios/MGLMapView.mm
platform/osx/app/AppDelegate.m
platform/osx/app/MainMenu.xib
platform/osx/src/MGLMapView.mm
src/mbgl/map/transform.cpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp

This PR fixes the trajectory of `mbgl::Map::flyTo()` to stay within the Earth’s atmosphere. When this function was originally ported from GL JS, there was apparently some confusion between zoom level and scale.
`flyTo()` now transitions the pitch in addition to the position and bearing; calls transition frame/finish callback functions, allowing client code to chain animations; and recognizes the same `speed` and `curve` parameters as GL JS. Unfortunately, these two parameters appear to be specific to the animation formulae and not expressed in physical units; I haven’t exposed them publicly because I don’t know of a good way to explain them other than “numbers that you fiddle with”. (They come from mapbox/mapbox-gl-js@983ae5efccb43c08d406bedbc21bff4e3593d66b.)
A …

Fix flyTo trajectory; port to OS X

---

src/mbgl/map/transform_state.cpp

As some versions of libstdc++ don't have it.

[core] Do not use std:: namespace for log2()

---

platform/default/glfw_view.cpp

Setting the viewport size from the main thread has no affect on Linux and thus, the map doesn't scale. We now set the viewport size on the beforeRender() hook that gets called from the Map thread.

[glfw] Set viewport size from the Map thread

---

src/mbgl/map/transform.cpp

`startTransition()` is ill-suited to atomic transitions, which are expected to be synchronous and end up at the final state.
/ref #3244
/cc @bleege

Atomic flyTo()

---

platform/osx/app/mapboxgl-app.gypi
platform/osx/sdk/framework-osx.gypi

Error message:
```
ninja: error: obj/gyp/osxsdk.ninja:97: bad $-escape (literal $ must be written as $$)
@rpath/Mapbox.framework/Versions/A/Mapbox -Wl,-rpath,$(inherited) $
^ near here
```

[osx] 'make compdb' is failing

---

platform/osx/app/mapboxgl-app.gypi

Xcode (or perhaps gyp’s Xcode adapter) doesn’t understand \$ inside a copy files run phase path.
/ref #3337

Fix crash on launch when osxapp is run without a debugger attached

---

src/mbgl/map/source.cpp
src/mbgl/map/source.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style_layer.cpp
src/mbgl/style/style_layer.hpp
test/fixtures/resources/style-unused-sources.json
test/fixtures/resources/style.json
test/style/pending_resources.cpp
test/style/resource_loading.cpp
test/style/unused_sources.cpp
test/test.gypi

Given https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/satellite-hybrid-v8.json as example of a style containing 2+ sources, if all layers related to a specific source are either disabled (e.g. due to class selections) or invisible, we should avoid _loading_ the style source entirely. This saves processing time and network bandwidth.
When the layers related to a specific style source are re-enabled, the burden of loading the style source could be reduced by using a cache file source.
/cc @mapbox/gl @mapbox/mobile

Avoid loading style source if its layer(s) are not shown

---

test/fixtures/resources/style-unused-sources.json
test/style/unused_sources.cpp

This extra test checks whether a style, initially with two sources, but only one source used, triggers the second source loading after a class `visible` is added.
/cc @jfirebaugh @tmpsantos

[core] Add more tests to on-demand source load

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/SpriteFactory.java

allow other type of drawable to be used from a resource drawable other than BitmapDrawables.
Closes #3107

[android] #3107 - add support non BitmapDrawables to SpriteFactory

---

package.json
src/mbgl/renderer/painter.cpp

Regressed in 6e41664cb033ee5edf6ae5ac66ed518d9f0d1f89. This restores it to the same behavior as gl-js, backed by test-suite tests.

[core] Fix background-pattern origin

---

include/mbgl/map/camera.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdate.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/MathUtils.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/CameraActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_transform_24dp.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_camera.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_drawer.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/src/jni.cpp
src/mbgl/map/transform.cpp

[android] Camera API

---

platform/default/glfw_view.cpp

Framebuffer width/height takes pixel ration in consideration.
Part of #3294.
/cc @tmpsantos

[osx] Use framebuffer width/height in GLFW port

---

platform/darwin/MGLMapCamera.mm

It’s MGLMapCamera (or a subclass), not MKMapCamera.

Typo in MGLMapCamera debug description

---

include/mbgl/ios/MGLMapView.h
include/mbgl/map/camera.hpp
include/mbgl/osx/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp

This is a followup to #3301 that further refines the flight path used by `Transform::flyTo()` to match GL JS exactly, even as the pitch varies between the endpoints. It fixes #3296 and ensures that the ending zoom level is respected regardless of the starting zoom level. Finally, I began documenting and renaming variables to reflect a better understanding of this algorithm, now that [this paper](https://www.win.tue.nl/%7Evanwijk/zoompan.pdf) has been rediscovered.
Other noteworthy changes:
* Began pushing mutators into `TransformState`, which will allow us to begin factoring redundant code out of `Transform`.
* Addresses mapbox/mapbox-gl-js#1853 by crossing the antimeridian if that would be a shorter path.
* Replaces the opaque `speed` and `curve` options with more intuitive options that …

Further refine flyTo() flight path

---

platform/osx/src/MGLMapView.mm

Flip the origin when determining the center point of the drag-rotate gesture on OS X.

Flip drag-rotate center point

---

CHANGELOG.md
include/mbgl/ios/MGLMapView.h
include/mbgl/osx/MGLMapView.h
platform/darwin/MGLGeometry.mm
platform/darwin/MGLGeometry_Private.h
platform/darwin/MGLMapCamera.mm
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm
src/mbgl/map/transform.cpp

Greatly simplified conversions between zoom level and altitude. Adjusted the (apparently vertical) field of view to more closely match MapKit. Conversions are now nearly identical to MapKit at all latitudes.
The conversion code is now shared between iOS and OS X. It isn’t in mbgl, because although the conversions are more or less consistent with MapKit, it isn’t clear that they’re consistent with mbgl itself. (mbgl also has its own concept of “altitude” that’s distinct from the conventional meaning of altitude.)
Building off this improvement, MGLMapView now has a variation of `-flyToCamera:…` that accepts a peak altitude parameter.
Fixes #2266, and probably also fixes #3286. Also fixed #2456 along the way.
/cc @friedbunny @adam-mapbox

Better zoom level–altitude conversion

---

test/miscellaneous/async_task.cpp

```
[ RUN      ] AsyncTask.RequestCoalescingMultithreaded
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to initialize loop.
./scripts/run_tests.sh: line 32: 80042 Abort trap: 6           (core dumped) ${CMD}
```
Default value of `ulimit -n` on OS X is 256. Raising it to 1024 allows the test to pass. Can we rewrite the test so that it doesn't try to open more than 256 files?

AsyncTask.RequestCoalescingMultithreaded test fails on OS X with default ulimits

---

Makefile

`make osx` now builds with Xcode instead of make, because building the OS X SDK and osxapp requires Xcode-specific build settings as of #3135. `make xosx` and `make nosx` are now aliases to `make osx`.
Fixes #3293.
/cc @kkaefer @jfirebaugh

make osx with Xcode

---

include/mbgl/ios/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLUserLocationAnnotationView.m

Renamed `-metersPerPixelAtLatitude:` to `-metersPerPointAtLatitude:`, leaving the old name as a deprecated alias. In Cocoa Touch terminology, “point” is the visual unit backed by pixels.
(On OS X, I called the equivalent method `-metersPerPointAtLatitude:` from the start, so this makes the two SDKs more consistent.)

Meters per point at latitude

---

scripts/main.mk

Updated remaining script paths from `scritps/$(HOST)/$(HOST_VERSION)` to `platform/$(HOST)/scripts/$(HOST_VERSION)`.
/cc @jfirebaugh @tmpsantos

[core] Fix build script paths

---

include/mbgl/util/exception.hpp
platform/node/test/js/map.test.js
src/mbgl/map/map_context.cpp
src/mbgl/map/map_context.hpp
src/mbgl/map/raster_tile_data.cpp
src/mbgl/map/source.cpp
src/mbgl/map/source.hpp
src/mbgl/map/tile_data.cpp
src/mbgl/map/tile_data.hpp
src/mbgl/map/tile_worker.hpp
src/mbgl/map/vector_tile.cpp
src/mbgl/map/vector_tile_data.cpp
src/mbgl/sprite/sprite_parser.cpp
src/mbgl/sprite/sprite_parser.hpp
src/mbgl/sprite/sprite_store.cpp
src/mbgl/sprite/sprite_store.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
src/mbgl/text/glyph_pbf.cpp
src/mbgl/text/glyph_pbf.hpp
src/mbgl/text/glyph_store.cpp
src/mbgl/text/glyph_store.hpp
src/mbgl/util/worker.cpp
src/mbgl/util/worker.hpp
test/sprite/sprite_parser.cpp
test/sprite/sprite_store.cpp
test/style/glyph_store.cpp
test/style/resource_loading.cpp

* Standardize on std::exception_ptr as the error representation
(fixes #2854).
* Don't format textual strings at the error source; pass on the
constituent data via observer method parameters instead.
* Use the null object pattern to simplify observer notification code.
* Further refactoring for ResourceLoading tests.
:eyes: @brunoabinader

[core] Rationalize error handling for resource loading

---

CHANGELOG.md
platform/ios/src/MGLMapView.mm

`-[MGLMapView showAnnotations:animated:]` hardcoded the edge inset to 100 points on all sides, which meant that views with height or width <=200 points would max-zoom into the center point of the bounds, not show the entire bounds.
This fix varies the edge padding based on the map view's frame size — if it's less than the default padding, use a fraction of the map view frame's height/width as inset padding.
Fix #3392, #3110.
/cc @1ec5

[ios] vary annotation bounds fit padding based on view size

---

test/fixtures/mock_file_source.cpp
test/fixtures/mock_file_source.hpp
test/fixtures/stub_style_observer.hpp
test/sprite/sprite_store.cpp
test/style/glyph_store.cpp
test/style/pending_resources.cpp
test/style/resource_loading.cpp

* Rewrite {Sprite,Glyph}Store tests in the style of ResourceLoading
* Simplify MockFileSource
:eyes: @brunoabinader

Simplify tests

---

CHANGELOG.md
platform/ios/src/MGLMapView.mm

If a user pinch-rotates and the gesture ends within ±7° of north, reset to north (0°).
This behavior is the same as in MapKit.
First proposed in #938, implemented in #1059, reverted in #1064. (Closes #1064.)
/cc @1ec5

[ios] snap to north if interaction ends within ±7°

---

Makefile
gyp/osx.gyp
platform/osx/scripts/run.sh
platform/osx/scripts/test.sh
platform/osx/test/Info.plist
platform/osx/test/MGLGeometryTests.mm
platform/osx/test/MGLStyleTests.mm
platform/osx/test/osxtest.gypi

Added an XCTest bundle to the osxsdk scheme. For now, it contains some basic tests of shared iOS/OS X code. It can easily be extended to cover more of the SDK, including UI tests via XCTUI.
Unlike what we did on iOS for #830, I’ve integrated the test bundle directly into the project that contains the SDK code, allowing us to write unit tests as opposed to just integration tests.
This PR works toward replacing KIF with XCTUI on iOS, which would eliminate the unreliability in #2734 and allow us to add better tests around user interaction and performance. I started with OS X because everything’s simpler on OS X. :smile:
/cc @incanus @friedbunny @jfirebaugh

OS X SDK unit tests

---

platform/android/bitrise.yml
platform/ios/bitrise.yml
platform/osx/bitrise.yml
platform/osx/scripts/run.sh

This PR moves building and testing of the OS X SDK from Travis to Bitrise, leaving Travis to build only the cross-platform rendering tests.
Since we now have three Bitrise hooks with identical output in our internal Slack room, I added pictograms to distinguish them from one another.
/cc @jfirebaugh @friedbunny @incanus

Move OS X SDK builds from Travis to Bitrise

---

platform/osx/src/MGLMapView.mm
src/mbgl/map/source.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform_state.cpp

I started out trying to fix the OS X SDK’s Zoom Out button, which refused to disable even as you reach the effective minimum zoom level. I wound up fixing a few related issues:
* Two active sources can have different minimum and maximum zoom levels. Always use the nearest available zoom level for the source. `TransformState` has the final say over whether a zoom level is allowed.
* Even if `TransformState::constrainMode` is `HeightOnly`, there isn’t usually a reason to _show_ more than one full revolution of the world at a time. Before this change, osxapp effectively constrained the zoom level based on whether the window was shorter or taller than 512 points. (Maps.app constrains the zoom level even further in standard view, but that’s because its satellite view is projected onto a globe, …

Various zoom level corrections

---

platform/osx/app/AppDelegate.h
platform/osx/app/AppDelegate.m
platform/osx/app/Info.plist
platform/osx/app/MainMenu.xib
platform/osx/app/MapDocument.h
platform/osx/app/MapDocument.m
platform/osx/app/MapDocument.xib
platform/osx/app/mapboxgl-app.gypi

Allow for multiple map windows open at a time. If windows aren’t kept when quitting, the last open window is restored at the next launch, just like in Maps.app.
Also fixed the zoom level used for the map feedback tool, and the URL handler now accepts a `pitch` argument.

Make osxapp document-based

---

test/fixtures/util.cpp
test/fixtures/util.hpp
test/storage/server.js
test/storage/storage.cpp
test/storage/storage.hpp

After 3a86321aeecbf4acb2c0b6040d1f332b616a823a, our test server is sometimes lingering around in case the main application crashed and failed to terminate the server. To prevent this from happening, we're going to use a second pipe that we're `dup`ing onto `stdin` in the server, and automatically terminate in case that pipe gets closed.

Make server tests more robust

---

platform/default/sqlite_cache.cpp
platform/default/sqlite_cache_impl.hpp
test/storage/database.cpp

Launching iosapp on a recent master spews these:
```
[ERROR] {SQLiteCache}[Database](1): no such column: accessed
[ERROR] {SQLiteCache}[Database](1): table http_cache has no column named accessed
```
/cc @jfirebaugh @kkaefer

SQLiteCache 'http_cache' table has no 'accessed' column

---

CHANGELOG.md
platform/ios/src/MGLMapView.mm

Set the GLKView’s layer to be non-opaque. In rudimentary testing, this appears to have no noticeable performance impact on styles that have opaque background layers (which should be the vast majority of styles). Any performance impact I’m seeing with a transparent background style layer appears to be due to content beneath the map view.
Fixes #3038.
/cc @incanus

Transparent GLKView

---

.travis.yml

This PR removes the OS X SDK (OS X + Xcode 7) from the Travis build matrix. OS X SDK builds on Bitrise have worked well for us since #3415. Meanwhile, the OS X build takes the longest in the Travis build matrix, even though it doesn’t even run or test anything. OS X–hosted Node.js builds will continue to run on Travis.
Obviates #3428.

Remove OS X SDK from build matrix

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MyLocationTrackingModeActivity.java

Closes #3444 and #3435.
Added change listeners to location tracking and bearing tracking, added requires permissions checks and handled them in the test app, update javadoc to reflect changes, formatting commit of MapView, Reposition UserLocationView when location tracking becomes active.

[android] #3444 #3435 - Stop user tracking and permissions annotation

---

test/storage/cache_size.cpp

Spotted sometimes on the bots:
```
[ RUN      ] Storage.CacheSizePruneLeastAccessed
../../test/storage/cache_size.cpp:201: Failure
Value of: tileIsCached(&cache, 7)
Actual: false
Expected: true
../../test/storage/cache_size.cpp:202: Failure
Value of: tileIsCached(&cache, 9)
Actual: false
Expected: true
```
/cc @kkaefer

[tests] Storage.CacheSizePruneLeastAccessed is flaky

---

CHANGELOG.md
ios/benchmark/MBXBenchViewController.mm
platform/ios/src/MGLMapView.mm

CADisplayLink holds a strong reference to its target, forming a cycle that must be broken with `-[CADisplayLink invalidate]` when the animation is complete. I don’t yet have enough faith that `MapChangeRegionWillChangeAnimated` and `MapChangeRegionDidChangeAnimated` notifications are always coming from mbgl in pairs, so this change limits CADisplayLink to when MGLMapView is in the view hierarchy. It also pauses the CADisplayLink when the application is in the background. Finally, `-[MGLMapView invalidate]` has been renamed because that term tends not to mean “redraw” in Cocoa but is rather tied to timers.
Fixes #3130, which is a regression introduced in #2922.
@adam-mapbox @tomtaylor, can you verify that the original fix has not regressed with this change?

Invalidate CADisplayLink

---

include/mbgl/ios/MGLMapView.h
platform/ios/src/MGLMapView.mm

The coordinate bounds conversion methods on MGLMapView have been public in the OS X SDK all along. This change makes them public in the iOS SDK too.
/cc @friedbunny @jfirebaugh

Add missing coordinate conversion methods to iOS SDK

---

platform/default/online_file_source.cpp
src/mbgl/map/map_context.cpp
src/mbgl/util/mapbox.cpp
src/mbgl/util/mapbox.hpp
src/mbgl/util/url.cpp
src/mbgl/util/url.hpp
test/storage/file_reading.cpp

We're currently storing `asset://` requests in the cache, but given that they're on the local file system anyway, we should never do that.

Don't store asset:// requests in the cache

---

platform/default/online_file_source.cpp
test/storage/cache_response.cpp
test/storage/server.js

Right now, we're storing all sorts of responses into the cache, potentially overwriting existing successful responses. This means that a bad connection could slowly remove all cache items by simply requesting them.

Only cache successful or NotFound responses

---

platform/default/online_file_source.cpp
test/miscellaneous/timer.cpp

There is no need for the timer to be created only under certain conditions. Stopping a non-started timer is a no-op (I added a test for this). Therefore it can simply be a direct member.
While here, rename the variable. It's a timer, not a request.
cc @kkaefer

[core] Simplify OnlineFileSource's Timer use

---

platform/default/async_task.cpp
platform/default/online_file_source.cpp
platform/default/run_loop.cpp
platform/default/timer.cpp
src/mbgl/map/map_context.cpp
src/mbgl/util/async_task.hpp
src/mbgl/util/timer.hpp
test/fixtures/mock_file_source.cpp
test/miscellaneous/async_task.cpp
test/miscellaneous/timer.cpp
test/style/pending_resources.cpp

Classes like `Timer` and `AsyncTask` have a `::ref()` and `::unref()` method which is legacy from `libuv` for keeping the main loop alive. Now that we have a `util::RunLoop` abstraction we don't need this and it just causes confusion.
Removing these methods also opens a door for optimization as we can lazy instantiate the `Impl` part of these objects and thus save some memory.

[core] ::unref() is probably no longer needed

---

test/fixtures/util.cpp

`execl` uses varargs thus must be NULL terminated.

[tests] Fix how we launch the test server

---

include/mbgl/osx/MGLMapView.h
platform/darwin/MGLMapCamera.mm
platform/osx/src/MGLMapView.mm

Fixed a compiler error that’s new in Xcode 7.3. Also corrected a typo in MGLMapView on OS X.

Fix error in Xcode 7.3 build

---

Makefile
platform/default/sqlite_cache.cpp

chrono's second is not an int64_t on x86_x64 and there is only a template for int64_t for bind and get.
Seems to start the demo app and work on x86_64 emulator

[android] Fixed x86_64 crash on startup

---

include/mbgl/map/camera.hpp
include/mbgl/map/map.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/NativeMapView.java
platform/android/src/jni.cpp
platform/ios/scripts/package.sh
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp
test/miscellaneous/transform.cpp

This PR cleans up `Transform` considerably, making it easier to implement #2600 at this low level:
* `CameraOptions` only describes the destination viewpoint now. `AnimationOptions` describes the transition to that destination viewpoint.
* Eliminated many redundant methods on `Transform`.
* Minimized usage of `TransformState::x` and `TransformState::y`.
* Added convenience constructors for `AnimationOptions`. When scaling, passing in view’s origin as the anchor no longer anchors the scaling operation at the view’s center. To specify no anchor, use `NaN` instead of 0.
* Corrected `setBearing()` to assume an origin at the upper-left corner of the view rather than the lower-left corner.
* Added an `anchor` option to `CameraOptions` that pins a coordinate to a point within the view throughout …

Refactor Transform

---

src/mbgl/style/style_parser.cpp

This PR removes a `std::move()` call, as suggested by Xcode’s fix-it feature. Xcode 7.3 beta 1 fails to compile this code with the following error:
```
/path/to/mapbox-gl-native/src/mbgl/style/style_parser.cpp
/path/to/mapbox-gl-native/src/mbgl/style/style_parser.cpp:240:12: Moving a local object in a return statement prevents copy elision
/path/to/mapbox-gl-native/src/mbgl/style/style_parser.cpp:240:12: Remove std::move call here
```
/ref #3480
/cc @kkaefer

Fix build error in Xcode 7.3

---

platform/android/src/http_request_android.cpp

[android] #3539 - silence warning about unused param message 

---

src/mbgl/map/transform.cpp

Crashing at the same line. Seems to be a race of the callback firing with an invalid `this` on the lambda. /cc @1ec5 
```
Program received signal SIGSEGV, Segmentation fault.
mbgl::Transform::<lambda(mbgl::TimePoint)>::operator() (now=..., __closure=0xc5c7a0) at ../../src/mbgl/map/transform.cpp:543
543	            transitionFinishFn = nullptr;
Thread 257 (Thread 0x7fff577f6700 (LWP 23998)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x000000000086581a in uv__epoll_wait (epfd=<optimized out>, events=<optimized out>, nevents=<optimized out>, timeout=<optimized out>) at src/unix/linux-syscalls.c:321
#2  0x0000000000863f02 in uv__io_poll (loop=0x7fffa4000bd0, timeout=-1) at src/unix/linux-core.c:243
#3  0x000000000085b163 in uv_run (loop=0x7fffa4000bd0, …
```

[core] ResourceLoading.Success and Transform.InvalidScale crashing

---

test/ios/MapViewTests.m

Remove test that fails on CI because of KIF unreliability.
Refs 61615a44fd49336905e7b18c8ac665ce1eb7d4a4, #2769, #2734.
/cc @1ec5

[ios] remove `testCompassTap` test

---

platform/ios/src/MGLMapboxEvents.m

The turnstile event is used solely to count monthly active users and should always be sent, regardless of whether the user has opted themselves out of telemetry.
The turnstile wasn't being turned if telemetry was paused because `_session` is invalided and `nil`'d in `pauseMetricsCollection`. This change instantiates a temporary `NSURLSession` for the turnstile event.
@1ec5 I could use your advice on my use of `strongSelf.session` here — before, we were straight-up calling `_session`, but inside of a background async block.

Send turnstile event when telemetry is paused

---

include/mbgl/ios/MGLMapView.h
include/mbgl/osx/MGLMapView.h
platform/ios/src/MGLCategoryLoader.m
platform/osx/src/MGLMapView.mm

This PR fixes the following static analyzer warnings reported by Xcode 7.3 beta 1 when building iosapp:
```
/path/to/mapbox-gl-native/platform/ios/src/MGLCategoryLoader.m
/path/to/mapbox-gl-native/platform/ios/src/MGLCategoryLoader.m:21:15: Value stored to 'description' during its initialization is never read
/path/to/mapbox-gl-native/platform/ios/src/MGLCategoryLoader.m:21:15: Value stored to 'description' during its initialization is never read
/path/to/mapbox-gl-native/platform/ios/src/MGLMapView.mm
/path/to/mapbox-gl-native/platform/ios/src/MGLMapView.mm:1197:9: Null passed to a callee that requires a non-null argument
/path/to/mapbox-gl-native/platform/ios/src/MGLMapView.mm:1197:9: Null passed to a callee that requires a non-null argument …
```

Fix static analyzer warnings in Xcode 7.3

---

src/mbgl/layer/symbol_layer.cpp
src/mbgl/map/tile_worker.cpp
src/mbgl/map/tile_worker.hpp
src/mbgl/map/vector_tile_data.cpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/renderer/symbol_bucket.hpp
src/mbgl/style/style_bucket_parameters.hpp
src/mbgl/util/worker.cpp
src/mbgl/util/worker.hpp

Previously, the placement of symbol layers depended on the order in which the glyphs they need were loaded. The placement order should be based on the style.
To fix this, symbol layers are placed in `placementPending` after they are parsed. After all layers are parsed, symbol layers (stored in `placementPending`) are placed and returned.
@kkaefer can you review this?

place symbol layers in correct order

---

platform/android/src/http_request_android.cpp
platform/darwin/http_request_nsurl.mm
platform/default/http_request_curl.cpp
test/storage/cache_revalidate.cpp

Until #2721 lands we still need this.
Fixes #3560.

[core] Restore existing response body

---

platform/default/default_file_source.cpp
platform/default/sqlite_cache.cpp
src/mbgl/storage/sqlite_cache.hpp
test/storage/cache_shared.cpp
test/test.gypi

We're currently only supporting one path, and calling this function will always return the same cache, as long as it's held elsewhere. That means subsequent requests won't necessarily honor the path passed to `SharedSQLiteCache::get()`.

Support multiple paths in SharedSQLiteCache::get

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java

[android] #3559 - don't show InfoWindow when marker is invalid

---

src/mbgl/annotation/annotation_manager.cpp
src/mbgl/map/source.cpp
src/mbgl/map/source.hpp
src/mbgl/map/source_info.hpp
src/mbgl/style/style_parser.cpp

https://github.com/mapbox/mapbox-gl-native/commit/e8705d535d56415ff8f97db1ad6b5a77ed3fcd4a#commitcomment-15454766 accidentally moved `tileSize` from the style to the TileJSON file.

Fix tileSize in style sources specification

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/BoundingBox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/CoordinateBounds.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/CoordinateRegion.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/CoordinateSpan.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngZoom.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/ProjectedMeters.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/CoordinateBoundsTest.java

Remove serialisable interface from classes in geometry package, implemented parceable on CoordinateBounds, CoordinateRegion and CoordinateSpan. Enforced Android code conventions on those classes.
Closes #3503

[android] #3503 - remove serialisable interface

---

include/mbgl/map/camera.hpp
include/mbgl/util/optional.hpp
platform/android/src/jni.cpp
src/mbgl/annotation/annotation_tile.cpp
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/map/geometry_tile.cpp
src/mbgl/map/geometry_tile.hpp
src/mbgl/map/map.cpp
src/mbgl/map/map_context.cpp
src/mbgl/map/map_context.hpp
src/mbgl/map/vector_tile.cpp
src/mbgl/map/vector_tile.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/sprite/sprite_atlas.cpp
src/mbgl/sprite/sprite_atlas.hpp
src/mbgl/style/filter_expression_private.hpp
src/mbgl/style/function.hpp
src/mbgl/style/layout_property.hpp
src/mbgl/style/property_parsing.cpp
src/mbgl/style/property_parsing.hpp
src/mbgl/style/property_transition.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
src/mbgl/text/shaping.hpp
src/mbgl/tile/geojson_tile.cpp
src/mbgl/tile/geojson_tile.hpp
src/mbgl/util/http_header.hpp
test/miscellaneous/comparisons.cpp

`std::experimental::optional` is likely to become a non-experimental part of the standard library in the next revision, and is more complete than our `mapbox/variant`-based implementation. It's supported by gcc 4.9 and clang 3.5; need to check on iOS/OS X.
For brevity, I recommend we define `mbgl/util/optional.hpp`:
```
#include <experimental/optional>
namespace mbgl {
using optional = std::experimental::optional;
}
```
And then use unqualified `optional<T>` wherever needed in the `mbgl` namespace.

switch to std::experimental::optional

---

CHANGELOG.md
include/mbgl/sprite/sprite_image.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
platform/android/src/jni.cpp
platform/default/glfw_view.cpp
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm
src/mbgl/annotation/annotation_manager.cpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/sprite/sprite_atlas.cpp
src/mbgl/sprite/sprite_atlas.hpp
src/mbgl/sprite/sprite_image.cpp
src/mbgl/sprite/sprite_parser.cpp
src/mbgl/sprite/sprite_store.cpp
src/mbgl/text/shaping.cpp
test/api/annotations.cpp
test/fixtures/util.cpp
test/fixtures/util.hpp
test/sprite/sprite_atlas.cpp
test/sprite/sprite_image.cpp
test/sprite/sprite_parser.cpp
test/sprite/sprite_store.cpp

ref #3031
ref #2198
For example, an icon that has:
- a pixel width of 10
- a pixel ratio of 3
- a scaled with of 3.333
is now supported.
SpriteImage is now constructed with the pixel width of the image instead of the width.
this works in android with @tobrun's https://github.com/mapbox/mapbox-gl-native/tree/3031-test-branch-android
@1ec5 I think this should fix #2198 - what's the best way to test that?

[core][ios][osx][android] fix icons with non-integer width/height

---

include/mbgl/util/run_loop.hpp
platform/darwin/http_request_nsurl.mm
platform/default/run_loop.cpp
test/miscellaneous/run_loop.cpp
test/test.gypi

```
[ RUN      ] Storage.HTTPLoad
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to close loop.
./scripts/run_tests.sh: line 32: 96090 Abort trap: 6           (core dumped) ${CMD}
make[1]: *** [test-Storage.HTTPLoad] Error 134
make: *** [test-Storage.HTTPLoad] Error 2
```
Presumably related to d7fdcc73bfcab39f63e547ce2af8435a9859cb08.
cc @tmpsantos

Test fail with "terminating with uncaught exception of type std::runtime_error: Failed to close loop."

---

.travis.yml
platform/node/README.md

We're continually squeezed by Travis build queue, so any reduction of the build matrix size is good. Can we drop node 0.10 on OS X and linux (2 rows)?
cc @mikemorris

Drop node 0.10 from build matrix

---

package.json
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/text/collision_tile.cpp
src/mbgl/text/collision_tile.hpp

Prevent symbols from colliding with tile edges when `symbol-avoid-edges` is true.
fixes https://github.com/mapbox/mapbox-gl-native/issues/3582
render tests: https://github.com/mapbox/mapbox-gl-test-suite/commit/bc0272cdde41d027a5df1ca8fb3aa1bc49aa8149
-js pull request: https://github.com/mapbox/mapbox-gl-js/pull/1951

implement symbol-avoid-edges

---

package.json
src/mbgl/text/check_max_angle.cpp

Instead of using the absolute value of the sum of angles, use the sum of the absolute values of angles.
This helps avoid labels on lines with sharp zig zags.
for example, the "Central Campus Mall" label in issue #2998
-js pr: https://github.com/mapbox/mapbox-gl-js/pull/1959
test-suite update: test-suite update: https://github.com/mapbox/mapbox-gl-test-suite/tree/max-angle-fix

[core] improve text-max-angle check

---

package.json
platform/node/CHANGELOG.md

Document dropping support for Node.js v0.10.x, add `engines` field to `package.json` and update changelog.

node-v3.0.0

---

package.json
src/mbgl/map/source.cpp
src/mbgl/map/source.hpp
src/mbgl/map/tile_data.hpp
src/mbgl/map/vector_tile_data.cpp
src/mbgl/map/vector_tile_data.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp

This adds `onPlacementRedone` to `Source::Observer` which is called when a tile is updated with new symbol placement. Style uses this to trigger a repaint.
fixes #3140
This also fixes a bug where placement could be redone with a stale PlacementConfig after the tile first finishes loading.
@jfirebaugh can you review?

[core] trigger repaint after placement is redone

---

package.json
src/mbgl/map/source.cpp
src/mbgl/map/source.hpp
src/mbgl/map/tile_data.hpp
src/mbgl/map/vector_tile_data.cpp
src/mbgl/map/vector_tile_data.hpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp

Use nearest neighbour texture filtering to draw sharper icons when the icons are aligned with the viewport. This matches -js.

[core] use nearest neigbour texture filtering for some line icons

---

platform/ios/src/MGLMapView.mm

Programmatic modification of the viewport should kick the user out of user tracking mode. Also, fixed a regression from #3589 in which rotating the map with two fingers failed to kick the user out of heading or course tracking mode. (It now goes into location tracking mode, per MapKit.)

Disable user tracking in -setVisibleCoordinates:

---

include/mbgl/map/map.hpp
ios/benchmark/MBXBenchViewController.mm
platform/android/src/jni.cpp
platform/default/glfw_view.cpp
platform/default/http_request_curl.cpp
platform/default/timer.cpp
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm
src/mbgl/map/map_data.hpp
src/mbgl/map/transform.cpp
src/mbgl/style/function.cpp
src/mbgl/style/property_parsing.cpp
src/mbgl/util/stopwatch.cpp
test/fixtures/mock_file_source.cpp
test/fixtures/util.cpp
test/fixtures/util.hpp
test/miscellaneous/timer.cpp
test/storage/cache_size.cpp
test/storage/http_retry_network_status.cpp

We have abstractions for `std::chrono` in `mbgl/util/chrono.hpp` for most common usages. This patch series reduces `std::chrono` cast complexity and usage to `include/mbgl/util/chrono.hpp`.
:eyes: @kkaefer @jfirebaugh @tmpsantos

Cleanup std::chrono usage

---

CHANGELOG.md
platform/ios/src/MGLMapboxEvents.m

Apps with `whenInUse` location permission will show a blue status bar when they continue to use location services after leaving the foreground. This is worrying and to be avoided, so let's disable telemetry location services in this situation.
Fixes #2945, refs #3641.
/cc @boundsj @1ec5 @jfirebaugh @mikemorris

[ios] Avoid the blue background location status bar

---

platform/ios/src/MGLMapboxEvents.m

This just removes some whitespace that made the implementation of
`pushTurnstileEvent` in `MGLMapboxEvents` look a little strange.
The indentation was right below an early return conditional
(with no braces) so it felt like the right thing to do (for
readability) to clean it up. Choosing and enforcing a consistent style
for conditionals with one line might be a good idea, too, but this
small change does not go there.

[ios] Remove incorrect tab whitespace in method

---

include/mbgl/util/run_loop.hpp
src/mbgl/map/tile_worker.cpp
src/mbgl/map/tile_worker.hpp
src/mbgl/util/worker.cpp

This is a short term fix for #3636. The reason for the hangs we were seeing was because the following happened:
- Work task completes, calls `callback`, which schedules the after callback on the main thread
- After callback was invoked and tried to cancel the work task first thing, which blocks on the mutex
- On the worker thread, we were destructing the arguments (in particular the `VectorTile` object) *after* we've called the callback in the first step; on slow devices, this could take 20-100ms
- Worker thread releases mutex, then main thread can finally acquire it to mark the task as canceled
This patch fixes this with the following changes:
- Move work task arguments from the tuple into the actual function, so they can be destructed there before the callback gets fired
- Actually …

WorkTasks: destruct data before invoking callback

---

CHANGELOG.md
include/mbgl/ios/MGLMapView.h
include/mbgl/map/map.hpp
include/mbgl/osx/MGLMapView.h
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/NativeMapView.java
platform/android/src/jni.cpp
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp

fixes https://github.com/mapbox/mapbox-gl-native/issues/509

add setters, getters for map's minZoom and maxZoom

---

platform/ios/src/MGLMapView.mm

Avoid resetting user tracking state when going from location or course tracking mode to heading tracking mode.
Fixes #3710.

Eliminate “flashlight mode”

---

include/mbgl/ios/MGLMapView.h
ios/app/MBXViewController.mm
ios/benchmark/MBXBenchViewController.mm
platform/ios/src/MGLMapView.mm

This change ports over `MGLMapDebugMaskOptions` from the OS X SDK, allowing you to toggle individual debugging aids. The old debug options have been deprecated and will be removed in a future release.
/ref #3100

Debug mask

---

LICENSE.md

We switched to libjpeg-turbo in #3632.
Original license requirements: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/LICENSE.md
License: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/turbojpeg.c

Add libjpeg-turbo license, remove libjpeg license

---

src/mbgl/map/vector_tile_data.cpp

fix #3727
If a workRequest exists, don't cancel it and start an new request. It's ok to just do nothing if the request exists because a new call to redoPlacement will be triggered after the existing request finishes.
This fixes a regression in https://github.com/mapbox/mapbox-gl-native/pull/3543
@tmpsantos can you review?

fix redoPlacement blocking main thread, fix #3727

---

include/mbgl/storage/resource.hpp
src/mbgl/map/map_context.cpp
src/mbgl/map/raster_tile_data.cpp
src/mbgl/map/raster_tile_data.hpp
src/mbgl/map/source.cpp
src/mbgl/map/vector_tile.cpp
src/mbgl/map/vector_tile.hpp
src/mbgl/sprite/sprite_store.cpp
src/mbgl/storage/resource.cpp
src/mbgl/text/glyph_pbf.cpp
src/mbgl/util/url.cpp
src/mbgl/util/url.hpp
test/storage/resource.cpp
test/test.gypi

Extract URL construction code for reuse in #3715.

[core] Rationalize Resource initialization

---

src/mbgl/map/source.cpp
src/mbgl/style/style_parser.cpp
src/mbgl/style/style_parser.hpp

Make `StyleParser::parseTileJSON` usable for #3715.

[core] Refactor TileJSON parsing for offline

---

include/mbgl/ios/MGLMapView.h
platform/ios/src/MGLMapView.mm

This PR rebases #3674 atop master for fast-forward merging. Along the way, I revised @jormon’s change to fix a syntax error that crept in and also performed a bit of copyediting.

Show annotations with custom edge padding

---

include/mbgl/util/constants.hpp
package.json
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/layer/circle_layer.cpp
src/mbgl/layer/fill_layer.cpp
src/mbgl/layer/line_layer.cpp
src/mbgl/map/geometry_tile.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/vector_tile.cpp
src/mbgl/map/vector_tile.hpp
src/mbgl/renderer/circle_bucket.cpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/renderer/symbol_bucket.hpp
src/mbgl/shader/raster.vertex.glsl
src/mbgl/text/collision_tile.cpp
src/mbgl/text/collision_tile.hpp
src/mbgl/text/get_anchors.cpp
src/mbgl/tile/geojson_tile.hpp
src/mbgl/util/constants.cpp
src/mbgl/util/get_geometries.cpp
src/mbgl/util/get_geometries.hpp

Convert all geometries to the maximum extent supported by our buffers and then use that constant extent everywhere else.
ports 1da1e5ab2bd10ea4d427d4f8dacd77e54f47e0b9 from -js
fixes https://github.com/mapbox/mapbox-gl-native/issues/250
Only the line extent render test is re-enabled. The rest of the extent render tests have other differences causing them to still fail. I'll work on these separately: https://github.com/mapbox/mapbox-gl-native/issues/3764 https://github.com/mapbox/mapbox-gl-native/issues/3765

[core] support tiles with non-4096 extents

---

include/mbgl/util/geo.hpp
platform/android/src/jni.cpp
platform/darwin/MGLGeometry_Private.h
platform/darwin/MGLMultiPoint.mm
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm
src/mbgl/annotation/point_annotation_impl.hpp
src/mbgl/map/map.cpp
test/map/transform.cpp
test/util/geo.cpp

Replace:
* `LatLngBounds()` (constructor)
* `LatLngBounds::getExtendable()` (static)
* `LatLngBounds(sw, ne)` (constructor)
With:
* `LatLngBounds::world()` (static)
* `LatLngBounds::empty()` (static)
* `LatLngBounds::fromCorners(a, b)` (static, swaps coordinates as necessary)

Improve LatLngBounds

---

include/mbgl/util/geo.hpp
test/map/transform.cpp

Implicit bool conversions are bad; they'll be used e.g. for a == b and a != b if those operators are not defined. This was happening at https://github.com/mapbox/mapbox-gl-native/blob/032c8fba3c8e3c122dd399b5c9341d92ad9d286f/src/mbgl/map/transform.cpp#L132-L132, for example.

[core] Make bool conversions explicit

---

platform/ios/src/MGLMapView.mm

Turn the Shows User Location inspectable into a no-op when running in the designables agent. Otherwise, we complain that the agent lacks Location Services permissions:
```
file:///path/to/TestApplication/TestApplication/Storyboard.storyboard: warning: IB Designables: Ignoring user defined runtime attribute for key path "showsUserLocation" on instance of "TestApplication.MapView". Hit an exception when attempting to set its value: In iOS 8 and above, this app must have a value for NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription in its Info.plist.
```

Fix designable warning when showing user location

---

include/mbgl/util/constants.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
src/mbgl/map/transform_state.cpp
src/mbgl/util/constants.cpp

Min / Max Zoom Level Clamping In Core and Android

---

platform/node/src/node_map.cpp

Creating a `v8::Function` with `Nan::GetFunction(Nan::New<v8::FunctionTemplate>)` can leak, use `Nan::New<v8::Function>` instead.
https://code.google.com/p/chromium/issues/detail?id=272579

patch memory leak in NodeMap::request

---

platform/node/src/node_map.cpp
platform/node/test/render.test.js
src/mbgl/renderer/painter_debug.cpp
src/mbgl/renderer/painter_symbol.cpp

fix #3579 
:eyes: @jfirebaugh @mikemorris

[node] add debug options to node bindings

---

CHANGELOG.md
platform/ios/src/MGLAccountManager.m

These categories need to be loaded explicitly so that they’re linked into the application binary. In the dynamic framework, they’re loaded inside the `InitializeMapbox()` framework initializer; for static frameworks, we recommend setting the `-ObjC` flag. Fabric uses the static framework without setting the `-ObjC` flag, so these redundant calls are needed. In principle, `InitializeMapbox()` could be folded into the static framework too, obviating this code. That’ll have to happen in an upcoming release when we can get enough testing.
/ref #3183 #2966 #3113
/cc @friedbunny @boundsj

Load categories in MGLAccountManager for Fabric

---

package.json
src/mbgl/text/get_anchors.cpp

-js: https://github.com/mapbox/mapbox-gl-js/pull/2077/files
This skips anchors if there is not enough room before the end of the line for the icon to fit.
Previously it allowed icons that extended past the end of a line as long as the icon's anchor fit on the line. This changes it so that the icon itself has to fit on the line. With these changes there are no icons on really short lines and no icons right at the end of lines.
The test suite changes (mapbox/mapbox-gl-test-suite@6b6a03e) make it look like this is a huge change, but in actual maps it only drops a small number of icons that are right at the ends of lines or are on really short lines.

[core] make sure icons fit before the ends of the line

---

CHANGELOG.md
ios/framework/framework-ios.gypi

Fixes #3870.
/cc @boundsj @friedbunny @parrots

Set dynamic framework minimum deployment target to iOS 8.0

---

CHANGELOG.md
platform/ios/src/MGLMapView.mm

#3322 #3456 replaced SMCalloutViewDelegate conformance with MGLCalloutViewDelegate conformance. Unfortunately, the two protocols differ in some symbols. This change restores SMCalloutViewDelegate methods alongside MGLCalloutViewDelegate methods.
Fixes #3871.
/cc @friedbunny @picciano

Conform to SMCalloutViewDelegate

---

include/mbgl/platform/default/glfw_view.hpp
platform/default/glfw_view.cpp
src/mbgl/map/source.cpp
src/mbgl/map/source.hpp
src/mbgl/map/tile_id.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_clipping.cpp
src/mbgl/util/clip_id.cpp
src/mbgl/util/clip_id.hpp
test/util/clip_ids.cpp

We're currently not painting clipping masks correctly in a few circumstances:
- Tiles are still being loaded
- Multiple sources use the same tile IDs

Fix clipping mask rendering

---

CHANGELOG.md
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm

Handle the case where the currently selected annotation isn’t one of the nearby annotations. This issue hasn’t come up before in the OS X SDK, from which this code was ported, because clicking an annotation while another annotation is selected only dismisses the callout popover.
Fixes #3284.
/cc @RomainQuidet @maciekish @Zakay

Fix crash reselecting annotation

---

src/mbgl/util/get_geometries.cpp

[core] round() not always on std:: namespace

---

CHANGELOG.md
include/mbgl/map/map.hpp
include/mbgl/map/mode.hpp
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp

Introduced a setter/getter for constrain mode. On iOS and OS X, the zoom level inspectable causes the zoom level to be set independently from the longitude and latitude. Thus, the latitude inspectable had no effect because the latitude was constrained to 0 at z0. Temporarily removing the heightwise constraint allows the map to center on the intended location before zooming, which is the usual case for storyboards and XIBs. On iOS, the only guarantee we have timing-wise is that all the inspectables are applied after initialization but before the view is added to a window. So we reimpose the heightwise constraint as soon as the view is added to a window, that is, before the user has a chance to pan the map out of bounds.
Fixes #3868.
/cc @friedbunny @brunoabinader @tmcw

Only constrain after adding to a window

---

CHANGELOG.md
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm

After filtering out elements of a vector using `std::remove_if()`, it’s apparently necessary to resize the vector. Otherwise, removing only has the effect of shifting the non-matching items to the end of the vector. This change reduces the annotation tap target back to almost what it was before #3261, except that these days the target is centered around the annotation image rather than the center point. There remains a much smaller slop area around the annotation, but nothing close to the effective padding before this change.
Fixes #3880.
/cc @jfirebaugh @BFTE

Exclude misses from nearby annotations

---

include/mbgl/storage/resource.hpp
platform/default/mbgl/storage/offline_database.cpp
platform/default/online_file_source.cpp
src/mbgl/annotation/annotation_tile.cpp
src/mbgl/renderer/debug_bucket.cpp

Xcode 7.3 errors hard on C++ misuse, in particular when using `std::move()` prevents copy elision.

Fix Xcode 7.3 error

---

platform/default/mbgl/storage/offline_download.cpp
src/mbgl/map/source.cpp
src/mbgl/style/style_parser.cpp
src/mbgl/style/style_parser.hpp
src/mbgl/util/mapbox.cpp
src/mbgl/util/mapbox.hpp
test/style/style_parser.cpp
test/util/mapbox.cpp

Native port of https://github.com/mapbox/mapbox-gl-js/pull/2044.
cc @jfirebaugh @kkaefer @brunoabinader

Add custom @2x handling for mapbox v4 tile API when tileSize: 512

---

ios/docs/doc-README.md
ios/docs/pod-README.md

We use absolute links to `master` in our docs, so #3913 affects our v3.1.1 release.
This will need to be merged back to `master`.
/cc @1ec5

[ios] Fix screenshot link in generated docs

---

platform/ios/scripts/package.sh

Distinguish between Apple Generic Versioning and Semantic Versioning in Info.plist. Also fill in the build number in the dynamic framework, where it was missing.
Fixes #3911.
/cc @friedbunny @bsudekum @picciano

Distinguish between AGV and semver

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UserLocationView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/ViewSettings.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/DoubleMapActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapPaddingActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MyLocationTrackingModeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_map_padding.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_map_padding.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_drawer.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_padding.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/dimens.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

3761 add map padding

---

platform/darwin/include/MGLGeometry.h

4-space indentation was being intepreted as a Markdown code block

Fix coordinate bounds documentation.

---

platform/ios/src/MGLMapboxEvents.m

This change adds logic to push a turnstile event whenever a map view
event is queued. It guards against sending the turnstile event more
than once per session.
Note that `pushTurnstileEvent` is actually a "force push" in that it
flushes the queue and, since it enqueues a turnstile event, the
flush's call to `postEvents` will attempt to send any queued events
even if telemetry is paused. This has the side effect of defeating
the other queue / timing / flush logic in place whenever map load
(and now implicitly turnstile) events are pushed.
This change does take care to continue to ensure that, in `pushEvent` even if the 
events instance is paused, the turnstile event is still pushed. 
This change drops the use of the priority background queue that used
to be used to dispatch async …

[iOS] Generate and send a turnstile event when map view event is queued

---

platform/default/online_file_source.cpp

Hit this one today testing  a3f8710574fe1a0c on Linux.
Can be reproduced by maximizing the window and full tilt (i.e. load as many tiles as possibles). After that, rotate the map as fast as possible.
```
#0  0x00007fd2daeac3f6 in std::string::assign(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000000000054ec8b in std::string::operator= (__str=..., this=<optimized out>) at /usr/include/c++/5/bits/basic_string.h:2951
#2  std::experimental::fundamentals_v1::_Optional_base<std::string, true>::operator= (__other=..., this=0x7fd2c08e0388)
at /usr/include/c++/5/experimental/optional:256
#3  std::experimental::fundamentals_v1::optional<std::string>::operator= (this=0x7fd2c08e0388)
at /usr/include/c++/5/experimental/optional:477
#4 …
```

[core] Crash on the OnlineFileSource

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

[android] #2816 - make save instance state robuster

---

.gitignore
Makefile
gyp/common.gypi
platform/linux/mapboxgl-app.gypi
scripts/collect-coverage.sh
scripts/main.mk
test/test.gypi

This PR:
- Instruments `Debug` target with coverage data (supported by GCC and clang)
- Adds a new build target `check` that collects unit tests coverage data and reports it in HTML
Fixes #3973.
/cc @tmpsantos @zugaldia @1ec5 @jfirebaugh @kkaefer

Generate unit tests coverage report via lcov

---

ios/docs/pod-README.md
ios/framework/Mapbox-static.h
platform/ios/INSTALL.md
platform/ios/scripts/package.sh

This change corrects a regression introduced in #3183, when the umbrella header used in version 3.0.1 was removed. The umbrella header inside the static framework now imports the required iOS SDK frameworks. With this change, it’s no longer necessary to manually link any frameworks other than Mapbox.framework.

Import required frameworks with static framework umbrella

---

CHANGELOG.md
platform/ios/include/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/osx/app/MainMenu.xib
platform/osx/app/MapDocument.m
platform/osx/include/MGLMapViewDelegate.h
platform/osx/src/MGLMapView.mm

**iOS**
- Set the poly annotation stroke and fill color to the map view's tint color
**OS X**
- Set the poly annotation stroke and fill color to the system menu item selection color
- Add polygon and polyline examples
Fixes #3927.
/cc @1ec5

Set default polyline and polygon color to match app

---

platform/default/async_task.cpp
platform/default/run_loop.cpp
platform/default/timer.cpp
platform/node/src/node_map.cpp
platform/node/src/node_map.hpp
platform/node/src/node_mapbox_gl_native.cpp
platform/node/src/node_mapbox_gl_native.hpp
platform/node/test/js/map.test.js

The run loop will be kept alive because it has an `AsyncTask`. We also can simple stop the loop with `uv_stop()`.
The `RunLoop` is still gonna be the last object to be destroyed because it is the first object to be created in the thread, so by design it won't outlive `Timer`s and `AsyncTask`s.
This patch won't change the current behavior, will just make the code simpler.

[core] libuv unref() not really needed

---

test/storage/http_retry_network_status.cpp

The loop will be alive until `.stop()` is called.

[tests] Timer is not needed to keep the main loop alive

---

CHANGELOG.md
platform/ios/src/MGLMapView.mm

The map feedback tool uses mapbox.js, so its zoom levels are one off the zoom levels used by Mapbox GL.
/ref #3427

Fix off-by-one zoom level for map feedback tool

---

platform/android/src/http_request_android.cpp
test/storage/http_reading.cpp
test/storage/server.js

We assume `response->data` an empty string instead of a null pointer.

Fix crash when we get a HTTP 200 with no data

---

src/mbgl/layer/background_layer.hpp
src/mbgl/layer/circle_layer.hpp
src/mbgl/layer/custom_layer.cpp
src/mbgl/layer/custom_layer.hpp
src/mbgl/layer/fill_layer.hpp
src/mbgl/layer/line_layer.hpp
src/mbgl/layer/raster_layer.hpp
src/mbgl/layer/symbol_layer.hpp
src/mbgl/style/style_layer.hpp

Since https://github.com/mapbox/mapbox-gl-native/commit/e04c5f650648d150e78da3602745b6190ec4aee3, we're using `dynamic_cast`s in a few areas, in particular the `SymbolLayer`. However, these are very slow, especially on iOS, eating up to 10% of our render time for Mapbox Streets. I think we should go back to storing an explicit enum.

Remove dynamic_casts

---

src/mbgl/util/clip_id.cpp

The TestApp's MainActivity has a worldview map. I'm observing the following crash when trying to pan out of bounds (this is is not limited to zoom 0):
```
MainActivity  V  OnCameraChange : Target: LatLng [longitude=0.0, latitude=0.0, altitude=0.0], Zoom:0.23601419, Bearing:-0.0, Tilt:0.0
V  OnCameraChange : Target: LatLng [longitude=5.880087093857298, latitude=0.0, altitude=0.0], Zoom:0.23601419, Bearing:-0.0, Tilt:0.0
V  OnCameraChange : Target: LatLng [longitude=0.41373897776685453, latitude=-13.008171512779839, altitude=0.0], Zoom:0.7938645, Bearing:-1.877268, Tilt:0.0
V  OnCameraChange : Target: LatLng [longitude=-3.581132412219887, latitude=-20.04411920307053, altitude=0.0], Zoom:1.4993753, Bearing:5.9545517, Tilt:0.0
V  OnCameraChange : Target: LatLng [longitude=-5.488161476830584, …
```

TestApp crashes when trying to pan out of bounds

---

include/mbgl/util/constants.hpp
platform/default/online_file_source.cpp
src/mbgl/util/constants.cpp
test/storage/http_expires.cpp
test/storage/server.js
test/test.gypi

The `OnlineFileSource` should treat a HTTP reply with expiration time already expired as an error and apply the same delay rules for retrying that we have in place for other errors, otherwise a faulty server can trigger an endless number of consecutive requests.

[core] HTTP replies with expiration time already expired should be treated as errors

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionDefinition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionError.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionMetadata.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionStatus.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineTilePyramidRegionDefinition.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/OfflineActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/offline/DownloadRegionDialog.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/offline/ListRegionsDialog.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_airplanemode_active_black_24dp.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_offline.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_drawer.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/dimens.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/src/jni.cpp
platform/android/src/jni.hpp

[android] - Implements Android bindings for offline API

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionMetadata.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/OfflineActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/offline/CustomMetadata.java

[android] Use the new camera api instead of hardcoded values

---

gyp/platform-ios.gypi
platform/ios/src/MGLLocationManager.h
platform/ios/src/MGLLocationManager.m
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapboxEvents.h
platform/ios/src/MGLMapboxEvents.m

When Mapbox telemetry is used in a host application that has background.location permissions AND `always` permissions granted by the user, the location manager utility will attempt to gather anonymous location data in the background to [improve map quality](https://www.mapbox.com/telemetry). Previously, the Mapbox SDK did little to optimize background data collection for the case of stationary devices. Running location services in the background, even in a passive way, consumes resources and contributes to battery drain and background activity time of the host application in the iOS battery report.
This change makes background data gathering more efficient by disabling standard location updates when the device has been stationary for at least five minutes. It also establishes region …

Introduce Location Manager Utility and Optimize Background Telemetry

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java

[android] #4157 - handle null icon when using parceable on MarkerOptions

---

bin/offline.cpp
bin/offline.gypi

The defaults remains the same: Bay area at zoom 15.
The key, if not supplied, is taken from the environment.
```
Allowed options:
-s [ --style ] URL                    Map stylesheet
--north degrees (=37.200000000000003) North latitude
--west degrees (=-122.8)              West longitude
--south degrees (=38.100000000000001) South latitude
--east degrees (=-121.7)              East longitude
--minZoom number (=0)                 Min zoom level
--maxZoom number (=15)                Max zoom level
--pixelRatio number (=1)              Pixel ratio
-t [ --token ] key                    Mapbox access token
-o [ --output ] file (=offline.db)    Output database file name
```

[offline] Accept parameters

---

include/mbgl/util/geo.hpp

Reverting https://github.com/mapbox/mapbox-gl-native/pull/3873 seems to fix the issue.
Testing on a Linux x86_64.

[core] Map flashing to clear color when interacting

---

src/mbgl/map/map_context.cpp
src/mbgl/style/style.cpp

In the `linuxapp`, press "R" to toggle night styles and observe how `Style::cascade` gets called ceaselessly.

Adding a class adds an infinite cascade loop

---

src/mbgl/map/map_context.cpp

Hardware without VAO support was being forced through the immediate mode render path on frames where label collision attempted to swap resources. Moving resource cleanup to the end of the frame appears to alleviate the issue. Here are some instruments traces I took that show cpu performance before and after the fix. If you want to see the results for yourself, my fork has a branch called `immediateModeReproCase` that will disable VAOs and force the glfw map to spin continuously. without the fix, framerate suffers greatly.
[immediateModeTraces.zip](https://github.com/mapbox/mapbox-gl-native/files/159220/immediateModeTraces.zip)
It's possible that there is an issue still hiding somewhere in our resource management code, but there shouldn't be any harm in moving resource cleanup to the end …

Fix for label collision forcing immediate mode rendering on some hardware.

---

bin/offline.cpp
platform/default/mbgl/storage/offline_database.cpp
platform/default/mbgl/storage/offline_database.hpp
platform/default/mbgl/storage/offline_download.cpp
test/storage/offline_download.cpp

We can't use `offlineDatabase.getRegionCompletedStatus(id)` at the beginning of the offline download to calculate starting values for `completedResourceCount` and `completedResourceSize`, because it doesn't account for tiles that might already exist in the database. We don't know which tiles are required until we've parsed the style and looked at the sources.
Instead, update `completedResourceCount` and `completedResourceSize` incrementally as we encounter resources that turn out to be in the database already.
Fixes #4147

Fix offline status reporting with pre-existing tiles

---

platform/android/src/jni.cpp

A typical log is like the following:
```
art  F  art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: use of deleted global reference 0x1005b6
F  art/runtime/java_vm_ext.cc:410] "Offline Thread" prio=5 tid=33 Runnable
F  art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x13261b80 self=0xd7837900
F  art/runtime/java_vm_ext.cc:410]   | sysTid=10721 nice=0 cgrp=default sched=0/0 handle=0xdbcfa930
F  art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 208107565 6797710 101 ) utm=8 stm=12 core=4 HZ=100
F  art/runtime/java_vm_ext.cc:410]   | stack=0xdbbfe000-0xdbc00000 stackSize=1014KB
F  art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
F  art/runtime/java_vm_ext.cc:410]   native: #00 pc 0035a55f  /system/lib/libart.so …
```

Deleting the global ref of the observerCallback in JNI makes the offline activity to crash

---

platform/ios/src/MGLAPIClient.m

This change replaces `MGLAPIClientDomain` with `MGLErrorDomain`, for consistency with errors raised elsewhere in the SDK. `NSLocalizedString()` calls were also moved, because once we tackle localization (#949), we would only localize the format strings, not every possible expanded string.
/cc @boundsj

Minor MGLAPIClient cleanup

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/src/http_request_android.cpp

Map is being displayed in a dialog. MapBox crashes when map is displayed in black and no tiles.
> 	03-03 13:03:56.492 E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb9c49b90
> 	03-03 13:03:56.521 E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb9776348
> 	03-03 13:03:56.522 D/OpenGLRenderer: endAllActiveAnimators on 0xb9c2d428 (RippleDrawable) with handle 0xb958b570
> 	03-03 13:03:56.593 I/mbgl: {Map}[Android]: Not activating as we are not ready
> 	03-03 13:03:56.596 E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
> 	03-03 13:03:56.607 I/mbgl: {Map}[Android]: Not deactivating as we are not ready
> 	03-03 13:03:56.658 W/com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest: [HTTP] Request could not be executed: Socket closed
> 	03-03 13:03:56.666 …

(Android) Crash when try to close map when it is displayed in black and no tiles

---

platform/android/src/native_map_view.cpp

[android] #2995 - test workaround for device not sharing context

---

src/mbgl/layer/line_layer.cpp
src/mbgl/layer/symbol_layer.cpp
src/mbgl/map/tile_id.hpp
src/mbgl/renderer/line_bucket.cpp
src/mbgl/renderer/line_bucket.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/renderer/symbol_bucket.hpp

We don't actually need it because it can be cancelled out.

Cancel out TileID::overscaling() in most places

---

platform/default/run_loop.cpp
test/util/run_loop.cpp

If you call `RunLoop::run()` twice, the second call is equivalent to `RunLoop::runOnce()`: it only runs the loop once. The expected behavior is that the loop runs until `RunLoop::stop()` is called again.
The reason is that `holderHandle` isn't re-`uv_ref`ed. It should be, every time `RunLoop::run()` is called.

Calling RunLoop::run() a second time doesn't work as expected

---

platform/default/mbgl/storage/offline_download.cpp
platform/default/mbgl/storage/offline_download.hpp
test/storage/offline_download.cpp

The core of the change is ensuring that ensureResource doesn't [release Zalgo](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony): it should be consistently async, rather than async in the case that the resource doesn't exist in the database, but sync if it does.
This ensures that status is reported in a more consistent sequence, regardless of the database state.
Fixes #4245 and should help with #4229.

[core] Fix offline status reporting regressions

---

Makefile
platform/ios/framework/Mapbox-static.h
platform/ios/scripts/package.sh
platform/ios/src/MGLAPIClient.m
platform/ios/src/MGLAccountManager.m
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapboxEvents.m
platform/ios/src/NSBundle+MGLAdditions.h
platform/ios/src/NSBundle+MGLAdditions.m
platform/osx/src/MGLMapView.mm

Added a new `ifabric` make target for packaging up a static framework similar to the one released as 3.0.1. Place artwork and certificate assets inside Mapbox.bundle inside Mapbox.framework. Link SystemConfiguration in the umbrella header.
Distinguish between the framework bundle and the resources bundle. For the dynamic frameworks and embedded static frameworks, the two are the same; for the non-embedded static framework, the latter resides inside the former.
FABKit integration would be a lot less manual if we could rely on build settings (perhaps via an .xcconfig file) to define the bundle identifier and display version string in MGLAccountManager. Unfortunately, our use of gyp keeps those settings from making it through to the Objective-C code. This will get a lot better once we fix …

Non-embedded static framework for iOS SDK

---

CHANGELOG.md
include/mbgl/annotation/point_annotation.hpp
include/mbgl/annotation/shape_annotation.hpp
include/mbgl/util/geo.hpp
include/mbgl/util/vec.hpp
src/mbgl/annotation/point_annotation_impl.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp
src/mbgl/util/tile_cover.cpp
test/map/transform.cpp
test/util/geo.cpp

When panning the map jumps from on location to another.
I'm guessing it's something related to the dateline.
You can see the bug in action [here](https://youtu.be/t3FsKKc5meY)

Map jumps from one position to another

---

platform/darwin/include/MGLGeometry.h
platform/darwin/src/MGLMapCamera.mm
platform/darwin/src/MGLMultiPoint.mm
platform/darwin/src/MGLPointAnnotation.m
platform/ios/src/MGLUserLocation.m

Adds description strings to:
- `MGLPointAnnotation`
- `MGLMultiPoint` (includes `MGLPolygon` & `MGLPolyline`)
- `MGLUserLocation`
This enables better debugging at break points:
```
(lldb) po mapView.annotations
<__NSArrayI 0x1517ae0a0>(
<MGLPolygon: 0x1517e5470; count = 3; bounds.ne = 46.000000, -121.000000; bounds.sw = 44.000000, -122.000000>,
<MGLPolyline: 0x1533c4cb0; count = 2834; bounds.ne = 48.680179, -122.846243; bounds.sw = 48.655880, -122.858304>,
<MGLPolygon: 0x153530080; count = 65; bounds.ne = 39.834352, -74.976614; bounds.sw = 38.448923, -75.802605>,
<MGLPolygon: 0x153530150; count = 150; bounds.ne = 42.519158, -74.689313; bounds.sw = 39.722485, -80.507165>,
<MGLPolygon: 0x1535303f0; count = 177; bounds.ne = 41.357463, -73.899234; bounds.sw = 38.784524, -75.551217>, …
```

[ios] Add description strings to constituent classes

---

src/mbgl/map/transform.cpp
test/map/transform.cpp

This reverts a line change from b33b2f15, because we explicitely want
the anchor to be invalid. You were right, @1ec5, when addressing this in https://github.com/mapbox/mapbox-gl-native/pull/4214/files#r55699097 :+1:
/cc @1ec5 @kkaefer

[core] Fix non-anchored Transform::setAngle

---

platform/default/mbgl/storage/offline_download.cpp
test/storage/offline_download.cpp

I think it’s reasonable for the SDKs to expect that the `mbgl::OfflineRegion` will automatically deactivate when complete.
/cc @jfirebaugh @bleege @boundsj

Deactivate offline region upon completion

---

include/mbgl/map/map.hpp
include/mbgl/util/geo.hpp
platform/default/glfw_view.cpp
platform/ios/src/MGLMapView.mm
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
test/map/transform.cpp

Enforce invalid anchors via `ScreenCoordinate::null()` when neeeded, backed up by unit tests. This patch reverts some more changes from b33b2f15 related to the default value for Transform functions. As pointed out by Minh, we use invalid screen coordinates to tell the affected transform functions to use the origin instead.
/cc @1ec5 @kkaefer

[core] Harden Transform anchor & padding usage

---

platform/darwin/src/MGLOfflinePack.mm

Due to ARC, MGLOfflinePack can be deallocated at any time following its initialization. `-dealloc` ensures that the offline region observer is unset, but that step is asynchronous; there is no guarantee that it completes before the first status change update. In fact, the pack is deallocated before the first status change update unless it is captured outside of the MGLOfflinePackAdditionCompletionHandler. The pack nil check is unnecessary because the subsequent code would be a no-op.
This is an alternative fix for #4287.
/cc @jfirebaugh @boundsj @bsudekum

Remove extraneous nil check from MGLOfflineRegionObserver

---

platform/darwin/include/MGLOfflineStorage.h
platform/ios/app/MBXOfflinePacksTableViewController.m

Remove all references to an offline pack before the call to `-[MGLOfflineStorage removePackWithCompletionHander:]`. Allow null completion handlers in MGLOfflineStorage APIs.
Fixes #4286.
/cc @boundsj

Fix crash removing offline pack while another pack is downloading

---

platform/ios/scripts/package.sh

#4104 deleted redundant .der files from the iOS resources directory, exposing a bug in which we failed to copy the shared resources directory into the static framework bundle.
Fixes #4316.
/cc @RomainQuidet

Copy .der files into static framework

---

include/mbgl/util/constants.hpp
src/mbgl/util/constants.cpp

We're currently declaring all of our constants in `constants.hpp` as `extern` and actually initialize them in the corresponding C++ file. Instead, we should declare them as constexpr and assign the value in the header file directly. The fact that they are defined elsewhere is an old debugging construct that allowed me to quickly change tile sizes without recompilation.

Make constants constexpr

---

Makefile

[android] Build ARMv8 on the `apackage` target

---

platform/ios/src/MGLAPIClient.m

Although often recommended, CFBundleName is not guaranteed to exist in an app's configuration. As an identifier of telemetry data, even when it is present it can be inconsistent because of localization.
CFBundleIdentifier, although possibly longer, will be consistent across locales and for the lifetime of an app in the App Store even if the app name changes in any locale.
cc @1ec5 @mick @camilleanne

[iOS] Use CFBundleIdentifier instead of CFBundleName in UA string

---

include/mbgl/util/math.hpp
include/mbgl/util/projection.hpp
src/mbgl/annotation/shape_annotation_impl.cpp
src/mbgl/map/transform.cpp
src/mbgl/util/geo.cpp
test/test.gypi
test/util/math.cpp

Tighten `min`, `max` and `clamp` functions to check for NaNs using stdlib min/max. Also switched redefinitions of min/max with a variadic template for each.
/cc @kkaefer @1ec5

[core] Check for NaNs in mbgl::util::{min,max,clamp}

---

CHANGELOG.md
platform/darwin/src/MGLOfflineStorage.mm
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm

Now there’s only one instance of `mbgl::OfflineFileSource`, created when the shared MGLOfflineStorage object is initialized. Also create and use the shared MGLOfflineStorage object when initializing an MGLMapView object.
The unified cache file is located in a subdirectory of Application Support, where the SDK has control over the file’s lifetime. The subdirectory is already named after the host application’s bundle identifier, ensuring that each Mapbox-powered application has an independent tile limit.
If there’s an ambient cache in a subdirectory of Caches, delete it. If there’s an offline cache in a subdirectory of Documents on iOS or Caches on OS X, move it to the unified cache location in a subdirectory of Application Support.
There are a couple consequences to this approach:
1. On …

Unify offline and ambient caches

---

platform/osx/src/MGLMapView.mm

Pan translations are broken for any MGLMapView with a non-zero frame origin. Fix this by using the 'nil' view when resetting the pan gesture recognizer translation.
To test this bug, set the leading-edge constraint of the map view in the test application to any non-zero value and try to pan the map.

Reset the translation to zero without adjusting for view

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/src/native_map_view.cpp

Per #4362, we're now unifying the ambient and the offline databases in one location. This PR:
1. Moves them both to a permanent storage folder.
2. Deletes any previous ambient database file.
/cc: @jfirebaugh @1ec5

[android] Unify cache and offline databases

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java

It's safe to call this method several times, [according to the documentation](http://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#loadLibrary%28java.lang.String%29) if this method is called more than once with the same library name, the second and subsequent calls are ignored.
Fixes #4175
/cc: @jfirebaugh

[android] Make sure we always load mapbox-gl when a native method is invoked

---

platform/default/default_file_source.cpp

No progress events should be processed after deleting a region.
Fixes #4403
@friedbunny Can you test against Sirius? This is timing dependent and difficult to write an automated test for.

[core] Stop any OfflineDownload before deleting a region

---

platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapboxEvents.m

Previously, the post of the turnstile event was a side effect of the
map.load event and would happen when the host app was started from a
terminated state at the first initialization of MGLMapView. The
turnstile event post was guarded with dispatch_once so that it would
only ever be sent once during the lifecycle of the application after
it started from the terminated state.
This changes that behavior by:
- Allowing a new turnstile event to be posted as much as once per
day
- Only triggering a map.view event when a map is initialized if the map
is loaded outside of the 'background' application state
- Sending a map.view event whenever a MGLMapView is instantiated
and the application did become active or enters foreground
iOS turnstile event sending behavior is now:
- A map.view event is …

[iOS] Send turnstile event as much as once per day

---

CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
src/mbgl/util/constants.cpp

Numbers greater than 21 trigger various bugs: #4416, #4272, #4168.

[all] Set maximum maxZoom to 21

---

src/mbgl/renderer/symbol_bucket.cpp

fix #4131 
When the map is rotated and symbol buffers are recalculated we don't reset `uploaded` so the buffers don't get uploaded during the upload pass. This fixes that by resetting `uploaded`.

upload new symbol buffers in upload pass

---

platform/ios/app/MBXViewController.mm

It uses the title, but not the style URL from `default_styles.hpp`

First style in iOS app is hard-coded to streets

---

CHANGELOG.md
platform/ios/src/MGLMapView.mm

The gesture recognizer only reports the gesture’s current center point, so use the previous center point to anchor the transition.
Fixes #4315.
/cc @mourner @friedbunny

Fix up center coordinate after lopsided pinch gesture

---

test/test.gypi

`make iproj` was producing a project with a broken `$()../test` folder containing a missing `fixtures` item. 
@kkaefer The "gyp doesn't prepend $(SRCROOT)” hack you mention doesn’t appear to be necessary — at least not on my system, running Xcode 7.3.
Refs https://github.com/mapbox/mapbox-gl-native/commit/c587eefbb1290cc01e3e14a0ae18a2d316a498fd#diff-6df1c496c702460f8a63d53bce86b8c7R139

Place unit test fixtures in correct place when creating iOS project

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/TelemetryService.java

If the receiver was already unregistered or was not registered, then call to unregisterReceiver throws IllegalArgumentException. In your case you need to just put special try/catch for this exception and ignore it.

TelemetryService: Catch IllegalArgumentException exception when unregisterReceiver

---

src/mbgl/map/map_context.cpp
src/mbgl/renderer/frame_history.cpp
src/mbgl/renderer/frame_history.hpp

Previous behavior prevented view from notifying when map was fully loaded, because the style sources relies on a future time point for checking if their tiles are updated. This was first caught only in still mode, but also happens in continuous mode for platforms that rely on `View::notifyMapChange` for updating the view.
Fixes #4439.
/cc @tobrun @jfirebaugh

[core] Update time point in map context on every update

---

platform/darwin/include/MGLTypes.h

This change fixes the build in Xcode 6.4.
/ref https://github.com/mapbox/mapbox-gl-native/pull/4455#issuecomment-200992226
/cc @boundsj

Stub out C nullability block type qualifiers for Xcode 6.4

---

platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm

The release-ios-3.2.0-android-4.0.0 branch includes #4275 but not #4285, meaning that `-[MGLMapView convertPoint:toCoordinateFromView:]` and dependent methods return latitudes that aren’t wrapped to ±180°. This change restores the wrapping on an interim basis.
@jfirebaugh has made the point that this method shouldn’t wrap anyways, but we don’t want to bump the major version number so close to a release. Although the wrapping isn’t documented anywhere, it’s consistent with MapKit, and it’s very likely that developers have come to rely on this behavior (as has iosapp). We can revisit unwrapping in a future release.
If a developer needs an unwrapped coordinate, they can detect this edge case by comparing the return values of `-[MGLMapView convertPoint:toCoordinateFromView:]` for two …

Wrap coordinates converted from points

---

Makefile
platform/ios/CHANGELOG.md
platform/ios/INSTALL.md
platform/ios/scripts/package.sh

Add a flavor of static build that:
- Puts resources in a Mapbox.bundle file
- Puts Mapbox.bundle and Settings.bundle at the same level as Mapbox.framework in the /static output folder
- Removes CFBundleExecutable and CFBundlePackageType from the Info.plist in Mapbox.bundle that cause errors when uploading to iTunes Connect
This also updates the `binary` instructions in INSTALL.md to reflect these changes.
Fixes #4118
cc @1ec5

[ios Fix static lib issues for signed device builds and iTunes connect uploads

---

platform/darwin/src/MGLOfflineStorage.mm

Avoid backing up the offline cache onto iCloud, because it can be redownloaded and would easily take up a significant portion of a standard iCloud account. Ideally, we’d even put ambiently cached resources in Caches, so it can be reclaimed by the system when disk space runs low. But unfortunately it has to live in the same file as offline resources.

Exclude offline cache from backups

---

platform/ios/CHANGELOG.md
platform/ios/docs/pod-README.md

Update the pod-README so generated documentation is correct and make a note in the changelog
regarding the updated / reverted procedure for installing the SDK as a static framework.

[ios] Update the pod-README and changelog regarding static lib changes

---

.jazzy.yaml
platform/darwin/include/MGLOfflinePack.h
platform/darwin/include/MGLOfflineStorage.h
platform/darwin/include/MGLTilePyramidOfflineRegion.h
platform/darwin/src/MGLOfflinePack.mm
platform/darwin/src/MGLOfflinePack_Private.h
platform/darwin/src/MGLOfflineRegion_Private.h
platform/darwin/src/MGLOfflineStorage.mm
platform/darwin/src/MGLOfflineStorage_Private.h
platform/darwin/src/MGLTilePyramidOfflineRegion.mm
platform/ios/app/MBXOfflinePacksTableViewController.m
platform/osx/app/AppDelegate.h
platform/osx/app/AppDelegate.m
platform/osx/app/MainMenu.xib
platform/osx/app/MapDocument.m
platform/osx/app/OfflinePackNameValueTransformer.h
platform/osx/app/OfflinePackNameValueTransformer.m
platform/osx/app/mapboxgl-app.gypi
platform/osx/test/MGLOfflinePackTests.m
platform/osx/test/MGLOfflineRegionTests.m
platform/osx/test/MGLOfflineStorageTests.m
platform/osx/test/osxtest.gypi

MGLOfflineStorage now maintains a canonical, strongly held collection of all valid offline packs and issues notifications for progress updates. MGLOfflinePackDelegate is now private and serves only as a link between MGLOfflineStorage and its MGLOfflinePacks. Clients that want to receive progress updates should use NSNotificationCenter or [key-value observing](https://developer.apple.com/library/ios/documentation/General/Conceptual/DevPedia-CocoaCore/KVO.html) (KVO) instead of the delegate pattern. ~~Progress updates come automatically: it’s no longer necessary (or possible) to call `-requestProgress` on an offline pack.~~
Client code can react to the successful addition of an offline pack either via the completion block or via a KVO insertion notification. Client code can get a list of …

Centralize offline pack management with KVO compliance and tests

---

include/mbgl/map/map.hpp
src/mbgl/map/map.cpp
src/mbgl/map/map_context.cpp
src/mbgl/map/map_data.hpp

Fixes #4500 for iOS.
Only `Map` needs to track the loaded state, and it can simply be set when beginning to load a style and reset when finished.
The only commit related to `MapData::loading` that I could find was 2ee7b0218929d56c9331ded5ef695fc6bc59f70b. I thought I remembered some additional adjustments to how this variable was used based on past bugs, but could not find any. There is one branch that references it, [`tmpsantos-MapChangeDidFinishLoadingMap`](https://github.com/mapbox/mapbox-gl-native/tree/tmpsantos-MapChangeDidFinishLoadingMap), which looks to be obsolete. @tmpsantos do you remember what this was about? Is anyone else aware of subtleties relating to `MapData::loading` or `MapChangeDidFinishLoadingMap` that I forgot to take into account?
This provides an alternative fix …

[core] Localize and simplify state for MapChangeDidFinishLoadingMap event

---

src/mbgl/map/tile_id.cpp
src/mbgl/map/tile_id.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter_background.cpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/renderer/painter_symbol.cpp

fix #3768
:eyes: @jfirebaugh 
This is slightly different than the -js implementation. In -js `pixelsToTileUnits` its just a regular function. Here it's a method on TileID. I think this makes sense until we refactor TileID/TileCoord and get rid of the -js and -native differences.

[core] simplify conversions from pixels to tile units

---

src/mbgl/sprite/sprite_parser.cpp
test/sprite/sprite_parser.cpp

- check that sprite metrics are within the bounds of the sprite. fix #714
- make sprite metrics problems Errors instead of Warnings
- check for negative image width, height

[core] make sprite metrics checking stricter

---

ISSUE_TEMPLATE.md

Add an issue template that everyone will see when creating a new issue here on GitHub. (Pull requests will not see this template, that would need a separate file: `PULL_REQUEST_TEMPLATE.md`)
Cribbed from [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js/blob/7b61aa9888bd98c3b6be0a9150225a1871fdae31/ISSUE_TEMPLATE.md), per @ansis’s suggestion in #4542.
**Raw template:**
**Markdown preview:**
/cc @mapbox/gl

Add GitHub issue template!

---

platform/default/glfw_view.cpp

Steps to reproduce:
1. Run GLFW client `make run-linux`
2. Zoom out e.g. via mouse scroll
3. Press `3` to add some point annotations - usually these are randomly placed in both latitude and longitude, but they all appear at the horizontal edges of the screen (screenshot below):
This issue seems old (if not always present), as I bisected it up to 3 months old commits. I suspect the following:
- We're not properly clamping the scale/zoom value when issuing `scaleBy`; or
- There's a bug in `PointAnnotationImpl::updateLayer`; or
- `GLFWView::makeRandomPoint` is bogus for the following scenario.
/cc @mapbox/gl

[glfw] Annotations are misplaced when zooming out

---

platform/osx/scripts/osxsdk.xcscheme
platform/osx/scripts/test.sh

https://www.bitrise.io/build/70ff810c4e3cc5a9
```
* Recreating project...
mv: rename ./build/osx-x86_64/gyp/osx.xcodeproj/xcuserdata/vagrant.xcuserdatad/xcschemes/osxsdk.xcscheme to ./build/osx-x86_64/gyp/osx.xcodeproj/xcshareddata/xcschemes/osxsdk.xcscheme: No such file or directory
make: *** [xctest] Error 1
==> Script finished with exit code: 2
ERRO[11:14:20] Step (Run SDK unit tests) failed, error: (exit status 2) 
```

OS X CI flapping: osxsdk.xcscheme: No such file or directory

---

Makefile

Prevents the following error output on Linux:
```Makefile:73: *** recipe commences before first target.  Stop.```

[build] Apply Makefile changes for {ios,isim,ibench}

---

Makefile

Fixes https://github.com/mapbox/mapbox-gl-native/issues/4578#issuecomment-205555132

Xcode project for node.js bindings should always use loop=uv

---

platform/ios/app/MBXViewController.m
platform/ios/app/mapboxgl-app.gypi

Converted MBXViewController from Objective-C++ to Objective-C. In the process, the dependency on default_styles.hpp was replaced by a hardcoded list of style URLs along with runtime assertions that the list of styles is the right length.
/cc @friedbunny @boundsj

Convert iosapp to pure Objective-C

---

gyp/mbgl.gyp

This prevented `LOOP=uv make linux` from working in OS X.
/cc @tmpsantos @kkaefer

[build] Fix libuv usage in OS X

---

platform/ios/scripts/deploy-packages.sh

A large part of the iOS SDK deploy process is creating the various binary flavors, uploading them to s3, and then testing that those uploads worked by downloading them -- those binaries are used in the next step of the process when they are attached to the github release.
This script automates that build, upload, and download process and can be run after `mbx auth`.
If this is useful at all, it'll probably be less so after https://github.com/mapbox/mapbox-gl-native/issues/4196. However, I'm making the PR since it won't hurt and might be helpful in the meantime.

Add script to automate s3 build and publish process

---

platform/node/README.md

Removes broken `mapbox://` example from https://github.com/mapbox/mapbox-gl-native/issues/3862 and other minor cleanup.

[node] clean up README.md

---

package.json
platform/node/CHANGELOG.md

- Adds debug render options ([#3840](https://github.com/mapbox/mapbox-gl-native/pull/3840))
- Fixes circle bucket rendering on tile boundaries ([#3764](https://github.com/mapbox/mapbox-gl-native/issues/3764))
- Fixes a segfault caused by improperly disposing the entire module in the `NodeLog` destructor ([#4639](https://github.com/mapbox/mapbox-gl-native/pull/4639))
- Fixes an issue with vanishing GeoJSON layers at high zoom levels ([#4632](https://github.com/mapbox/mapbox-gl-native/issues/4632))
- Fixes inheritance from EventEmitter ([#4567](https://github.com/mapbox/mapbox-gl-native/pull/4576))
- Fixes intermittent `stencil mask overflow` error ([#962](https://github.com/mapbox/mapbox-gl-native/issues/962))
- Drops support for Node.js v5.x prebuilt binaries due to ongoing npm3 …

node-v3.1.0

---

Makefile

Typing `make xproj` on Mac OS X no longer rebuilds the actual Xcode project when something changed. We should add either PHONY flags or make the target depend on all underlying files.

Rebuild project when something changed

---

package.json

Refs https://github.com/npm/npm/issues/10634#issuecomment-161186413?

unbundle node-pre-gyp to work around bundledDependencies bug in npm2

---

INSTALL.md
Makefile
platform/ios/bitrise.yml
platform/ios/scripts/package.sh
platform/node/bitrise.yml
platform/osx/bitrise.yml
scripts/main.mk

Bring back xcpretty. We've encountered issues with it in the past, but I'm willing to go back to it because the alternative -- immensely verbose build logs in which it is virtually impossible to find error output -- is worse.

[ios, osx] The return of xcpretty, part II

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

User location heading updates would not automatically restart when an app became active again.
Fixes #4668. Thanks to @JThramer for reporting.
/cc @1ec5

[ios] Restart user location heading updates on validation

---

Makefile
mbgl.gypi

The iOS build is topping out our build times at 30+ minutes.
We should investigate how to bring this down to the range of other builds (10-15 minutes).
Here's one thing to try: https://labs.spotify.com/2013/11/04/shaving-off-time-from-the-ios-edit-build-test-cycle/

Speed up iOS CI build

---

platform/osx/app/MainMenu.xib
platform/osx/src/MGLMapView.mm

Added a hidden preference to MGLMapView that enables “unnatural zooming”, in which the scroll wheel zooms in and out, as in a Web browser, instead of scrolling the map, as is the platform convention on iOS and OS X.
Added a checkbox to osxapp’s preferences window that toggles this hidden preference via a binding. You can use this checkbox, or invoke `defaults write com.mapbox.MapboxGL MGLScrollWheelZoomsMapView -bool YES`, or pass `-MGLScrollWheelZoomsMapView YES` into osxapp as command line arguments.
Fixes #4670.
/cc @kkaefer

Scroll to zoom on OS X

---

src/mbgl/map/map.cpp

This used to be async assuming the libuv behavior of holding the main loop until all the messages are processed and also for avoiding a deadlock at exit that no longer exits.
Now that we support multiple main loops implementation on different platforms, we do the cleanup synchronously to make sure all the platforms have the same behavior at exit.
Fixes #4631

[core] Do the MapContext::cleanup() synchronously

---

platform/darwin/src/async_task.cpp
test/util/async_task.cpp

When signaling an `AsyncTask`, then destroying the task before it fired, the Darwin `RunLoop` implementation currently crashes.

Darwin RunLoop: abort signaled AsyncTasks

---

platform/ios/app/MBXViewController.m
platform/ios/app/app-info.plist
platform/ios/src/MGLAPIClient.m

- Previously looked in app's Info.plist, now looks at NSUserDefaults
- Deprecation should be unnecessary for this internal test setting
- ~~Harmonized name with other keys (added 'Mapbox’)~~ Key name is `MGLTelemetryTestServerURL`
/cc @boundsj @1ec5

[iOS] Convert telemetry test server setting to user default

---

platform/default/headless_view.cpp

Instead of calling resize, which would compare against the uninitialized dimensions values, initialize dimensions and needsResize directly.
Fixes #3883.

[test] Fix use of uninitialized `dimensions` value

---

include/mbgl/gl/gl.hpp
src/mbgl/gl/gl.cpp

This causes duplicate objects -- one for every file that includes that header.

[core] Don't put static objects in a header file

---

include/mbgl/gl/gl_values.hpp
src/mbgl/gl/gl_config.cpp
src/mbgl/gl/gl_config.hpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/renderer/painter_raster.cpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/renderer/raster_bucket.cpp
src/mbgl/shader/linepattern_shader.hpp

We're currently calling this function manually in some places, but we should move that value to `GLConfig` so that it can be reset properly if the need arises.

Store glActiveTexture in GLConfig

---

platform/ios/benchmark/MBXBenchViewController.mm

Adds total and average frames per second to the summarized console output from a run of the iOS Bench GL app.
Sample output from #4704, last two lines are new:
```
2016-04-14 18:43:02.102 Bench GL[640:263343] Result:
2016-04-14 18:43:02.102 Bench GL[640:263343] | paris      | 60.0 fps |
2016-04-14 18:43:02.103 Bench GL[640:263343] | paris2     | 59.9 fps |
2016-04-14 18:43:02.103 Bench GL[640:263343] | alps       | 53.1 fps |
2016-04-14 18:43:02.103 Bench GL[640:263343] | us east    | 60.3 fps |
2016-04-14 18:43:02.103 Bench GL[640:263343] | greater la | 60.1 fps |
2016-04-14 18:43:02.103 Bench GL[640:263343] | sf         | 59.9 fps |
2016-04-14 18:43:02.103 Bench GL[640:263343] | oakland    | 60.0 fps |
2016-04-14 18:43:02.103 Bench GL[640:263343] | germany    | 59.8 fps |
2016-04-14 …
```

Add total and avg FPS to final benchmark summary

---

src/mbgl/map/map.cpp
src/mbgl/map/transform.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp

Return a const ref instead. We use this mostly for:
```
return transform->getState().getMinZoom();
return transform->getState().getMaxZoom();
return transform->getState().getWidth();
return transform->getState().getHeight();
return transform->getState().latLngToPoint(latLng);
return transform->getState().pointToLatLng(pixel);
```
And when passing it on `::invoke()` it gets copied when packing the arguments.

[core] Do not make a copy of the TransformState all the time

---

platform/default/glfw_view.cpp

Based on https://github.com/mapbox/mapbox-gl-native/issues/4578#issuecomment-207586376 - this is a proposed workaround I've been using in OS X. 
Fixes #4578.
/cc @jfirebaugh @kkaefer

[glfw] Workaround for OS X

---

src/mbgl/source/source.cpp
src/mbgl/source/source.hpp

fix #4047
port https://github.com/mapbox/mapbox-gl-js/pull/2158
> When the required tiles aren't loaded yet it tries to find parent tiles that area loaded that a cover the area. It used to just look for parents in the set of previously rendered tiles. There are many cases where the parents aren't in that set but they are in the cache.
>
> This reduces the amount of the viewport not covered by tiles. It makes tile loading look a lot faster.
>
> It helps a lot when you:
>
> zoom in and the pan around
>zoom in quickly and then zoom out more slowly

[core] look for loaded parent tiles in cache

---

platform/darwin/include/MGLTypes.h
platform/darwin/test/MGLGeometryTests.mm
platform/darwin/test/MGLOfflinePackTests.m
platform/darwin/test/MGLOfflineRegionTests.m
platform/darwin/test/MGLOfflineStorageTests.m
platform/darwin/test/MGLStyleTests.mm
platform/ios/app/MBXViewController.m
platform/ios/src/MGLAPIClient.m
platform/ios/src/MGLMapboxEvents.m
platform/osx/src/MGLMapView.mm

Now that #4641 has removed the prohibition against C99 extensions, this change removes many pragma statements that suppress warnings about variadic macros and designated initializers. Designated initializers and Elvis operators have been introduced wherever appropriate.
/ref #4191

Take advantage of C99

---

platform/darwin/src/http_file_source.mm
platform/ios/CHANGELOG.md

The user agent string for all non-telemetry requests in the iOS and OS X SDKs now conforms to the following format:
```
MyApp/0.1.2 Mapbox/3.4.5 MapboxGL/6.7.8 (deadfeed) iOS Simulator/9.0.1 (x86_64)
^ app       ^ sdk        ^ core                    ^ os                 ^ arch
```
This file only links against the cross-platform CoreFoundation and Foundation frameworks, not the platform-specific AppKit or UIKit frameworks, so the options for identifying the operating system and device are fairly limited. (I didn’t want to go through [such](https://github.com/WebKit/webkit/blob/67985c34ffc405f69995e8a35f9c38618625c403/Source/WebCore/page/mac/UserAgentMac.mm) [great](https://github.com/WebKit/webkit/blob/0d5a0900084c2babb65ff85dedcb1a42d854f54c/Source/WebCore/page/ios/UserAgentIOS.mm#L71) …

Include application and operating system name and version in user agent string

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXCustomCalloutView.m
platform/ios/include/MGLCalloutView.h
platform/ios/src/MGLMapView.mm

Previously, the user dot would blit across the screen, and `MGLMapView` would try to keep up but would tragically remain one step behind. With this PR, the user and `MGLMapView` waltz happily together.
Depends on #3589. Fixes #1041. Ref #1125.

Animate the user dot

---

scripts/main.mk

There is an assumption that the certificate bundle is in the same path as the binary.

[build] Make `run-glfw-app` not working on Linux

---

scripts/main.mk

```
$ make android -j8
make -f scripts/main.mk PLATFORM=android SUBPLATFORM=arm-v7 Makefile/all
make[1]: Entering directory '/opt/tmpsantos/Projects/mapbox-gl-native'
make[1]: command: Command not found
```
Build continues normally after that but we are missing a step or calling something that we should not be calling. Also happens when building GLFW.

[build] `Command not found` when building on Linux

---

platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

Apparently some versions of Android, notable 4.4.4 running on my Nexus 5, creates a GLContext on the Android UIThread which is the one we are now using for rendering after #2909.
If the context is not restored, nothing gets rendered (or sometimes partially, or artifacts) because Android will try to do GL stuff on the context used by Mapbox GL and mess things up.

[android] Restore prior GLContext if exists

---

.gitignore
platform/ios/benchmark/MBXBenchViewController.mm
platform/ios/ios.xcodeproj/project.pbxproj

If you’ve gone through the trouble of running ios-bench’s download.sh scripts, use those assets instead of fetching them at runtime from the server.
This fixes a regression introduced in abf93c008b993f178df327e7681418df51e72844 for #2746.
/cc @kkaefer

Use downloaded local assets in ios-bench if present

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXAppDelegate.h
platform/ios/app/MBXAppDelegate.m
platform/ios/app/MBXViewController.m
platform/ios/include/MGLMapView.h
platform/ios/src/MGLMapView.mm

If no access token is found in user defaults at launch, iosapp prompts the user for an access token. Renamed the user defaults key for the access token to conform to Cocoa naming conventions. The `MAPBOX_ACCESS_TOKEN` environment variable is still honored.
Added an action to MGLMapView that reloads the current style. Note that it doesn’t clear the cache; it’s pretty much only useful for ensuring that a change in access token is reflected on the map or for forcing the map view to retry loading tiles independently of the exponential back-off strategy.
Fixes #3102 and fixes #4696.
/cc @friedbunny @kkaefer

Prompt for access token in iosapp

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Make userTrackingMode KVO-compliant

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/benchmark/MBXBenchViewController.mm
platform/ios/include/MGLMapView.h
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapView_Internal.h

Marked `-[MGLMapView emptyMemoryCache]` as deprecated. Removed the option to empty the in-memory tile cache from iosapp. Split out a project-internal header for methods on MGLMapView that ios-bench needs, to reduce the likelihood of a redeclared category getting out of sync.
Fixes #1833.
/cc @kkaefer

Deprecate -[MGLMapView emptyMemoryCache]

---

platform/ios/CHANGELOG.md
platform/ios/app/Info.plist
platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapboxEvents.m
platform/ios/uitest/App-Info.plist

~~Use the staging telemetry server when compiled for the iOS Simulator. An alternative would’ve been to disable telemetry altogether in this scenario, but I think leaving it enabled and sending it to the staging endpoint leaves open the possibility of testing telemetry with mocked requests (#2822).~~
Disable telemetry when compiled for the iOS Simulator.
Fixes #3621.
/cc @boundsj @friedbunny @bleege

Use staging server in simulator

---

platform/osx/osx.xcworkspace/xcshareddata/xcschemes/mbgl-offline.xcscheme
platform/osx/osx.xcworkspace/xcshareddata/xcschemes/mbgl-render.xcscheme
platform/osx/osx.xcworkspace/xcshareddata/xcschemes/test.xcscheme

A change I've been wanting to make for awhile was unlocked by #4641.
These targets expect the working directory to be set to the repository root.
cc @1ec5

[osx] Create shared schemas for mbgl-offline, mbgl-render, and test targets that set a working directory

---

platform/ios/DEVELOPING.md
platform/ios/benchmark/MBXBenchAppDelegate.h
platform/ios/benchmark/MBXBenchAppDelegate.m
platform/ios/benchmark/MBXBenchViewController.mm
platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme
platform/osx/osx.xcodeproj/xcshareddata/xcschemes/osxapp.xcscheme

ios-bench now prompts for an access token on first launch just as iosapp and osxapp do (#4728). ios-bench waits to start benchmarking until after the access token is entered. If this application needs to run without user intervention, the `MAPBOX_ACCESS_TOKEN` environment variable is still supported.
Removed the `MAPBOX_ACCESS_TOKEN` environment variable from iOS contributor documentation. Since the tendency to inadvertently commit this environment variable was the reason for removing the iosapp scheme in #4737, I’ve reverted that change, so the contributor documentation is once again accurate.
/cc @jfirebaugh @boundsj @friedbunny @kkaefer

Prompt for access token in ios-bench; restore iosapp scheme

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapboxEvents.m

Fixed a deadlock that could occur if the host application attempts to set user defaults on a background queue. Now we observe user defaults changes synchronously.
/cc @jfirebaugh @boundsj

Fix hang observing user defaults on background queue

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/include/MGLAnnotationImage.h
platform/ios/src/MGLAnnotationImage.m
platform/ios/src/MGLAnnotationImage_Private.h
platform/ios/src/MGLMapView.mm
platform/osx/osx.xcodeproj/project.pbxproj
platform/osx/src/MGLAnnotationImage.m
platform/osx/src/MGLAnnotationImage_Private.h
platform/osx/src/MGLMapView.mm

MGLMapView observes changes to the `coordinate` property of each MGLAnnotation added to it. Changing the `coordinate` property in a KVO-compliant way causes the annotation to be relocated and its callout view, if present, to be dismissed. To avoid observing the same annotation twice yet also avoid expensive lookups when adding or removing annotations, MGLMapView indexes added point annotations in an NSMutableSet.
Added the ability to delete an unused annotation image’s images on iOS. (The OS X SDK doesn’t yet support changing an annotation image’s image.) When you nil out the image of an MGLAnnotationImage, MGLMapView deletes the sprite from the style and resets any annotation associated with the MGLAnnotationImage instance to use the default red pin icon under the hood. The annotation …

Update annotations and annotation images dynamically

---

platform/darwin/include/MGLAccountManager.h
platform/darwin/include/MGLOfflineStorage.h
platform/ios/CHANGELOG.md
platform/ios/include/MGLMapView.h
platform/ios/src/MGLCompactCalloutView.h
platform/osx/include/MGLMapView.h

Replaced Markdown syntax with HTML syntax for hyperlinks in documentation comments. HTML links work both inside Xcode (whether Objective-C or Swift) and on the Web (via jazzy).
Fixes #3961.
/cc @tmcw @friedbunny

Use HTML links in documentation

---

src/mbgl/style/value.hpp

Noticed this dead code while reviewing `mapbox::variant` usage with @artemp

[core] remove unused code in value.hpp

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm

Fixed a crash removing a polyline or polygon by only removing the `coordinate` key path observer from non-MGLMultiPoints. Noted in the changelog that you still need to replace an MGLMultiPoint to have it appear in a different location or in a different form.
The annotation tag is now passed in as the observation context. This fixes a crash when an annotation is added to the map view more than once, then removed more than once.
/ref https://github.com/mapbox/mapbox-gl-native/pull/3835#issuecomment-212342112

Fix crash removing multipoint or duplicate annotation

---

.travis.yml
platform/qt/app/qmapboxgl.gypi
platform/qt/scripts/configure.sh

Adding a Travis build bot for Mapbox GL's Qt target using Qt 5.0.2 (provided via `ubuntu-sdk-tools` source in Travis CI).
I'm using GCC 4.9 for both Qt4 and Qt5 for now due to compiler errors while using clang 3.5 (example below):
```
/usr/include/qt5/QtCore/qurl.h:326:56: error: friend declaration specifying a default argument must be a definition
friend __attribute__((visibility("default"))) uint qHash(const QUrl &url, uint seed = 0) noexcept;
```
/cc @tmpsantos

[build] Added Qt 5 build for Travis CI

---

src/mbgl/style/style.cpp
test/api/custom_layer.cpp

We are clearing all style layers in `Style::setJSON()`, which is called whenever a style change occurs. This is OK for previous style layers because we're assigning new layers based on the loaded JSON style, but we should preserve custom layers as they are not associated with a specific style.

[core] Preserve custom layers upon style switch

---

platform/qt/src/qmapboxgl.cpp

We were initializing `mbgl::Map` twice 😨 
/cc @tmpsantos

[Qt] Remove duplicated mbgl::Map initialization

---

platform/ios/DEVELOPING.md
platform/ios/INSTALL.md
platform/ios/docs/pod-README.md
platform/osx/INSTALL.md

Copyedited installation documentation to make sense to less experienced Xcode users, ensure consistency, remove redundant language, and reflect recent build changes.
/cc @friedbunny @boundsj @tmcw @bleege

Make installation documentation consistent

---

platform/ios/app/MBXOfflinePacksTableViewController.m
platform/osx/app/AppDelegate.h
platform/osx/app/AppDelegate.m
platform/osx/app/MapDocument.m

When selecting an offline pack for display in iosapp or osxapp, constrain the zoom level to the pack’s minimum and maximum zoom levels.
Fixes #4787.

Constrain zoom level when selecting offline pack

---

platform/ios/app/MBXViewController.m

Fixed a race condition in which the access token alert controller would fail to present because the view controller hadn’t yet entered the view hierarchy, plus a downstream crash caused by the access token being missing.

Fix crash on missing access token

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

PR cleans up javadoc for animate and ease camera and makes each method's purpose more clear. 
Closes #4624

[android] #4624 - changed javadoc wording for ease and animate camera

---

src/mbgl/layer/circle_layer.cpp
src/mbgl/layer/circle_layer.hpp
src/mbgl/layer/line_layer.cpp
src/mbgl/layer/line_layer.hpp
src/mbgl/layer/symbol_layer.cpp
src/mbgl/layer/symbol_layer.hpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/renderer/symbol_bucket.hpp

This moves the *{Layout,Paint}Properties classes closer to code generation.

[core] Quarantine style property irregularities in layer classes

---

platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm

Fixed a crash when deallocating an MGLMapView that has point annotations. Now we explicitly remove all the annotations from the view and thus remove all remaining KVO observers on those annotations.
Fixes #4805.

Fix dangling KVO observer crash

---

include/mbgl/map/map.hpp
platform/ios/CHANGELOG.md
platform/ios/include/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/osx/include/MGLMapView.h
platform/osx/osx.xcodeproj/project.pbxproj
platform/osx/src/MGLMapView.mm
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp

Added an API to get a camera that you can pass into `-[MGLMapView setCamera:]` that fits the given coordinate bounds, by analogy with `-[MKMapView regionThatFits:]` or `-[MKMapView mapRectThatFits:edgePadding:]`.
Added `mbgl::Map::getCameraOptions()` for getting the current camera options in fewer lines of code – less opportunity to forget a field.
@friedbunny, can you double-check that I haven’t flubbed anything with respect to edge insets / padding?

cameraThatFitsCoordinateBounds

---

Makefile
platform/ios/jazzy.yml
platform/ios/scripts/document.sh

Fixed some regressions introduced in 9c9ff2d2d4aeac9f605a6ca23447e54adea9f6bd for #4802. A backslash was missing from a shell script, causing arguments to get dropped and output to go in the repo root. Paths in the jazzy configuration file needed to be updated so jazzy could find the headers.
Also, only build the static framework for Fabric. Fabric’s Mac application has no use for the dynamic framework.
/cc @boundsj

Fix jazzy build step

---

platform/darwin/src/MGLClockDirectionFormatter.m
platform/darwin/src/MGLCompassDirectionFormatter.m
platform/darwin/test/MGLClockDirectionFormatterTests.m
platform/darwin/test/MGLCompassDirectionFormatterTests.m

Fixed an issue causing angles that are multiples of 360°, such as 720°, to be described as 0 o’clock. Fixed a crash when a compass direction is close enough to 360° to round up to 360°.

Fix direction formatter edge cases

---

.travis.yml

We plan to use [QQuickFramebufferObject](http://doc.qt.io/qt-5/qquickframebufferobject.html) as a base class to implement our Qt Quick item. This class has been provided by Qt Framework since Qt 5.2. Travis CI provides Qt 5.0.2 as part of `ubuntu-sdk-team` PPA which we currently use.
We need to find another PPA that provides a Qt version that is at least 5.2 to be able to build and run tests in our Qt Quick implementation.
/cc @tmpsantos

[build] Bump Travis Qt5 version from 5.0.2 to 5.2+

---

include/mbgl/style/types.hpp
src/mbgl/layer/background_layer.hpp
src/mbgl/layer/fill_layer.hpp
src/mbgl/layer/line_layer.hpp
src/mbgl/style/function.hpp
src/mbgl/style/function_evaluator.cpp
src/mbgl/style/function_evaluator.hpp
src/mbgl/style/layout_property.hpp
src/mbgl/style/paint_property.hpp
src/mbgl/style/property_parsing.cpp
src/mbgl/util/interpolate.hpp
test/style/functions.cpp

This allows the `Function<Faded<T>>` partial specialization to be eliminated, giving all property functions a consistent storage type.

[core] Extract Function::evaluate to a separate class

---

include/mbgl/annotation/shape_annotation.hpp
src/mbgl/sprite/sprite_parser.hpp
src/mbgl/style/filter_expression.hpp
src/mbgl/style/value.hpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/tile_worker.hpp
src/mbgl/util/variant.hpp
src/mbgl/util/worker.hpp

For parallelism with `mbgl::optional`, and to avoid exposing namespaces other than `mbgl` in the public API.

[core] Define mbgl::variant

---

platform/ios/src/MGLUserLocationAnnotationView.m

The user dot/puck was keeping whichever frame size it was initialized with. This had no apparent ill effects, except that the accessibility frame would be incorrect when the user location annotation type changed.
- Updates the accessibility frame (by proxy) when changing between dot and puck
- Keeps the same center point while updating the frame
- `updateFrameWithSize:` does not take CGSize because there is not yet
support for non-square user location annotations
Fixes #4823.
/cc @1ec5

Update frame size when changing dot/puck mode

---

platform/ios/app/MBXViewController.m

Use the default red pin images for world tour destinations in iosapp instead of the two-character box usually used for the “Add _n_ Points” actions.
Fixes a regression introduced in #4783.

Use default images for world tour destinations

---

platform/osx/src/MGLMapView.mm

Zooming (easiest using Shift + drag) in the osxapp is noticeably janky, even in a Release build.
(Doesn't seem to have been caused by #2909; it was janky before that PR too.)

zooming is janky

---

src/mbgl/style/style.cpp

For `Style::cascade` and `Style::recalculate`, when rendering with `MapMode::Still`. Fixes a subtle race condition with animated transitions exacerbated by cd1a06c2dc209da81b3d745c088e568b3b14809f.
/cc @brunoabinader @bsudekum @miccolis

use Clock::time_point::max() instead of frame time

---

platform/ios/resources/Base.lproj/Localizable.strings
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLUserLocationAnnotationView.m

The user location annotation view is created lazily, so if the user dot isn’t within view at launch, it doesn’t exist by the time UIKit first queries MGLMapView for child accessibility elements. This caused console spew about missing accessibility elements and prevented the ℹ️ from being visible to XCUITest.
Constantly posting accessibility layout change notifications on every location change made it very difficult to stay focused on an accessibility element, be it the user dot or some other element. Now we only post the notification when the user dot is focused, user tracking mode is off (so the user dot actually has a chance to move around), and the application is active (not in the middle of application switching). We also keep the focus on the user dot in that case, so you don’t have …

Fix ℹ️ accessibility and make the user dot less noisy

---

.travis.yml

ccache is not enabled for Trusty public bots on Travis.
Disabling unit tests for Qt5 for now so it will take
less time.
Fixes #4855. (not really, but better than nothing)

[build] Do not run unit tests for Qt5

---

Makefile

Doing `make V=1` is a common way of asking make file based builds to show all compiler arguments. 
This pull passes that option down to disable the use of `xcpretty` for osx/ios command line builds.
The goal here is to quickly be able to see all the compiler arguments to ensure any custom flags are being respected (without a developer needing to find and hack the `Makefile` to do this).

Respect V arg to make to disable xcpretty

---

include/mbgl/map/update.hpp
include/mbgl/util/traits.hpp
platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapbox.cpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_p.hpp
src/mbgl/renderer/render_pass.hpp

This replaces the previous `mapRegionDidChange()` signal with `mapChanged(QMapboxGL::MapChange)`, where `QMapboxGL::MapChange` reflects `mbgl::MapChange`.
/cc @tmpsantos

[Qt] s/mapRegionDidChange()/mapChanged(QMapboxGL::MapChange)/ signal

---

src/mbgl/style/function_evaluator.cpp
src/mbgl/style/function_evaluator.hpp
src/mbgl/util/interpolate.hpp

This changes some of the overloads to return the second value rather than the first. Returning the second value is consistent with -js. It also probably doesn't really matter in practice.
cc @ansis

[core] Eliminate interpolate special cases

---

platform/ios/src/MGLMapView.mm

Thanks for walking me through this, @1ec5.
- Redefine as local variables
- Check/assert that these local variables are not null
Analyzer warnings:

[ios] Fix analyzer's nullability complaints

---

bin/glfw.gypi
include/mbgl/util/string.hpp
platform/default/image.cpp
platform/ios/platform.gyp
platform/osx/platform.gyp

This removes the only boost dependency from public headers.

[core] Replace boost::lexical_cast with std::to_string

---

bin/glfw.gypi
mbgl.gypi
platform/android/platform.gyp
platform/ios/platform.gyp
platform/linux/platform.gyp
platform/osx/platform.gyp
platform/qt/platform.gyp
test/test.gypi

variant.hpp is used for types that are included in the public API, so all dependents must be able to include the header.
cc @springmeyer

[core] Use gyp's direct_dependent_settings to propagate variant cflags

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/res/drawable/ic_mylocationview_background.xml

[android] #4912 - remove lollipop attribute from background drawable

---

platform/ios/uitest/MapViewTests.m
platform/ios/uitest/ios-tests.xcodeproj/project.pbxproj

This PR makes the KIF tests build and pass once again following regressions introduced in #4641 and #1496. Link to the libKIF.a in the shared build products directory instead of at a nonexistent, hard-coded path. Fixed a compilation error in the KIF tests caused by importing a project-internal header even after the KIF project was moved out of the test project. Updated accessibility labels.
/ref #4837

Fix KIF tests

---

src/mbgl/map/map.cpp

NE padding was applied as if it was SW, thus causing the view's center to be offset.
**Example**
Originally detected the issue when using the iOS method
`- (void)setVisibleCoordinateBounds:(MGLCoordinateBounds)bounds edgePadding:(UIEdgeInsets)insets animated:(BOOL)animated;` to show the black polyline annotation with insets of top = 20, left = 20, bottom = 80, right = 20.
Before this fix:
After this fix:

Fix a bug in applying padding to the camera.

---

platform/ios/resources/en.lproj/Localizable.stringsdict
platform/ios/src/MGLMapView.mm

Corrected the English override strings for the map view’s accessibility value. Prior to this change, the accessibility value would say “0 annotation” instead of “0 annotations” for some reason.
The zoom level in the map view’s accessibility value is off by two.

Correct map accessibility value

---

scripts/main.mk

E.g. when running `make linux -jX`, it causes `linux` target dependencies `glfw-app`, `render` and `offline` to run in parallel. This is OK, however `${PLATFORM_CONFIG_OUTPUT}` target - which collects the mason configure data, installing dependencies along the way - was run repeatedly for each of these targets, causing an unstable build. This fix addresses this by explicitly telling Makefile that `${PLATFORM_CONFIG_OUTPUT}` is not meant to be run in parallel.
/cc @tmpsantos @jfirebaugh

[build] Fix parallel 'make linux' call

---

src/mbgl/style/filter.hpp
src/mbgl/style/filter_evaluator.hpp
src/mbgl/style/style_parser.cpp
test/style/filter.cpp

ref https://github.com/mapbox/feature-filter/pull/15
cc @1ec5 @jfirebaugh @mourner

Implement "has" / "!has" filter operators 

---

.travis.yml

Tracking the Travis package whitelist repo tickets here:
https://github.com/travis-ci/apt-package-whitelist/issues/2899
https://github.com/travis-ci/apt-package-whitelist/issues/2900
No really a serious problem because it can be installed via `before_install`, since we have `root` privileges on the Qt5 bot.

[Qt][build] qtpositioning5-dev and qtlocation5-dev are not whitelisted by Travis

---

platform/osx/src/MGLMapView.mm

This fixes a regression introduced in #2909. A print operation can’t run inside a draw operation of any sort, so defer the print operation until the next iteration of the run loop. Note that the map view still can only be printed using `-[NSView print:]` action rather than the preferred EPS- or PDF-writing methods.
Fixes #4956.

Display print dialog after drawing

---

platform/android/CONTRIBUTING_LINUX.md

Review https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/CONTRIBUTING_LINUX.md and make sure the steps to get the SDK building are accurate.
Target distribution Ubuntu Xenial Xerus (16.04).
/cc @danswick

[android] Review CONTRIBUTING_LINUX.md

---

README.md
platform/qt/README.md

The Qt SDK currently lacks any form of documentation. Each platform in this repository should have – at a minimum – a readme and installation guide in the subdirectory under platform/. A changelog would also be helpful once we start tagging releases.
/cc @brunoabinader @tmpsantos @tmcw

Documentation for Qt SDK

---

package.json

With Node 6, we're seeing `v8::ObjectTemplate::Set() with non-primitive values is deprecated` messages in the console. Simply upgrading NAN fixes this.

Upgrade Nan to fix v8::ObjectTemplate::Set() with non-primitive values is deprecated

---

platform/ios/src/MGLMapView.mm
platform/osx/app/Base.lproj/MapDocument.xib
platform/osx/src/MGLMapView.mm

This PR fixes the context menu on map views in osxapp so that the menu appears and is enabled in the right situations. These connections were lost in #3427.
As in MapKit, a two-finger tap (the “walking fingers” gesture) should be interpreted as a secondary click to open the context menu, if applicable. It should not zoom out; rather, a double-tap on a Magic Mouse should zoom out (“smart magnification”).
This PR also fixes a longstanding issue that made the osxapp context menu only apply to the right-clicked pin after first selecting the pin. It also happened to be a latent bug in the iOS implementation.
Fixes #3493.
/cc @kkaefer

Fix context menu on OS X

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

Closes #4700 
This PR deprecates OnLocationChangeListener in favour of LocationListener.
Reasons why I'm suggesting deprecation:
- we have 2 ways of listening to locational updates
- difference between the two is only noticeable if you read the related javadoc
- needed to decouple UserLocationView completely to allow a user provided implementation
👀  @bleege @zugaldia @cammace

[android] #4700 - decouple location listener from UserLocationView

---

platform/qt/src/qquickmapboxglrenderer.cpp

Because at low zoom levels setting a new coordinate won't
correspond to the actual coordinate on the map.

[Qt] Always use setCoordinateZoom()

---

platform/darwin/test/MGLStyleTests.mm
platform/ios/CHANGELOG.md

Looks like this ropes in some additional changes for v3.2.1 that were never merged back to master. I decided to keep the changes added in 8ecb20610bc633ee6201bc2b0a668301140d8fc1 to make sure we can handle arbitrary versions.

Merge iOS SDK 3.2.2 release branch into master

---

platform/ios/src/MGLMapView.mm

It seems there was a logic error in calculating the duration for animating the user's current location dot. Since the code used the MAX of 1 second, or the time between the current location and previous location, it could easily result in animations of 30 seconds or more in cases where there's a gap in location updates. This could happen in common situations such as when the user is indoors. The result was a very slow and strange movement of the location dot. Pretty sure MIN is more appropriate here, as it puts a cap on the animation duration.

[ios] fix potential for very slow animations of user location dot

---

platform/osx/scripts/package.sh

An error in the packaging script caused Mapbox.framework to be placed inside a folder named Mapbox.framework. This change moves the framework up one level.

Fix nested framework

---

include/mbgl/map/map.hpp
include/mbgl/map/mode.hpp
platform/default/glfw_view.cpp
platform/ios/src/MGLMapView.mm
platform/osx/src/MGLMapView.mm
platform/qt/include/qmapboxgl.hpp
platform/qt/qmlapp/main.qml
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qquickmapboxgl.cpp
platform/qt/src/qquickmapboxglrenderer.cpp
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp
src/mbgl/renderer/painter_symbol.cpp
test/map/transform.cpp
test/style/source.cpp
test/util/tile_cover.cpp

_Viewport mode_ satisfies embedding platforms that requires the viewport coordinate systems to be set according to its standards e..g. Qt Quick requires third-party rendering code to follow its standards with regards to viewport transforms.
Qt 5.6 adds a [mirrorVertically](http://doc.qt.io/qt-5/qquickframebufferobject.html#mirrorVertically-prop) property that solves the solution for that version of Qt onwards. Telling Mapbox GL core to flip the Y axis makes `QQuickMapboxGL` item available from Qt 5.2 onwards.
Fixes #4866.
:eyes: @kkaefer @tmpsantos

[core] [Qt] Added viewport mode

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/StyleInitializerTest.java

Fixes the issue that the style field within the initialiser is set to null.
Backed up these changes with unit tests.

[android] - fixes style init bug, added unit test to prevent regression

---

platform/qt/README.md
platform/qt/app/mapwindow.cpp
platform/qt/app/mapwindow.hpp
platform/qt/include/qmapbox.hpp
platform/qt/platform.gyp
platform/qt/src/qmapbox.cpp

When using Qt, we're not initializing the OpenGL extensions, so it's not using VAOs even if they're available as indicated by the message `[WARNING] {}[OpenGL]: Not using Vertex Array Objects` in the console.
/cc @tmpsantos @brunoabinader

Initialize VAO extensions in Qt app

---

platform/qt/app/mapwindow.cpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qquickmapboxglrenderer.cpp

Some issues to consider:
- `Map::Impl` only reads the pixel ratio once in the ctor. In my environment, I have an external  monitor connected to my MacBook. When moving the application window between them, the pixel ratio should be updated.
- We're hardcoding the pixel ratio to 1 in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/qt/src/qmapboxgl.cpp#L597.
/cc @tmpsantos

[Qt] QMapboxGL pixel ratio is wrong for Retina displays

---

bin/offline.cpp
include/mbgl/storage/resource.hpp
include/mbgl/storage/response.hpp
include/mbgl/util/chrono.hpp
include/mbgl/util/constants.hpp
platform/android/src/http_file_source.cpp
platform/darwin/src/http_file_source.mm
platform/default/http_file_source.cpp
platform/default/mbgl/storage/offline_database.cpp
platform/default/online_file_source.cpp
platform/default/sqlite3.cpp
platform/node/src/node_request.cpp
platform/qt/src/http_request.cpp
src/mbgl/renderer/debug_bucket.cpp
src/mbgl/renderer/debug_bucket.hpp
src/mbgl/storage/resource.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/tile_data.hpp
src/mbgl/tile/vector_tile_data.cpp
src/mbgl/util/chrono.cpp
src/mbgl/util/http_header.cpp
src/mbgl/util/http_header.hpp
test/map/map.cpp
test/storage/default_file_source.cpp
test/storage/http_file_source.cpp
test/storage/online_file_source.cpp

We're currently using a timepoint type that has microsecond precision, but since all of our timestamps are from HTTP fields, we don't need that. In fact, it's causing subtle bugs because seemingly identical timestamps differ on the fractional level, so comparison fails.

Move from SystemTimePoint to Timestamp

---

.gitignore
platform/ios/Mapbox.playground/Contents.swift
platform/ios/Mapbox.playground/contents.xcplayground
platform/ios/Mapbox.playground/timeline.xctimeline
platform/ios/app/MBXAnnotationView.h
platform/ios/app/MBXAnnotationView.m
platform/ios/app/MBXViewController.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLAnnotationView.m
platform/ios/src/MGLAnnotationView_Private.h
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/ios/src/Mapbox.h

Implement platform annotation view (UIViews) for iOS.
For native annotation views in the Mapbox SDK, I don't see any reason to stray too far from what a developer coming from the Apple's MapKit might expect. Combined with the existing Mapbox API for adding annotations this would look like:
```
// existing annotation model management API
-addAnnotation(s):
-removeAnnotation(s):
-selectAnnotation:animated:
...
// a new method to dequeue a reusable annotation view
-dequeueReusableAnnotationViewWithIdentifier:
// a new method in MGLMapViewDelegate protocol
-mapView:viewForAnnotation:
```
Below is an example of how the new methods noted above might be used in a future implementation. Note that MGLMapView will expect its delegate to supply a UIView that is a subclass of a new …

[ios] Add platform annotation views

---

platform/ios/src/MGLAPIClient.m

Do a _little_ bit more validation on the telemetry test server URL. HTTPS-only because this deals in location information.
Follows up on #4691.
/cc @boundsj @1ec5

[ios] Check that telemetry test server string is URL-like

---

platform/darwin/src/MGLGeometry.h
platform/darwin/src/MGLGeometry_Private.h
platform/darwin/test/MGLGeometryTests.mm
platform/ios/CHANGELOG.md

Makes the formerly-private `MGLCoordinateInCoordinateBounds()` function publicly available.
- The old private function converted `MGLCoordinateBounds`→`mbgl::LatLngBounds` and `CLLocationCoordinate2D`→`mbgl:LatLng`.
- The new public function compares `CLLocationCoordinate2D` and `MGLCoordinateBounds` directly.
/cc @1ec5

[ios] Make MGLCoordinateInCoordinateBounds() public

---

include/mbgl/util/string.hpp
src/mbgl/util/dtoa.cpp
src/mbgl/util/dtoa.hpp
test/test.gypi
test/util/number_conversions.cpp

Fixes #998 and excess trailing zeros introduced by #4916.
Supersedes #4965.
cc @friedbunny @1ec5

Use rapidjson's dtoa implementation to stringify floats

---

platform/default/default_file_source.cpp
test/storage/default_file_source.cpp

Right now, when calling `FileSource::request()`, we're making every effort to obtain the data. However, for #123, we need a more relaxed way to request things that can be obtained with low effort (e.g. by loading it from a cache, but *not* downloading it from the internet).

Allow requesting optional resources

---

package.json
platform/node/test/suite_implementation.js
src/mbgl/geometry/feature_index.cpp
src/mbgl/geometry/feature_index.hpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/vector_tile_data.cpp
src/mbgl/util/geometry.hpp

Another core part of #352.
I [disabled several query tests](https://github.com/mapbox/mapbox-gl-test-suite/commit/b3441d9a285ffbe9b876677acb13d7df07e5b975) that are failing and need investigation. At least some of them appear to stem from differences in geometry handling between geojson-vt-js and geojson-vt-cpp. However, having invested over a week into this PR now, I would like to move on to something new. @mourner is this something that you could pick up?

[core] Include geometry in queryRenderedFeatures results

---

src/mbgl/map/transform.cpp
src/mbgl/map/transform_state.cpp
test/map/transform.cpp

Fix cases where e.g. state has either zero width or height, causing the unit conversion functions to return NaNs.
:eyes: @kkaefer @jfirebaugh @ansis

[core] [Qt] Avoid NaNs in TransformState unit conversions

---

src/mbgl/renderer/frame_history.cpp
src/mbgl/renderer/frame_history.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/shader/icon.fragment.glsl
src/mbgl/shader/icon.vertex.glsl
src/mbgl/shader/icon_shader.hpp
src/mbgl/shader/sdf.fragment.glsl
src/mbgl/shader/sdf.vertex.glsl
src/mbgl/shader/sdf_shader.hpp

- this is simpler than predicting opacity based on current zooming speed
- this is smoother: symbols don't flicker when changing zoom speed or
when zooming in and out rapidly.
mapbox/mapbox-gl-js@1df1466
fix #4562 
---
The second commit sets `glActiveTexture` before binding any texture and makes sure that texture unit is correctly passed to the shader.

port better symbol fading with texture lookups

---

platform/ios/src/MGLMapView.mm
platform/osx/CHANGELOG.md
platform/osx/src/MGLMapView.mm

Fixes #5096. No blurb has been added to the iOS SDK changelog because the regression was introduced in #4766, which has not yet been released.
/cc @boundsj

Fix crash adding mixture of points and shapes

---

include/mbgl/map/mode.hpp
platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/osx/CHANGELOG.md
platform/osx/app/Base.lproj/MainMenu.xib
platform/osx/app/MapDocument.m
platform/osx/src/MGLMapView.h
platform/osx/src/MGLMapView.mm
src/mbgl/map/map.cpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter_background.cpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp

Together with `MapDebugOptions::Collision`, provides _wireframe_ rendering output so all drawn objects are visible. This mode ignores the line width, background and fill colors for better visualization.
/cc @mapbox/gl

[core] Wireframe debug mode

---

include/mbgl/gl/gl_values.hpp
include/mbgl/map/mode.hpp
include/mbgl/platform/default/glfw_view.hpp
platform/default/glfw_view.cpp
platform/osx/CHANGELOG.md
platform/osx/app/Base.lproj/MainMenu.xib
platform/osx/app/MapDocument.m
platform/osx/src/MGLMapView.h
platform/osx/src/MGLMapView.mm
platform/qt/app/mapwindow.cpp
platform/qt/src/qmapboxgl.cpp
src/mbgl/gl/gl_config.cpp
src/mbgl/gl/gl_config.hpp
src/mbgl/map/map.cpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_debug.cpp

The GLFW app had a debug view that visualized the stencil buffer rather than the color buffer. The OS X app no longer has that.

Stencil debugging view is gone

---

platform/darwin/src/MGLOfflineStorage.mm
platform/darwin/test/MGLOfflineStorageTests.m
platform/ios/CHANGELOG.md

Speculatively fixes #5112, where apps mistakenly backup the offline/ambient cache.
This moves the backup exclusion flag to a point just after `DefaultFileSource` has been created/initialized, ensuring that this flag is set on every launch.
As with the other offline storage tests, the new `-testBackupExclusion` must be run in alphabetical order — or, at least after the cache has been initialized. The cache file will persist in the simulator when you run these tests locally.
/cc @1ec5

[ios] Set backup exclusion flag after initializing DefaultFileSource

---

src/mbgl/algorithm/update_renderables_impl.hpp
src/mbgl/renderer/debug_bucket.cpp
src/mbgl/renderer/debug_bucket.hpp
src/mbgl/renderer/painter_debug.cpp
src/mbgl/source/source.cpp
src/mbgl/style/style.cpp
src/mbgl/style/style_bucket_parameters.hpp
src/mbgl/tile/raster_tile_data.cpp
src/mbgl/tile/raster_tile_data.hpp
src/mbgl/tile/tile_cache.cpp
src/mbgl/tile/tile_data.cpp
src/mbgl/tile/tile_data.hpp
src/mbgl/tile/tile_worker.cpp
src/mbgl/tile/tile_worker.hpp
src/mbgl/tile/vector_tile_data.cpp
src/mbgl/tile/vector_tile_data.hpp
test/algorithm/mock.hpp

It's time to remove the `TileData::State` enum. This enum holds linear state and should represent the lifecycle of a tile, but it's a stretch to say that it's linear. This removes it completely in favor of a clear API and a separate `obsolete` variable for `VectorTileData` objects.

Remove TileData::State

---

platform/ios/src/MGLMapView.mm

https://github.com/mapbox/mapbox-gl-native/pull/5097 introduced different arrays for points and shapes, but only ever attempted to use the points array. Adding a shape would crash.
/cc @1ec5

[ios] Fix points/shapes typo that caused crash

---

docker/linux/Dockerfile
docker/linux/test.sh

There are a few docker scripts that make testing on Linux easier, but they're not up-to-date with recent build system changes.

Fix Docker scripts

---

platform/qt/app/mapwindow.cpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qquickmapboxglrenderer.cpp

From http://doc.qt.io/qt-5/qguiapplication.html#devicePixelRatio, `QWindow::devicePixelRatio` is the most reliable pixel ratio because `QGuiApplication` returns the maximum pixel ratio of all available `QScreen` objects. This is not valid for cases e.g. where two or more `QScreen` objects with different pixel ratios are present and the application window appears on the screen with lower pixel ratio.
This patch also moved `glViewport` call to QMapboxGL domain.
:eyes: @tmpsantos @kkaefer

[Qt] QMapboxGLPrivate::getPixelRatio() cleanup

---

src/mbgl/geometry/buffer.hpp
src/mbgl/geometry/glyph_atlas.cpp
src/mbgl/geometry/line_atlas.cpp
src/mbgl/geometry/vao.cpp
src/mbgl/geometry/vao.hpp
src/mbgl/gl/gl_object_store.cpp
src/mbgl/gl/gl_object_store.hpp
src/mbgl/renderer/frame_history.cpp
src/mbgl/shader/shader.cpp
src/mbgl/sprite/sprite_atlas.cpp

Fixes a misused `operator bool()` plus usage of an undefined pointer in `{GL,TexturePool}Holder` code.
:eyes: @kkaefer @jfirebaugh 
Fixes #5136.

Fix texture leak in TexturePoolHolder

---

platform/node/src/node_map.cpp
platform/node/src/node_request.cpp
platform/node/src/node_request.hpp
platform/node/test/js/map.test.js

When requesting a resource in the node bindings, we're currently [returning a plain `AsyncRequest` object](https://github.com/mapbox/mapbox-gl-native/blob/c111250fcccaf5e57154852606ee740f0db242c1/platform/node/src/node_map.cpp#L536). This means that when we cancel the file request, we're not canceling the associated JS `request()` call. We can't do that because it's immediate, but that immediate function call is async, so it could fire the passed `callback` function later on, at a point when the `AsyncRequest` has long been destroyed.

[node] Don't fire callback when the AsyncRequest was canceled

---

src/mbgl/annotation/annotation_manager.cpp
src/mbgl/annotation/annotation_tile.cpp
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/annotation/shape_annotation_impl.cpp
test/api/annotations.cpp

Fixes #5159.
@jfirebaugh, any idea why no features are returned in the test? When I put this fix into my branch in #5110, annotation features are returned by `queryRenderedFeatures()`.

AnnotationTileLayer vends its own name

---

platform/qt/src/async_task.cpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_p.hpp

There is a bug on the code when the `QMapboxGL` is not created on the main thread.
```
#0  0x00007f7921c69418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f7921c6b01a in __GI_abort () at abort.c:89
#2  0x00007f7921c61bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7f7923f590d3 "runLoop == RunLoop::Get()", 
file=file@entry=0x7f7923f590b0 "../../src/mbgl/util/work_queue.cpp", line=line@entry=29, 
function=function@entry=0x7f7923f59140 <mbgl::util::WorkQueue::pop(std::function<void ()> const&)::__PRETTY_FUNCTION__> "void mbgl::util::WorkQueue::pop(const std::function<void()>&)") at assert.c:92
#3  0x00007f7921c61c82 in __GI___assert_fail (assertion=0x7f7923f590d3 "runLoop == RunLoop::Get()", 
file=0x7f7923f590b0 …
```

[Qt] QML test app crashing on debug builds

---

src/mbgl/renderer/frame_history.cpp

On the Javascript implementation the array is automatically filled with
zeroes which is not the same thing as `TimePoint::min()`. Here we need
to get our own "zero" which is the timestamp of the first frame.
Fixes #5109

[core] Fill the initial `changeTimes` with the reference timestamp of the first frame

---

platform/ios/src/MGLMapView.mm

This forces the call of the map view's display link target when the display link is created. When a map view is shown the first time this is not required. However, if the display link was torn down and then recreated due to the map view being removed / obscured in the view hierarchy the map view delegate may expect to be informed when the map view did finish loading the map when it is shown again.
This adds a call to `updateFromDisplayLink` just after a display link is created which helps trigger a full refresh of the map in the sense that all delegate methods get exercised including `mapViewDidFinishLoadingMap`.

[ios] Force update from display link when display link is created.

---

package.json
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_circle.cpp
src/mbgl/shader/circle_shader.hpp
src/mbgl/shader/collision_box_shader.cpp
src/mbgl/shader/icon_shader.cpp
src/mbgl/shader/line_shader.cpp
src/mbgl/shader/linepattern_shader.cpp
src/mbgl/shader/linesdf_shader.cpp
src/mbgl/shader/sdf_shader.cpp

Ported the following patches:
- [convert mat4 exMatrix to a vec2 extrudeScale](https://github.com/mapbox/mapbox-gl-shaders/commit/a8d549b7a41540d3a99767975ff1b7b18a6010e9)
- [Enabled data-driven styling for circle-radius](https://github.com/mapbox/mapbox-gl-shaders/commit/4356e41fa657837904d189e604468617ee601ddb)
- [Reduce shader boilerplate, refactor "Bucket"](https://github.com/mapbox/mapbox-gl-shaders/commit/7d3da8f1914954fd96f305b7116cfd127a616551)
Shader PR: https://github.com/mapbox/mapbox-gl-shaders/pull/4
Part of https://github.com/mapbox/mapbox-gl-shaders/issues/1.
/cc @jfirebaugh @kkaefer @ansis

[core] Update circle shader code

---

package.json
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/shader/icon_shader.hpp
src/mbgl/shader/sdf_shader.hpp

Ported the following patch:
- [convert mat4 exMatrix to a vec2 extrudeScale](https://github.com/mapbox/mapbox-gl-shaders/commit/a8d549b7a41540d3a99767975ff1b7b18a6010e9)
Shader PR: mapbox/mapbox-gl-shaders#5
Part of mapbox/mapbox-gl-shaders#1.
/cc @jfirebaugh @kkaefer @ansis

[core] Update icon shader code

---

platform/qt/src/qmapboxgl.cpp

I forgot to update `glViewport` to use the converted size. 
👀 @tmpsantos

[Qt] Fix typo in QMapboxGL::resize

---

.travis.yml

LLVM is no longer hosting a debian repo and the build was broken. Trusty
has the LLVM version we need.
Fixes #2696

[build] Migrate LLVM bots to Trusty

---

package.json
src/mbgl/tile/vector_tile.cpp

The keys in the vector tile may not be in alphabetical order. Building a vector of keys by looping over `std::map<std::string, …>` effectively sorts the keys by alphabetical order without sorting the associated values. ~~This change removes the `map` in favor of logic that [more closely matches vector-tile-js](https://github.com/mapbox/vector-tile-js/blob/91b134985381bb66fbd778720d3bbd94c3642cad/lib/vectortilelayer.js#L30).~~ This change inserts keys in the same order in which they appear in the vector tile.
Fixes #5182.

Store feature keys in same order as in vector tile

---

platform/ios/app/MBXAnnotationView.m
platform/ios/app/MBXViewController.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLAnnotationContainerView.h
platform/ios/src/MGLAnnotationContainerView.m
platform/ios/src/MGLAnnotationView.mm
platform/ios/src/MGLMapView.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/5140
Fixes https://github.com/mapbox/mapbox-gl-native/issues/5089
Adds a new UIView subclass to contain MGLAnnotationView instances and an API for helping to manage the addition of new annotations. To mitigate [known performance issues with `UIView:addSubview:`](http://blog.benjamin-encz.de/post/disassembling-uikit-tintcolor-visitor), this batches up the addition of subviews to the container _before_ adding the container itself to the view hierarchy. The organization of the views in the separate container also naturally avoids the "piercing" issue seen before between annotations and callouts.

[ios] Add annotation container view

---

package.json
scripts/build-shaders.py

GL JS has introduced some simple `#pragma` statements in the shaders in order to reduce data-driven styling boilerplate. 
Supporting these `#pragma` statements in GL Native will reduce the need for `#ifdef` statements in the shaders and lay some foundation for data-driven styling in GL Native. 
- `#pragma mapbox: define foo lowp` statements: define a uniform variable `u_foo` with the specified precision 
- `#pragma mapbox: initialize foo lowp` statements: alias the uniform variable from `u_foo` to `foo`
ref https://github.com/mapbox/mapbox-gl-js/pull/2585
cc @jfirebaugh @1ec5 @mourner

Support "#pragma mapbox:" commands in the shaders

---

README.md
platform/qt/README.md

We currently have build bots for Qt4 and Qt5 running on Linux in Travis. We should do the same for OS X on Bitrise.

[build] Configure Qt build bots for OS X on Bitrise

---

platform/node/README.md

A simple update to the readme on instructions for Node version.
See https://github.com/mapbox/mapbox-gl-native/issues/5144

Updated readme with clear instructions that this requires Node v4.x 

---

scripts/build-version.py

This patch ensures that tag always contains 3 elements, as long as tag is a list.
The `scripts/build-version.py` code sometimes doesn't work, esp. if the code is run within another git repo or alternative build system where tags are 2 elements:
```
if is_git_repo():
raw_tag = subprocess.check_output("git describe --tags --always --abbrev=0", shell=True)
raw_rev = subprocess.check_output("git rev-parse HEAD", shell=True)
if raw_tag == raw_rev:
tag = DEFAULT_TAG
rev = parse_rev(raw_rev)
else:
tag = parse_tag(raw_tag)
rev = parse_rev(raw_rev)
else:
tag = DEFAULT_TAG
rev = DEFAULT_REV
print "Tag: {0}".format(tag)
print "Rev: {0}".format(rev)
```
When building via buildroot, this prints:
```
max@dfaefaadca5c:~/buildroot$ make
>>> qmapboxgl 6abd3d7 Building …
```

Ensure version tag always has 3 parts.

---

platform/ios/src/MGLAnnotationContainerView.m
platform/ios/src/MGLAnnotationView.mm
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapView_Internal.h

Corrected the accessibility frames of annotation views to match the views’ bounds instead of the bounds of the default annotation image (which could be empty if no default GL point annotation has been added).
~~Ideally, we’d figure out how to make the annotation view its own accessibility element, so that it or a subclass can specify a custom frame or Bézier path. But I’m punting on that for now to keep things simple.~~ Annotation views are now their own accessibility elements. A subclass can define a custom accessibility path.
Fixes #5038.

Make annotation views accessible to VoiceOver

---

include/mbgl/storage/network_status.hpp
include/mbgl/util/run_loop.hpp
platform/android/src/async_task.cpp
platform/android/src/run_loop_impl.hpp
src/mbgl/geometry/glyph_atlas.hpp
src/mbgl/map/map.cpp
src/mbgl/map/transform_state.cpp
src/mbgl/renderer/bucket.hpp
src/mbgl/sprite/sprite_atlas.hpp
src/mbgl/storage/network_status.cpp
src/mbgl/style/bucket_parameters.hpp
src/mbgl/text/glyph_pbf.hpp
src/mbgl/tile/tile_worker.cpp
src/mbgl/tile/tile_worker.hpp
src/mbgl/tile/vector_tile_data.hpp
src/mbgl/util/atomic.hpp
src/mbgl/util/math.cpp
src/mbgl/util/math.hpp
src/mbgl/util/thread.hpp

Added polyfills for classes and functions that are buggy on ARMv5 binaries running on ARMv7+ phones.
Fixes #3985

[android] Workaround ARMv5 ABI errors

---

platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/osx/app/MapDocument.m
platform/osx/src/MGLMapView.h
platform/osx/src/MGLMapView.mm

Ignore multipoints (as opposed to polylines and polygons) when adding annotations, just like we ignore multipolylines, multipolygons, and shape collections. Asserting on all these cases would be just as reasonable, but the other types are already ignored so I figure it’s best to be consistent.
In osxapp, break multipoint features into points before adding them as annotations.
Split out from #5245.

Ignore multipoints when added as annotations

---

src/mbgl/gl/object_store.hpp
src/mbgl/gl/texture_pool.cpp
src/mbgl/gl/texture_pool.hpp
src/mbgl/util/raster.cpp
src/mbgl/util/raster.hpp
test/gl/object.cpp

TexturePool is a very risky class at the moment. To make it safe:
* The `getTextureID` method should return an RAII object that releases the texture back to the pool on destruction.
* `TexturePool` should release all texture resources in its destructor. Before doing so, it should assert that there are no active acquisitions -- the pool itself must outlive the RAII'ed acquisitions.

TexturePool should use RAII

---

include/mbgl/util/image.hpp
src/mbgl/util/raster.cpp

Revert 61dad6eae59e284fdba63fcd76d9192aba900db4. No one owned the data after release(), so this wasn't being free'd. `reset()` does that, thus this patch causes a huge memory leak.
:eyes: @tmpsantos @kkaefer

[core] Fix memory leak in Raster image data

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

The Documentation link [on CocoaPods.org](https://cocoapods.org/pods/Mapbox-iOS-SDK) should point to the API reference, not to the main ios-sdk front page, which is already linked right above.

[ios] Point podspec to API reference

---

platform/default/webp_reader.cpp

`delete []` was being called for a `malloc()` allocated C buffer.
Found by valgrind:
```
==23065== Mismatched free() / delete / delete []
==23065==    at 0x4C2F77B: operator delete[](void*) (vg_replace_malloc.c:621)
==23065==    by 0x50C5529: std::default_delete<unsigned char []>::operator()(unsigned char*) const (unique_ptr.h:119)
==23065==    by 0x523EC85: std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >::reset(unsigned char*) (unique_ptr.h:581)
==23065==    by 0x523E3D4: mbgl::Raster::upload(mbgl::gl::ObjectStore&) (raster.cpp:63)
==23065==    by 0x520CA08: mbgl::RasterBucket::upload(mbgl::gl::ObjectStore&) (raster_bucket.cpp:16)
==23065==    by 0x520E56A: mbgl::Painter::render(mbgl::style::Style const&, mbgl::FrameData const&, mbgl::SpriteAtlas&) …
```

[core] Fix deleter mismatch

---

INSTALL.md
platform/ios/DEVELOPING.md

Prompted by #5229.
- Add subsections to the “Building” section.
- Add more detail to `make` packaging commands and emphasize that Debug
is the default build type.
- ~~Manually checking out git submodules is no longer necessary.~~ Removed in #5232.
/cc @1ec5 @jfirebaugh

[ios] Reorganize and update development instructions

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Avoid creating an array with `nil`. Also fixed a write-without-read analyzer warning introduced in #5235.
Fixes #5274.
/cc @boundsj

Fix crash in userLocationVerticalAlignment, analyzer warning

---

platform/ios/src/MGLMapView.mm

On each frame update, update annotation views before informing the delegate of the new frame. This allows the delegate to manipulate annotation views without fear of the SDK overriding those modifications.
For example, if you want a particular view-backed annotation other than the selected annotation to appear in front of any other view-backed annotations, your MGLMapViewDelegate can hold a strong reference to the view it provides for that annotation and implement this method:
```objc
- (void)mapViewDidFinishRenderingFrame:(MGLMapView *)mapView fullyRendered:(BOOL)fullyRendered {
// Make way for Its Preeminence!
[self.preeminentAnnotationView.superview bringSubviewToFront:self.preeminentAnnotationView];
}
```
/ref #991 #5264
/cc @frederoni @boundsj @zugaldia

Update annotation views before informing delegate

---

.travis.yml
Makefile
configure
platform/qt/scripts/configure.sh
scripts/valgrind.sh
scripts/valgrind.sup
test/storage/asset_file_source.cpp

We should perform memory checks as part of our automated build bots process. The idea is to add a new Makefile target similar to `run-valgrind-glfw-app` that could run e.g. unit tests and analyzes the data from [valgrind's memcheck](http://valgrind.org/docs/manual/mc-manual.html).
/cc @mapbox/gl

Memory leak bot

---

platform/osx/app/AppDelegate.m
platform/osx/app/Base.lproj/MainMenu.xib

Added tile count and tile size columns to osxapp’s Offline Packs window. Also expanded the byte count formatters to include the raw byte count for debugging purposes.
Followup to #4874.
/cc @mapsam @jakepruitt @springmeyer

Tile count, tile size columns in osxapp

---

platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm

We introduce a new MGLZoomGestureCentering enum and corresponding zoomGestureCentering property on MGLMapView.
Currently, Mapbox automatically adjusts the center of the map relative to the user's gesture location, but for some applications (e.g Uber, Lyft) it is preferable to keep the map center "locked" in response to zoom gestures.
Exisiting code will retain its current behavior without modification and will implicitly use the default value of MGLZoomGestureCenteringFollowsTouch. New code can specify MGLZoomGestureCenteringLockedInPlace to get the new "locked" behavior.

[ios] Support for a customizable zoom gesture centering strategy.

---

package.json

Extrude scale is already multiplied with altitude by default since
62b4dd554ab4df891221b1e43bda5a0f5dc1741a.
Fixes #5006.

[core] Port pitched circle rendering from gl-js

---

include/mbgl/style/layers/symbol_layer.hpp
include/mbgl/style/types.hpp
package.json
scripts/generate-style-code.js
src/mbgl/geometry/icon_buffer.cpp
src/mbgl/geometry/icon_buffer.hpp
src/mbgl/geometry/text_buffer.cpp
src/mbgl/geometry/text_buffer.hpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/shader/icon_shader.hpp
src/mbgl/shader/sdf_shader.hpp
src/mbgl/style/layers/symbol_layer.cpp
src/mbgl/style/layers/symbol_layer_impl.cpp
src/mbgl/style/layers/symbol_layer_properties.cpp
src/mbgl/style/layers/symbol_layer_properties.hpp
src/mbgl/style/property_evaluator.cpp
src/mbgl/style/property_parsing.cpp
src/mbgl/style/property_parsing.hpp
src/mbgl/text/quads.cpp
src/mbgl/text/quads.hpp

Native port of https://github.com/mapbox/mapbox-gl-js/pull/2668.
cc @lucaswoj @jfirebaugh @mollymerp @lxbarth

text-pitch-alignment

---

package.json
src/mbgl/text/quads.cpp

Fixes bug in text-rotate handling and passes new render tests in https://github.com/mapbox/mapbox-gl-test-suite/pull/105.

Don't apply textRotate twice

---

Makefile

A clean build e.g. `make qt-app` is causing mixed npm/mason output:
```
./configure platform/qt/scripts/configure.sh build/qt-osx-x86_64/config.gypi osx x86_64
npm update # Install dependencies but don't run our own install script.
* Using Python 2.7.10
* Installed system-provided Qt 5.6.0
normalizeTree → correctMk ▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
normalizeTree → addLocalD ▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
* Installed binary package at /Users/bruno/work/mapbox-gl-native/mason_packages/headers/unique_resource/dev
* Downloading binary package headers/protozero/1.3.0.tar.gz...
* Installed binary …
```

[build] Mixed npm/mason output in clean build

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java

[android] #5285 - bring selected MarkerView to the front

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/InfoWindowActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_infowindow.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Fixes #4159.
/cc: @tobrun @ivovandongen

Expose an API to enable selection/deselection of markers on a map tap

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java

4924 make gesture focal point configurable

---

platform/ios/src/MGLMapView.h

When using a subclass of `MGLAnnotationView` or `MGLAnnotationImage`, the following warning occurs when calling `dequeueReusableAnnotationImageWithIdentifier` or `dequeueReusableAnnotationViewWithIdentifier`:
`Incompatible pointer types initializing 'MyClassName *' with an expression of type 'MGLAnnotationView * _Nullable'`
This change eliminates the warning  and matches Apple's implementation of `UITableViewCell`.

[ios] Satisfy compiler warning when dequeueing subclasses of MGLAnnotationView or MGLAnnotationImage

---

platform/ios/app/MBXAnnotationView.m
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLAnnotationView.mm
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapViewDelegate.h

Fixes  #5127 #5128 #5130 
Added `selected` and `enabled` property to `MGLAnnotationView` and hooked it up.
Added `mapView:did(De)SelectAnnotationView:` protocol methods.
@boundsj 
I kept the annotation and annotation views selection protocol methods separated but let me know if you want me to combine them into `mapView:did(De)SelectAnnotation:annotationView:`
/cc @1ec5 @friedbunny

[ios] fixes #5127, #5128, #5130 added enabled and selected property to MGLAnnotationView

---

.clang-tidy
Makefile
platform/osx/bitrise-tidy.yml
scripts/clang-tidy.sh

Also use HeaderFilterRegex in `.clang-tidy` instead of passing it as a parameter on the command call.
:eyes: @kkaefer

[tidy] Install mason clang-tidy if CLANG_TIDY is not set

---

platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLAnnotationView.mm
platform/ios/src/MGLAnnotationView_Private.h
platform/ios/src/MGLMapView.mm
platform/ios/test/MGLAnnotationViewTests.m

Also added a test case to make sure the `annotation` property is handled correctly but there's no reference to the `platform/ios/test/MGLAnnotationViewTests.m` file in the project file as I'm figuring out the details around [#4641](https://github.com/mapbox/mapbox-gl-native/pull/4641).
/cc @1ec5 @boundsj @friedbunny

[ios] fixes #5129 added annotation property to MGLAnnotationView

---

platform/default/mbgl/storage/offline_download.cpp
src/mbgl/style/parser.cpp
src/mbgl/style/parser.hpp
src/mbgl/style/sources/geojson_source.cpp
src/mbgl/style/sources/geojson_source.hpp
src/mbgl/style/sources/raster_source.cpp
src/mbgl/style/sources/raster_source.hpp
src/mbgl/style/sources/vector_source.cpp
src/mbgl/style/sources/vector_source.hpp
src/mbgl/style/tile_source.cpp
src/mbgl/style/tile_source.hpp
src/mbgl/tile/geojson_tile.cpp
src/mbgl/tile/geojson_tile.hpp
src/mbgl/util/tileset.hpp
test/style/source.cpp
test/style/style_parser.cpp
test/style/tile_source.cpp
test/test.gypi

A tile source can either specify a URL to TileJSON, or inline TileJSON. Use `variant<std::string, Tileset>` in `TileSource` to represent that reality.
While here, cherry pick the removal of unused `Tileset` attributes from #5286.

[core] Rationalize URL vs Tileset handling

---

src/mbgl/platform/log.cpp

Follows https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/thread.hpp#L98-L104.
:eyes: @kkaefer @tobrun @tmpsantos

[core] Do not use pthread_getname_np before Glibc 2.11

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

Removes deprecation of `setOnMyLocationChangeListener`
Closes #4700.
cc @bleege @zugaldia

[android #4700 - remove deprecation MyLocationListener

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/directions/DirectionsActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/geocoding/GeocoderActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/navigation/LocationPickerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/PulseMarkerView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/PulseMarkerViewOptions.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/anim/pulse.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_circle.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_clear_24dp.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_location_picker.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/view_pulse_marker.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/dimens.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/build.gradle

Still need to squash the commits

5282 locationpicker

---

Makefile

Build platform equals to host platform if not cross compiling, otherwise use the mason-provided platform.
:eyes: @kkaefer @tmpsantos

[build] Use mason platform info when cross-compiling

---

include/mbgl/style/transition_options.hpp
include/mbgl/util/constants.hpp
include/mbgl/util/unitbezier.hpp
platform/android/src/jni.cpp
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm
platform/qt/app/mapwindow.cpp
platform/qt/include/qmapbox.hpp
platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapboxgl.cpp
src/mbgl/map/transform.cpp
src/mbgl/style/cascade_parameters.hpp
src/mbgl/style/paint_property.hpp
src/mbgl/style/property_parsing.cpp
src/mbgl/style/style.cpp

Use a shared default `UnitBezier` transition ease for both transform and style transitions. `UnitBezier` is now `constexpr` and all its functions can be safely marked `const`.
Fixes #363.
👀 @jfirebaugh @kkaefer @1ec5

[core] Use default transition ease for style transition

---

src/mbgl/platform/log.cpp
src/mbgl/util/thread.hpp

Follow-up to #5389. Unfortunately Apple headers defines a different `pthread_getname_np` from Glibc, so creating a common `#define` would eventually add more code lines than the contrary. I left them out of `Thread` because it is a template class.
:eyes: @jfirebaugh @kkaefer

[core] Factor out thread name setter/getter

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Fixes #5398.
I also standardized the other InfoWindow examples.
/cc: @cammace

Rename Custom Dynamic InfoWindow Adapter in testapp

---

platform/default/jpeg_reader.cpp
platform/default/png_reader.cpp

Fixes #4915.
:eyes: @jfirebaugh @springmeyer

[core] Replace boost iostream with std::{i,s}stream

---

src/mbgl/map/map.cpp
src/mbgl/renderer/bucket.hpp
src/mbgl/renderer/circle_bucket.cpp
src/mbgl/renderer/circle_bucket.hpp
src/mbgl/renderer/fill_bucket.cpp
src/mbgl/renderer/fill_bucket.hpp
src/mbgl/renderer/line_bucket.cpp
src/mbgl/renderer/line_bucket.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_raster.cpp
src/mbgl/renderer/raster_bucket.cpp
src/mbgl/renderer/raster_bucket.hpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/renderer/symbol_bucket.hpp
src/mbgl/tile/raster_tile.cpp
src/mbgl/tile/raster_tile.hpp
src/mbgl/util/raster.cpp
src/mbgl/util/raster.hpp

The `Raster` object currently has a construction-time dependency on `TexturePool`, but all we do is store the reference until we need it when calling `.bind()`. Instead, we can just pass it then.

Remove TexturePool dependency from Raster

---

platform/qt/include/qmapbox.hpp
platform/qt/src/qmapboxgl.cpp

[Qt] Use mbgl::LineString instead of mbgl::Polygon as default shape

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

From @boundsj 
> This adds a guard so that when a shove gesture is occurring, no other
gestures take place. This helps avoid the disorienting feeling of
having the map move left and right and rotate while trying to tilt it
and looks more like Google maps.
To @boundsj:
> join the dark side we have cookies
Or at least Marshmallow, Lollipop, KitKat,..

[android] Cancel other gestures during shove.

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/app/Base.lproj/MainMenu.xib
platform/macos/app/MapDocument.m
platform/macos/src/MGLMapView.h
platform/macos/src/MGLMapView.mm

A verb doesn’t make sense in this enum value. Besides, overdrawing is the bug that this effect exposes, not the effect itself. Instead, use a descriptive, Cocoa-compliant word for this effect and describe it in detail in the documentation comment. The core implementation continues to use the same term as GL JS.
/ref #5403
/cc @brunoabinader @friedbunny

Rename overdraw to overdraw visualization

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java

5427 marker view flat bug

---

platform/ios/app/MBXAnnotationView.m
platform/ios/app/MBXViewController.m
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLAnnotationView.mm
platform/ios/src/MGLAnnotationView_Private.h
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapViewDelegate.h

Fixes #5036
Setting MGLAnnotationView's `draggable` property to YES will make it draggable.
In order to make it stick to the location where it was dropped, you have to implement;
`-mapView:didDragAnnotationView:toLocation:`
and update the `coordinate` property of the associated annotation.
Made a few changes compared to previous PR which didn't take center offset into account.
- Circle offset is 0,0
- Rectangle offset is "bottom-left"
also updated doc in MGLMapViewDelegate, I hope it's more clear now.
/cc @1ec5 @boundsj @friedbunny

[ios] fixes #5036 draggable annotation views

---

platform/ios/src/MGLMapView.mm

The current implementation of view backed annotations mostly relies on the existing annotation model manager and the associated underlying boost query implementations for annotation management. However since, in the case of view backed annotations, the representation of the model is a UIView, an image was not installed. Because the underlying annotation management implementation is not entirely comfortable working without an image, it would report `[INFO] {Worker}[Sprite]: Can't find sprite named 'default_marker'` when annotation models without an image were encountered.
This updates the annotation adding logic to create (or reuse) and install a small, invisible image for each view backed annotation.
This stops the issue noted in #5210 for iOS.
cc @1ec5

[ios] Use transparent image for annotations backed by views

---

Makefile

Update `make node` to respect `BUILDTYPE` by passing `--debug` to `node-pre-gyp` if `BUILDTYPE=Debug`

[node] add BUILDTYPE=Debug support to make node

---

platform/ios/src/MGLMapView.mm

Fixed a crash on iOS 8.1 and below due to specifying the compass legend’s font weight using a font weight constant that was introduced in iOS 8.2. `UIFontWeightUltraLight` happens to equal −0.8 on iOS 9 in the default configuration. I think it’s reasonable to hardcode this value as a fallback; we still use the system constant when it’s available.
Fixes #5486, a regression introduced in #4783.

Specify ultra light weight literally

---

platform/ios/src/MGLAnnotationView.mm
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapView_Internal.h
platform/ios/test/MGLAnnotationViewTests.m

Closes https://github.com/mapbox/mapbox-gl-native/issues/5494
Closes https://github.com/mapbox/mapbox-gl-native/issues/5495
This fixes two issues with annotation views that were exposed when dragging them:
1) The annotation view's mapView property was not set until it was moved (in `updateAnnotations:`) so it did not always call its delegate back about the map view delegate dragging methods. This adds a call to
set the property when an annotation view is created so the delegate methods are always called.
2) Since the mapView is now always set, a call to the map view's callout view for selected annotation was added to the annotation view drag handler. This forces the callout to close and eliminates an issue where the callout would remain visible as an annotation was dragged away which had …

[ios] Always set map view reference when annotation view is created.

---

platform/ios/test/MGLAnnotationViewTests.m

Prevent a race condition by not fulfilling the expectation until after the view has been added.

[ios] prevent a race condition 

---

platform/ios/src/MGLAnnotationView.mm

This stops the quick zoom gesture (double-tap and hold) from also triggering a drag, when performed on a draggable annotation view. 
Here is the buggy sequence of events:
1. MGLMapView’s quick zoom long press gesture fires [after one tap and a 0 second long press](https://github.com/mapbox/mapbox-gl-native/blob/33a8856c2af9c587e35b97658f9a7aed85a7cf60/platform/ios/src/MGLMapView.mm#L506-L507).
1. If the long press is held, MGLAnnotationView’s long press fires after the default delay (0.5 seconds).
1. Panning vertically will zoom the map and drag the annotation.
MGLAnnotationView’s drag was unconditionally allowed to fire simultaneously, even though it was also being performed with MGLMapView’s quick zoom. This PR limits MGLAnnotationView’s drag gesture by only allowing its long press and …

[ios] Fix conflict between view dragging gesture and quick zoom

---

platform/ios/src/MGLMapView.mm

This removes the guard for setting the sprite symbol name when annotation coordinates are updated. The guard was added when UIView backed annotations did not have invisible image placeholders. Since images are now present for both sprite and UIView backed annotations, the guard is no longer necessary and removing it allows for the correct symbol name to be passed to the mbgl map's `updateAnnoation` method and this gets rid of `[INFO] {Worker}[Sprite]: Can't find sprite named 'default_marker'` log message.
To put it another way, this gets rid of log messages related to unknown sprite names when annotations backed by UIViews have their coordinates changed.
This is an additional fix required for https://github.com/mapbox/mapbox-gl-native/issues/5210 that was missed in …

[ios] Always use symbol name for annotation update

---

platform/darwin/src/async_task.cpp

The map events instigated by certain actions (i.e. updates from a UIScrollView) are not processed by the run loop with `kCFRunLoopDefaultMode`until the thread is idle. This changes the mode to `kCFRunLoopCommonModes` to avoid this issue.
cc @1ec5 @jfirebaugh

[ios, macos] Use common instead of default mode for run loop source

---

platform/ios/CHANGELOG.md
platform/ios/jazzy.yml
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm

This is a continuation of #3619 that makes the “drift” animation after a user gesture configurable.
/cc @csmulhern @frederoni

Adjustable map deceleration rate

---

include/mbgl/util/char_array_buffer.hpp
platform/default/jpeg_reader.cpp
platform/default/png_reader.cpp

Implements a custom `std::streambuf` that reads directly from a char array. This buffer assumes that the array remains valid during its entire lifetime. This avoid creating temporary `std::string` objects and thus optimizes image decode.
Suggested by @artemp in https://github.com/mapbox/mapbox-gl-native/pull/5417#issuecomment-227700063.
:eyes: @artemp @jfirebaugh

[core] Added CharArrayBuffer

---

src/mbgl/renderer/painter_debug.cpp

Fixes an issue with rendering debug frame/text being too opaque in certain zooms.
| Before | After |
|:--:|:--:|
| <img width="400" alt="screen shot 2016-07-02 at 1 03 54 pm" src="https://cloud.githubusercontent.com/assets/76133/16539776/b69c54f8-4055-11e6-8726-940ed43ff66b.png"> | <img width="400" alt="screen shot 2016-07-02 at 1 04 07 pm" src="https://cloud.githubusercontent.com/assets/76133/16539782/eded61f4-4055-11e6-9d6d-7a948c12398b.png"> |
:eyes: @kkaefer @tmpsantos

[core] Enforce solid fragColor for debug frame/text

---

package.json
src/mbgl/geometry/static_vertex_buffer.cpp
src/mbgl/geometry/static_vertex_buffer.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_background.cpp
src/mbgl/renderer/painter_clipping.cpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_raster.cpp
src/mbgl/renderer/raster_bucket.cpp
src/mbgl/renderer/raster_bucket.hpp
src/mbgl/shader/raster_shader.cpp
src/mbgl/shader/raster_shader.hpp
src/mbgl/shader/shader.cpp
src/mbgl/shader/shader.hpp

So far this has been the trickiest pending task from https://github.com/mapbox/mapbox-gl-shaders/issues/1. I'm afraid this will require help from someone with more GL expertise. I've started updating `RasterShader` according to the new shader code and am assuming that `tile == parentTile` for testing purposes.
Question: If `u_buffer_scale` is always 1 - why do we need to expose this as a uniform? I assume we want to eventually expose this as as data-driven style property?
Part of https://github.com/mapbox/mapbox-gl-native/issues/115.
:eyes: @kkaefer @lucaswoj @ansis @jfirebaugh

[core] Update RasterShader to support crossfading

---

platform/ios/jazzy.yml
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLMapViewDelegate.h
platform/macos/src/MGLMapViewDelegate.h

Reorganized MGLMapViewDelegate and MGLAnnotationView symbols into sections by task. Wrapped documentation comments at column 80 for readability.
Added documentation for `-mapViewWillStartRenderingFrame:` and `-mapViewDidFinishRenderingFrame:fullyRendered:`, which are supported and behave as expected (except for the part that has been left undocumented; see #2775). Synchronized iOS and macOS documentation for MGLMapViewDelegate. Added cross-references between annotation image and annotation view delegate methods and among the various callout delegate methods.
Added missing `MGLAnnotationViewDragState` documentation and also added the symbol to jazzy’s table of contents. Rewrote MGLAnnotationView documentation and removed the unnecessary custom getter on `scalesWithViewingDistance` based on …

Rewrote MGLMapViewDelegate, MGLAnnotationView documentation

---

platform/ios/Mapbox.playground/Contents.swift
platform/ios/app/MBXViewController.m
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLAnnotationView.mm

Removed MGLAnnotationView’s option to lie flat against a tilted map to work around #5090.

Remove MGLAnnotationView.flat

---

platform/ios/app/MBXAnnotationView.h
platform/ios/app/MBXAnnotationView.m
platform/ios/app/MBXViewController.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLAnnotationView.mm
platform/ios/src/MGLAnnotationView_Private.h
platform/ios/src/MGLMapView.mm

This PR is a subset of #5245 that focuses on improving KVO compliance and animation in MGLAnnotationView:
* Fixed a bug causing an annotation view to be scaled based on a pitch of 0° when setting the view’s center offset.
* Always reposition the annotation view using the standard `-setCenter:` setter, fixing KVO compliance for the center key path and making the view behave more like a normal view. `-setCenter:` updates the transform by side effect, and it always starts from the identity transform to avoid surprises.
* An annotation view moves immediately when you change its `centerOffset` or `scalesWithViewingDistance` property.
* Made annotation views’ positions animatable. In iosapp, tapping the callout view of a D.C. fire hydrant annotation causes the annotation view to slide to the …

Annotation view implicit animation

---

platform/ios/CHANGELOG.md
platform/ios/scripts/document.sh

So much has changed in the iOS SDK v3.3.0 milestone that the release notes have become unwieldy, with 26 notable changes total, compared to just 18 in the v3.2.0 milestone. This change categorizes the v3.3.0 release notes by topic. The topics are sorted from most basic usage (styles) to most advanced usage (offline maps), followed by some less important topics at the bottom (packaging). Within each topic, the changes are sorted from those with the most developer or user impact (e.g., feature querying) to the least (debug flags).
Though this approach does push the important view-backed annotations blurb further down, I’m hopeful that, overall, fewer changes will get buried this way. This PR will cause a big merge conflict on master, but in the long run, encouraging additions to the middle …

Split release notes into sections by topic

---

src/mbgl/util/mapbox.cpp
test/util/mapbox.cpp

If `getMapboxURLPathname` parse a url with querystring, such as `mapbox://p/a/t/h?query=aa`, an infinite loop happens and crash your computer. This is a serious bug which will affect all platforms.  You should fix it ASAP!

mapbox: URL containing query string causes infinite loop

---

src/mbgl/renderer/raster_bucket.cpp
src/mbgl/util/raster.cpp
src/mbgl/util/raster.hpp

We currently don't support mipmap levels for our GL texture wrapper object `Raster`. This cleans up the code and adds mipmap levels.

Allow setting explicit mipmap levels for Raster

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/jni.cpp

refs #5104 
Expanding this PR scope with suggestion from @jfirebaugh to eliminate `getField` calls:
- from 117 to 105ms 
- from 32 to 30ms
- from 34 to 31ms
- from 94 to 86ms
- from 103 to 94ms
- from 106 to 97ms
Out of scope for this PR:
- Java List object manipulation in JNI (eg. addMarkers, AddPolylines,...)
- Offline related calls

5104 faster jni

---

platform/ios/app/MBXViewController.m
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLAnnotationView.mm
platform/ios/src/MGLMapViewDelegate.h

This PR simplifies implementing draggable annotation views by removing `didDragAnnotationView:toCoordinate` and instead call `setCoordinate:` on the associated MGLAnnotation. It also adds support for canceling a drag operation by setting `dragState` to `MGLAnnotationViewDragStateCanceling` as mentioned in [#5544](https://github.com/mapbox/mapbox-gl-native/issues/5544)
👀 @1ec5 @boundsj

[ios] fixes #5544 support canceling a drag operation and not by default

---

platform/ios/scripts/package.sh

Dynamic and static framework w/ and w/o symbols seems to be working except for one case;
- `platform :ios, '7.0'` in Podfile
- `Deployment target set to 7.0` in Xcode (not using `use_frameworks!`)
Yields:
```
[!] Unable to satisfy the following requirements:
- `Mapbox-iOS-SDK (from `../mapbox-gl-native/build/ios/pkg/dynamic/Mapbox-iOS-SDK-symbols.podspec`)` required by `Podfile`
It seems like you've changed the constraints of dependency `Mapbox-iOS-SDK` inside your development pod `Mapbox-iOS-SDK`.
You should run `pod update Mapbox-iOS-SDK` to apply changes you've made.
```
- `pod update Mapbox-iOS-SDK` yields the same error message.
Podfile
```
platform :ios, '7.0'
target 'podtest' do
pod 'Mapbox-iOS-SDK', :path => "../mapbox-gl-native/build/ios/pkg/dynamic/Mapbox-iOS-SDK-symbols.podspec" …
```

[ios] fixes #4536 include podspec in iOS releases

---

Makefile
mbgl.gypi
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/platform.gyp

Fixes https://github.com/mapbox/mapbox-gl-native/issues/5526
Fixes https://github.com/mapbox/mapbox-gl-native/issues/5448
In https://github.com/mapbox/mapbox-gl-native/commit/f791eb32b9ebe96845e87e5a6acd3ee46182c1d5 we simplified the package script and intended to remove support for building the SDK without Bitcode support. The intention was to use the ENABLE_BITCODE project setting to do this and remove the control of that variable in the
script. However, since we use `xcodebuild build` this only uses bitcode `marker` by default and causes a failure when an app that uses the Mapbox SDK is archived.
This adds the `BITCODE_GENERATION_MODE` and `bitcode` value to the necessary iOS SDK and mbgl and platform targets. If an app that uses the Mapbox SDK is built with these flags set, it will be …

Add support for full Bitcode builds

---

platform/android/src/run_loop.cpp
platform/android/src/run_loop_impl.hpp
platform/android/src/timer.cpp
test/util/timer.cpp

Wake up the main thread run loop with a file descriptor event from a thread that exists for this sole purpose.
This was probably causing expired tiles to not be re-requested.
/cc @ivovandongen

[android] Add support for timers on the main thread

---

platform/ios/scripts/package.sh

Resource bundle and required frameworks were not included so let's omit podspec for static lib until next release

[ios] omit podspec for static lib

---

src/mbgl/tile/geometry_tile.cpp

This manually includes in the implementation change in https://github.com/mapbox/mapbox-gl-native/commit/903d609b40b6d0f4873f7bb46d96f4a06d7b17d6 from the master branch for the iOS 3.3.0 release.
cc @jfirebaugh @1ec5

[core] Re-close polygons after clipping with clipper

---

scripts/generate-style-code.js

Currently, it produces `{ 255, 255, 255, 1 }` for white, but the correct GL color is `{ 1, 1, 1, 1 }`. Also makes sure the colors are premultiplied.

Style spec code generator produces wrong colors

---

platform/macos/CHANGELOG.md
platform/macos/app/AppDelegate.m
platform/macos/src/MGLMapView.mm

NSView’s built-in context menu handling preempts non-right-click gesture recognizers, so preempt it with a right-click gesture recognizer that does essentially the same thing. With this change, two-finger double-tapping on a trackpad also zooms out, consistent with MapKit.
Fixes #5078.
/cc @kkaefer

Use gesture recognizer for context menu

---

include/mbgl/gl/gl_values.hpp
platform/ios/ios.xcodeproj/project.pbxproj
src/mbgl/gl/gl_config.hpp
src/mbgl/renderer/painter.cpp
test/gl/object.cpp

We frequently call our wrapped GL state/value system with `.reset()` when we want to set the value to its default value. However, `.reset()` currently forces the value without checking the previous state. This changes the behavior of `.reset()` to "set default value" (which does nothing when the value was already the default value).

Remove redundant GL state calls

---

include/mbgl/style/conversion/make_property_setters.hpp
include/mbgl/style/layers/circle_layer.hpp
include/mbgl/style/types.hpp
package.json
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_circle.cpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/shader/circle_shader.hpp
src/mbgl/style/layers/circle_layer.cpp
src/mbgl/style/layers/circle_layer_properties.cpp
src/mbgl/style/layers/circle_layer_properties.hpp
src/mbgl/style/property_evaluator.cpp
src/mbgl/style/types.cpp

Makes the behavior changed in #5006 configurable.
Corresponding commits:
* https://github.com/mapbox/mapbox-gl-style-spec/commit/83b1a3e5837d785af582efd5ed1a212f2df6a4ae
* https://github.com/mapbox/mapbox-gl-shaders/commit/4d1f89514bf03536c8e682439df165c33a37122a
* https://github.com/mapbox/mapbox-gl-test-suite/commit/f3b8d8c6e31c7f8417aab123dc7787df2b263247
GL-JS PR: https://github.com/mapbox/mapbox-gl-js/pull/2821

Add support for circle-pitch-scale property

---

platform/macos/app/Base.lproj/MainMenu.xib

Followed up #5452 with some changes to keyboard shortcuts that ensure conformance to the [Apple Human Interface Guidelines](https://developer.apple.com/library/prerelease/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/InteractivityInput.html#//apple_ref/doc/uid/20000957-CH10-SW4) and avoid conflicts between menu items:
* File ‣ Print and Page Setup are once again the familiar ⌘P and ⇧⌘P, respectively. Users are accustomed to using these shortcuts without ever looking at the menu to know that they’ve been reassigned.
* Debug ‣ Show Tooltips on Dropped Pins no longer has a keyboard shortcut. ⌥⌘T is taken by View ‣ Show Toolbar. If showing tooltips on dropped pins is useful enough (despite any performance hit), let’s make it enabled by default instead.
* Debug ‣ Blanket Map …

Revise keyboard shortcuts in macosapp

---

include/mbgl/gl/gl_values.hpp
src/mbgl/geometry/glyph_atlas.cpp
src/mbgl/geometry/glyph_atlas.hpp
src/mbgl/geometry/line_atlas.cpp
src/mbgl/geometry/line_atlas.hpp
src/mbgl/gl/gl_config.cpp
src/mbgl/gl/gl_config.hpp
src/mbgl/renderer/bucket.hpp
src/mbgl/renderer/circle_bucket.cpp
src/mbgl/renderer/circle_bucket.hpp
src/mbgl/renderer/fill_bucket.cpp
src/mbgl/renderer/fill_bucket.hpp
src/mbgl/renderer/frame_history.cpp
src/mbgl/renderer/frame_history.hpp
src/mbgl/renderer/line_bucket.cpp
src/mbgl/renderer/line_bucket.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter_background.cpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/renderer/raster_bucket.cpp
src/mbgl/renderer/raster_bucket.hpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/renderer/symbol_bucket.hpp
src/mbgl/sprite/sprite_atlas.cpp
src/mbgl/sprite/sprite_atlas.hpp
src/mbgl/util/raster.cpp
src/mbgl/util/raster.hpp

Our GL state tracking system currently doesn't include bound textures, so we're repeatedly setting the bound texture as well as changing the active texture to do so.B

Track bound textures

---

src/mbgl/renderer/painter_raster.cpp

This isn't failing the test-suite outright because the tests are ignored for other reasons, but, `raster-opacity/literal`:

raster-opacity is broken

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

We currently support the same API twice on the MapView object. Removing direction api in favor of bearing. Bearing has been the terminology used for internal API while direction reflects our public API. The methods contained in MapView are for internal use only.

[android] - remove duplicate bearing/direction API from MapView

---

platform/ios/src/MGLMapView.mm

Fixes a bug where the selection of annotation views would never be animated, because `-[MGLMapView selectAnnotation:animated:]` wasn’t passing along its `animated` value.
This change means that tapped view annotations now properly receive `animated = YES` — e.g., when a custom view annotation class overrides `-setSelected:animated:`.
I’ve put this on the v3.3.0 milestone because it’s a minor change that shouldn’t need serious testing. We could push this to v3.3.1, though, if we don’t think there’s enough time for another RC before release.
/cc @boundsj @frederoni @1ec5

[ios] Pass along `animated` property when selecting annotation views

---

src/mbgl/map/transform_state.cpp

When panning past the antimeridian, the wrapped copy of the world is blank until the antimeridian goes past the center of the view.
Reproduces in fe99295970a1f5e2d8834b35ce327938a1738240 on macOS and the iOS Simulator.

Wrapped world is blank

---

include/mbgl/style/conversion.hpp
platform/node/src/node_map.cpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qt_geojson.hpp
src/mbgl/style/sources/geojson_source_impl.cpp

char* increases the risk of pointing to a invalid reference. Qt had to use a static variable as retainer to workaround.

[core] Report conversion errors using std::string

---

platform/qt/scripts/configure.sh

At least on the Fedora system I'm using the qt5 development packages don't provide a binary named `qmake` (at least not one that would be in `$PATH`). This is a simple change that uses `qmake-qt5` if `qmake` isn't found. If `qmake` is available the behaviour is as before.
It does NOT test whether `qmake-qt5` is available. That is similar to the behaviour this script had before: if `qmake` wasn't found, it just exits with an error.

[qt] if `qmake` isn't available, try `qmake-qt5`

---

platform/ios/src/MGLMapView.mm

Ensure the `mapView` property is set when positioning the annotation view, in case the map view needs to be consulted about its rotation or pitch. I overlooked this reversed order when implementing #5550.
/cc @frederoni @boundsj @friedbunny

Ensure mapView is set when positioning annotation view

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/macos/app/wms.json
platform/macos/macos.xcodeproj/project.pbxproj
src/mbgl/storage/resource.cpp
test/storage/resource.cpp

Ported mapbox/mapbox-gl-js#2805 and mapbox/mapbox-gl-js@0877cac1d065a57c6ff2ce32f6b1201376ff8116 to support [quadkey](https://msdn.microsoft.com/en-us/library/bb259689.aspx) tokens in tile URL templates.
Ported https://github.com/mapbox/mapbox-gl-js/pull/2612#issuecomment-223595580 along with the necessary parts of mapbox/whoots-js@f2ca0caf9889581c1eda2de649eff32542c61eea for limited WMS scheme support. Added a local style to macosapp that you can use to debug WMS support in the macOS SDK: zoom in to New Jersey, then go to View ‣ Custom Style and enter `wms.json`.
Fixes #822 and fixes #5485.
/cc @lucaswoj @tmcw @bhousel

Quadkey tokens in tile URL templates, limited WMS support

---

platform/darwin/src/MGLAccountManager.h
platform/darwin/src/MGLTypes.h
platform/ios/jazzy.yml
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLMapView.h
platform/macos/jazzy.yml

This pull request reorganizes jazzy’s navigation categories by demoting less commonly used parts of our SDK to generic “Other” categories at the bottom of the list. In particular, this makes the Maps and Offline sections easier to understand.
I’ve also cleaned up some typos in the inline documentation and added two back-references to enum docs about which MGLMapView properties they are used with.
/cc @1ec5

Reorganize jazzy’s navigation categories; cleanup docs

---

include/mbgl/annotation/annotation.hpp
platform/android/src/jni.cpp
platform/darwin/src/MGLMultiPoint_Private.h
platform/darwin/src/MGLPolygon.mm
platform/darwin/src/MGLPolyline.mm
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapViewDelegate.h
platform/macos/src/MGLMapView.mm
platform/macos/src/MGLMapViewDelegate.h
src/mbgl/renderer/painter_fill.cpp
src/mbgl/style/layers/background_layer_properties.hpp
src/mbgl/style/layers/circle_layer_properties.hpp
src/mbgl/style/layers/fill_layer_properties.hpp
src/mbgl/style/layers/line_layer_properties.hpp
src/mbgl/style/layers/symbol_layer_properties.hpp
src/mbgl/style/paint_property.hpp
test/api/annotations.cpp

Ref: [include/mbgl/annotation/annotation.hpp#L41](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/annotation/annotation.hpp#L41)
This implies adapting all platform-specific code to return an optional color value for this, specifically:
- Android: [platform/android/src/jni.cpp#L788](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/jni.cpp#L788)
- Darwin: [platform/darwin/src/MGLPolygon.mm#L48](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLPolygon.mm#L48)
Then we could cleanup the outline color check done in [src/mbgl/renderer/painter_fill.cpp#L27-L31](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/painter_fill.cpp#L27-L31).
/cc @tobrun @1ec5 @jfirebaugh

mbgl::FillAnnotation::outlineColor should be an optional<Color>

---

mbgl.gypi
platform/android/platform.gyp

This piece from Realm on [Reducing your Android APK size When Using Native Libraries](https://realm.io/news/reducing-apk-size-native-libraries/) suggests the following approach to reducing library size:
> At that point both our core (libtightdb) and the JNI code was compiled with GCC with the -Os flag, which tries to optimize the library for size while maintaining decent performance. We also enabled -visibility=hidden to hide most of the unneeded ELF symbols.
Per convo with @tmpsantos we don't use the `-Os` flag as we optimize for performance, but we could benefit from `-visibility=hidden` as Qt does.
It'd be interesting to compare library size before and after adding those flags.

Add -fvisibility=hidden param to Android build

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapboxAccountManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/MapboxAccountManagerNotStartedException.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Proposed solution that closes #5541:
- remove requirement to call `MapboxAccountManager` before `setContentView`
- introduces a concrete `MapboxAccountManagerNotStartedException`
This solution was tested against: 
- `MapboxAccountManager.start` after setContentView in Activity
- setting up an accesstoken in xml
- setting up an accesstoken via MapboxMapOptions
- setting up an accesstoken via `MapboxAccountManager.start` in Application object
cc @bleege @cammace @danswick @ivovandongen @zugaldia

5541 mapbox account manager

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PressForMarkerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_press_for_marker.xml

Refs #5652, enforce practice of loading a style and configuring the initial location early.

[android] #5652 - enforce best practices on test activities

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapUtils.java

5438 MyLocationView transformation

---

package.json
platform/node/src/node_map.cpp
platform/node/src/node_map.hpp

Changes:
- Added `removeLayer` Node binding to support https://github.com/mapbox/mapbox-gl-test-suite/commit/f496dcdb9cfe93adbee83a2f2f47b1c93860e56c
- Updated `mapbox-gl-test-suite` to https://github.com/mapbox/mapbox-gl-test-suite/commit/3fabb909ba50af1175a2409e9a3cda56fb41b5c7
- Added regression test for https://github.com/mapbox/mapbox-gl-native/pull/5648
:eyes: @mikemorris @bsudekum

[node] Added 'removeLayer' binding

---

platform/ios/Mapbox-iOS-SDK-static-part.podspec
platform/ios/scripts/package.sh

[ios] fixes #4536 include podspec for static framework

---

platform/ios/src/MGLMapView.mm

This is the view annotation deselection counterpart to https://github.com/mapbox/mapbox-gl-native/pull/5646's selection (that I neglected to check). Going to put this on v3.3.1, as this is a minor fix and we can live without it in the short term.
/cc @1ec5 @boundsj @frederoni

[ios] Also pass `animated` property when deselecting annotation views

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml

In order to enable this functionality, the developer can now set a `SetStorageExternal` boolean flag in the `AndroidManifest.xml` file to switch to external storage:
```
<meta-data
android:name="com.mapbox.SetStorageExternal"
android:value="true" />
```
The default value for storage remains internal storage (`false`), like until now. 
Finally, note that this PR does not enable multiple sources for storage, tiles still need to be stored in the same database file on disk. The storage path, internal or external, is shared between the `NativeMapView` and the `OfflineManager` objects and, because it's a Manifest value, cannot be changed programmatically at runtime.
Fixes #5589.
/cc: @cammace @danswick @jfirebaugh @1ec5 @hjudge

Introduce a getDatabasePath() method that enables switching storage paths

---

src/mbgl/map/map.cpp

Fixes a bug where calculating a camera's padded bounds for a single point would cause division by zero, resulting in NaN for `minScale`. This invalid `minScale` would then be used to create an invalid padded `centerPixel`.
This was introduced by 8e30a4a0806e970e727c3563b8ed57dbaf9a0fa0 in #4285, where the scale and padding calculations were split.
The “Add Custom Callout Point” option in ios-app exercises this bug, where the map zooms in on a single annotation, à la:
```objc
[self.mapView showAnnotations:@[ oneSingularAnnotation ] animated:NO];
```
/cc @brunoabinader @1ec5

[core] Guard against camera's `minScale` being NaN

---

platform/ios/app/MBXViewController.m
platform/ios/app/Main.storyboard

Long pressing drops pins again. The minimum press duration has been extended to a second to avoid preempting the built-in gesture for draggable annotations.
/cc @frederoni

Reenable long tap to drop pins

---

include/mbgl/platform/platform.hpp
platform/android/platform.gyp
platform/android/src/asset_file_source.cpp
platform/android/src/run_loop.cpp
platform/android/src/thread.cpp
platform/darwin/src/nsthread.mm
platform/default/asset_file_source.cpp
platform/default/thread.cpp
platform/qt/platform.gyp
src/mbgl/platform/log.cpp
src/mbgl/util/thread.hpp

Still reduces scheduler priority for Android NDK API lower than 21 where SCHED_IDLE is not defined.
Fixes #5535

[core] Lower current scheduler priority if SCHED_IDLE is not supported

---

benchmark/parse/filter.cpp
include/mbgl/style/filter.hpp
include/mbgl/style/filter_evaluator.hpp
include/mbgl/util/feature.hpp
platform/darwin/test/MGLFeatureTests.mm
src/mbgl/annotation/shape_annotation_impl.cpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/style/bucket_parameters.cpp
test/style/filter.cpp

https://github.com/mapbox/mapbox-gl-style-spec/issues/391
Reroll of #5706 because Bitrise doesn't like branches named `$id`.

[core] Add support for $id key to filters

---

platform/ios/src/MGLMapView.mm

Compass, logo and attribution button new respects the map view's content inset.
👀 @1ec5 @friedbunny @boundsj

[ios] fixes #3697 compass, logo and attribution now respects insets

---

platform/darwin/src/MGLOfflineStorage.h
platform/darwin/src/MGLOfflineStorage.mm
platform/darwin/test/MGLOfflineStorageTests.m
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Added a property to MGLOfflineStorage that indicates the disk space occupied by all cached and offline resources.
Fixes the iOS side of #5580.
/cc @friedbunny @jfirebaugh @zugaldia

Offline storage size API

---

src/mbgl/util/mapbox.cpp
test/util/mapbox.cpp

When a style contains a sprite URL that is invalid, Mapbox GL Native crashes when the filename of the sprite URL does not contain a file extension.
```
#18. Crashed: DefaultFileSource
0  AppName                        0x1000effdc CLSProcessRecordAllThreads + 4296146908
1  AppName                        0x1000effdc CLSProcessRecordAllThreads + 4296146908
2  AppName                        0x1000f03fc CLSProcessRecordAllThreads + 4296147964
3  AppName                        0x1000e10c0 CLSHandler + 4296085696
4  AppName                        0x1000ee704 __CLSExceptionRecord_block_invoke + 4296140548
5  libdispatch.dylib              0x182fb947c _dispatch_client_callout + 16
6  libdispatch.dylib              0x182fc4728 _dispatch_barrier_sync_f_invoke + 100
7  AppName …
```

Crash when parsing invalid sprite URL

---

.travis.yml
platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.h
platform/node/CHANGELOG.md
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_debug.cpp

#5371 and #5534 add a second set of shaders for overdraw mode. We should completely disable this with `ifdefs` or so when we're building a release build for publication to avoid additional shader compilation overhead. Overdraw mode is a debugging tool and shouldn't be in the SDK.

Add ability to disable overdraw shaders 

---

platform/ios/CHANGELOG.md
platform/ios/scripts/package.sh

Fixes #5726 
Our release builds for device (with lipoed simulator binary) create a dSYM files for both the device and simulator. However the script only copied the device dSYM file to the output location.
This adds a step to create a dSYM file with all relevant architectures. 
cc @1ec5 @incanus

[ios] Add simulator dSYM file to build output.

---

platform/macos/CHANGELOG.md
platform/macos/app/Base.lproj/MainMenu.xib
platform/macos/app/MapDocument.m
platform/macos/src/MGLMapView.h
platform/macos/src/MGLMapView.mm

- Ported `showAnnotations:animated:` and `showAnnotations:edgePadding:animated:` from the iOS SDK.
- Added "Show All Annotations" debug menu item with ⇧⌘A shortcut key.
- Disabled "Add Animated Annotation" debug menu item when the annotation is already shown.
/cc @1ec5

[macos] Add `showAnnotations:` methods

---

platform/default/run_loop.cpp

UV_RUN_ONCE might block and that is not the semantics we expect from RunLoop::runOnce().

[default] uv_run should use UV_RUN_NOWAIT

---

platform/ios/src/MGLAnnotationImage.h
platform/ios/src/MGLCalloutView.h
platform/ios/src/MGLCompactCalloutView.h
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapViewDelegate.h
platform/ios/src/MGLUserLocation.h
platform/ios/src/MGLUserLocationAnnotationView.h

- Makes the use of apostrophes in the iOS SDK documentation consistent by converting “dumb” `'` into smart `’`.
- Adds ticks around class/property names/values.
- Breaks lines at 80 characters.
This isn’t strictly necessary, is probably rather pedantic, and it may mildly disturb a couple of @frederoni’s inflight PR’s, but let’s yank the bandaid off and do this all at once.
/cc @1ec5 @boundsj @frederoni @incanus

[ios] Reformat inline documentation with ticks, smart quotes, breaks

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapView.mm

- Limits view annotations to single-point annotations.
- Refactors iosapp’s test shapes into a separate function.
- Adds detail to the descriptions of individual shapes.
- Makes the holey shape square (rather than trapezoidal, as below).
In v3.3.x, it was possible for any annotation class to be assigned an annotation view. If your implementation of `-mapView:viewForAnnotation:` didn't check if `annotation` was a kind of `MGLPointAnnotation`, you could end up drawing view annotations for `MGLMultiPoint` subclasses, such as `MGLPolygon`:
As this fix uses the `MGLMultiPoint` superclass to exclude polygons and polylines, we will have to reevaluate if/when the proposed geometry class hierarchy changes in #5201 happen.
/cc @boundsj @1ec5 @incanus @frederoni

[ios] Do not allow multipoint annotations to be assigned views

---

include/mbgl/platform/default/glfw_view.hpp
platform/default/glfw_view.cpp

Added `addRandomLineAnnotations` as part of investigating #5763.

[glfw] Added 'addRandomLineAnnotations'

---

platform/android/src/jni.cpp

This PR creates brings `PushLocalFrame` in `listOfflineRegions` to avoid a local reference table overflow.
Fixes #5629
/cc: @jfirebaugh @danswick

Create a new local reference frame in JNI listOfflineRegions

---

.mention-bot

We added [mention-bot](https://github.com/facebook/mention-bot) to this repo recently, which attempts to automatically notify relevant reviewers when someone (apparently only those with commit powers?) submits a pull request.
This PR adds a config file to the repo that makes small changes to mention-bot’s behavior:
- Limit notifications to members of the Mapbox GitHub organization.
- Tweak the message a bit for concision and punctuation.
- Experimentally bump number of PR files checked from 5 to 10.
/cc @brunoabinader @1ec5

Add mention-bot config

---

platform/qt/include/qquickmapboxgl.hpp
platform/qt/qmlapp/main.qml
platform/qt/src/qquickmapboxgl.cpp
platform/qt/src/qquickmapboxglrenderer.cpp

Implements background `color` property for `QQuickMapboxGL` after runtime style API has been implemented (#837 and #5642).
Example:

[Qt] Implement QQuickMapboxGL color property

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLAnnotationView.mm

Fixes #5539. Allows non-dragging pan gestures that are initiated on view annotations to pan the underlying map.
(This PR is now filed against the v3.3.0 release branch and supersedes #5812.)
Annotation views each have long press and pan gesture recognizers. If a view is not draggable or not in a positive dragging state, the pan gesture recognizer should not begin. This commit makes the criteria for rejecting pans more strict — only `_panGestureRecognizer` should be rejected, not the entire `UIPanGestureRecognizer` class.
/cc @frederoni @1ec5

[ios] Limit annotation view pan gesture check to own recognizer

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Fixes #5571.
/cc @friedbunny @frederoni

Omit accuracy halo from annotation hit testing

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/jni.cpp
platform/android/src/jni.hpp
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

closes #5587. Merges into `5000-SurfaceView` of #5801.

[android] #5587 - SurfaceView compatible snapshot API

---

src/mbgl/style/layer_impl.cpp
src/mbgl/style/layer_impl.hpp
src/mbgl/style/style.cpp

[core] Respect minzoom and maxzoom properties

---

.travis.yml
platform/node/scripts/after_script.sh

Commit mapbox/mapbox-gl-native@29ee60a caused npm packages to be built in debug mode.
/cc @mikemorris

build and publish Node.js binaries with BUILDTYPE=Release

---

platform/macos/scripts/package.sh

Use `ditto` to avoid following symlinks when copying the framework into place.
Fixes #5818.
/cc @frederoni

Avoid following symlinks copying framework

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MultiPoint.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Polygon.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Polyline.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolylineActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_polygon.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_polyline.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/src/jni.cpp

closes #5663 #5662, refs #5224.
Still an issue with in #5844 but we have temp. workaround for this. 
cc @zugaldia @ivovandongen @cammace @bleege

5663 updatable shape annotations

---

platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

[core] Refcount the view activations

---

platform/node/DEVELOPING.md

Refs #4854
Realized this wasn't properly documented anywhere, would be good to get a less janky (automated) solution in place for publishing macOS binaries. Maybe switching back from `BITRISE_GIT_TAG` to `BITRISE_COMMIT` or something would work if Bitrise still doesn't run CI on tag pushes?
/cc @jfirebaugh @1ec5 @friedbunny for review, @miccolis

[node] add docs on publishing releases

---

platform/android/bitrise.yml

Fixes our daily snapshot build by adding the cmake dependency.

[android] - fix scheduled build with cmake dependency

---

platform/ios/src/MGLMapView.mm
platform/ios/src/MGLUserLocationAnnotationView.h
platform/ios/src/MGLUserLocationAnnotationView.m

Fixes #5571 (which wasn’t completely covered by #5816). Rather than try to exclude layers in the touch hit test, this specifically only checks against the main layer for the user dot or puck.
Essentially a back-port of e4a9173a2a5c585dda3fa7a0f955cff1552f8d25 from #5882.
/cc @1ec5 @frederoni

[ios] Hit test the user location annotation dot specifically (redone for release branch)

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/FeatureOverviewActivity.java

Noticed a bug that we can't open the activity when we already had accepted the permission.

[android] fix location permissions already accepted

---

platform/ios/src/MGLAPIClient.m

Fixes https://github.com/mapbox/mapbox-gl-native/issues/5924

[ios] Guard against nil data task

---

platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLAnnotationContainerView_Private.h
platform/ios/src/MGLMapView.mm

Fixes #5820 
This adjusts the tap point for the map's single tap gesture recognizer to use the coordinate to point translated point of the actual annotation the view represents. This fixes an issue where views that were offset in the point coordinate system were not selected when tapped since their associated annotations were actually at the origin of the offset.
An alternative would've been to use a gesture recognizer on each view but we've already stated that we don't want to go down that route since it would not work well with the existing logic we have for handling single taps and finding annotations near those taps.
Note: as before, if a mixture of annotations views with and without centerOffset is used, the selection behavior may look strange due to the cycling logic we use to …

[ios] Account for center offset when tapping annotation views

---

platform/ios/ios.xcodeproj/project.pbxproj

iOS SDK v3.3.x included [NSData+MGLAdditions.h](https://github.com/mapbox/mapbox-gl-native/blob/c354ae523a00b4c0e0577c4784b53553ea1a1cb7/platform/darwin/src/NSData%2BMGLAdditions.h) in its dynamic framework package, in a “PrivateHeaders” folder:
This private category on NSData is for gzip compression, which is only used internally.
The file was not included in the static framework. Somewhat counterintuitively, marking headers “Private” still includes the files in packaged builds — one must mark files “Project” to exclude them:
/cc @frederoni

[ios] Exclude NSData category's header from dynamic framework

---

include/mbgl/map/map.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/jni.cpp
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm
src/mbgl/annotation/annotation_manager.cpp
src/mbgl/annotation/annotation_manager.hpp
src/mbgl/annotation/annotation_tile.cpp
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/annotation/shape_annotation_impl.cpp
src/mbgl/annotation/symbol_annotation_impl.cpp
src/mbgl/map/map.cpp
test/api/annotations.cpp

`queryPointAnnotations()` accepts a screen rectangle instead of a geographic bounding box. If you pass in the bounds (in screen coordinates) of a rotated, tilted map view, the query is restricted to the trapezoidal region visible in the map view.
Fixes #5151.
@jfirebaugh to review the C++ side. @tobrun to review the Java side, which I edited blind without a Java IDE. 😬

Replace getPointAnnotationsInBounds() w/ queryPointAnnotations()

---

test/api/annotations.cpp

This fixes the travis error we are seeing (i.e. https://travis-ci.org/mapbox/mapbox-gl-native/jobs/151947796) from a test added in https://github.com/mapbox/mapbox-gl-native/pull/5165
cc @1ec5

[core] Compare unsigned int to unsigned int to pass tidy check

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Corrects implementation of #5165 for Android. 
We need to take in account screen density when we query for annotations.

[android] - make query point annotations depend on screendensity

---

platform/darwin/test/MGLOfflineStorageTests.m

XCTest apparently no longer executes tests in alphabetical order, so naming the test `testAAALoadPacks` doesn’t ensure it gets run first. Instead, put the pack loading test inside `-setUp`, but also put it inside a `dispatch_once()` block to ensure that it only gets run before the first offline storage test that gets run in the current process.
Fixes #6006.
/cc @friedbunny @boundsj

Replace testAAALoadPacks with a setUp method

---

platform/darwin/src/NSURL+MGLAdditions.h
platform/darwin/src/NSURL+MGLAdditions.m
platform/ios/CHANGELOG.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/src/MGLMapView.mm

It turns out that `mbgl::AssetFileSource` supports absolute file URLs in addition to relative file URLs. So replace the file: scheme with asset: while percent-escaping as necessary.
Also added amsterdam.geojson to macos.xcodeproj for consistency with ios.xcodeproj.
Fixes #3505.
/cc @frederoni

Accept absolute file paths as style URLs

---

include/mbgl/storage/resource.hpp
include/mbgl/style/conversion/tileset.hpp
include/mbgl/util/tileset.hpp
package.json
platform/default/mbgl/storage/offline_download.cpp
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
src/mbgl/storage/resource.cpp
src/mbgl/tile/tile_loader_impl.hpp
test/map/map.cpp
test/storage/offline_database.cpp
test/storage/offline_download.cpp
test/storage/resource.cpp

Hi,
We want to provide our own raster overlay for a certain area but MapBox flips the y coordinate while our tile service does not. We are providing a `style.json` and a `tileset.json` file like this:
style.json
{
"version": 7,
"sources": {
"simple-tiles": {
"type": "raster",
"url": "http://localhost:9000/tileset.json",
"tileSize": 256
}
},
"layers": [
{
"id": "background",
"type": "background",
"paint": {
"background-color": "rgb(140,215,225)"
}
},
{
"id": "simple-tiles",
"type": "raster",
"source": "simple-tiles"
}
]
}
tileset.json
{
"tiles": [
"http://localhost:9000/proxy.php?z={z}&x={x}&y={y}"
],
"tilejson": "2.1.0",
"scheme": "tms"
}
The proxy-php currently only flips the y-coordinate back, we want to get rid of the proxy.php file. How can we achieve non-flipped-y tile loading?

Raster tile overlay with TMS coordinates (non-flipped Y)

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxCountActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxHighlightActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesPropertiesActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_query_features_box.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_query_features_point.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/src/conversion/collection.hpp
platform/android/src/conversion/constant.hpp
platform/android/src/conversion/conversion.hpp
platform/android/src/geometry/conversion/feature.hpp
platform/android/src/geometry/conversion/geometry.hpp
platform/android/src/jni.cpp
platform/android/src/jni/local_object.hpp

5869 android query rendered features

---

platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLBackgroundStyleLayer.mm
platform/darwin/src/MGLBaseStyleLayer.h
platform/darwin/src/MGLBaseStyleLayer.mm
platform/darwin/src/MGLBaseStyleLayer_Private.hpp
platform/darwin/src/MGLCircleStyleLayer.mm
platform/darwin/src/MGLFillStyleLayer.mm
platform/darwin/src/MGLLineStyleLayer.mm
platform/darwin/src/MGLRasterStyleLayer.mm
platform/darwin/src/MGLStyleLayer.mm.ejs
platform/darwin/src/MGLSymbolStyleLayer.mm
platform/ios/app/MBXViewController.m

Fixes #5957 by introducing an automatic call to `-[MGLBaseStyleLayer update]` for all setters. 
https://github.com/mapbox/mapbox-gl-native/issues/6017 tracks a more efficient transaction block mechanism, which doesn't necessarily have to be a part of the same release. 
/cc @frederoni @1ec5

iOS immediate style 😎

---

platform/ios/src/MGLFaux3DUserLocationAnnotationView.m

User location annotation performance wasn’t bad previously, but there are some small tweaks we can make to improve both perceived and actual performance.
This PR is proposed against `5039-MGLUserLocationAnnotationView-refactor` until #5882 lands. We can now [change the base branch of existing pull requests](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request), so I’ll try that out before merging this.
The biggest improvement is to the accuracy ring: instead of queueing up implicit animations while zooming, now we only animate changes to the ring’s size (i.e., when the horizontal accuracy changes). This fixes the wobbling effect you could see at the edges of the ring when zooming.
We’re able to disable the implicit animation during zooms because we already update the user …

Improve user location annotation performance

---

INSTALL.md
platform/darwin/src/MGLCompassDirectionFormatter.h

1. iOS docs bug reported via user. 
1. Update dependencies for CMake since https://github.com/mapbox/mapbox-gl-native/pull/5359 landed. (look ok @kkaefer?)

minor docs updates

---

platform/qt/include/QQuickMapboxGLStyle
platform/qt/include/qmapboxgl.hpp
platform/qt/include/qquickmapboxgl.hpp
platform/qt/include/qquickmapboxglstyle.hpp
platform/qt/include/qquickmapboxglstyleproperty.hpp
platform/qt/qmlapp/main.cpp
platform/qt/qmlapp/main.qml
platform/qt/qt5.cmake
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qquickmapboxgl.cpp
platform/qt/src/qquickmapboxglrenderer.cpp
platform/qt/src/qquickmapboxglrenderer.hpp
platform/qt/src/qquickmapboxglstyle.cpp
platform/qt/src/qquickmapboxglstyleproperty.cpp
platform/qt/src/qt_conversion.hpp

This PR introduces a new QML item: `QQuickMapboxGLStyle`. This item is responsible for managing the Mapbox GL style, as seen on the QML example below:
```qml
...
MapboxMap {
style: MapboxStyle {
id: styleStreets
style: "mapbox://styles/mapbox/streets-v9"
}
...   
```
~~Now every `QQuickMapboxGLStyleProperty` can be a child item of either `QQuickMapboxGL` or `QQuickMapboxGLStyle`.~~ (as per discussion with @tmpsantos, we felt like style properties should only be children of the style to simplify the API).
A `QQuickMapboxGLStyleProperty` being a child of `QQuickMapboxGLStyle` assures that only properties associated with that particular style will reflect on the map - and that happens only when the style is the current set via `style` property.
Other changes in this PR includes:
- Invert …

[Qt] Added QQuickMapboxGLStyle

---

platform/darwin/src/MGLGeoJSONSource.h
platform/darwin/src/MGLGeoJSONSource.mm
platform/ios/app/MBXViewController.m
platform/macos/app/Base.lproj/MainMenu.xib
platform/macos/app/Base.lproj/MapDocument.xib
platform/macos/app/MapDocument.m

MGLGeoJSONSource can now be initialized with GeoJSON data. Replaced the `data` property with a `geoJSONData` property and added `features` and `URL` properties alongside it. Each property may be set or unset based on how the object was initialized.
Along the way, this change replaces the Dropbox-hosted fixture with a local GeoJSON document for the runtime styling demos in iosapp and macosapp. The runtime styling demo has been renamed “Manipulate Style”, and in macosapp it has been moved from the context menu to the Debug menu.
Fixes #5965, fixes #5966, fixes #6021, fixes #6022, fixes #6024. Depends on #6026.
/cc @frederoni

More MGLGeoJSONSource options

---

include/mbgl/style/sources/geojson_source.hpp
include/mbgl/style/sources/raster_source.hpp
include/mbgl/style/sources/vector_source.hpp

Adds some template instances to use with `Source.is()`

[core] add template instances for Source.is<>().

---

Makefile
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/style/RuntimeStyleTests.java
platform/android/bitrise.yml
platform/android/scripts/generate-test-code.js

**tl;dr**: Integrates Google Firebase device lab into Bitrise
Closes #5211, For each commit pushed to this repo, our CI will run tests on Firebase device lab. 
Benefit of his approach is that these tests are deployed on a real device but as downside it also increases the android build time from 10 -> 17 minutes with 4 minutes of actual device testing. 
This PR includes:
- added make target for generating debug and test apks
- auth with Google service account credentials from bitrise configuration
- auth with dev map accesstoken from bitrise configuration
- runs tests on firebase device lab
- fails the build a test test fails
- ignored some tests that were failing
- excluded locational test activities from test generation
Review @ivovandongen / @zugaldia ?

[android] #5211 - run UI tests in our CI workflow

---

platform/macos/config.cmake

#5359 [increased](https://github.com/mapbox/mapbox-gl-native/blob/112789a76111d4dd38e50c73ae1e81e5c53dd59c/platform/macos/config.cmake#L1) the minimum deployment target for mbgl libraries from OS X 10.10.0 to OS X 10.11. The SDK targets’ minimum deployment target [remains](https://github.com/mapbox/mapbox-gl-native/blob/112789a76111d4dd38e50c73ae1e81e5c53dd59c/platform/macos/macos.xcodeproj/project.pbxproj#L1228) at OS X 10.10.0. For consistency, if not for compatibility, the mbgl libraries’ minimum deployment targets should be reduced back to OS X 10.10.0.
/cc @kkaefer

macOS minimum deployment target excludes OS X 10.10.0

---

include/mbgl/map/map.hpp
src/mbgl/map/map.cpp
src/mbgl/style/parser.cpp
src/mbgl/style/parser.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
test/style/style.cpp

[`mbgl::style::Parser::parse()`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/parser.cpp#L23) should parse the [`name`](https://www.mapbox.com/mapbox-gl-style-spec/#root-name) and [`metadata`](https://www.mapbox.com/mapbox-gl-style-spec/#root-metadata) root properties out of the style JSON and expose them with accessors on the `mbgl::style::Style` class. The SDK could read the name of the style aloud in accessibility contexts.
Similarly, root properties such as [`center`](https://www.mapbox.com/mapbox-gl-style-spec/#root-center) and [`zoom`](https://www.mapbox.com/mapbox-gl-style-spec/#root-zoom) may be useful for establishing a default viewport for the style other than the Null Island default used in the SDK currently. This would enable the developer to set the …

Parse and expose more style JSON root properties

---

include/mbgl/map/mode.hpp
platform/default/glfw_view.cpp
platform/macos/app/Base.lproj/MainMenu.xib
platform/macos/app/MapDocument.m
platform/macos/src/MGLMapView.h
platform/macos/src/MGLMapView.mm
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_debug.cpp

We are [showing the stencil buffer](https://github.com/mapbox/mapbox-gl-native/pull/4669) in the debug app, but there's no way to show the depth buffer.

Add option to show depth buffer

---

platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLBaseStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLRasterStyleLayer.h
platform/darwin/src/MGLStyleLayer.h.ejs
platform/darwin/src/MGLSymbolStyleLayer.h

This PR improves the runtime styling API’s generated documentation in several ways:
* Source and layer headers have been audited for nullability. Properties representing optional attributes are qualified with `null_resettable`. The default value is stated in documentation. (Fixes #5945.)
* References to other attributes now use camelCase for consistency with the Objective-C/Swift property rather than kebab-case as defined in the style specification. (Fixes #5951.)
* References to valid enumeration values are expanded into the full Objective-C symbol name for clarity. (Fixes #5949.)
* Documentation expresses screen distances in points instead of pixels. (Fixes #5950.)
* The documentation for each numeric property indicates its unit.
* Interdependencies between properties are described in …

Expand and clean up runtime styling documentation

---

platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLBaseStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLRasterStyleLayer.h
platform/darwin/src/MGLStyleAttribute.mm
platform/darwin/src/MGLStyleAttributeFunction.h
platform/darwin/src/MGLStyleAttributeFunction.mm
platform/darwin/src/MGLStyleAttributeValue_Private.h
platform/darwin/src/MGLStyleLayer.h.ejs
platform/darwin/src/MGLSymbolStyleLayer.h
platform/darwin/src/NSArray+MGLStyleAttributeAdditions.mm
platform/darwin/src/NSValue+MGLStyleAttributeAdditions.mm
platform/darwin/src/NSValue+MGLStyleAttributeAdditions_Private.h
platform/darwin/test/MGLRuntimeStylingHelper.m

An offset style attribute is now exposed publicly as an NSValue representing a `CGVector` instead of an NSArray of NSNumbers. Likewise, a padding style attribute is now exposed publicly as an NSValue representing an `NSEdgeInsets` or `UIEdgeInsets` instead of an NSArray of NSNumbers.
This change also fixes round-tripping of padding values due to a difference between the style specification and Foundation regarding the order of edges around a box. It uses a designated initializer on `NSEdgeInsets`/`UIEdgeInsets` to ensure correct order when converting from C++ to Objective-C.
Fixes #5947, fixes #6065. Depends on #6076.
/cc @frederoni

Offsets as vectors, padding as edge insets

---

platform/ios/scripts/release-fabric.sh
platform/ios/scripts/validate-fabric-zip.sh

This adds a script that automates the process of uploading the required build output to Fabric. It requires the `FABRIC_KIT_API_KEY` env variable and another new script called `validate-fabric-zip.sh`.

[ios] Automate upload of build output to Fabric

---

platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.h

This PR fixes a typo in the generated documentation for color properties in the runtime styling API. It also aliases RGB 0, 0, 0 to `+[NSColor blackColor]` / `+[UIColor blackColor]`.
/cc @frederoni

Copyedit default color property documentation

---

platform/android/MapboxGLAndroidSDK/proguard-rules.pro

Closes #6077 
I was able to proguard the testapp with this configuration. Would love some 👀 . 
You can retest this with adding the following in our build.gradle of the testapp:
```
buildTypes {
debug {
// run code coverage reports
testCoverageEnabled = true
minifyEnabled true
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
```
Review @cammace, @bleege

[android] #6077 - keep rules for Signature and Annotation

---

cmake/glfw.cmake
cmake/node.cmake
cmake/offline.cmake
cmake/render.cmake
cmake/test.cmake

Currently, only `mbgl-core` and `mbgl-loop` have calls to `create_source_groups`, which files all of the source files into the correct groups so they appear as a folder structure in Xcode. This patch adds those calls to all other targets that have source files as well.

Add CMake source groups for the rest of the targets

---

platform/default/mbgl/storage/offline_database.cpp
platform/default/mbgl/storage/offline_database.hpp
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
test/storage/offline_database.cpp

This pull request changes our offline/ambient cache database schema to use write-ahead logging and normal sync, which greatly increases the speed that resources can be written and read.
SQLite offers several [journal modes](https://www.sqlite.org/pragma.html#pragma_journal_mode) — we were using the default, `DELETE`, which continuously writes a “rollback journal” that is then deleted at the end of the transaction. This mode offers good data safety and is [atomic](https://www.sqlite.org/atomiccommit.html), but is subsequently somewhat slow.
[Write-head logging](https://www.sqlite.org/wal.html) (`WAL`) is a different type of journaling that offers better performance but marginally reduced data safety. WAL effectively writes to a separate cache and periodically flushes back to the main …

[core] Update SQLite schema with WAL journal mode and normal sync

---

platform/ios/src/MGLFaux3DUserLocationAnnotationView.m

Subtly improves the performance of the dot/puck’s shadow by disabling its implicit animation — it no longer lags behind when you’re executing the pitch gesture.
Follows on from #6019.
/cc @1ec5

Disable implicit animation of user annotation pitch changes

---

platform/darwin/src/MGLTypes.h
platform/ios/src/MGLMapView.h
platform/macos/src/MGLMapView.h

~~This brings the depth buffer (#6087) and stencil buffer (#4669) debug modes to iOS~~ by moving `MGLMapDebugMaskOptions` to MGLTypes.h, which is shared between macOS and iOS targets.
~~These alternative buffer modes aren’t exposed in iosapp, but they are available in code.~~ These modes are excluded from iOS per https://github.com/mapbox/mapbox-gl-native/pull/6094#issuecomment-241101240.
The main advantage of this PR is now that we have slightly less duplicate code. 😁
/cc @kkaefer @1ec5

[ios, macos] Move debug mask options to shared header

---

platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm

Fixed an issue in which a map view that doesn’t occupy the entire window would consider its center point to be the window’s center point rather than the view’s.
/ref #4504

Avoid negative content insets

---

platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.h

Distinguish between `{NS,UI}Color.blackColor` and `{NS,UI}Color.clearColor` in documentation comments for runtime styling API properties. In #6124, generate-style-code.js has the same special cases for clear, black, and white.
/cc @frederoni

Distinguish between blackColor and clearColor

---

include/mbgl/platform/default/headless_view.hpp
platform/default/headless_view.cpp
src/mbgl/map/map.cpp
src/mbgl/style/observer.hpp
src/mbgl/style/parser.cpp
src/mbgl/style/parser.hpp
src/mbgl/style/style.cpp
test/fixtures/style_parser/non-object.info.json
test/map/map.cpp
test/src/mbgl/test/util.hpp
test/style/style_parser.cpp

Currently this signal is never emitted, which can cause the Still mode to starve in case of an invalid style or failed request.

[core] Emit MapChangeDidFailLoadingMap when the style cannot be loaded or parsed

---

platform/darwin/src/MGLStyle.h
platform/darwin/src/MGLStyle.mm
platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm

This is a followup to #6002 that exposes the current style’s name and makes `-[MGLMapView resetPosition]` reset to the style’s default viewport rather than the SDK default.

Expose name and default position of current style

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapViewDelegate.h
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm
platform/macos/src/MGLMapViewDelegate.h

Documented `-[MGLMapViewDelegate mapViewDidFailLoadingMap:withError:]` on iOS and ported the declaration and call site over to macOS. Also mentioned the sudden new use of this API in the changelogs.

Document -mapViewDidFailLoadingMap:withError:

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLFaux3DUserLocationAnnotationView.m

This change removes the 1.5× exaggeration of the user location annotation’s heading indicator.
Also cleaned up some of the heading mask calculations while I was at it.
Fixes #3718.
/cc @1ec5

Stop exaggerating heading accuracy indicator size

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/build.gradle

This PR removes dependencies on MAS SNAPSHOT versions. It also brings down the SDK dependency from `mapbox-android-services` to `mapbox-java-services` as none of the Android-specific code is currently used by the SDK.
Fixes #6148.
/cc: @ivovandongen

Update MAS dependencies to v1.3.0

---

platform/node/src/node_map.cpp
platform/node/test/js/map.test.js

[node] Throw on invalid style JSON

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLAnnotationView.mm

I unearthed a bug where trying to set an annotation view `transform` of your own gets rapidly reset nearly every frame while annotation view `center` is changing due to the `CATransform3DIdentity` that is repeatedly set in our `setCenter:` override. 
One case this doesn't cover is when you _do_ have draggable views but still want to set a `transform`. Perhaps we could create an alternate setter called `setCenterDuringAnnotationUpdate:` which is called by `-[MGLMapView updateAnnotationViews]` to bypass any of this drag-related `transform` setting entirely? 
@1ec5 @friedbunny @boundsj

avoid altering annotation view transforms set by user

---

platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapViewDelegate.h

Prior to v3.4.0, a developer could indiscriminately return any UIView-conforming object in `mapView:viewForAnnotation:` and everything would be fine. With custom user location annotation views, we now also pass in a `MGLUserLocation` annotation, which requires a view that conforms to `MGLUserLocationAnnotationView`.
This pull request ignores views that the developer nominated for the user location annotation view that are not actually a kind of `MGLUserLocationAnnotationView`. This changes the alpha.2 behavior of asserting when the inheritance was wrong. When we ignore a view, the default user dot is used in its stead.
I’ve also documented that `mapView:viewForAnnotation:` can be used to customize the user location annotation view, because this is a somewhat unexpected new behavior.
Fixes …

Ignore non-conforming user location annotation views

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java

closes #5875 
We weren't correctly parceling drawable related to MyLocationView. This resulted in "not" showing the MyLocationView interaction with fragments. This is the item mentioned in the Friday meeting that was supposably a blocker for release.
cc @zugaldia

[android] #5875 - MapboxMap options not parceling drawables

---

platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/gradle-spoon.gradle
platform/android/build.gradle

This PR adds the spoon gradle plugin to the project. We now have a separate gradle command for executing instrumentation tests on multiple devices at once. This is handy if you have a setup as:
This new gradle configuration conforms to the guidelines set in https://github.com/mapbox/mapbox-gl-native/issues/6009.

[android] add spoon gradle plugin

---

platform/ios/src/MGLMapView.mm

Previously, annotations backed by sprite had their frames updated by the view backed annotation update method. This guards against that by aborting an update for an annotation if an associated
view cannot be found.
In addition, some dead code is removed.
Fixes #5787 
cc @incanus

[ios] Avoid updating sprite backed annotations in view update method

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Fixes #3778 
Subsumes #4067 
This pulls just https://github.com/mapbox/mapbox-gl-native/pull/4067/commits/ccbdeaa451c7ec125e5b7b7af0f4eaa32ac8cce8 from https://github.com/mapbox/mapbox-gl-native/pull/4067 to fix the issue where the map did not correctly update to reflect the centerOffset when the user location was being tracked.

Use contentInset to set center coordinate for contentInset updates

---

platform/ios/INSTALL.md
platform/ios/docs/pod-README.md

- Adds -ObjC flag for static lib.
- Fixes link to iOS SDK site.
- Pushes CocoaPods down the list.
- Changes CocoaPods to use local path, not HTTP.
- Emphasizes that INSTALL.md is only for custom builds.
Fixes #6195.
/cc @1ec5

Update INSTALL doc for -ObjC; use local podspec path

---

platform/macos/config.cmake

**Platform: node**
**Mapbox SDK version: master**
1. `git clone mapbox-gl-native...`
2. `cd mapbo-gl-native`
3. `npm install --build-from-source`
Building `node-mapbox-gl-native`
Errors on gyp:
```
bobby mapbox-gl-native (master) $ npm install --build-from-source
> mapbox-gl-native@3.3.2 preinstall /path/mapbox-gl-native
> npm install node-pre-gyp
node-pre-gyp@0.6.29 node_modules/node-pre-gyp
├── semver@5.2.0
├── nopt@3.0.6 (abbrev@1.0.9)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── tar@2.2.1 (block-stream@0.0.9, inherits@2.0.1, fstream@1.0.10)
├── rc@1.1.6 (ini@1.3.4, deep-extend@0.4.1, strip-json-comments@1.0.4, minimist@1.2.0)
├── tar-pack@3.1.4 (uid-number@0.0.6, once@1.3.3, readable-stream@2.1.4, fstream@1.0.10, debug@2.2.0, fstream-ignore@1.0.5)
├── rimraf@2.5.4 (glob@7.0.5)
├── …
```

[node] Cannot build from source

---

platform/ios/src/MGLAnnotationView.mm
platform/ios/src/MGLUserLocationAnnotationView.m

We were disabling the implicit animation of `position` changes for annotation views (bb2f627 in #5550), but this meant that UIView animations were also being canceled. Once the user location annotation started inheriting from MGLAnnotationView, this meant that non-tracking changes to the user dot became unanimated.
This change shouldn’t affect the sync between map view and annotation views, as we already disable implicit animations when we update their position in [-[MGLMapView updateAnnotationViews]](https://github.com/mapbox/mapbox-gl-native/blob/c075386a984cd5de21f6201341d360a5c1039b67/platform/ios/src/MGLMapView.mm#L4548).
This also removes redundant implicit animation disabling in MGLUserLocationAnnotationView.
@incanus, I could definitely use some help confirming that this doesn’t …

Allow implicit animation of annotation views

---

platform/ios/INSTALL.md
platform/ios/Mapbox-iOS-SDK-static-part.podspec

Added the `-ObjC` flag to the static podspec, per @frederoni in https://github.com/mapbox/mapbox-gl-native/pull/6213#issuecomment-243693614. This is a mixed bag (because CocoaPods is CocoaPods) and still requires the user to add an extra build flag:
```
[!] The `firststepsstatic [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-firststepsstatic/Pods-firststepsstatic.release.xcconfig'. This can lead to problems with the CocoaPods installation
- Use the `$(inherited)` flag, or
- Remove the build settings from the target.
```
Also rewrote the custom build CocoaPods instructions to reflect the changes in https://github.com/mapbox/mapbox-gl-native/pull/5653.
Fixes #6195, refs #6213.
/cc @1ec5 @frederoni

Add -ObjC to static podspec; update custom CocoaPods steps

---

CMakeLists.txt

Upgrades to latest protozero release. This ensures that upcoming PRs do not need to suppress extra warnings (when we start using new headers inside protozero for `protozero::dataview`).

Upgrade to protozero 1.4.2

---

platform/ios/test/MGLAnnotationViewTests.m

The annotation view test uses a fake MGLTestCalloutView that declares conformance to the MGLCalloutView protocol. However, several properties and a method were not implemented in the test which caused several warnings that were visible if you compiled the SDK tests. This change stubs out the properties and method so the warnings go away.
cc @frederoni @1ec5

[ios] Silence MGLCalloutView related warnings in tests

---

platform/darwin/src/MGLBaseStyleLayer_Private.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.mm
platform/darwin/src/MGLFeature.mm
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.mm
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLLineStyleLayer.mm
platform/darwin/src/MGLStyleLayer.h.ejs
platform/darwin/src/MGLStyleLayer.mm.ejs
platform/darwin/src/MGLSymbolStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.mm
platform/darwin/src/MGLValueEvaluator.h
platform/darwin/src/NSComparisonPredicate+MGLAdditions.h
platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm
platform/darwin/src/NSCompoundPredicate+MGLAdditions.h
platform/darwin/src/NSCompoundPredicate+MGLAdditions.mm
platform/darwin/src/NSExpression+MGLAdditions.h
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/src/NSPredicate+MGLAdditions.h
platform/darwin/src/NSPredicate+MGLAdditions.mm
platform/darwin/test/MGLFilterTests.mm
platform/darwin/test/MGLStyleLayerTests.xib
platform/darwin/test/amsterdam.geojson
platform/ios/app/MBXViewController.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/app/MapDocument.m
platform/macos/macos.xcodeproj/project.pbxproj

MGLStyleLayer predicates (filters)

---

platform/darwin/src/MGLGeoJSONSource.h
platform/darwin/src/MGLVectorSource.h

Clang/Sourcekitten [do not appear to like](https://gist.github.com/friedbunny/3699634f9a0dcf26f21305adb5bdfbc2) HTML tags in `@param` definitions. I’ve moved the HTML links into the body of the method documentation.
Also:
- Wraps lines at 80 chars.
- Adds minimal docs for MGLGeoJSONSource so it will be seen by jazzy.
/cc @1ec5 @boundsj @incanus

Fix jazzy doc generation failure and document MGLGeoJSONSource

---

src/mbgl/annotation/annotation_source.cpp
src/mbgl/annotation/annotation_source.hpp
src/mbgl/map/map.cpp
src/mbgl/style/source_impl.cpp
src/mbgl/style/source_impl.hpp
src/mbgl/style/sources/geojson_source_impl.cpp
src/mbgl/style/sources/geojson_source_impl.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
src/mbgl/style/tile_source_impl.cpp
src/mbgl/style/tile_source_impl.hpp
src/mbgl/style/update_parameters.hpp
test/style/source.cpp

There are some very generic terms like `update` used in `Source` member functions names. Instead, we should explicitly name these functions after what they are updating.

Improve naming in Source

---

platform/android/bitrise.yml
platform/android/scripts/generate-test-code.js

Closes #6218: adds the test results from Firebase test lab as an artefact to the Android Bitrise job.

[android] - get firebase test lab results with gsutil

---

package.json
platform/node/index.js
platform/node/src/node_map.cpp
platform/node/src/node_map.hpp
platform/node/src/node_request.cpp
platform/node/test/js/map.test.js
platform/node/test/memory.test.js
platform/node/test/suite_implementation.js

Resurrects #5527, but with a JavaScript shim in front to preserve the callback-passing public API.
/cc @tmpsantos @jfirebaugh @miccolis

NodeRequest member function instead of v8::Context

---

platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLBackgroundStyleLayer.mm
platform/darwin/src/MGLBaseStyleLayer.mm
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.mm
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.mm
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLLineStyleLayer.mm
platform/darwin/src/MGLRasterStyleLayer.h
platform/darwin/src/MGLRasterStyleLayer.mm
platform/darwin/src/MGLRuntimeStylingTests.m.ejs
platform/darwin/src/MGLStyleLayer.h
platform/darwin/src/MGLStyleLayer.h.ejs
platform/darwin/src/MGLStyleLayer.mm.ejs
platform/darwin/src/MGLSymbolStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.mm
platform/darwin/test/MGLBackgroundStyleLayerTests.m
platform/darwin/test/MGLCircleStyleLayerTests.m
platform/darwin/test/MGLFillStyleLayerTests.m
platform/darwin/test/MGLFilterTests.mm
platform/darwin/test/MGLLineStyleLayerTests.m
platform/darwin/test/MGLRasterStyleLayerTests.m
platform/darwin/test/MGLSymbolStyleLayerTests.m
platform/ios/app/MBXViewController.m
platform/macos/app/MapDocument.m

Previously, we declared MGLStyleLayer initializers in the MGLStyleLayer protocol as optional methods. In the generated implementation, this made it easier to opt in and out of initializers that did or or did not make sense for the subclass. However, this approach was dangerous since it was easy for an application developer to initialize an MGLStyleLayer subclass with an init method that was actually not implemented in that class causing an exception at runtime.
This commit moves the init methods that each subclass supports to each subclass so xcode (and the compiler) help the developer avoid the previously possible runtime exception.
In addition, a new init method is added that takes the source layer and passes that on to `mbgl::style:Layer` (but only on classes where this is possible in …

[ios, macos] Put MGLStyleLayer inits in respective classes

---

platform/default/sqlite3.cpp
platform/default/sqlite3.hpp

Implements [SQLite error logging](http://www.sqlite.org/errlog.html) in a very verbose fashion — for now, everything gets logged. As we see what comes down the tube, we can selectively silence common or irrelevant messages.
**Notes**
- `sqlite3_config()` must be called [before the database is initialized](http://www.sqlite.org/c3ref/config.html) (which happens automatically via `sqlite3_open_v2()`).
- I’m very unconfident about my type choices, would appreciate feedback.
Fixes #6267.
/cc @jfirebaugh @kkaefer @tobrun

Implement SQLite error logging

---

platform/default/sqlite3.cpp
platform/default/sqlite3.hpp

Fixes the `SQLITE_MISUSE` warning on the first launch of an app — half of #6295.
Follows-up on the initial SQLite logging implementation in #6291.

Move SQLite logging setup to before database initialization

---

include/mbgl/map/map.hpp
platform/darwin/src/MGLStyle.mm
platform/default/glfw_view.cpp
platform/qt/app/mapwindow.cpp
platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapboxgl.cpp
src/mbgl/map/map.cpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
test/map/map.cpp

Fixes #6118.
- Updated GLFW and darwin API usage accordingly

Move class handling to Style

---

cmake/core-files.cmake
cmake/test-files.cmake
include/mbgl/storage/response.hpp
include/mbgl/util/chrono.hpp
include/mbgl/util/constants.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/src/http_file_source.cpp
platform/android/src/jni.cpp
platform/darwin/src/http_file_source.mm
platform/default/http_file_source.cpp
platform/default/online_file_source.cpp
platform/qt/src/http_request.cpp
src/mbgl/storage/response.cpp
src/mbgl/util/chrono.cpp
src/mbgl/util/http_header.cpp
src/mbgl/util/http_header.hpp
src/mbgl/util/http_timeout.cpp
src/mbgl/util/http_timeout.hpp
test/storage/online_file_source.cpp
test/storage/server.js
test/util/http_timeout.cpp

[core] rate limit handling on online file source

---

src/mbgl/tile/tile_worker.cpp

This provides temporary prevention for crashing due to #6263, which will hopefully help stabilize our Android builds prior to stuff like #1471 landing.
Instead of a crash, the race condition will produce a blank tile. Note that the race is run only if a layout property or filter is modified. I don't see any way for it to be triggered in other scenarios. So it won't become a possible cause of "blank tiles" in general.

[core] Band-aid to prevent GeometryTile::redoLayout race condition from causing a crash

---

platform/ios/src/MGLMapView.mm

This reverts a previous change that used only the `contentInset` when setting the center coordinate of the map view. Instead of `contentInset`, `edgePaddingForFollowing` is now used again. This fixes
the regression introduced in https://github.com/mapbox/mapbox-gl-native/pull/6216 that caused the user dot annotation to be misplaced when the map was configured to show the annotation in any place other than in the center of the map.
In addition, `edgePaddingForFollowing` is updated to account for `contentInset` when it calculates its `UIEdgeInsets`. This fixes a bug where the user dot would move to the center of the content frame
(when it was adjusted for content insets) but the map would not scroll along with it yielding the effect of the user dot being misplaced.
Fixes #6257 
Reverts …

Use content inset to calculate edge padding

---

cmake/core-files.cmake
src/mbgl/layout/symbol_layout.cpp
src/mbgl/layout/symbol_layout.hpp
src/mbgl/renderer/bucket.hpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/renderer/symbol_bucket.hpp
src/mbgl/style/bucket_parameters.hpp
src/mbgl/style/layers/symbol_layer_impl.cpp
src/mbgl/style/layers/symbol_layer_impl.hpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/tile_worker.cpp
src/mbgl/tile/tile_worker.hpp
src/mbgl/util/clip_lines.cpp
src/mbgl/util/clip_lines.hpp
src/mbgl/util/merge_lines.hpp
src/mbgl/util/worker.cpp
src/mbgl/util/worker.hpp

I still need to debug this, but I want to get @ansis and @kkaefer 👀  on it as soon as possible.
This PR splits `SymbolBucket` in two. The new class `SymbolLayout` lives on the worker thread only and contains the persistent data needed for repeated placement. `SymbolBucket` contains the data generated during placement, and is transferred to the main thread for rendering.
This eliminates the risky sharing of `GeometryTile::buckets` between the main thread and worker thread during `TileWorker::redoPlacement`. `SymbolBucket::swapRenderData` is no longer necessary.
While here, rationalize the names of states a `SymbolLayout` may be in:
* `Pending`: Waiting for the necessary glyphs or icons to be available.
* `Prepared`: The potential positions of text and icons have been determined.
* …

[core] Extract SymbolLayout from SymbolBucket

---

src/mbgl/style/class_dictionary.hpp
test/src/mbgl/test/conversion_stubs.hpp

The build is currently broken in GCC 5 after https://github.com/mapbox/mapbox-gl-native/pull/6324 due to a missing `std::hash` specialization for `mbgl::style::ClassID`, which doesn't automatically use the underlying enum type's `hash` implementation.
/cc @bleege

Fix broken compile on GCC

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java

Disabling closable strictmode since they make our [tests flaky](https://github.com/mapbox/mapbox-gl-native/issues/6286#issuecomment-246362353).
We aren't able to resolve this issue from our end since it's coming from OKHttp dependency.

[android] - disable closable strictmode

---

include/mbgl/storage/default_file_source.hpp
include/mbgl/storage/online_file_source.hpp
include/mbgl/util/constants.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/DynamicMarkerChangeActivity.java
platform/android/src/jni.cpp
platform/default/default_file_source.cpp
platform/default/online_file_source.cpp
src/mbgl/util/mapbox.cpp
src/mbgl/util/mapbox.hpp
test/storage/online_file_source.cpp
test/util/mapbox.cpp

This PR enables configuration of a custom URL base endpoint. 
Review c++: @jfirebaugh @tmpsantos 
Review java: @zugaldia 
Side notes vs GL-JS implementation:
-  I went for using APIBaseURL over APIURL for readability 
-  I initially mimicked the Config class concept but removed it after discussion with @tmpsantos

[core] [android] - configurable API endpoint

---

platform/android/MapboxGLAndroidSDKTestApp/update_icons.sh

Removes an icon burning script that appears to be unused. If this script is indeed still used, we should move it to `platform/android/someplace`.
/cc @bleege @tobrun

Move unused icon burning script

---

src/mbgl/util/interpolate.hpp
test/style/functions.cpp

This change fixes the bugs reported in #6303 and #5823. It swaps the behaviour of the interpolate function for discrete values to return the value just less than the current zoom level, in accordance with the Mapbox style documentation.

Fix for stepwise functions 

---

platform/android/CONTRIBUTING_MACOS.md
platform/android/README.md

Closes #6297 
Fixes broken links in macOS contributing doc and image address in readme.
cc: @tobrun @zugaldia

[Android] Fixed readme image and links in contributing file

---

src/mbgl/util/mapbox.cpp
test/util/mapbox.cpp

Carries over any query strings from `mapbox://`-prefixed styles urls, source urls and tile urls to the `api.mapbox.com` requests.
cc/ @mapsam @1ec5 @jfirebaugh @yhahn @GretaCB

Persist querystrings in mapbox:// resource urls to API requests

---

platform/ios/scripts/document.sh

Fixes #6360 by reverting #4470.
This works when using [jazzy 0.7.2](https://github.com/realm/jazzy/releases/tag/v0.7.2) with Xcode 8.0 or Xcode 7.3.1 (via `xcode-select`).
/cc @1ec5

[ios] Don't specify Swift version for jazzy doc generation

---

platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme

Xcode 8 introduces a lot of console crap by default. On a stock run of the `iosapp` you see this just when launching: 
```
2016-09-19 13:25:43.354235 Mapbox GL[20870:4777188] subsystem: com.apple.UIKit, category: HIDEventFiltered, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-09-19 13:25:43.354676 Mapbox GL[20870:4777188] subsystem: com.apple.UIKit, category: HIDEventIncoming, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-09-19 13:25:43.362187 Mapbox GL[20870:4777187] subsystem: com.apple.BaseBoard, category: MachPort, enable_level: 1, …
```

add OS_ACTIVITY_MODE=disable for Xcode 8 spew

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapboxAccountManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java

This PR does two things:
1. Adjust logging levels for failed OkHttp requests as described in #6356.
2. Remove an unnecessary `Log` in `MapboxAccountManager` (when `isConnected` is false an exception is thrown and logged separately).
/cc: @bleege for review.
Fixes #6356.

Adjust logging level for failed OkHttp requests

---

include/mbgl/storage/network_status.hpp
platform/default/mbgl/storage/offline_download.hpp
src/mbgl/algorithm/update_renderables.hpp
src/mbgl/annotation/annotation_manager.hpp
src/mbgl/layout/symbol_layout.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/render_item.hpp
src/mbgl/renderer/symbol_bucket.hpp
src/mbgl/sprite/sprite_atlas.hpp
src/mbgl/storage/network_status.cpp
src/mbgl/style/update_batch.hpp
src/mbgl/text/collision_tile.cpp
src/mbgl/text/glyph_atlas.cpp
src/mbgl/text/glyph_atlas.hpp
src/mbgl/text/glyph_range.hpp
test/text/glyph_atlas.cpp

The `std::set` collection is ordered. It is less efficient than its `std::unordered_set` counterpart. This PR converts as many uses of `std::set` into `std::unordered_set` as possible. 
see https://github.com/mapbox/mapbox-gl-native/issues/3980
Below is a list of all uses of `std::set`. We will check of each as it is switched to `std::unordered_set` or we confirm that it cannot be switched. 
- `./include/mbgl/storage/network_status.hpp:31:    static std::set<util::AsyncTask*> observers;` done in ac000d10a301d7e2a7c4dc66d84222e7d319d244
- `./src/mbgl/algorithm/generate_clip_ids.hpp:20:        std::set<CanonicalTileID> children;` done in a289d58e346cfb2ef4ffcfe160734d59222fb013
- `./src/mbgl/algorithm/update_renderables.hpp:24:    std::set<UnwrappedTileID> checked;` done in …

[core] Convert uses of std::set to std::unordered_set

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AddRemoveMarkerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_add_remove_marker.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
src/mbgl/annotation/annotation_manager.cpp

closes #6208 
closes #5915
This PR removes unnecessary `updateAnnotation` calls. 
This was resulting in having ghost annotations. 
This PR also adds a test activity to prevent regression.
Review @ivovandongen / @zugaldia 
cc @jfirebaugh

[android] - do not update marker while creating

---

src/mbgl/map/change.hpp
src/mbgl/map/map.cpp
src/mbgl/style/observer.hpp
src/mbgl/style/style.cpp
test/map/map.cpp

Fixes #4527
Needed to properly time callbacks in #6032

[core] style loaded signal

---

src/mbgl/style/style.cpp

In reworking the fix in #6371 the `MapChangeDidFinishLoadingStyle` signal is now sent a little too early. This results in style manipulations in the form of layer additions not showing up correctly as the layers/sources from the style itself are not added yet. This change fixes that.
@tmpsantos Could you please review this change as you also looked at #6371?

[core] MapChangeDidFinishLoadingStyle - Ensure style is loaded

---

test/util/memory.cpp

**Platform:** Qt4
**Mapbox SDK version:** `master` @ fe28b57fe08bcd1069dad8fd47827da6bd835285
[Tests on Travis are failing with](https://travis-ci.org/mapbox/mapbox-gl-native/jobs/156589001): 
```
../../../test/util/memory.cpp:168: Failure
Expected: (memoryFragments) < (10 * 1024 * 1024), actual: 10678272 vs 10485760
Abnormal memory growth detected.
[  FAILED  ] Memory.Fragmentation (203157 ms)
```
/cc @tmpsantos @brunoabinader

Memory.Fragmentation test failure: Abnormal memory growth detected

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Fixes #6032 
This may have a significant impact, so let's get a good set of testcases here:
- Clean install testapp
- Open offline activity
- Make sure onMapReady callback is called
- Kill and reopen the testapp
- Open offline activity
- Make sure onMapReady callback is called
- Turn on flight mode
- Kill and reopen the testapp
- Open offline activity
- Make sure onMapReady callback is called
- Download offline region
- Turn on flight mode
- Kill and reopen the testapp
- Open offline activity
- Make sure onMapReady callback is called
cc @tobrun please add any cases you find

[android] change timing of onMapReady to facilitate runtime style

---

platform/qt/config.cmake

The Qt version of `mbgl-test` isn't linked with the Mason version of SQLite we're using. On most systems, `sqlite.h` is installed, so we haven't seen any errors from this, but it might mean that we're using headers for a SQLite version that doesn't match the one we're actually linking.

Link Qt tests with Mason sqlite

---

platform/android/bitrise.yml

Increases timeout on the firebase tests to 15 minutes.

[android] - increase firebase test timeout to 15 minutes

---

src/mbgl/style/source_impl.hpp
src/mbgl/style/sources/geojson_source_impl.cpp
src/mbgl/style/sources/geojson_source_impl.hpp
src/mbgl/tile/geojson_tile.cpp
src/mbgl/tile/geojson_tile.hpp

References #6264, this PR follows approach as documented in OP:
>  For GeoJSON data changes, maybe we can get away without batching, and instead just add a loop over tiles in GeoJSONSource::Impl::setGeoJSON, calling GeometryTile::setData on each one with the new data.
cc @mollymerp

6264 mutable geojson

---

platform/darwin/src/MGLOfflinePack.h
platform/darwin/src/MGLOfflinePack.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

This is a cosmetic fix that makes an offline pack appear to stop downloading as soon as `-suspend` is called on it.
Note that this change does not address the crash in #6092, which occurs because the `MBGLOfflineRegionObserver`’s weak pointer to the MGLOfflinePack object has gone stale by the time late notifications come in from the `mbgl::OfflineRegion`. `MBGLOfflineRegionObserver` is owned by `mbgl::OfflineRegion` and MGLOfflinePack doesn’t currently have a reference to it, although that might be one future direction for improvement.
Fixes #5538.

Ignore progress updates after suspending

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/Source.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/VectorSource.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_runtime_style.xml
platform/android/config.cmake
platform/android/src/jni.cpp
platform/android/src/style/conversion/geojson.hpp
platform/android/src/style/conversion/url_or_tileset.hpp
platform/android/src/style/sources/geojson_source.cpp
platform/android/src/style/sources/geojson_source.hpp
platform/android/src/style/sources/raster_source.cpp
platform/android/src/style/sources/raster_source.hpp
platform/android/src/style/sources/source.cpp
platform/android/src/style/sources/source.hpp
platform/android/src/style/sources/sources.cpp
platform/android/src/style/sources/sources.hpp
platform/android/src/style/sources/vector_source.cpp
platform/android/src/style/sources/vector_source.hpp

[android] Runtime Styling API: mutable GeoJsonSource

---

platform/darwin/src/MGLGeoJSONSource.h

Fixes: https://github.com/mapbox/mapbox-gl-native/issues/6236

[ios, macos] Clarify MGLGeoJSONSource option units in API docs

---

platform/darwin/src/MGLStyle.h
platform/darwin/src/MGLStyle.mm

The core functions here can return `nullptr` if queries aren't found, yet we proceed merrily until the user gets a runtime crash. We should instead follow Cocoa convention and return `nil` early. 
This also touches up source querying to also support `nullable`. 
Also curious about the background of the dead code. 
/cc @1ec5 @frederoni

proper use of nullability for source & layer querying

---

Makefile

Build the shared library.
Fixes #6415

[Qt] Added missing `qt-lib` target

---

bin/glfw.cpp
platform/qt/app/mapwindow.cpp

There is no quick and easy way of setting a custom style in our demo applications - current process involves e.g. replacing one of the default styles with the custom style. I've been using these patches for my own debugging and thought it could be a good addition for GL native developers that frequently needs to test/debug non-default styles.
__Usage__: Export your custom style URL as a `MAPBOX_STYLE_URL` environment variable prior to running the demo application. Once the application starts, it'll use the url given by the envvar if set, otherwise use default styles.
Currently supports GLFW and Qt apps.

Initial style from MAPBOX_STYLE_URL if set

---

package.json
src/mbgl/renderer/painter_symbol.cpp

Capturing the stopgap fix for a viewport-oriented clipped text bug, similar to issue reported in https://github.com/mapbox/mapbox-gl-js/issues/2074#issuecomment-242253307 for GL JS but in the context of viewport pitched labels.
cc @ansis

[core] Don't use depth test unless text is pitch-aligned to map

---

platform/darwin/src/MGLRasterSource.h
platform/darwin/src/MGLRasterSource.mm
platform/darwin/src/MGLTileSet.h
platform/darwin/src/MGLTileSet.mm
platform/darwin/src/MGLTileSet_Private.h
platform/darwin/src/MGLVectorSource.h
platform/darwin/src/MGLVectorSource.mm
platform/ios/app/MBXViewController.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/Mapbox.h
platform/ios/test/MGLTileSetTests.mm

Add tile template option to raster and vector sources

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapboxAccountManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/net/ConnectivityListener.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/net/ConnectivityReceiver.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/net/NativeConnectivityListener.java
platform/android/config.cmake
platform/android/src/connectivity_listener.cpp
platform/android/src/connectivity_listener.hpp
platform/android/src/jni.cpp
platform/android/src/timer.cpp
platform/default/online_file_source.cpp
src/mbgl/storage/network_status.cpp

Fixes #6210 
Fixes #5118
Fixes #5827

[android] fix offline region download crashes

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/assets/fill_filter_style.json
platform/android/MapboxGLAndroidSDKTestApp/src/main/assets/line_filter_style.json
platform/android/MapboxGLAndroidSDKTestApp/src/main/assets/numeric_filter_style.json
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_runtime_style.xml
platform/ios/app/MBXViewController.m
platform/ios/app/fill_filter_style.json
platform/ios/app/line_filter_style.json
platform/ios/app/numeric_filter_style.json
platform/ios/ios.xcodeproj/project.pbxproj

Work in progress to test filtered fills & lines.

fix #6379: beef up runtime styling manual tests

---

.travis.yml
package.json
platform/node/scripts/after_script.sh

To actually run Node.js tests, refs https://github.com/mapbox/mapbox-gl-native/pull/6226#issuecomment-248322166. Why are conditionals in bash so complicated.
@tmpsantos `npm run test-memory` is currently not included in `make test-node` - should it be? This slows downs the tests on Travis substantially, but appears to be passing.
There is currently a single failing test in `npm run test-suite` (passing locally on OS X though). Is this just an anti-aliasing difference where we could bump up the [`allowed`](https://github.com/mapbox/mapbox-gl-test-suite/blob/master/render-tests/text-font/chinese/style.json#L7) threshold slightly, or is there something wrong I'm not seeing @amyleew?
- diff: 0.00057220458984375
- zoom: 11
- center: -70.751953125,43.38904828677382
- width: 512
- height: 512 …

fix bad conditional in .travis.yml

---

platform/darwin/scripts/generate-style-code.js

CSS hexadecimal RGB syntax can contain all the hexadecimal digits, not just the decimal digits. We don’t exercise this code path yet, because the style specification only defaults style properties to colors that we’ve special-cased with NSColor/UIColor method names (`blackColor`, `whiteColor`, `clearColor`).

Allow full hexadecimal colors in layer documentation

---

package.json
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.h

Analog to https://github.com/mapbox/mapbox-gl-style-spec/pull/506 to clarify "circle color" as the fill color.

clarify circle color as fill

---

platform/darwin/scripts/generate-style-code.js

Ref https://github.com/mapbox/mapbox-gl-style-spec/issues/504.
Modifies the style documentation generation code to allow for an array as the required property value. An array means that the property must have one of multiple possible values.
I tried to match the sentence-style syntax and punctuation I saw elsewhere. Here's what we end up with in a few scenarios:
```
"requires": [ 
{
"icon-text-fit": ["both", "width", "height"]
},
],
``` 
> This property is only applied to the style if `iconTextFit` is set to either an `NSValue` object containing `MGLSymbolStyleLayerIconTextFitBoth`, or an `NSValue` object containing `MGLSymbolStyleLayerIconTextFitWidth`, or an `NSValue` object containing `MGLSymbolStyleLayerIconTextFitHeight`. Otherwise, it is ignored.
```
"requires": [
{
"icon-text-fit": …
```

Doc gen handles arrays as required property values

---

src/mbgl/util/mapbox.cpp

This function can be called from different threads and was depending on a global `std::string protocol` which can do heap allocations.
The first thread to use it would initialized it which is not exactly safe, so this patch moves it to a `char *` that is just a pointer to
the data segment, so no races.
Valgrind detected it on #6431.
```
==9874== Conditional jump or move depends on uninitialised value(s)
==9874==    at 0x4C307C2: __memcmp_sse4_1 (in /home/travis/build/mapbox/mapbox-gl-native/mason_packages/linux-x86_64/valgrind/latest/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9874==    by 0x79896E: mbgl::util::mapbox::isMapboxURL(std::string const&) (in /home/travis/build/mapbox/mapbox-gl-native/build/qt-linux-x86_64/Release/mbgl-test)
==9874==    by 0x6DC756: …
```

[core] Fix initialization race on util::mapbox::isMapboxURL

---

include/mbgl/map/map.hpp
platform/qt/include/qmapbox.hpp
platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapbox.cpp
src/mbgl/map/change.hpp
src/mbgl/map/map.cpp
src/mbgl/style/source_observer.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
src/mbgl/style/tile_source_impl.cpp
src/mbgl/style/tile_source_impl.hpp
test/src/mbgl/test/stub_style_observer.hpp
test/style/source.cpp

Implemented observer callbacks so the style knows when the source’s attribution changes and the map knows when the style’s attribution changes. Also implemented a getter for a tile source’s attribution.
Working towards #2723. Blocks #5999.
/cc @tmpsantos

Core support for source-driven attribution

---

platform/default/mbgl/storage/offline_download.cpp
platform/default/mbgl/storage/offline_download.hpp
platform/default/online_file_source.cpp
src/mbgl/text/glyph_range.hpp
test/src/mbgl/test/fake_file_source.hpp
test/storage/offline_download.cpp

Don't allow OfflineDownload to flood the request queue. Fixes #4414.

[core] Incremental offline downloads

---

include/mbgl/map/map.hpp
include/mbgl/style/source.hpp
platform/qt/include/qmapbox.hpp
platform/qt/src/qmapbox.cpp
src/mbgl/map/change.hpp
src/mbgl/map/map.cpp
src/mbgl/style/source.cpp
src/mbgl/style/source_impl.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
src/mbgl/style/tile_source_impl.cpp
src/mbgl/style/tile_source_impl.hpp

This is a followup to #6431 that addresses the feedback in https://github.com/mapbox/mapbox-gl-native/pull/6431#pullrequestreview-1184531. SDK code that wishes to display the style’s full attribution, such as MGLMapView in #5999, is now responsible for iterating over the style’s sources. The source attribution change notification has been generalized so that it can be reused in the future for other source changes.
/cc @jfirebaugh @tmpsantos

Clean up source-driven attribution

---

platform/android/src/jni.cpp
platform/android/src/native_map_view.cpp

closes #6438.
Proposal to disable logs that are currently executed when users perform gestures.
These logs were written both in Release and Debug mode and we have received request to disable them. While this is not a long term solution it enables us to ship in short term. I'm suggesting to rethink this for the `5.0.0` refactor/release.
cc @cammace @ivovandongen @zugaldia

[android] - disable general purpose logging during transformation change

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

This fixes an issue noted in https://github.com/mapbox/mapbox-gl-native/issues/6458#issuecomment-249808011 where the map view would drop annotation views
if the developer did not make full use of the reuse queue. 
The fixes are:
- Guard against enqueuing a view for reuse if it does not have a `viewReuseIdentifier`. Previously, if the app developer created a new annotation view with no reuse id each time `[MGLMapViewDelegate mapView:viewForAnnotation:]` was called and then the view was scrolled offscreen, we  attempted to add the view to the reuse queue (for no good reason) and  did not update the views center ever again.  This change avoids the reuse queue and just updates the
center always.
- Add any annotation view that should be displayed but is not in the annotation container view to …

[ios] Always show annotation view even when view reuse is not used

---

CMakeLists.txt
cmake/core-files.cmake
src/mbgl/util/geojson.cpp

Mapbox GL Native Core depends only on header-only libraries.
This increases portability as we don't need to deal with ABI breakages and getting deps pre-built to all the platforms we target.

[core] Use geojson as a header only library

---

platform/qt/src/http_file_source.cpp
platform/qt/src/http_file_source.hpp

Qt macOS network manage implementation differs from linux in a sense that some requests do not generate a `finished()` signal, but an `error()` instead - that is not caught up by the network access manager. This made QMapboxGL.styleURL utest hang for macOS.
/cc @ivovandongen @tmpsantos

[Qt] Connect to finished() and error() signals from QNetworkReply

---

Makefile
platform/darwin/src/MGLOfflineStorage.mm
platform/ios/bitrise.yml
platform/macos/bitrise.yml

Restored the make rule for running macOS SDK unit tests. Invoke that rule on Bitrise. Note that the tests will fail to build until #5994 is merged.
Fixes #5991.
/cc @kkaefer

Restore macOS unit tests on CI

---

src/mbgl/gl/context.cpp

An oversight in #6486 means that we're iterating way too often over all of the programs we are about to delete.

Remove n^2 iteration over programs when deleting

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapview_internal.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_marker_view.xml

This PR allows to use the older TextureView approach in favor of SurfaceView.
This feature is annotated with deprecation, it could possibly be removed in future releases.

Optionable textureview

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapboxAccountManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/src/http_file_source.cpp

Fixes #1993 
Example user agent string:
```
com.mapbox.mapboxsdk.testapp/4.1.0 (9) Mapbox/4.2.0-SNAPSHOT (0c25615) Android/24 (armeabi-v7a)
```
eg: 
```
<app packagename>/<app version string> (<app version code>) Mapbox/<SDK version> (<git revision>) Android/<API level> (ABI)
```
cc @mick

[android] user agent string

---

cmake/test-files.cmake
include/mbgl/storage/default_file_source.hpp
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/StyleFileActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_style_file.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/raw/local_style.json
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/config.cmake
platform/darwin/src/NSURL+MGLAdditions.m
platform/default/default_file_source.cpp
platform/default/local_file_source.cpp
platform/ios/config.cmake
platform/linux/config.cmake
platform/macos/config.cmake
platform/qt/qt.cmake
src/mbgl/storage/local_file_source.hpp
test/storage/local_file_source.test.cpp

LocalFileSource

---

CMakeLists.txt
src/mbgl/geometry/buffer.hpp
src/mbgl/geometry/collision_box_buffer.cpp
src/mbgl/geometry/collision_box_buffer.hpp
src/mbgl/geometry/elements_buffer.hpp
src/mbgl/geometry/icon_buffer.cpp
src/mbgl/geometry/icon_buffer.hpp
src/mbgl/geometry/line_buffer.cpp
src/mbgl/geometry/line_buffer.hpp
src/mbgl/geometry/text_buffer.cpp
src/mbgl/geometry/text_buffer.hpp
test/storage/online_file_source.test.cpp

We used to treat all warnings as errors with `-Werror`. I think this was lost with the switch to CMake; we should restore it.

Restore -Werror

---

platform/macos/scripts/document.sh

macOS counterpart to https://github.com/mapbox/mapbox-gl-native/pull/6377 — fixes jazzy doc generation with Xcode 8 by no longer specifying a specific Swift version.
/cc @1ec5

[macos] Don't specify Swift version for jazzy doc generation

---

platform/ios/CHANGELOG.md
platform/ios/DEVELOPING.md
platform/ios/scripts/package.sh
platform/macos/CHANGELOG.md
platform/macos/DEVELOPING.md
platform/macos/scripts/package.sh

Fixes #6502. Stripped dynamic framework packages should now come with the correct dSYM.
Disabling `GCC_GENERATE_DEBUGGING_SYMBOLS` for `SYMBOLS=NO` builds meant that those builds had no debug symbols to strip or add to a dSYM. Running `make iframework SYMBOLS=NO` would fail to create a dSYM, but our deploy script would evidently [reuse the symbol-ful dSYM](https://github.com/mapbox/mapbox-gl-native/issues/6502#issuecomment-250605473).
With the added UUID validation, the above scenario would now fail:
```
* Stripping symbols from binaries…
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: changes being made to the file will invalidate the code signature in: /Users/jason/Documents/Mapbox/mapbox-gl-native/build/ios/pkg/dynamic/Mapbox.framework/Mapbo …
```

Fix bad dSYM for symbol-stripped dynamic framework builds

---

platform/darwin/scripts/generate-style-code.js

Mildly decoupled the transformation from the style specification to the format required for iOS/macOS documentation so it’s harder for style specification references to other properties’ values to fall through the cracks.
Fixes #6541.
/cc @incanus

Loosen style doc transform regex

---

platform/ios/src/MGLMapView.mm

This removes the calls to top and bottom for content inset of the map view when calculating the edge padding for following. https://github.com/mapbox/mapbox-gl-native/pull/6313 added this along with the left and right values. 
The correction in this PR eliminates a bug where the map did not scroll to the correct location for the user dot (it was several points off on the y axis) and also a bug in `didUpdateLocationWithUserTrackingAnimated:` where the map panning operations would always occur because the current and correct points never matched up even if a stream of location values that were the same were processed.

[ios] Remove double counting of content inset top and bottom

---

Makefile

Follow-up from enabling the benchmarks.

[tests] Do not run benchmarks with GDB

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationDrawableActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_tracking.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Follow up on #6569, changed exposed API from original PR (closes #6549, closes #6567)
> This fixes issues #6549 and #6567. Also pertinent to #6557.
Additional code has been added to the test app (Activity "User Tracking
Mode") to test. A potential race condition in the MapboxMap#easeCamera() methods where
a camera change generated by tracking which could have reset the tracking
modes has been eliminated by factoring out a new method
MapboxMap#easeCameraInternal().

[android] Revise handling of tracking modes and interactions with touch gestures.

---

cmake/test-files.cmake
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/geometry_tile_worker.cpp
src/mbgl/tile/raster_tile.cpp
src/mbgl/tile/raster_tile.hpp
src/mbgl/tile/raster_tile_worker.cpp
test/tile/raster_tile.test.cpp
test/tile/vector_tile.test.cpp

In 41bbd4e4f7d66465433e370ca024ab0239fcace3 I merged two error pathways that need to be distinct:
* If an error occurs while loading a tile, the tile should not be treated as renderable
* If an error occurs while creating the tile layout, the tile can be considered renderable (there might be partial data, or the data from a prior layout may still be used)
Fixes #6506
Fixes #6547
@halset, thanks for locating the offending commit, it made the cause of this regression easy to find.

[core] Tiles that error on load are not renderable

---

platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm
platform/darwin/test/MGLFilterTests.mm

Removed support for the `CONTAINS` operator, which was incorrectly interpreted to mean a transposed `IN` rather than a find-substring operation. A proper implementation would be blocked by mapbox/mapbox-gl-style-spec#233.
Fixes #6586.
/cc @boundsj

Remove support for CONTAINS operator

---

platform/ios/src/MGLMapboxEvents.m

If metrics collection was paused when the host app was previously backgrounded, metrics collection should resume if the host app becomes active. This change observes `UIApplicationDidBecomeActiveNotification` so that, when responding to that notification, the application is in the required state (active) when the method to determine if metrics should be collected is run.
cc @1ec5 @friedbunny @pveugen

[ios] Observer that app did become active instead of will foreground

---

Makefile
platform/ios/scripts/deploy-packages.sh
platform/ios/scripts/publish.sh

Spent some time converting @boundsj’s `deploy-packages.sh` into a more automated `make` command:
- **`make ideploy` is now the one-stop shop for deploying releases.**
- Automatically detects latest `ios-vX.X.X-pre.X` tag.
- Fails if version has already been published on GitHub.
- Fails if tag does not exist, checks it out if it does.
- Specify a version and skip GitHub publishing: `make ideploy VERSION_TAG=ios-v9.8.7 GITHUB_RELEASE=false`
- Does not allow your computer to go to sleep (`caffeinate`), which would ruin the deploy.
- Adds more informative steps, formatted like the build `make` commands.
- Shows upload progress for s3.
- Removes overly-verbose `github-release` output.
- Tried to filter this instead, but `sed` would occasionally kill the entire process.
- Installs …

iOS deploy script enhancements

---

platform/android/scripts/release.py

@mapbox/android -
This is the first iteration of a script to helps us automate our release process. For now, you can start using it to build snapshots, although it should also support betas and final releases.
A couple of examples:
- Publish a snapshot from master (`release.py` uses the current branch)
```
$ git branch
* master
1234-fix-crash
$ python release.py --stage snapshot
```
- Publish a snapshot from a feature branch (same as before, just switch branchs with git):
```
$ git branch
master
* 1234-fix-crash
$ python release.py --stage snapshot
```
I'm also working on updating our release process docs to details the install process and usage. Any thoughts meanwhile?

Automate build process for Android SDK releases

---

src/mbgl/map/map.cpp
test/map/map.test.cpp

These calls should produce the same results:
``` c++
double zoom = 0;
LatLng latLng { 1, 1 };
// call 1
mbgl::Map::setZoom(zoom);
mbgl::Map::setLatLng(latLng);
// call 2
mbgl::map::setLatLngZoom(latLng, zoom);
```
Previously part of #6553.

Map::setLatLng differs from Map::setLatLngZoom if zoom is same
