mapbox/mapbox-gl-native

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java

More general solution for the issue of #5608

update marker invalidation with SurfaceView

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java

[android] #5513 - make sure view is measured first before anchoring

---

platform/macos/app/Base.lproj/MainMenu.xib

We should add a few keybindings to the Debug menu for the macOS application.
Here's my proposal:
- Tile boundaries: **⌘B**
- Tile info: **⌘I**
- Timestamps: **⌘T**
- Collision: **⌘⇧C**
- Overdraw: **⌘⇧O**
- Stencil buffer: **⌘⌥S**
- Color buffer: **⌘⌥C**

Key bindings for macosapp

---

src/mbgl/renderer/bucket.hpp
src/mbgl/renderer/circle_bucket.cpp
src/mbgl/renderer/circle_bucket.hpp
src/mbgl/renderer/fill_bucket.cpp
src/mbgl/renderer/fill_bucket.hpp
src/mbgl/renderer/line_bucket.cpp
src/mbgl/renderer/line_bucket.hpp
src/mbgl/renderer/paint_parameters.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/renderer/painter_background.cpp
src/mbgl/renderer/painter_circle.cpp
src/mbgl/renderer/painter_clipping.cpp
src/mbgl/renderer/painter_debug.cpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/renderer/painter_raster.cpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/renderer/raster_bucket.cpp
src/mbgl/renderer/raster_bucket.hpp
src/mbgl/renderer/render_tile.cpp
src/mbgl/renderer/render_tile.hpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/renderer/symbol_bucket.hpp
src/mbgl/shader/shaders.hpp

Start preparing for data-driven styles. This is mainly just small, unconnected cleanups so far. See commits for details.

Refactor rendering

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java

Limiting Location Data To 7 Digits After Decimal Place

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/ViewPagerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_viewpager.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

5649 mapview capture scroll gestures

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/InvalidMarkerPositionException.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/InfoWindowTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerViewTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java

[android] #5631 - add exception when creating an invalid marker

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/LatLngBoundsActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java

[android] latlngbounds includes added in builder

---

platform/darwin/src/MGLMultiPoint_Private.h
platform/darwin/src/MGLPolygon.mm
platform/darwin/src/MGLPolyline.mm
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapViewDelegate.h
platform/macos/src/MGLMapView.mm
platform/macos/src/MGLMapViewDelegate.h
src/mbgl/style/layers/layer_properties.hpp.ejs
src/mbgl/style/paint_property.hpp

Follow-up to review comments from https://github.com/mapbox/mapbox-gl-native/pull/5464.
:eyes: @1ec5 @jfirebaugh

Update color layer properties code generator

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java

This PR adds a new API to the `OfflineRegion` object to enable or disable the delivery of messages once a region state is set as `STATE_INACTIVE`. Note that it doesn't change the internal state of the region, this only changes whether the callback will emit or not notifications.
From now on, by default, the API won't provide updates when a region is set inactive although this behavior can be changed via `OfflineRegion.setDeliverInactiveMessages(true)`.
/cc: @danswick @1ec5 
This handles the Android side of #5538.

Add an API to enable/disable delivering messages when the region goes inactive

---

platform/darwin/src/MGLAccountManager.h
platform/darwin/src/MGLTypes.h
platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-static-part.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/ios/jazzy.yml
platform/ios/scripts/package.sh
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/macos/jazzy.yml

No keycaps were harmed in the production of this PR.
/cc @boundsj @frederoni @friedbunny

Merge iOS SDK 3.3.0 release branch into master

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/GzipRequestInterceptor.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java

GZIP Android Telemetry Data

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java

Adding Endpoint Support For SharedPreferences

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties
src/mbgl/util/mapbox.cpp
test/util/mapbox.cpp

Merge Release Android V4.1.1 Branch To Master

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

[android] #5717 - correctly load style from xml attributes

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

closes #5745, `MapboxMap#selectMarker()` now calls `MarkerViewManager#selectMarkerView`

[android] #5745 - allow selectMarker on MapboxMap 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_press_for_marker.xml

5679 mapbox logo margin orientation bug

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

[android] Fixes #5777. deselectMarker is delegated to MapboxMap.

---

platform/ios/CHANGELOG.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/scripts/package.sh

5782: build static framework correctly

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Fix crash drawing compass on iOS 7

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

[android] #5500 - add layout editor support for my location view

---

platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapview_internal.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/NavigationDrawerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Closes #5738, resolves all the overlain view rendering issues we have noticed with SurfaceView.
Targets to merge into `5000-surfaceView` from PR in #5801 .

5738 overlain components on surfaceview

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/imagegenerator/PrintActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_print_24dp.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_print.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Add print example to the test app. 
```java
@Override
public void onSnapshotReady(Bitmap snapshot) {
PrintHelper photoPrinter = new PrintHelper(this);
photoPrinter.setScaleMode(PrintHelper.SCALE_MODE_FIT);
photoPrinter.printBitmap("map.jpg - mapbox print job", snapshot);
}
```
Example:

[android] - add print example

---

platform/ios/Mapbox.playground/Contents.swift

Left in the old code for those using Xcode 7.3.
Fixes #5846.
/cc @friedbunny @boundsj @frederoni

Migrate playground to Swift 3

---

package.json

Get tests for recently fixed bugs.
https://github.com/mapbox/mapbox-gl-test-suite/pull/128
https://github.com/mapbox/mapbox-gl-test-suite/pull/130

[tests] Update test-suite

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java

[android] #5717 - update MarkerView when added to the map

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/ConversionException.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/BackgroundLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/RasterLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/VectorSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/style/BackgroundLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/style/CircleLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/style/FillLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/style/LineLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/style/RasterLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/style/SymbolLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/style/layer.junit.ejs
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java

Some convenience methods the runtime style api

[android] #5858 - added convenience methods for color properties layer

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Changed compass sensor from accelerometer and magnetometer to using the rotation vector. Also fixed bug, we were only updating the camera bearing when the user location moved. Now when `MyLocationTracking.TRACKING_FOLLOW` is enabled as well as compass, we constantly rotate the camera to point same direction as user.
Closes #5861 
cc: @zugaldia @tobrun

[android] - 5861 better compass

---

platform/android/CHANGELOG.md

[android] - update CHANGELOG.md for 4.2.0-beta.1 release

---

platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapview_internal.xml

This PR proposes to move the MyLocationView under the logo, attribution and compass.
cc @zugaldia @ivovandongen

[android] - move MyLocationView under overlays 

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/FeatureOverviewActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DoubleMapActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/activity/Feature.java

5888 double map view broken

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CustomLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/customlayer/CustomLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_custom_layer.xml
platform/android/src/style/layers/custom_layer.cpp

Fixes issue caused by careless refactor on my part. Updated the test to test update as well and show off the z-ordering.

[android] #5887 - Custom layer crash fix + updated test case

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapboxAccountManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Annotation.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/ProjectedMeters.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java

refs #5880, lowers the amount of warning by 30.

[android] #5880 - javadoc cleanup part one

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java

[android] #5889 - update info window location

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/BackgroundLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/RasterLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/package-info.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/TileSet.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/package-info.java

refs #5880, part 2 of the javadoc cleanup, all warnings were removed. 
Still need to look into if the public api is completely covered before closing.

[android] javadoc cleanup part 2

---

platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/geocoding/GeocoderActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/navigation/LocationPickerActivity.java

We are now using the latest version of MAS along with the latest supportLibVersion
cc: @tobrun

[android] updated mas in testapp

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTintActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java

closes #5934
cc @bleege @ivovandongen

[android] #5934 - memory leak on animators + location listeners

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java

closes #5963, small logic bug in test activity nothing SDK related.

[android] #5963 - fixes location tracking mode activity

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Filter.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Function.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java
platform/android/src/style/android_conversion.hpp

Fixes issue with filters on number properties. Also probably fixes issues with https://github.com/mapbox/mapbox-gl-native/issues/5852
@tobrun Can you review please?

[android] #5978 - fix number property filters

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_geojson_clustering.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_runtime_style.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Fix in https://github.com/mapbox/mapbox-gl-native/issues/5978 also fixed filtering on geojson sources.
@tobrun Review please.

[android] #5852 - geojson source clustering

---

platform/macos/macos.xcodeproj/project.pbxproj

Link unit test bundle against libmbgl-core

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/raw/amsterdam.geojson

Adds an example on `RuntimeStyleActivity` with numerical filters.
@tobrun review please

[android] #6014 - add example with numerical filter

---

platform/darwin/src/MGLGeoJSONSource.mm
platform/darwin/src/MGLRasterSource.mm
platform/darwin/src/MGLSource.h
platform/darwin/src/MGLSource.mm

Remove MGLSource.sourceType

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/NoSuchSourceException.java

Adds the missing exception and updates the related method signatures.
@tobrun review please?

[android] #6034 - add missing NoSuchSourceException

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/colors.xml

- replaced default colors with dark material design colors 
- changed textcolor to white 
- added click event on toolbar arrow  
- made sanity test generation compatible (add mapbox as class member of activity).

[android] - Improve GeoJson clustering example

---

platform/darwin/src/MGLStyleAttributeFunction.h

[ios, macos] fixes #6056 backwards compatibility macro

---

platform/macos/macos.xcodeproj/project.pbxproj

Take NSColor+MGLAdditions private

---

.travis.yml
include/mbgl/platform/default/headless_view.hpp
platform/qt/bitrise-qt4.yml
platform/qt/bitrise-qt5.yml
platform/qt/config.cmake
platform/qt/qt.cmake
platform/qt/test/headless_view_qt.cpp
test/api/custom_layer.cpp
test/gl/object.cpp

Using legacy QGLWidget because we support Qt4.

[Qt] Implement a Qt headless renderer

---

cmake/core-files.cmake
cmake/test-files.cmake
include/mbgl/style/conversion/geojson_options.hpp
include/mbgl/style/conversion/source.hpp
test/src/mbgl/test/conversion_stubs.hpp
test/style/conversion/geojson_options.cpp

For re-use in https://github.com/mapbox/mapbox-gl-native/pull/6054
@tmpsantos Could you check if this impacts QT at all? Checked ios/tests.

[core] extract GeoJSONOptions conversion from GeoJSONSource conversion

---

include/mbgl/style/layers/background_layer.hpp
include/mbgl/style/layers/circle_layer.hpp
include/mbgl/style/layers/fill_layer.hpp
include/mbgl/style/layers/layer.hpp.ejs
include/mbgl/style/layers/line_layer.hpp
include/mbgl/style/layers/raster_layer.hpp
include/mbgl/style/layers/symbol_layer.hpp
scripts/generate-style-code.js
src/mbgl/style/layers/background_layer.cpp
src/mbgl/style/layers/circle_layer.cpp
src/mbgl/style/layers/fill_layer.cpp
src/mbgl/style/layers/layer.cpp.ejs
src/mbgl/style/layers/layer_properties.hpp.ejs
src/mbgl/style/layers/line_layer.cpp
src/mbgl/style/layers/raster_layer.cpp
src/mbgl/style/layers/symbol_layer.cpp

Fixes #6117.
/cc @1ec5 @frederoni @ivovandongen

[core] Add static getters for property default values

---

platform/ios/uitest/OHHTTPStubs/OHHTTPStubs/Sources/HTTPMessage/OHHTTPStubsResponse+HTTPMessage.h
platform/ios/uitest/OHHTTPStubs/OHHTTPStubs/Sources/OHHTTPStubsResponse+HTTPMessage.h
platform/ios/uitest/OHHTTPStubs/OHHTTPStubs/Sources/OHHTTPStubsResponse.h

[ios] Fix typo

---

platform/android/CHANGELOG.md

This PR updates the `CHANGELOG.md` file.
Release ticket is https://github.com/mapbox/mapbox-gl-native/issues/6155.

Release 4.2.0-beta.2

---

CMakeLists.txt
src/mbgl/tile/vector_tile.cpp

Upgrades to protozero v1.4.0 which brings performance benefits (https://github.com/mapbox/protozero/blob/master/CHANGELOG.md#140---2016-07-22).

Upgrade to protozero 1.4.0

---

Makefile
cmake/test.cmake
platform/qt/app/main.cpp
platform/qt/app/mapwindow.cpp
platform/qt/config.cmake
platform/qt/config.qdocconf
platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qquickmapboxglrenderer.cpp
platform/qt/test/qmapboxgl.cpp
test/src/mbgl/test/util.hpp

Foundations for adding documentation to every single public API and also unit tests for them.

[Qt] Added utest and doc stubs

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/camera/CameraPositionTest.java

Corrected a systematic typo.
/cc @tobrun

Radiant → radian

---

.gitignore
include/mbgl/style/sources/geojson_source.hpp
platform/default/mbgl/storage/offline_download.cpp
src/mbgl/algorithm/update_renderables.hpp
src/mbgl/annotation/annotation_tile.cpp
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/style/source_impl.cpp
src/mbgl/style/source_impl.hpp
src/mbgl/style/sources/geojson_source.cpp
src/mbgl/style/sources/geojson_source_impl.cpp
src/mbgl/style/sources/geojson_source_impl.hpp
src/mbgl/tile/geojson_tile.cpp
src/mbgl/tile/geojson_tile.hpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/geometry_tile_data.hpp
src/mbgl/tile/vector_tile.cpp
src/mbgl/util/worker.cpp
src/mbgl/util/worker.hpp
test/algorithm/update_renderables.cpp

Various cleanups to code I was reviewing prior to working on #5701.

Preparatory cleanup for tile reloading

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java

[android] Anchoring was only set once while it was still unmeasured

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

[android] #6113 - receiver not registered exception

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java

[android] alpha not applied from builder fix for marker view

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java

[android] added missing rotation, cleanup duplicate entries

---

platform/ios/src/MGLFaux3DUserLocationAnnotationView.m
platform/ios/src/MGLUserLocationAnnotationView.h

jazzy crashes on `#import <Mapbox/Mapbox.h>`
👀  @friedbunny

[ios, macos] fix imports

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/VideoViewActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_video_view.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Closes: https://github.com/mapbox/mapbox-gl-native/issues/6196
Pinging someone on @mapbox/android to review!
cc: @danswick @pdgoodman

[android] added video view example

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/VideoViewActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_video_view.xml

#6196 broke our auto generated test suite integration on master.
Issue and fix is documented in https://github.com/mapbox/mapbox-gl-native/pull/6086#issuecomment-240996903.

[android] - fix breaking build on master

---

include/mbgl/style/filter_evaluator.hpp

This fixes an out of date documentation comment.

Update filter doc usage example

---

platform/android/src/geometry/conversion/feature.hpp

[android] fix boolean to JsonPrimitive conversion

---

platform/android/src/style/layers/layer.hpp

[android] Remove declaration of deleted method

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/activity/BaseTest.java

Closes #6279, improves experience around the issue documented in https://github.com/mapbox/mapbox-gl-native/pull/6086#issuecomment-240996903.

[android] - throw concrete exception when generated test cases fail 

---

platform/android/bitrise.yml

[android] - run ndk-stack as part of the build

---

wrap.cpp

Adds core unit tests for `wrap.hpp`.
cc @jfirebaugh @tmpsantos

[core] - add unit test for wrap

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

[android] - ensure access token is set when trying to load a style

---

platform/android/MapboxGLAndroidSDKTestApp/build.gradle

closes #6277, aims to make instrumentation tests more robust

6277 disable leak canary during instrumenation tests

---

cmake/core-files.cmake
include/mbgl/util/run_loop.hpp
include/mbgl/util/work_task.hpp
include/mbgl/util/work_task_impl.hpp
platform/android/src/asset_file_source.cpp
platform/default/asset_file_source.cpp
platform/default/default_file_source.cpp
src/mbgl/util/thread.hpp
src/mbgl/util/worker.cpp
test/util/thread.cpp

Preparation for #1471. Fixes #5064.

Extract and clean up WorkTaskImpl

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Fixes https://github.com/mapbox/mapbox-gl-native/issues/6317.
@tobrun please review.
/cc: @cammace

Avoids NullPointerException when checking mMapboxMap.getUiSettings()

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml

New Staging Server PK Access Token For Android TestApp

---

src/mbgl/tile/tile_worker.cpp

[core] Another band-aid (#6322)

---

platform/macos/src/MGLMapView.mm
src/mbgl/algorithm/generate_clip_ids.hpp
src/mbgl/geometry/line_atlas.hpp
src/mbgl/gl/gl.cpp
src/mbgl/renderer/symbol_bucket.hpp
src/mbgl/style/paint_property.hpp
src/mbgl/tile/tile_id.hpp
src/mbgl/tile/vector_tile.cpp
src/mbgl/util/merge_lines.cpp
src/mbgl/util/merge_lines.hpp
test/src/mbgl/test/conversion_stubs.hpp

Unordered Map

---

src/mbgl/renderer/symbol_bucket.hpp

Fixes #3980 
/cc @jfirebaugh @lucaswoj @incanus

Putting friend class SymbolLayout back

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/ViewSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Removed Hungarian notation and fixes other Checkstyle issues in map package. @tobrun can you review?

[android] Cleans up code in map package

---

Makefile

[android] - optimise execution time of Android CI integration

---

src/mbgl/geometry/feature_index.cpp

[core] Allow queryRenderedFeatures prior to symbol placement

---

src/mbgl/actor/thread_pool.cpp
src/mbgl/actor/thread_pool.hpp

[core] Fix ThreadPool race condition

---

platform/android/MapboxGLAndroidSDK/build.gradle

[android] update mas dependency

---

include/mbgl/storage/default_file_source.hpp
platform/default/default_file_source.cpp
platform/default/mbgl/storage/offline_database.cpp
platform/default/mbgl/storage/offline_database.hpp
test/storage/offline_database.cpp

[core] allow offline region metadata to be updated

---

include/mbgl/gl/gl.hpp
src/mbgl/gl/gl.cpp

As recommended in https://www.opengl.org/wiki/GLAPI/glGetError
/cc @tmpsantos

Check glGetError in a loop

---

platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm
platform/darwin/src/NSPredicate+MGLAdditions.mm
platform/darwin/test/MGLFilterTests.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/6244
cc @1ec5 @frederoni

Add more predicate operator to mbgl filter translations

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties

See https://github.com/mapbox/mapbox-gl-native/issues/6418.
This PR only updates the `CHANGELOG`.
/cc: @cammace for review.

Release Android v4.2.0-beta.3

---

platform/ios/app/MBXViewController.m

Carryover of https://github.com/mapbox/mapbox-gl-native/pull/6389 to avoid Emoji in the branch name, which is busting Travis. 
😭 
/cc @1ec5

[ios] revamp settings/debug UI in test app

---

platform/darwin/test/MGLOfflineStorageTests.m

Just want to run this a few times and try to reproduce -> https://www.bitrise.io/build/4a53af4219ae7884

Fix for flaky CI test

---

platform/linux/README.md
platform/qt/README.md

Had these done, but forgot to update my branch before pushing to master.

[glfw, qt] Added missing docs

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

Closes #5737.
Treat camera change equal to a gesture
Review @cammace 
cc @zugaldia

[android] - disable tracking when a camera change occurs,

---

platform/qt/qmlapp/main.qml

It is going to be part of our documentation, so make it KISS as possible.

[Qt] Simplify QML example

---

platform/qt/config.cmake
platform/qt/include/QQuickMapboxGL
platform/qt/include/QQuickMapboxGLMapParameter
platform/qt/include/qmapbox.hpp
platform/qt/qmlapp/main.cpp
platform/qt/qt.cmake
platform/qt/qt4.cmake
platform/qt/qt5.cmake
platform/qt/src/async_task.cpp
platform/qt/src/qmapbox.cpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_p.hpp
platform/qt/src/qquickmapboxgl.cpp
platform/qt/src/qquickmapboxgl.hpp
platform/qt/src/qquickmapboxglmapparameter.cpp
platform/qt/src/qquickmapboxglmapparameter.hpp
platform/qt/src/qquickmapboxglrenderer.cpp
platform/qt/src/qquickmapboxglrenderer.hpp
platform/qt/src/qt_geojson.hpp
platform/qt/src/run_loop.cpp
platform/qt/src/timer.cpp

Make some headers private, so we only commit to the QML API.

[Qt] Header cleanup

---

.gitignore
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLBaseStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLRasterSource.h
platform/darwin/src/MGLRasterSource.mm
platform/darwin/src/MGLRasterStyleLayer.h
platform/darwin/src/MGLSource.h
platform/darwin/src/MGLStyle.h
platform/darwin/src/MGLStyleLayer.h.ejs
platform/darwin/src/MGLSymbolStyleLayer.h
platform/darwin/src/MGLVectorSource.h
platform/ios/jazzy.yml
platform/macos/jazzy.yml

Hitting #5959 and #5960. 
/cc @boundsj @1ec5 @frederoni

flesh out iOS runtime styling docs

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineUtils.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/UpdateMetadataActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/OfflineUtils.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_metadata_update.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/scripts/generate-test-code.js
platform/android/src/jni.cpp

closes #6402 
Provides Android binding integration in the core feature of updating metadata.
Hasn't been added to a specific milestone (needs discussion-label).

6402 update offline metadata android

---

src/mbgl/gl/context.cpp
src/mbgl/gl/state.hpp

[core] Mark tracked state as dirty when the tracked object is destroyed

---

platform/android/MapboxGLAndroidSDK/build.gradle

[android] - update to lost 1.1.1

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java

Fixes #6443 
cc @mick @zugaldia

[android] update telemetry user-agent

---

cmake/core-files.cmake
include/mbgl/gl/gl.hpp
include/mbgl/platform/default/headless_view.hpp
platform/android/src/native_map_view.cpp
platform/default/glfw_view.cpp
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm
platform/qt/src/qmapbox.cpp
src/mbgl/geometry/vao.cpp
src/mbgl/gl/context.cpp
src/mbgl/gl/debugging.cpp
src/mbgl/gl/debugging.hpp
src/mbgl/gl/extension.cpp
src/mbgl/gl/extension.hpp
src/mbgl/gl/gl.cpp
src/mbgl/gl/value.cpp
src/mbgl/gl/vertex_array.cpp
src/mbgl/gl/vertex_array.hpp
src/mbgl/renderer/painter.cpp

They're currently all in the gl.hpp/cpp files.

Pull OpenGL extension loading into their own headers

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/camera/CameraPositionTest.java

[android] - convert bearing from core to degrees

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/ToolbarComposer.java

Closes #6488:
- Fixes state of Polygon when recreating (resolves crash)
- Refactor into static config inner class (thoughts?)
- Introduces a toolbar composer class (thoughts?)
- cleanup code PolygonActivity

[android] - fix polygon test activity

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CustomSpriteActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_add_sprite.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/src/jni.cpp

[android] add/remove Sprite Image

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Fixes regression introduced in #6491

[android] - make MyLocationView converts to degrees

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Follow up on #6556.
Closes #6512.

Rework setStyleUrl() logic to avoid NPE as per #6512 

---

Makefile
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/BackgroundLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Filter.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Function.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Property.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/RasterLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property.java.ejs
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/Source.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/VectorSource.java
platform/android/scripts/generate-style-code.js

Update Runtime Style JavaDoc

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTintActivity.java

Refs https://github.com/mapbox/mapbox-gl-native/pull/6413#pullrequestreview-970386

[android] - correct focal point with padding and tilt enabled 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

[android] - correct focal point data when double tapping

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

[android] - invalidate focal point when setting MyLocationView padding

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Filter.java
platform/android/src/style/android_conversion.hpp
platform/android/src/style/value.cpp

- Fixes #6605 (local ref table overflow)
- Fixes issue with null elements in collections
- Hides implementation details in public API to avoid confusion (Eg Statement implementation classes)
Review @tobrun

[android] Runtime Style Filter enhancements

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java

[android] - close response body to avoid connection leak

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Fixed issue for MyLocationView not correctly interpolating cursor position - related to [6649](https://github.com/mapbox/mapbox-gl-native/issues/6649)

[android] Fixed wrong location view interpolation

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/almeros/android/multitouch/gesturedetectors/TwoFingerGestureDetector.java

[android] Fix gestures when MapView is not full screen

---

platform/macos/src/NSImage+MGLAdditions.mm

Followup to last-minute refactoring in #6637.
/cc @friedbunny @rmnblm

Fix macOS compiler error — -[NSImage(MGLAdditions) mgl_spriteImage]

---

README.md

better formatting for external libraries listing

---

platform/android/src/style/value.cpp
platform/android/src/style/value.hpp

[android] don't delete local reference on value copy

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java

Makes MarkerViewManager more robust when trying to mutate markers that were already removed. 
Resolves memory leak mentioned in #6715 
closes #6698 
closes #6715

MarkerView more robust when updates are asynchronous

---

platform/android/MapboxGLAndroidSDK/proguard-rules.pro
platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/proguard-rules.pro
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java

This PR consists out 2 commits:
- first one fixes proguard issues inside the SDK
- second commit fixes proguard related issues with the test app (dependencies)
closes #6700

6700 proguard update

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java

follow up from #6646, added reusable point to Projection instead of Mapview.

Reusable point fromScreenLocation

---

platform/darwin/src/MGLTileSet.h
platform/macos/macos.xcodeproj/project.pbxproj

Added MGLTileSet files to the macOS project. Also reformatted some MGLTileSet documentation.
/cc @boundsj

Add MGLTileSet to macOS project

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

/cc @1ec5 @boundsj @frederoni @incanus

Prepare for ios-v.3.4.0-beta.1 release

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/DynamicMarkerChangeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_dynamic_marker.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_manual_zoom.xml
platform/android/src/jni.cpp

in https://github.com/mapbox/mapbox-gl-native/pull/6660 we updated the way we get and update our camera options. This now needs to be reflected in MyLocationView code when we track the user heading.
- Using `setCompass(0)` always shows the MyLocationView facing north when we track the user location and the heading.
- Using ` setCompass(gpsDirection + bearing)` not only shows the direction  of the gps but recalculates it based in current heading of the map.
Review @zugaldia / @cammace

[android] - fixup MyLocationView heading

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/MapInDialogActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_map_in_dialog.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/fragment_dialog_map.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/scripts/generate-test-code.js

Will help in debugging issue https://github.com/mapbox/mapbox-gl-native/issues/6634. 
cc: @mapbox/android

Adds map dialog activity to testapp

---

platform/android/src/style/sources/geojson_source.cpp
platform/android/src/style/sources/source.cpp
platform/android/src/style/sources/source.hpp

Cleans up explicit repaint calls when updating geojson source
Review @tobrun

[android] geojson source - remove explicit repaint requests

---

src/mbgl/style/source_observer.hpp
src/mbgl/style/sources/geojson_source_impl.cpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
test/src/mbgl/test/stub_style_observer.hpp
test/style/source.test.cpp

Fixes #6757 
Review @tmpsantos  / @brunoabinader ?

[core] Reload geojson source on url change

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RealTimeGeoJsonActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_default.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Adds same example as GL-JS [here](https://www.mapbox.com/mapbox-gl-js/example/live-geojson/). 

[android] - add realtime geojson example from gl-js

---

src/mbgl/style/style.cpp
test/style/source.test.cpp

Fixes formatting issues in #6770
cc @jfirebaugh

[core] fixup formatting on #6770

---

platform/android/bitrise.yml

This PR:
- introduces more separate steps
- adds additional console messages
- adds slack integration to all workflows
- general cleanup
TODO:

Android Bitrise cleanup

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java

[android] - cap width/height at maximum, don't throw exception.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java

Resolves first todo for #5797. Other open todo is:

[android] - only pin certificates on current used environement.

---

platform/android/src/jni.cpp

[android] fix exception class

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CompassViewSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_dynamic_marker.xml
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java

This PR tackles 2 issues:
- usage of Timer in CompassView
- feature request for making fading optional (closes #3252)

[android] - remove timer from compassView, make fading optional

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java

[android] - MarkerView is responsible for managing height and width

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

closes #6815, targets `release-android-v4.2.0`.
Fixes [issue](https://github.com/mapbox/mapbox-gl-native/issues/6815#issue-185225677) with MyLocationTracking enabled with compass bearing.
Fixes [issue](https://github.com/mapbox/mapbox-gl-native/issues/6815#issuecomment-256310224) with MyLocationTracking enabled with GPS bearing.

Tracking mode fixes

---

src/mbgl/geometry/vao.hpp

Refs #5731
cc @pveugen @kkaefer @friedbunny

[core] Band-aid for crash triggered by unbound element buffer

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/directions/DirectionsActivity.java

Closes #6811 
cc: @tobrun for review

updated directions example in testapp to v5

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/build.gradle

Closes https://github.com/mapbox/mapbox-gl-native/issues/5930
cc: @tobrun for review

removes sdk manager plugin

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxSymbolCountActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/raw/test_points_utrecht.geojson
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Adds a test activity to test querying on rendered symbols.
review @tobrun

[android] add test activity for symbol querying

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java

[android] - only calculate offset margins in viewport InfoWindow 

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/customlayer/CustomLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/customlayer/ExampleCustomLayer.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_custom_layer.xml
platform/android/src/example_custom_layer.cpp

Little more clarity about how to use CustomLayer::update to trigger a repaint.

[android] update custom layer example with invalidation example

---

package.json
src/mbgl/style/source_impl.cpp
src/mbgl/style/source_impl.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/geometry_tile_worker.cpp
src/mbgl/tile/geometry_tile_worker.hpp
src/mbgl/tile/tile.hpp

Fixes #6820. Corresponding test-suite PR: https://github.com/mapbox/mapbox-gl-test-suite/pull/158.
This will need to be cherrypicked to the iOS and Android release branches.

[core] Separate pathway for notifying workers of new images/glyphs

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/MathUtils.java

converts bearing from core for invalidating the CameraPosition. 

Convert bearing from core

---

cmake/shaders.cmake
package.json
scripts/build-shaders.js

See https://github.com/mapbox/mapbox-gl-shaders/pull/33.
Corresponding GL JS PR: https://github.com/mapbox/mapbox-gl-js/pull/3566/
👀 @jfirebaugh

Update to mapbox-gl-shaders with vertex/fragment preludes

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

[android] - fix inconsistency of float usage in Camera params

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_symbollayer.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_symbol_layer.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Testcase for:
- #6928 
- #6932

[android] test activity for runtime changes to symbols

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/net/ConnectivityReceiver.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionStatus.java

We'll also need to cherry-pick this into master, closing other PR. I'm still getting 28 warnings when generating the javadoc but these seem to all be related to the excluded files. 
cc: @tobrun

javadoc fixes

---

src/mbgl/map/map.cpp

Cherry-pick of #6972 to iOS release branch.
cc @boundsj

[core] Ensure correct GL context in Map::onLowMemory()

---

src/mbgl/map/map.cpp
src/mbgl/style/style.hpp

Fixes #6129. Alternate take on #6608.
Needed for getting the regression test for #6932 to work correctly.

[core] Default camera position to that specified by the style

---

platform/node/src/node_map.cpp
platform/node/test/suite_implementation.js

Fixes several causes of needless or redundant setting of map camera options. Needed for #6932.

[node] Fix camera logic

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java

[android] - check for values for a camera position update

---

Makefile

[android] - update make clean for Android Wear module

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

[android]  - allow using rotate gesture when not tracking user 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Port of fix in #7015 targetting `android-release-v4.2.0`.
Review @cammace.

[android] - getMarkerViews in rect should return in bound views

---

package.json
src/mbgl/style/layer_observer.hpp
src/mbgl/style/layers/layer.cpp.ejs
src/mbgl/style/layers/line_layer.cpp
src/mbgl/style/layers/symbol_layer.cpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
test/src/mbgl/test/stub_layer_observer.hpp
test/style/style_layer.test.cpp

Cherry pick 6932 into android-v4.2.0 branch

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
platform/android/src/jni.cpp
platform/android/src/style/layers/layer.cpp
platform/android/src/style/layers/layer.hpp
platform/android/src/style/sources/source.cpp
platform/android/src/style/sources/source.hpp

[android] return layer/source ownership on remove

---

include/mbgl/map/map.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
platform/android/src/jni.cpp
platform/android/src/style/layers/layer.cpp
platform/android/src/style/layers/layer.hpp
platform/android/src/style/sources/source.cpp
platform/android/src/style/sources/source.hpp
src/mbgl/map/map.cpp
src/mbgl/style/layers/custom_layer_impl.cpp
src/mbgl/style/layers/custom_layer_impl.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp

Brings #7014 and #7039 to the 4.2.0 release.

Cherry pick 7039

---

src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/geometry_tile_worker.cpp

Fixes https://github.com/mapbox/mapbox-gl-native/issues/7050

Cherry pick #7025

---

src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/geometry_tile_worker.cpp

Fixes #7051.
/cc: @ivovandongen for review.

Prevent duplicate symbol placement requests

---

package.json
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

[android] Cherry pick #7044 (Update GLSL + ensure binding to OpenGL ES 2.0)

---

package.json

[build] Added nan@2.4.0 dependency

---

platform/darwin/src/MGLStyle.mm

Cleanup per https://github.com/mapbox/mapbox-gl-native/pull/7060#issuecomment-260517173.

[ios, macos] refs #7060: properly check removed layers & sources

---

src/mbgl/layout/symbol_layout.cpp
src/mbgl/renderer/painter_symbol.cpp
src/mbgl/renderer/symbol_bucket.cpp
src/mbgl/renderer/symbol_bucket.hpp

Follows https://github.com/mapbox/mapbox-gl-js/commit/b9d95095c63a8e0193b6ee391ab308e75e1ecea3.

[core] Use indexed rendering for collision boxes

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

ios-v3.4.0-beta.3

---

Makefile

Should be faster than npm update.

[build] Use npm install --ignore-scripts

---

platform/darwin/scripts/generate-style-code.js
platform/darwin/scripts/style-spec-overrides-v8.json
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.h

Cherry picked https://github.com/mapbox/mapbox-gl-native/pull/6107/commits/792d75b89370a84318402aef9e609d235f1ebd66 from master
@boundsj @1ec5 👀

Override style spec documentation

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Updated the iOS and macOS changelogs to mention #7091.
/cc @kkaefer

Update changelogs for #7091

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

[android] - allow compass update without animation

---

platform/ios/DEVELOPING.md
platform/macos/DEVELOPING.md

Added instructions for localizing the iOS and macOS SDKs.
/cc @friedbunny @YunjieLi @tony-cj

Document localization workflow

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PressForMarkerActivity.java

[android] - delay invalidating marker views

---

src/mbgl/style/source_impl.cpp

Cherry pick 7091 into v4.2.0

---

platform/android/MapboxGLAndroidSDK/build.gradle

Fixes #7129.
@cammace please review.
/cc: @tobrun @adavis @Guardiola31337

Remove explicitely guava from gradle import

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_map_simple.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/scripts/generate-test-code.js

Fixes #6481.
cc/ @cammace @zugaldia @tobrun

Add simple map activity to testapp

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java

Cherry picking #7133 to master.

Allow deselection of a MarkerView not found in current viewport

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java

This PR allows to deselect markers that aren't found in the current viewport.
Review @zugaldia.

[android] - allow deselection of out of viewport MarkerView

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
src/mbgl/style/source_impl.cpp

cc @1ec5 @kkaefer 
ref https://github.com/mapbox/mapbox-gl-native/pull/7091

Cherry pick 7091 into iOS v3.4.0

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

[android] - use double to restore instance state of MyLocationView

---

bin/render.cpp

Makes it possible to render images with larger scale factor than 1 via render.cpp

Add ratio argument to render.cpp

---

platform/darwin/src/NSValue+MGLStyleEnumAttributeAdditions.h
platform/darwin/src/NSValue+MGLStyleEnumAttributeAdditions.h.ejs
platform/darwin/src/NSValue+MGLStyleEnumAttributeAdditions.mm
platform/darwin/src/NSValue+MGLStyleEnumAttributeAdditions.mm.ejs

Fixes https://github.com/mapbox/mapbox-gl-native/issues/7168
cc @1ec5

Use namespaced property names in style NSValue category

---

platform/darwin/src/MGLMultiPoint.mm
platform/darwin/src/MGLPointCollection.mm
platform/ios/app/MBXViewController.m

Fixes issue noted in https://github.com/mapbox/mapbox-gl-native/pull/7083#pullrequestreview-8705064
cc @1ec5

Fix integer formatting in formatted exception strings

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraAnimationTypeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java

Yesterday we merged Timber #6372  but in meantime another commit with a log message was merged.
cc @kkaefer @ivovandongen

[android] - fixup timber merge

---

platform/android/tests/docs/ACTIVITY_SANITY_TEST.md

Fixes #7147.
Cc/ @tobrun @zugaldia

Fix ACTIVITY_SANITY_TEST.md file with new generation command

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

[android] - fix null pointer on Map init

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

closes #7187, Review @ivovandongen

[android] - handle null location update for MyLocationView

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

[android] add source_did_change event to intdef list

---

platform/ios/ios.xcodeproj/project.pbxproj

This should fix bitrise CLI failing for iOS in our release branch.
cc: @ivovandongen @tobrun for review

Cherrypick #6948 into release branch

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java

WIP, Closes #7175. 
@cammace 
can you validate that this solves the issue? 
or provide clear steps to reproduce?
Not seeing the log message locally.

[android] - hardware layer when animate CompassView

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Cherry pick 7146

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Cherry pick #7199 
Review @tobrun

Cherry pick #7199

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/feature/QueryRenderedFeaturesBoxCountTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/feature/QueryRenderedFeaturesPropertiesTest.java

Locally this tests works but on CI it fails.
Short term solution is to ignore the test to unblock others.

[android] - disable CI failing test

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_marker_view_scale.xml

Related to #7239, tilt wasn't getting applied to MarkerViews.

setting MarkerView tilt when adding it to the map

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
platform/darwin/src/MGLRuntimeStylingTests.m.ejs
platform/darwin/src/MGLStyle.mm
platform/darwin/test/MGLBackgroundStyleLayerTests.m
platform/darwin/test/MGLCircleStyleLayerTests.m
platform/darwin/test/MGLFillStyleLayerTests.m
platform/darwin/test/MGLFilterTests.mm
platform/darwin/test/MGLLineStyleLayerTests.m
platform/darwin/test/MGLMapViewTests.h
platform/darwin/test/MGLMapViewTests.m
platform/darwin/test/MGLMapViewTests.xib
platform/darwin/test/MGLRasterStyleLayerTests.m
platform/darwin/test/MGLSymbolStyleLayerTests.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/test/MGLSourceTests.m
platform/macos/macos.xcodeproj/project.pbxproj
src/mbgl/style/style.cpp
test/style/style.test.cpp

Check for duplicate source IDs

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Annotation.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Icon.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/IconFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MultiPoint.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Polygon.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/PolygonOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Polyline.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/PolylineOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java

Cherry picks https://github.com/mapbox/mapbox-gl-native/pull/7013 into master
cc: @tobrun for review

cherry picked 7013 into master

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/annotations/MarkerViewTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/feature/QueryRenderedFeaturesBoxCountTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/feature/QueryRenderedFeaturesHighlightTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/feature/QueryRenderedSymbolBoxCountTest.java

This PR ignores some tests on CI, these fail for an to be investigated reason.
Refs #7221.
cc @kkaefer

[android] - ignore unreliable tests

---

platform/ios/CHANGELOG.md

Merge release ios v3.3.7 into master

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java

Cherry pick #7237 into android v4.2.0

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

Pulled in external contribution from #7230 to make our CI run. 

[android] Fix javadoc for MapboxMap.updateMarker()

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/almeros/android/multitouch/gesturedetectors/TwoFingerGestureDetector.java

[android] - make rotation gesture easier to trigger

---

cmake/core-files.cmake
include/mbgl/style/function.hpp
include/mbgl/style/property_value.hpp
src/mbgl/programs/fill_program.cpp
src/mbgl/style/cross_faded_property_evaluator.cpp
src/mbgl/style/cross_faded_property_evaluator.hpp
src/mbgl/style/function.cpp
src/mbgl/style/paint_property.hpp
src/mbgl/style/property_evaluator.cpp
src/mbgl/style/property_evaluator.hpp

Shuffling some code around in preparation for adding support for data-driven function types.

[core] Function cleanup

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

[android] - refactor marker selection and listener invocation

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.java

Cleans up our initialisation code related to MapboxMapOptions in MapboxMap and propagates the initialisation code to the classes responsible for that configuration. While I feel current progress is an improvement, I'm open to alternatives of initialising our components. 

[android] - cleanup initialisation code for MapboxMap

---

platform/android/bitrise.yml

[android] - fix ndk stack CI step

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

closes #7350, can be tested with CameraPositionActivity.java

[android] - invalidate camera after gesture, cleanup.

---

platform/qt/src/bidi.cpp

[Qt] Fix build when ICU is disabled

---

platform/node/test/suite_implementation.js
src/mbgl/map/map.cpp
src/mbgl/style/source_impl.cpp

Had to leave out the render tests as it depends on other changes that we don't want to bring into the release.
Fixes #7244

Cherry pick 7242

---

platform/android/MapboxGLAndroidSDK/proguard-rules.pro
platform/android/MapboxGLAndroidSDKTestApp/build.gradle

[Android] Cherry pick #7389 into release

---

platform/android/MapboxGLAndroidSDKTestApp/proguard-rules.pro

Closes https://github.com/mapbox/mapbox-gl-native/issues/7412

Cherry pick 7411 into release branch

---

platform/android/MapboxGLAndroidSDK/gradle.properties

Need to change version name for release.

Change version for release

---

platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qquickmapboxglrenderer.cpp

It will create or update a source. Right now only GeoJSON sources are mutable and can be updated using this method.

[Qt] Implement updateSource

---

platform/macos/config.cmake

Add -Wl,-bind_at_load to node.js bindings on macOS

---

package.json
platform/node/test/suite_implementation.js
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/tile.hpp

[core] Mark tile as incomplete while redoing placement

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

cc @1ec5 @friedbunny @frederoni

[ios] Update podspec for release 3.4.0 beta 5

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewScaleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_marker_view_scale.xml

This is a port of https://github.com/mapbox/mapbox-gl-native/pull/6813/commits/dcd246c05a6058c141962fb0b2798d00ff1e8ac5 from the release branch to master. The underlying MarkerView system was refactored since cutting the release branch and this implementation has to be reimplemented.

[android] - add OnMarkerView callback

---

platform/android/MapboxGLAndroidSDKWearTestApp/src/main/java/com/mapbox/weartestapp/MapboxApplication.java

#6534 has resulted in regressing the wear test app. 
cc @cammace @kkaefer

Regression wear module

---

package.json
src/mbgl/layout/symbol_feature.hpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/layout/symbol_layout.hpp
src/mbgl/text/get_anchors.cpp
test/util/merge_lines.test.cpp

[core] Fix symbol rendering for multipoints

---

src/mbgl/style/bucket_parameters.cpp
src/mbgl/style/bucket_parameters.hpp
src/mbgl/style/layer_impl.hpp
src/mbgl/style/layers/background_layer_impl.cpp
src/mbgl/style/layers/background_layer_impl.hpp
src/mbgl/style/layers/circle_layer_impl.cpp
src/mbgl/style/layers/circle_layer_impl.hpp
src/mbgl/style/layers/custom_layer_impl.cpp
src/mbgl/style/layers/custom_layer_impl.hpp
src/mbgl/style/layers/fill_extrusion_layer_impl.cpp
src/mbgl/style/layers/fill_extrusion_layer_impl.hpp
src/mbgl/style/layers/fill_layer_impl.cpp
src/mbgl/style/layers/fill_layer_impl.hpp
src/mbgl/style/layers/line_layer_impl.cpp
src/mbgl/style/layers/line_layer_impl.hpp
src/mbgl/style/layers/raster_layer_impl.cpp
src/mbgl/style/layers/raster_layer_impl.hpp
src/mbgl/style/layers/symbol_layer_impl.cpp
src/mbgl/style/layers/symbol_layer_impl.hpp
src/mbgl/tile/geometry_tile_worker.cpp

Miscellaneous cleanups, see individual commits for details.

Bucket cleanup

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/TelemetryService.java

Uses a local broadcast receiver instead of a system wide receiver.

[android] - use local broadcast receiver for telemetry

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

[android] - fix null pointer on trackingsettings

---

platform/android/bitrise.yml

Refs https://github.com/mapbox/mapbox-gl-native/issues/6546#issuecomment-268896562
Review @jfirebaugh

[android] - downscale instrumentation tests on CI

---

src/mbgl/util/interpolate.hpp
test/style/functions.test.cpp

[core] Correct boolean function interpolation

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Release beta 6

---

Makefile
platform/android/MapboxGLAndroidSDKWearTestApp/build.gradle
platform/android/MapboxGLAndroidSDKWearTestApp/src/test/java/com/mapbox/weartestapp/utils/OffsettingHelperTest.java
platform/android/bitrise.yml

- update + cleanup tabs in bitrise.yml
- cleanup wear gradle file
- added new make target
- added unit test configuration to Wear module
- added dumy unit test to compile/test wear module
Review @cammace / @kkaefer

[android] - build and test wear module on CI

---

platform/android/CHANGELOG.md

[android] - update changelog for 4.2.1

---

platform/qt/app/mapwindow.cpp
platform/qt/config.qdocconf
platform/qt/include/qmapbox.hpp
platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapbox.cpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_p.hpp
platform/qt/src/qquickmapboxgl.cpp
platform/qt/src/qquickmapboxgl.hpp
platform/qt/src/qquickmapboxglrenderer.cpp
platform/qt/test/qmapboxgl.cpp

[Qt] Add docs for QMapboxGL

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

Closes #7514, more information [here](https://github.com/mapbox/mapbox-gl-native/issues/7514#issuecomment-270061950).

[android] - limit the scale factor for double tap zoom

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java

Refs #7575 and #5621 + moves validation of the access token inside Mapbox#getAccessToken.

[android] - cleanup accesstoken in OfflineManager

---

include/mbgl/util/color.hpp
src/mbgl/gl/value.cpp
src/mbgl/gl/value.hpp

GCC can't cope with it.
Fixes #7303.

[core] Remove constexpr from Color

---

LICENSE.md
platform/android/MapboxGLAndroidSDK/gradle-javadoc.gradle
platform/ios/app/Info.plist
platform/ios/benchmark/Info.plist
platform/ios/jazzy.yml
platform/ios/uitest/LaunchScreen.xib
platform/macos/jazzy.yml
test/src/app-info.plist

Here’s to an odder, more prime year than 2016.

Happy new year! 🎉

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java

[android] - move snapshot to NativeMapView

---

package.json

Forgot to rebase test-suite before merging #7586.
#monorepo

Fix test-suite SHA

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CircleLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_directions_bus_black_24dp.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_circle_layer.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_location_source.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Update to our Circle layer to investigate a bug.

Circle layer example update

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

[android] - rework MarkerView update mechanism

---

platform/android/CHANGELOG.md

We haven't been updating the changelog consistently while working on the 5.0.0 release. 
This PR tries to catch up on all the implemented changes.

[android] - update CHANGELOG.md for 5.0.0 with current progress

---

platform/macos/app/MapDocument.m

Include pitch in shared URL

---

platform/darwin/docs/theme/assets/js/jazzy.js

Added a bit of jQuery to work around realm/jazzy#714 within the browser.

Replace <q> tags with quotation marks in code blocks

---

package.json
platform/node/CHANGELOG.md

Let's get a node release out with the new add/remove image APIs.

Bump version, update changelog (v3.4.3)

---

CMakeLists.txt
package.json
platform/node/scripts/after_script.sh
platform/node/test/query.test.js
platform/node/test/render.test.js
platform/node/test/suite_implementation.js

Refs https://github.com/mapbox/mapbox-gl-js/pull/3834. Next step of `monorepo`.

[build] Use test-suite integration tests from mapbox-gl-js

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/TelemetryService.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/telemetry/ExponentialBackOffTest.java

This PR cherry picks some telemetry improvements from [WIP-LocationSource](https://github.com/mapbox/mapbox-gl-native/tree/4331-location-source) branch.
- exponential backoff counter when waiting for permissions to be accepted
- test for exponential backoff
- disabled logging (normally I would remove these logs but due to lack of tests keeping them around).
- usage of a local broadcast receiver 

[android] - cleanup telemetry

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java

Closes #7661 + added javadoc to getInstance method.
Review @kkaefer / @ivovandongen

[android] - synchronised mutators for thread safety in Mapbox

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Bump the podspec version in preparation for tagging and release.

[ios] Release v3.4.0-beta.7

---

platform/darwin/scripts/generate-style-code.js

[ios, macos] Temporarily ignore the fill extrusion layer

---

platform/darwin/src/MGLCircleStyleLayer.mm
platform/darwin/src/MGLFillStyleLayer.mm
platform/darwin/src/MGLLineStyleLayer.mm
platform/darwin/src/MGLStyleLayer.mm.ejs
platform/darwin/src/MGLSymbolStyleLayer.mm

Fix nilling out predicate

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java

fix typo in android docs

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec
platform/macos/README.md
platform/macos/docs/pod-README.md

Synchronized bundled README installation instructions with those in INSTALL.md. Bumped screenshot up a bit. Corrected link to published documentation.

Correct podspecs, readmes

---

src/mbgl/style/style.cpp

The previous sorting criteria would sometimes allow
C > B, B > A but A > C, making the internal std::sort
code sometimes point to an invalid reference.
Fixes #7737

[core] Fix ambiguous condition on the sort criteria

---

src/mbgl/gl/debugging.cpp
src/mbgl/gl/debugging.hpp
src/mbgl/renderer/painter.cpp

Restore GL_KHR_debug messages in release builds

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Updated podspecs for v3.4.0-rc.1.

iOS SDK v3.4.0-rc.1

---

src/mbgl/layout/merge_lines.cpp
test/util/merge_lines.test.cpp

[core] Clean up merge_lines.cpp and add bounds checking

---

platform/android/CHANGELOG.md

Not sure how this got in here.

Remove conflict marker from changelog

---

platform/qt/qmapbox.qrc
platform/qt/qt4.cmake
platform/qt/qt5.cmake
platform/qt/resources/common.qrc
platform/qt/src/http_file_source.cpp
platform/qt/src/http_file_source.hpp

The CA certificate we are bundling will expire in Aug/2018.

[Qt] Use system defaults CA

---

platform/qt/include/qmapboxgl.hpp
platform/qt/src/http_request.hpp
platform/qt/src/qmapboxgl_p.hpp
platform/qt/src/qquickmapboxgl.hpp
platform/qt/src/qquickmapboxglrenderer.hpp

Fix when building with namespaces enabled.
http://wiki.qt.io/Qt_In_Namespace

[Qt] Fix build when using Qt namespaces

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java

[android] - deselect marker on infowindow click

---

include/mbgl/style/layer.hpp

[core] Include what you use

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Updated the iOS podspecs for version 3.4.0.

iOS SDK v3.4.0

---

platform/macos/INSTALL.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec
platform/macos/README.md
platform/macos/docs/pod-README.md

Updated macOS SDK podspecs for version 0.3.0. Also made the download link in the installation instructions easier to find.
/cc @friedbunny @frederoni

macOS SDK v0.3.0

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Closes #7086 
- call `MyLocationView.invalidate()` to redraw the MyLocationView after setting tilt
- call `MyLocationView.setTilt` after the CameraUpdate has finished animating

[android] - redraw MyLocationView when tilt changes programatically 

---

.travis.yml

Building a debug build with both GCC and clang is sufficient.
cc @brunoabinader @tmpsantos

[linux] Remove unnecessary rows from Travis CI matrix

---

platform/darwin/src/MGLShapeSource.h

Added note that clustering needs a GeoJSON source

Clarify that clustering option is for shape sources

---

platform/darwin/src/MGLShapeSource.h

Changed `@param URL` -> `@param url`

URL -> url

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/macos/CHANGELOG.md

- Updated the podspecs for v3.4.1.
- Also did some slight copy-editing, hope you don’t mind @fabian-guerra. 🙇
- [Changes since v3.4.0.](https://github.com/mapbox/mapbox-gl-native/compare/ios-v3.4.0...fb-ios-v3.4.1) Anything else that should go in the changelog that we’ve missed or should reword?

iOS SDK v3.4.1

---

platform/macos/app/AppDelegate.m
platform/macos/app/Base.lproj/MainMenu.xib

Short term fix for #7845.
Longer term, we should have a look at the [correct way of printing documents](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Printing/osxp_printapps/osxp_printapps.html#//apple_ref/doc/uid/20000861-BAJBFGED)

Enable printing on macOS

---

platform/default/headless_display.cpp
platform/macos/CHANGELOG.md
platform/macos/app/Info.plist
platform/macos/src/MGLOpenGLLayer.mm

Cherry-picked from #7834. Added the changelog blurb to the v0.3.1 section instead of the v0.3.0 section.

Allow use of integrated GPU

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

Closes #7850, Review @zugaldia

[android] - move pan gesture event to correct GestureDetector callback

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

Closes #6099.
Our old implementation didn't handle any click events for selected markers (in such a case we would fallback to the default OnMapClick interface and deselect current open markers). This PR allows the OnMarkerClick to be called for an selected marker. This gives the user the ability to override the default behaviour of deselecting the clicked selected marker. 

[android] - trigger marker click event for clicking selected marker

---

platform/darwin/src/MGLDistanceFormatter.h
platform/darwin/src/MGLDistanceFormatter.m
platform/darwin/test/MGLDistanceFormatterTests.m
platform/ios/CHANGELOG.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/jazzy.yml
platform/ios/src/Mapbox.h
platform/macos/jazzy.yml
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/src/Mapbox.h

Fixes #3331 
Cherry-picked `MGLDistanceFormatter` from https://github.com/mapbox/mapbox-gl-native/pull/7631
@1ec5 👀

Distance formatter

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

[android] - Config dismissing tracking modes with camera change

---

.travis.yml

This may help diagnose the intermittent CI failures.

[node] Run tests under apitrace

---

platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml

This PR makes sure the SDK exposed attributes found in public.xml are correctly mapped on attrs.xml.

[android] - update SDK exposed attributes in public.xml

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java

@cammace Can you please review this?

Disable double tap gesture to zoom in

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java

Bring the [changes](https://github.com/mapbox/mapbox-java/pull/307) did in `MAS` into `LocationSource`.
cc/ @zugaldia

Use WeakReference to avoid leaks

---

platform/android/MapboxGLAndroidSDKTestApp/gradle-config.gradle

In order to build the project using IntelliJ IDEA, some issues have to be fixed:
It doesn't affect AS at all.

IntelliJ IDEA support

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
platform/android/src/conversion/collection.hpp

[android] fix reference table overflow in query rendered features

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

This also adds dates to two previous releases that did not have them.

Update changelogs for DDS

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java
platform/android/src/jni.cpp

Fixes #7493 
I'm not receiving focal point changes from `onFocalPointChanged` listener, even having `myLocationEnabled` set to `true`.
cc/ @tobrun

[WIP] Compass click rotates around focal point (if available)

---

.travis.yml
scripts/travis_setup.sh

[node] Run test with logbt

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Added mention of #7786, #7989, #7902. Moved #7956 to the correct section.

Update changelogs for iOS SDK v3.5.0-beta.1

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Update podspec for release 3.5.0 beta 1

---

src/mbgl/annotation/annotation_manager.cpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/map/map.cpp
src/mbgl/programs/fill_program.cpp
src/mbgl/programs/fill_program.hpp
src/mbgl/programs/line_program.cpp
src/mbgl/programs/line_program.hpp
src/mbgl/renderer/painter_background.cpp
src/mbgl/renderer/painter_fill.cpp
src/mbgl/renderer/painter_line.cpp
src/mbgl/sprite/sprite_atlas.cpp
src/mbgl/sprite/sprite_atlas.hpp
test/sprite/sprite_atlas.test.cpp
test/text/quads.test.cpp

Fixes #6835 and simplifies the API and implementation.

[core] Clean up SpriteAtlas

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java

Avoid nullpointer when View receives invalidate callback

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

closes #7858, Follow up from #7922 (couldn't get CI bots to start).

Rotation sensor unavailable

---

platform/macos/CHANGELOG.md
platform/macos/src/MGLOpenGLLayer.mm

Reuse OpenGL context when switching screens

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java

[android] - only remove location updates when connected

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/macos/CHANGELOG.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec

Updated podspecs for iOS SDK v3.4.2 and macOS SDK v0.3.1.
/cc @friedbunny @frederoni

ios-v3.4.2, macos-v0.3.1

---

.travis.yml
Makefile
platform/qt/config.qdocconf
platform/qt/include/qmapbox.hpp
platform/qt/src/qmapbox.cpp
platform/qt/src/qmapboxgl.cpp

[Qt] Document QMapbox + qdoc fixes

---

platform/default/headless_backend_osmesa.cpp
platform/linux/src/headless_backend_egl.cpp

[linux] Don't manually activate context before destroying it

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs

[android] - remove obsolete filters

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java

[android] - move calculating a bounding box zoom level to projection.

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/dependencies.gradle

Closes https://github.com/mapbox/mapbox-gl-native/issues/8168.

Update to MAS 2.0.0-beta.2 and handle dependencies consistently

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/scripts/generate-style-code.js

Fix units in runtime styling javadoc

---

platform/ios/CHANGELOG.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/scripts/package.sh

Cherrypick 7773 7844

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java

[android] - reverse compass direction

---

benchmark/api/query.benchmark.cpp
platform/default/mbgl/gl/offscreen_view.cpp
platform/default/mbgl/gl/offscreen_view.hpp
platform/node/src/node_map.cpp
test/api/annotations.test.cpp
test/api/api_misuse.test.cpp
test/api/custom_layer.test.cpp
test/api/query.test.cpp
test/api/render_missing.test.cpp
test/api/repeated_render.test.cpp
test/map/map.test.cpp

In preparation for #8148, we should privatize this implementation.

Privatize OffscreenView implementation

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Follow up from #8121. Couldn't get the CI bots to work on that PR.

Fix a NPE that occurs when MapView is initialized

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

[android] - don't allow transforming to the same camera position

---

src/mbgl/layout/symbol_instance.cpp
src/mbgl/layout/symbol_instance.hpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/layout/symbol_layout.hpp
src/mbgl/text/glyph.hpp
src/mbgl/text/glyph_set.cpp
src/mbgl/text/quads.cpp
src/mbgl/text/quads.hpp
test/text/quads.test.cpp

Some work attempting to get under the memory ceiling in #7939.
cc @anandthakker

Reduce memory requirements for symbol layers

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/checkstyle.xml

Removes the unnecessary semicolon found and adds a rule to prevent it from happening again.
cc/ @tobrun

Add empty statement checkstyle rule and fix issues

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

#8113 omitted a link to itself.

Update changelogs for #8113

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Release 3.5.0 beta.2

---

src/mbgl/util/offscreen_texture.cpp
src/mbgl/util/offscreen_texture.hpp

Obsoletes https://github.com/mapbox/mapbox-gl-native/pull/8211 and paves the way to #8148

Privatize OffscreenTexture 

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties

References https://github.com/mapbox/mapbox-gl-native/issues/8221.

Updates version name and CHANGELOG after 5.0.0-beta.2 release

---

include/mbgl/util/traits.hpp
platform/default/bidi.cpp

[core] Support ICU cast when UCHAR_TYPE != char16_t

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLRasterStyleLayer.h
platform/darwin/src/MGLStyleValue.h
platform/darwin/src/MGLStyleValue.mm
platform/darwin/src/MGLStyleValue_Private.h
platform/darwin/src/MGLSymbolStyleLayer.h
platform/darwin/test/MGLStyleValueTests.swift
platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/docs/guides/For Style Authors.md
platform/macos/CHANGELOG.md
platform/macos/app/MapDocument.m
platform/macos/docs/guides/For Style Authors.md

Fixes https://github.com/mapbox/mapbox-gl-native/issues/8072

[ios, macos] Rename MGLStyleConstantValue to MGLConstantStyleValue

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/functions/CompositeFunction.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/functions/SourceFunction.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyValue.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs

[android] use PropertyValue for default values in functions

---

test/util/memory.test.cpp

[test] Increase memory test ceiling slightly

---

platform/android/scripts/ndk.sh

The [Android NDK r14 was released a few days ago](https://developer.android.com/ndk/downloads/revision_history.html) and ships with Clang 3.9, which [seems to have a regression around undefined variable template error message](https://github.com/mapbox/mapbox-gl-native/issues/7702).

Pin Android NDK version

---

platform/android/bitrise.yml

[android] - build aar only once for release builds

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/dependencies.gradle

Fixes https://github.com/mapbox/mapbox-gl-native/issues/8328.

[android] Update to MAS v2.0.0-beta.3

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

[android] - NPX mapZoomButtonController

---

platform/android/MapboxGLAndroidSDK/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml

Fixes https://github.com/mapbox/mapbox-gl-native/issues/8317.

[android] Include the telemetry service to simplify set up

---

platform/darwin/src/MGLFoundation.mm
platform/darwin/src/MGLFoundation_Private.h
platform/darwin/src/MGLOfflineStorage.mm

Cherry pick 8321 from master

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Mentioned #8298 and #8139. Copyedited recent additions. Shuffled some entries around.

Update changelogs for v3.5.0-beta.3

---

platform/macos/bitrise.yml

Fixes #8173 (probably by omitting `make xproj`).

[macos] Simplify bitrise.yml

---

platform/default/async_task.cpp
platform/default/run_loop.cpp
platform/default/timer.cpp
platform/node/src/node_map.cpp
platform/node/src/util/async_queue.hpp

[node, glfw] Cleanup libuv code

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties

This PR updates the CHANGELOG.md file and reverts the version name to SNAPSHOT.

[android] Release 5.0.0-beta.3

---

platform/android/config.cmake
platform/android/version-script

[android] Link with a version script to restrict symbol visibility

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml

Fixes #8157.
👀  @tobrun @zugaldia

Add changing compass view image feature

---

src/mbgl/renderer/line_bucket.cpp
src/mbgl/renderer/line_bucket.hpp

Ports https://github.com/mapbox/mapbox-gl-js/pull/4413, fixing https://github.com/mapbox/mapbox-gl-native/issues/7714.

[core] Never join coincident start/end points of LineStrings

---

cmake/test-files.cmake
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/tile/geometry_tile.cpp
test/tile/annotation_tile.test.cpp

Cherry pick https://github.com/mapbox/mapbox-gl-native/pull/8374 (that addresses https://github.com/mapbox/mapbox-gl-native/issues/8289) into the release branch.
cc @1ec5 @ivovandongen @tobrun @jfirebaugh

Cherry pick 8374

---

package.json
platform/node/CHANGELOG.md

Putting out a new release of node bindings.

[node] bump version, add changelog entry

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

[ios, macos] Update changelogs for 8374

---

package.json
platform/node/CHANGELOG.md

[node] bump version number; changelog entry

---

src/mbgl/shaders/symbol_sdf.cpp

Increase precision of shader variable

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

- Update podspec files.
cc @1ec5 @fabian-guerra @friedbunny

[ios] Release v3.5.0-rc.1

---

platform/android/MapboxGLAndroidSDK/proguard-rules.pro

Closes #8432, update the SDK proguard configuration with new files added this release.

[android] - update proguard configuration for 5.0.0

---

platform/android/dependencies.gradle

Fixes https://github.com/mapbox/mapbox-gl-native/issues/7643.

[android] Update dependencies to MAS v2.0.0 final

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] updated pod spec to release version

---

platform/android/MapboxGLAndroidSDK/gradle-javadoc.gradle
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties

Refs https://github.com/mapbox/mapbox-gl-native/issues/8452

Bump Android SNAPSHOT version

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Reverts https://github.com/mapbox/mapbox-gl-native/pull/8462

Bump podspec version for v3.5.0-rc.2

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Podspec update to final release 3.5.0

[ios] podspec update to 3.5.0

---

src/mbgl/shaders/circle.cpp
src/mbgl/shaders/debug.cpp
src/mbgl/shaders/fill.cpp
src/mbgl/shaders/fill_outline.cpp
src/mbgl/shaders/line.cpp
src/mbgl/shaders/line_sdf.cpp
src/mbgl/shaders/symbol_sdf.cpp

Addresses #8385
Updates shaders to reflect https://github.com/mapbox/mapbox-gl-js/pull/4476

Use highp for color attributes

---

src/mbgl/text/quads.cpp

@anandthakker and I paired on trying to understand how getSegmentGlyphs works, since we couldn't pick @ansis 's brain. Our goal was (1) make sure we understand how the function is supposed to work, and then (2) use the comments as guidelines to refactor the function so that some of the magic parts are less mysterious.

Verbose commenting on getSegmentGlyphs

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties

References https://github.com/mapbox/mapbox-gl-native/issues/8501.

[android] Release Android v5.0.1

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/VectorSource.java
test/map/map.test.cpp

[android] - update VectorSource javadoc

---

platform/android/src/java_types.cpp
platform/android/src/java_types.hpp
platform/android/src/style/android_conversion.hpp
platform/android/src/style/value.cpp
platform/android/src/style/value.hpp

[android] use more appropriate numeric types for filter conversion

---

.travis.yml
include/mbgl/util/enum.hpp
test/api/annotations.test.cpp

Ports #8336 to the release branch. Fixes #8528.

Fix android release branch build

---

src/mbgl/tile/geometry_tile.cpp
test/tile/vector_tile.test.cpp

[core] check null data in query source features

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/src/native_map_view.cpp

[android] - consitent use of milliseconds unit in java code

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CircleLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_circle_layer.xml

Refs #8200, this PR adds the possibility to toggle between styles for the CircleLayerActivity.
Closes https://github.com/mapbox/mapbox-gl-native/issues/8546

CircleLayerActivity with style toggle

---

platform/ios/src/MGLMapView.mm

Replaced UIActionSheet and UIAlertView with UIAlertController for the attribution sheet and telemetry opt-out alert, respectively. The sheet and alert look identical to how they did previously.
This change is loosely based on https://github.com/mapbox/mapbox-gl-native/pull/1497#issuecomment-100776747.
Fixes #8371.
/cc @incanus @frederoni

Replace UIActionSheet, UIAlertView with UIAlertController

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec

Updated the podspecs for macOS SDK v0.4.0-beta.1.

macOS SDK v0.4.0

---

cmake/core-files.cmake
cmake/test-files.cmake
include/mbgl/map/map.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp
proto/binary_program.proto
src/mbgl/gl/attribute.hpp
src/mbgl/gl/context.cpp
src/mbgl/gl/context.hpp
src/mbgl/gl/features.hpp
src/mbgl/gl/program.hpp
src/mbgl/gl/program_binary.cpp
src/mbgl/gl/program_binary.hpp
src/mbgl/gl/types.hpp
src/mbgl/gl/uniform.hpp
src/mbgl/map/map.cpp
src/mbgl/programs/binary_program.cpp
src/mbgl/programs/binary_program.hpp
src/mbgl/programs/program.hpp
src/mbgl/programs/program_parameters.hpp
src/mbgl/programs/programs.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/shaders/shaders.cpp
src/mbgl/shaders/shaders.hpp
src/mbgl/util/io.cpp
src/mbgl/util/io.hpp
test/programs/binary_program.test.cpp

Brings 3c91b6b7de487993e75de552ba44249740644e42 and its prerequisite d5c2920104ea733b8ed417d2b9bdbade61b049cd to the release branch.

Port binary shader caching to release branch

---

platform/macos/app/Base.lproj/MapDocument.xib
platform/macos/app/MapDocument.m

Show zoom level in window's title bar

---

src/csscolorparser/csscolorparser.cpp
src/csscolorparser/csscolorparser.hpp
src/mbgl/util/color.cpp
test/fixtures/style_parser/colors.info.json
test/fixtures/style_parser/colors.style.json
test/fixtures/style_parser/stop-zoom-value.style.json

Return none for invalid colors

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

[android] - apply mix/max zoom xml attributes

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Update podspecs and changelog for v3.5.1

---

src/mbgl/gl/gl.hpp

Thanks to @lbud for catching this out :bowing_man: 
/cc @tmpsantos

[Qt] Fix typo in gl.hpp

---

platform/android/dependencies.gradle

Fixes https://github.com/mapbox/mapbox-java/issues/429.

[android] Update LOST to latest version

---

mapbox-gl-native.pro

Fixes Qt static build (ref: https://bugreports.qt.io/browse/QTBUG-59281).
/cc @tmpsantos

[Qt] Fix Qt static build

---

src/mbgl/util/compression.cpp

[Qt] Fix build when zlib is compiled with -DZ_PREFIX

---

src/mbgl/style/source_impl.hpp
src/mbgl/style/style.cpp

[core] Invalidate cached tiles of disabled sources on relayout

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Update podspecs and changelog for v3.5.2

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java

Fixes #8549 
- Added compass drawable initialization in `UiSettings`.
:eyes: @tobrun

[android] Add compass drawable initialization in UiSettings

---

circle.yml

This allows us to remove Android from the Bitrise builds.

Run Firebase on Circle CI + publish binary metrics on Circle CI

---

platform/android/CHANGELOG.md

Added polygon holes and custom location source features to changelog.
👀  @tobrun

[android] Update changelog

---

platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml

Removed duplicated resources:
`public_string/mapbox_myLocationViewContentDescription`
`public_string/mapbox_compassContentDescription`
`public_string/mapbox_attributionsIconContentDescription`
👀  @tobrun

[android] Remove duplicated resources

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Post resetting tracking settings flag to avoid race condition

---

platform/macos/src/MGLMapView.mm

[macos] Fix pinch gesture scaling math

---

platform/android/src/native_map_view.cpp

Set firsRender flag to false when destroying the surface

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/LatLngBoundsActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/camera/CameraPositionTest.java
platform/android/build.gradle
platform/android/config.cmake
platform/android/src/jni.cpp
platform/android/src/map/camera_position.cpp
platform/android/src/map/camera_position.hpp
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
test/map/map.test.cpp
test/map/transform.test.cpp

This PR cherry picks #8744 &  #8765 to the release branch:

Cherry pick latlngbounds to release branch

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

[android] - avoid calling OnMarkerViewClickListener twice

---

src/mbgl/renderer/line_bucket.cpp

An equivalent of https://github.com/mapbox/mapbox-gl-js/pull/4634.

[core] Fix an issue with lines that have duplicate points

---

package.json
platform/node/CHANGELOG.md

I'm going to create a couple pre releases for testing. 
Todo:
/cc @tmpsantos @miccolis

Release node v3.5.0

---

circle.yml

closes #8813, this PR copies the same setup as with `Show statistics`.

[android] - fix publish snapshot step

---

cmake/core-files.cmake
src/mbgl/annotation/annotation_manager.cpp
src/mbgl/map/map.cpp
src/mbgl/sprite/sprite_atlas.cpp
src/mbgl/sprite/sprite_atlas.hpp
src/mbgl/sprite/sprite_atlas_worker.cpp
src/mbgl/sprite/sprite_atlas_worker.hpp
src/mbgl/sprite/sprite_parser.cpp
src/mbgl/sprite/sprite_parser.hpp
src/mbgl/style/style.cpp
src/mbgl/style/style.hpp
test/sprite/sprite_atlas.test.cpp
test/sprite/sprite_parser.test.cpp
test/style/source.test.cpp
test/style/style.test.cpp
test/style/style_layer.test.cpp
test/tile/annotation_tile.test.cpp
test/tile/geojson_tile.test.cpp
test/tile/raster_tile.test.cpp
test/tile/vector_tile.test.cpp

Merge https://github.com/mapbox/mapbox-gl-native/pull/8781

Move Sprite parsing to thread pool

---

platform/qt/app/mapwindow.cpp
platform/qt/src/qmapboxgl.cpp

Also write one example of how to use it on the low level API.
The Qt plugin will get it for free when we bump the Qt version.

[Qt] Add extrusions support

---

platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/ios/src/UIViewController+MGLAdditions.h
platform/ios/src/UIViewController+MGLAdditions.m

[ios] cherry-picked 8837

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Updated podspecs and changelog for v3.5.3

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/BuildingFillExtrusionActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_building_layer.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/src/style/layers/layer.cpp

[android] - add 3D buildings example

---

platform/android/src/style/layers/unknown_layer.cpp
platform/android/src/style/sources/unknown_source.cpp
src/mbgl/gl/context.cpp

[Throw by value, catch by reference](http://ptgmedia.pearsoncmg.com/images/0321113586/items/sutter_item73.pdf)

[core] Throw exceptions by value

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/dependencies.gradle

- bump android support library version to latest
- fixup dependencies to use the ones defined in the root of the project (`dependencies.gradle`)

[android] - bump android support library, fixup SDK dependencies

---

include/mbgl/map/view.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/painter.hpp
src/mbgl/util/offscreen_texture.cpp
src/mbgl/util/offscreen_texture.hpp

[core] Reuse fill-extrusion textures between frames

---

src/mbgl/style/style.cpp

Fixes #8871. Refs https://github.com/mapbox/mapbox-gl-js/pull/4700.

[core] When a layer is added, reload its source's tiles

---

Makefile

Fixes running a single test class command line

[android] fix ui test filter in makefile

---

platform/android/MapboxGLAndroidSDKTestApp/gradle-config.gradle
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/TokenUtils.java

Fixes #8783
👀  @zugaldia @tobrun

[android] Fix gradle developer config creation task with discussed suggestions

---

platform/default/default_file_source.cpp

Fixes #8955 by allowing a nullptr to reset the transform callback

[core] allow filesource url transform reset

---

platform/darwin/src/MGLStyleValue.h

Edited the documentation for identity interpolation mode to clarify its use.

[ios, macos] edited identity interpolation mode documentation

---

.travis.yml
Makefile
scripts/travis_setup.sh

[build] Use gdb 2017-04-08-aebcde5

---

cmake/mbgl.cmake

[core][ios] Use explicit submodule update for ios target

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

Closes #9028. Code in this PR is going to be refactored for DRY when merging to master (related to #8261).

[android] -  don't leak selected markers when removing

---

platform/darwin/src/MGLStyleValue.mm

Closes https://github.com/mapbox/mapbox-gl-native/issues/8571

[ios, macos] Change == to = in style function initializers

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLAnnotationView.mm
platform/ios/test/MGLAnnotationViewTests.m

Closes https://github.com/mapbox/mapbox-gl-native/issues/9005

[ios] Add annotation view initializer with annotation and reuse id

---

platform/macos/app/MapDocument.m

Enable macosapp’s View ‣ Traffic Night menu item and check it when that style is active.
Followup to #6301.

Enable View ‣ Traffic Night

---

src/mbgl/style/layers/custom_layer_impl.cpp

Missed some logging when cleaning up.

CustomLayer cleanup debug logging

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

[android] - stop location updates when toggling MyLocationView

---

platform/darwin/src/MGLLight.h
platform/darwin/src/MGLLight.mm
platform/darwin/test/MGLLightTest.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/9085

[ios, macos] Fix MGLLight.anchor to accept style functions

---

platform/ios/jazzy.yml
platform/macos/jazzy.yml

Addresses https://github.com/mapbox/mapbox-gl-native/issues/9087

[ios] Moved `MGLLight` in jazzy table of contents

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/res/values/dimens.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_press_for_marker.xml

This PR fixes the logo placement for creating a Mapview programatically + fixes the placement of non-default Logo locations in the testapp.

[android] - logo placement for creating a Mapview programatically

---

platform/android/dependencies.gradle

Fixes #8939 
cc/ @tobrun @zugaldia

[android] Update Lost to final version 3.0.0

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java

Closes #8990, still need to validate if with a test if this change is actually valid.

[android] - convert dp to pixels when getting meters per pixel at.

---

package.json
platform/node/CHANGELOG.md

Bump node version - v3.5.3

---

platform/ios/src/MGLMapView.mm

Fixes #9096
As @incanus and @jmkiley pointed out, this was a lifecycle issue I overlooked. The private _UILayoutSpacer was being deallocated before MGLMapView leaving a stale observer that raised an exception. This fix removes the observers if MGLMapView is moved to a nil window which is called before _UILayoutSpacer gets deallocated.

[ios] remove layout guide observers

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Release ios v3.6.0 beta.2

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Cherry pick #9133 + update CHANGELOG
cc/ @tobrun

[android] Cherry picking 9133

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

fixes "infinite" callbacks from #9177

dealing with "infinite" camera move callbacks

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

[android] - keep location tracking mode after screen rotation

---

src/mbgl/map/transform.cpp

Cherry picks https://github.com/mapbox/mapbox-gl-native/pull/9199 to the iOS 3.6.0 / Android 5.1.0 release branch.

fix #8300 flyTo for close points (release-ios-v3.6.0-android-v5.1.0)

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Closes #9132 , follow up from #9207, the CI bots didn't want to start when pushing the related branch.

Invalidating MyLocationView bearing when not following

---

cmake/test-files.cmake
include/mbgl/style/function/composite_function.hpp
src/mbgl/programs/symbol_program.hpp
test/programs/symbol_program.test.cpp

Fix undefined memory access in getCoveringRanges()

---

platform/darwin/src/MGLLight.h

Fixes https://github.com/mapbox/mapbox-gl-native/issues/9234

[ios, macos] mglspherical fix type

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/BitmapUtils.java

[android] - snapshot bitmap with view based content

---

platform/ios/app/MBXViewController.m

Wrote this for debugging purposes and thought it might be worth adding permanently.

[iOS] add runtime styling command for adding building extrusions

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Update pods spec for iOS v3.6.0-beta.3

---

scripts/generate-shaders.js

The main fix is switching from ifdef -> ifndef. The rest of the changes just make a cleaner diff.
This fixes `generate-shaders.js` so that it actually generates the same shaders as the committed ones (except for the symbol shaders which lag behind -js). I'm guessing a fix to the script was accidentally left out of https://github.com/mapbox/mapbox-gl-native/commit/2cbc3d3332e32054e9fdc5323fef8e98f5f99a79 which includes correct generated shaders.

fix shader generation script

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/PulseMarkerViewOptions.java

- Fixes pulse marker view options parcelable creator.
cc/ @tobrun

[android] Fix pulse marker view options parcelable creator

---

platform/android/CHANGELOG.md

Release Android v5.1.0-beta.5

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

7910: cancel tracking if ongoing animation is stopped manually

---

platform/ios/CHANGELOG.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/de.lproj/Localizable.strings
platform/ios/resources/hu.lproj/Localizable.strings

Added a partial Hungarian localization from Transifex. Also updated the German localization.

Added Hungarian localization

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Update pods spec for iOS v3.6.0-rc.1

---

include/mbgl/map/map.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm
src/mbgl/annotation/render_annotation_source.cpp
src/mbgl/annotation/render_annotation_source.hpp
src/mbgl/map/map.cpp
src/mbgl/renderer/render_source.hpp
src/mbgl/renderer/render_style.cpp
src/mbgl/renderer/render_style.hpp
src/mbgl/renderer/sources/render_geojson_source.cpp
src/mbgl/renderer/sources/render_geojson_source.hpp
src/mbgl/renderer/sources/render_image_source.hpp
src/mbgl/renderer/sources/render_raster_source.cpp
src/mbgl/renderer/sources/render_raster_source.hpp
src/mbgl/renderer/sources/render_vector_source.cpp
src/mbgl/renderer/sources/render_vector_source.hpp

Centralize tile cache size

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/ios/docs/guides/For Style Authors.md

Addresses https://github.com/mapbox/mapbox-gl-native/issues/9377

[ios] Add link to designing maps for mobile devices

---

platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

iOS v3.6.0 podspec bump

---

platform/android/dependencies.gradle

Follow up on #9394, currently testing integration with SNAPSHOT until final release of MAS lands.

Update MAS to latest for final release

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.java

- Fixes #9393 
👀 @tobrun @cammace

[android] Fix my location drawable getting tinted

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java

[android] - map's visible region fix

---

src/mbgl/layout/symbol_projection.cpp

Molly and I just did a quick JS to C++ port of mapbox/mapbox-gl-js#4853
As we were working on it, I noticed that in both the JS and native versions, `placeGlyphsAlongLine` assumes it's not being passed a label with 0 glyphs. That assumption appears to hold, but it's a bit brittle.
/cc @ansis @mollymerp

Fix issue #9457 (keep-upright for pitched lines)

---

platform/qt/src/qmapbox.cpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_p.hpp

Fix issues of concurrent access to the sqlite cache.
Fixes #9108.

[Qt] Share the DefaultFileSource for all QMapboxGL instances

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/src/native_map_view.cpp

A user that is forking our repo has reached out and proposed a change in our current onFling integration.
First tests locally show a more natural onFling integration vs what we have on master.

Fine tune fling gesture

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/res/values-fr/strings.xml
platform/darwin/resources/fr.lproj/Foundation.strings
platform/ios/framework/Settings.bundle/hu.lproj/Root.strings
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/fr.lproj/Localizable.strings
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/sdk/fr.lproj/Localizable.strings

Added a French localization to the Android SDK, French error strings to the iOS and macOS SDKs, and an example Hungarian settings bundle to the iOS SDK.
/cc @tobrun @fabian-guerra

Update French, Hungarian localizations

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

[android] add api to enable/disable tile prefetching

---

src/mbgl/renderer/image_manager.cpp
src/mbgl/renderer/image_manager.hpp
src/mbgl/renderer/render_style.cpp
src/mbgl/style/style_impl.cpp
test/renderer/image_manager.test.cpp

[core] Correctly track sprite loaded state through smart setStyle

---

platform/node/test/ignores.json

See https://github.com/mapbox/mapbox-gl-native/issues/9559
/cc @ChrisLoer @mollymerp

[test] Add native ignore for `text-justify/property-function`

---

src/mbgl/gl/context.cpp

[core] Work around Adreno 2xx GPU bugs (╯°□°）╯︵ ┻━┻)

---

circle.yml
platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/IconManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolylineActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_check_box.xml
platform/android/dependencies.gradle
platform/android/src/native_map_view.cpp
src/mbgl/gl/context.cpp

Release android v5.1.1

---

platform/android/MapboxGLAndroidSDK/proguard-rules.pro

- Fixes #9569 
👀 @tobrun @cammace

[android] Fix geojson source proguard issue

---

Makefile

This PR updates the make file with inline comments explaining the make target.
Refs #8390

Make target documentation

---

README.md

[docs] Add FOSSA 'license scan' badge

---

src/mbgl/gl/context.cpp

Cherry picks https://github.com/mapbox/mapbox-gl-native/commit/cebc3c8d4bac9df72983807c856def5d8954b212 from master into the release branch.

[android] Disable program caching on Adreno 3xx, 4xx, and 5xx GPUs due to known bugs

---

circle.yml
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/proguard-rules.pro
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/InfoWindowManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java

This PR cherry-picks commits for the v5.1.2 release and starts building snapshots.

Cherry-pick for android v5.1.2 + build snapshots

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Addresses https://github.com/mapbox/mapbox-gl-native/pull/9571#discussion_r130041745

[ios] tilt gesture type fix

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Bump podspec to 3.6.1

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java

This PR workarounds the crash shown in #9649 while we work on resolving the upstream issue in https://github.com/mapbox/mapbox-java/issues/527.

Try/catch initialization of Telemetry

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java

[android] - fix OnCameraMoveStartedListener typo

---

platform/android/dependencies.gradle

[android] - bump MAS dependency

---

platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties
platform/android/dependencies.gradle

Release Android v5.1.2, update config

---

platform/ios/docs/doc-README.md
platform/ios/docs/pod-README.md

[ios] Update READMEs to link to help page

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

This PR replaces per method annotations for UiThread with a class level annotation.

Annotate MapboxMap class with UiThread

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

enable location change animation of MyLocationView by default

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Pod spec bump for iOS SDK v3.6.2

[ios] Update pods spec for iOS v3.6.2

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java
platform/android/dependencies.gradle

Release android v5.1.3

---

platform/android/CHANGELOG.md

This PR updates master with the changelog from the release branch.
For next releases we should commit to master first and cherry pick after.
Refs https://github.com/mapbox/mapbox-gl-native/issues/9683#issuecomment-323344353
cc @ragaisis

[android] - update changelog with 5.1.x patch releases

---

include/mbgl/style/conversion/make_property_setters.hpp
include/mbgl/style/layers/symbol_layer.hpp
include/mbgl/style/types.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Property.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/scripts/generate-style-code.js
platform/android/src/style/conversion/types.hpp
platform/android/src/style/conversion/types_string_values.hpp
platform/android/src/style/layers/symbol_layer.cpp
platform/android/src/style/layers/symbol_layer.hpp
platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLSymbolStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.mm
platform/darwin/test/MGLSymbolStyleLayerTests.mm
scripts/generate-style-code.js
src/mbgl/layout/symbol_layout.cpp
src/mbgl/style/function/categorical_stops.cpp
src/mbgl/style/function/identity_stops.cpp
src/mbgl/style/layers/symbol_layer.cpp
src/mbgl/style/layers/symbol_layer_properties.hpp
src/mbgl/style/types.cpp
src/mbgl/text/shaping.cpp
src/mbgl/text/shaping.hpp
test/text/quads.test.cpp

Companion PR of https://github.com/mapbox/mapbox-gl-js/pull/5183.

Add icon-anchor property

---

platform/node/test/ignores.json

Enable tests for #1350, #9704

---

platform/node/test/ignores.json
src/mbgl/renderer/layers/render_fill_layer.cpp

Ports https://github.com/mapbox/mapbox-gl-js/pull/5206 to gl-native.

[core] Fix z-fighting of translucent fills

---

platform/ios/app/MBXViewController.m

[ios] Fix slight mismerge in iosapp

---

src/mbgl/renderer/painter_fill.cpp

Hand-ports b05e5ddd347a9362535ca33cefceae92c51c998f

[core] Fix fill layer z-fighting

---

platform/node/test/render.test.js

Enables reusing a given random seed, auto-generating one if needed.
Reference / port of: https://github.com/mapbox/mapbox-gl-js/pull/5216

[node] Shuffle seed support

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Preparing for the first alpha release of v3.7.0, from the `master` branch.
/cc @fabian-guerra @boundsj @1ec5

[ios] Update podspecs for v3.7.0-alpha.1

---

.tx/config
platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/res/values-ru/strings.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values-uk/strings.xml
platform/darwin/resources/de.lproj/Foundation.stringsdict
platform/darwin/resources/ru.lproj/Foundation.strings
platform/darwin/resources/uk.lproj/Foundation.strings
platform/darwin/resources/vi.lproj/Foundation.stringsdict
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/lt.lproj/Localizable.stringsdict
platform/ios/resources/ru.lproj/Localizable.strings
platform/ios/resources/uk.lproj/Localizable.strings
platform/ios/resources/uk.lproj/Localizable.stringsdict
platform/ios/resources/zh-Hant.lproj/Localizable.strings
platform/ios/resources/zh-Hant.lproj/Localizable.stringsdict
platform/macos/CHANGELOG.md
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/sdk/hu.lproj/Localizable.strings
platform/macos/sdk/ru.lproj/Localizable.strings
platform/macos/sdk/uk.lproj/Localizable.strings
platform/macos/sdk/zh-Hant.lproj/Localizable.strings

Added Russian and Ukrainian localizations to the Android SDK from Transifex. Added a Hungarian localization to the macOS SDK. Updated Russian, Traditional Chinese, and Ukrainian localizations in the iOS and macOS SDKs.
/cc @fabian-guerra @tobrun @ivanrigovsky @Andygol @yzsolt

Russian, Ukrainian, Hungarian localizations

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

iosv3.6.3 podspec bump

---

include/mbgl/storage/offline.hpp
platform/default/mbgl/storage/offline.cpp
src/mbgl/util/tile_cover.cpp
src/mbgl/util/tile_cover.hpp

Follow up to [#9906(comment)](https://github.com/mapbox/mapbox-gl-native/pull/9906#discussion_r138017806)

Fix platform dependent number type `unsigned long` -> `uint64_t`

---

circle.yml
platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/src/main/java/com/almeros/android/multitouch/gesturedetectors/TwoFingerGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionStatus.java
platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java
platform/android/dependencies.gradle

This PR cherry picks changes needed for v5.1.4 to the release branch from master.

Release android v5.1.4

---

platform/android/MapboxGLAndroidSDK/gradle.properties

[android] Fix 5.2.0-SNAPSHOT CI build failing

---

circle.yml
package.json
platform/node/CHANGELOG.md
platform/node/scripts/after_success.sh

Going to start off with a prerelease since so much has changed since the last release.
/cc @brunoabinader @tmpsantos @jfirebaugh @ivovandongen

Release node v3.5.6

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Update changelog and bump pod spec.

---

cmake/core-files.cmake
src/mbgl/layout/symbol_projection.cpp
src/mbgl/layout/symbol_projection.hpp
src/mbgl/text/collision_feature.cpp
src/mbgl/text/collision_feature.hpp
src/mbgl/text/collision_index.cpp
src/mbgl/text/collision_index.hpp

The global/viewport based replacement for `CollisionTile`.
Compiles but not tested.
/cc @ansis

Start implementing `CollisionIndex`

---

package.json
platform/node/CHANGELOG.md

[node] Release v3.5.7 (#10164)

---

platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.h
platform/macos/src/MGLMapView.mm

in -[MGLMapView cameraThatFitsShape:shape direction: edgePadding:]
Merging changes from the release-agua branch for #10166

[ios][macos] Use CLLocationDirection for direction parameter 

---

cmake/core-files.cmake
include/mbgl/storage/default_file_source.hpp
include/mbgl/storage/file_source.hpp
include/mbgl/storage/resource.hpp
include/mbgl/tile/tile_necessity.hpp
platform/default/default_file_source.cpp
src/mbgl/algorithm/update_renderables.hpp
src/mbgl/annotation/annotation_tile.cpp
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/storage/resource.cpp
src/mbgl/style/sources/image_source.cpp
src/mbgl/tile/geojson_tile.cpp
src/mbgl/tile/geojson_tile.hpp
src/mbgl/tile/raster_tile.cpp
src/mbgl/tile/raster_tile.hpp
src/mbgl/tile/tile.cpp
src/mbgl/tile/tile.hpp
src/mbgl/tile/tile_loader.hpp
src/mbgl/tile/tile_loader_impl.hpp
src/mbgl/tile/vector_tile.cpp
src/mbgl/tile/vector_tile.hpp
test/algorithm/mock.hpp
test/algorithm/update_renderables.test.cpp
test/storage/default_file_source.test.cpp

In-depth explanation in https://github.com/mapbox/mapbox-gl-native/issues/10015#issuecomment-334286498

Prevent non-updating tiles by disallowing an expiration time of 0

---

cmake/core-files.cmake
include/mbgl/storage/default_file_source.hpp
include/mbgl/storage/file_source.hpp
include/mbgl/storage/resource.hpp
include/mbgl/tile/tile_necessity.hpp
platform/default/default_file_source.cpp
src/mbgl/algorithm/update_renderables.hpp
src/mbgl/annotation/annotation_tile.cpp
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/storage/resource.cpp
src/mbgl/style/sources/image_source.cpp
src/mbgl/tile/geojson_tile.cpp
src/mbgl/tile/geojson_tile.hpp
src/mbgl/tile/raster_tile.cpp
src/mbgl/tile/raster_tile.hpp
src/mbgl/tile/tile.cpp
src/mbgl/tile/tile.hpp
src/mbgl/tile/tile_loader.hpp
src/mbgl/tile/tile_loader_impl.hpp
src/mbgl/tile/vector_tile.cpp
src/mbgl/tile/vector_tile.hpp
test/algorithm/mock.hpp
test/algorithm/update_renderables.test.cpp
test/storage/default_file_source.test.cpp

Backport: Prevent non-updating tiles by disallowing an expiration time of 0

---

src/mbgl/util/i18n.cpp

[core] Fix out-of-bounds array access

---

platform/node/test/ignores.json

See https://github.com/mapbox/mapbox-gl-native/issues/10195.

Ignore raster-masking/overlapping-zoom

---

include/mbgl/storage/offline.hpp
include/mbgl/style/types.hpp
platform/default/mbgl/storage/offline.cpp
platform/default/mbgl/storage/offline_download.hpp
src/mbgl/annotation/render_annotation_source.hpp
src/mbgl/renderer/sources/render_geojson_source.hpp
src/mbgl/renderer/sources/render_image_source.hpp
src/mbgl/renderer/sources/render_raster_source.hpp
src/mbgl/renderer/sources/render_vector_source.hpp
src/mbgl/renderer/tile_pyramid.hpp
src/mbgl/util/mapbox.cpp
src/mbgl/util/mapbox.hpp
src/mbgl/util/tile_cover.cpp
src/mbgl/util/tile_cover.hpp
test/storage/offline.test.cpp
test/style/source.test.cpp
test/util/mapbox.test.cpp

[core] Move SourceType to the 'style' namespace

---

benchmark/function/camera_function.benchmark.cpp
benchmark/function/composite_function.benchmark.cpp
benchmark/function/source_function.benchmark.cpp
benchmark/parse/filter.benchmark.cpp
test/style/conversion/function.test.cpp
test/style/conversion/geojson_options.test.cpp
test/style/conversion/layer.test.cpp
test/style/conversion/light.test.cpp
test/style/filter.test.cpp

[core] Use convertJSON instead of RapidJSON directly

---

src/mbgl/algorithm/generate_clip_ids_impl.hpp
src/mbgl/renderer/render_tile.hpp
src/mbgl/renderer/renderer_impl.cpp
test/algorithm/generate_clip_ids.test.cpp

Backport: Determine need for clip ID based on actual layers/tiles

---

src/mbgl/storage/resource.cpp
test/storage/resource.test.cpp

Backport: Correctly alter sprite URLs 

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Podspec bump to iOS SDK v3.7.0-beta.2

[ios] Bump podspec to v3.7.0-beta.2

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

On stop null check

---

INSTALL.md
platform/android/README.md
platform/ios/INSTALL.md
platform/ios/README.md

Updating iOS & Android Maps SDK installation links to align with install updates to mapbox.com

updating ios & android install links

---

src/mbgl/style/style_impl.cpp

Cherry picks #10270 to the release branch.

[core] Add layer before notifying observer

---

src/mbgl/tile/geojson_tile.cpp

/cc @ericrwolfe @Guardiola31337 @danesfeder

Cherry-pick " [core] fix crash when querying GeoJSON tiles" into release-agua

---

platform/node/test/suite_implementation.js

Ports https://github.com/mapbox/mapbox-gl-js/commit/0069349550b263fdce9982d38183d9ab57ca7305

Add support for 'sleep' operation in render tests

---

src/mbgl/gl/context.cpp

Cherry picks #10253 to the agua release branch.

Blacklist VAO usage on adreno 3xx

---

src/mbgl/layout/symbol_instance.cpp
src/mbgl/layout/symbol_instance.hpp
src/mbgl/programs/symbol_program.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp

Start collision repaint

---

src/mbgl/renderer/buckets/symbol_bucket.cpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp

This moves symbol opacity buffer uploading from within `Placement::updateOpacities(...)` to the upload pass. @ChrisLoer

upload symbol opacity buffers in main upload pass

---

platform/android/CHANGELOG.md

- Addresses #10297
👀 @tobrun @zugaldia @lilykaiser

[android] release v5.2.0-beta.3

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/ZoomFunctionSymbolLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_symbols.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/actions.xml

Follow up on external PR in https://github.com/mapbox/mapbox-gl-native/pull/10097
cc @snijsure

Add symbol layer toggle

---

platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10228

[ios, macos] Iterate over annotations

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Bump podspec to v3.7.0-beta.3

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/res/values-bg/strings.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values-hu/strings.xml
platform/darwin/resources/bg.lproj/Foundation.strings
platform/darwin/resources/bg.lproj/Foundation.stringsdict
platform/darwin/resources/hu.lproj/Foundation.stringsdict
platform/darwin/resources/pt-BR.lproj/Foundation.strings
platform/ios/CHANGELOG.md
platform/ios/framework/Settings.bundle/bg.lproj/Root.strings
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/bg.lproj/Localizable.strings
platform/ios/resources/bg.lproj/Localizable.stringsdict
platform/ios/resources/pt-BR.lproj/Localizable.strings
platform/macos/CHANGELOG.md
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/sdk/bg.lproj/Localizable.strings
platform/macos/sdk/pt-BR.lproj/Localizable.strings

Added a Bulgarian localization to the Android, iOS, and macOS SDKs. Added a Hungarian localization to the Android SDK. Updated the Brazilian Portuguese and Hungarian localizations in the iOS and macOS SDKs.
/cc @tobrun @fabian-guerra

Synchronize localizations with Transifex

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java

throw IAE in animate() and easeCamera()  when duration <= 0

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties

Release android v5.1.5

---

circle.yml
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/widgets/AttributionTest.java
platform/android/scripts/generate-test-code.js

This PR tests if we are able to run all instrumentation tests in a timely fashion. We were recently able to speed up the tests with https://github.com/mapbox/mapbox-gl-native/commit/c9c2e96240b17ce4bd32729a66cdd3ff213aa313.

Run full test suite on CI

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Fix illegalArgument occurences of ease/animate

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

explicitly use a positive animation duration before animating user location.

Check for positive animation duration

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnaphotUtil.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshot.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
platform/android/src/snapshotter/map_snapshot.cpp
platform/android/src/snapshotter/map_snapshot.hpp
platform/android/src/snapshotter/map_snapshotter.cpp
platform/android/src/snapshotter/map_snapshotter.hpp

This PR cherry picks a couple of commits to the release branch.

Cherry pick to agua

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRenderThread.java

Fixes the EGL cleanup code so it doesn't crash on cleaning up bad display / context.

TextureView - cleanup destruction code

---

platform/darwin/src/MGLShapeSource.h

Clarifies how to update a shape source.

[ios, macos] Note how to update a shape source

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/IconManager.java

Check for null value when calling mapboxMap.clear

---

src/mbgl/layout/symbol_layout.cpp
src/mbgl/programs/collision_box_program.hpp
src/mbgl/renderer/buckets/symbol_bucket.cpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/renderer/layers/render_symbol_layer.cpp
src/mbgl/text/placement.cpp

They're not really about opacity.
@ansis

Rename CollisionBoxOpacityAttributes -> CollisionBoxDynamicAttributes.

---

src/mbgl/renderer/renderer_impl.cpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp
src/mbgl/tile/geometry_tile.cpp

Make "recent/stale" Placement state private.
/cc @ansis @jfirebaugh @kkaefer

Fix sanitizer issue caused by adding a duration to TimePoint::max() in MapMode::Still.

---

src/mbgl/layout/symbol_instance.hpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/renderer/buckets/symbol_bucket.cpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/renderer/paint_parameters.cpp
src/mbgl/renderer/paint_parameters.hpp
src/mbgl/renderer/render_layer.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/text/placement.cpp

Cleaned up some of my TODOs in `start-collision`. Going commit-by-commit might be the clearest way to review.
@ChrisLoer

misc viewport collision cleanup

---

platform/darwin/src/MGLMapSnapshotter.mm

[ios, macos] Add attribution to snapshots.

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Bump podspec to beta.4

---

platform/android/CHANGELOG.md

- Addresses #10379
@zugaldia @tobrun @lilykaiser

[android] Release 5.2.0-beta.4

---

platform/darwin/src/MGLMapSnapshotter.mm

[ios, macos] Cleanup duplicated snapshotter frame code.

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/EmptyLocationSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MockLocationEngine.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationDrawableActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java
platform/android/dependencies.gradle

Cherry pick of https://github.com/mapbox/mapbox-gl-native/pull/10380 to master. This makes  resolving conflicts for merging back to master in https://github.com/mapbox/mapbox-gl-native/pull/10421 a lot easier. Since expressions have landed, we will need to revisit that merge anyways. 

Revert adding mapbox-android-core dependency

---

platform/qt/src/sqlite3.cpp

We need to enforce that the QVariant passed to `QSqlQuery::bindValue` is of `QVariant::Type::String`, otherwise the Qt SQLite driver treats the QByteArray as blob - which causes the database incompatibilities between Qt and non-Qt versions.
Fixes #10428.

[Qt] Explicit QVariant type as string when binding text

---

platform/ios/docs/guides/Adding Points to a Map.md

- Removes link to a deprecated guide
- Corrects link to API documentation

[ios] Minor fixes for "Adding Points to a Map" guide

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Some minor additions to the iOS and macOS changelogs to capture what’s happened on the master branch during iOS SDK v3.7.0 / macOS SDK v0.6.0 development.

Update iOS, macOS changelogs

---

include/mbgl/style/expression/parsing_context.hpp
include/mbgl/style/expression/type.hpp
include/mbgl/util/string.hpp
src/mbgl/style/expression/array_assertion.cpp
src/mbgl/style/expression/at.cpp
src/mbgl/style/expression/case.cpp
src/mbgl/style/expression/coercion.cpp
src/mbgl/style/expression/compound_expression.cpp
src/mbgl/style/expression/interpolate.cpp
src/mbgl/style/expression/let.cpp
src/mbgl/style/expression/literal.cpp
src/mbgl/style/expression/match.cpp
src/mbgl/style/expression/parsing_context.cpp
src/mbgl/style/expression/step.cpp

Sadly we don't have bots for these two setups.

[core] Fix build on Android + GCC and Android + armeabi

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java
platform/android/dependencies.gradle

Follow up of https://github.com/mapbox/mapbox-gl-native/pull/10066 but targeted to release branch. 
Still requires to override min version of the lost dependency.

Downgrade min sdk to 14

---

platform/qt/src/qmapboxgl.cpp
platform/qt/src/qt_image.cpp

Refs: http://doc-snapshots.qt.io/qt5-5.10/qimage-obsolete.html / https://codereview.qt-project.org/#/c/199772/

[Qt] Fix deprecation warnings in Qt 5.10

---

src/mbgl/layout/symbol_projection.cpp
src/mbgl/renderer/buckets/symbol_bucket.cpp
src/mbgl/renderer/render_layer.hpp
src/mbgl/text/collision_index.cpp
src/mbgl/text/placement.hpp

Small changes made in response to @kkaefer's review comments.
/cc @ansis

Viewport collision small stuff

---

include/mbgl/tile/tile_id.hpp
src/mbgl/geometry/feature_index.hpp
src/mbgl/gl/context.hpp
src/mbgl/layout/symbol_instance.cpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/programs/collision_box_program.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp
src/mbgl/text/collision_feature.hpp
src/mbgl/text/collision_index.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/geometry_tile_worker.cpp

/cc @ansis @jfirebaugh @kkaefer

viewport-collision: small changes in response to jfire review

---

platform/ios/resources/es.lproj/Localizable.strings
platform/ios/resources/es.lproj/Localizable.stringsdict
platform/ios/resources/vi.lproj/Localizable.strings
platform/ios/resources/vi.lproj/Localizable.stringsdict

Updated Spanish and Vietnamese translations from Transifex, now that we’ve merged the release-agua branch back to master and Transifex has picked up the changes in #9950.
/cc @fabian-guerra @frederoni

Update Spanish, Vietnamese translations

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Update podspecs to v3.7.0-rc.1

---

platform/node/DEVELOPING.md

Fix node docs

---

cmake/test-files.cmake
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/cross_tile_symbol_index.hpp
test/text/cross_tile_symbol_index.test.cpp

adds a unit test for CrossTileSymbolLayerIndex

add unit test for CrossTileSymbolIndex

---

platform/android/CHANGELOG.md

- Addresses #10463 
👀 @osana @langsmith @zugaldia @tobrun

Release Android v5.2.0 beta.5

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties

- Addresses #10486 
👀 @tobrun @osana @langsmith

Release Android v5.2.0

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/BottomSheetActivity.java

Fragment crashes when being popped from the backstack

---

platform/qt/include/qmapbox.hpp
platform/qt/src/qmapboxgl.cpp

Updates documentation on `SharedGLContext` plus minor qdoc warnings.

[Qt] Update documentation

---

platform/qt/qt.cmake
platform/qt/src/qt_logging.cpp
src/mbgl/gl/context.hpp

Logging and rendering were broken.

Fix runtime issues on Windows

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java

Renamed branch from https://github.com/mapbox/mapbox-gl-native/pull/10269 so that CI passes.

[android] Set a larger limit for the HTTP dispatcher

---

platform/qt/mbgl/gl/gl_impl.hpp

[core] Fix Qt4 on macOS

---

platform/darwin/src/MGLComputedShapeSource.mm

This resolves a warning from the static analyzer and fixes #10571. @asheemmamoowala and I looked at this together and paired on a light refactoring.

[darwin] Adjusts initializer body to avoid premature ivar usage

---

platform/ios/src/MGLMapView.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10591

[ios] Fix setting minimumZoomLevel does not work.

---

platform/darwin/src/MGLAttributionInfo.h
platform/darwin/src/MGLAttributionInfo.mm
platform/darwin/src/MGLMapSnapshotter.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10490

[ios, macos] Refactor snapshot attribution.

---

platform/android/CHANGELOG.md

Release Android v5.2.1

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

[ios] Update changelog and bump podspec to 3.7.1

---

platform/android/README.md

Updated readme for Arch Linux users.

Updated README for Arch Linux users

---

platform/darwin/src/MGLRendererConfiguration.h
platform/darwin/src/MGLRendererConfiguration.mm
platform/ios/docs/guides/Info.plist Keys.md
platform/macos/docs/guides/Info.plist Keys.md
platform/macos/src/MGLMapView.mm

Also removes related dead code in macos MGLMapView.mm

[darwin, macos] Rename Info.plist key for consistency

---

platform/node/test/ignores.json
src/mbgl/text/collision_index.cpp

- Port of GL JS PR #5703.
- Fixes issue #10616

[core] Include bucket name in queryRenderedSymbols duplicate feature filter

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUtil.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java

Readd configurable http logging

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java

Update metadata documentation

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapTouchListenersTest.java

Map touch listeners API based on lists

---

platform/ios/src/MGLMapView.mm

Fixes the regression in #10485

[ios] Fix the content insets for the scale and compass view.

---

platform/ios/ios.xcodeproj/project.pbxproj

[ios] Fix C++ symbol visibility warnings in test suite

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java

Refs https://github.com/mapbox/react-native-mapbox-gl/pull/871#issuecomment-352140910

Activate filesource for creating an offline region

---

INSTALL.md
platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/src/main/res/values-es/strings.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values-vi/strings.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml
platform/android/README.md

Cherry picks of:
- https://github.com/mapbox/mapbox-gl-native/pull/10609
- https://github.com/mapbox/mapbox-gl-native/pull/10740

Cherry pick translations + SDK name changes

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/BitmapUtils.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTintActivity.java

Cherry pick of https://github.com/mapbox/mapbox-gl-native/pull/10746

Cherry pick #10746

---

platform/android/CHANGELOG.md

Release Android v5.3.0

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Podspec bump and changelog update

[ios] Update changelog. Podspec bump to v3.7.2

---

platform/macos/src/MGLMapView.h

macOS docs for https://github.com/mapbox/mapbox-gl-native/pull/9804

[macos] Update visible coordinates documentation 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java

use US local when converting between int color and RGBA String

---

platform/ios/src/MGLMapboxEvents.m

A proposal for discussion: This attempts to work around reports of repeated calls to `[CLLocationManager authorizationStatus]` blocking the main thread by dispatching it to the background, serial queue that is already available in `MGLMapboxEvents`.

Dispatch location auth status check to background

---

platform/macos/scripts/deploy-packages.sh
platform/macos/scripts/package.sh

Various fixes to `make xpackage` and `make xdeploy` that I caught (or rather that caught me) while releasing macOS SDK v0.6.0, including a partial rollback of some of the changes that I made in #10191 after I performed a dry run of the initial PR. deploy-packages.sh now uses `getopt`, which is cool, if finicky.

Fix macosapp deployment

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java

RTL support

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java

added parameter validation LatLngBounds.from()

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

- Fixes sending more than once double tap event on a single double tap gesture
👀 @tobrun @LukasPaczos @osana @zugaldia @electrostat

[android] Fix sending more than once double tap event

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

- Cherry pick of #10854 into `master`
👀 @tobrun @LukasPaczos @osana

[android] Cherry pick fix sending more than once double tap event 

---

src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/cross_tile_symbol_index.hpp
src/mbgl/text/placement.cpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/tile.hpp
test/text/cross_tile_symbol_index.test.cpp

This is a companion to https://github.com/mapbox/mapbox-gl-js/pull/5890 that ports the new changes made in that pr back to -native. 
@ChrisLoer

port minor collision changes from -js

---

platform/darwin/src/MGLShapeSource.h

Fixed a jazzy warning.
Fixes #10821.
/cc @friedbunny @asheemmamoowala

Remove redundant typedef

---

platform/node/test/ignores.json
src/mbgl/shaders/collision_circle.cpp

Fixes issue #10876.
/cc @jfirebaugh @nickidlugash

[core] Update debug collision circle shader (#10876)

---

platform/node/test/ignores.json
src/mbgl/style/expression/parsing_context.cpp

Fixes #10533, porting https://github.com/mapbox/mapbox-gl-js/pull/5738.

[core] Enable implicit type assertions for array types

---

platform/android/CHANGELOG.md

This PR updates the changelog contents for the upcoming 5.3.1 release.

Changelog for 5.3.1 release

---

platform/android/MapboxGLAndroidSDK/gradle.properties

Release Android v5.3.1

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/darwin/scripts/generate-style-code.js
platform/darwin/scripts/style-spec-overrides-v8.json
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillExtrusionStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLRasterStyleLayer.h
platform/darwin/src/MGLRasterStyleLayer.mm
platform/darwin/src/MGLSymbolStyleLayer.h
platform/darwin/test/MGLRasterStyleLayerTests.mm
scripts/generate-style-code.js

 Commit accumulated `make style-code` updates

---

platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/ios/test/MGLMapViewLayoutTests.m
platform/ios/test/MGLMapViewTests.m

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10834

[ios] Fix the layout constraints on iOS 11 for iPhone X 

---

include/mbgl/style/expression/interpolate.hpp
platform/node/test/ignores.json
src/mbgl/style/expression/step.cpp
src/mbgl/style/expression/value.cpp

Fixes #10618, porting https://github.com/mapbox/mapbox-gl-js/pull/5757.

Handle NaN input to interpolate and step

---

platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Bump podspec for Mapbox Map SDK for iOS v3.7.3

[ios] Bump podspec to v3.7.3

---

CMakeLists.txt

Update vector-tile dependency to 1.0.1

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Validate surface creation before destroying map

---

platform/glfw/glfw_view.cpp
platform/glfw/glfw_view.hpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp
src/mbgl/tile/geometry_tile_worker.cpp
src/mbgl/tile/geometry_tile_worker.hpp

This fixes various bugs that were causing symbols to flicker and fade when updated. fixes #https://github.com/mapbox/mapbox-gl-native/issues/10559
cc @ChrisLoer @asheemmamoowala

fix symbol flickering after data updates

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLMapboxEvents.m
platform/ios/test/MGLMapViewLayoutTests.m
platform/macos/CHANGELOG.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec
platform/macos/scripts/deploy-packages.sh
platform/macos/scripts/package.sh

Merge `release-agua` back to `master`

Merge release-agua back to master

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/build.gradle
platform/android/gradle/dependencies.gradle

Cleanup dependencies.gradle
