- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
Closes #6597, solves the use-case of not updating the tilt value of a MarkerView on startup. This should solve other issues related to camera changes and tilt but this hasn't been fully tested yet.
> [android] - apply tilt to markerview with initial camera position

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/AnimatorUtils.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerViewTest.java
Customer reached out about following use-case:
> 
When we update our MarkerView rotation from 359 to 0, the rotation is executed counterclockwise with a value of 359 degrees instead of rotating with value 1.
This PR constrains input to 0 - 359 degrees and manages calculating the rotation value ourselves. This resulted in introducing an new `AnimatorUtils#animateRotateBy`. To validate the changes I added some test cases to MarkerViewTest.
> Rotate markerview

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/camera/CameraPositionTest.java
I noticed that the android binding was not providing the correct value type to core when executing one of the CameraOptions methods (jumpTo, moveTo, flyTo). The binding was also not restoring the value correctly when requesting the camera value from core. 
> [android] - correct camera position

- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/MultiMapActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_multi_map.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
- platform/android/scripts/generate-test-code.js
Adds a new activity to the TestApp that shows multiple maps in the same activity. It uses `SupportMapFragment`.
Current iteration:
/cc: @tobrun @cammace
> Sample multimap activity

- src/mbgl/annotation/annotation_manager.cpp
- src/mbgl/text/collision_tile.cpp
- test/api/annotations.test.cpp
We currently set `icon-allow-overlap` to `true` [when creating the annotation symbol layer](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/annotation/annotation_manager.cpp#L187) but we also need `icon-ignore-placement` set to `true`.
Ignoring icon placements causes symbol annotations to skip calculating the placement scale - which is currently broken (see #6628) and thus returning the correct values for rendered features.
> Annotation symbols should ignore icon placement

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
This annotation was incorrect, causing a crash when using the adapter with Kotlin due to a null convertView argument being passed to getView().
> Use correct nullity annotation for convertView

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapboxAccountManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/net/ConnectivityReceiver.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java
Currently, the PR only covers the usecase where an app handles its connectivity state internally and bypasses `ConnectivityManager`.
Fixes #6617.
/cc: @danswick @mapbox/android
> Introduce a setConnected method to manually set a connected flag

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Regression from https://github.com/mapbox/mapbox-gl-native/pull/6641. 
I based those changes on the specification of `CameraOptions`:
```
struct CameraOptions {
...
/** Bearing, measured in radians counterclockwise from true north. Wrapped
to [−π rad, π rad). */
optional<double> angle;
/** Pitch toward the horizon measured in radians, with 0 rad resulting in a
two-dimensional map. */
optional<double> pitch;
};
```
This is the core model object that is used by moveTo, easeTo and flyTo. This PR reverts using degrees instead of the noted radiants above. Not sure why this is now working correctly by passing in degrees. 
> [android] - revert making bearing and tilt to radiants

- cmake/test-files.cmake
- src/mbgl/style/source_impl.cpp
- src/mbgl/tile/tile.hpp
- src/mbgl/util/tile_coordinate.hpp
- test/tile/tile_coordinate.test.cpp
> Add unit tests for TileCoordinate and TilePoint

- platform/darwin/src/MGLStyle.mm
- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLMapViewDelegate.h
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
- platform/macos/src/MGLMapViewDelegate.h
Fixes #6412 by implementing `-mapView:didFinishLoadingStyle:` delegate methods, made possible at the core level by #6371.
Also adds `MGLStyle.description` and a private `MGLStyle.URL` property, which are useful when debugging:
```
<MGLStyle: 0x60800001e0a0; name = "Mapbox Dark", URL = "mapbox://styles/mapbox/dark-v9”>
```
/cc @1ec5
> Add -mapView:didFinishLoadingStyle: delegate methods

- platform/macos/bitrise.yml
- platform/macos/macos.xcodeproj/xcshareddata/xcschemes/CI.xcscheme
Fixes #6615.
Adds `mbgl-test` and `mbgl-benchmark` as part of CI scheme.
> [macos] Merge mbgl-{test,benchmark} in CI scheme

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
Fixes issue of Android not correctly converting the android camera position to the core CameraOptions equivalent as mentioned in https://github.com/mapbox/mapbox-gl-native/pull/6656.
> [android] - correct android to core conversion of camera options.

- src/mbgl/map/map.cpp
- test/api/annotations.test.cpp
Extracted out of https://github.com/mapbox/mapbox-gl-native/pull/3563.
/cc @ivovandongen
> [core] Skip duplicated IDs when querying point annotations

- platform/android/src/jni.cpp
Small cleanups derived from #6655:
- Use `mbgl::AnnotationIDs` alias for `std::vector<mbgl::AnnotationID>`
- Improve `std_vector_uint_to_jobject` perf by moving elements
> [android] Using mbgl::AnnotationIDs in JNI code

- src/mbgl/renderer/painter_symbol.cpp
Fixes #5055.
Because render tests are done in still mode - [which causes the stencil function to be properly updated](https://github.com/mapbox/mapbox-gl-native/issues/5055#issuecomment-252938666) - there is no need for a render test.
Example output:
> [core] Disable stencil test when rendering collision boxes

- platform/android/MapboxGLAndroidSDKTestApp/gradle.properties
This allows the test app to be compiled faster by allowing gradle to use up to 2GB of memory. We already had this configuration enabled for the SDK module, but this is not picked up when building the testapp.
Review @zugaldia / @cammace
> [android] - allow gradle to allocate more memory

- platform/darwin/src/MGLStyle.h
- platform/darwin/src/MGLStyle.mm
- platform/darwin/src/MGLStyle_Private.h
- platform/darwin/src/MGLTypes.h
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLMapView.mm
- platform/ios/src/UIImage+MGLAdditions.h
- platform/ios/src/UIImage+MGLAdditions.mm
- platform/macos/macos.xcodeproj/project.pbxproj
- platform/macos/src/MGLMapView.mm
- platform/macos/src/NSImage+MGLAdditions.h
- platform/macos/src/NSImage+MGLAdditions.mm
With the changes to the core in https://github.com/mapbox/mapbox-gl-native/pull/6375 we can now add custom images to the sprite atlas. This PR resolves https://github.com/mapbox/mapbox-gl-native/issues/6436 to add the possibility to add custom images from bundles in iOS and macOS.
As proposed from @1ec5 in #6436, I've first named the method `setImage:forName:` but to stay consistent with all other methods of `MGLStyle.h` I've decided to name the method `addImage:forName:`.
**Usage:**
``` swift
let imageURL = Bundle.main.url(forResource: "animal-dog", withExtension: "png")
mapView.style().addImage(imageURL!.path, forName: "dog")
let styleLayer  = MGLSymbolStyleLayer(identifier: "restaurants", source: geoJSONSource)
styleLayer.predicate = NSPredicate(format: "amenity == 'restaurant'") …
```
> [ios, macos] possibility to set custom images to style

- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/text/collision_tile.cpp
- src/mbgl/text/collision_tile.hpp
Reuse reverse rotation matrix from `CollisionTile` when populating the collision boxes plus minor cleanups.
Spin-off from #3563.
> [core] Cleanup SymbolLayout

- platform/android/bitrise.yml
This downscales our CI instrumentation tests to only run one sanity test.
More information in https://github.com/mapbox/mapbox-gl-native/issues/6546.
> [android] - downscale amount of instrumentation tests on CI

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/IconFactory.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Closes #6352, this PR stops the log messages from SymbolAnnotation to pop-up:
```
can't find sprite ..... for ...
```
This PR matches behaviour of iOS in https://github.com/mapbox/mapbox-gl-native/pull/5461 & https://github.com/mapbox/mapbox-gl-native/pull/5461. 
Review @zugaldia / @cammace
> [android] - add transparent image for MarkerViews ghosting SymbolAnnotations

- platform/ios/CHANGELOG.md
- platform/ios/app/MBXViewController.m
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLMapViewDelegate.h
- platform/macos/CHANGELOG.md
- platform/macos/app/MapDocument.m
- platform/macos/src/MGLMapView.mm
- platform/macos/src/MGLMapViewDelegate.h
This replaces `-[MGLMapViewDelegate mapView:alphaForShapeAnnotation:]` with the alpha component already provided in `-[MGLMapViewDelegate mapView:strokeColorForShapeAnnotation:]` or `-[MGLMapViewDelegate mapView:fillColorForPolygonAnnotation:]`.
This should better meet developer expectations and simplify our annotation delegate API situation a tiny bit.
/cc @1ec5 @incanus @boundsj
> Deprecate -[MGLMapViewDelegate mapView:alphaForShapeAnnotation:]

- platform/qt/bitrise-qt5.yml
Always get the latest installed Qt5 version from Homebrew when creating the `mkspec` and `plugin` symlinks.
Fixes #6712.
> [qt] Fix Qt5 bitrise bot

- package.json
- platform/android/scripts/generate-style-code.js
Fixes #6705
Difference in the way uniq with iteratee is implemented between lodash [3.10.1](https://lodash.com/docs/3.10.1#uniq) and [4.17.4](https://lodash.com/docs/4.16.4#uniqBy) broke the code generation script.
review @mikemorris
> fix android style code

- platform/default/mbgl/storage/offline_database.cpp
- platform/default/mbgl/storage/offline_database.hpp
- platform/default/mbgl/storage/offline_download.cpp
- test/storage/offline_database.test.cpp
When a offline download continues with lots of existing tiles, it is too expensive to get the tile and even decompress it to only check if it exist. This add hasRegionResource, hasResource and hasTile to the existing get-methods. This solve one part of #6651 and is a subset of the earlier #6691.
> added hasRegionResource when the content are not needed by the caller

- platform/darwin/src/MGLMultiPoint.h
- platform/darwin/src/MGLPolygon.h
- platform/darwin/src/MGLPolyline.h
In https://github.com/mapbox/mapbox-gl-native/pull/6524 we added a class factory method to `MGLMultiPoint`. Since `MGLMultiPoint` is a superclass of `MGLPolyline` and `MGLPolygon`, when [modern Swift 3 translation rules](https://github.com/apple/swift-evolution/blob/master/proposals/0005-objective-c-name-translation.md) are applied, the result is ambiguous class factory method names for MultiPoint -> PolyLine and Polygon.
This change decorates the class factory methods with `NS_SWIFT_NAME({shape_name}(coordinates:count:))` so that, at the call site in a modern Swift app, we can write:
```Swift
MGLPolyline.polyline(coordinates: &coordinates, count: UInt(coordinates.count))
```
cc @friedbunny @1ec5
> [ios, macos] Use swift_name for MGLMultiPoint and subclasses

- platform/ios/scripts/deploy-packages.sh
Fixes `build/ios/deploy` directory creation. This directory was being created but then immediately blown away by `make clean`.
This PR also includes:
Try to avoid `github-release` sometimes failing with:
```
* Uploading mapbox-ios-sdk-3.4.0-beta.1-symbols.zip to GitHub
./platform/ios/scripts/deploy-packages.sh: line 119: unexpected EOF while looking for matching `”’
```
```
* Finished deploying 3.4.0-beta.1 in 5 minutes and 20 seconds
```
/cc @boundsj
> [ios] Fix deploy script temp directory creation

- platform/ios/src/MGLMapboxEvents.m
Upload any events collected when the app was in use for apps that only have "when in use" location permissions. Also, for all apps, avoid posting event data if there is only a single event.
> [ios] Optimize event uploading

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/net/package-info.java
Adds package-info.java for the net package. 
Needed for javadoc table overview on `/index.html`.
> [android] - add package-info.java for net package

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
In our Map change events we had some:
```
* <p>
* This {@link MapChange} is currently not implemented.
* </p>
```
While they actually are implemented. 
> [android] - update map change events javadoc

- platform/darwin/src/MGLStyle.mm
- platform/darwin/src/MGLStyleLayer.mm
Implement the layer property on MGLStyleLayer itself, where it’s declared, so that the check for an abstract style layer doesn’t itself raise an exception. The concrete style layer classes still declare their own layers as covariant properties, although those properties aren’t actually used anywhere.
Fixes #6736.
/cc @boundsj @bsudekum
> Raise correct style layer misuse exception

- include/mbgl/util/projection.hpp
- src/mbgl/annotation/symbol_annotation_impl.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/util/tile_coordinate.hpp
- src/mbgl/util/tile_cover.cpp
- test/api/annotations.test.cpp
- test/tile/tile_coordinate.test.cpp
If I add an annotation at the coordinates 0°, 0°, an annotation also appears at the coordinates 0°, 180°, but only at z1.
> Annotating Null Island also annotates its antipode

- platform/darwin/src/MGLFeature.h
- platform/darwin/src/MGLFeature_Private.h
- platform/ios/CHANGELOG.md
- platform/ios/app/MBXViewController.m
- platform/ios/test/MGLGeoJSONSourceTests.mm
- platform/macos/CHANGELOG.md
Instances of MGLFeature subclasses can now have their attributes and identifier properties mutated.
Follow up to https://github.com/mapbox/mapbox-gl-native/issues/6302
cc @1ec5
> [ios, macos] Make feature attributes and identifier writable

- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
- platform/android/bitrise.yml
WIP, closes #6366 
- moves AWS env to `testapp gradle.properties` vs`sdk gradle.properties`
- removed unneeded comments 
- added console logs to get direct feedback during builds.
> Update AWS device farm config

- platform/android/CONTRIBUTING_MACOS.md
- platform/android/MapboxGLAndroidSDK/gradle.properties
- platform/android/MapboxGLAndroidSDKTestApp/gradle.properties
- platform/android/MapboxGLAndroidSDKWearTestApp/build.gradle
CI doesn't apply heap size configuration from gradle.properties, setting in build.gradle instead.
eg. still seeing:
> To run dex in process, the Gradle daemon needs a larger heap.
It currently has approximately 1662 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to more than 2048 MB.
To do this set org.gradle.jvmargs=-Xmx2048M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html
Even though we applied the suggestion here in #6678.
> Update docs on gradle configuration

- include/mbgl/platform/default/glfw_view.hpp
- platform/default/glfw_view.cpp
Adds (registration of) a mapchange callback handler.
cc @brunoabinader
> [glfw] add map change callback methods to glfw_view

- platform/android/src/jni.cpp
Removes method logging from JNI calls but keeps the logging for lifecycle related methods.
> [android] - remove jni method logging, only keep lifecycle related logs

- platform/node/bitrise.yml
Fixes #4854
Refs #6523, #6525 
[Bitrise recently added the ability to trigger workflows from git tag pushes](http://blog.bitrise.io/2016/10/15/trigger-builds-with-git-tags.html), which finally unblocked this!
I can't seem to get this configured correctly following the instructions in https://bitrise-io.github.io/devcenter/webhooks/trigger-map/ - tag pushes to an updated webhook URL are being rejected by Bitrise.
```
{"success_responses":[],"failed_responses":[{"status":"error","message":"trigger pattern did not match any defined mapping: no matching workflow found with trigger params: push-branch: , pr-source-branch: , pr-target-branch: , tag: node-v3.4.0-pre.11","service":"bitrise","slug":"55e3a9bf71202106","build_slug":"","build_number":0,"build_url":"","triggered_workflow":""}]}
```
Is …
> Publish Node.js binaries on tag pushes in Bitrise

- CMakeLists.txt
- platform/qt/app/mapwindow.cpp
On this PR:
- Added a workaround fix for an issue [with older Qt versions](https://bugreports.qt.io/browse/QTBUG-36802) preventing the QMapboxGL demo application from running.
- Enforce C++14 as default standard on CMake to satisfy latest Qt builds.
Fixes #6794.
> Qt macOS fixes

- src/mbgl/style/sources/geojson_source_impl.cpp
Fixes https://github.com/mapbox/mapbox-gl-native/pull/6770#discussion_r84544664
@jfirebaugh added a check on an existing request in `setURL` as well so that any pending request is canceled when changing the url, not only when it was previously done loading.
> [core] geojson source - reset req on setURL

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
Refers #5388.
Notes:
- Moves touch interaction of MarkerViews to core
- Replaced average icon width/height for touch surface padding to a fixed size, since this was giving incorrect results. Will need to revisit later to fix this.
- Noticed some strange behaviour that click events were not triggered and had to wait a couple of seconds before being able to click the map.
> [android] #5388 - moves touch handling of MarkerViews to core

- src/mbgl/style/source_impl.hpp
- src/mbgl/style/sources/geojson_source_impl.cpp
- src/mbgl/style/sources/geojson_source_impl.hpp
Fixes #6801
Clears the tile cache on `GeoJSONSource#setGeoJSON` to avoid stale shapes and cancels any pending requests to avoid pending requests overwriting the content that is set(https://github.com/mapbox/mapbox-gl-native/pull/6798#issuecomment-255583033)
> Geojsonsource fixes

- platform/android/CONTRIBUTING_MACOS.md
Closes #6722
I agree that the most common/easy way to install Android Studio would be simply going to their website. I made this clear in the instructions by removing the `brew` command and instead suggesting to download from site.
cc: @zugaldia for review
> removed brew cask install android studio instruction

- platform/darwin/scripts/generate-style-code.js
- platform/darwin/src/MGLSymbolStyleLayer.h
> Fix syntax error in documentation comment

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerViewTest.java
closes #6816, targeting `release-android-v4.2.0`. This PR cancels ongoing rotation animations and uses the current animated value instead of using the previous set rotation. If you would call `MarkerView#setRotate` while an animation was ongoing you would end up with a wrong rotation value. 
> Use animated rotation value for MarkerView.setRotate

- platform/darwin/src/MGLStyleValue.h
- platform/darwin/test/MGLStyleValueTests.swift
- platform/darwin/test/test-Bridging-Header.h
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/test/test-Bridging-Header.h
- platform/macos/macos.xcodeproj/project.pbxproj
MGLStyleConstantValue and MGLStyleFunction now inherit from MGLStyleValue with a generic argument matching the child class’s own generic argument.
Added tests of MGLStyleValue written in Swift, along with bridging headers just in case they become needed in the future.
Fixes #6823.
/cc @incanus @boundsj
> Correct MGLStyleValue inheritance

- platform/darwin/src/MGLGeoJSONSource.h
- platform/darwin/src/MGLGeoJSONSource.mm
- platform/darwin/src/MGLGeoJSONSource_Private.h
- platform/darwin/src/MGLRasterSource.mm
- platform/darwin/src/MGLSource.mm
- platform/darwin/src/MGLSource_Private.h
- platform/darwin/src/MGLStyle.mm
- platform/darwin/src/MGLVectorSource.mm
- platform/ios/app/Info.plist
- platform/ios/app/MBXViewController.m
- platform/ios/test/MGLGeoJSONSourceTests.mm
WIP for source portion of: https://github.com/mapbox/mapbox-gl-native/issues/6254
Fixes #6159
> Make source ownership consistent and make MGLGeoJSONSource's content properties mutable

- platform/ios/app/MBXViewController.m
- platform/ios/src/MGLMapView.h
- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.h
- platform/macos/src/MGLMapView.mm
This adds an API for getting all annotations that are currently visible on the map. We can also add an additional API to query by a specific rect. That API can be used internally to power this one.
This also adds a new option to iosapp to test the feature. 
Fixes #5467
> Introduce visible annotations API

- src/mbgl/style/style.cpp
- test/map/map.test.cpp
As a follow-up to #6373, this change stops our renderer from requesting tiles from sources that don't have a layer that actually requires it. Currently, if a source has been loaded before, but no layer is enabled due to the current zoom level, we are still happily loading all of the tiles even thought they are never used.
> Don't load tiles if no layer requires them

- src/mbgl/style/source_impl.cpp
- src/mbgl/style/source_impl.hpp
- src/mbgl/style/style.cpp
As a followup to #6345: When no layer of a source is visible anymore, we are currently disabling the source, but we don't evict tiles that are still stored in that source.
> Remove tiles from source when source is disabled

- platform/qt/src/qmapboxgl.cpp
Qt 5.x for Linux platform implements a different behavior for `QGLWidget` when compared to the macOS - the viewport size is not initially set. Thus, we need to account for this by using the assignment operator that eventually calls for the viewport OpenGL setter function.
Fixes #6827.
/cc @kkaefer @tmpsantos
> [Qt] Fix viewport size for Linux on Qt5

- include/mbgl/util/size.hpp
- src/mbgl/text/glyph.hpp
- src/mbgl/text/shaping.hpp
Otherwise, it can participate in unexpected conversions. Case in point: GlyphSet::insert was comparing the result of GlyphMetrics::operator bool() where it wanted to use operator==.
> [core] operator bool() must always be explicit

- platform/ios/app/MBXViewController.m
Adds the option to toggle between Chinese and English country labels in ios-app.
/cc @boundsj @pveugen @1ec5
> [ios] Add country label language toggle demo

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
closes #6838, review @ivovandongen
> [android] - prevent null pointer when receiving connectivity events

- cmake/core-files.cmake
- include/mbgl/math/log2.hpp
- include/mbgl/util/constants.hpp
- src/mbgl/algorithm/generate_clip_ids_impl.hpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/map/map.cpp
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/math/log2.cpp
- src/mbgl/renderer/circle_bucket.cpp
- src/mbgl/renderer/circle_bucket.hpp
- src/mbgl/renderer/fill_bucket.cpp
- src/mbgl/renderer/fill_bucket.hpp
- src/mbgl/renderer/line_bucket.cpp
- src/mbgl/renderer/line_bucket.hpp
- src/mbgl/renderer/painter_symbol.cpp
- src/mbgl/renderer/symbol_bucket.hpp
- src/mbgl/sprite/sprite_atlas.hpp
- src/mbgl/text/collision_tile.cpp
- src/mbgl/util/math.hpp
- test/api/annotations.test.cpp
- test/map/transform.test.cpp
Reuse `TransformState::{zoomScale,scaleZoom,getZoomFraction}` and `util::log2` whenever possible.
> [core] Transform{,State} cleanups

- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/default/glfw_view.cpp
- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
- platform/qt/src/qmapboxgl.cpp
- src/mbgl/gl/value.hpp
- src/mbgl/renderer/painter_debug.cpp
Reported in https://github.com/mapbox/mapbox-gl-native/issues/6799#issuecomment-257163112, when visualizing the depth/stencil buffer in the debug app, it only covers the lower left quarter of the screen on monitors that have a pixel ratio > 1.
> macOS: Depth/Stencil buffer visualization doesn't cover full screen

- src/mbgl/map/map.cpp
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/renderer/painter_symbol.cpp
- test/api/annotations.test.cpp
Partially reverts #6790.
As per https://github.com/mapbox/mapbox-gl-native/pull/6790#issuecomment-257331524.
> [core] Use GL_LINEAR on sprite texture if panning

- include/mbgl/util/image.hpp
- src/mbgl/annotation/annotation_manager.cpp
- src/mbgl/geometry/line_atlas.cpp
- src/mbgl/geometry/line_atlas.hpp
- src/mbgl/gl/context.cpp
- src/mbgl/gl/context.hpp
- src/mbgl/gl/texture.hpp
- src/mbgl/gl/types.hpp
- src/mbgl/renderer/frame_history.cpp
- src/mbgl/renderer/frame_history.hpp
- src/mbgl/renderer/painter_line.cpp
- src/mbgl/renderer/painter_symbol.cpp
- src/mbgl/shader/symbol_uniforms.cpp
- src/mbgl/shader/symbol_uniforms.hpp
- src/mbgl/sprite/sprite_atlas.cpp
- src/mbgl/sprite/sprite_atlas.hpp
- src/mbgl/style/style.cpp
- src/mbgl/text/glyph_atlas.cpp
- src/mbgl/text/glyph_atlas.hpp
- test/sprite/sprite_atlas.test.cpp
- test/text/glyph_atlas.test.cpp
Currently, the `*Atlas` objects, as well as the `FrameHistory` object are directly using OpenGL commands to manage their texture. We should change this to use the default-provided texture management logic in `gl::Context`.
A small roadblock is the fact that we currently only support RGBA textures, but the `GlyphAtlas`, `LineAtlas`, and `FrameHistory` use mono-channel (`GL_ALPHA`) textures.
Note that all of these are currently using `glTexSubImage2D` for subsequent uploads. However, internally most drivers will create a copy of the existing data and patch up that data, so there is very little advantage of subimage patching over full texture uploads.
> Refactor Atlases+FrameHistory to use wrapped texture objects

- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/CI.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/bench.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/dynamic+static.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/dynamic.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/static.xcscheme
- platform/macos/macos.xcodeproj/xcshareddata/xcschemes/CI.xcscheme
- platform/macos/macos.xcodeproj/xcshareddata/xcschemes/dynamic.xcscheme
- platform/macos/macos.xcodeproj/xcshareddata/xcschemes/macosapp.xcscheme
- platform/macos/scripts/executable.xcscheme
- platform/macos/scripts/library.xcscheme
- platform/macos/scripts/node.xcscheme
Xcode 8.1 recommends several changes to build settings in mbgl:
Some of these settings throw errors in existing code:
```
/path/to/mapbox-gl-native/src/mbgl/renderer/painter_symbol.cpp:125:87: error: code will never be executed [-Werror,-Wunreachable-code]
const bool drawAcrossEdges = (frame.mapMode == MapMode::Continuous) && (true || !(layout.textAllowOverlap || layout.iconAllowOverlap ||
^~~~~~
/path/to/mapbox-gl-native/src/mbgl/renderer/painter_symbol.cpp:125:77: note: silence by adding parentheses to mark code as explicitly dead
const bool drawAcrossEdges = (frame.mapMode == MapMode::Continuous) && (true || !(layout.textAllowOverlap || layout.iconAllowOverlap ||
^
/* DISABLES CODE */ ( )
1 error generated.
```
```
/path/to/mapbox-gl-native/test/sprite/sprite_atlas.test.cpp:329:9: …
```
> Xcode 8.1 recommended build settings for mbgl

- platform/ios/CHANGELOG.md
- platform/ios/app/MBXViewController.m
- platform/ios/app/Main.storyboard
- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
Now that https://github.com/mapbox/mapbox-gl-native/pull/5165 has landed, we can address the issues reported in https://github.com/mapbox/mapbox-gl-native/issues/5787 and again in https://github.com/mapbox/mapbox-gl-native/issues/5489#issuecomment-239492522. This PR will:
Fixes #5787 
cc @incanus @1ec5
> Optimize annotation view updates

- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Added an entry for #6833. Moved a bunch of notes up in the list to reflect their importance in terms of developer or user impact.
/cc @friedbunny @boundsj
> Update changelogs for v3.4.0-beta.2

- cmake/test-files.cmake
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/renderer/circle_bucket.cpp
- src/mbgl/renderer/circle_bucket.hpp
- src/mbgl/renderer/fill_bucket.cpp
- src/mbgl/renderer/fill_bucket.hpp
- src/mbgl/renderer/line_bucket.cpp
- src/mbgl/renderer/line_bucket.hpp
- src/mbgl/renderer/symbol_bucket.cpp
- src/mbgl/renderer/symbol_bucket.hpp
- test/gl/bucket.test.cpp
As per @jfirebaugh review in https://github.com/mapbox/mapbox-gl-native/commit/384f1a1960c9a21039642afe9bd1df58a93fddfc#commitcomment-19656901, commit 384f1a1960c9a21039642afe9bd1df58a93fddfc introduced a regression in `{Circle,Fill,Line,Symbol}Bucket::hasData()` in a sense that an empty bucket would never return `false`.
> [core] Fix regression in Bucket::hasData

- platform/ios/app/MBXViewController.m
Although functionality was not affected, a previous merge garbled the language test with a temporary test done for annotation view performance improvement.
cc @1ec5
> [ios] Fix bad merge in iosapp

- platform/android/MapboxGLAndroidSDK/build.gradle
We were still using `3.3.0` (latest is `3.4.1`). [Changelog](https://github.com/square/okhttp/blob/master/CHANGELOG.md). 
cc: @tobrun for review
> Upgraded okhttp dependency to latest version

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java
This PR implements the onCancel from OnCancelableCallback, if a user executes an long ease animation and interrupts it with a gesture the onCancel will now be invoked.
> Cancelable callback invocation

- platform/ios/src/MGLMapView.mm
This fixes an issue where, if a multipoint annotation was added, native annotation view update logic would crash. Adding the annotation tag for multipoints, too, avoids the out of range exception.
cc @1ec5 @incanus
> [ios] Store annotation tags for MGLMultiPoint annotations in the map

- .travis.yml
- scripts/clang-tools.sh
The difference between `tidy` and `check` targets are that `check` only runs `clang-tidy` over the files that were modified by patches diverging from `master` branch. This is much faster than running `clang-tidy` over all files, on every Travis run.
> [build] Replace 'tidy' with 'check'

- package.json
- platform/node/CHANGELOG.md
- src/mbgl/sprite/sprite_parser.cpp
- test/sprite/sprite_parser.test.cpp
This breaks the `Can't create sprite with invalid metrics` catchall into individual verbose error cases. I'm pretty sure this should be tweaked slightly to avoid allocating the `std::stringstream` in non-error cases.
> More verbose errors on invalid sprite metrics

- platform/android/src/native_map_view.cpp
- platform/default/offscreen_view.cpp
- platform/macos/src/MGLMapView.mm
- platform/macos/src/MGLOpenGLLayer.mm
- platform/qt/src/qmapboxgl.cpp
- src/mbgl/geometry/line_atlas.cpp
- src/mbgl/gl/context.cpp
- src/mbgl/gl/context.hpp
- src/mbgl/gl/extension.cpp
- src/mbgl/gl/types.hpp
- src/mbgl/gl/value.cpp
- src/mbgl/gl/value.hpp
- src/mbgl/renderer/debug_bucket.cpp
- src/mbgl/renderer/fill_bucket.cpp
- src/mbgl/renderer/frame_history.cpp
- src/mbgl/renderer/painter.cpp
- src/mbgl/renderer/painter_debug.cpp
- src/mbgl/shader/symbol_vertex.cpp
- src/mbgl/util/offscreen_texture.cpp
- test/gl/object.test.cpp
We should only use `gl.hpp` in the OpenGL bindings, and not in any other code.
> Remove remaining uses of gl.hpp

- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
Fixes https://github.com/mapbox/mapbox-gl-native/issues/6901
When annotations are removed concurrently with being updated because of a map redraw, it is possible that mbgl will still consider an annotation to exist depending on what part of the map lifecycle the call update annotations happens. However, the annotation context by
tag map in MGLMapView (on the main thread) will always be up to date.
This adds a guard that uses that map to avoid considering annotations that have actually been removed as visible.
Another issue was that adding the same annotation object twice has always been allowed and has worked, visually. However, a recent refactor to make the reuse queue work correctly is not tolerant of the a single view representing two annotation instances that are the same.
The effect …
> [ios] Work around annotation race condition

- platform/darwin/src/MGLTypes.h
Define `NSErrorDomain` before its first use. Define `NSNotificationName` as a typedef instead of a `#define`. Guard these shims on the existence of `NS_STRING_ENUM` rather than another macro that’s new to Xcode 8.
Fixes #6906.
/cc @boundsj
> Fix SDK compilation in Xcode 7.3

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
- platform/android/src/jni.cpp
closes https://github.com/mapbox/mapbox-gl-native/issues/6897.
> [android]  - using bearing clockwise versus counterclockwise

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/IconManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/InfoWindowManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
Closes #6067, 
This refactor introduces the concept of AnnotationManager. This class is responsible for everything related to annotations. Mains goals for this refactor are:
Note: the requirement of having no reference to Mapview/MapboxMap directly has resulted in passing Mapbox in some methods. This is going to be resolved when we pick up https://github.com/mapbox/mapbox-gl-native/issues/6912. 
* =  I had to change a couple of things due to mocking out classes, logic remained the same.
> 6067 annotation manager

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Checks that the attribution tint color isn't set to fully transparent.
cc: @tobrun
> Added attribution tint color check

- platform/ios/ios.xcodeproj/project.pbxproj
Fixes #6947 
Did this start with Xcode 8.1 or later?
Root.plist is usually picked up automatically from the settings bundle. Not sure why it doesn't all of a sudden.
@kkaefer 👀
> [ios] specify plist-file for settings bundle

- platform/darwin/scripts/generate-style-code.js
- platform/darwin/scripts/style-spec-overrides-v8.json
- platform/darwin/src/MGLBackgroundStyleLayer.h
- platform/darwin/src/MGLCircleStyleLayer.h
- platform/darwin/src/MGLFillStyleLayer.h
- platform/darwin/src/MGLLineStyleLayer.h
- platform/darwin/src/MGLSymbolStyleLayer.h
Fixes #5954 - Override some gl-style-spec documentation to make it more idiomatic.
👀  @1ec5 @friedbunny
> Override style specification documentation in runtime styling API

- Makefile
- platform/android/.gitignore
- platform/android/bitrise.yml
closes #6697
This PR reworks the make targets for the android platform. 
- general cleanup, consistency naming
- allow running application on a device from cmake
- allow running our different types of android tests from cmake
- provide convenience method for running ndk-stack
- `make android-lib-$1` - builds core into a .so file
- `make android-$1`  - builds .so + .aar + .apk file
- `make run-android-$1` - builds .so + .aar + .apk file and runs it on a device
- `make apackage` - builds .so files for all supported ABI + .aar file
You can replace the $1 above with one of the following ABI:
> arm-v5 arm-v7 arm-v8 x86 x86-64 mips
Alternatively we provided some convenient configurations for `arm-v7`:
- `make android `
- `make run-android`
- `make run-android-unit-test` - executes unit tests on …
> [android] - update make targets

- platform/darwin/src/MGLStyleLayer.mm
https://github.com/mapbox/mapbox-gl-native/pull/6904 renamed the `layer` property to `rawLayer`. The subclasses of `MGLStyleLayer` were all updated to use `rawLayer` but the
`MGLStyleLayer` itself was not. So, common functionality like setting visibility caused a crash.
This removes the `layer` property in `MGLStyleLayer` itself and uses the `rawLayer` property that actually points to the mbgl layer.
cc @1ec5
> [ios, macos] Use the rawLayer pointer to access the mbgl layer

- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
Streamlined `-[MGLMapView annotationTagForAnnotation:]` to use the `std::map` added in #5987 on iOS. Added the same `map` to the macOS implementation.
Replaced unsafe calls to `std::map::at()` – which throws an exception when the given element isn’t found – with calls to the newly streamlined `-annotationTagForAnnotation:`. One of these unsafe calls was added in #5987 and is reverted by this PR in favor of returning `nil`.
Return the user location annotation view when given the user location annotation.
Fixes #6953.
/cc @boundsj
> Fix crash getting annotation view

- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/MathUtils.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerViewTest.java
- platform/android/src/jni.cpp
This PR cherry picks patch fixes made to `release-android-v4.2.0` to master.
Capturing discussion with @ivovandongen: that the approach of patching master and cherry picking to release branch (reverse what happened here) is more logical in a multi platform project. This keeps changes between master/release branches minimal and makes resolving merge conflicts occur after development instead of occurring after release. From now on let's try to apply this as a best practice.
Review @ivovandongen 
> Cherry pick release v4.2.0

- Makefile
- platform/android/scripts/generate-style-code.js
- platform/darwin/scripts/generate-style-code.js
- scripts/generate-style-code.js
- scripts/style-code.js
Android builds currently regenerate the style code on every build, which triggers a recompile of many dependent files (~60 files), so running `make android-lib-arm-v7` twice without modifying any files in between isn't fast.
> Fast Android rebuilds

- src/mbgl/renderer/frame_history.hpp
- test/map/map.test.cpp
An alternative fix to #6747/#6667: In `FrameHistory::needsAnimation`, we are computing `time - previousTime`, but since `previousTime` was initialized to `TimePoint::min()`, we got a integer overflow, which produced invalid values and made the map render continuously.
/cc @tobrun
> Don't initialize timestamps to TimePoint::min()

- src/mbgl/map/map.cpp
> [core] Ensure correct GL context in Map::onLowMemory()

- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
Getting a crash in the testapp when opening the soft keyboard and attempting to resize the map.
```
11-04 15:18:19.860 24581-24581/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-04 15:18:19.860 24581-24581/? A/DEBUG: Build fingerprint: 'google/sailfish/sailfish:7.1/NDE63L/3273814:user/release-keys'
11-04 15:18:19.860 24581-24581/? A/DEBUG: Revision: '0'
11-04 15:18:19.860 24581-24581/? A/DEBUG: ABI: 'arm'
11-04 15:18:19.860 24581-24581/? A/DEBUG: pid: 24520, tid: 24520, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
11-04 15:18:19.861 24581-24581/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-04 15:18:19.864 24581-24581/? A/DEBUG: Abort message: '../../../platform/android/src/native_map_view.cpp:127: void …
```
> Viewport getCurrentValue failed assertion error

- package.json
- platform/node/CHANGELOG.md
Publishing a patch release to get the `stencil mask overflow` fix from #6871 out before a (semver-major?) change removing ClipperLib from published binaries in #6965.
> node-v3.4.1

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/BackgroundLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CannotAddLayerException.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/RasterLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CannotAddSourceException.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/customlayer/CustomLayerActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CircleLayerActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CustomSpriteActivity.java
- platform/android/src/jni.cpp
- platform/android/src/style/layers/layer.cpp
- platform/android/src/style/layers/layer.hpp
- platform/android/src/style/sources/source.cpp
- platform/android/src/style/sources/source.hpp
Fixes #6995
Should be ported to the 4.2.0 release branch as well.
cc @jfirebaugh @tobrun
> [android]  Refactor layer/source ownership

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- src/mbgl/map/map.cpp
Follow up from https://github.com/mapbox/mapbox-gl-native/pull/6989. When trying to make it work on android I noticed that `getLatLng` also set cameraMutated to true. This PR fixes this up + corrects the check in java code to validate if no camera position was provided.
```cpp
LatLng Map::getLatLng(optional<EdgeInsets> padding) const {
impl->cameraMutated = true;
return impl->transform.getLatLng(padding);
}
```
Review @jfirebaugh
> Default Style Camera on Android

- package.json
- src/mbgl/style/layer_observer.hpp
- src/mbgl/style/layers/layer.cpp.ejs
- src/mbgl/style/layers/line_layer.cpp
- src/mbgl/style/layers/symbol_layer.cpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style.hpp
- test/src/mbgl/test/stub_layer_observer.hpp
- test/style/style_layer.test.cpp
> Reflect changes in icon size immediately

- include/mbgl/map/map.hpp
- src/mbgl/map/map.cpp
- src/mbgl/style/layers/custom_layer_impl.cpp
- src/mbgl/style/layers/custom_layer_impl.hpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style.hpp
When a source or layer is removed transfer ownership back to the caller so it can (optionally) take it.
ref https://github.com/mapbox/mapbox-gl-native/issues/6959
cc @jfirebaugh
> [core] Return source and layer ownership

- src/mbgl/gl/extension.cpp
When running any application or test binary, the following is printed at startup:
<blockquote>
2016-11-08 09:03:35.915 mbgl-test[48917:6215380] [INFO] {}[OpenGL]: Vendor: Intel Inc.
2016-11-08 09:03:35.916 mbgl-test[48917:6215380] [INFO] {}[OpenGL]: Renderer: Intel(R) Iris(TM) Graphics 6100
2016-11-08 09:03:35.916 mbgl-test[48917:6215380] [INFO] {}[OpenGL]: Version: 2.1 INTEL-10.14.73
2016-11-08 09:03:35.916 mbgl-test[48917:6215380] [INFO] {}[OpenGL]: Shading Language Version: 1.20
2016-11-08 09:03:35.916 mbgl-test[48917:6215380] [INFO] {}[OpenGL]: Extensions: GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow …
> Remove debug spew

- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/geometry_tile_worker.cpp
In some situations, we are doing the same symbol placement request multiple times:
- placement configuration changed => triggers request
- rerender trigger update, which triggers a null change, but since the original request didn't complete yet, we are starting another placement request
> Prevent duplicate symbol placement requests

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
Targets release branch, extracted from #6532.
This PR allows to call new animations directly from the onFinish from another. Prior this fix one camera update cancelled the other because it was still resolving his onFinish event. Side effect, this mostly solves #6769 (definitive solution in https://github.com/mapbox/mapbox-gl-native/issues/6999). 
> [android] - post camera updates to the end of the message queue

- platform/qt/qt.cmake
This post-build step for `qmapboxgl` target copies the `platform/qt/include` folder into build path.
/cc @assanegu
> [Qt] Copy headers to build path in 'qt-lib' target

- package.json
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
Thanks to @masterjefferson [logcat](https://github.com/mapbox/mapbox-gl-native/issues/6400#issuecomment-250237354), we've found the root cause for the crashes using Android emulator Hardware OpenGL ES 2.0 support - in particular:
```
ERROR: 0:6: error(#101) Macro redefined: lowp
ERROR: 0:7: error(#101) Macro redefined: mediump
ERROR: 0:8: error(#101) Macro redefined: highp
```
This means that the shader compiler was already defining those macros for non-GLSL ES shader code. I have a PR in https://github.com/mapbox/mapbox-gl-shaders/pull/36 that checks if those macros are already defined, and also ensure NativeMapView that we're binding to the [EGL's OpenGL ES 2.0 API](https://www.khronos.org/registry/egl/sdk/docs/man/html/eglBindAPI.xhtml).
Fixes the issues mentioned in #2995 and #6400. …
> [android] Update GLSL + ensure binding to OpenGL ES 2.0

- platform/darwin/src/MGLMultiPoint.h
- platform/darwin/src/MGLMultiPoint.mm
- platform/darwin/src/MGLPointCollection.mm
Fixes https://github.com/mapbox/mapbox-gl-native/issues/6580
cc @incanus @1ec5
> [ios, macos] Use std::vector for MGLMultiPoint coordinate storage

- platform/ios/ios.xcworkspace/contents.xcworkspacedata
- platform/ios/uitest/ios-tests.xcodeproj/project.pbxproj
The ios-tests (KIF tests) project now pulls in OHHTTPStubs via a cross-project framework dependency, just like it pulls in our iOS SDK. Previously, the headers and implementation files making up OHHTTPStubs were added individually to the ios-tests target. But OHHTTPStubs was upgraded from 4.3.0 to 5.2.0 in #6150, the file references were left alone, leading to a number of broken or missing file references. The new target dependency is resilient to changes in OHHTTPStubs.
This PR also upgrades KIF to 3.5.1 and OHHTTPStubs to 5.2.2 in order to build and run in Xcode 8.1.
Fixes #6955.
/cc @boundsj @incanus @friedbunny
> Fix ios-tests build failures

- cmake/core-files.cmake
- package.json
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- src/mbgl/text/glyph_set.cpp
- src/mbgl/text/glyph_set.hpp
- src/mbgl/util/i18n.cpp
- src/mbgl/util/i18n.hpp
Automatically insert a line break after any supported Chinese, Japanese, or Yi character in a point-placed label as needed to stay within the `text-max-width`. Balance the lines unless non-ideographic text such as Latin letters are present.
_Compare the label on the map to the popover title, which shows the queried feature’s name. A line break is absent from the feature but applied automatically by the renderer._
Ported from mapbox/mapbox-gl-js#3420. Fixes #1223. Depends on mapbox/mapbox-gl-test-suite#153.
Before merging:
/cc @lucaswoj @xrwang
> Line-break ideographic text by character

- platform/darwin/src/MGLBackgroundStyleLayer.mm
- platform/darwin/src/MGLCircleStyleLayer.mm
- platform/darwin/src/MGLFillStyleLayer.mm
- platform/darwin/src/MGLGeoJSONSource.mm
- platform/darwin/src/MGLLineStyleLayer.mm
- platform/darwin/src/MGLRasterSource.mm
- platform/darwin/src/MGLRasterStyleLayer.mm
- platform/darwin/src/MGLSource_Private.h
- platform/darwin/src/MGLStyle.mm
- platform/darwin/src/MGLStyleLayer.mm.ejs
- platform/darwin/src/MGLStyleLayer_Private.h
- platform/darwin/src/MGLSymbolStyleLayer.mm
- platform/darwin/src/MGLVectorSource.mm
If a source or layer is removed from the style, recapture the unique pointer ownership. This makes it safe to add back sources and layers after they have been removed.
Fixes iOS and macOS portion of https://github.com/mapbox/mapbox-gl-native/issues/6959
cc @1ec5 @frederoni @incanus
> [ios, macos] Take back source and layer ownership on removal

- .travis.yml
- cloudformation/travis.template
- platform/android/bitrise.yml
- platform/android/scripts/metrics.sh
- platform/ios/bitrise.yml
- platform/ios/scripts/metrics.sh
- platform/linux/scripts/after_success.sh
- platform/linux/scripts/metrics.sh
- platform/macos/bitrise.yml
- platform/macos/scripts/metrics.sh
- scripts/log_binary_size.sh
Add logging to CloudWatch that records binary size for Linux, Android, iOS and macOS. In the case of fat binaries, the binary size is split up to individual architectures (iOS/Android) in addition to the default archive.
The idea is that we'll have nightly builds (running in EU early morning) that create a stripped release build to approximate the size of the library in a deployed setting, and record those. Using the data stored in CloudWatch, we'll be able to generate graphs of how the binary size changes over time.
> Track binary size over time

- .travis.yml
- package.json
- platform/node/CHANGELOG.md
- platform/node/bitrise.yml
- platform/node/scripts/after_script.sh
- platform/node/scripts/after_success.sh
Switches Node.js Linux binary builds from OSMesa back to GLX/xvfb to remove a runtime dependency on `libOSMesa.so.8` and allow `libGL.so` to be supplied at runtime by alternate implementations, like the NVIDIA proprietary drivers for rendering on hardware GPUs.
/cc @brunoabinader @springmeyer
> Switch Node Linux binary builds back to GLX/xvfb

- platform/darwin/src/MGLMultiPoint.mm
- platform/darwin/src/MGLPointCollection.mm
Avoid precision loss / cast warnings.
cc @incanus @1ec5
> [ios, macos] Use NSNumber in exception strings

- src/mbgl/gl/attribute.cpp
- src/mbgl/gl/attribute.hpp
- src/mbgl/gl/context.cpp
- src/mbgl/gl/context.hpp
- src/mbgl/gl/program.hpp
- src/mbgl/gl/segment.hpp
- src/mbgl/programs/circle_program.hpp
- src/mbgl/programs/collision_box_program.hpp
- src/mbgl/programs/debug_program.hpp
- src/mbgl/programs/raster_program.hpp
- src/mbgl/renderer/circle_bucket.hpp
- src/mbgl/renderer/debug_bucket.cpp
- src/mbgl/renderer/debug_bucket.hpp
- src/mbgl/renderer/fill_bucket.hpp
- src/mbgl/renderer/line_bucket.hpp
- src/mbgl/renderer/painter.cpp
- src/mbgl/renderer/painter.hpp
- src/mbgl/renderer/painter_background.cpp
- src/mbgl/renderer/painter_clipping.cpp
- src/mbgl/renderer/painter_debug.cpp
- src/mbgl/renderer/painter_raster.cpp
- src/mbgl/renderer/symbol_bucket.hpp
Per https://github.com/mapbox/mapbox-gl-native/pull/6468#discussion_r85182731
This is safer now -- it can be an implementation detail of Segment/Context. And the typing of SegmentVector now ensures that the attributes and program match.
Also, we've determined the cause of #5731.
cc @kkaefer
> Return to static, per-segment approach to VAOs

- test/map/map.test.cpp
> [tests] Disable "ContinuousRendering" test; causing spurious CI failures

- .travis.yml
- CMakeLists.txt
- Makefile
- package.json
- platform/default/glfw_view.cpp
- platform/linux/config.cmake
- platform/linux/src/headless_backend_egl.cpp
- platform/linux/src/headless_display_egl.cpp
- scripts/travis_setup.sh
- test/api/annotations.test.cpp
- test/api/api_misuse.test.cpp
- test/api/custom_layer.test.cpp
- test/api/query.test.cpp
- test/api/render_missing.test.cpp
- test/api/repeated_render.test.cpp
- test/gl/object.test.cpp
- test/map/map.test.cpp
- test/src/mbgl/test/util.cpp
- test/src/mbgl/test/util.hpp
- test/util/memory.test.cpp
- test/util/offscreen_texture.test.cpp
Follow-up to the work started by @tiagovignatti in #5843 - thanks Tiago!
This PR implements EGL headless backend, using `EGL_DEFAULT_DISPLAY` as primary display - thus no need for handling render nodes directly via [gbm](https://en.wikipedia.org/wiki/Mesa_(computer_graphics)#Generic_Buffer_Management).
Though we use software rendering via LLVMpipe, we still need a valid display for EGL to be properly initialized. On Travis CI, _like the Qt builds_, we still need to start Xvfb to obtain a valid display.
I've put some effort attempting to find a working setup for Mesa to have its EGL platform working with a native display that doesn't require a window system, but so far no success. The most promising option, though, comes from this recent [Mesa …
> [linux] Added EGL headless backend support

- src/mbgl/style/source_impl.cpp
When abandoning geometry (vector) tiles, we're putting them into a [cache](https://github.com/mapbox/mapbox-gl-native/blob/5479b75c9fa971332aadfede6b380267eebbd566/src/mbgl/style/source_impl.cpp#L163-L180), but [for raster sources, that cache is of size 0](https://github.com/mapbox/mapbox-gl-native/blob/5479b75c9fa971332aadfede6b380267eebbd566/src/mbgl/style/source_impl.cpp#L142), so raster tiles get immediately deleted when they are moving outside of the viewport.
We should hold on to raster tiles as well to avoid flickering when they are getting moved out and back into the viewport.
> Raster tiles are not cached

- platform/android/bitrise.yml
- scripts/log_binary_size.sh
I piggy-backed on the scheduled Bitirse build that already exists, but it turned out that it is not building master but the current release branch. That means we need to add a second scheduled build that runs master.
> Create separate Android nightly build

- package.json
- platform/node/src/node_map.cpp
- platform/node/src/node_map.hpp
- platform/node/test/js/map.test.js
- platform/node/test/suite_implementation.js
Revert node `Map#render` API to "stateless" camera semantics: the center, zoom, bearing, and pitch passed are what is used to render, with defaults for unspecified values.
For the test-suite implementation, which wants stateful semantics, track the camera options manually. Also, change the implementation of `Map#render` so that it avoids calling `setCenter`, etc. when the value is not changing. (Internally, `setCenter` does not short-circuit, so it could cause undesired updates.)
cc @mikemorris
> [node] Revert semantics of Map#render

- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/renderer/painter.cpp
- src/mbgl/renderer/painter_symbol.cpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style.hpp
- test/api/annotations.test.cpp
~~Re-enable symbol clipping based on layout property settings, cleaning up workarounds and adds padding to symbol annotation tiles.~~
Avoid clipping symbols in continuous mode - preserving clipping behavior in still mode. To avoid overdrawing symbols on tile edges, we avoid inserting symbol features with anchors located among the tile extent edges.
Fixes #1673 and #6670.
/cc @jfirebaugh @ansis
> [core] Avoid clipping symbols in continuous mode

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/src/jni.cpp
Fixes #7104 
The root cause was that the nativeMapView's `gestureInProgress` was false during the fling.
This resulted in mbgl map unwrapping the longitude to find the shortest path > https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/transform.cpp#L111
Without the unwrapping, the deceleration rate was way too slow as well as the duration causing a simple fling to go around the world 50 times before stopping. The new deceleration rate mimics a scrollView with fast scrolling disabled.
@tobrun  👀
> [android] fixed horizontal panning going the opposite direction

- src/mbgl/util/mapbox.cpp
We're only using `<regex>` in one instance, for removing `access_token=*` from URLs when putting them into the cache. However, `<regex>` adds quite a bit to the binary size; I'm measuring these size reductions:
- Android/arm-v7: 4,903,78 => 4,842,348 bytes, ~60KB reduction
- macOS/x86_64: 3,955,184 => 3,860,600 bytes, ~95KB reduction 
- iOS/arm64: 3,012,356 => 2,961,728 bytes, ~50KB reduction
> Don't use <regex> to reduce binary size

- platform/android/config.cmake
Adding `-ffunction-sections -fdata-sections` as compile flags, and `-Wl,--gc-sections` as link flags reduces the side of the shared library on Android: 4,916,076 bytes => 4,809,548 bytes for arm-v7.
> Android: Use gc-sections to reduce code size

- platform/ios/src/MGLMapView.mm
Fixes regression https://github.com/mapbox/mapbox-gl-native/issues/6954#issuecomment-260768209
There's no need to attach the constraints to the superview as mentioned in the comment. This fixes the compass being out of bounds when not in full screen.
@1ec5 👀
> [ios] simplified constraints and fixed regression 6954

- platform/android/bitrise.yml
https://github.com/mapbox/mapbox-gl-native/pull/6979 got merged, we can safely reenable running all our instrumentation tests back on Firebase.
> run all espresso tests on Firebase test lab

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Targets release branch, some follow up work on the cancelable callback system.
While doing some testing I noticed that we weren't correctly calling the onFinish callback. This could led to situations that we recevied callbacks for the previously set callback while the current one should be invoked. 
> Call correct onfinish callback

- platform/android/config.cmake
We're currently first assembling all object files into a `libmbgl-core.a`, then linking that into the actual shared object. However, the archive file is > 200MB in size, so assembling it takes a while and requires some disk I/O. Since we're using a recent clang version, we can just create thin archives using the `T` flag to avoid all of that.
> Use thin archives when building Android

- scripts/log_binary_size.sh
- scripts/publish_binary_size.sh
We should upload the binary size metrics to S3 so that we can have a public chart of binary size over time.
> Upload binary size metrics to S3

- platform/darwin/scripts/generate-style-code.js
- platform/darwin/src/MGLBackgroundStyleLayer.mm
- platform/darwin/src/MGLCircleStyleLayer.mm
- platform/darwin/src/MGLFillStyleLayer.mm
- platform/darwin/src/MGLGeometry.h
- platform/darwin/src/MGLLineStyleLayer.mm
- platform/darwin/src/MGLRasterStyleLayer.mm
- platform/darwin/src/MGLStyleLayer.mm.ejs
- platform/darwin/src/MGLStyleValue_Private.h
- platform/darwin/src/MGLSymbolStyleLayer.mm
- platform/darwin/src/NSValue+MGLStyleEnumAttributeAdditions.h
- platform/darwin/src/NSValue+MGLStyleEnumAttributeAdditions.h.ejs
- platform/darwin/src/NSValue+MGLStyleEnumAttributeAdditions.mm
- platform/darwin/src/NSValue+MGLStyleEnumAttributeAdditions.mm.ejs
- platform/ios/app/MBXViewController.m
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/Mapbox.h
- platform/macos/macos.xcodeproj/project.pbxproj
- platform/macos/src/Mapbox.h
Fixes https://github.com/mapbox/mapbox-gl-native/issues/6760
> Map Darwin style enumerations to mbgl equivalents

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/InfoWindowManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/annotations/MarkerViewTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraMoveTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraAnimationTypeActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
- platform/android/bitrise.yml
WIP - closes #6532 - This PR moves camera logic to a dedicated java class. 
Todo
After this we can look into integrating https://github.com/mapbox/mapbox-gl-native/issues/4746
> [android] - move camera logic to dedicated transform class

- platform/android/src/style/conversion/types.hpp
- platform/android/src/style/conversion/types.hpp.ejs
- platform/android/src/style/conversion/types_string_values.hpp
- platform/android/src/style/conversion/types_string_values.hpp.ejs
- platform/android/src/style/layers/background_layer.cpp
- platform/android/src/style/layers/background_layer.hpp
- platform/android/src/style/layers/circle_layer.cpp
- platform/android/src/style/layers/circle_layer.hpp
- platform/android/src/style/layers/fill_layer.cpp
- platform/android/src/style/layers/fill_layer.hpp
- platform/android/src/style/layers/layer.cpp.ejs
- platform/android/src/style/layers/layer.hpp.ejs
- platform/android/src/style/layers/line_layer.cpp
- platform/android/src/style/layers/line_layer.hpp
- platform/android/src/style/layers/raster_layer.cpp
- platform/android/src/style/layers/raster_layer.hpp
- platform/android/src/style/layers/symbol_layer.cpp
- platform/android/src/style/layers/symbol_layer.hpp
Fixes #7157.
Fixed a documentation comment included in templates (old command not working anymore, the good one is `make android-style-code`) and regenerated classes.
Note:
When launching `make style-code` some of the files are skipped…
What am I missing? How do I need to proceed to regenerate all classes?
(There are still some classes with the incorrect command). 
Cc/ @ivovandongen @tobrun @zugaldia
> Fix incorrect command comment in templates

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/feature/QueryRenderedFeaturesBoxCountTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/feature/QueryRenderedFeaturesHighlightTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/feature/QueryRenderedFeaturesPropertiesTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/feature/QueryRenderedSymbolBoxCountTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxCountActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxHighlightActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxSymbolCountActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesPropertiesActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_query_features_box.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_query_features_point.xml
This PR contains a couple of tests that validate if query rendered features has regressed. It currently covers the 4 testapp activities related to query rendered features. The tests executes the default user action and validates if the expected result is shown in a Toast message/InfoWindow. 
Related to f4b91fe, there is an issue on master that doesn't seem to load the map without moving it to xml, looking into this issue as part of #6532. **update**: the PR following #6532 is not showing this issue.
> Add instrumentation tests for query rendered features

- platform/qt/app/mapwindow.cpp
- platform/qt/app/mapwindow.hpp
- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qmapboxgl_p.hpp
This PR:
- Workarounds two different bugs in Qt for macOS:
- Qt 4.x provides an incomplete FBO on first paint: http://lists.qt-project.org/pipermail/qt-interest-old/2011-August/035466.html
- Consume GL_INVALID_OPERATION from Qt 5.x render calls: https://bugreports.qt.io/browse/QTBUG-36802
- The latter causes the Qt QML example and the upcoming Mapbox GL plugin for Qt framework to work again on Qt 5.7 onwards.
- Lazy load QMapboxGL in the Q{,Open}GLWidget MapWindow example to avoid OpenGL initialization issues.
- Use QOpenGLWidget instead of QGLWidget for the MapWindow example from Qt 5.4 onwards.
Fixes the root cause of #6849. (/cc @assanegu)
> [Qt] Use QOpenGLWidget instead of QGLWidget from Qt 5.4 onwards

- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
This adds a ref count to guard against calling activate after it has already been called. This can happen when a layer is added during certain map lifecycle methods like MapChangeWillStartRenderingFrame that also triggers activation. This also protects against issues related to a deactivation of the context happening in an inner scope while an outer scope is still expecting to be able to use the context.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7163
cc @1ec5 @incanus @jfirebaugh
> [ios, macos] Refcount view activations

- src/mbgl/programs/program.hpp
std::to_string() potentially uses a decimal point character different
than a dot (.), depending on the environment's locale. But since this
generated string will be part of GLSL code, there needs to be a dot and
nothing else.
https://github.com/mapbox/mapbox-gl-native/pull/7197
> Always use a dot as a decimal point in string, independent of locale

- cmake/shaders.cmake
If you update the commit hash of mapbox-gl-shaders in package.json, run `make xproj`, and build, it should run `build-shaders.js` for each of the modified shaders. But it doesn't -- the old output is used.
cc @kkaefer
> Updating mapbox-gl-shaders doesn't trigger build-shaders.js

- platform/darwin/test/MGLOfflineStorageTests.m
This fixes the spurious offline storage unit test failure on iOS that was originally reported in #6385 and still reproduces consistently on the branch for #5999. See https://github.com/mapbox/mapbox-gl-native/pull/5999#issuecomment-263678869 for details.
I introduced this bug as part of #6397. Even if the expectation is immediately fulfilled, we still have to wait for it to be fulfilled, because the expectation only gets unregistered after waiting. The zombie expectation was fulfilling a stricter expectation in a test method.
/cc @frederoni
> Fix spurious offline storage test failure

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/BackgroundLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Property.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/RasterLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property.java.ejs
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/BackgroundLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RasterLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs
Fixes #6348.
I added @UiThread annotation in `layer.java.ejs`, fixed a documentation comment included in templates (old command not working anymore, the good one is `make android-style-code`) and regenerated java classes.
Cc/ @ivovandongen @tobrun @zugaldia
> Add uithread annotation and regenerate classes

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewScaleActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_marker_view_scale.xml
Closes #7074, targets android release branch for 4.2.0.
Review @ivovandongen .
> [android] - callback for asynchronous adding of a MarkerView

- platform/darwin/src/MGLStyle.h
- platform/ios/src/MGLMapView.h
- platform/macos/src/MGLMapView.h
Fixes https://github.com/mapbox/mapbox-gl-native/issues/6616 for iOS and macOS
cc @1ec5
> [ios, macos] Add notes to APIs that rely on style and source ids

- package.json
- src/mbgl/layout/symbol_feature.hpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/text/bidi.cpp
- src/mbgl/text/bidi.hpp
- src/mbgl/text/glyph_set.cpp
- src/mbgl/text/glyph_set.hpp
- src/mbgl/util/i18n.cpp
- src/mbgl/util/i18n.hpp
- test/util/merge_lines.test.cpp
Fix for https://github.com/mapbox/mapbox-gl-native/issues/7112
Also makes small changes to handling of leading/trailing whitespace in labels:
- Trim whitespace before calculating line max-width for alignment/justification
- Don't crash if line-breaking algorithm creates a line with just a single whitespace character on it
> Full support for bidirectional line breaking

- platform/darwin/src/MGLBackgroundStyleLayer.mm
- platform/darwin/src/MGLCircleStyleLayer.mm
- platform/darwin/src/MGLFillStyleLayer.mm
- platform/darwin/src/MGLLineStyleLayer.mm
- platform/darwin/src/MGLRasterStyleLayer.mm
- platform/darwin/src/MGLStyleLayer.mm
- platform/darwin/src/MGLStyleLayer.mm.ejs
- platform/darwin/src/MGLStyleLayer_Private.h
- platform/darwin/src/MGLSymbolStyleLayer.mm
This updates the code generation for style layers to add a test to check that the style object returned from mbgl can be safely cast into the expected type so ownership can be returned to the caller when removing layers.
Previously a crash occurred if a layer of type T was added before a layer of type U but both layers shared the same identifier. In that case, if the pointer to the second layer of type U
was used to remove that layer, a runtime exception would occur since mbgl returns the layer with type T (the first one added) and the unsafe cast was triggered.
Now, even though the unsafe cast is avoided, an exception will still occur if layers with the same identifier are manipulated as described above but this is done as part of a validation check for all public style layer methods at …
> Avoid unsafe cast when removing style layers

- src/mbgl/gl/context.cpp
- src/mbgl/gl/program.hpp
- src/mbgl/gl/segment.hpp
- src/mbgl/renderer/debug_bucket.cpp
- src/mbgl/renderer/debug_bucket.hpp
- src/mbgl/renderer/painter.cpp
- src/mbgl/renderer/painter.hpp
- src/mbgl/renderer/painter_background.cpp
- src/mbgl/renderer/painter_clipping.cpp
- src/mbgl/renderer/painter_debug.cpp
- src/mbgl/renderer/painter_raster.cpp
I found that maintaining both pathways was a drag on work towards #4860. It's easier to use indexed rendering consistently.
cc @kkaefer
> [core] Use indexed rendering everywhere

- platform/darwin/src/MGLVectorStyleLayer.h
- platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm
- platform/darwin/test/MGLFilterTests.mm
This reverts commit 6877e3efe73fb6e103c2635f1e4b1c1866b17d5c.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/6784
cc @1ec5
> [ios, macos] Add back support for CONTAINS operator

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.h
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
I couldn't tell from the discussion on #2278 and #7194 if implementation of this was already in progress or not, but i needed this functionality to be able to continue with a progress.  If this is already is progress, please ignore this PR.
> Make tap gesture recognizer fail if it doesn’t do anything

- cloudformation/travis.template
The `BitriseUser` in CloudFormation currently does not have access to `s3://mapbox/mapbox-gl-native/metrics`, so publishing the metrics fails.
> Allow Bitrise user to publish metrics

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java
> [android] telemetry - horizontal accuracy

- Makefile
- platform/android/config.cmake
We're currently running strip operations for every invocation, and build the test cases always, which makes the Android nightly build [go over Bitrise's 45 minute limit](https://www.bitrise.io/build/1a579128dd97a6a4). We should refactor `make apackage` so that it doesn't build the `mbgl-test` library.
> Refactor Android CMake targets

- package.json
This commit updates the mapbox-gl-test-suite to a commit on the master branch of that repository.
/ref https://github.com/mapbox/mapbox-gl-native/pull/7123#discussion_r90630129
/cc @ChrisLoer
> Update mapbox-gl-test-suite version

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
Fixes #3154 
An open callout view now stays open while panning around.
Tapping the map view will dismiss the callout view.
> [ios] keep callout view open when panning

- platform/darwin/src/MGLFeature.mm
- platform/darwin/src/MGLFeature_Private.h
- platform/darwin/src/MGLGeoJSONSource.h
- platform/darwin/src/MGLGeoJSONSource.mm
- platform/darwin/src/MGLPointAnnotation.mm
- platform/darwin/src/MGLPointCollection.mm
- platform/darwin/src/MGLPolygon.mm
- platform/darwin/src/MGLPolyline.mm
- platform/darwin/src/MGLShapeCollection.mm
- platform/darwin/src/MGLShape_Private.h
- platform/darwin/test/MGLGeoJSONSourceTests.mm
- platform/darwin/test/MGLStyleTests.mm
- platform/darwin/test/MGLStyleValueTests.swift
- platform/ios/app/MBXViewController.m
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/macos/macos.xcodeproj/project.pbxproj
First stab at #6986 
I'm slightly hesitant about replacing `-[MGLGeoJSONSource initWithIdentifier:features:options:]` with `feature` because of the additional initialization of MGLShapeCollectionFeature devs has to do now compared to a concise array literal prior to this change.
@1ec5 👀
> Allow initializing MGLGeoJSONSource from a shape

- platform/android/config.cmake
The Android NDK uses the gold linker by default, and it includes a function called [Identical Code Folding](http://research.google.com/pubs/pub36912.html), which deduplicates identical functions. It can be enabled by adding  `--icf=safe` to the linker flags, and reduces the code in a different way from [--gc-sections](https://github.com/mapbox/mapbox-gl-native/pull/7107). Just by enabling ICF, I got a reduction from 4,916,076 bytes to 4,715,372 bytes for arm-v7.
We are currently using the gold linker for `arm-v5`, `arm-v7`, `x86`, and `x86_64`, but [we **aren't** using it currently for `arm-v8`](https://github.com/mapbox/mason/blob/master/mason.sh#L147) due to [a bug that @tmpsantos previously discovered](https://code.google.com/p/android/issues/detail?id=204151). The gold linker doesn't …
> Android: Use Identical Code Folding to reduce binary size

- platform/node/CHANGELOG.md
> Fix spelling on month in node.js changelog

- platform/darwin/scripts/generate-style-code.js
- platform/darwin/scripts/style-spec-cocoa-conventions-v8.json
- platform/darwin/src/MGLLineStyleLayer.h
- platform/darwin/src/MGLLineStyleLayer.mm
- platform/darwin/src/MGLRasterStyleLayer.h
- platform/darwin/src/MGLStyleLayer.h.ejs
- platform/darwin/src/MGLSymbolStyleLayer.h
- platform/darwin/src/MGLSymbolStyleLayer.mm
- platform/darwin/test/MGLLineStyleLayerTests.m
- platform/darwin/test/MGLSymbolStyleLayerTests.m
Fixes #6098 
Renamed a couple of more style spec properties.
- line-dasharray => line-dash-pattern
- icon-size => icon-scale
> Rename style spec properties

- platform/ios/src/UIImage+MGLAdditions.mm
- platform/macos/app/MapDocument.m
- platform/macos/src/NSImage+MGLAdditions.mm
This is a followup to #7096 that converts template images to SDF icons and back when storing them as style images. It turns out that template images and SDF icons are exactly the same format ([source](https://github.com/mapbox/maki/blob/cb5d8516eb4d0fcbe38f69dd285268f43c3d6a4e/sdf-render.js#L70-L75)).
Also extended the Manipulate Style command in macosapp to replace theater POIs with AppKit’s built-in `NSImageNameIChatTheaterTemplate` template image:
Fixes #7291.
/cc @incanus @friedbunny
> Template images as style images

- platform/darwin/src/MGLGeometry.h
- platform/darwin/src/MGLMultiPoint.h
- platform/darwin/src/MGLMultiPoint.mm
- platform/darwin/src/MGLOverlay.h
- platform/darwin/src/MGLPointCollection.mm
- platform/darwin/src/MGLPolygon.mm
- platform/darwin/src/MGLPolyline.mm
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Added the complete set of methods for mutating the vertices of an MGLMultiPoint. Invalidate `overlayBounds` whenever the coordinates change, but don’t recompute the bounds until they’re requested. Previously, `-[MGLMultiPoint replaceCoordinatesInRange:withCoordinates:]` failed to recompute the bounds.
Rewrote MGLMultiPoint documentation to refer to vertices instead of points. Removed a paragraph in MGLOverlay documentation that was full of references to features that exist in MKOverlay but not MGLOverlay.
Added a utility function for testing whether two `MGLCoordinateBounds`es intersect, based on `mbgl::LatLngBounds::intersects()`. Removed unused color conversion code.
Fixes #6583.
/cc @boundsj @incanus
> More ways to reshape an MGLMultiPoint

- bin/render.cpp
- cmake/test-files.cmake
- src/mbgl/util/url.cpp
- src/mbgl/util/url.hpp
- test/util/url.test.cpp
Our mbgl-render CLI app accepts a `--style` parameter, but it only takes paths to local files, and you can't specify URLs.
> Allow specifying URLs, not just file names to mbgl-render

- platform/darwin/test/MGLGeoJSONSourceTests.mm
Assigning MGLShapeCollection from MGLShape requires casting to prevent compiler warnings.
> Fix compiler warnings

- platform/qt/src/qmapboxgl.cpp
A bug present in Qt 5.7 onwards affected macOS in a sense that it'd eventually enqueue the GL error pipeline with a `GL_INVALID_OPERATION` caused by a faulty usage of `glClearDepthf` instead of `glClearDepth` in Desktop GL - details in https://bugreports.qt.io/browse/QTBUG-57490 and https://bugreports.qt.io/browse/QTBUG-56798.
Proposed fix for Qt 5.7 in https://codereview.qt-project.org/#/c/179218/ - this is probably coming on the next patch release.
/cc @tmpsantos
> [qt, macos] Remove workaround for a bug in Qt 5.7

- platform/darwin/src/MGLStyle.h
- platform/darwin/src/MGLStyle.mm
- platform/darwin/test/MGLStyleTests.mm
cc @1ec5 @ivovandongen 
(sorry!)
> [ios, macos] Fix typo in exception name for style source identifier

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
Closes #7322, there was a typo with `)` which resulted in applying screen density to already density dependant values.  Review @cammace
> [android] - screen density for instance variables of MapboxMapOptions

- platform/darwin/src/MGLVectorStyleLayer.h
Fixes https://github.com/mapbox/mapbox-gl-native/issues/6970
cc @1ec5 @frederoni
> [ios, macos] Warn about special characters in predicates

- platform/darwin/scripts/style-spec-cocoa-conventions-v8.json
- platform/darwin/src/MGLRasterStyleLayer.h
- platform/darwin/src/MGLRasterStyleLayer.mm
- platform/darwin/test/MGLRasterStyleLayerTests.m
Properties shouldn't be verbs.
This PR renames `raster-hue-rotate` to `raster-hue-rotation`
> Rename raster hue rotate

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/TrackingSettingsTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettingsTest.java
remove location enabled flag from MapboxMap, decouple TrackingSettings from MyLocationViewSettings using a FocalPointChangeListener interface, Move state related to tracking modes to MyLocationView (shared object between MyLocationViewSettings and TrackingSettings).
> [android] - remove location enabled flag from MapboxMap

- platform/android/config.cmake
#7109 mistakenly added ICF to all architectures, but it is not supported on mips. Additionally, arm64 doesn't seem to use the gold linker by default.
> Fix Identical Code Folding on Android

- platform/qt/include/qmapboxgl.hpp
- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qmapboxgl_p.hpp
Used by `QGeoMap` to show copyrights (example below):
Part of #2723.
/cc @tmpsantos
> [qt] Added copyrightsChanged() signal

- platform/darwin/src/MGLOpenGLStyleLayer.mm
This fixes an issue where our iOS SDK could not be compiled as a Release build.
> [ios, macos] Silence -Wc++11-narrowing warning in open gl layer

- platform/darwin/src/MGLFeature.h
- platform/darwin/src/MGLPointCollection.h
- platform/darwin/src/MGLRuntimeStylingTests.m.ejs
- platform/darwin/src/MGLShapeSource.h
- platform/darwin/src/MGLShapeSource.mm
- platform/darwin/src/MGLShapeSource_Private.h
- platform/darwin/src/MGLStyle.mm
- platform/darwin/src/MGLVectorStyleLayer.h
- platform/darwin/test/MGLCircleStyleLayerTests.m
- platform/darwin/test/MGLFillStyleLayerTests.m
- platform/darwin/test/MGLFilterTests.mm
- platform/darwin/test/MGLLineStyleLayerTests.m
- platform/darwin/test/MGLRasterStyleLayerTests.m
- platform/darwin/test/MGLShapeSourceTests.mm
- platform/darwin/test/MGLStyleTests.mm
- platform/darwin/test/MGLStyleValueTests.swift
- platform/darwin/test/MGLSymbolStyleLayerTests.m
- platform/ios/app/MBXViewController.m
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/jazzy.yml
- platform/ios/src/Mapbox.h
- platform/macos/app/MapDocument.m
- platform/macos/jazzy.yml
- platform/macos/macos.xcodeproj/project.pbxproj
- platform/macos/src/Mapbox.h
ref https://github.com/mapbox/mapbox-gl-native/issues/7160
> [ios, macos] Rename MGLGeoJSONSource to MGLShapeSource

- platform/darwin/src/MGLAttributionInfo.h
- platform/darwin/src/MGLRasterSource.h
- platform/darwin/src/MGLShapeSource.h
- platform/darwin/src/MGLSource.h
- platform/darwin/src/MGLVectorSource.h
- platform/darwin/test/MGLStyleTests.mm
- platform/darwin/test/MGLStyleValueTests.swift
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Expanded documentation comments about the runtime styling source classes to match the level of detail found in the style layer documentation. This PR will be affected by or will affect #7334 and #7337.
Also fixed a few stray references to GeoJSON sources.
/cc @boundsj @ericrwolfe
> Expand source documentation

- include/mbgl/map/backend.hpp
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/darwin/src/MGLStyle.mm
- platform/darwin/test/MGLStyleTests.mm
- platform/ios/src/MGLMapView.mm
- src/mbgl/map/map.cpp
- src/mbgl/style/style.cpp
- test/style/style_layer.test.cpp
> Check for duplicate layer IDs

- platform/ios/config.cmake
Trying to land #7131 as separate PRs to make the changes easier to reason about.
This changes the *default* setting to only build the active architecture (i.e. they for the device you connected to your Mac). This cuts build time in half since we don't need to build the other architecture when iterating.
On CI, and for `make ipackage/iframework`, we are using the `package.sh` script which already forces `ONLY_ACTIVE_ARCH=NO` and ensures that both architectures get built, so we can discover build-time issues for different architectures. Similarly, running other iOS-related make targets that build for Simluator already force `ONLY_ACTIVE_ARCH=YES`. This means that this change *only* affects what is being built when you use Xcode to manually compile apps; automated builds are unaffected by …
> Only build active architecture in Xcode

- platform/darwin/src/MGLFeature.mm
- platform/darwin/src/MGLShapeCollectionFeature_Private.h
- platform/darwin/src/MGLShapeSource.mm
- platform/darwin/test/MGLShapeSourceTests.mm
- platform/ios/app/MBXViewController.m
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/macos/macos.xcodeproj/project.pbxproj
fixes https://github.com/mapbox/mapbox-gl-native/issues/7336
> [ios, macos] Load features into shape source if possible

- package.json
- platform/node/test/suite_implementation.js
- src/mbgl/map/map.cpp
- src/mbgl/style/source_impl.cpp
Fixes #7241
Fixes #7225
Fixes #6758
Re-ordering `relayout()` after `recalculate()` ensures that sources are enabled before checking if tiles need to be reloaded on them.
> Relayout after recalculating to ensure visibility changes are handled correctly

- platform/darwin/scripts/generate-style-code.js
- platform/darwin/scripts/style-spec-overrides-v8.json
- platform/darwin/src/MGLStyle.h
- platform/darwin/src/MGLSymbolStyleLayer.h
SDF icons are known as template images in AppKit and UIKit. `iconImage` was renamed `iconImageName` in #7128, so any references to it (including in property requirements lists) need to be updated.
/ref #7300
> Override references to property names in property requirements lists

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
mitigates #5281, this PR impacts the fling gesture by
- limiting the input for moveBy based on tilt current value (ranges from 1/2 -> 1/8)
- lower limiting with no tilt, fling gesture shifts more
- lower animation time, makes animation feel more natural and snappy (removes laggy ending)
@cammace can you test this out? feel free to play with the variables to get the best possible UX.
> Tilt results in fling moving in a reverse direction

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
We used to perform these tests with local jvm unit tests, recent refactors made it impossible to mock out interactions with core. These tests were converted to instrumentation tests but suffered from a couple of crashes. I now think this is related to not having the following line in the test:
```
ViewUtils.checkViewIsDisplayed(R.id.mapView);
```
This line will make espresso wait until the view hierarchy is ready and the message queue is empty.
I will start multiple runs for this PR on our CI to determine is this is a valid fix.
> [android] - Reenable MapboxMapTest 

- platform/android/bitrise.yml
This path can be non existent due to core/android compile errors.
closes #7382
> Android CI create archivable path if non existent

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
Fixed a typo in the documentation comment for `MapboxMap.addImage()`.
> Fix typo in MapboxMap.addImage() documentation

- include/mbgl/map/backend.hpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/darwin/src/MGLStyle.mm
- platform/darwin/test/MGLStyleTests.mm
- src/mbgl/map/map.cpp
- src/mbgl/style/style.cpp
- test/style/style_layer.test.cpp
This brings in:
- [core] use raii to guard backend deactivation https://github.com/mapbox/mapbox-gl-native/commit/c76a933514e4e1514a58ac0e668b13eebab37794
- [core] guard against duplicate layer ids https://github.com/mapbox/mapbox-gl-native/commit/028db7febacf7d40598aff32653ae89599d0d0d2
- [ios, macos] handle duplicate layer error https://github.com/mapbox/mapbox-gl-native/commit/e9f101a52f626744991ee73c3ced9c48bc013a51
But not:
- [android] test duplicate layer id exception handling https://github.com/mapbox/mapbox-gl-native/commit/a32e62cb0f3a6d9654712ab93380b15db7b337aa
from https://github.com/mapbox/mapbox-gl-native/pull/7257 which landed in `master`
cc @1ec5 fyi @ivovandongen
> Cherry pick 7257 into iOS 3.4.0 release branch

- platform/ios/app/MBXViewController.m
This fixes a few bugs in our iosapp examples that were exposed by recent refinements to the APIs they use.
fyi @1ec5 @frederoni
> [ios] Fix iosapp runtime styling examples

- platform/ios/app/MBXViewController.m
Use `NSLocaleLanguageCode` instead of `-[NSLocale languageCode]`, which is newer than the minimum deployment target.
Fixes #7399.
/cc @boundsj
> Fix crash on launch in iosapp

- platform/android/MapboxGLAndroidSDK/proguard-rules.pro
- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
Closes https://github.com/mapbox/mapbox-gl-native/issues/7378
Closes #7313
There seemed to be an issue with obfuscation and JNI bindings, adding `-dontobfuscate` resolved #7378. I also added `-dontwarn okhttp3.**` which was being required in both testapp and demo app. Lastly I ported over the `mapbox-java` proguard rules.
> Fixed proguard rules

- Makefile
This updates the `make apackage` command with the latest gradle `3.2.1` syntax.
cc @kkaefer
> [android] - update gradle command line args for CI

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTintActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_my_location_dot_color.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettingsTest.java
Closes https://github.com/mapbox/mapbox-gl-native/issues/7116
Set the default user location color to be `mapbox_blue` and not transparent and allow for any color int value below 1 to tint user location foreground and background. We might be able to get rid of the color check `if (color < 1)`?
> Allows for setting the user location icon to transparent

- platform/ios/src/MGLMapView.mm
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7424
I'm not sure why we used a CATransaction for the callout view update. It does seem like, when it is called from a path initiated by CADisplayLink, there view is constantly hidden and shown again. If the transaction is removed, that does not occur.
cc @frederoni @1ec5
> [ios]] Remove transaction in callout view update

- platform/ios/src/MGLMapView.mm
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7342
cc @1ec5 @frederoni
> [ios] Fix dequeue view variable scope

- src/mbgl/style/source_impl.cpp
This ports https://github.com/mapbox/mapbox-gl-native/pull/7242/commits/2d323211af54499d5c822b8e45d7415bf92112f0 to the iOS 3.4.0 release branch.
cc @1ec5 @jfirebaugh
> [core] Port ensure a non-zero source tile cache size

- platform/android/CHANGELOG.md
The 4.2.0 final is currently being release and the `Changelog` needs to reflect this with information on what has changed.
> updated changelog for 4.2.0 release

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
Refs #6546, Closes #7447, this PR attempts to make our MapboxMap tests more robust by wrapping the executed code in a ViewAction. This ensures that we are calling MapboxMap methods from the application UI thread. I have done ~20 tests locally without seeing the exception from #7447, will setup some additional tests on CI to be :100: that this change fixes the issue.
Review @cammace 
cc @mapbox/android @jfirebaugh
> [android] - wrap mapbox map test in ViewActions

- Makefile
Running this command doesn't work since it's using `dalvikvm32` when trying to build a JAR file that contains 64 bit libraries. When switching to `dalvikvm64`, I'm getting stuck at this error:
```
CANNOT LINK EXECUTABLE "dalvikvm64": "/system/lib/liblog.so" is 32-bit instead of 64-bit
```
> `make run-android-core-test-arm-v8` doesn't work

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/TestConstants.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/MaxMinZoomActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/MapFragmentActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/SupportMapFragmentActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java
This PR changes the following items:
- move max/min zoom code from `MapboxMap.java` to `Transform.java`
- cleanup usage of double vs float
- renamed public API methods for parity reasons
> [android] - max/min refactor

- platform/ios/scripts/document.sh
This allows runners of `document.sh` to use their own custom, local theme. It uses the existing theme by default.
> Make theme configurable

- platform/darwin/src/MGLShape.h
- platform/darwin/src/MGLShape.mm
This change ensures that `-shapeWithData:encoding:error:` is only available on MGLShape in Swift.
Fixes #7456.
> Fix return type of MGLShape factory method

- platform/darwin/docs/theme/assets/css/jazzy.css.scss
- platform/darwin/docs/theme/templates/doc.mustache
- platform/darwin/docs/theme/templates/nav.mustache
On category pages, the current category is highlighted in the navigation list:
On topic pages, the current topic is highlighted:
This effect assumes that categories and topics are named uniquely. The only thing that would prevent that from happening would be a guide named identically to a category or topic, which we can easily avoid.
@mayagao, I just reused the navigation bar’s background color for the highlight. Feel free to improve the style.
> Highlight current topic in documentation

- Makefile
Updated make targets with:
- checkstyle
- spoon
- aws device farm
cc @cammace
> [android] - make targets for checkstyle, spoon and AWS device farm

- platform/darwin/src/MGLStyleValue.h
- platform/darwin/src/MGLStyleValue.mm
- platform/darwin/src/MGLStyleValue_Private.h
- platform/darwin/test/MGLStyleValueTests.swift
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7421
cc @1ec5
> [ios, macos] Rename base to interpolationBase

- Makefile
When building the core tests or calling `make android`, we are building both the wear module as the phone module. Only the phone module is required in normal situations and building them both is unnecessary.
cc @cammace @kkaefer
> [android] - only build phone module

- platform/android/MapboxGLAndroidSDK/build.gradle
Upgrade okhttp from 3.4.1 to 3.5.0 (released december the 1st, 2016)
> Upgrade okhttp to 3.5.0

- platform/darwin/src/MGLOpenGLStyleLayer.h
- platform/darwin/src/MGLOpenGLStyleLayer.mm
Removed the `perspectiveSkew` field from the `MGLStyleLayerDrawingContext` struct in anticipation of #7444. It was always set to 1.5, so I don’t think anyone would’ve been using it anyways.
> Omit perspectiveSkew from drawing context struct

- platform/darwin/docs/theme/assets/css/jazzy.css.scss
- platform/darwin/docs/theme/templates/nav.mustache
Italicize protocols and abstract classes in the generated documentation’s navigation sidebar. This treatment hopefully gives the concrete classes more prominence while keeping concrete classes together with their abstract superclasses:
This visual distinction doesn’t necessarily preclude the “Protocols and Abstract Classes” and “Style Layers (Abstract)” categories being added in #7338, although it may make them less necessary. (I do agree that we need to reorganize the categories regardless.) I think keeping concrete classes together with their abstract superclasses in navigation is important, because classes very often inherit initializers and properties from their superclasses. Until realm/jazzy#708 lands, it’s a bit difficult otherwise to navigate from a class to its superclass.
I …
> Indicate protocols, abstract classes in documentation navigation

- include/mbgl/style/sources/geojson_source.hpp
- include/mbgl/style/sources/raster_source.hpp
- include/mbgl/style/sources/vector_source.hpp
- platform/darwin/src/MGLRasterSource.mm
- platform/darwin/src/MGLTileSource.h
- platform/darwin/src/MGLTileSource.mm
- platform/darwin/src/MGLVectorSource.mm
- platform/macos/app/MGLVectorSource+MBXAdditions.h
- platform/macos/app/MGLVectorSource+MBXAdditions.m
- platform/macos/app/MapDocument.m
- platform/macos/macos.xcodeproj/project.pbxproj
- src/mbgl/style/sources/geojson_source.cpp
- src/mbgl/style/sources/geojson_source_impl.cpp
- src/mbgl/style/sources/geojson_source_impl.hpp
- src/mbgl/style/sources/raster_source.cpp
- src/mbgl/style/sources/vector_source.cpp
Added a method to MGLTileSource (and thus MGLRasterSource and MGLVectorSource) that returns the TileJSON URL, if any, that was used to initialize the source. #7377 removed this method, but this PR adds it back in; this time, it works for sources obtained via `-[MGLStyle layerWithIdentifier:]` too.
The “Labels In” feature in macosapp now avoids localizing sources other than Mapbox Streets v6–7, demonstrating how tantalizingly close we are to implementing #7031.
Working towards #6584. Depends on #7377.
@ivovandongen to review the core parts; @frederoni to review the iOS/macOS parts.
> URL accessor for raster and vector sources

- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java
- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
> [android] - update lost to 2.0.0, gradle cleanup

- src/mbgl/util/mapbox.cpp
- src/mbgl/util/url.cpp
- src/mbgl/util/url.hpp
- test/util/mapbox.test.cpp
- test/util/url.test.cpp
An attempt at https://github.com/mapbox/mapbox-gl-native/issues/6183.
> Refactor URL parsing code

- platform/darwin/src/MGLCircleStyleLayer.h
- platform/darwin/src/MGLFillStyleLayer.h
- platform/darwin/src/MGLLineStyleLayer.h
- platform/darwin/src/MGLRasterSource.h
- platform/darwin/src/MGLRasterStyleLayer.h
- platform/darwin/src/MGLShapeSource.h
- platform/darwin/src/MGLSource.h
- platform/darwin/src/MGLStyleLayer.h.ejs
- platform/darwin/src/MGLSymbolStyleLayer.h
- platform/darwin/src/MGLVectorSource.h
- platform/darwin/src/MGLVectorStyleLayer.h
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/jazzy.yml
- platform/ios/scripts/add-examples-to-docs.js
- platform/ios/scripts/document.sh
- platform/ios/test/MBLDocumentationExampleTests.swift
- platform/ios/test/MGLDocumentationExampleTests.swift
Examples for:
* Sources
* `MGLGeoJSONSource`
* `MGLVectorSource`
* `MGLRasterSource`
* Layers
* `MGLCircleStyleLayer`
* `MGLFillStyleLayer`
* `MGLLineStyleLayer`
* `MGLSymbolStyleLayer`
* `MGLVectorStyleLayer.predicate`
Swift 3 for now. We can add Objective-C inline or a link to the respective examples on http://mapbox.com/ios-sdk/examples later.
> [ios] Add inline examples in documentation

- platform/ios/jazzy.yml
- platform/macos/jazzy.yml
* Move guides front-and-center (to be expanded out to include more guides)
* Organize shape classes heirarchically for clarity
* Clarify features, sources, and layers as related to map styling (as opposed to annotations)
> [ios] Reorder classes in jazzy docs sidebar

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/MapFragmentUtils.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/SupportMapFragmentActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DoubleMapActivity.java
I noticed that DoubleMapActivity in the test app wasn't working correctly, this cascaded in fixing up some fragment logic and decoupling duplicated code from it. Review @cammace
> [android] - harden MapboxMapOptions, decouple fragment logic

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
A call to `getCameraPosition` automatically resulted in invalidating the camera position before https://github.com/mapbox/mapbox-gl-native/pull/7189 . To limit jni calls we removed this but didn't update the part in code where we actually needed to invalidate the position. This PR solves that.
> [android] - update components  with latest camera values

- CMakeLists.txt
- cmake/core.cmake
- package.json
- src/mbgl/layout/symbol_layout.cpp
> [core] Polylabel-based "pole of inaccessibility" symbol placement

- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- platform/macos/macos.xcodeproj/project.pbxproj
- platform/macos/sdk/zh-Hans.lproj/Localizable.strings
The macOS SDK adds only two substantive localizable strings on top of the localization that @YunjieLi already contributed to the iOS SDK in #7316.
> Add Simplified Chinese localization

- include/mbgl/style/layers/custom_layer.hpp
- package.json
- platform/darwin/src/MGLGeometry.mm
- platform/darwin/src/MGLOpenGLStyleLayer.h
- platform/darwin/src/MGLOpenGLStyleLayer.mm
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/programs/line_program.cpp
- src/mbgl/programs/line_program.hpp
- src/mbgl/programs/symbol_program.cpp
- src/mbgl/renderer/painter_circle.cpp
- src/mbgl/renderer/painter_line.cpp
- src/mbgl/style/layers/custom_layer_impl.cpp
- test/map/transform.test.cpp
- test/util/tile_cover.test.cpp
fix #7439
ports https://github.com/mapbox/mapbox-gl-js/pull/3790
> This cleans up a bunch of matrix and antialiasing code.
> 
> - removes the confusing altitude and replaces it with fov
> - fixes text blurriness at non-default FOVs
> - removes the hack added in #3740 and adds a different fix
> - makes pitched line antialiasing clearer and removes lineStretch and lineAntialiasingMatrix
TODO:
I removed `altitude` from `CustomLayerRenderParameters` and added `fieldOfView`. Is this considered an external interface / breaking change? Should I remove it from the platform bindings as well? Or should I calculate it and add it? The old altitude value is just `0.5 / tan(fov / 2) * height`
@jfirebaugh
> [core] port matrix and antialiasing cleanup

- platform/darwin/src/MGLStyleValue.h
Corrected several issues with `MGLStyleValue`’s inline docs:
- Moved the enumerations responsibility to `NSValue` (from `NSNumber`).
- Corrected the names of `NSEdgeInsets` and `UIEdgeInsets`.
- ~~Changed list formatting to Markdown, as jazzy wasn’t parsing code ticks inside HTML tags.~~
- Changed the backticks to `<code>` blocks, which parse correctly in jazzy and are the same in appearance as the Markdown version.
Now in jazzy:
Note that Xcode’s Quick Help now fails to add linebreaks to this list:
> Correct formatting and typos in MGLStyleValue documentation

- platform/darwin/src/MGLStyle.h
- platform/darwin/src/MGLStyle.mm
- platform/darwin/test/MGLStyleTests.mm
Fixed #7474 Reverse MGLStyle.layers.
> Reversed MGLStyle.layers

- platform/darwin/src/MGLFeature.mm
- platform/darwin/src/MGLFeature_Private.h
- platform/darwin/src/MGLMultiPoint.mm
- platform/darwin/src/MGLPointAnnotation.mm
- platform/darwin/src/MGLPointCollection.mm
- platform/darwin/src/MGLPolygon.mm
- platform/darwin/src/MGLPolyline.mm
- platform/darwin/src/MGLShape.h
- platform/darwin/src/MGLShape.mm
- platform/darwin/src/MGLShapeCollection.mm
- platform/darwin/src/MGLShape_Private.h
- platform/darwin/src/NSArray+MGLAdditions.h
- platform/darwin/src/NSArray+MGLAdditions.mm
- platform/darwin/src/NSCoder+MGLAdditions.h
- platform/darwin/src/NSCoder+MGLAdditions.mm
- platform/darwin/test/MGLCodingTests.m
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLAnnotationImage.h
- platform/ios/src/MGLAnnotationImage.m
- platform/ios/src/MGLAnnotationView.h
- platform/ios/src/MGLAnnotationView.mm
- platform/ios/src/MGLUserLocation.h
- platform/ios/src/MGLUserLocation.m
- platform/macos/macos.xcodeproj/project.pbxproj
- platform/macos/src/MGLAnnotationImage.h
- platform/macos/src/MGLAnnotationImage.m
This PR fixes #6200 
All feature and annotation classes now conform to NSSecureCoding which means they can be serialized and deserialized. This is useful for [UIStateRestoring](https://developer.apple.com/reference/uikit/uistaterestoring) among other things.
@incanus @1ec5 👀
> Make features and annotations conform to NSSecureCoding

- platform/darwin/src/MGLTileSource.h
Pithy example, external reference link, and clarification. 
As best I can tell, only the first template string is ever used (cf. [`offline_download.cpp`](https://github.com/mapbox/mapbox-gl-native/blob/b57b3b4bf6841be5604c54c94db6b9d822d985e1/platform/default/mbgl/storage/offline_download.cpp#L246) & [`tile_loader_impl.hpp`](https://github.com/mapbox/mapbox-gl-native/blob/b57b3b4bf6841be5604c54c94db6b9d822d985e1/src/mbgl/tile/tile_loader_impl.hpp#L20))
/cc @1ec5 @boundsj @jfirebaugh
> Expand documentation on MGLTileSource URL templates

- .gitmodules
- CMakeLists.txt
- cmake/shaders.cmake
- package.json
> [build] Use a submodule for mapbox-gl-js rather than an npm dependency

- platform/darwin/src/NSExpression+MGLAdditions.mm
- platform/darwin/test/MGLExpressionTests.mm
Convert NSNull into an `mbgl::NullValue`. This latent bug was exposed by #7377, which sent MGLShapeSource through the same code path used to convert MGLVectorSource predicates into mbgl style filters.
Fixes #7467.
> Fix null expression crash

- platform/darwin/src/MGLRasterSource.mm
- platform/darwin/src/MGLShapeSource.mm
- platform/darwin/src/MGLStyleLayer_Private.h
- platform/darwin/src/MGLVectorSource.mm
- platform/ios/benchmark/MBXBenchViewController.mm
- platform/ios/src/MGLMapView_Private.h
- platform/macos/src/MGLMapView_Private.h
Fixed a stale include in iosbench. MGLMapView_Private.h forward-declares `mbgl::Map` instead of including mbgl.hpp, which iosbench has no access to.
> Fix iosbench build

- platform/darwin/src/MGLOfflineStorage.h
Attempts to address a common question about why removing an offline pack does not result in the immediate deletion of its associated resources — see #7521, etc.
Text adapted from: https://www.mapbox.com/help/mobile-offline/#removing-offline-regions
> Document that offline pack resource removal is not guaranteed

- platform/darwin/src/MGLCircleStyleLayer.mm
- platform/darwin/src/MGLFillStyleLayer.mm
- platform/darwin/src/MGLLineStyleLayer.mm
- platform/darwin/src/MGLRasterStyleLayer.mm
- platform/darwin/src/MGLStyleLayer.mm.ejs
- platform/darwin/src/MGLSymbolStyleLayer.mm
Fixes #7557 
This PR adds a sourceIdentifier getter for all concrete subclasses of MGLForegroundStyleLayer.
> Implement MGLForegroundStyleLayer.sourceIdentifier

- platform/darwin/docs/guides/For Style Authors.md
- platform/darwin/docs/guides/For Style Authors.md.ejs
- platform/darwin/docs/guides/Working with GeoJSON Data.md
- platform/darwin/scripts/generate-style-code.js
- platform/darwin/src/MGLShapeSource.h
- platform/darwin/src/MGLTileSource.h
- platform/ios/docs/guides/For Style Authors.md
- platform/ios/docs/guides/Runtime Styling.md
- platform/ios/docs/guides/Working with Mapbox Studio.md
- platform/ios/jazzy.yml
- platform/ios/scripts/document.sh
- platform/macos/docs/guides/For Style Authors.md
- platform/macos/docs/guides/Info.plist Keys.md
- platform/macos/jazzy.yml
- platform/macos/scripts/document.sh
Added two guides to the jazzy documentation:
* “Working with GeoJSON Data” maps GeoJSON concepts and types to the runtime styling API.
* “Information for Style Authors” points out a number of tips for designing a style appropriate for an iOS or macOS application and also maps style JSON types to the runtime styling API to help Mapbox Studio users. This document is generated by `make style-code-darwin` just like the rest of the runtime styling API. I avoided talking in great detail about Studio or the runtime styling API to avoid overlapping with #7488.
~~These two guides are shared between the iOS and macOS docsets. This means the iOS SDK documentation will include some language specific to macOS and vice versa. I think this is fine, given that Apple’s own guides do the same thing.~~ The …
> Guides for style and GeoJSON authors

- platform/macos/scripts/document.sh
Updated changelog parsing code in the documentation generation script to handle subheadings within the current release’s release notes. Previously, the “Changes in version …” section stopped at the first subheading. The corresponding iOS code was updated in #5552.
> Include subheadings in release notes

- platform/qt/include/qmapboxgl.hpp
- platform/qt/src/qmapboxgl.cpp
Useful for redirecting to a cache server or debugging.
> [Qt] Expose method for changing the base API URL

- platform/darwin/src/MGLStyle.h
- platform/darwin/src/MGLStyle.mm
MGLStyle’s `sources` and `layers` properties are now immutable collections but remain writable. Now Swift developers will see `layers`’ type as `[MGLStyleLayer]`, not `NSMutableArray`. If you need a mutable array of layers, use `-mutableArrayValueForKey:`.
Fixes #7459.
/cc @bsudekum
> Immutable source and style layer collections

- package.json
- platform/default/bidi.cpp
- platform/qt/src/bidi.cpp
- src/mbgl/text/bidi.hpp
- src/mbgl/text/glyph_set.cpp
- src/mbgl/text/glyph_set.hpp
- src/mbgl/util/i18n.cpp
Porting newline-handling changes from gl-js -- biggest change is the "raggedness minimizing" line breaking algorithm from https://github.com/mapbox/mapbox-gl-js/pull/3743.
> Fix issue #7253: port gl-js line breaking behavior

- platform/macos/app/Base.lproj/MapDocument.xib
- platform/macos/app/MGLStyle+MBXAdditions.h
- platform/macos/app/MGLStyle+MBXAdditions.m
- platform/macos/app/MapDocument.m
- platform/macos/macos.xcodeproj/project.pbxproj
#7484 reversed the `MGLStyle.layers` property to arrange the layers from back to front. In a vertical list, however, the layers should always be arranged from front to back, as if the user is viewing a cross section of the style. This change implements a `reversedLayers` property on MGLStyle via a category specific to macosapp. (Neither SDK is affected.)
Depends on #7539.
> Arrange layers top to bottom in sidebar

- src/mbgl/map/map.cpp
- src/mbgl/map/update.hpp
Update only when, and just prior to, rendering, giving no opportunity to interleave unexpected state changes. Abandon the use of `AsyncTask` in continuous mode; instead call `backend.invalidate()` whenever something occurs that needs to trigger a update/render, relying on the platform implementation of invalidate to perform coalescing.
This fixes #7040.
/cc @jfirebaugh @pveugen
> Unify update and render into a single step

- platform/ios/src/MGLMapView.mm
Views that are added outside of the viewport do not always have an instantiated presentationLayer. Attempting to use a nil presentationLayer to move a view offscreen resulted in the view being pinned to the left side of the view port (at x == 0).
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7558
> [ios] Only use non nil presentationLayers to adjust annotation views

- platform/darwin/src/MGLShapeCollection.h
- platform/darwin/src/MGLShapeCollection.mm
- platform/darwin/test/MGLFeatureTests.mm
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7628
> Allow creation of shape collections with no shapes

- platform/darwin/src/MGLStyle.h
- platform/ios/app/MBXViewController.m
Sources and layers added outside of mapView:didFinishLoadingStyle: and mapViewDidFinishLoadingMap: are not guaranteed to appear since the map may not be fully loaded and ready to accept new sources and layers.
This also fixes a compiler warning in iosapp.
ref https://github.com/mapbox/mapbox-gl-native/issues/7492
> Document requirement about adding sources and layers

- platform/darwin/test/MGLShapeSourceTests.mm
- src/mbgl/style/sources/geojson_source_impl.cpp
Ignore empty feature collections or non–feature collections for the purposes of deciding whether to cluster or tile the GeoJSON. A source’s clustering option can only be set when the source is constructed, but `setGeoJSON()` enables the developer to swap a clusterable feature for an unclusterable geometry and back.
Added iOS/macOS unit tests of creating shape sources with unclusterable shapes. The second of these tests depends on #7632 to pass.
Fixes #7622.
/cc @boundsj
> Avoid clustering unclusterable GeoJSON

- platform/darwin/src/MGLShape.h
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7614
> [ios, macos] Document that MGLShape can deserialize GeoJSON

- platform/darwin/docs/guides/For Style Authors.md.ejs
- platform/darwin/scripts/generate-style-code.js
- platform/darwin/src/MGLBackgroundStyleLayer.h
- platform/darwin/src/MGLCircleStyleLayer.h
- platform/darwin/src/MGLFillStyleLayer.h
- platform/darwin/src/MGLLineStyleLayer.h
- platform/darwin/src/MGLSymbolStyleLayer.h
- platform/darwin/src/NSValue+MGLStyleAttributeAdditions.mm
- platform/ios/docs/guides/For Style Authors.md
- platform/macos/docs/guides/For Style Authors.md
On macOS, `CGVector` is now interpreted as extending upward instead of downward, for consistency with the [predominant screen origin](https://developer.apple.com/library/content/documentation/General/Conceptual/Devpedia-CocoaApp/CoordinateSystem.html) on that platform. It is possible to flip the screen coordinate system by setting `NSView.flipped`. However, I’d rather not support that decidedly less common setup, since that would require each MGLStyleLayer instance to maintain a backpointer to MGLMapView.
Documentation comments for color-, offset-, and edge insets–typed properties are clearer about their types. In some cases, this meant some additional conditional compilation. There are no longer any references to the `MGLColor` macro within the style layer headers.
This PR goes in the …
> Flip CGVector-typed properties on macOS

- platform/qt/app/mapwindow.cpp
- platform/qt/include/qmapboxgl.hpp
- platform/qt/src/qmapboxgl.cpp
Add even more docs to QMapboxGL.
> [Qt] Add more docs

- platform/qt/qt.cmake
Use mason platform instead of CMake host, because the target won't always be the same arch as the host.
> [Qt] Fix cross compilation on OSX

- platform/darwin/scripts/update-examples.js
- platform/darwin/src/MGLShape.h
- platform/darwin/test/MGLDocumentationExampleTests.swift
Added an example of deserializing an MGLShape from a GeoJSON file.
/ref https://github.com/mapbox/mapbox-gl-native/issues/7622#issuecomment-271118434
/cc @nitrag
> Add MGLShape from GeoJSON example

- package.json
- platform/node/src/node_map.cpp
- platform/node/src/node_map.hpp
- platform/node/test/js/map.test.js
- platform/node/test/suite_implementation.js
This exposes the `addImage` and `removeImage` functions to platform: node. Example usage:
```js
map.addImage('myImageName', {
imageBuffer: <Premultiplied image buffer>,
height: 40,
width: 40
});
```
The developer then would add a corresponding layer, `myImageName` to style the image.
@jfirebaugh I'm not seeing tests for other similar APIs like `addLayer`. How should this be tested?
> Add addImage, removeImage API

- cloudformation/travis.template
Since we've moved to npm + orgs (@mapbox/package), we'll need to update the allowed s3 publish location.
/cc @lucaswoj
> Allow new s3 publish location

- platform/darwin/src/NSString+MGLAdditions.h
- platform/darwin/src/NSString+MGLAdditions.m
- platform/darwin/test/MGLNSStringAdditionsTests.m
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLMapView.mm
- platform/macos/macos.xcodeproj/project.pbxproj
Replaced `-[NSString capitalizedStringWithLocale:]` with a hand-rolled title-casing method that relies on NSLinguisticTagger to capitalize the right words.
Fixes #7409.
> Title case attribution buttons

- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/directions/DirectionsActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/geocoding/GeocoderActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/navigation/LocationPickerActivity.java
Now that MAS 2.0.0 is split up into smaller modules via https://github.com/mapbox/mapbox-java/pull/251 we can use its submodules to reduce the SDK method count. This PR addresses that.
As a collateral, some package names have changed, this is also fixed with this PR. No code is otherwise changed.
/cc: @mapbox/android
> Use smaller package of MAS to reduce method count

- cmake/test-files.cmake
- src/mbgl/geometry/feature_index.cpp
- src/mbgl/geometry/feature_index.hpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/layout/symbol_layout.hpp
- src/mbgl/style/group_by_layout.cpp
- src/mbgl/style/group_by_layout.hpp
- src/mbgl/style/layers/symbol_layer_impl.cpp
- src/mbgl/style/layers/symbol_layer_impl.hpp
- src/mbgl/text/collision_tile.cpp
- src/mbgl/text/collision_tile.hpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/geometry_tile_worker.cpp
- test/src/mbgl/test/stub_tile_observer.hpp
- test/style/group_by_layout.test.cpp
- test/tile/geojson_tile.test.cpp
- test/tile/vector_tile.test.cpp
Discard prior symbol buckets only when new symbol buckets became available, in order to eliminate flickering when tiles are refreshed. Plus followup refactor.
Fixes #7615
> [core] Fix symbol flickering during tile reload

- Makefile
This PR enables to run one specific unit or instrumentation test from make:
```bash
make run-android-unit-test-com.mapbox.mapboxsdk.style.layers.FilterTest.*
make run-android-ui-test-com.mapbox.mapboxsdk.testapp.camera.CameraEaseTest
```
Closes #7510 
> [android] - add filter to unit and instrumentation tests

- package.json
- platform/node/CHANGELOG.md
Although we initially thought we could simply re-run the publish binary travis test, it looks like node-pre-gyp is complaining:
```
de-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@4.7.2 | darwin | x64
node-pre-gyp info package packing /Users/vagrant/git/lib
node-pre-gyp info package packing /Users/vagrant/git/lib/mapbox-gl-native.node
node-pre-gyp info package Binary staged at "build/stage/@mapbox/mapbox-gl-native/v3.4.3/node-v46-darwin-x64.tar.gz"
node-pre-gyp info publish Detecting s3 credentials
node-pre-gyp info publish Authenticating with s3
node-pre-gyp info publish Checking for existing binary at https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.4.3/node-v46-darwin-x64.tar.gz
node-pre-gyp …
```
> Update version number and changelog

- platform/macos/src/MGLMapView.mm
An implementation of `-validateMenuItem:` should rarely call the superclass implementation.
Tested that all the View and Help menu items and their keyboard shortcuts continue to work.
Fixes #7623.
/cc @frederoni
> Fix exception on certain keyboard shortcuts

- platform/darwin/src/MGLNetworkConfiguration.m
- platform/darwin/src/MGLRasterSource.mm
- platform/darwin/src/MGLShape.mm
- platform/ios/src/MGLAnnotationImage.m
- platform/macos/src/MGLAnnotationImage.m
- platform/macos/src/NSImage+MGLAdditions.mm
This PR fixes the following static analyzer warnings, which were introduced in #6709, #7377, #6559, and #7300:
```
/path/to/mapbox-gl-native/platform/darwin/src/MGLNetworkConfiguration.m:16:9: Null is returned from a method that is expected to return a non-null value
/path/to/mapbox-gl-native/platform/darwin/src/MGLRasterSource.mm:63:23: Function call argument is an uninitialized value (within a call to 'make_unique')
/path/to/mapbox-gl-native/platform/darwin/src/MGLShape.mm:98:10: The left expression of the compound assignment is an uninitialized value. The computed value will also be garbage
/path/to/mapbox-gl-native/platform/ios/src/MGLAnnotationImage.m:60:54: Null passed to a callee that requires a non-null 1st parameter
/path/to/mapbox-gl-native/platform/ios/src/MGLAnnotationImage.m:6 …
```
> Fix miscellaneous static analyzer warnings

- platform/darwin/src/MGLCircleStyleLayer.h
- platform/darwin/src/MGLFillStyleLayer.h
- platform/darwin/src/MGLLineStyleLayer.h
- platform/darwin/src/MGLRasterSource.h
- platform/darwin/src/MGLRasterStyleLayer.h
- platform/darwin/src/MGLShapeSource.h
- platform/darwin/src/MGLSymbolStyleLayer.h
- platform/darwin/src/MGLVectorSource.h
- platform/darwin/src/MGLVectorStyleLayer.h
- platform/darwin/test/MGLDocumentationExampleTests.swift
- platform/darwin/test/MGLStyleLayerTests.h
- platform/darwin/test/MGLStyleLayerTests.m
- platform/darwin/test/MGLStyleLayerTests.xib
- platform/darwin/test/MGLStyleTests.mm
- platform/ios/src/MGLMapView.h
- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.h
- platform/macos/src/MGLMapView.mm
MGLMapView’s `style` property is now nullable (optional in Swift) and is set to `nil` while the style loads and in the event that the style has failed to load. The `styleURL` property remains null-resettable (implicitly-unwrapped-optional in Swift) as before.
Essentially, the API as it exists has a trap: the developer is tempted to have runtime styling code run synchronously after initializing the map view, for example in `-viewDidLoad`. Unfortunately, any runtime styling API operations they perform while the style loads [gets wiped out](https://github.com/mapbox/mapbox-gl-native/blob/5da85bafd8266ebea0c1e48e70f6e93fbbfbeecd/src/mbgl/style/style.cpp#L100-L101). Instead, they must wait until the style has finished loading, in `-[MGLMapViewDelegate mapView:didFinishLoadingStyle:]`.
We want …
> Make MGLMapView.style property nullable

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
Solves the issue of triggering a onFling after a scale gesture has ended.
Closes #7666
> [android] - avoid triggering a fling gesture after a scale gesture.

- test/style/functions.test.cpp
Fixes the following error:
```
../../../mason_packages/linux-x86_64/gtest/1.7.0/include/gtest/internal/gtest-internal.h:133:55: error: converting ‘false’ to pointer type for argument 1 of ‘char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)’ [-Werror=conversion-null]
(sizeof(::testing::internal::IsNullLiteralHelper(x)) == 1)
^
```
Related upstream issues:
https://github.com/google/googletest/issues/458
https://github.com/google/googletest/issues/322
Not seen in CI because of https://github.com/mapbox/mapbox-gl-native/blob/0ef52d7f7ceee670e8961e811364d215fde7e980/scripts/travis_setup.sh#L17-L22
> [tests] Sidestep a gcc or gtest bug

- platform/ios/docs/guides/Adding Points to a Map.md
- platform/ios/docs/guides/Runtime Styling.md
- platform/ios/docs/guides/Working with Mapbox Studio.md
- Clarify and simplify some parts of the annotations guide.
- Add more links to examples, where appropriate.
- Remove support email link.
- Code ticks around `UIView`.
- Smart quotes.
> [ios] Copy-edit guides

- platform/darwin/test/MGLStyleLayerTests.m
This change fixes the spurious integration test failures in `-[MGL*LayerTests testPropertyNames]` seemingly introduced in #7664 by paring the tests back. They no longer test integration within a real window or view hierarchy, which is always risky business in the supposedly headless environment of XCTest. Integration tests involving MGLMapView are more properly the domain of XCUITest (#4837) anyhow.
> Run style layer tests headlessly

- platform/ios/app/MBXCustomCalloutView.h
- platform/ios/app/MBXCustomCalloutView.m
- platform/ios/app/MBXViewController.m
- platform/ios/src/MGLCalloutView.h
- platform/ios/src/MGLCompactCalloutView.m
- platform/ios/src/MGLMapView.mm
This proposal makes the `MGLCalloutView` a bit more versatile by adding an `anchoredToAnnotation` and a `dismissesAutomatically` property. It also fixes issues like #7483 by falling back to the same behavior as in 3.4.0 beta 4 by default.
/cc @friedbunny @1ec5 @boundsj
> Optional positioning and stickiness for callout view

- platform/ios/src/MGLAPIClient.h
- platform/ios/src/MGLAPIClient.m
- platform/ios/src/MGLMapboxEvents.m
This flushes the cache just before pausing so that data collected before the pause is not thrown away. It also refactors event creation to avoid possible nil value inserts into dictionaries
and adds a small optimization to avoid creating immutable dictionaries to help create mutable ones.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7578
> Flush telemetry cache when data collection is paused

- platform/darwin/docs/guides/Working with GeoJSON Data.md
- platform/darwin/src/MGLFeature.mm
- platform/darwin/src/MGLShapeSource.h
- platform/darwin/src/MGLShapeSource.mm
- platform/darwin/test/MGLDocumentationExampleTests.swift
- platform/darwin/test/MGLShapeSourceTests.mm
- platform/ios/app/MBXViewController.m
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7453
This adds two new convenience initializers to MGLShapeSource:
- `-initWithIdentifier:features:options:` takes an array of shape objects that conform to MGLFeature, inserts them in a shape collection feature, and creates a source with that shape. 
- `-initWithIdentifier:shapes:options:` does the same but with concrete MGLShape objects that get added to a shape collection.
Although both are technically convenience initializers, developers will most often want to use -`initWithIdentifier:features:options:` since features objects unlock key runtime styling functionality. So, the inline example has been updated to demonstrate `MGLShapeSource` usage with `-initWithIdentifier:features:options:`
The type system will help ensure that …
> Add convenience initializers to shape source

- platform/darwin/test/MGLStyleLayerTests.m
- platform/darwin/test/MGLStyleTests.mm
This PR is an attempt to fix macOS test failures that occur only in CI while making iOS tests potentially more reliable as well.
Removed UIViewController from MGLStyleLayerTests on iOS, because we aren’t really testing integration at that level. Switched to delegate-based expectation fulfillment for both MGLStyleLayerTests and MGLStyleTests, conditionalized on whether the style has already loaded, to avoid race conditions that bleed into other tests.
> Make style-related tests more robust

- platform/darwin/docs/guides/For Style Authors.md.ejs
- platform/darwin/docs/guides/Working with GeoJSON Data.md
- platform/ios/docs/guides/For Style Authors.md
- platform/macos/docs/guides/For Style Authors.md
For numeric style attributes, the generic argument to MGLStyleValue is technically an NSNumber in Swift, but you don’t need to use NSNumber `*Value` properties with it:
```swift
layer.circleOpacity = MGLStyleValue(rawValue: 0.7)
let value = layer.circleOpacity as! MGLStyleConstantValue
assert(Float(value) == 0.7)
```
This PR replaces NSNumber properties with standard Swift types in the Swift column of type correspondence tables. I think we need to do this, because I see a lot of instances where developers unnecessarily write, for instance:
```swift
layer.circleOpacity = MGLStyleValue(rawValue: NSNumber(value: 0.7))
```
There’s a risk that the developer would read this and think they can write the following:
```swift
let opacity = layer.circleOpacity as! MGLStyleConstantValue
let …
```
> Document simpler types for style values in Swift

- platform/darwin/src/MGLShapeSource.h
Like #7683, but based on the release-ios-v3.4.0 branch.
/cc @nitrag
> Note that MGLShapeSource.shape must be set on main thread

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
This PR attempts to improve our fling gesture with:
- ignore small fling gestures that can occur after other gestures (see https://github.com/mapbox/mapbox-gl-native/issues/7536 for more information)
- calculate animation duration based on the velocity of the fling see https://github.com/mapbox/mapbox-gl-native/issues/7549#issuecomment-271207473.
This solution relies on https://github.com/mapbox/mapbox-gl-native/pull/7675 getting merged first.
> [android] - improved fling gesture 

- platform/darwin/docs/guides/Working with GeoJSON Data.md
jazzy kebab-cases anchors in guides.
> Fix link in “Working with GeoJSON Data” guide

- platform/ios/CHANGELOG.md
- platform/ios/app/MBXViewController.m
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLMapViewDelegate.h
- platform/macos/CHANGELOG.md
- platform/macos/app/MapDocument.m
- platform/macos/src/MGLMapView.mm
- platform/macos/src/MGLMapViewDelegate.h
Fixes #7524 by reverting #6706.
> Revert alphaForShapeAnnotation delegate method deprecation

- platform/darwin/src/MGLAttributionInfo.mm
The inline stylesheet used when converting an attribution HTML string to an attributed string now specifies the system font as the default font. It still isn’t clear to me why macosapp has been defaulting to the system font, but it makes sense to me that the default default font would be Times without this change. This change makes use of WebKit’s proprietary `-apple-system` keyword, which [Apple recommends](https://webkit.org/blog/3709/using-the-system-font-in-web-content/) for this purpose.
There is still a slight difference between macosapp and an application outside macos.xcworkspace, but I think the two results are close enough:
Fixes #7722.
/cc @frederoni @friedbunny
> Default to system font in attribution titles

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
Closes #7449  
This PR adds safe guards to all our core invocations to make sure the native code doesn't crash while we destroy the mapobject. This behaviour can be produced if we define a asynchronous callback that get invoked during map destruction (eg. Animation callbacks/Handlers/etc.).
I have been experimenting with different approaches but these didn't always cover all the different use-cases. For now I'm settling with these safeguards to be able to ship in near future. Will revisit this once we have made more progress on refactor project that will move ownership/responsibility and thus making this more manageable.  
@cammace this resolves the crash you have been seeing on AnimatedMarkerActivity.
> Safe guard destroying NativeMapview from async invocation

- platform/android/bitrise.yml
This PR improves our CI integration by notifying the android team when releasing nightly snapshots is failing. This should help discover issues as #7640 faster.
> [android] - notify team when nightly snapshot build fails

- src/mbgl/util/mapbox.cpp
- src/mbgl/util/url.cpp
- test/util/url.test.cpp
Our URL class added in https://github.com/mapbox/mapbox-gl-native/pull/7464 does not include the leading `/` of the pathname. @jfirebaugh notes in https://github.com/mapbox/mapbox-gl-native/pull/7485#discussion_r96322459 that this is inconsistent with the definitions of path elsewhere, e.g. [`window.Location`](https://developer.mozilla.org/en-US/docs/Web/API/Location), [node](https://nodejs.org/api/url.html#url_urlobject_pathname), [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.3).
> Include leading / in URL path

- src/mbgl/style/source_impl.cpp
- src/mbgl/tile/tile_id.hpp
- src/mbgl/util/tile_cover.cpp
Follow-up to #7737.
Integration query tests as well as unit tests in `test/tile/tile_id.test.cpp` and `test/util/tile_cover.cpp` should cover this.
> [core] Prefer std::tie usage

- scripts/travis_setup.sh
Followup per https://github.com/mapbox/mapbox-gl-native/pull/7691#pullrequestreview-16557411
> [linux] No need for CXXABI suffix for mesa

- cmake/test-files.cmake
- src/mbgl/style/paint_property.hpp
- test/style/paint_property.test.cpp
> [core] Fix calculation of delayed transitions

- platform/darwin/src/MGLMapCamera.h
- platform/darwin/src/MGLShapeCollection.h
- platform/darwin/src/MGLStyleLayer.h
- platform/ios/src/MGLMapView.h
- Corrected typos in MGLMapView.h and MGLMapCamera.h
- Removed line from MGLShapeCollection.h
- Inserted a reminder in MGLStyleLayer.h initializer description to remind user not to initialize MGLStyleLayer directly
> Typo fixes, added line to MGLStyleLayer initializer description

- CMakeLists.txt
With the previous command, the second time it would run generated a node_modules symlink inside the top-level node_modules directory.
> [build] Avoid creating a recursively symlinked node_modules

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/Style.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
- platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_scroll_by.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/TrackingSettingsTest.java
Closes #7575, finalising public api for 5.0.0, cleanup deprecation
- remove deprecated emerald
- remove deprecation annotation for setStyle
- remove deprecated dismiss tracking on gesture
This PR doesn't include the removal of TextureView. 
As proposed [here](https://github.com/mapbox/mapbox-gl-native/issues/7575#issuecomment-270070568), I'm going to pick this up with https://github.com/mapbox/mapbox-gl-native/issues/5766.
> deprecation cleanup for 5.0.0

- platform/macos/src/MGLMapView.mm
`-[MGLMapView awakeFromNib]` nils out the `styleURL` property to ensure a style is always present on load. However, if the style URL is specified in the Style URL inspectable, it is set somewhere between `-initWithCoder:` and `-awakeFromNib`; nilling out the `styleURL` property in `-awakeFromNib` thus resets the style to the default. This change guards against nilling out a non-nil style URL, ensuring that `-setStyleURL:` is called once and only once on launch.
Unlike the macOS implementation of MGLMapView, the iOS implementation nils out the `styleURL` property within `-initWithCoder:`. While that approach would also work for macOS, `-setStyleURL:` would end up getting called twice, and Mapbox Streets v9 would get loaded briefly, wastefully, even if the second call to `-setStyleURL:` …
> Avoid clobbering Style URL inspectable

- platform/default/mbgl/storage/offline_database.cpp
> [core] Evict cached resources and tiles equally by access time

- CMakeLists.txt
- cmake/mbgl.cmake
- cmake/shaders.cmake
There are [checks](https://github.com/mapbox/mapbox-gl-native/blob/master/CMakeLists.txt#L7-L25) for both of these, but they don't work since the current working directory is not the source directory (it's the build directory). Instead, we'll have to supply the absolute path for these checks to work correctly.
> git + npm is run on every CMake invocation

- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Updated the iOS SDK and macOS SDK changelogs to mention #7446, #7356, #7465, #7616, #7445, #7444, #7526, #7586, #7574, and #7770. Also corrected the blurb about #7711. The changelogs are now current as of bf82b07ac8679b30b5f98cb2393c531d2a7d4e12.
> Update iOS, macOS changelogs

- src/mbgl/util/thread.hpp
pthread is not used directly, but per platform basis.
> [core] Remove unused include

- include/mbgl/gl/gl.hpp
Better compatibility when compiling to the several platforms supported by Qt.
> [Qt] Use Qt's OpenGL header

- .travis.yml
- platform/android/config.cmake
- platform/default/utf.cpp
- platform/ios/config.cmake
- platform/linux/config.cmake
- platform/macos/config.cmake
- platform/qt/qt.cmake
- platform/qt/src/bidi.cpp
- platform/qt/src/string_stdlib.cpp
- platform/qt/src/utf.cpp
- src/mbgl/util/utf.hpp
> [core][Qt] Use Qt for UTF16, since `codecvt` is not always available

- platform/android/bitrise.yml
Refs #7733, this PR [disables building for MIPS](https://github.com/mapbox/mapbox-gl-native/issues/7733#issuecomment-273502978) for our nightly builds (both SNAPSHOTS as metrics). 
This is no final solution but will unblock us for the time beeing.
> [android] - unblock building nightly builds

- platform/android/src/native_map_view.cpp
Closes #5748,
This PR removes unnecessary logging from `native_map_view.cpp` and limits logging to only errors and warnings. In normal cases the end developer will only see statements about webrequests as:
```
V/HTTPRequest: [HTTP] Request was successful (code = 200).
```
I'm targetting to close #5748 with this PR but we still need to clean up logging from telemetry. I'm proposing to postpone that until we extract telemetry from the SDK. cc @zugaldia
> [android] - remove redudant log statements in native_map_view.cpp

- src/mbgl/programs/line_program.hpp
- src/mbgl/renderer/line_bucket.cpp
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7778, a alternative fix for https://github.com/mapbox/mapbox-gl-js/pull/4008
@lbud  I am using a different fix: I found that computing the unit vector of (0, 0) on native [returns a vector of (0, 0)](https://github.com/mapbox/mapbox-gl-native/commit/768c259#commitcomment-20538139), while JS uses NaN. I investigated a little further and ultimately found that this makes `miterLength` NaN as well on JS. Instead of using NaN all the way down, this patch uses an explicit value of `0`, and sets the `miterLimit` to Infinity in that case. This change also fixes the missing line caps we saw on native (which was also a result of the different way of computing `unit(0, 0)`).
I think we should port this change back to JS as well, since it …
> Fix rendering 180° line joins

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/TrackingSettingsTest.java
Closes #7349, contains following changes:
- zoom to at least 2 when location tracking is enabled
- introduce interface for zoom invalidation
- simplify example
update: added a unit test for new interface and tests for FocalPointChange interface. This cascaded in a change in MyLocationView.
> [android] - zoom to at least 2 when tracking is enabled

- .travis.yml
- cmake/test-files.cmake
- platform/default/mbgl/storage/offline_database.cpp
- platform/default/sqlite3.cpp
- platform/default/sqlite3.hpp
- platform/qt/config.cmake
- platform/qt/qt.cmake
- platform/qt/qt4.cmake
- platform/qt/qt5.cmake
- platform/qt/src/sqlite3.cpp
- test/storage/offline_database.test.cpp
- test/storage/sqlite.test.cpp
Updates mapbox::sqlite API (from `platform/default/sqlite3.hpp`) to be platform-agnostic, providing means of having a Qt-only implementation that doesn't directly depend on sqlite3 headers/libraries.
> [Qt] Implement mapbox::sqlite::{Database,Statement} using QtSql

- .travis.yml
- CMakeLists.txt
- platform/linux/config.cmake
- scripts/travis_setup.sh
- scripts/valgrind.sup
Upgrade to mesa 13.0.3 (https://github.com/mapbox/mason/pull/324), and also rationalize how it's used:
* Always use the mason package at build time
* Always use the mason package at run time (via `LD_LIBRARY_PATH`)
> [linux] mesa 13.0.3

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
Closes #7782 + fixes that camera position invalidations happen for all moveCamera invocations and inside the actual runnable invoking the `jumpTo`.
> [android] - invalidate MarkerView after render invocation

- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/adapter/FeatureSectionAdapter.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
Useful to be able to easily access a simple map activity to test basic map features.
> Move the simple map activity to a "Basic" section, always listed first

- platform/ios/src/MGLMapView.h
- platform/macos/src/MGLMapView.h
Adding Gesture info as discussed: https://github.com/mapbox/mapbox-gl-native/issues/2278#issuecomment-273685832
Not sure if using codeblocks is kosher.
> Document how to avoid gesture recognizer conflicts

- platform/darwin/docs/guides/For Style Authors.md.ejs
- platform/ios/docs/guides/For Style Authors.md
- platform/macos/docs/guides/For Style Authors.md
mapbox/mapbox-gl-style-spec#656 added a `canvas` source type that only makes sense in a webpage context (but see mapbox/mapbox-gl-native#7471). This PR points out that canvas sources are unsupported in the iOS and macOS SDKs’ “Information for Style Authors” guide. Whereas most of the runtime styling API is generated automatically, the source API is maintained by hand, since each source type requires a unique set of initializers and methods.
Also fixed a typo in the same guide.
/cc @lbud @lucaswoj
> Note that canvas sources are unsupported

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/ios/uitest/MapViewTests.m
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
Fixed an issue causing MGLMapView’s `camera`’s `heading` to be set to a negative value, indicating an undefined heading, when the map view faces northwest. The heading is now wrapped to between zero and 360 degrees, for consistency with MGLMapView’s `direction` property.
Fixes #7723.
> Wrap camera heading

- platform/android/config.cmake
- platform/default/image.cpp
- platform/default/png_reader.cpp
- platform/default/png_writer.cpp
- platform/linux/config.cmake
We shouldn't supply that as part of the core library; that's something implementors can handle. On Android, https://github.com/mapbox/mapbox-gl-native/pull/7329 will remove it, and on macOS, solving https://github.com/mapbox/mapbox-gl-native/issues/7812 will remove the need for it as well. The only remaining user will be in the tests, and in the `bin/render.cpp` utility.
> Remove util::encodePNG

- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/styles.xml
Before:
After:
Tested on a Samsung Galaxy 4 running Android version 5.0.1
> [Android] Make spinner under Add Markers in Bulk readable

- platform/darwin/src/headless_display_cgl.cpp
- platform/macos/CHANGELOG.md
- platform/macos/app/Info.plist
- platform/macos/src/MGLOpenGLLayer.mm
On computers that have more than one GPU, macOS automatically switches to the discrete one if the app doesn't opt in to also using the integrated GPU: https://developer.apple.com/library/content/qa/qa1734/_index.html
> macOS: Allow use of integrated GPU

- platform/ios/CHANGELOG.md
- platform/ios/ios.xcodeproj/project.pbxproj
Made MGLOpenGLStyleLayer.h public in the static library, fixing a build error that occurred in applications that linked against the static framework.
This issue slipped under our radar through a combination of factors:
* We don’t build an application that links against the static library on Bitrise, or the static library itself for that matter.
* jazzy warns about any symbols declared in the table of contents but left undefined in the framework. However, as of #7569, we point jazzy to the checked-in headers rather than the built static library headers (which omitted MGLOpenGLStyleLayer.h).
* After building the release, I tested linking the dynamic framework into an application but not the static framework.
/cc @kkaefer
> Make MGLOpenGLStyleLayer.h public in static library

- platform/darwin/docs/guides/For Style Authors.md.ejs
- platform/darwin/scripts/update-examples.js
- platform/darwin/test/MGLDocumentationExampleTests.swift
- platform/ios/docs/guides/For Style Authors.md
- platform/ios/src/MGLMapView.h
- platform/macos/docs/guides/For Style Authors.md
Added the examples from #7816 to the unit tests to fix `make darwin-update-examples` and `make style-code-darwin`.
Also include a mention of Night Shift in the macOS version of “Information for Style Authors”, now that macOS Sierra 10.12.4 beta includes Night Shift.
> Test MGLMapView gesture recognizer example; refer to Night Shift on macOS

- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
When converting from view coordinates to screen coordinates, use the screen containing the window, which may not be the screen with keyboard focus (if ⌃ is also held down).
This fixes an issue where the mouse cursor jumped after shift- or option-dragging a map view if the window opened on a screen with a different size than the screen with keyboard focus.
/ref #7819
> Fix cursor jumping after modifier-dragging in dual-screen setup

- platform/ios/src/MGLMapView.mm
> fixes #6688: assert remaining map view notification responses are main thread

- .gitmodules
This allows pushing directly from the submodule, if you have https authentication set up.
> [build] Use https for mapbox-gl-js submodule

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
According to #7256 to solve "flash of black" one alternative is set `MGLMapView.opaque = NO` but one concern was how this may affect the performance. Changing `opaque = NO` resulted in a reduction in FPS from an average of 50.63 to 49.61. This is unnoticeable but we can keep tracking this in case something comes up.
(Benchmark tests were done using bench app)
> Make MGLMapView non opaque by default

- Makefile
Noticed in #7827 that we don't have a make target for generating Android SDK documentation. This PR introduces the target and will generate the javadoc files in `/platform/android/MapboxGLAndroidSDK/build/docs/release/..`.
> [android] - add make target for javadoc generation

- platform/qt/app/mapwindow.cpp
- platform/qt/app/mapwindow.hpp
- platform/qt/include/qmapbox.hpp
- platform/qt/include/qmapboxgl.hpp
- platform/qt/resources/common.qrc
- platform/qt/src/qmapboxgl.cpp
Add new types in `QMapbox` namespace to support the new `geometry.hpp`-based geometries.
> [Qt] Refactor QMapbox Annotations API

- include/mbgl/util/image.hpp
- platform/darwin/mbgl/util/image+MGLAdditions.hpp
- platform/darwin/src/image.mm
- platform/default/png_writer.cpp
- platform/ios/config.cmake
- platform/ios/src/UIImage+MGLAdditions.mm
- platform/macos/config.cmake
- platform/macos/src/MGLMapView.mm
- platform/macos/src/NSImage+MGLAdditions.h
- platform/macos/src/NSImage+MGLAdditions.mm
When calling `encodePNG`, on the bytes of the textures, only to decompress it in the very next line: https://github.com/mapbox/mapbox-gl-native/blob/f1c3cfb7e2d46a4563d680bcab888fa01b2ca160/platform/macos/src/MGLMapView.mm#L790-L792
Instead, we can just use the data we already have to initialize the `NSImage` without going through the compression/decompression routine.
> macOS: Don't round-trip still images through encoding

- src/mbgl/style/source_impl.cpp
`TileCacheStrategy` can now be passed on `Map` ctor as a hint for the style sources about their cache strategy:
- `NoCache`: Do not retain tiles.
- `ConservativeCache`: Retain visible tiles from all zoom levels.
- `DoubleCache`: Twice as conservative.
This is also combined with updating the cache size whenever the transform dimensions or zoom range changes.
> [core] Improve tile cache sizing calculation

- platform/qt/src/sqlite3.cpp
On the default all integers map to `sqlite3_bind_int64`.
> [Qt] Make datatypes compatible with the default implementation

- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
One source of flaky instrumentation tests is the device rotation. When set to landscape mode, the map can return different values for the same test case than in portrait mode. This makes making assertions unreliable or we would have to take in account a larger delta. This PR solves this by forcing device orientation to portrait mode.
> Force portrait mode for instrumentation tests

- platform/android/CHANGELOG.md
- platform/android/scripts/release.py
With the new strategy we are following related to managing release branches, we seem to have forgotten to bring back the CHANGELOG changes for the different 4.x (beta) releases. 
> [android] - update changelog with 4.x entries

- platform/macos/app/MapDocument.m
As of #6742, we no longer overload MGLMultiPoint for GeoJSON multipoints, instead representing those shapes with MGLPointCollection. However, the function in macosapp that “flattens” some of the more exotic GeoJSON types into annotation-compatible types was still attempting to flatten MGLMultiPoints. This function is used when feeding feature querying results back to the map as annotations.
/cc @boundsj @frederoni
> Flatten point collections, not multipoints

- platform/macos/app/AppDelegate.m
- platform/macos/app/Base.lproj/MainMenu.xib
- platform/macos/src/MGLMapView.mm
In a Debug build, if you set the style URL to a mapbox: URL before providing an access token, the following C++ assertion fails:
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: You must provide a Mapbox API access token for Mapbox tile sources
```
If you set the style URL to `nil`, however, nothing happens. Instead of crashing or silently bailing, MGLMapView now logs a warning to the console and bails even if the style URL is set to a mapbox: URL. The reason the macOS implementation of `-[MGLMapView setStyleURL:]` bails instead of asserting, as the iOS implementation does, is that the non-modal Preferences window needs a chance to accept the user’s access token before loading the style.
Speaking of which, the Preferences window now takes first …
> Turn missing access token assertion into warning

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/config.cmake
- platform/android/src/bitmap.cpp
- platform/android/src/bitmap.hpp
- platform/android/src/bitmap_factory.cpp
- platform/android/src/bitmap_factory.hpp
- platform/android/src/image.cpp
- platform/android/src/jni.cpp
- platform/android/src/native_map_view.cpp
- platform/android/src/test/main.jni.cpp
Another take at #7329.
- Removes `libjpeg-turbo` and `libpng` in favor of calls to [`BitmapFactory.decodeByteArray`](https://developer.android.com/reference/android/graphics/BitmapFactory.html#decodeByteArray(byte%5B%5D,%20int,%20int,%20android.graphics.BitmapFactory.Options)). We're doing a bunch of copies, but I don't think we can avoid any of them. I implemented a version that used `java.nio.ByteBuffer` and supplying the pointer address directly, but Java can't generate a `byte[]` required for `decodeByteArray`. We could alternatively implement a `NativeInputStream` (similar to the `NativeOutputStream` contained in this PR) and use [`BitmapFactory.decodeStream`](https://developer.android.com/reference/android/graphics/BitmapFactory.html#decodeStream(java.io.InputStream)) to avoid one …
> Android: use system-provided image decoding + encoding

- .travis.yml
This caused a build failure right away: https://travis-ci.org/mapbox/mapbox-gl-native/jobs/195965940, and in general I think this is something that is going to be more trouble than it's worth to rigorously enforce.
> [build] Revert checking codestyle in CI

- platform/ios/framework/strip-frameworks.sh
This self-deletes `strip-frameworks.sh` during the build script phase, after it’s done doing its deed. Without this trap, the script is distributed to users in released apps in Mapbox.framework.
Does not address the CocoaPods use-case, where this script is unnecessary and not executed, but still ultimately included in the built app.
/cc @boundsj
> [ios] Stop including framework stripping script in built product

- platform/ios/framework/strip-frameworks.sh
Reverts part of #7895.
Unfortunately, Xcode expects this script to be cached after the first build and will fail on subsequent incremental builds when it’s missing. There appears to be no reasonable way to detect if a build is intended for archive/app store distribution, nor to fix the Run Script Phase path in such a way that it’s more resilient. 😞
> [ios] Revert self-deletion of framework stripping script

- platform/node/bitrise.yml
- platform/qt/src/sqlite3.cpp
Guarantee `QSqlDatabase` connection name uniqueness by using a static counter together with the current thread.
Fixes https://bugreports.qt.io/browse/QTBUG-58552.
> [Qt] Guarantee QSqlDatabase connection name uniqueness

- test/util/http_timeout.test.cpp
- test/util/mapbox.test.cpp
Removes a few unneeded includes from tests, adds one that is needed.
> Remove unneeded <regex> includes

- platform/darwin/resources/zh-Hant.lproj/Foundation.strings
- platform/ios/CHANGELOG.md
- platform/ios/framework/Settings.bundle/zh-Hant.lproj/Root.strings
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/resources/zh-Hant.lproj/Localizable.strings
- platform/macos/CHANGELOG.md
- platform/macos/macos.xcodeproj/project.pbxproj
- platform/macos/sdk/zh-Hant.lproj/Localizable.strings
Added Traditional Chinese localizations to the iOS and macOS SDKs, using [OpenCC](https://github.com/BYVoid/OpenCC/) to convert the Simplified Chinese localizations added in #7316 and #7503. ([Instructions](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#adding-a-localization))
I spot-checked the results but would appreciate a review by @lily-chai, @virginiayung, or @jenyuhk. Also, if any of these strings could have more idiomatic translations, we could add Taiwan- or Hong Kong–specific localizations, [again using OpenCC](https://github.com/BYVoid/OpenCC/#預設配置文件).
Fixes #7370.
/cc @YunJieLi @friedbunny
> Traditional Chinese localization

- .gitignore
- .tx/config
- platform/ios/DEVELOPING.md
- platform/macos/DEVELOPING.md
This PR configures and documents a workflow for pulling translations of the iOS and macOS SDKs from the [Mapbox GL Native project on Transifex](https://www.transifex.com/mapbox/mapbox-gl-native/). This setup can easily be generalized to manage any localizable strings in the Android SDK.
Although the `tx` tool is considerably slower than the REST API usage in iD and osrm-text-instructions, I like the various conveniences built the tool. One area for future improvement would be automating adding a new language to the Xcode projects using [node-xcode](https://github.com/alunny/node-xcode/tree/master/lib) or the [xcodeproj](https://github.com/CocoaPods/Xcodeproj) gem.
/cc @bhousel @freenerd
> Manage translations in Transifex

- platform/darwin/src/MGLStyleValue_Private.h
- platform/darwin/test/MGLStyleValueTests.swift
In https://github.com/mapbox/mapbox-gl-native/pull/7596 I missed adding default value support to identity functions. This adds it so that source functions with any interpolation mode can use default values.
cc @jfirebaugh @1ec5 @incanus
> [ios, macos] Implement default value for identity functions

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngTest.java
Closes #4522, this PR wraps every longitude value coming from core and replaces the previous wrap implementation. Before merging we will need some additional testing for animating around the dateline. 
> [android] - wrap longitude values from core

- platform/ios/docs/guides/Gesture Recognizers.md
- platform/ios/docs/guides/UserInteractions.md
- platform/ios/jazzy.yml
- platform/node/bitrise.yml
Added an overview of built-in gesture recognizers in iOS SDK. 
Addresses #7635 
cc @1ec5  @friedbunny
> [ios] add user interaction guide

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
Fixes #7789 
The stuttering effect is not as noticeable as I first thought. Concurrent animations (#3625) might still be a blocker though.
The transition is more or less smooth depending on the timing of the subsequent location update.
@bsudekum 👀
> Persist user tracking mode despite programmatic camera changes

- platform/darwin/src/MGLOfflinePack.mm
- platform/darwin/src/MGLOfflinePack_Private.h
- platform/darwin/src/MGLOfflineStorage.mm
- platform/ios/CHANGELOG.md
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/CI.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/bench.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/dynamic+static.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/dynamic.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme
- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/static.xcscheme
- platform/ios/uitest/ios-tests.xcodeproj/xcshareddata/xcschemes/Mapbox GL Tests.xcscheme
- platform/macos/CHANGELOG.md
> Post offline pack notifications from MGLOfflinePack

- src/mbgl/map/map.cpp
Hope to get complete apitrace with a clean exit rather than an abort. I plan to revert this change once we fix the underlying issue in https://github.com/mapbox/mapbox-gl-native/issues/7681#issuecomment-277826166.
> [node] Temporary: exit(1) on exception in Painter::render

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
see https://github.com/mapbox/mapbox-gl-native/issues/7955
> 7955 fix MGLMapView leaks MGLReachability objects (and threads)

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerViewTest.java
This PR allows to use an `ObjectAnimator` to animate the rotation value instead of doing the animation ourselves. Closes #7798
> Allow ObjectAnimator to animate rotation of MarkerView

- include/mbgl/storage/response.hpp
- test/map/map.test.cpp
- test/storage/server.js
- test/util/http_timeout.test.cpp
1. Set a style URL with the network connection down and empty cache.
2. Turn the network connection up.
3. Call mbgl::NetworkStatus::Reachable()
Style request gets retried and we see a map.
Blank map.
> [core] Style request doesn't get retried on mbgl::NetworkStatus::Reachable()

- platform/qt/app/mapwindow.cpp
- platform/qt/include/qmapbox.hpp
- platform/qt/include/qmapboxgl.hpp
- platform/qt/src/qmapbox.cpp
- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qt_conversion.hpp
- platform/qt/src/qt_geojson.hpp
Using a mix of runtime styles and annotations API, we can e.g. create a circle layer using `AnnotationManage::SourceID` as source, and then later adding a `StyleSourcedAnnotation` passing that newly-created layer ID.
The technique above already works for most annotation geometry types - except `Point`. This PR:
1. Adds support for `Point<double>` in `ShapeAnnotationGeometry` variant, used by `StyleSourcedAnnotation` to store the annotation's geometry
2. Adds support for `CircleLayer` in `StyleSourcedAnnotation`
3. Forwards API changes into QMapbox{GL} API
This makes it possible for implementing [MapCircle](http://doc.qt.io/qt-5/qml-qtlocation-mapcircle.html) QML item natively for our QtLocation Mapbox GL plugin.
> [qt] Added support for features as input for GeoJSON source

- platform/android/bitrise.yml
Currently our SNAPSHOTs are timing out, removing this should fix the issue.
cc: @zugaldia
> Removed arch from bitrise script so snapshots build

- platform/darwin/src/MGLStyleValue.h
- platform/darwin/src/MGLStyleValue.mm
- platform/darwin/src/MGLStyleValue_Private.h
- platform/darwin/test/MGLStyleValueTests.swift
Fixes: https://github.com/mapbox/mapbox-gl-native/issues/7934
Addresses `MGLStyleValue` documentation todos noted in https://github.com/mapbox/mapbox-gl-native/issues/7924:
> Add back MGLStyleFunction and re-document MGLStyleValue

- platform/darwin/src/MGLStyleValue.h
Addresses enumeration todos noted in https://github.com/mapbox/mapbox-gl-native/issues/7924
> [ios, macos] Document DDS enumerations

- platform/darwin/src/MGLCircleStyleLayer.h
- platform/darwin/src/MGLLineStyleLayer.h
- platform/darwin/test/MGLDocumentationExampleTests.swift
Addresses generated examples todo noted in https://github.com/mapbox/mapbox-gl-native/issues/7924:
cc @ericrwolfe @friedbunny @1ec5
> Update documentation examples to use new style functions

- platform/darwin/scripts/generate-style-code.js
- platform/darwin/src/MGLBackgroundStyleLayer.h
- platform/darwin/src/MGLCircleStyleLayer.h
- platform/darwin/src/MGLFillStyleLayer.h
- platform/darwin/src/MGLLineStyleLayer.h
- platform/darwin/src/MGLRasterStyleLayer.h
- platform/darwin/src/MGLSymbolStyleLayer.h
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7935
This adds documentation to each style layer property that specifies the function and interpolation mode combinations that will work for the property. 
In some cases, function and interpolation stop combination values that don't make sense will be coerced into a values that do. For example, a camera function with and exponential interpolation mode that is set on a property that is a piecewise-constant function will be converted into a camera function with an interval interpolation mode.
> Add function and interpolation mode to style property docs

- platform/qt/include/qmapboxgl.hpp
- platform/qt/src/qmapboxgl.cpp
Used by the Qt plugin in addition to `QMapboxGL::layerExists` as a helper tool for handling managed Qt map items.
> [Qt] Added QMapboxGL::sourceExists

- platform/ios/ios.xcodeproj/project.pbxproj
#7888 added MGLDistanceFormatter.h and MGLDistanceFormatter.m to the dynamic target but not the static target. This PR adds them to the static target as well. The dynamic+static scheme was able to build because MGLDistanceFormatter.h has remained in the project’s header search path, whereas a normal application target linking against the static framework would fail to build.
/cc @boundsj
> Add MGLDistanceFormatter to static library

- src/mbgl/tile/geometry_tile_data.cpp
- test/tile/geometry_tile_data.test.cpp
This PR moves native to match JS which compares unsigned areas when limiting polygon rings (https://github.com/mapbox/mapbox-gl-js/blob/fddba1b48e7e65b821ef7c7c3813f03baa8abf9d/js/util/classify_rings.js#L19)
This is important. Currently we compare signed area which means we incorrectly sort polygons before limiting.
Fixes various rendering issues like the coast of sweden:
Before:
After:
> Compare absolute value of polygon ring area

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLMapViewDelegate.h
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
- platform/macos/src/MGLMapViewDelegate.h
Added a way for the delegate to restrict where the user can move within the map using gestures. This approach allows the developer to restrict to a non-rectangular region or vary the region by zoom level or pitch as necessary, such as to prevent the user from seeing beyond a certain region regardless of the degree of tilt.
This PR intentionally keeps things simple to unblock some key use cases. Future improvements could include implementing a “rubber band” effect, allowing the delegate to “redirect” the camera to some other camera (https://github.com/mapbox/mapbox-gl-native/issues/2457#issuecomment-222051074), and automatically restricting the camera to downloaded regions (#5042).
Before we can land this feature:
* Or maybe find a way to call the method less frequently?
* Or calculate the …
> Delegate method to restrict movement

- include/mbgl/style/conversion/filter.hpp
- include/mbgl/style/filter.hpp
- include/mbgl/style/filter_evaluator.hpp
- platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm
- platform/darwin/src/NSExpression+MGLAdditions.h
- platform/darwin/src/NSExpression+MGLAdditions.mm
- platform/darwin/src/NSPredicate+MGLAdditions.mm
- platform/darwin/test/MGLExpressionTests.mm
- platform/darwin/test/MGLPredicateTests.mm
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- src/mbgl/style/conversion/stringify.hpp
> [core] Introduce dedicated filter types for $type and $id special cases

- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/resources/ja.lproj/Localizable.strings
Adds an 84% complete Japanese translation of our iOS strings.
(Xcode also automatically removed a duplicate[?] entry for `MGLDistanceFormatter.h` in the project.)
/cc @boundsj
> [ios] Add partial Japanese localization

- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Added mention of #7621. I’ve already updated the iOS SDK v3.5.0-beta.1 release notes to include this blurb.
> Update changelog for #7621

- platform/darwin/docs/theme/assets/css/jazzy.css.scss
Added MGLStyleFunction to the list of classes to mark as abstract classes in the sidebar of the jazzy-generated documentation. MGLStyleFunction became an abstract class in #7943.
/cc @boundsj
> Mark MGLStyleFunction as abstract in documentation navigation

- platform/glfw/glfw_view.cpp
- platform/linux/config.cmake
- platform/macos/config.cmake
Makes testing/comparison with https://github.com/mapbox/mapbox-gl-native/issues/7820 easier.
> Use newer GLFW version that supports automated graphic switching

- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
- platform/android/build.gradle
Progress towards https://github.com/mapbox/mapbox-gl-native/issues/7643.
Background on the new version of MAS is on https://github.com/mapbox/mapbox-java/issues/322.
> Update SDK dependency to MAS beta.1

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
This fixes #8021 
Don't deselect annotations on pan/zoom, even if the annotation moves out of the visible bounds. Now MapBox behaves like Google Maps and MapKit.
> Don't deselect annotations on pan/zoom, even if the annotation moves out of the visible bounds

- src/mbgl/util/url.cpp
- test/util/url.test.cpp
Our URL parsing library doesn't split this information out from the `domain` part, but we should support parsing URLs that contain these things.
Follow-up to https://github.com/mapbox/mapbox-gl-native/pull/7464
> Add tests for user/password, port, trailing dot, and IPv4/IPv6 addresses

- platform/glfw/glfw_view.cpp
Reproducible on Linux. On OSX, map looks slightly scaled.
> [glfw] Fix viewport not being resized

- include/mbgl/map/map.hpp
- platform/ios/CHANGELOG.md
- platform/ios/app/MBXViewController.m
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/app/MapDocument.m
- platform/macos/src/MGLMapView.mm
- src/mbgl/map/map.cpp
Rounds double-tap and two-finger tap zoom gestures to the nearest integer zoom level. This has benefits for raster tiles, as well as styles with zoom-based functions that transition on integers.
This results in a wider possible zoom range per gesticulation — 1.0 → ~0.5-1.5 levels. Here’s a comparison of double-tapping to zoom in with the changes in this PR:
| Starting Zoom | Old Result | New Result |
|:----------:|:-------------:|:------:|
| 4.0 |    5.0 (+1.0)   |   5.0 (+1.0) |
| 4.4 |    5.4 (+1.0)   |   **5.0** (+0.6) |
| 4.6 |    5.6 (+1.0)   |   **6.0** (+1.4) |
Fixes #2276. 
Exposes an already-existing `setZoom` variation that takes an `anchor` parameter — I did this to avoid calculating scale levels in the iOS zoom code. This makes `Map::setZoom(zoom, {}, duration)` ambiguous,  so …
> Round tap-zoom gestures to nearest integer

- platform/macos/CHANGELOG.md
- platform/macos/src/MGLOpenGLLayer.mm
> macOS: reuse OpenGL context when switching screens

- platform/glfw/glfw_view.hpp
Mesa does not check if GLAPIENTRY was defined before before defining
it, what makes the compiler sad. So we make Mesa define it first,
before GLFW.
Follow-up of #8017.
/cc @kkaefer
> [glfw] Include gl.hpp first to avoid redefinition of GLAPIENTRY

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
Closes #8032, This PR enables updating the underlying Marker of a MarkerView when that MarkerView isn't found in the current Viewport.
> [android] - keep MapboxMap reference when MarkerView out of viewport

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraAnimateTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraEaseTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraInternalApiTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraMoveTest.java
Refs #7221, been running our instrumentation tests on a range of Android devices. this PR fixes up master to ignore tests that can result in false positives on larger screen devices. Next actions to resolve this are documented in https://github.com/mapbox/mapbox-gl-native/issues/7221#issuecomment-279980479.
> [android] - ignore device dependant tests

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
I noticed we had some unused telemetry constants in `MapboxConstants.java`.
Looking more into this I'm seeing that these are now included in external telem library [here](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/constants/TelemetryConstants.java#L25-L40). 
Good to remove @zugaldia?
> [android] - remove unused telem constants

- include/mbgl/gl/gl.hpp
C++11 destructors are noexcept by default, so the prior definition always called std::terminate without allowing anything to catch the exception.
This explains why the `catch` I added in f0d4411 wasn't catching.
> [core] Add noexcept(false) in MBGL_CHECK_ERROR

- src/mbgl/shaders/symbol_sdf.cpp
Need highp precision for gamma values on mobile devices. lowp triggers aliasing artifacts at larger font sizes.
Note that this change is a hand-edit to the generated shader sources, rather than pulling https://github.com/mapbox/mapbox-gl-js/pull/4275 and running the generator script. The reason for that is that the upstream shader now assumes support for DDS properties that gl-native does not yet support. Once that support lands in gl-native, we can regenerate the shader source.
Fixes #7599.
> [core] Fix aliased text on mobile GPUs

- CMakeLists.txt
- Makefile
- test/src/mbgl/test/util.hpp
These tests have always been flaky (https://github.com/mapbox/mapbox-gl-native/issues/5364), and started failing more consistently on macOS CI after upgrading the Bitrise stack.
> [tests] Disable timing-based Timer tests in CI

- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
I messed up previous commit with some rebase. This one contains all the changes from review of #8033.
> [macos] Make +, - and = keys zoom in/out 

- platform/ios/scripts/package.sh
In https://github.com/mapbox/mapbox-gl-native/pull/6984 we started using [ICU](https://github.com/mapbox/mason/pull/275) in core. This causes linker errors in an iOS application that uses a static build of the Mapbox iOS SDK.
This passes ICU (via Mason) to libtool when the iOS static build is created so that the dependency is available when the Mapbox iOS SDK is used in a host iOS application. 
The ICU lib actually replaces libgeojson. On our build machines libgeojson was not actually getting passed to libtool since the path used was provided by {IOS_SDK_VERSION} (created with `xcrun --sdk iphonesimulator|iphoneos --show-sdk-version` was greater than the `8.0` value that is [currently hard coded in the mason.sh script](https://github.com/mapbox/mason/blob/master/mason.sh#L70). I'm still …
> Pass ICU to libtool in package script

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLLocationManager.m
> [ios] Disable region monitoring when stopping location monitoring

- include/mbgl/style/layers/symbol_layer.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs
- platform/darwin/scripts/generate-style-code.js
- platform/darwin/src/MGLStyleLayer.mm.ejs
- platform/darwin/src/MGLStyleValue_Private.h
- platform/darwin/src/MGLSymbolStyleLayer.h
- platform/darwin/src/MGLSymbolStyleLayer.mm
- platform/darwin/test/MGLBackgroundStyleLayerTests.mm
- platform/darwin/test/MGLCircleStyleLayerTests.mm
- platform/darwin/test/MGLFillStyleLayerTests.mm
- platform/darwin/test/MGLLineStyleLayerTests.mm
- platform/darwin/test/MGLRasterStyleLayerTests.mm
- platform/darwin/test/MGLStyleLayerTests.mm.ejs
- platform/darwin/test/MGLSymbolStyleLayerTests.mm
- platform/macos/app/Base.lproj/MapDocument.xib
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/style/function/categorical_stops.cpp
- src/mbgl/style/function/identity_stops.cpp
- src/mbgl/style/layers/symbol_layer.cpp
- src/mbgl/style/layers/symbol_layer_properties.hpp
So, I got to what I thought should at least compile here so that I could try it / iterate, but ran into this semi-mysterious compiler error:
```
▸ Compiling parser.cpp
❌  /Users/anand/c/mapbox/mapbox-gl-native/include/mbgl/style/conversion/function.hpp:333:20: no matching constructor for initialization of 'CompositeFunction<std::__1::basic_string<char> >'
return CompositeFunction<T>(*propertyString, convertedStops, *defaultValue);
^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
❌  /Users/anand/c/mapbox/mapbox-gl-native/include/mbgl/style/conversion/function.hpp:333:20: no matching constructor for initialization of 'CompositeFunction<mbgl::style::TextTransformType>'
return CompositeFunction<T>(*propertyString, convertedStops, *defaultValue);
^
```
Telling that this has …
> [core] Enable property functions for text-{field,transform}

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/functions/Function.java
Needed to fix conversion due to changes in templates here: https://github.com/mapbox/mapbox-gl-native/commit/685f237d0286ef13aac52cbbab93fed82a0b31b8
> [android] fix default value conversion on dds functions

- CMakeLists.txt
- test/src/mbgl/test/util.hpp
> Disable timing-based Timer tests in CI

- src/mbgl/style/layers/circle_layer_impl.cpp
This adds a line to pass the circle layer render check if the circle stroke color is visible. Previously, a transparent circle color would cause the layer to be passed up even if the circle stroke color had
a non-zero alpha.
cc @jfirebaugh @jmkiley
Fixes https://github.com/mapbox/mapbox-gl-native/issues/8077
> Render a circle if either the color or stroke color are visible

- platform/ios/app/MBXViewController.m
Copy-pasted the better implementation from macOS. Fixes a crash that happened when trying to modify a non-mutable NSDictionary. Issue started some time after v3.5.0-beta.1.
> [ios] Fix locale-based language switching demo

- platform/darwin/src/MGLMapCamera.h
- platform/darwin/src/MGLMapCamera.mm
- platform/darwin/test/MGLGeometryTests.mm
- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/ios/uitest/MapViewTests.m
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
Avoid canceling transitions (and triggering preexisting completion handlers) until we get a chance to ensure that a new transition really does have to begin. Consistently avoid mbgl transitions for redundant camera changes. Upon bailing, schedule the completion handler to run asynchronously on a delay equivalent to the requested animation duration.
~~MGLMapCamera now performs a float-precision equality check to avoid trivial differences. Added an equality operator to CameraOptions that similarly uses float-precision.~~ Added a “functional” equality method to MGLMapCamera that avoids trivial differences.
Having made these changes, I very much want to move these redundancy checks into `mbgl::Transform`. However, that depends on eliminating the numerous SDK-side `cancelTransitions()` calls: …
> Short-circuit redundant camera changes

- platform/darwin/src/MGLFeature.h
- platform/darwin/src/NSExpression+MGLAdditions.mm
- platform/darwin/test/MGLExpressionTests.mm
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
When converting a constant NSExpression to an `mbgl::Value`, turn an NSColor or UIColor into an `std::string` containing a CSS color string. This allows developers to set an attribute of an MGLFeature to an NSColor or UIColor (rather than a CSS color string, which would be foreign), then use it in an MGLStyleFunction with identity interpolation.
Along the way, I added language to `MGLFeature.attributes`’ documentation to talk about the use of feature attributes in identity-interpolated style functions. I also simplified the NSExpression unit tests to more specifically test the category methods that convert constant NSExpressions to `mbgl::Value`s, without going through NSPredicate. Normally I’d be hesitant to rely so heavily on macros, which makes debugging more difficult, but the …
> Convert NSColor/UIColor expressions to CSS color string values

- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Removed a duplicate entry for #5932. Moved the #7125 entry to the right release. Added a blurb about #7937. Added dates for iOS SDK v3.4.0 and v3.4.1 and macOS SDK v0.3.0.
> Update, clean up changelogs

- include/mbgl/storage/default_file_source.hpp
- include/mbgl/storage/online_file_source.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/Resource.java
- platform/android/config.cmake
- platform/android/src/default_file_source.cpp
- platform/android/src/default_file_source.hpp
- platform/android/src/jni.cpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/darwin/src/MGLFoundation.mm
- platform/darwin/src/MGLFoundation_Private.h
- platform/darwin/src/MGLOfflineStorage.h
- platform/darwin/src/MGLOfflineStorage.mm
- platform/darwin/src/run_loop.cpp
- platform/darwin/test/MGLOfflineStorageTests.mm
- platform/default/default_file_source.cpp
- platform/default/online_file_source.cpp
- platform/ios/CHANGELOG.md
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/macos.xcodeproj/project.pbxproj
- platform/macos/src/MGLMapView.mm
- test/storage/default_file_source.test.cpp
An alternative to https://github.com/mapbox/mapbox-gl-native/pull/7485. This implements a way of modifying the URLs that get requested from the internet. Potential use cases are altering URLs or hostnames and supporting use cases as described in https://github.com/mapbox/mapbox-gl-native/issues/7455
This implementation invokes the supplied callback on the main thread (where the `DefaultFileSource:: setResourceTransform` happens) to avoid threading issues. I benchmarked the time it takes to transform the URL, and typically got times <1ms roundtrip (for scheduling the callback on the main thread and returning the result to the `OnlineFileSource` thread), but it can sometimes be higher when the main thread is busy rendering the map.
To do:
Caveats:
- Does not allow transforming `asset://` …
> Allow transforming URLs before requesting

- src/mbgl/gl/context.cpp
- src/mbgl/gl/context.hpp
- src/mbgl/gl/segment.hpp
Previously, if VAOs were not supported, a VAO with ID 0 was getting into `Context::abandonedVertexArrays`, and a crash ensued when trying to call `gl::DeleteVertexArrays`.
Fixes #8079
> [core] Redo approach to unsupported VAO extension

- platform/android/config.cmake
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/default/mbgl/util/default_thread_pool.cpp
- platform/default/mbgl/util/shared_thread_pool.cpp
- platform/default/mbgl/util/shared_thread_pool.hpp
- platform/ios/config.cmake
- platform/ios/src/MGLMapView.mm
- platform/macos/config.cmake
- platform/macos/src/MGLMapView.mm
- platform/qt/qt.cmake
- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qmapboxgl_p.hpp
Currently, every map object creates its own thread pool, but we should use a shared thread pool, possibly with a static function cache holding on to weak `shared_ptr` so that the thread pool gets destructed when the last map object ceases to exist.
> iOS/Android: Use shared thread pool

- cmake/core-files.cmake
- include/mbgl/map/backend.hpp
- include/mbgl/map/backend_scope.hpp
- platform/android/src/native_map_view.cpp
- platform/default/mbgl/gl/headless_backend.cpp
- platform/default/mbgl/gl/headless_backend.hpp
- src/mbgl/map/backend_scope.cpp
- src/mbgl/map/map.cpp
- test/gl/object.test.cpp
- test/map/map.test.cpp
- test/util/offscreen_texture.test.cpp
Eliminate manual activate/deactivate, and always use `BackendScope`. `BackendScope` now works as a stack, pushing the new context when coming into scope and restoring the prior context when going out of scope.
Fixes #7681
Fixes #8076
> [core] Fix HeadlessBackend context management

- scripts/travis_setup.sh
The logbt 2.0.1 release is now fixed to no longer restrict coredump reporting for specific exit codes. This means it behaves the same as the branch currently in use after #8043. This gets us using a released version.
> Upgrade to logbt 2.0.1

- Makefile
Per chat, this helps navigate the myriad Android architecture options so that we don't have to `grep` the `Makefile` all the time (assuming it's kept up to date). 
- Does this cover our bases? 
- Is it likely to get updated as things move along? 
- Anything else? 
@mapbox/android
> add make android-help target

- platform/ios/app/MBXViewController.m
Per chat with @kkaefer, a quick settings toggle in the iOS demo app for toggling a second map view for use in debugging a shared thread pool in https://github.com/mapbox/mapbox-gl-native/pull/8094. 
The bulk of the work is updating constraints to keep the two map views in the right place & size during device rotation.
> add setting to toggle two maps for thread debugging

- platform/darwin/test/MGLGeometryTests.mm
In `testCoordinateInCoordinateBounds` the coordinates for Wyoming were inverted, misleading how to pass ne/sw coordinates to `MGLCoordinateBoundsMake`
> [ios, macos] fixed wyoming inverted coordinates

- scripts/valgrind.sh
This reverts commit 090fb92fbf073728e1a9b5196e880a216f11e109.
Fixes #8103.
> Revert "[build] Add --track-origins=yes to valgrind arguments"

- include/mbgl/map/map.hpp
- platform/android/src/jni.cpp
- src/mbgl/map/map.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
Closes #8081, this PR enables to use AnimationOptions when performing a moveBy transformation.
For Android I'm adding `mbgl::util::UnitBezier { 0, 0.3, 0.6, 1.0 }` as interpolator to get a better UX for current fling gesture:
Before:
After:
> Transform::moveBy with AnimationOptions

- platform/ios/DEVELOPING.md
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/macos/DEVELOPING.md
- platform/macos/macos.xcodeproj/project.pbxproj
Adds blank `Localizable.strings` to iosapp and macapp, so that our SDK localizations will be used in those apps.
> [ios, macos] Enable localizations in iosapp & macosapp

- platform/android/bitrise.yml
With the improved setup on CI, I'm no longer getting timeouts when doing `make apackage`, this PR brings that behavior back to our `nightly` and `scheduled` builds:
Fixes https://github.com/mapbox/mapbox-gl-native/issues/7733.
@tobrun Please review.
> Bring all architectures back to CI builds

- platform/qt/include/qmapbox.hpp
- platform/qt/include/qmapboxgl.hpp
- platform/qt/src/qmapboxgl.cpp
Projected meters are required to calculate the circle radius for QML `MapCircle` items.
Remaining documentation to be handled in https://github.com/mapbox/mapbox-gl-native/pull/8006.
> [Qt] Added missing conversion helpers

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/camera/CameraEaseTest.java
- platform/android/MapboxGLAndroidSDKWearTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKWearTestApp/src/main/java/com/mapbox/weartestapp/activity/FeatureOverviewActivity.java
- platform/android/MapboxGLAndroidSDKWearTestApp/src/main/java/com/mapbox/weartestapp/activity/SimpleWearMapActivity.java
- platform/android/MapboxGLAndroidSDKWearTestApp/src/main/res/layout/activity_simple_mapview.xml
We currently have two "simple" mapview examples in our project. One for the Phone module and one for the wear module. The issue I'm constantly hitting is trying to do some tests on the phone module but accidentally changing the code for the wear module instead. Renaming the wear example to explicitly state Wear in it's name will resolve this.
> [android] - rename simple example map view 

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Closes #6999. Inspired from a construction used in #8031, posting invocation of the onMapReady callback results in providing our users with a MapboxMap that is instantiated with measured components while they are unmeasured with current implementation. Been testing this against the issues linked in #6999 and all issues are no longer reproducible. 
Review @ivovandongen @zugaldia
> [android] - post invoking onMapReady to the end of the message queu

- platform/darwin/src/MGLStyle.h
- platform/ios/src/MGLMapView.h
- platform/macos/src/MGLMapView.h
jazzy is inconsistently converting straight apostrophes that immediately follow backticks into either `&lsquo;` or `&rsquo;` from one run to the next. Smarten the apostrophe to keep it stable.
/cc @boundsj
> Smarten apostrophes after backticks

- icu_dependency.pri
- mapbox-gl-native.pro
Take advantage of `qtConfig(icu)` provided via QMake to let Mapbox GL native know when to use the default ICU-based bidi pimpl over the stub Qt one.
> [Qt] Use ICU whenever available

- Makefile
While doing a git bisect or switching between master and release branches, 
I often hit `INSTALL_FAILED_VERSION_DOWNGRADE` when trying to run tests from the commandline;
> com.android.builder.testing.ConnectedDevice > runTests[Pixel - 7.1.1] FAILED 
com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_FAILED_VERSION_DOWNGRADE
at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:147)
FAILURE: Build failed with an exception.
To optimise the flow for developers not working with AS, I'm proposing to remove the current installed application before running any `make run-android-*` that are installed on an Android device.
> [android] - uninstall apk on device before running a make run-android-*

- Makefile
- platform/android/bitrise.yml
- platform/android/config.cmake
- platform/android/scripts/ndk.sh
We're currently downloading packaging and downloading the NDK via mason, but that adds download/unpacking overhead to every CI build, and burdens us with having to update the NDK.
Instead, we should use the NDK and CMake files provided with the NDK installed on the system.
> Use system NDK for building library

- Makefile
- cmake/NodeJS.cmake
- cmake/mbgl.cmake
- cmake/node.cmake
- package.json
- Removes need to run `npm install` before invoking CMake
> Use node-cmake 2.x

- src/mbgl/gl/segment.hpp
Follows `std::call_once` approach from 2ec2860ce5.
> [core] Use std::call_once to report about missing VAOs

- src/mbgl/tile/raster_tile.cpp
- src/mbgl/tile/raster_tile_worker.cpp
- test/tile/raster_tile.test.cpp
We're currently treating raster tiles that are "empty" or not found as valid by setting `DataAvailability::All`. Tiles that can't be found on the server and that return a 404 code are [treated as valid responses with no content ("empty")](https://github.com/mapbox/mapbox-gl-native/blob/10b8ef644188ee02cdce5b8db35fed1c32688758/platform/darwin/src/http_file_source.mm#L289).
While the concept of an "empty" tile makes sense for vector sources (denoting no features within that tile), it doesn't make sense for raster sources. Instead, we should fall back to lower zoom level tiles. Our [`updateRenderables`](https://github.com/mapbox/mapbox-gl-native/blob/10b8ef644188ee02cdce5b8db35fed1c32688758/src/mbgl/algorithm/update_renderables.hpp) algorithm takes care of loading these lower zoom level …
> Don't treat empty raster tiles as valid

- platform/linux/config.cmake
- platform/qt/config.cmake
gtest was broken because of lack of CXX11ABI support.
> [build] Fix build on Ubuntu 16.04+

- cmake/node.cmake
- platform/node/index.js
- platform/node/test/js/require.js
https://nodejs.org/api/addons.html#addons_building specifies that 
> The module_name must match the filename of the final binary (excluding the .node suffix)."
While the mismatch between `mapbox-gl-native` and `mapbox_gl_native` hasn't caused issues so far, we should play by the book. We use the [underscore version in our code](https://github.com/mapbox/mapbox-gl-native/blob/node-module-name/platform/node/src/node_mapbox_gl_native.cpp#L80), and can't change that one to dashes, since it must be a valid C identifier.
> Adhere to node module naming requirements

- include/mbgl/storage/default_file_source.hpp
- platform/default/default_file_source.cpp
- platform/glfw/glfw_view.cpp
- platform/glfw/glfw_view.hpp
- platform/glfw/main.cpp
- src/mbgl/util/thread.hpp
- test/util/thread.test.cpp
Make a thread completely halt and not process any message on the message queue until resume() is called.
Sending a sync message to a halted thread will result on a deadlock, thus the assertion.
Deleting a paused thread will trigger a resume.
> [core] Add pause/resume to the Thread class

- platform/default/bidi.cpp
As of C++11, it's safe to preallocate `std::[u16]string` and write to the buffer via `&s[0]` (C++17 makes it possible via `.data()` as well).
> [core] Avoid some string copies in bidi implementation

- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/text/glyph_atlas.cpp
- src/mbgl/text/glyph_atlas.hpp
- test/text/glyph_atlas.test.cpp
Fixes the `GlyphAtlas` equivalent of #6835.
> [core] Replace three maps/mutexes in GlyphAtlas with a single map and mutex

- include/mbgl/map/map.hpp
- platform/android/src/native_map_view.cpp
- platform/glfw/glfw_view.cpp
- src/mbgl/map/map.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
This PR enables to use AnimationOptions when performing a zoom/scale transformation (equivalent to #8092 for moveBy). This allows bindings to use an interpolator while doing a zoom/scale transformation.
To showcase the possibilities with this API, here is an example of the double tap zoom gesture using the `easeInOutBack` interpolator with an increased duration:
Note that atm I'm not changing the default behaviour for Android.
> [core] - allow zooming/scaling to use AnimationOptions

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs
https://github.com/mapbox/mapbox-gl-native/pull/7944 left some unit tests broken, the generation script generated invalid test assertions.
cc @anandthakker
> [android] fix unit tests for #7944

- .travis.yml
- cmake/test-files.cmake
- scripts/log_memory_benchmarks.sh
- test/src/mbgl/test/getrss.cpp
- test/src/mbgl/test/getrss.hpp
- test/util/memory.test.cpp
Even when we're passing this test, it can be very useful to have a log of the memory usage value, so that we can get a sense of the memory impact of new features and also to make sure that it's reasonable when we to increase the thresholds for these checks, when necessary.
Closes #8149  (leaving integration w/ the fancy nightly metrics graph for another day)
> [core] Log Memory.Footprint test results

- scripts/generate-shaders.js
- src/mbgl/shaders/circle.hpp
- src/mbgl/shaders/collision_box.hpp
- src/mbgl/shaders/debug.hpp
- src/mbgl/shaders/fill.hpp
- src/mbgl/shaders/fill_outline.hpp
- src/mbgl/shaders/fill_outline_pattern.hpp
- src/mbgl/shaders/fill_pattern.hpp
- src/mbgl/shaders/line.hpp
- src/mbgl/shaders/line_pattern.hpp
- src/mbgl/shaders/line_sdf.hpp
- src/mbgl/shaders/raster.hpp
- src/mbgl/shaders/symbol_icon.hpp
- src/mbgl/shaders/symbol_sdf.hpp
No need to include it; we only define char strings.
> Remove gl.hpp include from shaders

- platform/qt/include/qmapboxgl.hpp
- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qmapboxgl_p.hpp
- platform/qt/src/qquickmapboxglrenderer.cpp
We don't really need to handle FBO internally - FBO size is obtained via `QMapboxGL::resize` already and thus allows the client platform to have complete control over it.
> [Qt] FBO handling should happen outside of QMapboxGL::render

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java
This PR adds a java unit test for Mapbox and tests the following:
- accessToken validation
- enforcing applicationContext
- switching between Android Connectivity change events and manually managing them
Code coverage after adding the test:
> [android] - add unit test for Mapbox

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java
- platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
- platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml
- platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_preview.xml
- platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml
This PR optimises accessibility support for TalkBack by applying content description to all overlain View elements and removing `setClickable(true)` and `setLongClickable(true)` (these flags introduced some additional talkback responses while the map also works correctly without).
I have been looking into using an [AccesibilityDelegate](https://developer.android.com/reference/android/support/v4/view/ViewCompat.html#setAccessibilityDelegate) but it seems that they only support a limited amount of gestures. (click, longclick) and it's not possible to add custom ones. To work around this I added `mapbox_mapActionDescription ` which has a similar structure as the one generated by AccessibilityDelegateCompat.
> [android] - add accessibility support to the Android SDK 

- platform/ios/scripts/deploy-packages.sh
The previous incantation is now failing due to redirects. Getting only the headers from curl and checkin the first line works reliably.
cc @friedbunny
> [ios] Use curl to verify that a release is not published

- include/mbgl/util/traits.hpp
- platform/default/bidi.cpp
In environments where `Uchar*` cannot be implicitly convertible to `char16_t*` (e.g. when using a system-provided ICU in which `UCHAR_TYPE` was not defined in compile time), we need to safeguard parameter passing from `std::u16string` types.
> [core] Safeguard ICU UChar usage

- src/mbgl/geometry/anchor.hpp
- src/mbgl/layout/symbol_instance.cpp
- src/mbgl/layout/symbol_instance.hpp
- src/mbgl/layout/symbol_layout.hpp
- src/mbgl/text/check_max_angle.cpp
- src/mbgl/text/check_max_angle.hpp
- src/mbgl/text/collision_feature.cpp
- src/mbgl/text/collision_feature.hpp
- src/mbgl/text/get_anchors.cpp
- src/mbgl/text/get_anchors.hpp
- src/mbgl/text/quads.cpp
- src/mbgl/text/quads.hpp
Cosmetic stuff: fixing `&` placement, converting long parameter lists to one-parameter-per-line, etc.
> [core] Clean up symbol-related code

- platform/ios/src/MGLAnnotationView.h
- platform/ios/src/MGLAnnotationView.mm
- platform/ios/src/MGLAnnotationView_Private.h
- platform/ios/src/MGLMapView.mm
> [ios] MGLAnnotationView annotation property made writable

- CMakeLists.txt
- platform/android/config.cmake
> [all] Build all release builds with -Os

- platform/ios/CHANGELOG.md
- platform/ios/INSTALL.md
- platform/macos/CHANGELOG.md
- platform/macos/docs/pod-README.md
Fixes https://github.com/mapbox/mapbox-gl-native/issues/1623. ~~Does not address macOS.~~ @1ec5 added macOS instructions.
> Added basic notes about using Carthage

- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
- platform/android/build.gradle
- platform/android/dependencies.gradle
- platform/android/gradle/wrapper/gradle-wrapper.properties
Yesterday Google announced the official release of Android Studio 2.3.0.
This PR:
- updates the gradle version 
- updates the android gradle plugin
- updates to the latest support libraries
- adds configuration to improve build times (captured from Configure DEX options section in https://developer.android.com/studio/build/gradle-tips.html).
> [android] - Android Studio 2.3 stable

- platform/darwin/src/MGLStyle.mm
- platform/darwin/src/NSDate+MGLAdditions.h
- platform/darwin/src/NSDate+MGLAdditions.mm
- platform/darwin/test/MGLNSDateAdditionsTests.mm
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLMapView.mm
- platform/ios/test/MGLNSDateAdditionsTests.mm
- platform/macos/macos.xcodeproj/project.pbxproj
- platform/macos/src/MGLMapView.mm
- platform/macos/test/MGLNSDateAdditionsTests.mm
> [ios] duration to time interval fix

- include/mbgl/gl/gl.hpp
- platform/qt/config.cmake
- platform/qt/qt4.cmake
- platform/qt/qt5.cmake
- platform/qt/test/headless_backend_qt.cpp
OpenGL on Qt5 is offered via QtGui.
> [Qt] Remove legacy QOpenGL dependency from Qt5 build

- platform/darwin/src/MGLTypes.h
- platform/ios/src/MGLMapView.h
This pull request clarifies the documentation around `MGLUserTrackingModeFollowWithHeading` to include more detail. It also excludes the `MGLUserTrackingMode` enum from macOS.
cc @friedbunny
> Improve MGLUserTrackingMode docs and exclude from macOS

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
When relocating a selected point annotation, update the associated callout (iOS) or popover (macOS) to reflect the annotation’s new coordinates rather than deselecting the annotation.
Fixes #6284.
/cc @frederoni
> Update callout/popover when relocating annotation

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AddRemoveMarkerActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/ViewToBitmapUtil.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/view_custom_marker.xml
This PR adds an example on converting an Android SDK view to a Bitmap and using that for a SymbolAnnotation. Note that this is not an SDK feature but solely an example utility method. To use this on a larger scale/more dynamically we would need to implement some kind of [bitmap pooling/reuse](https://developer.android.com/topic/performance/graphics/manage-memory.html).
> [android] - example for converting View to Bitmap

- include/mbgl/util/event.hpp
Fixed a typo in 3ae506ee1301bcc3f9961a9282f710b8b7fa8039 for #5359 that suppressed debug events in debug builds and enabled them in release builds.
/cc @anandthakker
> Enable debug events in Debug configuration

- src/mbgl/style/source_impl.cpp
- src/mbgl/style/source_impl.hpp
- src/mbgl/style/style.cpp
> [core] clear source when removed from style

- platform/ios/CHANGELOG.md
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/resources/Base.lproj/Localizable.strings
- platform/ios/resources/ja.lproj/Localizable.strings
- platform/ios/scripts/deploy-packages.sh
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLSDKUpdateChecker.h
- platform/ios/src/MGLSDKUpdateChecker.mm
Implements #7311 for iOS. This adds a check that the developer is using the latest stable release of our iOS SDK and, if not, prints a note to console with a link to the new release.
Inspired by [Realm’s update check](https://github.com/realm/realm-cocoa/blob/216333cf82e1afcba5e6c4547e6fb983165d510f/Realm/RLMUpdateChecker.mm). 🙇 
- Only runs if using the simulator — method is a no-op anywhere else, including Swift Playgrounds.
- Version comparison is extremely simple and ignores semver — if the version strings don’t match, it assumes the developer needs to upgrade.
- Deploy script uploads a text file to http://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/latest_version with the version in format: `x.x.x`
- @mick Is s3 the best location for this link? Would it be better on …
> [ios] Add SDK version update checking/notification

- platform/ios/src/MGLMapViewDelegate.h
- platform/macos/src/MGLMapViewDelegate.h
Added a sentence to `regionIsChanging` and `regionDidChangeAnimated` to state that these delegate methods can be called before the map view has finished loading.
> [ios] Added a timing note for two delegate methods

- platform/macos/src/MGLMapView.mm
Adds two methods I forgot to add in #8246 when adding predicate options to `visibleFeaturesIn*`.
> [macos] add missing method declarations for visibleFeaturesX

- platform/darwin/resources/ca.lproj/Foundation.strings
- platform/darwin/resources/ca.lproj/Foundation.stringsdict
- platform/darwin/resources/lt.lproj/Foundation.strings
- platform/darwin/resources/lt.lproj/Foundation.stringsdict
- platform/darwin/resources/pl.lproj/Foundation.stringsdict
- platform/darwin/resources/ru.lproj/Foundation.stringsdict
- platform/darwin/resources/uk.lproj/Foundation.stringsdict
- platform/ios/CHANGELOG.md
- platform/ios/framework/Settings.bundle/ca.lproj/Root.strings
- platform/ios/framework/Settings.bundle/fi.lproj/Root.strings
- platform/ios/framework/Settings.bundle/nl.lproj/Root.strings
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/resources/ca.lproj/Localizable.strings
- platform/ios/resources/ca.lproj/Localizable.stringsdict
- platform/ios/resources/ru.lproj/Localizable.strings
- platform/ios/resources/ru.lproj/Localizable.stringsdict
- platform/macos/CHANGELOG.md
- platform/macos/macos.xcodeproj/project.pbxproj
- platform/macos/sdk/ca.lproj/Localizable.strings
- platform/macos/sdk/fi.lproj/Localizable.strings
- platform/macos/sdk/nl.lproj/Localizable.strings
- platform/macos/sdk/ru.lproj/Localizable.strings
Pulled the latest translations from Transifex to complete the Russian and Lithuanian localizations and add Catalan, Finnish (partial), and Dutch (partial) localizations. For declension of angular measures, I consulted [this CLDR chart](http://www.unicode.org/cldr/charts/latest/by_type/units.other_units.html#degree).
/cc @eimantas @rroset @tobrun
> Russian, Catalan, Lithuanian, Finnish, Dutch

- scripts/generate-shaders.js
- src/mbgl/gl/attribute.cpp
- src/mbgl/gl/attribute.hpp
- src/mbgl/programs/attributes.hpp
- src/mbgl/programs/program.hpp
- src/mbgl/shaders/circle.cpp
- src/mbgl/shaders/fill.cpp
- src/mbgl/shaders/fill_outline.cpp
- src/mbgl/shaders/fill_outline_pattern.cpp
- src/mbgl/shaders/fill_pattern.cpp
- src/mbgl/shaders/line.cpp
- src/mbgl/shaders/line_pattern.cpp
- src/mbgl/shaders/line_sdf.cpp
- src/mbgl/shaders/symbol_icon.cpp
- src/mbgl/shaders/symbol_sdf.cpp
- src/mbgl/style/paint_property_binder.hpp
- Rename `MinMax` attribute to `ZoomInterpolatedAttribute`, signaling
intent to use it only for composite functions. The idea is that
source functions will bind the base `Attribute` instead, so as not to
use double-sized vertex buffers.
- Change the attribute name string in ^ from `a_{name}_minmax` to just
`a_{name}`, to match the base attributes, and update the shaders to
match.  (We're only ever binding the base one or the ZoomInterpolated
one, never both.)
- Change the specific `*PaintPropertyBinder` types and the general `PaintPropertyBinder` type to use the base attribute for non-composite-function values and the `ZoomInterpolatedAttribute<>` for composite-function values.  **🚧 I think this is the part that I don't have quite right.**
cc @jfirebaugh @mollymerp  (note that this PR is …
> WIP Avoid using double-sized buffers for source functions

- include/mbgl/style/property_value.hpp
- src/mbgl/style/paint_property.hpp
- test/style/paint_property.test.cpp
> For data-driven paint setters, transition immediately to target value

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
> [android] - don't disable tracking when animating the camera bearing.

- scripts/publish_binary_size.sh
We currently publish the most recent 30 days, which doesn't seem enough.
https://github.com/mapbox/mapbox-gl-native/issues/8035#issuecomment-285089819
> Increase binary size duration chart to 60 days

- platform/android/config.cmake
- platform/ios/config.cmake
- platform/linux/config.cmake
- platform/macos/config.cmake
- platform/qt/config.cmake
Example size savings for macOS:
```
VM SIZE                              FILE SIZE
++++++++++++++ GROWING                ++++++++++++++
+2.4% +3.93Ki [None]                 +3.14Ki  +1.8%
+0.5%    +344 __TEXT,__unwind_info      +344  +0.5%
+1.2%     +24 __DATA,__got               +24  +1.2%
+0.0%     +16 __TEXT,__const             +16  +0.0%
-------------- SHRINKING              --------------
-2.0% -52.2Ki __TEXT,__text          -52.2Ki  -2.0%
-0.3%     -80 __DATA,__const             -80  -0.3%
-0.2%     -10 __TEXT,__stub_helper       -10  -0.2%
-0.2%      -8 __DATA,__la_symbol_ptr       0  [ = ]
-0.2%      -6 __TEXT,__stubs              -6  -0.2%
-1.3% -48.0Ki TOTAL                  -48.8Ki  -1.3%
```
Refs #8035.
> Use ICU compiled with -Os

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
This PR fixes two issues: 
- not activating/deactivating the LocationSource when toggling MyLocationView state, we aren't receiving any location updates atm.
- incorrect accuracy circle width (closes #6084).
> MyLocationView activate/deactivate LocationSource

- scripts/generate-shaders.js
- src/mbgl/gl/attribute.cpp
- src/mbgl/gl/attribute.hpp
- src/mbgl/programs/attributes.hpp
- src/mbgl/programs/symbol_program.hpp
- src/mbgl/shaders/circle.cpp
- src/mbgl/shaders/fill.cpp
- src/mbgl/shaders/fill_outline.cpp
- src/mbgl/shaders/fill_outline_pattern.cpp
- src/mbgl/shaders/fill_pattern.cpp
- src/mbgl/shaders/line.cpp
- src/mbgl/shaders/line_pattern.cpp
- src/mbgl/shaders/line_sdf.cpp
- src/mbgl/shaders/preludes.cpp
- src/mbgl/shaders/symbol_icon.cpp
- src/mbgl/shaders/symbol_sdf.cpp
- src/mbgl/style/paint_property_binder.hpp
fixes #8183 
related gl-js PR: https://github.com/mapbox/mapbox-gl-js/pull/4363
@anandthakker and I worked on this for the past couple days 🤖
cc @jfirebaugh
> [core] Reduce number of vertex attributes passed to shaders

- platform/darwin/src/MGLFoundation.mm
- platform/darwin/src/MGLFoundation_Private.h
- platform/darwin/src/MGLOfflineStorage.mm
We should explicitly initialize rather than use a global static variables for the main thread's `RunLoop`.
When linking Mapbox GL as a static library, the object file (MGLFoundation.o) containing the global static variable initialization was not linked into the resulting binary since it was not referenced. This resulted in the RunLoop not being initialized in the main thread.
Reverts 03a14ff0003e976a4ded70d284bc80adf54bc6c9 in  https://github.com/mapbox/mapbox-gl-native/pull/8084
> Darwin static libs: don't rely on static variable initialization

- benchmark/parse/filter.benchmark.cpp
- src/mbgl/style/tile_source_impl.cpp
- test/style/conversion/function.test.cpp
- test/style/filter.test.cpp
``` 
VM SIZE                                                                                        FILE SIZE
++++++++++++++ GROWING                                                                          ++++++++++++++
+0.9%      +6 mbgl::style::conversion::Result<mapbox::util::variant<std::__1::basic_string<cha      +6  +0.9%
-------------- SHRINKING                                                                        --------------
[DEL] -2.41Ki mbgl::style::conversion::Result<mbgl::Tileset> mbgl::style::conversion::Converte -2.41Ki  [DEL]
-0.3% -1.43Ki [None]                                                                           -1.49Ki  -0.3%
-32.6%    -172 GCC_except_table104                                                                 -172 -32.6%
-0.1%      -2 …
```
> [core] Avoid unnecessary convert template instantiations

- cmake/core-files.cmake
- src/mbgl/programs/program.hpp
- src/mbgl/shaders/shaders.cpp
- src/mbgl/shaders/shaders.hpp
```
VM SIZE                               FILE SIZE
++++++++++++++ GROWING                 ++++++++++++++
+0.1%     +16 __DATA,__data               +16  +0.1%
-------------- SHRINKING               --------------
-0.8% -19.9Ki __TEXT,__text           -19.9Ki  -0.8%
-1.2% -3.61Ki __TEXT,__gcc_except_tab -3.61Ki  -1.2%
-0.7%    -468 __TEXT,__unwind_info       -468  -0.7%
-0.0%     -32 [None]                     -416  -0.2%
-0.0%     -16 __TEXT,__const              -16  -0.0%
-0.7% -24.0Ki TOTAL                   -24.4Ki  -0.7%
```
Refs #8035.
> [core] Extract and de-templatize several Program static methods

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BasePointCollection.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Polygon.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Polyline.java
This PR renames `MultiPoint` to `BasePointCollection` to avoid name clashing with the actual GeoJSON object, which we also support via [`mapbox-java-geojson`](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libjava-geojson/src/main/java/com/mapbox/services/commons/geojson/MultiPoint.java)
Fixes https://github.com/mapbox/mapbox-gl-native/issues/3288.
> [android] Renames MultiPoint to BasePointCollection

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewContainer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/IconManager.java
- platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml
Closes #8236, refs # 8159 #5388 #5639
This PR moves touch handling of MarkerViews back to View#setOnClickListener and fixes the issue with the original implementation as shown in #5388.
This change is motivated by 2 items:
- better UX for users, as we are hooking into the platform default way of handling touch events 
- better touch target surface (see #8159)
> Move MarkerView click handling back to View#setOnClickListener

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/MaxMinZoomActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java
Closes #8262. 
This PR adds a style loading callback that is invoked when the style has finished loading.
> [android] - add style loading callback 

- platform/android/bitrise.yml
- platform/ios/bitrise.yml
- platform/macos/bitrise.yml
- platform/node/bitrise.yml
- platform/qt/bitrise-qt4.yml
- platform/qt/bitrise-qt5.yml
Replaces #6525. Fixes #6523.
Bitrise's [built in](http://devcenter.bitrise.io/tips-and-tricks/skip-a-build/) feature seems to be buggy, in that it ran three of the five builds even though the commit was tagged `[skip ci]`. But since our workaround was pretty poor (the builds still ran, they just did less), and we rarely skip builds, let's just remove it anyway.
> [build] Remove custom bitrise 'skip ci' stuff

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_debug_mode.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
Follow up from #7630 (but now covers all interactions)
Android equivalent of iOS PR in https://github.com/mapbox/mapbox-gl-native/pull/8027
Besides zooming to rounded zoom levels, this PR also fixes the issue of not getting the final value during OnCameraChange event. Without this change I was receiving zoom levels that just not hit the actual value ( eg. 0.9999988 instead of 1.0).
> [android] - zoom to rounded levels

- platform/darwin/src/MGLStyleValue_Private.h
This exception message had a typo; developers would’ve been advised to use a method that doesn’t exist, due to case sensitivity. Moreover, the method has been renamed since this message was written.
Fixes #7994.
> Fix camera function exception message

- platform/ios/src/MGLAnnotationView.mm
- platform/ios/src/MGLMapView.mm
Raises an exception outlining the problem.
> Raise exception when MGLAnnotationView.annotation property is nil

- platform/darwin/src/MGLPolyline.mm
- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
Now that annotation classes override `-isEqual:`, it’s no longer appropriate to rely on `-isEqual:` or `-containsObject:` to check for the preexistence of an annotation. Those methods become deep equality tests, which have worse performance. Checking for identity allows the developer to add a polyline and polygon with identical coordinates, title, etc. to the map.
Implemented a missing `-[MGLPolyline isEqual:]`.
Removed outdated comments about `-annotationTagForAnnotation:` being expensive, which is no longer true as of #6957.
Fixes #7811.
> Fixed polyline equality

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BubbleLayout.java
Lint is complaining about the visibility of `BubbleLayout`:
```
:MapboxGLAndroidSDKTestApp:compileReleaseSources
/bitrise/src/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BubbleLayout.java:38: Error: This class should be public (com.mapbox.mapboxsdk.annotations.BubbleLayout) [Instantiatable]
public BubbleLayout(Context context, AttributeSet attrs, int defStyleAttr) {
~~~~~~~~~~~~
Explanation for issues of type "Instantiatable":
Activities, services, broadcast receivers etc. registered in the manifest
file (or for custom views, in a layout file) must be "instantiatable" by
the system, which means that the class must be public, it must have an
empty public constructor, and if it's an inner class, it must be a static
inner class.
1 errors, 0 warnings
``` …
> [android] Make BubbleLayout public

- platform/ios/CHANGELOG.md
- platform/ios/INSTALL.md
- platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
- platform/ios/bitrise.yml
- platform/ios/scripts/deploy-nightly.sh
- platform/ios/scripts/publish.sh
Fixes #4196. Uploads a nightly build to s3 and makes it available via a special podspec.
- Dynamic framework, stripped release build only for now.
- Piggy-backs on @kkaefer’s binary size metrics Bitrise workflow that already runs nightly.
- Uploads both to a [date-versioned file]( https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-nightly-dynamic-2017-03-09.zip) and overwrites a [stable URL file]( https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-nightly-dynamic.zip).
- Adds a `Mapbox-iOS-SDK-nightly-dynamic` podspec that points to the latest nightly.
Use this line in your podfile to test this branch:
```
pod 'Mapbox-iOS-SDK-nightly-dynamic', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/fb-publish-nightly/platform/i …
```
> [ios] Publish nightly build

- platform/darwin/src/MGLStyle.mm
- platform/macos/src/MGLMapView.mm
Suppressed unused variable warnings in Release configuration that occurred because they were only used within `NSAssert()` invocations, which are omitted from Release builds.
> Suppress unused variable warnings

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
Enables the one-finger quick-zoom gesture on iPad. We had been specifically limiting this gesture to the iPhone, but it makes sense to consistently offer this gesture on all iOS devices (as Google does).
/cc @jmkiley
> [ios] Enable one-finger quick-zoom gesture on iPad

- src/mbgl/util/compression.cpp
It will redefine mbgl::util::compress to mbgl::util::z_compress and
cause a link error. Aka pre-processor hell.
> [build] Fix build when using a Z_PREFIX zlib

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
> [android] don’t crash on map changed callback when OnMapChangedListener throws a runtime exception

- cmake/test-files.cmake
- src/mbgl/annotation/annotation_tile.hpp
- src/mbgl/tile/geometry_tile.cpp
- test/tile/annotation_tile.test.cpp
fixes #8289
We could make this check more granular since the `FeatureIndex` is still usable in this case, but since it's an edge case, I don't know if it's worth it.
> [core] don’t use stale collision tile in feature queries

- platform/android/config.cmake
- platform/android/version-script
Cherry-picks 78d6d07d57d8b2f9a5aa25f9f84cc18b6d3b90e6 to the release branch.
> [android] Link with a version script to restrict symbol visibility

- platform/node/src/node_request.cpp
- platform/node/src/node_request.hpp
- platform/node/test/memory.test.js
- platform/node/test/mockfs.js
Replies are assumed to be asynchronous after e3500c1f791be82.
> [node] Fix memory test hanging after GlyphAtlas refactoring

- platform/darwin/src/MGLShapeSource.h
- platform/darwin/src/MGLTileSource.h
- platform/darwin/src/MGLVectorSource.h
- platform/ios/src/MGLMapView.h
- platform/macos/src/MGLMapView.h
Copyedited and expanded documentation about visible feature querying and source feature querying. Linked the two APIs together. Now that runtime styling is supported, visible feature querying documentation can talk about MGLSource subclasses instead of linking out to the style specification.
A possible future improvement would be factoring this documentation out into the MGLMapView class documentation comment or even a jazzy guide. That would require some code examples and screenshots, so that can happen for a later release.
Also fixed a couple incorrect Swift method names on macOS.
/cc @jmkiley @ivovandongen
> Expand feature querying documentation

- package.json
- platform/node/scripts/after_success.sh
Since https://github.com/mapbox/mapbox-gl-native/commit/6b0ad899b3ced4932cf600a4f89b2609512c98be changed the module name, pre gyp was looking for node bindings `mapbox-gl-native` instead of `mapbox_gl_native`.
Also checks whether the build is a release or not instead whether its a debug build.
> [node] Fix module_name, check if release

- platform/node/bitrise.yml
This cleans up the node bitrise builds. Most notably, it adds `export BUILDTYPE=Release` which verifies we're creating Release binaries and not debug.
> [node] Cleanup bitrise.yml; split test/publish workflows

- cmake/core-files.cmake
- include/mbgl/map/backend.hpp
- include/mbgl/map/map.hpp
- include/mbgl/map/map_observer.hpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/default/mbgl/gl/headless_backend.cpp
- platform/default/mbgl/gl/headless_backend.hpp
- platform/glfw/glfw_view.cpp
- platform/glfw/glfw_view.hpp
- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
- platform/node/src/node_map.cpp
- platform/node/src/node_map.hpp
- platform/qt/include/qmapboxgl.hpp
- platform/qt/src/qmapbox.cpp
- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qmapboxgl_p.hpp
- src/mbgl/map/backend.cpp
- src/mbgl/map/map.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
- test/map/map.test.cpp
- test/map/transform.test.cpp
- test/tile/tile_coordinate.test.cpp
Implements `mbgl::MapObserver`, replacing `mbgl::MapChange` enumerator and `mbgl::Backend::notifyMapChange`. Now `mbgl::Backend` inherits from `mbgl::MapObserver`, which provides non-pure virtual equivalents for the enumerator items.
Caveats:
- Qt preserves the `QMapboxGL::MapChange` enumerator from the public API.
- Android refactor still requires `mbgl::MapChange` - this is not necessary but finishing up this platform refactor can happen on a separate PR. Once we finish cleaning up the Android platform, then we can safely remove `mbgl::MapChange` source code entirely.
Added suggested reviewers for platform-specific patches as well as core changes - please replace yourself with someone else from the mobile team otherwise.
Fixes #6383.
> [core] Replace mbgl::MapChange with mbgl::MapObserver

- include/mbgl/style/layers/custom_layer.hpp
- platform/node/bitrise.yml
- src/mbgl/style/layers/custom_layer.cpp
Fixes:
```
module.js:434
return process.dlopen(module, path._makeLong(filename));
^
Error: dlopen(/Users/john/Development/mapbox-gl-native/lib/mapbox_gl_native.node, 1): Symbol not found: __ZNK4mbgl5style5Layer2isINS0_11CustomLayerEEEbv
Referenced from: /Users/john/Development/mapbox-gl-native/lib/mapbox_gl_native.node
Expected in: flat namespace
in /Users/john/Development/mapbox-gl-native/lib/mapbox_gl_native.node
at Error (native)
at Object.Module._extensions..node (module.js:434:18)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/Users/john/Development/mapbox-gl-native/platform/node/index.js:5:12)
at Module._compile (module.js:409:26)
at …
```
> [node] Work around a link error on macOS release builds

- src/mbgl/renderer/circle_bucket.cpp
- src/mbgl/renderer/fill_bucket.cpp
- src/mbgl/renderer/line_bucket.cpp
- src/mbgl/renderer/symbol_bucket.cpp
- src/mbgl/style/paint_property_binder.hpp
```
VM SIZE                               FILE SIZE
++++++++++++++ GROWING                 ++++++++++++++
+2.0% +4.72Ki __TEXT,__const          +4.72Ki  +2.0%
+14% +3.31Ki __DATA,__data           +3.31Ki   +14%
-------------- SHRINKING               --------------
-1.8% -45.5Ki __TEXT,__text           -45.5Ki  -1.8%
-0.5%    -783 [None]                  -1.88Ki  -1.1%
-26.6%    -736 __DATA,__bss                  0  [ = ]
-0.5%    -453 __TEXT,__cstring           -453  -0.5%
-0.6%    -432 __TEXT,__unwind_info       -432  -0.6%
-0.1%    -148 __TEXT,__gcc_except_tab    -148  -0.1%
-0.2%     -10 __TEXT,__stub_helper        -10  -0.2%
-0.2%      -8 __DATA,__la_symbol_ptr        0  [ = ]
-0.2%      -6 __TEXT,__stubs               -6  -0.2%
-1.1% -40.0Ki TOTAL                   -40.4Ki  -1.1%
``` …
> [core] Replace variant with polymorphic PaintPropertyBinder class

- src/mbgl/style/style.cpp
See https://github.com/mapbox/mapbox-gl-native/issues/8433#issuecomment-287193423 for the problem outline. This instead always updates the need to iterate on transitions even when layers are skipped in a render pass because they aren't yet iterated from non-visibility. Hat tip to @jfirebaugh for the succinct patch. 
/cc @boundsj @fabian-guerra @1ec5 @ericrwolfe
> fixes #8433: lack of fade in transitions

- platform/ios/bitrise.yml
Posts a notification to #gl-bots on Slack that reports the success/failure of the nightly iOS Bitrise workflow.
(Note that I already added this through Bitrise’s web interface as a test run for tonight — will remove that once this is merged.)
/cc @boundsj @kkaefer
> [build] Post nightly iOS build status to Slack

- cloudformation/travis.template
Fixes #8364 by giving the Bitrise aws user permission to upload to `s3://mapbox/mapbox-gl-native/ios/builds/`.
> [build] Give ios/builds s3 permission to Bitrise user

- include/mbgl/map/map_observer.hpp
- include/mbgl/util/exception.hpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/darwin/src/MGLTypes.h
- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
- platform/node/src/node_map.cpp
- platform/node/src/node_map.hpp
- platform/node/test/js/map.test.js
- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qmapboxgl_p.hpp
- src/mbgl/map/map.cpp
- src/mbgl/style/observer.hpp
- src/mbgl/style/style.cpp
- test/map/map.test.cpp
Forwards the ~error type and message~ `std::exception_ptr` from style::Observer::onStyleError as well as non-style related errors.
As per @1ec5 comments in #8398:
> This would allow all the SDKs – not only the iOS and macOS SDKs – to provide more information when the map fails to load for some reason.
Fixes #8398.
> Pass std::exception_ptr in MapObserver::onDidFailLoadingMap

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
> [android] - fix LOST location updates

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Annotation.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/ConversionException.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/InvalidMarkerPositionException.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/package-info.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonOptions.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterSource.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/TileSet.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/VectorSource.java
Closes #8322, @langsmith I went ahead and started the cleanup of the JavaDoc, Feel free tor review and make edits. (note that some files are generated from the style specification and the content from these shouldn't be changed in this repo, you can identify these with `// This file is generated.` at the top of the file ).
> 8322 javadoc 5.0.0 release

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewContainer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java
> [android] - only dispatch events if not handled by MarkerView

- platform/android/CHANGELOG.md
Updates CHANGELOG.md with changes for the 5.0.0 release.
> [android] - update CHANGELOG.md for 5.0.0 release

- platform/macos/bitrise.yml
`apt-get install` commands were present when the nightly build was introduced. Prior to 12b99f0085c15ed59d10b6cc2003e6ee367bdce3 they were in a separate section without `set -eu -o pipefail`, so the error was ignored. I assume they are not needed, since the build was succeeding despite the error.
While here, ensure xcpretty is installed.
Fixes #8458
> [macos] Fix nightly build script

- platform/ios/CHANGELOG.md
- platform/ios/resources/Base.lproj/Localizable.strings
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/sdk/Base.lproj/Localizable.strings
- platform/macos/src/MGLMapView.mm
Ensured the uniqueness of localizable string IDs added in #8418 to unbreak `make genstrings`. Ran `make genstrings` to add the `-[MGLMapViewDelegate mapViewDidFailToLoad:withError:]` error description strings to the base localization.
Moved the changelog entries for #8418 to new sections, since #8418 won’t make it into either iOS SDK v3.5.x or macOS SDK v0.4.x.
> Fix map load error descriptions

- include/mbgl/storage/default_file_source.hpp
- platform/darwin/src/MGLOfflineStorage.mm
Fixes https://github.com/mapbox/mapbox-gl-native/issues/8464
Calls to the file source pause and resume method are triggered by UIApplicationDidEnterBackgroundNotification and UIApplicationWillEnterForegroundNotification notifications. Testing has shown that those notifications may happen more than once on device. This adds a local guard to protect against unbalanced calls to pause and resume.
> Guard against over calling pause or resume

- platform/ios/scripts/deploy-packages.sh
- platform/ios/src/MGLSDKUpdateChecker.mm
Decouple the version checker (https://github.com/mapbox/mapbox-gl-native/pull/8282) updating from the deploy process. File is now hosted on the ios-sdk site.
/cc @1ec5 @boundsj
> [ios, build] Change version checker URL to ios-sdk site

- include/mbgl/style/source.hpp
- src/mbgl/annotation/annotation_source.cpp
- src/mbgl/annotation/annotation_source.hpp
- src/mbgl/style/source.cpp
- src/mbgl/style/source_impl.hpp
- src/mbgl/style/sources/geojson_source_impl.cpp
- src/mbgl/style/sources/geojson_source_impl.hpp
- src/mbgl/style/tile_source_impl.cpp
- src/mbgl/style/tile_source_impl.hpp
- test/style/source.test.cpp
Expose `Source::getZoomRange` as part of `Source` public API, also marking it `const`.
Part of #6584.
> [core] Expose Source::getZoomRange

- platform/darwin/src/MGLStyle.h
Unless I'm mistaken, transitions via `-[MGLMapView setStyleURL:]` are not currently supported.
/cc @1ec5 @incanus
> [ios][macos] Document that transitions using setStyleURL are not supported

- include/mbgl/map/map_observer.hpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/macos/src/MGLMapView.mm
- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qmapboxgl_p.hpp
- src/mbgl/map/map.cpp
- src/mbgl/style/source_observer.hpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style.hpp
- src/mbgl/style/tile_source_impl.cpp
- test/src/mbgl/test/stub_style_observer.hpp
- test/style/source.test.cpp
Rename `MapObserver::onSourceDidChange` to `MapObserver::onSourceAttributionChanged`, passing both `sourceID` and `attribution` as strings.
Fixes #8397.
> Pass source object in MapObserver::onSourceChanged

- src/mbgl/annotation/annotation_manager.hpp
- src/mbgl/gl/context.hpp
- src/mbgl/layout/symbol_layout.hpp
- src/mbgl/renderer/circle_bucket.hpp
- src/mbgl/renderer/fill_bucket.hpp
- src/mbgl/renderer/line_bucket.hpp
- src/mbgl/renderer/symbol_bucket.cpp
- src/mbgl/renderer/symbol_bucket.hpp
- src/mbgl/style/paint_property.hpp
- src/mbgl/tile/geometry_tile_worker.hpp
- src/mbgl/tile/vector_tile.cpp
- test/tile/vector_tile.test.cpp
Replacement for #8426.
```
VM SIZE                               FILE SIZE
++++++++++++++ GROWING                 ++++++++++++++
+0.1%     +92 __TEXT,__unwind_info        +92  +0.1%
-------------- SHRINKING               --------------
-1.0% -25.7Ki __TEXT,__text           -25.7Ki  -1.0%
-2.9% -4.80Ki [None]                  -1.12Ki  -0.7%
-0.5% -1.55Ki __TEXT,__gcc_except_tab -1.55Ki  -0.5%
-0.0%     -48 __TEXT,__const              -48  -0.0%
-0.9% -32.0Ki TOTAL                   -28.3Ki  -0.8
```
Refs #8035
> [core] Prefer std::map to std::unordered_map for smaller binary size

- include/mbgl/style/source.hpp
- src/mbgl/annotation/annotation_source.cpp
- src/mbgl/annotation/annotation_source.hpp
- src/mbgl/style/source.cpp
- src/mbgl/style/source_impl.cpp
- src/mbgl/style/source_impl.hpp
- src/mbgl/style/sources/geojson_source_impl.cpp
- src/mbgl/style/sources/geojson_source_impl.hpp
- src/mbgl/style/tile_source_impl.cpp
- src/mbgl/style/tile_source_impl.hpp
- test/style/source.test.cpp
Based on https://github.com/mapbox/mapbox-gl-native/pull/8472#discussion_r107035011 - we want to have the return value from `Source::getZoomRange` optional e.g. in all `Source` implementations except annotation, we'll return a valid zoom range only after the source has been loaded.
> Make Source::getZoomRange return an optional range

- platform/qt/app/mapwindow.cpp
- platform/qt/include/qmapboxgl.hpp
- platform/qt/qt4.cmake
- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qmapboxgl_p.hpp
- platform/qt/test/qmapboxgl.cpp
Our renderer sometimes needs to rebind the originally bound framebuffer, and does so by calling `view.bind()`. This is currently implemented as binding FBO 0 in all cases, but this is incorrect because it depends on the Widget implementation that we're rendering to: `QGLWidget` uses a default FBO of 0, but `QOpenGLWidget` doesn't and returns the correct FBO with `defaultFramebufferObject()`. We need a way for implementations to supply the correct FBO and update the sample application accordingly.
> Qt: Correctly restore FBOs

- cmake/core-files.cmake
- cmake/test-files.cmake
- include/mbgl/map/map.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- proto/binary_program.proto
- src/mbgl/gl/attribute.hpp
- src/mbgl/gl/context.cpp
- src/mbgl/gl/context.hpp
- src/mbgl/gl/features.hpp
- src/mbgl/gl/program.hpp
- src/mbgl/gl/program_binary.cpp
- src/mbgl/gl/program_binary.hpp
- src/mbgl/gl/types.hpp
- src/mbgl/gl/uniform.hpp
- src/mbgl/map/map.cpp
- src/mbgl/programs/binary_program.cpp
- src/mbgl/programs/binary_program.hpp
- src/mbgl/programs/program.hpp
- src/mbgl/programs/program_parameters.hpp
- src/mbgl/programs/programs.hpp
- src/mbgl/renderer/painter.cpp
- src/mbgl/renderer/painter.hpp
- src/mbgl/shaders/shaders.cpp
- src/mbgl/shaders/shaders.hpp
- src/mbgl/util/io.cpp
- src/mbgl/util/io.hpp
- test/programs/binary_program.test.cpp
On some Android devices, compiling shaders contributes significantly to slow renderer initialization time. We've [previously attempted to use compiled shaders](https://github.com/mapbox/mapbox-gl-native/issues/588), but removed it in https://github.com/mapbox/mapbox-gl-native/pull/778. It's time to reconsider.
Most Android devices seem to support [`GL_OES_get_program_binary`](https://www.khronos.org/registry/OpenGL/extensions/OES/OES_get_program_binary.txt), while macOS and iOS devices do not. However, we haven't identified slow shader compiles as a problem on these platforms.
> Reconsider compiled shader programs

- .travis.yml
- Makefile
- platform/qt/bitrise-qt4.yml
- scripts/check-qt.sh
Detects the Qt version based on the `qmake` found in the user path - we'll no longer need to specify `WITH_QT_4=1` when e.g. building using Qt 4.
> [build] Autodetect Qt{4,5}

- include/mbgl/map/camera.hpp
- include/mbgl/map/map.hpp
- include/mbgl/util/geo.hpp
- src/mbgl/map/map.cpp
- src/mbgl/map/transform.hpp
- test/map/map.test.cpp
Naïve solution for `Map::latLngBoundsForCamera` using a copy of `Transform` to calculate the shallow state.
Ref: #8499.
> [core] Added Map::latLngBoundsForCamera

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
> [android] - correct anchoring when Icon is updated

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionDefinition.java
- platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
- platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java
> [android] - harden offline region creation / update LatLngBounds

- docker/bitrise/android/Dockerfile
- platform/android/bitrise.yml
This PR intents to lower the build time we spend on the Android/Bitrise app. We are past the 25 minute mark, but most of that time is spent downloading Gradle dependencies and installing other dependencies.
Instead, we can use a pre-built Docker image that contains most of these things. While we're at it, we can also add `ccache` to increase compilation times. Our builds are already switched to using `mbgl/android:latest` instead of `bitriseio/android-ndk:latest` and build time has decreased from 26 minutes to just 10 minutes, including Firebase tests.
Bitrise updates their base image every Saturday, so we'll have to add a scheduled build that updates our image to avoid pulling the old Bitrise image. This conenviently lets us refresh our primed `ccache`.
> Use prebuilt Docker image for Android/Bitrise

- platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
- platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_infowindow_content.xml
- platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml
Refs https://github.com/mapbox/mapbox-gl-native/issues/8155, Preparation work for integrating transfix into the Android code. 
- mark non-translatable resources 
- remove debug string resources  
- expose strings in public.xml for resource overloading.
> Prepare String resources for Transifex integration

- src/mbgl/text/quads.cpp
h/t @ChrisLoer catching this place where we were relying on member
initialization order.  While it _happened_ to be okay here, it's
unnecessarily fragile.
> Small edit to improve code resiliency

- include/mbgl/style/conversion/make_property_setters.hpp
- include/mbgl/style/layers/symbol_layer.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
- platform/darwin/src/MGLSymbolStyleLayer.h
- platform/darwin/src/MGLSymbolStyleLayer.mm
- platform/darwin/test/MGLSymbolStyleLayerTests.mm
- platform/node/src/node_map.cpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/shaders/circle.cpp
- src/mbgl/shaders/debug.cpp
- src/mbgl/shaders/fill.cpp
- src/mbgl/shaders/fill_outline.cpp
- src/mbgl/shaders/line.cpp
- src/mbgl/shaders/line_sdf.cpp
- src/mbgl/shaders/symbol_sdf.cpp
- src/mbgl/style/layers/symbol_layer.cpp
- src/mbgl/style/layers/symbol_layer_properties.hpp
- src/mbgl/text/glyph_set.cpp
> [core] implement dds for text-offset

- platform/ios/src/MGLMapView.mm
Fixes #8163 while this is only a nil check, we need to continue investigating why `annotationContext.annotation` is nil when calling `visibleAnnotationsInRect`
> [ios] Crash fix on render with view-backed annotations

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapViewDelegate.h
Fixes https://github.com/mapbox/mapbox-gl-native/issues/8420
`- (nullable UIView <MGLCalloutView> *)mapView:(MGLMapView *)mapView calloutViewForAnnotation:(id <MGLAnnotation>)annotation;` bridges with a `UIView?` return type in Swift. This changes replaces the `UIView` type in the method signature so that, when bridged to Swift, the returned object is defined as `MGLCalloutView?`.
> [ios] Modify return type so callout bridges with protocol in Swift

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java
- platform/android/src/native_map_view.cpp
> [android] - Style wide transition options in milliseconds

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/FeatureOverviewActivity.java
closes #8424 
@Guardiola31337 I went a head a patched this up, needed this for testing. Feel free to tackle improvements related to requesting runtime permissions in the test app in a separate ticket.
> [android] - fixup location permissions pre Android Marshmallow

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/storage/UrlTransformActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
- platform/android/src/file_source.cpp
> Fix resource transform callback

- .tx/config
- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/res/values-ca/strings.xml
- platform/android/MapboxGLAndroidSDK/src/main/res/values-nl/strings.xml
This PR adds [mapbox-gl-native Transifex project](https://www.transifex.com/mapbox/mapbox-gl-native) integration for the Android Mapbox SDK. 
To test integration, Dutch translations were added.
@1ec5 I moved the lang_map of the previous integration to the specific tasks (Android follows
the ISO 639-1 standard). I feel this was the best solution as applying a lang_map to a specific task will not override the project lang_map but will extend it. 
> [android] - Transifex intregration and Dutch translations.

- platform/ios/resources/Base.lproj/Localizable.strings
- platform/ios/src/MGLMapView.mm
Localized the accessibility hint for the “map view proxy” accessibility element that represents the act of closing the selected annotation’s callout view and returning to the map.
Fixes #8569.
> Localize map view proxy accessibility hint

- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
- platform/android/MapboxGLAndroidSDKWearTestApp/build.gradle
Because of Transiflex integration, lint is complaining that the test application is not being translated.
> [android] - disable requiring supported languages for test applications

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
- platform/android/src/file_source.cpp
Cherry-pick of #8582 to release branch.
> Cherry pick v5.0.2 changes

- src/mbgl/gl/context.cpp
Captured via `clang-analyzer-deadcode.DeadStores`.
/cc @kkaefer
> [core] Value stored to 'format' is never read in Context::drawPixels

- include/mbgl/style/conversion/make_property_setters.hpp
- include/mbgl/style/layers/symbol_layer.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
- platform/darwin/src/MGLSymbolStyleLayer.h
- platform/darwin/src/MGLSymbolStyleLayer.mm
- platform/darwin/test/MGLSymbolStyleLayerTests.mm
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/style/layers/symbol_layer.cpp
- src/mbgl/style/layers/symbol_layer_properties.hpp
Refs https://github.com/mapbox/mapbox-gl-js/issues/4304.
> [core] Add DDS support for icon-image

- platform/default/sqlite3.cpp
- src/mbgl/util/thread_local.hpp
Fix build on GCC6. C+11 defaults ctors to nothrow.
> [core] Do not throw on ctor and dtor

- platform/darwin/docs/guides/Data-Driven Styling.md.ejs
- platform/darwin/docs/guides/For Style Authors.md.ejs
- platform/ios/docs/guides/Data-Driven Styling.md
- platform/ios/docs/guides/For Style Authors.md
- platform/macos/docs/guides/Data-Driven Styling.md
- platform/macos/docs/guides/For Style Authors.md
Cursorily copy-edited the data-driven styling guide, removing a stray class reference, replacing a redundant h1, and making stops examples platform-agnostic and less redundant.
Fixed an issue in the style authors guide where style function tables appeared under each style layer type table.
Fixes #8524.
/ref #8525
/cc @friedbunny @ericrwolfe
> Copyedit data-driven styling guides

- circle.yml
- platform/android/src/geojson/multi_point.cpp
- platform/android/src/geojson/polygon.cpp
- platform/android/src/geojson/util.hpp
Clang 3.8 and below seems to be unable to implicitly convert derived objects when they inherit from the same base class.
> Fix compilation with Android NDK r13b

- cmake/test-files.cmake
- include/mbgl/style/function/composite_function.hpp
- test/style/function/composite_function.test.cpp
This fixes a bug where, for a zoom value greater than that of the highest zoom
stop, composite function interpolation would return `nan`. (Blocking a render
test over in https://github.com/mapbox/mapbox-gl-native/pull/8593)
> Fix edge case in composite function interpolation

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/gradle.properties
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java
> Release android v5.0.2

- platform/ios/CHANGELOG.md
- platform/ios/app/MBXViewController.m
- platform/ios/src/MGLMapView.mm
Continuation of https://github.com/mapbox/mapbox-gl-native/issues/8420.
Fixes warning introduced in https://github.com/mapbox/mapbox-gl-native/pull/8541
This silences a compatibility warning that was introduced in a previous refactor that changed the return type of the callout view for annotation delegate method. This also adds checks to ensure that the callout view provided by the delegate to the map view is of the correct type and conforms to the correct protocol.
> [ios] Silence incompatible type warning for callout view

- platform/ios/scripts/publish.sh
- platform/macos/CHANGELOG.md
- platform/macos/scripts/deploy-packages.sh
When zipping the framework for deployment, preserve symlinks instead of resolving them. Prior to this change, the published framework bundle contained multiple copies of the Mapbox executable and of every resource file, because the standard layout for a framework on macOS requires symlinks from the root folder and Versions/Current/ to Versions/A/.
Fixes #8636.
/cc @kkaefer @frederoni
> Preserve symlinks when zipping framework

- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
Addresses https://github.com/mapbox/mapbox-gl-native/issues/8163#issuecomment-290246849
> [ios] assertion to check if an annotationTag > 0

- platform/ios/docs/guides/Adding Points to a Map.md
Replaces link with a different example of how to add a tap gesture.
> [ios] Replaced link to select a feature example

- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
Replaced `std::map::operator[]` usage with `std::map::at()`. Backed up an assertion on iOS with a guard when `-annotationTagsInRect:` returns the tag of a nonexistent annotation, for consistency with macOS. Removed an unnecessary and risky subscript into `_annotationContextsByAnnotationTag` in `-positioningRectForCalloutForAnnotationWithTag:` on iOS.
/ref https://github.com/mapbox/mapbox-gl-native/issues/8163#issuecomment-291736586
> Harden std::map usage in MGLMapVIew

- src/mbgl/text/glyph.hpp
- src/mbgl/text/glyph_atlas.cpp
- src/mbgl/text/glyph_atlas.hpp
- src/mbgl/text/glyph_pbf.cpp
- src/mbgl/text/glyph_pbf.hpp
- src/mbgl/text/glyph_set.cpp
- src/mbgl/text/glyph_set.hpp
- test/text/glyph_atlas.test.cpp
- test/text/glyph_pbf.test.cpp
First of several followup refactors to #8341: the split between `GlyphAtlas` and `GlyphPBF` was awkward. Inline `GlyphPBF`, while leaving the actual PBF parsing code independent and tested in isolation.
> [core] Inline GlyphPBF into GlyphAtlas

- platform/android/bitrise.yml
Currently CI is failing for x86-64 ABI since Bitrise uses NDK14. 
This PR disables building that ABI so we can continue publishing snapshots for now.
> [android] - disable building x86-64 on CI for snapshot builds

- platform/node/src/node_map.cpp
In this code block, were calling `node::Buffer::Length(imageBuffer)` and `node::Buffer::Data(imageBuffer);` more than once. This function is cheap but not free. This pulls both these calls out as variables.
/cc @springmeyer @jfirebaugh @tmpsantos
> [node] Calculate image buffer and length once

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
Fixes https://github.com/mapbox/mapbox-gl-native/issues/8674
In https://github.com/mapbox/mapbox-gl-native/pull/8637 we stopped indexing into std::map to avoid silently creating bogus entries in collections like `_annotationContextsByAnnotationTag`. However, since the user annotation is effectively always represented with `MGLAnnotationTagNotFound` (that equals `UINT32_MAX`) and the user annotation is processed similarly to regular annotations in some cases, we opened the door to a crash.
Specifically, with #8637, attempts to lookup an annotation context for the user annotation's tag (`MGLAnnotationTagNotFound`) in order to update the callout view triggered the map's ` std::out_of_range` exception.
This PR guards against this by first checking to see if the annotation tag involved in the …
> [ios] Guard against looking up annotation contexts MGLAnnotationTagNotFound

- platform/qt/bitrise-qt5.yml
Updated the Qt5 macOS Bitrise bot’s configuration to reflect the `qt5` formula’s rename to `qt` in Homebrew/homebrew-core@b92c519bbd3cb869b4861017210e07fc42a0cc5f.
Fixes #8691.
> Rename qt5 formula to qt

- platform/macos/CHANGELOG.md
- platform/macos/Mapbox-macOS-SDK-symbols.podspec
- platform/macos/Mapbox-macOS-SDK.podspec
- platform/qt/bitrise-qt5.yml
Updated the changelog and podspecs for macOS SDK v0.4.1 and cherry-picked #8692 to keep the Qt5 macOS build passing.
> Update changelog, podspecs for macOS SDK v0.4.1

- Makefile
- Prefer `commanv -v` instead of `which`
- Search for `nodejs` if `node` is not found in `android-configuration`
> [build] Use 'nodejs' if 'node' is not found in android-configuration

- include/mbgl/util/image.hpp
- include/mbgl/util/size.hpp
- platform/android/build.gradle
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/default/mbgl/gl/offscreen_view.cpp
- platform/ios/src/MGLMapView.mm
- platform/ios/test/MGLAnnotationViewTests.m
- platform/macos/src/MGLMapView.mm
- platform/qt/src/qmapboxgl.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- src/mbgl/util/offscreen_texture.cpp
- src/mbgl/util/tile_cover.cpp
- test/map/transform.test.cpp
Some platforms provide their own size type defaulting to -1 in both width and height e.g. Qt's [QSize](http://doc-snapshots.qt.io/qt5-5.9/qsize.html). We should special case this and make this part of the assertion check.
> Tighten size check

- platform/qt/bitrise-qt5.yml
This change avoids hard-coding the path to the Homebrew cellar for the `qt` formula, per https://github.com/mapbox/mapbox-gl-native/pull/8692#issuecomment-292762518.
/cc @friedbunny @brunoabinader
> Avoid hardcoding Qt cellar path

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/MapboxConfigurationException.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java
Throw an InvalidateAccessToken exception instead.
Closes #8661
> [android] - avoid nullpointer by validating Mapbox.java creation 

- platform/darwin/src/MGLAttributionInfo.mm
- platform/darwin/test/MGLAttributionInfoTests.m
- platform/macos/CHANGELOG.md
Fixed an issue causing the attribution button text to appear blue instead of black. On macOS 10.12 and above, hyperlinks in attributed strings are blue regardless of any color attributes applied to the same run of text. The link attribute is unnecessary because the button already handles click events and the URL in the tooltip.
Fixes #8618.
/cc @friedbunny @frederoni
> Remove link attribute from attribution text

- include/mbgl/map/map.hpp
- include/mbgl/util/geo.hpp
- src/mbgl/map/map.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- test/map/transform.test.cpp
Implements a setter and getter for coordinate bounds in `Map` API - which can be used e.g. to limit the boundaries in which the user can set geographical coordinates.
Related: #3602.
> [core] AddedMap::{set,get}LatLngBounds

- platform/ios/CHANGELOG.md
- platform/ios/app/MBXEmbeddedMapViewController.h
- platform/ios/app/MBXEmbeddedMapViewController.m
- platform/ios/app/MBXViewController.m
- platform/ios/app/Main.storyboard
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLMapView.mm
Fixes #7217
Added an example behavior of MGLMapView as a subview of UIScrollView in
iOS app.
> [ios] Disable/enable related gesture recognizer when disabling/enabling user interactivity.

- Makefile
In #8662 we added support for `nodejs` when `node` wasn't found, but the check was missing a second `|`.
> Fix Node.js detection for Android

- include/mbgl/map/camera.hpp
- include/mbgl/map/map.hpp
- include/mbgl/util/geo.hpp
- src/mbgl/map/map.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
`EdgeInsets` has a natural "empty" state. It can always be considered to be present, with a default value of "no insets".
Fixes #8693, replaces #8707.
> [core] Revert use of optional<EdgeInsets>

- platform/darwin/src/MGLMultiPoint.h
Clarified the documentation for various MGLMultiPoint methods to indicate that only shape annotations automatically redraw in response to the multipoint object being mutated; sources must be mutated explicitly.
/cc @incanus
> Clarify redrawing based on multipoint mutation

- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Added various mbgl changes to the iOS and macOS changelogs: #8544, #8590, #8592, #8593, #8653, #8613, and #8562. Started separating the blurbs by topic, since there will probably be several more for this set of releases.
> Update and reorganize changelogs

- platform/ios/app/MBXAnnotationView.m
- platform/ios/app/MBXViewController.m
- platform/ios/src/MGLMapView.mm
Checks whether an annotation view has any `animationKeys` in `updateAnnotations` before adding the annotation view to reuse queue. Should prevent annotations that are being moved offscreen from disappearing. 
Bug and Fix
Addresses #8489, uses @boundsj's suggested fix.
> [ios] added check for annotation view animation

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/LatLngBoundsForCameraActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_restricted_bounds.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
Android binding integration of https://github.com/mapbox/mapbox-gl-native/pull/8583.
closes #3602
> Limit Viewport

- include/mbgl/map/map.hpp
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/glfw/glfw_view.cpp
- platform/ios/src/MGLMapView.mm
- platform/macos/src/MGLMapView.mm
- platform/qt/src/qmapboxgl.cpp
- src/mbgl/map/map.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- test/map/transform.test.cpp
We don't need to have two different measurement systems for map zoom.
Tested:
* Scroll zoom, pinch zoom, double click zoom, +/-, menu items in macosapp.
* Pinch zoom, tap-and-drag zoom, double tap zoom in iosapp.
* Pinch zoom, tap-and-drag zoom, double tap zoom in Android test app.
* Scroll zoom, double click zoom in glfw-app.
> [all] Remove redundant scale-related camera methods

- platform/darwin/test/MGLSDKTestHelpers.swift
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/test/MGLMapViewDelegateIntegrationTests.swift
- platform/macos/macos.xcodeproj/project.pbxproj
- platform/macos/test/MGLMapViewDelegateIntegrationTests.swift
Here is an idea to add the kind of tests described in https://github.com/mapbox/mapbox-gl-native/issues/8666 for `MGLMapViewDelegate`. 
As noted in #8666, the simple presence of the delegate method implementations will trigger warnings/errors in the tests if the delegate methods change -- no assertions required. There is a single test that reflects on the methods in the subject and the test class to ensure that there is full coverage. If new methods are added to the delegate in the future, this test will fail until the developer adds coverage.
cc @1ec5 @jmkiley @friedbunny
> [ios, macos] Add Swift integration tests for map view delegate

- src/mbgl/map/map.cpp
- src/mbgl/map/transform.cpp
- test/map/map.test.cpp
- test/map/transform.test.cpp
When calculating the screen coordinates for the given geographical coordinates boundaries in `Map::cameraForLatLngs`, we use `Map::pixelForLatLng`, which is implemented by calling `Transform::latLngToScreenCoordinate`.
The latter assumed that all conversions were required to be using the longitude shortest path. This is not true for `Map::cameraForLatLngs`, in which we require the longest path to properly calculate the virtual camera center.
Fixes #8737.
/cc @tobrun @jfirebaugh
> [core] Ignore shortest path in Map::cameraForLatLngs

- src/mbgl/text/glyph.hpp
- src/mbgl/text/glyph_atlas.cpp
- src/mbgl/text/glyph_atlas.hpp
- src/mbgl/text/quads.cpp
- src/mbgl/text/shaping.cpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/geometry_tile_worker.cpp
- src/mbgl/tile/geometry_tile_worker.hpp
- test/text/glyph_atlas.test.cpp
* Replace `GlyphRangeSet` in `onGlyphsAvailable` with optionals in the map. `GlyphRangeSet` isn't keyed by `FontStack`, so using it to indicate that a particular range was loaded could have produced false positives.
* Combine the two `GlyphID`-keyed maps in `GlyphAtlas::Entry` into one.
> More GlyphAtlas refactoring

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Closes #7553, this PR hardens the call to `NativeMapView#createSurface` by ensuring it's called after    `NativeMapView#initializeDisplay` & `NativeMapView#InitializeContext`.
> Synchronize display/context initalisation with surface creation

- src/mbgl/annotation/annotation_manager.cpp
This flag will get set automatically by `Style::recalculate`:
* [`Map::Impl::render` sets `Update::Classes` after calling `AnnotationManager::updateStyle`](https://github.com/mapbox/mapbox-gl-native/blob/09a22715769c629ad433b405908b60e1b9fa969b/src/mbgl/map/map.cpp#L238-L238)
* [When `Update::Classes` is set, `Style::recalculate` gets called](https://github.com/mapbox/mapbox-gl-native/blob/09a22715769c629ad433b405908b60e1b9fa969b/src/mbgl/map/map.cpp#L250-L250)
* [`Style::recalculate` resets all `enabled` flags, then re-enables them as needed](https://github.com/mapbox/mapbox-gl-native/blob/5e53d0586fe97db1d49b4b63313c96efb7bf71f8/src/mbgl/style/style.cpp#L312-L316)
> [core] Remove unnecessary Source::Impl::enabled assignment

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/layer.java.ejs
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/BackgroundLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RasterLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java
- platform/android/src/style/layers/layer.cpp
- platform/android/src/style/layers/layer.hpp
- platform/android/src/style/layers/layer.hpp.ejs
Closes #8663, need to fixup some whitespacing in the `.ejs` template file before reviewing.
This PR add a getter for source layer identifier on the layer classes that support it. Exposing this allows to iterate all layers and check for a specfic source layer identifiers, eg. `road`.
> [android] - expose source layer identifier

- src/mbgl/geometry/feature_index.cpp
- src/mbgl/geometry/feature_index.hpp
- src/mbgl/renderer/bucket.hpp
- src/mbgl/renderer/circle_bucket.cpp
- src/mbgl/renderer/circle_bucket.hpp
- src/mbgl/renderer/fill_bucket.cpp
- src/mbgl/renderer/fill_bucket.hpp
- src/mbgl/renderer/line_bucket.cpp
- src/mbgl/renderer/line_bucket.hpp
- src/mbgl/style/layer_impl.hpp
- src/mbgl/style/layers/circle_layer_impl.cpp
- src/mbgl/style/layers/circle_layer_impl.hpp
- src/mbgl/style/layers/fill_layer_impl.cpp
- src/mbgl/style/layers/fill_layer_impl.hpp
- src/mbgl/style/layers/line_layer_impl.cpp
- src/mbgl/style/layers/line_layer_impl.hpp
- src/mbgl/style/paint_property_binder.hpp
- src/mbgl/style/paint_property_statistics.hpp
- src/mbgl/style/possibly_evaluated_property_value.hpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style.hpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/raster_tile.cpp
- src/mbgl/tile/raster_tile.hpp
- src/mbgl/tile/tile.hpp
> Account for property functions in query rendered features

- platform/node/test/suite_implementation.js
- src/mbgl/algorithm/update_renderables.hpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/raster_tile.cpp
- src/mbgl/tile/tile.hpp
- test/algorithm/mock.hpp
- test/algorithm/update_renderables.test.cpp
- test/tile/raster_tile.test.cpp
- test/tile/vector_tile.test.cpp
In https://github.com/mapbox/mapbox-gl-native/pull/8164, we implemented raster tile overzooming. However, this fails in non-continuous rendering modes ("Still image rendering").
I believe this is a combination of two bugs, one of them in the node bindings, the other in `updateRenderables`:
- Node `FileSource` doesn't support optional, so the code path for loading parent tiles is never triggered, and all tiles we attempt to load are not in `complete` state,
- Still image rendering relies on tiles being marked as `complete`, but that never happens when a tile can't be loaded. This isn't an issue for continuous rendering because we just render what we have, but it's a termination condition for Still image rendering.
JS test is in https://github.com/mapbox/mapbox-gl-js/pull/4612
/cc …
> Render parent raster tiles when tiles can't be loaded

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxEventWrapper.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
Closes #8650, this PR introduces a wrapper implementation of MapboxEvent. This is needed to ignore events when the Map isn't ready to handle them (when we don't have a camera position to get the zoom level from). A use-case where this can occur is running monkeyrunner, note that I haven't been able to reproduce with normal behavior.
> Harden telemetry event dispatch

- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/LatLngBoundsActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/camera/CameraPositionTest.java
- platform/android/config.cmake
- platform/android/src/jni.cpp
- platform/android/src/map/camera_position.cpp
- platform/android/src/map/camera_position.hpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
closes https://github.com/mapbox/mapbox-gl-native/issues/4796
This PR moves calculating LatLngBounds to core instead of doing it in java. To achieve this I had to expose a `public CameraPosition getCameraForLatLngbounds(LatLngBounds bounds)` on MapboxMap (afaik the only way to make it work with our current `CameraUpdateFactory` setup).
This PR also refactors returning a CameraPosition directly from core instead of an double array. (this refactors the code for `getCameraValues` into `getCameraPosition`.
> move calculation of LatLngBounds to core

- platform/node/src/node_map.cpp
- platform/node/src/node_map.hpp
- platform/node/test/benchmark.js
- platform/node/test/js/cancel.test.js
- platform/node/test/js/map.test.js
- platform/node/test/js/request_fail.test.js
- platform/node/test/js/request_notfound.test.js
Test for timeout and when the request fails.
> [node] Add request failure tests

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/CustomLocationEngineActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MockLocationEngine.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_custom_location_engine.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
> [android] Add a way to use a custom location source

- include/mbgl/style/function/composite_function.hpp
- src/mbgl/util/interpolate.cpp
b5b4549 / #8613 handled the edge case for layout properties, but not paint properties. Move the check for a degenerate range to interpolationFactor in order to handle both correctly.
> [core] More complete fix for composite function interpolation edge case

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java
- platform/android/src/map/camera_position.cpp
Closes #8792, regression from #4796, the camera position values weren't correctly converted. (eg. angle + pitch from core are in rad while in the Android binding they are in degrees).
> [android] - convert camera position values coming from core

- platform/ios/src/MGLMapView.mm
Uses a simple and performant pointer equality test to bail early on view hierarchy recursion so as to not accidentally alter user-defined tint colors. 
Not applicable to macOS. 
/cc @jmkiley @boundsj
> fixes #8522: don't alter tint color on annotation views

- cmake/core-files.cmake
- src/mbgl/annotation/annotation_manager.cpp
- src/mbgl/map/map.cpp
- src/mbgl/sprite/sprite_atlas.cpp
- src/mbgl/sprite/sprite_atlas.hpp
- src/mbgl/sprite/sprite_atlas_worker.cpp
- src/mbgl/sprite/sprite_atlas_worker.hpp
- src/mbgl/sprite/sprite_parser.cpp
- src/mbgl/sprite/sprite_parser.hpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style.hpp
- test/sprite/sprite_atlas.test.cpp
- test/sprite/sprite_parser.test.cpp
- test/style/source.test.cpp
- test/style/style.test.cpp
- test/style/style_layer.test.cpp
- test/tile/annotation_tile.test.cpp
- test/tile/geojson_tile.test.cpp
- test/tile/raster_tile.test.cpp
- test/tile/vector_tile.test.cpp
We're currently parsing the sprite + accompanying JSON in the main thread. On some devices, parsing is rather slow and parsing time increases with sprite size. We should move it to a thread pool thread, since sprite loading is asynchronous anyway.
> Move Sprite parsing to thread pool

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/BaseLocationActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/CustomLocationEngineActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationDrawableActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTintActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationToggleActivity.java
closes #8806, this patches up the test app code related to requesting runtime permissions on older android OS versions. This is the second bug we had related to test app code and runtime permissions. I'm proposing to start looking into using [Dexter](https://github.com/Karumi/Dexter).
> [android] - fix test app runtime permissions

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java
> [android] - share locationsource between location components

- platform/ios/docs/guides/Working with Mapbox Studio.md
I switched a link in the Working with Mapbox Studio Guide from the [dynamically-styled circles](https://www.mapbox.com/ios-sdk/examples/runtime-circle-styles/) example to [data-driven circles](https://www.mapbox.com/ios-sdk/examples/dds-circle-layer/).
> [ios] Swapped link for circle layer example

- src/mbgl/annotation/annotation_manager.cpp
- src/mbgl/annotation/annotation_manager.hpp
- src/mbgl/annotation/annotation_tile.cpp
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/layout/symbol_layout.hpp
- src/mbgl/renderer/painter_symbol.cpp
- src/mbgl/renderer/render_symbol_layer.cpp
- src/mbgl/renderer/render_symbol_layer.hpp
- src/mbgl/renderer/symbol_bucket.hpp
- src/mbgl/sprite/sprite_atlas.cpp
- src/mbgl/sprite/sprite_atlas.hpp
- src/mbgl/style/layers/symbol_layer_impl.hpp
- src/mbgl/style/style.cpp
- src/mbgl/tile/geojson_tile.cpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/tile/geometry_tile_worker.cpp
- src/mbgl/tile/geometry_tile_worker.hpp
- src/mbgl/tile/vector_tile.cpp
* Simplify SymbolLayout; it never needs to care about more than one SpriteAtlas.
* Move the reference from SymbolLayer::Impl to SymbolBucket. This is a prerequisite for making layer Impls immutable.
> [core] Tweak handling of annotation special case SpriteAtlas

- CMakeLists.txt
- Makefile
Used for cases where we only need to build a static library containing the C++ core API.
> [build] Added linux-core target

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
closes #7961, adds an additional check if an annotation is not found in `LongSparseArray<Annotation>`. This will avoid the crash mentioned in #7961.
> [android] - warning log when attempting to update a non-added annotation

- platform/darwin/src/MGLStyleLayer.h
- platform/ios/docs/guides/Working with Mapbox Studio.md
The `maximumZoomLevel` for a `MGLStyleLayer` is currently the zoom level that a layer is rendered up to, but not including.
Cherry-picked #8818 so that it can land in v3.5.3.
cc @boundsj  @captainbarbosa
> [ios, macos] Updated `maximumZoomLevel` description, cherry-picked #8818

- .tx/config
- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/res/values-es/strings.xml
- platform/android/MapboxGLAndroidSDK/src/main/res/values-lt/strings.xml
- platform/android/MapboxGLAndroidSDK/src/main/res/values-vi/strings.xml
- platform/darwin/resources/es.lproj/Foundation.strings
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/resources/ca.lproj/Localizable.strings
- platform/ios/resources/ca.lproj/Localizable.stringsdict
- platform/ios/resources/ru.lproj/Localizable.stringsdict
- platform/ios/resources/sv.lproj/Localizable.strings
- platform/ios/resources/sv.lproj/Localizable.stringsdict
- platform/ios/resources/vi.lproj/Localizable.strings
- platform/ios/resources/zh-Hans.lproj/Localizable.strings
- platform/macos/macos.xcodeproj/project.pbxproj
Pulled the latest Catalan, Simplified Chinese, Spanish, Swedish, and Vietnamese localizations of the iOS and macOS SDKs from Transifex. Added Lithuanian, Spanish, and Vietnamese localizations of the Android SDK from Transifex as well.
@langsmith, are any other changes needed on the Android side besides adding these files in the resource directory?
/cc @eimantas @rroset @frederoni
> Update localizations from Transifex

- src/mbgl/algorithm/generate_clip_ids_impl.hpp
When it starts, we get a log warning for every frame, which is
expensive. Now we get only one warning.
> [core] Suppress "stencil mask overflow" warning

- Makefile
- platform/default/bidi.cpp
- platform/default/png_reader.cpp
- platform/linux/config.cmake
Fixes compilation issues when building `linux-core` target using older lib{icu,png} versions, and added extra steps for a minimal default runtime on Linux desktop.
> [build] Improve 'linux-core' build

- platform/android/CHANGELOG.md
Refs https://github.com/mapbox/mapbox-gl-native/issues/8856
> CHANGELOG.md for release-v5.1.0-beta.1

- src/mbgl/map/map.cpp
This reverts commit f0d4411871d43012dc9e24a376ebc70ec6ca9224, which was intended to be a temporary change to help diagnose an OpenGL error (which it did!).
> Revert "[node] Temporary: exit(0) on exception in Painter::render"

- src/mbgl/map/map.cpp
This should happen automatically during rendering. After removing, I can no longer replicate the original issue (#1889).
> [core] Remove forced style cascade

- src/mbgl/map/map.cpp
Since the advent of the runtime styling APIs, the APIs used by `AnnotationManager::updateStyle` will automatically set this flag as needed.
> [core] No need to manually set Update::Classes flag after annotation update

- platform/android/MapboxGLAndroidSDK/build.gradle
Closes #8878, I verified with `println` that `targets "example-custom-layer"` is only reached when doing a debug build + verified that it's not included in the resulting `.aar`:
> [android] - only build custom layer for debug builds

- cmake/core-files.cmake
- src/mbgl/map/map.cpp
- src/mbgl/map/update.hpp
- src/mbgl/renderer/property_evaluation_parameters.hpp
- src/mbgl/renderer/update_parameters.hpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style.hpp
- src/mbgl/tile/geometry_tile_worker.cpp
- test/style/paint_property.test.cpp
Combine `Style::cascade`, `recalculate`, `relayout`, and `updateTiles` into a single method. This allows multiple loops over sources and layers to be consolidated and prepares for additional Style-Map decoupling: rather than tracking pending updates via a set of `Update` flags held by the Map and passed to the Style, the Style can use its own data to determine what to update. To start out with, this replaces `Update::Layout` with use of the `UpdateBatch::sourceIDs` that the Style already tracks.
> [core] Omnibus Style::update method

- .travis.yml
- package.json
- platform/node/bitrise.yml
It's time to add support for node v6. I think this should be fairly straightforward quest:
/cc @tmpsantos @jfirebaugh @springmeyer
> Add support for node v6

- platform/qt/src/qmapboxgl.cpp
- platform/qt/src/qmapboxgl_p.hpp
This reverts commit 806da5d940aed7021f921ab98b9ae8e4e364f732 as per discussion in https://github.com/mapbox/mapbox-gl-native/pull/8887#issuecomment-299202658.
> Revert "[Qt] Don't regen BackendScope on every QMapboxGL::render() call"

- .travis.yml
- package.json
- platform/node/scripts/after_success.sh
Debug builds are an important way to find bugs that otherwise might be silent (because release builds remove `assert`) and to provide line numbers for crash reports (aka backtraces).
This enables the ability to publish both release the debug builds for the linux node bindings.
Release builds will still be the default. To install the debug build in a downstream app the developer would need to do:
```
npm install --debug
```
More info on debug builds: https://github.com/mapbox/cpp/blob/master/glossary.md#debug-build
Next steps:
> [node] Start publishing both release+debug builds

- src/mbgl/map/map.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
- src/mbgl/map/zoom_history.hpp
- src/mbgl/style/style.cpp
Followup to #8888, elaborating on:
> rather than tracking pending updates via a set of Update flags held by the Map and passed to the Style, the Style can use its own data to determine what to update
* Don't use `RecalculateStyle` to track zoom changes. Instead, `Style::update` can use the zoom history to check for a change in zoom from the previous frame.
* Don't use `RecalculateStyle` to track active property transitions. Style already knows which layers/light have an active transition, and can re-evaluate only those that do.
This leaves layer property changes as the only use of `RecalculateStyle`.
> [core] Reduce use of RecalculateStyle

- src/mbgl/style/layer_impl.cpp
- src/mbgl/style/source_impl.cpp
- src/mbgl/style/style.cpp
This ensures that the observer is not an invalid reference if the removed Source/Layer is retained, but the Style is deallocated.
This would have caused memory corruption in the following sequence:
1. Remove a source/layer from the style, retaining a reference
2. Change the style URL
3. Mutate the source/layer via the retained reference (e.g. `GeoJSONSource::setURL`, `Layer::setFilter`, or any other setter)
> [core] Reset observers of removed Sources and Layers

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java
- platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml
Closes #8899, this PR refactors the code to have a try/catch block around the `Intent.ACTION_VIEW` for browser intents. Capturing from the issue that it's possible to run in ActivityNotFound exception if you don't have a browser installed.
> [android] - show error message when no browser is installed 

- cmake/core-files.cmake
- include/mbgl/style/conversion/light.hpp
- include/mbgl/style/light.hpp
- include/mbgl/style/light.hpp.ejs
- scripts/generate-style-code.js
- src/mbgl/map/map.cpp
- src/mbgl/renderer/painter.cpp
- src/mbgl/renderer/render_light.cpp
- src/mbgl/renderer/render_light.hpp
- src/mbgl/style/light.cpp
- src/mbgl/style/light.cpp.ejs
- src/mbgl/style/light_impl.cpp
- src/mbgl/style/light_impl.hpp
- src/mbgl/style/light_observer.hpp
- src/mbgl/style/light_properties.hpp
- src/mbgl/style/parser.cpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style.hpp
- test/style/conversion/light.test.cpp
Splits Light in Style and Render portions. Also adds accessors for api clients.
> Render light

- package.json
- platform/node/CHANGELOG.md
Note, Node v4 binaries will be removed on August 1st.
/cc @tmpsantos @jfirebaugh
> [node] bump version, add changelog entry

- platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme
- platform/ios/src/MGLScaleBar.mm
Fixes an issue where the scale bar would report its width as `NaN` when hidden, which throws an exception on iOS 8 & 9 (and a warning in iOS 10).
We didn’t see the console warning in iosapp because `OS_ACTIVITY_MODE=disable` (#6382) was still being set, which hid this important message. Xcode 8’s spew has been fixed, so it’s time to remove this.
Fixes #8854 and #8909.
/cc @frederoni
> [ios] Check for NaN when calculating scale bar width

- platform/darwin/docs/guides/Using Style Functions at Runtime.md.ejs
- platform/darwin/scripts/generate-style-code.js
- platform/darwin/scripts/update-examples.js
- platform/darwin/test/MGLDocumentationGuideTests.swift
- platform/ios/docs/guides/Using Style Functions at Runtime.md
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/macos/docs/guides/Using Style Functions at Runtime.md
- platform/macos/macos.xcodeproj/project.pbxproj
This PR extracts the example code from the “Using Style Functions at Runtime” jazzy guide into unit tests run as part of the iOS and macOS unit test targets. Running `make darwin-style-code` inserts the code back into the guide as it generates the final Markdown.
Managing the example code this way helps us avoid syntax errors, as demonstrated by the syntax error this PR fixes. It also gives us an early warning system for when changes to the API break the most common coding patterns, which are enshrined in this guide and others like it.
Fixes #8461 and fixes #8902.
/cc @jmkiley @friedbunny
> Manage jazzy guide example code inside unit tests

- .tx/config
- platform/android/CHANGELOG.md
- platform/android/MapboxGLAndroidSDK/src/main/res/values-sv/strings.xml
- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/resources/ca.lproj/Localizable.stringsdict
- platform/ios/resources/de.lproj/Localizable.stringsdict
- platform/ios/resources/en.lproj/Localizable.stringsdict
- platform/ios/resources/es.lproj/Localizable.strings
- platform/ios/resources/es.lproj/Localizable.stringsdict
- platform/ios/resources/lt.lproj/Localizable.strings
- platform/ios/resources/lt.lproj/Localizable.stringsdict
- platform/ios/resources/pt-BR.lproj/Localizable.stringsdict
- platform/ios/resources/ru.lproj/Localizable.stringsdict
- platform/ios/resources/sv.lproj/Localizable.stringsdict
- platform/ios/resources/vi.lproj/Localizable.stringsdict
- platform/macos/sdk/lt.lproj/Localizable.strings
- platform/macos/sdk/sv.lproj/Localizable.strings
This change formally puts the iOS SDK’s Localizable.stringsdict file under Transifex’s control. Although Transifex supports the stringsdict format, it doesn’t allow translators to customize the format. This change splits out a separate `level` key for the same format string and moves any prefixes and suffixes into the `level` and `count` keys. For now, each localization has been updated manually, but future updates will come from Transifex.
Along the way, various localizations have been updated on iOS and macOS, and a Swedish localization has been added to the Android SDK.
/cc @frederoni @langsmith
> Update localizations and stringsdicts from Transifex

- cmake/glfw.cmake
- platform/glfw/glfw_view.cpp
- platform/glfw/glfw_view.hpp
Workaround for fixing the GLFW build on Linux until we fix https://github.com/mapbox/mason/issues/406.
> [build] Suppress GLFW redefining GLAPIENTRY error

- platform/ios/src/MGLMapView.mm
Fixes https://github.com/mapbox/mapbox-gl-native/issues/8603
Fixes https://github.com/mapbox/mapbox-gl-native/issues/8925
The value for determining the visible viewport buffer and also the distance to move offscreen an annotation view outside of that buffer was based on the annotation view width and height. This changes that to use the map viewport width and height as constants and avoids a class of bugs where the annotation view would become detached from the tracking system when it did not have a size but contained views with a size or the view was animating from a small to large size.
> [ios] Use map view frame to calculate annotation view reuse adjustments

- platform/ios/src/MGLMapView.mm
The value for determining the visible viewport buffer and also the distance to move offscreen an annotation view outside of that buffer was based on the annotation view width and height. This changes that to use the map viewport width and height as constants and avoids a class of bugs where the annotation view would become detached from the tracking system when it did not have a size or was animating from a small to large size.
> Cherry pick 8926 to the 3.5.x release branch

- platform/android/scripts/release.py
As explained on https://github.com/mapbox/mapbox-gl-native/issues/8858 we've recently switched to CircleCI for our Android builds. This PR updates the `release.py` script to use CircleCI to trigger our release builds.
The script usage is the same as before but the environment variable with the API token is now named `CIRCLECI_API_TOKEN`. You can add a token to your account on https://circleci.com/account/api.
@tobrun let's test this out for `beta.2`.
cc: @kkaefer
> Update release script to support CircleCI builds

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterSource.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/VectorSource.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
- platform/android/src/style/sources/geojson_source.cpp
- platform/android/src/style/sources/geojson_source.hpp
- platform/android/src/style/sources/raster_source.cpp
- platform/android/src/style/sources/raster_source.hpp
- platform/android/src/style/sources/vector_source.cpp
- platform/android/src/style/sources/vector_source.hpp
> [android] url getter on sources

- circle.yml
This PR changes Circle CI configuration to build a SNAPSHOT when a PR is merged to `release-ios-v3.6.0-android-v5.1.0` instead of `master`.
> [android] - build SNAPSHOT from release branch

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java
Closes #8786 
- keep offline observer when timeout occurs (test app code)
- make observer param nulllable, resetting observer is valid (eg. when download finished downloading)
- add null checking to observer 
- fixup log messages, timber has formatting build in
> [android] - keep offline observer when timeout occurs

- platform/ios/app/Info.plist
- platform/ios/app/MBXViewController.m
This was snuck into the file in https://github.com/mapbox/mapbox-gl-native/commit/67ffc9685e573b10e4761b0bdb9962c79139f5da
Reported by @mb12 in https://github.com/mapbox/mapbox-gl-native/issues/8914
> [iOS] remove Secure Transport exception from demo app

- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java
- platform/android/MapboxGLAndroidSDKTestApp/build.gradle
- platform/android/build.gradle
- platform/android/dependencies.gradle
This PR updates the LOST dependency to v2.3.0-SNAPSHOT. This allows us to test if this new version resolves the reported issue in https://github.com/mapzen/lost/issues/173 and allows us to ship this in our own SNAPSHOT builds.
> update LOST to 2.3.0-SNAPSHOT

- .travis.yml
- scripts/clang-tools.sh
Fixed an issue where no clang-tidy issues found causes the build to fail - also disables the check when running on `master` branch - that's a no-op.
> [build] Don't run Travis 'check' build on master

- src/mbgl/style/observer.hpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style.hpp
- test/sprite/sprite_loader.test.cpp
- test/src/mbgl/test/stub_style_observer.hpp
- test/text/glyph_atlas.test.cpp
It doesn't need to inherit from SpriteLoaderObserver and GlyphAtlasObserver.
> [core] Trim StyleObserver interface

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
This PR corrects OnMarkerViewClickListener integration when deselecting a Marker.
I was underway of refactoring parts of the AnnoationManager for readability but remembered @Guardiola31337 picking up a part of this in #8261 (which isn't on the target branch). This PR just fixes up the related business logic, we can revisit the refactor when we merge back to master.
Closes #8991
> MarkerView deselect events with OnMarkerViewClickListener

- circle.yml
Follow up from #8976, where we altered the CircleCI configuration to release a beta build from the specific release branch. Now that this has happened. The configuration should be updated to build SNAPSHOT from the default 5.1.0 release branch (when a PR is merged to that branch).
@zugaldia, I added a note in https://github.com/mapbox/mapbox-gl-native/issues/8390#issuecomment-301407876 to update the release documentation with a step-by-step guide related to the CircleCI.
> [android] - publish SNAPSHOT from release 5.1.0 branch

- include/mbgl/style/image.hpp
- src/mbgl/annotation/annotation_manager.cpp
- src/mbgl/sprite/sprite_atlas.cpp
- src/mbgl/sprite/sprite_atlas.hpp
- src/mbgl/style/image.cpp
- src/mbgl/style/style.cpp
- test/sprite/sprite_atlas.test.cpp
- test/text/quads.test.cpp
> [core] Immutable<Impl> for Image

- bin/render.cpp
Replaces https://github.com/mapbox/mapbox-gl-native/pull/8780
> [core] mbgl-render: allow scale factor to be floating point number

- circle.yml
We don't need to go through the trigger image anymore.
> Circle: use workflows instead of a trigger build

- platform/darwin/docs/guides/Tile URL Templates.md.ejs
- platform/darwin/scripts/generate-style-code.js
- platform/darwin/src/MGLRasterSource.h
- platform/darwin/src/MGLVectorSource.h
- platform/ios/docs/guides/Tile URL Templates.md
- platform/ios/jazzy.yml
- platform/macos/docs/guides/Tile URL Templates.md
- platform/macos/jazzy.yml
Factored out redundant tile URL template documentation from the MGLRasterSource and MGLVectorSource documentation into a jazzy guide. This documentation used to live in one place, on a method on MGLTileSource, but that method had to be moved to MGLTileSource’s concrete subclasses. A jazzy guide is easier to link to than a heading in a method’s documentation, in any case.
This would’ve been a simple Markdown document, except for the reference to NSScreen/UIScreen towards the bottom, which required the use of `make darwin-style-code` to differentiate between the two platforms. However, I’m open to using a single Markdown document with a simple “NSScreen or UIScreen” if that seems more intuitive.
Fixes #8634.
/cc @jmkiley @friedbunny @jfirebaugh
> Factor out tile URL template guide

- include/mbgl/style/image.hpp
- platform/macos/src/NSImage+MGLAdditions.mm
- src/mbgl/sprite/sprite_atlas.cpp
- src/mbgl/sprite/sprite_atlas.hpp
- src/mbgl/style/image.cpp
- src/mbgl/style/image_impl.hpp
- src/mbgl/text/shaping.cpp
- test/sprite/sprite_atlas.test.cpp
- test/sprite/sprite_parser.test.cpp
- test/style/style_image.test.cpp
These methods were not named in a way that indicates they return dimensions divided by the pixel ratio. In the one place they were used, inlining the calculation eliminates redundant arithmetic operations anyway.
> [core] Remove ambiguous get{Width,Height} accessors from style::Image

- platform/ios/src/MGLMapView.mm
> [ios] Telemetry button in modal view controllers

- cmake/core-files.cmake
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/util/throttler.cpp
- src/mbgl/util/throttler.hpp
Whenever the position of the camera changes (change in pitch or bearing), we have to run the symbol placement logic in `GeometryTileWorker::attemptPlacement` in order to do collision detection for the new geometry. Collision detection is too expensive to do on every frame, so we do it asynchronously on the worker threads, and update the render thread with new collision information whenever it becomes available.
The current implementation has the worker threads run placement requests as frequently as possible: the idea is that even though we can't do collision detection synchronously, we want it to be "as close as possible" to avoid the temporary appearance of collisions as the map rotates. This means that when the camera position is continuously changing (maybe in a "route following" …
> Throttle tiles to redo symbol placement at most once every 300ms.

- CMakeLists.txt
- include/mbgl/map/map_observer.hpp
- src/mbgl/programs/symbol_program.hpp
- src/mbgl/sprite/sprite_atlas.hpp
- src/mbgl/style/sources/geojson_source_impl.hpp
- src/mbgl/text/glyph_atlas.hpp
https://github.com/mapbox/mapbox-gl-native/commit/3f0c89d633a5056006557ad5f4b9e446807d00ee introduced a `GeoJSONData` object that is held in a `unique_ptr`, and has two child classes with data members. However, the `unique_ptr` created only holds the parent object, and it doesn't have a a `virtual` destructor, which means that during destruction, it'll only delete the base class part of the object (probably empty due to [empty base optimization](http://en.cppreference.com/w/cpp/language/ebo)), which leaves the other data members defined by the child classes (`GeoJSONVT` or `Supercluster`) allocated, creating a memory leak.
/cc @tmpsantos @bsudekum
> Make destructor virtual to avoid object splicing during destructor

- src/mbgl/layout/symbol_layout.cpp
Fixes issue #8982.
The upshot of this is basically that Latin text should just require a single page of Latin glyphs, not an extra page of full-width punctuation.
Nice catch, @mb12!
> [core] Don't unnecessarily request glyphs for verticalized punctuation.

- platform/darwin/src/MGLStyleLayer.h
- platform/ios/CHANGELOG.md
Merged the release-ios-v3.5.0-android-v5.0.0 branch as of db7bb509e95d737199efa73a47bdcc973966ed97 into the master branch as of 8c75001443d5b91059f90aadbec126e47f6fc64b. Effectively, this merge brings in a commit that snuck into #8842 and changelog updates.
I’ll cherry-pick these commits into the release-ios-v3.6.0-android-v5.1.0 branch afterwards.
/cc @boundsj @jmkiley
> Merge release-ios-v3.5.0-android-v5.0.0 into master (after iOS SDK v3.5.4)

- platform/android/MapboxGLAndroidSDK/build.gradle
- platform/android/dependencies.gradle
Unblocks https://github.com/mapbox/mapbox-gl-native/pull/9045, more information in https://github.com/mapbox/mapbox-gl-native/pull/9045#issuecomment-302612989.
> [android] - bump tools and support lib version due to SNAPSHOT dependencies

- CMakeLists.txt
- include/mbgl/map/map_observer.hpp
- src/mbgl/programs/symbol_program.hpp
- src/mbgl/sprite/sprite_atlas.hpp
- src/mbgl/style/sources/geojson_source_impl.hpp
- src/mbgl/text/glyph_atlas.hpp
Pull https://github.com/mapbox/mapbox-gl-native/pull/9035 into the release branch, fixing a memory leak.
> Release ios v3.6.0 android v5.1.0  virtual destructor splicing

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/ios/src/MGLScaleBar.mm
Fixes #6954
This PR adds observers to the top and bottom layout guides if necessary in order to re-layout after changes have occurred. (i.e due to showing/hiding a navigation bar)
It also replaces constraints with manual layout to avoid manipulating the view controller's view which is the developer's responsibility.
> Observe layout guides

- src/mbgl/util/premultiply.cpp
- test/util/image.test.cpp
Follow up to https://github.com/mapbox/mapbox-gl-native/commit/5c52401d5504ab4b84d1510042c6b97504c50933
> Leave Image objects in a valid state after premultiply/unpremultiply

- package.json
- platform/node/CHANGELOG.md
Most significant change is fixing the memory leak found in https://github.com/mapbox/mapbox-gl-native/pull/9035
> Release node-v3.5.2

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
Closes https://github.com/mapbox/mapbox-gl-native/issues/8754
The annotation container view keeps an array of annotation views that is separate from the array of subviews that is a property of the UIView parent class. This removes an annotation view from that container view array when the associated annotation is removed. This avoids issue related to previously removed annotation views continuing to be involved in map view logic around annotation view selection due to taps.
> [ios] Remove annotation view from container view when annotation removed

- cmake/test-files.cmake
- include/mbgl/style/function/camera_function.hpp
- include/mbgl/style/function/exponential_stops.hpp
- include/mbgl/style/function/interval_stops.hpp
- test/style/function/exponential_stops.test.cpp
- test/style/function/interval_stops.test.cpp
Small optimization I spotted doing some profiling.
> [core] Eliminate round-trip through `Value` in `CameraFunction::evaluate`

- platform/darwin/src/MGLStyleLayer.h
- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Cherry-picked #9044 into the release-ios-v3.6.0-android-v5.1.0 branch. Also added blurbs for #8954 and #9027.
/cc @boundsj @jmkiley
> Cherry-pick iOS SDK v3.5.3–3.5.4 changelog entries into v3.6.0 release branch

- platform/darwin/src/MGLFillExtrusionStyleLayer.h
- platform/darwin/test/MGLDocumentationExampleTests.swift
> [ios, macos] Updated `MGLFillExtrusionStyleLayer` example predicate

- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.h
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.h
- platform/macos/src/MGLMapView.mm
Implemented by filtering the `annotations` property for
annotations that conform to `MGLOverlay` protocol.
Fixes #4281.
> [ios, macos] Add `overlays` property to `MGLMapView.mm`

- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/util/i18n.cpp
- src/mbgl/util/i18n.hpp
Port of https://github.com/mapbox/mapbox-gl-js/issues/4208, fixes issue #9057.
/cc @1ec5 @nickidlugash @boundsj @zugaldia
> Disable letter spacing for Arabic text

- platform/android/src/map/camera_position.cpp
- platform/android/src/native_map_view.cpp
Closes #9079, in #9050 I adjusted the bindings to conform to a conversion for [−π rad, π rad] to [0 degrees, 360 degrees] but I missed that the original value is measured in counterclockwise from true north. This PR fixes that up + also uses util to convert angles.
> [android] - horizontally rotated in snapshot

- cmake/core-files.cmake
- src/mbgl/layout/symbol_layout.cpp
- src/mbgl/tile/geometry_tile.cpp
- src/mbgl/tile/geometry_tile.hpp
- src/mbgl/util/i18n.cpp
- src/mbgl/util/i18n.hpp
- src/mbgl/util/throttler.cpp
- src/mbgl/util/throttler.hpp
Cherry-picks https://github.com/mapbox/mapbox-gl-native/pull/9062 and https://github.com/mapbox/mapbox-gl-native/pull/9031 to release-ios-v3.6.0-android-5.1.0
cc/ @mapbox/android
> Cherry-pick arabic text to release branch v3.6.0

- platform/ios/app/MBXViewController.m
- platform/macos/app/MGLVectorSource+MBXAdditions.h
- platform/macos/app/MGLVectorSource+MBXAdditions.m
- platform/macos/app/MapDocument.m
Rely on NSBundle to select the most appropriate locale based on the user’s preferred languages. This code is used in iosapp’s “Label Countries In” demonstration and macosapp’s View ‣ Labels In setting. (#7031 tracks folding that logic into the SDKs proper.)
Added Arabic, Portuguese, and Simplified Chinese to the list of languages with specialized fields in the Mapbox Streets source, based on [this revised document](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#overview). The previous logic was insufficient for choosing between `zh` and `zh-Hans`.
> More robust Mapbox Streets label localization

- platform/darwin/src/NSBundle+MGLAdditions.h
- platform/darwin/src/NSBundle+MGLAdditions.m
- platform/ios/CHANGELOG.md
- platform/ios/src/MGLAPIClient.m
- platform/ios/src/MGLMapView.mm
Fixes #9072 and unblocks #9060. When using the static framework, load resources from Mapbox.bundle.
/cc @boundsj @1ec5
> [ios] Fallback to Mapbox.bundle as the framework bundle

- platform/ios/CHANGELOG.md
- platform/macos/CHANGELOG.md
Reorganized the changelogs with a new packaging section. Added blurbs about #9062, #8713, #9060, and #9031.
/cc @fabian-guerra @friedbunny @jmkiley
> Update changelogs for iOS SDK v3.6.0-beta.1

- include/mbgl/actor/mailbox.hpp
- src/mbgl/actor/mailbox.cpp
- test/actor/actor.test.cpp
Otherwise, an ActorRef that's in the process of sending a message could attempt to access an invalid Scheduler reference:
```
Thread 1                     Thread 2
--------------------------------------------------
Scheduler::Scheduler
Actor::Actor
weakMailbox.lock()
Actor::~Actor
Scheduler::~Scheduler
mailbox->push()
scheduler.schedule() 💣
```
Fixes the issue described in https://github.com/mapbox/mapbox-gl-native/issues/8864#issuecomment-298784717.
> [core] Block in Mailbox::close() until the mailbox isn't being sent a message

- platform/android/src/map/camera_position.cpp
> [android] - LatLngBounds bearing default value

- platform/ios/ios.xcodeproj/project.pbxproj
- platform/ios/src/MGLAnnotationView.mm
- platform/ios/test/MGLAnnotationViewIntegrationTests.swift
- platform/ios/test/MGLAnnotationViewTests.m
- platform/ios/test/MGLAnnotationViewTests.swift
https://github.com/mapbox/mapbox-gl-native/issues/9066#issuecomment-303628986 pointed out that Swift subclasses of `MGLAnnotationView` will trigger runtime exceptions unless they override `init(annotation, reuseIdentifier)`. This fixes that issue by using common init function in both of the provided initializers so that subclasses of `MGLAnnotationView` written in Swift don't need to override `init(annotation, reuseIdentifier)`
> Fix annotation initializers for subclasses of MGLAnnotationView

- platform/android/MapboxGLAndroidSDK/gradle-checkstyle.gradle
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Property.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/Light.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/Position.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/light.java.ejs
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LightTest.java
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/light.junit.ejs
- platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/BuildingFillExtrusionActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/FillExtrusionStyleTestActivity.java
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_paint.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_building_layer.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_extrusion_test.xml
- platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_building.xml
- platform/android/config.cmake
- platform/android/scripts/generate-style-code.js
- platform/android/src/jni.cpp
- platform/android/src/native_map_view.cpp
- platform/android/src/native_map_view.hpp
- platform/android/src/style/conversion/position.hpp
- platform/android/src/style/conversion/types.hpp
- platform/android/src/style/conversion/types_string_values.hpp
- platform/android/src/style/light.cpp
- platform/android/src/style/light.cpp.ejs
- platform/android/src/style/light.hpp
- platform/android/src/style/light.hpp.ejs
- platform/android/src/style/position.cpp
- platform/android/src/style/position.hpp
Closes #8841,  Follow-up from #8889 & WIP. 
This PR adds Android binding support for [Light](https://www.mapbox.com/mapbox-gl-js/style-spec/#light). 
Current status is a POC, this can be used as a base to generate classes from:
> add binding support for Light

- src/mbgl/renderer/painter.cpp
- src/mbgl/renderer/painter.hpp
- src/mbgl/renderer/render_item.hpp
- src/mbgl/renderer/render_layer.cpp
- src/mbgl/renderer/render_layer.hpp
- src/mbgl/style/style.cpp
This PR moves RenderTile ownership to RenderLayers. This allows moving the management of layer-specific behaviors for RenderItem's from Painter to the individual RenderLayers.
This is also needed to allow layers to have different behaviors based on the source type, as needed for ImageSource
> [core] RenderLayer to manager RenderTiles

- include/mbgl/actor/mailbox.hpp
- src/mbgl/actor/mailbox.cpp
- test/actor/actor.test.cpp
Split off from #9100
Prevents deadlocking in `Mailbox::close()` when an actor releases a smart pointer to itself in a callback.
> Prevent deadlock in self closing actors

- include/mbgl/storage/default_file_source.hpp
- platform/default/default_file_source.cpp
Makes sure that DefaultFileSource can be used concurrently. Enables us to use the DefaultFileSource from multiple threads fro a-sync rendering #8820
> Thread safe Default File Source

- src/mbgl/map/map.cpp
- src/mbgl/style/style.cpp
This reverts commit 3790caafa3c98706c5cf0618c8aec592b2780bba.
From initial investigations, `timePoint` is used elsewhere other than in `TransitionParameters` and `PropertyEvaluationParameters`, and being its value `Clock::time_point::max()` causes a stall in the styling mechanism in some cases. This probably needs further investigation.
Fixes #9106.
/cc @bsudekum
> Revert "[core] Factor timePoint initialization"

- include/mbgl/style/layer.hpp
- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
- platform/darwin/test/MGLStyleTests.mm
- src/mbgl/style/style.cpp
- test/style/style.test.cpp
Closes #9121
I opted to log a warning instead of throwing an exception. I can see it going both ways though.
> Check source usage before removal

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Icon.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/IconManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
- platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/IconTest.java
> [android] - harden orientation changes

- src/mbgl/renderer/style_diff.cpp
- src/mbgl/renderer/style_diff.hpp
- src/mbgl/sprite/sprite_atlas.cpp
- src/mbgl/sprite/sprite_atlas.hpp
- src/mbgl/style/style.cpp
- src/mbgl/style/style.hpp
- test/sprite/sprite_atlas.test.cpp
Use style diffing to resolve updates to images and updates that require reloading tiles.
> [core] Replace inline SpriteAtlas updates with diffing

- platform/darwin/src/MGLAttributionInfo.mm
- platform/darwin/src/MGLAttributionInfo_Private.h
- platform/darwin/src/MGLOfflineStorage.mm
- platform/darwin/src/NSBundle+MGLAdditions.h
- platform/darwin/src/NSBundle+MGLAdditions.m
- platform/darwin/test/MGLAttributionInfoTests.m
- platform/ios/CHANGELOG.md
- platform/ios/src/MGLMapView.mm
- platform/macos/CHANGELOG.md
- platform/macos/src/MGLMapView.mm
This port of mapbox/mapbox-gl-js#4685 updates the “Improve This Map” button on iOS and macOS to open the ~~yet-to-be-launched~~, [Mapbox GL–powered feedback tool](https://www.mapbox.com/feedback/) instead of the existing Map Feedback tool. Should the new feedback tool accept additional parameters, like rotation, pitch, and the SDK version, this code could be updated quite easily to provide them.
Fixes the iOS and macOS side of #8988. ~~Hold until the new feedback form is ready.~~
/cc @friedbunny @mollymerp @tristen
> Migrate to GL JS–powered feedback form

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyBearingTracking.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyLocationTracking.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/Style.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/FocalPointChangeListener.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/Resource.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/functions/CompositeFunction.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Filter.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/TransitionOptions.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/package-info.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/AnimatorUtils.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java
First stab at optimizing and correcting the javadoc for the 5.1.0 release. Focus for this PR is package information and class level javadoc.
> [android] - javadoc update for 5.1.0 release

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
> [android] Fix tracking mode + camera race condition

- platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
Adds missing `accessToken` variable which made release branch builds to fail.
cc/ @tobrun
> [android] Fix missing access token variable issue

- platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MockLocationEngine.java
- Prevents `NullPointerException` in `CustomLocationEngineActivity`.
cc/ @tobrun
> [android] Custom location engine activity null check

- include/mbgl/map/map.hpp
- src/mbgl/map/map.cpp
- src/mbgl/map/transform.cpp
- src/mbgl/map/transform.hpp
- src/mbgl/map/transform_state.cpp
- src/mbgl/map/transform_state.hpp
- test/map/transform.test.cpp
Have `TransformState` bounds empty by default - bypassing the boundary check if not present in `TransformState::setLatLngBounds`. This was causing issues when e.g. panning over the dateline.
Fixes #8951.
/cc @friedbunny - can you please verify this on iOS?
> [core] Make TransformState LatLngBounds optional

- platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
On master the `RuntimeStyleTests` test suite is currently crashing after run. `testRemoveSourceInUse` is marked as failed, but actually some other test cases in that suite are to blame. 
Crash dump:
```
********** Crash dump: **********
Build fingerprint: 'google/sailfish/sailfish:7.1.2/N2G47O/3852959:user/release-keys'
pid: 12043, tid: 12070, name: DefaultFileSour  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20
Stack frame #00 pc 00047676  /system/lib/libc.so (pthread_mutex_lock+1)
Stack frame #01 pc 0061f0cd  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__libcpp_mutex_lock(pthread_mutex_t*) at /Volumes/Android/buildbot/src/android/ndk-r14-release/external/libcxx/include/__threading_support:65 …
```
> Fix crash in runtime style ui tests
