mapbox/mapbox-gl-native

platform/default/glfw_view.cpp
=> Correctly call resize with width and height

platform/default/glfw_view.cpp
=> Correctly handle swapping

src/mbgl/renderer/symbol_bucket.cpp, src/mbgl/renderer/symbol_bucket.hpp, src/mbgl/util/merge_lines.hpp, test/merge_lines.cpp, test/test.gyp
ported from https://github.com/mapbox/mapbox-gl-js/pull/683
@kkaefer can you review?
=> merge adjacent roads with the same text for labeling

platform/default/glfw_view.cpp, src/mbgl/map/map.cpp
Hopefully fixes https://github.com/mapbox/node-mapbox-gl-native/issues/72
=> Move terminate() call to GLFWView to avoid problems with node

include/mbgl/map/map.hpp, src/mbgl/geometry/line_atlas.cpp, src/mbgl/geometry/line_atlas.hpp, src/mbgl/map/map.cpp, src/mbgl/renderer/line_bucket.cpp, src/mbgl/renderer/line_bucket.hpp, src/mbgl/renderer/painter.cpp, src/mbgl/renderer/painter.hpp, src/mbgl/renderer/painter_line.cpp, src/mbgl/shader/line.fragment.glsl, src/mbgl/shader/line.vertex.glsl, src/mbgl/shader/line_shader.hpp, src/mbgl/shader/linesdf.fragment.glsl, src/mbgl/shader/linesdf.vertex.glsl, src/mbgl/shader/linesdf_shader.cpp, src/mbgl/shader/linesdf_shader.hpp, src/mbgl/style/function_properties.cpp, src/mbgl/style/property_fallback.cpp, src/mbgl/style/property_key.hpp, src/mbgl/style/property_value.hpp, src/mbgl/style/style_layer.cpp, src/mbgl/style/style_parser.cpp, src/mbgl/style/style_parser.hpp, src/mbgl/style/style_properties.hpp, src/mbgl/util/interpolate.hpp
native version of https://github.com/mapbox/mapbox-gl-js/pull/938
For a list of changes and screenshots see https://github.com/mapbox/mapbox-gl-js/pull/938
=> improved dashed lines

src/mbgl/renderer/painter.cpp, src/mbgl/renderer/painter.hpp, src/mbgl/renderer/painter_fill.cpp, src/mbgl/renderer/painter_line.cpp, src/mbgl/shader/linesdf.fragment.glsl, src/mbgl/shader/linesdf.vertex.glsl, src/mbgl/shader/linesdf_shader.hpp
Implements https://github.com/mapbox/mapbox-gl-style-spec/issues/236
JS: https://github.com/mapbox/mapbox-gl-js/pull/950
=> don't permanently crossfade patterns

.gitignore, Makefile, config/defaults.mk, configure, scripts/flock.py
Also separates out the configuration defaults so they can be used more easily in dependent builds.
=> Move config-*.gypi files to config/ folder

platform/ios/MGLMapView.mm
=> put cache.db in the caches folder

platform/ios/MGLMapView.mm
=> Revert "put cache.db in the caches folder"

.travis.yml, android/scripts/common.sh, android/scripts/run-build.sh, travis/travis-resources.template
Part of https://github.com/mapbox/mapbox-gl-native/issues/875
=> Move to mapbox bucket

android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/app/MainActivity.java
=> Merging GPS Rotation

android/java/MapboxGLAndroidSDK/build.gradle, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/lib/constants/MapboxConstants.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/lib/util/JavaFileSource.java
=> Pulling In Initial Java FileSource Implementation

ios/app/MBXViewController.mm
Fixes goose hunts like #936. :hatched_chick:
=> Bump iOS app styles versions to 7

platform/ios/MGLMapView.mm
Carryover from #935. 
Just a couple code style tweaks, unless I'm mistaken @1ec5. 
* Use a property instead of an instance variable. We tended to the latter a lot in the SDK because that's how the upstream project was, but tend to prefer interface/class extension properties (if applicable) now. 
* No need for `dispatch_once()`? 
* Return an `NSArray` for the styles, not the `NSMutableArray` that we track internally. 
If this checks out in CI and looks good @1ec5, feel free to merge.
=> refs #935: remove dispatch_once, favor property use, and return immutable styles

src/mbgl/map/vector_tile.cpp, src/mbgl/style/value.cpp, src/mbgl/style/value.hpp, src/mbgl/text/glyph_store.hpp
=> VectorTile related cleanup

Makefile
=> Gradle Speed

Makefile, android/scripts/common.sh
Fix Android failures on Travis: https://travis-ci.org/mapbox/mapbox-gl-native/builds/54004070
=> Build $(BUILDTYPE) apk file and only upload those

.gitignore, Makefile, android/cpp/jni.cpp, android/cpp/native_map_view.cpp, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/NativeMapView.java, configure, gyp/common.gypi, include/mbgl/android/native_map_view.hpp, include/mbgl/map/map.hpp, include/mbgl/map/view.hpp, include/mbgl/platform/default/glfw_view.hpp, include/mbgl/platform/default/headless_view.hpp, ios/app/mapboxgl-app.gyp, linux/mapboxgl-app.gyp, platform/default/glfw_view.cpp, platform/default/headless_view.cpp, platform/ios/MGLMapView.mm, src/mbgl/map/map.cpp, src/mbgl/map/source.cpp, src/mbgl/map/view.cpp
=> black flicker on iOS device rotation

platform/ios/MGLMapView.mm
=> paint it black

platform/ios/MGLMapView.mm
=> iOS setAppliedStyleClasses -> setStyleClasses

include/mbgl/map/annotation.hpp, include/mbgl/map/map.hpp, include/mbgl/util/constants.hpp, include/mbgl/util/geo.hpp, macosx/mapboxgl-app.gyp, src/mbgl/map/annotation.cpp, src/mbgl/map/geometry_tile.hpp, src/mbgl/map/live_tile.cpp, src/mbgl/map/live_tile.hpp, src/mbgl/map/live_tile_data.cpp, src/mbgl/map/live_tile_data.hpp, src/mbgl/map/map.cpp, src/mbgl/map/source.cpp, src/mbgl/map/source.hpp, src/mbgl/map/tile_parser.cpp, src/mbgl/map/tile_parser.hpp, src/mbgl/map/vector_tile.cpp, src/mbgl/map/vector_tile.hpp, src/mbgl/map/vector_tile_data.cpp, src/mbgl/map/vector_tile_data.hpp, src/mbgl/renderer/symbol_bucket.cpp, src/mbgl/style/style_parser.cpp, src/mbgl/style/types.hpp, src/mbgl/util/constants.cpp
Take two of https://github.com/mapbox/mapbox-gl-native/pull/1018. Lots of review by @jfirebaugh, commits in to fix, and re-squashed.
=> refs #893 #992: point annotations API

linux/main.cpp, platform/default/glfw_view.cpp, scripts/valgrind.sup, src/mbgl/geometry/line_atlas.cpp
This branch also adds a reference Valgrind suppression file making it easier for further debugging.
=> Fix a few memory leaks

platform/ios/MGLMapView.mm
Squash / tweak of https://github.com/mapbox/mapbox-gl-native/pull/938. Feels great & MapKit-like in testing.
=> bring in tweaked compass snapping fixes from @friedbunny

platform/ios/MGLMapboxEvents.m, platform/ios/MGLMetricsLocationManager.m
Misc enhancements since original merge in #1036.
=> Enhancements Since Original Merge

ios/app/mapboxgl-app.gyp
=> Adding Settings.bundle to project generation

ios/MapboxGL.podspec
Ref #1036, #1094
/cc @incanus @bleege
=> update podspec frameworks

platform/ios/MGLMapView.mm
=> Assume UTF-8–encoded JSON stylesheets

include/mbgl/ios/MGLMapView.h, include/mbgl/ios/MGLMapboxEvents.h, include/mbgl/ios/MGLMetricsLocationManager.h, platform/ios/MGLMapView.mm, platform/ios/MGLMapboxEvents.m, platform/ios/MGLMetricsLocationManager.m
Squash of https://github.com/mapbox/mapbox-gl-native/pull/1130. Should be ready to pending CI.
=> fixes #1116: metrics stability & performance refactor

include/mbgl/ios/MGLMapboxEvents.h, platform/ios/MGLMapView.mm, platform/ios/MGLMapboxEvents.m, platform/ios/MGLMetricsLocationManager.m
More in our quest for strong typing and localizing backend metrics strings to the inside of the metrics manager.
=> more metrics magic strings removals

include/mbgl/map/map.hpp, src/mbgl/map/map.cpp
Continuation of https://github.com/mapbox/mapbox-gl-native/pull/1022, which became solid general improvements that were worth merging. Going to figure out a threading strategy here. 
/cc @kkaefer
=> make annotations API threadsafe

platform/ios/MGLMapboxEvents.m
=> Resplitting anonid into advertiserId and vendorId

platform/ios/MGLMapboxEvents.m
=> Back To Bool

include/mbgl/ios/MGLMapboxEvents.h, platform/ios/MGLMapView.mm, platform/ios/MGLMapboxEvents.m
=> Removing enabled.mail

platform/ios/MGLMapView.mm
* more quickly unhide dot when nearing viewport
* improvements to maintaining user tracking mode during tap zooms
* removed a redundant layer hide
* better at ignoring bad location data
* be sure to use existing coordinate utilities
=> refs #1125: user dot improvements

src/mbgl/style/style_parser.cpp
To avert issues like https://github.com/mapbox/mapbox-gl-styles/issues/57, we should normalize the font stack names (split on comma, then trim, then join).
Refs https://github.com/mapbox/mapbox-gl-style-spec/issues/257
=> Normalize font names

platform/ios/MGLMapboxEvents.m
=> App Bundle Id

platform/ios/MGLMapboxEvents.m
=> Changing "Location" to "location"

platform/darwin/http_request_nsurl.mm
=> Events = True

platform/ios/MGLUserLocationAnnotationView.m
=> Smooth edges of user location annotation icon's shadow

platform/ios/MGLMetricsLocationManager.m
=> LocationManager Defaults

platform/ios/MGLMapboxEvents.m
=> Changes To Metrics Data

include/mbgl/ios/MGLMapboxEvents.h, include/mbgl/ios/MGLMetricsLocationManager.h, ios/app/MBXAppDelegate.m, platform/ios/MGLMapboxEvents.m
=> Pause and Resume Metrics

include/mbgl/platform/log.hpp, include/mbgl/storage/default/sqlite_cache.hpp, platform/default/sqlite3.cpp, platform/default/sqlite_cache.cpp, src/mbgl/platform/log.cpp, src/mbgl/util/io.cpp, src/mbgl/util/io.hpp, test/fixtures/fixture_log_observer.cpp, test/fixtures/fixture_log_observer.hpp, test/storage/database.cpp, test/test.gyp
The app crashes if you dismiss the mapview in a modalview and reopen it...
SQL Cache (28) - sqlite3.cpp
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: failed to run statement
=> Sqlite thread is not safe!

platform/ios/MGLMapboxEvents.m
=> Created Cleanup

include/mbgl/ios/MGLMapboxEvents.h, platform/ios/MGLMapboxEvents.m, platform/ios/MGLMetricsLocationManager.m
=> Adding horizontalAccuracy to location event

platform/ios/MGLMapboxEvents.m
=> Changing "new" to "alloc init"

include/mbgl/ios/MGLMapView.h, include/mbgl/map/map.hpp, ios/app/MBXViewController.mm, platform/ios/MGLMapView.mm, src/mbgl/map/map.cpp, src/mbgl/map/source.cpp, src/mbgl/map/source.hpp, src/mbgl/map/tile_cache.cpp, src/mbgl/map/tile_cache.hpp
Squash of #1255 and brings in latest memory bug fixes from #1267.
=> fixes #1157, #1255: cache parsed tiles in memory

platform/ios/MGLMapView.mm
Moves from the `UIView` snapshot stuff back to `UIImageView`, which seems to be more reliable and works better with constraints, hitting #1276. We also now maintain the snapshot image view in the hierarchy after first use and just hide/show it.
=> fixes #1276: maintain snapshot in hierarchy & hide when appropriate

android/cpp/jni.cpp
I have tried building the Android project from the master branch. My environment is set up with homebrew and cask following the instructions in the readme. <code>make android</code> appears to complete successfully and the project under <code>android/java</code> imports into Android Studio and builds without error.
When I try deploying the TestApp to my Nexus 5 running Android 5.1 the application flashes on screen and crashes. Here's the output from logcat: https://gist.github.com/tnightingale/49b605b793bb1ced68be
This looks similar to the initial errors mentioned in #738.
=> Android TestApp crashes on startup

include/mbgl/ios/MGLMapboxEvents.h, platform/ios/MGLMapboxEvents.m
=> NSURLSession

include/mbgl/ios/MGLMapboxEvents.h, ios/app/app-info.plist, platform/ios/MGLMapView.mm, platform/ios/MGLMapboxEvents.m
=> Build Number To User Agent

platform/ios/MGLMapboxEvents.m
=> Optimizing fallback to digicert check strategy

platform/ios/MGLMetricsLocationManager.m
=> Throttling The Requested Accuracy Level Down

platform/ios/MGLMetricsLocationManager.m
For #1410 
/cc @sbma44 @camilleanne @mick @edenh @TheMarex @aaronlidman @morganherlocker
=> One Kilometer Desired Accuracy

include/mbgl/platform/default/glfw_view.hpp, include/mbgl/util/constants.hpp, linux/main.cpp, linux/mapboxgl-app.gypi, macosx/main.mm, macosx/mapboxgl-app.gypi, platform/default/default_styles.cpp, platform/default/default_styles.hpp, platform/default/glfw_view.cpp
Makes the life of people using Linux as development environment way
easier.
Just press 's' to cycle through 3 different styles.
=> Add style change functionality to the Linux test app

bin/render.cpp
Fix the broken build. We should probably build it on the bots, but we need to wait for https://github.com/travis-ci/travis-ci/issues/3759 first.
=> Render tool is broken

platform/ios/MGLMapboxEvents.m
=> Metrics Event TTL Fix

platform/ios/MGLMapboxEvents.m
=> Send All Events At Flush

.travis.yml, scripts/android/install.sh, scripts/android/run.sh, scripts/ios/install.sh, scripts/ios/package.sh, scripts/ios/run.sh, scripts/linux/install.sh, scripts/linux/run.sh, scripts/linux/setup.sh, scripts/osx/install.sh, scripts/osx/run.sh, scripts/osx/setup.sh
Needed to avoid code duplication in node-mapbox-gl-native travis scripts, refs https://github.com/mapbox/mapbox-gl-native/pull/1339, https://github.com/mapbox/node-mapbox-gl-native/pull/119.
=> break out setup.sh from run.sh

Makefile
=> bring back $JOBS for ios packaging

src/mbgl/renderer/painter.cpp
=> Set correct strata for background render

.travis.yml
@kkaefer Existing code is copypasta right? It seems to originate in 2b633cc51cd44be3f0224f0b105b18f0a3d7d657.
=> Run correct after_failure script

include/mbgl/ios/MGLAccountManager.h, ios/app/MBXAppDelegate.m
=> Adding Getter Method

platform/ios/MGLMapView.mm
Fixes the compass showing the old/wrong bearing when the device changes orientation.
/cc @incanus @1ec5 @bleege
=> Rotate compass on device orientation changes

src/mbgl/util/clip_id.cpp
=> Coverity [64756] Unintentional integer overflow

android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
Fixes #1264 
@incanus @bleege When you guys are happy with the new style menu this can be merged.
=> Update Android to use new styles

README.md
Fixes #1570 
@jfirebaugh Can you read to see if these instructions are good? It should be platform agnostic
=> Add README instructions for running on Android emulator and devices

platform/ios/MGLUserLocation.m
What’s a map without a You Are Here sticker?
/cc @incanus
=> Less bland default title for user dot annotation

ios/app/app-info.plist, platform/ios/MGLMapboxEvents.m
=> Manage Metrics TEST URL Via Info.plist

src/mbgl/geometry/glyph_atlas.cpp, src/mbgl/geometry/sprite_atlas.cpp, src/mbgl/text/placement.cpp
ports https://github.com/mapbox/mapbox-gl-js/pull/1195 to fix #1398
=> port sprite atlas pollution fix

platform/darwin/http_request_nsurl.mm
=> Adding mapbox.com checking to http requests

android/java/MapboxGLAndroidSDK/build.gradle, android/java/MapboxGLAndroidSDKTestApp/build.gradle
Fixes message in Android studio about broken layouts
=> Update Android gradle plugin to 1.2.3

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
Fixes a bug I found while looking at something else
=> Fix swapped lat/lng

test/resources/resource_loader.cpp
This will make the tests less verbose and at the same time make sure we are logging properly.
=> Add check for log messages on ResourceLoader tests

platform/ios/MGLMapboxEvents.m
=> Adding version and instance to Turnstile event

platform/ios/MGLMapboxEvents.m
=> Code Review Suggestions

include/mbgl/ios/MGLAccountManager.h, include/mbgl/ios/MGLMapView.h
Refs #1759 & works around current appledoc problem. 
/cc @1ec5
=> remove docs for unavailable API

README.md, platform/ios/MGLMultiPoint.mm
Fixed a typo in the bounds calculation, and updated README to include a missing dependency.
=> MGLMultiPoint bounds - bugfix

android/cpp/jni.cpp, android/cpp/native_map_view.cpp, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/NativeMapView.java, include/mbgl/android/jni.hpp, include/mbgl/android/native_map_view.hpp, include/mbgl/map/map.hpp, include/mbgl/map/view.hpp, include/mbgl/platform/default/glfw_view.hpp, include/mbgl/platform/default/headless_view.hpp, platform/default/glfw_view.cpp, platform/default/headless_view.cpp, platform/ios/MGLMapView.mm, src/mbgl/map/map.cpp, src/mbgl/map/map_context.cpp, src/mbgl/map/map_context.hpp, src/mbgl/map/map_data.hpp, src/mbgl/map/source.cpp, src/mbgl/map/transform.cpp, src/mbgl/map/transform.hpp, src/mbgl/map/transform_state.cpp, src/mbgl/map/transform_state.hpp, src/mbgl/map/view.cpp, test/fixtures/mock_view.hpp, test/miscellaneous/map_context.cpp, test/miscellaneous/transform.cpp, test/style/resource_loading.cpp
In most cases, the main/UI thread triggers rendering, except for our GLFW sample app.
=> Always drive rendering from the main thread

.ycm_extra_conf.py
Besides a couple file path modifiers, we need to manually add the OSX SDK system root path.
Follow-up for #1794.
@tmpsantos review?
=> Update YCM to support OSX

platform/default/sqlite_cache.cpp, platform/default/sqlite_cache_impl.hpp, src/mbgl/map/map_context.cpp, src/mbgl/map/map_context.hpp, src/mbgl/map/raster_tile_data.cpp, src/mbgl/map/source.cpp, src/mbgl/map/sprite.cpp, src/mbgl/map/vector_tile_data.cpp, src/mbgl/storage/default_file_source.cpp, src/mbgl/storage/default_file_source_impl.hpp, src/mbgl/text/glyph_pbf.cpp, src/mbgl/util/run_loop.hpp, src/mbgl/util/thread.hpp, src/mbgl/util/worker.cpp, test/miscellaneous/thread.cpp, test/storage/database.cpp, test/style/mock_file_source.cpp, test/style/resource_loading.cpp
Use util::RunLoop::getLoop() instead when it is needed. This will
simplify a bit our interfaces.
=> Do not pass uv_loop_t around

include/mbgl/ios/MGLMapView.h, platform/ios/MGLMapView.mm
=> Assert if -mapView:symbolNameForAnnotation: is implemented

include/mbgl/map/map.hpp
Fixes https://github.com/mapbox/mapbox-gl-native/issues/1859 in local stripped build testing.
=> refs #1859: use traditional struct declaration

include/mbgl/util/uv.hpp, platform/default/asset_request_zip.cpp, platform/default/glfw_view.cpp, platform/default/http_request_curl.cpp, platform/default/sqlite_cache_impl.hpp, platform/default/uv_zip.c, platform/default/uv_zip.h, src/mbgl/map/annotation.cpp, src/mbgl/map/tile_worker.cpp, src/mbgl/util/uv.cpp, src/mbgl/util/worker.cpp, src/mbgl/util/worker.hpp, test/fixtures/mock_view.hpp
Fixes a few issues found by cppcheck static analysis tool
=> cppcheck run

android/java/.gitignore, android/java/MapboxGLAndroidSDKTestApp/build.gradle, android/java/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java
=> Integrating Crashlytics / Fabric Into Android

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
=> Tighten Access Token Checking Logic

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/res/values/attrs.xml, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MapFragment.java, android/java/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_main.xml, android/java/MapboxGLAndroidSDKTestApp/src/main/res/layout/fragment_main.xml
=> MapView Instantiation Support

android/cpp/jni.cpp, android/cpp/native_map_view.cpp, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/NativeMapView.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java, include/mbgl/android/native_map_view.hpp
Hook up collisionDebug, isFullyLoaded, onLowMemory in Android
Rename class to styleClass in Java to match iOS
Fixed some formatting
Fixes #1905
Fixes #1946
Fixes #1263
=> First pass at updating JNI bindings

android/java/MapboxGLAndroidSDK/build.gradle, android/java/MapboxGLAndroidSDKTestApp/build.gradle
=> Removing Bit Rot

android/cpp/jni.cpp, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/Annotation.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/NativeMapView.java, include/mbgl/android/jni.hpp
Working towards https://github.com/mapbox/mapbox-gl-native/issues/1920
=> First pass at tidying up Android annotation code

Makefile, platform/default/png_reader.cpp
Fixed some nits left behind on the buildsystem refactoring.
=> New buildsystem follow-up

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
=> Adding Null Check For GPS Marker

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
=> Commenting Out setElevation() Usage

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
Checks if we have access to totalMemory (only on post-Jelly Bean devices).
Still need to work out what to do on older devices.
=> Check API level for totalMemory

android/java/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_main.xml
=> FAB Shadow

android/java/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_main.xml
Re-merging due to revert of PR #2034.  More details at https://github.com/mapbox/mapbox-gl-native/pull/2034#issuecomment-130456974
For #1856
=> Removal of FAB Shadow Take 2

Makefile, android/cpp/jni.cpp, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/NativeMapView.java
For https://github.com/mapbox/mapbox-gl-native/issues/1191
=> Implement setGestureInProgress on Android

scripts/main.mk
=> Fix xcpretty from swallowing xcodebuild error codes

.travis.yml
=> Remove MIPS target from Travis build matrix

src/mbgl/util/mapbox.cpp, test/miscellaneous/mapbox.cpp
fixes https://github.com/mapbox/mapbox-gl-style-spec/issues/309
ref https://github.com/mapbox/mapbox-gl-js/pull/1422, #1918 
:eyes: @jfirebaugh @jakepruitt @ansis @kkaefer
=> Support new glyph URL syntax

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/http/HTTPContext.java, platform/android/http_request_android.cpp
=> Use uv::async in HTTPAndroidRequest to ensure the correct thread deletes request object

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
=> removing annotations in mapview, not only in nativemapview

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/res/values/attrs.xml, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java
Fixes https://github.com/mapbox/mapbox-gl-native/issues/2090
Adds missing XML attributes.
Fixes bug where GPS stays on always after rotation.
=> Fix state saving on Android

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
Also adds Collections.unmodifiableList to returned lists from public methods
Fixes #1998
=> Adds getAnnotations to Android

platform/ios/MGLMapView.mm
=> Avoid deprecated CLLocationManagerDelegate method

ios/app/MBXViewController.mm, platform/ios/MGLMapView.mm
- Mapbox Streets -> Streets
- style version from string to integer
- 7 -> 8
@jfirebaugh Should we drop Outdoors from the style cycling mix in the iOS test app, given that there is no v8 of it?
=> iOS app/framework fixes for v8

INSTALL.md
@bleege  asked me to review the env. setup for Android. 
This PR contains 2 textual changes to INSTALL.md:
- more concrete example for path JAVA_HOME
- update outdated text of a menu item in Android Studio
=> Documentation Android build process

android/java/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> Use v8 styles on Android.

platform/ios/MGLMapView.mm
=> Disable heading updates for .FollowWithCourse

android/java/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_main.xml
=> Removing FAB Shadow In TestApp

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
as discussed in #1942
the event listeners should be converted to lists and the onfling and onscroll listeneers should probably have some parameters
=> added click, longclick, scroll, fling events

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
=> Fix crash when using MapView access token constructor

README.md, platform/node/CHANGELOG.md
/cc @jfirebaugh @bsudekum @lucaswoj
=> Update node changelog

.travis.yml
For #2253 
/cc @mapbox/mobile @jfirebaugh @kkaefer
=> Update Travis Android Config

android/cpp/jni.cpp, android/java/MapboxGLAndroidSDK/build.gradle, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/Annotation.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/InfoWindow.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/InfoWindowTipView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/Marker.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/NativeMapView.java, android/java/MapboxGLAndroidSDK/src/main/res/layout/infowindow.xml, android/java/MapboxGLAndroidSDK/src/main/res/values/colors.xml, android/java/MapboxGLAndroidSDK/src/main/res/values/strings.xml, android/java/MapboxGLAndroidSDKTestApp/build.gradle, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java
=> Android Popups / InfoWindows

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/Marker.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java
=> Supporting Custom InfoWindow TouchListeners

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
For #2244
/cc @incanus @ljbade @tobrun
=> Switch to TextureView

include/mbgl/ios/MGLPolyline.h
=> [iOS] Fix MGLPolyline documentation typo

platform/node/src/node_map.cpp, platform/node/test/js/map.test.js
=> [node] throw if a render is already pending, fixes #2247

android/cpp/native_map_view.cpp, include/mbgl/android/native_map_view.hpp, include/mbgl/storage/sqlite_cache.hpp, platform/default/sqlite_cache.cpp
For #2018 
/cc @incanus @ljbade
=> Fix DBLock For Android Rotation

INSTALL.md
add instructions to install Android Support Repository
=> add instructions to install Android Support Repository

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java
=> Remove Android style URL validation

android/cpp/native_map_view.cpp, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java, include/mbgl/map/map.hpp, src/mbgl/map/map.cpp
=> Fix freezing on Android when rotating

Makefile, android/java/.gitignore, android/java/MapboxGLAndroidSDKTestApp/build.gradle, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java, android/mapboxgl-app.gypi, scripts/android/run.sh
=> Add Crashlytics NDK to Android

android/cpp/jni.cpp, android/cpp/native_map_view.cpp, include/mbgl/android/native_map_view.hpp
Refactor NativeMapView to hold std::unique_ptr to Map and DefaultFileSource
Add missing asserts to attach_jni_thread/detach_jni_thread
Fixes #2406
=> Fix JNI crash in attach_jni_thread

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/Marker.java, android/java/MapboxGLAndroidSDKTestApp/build.gradle, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java
=> Improve Safety Around Remove Annotations

.travis.yml, bin/render.cpp, macosx/main.mm
=> disable -Wunused-local-typedef on OS X

android/java/MapboxGLAndroidSDK/gradle.properties
=> Setting VERSION_NAME To 0.1.0 For Release

android/java/MapboxGLAndroidSDK/gradle.properties, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/Marker.java
Android 0.1.0 has been released and pushed to the Sonatype Central Repository.  The final step of the process is to merge the release branch back into `master`.
/cc @mapbox/mobile @jfirebaugh @kkaefer
=> Merge release-android-0.1.0 Branch Back Into Master

android/java/MapboxGLAndroidSDK/gradle.properties, android/java/MapboxGLAndroidSDKTestApp/build.gradle
=> Updating Artifacts For 0.2.0 Development

android/java/MapboxGLAndroidSDK/build.gradle, android/java/MapboxGLAndroidSDKTestApp/build.gradle, android/java/build.gradle
=> Wrapping Android make Commands

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/geometry/BoundingBox.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/geometry/CoordinateSpan.java, android/java/MapboxGLAndroidSDKTestApp/src/test/java/BoundingBoxTest.java
Original PR #2376, related to #2374
=> Improved BoundingBox implementation + added testacases

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
=> Exposing attribution + logo visibility

android/java/MapboxGLAndroidSDK/build.gradle, android/java/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
Moved branch from forked to repo, original PR -> #2423 and issue -> #2223
=> Configuration for limiting resource visibility

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/widgets/CompassView.java
=> Refactored Compass in separate View class

android/cpp/jni.cpp, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/NativeMapView.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java
=> 2428 add markers bulk jni integration

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/CompassView.java
=> Fixing Import Statements From Previous Merge

android/cpp/jni.cpp
=> Fixing JNI References To New Package Structure

platform/ios/MGLMapView.mm
At some point, the `NSMapTable` we use internal to `MGLMapView` went from being a simple annotation-to-ID mapping and instead is keyed on annotation and maps to a dictionary (currently with keys `MGLAnnotationIDKey` for the ID integer and, optionally, `MGLAnnotationSymbolKey` for the sprite symbol string). 
This just renames this map table from `annotationIDsByAnnotation` to `annotationMetadataByAnnotation`. 
Refs https://github.com/mapbox/mapbox-gl-native/issues/2490
=> [ios] refactor annotation map table name

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
=> Add OnMarkerClickListener

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
Issue at #2076, original PR #2372
=> [android] #2076 expose getMetersPerPixelAtLatitude

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/InfoWindow.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/SecondMapActivity.java
had to move some parts in InfoWindow + Marker too make it work
See issue #2451
=> Add InfoWindowAdapter

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/InfoWindow.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
Marker click centers map on marker
Fixed up variable names
Closes #2507
Flip Y coordinate in to/fromScreenLocation
Fixes #2519
=> [android] Add OnMapClickListener, onMapLongClickListener

src/mbgl/renderer/painter.cpp
See backstory in #2527, but this is all that's needed here. 
/cc @adam-mapbox
=> refs #2527, fixes #774: properly unbind VAO

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> JavaDoc MapView part 4

include/mbgl/map/map.hpp, src/mbgl/map/map.cpp, src/mbgl/map/map_context.cpp, src/mbgl/map/map_data.hpp
=> Correctly handle spurious wake-ups in Map::pause()

src/mbgl/map/map.cpp
=> [core] Protect MapData.pause with a lock

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] JavaDoc MapView part 5

platform/ios/MGLMapboxEvents.m
No sense in letting more complicated aspects of this refactor hold up the simple changes.
/cc @mapbox/mobile @twbell @mikemorris
=> [iOS] Telemetry refactor, PHASE 1

android/java/.gitignore, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ApiAccess.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/InvalidAccessTokenException.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
Fix .gitignore for token.txt
Add JavaDoc to ApiAccess.
Create specific exception for missing access token.
Closes #2570
Closes #2563
=> Tidy up new ApiAccess token class.

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
=> [android] Refactor annotations functions

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] JavaDoc MapView part 6

android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PressForMarkerActivity.java
=> [android] Change PressForMarkerActivity to use OnMapLongClick event.

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ApiAccess.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/InvalidAccessTokenException.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] JavaDoc MapView Part 7

android/cpp/jni.cpp, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/NativeMapView.java
=> [android] Tidy up MapView API

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/InvalidAccessTokenException.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/package-info.java
=> Organizing Exceptions

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindowTipView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/res/layout/infowindow.xml
=> Moving InfoWindow classes to annotations package

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/Style.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowAdapterActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapFragmentActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PressForMarkerActivity.java
Implemented Style as mentioned in #2586
=> [android]  #2586 - Refactor Style with Android Support Annotations 

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #2586 - Replace MapChange enum with ints

src/mbgl/renderer/painter.cpp
For labels, there are currently situations where we show a combinations of parent and child tiles when zooming in. Since labels aren't clipped by the stencil buffers, this results in duplicate labels being shown until all child tiles have loaded.
I think the easiest way to solve this issue is to never show a combination of parent and child tiles. This might mean that we have to wait some time until we show a new tile, but we only need to do this when we *already* have the parent tile, so there's at least something that we can show.
Likely, this will also allow us to significantly reduce the "stencil mask overflow" messages, since we don't need to compute distinct mask IDs for partially covered tiles.
=> Show parent tile XOR child tiles

android/java/.gitignore, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
Closes #2602 
This reverts commit 67f0108389cdd51f3c59ae7638ea2ecd1c4fa899.
=> [android] #2602 InfoWindowAdapter Activity freezes on open

android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PressForMarkerActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_press_for_marker.xml
=> [android] #2606 - have test activity use map view object instantiation

android/java/MapboxGLAndroidSDK/build.gradle, android/java/MapboxGLAndroidSDK/src/main/java/overview.html
=> [android] Remove R and BuildType from JavaDoc. Remove iOS image.

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java
=> [android] Make Marker anchor property private

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] # 2659 - While zooming location change is incorrect

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> 2661 improve configuration location updates

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> 2663 animate user dot

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/CompassView.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
bearing is not done for milestone 2.1.0, cleanup code to resemble that state
=> 2666 cleanup bearing

README.md, test/ios/MapViewTests.m
This passes both Travis and Bitrise.
=> refs #2419: tweaks to iOS tests for Bitrise

src/mbgl/style/style_layer.cpp
Some property transitions were being set to their fallback values when no classes are being used. This issue is particularly perceived when the default transition duration is not zero (animated transitions).
/cc @tmpsantos @kkaefer @jfirebaugh
=> [core] Fix transition to default style when no classes are applied

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/Style.java, android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/java/MapboxGLAndroidSDK/src/main/res-public/values/public.xml, android/java/MapboxGLAndroidSDK/src/main/res/color/material_bg_selector.xml, android/java/MapboxGLAndroidSDK/src/main/res/drawable/ic_info_selector.xml, android/java/MapboxGLAndroidSDK/src/main/res/layout/attribution_list_item.xml, android/java/MapboxGLAndroidSDK/src/main/res/layout/infowindow_content.xml, android/java/MapboxGLAndroidSDK/src/main/res/layout/infowindow_view.xml, android/java/MapboxGLAndroidSDK/src/main/res/values/attrs.xml, android/java/MapboxGLAndroidSDK/src/main/res/values/strings.xml, android/java/MapboxGLAndroidSDK/src/main/res/values/styles.xml, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowAdapterActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow.xml, android/java/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow_adapter.xml
Use `_` in public resources ids
Make visibility attributes `enum`s
Make `attr`s public
Remove info window margin public value
Reformat XML code
Test app uses XML map properties for InfoWindow activities
Fixes #2703
=> Add style string resources

android/java/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/VisibleCoordinateBoundsActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_visible_bounds.xml, android/java/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> [android] #2716 - moved visible coordinate bounds to separate activity

android/cpp/jni.cpp, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/BulkMarkerActivity.java, platform/default/default_styles.cpp
Change test to 1000 markers
For #2726
=> [android] Fix JNI local ref overflow

android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/BulkMarkerActivity.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/TimingLogger.java
=> [android] Test max 27.4k markers

android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/CompassView.java, android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/BulkMarkerActivity.java
=> [android] Fix disabling compass

src/mbgl/annotation/shape_annotation_impl.cpp
=> [core] Fix integer overflow for high maximum zoom levels

gyp/platform-ios.gypi, platform/ios/MGLAccountManager.m, platform/ios/vendor/Fabric, platform/ios/vendor/Fabric.framework/Headers/FABAttributes.h, platform/ios/vendor/Fabric.framework/Headers/FABKitProtocol.h, platform/ios/vendor/Fabric.framework/Headers/Fabric+FABKits.h, platform/ios/vendor/Fabric.framework/Headers/Fabric.h, platform/ios/vendor/Fabric.framework/Info.plist, platform/ios/vendor/Fabric.framework/Modules/module.modulemap
More to do here, but this is a start.
=> refs #2684: integrate Twitter Fabric

android/java/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
=> [android] Remove the WRITE_EXTERNAL_STORAGE permission from test app

android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow.xml, android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow_adapter.xml, android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_main.xml, android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_map_fragment.xml, android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_marker_bulk.xml, android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_press_for_marker.xml, android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_visible_bounds.xml
=> [android] #2523 - fix toolbar alignment issue

src/mbgl/map/vector_tile_data.cpp
=> [core] Initialize attributes before using them

android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/BulkMarkerActivity.java, android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/GeoParseUtil.java, android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/TimingLogger.java, android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_marker_bulk.xml, android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> 2726 add markers in bulk

platform/android/native_map_view.cpp
=> [android] Restore old GL context after createSurface

platform/android/native_map_view.cpp
=> [android] Fix crash on Marshmallow

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] Fix NullPointerException in editor mode

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] Remove NullPointerException from MapView

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java, android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
=> [android] Grey out GPS marker when location is stale

INSTALL.md
Updates `INSTALL.md` with libuv version recommendation and new project URL. This would be a good opportunity to check that the rest of our listed dependencies are up-to-date @mapbox/gl.
Refs #2609
=> [meta] update INSTALL dependencies

platform/default/sqlite_cache.cpp, src/mbgl/util/thread.hpp
Makes debugging/profiling easier.
=> [core] Set names to threads on Linux

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java, android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/PolygonOptions.java, android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/PolylineOptions.java
=> [android] Implement Parcelable annotations

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java
=> [android] #2864 - improved compass update cycle, removed lowpassfilter

android/MapboxGLAndroidSDK/gradle.properties
=> Setting Up Android 2.3.0-SNAPSHOT Mode

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] Adjust annotation touch tolerance to match default marker

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PressForMarkerActivity.java
=> [android] Save added markers in test app

CONTRIBUTING.md
Text copied mostly from https://www.mapbox.com/about/open/.
/cc @mapbox/gl @mapbox/mobile
=> Add code of conduct to CONTRIBUTING

package.json, platform/node/CHANGELOG.md
=> [node] Update to pre11, update changelog

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml, android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml, android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
=> [android] Add setZoomControlsEnabled and setAllGesturesEnabled

platform/node/CHANGELOG.md, platform/node/README.md, platform/node/src/node_map.cpp, platform/node/test/js/map.test.js
=> make ratio optional, default to 1.0

src/mbgl/map/map_context.cpp, src/mbgl/map/source.cpp, src/mbgl/renderer/painter.cpp, src/mbgl/renderer/painter.hpp
Seems like #2138 got reverted, but was never revisited. Since this boosts performance quite a bit, we should bring it back.
=> Speed up time to first render call (again)

src/mbgl/storage/http_context_base.hpp
=> [core] Added missing virtual destructor to HTTPContextBase

package.json, scripts/node/after_script.sh, scripts/node/package-version.js
Refs #2365
If a git tag beginning with `node-v*` points at `$TRAVIS_COMMIT`.
/cc @lucaswoj @bsudekum
=> autopublish node-pre-gyp binary

platform/ios/MGLMapView.mm
This PR ensures that `-[MGLMapViewDelegate mapView: regionDidChangeAnimated:]` calls only go out after programmatic animations come to an end. It also adds willChange/didChange calls around pitch changes.
Fixes #2436. Related to #2700.
=> Defer didChange until after animation

src/mbgl/map/source.hpp
Instead of hardcoding the tile size again.
=> [core] Use tileSize constant

android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
=> [android] Check for location permission in MyLocationTrackingModeActivity

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/SpriteFactory.java, android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java
Also tidy android.os.Build refs
Fixes #2976
=> [android] Fix Canvas.quickReject() crash on API 15

docs/DEVELOP_ANDROID_OSX.md
=> Updating Android Setup Instructions

android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
=> [android] #3001 add config changes example to test app

android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/VisibleCoordinateBoundsActivity.java, android/MapboxGLAndroidSDKTestApp/src/main/res/values/dimens.xml
=> [android] #3019 - optimise visible coordinatebounds

android/MapboxGLAndroidSDKTestApp/build.gradle, docs/DEVELOP_ANDROID_LINUX.md, docs/DEVELOP_ANDROID_OSX.md
=> [android] #3023 - reactive token generation

ios/app/MBXViewController.mm
=> Demonstrate show annotations in iosapp

CHANGELOG.md
=> Attach compass gesture recognizer to compass view

platform/ios/MGLMapView.mm, test/ios/MapViewTests.m
Coalescing willChange/didChange callbacks means keeping track of how many gestures are currently in progress; by contrast, tracking this state with a boolean opens the door to many race conditions. This change refactors the gesture recognizers, making them more consistent with each other, more consistent in the case where more than one of them has fired, and a whole lot easier to reason about. It also explicitly cancels transitions before all programmatic viewport-modifying methods, since mbgl only does so when animating.
Two behavioral changes result from this PR:
* When the map automatically rotates back to 0° at low zoom levels, that animation gets a separate willChange/didChange pair. Coalescing the two pairs will be possible again once we implement #1581.
* Drift-panning, …
=> Ensure consistent willChange/didChange callbacks

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/GeoConstants.java, android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java, android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MathConstants.java, android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> Make OnMapChangeListener Enum Docs More Helpful 

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyBearingTracking.java, android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyLocationTracking.java, android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java
=> [android] - #2862 Correct behaviour when switching between tracking modes, added javadoc

src/mbgl/annotation/shape_annotation_impl.cpp, src/mbgl/map/map_context.cpp, src/mbgl/map/tile_worker.cpp, src/mbgl/map/tile_worker.hpp, src/mbgl/map/vector_tile_data.cpp, src/mbgl/renderer/painter.cpp, src/mbgl/renderer/painter.hpp, src/mbgl/style/style.cpp, src/mbgl/style/style.hpp, src/mbgl/style/style_bucket_parameters.hpp, src/mbgl/style/style_layer.cpp, src/mbgl/style/style_parser.cpp, src/mbgl/style/style_parser.hpp, src/mbgl/util/worker.cpp, src/mbgl/util/worker.hpp
:eyes: @brunoabinader @kkaefer Yet more Style API preparation.
=> [core] More threadsafety for Style / StyleLayer

src/mbgl/renderer/painter.cpp, src/mbgl/renderer/painter_fill.cpp, src/mbgl/renderer/painter_line.cpp, src/mbgl/renderer/symbol_bucket.cpp, src/mbgl/sprite/sprite_atlas.cpp, src/mbgl/sprite/sprite_atlas.hpp, test/sprite/sprite_atlas.cpp
=> fill-pattern areas flash black during load

platform/ios/MGLAccountManager.m, platform/ios/MGLCategoryLoader.m
=> fixes #3113: bring in map view in absence of -ObjC linker flag for IB

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3188 - Save tilt value under a change in device orientation

android/MapboxGLAndroidSDK/gradle.properties, android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties
=> Merge 2.3.0 Release Branch

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, android/MapboxGLAndroidSDKTestApp/src/test/java/annotations/MarkerTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/geometry/BoundingBoxTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/geometry/CoordinateBoundsTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/geometry/CoordinateRegionTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/geometry/CoordinateSpanTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/geometry/LatLngTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/geometry/LatLngZoomTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/geometry/ProjectedMetersTest.java
Closes #3215 
- added unit test for marker 
- moved tests to their own dedicated packages (annotation vs geometry)
- added toString method to Marker
=> [android] #3215 added unit test for marker

platform/default/run_loop.cpp
=> [core] Better C++ usage on RunLoop

platform/node/README.md
Fixes #2672
@miccolis @bsudekum is this documentation clear enough?
=> document node bindings EventEmitter interface

android/MapboxGLAndroidSDKTestApp/src/test/java/annotations/MarkerTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/annotations/PolygonTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/annotations/PolylineTest.java
=> [android] #3221 - added unit test for Polyline and Polygon, updated test for Marker

src/mbgl/renderer/painter.cpp, src/mbgl/renderer/painter_circle.cpp, src/mbgl/renderer/painter_clipping.cpp, src/mbgl/renderer/painter_fill.cpp, src/mbgl/renderer/painter_raster.cpp
=> [core] Ensure GL state is set to necessary values in more places

android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/TiltActivityTest.java
=> [android] #3224 - add espresso test for TiltActivity

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java
=> [android] #3240 - Reimplemented compass algorithm for compass bearing fixed switching between user location tracking modes

gyp/shaders.gypi, scripts/build-shaders.py, src/mbgl/shader/box_shader.cpp, src/mbgl/shader/circle_shader.cpp, src/mbgl/shader/dot_shader.cpp, src/mbgl/shader/icon_shader.cpp, src/mbgl/shader/line_shader.cpp, src/mbgl/shader/linepattern_shader.cpp, src/mbgl/shader/linesdf_shader.cpp, src/mbgl/shader/outline_shader.cpp, src/mbgl/shader/pattern_shader.cpp, src/mbgl/shader/plain_shader.cpp, src/mbgl/shader/raster_shader.cpp, src/mbgl/shader/sdf_shader.cpp
We're currently rebuilding shaders no matter what.
=> Only rebuild shaders when something changed

android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
Updates order of lifecycle methods, as per @tobrun's suggestion in #2957, to: 
```
onCreate();
onStart();
onResume();
onPause();    
onStop();
onDestroy();
```
=> updates order of lifecycle methods. Addresses #2957

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java
=> [android] #3248 - enforce application context in a singleton

android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
=> [android] #3246 disable zoom controls

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3245 Reverse Tilt Gesture

android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/VisibleCoordinateBoundsActivity.java
=> [android] #3267 limit user input as an example to VisibleCoordinateBounds

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3191 - remove double direction state

android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java
=> [android] #3262 stop listening to bearing when state switches

docs/DEVELOP_ANDROID_OSX.md
Fixes #3266
cc @bleege for the review
=> Expand DEVELOP_ANDROID_OSX with more gotchas.

android/MapboxGLAndroidSDKTestApp/src/test/java/BoundingBoxTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/CoordinateBoundsTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/CoordinateRegionTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/CoordinateSpanTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/LatLngTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/LatLngZoomTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/MarkerTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/PolygonTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/PolylineTest.java, android/MapboxGLAndroidSDKTestApp/src/test/java/ProjectedMetersTest.java
=> [android] #3311 fix unit test configuration

gyp/platform-ios.gypi, include/mbgl/ios/MGLMapView+MGLCustomStyleLayerAdditions.h, include/mbgl/ios/Mapbox.h, ios/app/MBXViewController.mm, platform/ios/MGLMapView.mm
This needs to be converted into a giant switch statement, but that wouldn’t prevent issues like this cropping up in a merge anyways.
=> Fix off-by-one error due to merge

include/mbgl/util/constants.hpp, src/mbgl/map/map.cpp, src/mbgl/map/transform.cpp, src/mbgl/util/constants.cpp
Also factored out the maximum pitch into a constant.
/cc @bleege
=> Clamp pitch in easeTo(), flyTo()

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/CameraActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_camera.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> Refine Android Camera API

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/layers/ExampleCustomLayer.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_now_wallpaper_24dp.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_drawer.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml, platform/android/src/example_custom_layer.cpp
=> Custom Layer House Cleaning

INSTALL.md, Makefile, platform/ios/scripts/install.sh, platform/ios/scripts/test.sh, platform/osx/scripts/install.sh, scripts/main.mk, scripts/xcpretty.sh
It's buggy and hides necessary diagnostics.
cc @1ec5 @incanus
=> [ios, osx] Drop xcpretty

platform/android/MapboxGLAndroidSDKTestApp/build.gradle, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
=> Removing Crashlytics From TestApp

gyp/platform-ios.gypi
This fixes iosapp builds.
/cc @jfirebaugh @friedbunny
=> Add SQLite, zlib linker flags

include/mbgl/platform/log.hpp, include/mbgl/util/string.hpp, test/fixtures/resources/style.json, test/style/resource_loading.cpp
Make it more readable and easier to debug.
cc @brunoabinader
=> [tests] Rewrite resource loading test

platform/osx/app/AppDelegate.m
=> Restore last viewed style at launch

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3283 - fix setCenterCoordinate animation

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> Improve Camera API Callbacks

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPContext.java
=> [android] better http log messages

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] Fix zoom gestures when scrolling is disabled

platform/osx/src/MGLMapView.mm
=> Double-tap to zoom out on Magic Mouse

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/BoundingBox.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/BoundingBoxTest.java
=> [android] #3308 - remove default constructor

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java
=> [android] #3397 - animating change of direction

.jazzy.yaml, LICENSE.md, ios/app/app-info.plist, ios/benchmark/app-info.plist, platform/android/MapboxGLAndroidSDK/build.gradle, test/ios/LaunchScreen.xib
=> Happy new year!

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] Fixes crash related to location listener

src/mbgl/layer/symbol_layer.cpp, src/mbgl/map/source.cpp, src/mbgl/map/tile_worker.cpp, src/mbgl/map/tile_worker.hpp, src/mbgl/map/vector_tile_data.cpp, src/mbgl/map/vector_tile_data.hpp, src/mbgl/renderer/painter_symbol.cpp, src/mbgl/renderer/symbol_bucket.cpp, src/mbgl/renderer/symbol_bucket.hpp, src/mbgl/style/style.cpp, src/mbgl/style/style_bucket_parameters.hpp, src/mbgl/style/style_update_parameters.hpp
To minimize label clipping.
/cc @bsudekum @ansis @miccolis
=> always add labels to buffers in MapMode::Still

package.json
adds render test for #2829
diff:
=> add test for text clipping at tile edges

package.json, platform/node/CHANGELOG.md
=> [node] bump version to v2.2.1

package.json, src/mbgl/text/font_stack.cpp, src/mbgl/text/font_stack.hpp
re: https://github.com/mapbox/mapbox-gl-native/issues/3469
=> Fix text offset bug

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3481 - add check to enable location in tracking mode

platform/default/online_file_source.cpp
In every case where setResponse is called, notify was called soon after. In one case immediately, in another, after intervening functions which are safe to reorder after notifications.
The null-check of response is safe to eliminate because response must not be null inside setResponse.
cc @kkaefer
=> [core] Merge OnlineFileRequestImpl::notify into OnlineFileRequestImpl::setResponse

platform/android/MapboxGLAndroidSDKTestApp/build.gradle, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java
=> [android] #2184 - added LeakCanary to Android test app

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3498 - disable missing permission lint check inline

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapFragmentActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PressForMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/TiltActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow_adapter.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow_concurrent.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_marker_bulk.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_my_location_tracking.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_polyline.xml
=> 3327 inconsitent zoom vs zoomlevel

platform/android/tests/README.md, platform/android/tests/docs/EXERCISER_TESTS.md, platform/android/tests/docs/PERFORMANCE_TESTS.md, platform/android/tests/docs/UI_TESTS.md, platform/android/tests/docs/UNIT_TESTS.md, platform/android/tests/scripts/devicefarm.py
Closes #3347 
:eyes: @zugaldia
=> 3447 add test documentation

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/BulkMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/CoordinateChangeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapFragmentActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MyLocationTrackingModeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PressForMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/TiltActivity.java
=> [android] #3309 - replace coordinate naming with LatLng

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java
=> [android] #3518 - fix context leak InfoWIndow by using a WeakReference

platform/ios/scripts/package.sh
Fixes #3521.
/cc @RomainQuidet @friedbunny
=> Always run jazzy against iOS Simulator

package.json, src/mbgl/renderer/painter_fill.cpp, src/mbgl/shader/pattern.vertex.glsl, src/mbgl/shader/pattern_shader.hpp
=> [core] seamless fill-pattern

platform/android/MapboxGLAndroidSDKTestApp/build.gradle
=> [android] #3531 - disable proguard in test app

platform/android/MapboxGLAndroidSDK/proguard-rules.pro, platform/android/MapboxGLAndroidSDKTestApp/proguard-rules.pro
=> [android] #3514 - update pro guard for custom layers package

src/mbgl/renderer/painter_symbol.cpp, src/mbgl/shader/icon_shader.hpp, src/mbgl/shader/sdf_shader.hpp
=> set u_texture uniform value for sdf and icon shaders

package.json, src/mbgl/renderer/painter_line.cpp
=> fix overscaled line patterns and re-enable render tests

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3535 - improve disabling tracking modes

platform/android/MapboxGLAndroidSDK/build.gradle, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPContext.java
=> [android] #3461 - upgrade to okhttp3 for faster tile loading! :rocket:

platform/node/src/node_request.cpp, platform/node/test/render.test.js
=> [test] Don't pass raw strings as error message

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3450 - fix rotation when enabling user location

platform/android/build.gradle
=> [android] #3052 - update gradle to 2.10

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3517 - recreating InfoWindow with correct MapView instance

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java
=> [android] #3573 - Marker clicks stop working after orientation change

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/DoubleMapActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_dns_24dp.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/fragment_double_map.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_drawer.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> [android] #3593 - added double map view example

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java
=> [android] #3507 - fix location listener leak in UserLocationView

platform/default/glfw_view.cpp
Follow-up of the transform refactoring.
=> [glfw] Fix panning direction

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapFragment.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Annotation.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Icon.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/IconFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MultiPoint.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/PolygonOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/PolylineOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/CoordinateBounds.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/CoordinateRegion.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/CoordinateSpan.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/ILatLng.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/IProjectedMeters.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngZoom.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/ProjectedMeters.java
=> 3338 add javadoc annotations package

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3525 - fix ConnectivityManager context leak

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> [android] #3156 - improving marker selection touch handling

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PolylineActivity.java
=> [android] #3604 - polyline activity memory leak fix

platform/android/MapboxGLAndroidSDK/build.gradle
=> [android] #3608 - upgrade okhttp3 to version 2

package.json, platform/node/CHANGELOG.md
Tag node-v2.2.2 release and update changelog.
=> node-v2.2.2

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/UserLocationView.java
=> [android] #3661 - GPS heading with extra rotation fix

package.json, src/mbgl/text/collision_feature.cpp, src/mbgl/text/collision_feature.hpp
port https://github.com/mapbox/mapbox-gl-js/pull/1981
=> [core] fix missing icon collision boxes

platform/ios/src/MGLMapView.mm
Adding Settings.bundle is no longer a requirement to get started.
/cc @1ec5
=> [ios] Update IB designables message to remove Settings.bundle mention

ios/framework/Mapbox.h
=> Quote umbrella header imports

platform/ios/src/MGLMapView.mm
Fixed a regression from #3261, as reported in https://github.com/mapbox/mapbox-gl-native/issues/3159#issuecomment-174422048.
=> Allow removing never-added annotations

src/mbgl/annotation/annotation_manager.cpp, src/mbgl/renderer/painter_symbol.cpp, src/mbgl/style/style.cpp
=> [core] bump sprite atlas to 1024x1024

platform/android/MapboxGLAndroidSDKTestApp/build.gradle, platform/android/tests/docs/UI_TESTS.md, platform/android/tests/docs/UNIT_TESTS.md
=> [android] #3708 - enable code coverage + docs

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPContext.java, platform/android/MapboxGLAndroidSDKTestApp/build.gradle, platform/android/tests/docs/UI_TESTS.md, platform/android/tests/docs/UNIT_TESTS.md
=> 3692 fix nullpointer exception message

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java
=> Commenting out content padding in MapView API

CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPContext.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties
=> Merge release-android-v3.2.0 In Master

src/mbgl/style/style.cpp, src/mbgl/style/style_parser.cpp, src/mbgl/style/style_parser.hpp, test/miscellaneous/style_parser.cpp
=> [core] Move rapidjson document creation into StyleParser

src/mbgl/map/source.cpp, src/mbgl/map/source_info.hpp, src/mbgl/style/style_parser.cpp
=> [core] Camel-case member names

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/CoordinateChangeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/DoubleMapActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/ManualZoomActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/VisibleCoordinateBoundsActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
=> 3760 introduce ui settings

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/ManualZoomActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
=> 3753 optimizing zoom

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
=> [android] #3776 - UiSettings uses MapView instead of MapboxMap

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/SupportMapFragmentActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_drawer.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> [android] #3759 - Add SupportMapFragment

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
=> [android] #3736 - clicks should ignore marker validation

src/mbgl/map/map_context.cpp, src/mbgl/map/transform_state.cpp, src/mbgl/map/transform_state.hpp, src/mbgl/renderer/painter.cpp, src/mbgl/renderer/painter_symbol.cpp
=> Cleanup TransformState

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraUpdateFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/ScrollByActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_input_24dp.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_scroll_by.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_drawer.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> 3752 scroll by camera update

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraUpdateFactory.java
=> [android] #3811 - handle null target value by using previous position

include/mbgl/storage/response.hpp, platform/android/src/http_request_android.cpp, platform/darwin/http_request_nsurl.mm, test/fixtures/stub_file_source.cpp, test/fixtures/stub_file_source.hpp, test/sprite/sprite_store.cpp, test/storage/storage.hpp, test/style/glyph_store.cpp, test/style/source.cpp
=> Fix request cancelling tests; eliminate Response::Error::Reason::Canceled

platform/ios/INSTALL.md
Show how to point a podspec at an officially tagged pre-release.
=> [ios] Explain prerelease testing in docs

platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/utils/MockParcel.java
=> [android] #3830 added mocked parcel implementation

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowActivity.java
=> [android] #3747 - InfoWindowLongClickListener

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/CameraActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
=> 3745 on camera change listener

platform/android/MapboxGLAndroidSDK/build.gradle
=> [android] #3852 - upgrade to okhttp 3.1.1

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowActivity.java
=> [android] #3746 - InfoWindowCloseListener

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
=> [android] #3895 - handles the case of not requested/accepted permissions

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java
=> [android] #3876 - rename InfoWindowClickListener method

Makefile, gyp/linux.gyp, platform/linux/scripts/run.sh, platform/osx/scripts/run.sh, scripts/main.mk
And also make the target available for Linux users.
=> [build] Build `offline` tool on the Linux bots

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/TelemetryLocationReceiver.java
=> No More Beep

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/MainActivityScreenTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/DrawerUtils.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/GestureUtils.java
=> [android] #3919 - restore espresso tests

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MyLocationTrackingModeActivity.java
=> [android] #3900 - Using CopyWriteArrayList

platform/android/MapboxGLAndroidSDK/build.gradle
=> Upgrading OkHttp to version 3.1.2

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
=> [android] #3895 - remove request permission annotation

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java
=> Using ApplicationContext Instead Of Activity Context

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/IconFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/BulkMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/GeocoderActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowAdapterActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PolylineActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/annotations/CityStateMarker.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/annotations/CityStateMarkerOptions.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
=> [android] #3756 - unit test annotations integration in MapboxMap

include/mbgl/util/math.hpp, package.json, src/mbgl/layer/line_layer.cpp, src/mbgl/renderer/line_bucket.cpp, src/mbgl/renderer/line_bucket.hpp, src/mbgl/util/clip_lines.cpp
port https://github.com/mapbox/mapbox-gl-js/pull/2043 and https://github.com/mapbox/mapbox-gl-js/pull/2113
fix #2607
=> less slanted dashes near sharp corners

platform/android/MapboxGLAndroidSDK/proguard-rules.pro, platform/android/MapboxGLAndroidSDKTestApp/proguard-rules.pro
=> [android] #3750 - update proguard library for 4.0.0 release

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/CameraActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/CoordinateChangeActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/DirectionsActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/DoubleMapActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/GeocoderActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/InfoWindowConcurrentActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/LatLngBoundsActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/MainActivityScreenTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/MainActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/ManualZoomActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/MapPaddingActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/MapboxMapActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/MaxMinZoomActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/ScrollByActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/SupportMapFragmentActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/DoubleMapActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/fragment_double_map.xml
=> [android] #3941 - update espresso tests

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
=> [android] #3976 - remove annotations doesn't work

platform/android/MapboxGLAndroidSDK/build.gradle, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CompassView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ApiAccess.java, platform/android/MapboxGLAndroidSDK/src/main/res/layout/attribution_telemetry_view.xml, platform/android/MapboxGLAndroidSDK/src/main/res/layout/infowindow_content.xml, platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapview_internal.xml, platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml, platform/android/MapboxGLAndroidSDKTestApp/build.gradle, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_directions.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow_adapter.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow_concurrent.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_mapboxmap.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_marker_bulk.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_my_location_tracking.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_polyline.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/fragment_double_map.xml
=> [androd] #3119 - use resourcePrefix for library resources

platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/IconTest.java
=> [android] #4000 - add unit tests icon

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/InfoWindowTest.java
=> [android] #4003 - add unit tests for InfoWindow

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/VisibleRegion.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/ProjectedMetersTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/VisibleRegionTest.java
=> [android] #4007 - improve coverage geometry package

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UserLocationView.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/TrackingSettingsTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
=> [android] #4009 - add tests for tracking settings

platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/camera/CameraPositionTest.java
=> [android] #4015 - added unit test for CameraPosition

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
=> [android] #4017 - update unit test for MapboxMap

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java, platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MaxMinZoomActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
=> 4018 move maxmin zoomlevel configuration

platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngSpanTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/ProjectedMetersTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/VisibleRegionTest.java
Refs #3832 cc @tobrun for the review.
=> Hit missed lines in equality tests

platform/android/MapboxGLAndroidSDK/build.gradle
=> [android] #4040 - disable resource prefix

platform/darwin/src/http_request_nsurl.mm
The lock is in place to enforce that `async` is not accessed if the request has been cancelled. Therefore it's not necessary to hold the lock beyond setting cancelled to true, and in fact it's unsafe to so: if this is the last remaining shared reference, `delete this` will destroy the mutex. If the lock was held, it would then be orphaned.
Fixes #4025.
=> [ios, osx] Don't delete a mutex with an active lock

.travis.yml, Makefile, README.md, platform/linux/scripts/coveralls.sh, scripts/coveralls.sh, scripts/main.mk
=> [tests] Upload coverage reports to coveralls.io

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
=> [android] #4057 - quick zoom fix

platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
=> [android] #4050 - expose style urls via public.xml

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
=> [android] #3688 - naming consistency bearing and direction

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
=> [andriod] #4051 - add callback to move camera api

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
=> [android] #4038 - fix crash on polygons and polylines

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationListener.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationService.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UserLocationView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java
=> 4083 relax permission check

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyBearingTracking.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyLocationTracking.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/UserLocationView.java, platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapview_internal.xml
=> [android] #4094 - bring back view package

platform/android/MapboxGLAndroidSDK/build.gradle, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEvent.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java
=> Converting Android Telemetry To V2 Data Model

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/layers/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/OnMapReadyCallback.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/ViewSettings.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/UserLocationView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/package-info.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/package-info.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/MainActivityTest.java
=> [android] #4097 - update javadoc maps package

platform/android/MapboxGLAndroidSDK/build.gradle, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java, platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml, platform/android/MapboxGLAndroidSDK/src/main/res/layout/attribution_telemetry_view.xml, platform/android/MapboxGLAndroidSDK/src/main/res/layout/infowindow_content.xml, platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapview_internal.xml, platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_directions.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow_adapter.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow_concurrent.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_mapboxmap.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_marker_bulk.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_my_location_tracking.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_polyline.xml
=> [android] #4021 - fix up library resource prefix

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/DynamicMarkerChangeActivity.java
=> [android] #4063 - fix update point annotation broken

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/TelemetryLocationReceiver.java
=> Remove ApiAccess From MapboxEventsManager

include/mbgl/util/constants.hpp, platform/default/online_file_source.cpp, src/mbgl/util/constants.cpp
Fix no viable conversion on OSX.
=> [core] Build fix

platform/android/src/jni.cpp
=> [android] Remove invoke to DeleteGlobalRef to avoid client crash

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/TelemetryService.java
=> Flushing Telemetry Events At App Termination

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
=> [android] #4126 - make zoom package private

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPContext.java
=> [android] Set log level of successful HTTP requests to verbose

platform/android/MapboxGLAndroidSDK/build.gradle, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java
=> OkHttp 3.2.0 And SHA256 Certificate Pins

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/CameraActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/CoordinateChangeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/DoubleMapActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/DynamicMarkerChangeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/GeocoderActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/LatLngBoundsActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/ManualZoomActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapFragmentActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapPaddingActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxMapActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MaxMinZoomActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/OfflineActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PressForMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/ScrollByActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/TiltActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
closes #4166 
:eyes: @bleege @zugaldia
=> [android] #4166 - move style url to map view for improved async loading

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/GeocoderActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_droppin_24dp.xml
=> [android] #4149 - added a drop pin example to the GeocoderActivity

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/UserLocationView.java, platform/android/src/jni.cpp
=> [android] #3867 - performance improvement for invalidating the camera

src/mbgl/map/map.cpp, src/mbgl/map/transform_state.cpp, src/mbgl/map/transform_state.hpp, src/mbgl/renderer/line_bucket.cpp, src/mbgl/renderer/painter_fill.cpp, src/mbgl/renderer/painter_line.cpp, src/mbgl/renderer/symbol_bucket.cpp, src/mbgl/util/mapbox.cpp
Minor leftovers from #3873.
:eyes: @kkaefer @jfirebaugh
=> TransformState cleanups & constants usage

platform/android/src/jni.cpp
=> [android] Make listOfflineRegions include definitions

platform/ios/src/MGLAPIClient.m, platform/ios/src/MGLMapView.mm, platform/ios/src/MGLMapboxEvents.h, platform/ios/src/MGLMapboxEvents.m
=> [iOS] Update iOS Telemetry for V2

include/mbgl/platform/default/headless_display.hpp, include/mbgl/platform/default/headless_view.hpp, include/mbgl/style/types.hpp, src/mbgl/renderer/painter.hpp, src/mbgl/util/thread.hpp, test/storage/offline_database.cpp
We're currently not initializing a few fields according to clang-tidy.
=> Initialize all fields

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
=> [android] #4211 - avoid crashes when NativeMapView is being destroyed

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/AnimatedMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_compare_arrows_black_24dp.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_animated_marker.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_drawer.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> [android] #4206 - property animation example

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java, platform/android/src/jni.cpp
Including #4202.
:eyes: @zugaldia @bleege
=> [android] Fix various offline JNI issues

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/OfflineActivity.java
=> [android] Reporting is no longer an issue

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/AnimatedMarkerActivity.java
=> [android] #4217 - fix build warning casting a varargs

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
=> Removing WAKE_LOCK from TestApp's AppManifest

platform/android/src/native_map_view.cpp
=> [android] #3631 - resize fix issue

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/IconBitmapChangedException.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/InvalidAccessTokenException.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/TelemetryServiceNotConfiguredException.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/TooManyIconsException.java
=> [android] #4078 - improve exception message

platform/default/mbgl/storage/offline_download.cpp, test/storage/offline_download.cpp
Refs #4229. There are likely additional issues besides this one. Hopefully fixing this will make the other issues easier to figure out.
=> [core] Ensure OfflineRegionStatus::downloadState is accurately reported

platform/android/src/native_map_view.cpp, platform/android/src/native_map_view.hpp
=> [android] #4240 - add flag to resize only when needed.

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
Speculative fix for #4255.
cc @tobrun
=> [android] Route exceptions in HTTPRequest constructor to onFailure

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
=> [android] #4263 - define multiple callbacks for OnMapReady

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/PolylineActivity.java
=> [androd] #4269 - polyline activity crash fix

CHANGELOG.md, src/mbgl/map/transform.cpp, test/map/transform.cpp
Added missing case. Really fixes #4155 this time.
:eyes: @tobrun
=> [core] Fix screen coordinates when crossing the antimeridian (#2)

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/MainActivityTest.java
=> [android] #4273 - library resource prefix espresso update

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java
=> [android] #4283 - strict mode

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java
=> [android] #4252 - close concurrent window fix

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java, platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
=> [android] #4304 - logo visibility fix for attributes defined in xml

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MaxMinZoomActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/OfflineActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
=> [android] #4318 - move min/max zoom level to MapboxMap

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java
=> [android] #4320 - rename including to contains

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapUtils.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/robotium/SimpleRotateTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/robotium/SimpleZoomTest.java
=> [android] #4308 - add some simple gesture tests

platform/default/online_file_source.cpp, test/storage/http_expires.cpp
Regression introduced by 59a45b8400c1c0.
=> [core] Fix regression of prior expiration time not being respected

platform/ios/src/MGLLocationManager.m
This increases the distance filter to five meters. The additional location data captured at 1 meter is not required.
cc @1ec5
=> [iOS] Increase distance filter

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java
=> Initialize Only Once Please

platform/default/mbgl/storage/offline_database.cpp
Endeavor to obtain the `what()` from exceptions like #4382 and #4387.
:eyes: @1ec5
=> [core] Add additional logging for exceptions during database connection / creation

platform/darwin/README.md
cc @1ec5 is this readme accurate?
=> Add Darwin readme

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java, platform/android/src/native_map_view.cpp, platform/default/mbgl/storage/offline_database.cpp
closes #4327
Workaround solution for `4.0.0` release, I ticketed the need for a real solution in #4406
cc @bleege @zugaldia
=> [android] #4327 - OnDoubleTap needs to trigger camera invalidation 

platform/android/bitrise.yml
=> [android] #4365 - add Bitrise step to upload APK file to AWS s3

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
=> [android] Add Javadoc for offline package

src/mbgl/util/token.hpp, test/util/token.cpp
=> [core] Allow the use of special characters in property field names

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapFragmentActivity.java
=> [android] #4398 - Default value bug fix for MapboxMapOptions

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java, platform/android/src/jni.cpp
=> Wrapping all LatLng from nativeLatLngForPixel()

CHANGELOG.md
=> Adding Node.js to primary CHANGELOG

platform/ios/scripts/document.sh
Fixes #4468.
/cc @RomainQuidet @boundsj
=> Use current Swift version with jazzy

platform/ios/CHANGELOG.md, platform/ios/scripts/document.sh, platform/ios/scripts/package.sh
Fixed a regression introduced in #4466 in which the changelog is essentially empty.
Fixes #4469.
/cc @bleege @boundsj
=> Fix changelog processing

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties, platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties
=> Releasing Android 4.0.0 RC 1

package.json, src/mbgl/renderer/painter.cpp, src/mbgl/renderer/painter.hpp, src/mbgl/renderer/painter_background.cpp, src/mbgl/renderer/painter_fill.cpp, src/mbgl/shader/pattern.vertex.glsl, src/mbgl/shader/pattern_shader.hpp
=> fix background-pattern rendering in perspective view

package.json, src/mbgl/geometry/line_buffer.cpp, src/mbgl/renderer/line_bucket.cpp, src/mbgl/renderer/line_bucket.hpp, src/mbgl/shader/line.vertex.glsl, src/mbgl/shader/line_shader.cpp, src/mbgl/shader/linepattern.vertex.glsl, src/mbgl/shader/linepattern_shader.cpp, src/mbgl/shader/linesdf.vertex.glsl, src/mbgl/shader/linesdf_shader.cpp
fix #4492
port https://github.com/mapbox/mapbox-gl-js/pull/2114
=> reset line distance when it is near max representable distance

platform/android/CONTRIBUTING_LINUX.md, platform/android/CONTRIBUTING_OSX.md, platform/android/README.md
=> [android] More strongly redirect non-contributors to the product website

package.json, src/mbgl/renderer/painter.cpp, src/mbgl/renderer/painter.hpp, src/mbgl/renderer/painter_background.cpp, src/mbgl/renderer/painter_fill.cpp, src/mbgl/shader/pattern.vertex.glsl, src/mbgl/shader/pattern_shader.hpp
Cherry-pick of #4499 to the release branch.
=> [core] fix background-pattern rendering in perspective view

package.json, src/mbgl/renderer/line_bucket.cpp, src/mbgl/renderer/symbol_bucket.cpp, src/mbgl/text/get_anchors.cpp
=> [core] fix infinite loop in mbgl::resample

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
=> [android] #4515 - correctly calculate bounds

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/PolygonActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> [android] #4530 - add polygon example to test app

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
=> [android] #4520 - don't update camera position after padding call

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/camera/CameraPositionTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
=> [android] #4565 - improved coverage of camera package

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/SnapshotActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_add_a_photo_black_24dp.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_snapshot.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/ids.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=>  [android] #3466 - snapshot

package.json, platform/default/headless_display.cpp, platform/node/bitrise.yml, platform/node/scripts/after_script.sh, platform/node/scripts/run.sh
It should be running `npm test` and `npm run test-suite` but is not.
=> Bitrise Node OS X build is not running tests

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
=> [android] #4553 - remove annotations fix

platform/android/tests/docs/UNIT_TESTS.md
=> [android] Unit tests doc update

Makefile, scripts/main.mk
=> [build] Fix/simplify ios, isim, and ibench targets

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/telemetry/HttpTransportTest.java
=> Ensuring userAgent is always ASCII formatted

src/mbgl/renderer/painter_debug.cpp
=> [core] get rid of empty buffer warning

platform/android/bitrise.yml
=> [android] #4586 - disable publish s3

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Annotation.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/AnnotationTest.java
Added some unit tests for uncovered code
=> [android] - added tests for Annotation

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/espresso/BulkMarkerActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/BulkMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> Restoring Name of BulkMarkerActivity

.jazzy.yaml
Fixes #4620.
/ref realm/jazzy#456
/cc @boundsj
=> Update jazzy config flags for jazzy 0.6.0

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java
Little operator calling optimization
@tobrun @bleege
=> [Android] MapboxEventManager: operator size optimized

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
=> [android] #3643 - improved touch target with getAnnotationsInBounds

platform/node/src/node_log.cpp, platform/node/src/node_mapbox_gl_native.cpp, platform/node/test/js/require.js
=> don't dispose parent module in NodeLog destructor

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Icon.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/utils/MockParcel.java
Some tests for missed lines in Marker
=> [android] - Marker test coverage

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
=> [android] #4635 - fix rotate disabled with location tracking

Makefile
=> [osx] Print crash diagnostics

test/util/async_task.cpp
=> [test] This "very unlikely" condition in fact happens regularly in CI

platform/default/mbgl/storage/offline_database.cpp, platform/default/sqlite3.cpp, platform/default/sqlite3.hpp
=> [core] Fix race condition that could lead to a UNIQUE constraint failure

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_refresh_24dp.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_debug_mode.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> Adding Debug Mode Example To TestApp

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolylineActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java
=> [android] #4335 - add clear method for removing annotations to MapboxMap

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/FeatureOverviewActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DoubleMapActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> [android] #4754 - double map view example

.ycm_extra_conf.py, Makefile, bin/offline.sh, platform/ios/WorkspaceSettings.xcsettings, platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/ios.xcodeproj/xcshareddata/xcschemes/CI.xcscheme, platform/ios/ios.xcworkspace/contents.xcworkspacedata, platform/ios/platform.gyp, platform/ios/scripts/package.sh, platform/ios/uitest/ios-tests.xcodeproj/project.pbxproj, platform/osx/WorkspaceSettings.xcsettings, platform/osx/osx.xcodeproj/project.pbxproj, platform/osx/osx.xcodeproj/xcshareddata/xcschemes/CI.xcscheme, platform/osx/osx.xcworkspace/contents.xcworkspacedata, platform/osx/osx.xcworkspace/xcshareddata/xcschemes/mbgl-offline.xcscheme, platform/osx/osx.xcworkspace/xcshareddata/xcschemes/mbgl-render.xcscheme, platform/osx/osx.xcworkspace/xcshareddata/xcschemes/test.xcscheme, platform/osx/platform.gyp, platform/osx/scripts/osxtest.xcscheme, scripts/main.mk
Refs #4738 
cc @1ec5 -- want to add what you mentioned in https://github.com/mapbox/mapbox-gl-native/issues/4738#issuecomment-211516320?
=> Rationalize ios and osx build output

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DoubleMapActivity.java
Refs #4260 
Add the possibility to have 2 Activities after each other both containing a mapview.
=> [android] #4260 - added example of 2 map activities

README.md
Qt now lives on the main repository.
=> [Qt] Add QMapboxGL to README.md

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java
=> [android] #2835 - limit the amount of object allocations 

src/mbgl/geometry/glyph_atlas.cpp, src/mbgl/geometry/glyph_atlas.hpp, src/mbgl/renderer/symbol_bucket.cpp, src/mbgl/text/glyph_pbf.cpp, src/mbgl/text/glyph_pbf.hpp, src/mbgl/text/glyph_set.cpp, src/mbgl/text/glyph_set.hpp, src/mbgl/text/glyph_store.cpp, src/mbgl/text/glyph_store.hpp, test/style/glyph_store.cpp
A font stack is an array of font names. This is not that.
=> [core] FontStack ⇢ GlyphSet

Makefile
=> [build] Depend on directories, so that projects are regenerated when files are added or removed

include/mbgl/storage/resource.hpp, include/mbgl/style/types.hpp, scripts/main.mk, src/mbgl/geometry/glyph_atlas.cpp, src/mbgl/geometry/glyph_atlas.hpp, src/mbgl/layer/symbol_layer.hpp, src/mbgl/storage/resource.cpp, src/mbgl/style/function.cpp, src/mbgl/style/property_parsing.cpp, src/mbgl/style/style.cpp, src/mbgl/style/style.hpp, src/mbgl/style/style_parser.cpp, src/mbgl/style/style_parser.hpp, src/mbgl/style/types.cpp, src/mbgl/text/glyph_pbf.cpp, src/mbgl/text/glyph_pbf.hpp, src/mbgl/text/glyph_store.cpp, src/mbgl/text/glyph_store.hpp, src/mbgl/util/interpolate.hpp, test/map/map.cpp, test/src/mbgl/test/stub_style_observer.hpp, test/storage/resource.cpp, test/style/glyph_store.cpp, test/style/style_parser.cpp
Font stacks are vectors of strings; type them as such.
=> [core] Use the proper type for font stacks

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/camera/CameraPositionTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngSpanTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/ProjectedMetersTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/geometry/VisibleRegionTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/utils/MockParcel.java
=> [android] #4814 - simplified mock parcel testing

platform/qt/scripts/configure.sh
Expose less symbols on the shared library.
Fixes #4809
=> [Qt] Set default visibility to hidden for Qt

platform/qt/scripts/configure.sh, platform/qt/scripts/toolchain.sh, scripts/main.mk
=> [Qt] Add toolchain support

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java
=> Use CopyOnWriteArrayList For Non Blocking Iterations

include/mbgl/style/types.hpp, src/mbgl/style/property_parsing.cpp, src/mbgl/style/style_parser.cpp
No need for these to be public.
=> [core] Move enum type classes to implementation

platform/ios/src/MGLMapView.mm
=> Hide compass from VoiceOver when pointing north

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/ViewSettings.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/UserLocationView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java, platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml, platform/android/MapboxGLAndroidSDK/src/main/res/values/styles.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_polyline.xml, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java
=> 3231 tint support

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/robotium/BaseMainActivityTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/robotium/CompassViewTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/robotium/SimpleRotateTest.java, platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/robotium/SimpleZoomTest.java
=> [android] #4845 - disable robotium

platform/ios/ios.xcodeproj/project.pbxproj, platform/ios/resources/Base.lproj/Localizable.strings, platform/ios/resources/Base.lproj/Localizable.stringsdict, platform/ios/src/MGLMapView.mm
Announce the zoom level and number of visible annotations after zooming using VoiceOver’s swipe up or swipe down gesture.
/ref #4821
=> Announce zoom level and visible annotations after zooming via VoiceOver

platform/qt/platform.gyp, platform/qt/scripts/configure.sh, scripts/main.mk
=> [build][Qt] Move Qt version define to configure.sh.

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
=> [android] #4850 - user location view is show instantly when toggled on

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/imagegenerator/SnapshotActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_snapshot.xml
=> [android] #4633 - add non-gl content to snapshot bitmap

include/mbgl/storage/offline.hpp, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionStatus.java, platform/android/src/jni.cpp, platform/darwin/src/MGLOfflinePack.h, platform/darwin/src/MGLOfflinePack.mm, platform/darwin/test/MGLOfflinePackTests.m, platform/default/mbgl/storage/offline_database.cpp, platform/default/mbgl/storage/offline_database.hpp, platform/default/mbgl/storage/offline_download.cpp, platform/ios/CHANGELOG.md, test/storage/offline_database.cpp
=> Add tile-only count and size properties to offline status

platform/qt/include/qmapbox.hpp, platform/qt/src/qmapbox.cpp, platform/qt/src/qquickmapboxglrenderer.cpp
It will also enable Vertex Array Objects.
=> [Qt] Initialize GL extensions

include/mbgl/map/view.hpp, include/mbgl/platform/default/glfw_view.hpp, platform/default/glfw_view.cpp
Has mentions about calls coming from a different thread that are no longer valid.
=> [core] Fix View class documentation

platform/qt/src/qmapboxgl.cpp, platform/qt/src/qmapboxgl_p.hpp
Fixes label animation not completing.
=> [Qt] Make needsRendering signal asynchronous

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/Style.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/res/values/integers.xml, platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/LatLngBoundsActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/ManualZoomActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/MapFragmentActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/SupportMapFragmentActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/geocoding/GeocoderActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DoubleMapActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/constants/AppConstant.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/constants/StyleVersionTest.java
Android equivalent of https://github.com/mapbox/mapbox-gl-native/pull/4759 needed for https://github.com/mapbox/mapbox-gl-native/issues/4577 and https://github.com/mapbox/mapbox-gl-native/issues/4702.
Targets the #4759  PR so we can merge all platforms at once.
@danswick @cammace : 
when #4759 and this PR lands we will need to update the examples and docs.
👀  @jfirebaugh @1ec5 
cc @bleege @zugaldia
=> [android] #4702 - upgrade default styles for Android

platform/qt/include/qmapbox.hpp
=> [Qt] C++98 compatibility

.travis.yml, INSTALL.md, mbgl.gypi, platform/default/image.cpp, platform/default/sqlite3.cpp, platform/linux/README.md, platform/linux/scripts/coveralls.sh, platform/qt/platform.gyp, src/mbgl/util/compression.cpp
=> [linux] Build with GCC 5

platform/qt/app/mapwindow.cpp, platform/qt/qmapbox.qrc, platform/qt/qmlapp/main.cpp
=> [Qt] Set the test application icon

platform/qt/include/qquickmapboxgl.hpp, platform/qt/qmlapp/main.qml, platform/qt/src/qquickmapboxgl.cpp, platform/qt/src/qquickmapboxglrenderer.cpp, platform/qt/src/qquickmapboxglrenderer.hpp
- Add slider for controlling pitch.
- Rounded corners on the map.
- Add slider to flip the map to a satellite (in fact we have two maps in sync).
=> [Qt] Improve Qt QML app example

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationDotColor.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_my_location_dot_color.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/colors.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/styles.xml
Fixes #4896 example for the user dot. It changes the color depending on which button you push at the bottom. 
cc: @zugaldia @tobrun @bleege
=> [android] added user dot customization example

platform/qt/include/qquickmapboxgl.hpp, platform/qt/src/qquickmapboxgl.cpp
Build fix for some Qt versions.
=> [Qt] Include what you use

platform/qt/platform.gyp, platform/qt/scripts/configure.sh, platform/qt/src/image.cpp, src/mbgl/util/mapbox.cpp, test/util/image.cpp
Pull less dependencies. Useful when building for Yocto.
=> [Qt] Make it possible to disable libwebp and libjpeg-turbo at build time

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java
=> [android] #4894 - correctly calculate LatLngBounds

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
=> [android] #4763 - introduce StyleInitializer class

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java
=> [android] #4748 - add javadoc for unregistering location listeners

platform/ios/src/MGLMapView.mm, platform/osx/src/MGLMapView.mm
The tile cache size is only recomputed when an input changes.
This code was originally introduced in #1281 (actually 52d00686d4c160e2890a7dd9cdcaa4a1fa14d5bd for #1255). `Map::setSourceTileCacheSize()` bails if the new size is no different than the current one, but by then we’ve already gotten the zoom limits and process info. By contrast, the Android SDK sets the tile cache size just once, in the `NativeMapView` constructor. This is part of a push to minimize the work we’re doing at the SDK level in the drawing routines, currently the hottest-running SDK code on iOS and OS X.
Fixes #4026.
=> Avoid recomputing tile cache size on every redraw

platform/osx/app/MapDocument.m, platform/osx/src/MGLMapView.mm
=> Exclude subviews from click gestures

platform/android/src/native_map_view.cpp
This fixes the black screen issue we have seen on multiple devices. It reimplements a fix we used to have for these devices but was removed during the lift for rendering on main thread. 
👀  @tmpsantos 
cc @bleege @zugaldia @cammace @danswick
=> [android] - fix black screen

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationDrawableActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTintActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_my_location_dot_color.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> 4930 userlocation not changing colors immediately

platform/default/default_file_source.cpp
In `DefaultFileSource`, we're constructing a new object called `Task`, which just holds another `unique_ptr`. We can just do everything inline.
=> Remove indirection in DefaultFileSource

platform/android/CHANGELOG.md, platform/android/MapboxGLAndroidSDK/gradle.properties, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/TelemetryLocationReceiver.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/TelemetryService.java, platform/android/MapboxGLAndroidSDK/src/main/java/overview.html, platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/TimingLogger.java
=> Merge Android 4.0.1 Release Branch Into Master

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Targets master to merge the code from https://github.com/mapbox/mapbox-gl-native/pull/4988
=> [android] - move OnMapReady callback for offline bug

platform/android/MapboxGLAndroidSDK/build.gradle
=> Updating LOST To Version 1.1.0

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PressForMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_press_for_marker.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_press_for_marker.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> Restore PressForMarker TestApp Activity

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
Fixes #4942 added ObjectAnimator to the MyLocationView direction. Worked on my phone but occasionally jumps around still. 
@tobrun @zugaldia @bleege
=> [android] Animate MylocationView direction

platform/ios/CHANGELOG.md, platform/ios/Mapbox.playground/Contents.swift, platform/ios/src/MGLAnnotationView.h, platform/ios/src/MGLAnnotationView.m
=> [ios] Added centerOffset to MGLAnnotationView

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/ViewMarkerAdapterActivity.java
=> [android] #5081 - added rotation to View Marker

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/Style.java
=> Fixing Satellite Streets URL for V9

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/BulkMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/ViewMarkerAdapterActivity.java
=> [android] #5084 - remove addMarkerViews, renamed addMarkerView 

platform/ios/app/MBXViewController.m
- Remove unsupported custom style layer example.
- Only show debug log print/delete options if debug logging is enabled.
/cc @1ec5 @jfirebaugh
=> Cleanup iOS demo app

Makefile, platform/android/platform.gyp, platform/linux/platform.gyp, platform/qt/platform.gyp
=> More Makefile cleanup

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java
=> MapboxAccountManager And Offline Support

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerTest.java
=> [android] #5102 - update marker view position correctly 

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewOptions.java
=> [android] #5115 - add visible integration to MarkerView

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewOptions.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/CountryMarkerViewOptions.java
=> [android] #5079 - add anchor and InfoWindowAnchor to MarkerView

platform/android/MapboxGLAndroidSDK/build.gradle
=> [android] #5131 - update okhttp dependency

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerViewTest.java
adds unit tests for the MarkerView/MarkerViewOptions model objects
=> [android] - add unit test for MarkerView

platform/android/bitrise.yml
=> Setting Bitrise Workflows BUILDTYPE=Release

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdateFactory.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/LatLngBoundsActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_map_padding.xml
=> 5034 camera animations not respecting padding

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java, platform/android/src/jni.cpp
=> [android] #3629 - smooth MyLocationView animation while tracking enabled

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
=> [android] #3629 - smooth animation for non location tracking

platform/ios/src/MGLMapView.mm
I want to use a UIMenuController on a MGLMapView in my app. For that to work, MGLMapView#canBecomeFirstResponder need to return YES.
=> [ios] canBecomeFirstResponder

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
=> 5113 javadoc view annotations

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEvent.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java
=> Changing Telemetry Endpoint to events.mapbox.com

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.java
=> [android] #5113 - added javadoc for MyLocationViewSettings

platform/ios/jazzy.yml
Added MGLAnnotationView to jazzy’s table of contents.
/ref #4801
/cc @boundsj
=> Add MGLAnnotationView to jazzy TOC

platform/ios/src/MGLMapboxEvents.m
Previously, the SDK sent the turnstile every time the map loaded but not more than once every 24 hours. This change updates the logic so that the guard is based on the the calendar day and not a 24 hour interval. This addresses the issue where a turnstile event might be sent at 11pm on day 1, not at all on day 2 (if the event could have only been sent before 11pm on day 2), and then again on day 3. Basing off of the calendar day, the event can be sent at least once per day.
cc @mick @friedbunny @1ec5
=> [ios] Base turnstile send time guard on calendar day

.travis.yml
=> [build] Upload node test results

platform/android/MapboxGLAndroidSDKTestApp/proguard-rules.pro
=> [android] #4727 - fix proguard test app

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/res/layout/view_image_marker.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/view_custom_marker.xml
=> 5214 remove requirement adapter marker view

src/mbgl/gl/object_store.hpp, src/mbgl/gl/texture_pool.cpp, src/mbgl/gl/texture_pool.hpp, src/mbgl/map/map.cpp, src/mbgl/util/raster.cpp, test/gl/object.cpp
First steps towards making sure we are not leaking any abandoned/unused GL textures.
:eyes: @kkaefer @jfirebaugh @tmpsantos @mikemorris
=> [core] Added Texture Pool tests

platform/qt/bitrise-qt4.yml, platform/qt/bitrise-qt5.yml
=> [build] Added Bitrise Qt5 OS X

Makefile, platform/android/CONTRIBUTING_LINUX.md, platform/ios/DEVELOPING.md, platform/node/README.md
* Correctly initialize 'em
* Don't need to manually initialize 'em
cc @friedbunny
=> Submodules

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/BulkMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/TextMarkerView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/TextMarkerViewOptions.java, platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/annotations/MarkerViewTest.java
=> [android] #5171 - introduce new select/deselect animation View Markers

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/CountryMarkerViewOptions.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/TextMarkerViewOptions.java, platform/android/src/jni.cpp
=> 5076 optimise view reuse cache

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewOptions.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/CountryMarkerViewOptions.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/TextMarkerViewOptions.java
=> [android] #5241 -float rotation on markerview

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java
=> [android] #5167 - add support annotations to MarkerView

scripts/generate-style-code.js, src/mbgl/style/layers/line_layer_properties.hpp
=> [core] Revert line-round-limit default to 1

package.json
=> New hash for gl-shaders

platform/ios/src/MGLMapView.mm
Fixes #991. Split out from #5245.
/cc @boundsj
=> Bring annotation view to front when selected

package.json, scripts/build-shaders.py, src/mbgl/renderer/painter_fill.cpp, src/mbgl/shader/outline_shader.hpp
Improves #pragma usage in shader code by specifying the variable type.
Part of https://github.com/mapbox/mapbox-gl-shaders/issues/8
Requires https://github.com/mapbox/mapbox-gl-shaders/pull/13.
👀 @kkaefer @jfirebaugh @lucaswoj
=> [core] Shader pragma types

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Annotation.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/DynamicMarkerChangeActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
=> Enable Update Of InfoWindow Title And Snippet

src/mbgl/gl/texture_pool.cpp, src/mbgl/gl/texture_pool.hpp, src/mbgl/util/raster.hpp, test/gl/object.cpp
Follow-up for https://github.com/mapbox/mapbox-gl-native/pull/2336#issuecomment-224353056.
=> [core] s/SharedTexture/PooledTexture/

scripts/travis_setup.sh
Just keeping up with dependencies. I hoped that this might resolve some of the test-suite rendering differences, but it does not.
cc @mikemorris
=> [linux] Mesa 11.2.2

package.json
https://github.com/mapbox/mapbox-gl-shaders/pull/16
=> Fix for opacity/blur type in circle shaders

include/mbgl/util/geo.hpp, include/mbgl/util/projection.hpp, test/test.gypi, test/util/projection.cpp
=> [test] Added Projection tests

package.json, src/mbgl/renderer/painter_line.cpp
Refs:
- mapbox-gl-test-suite: https://github.com/mapbox/mapbox-gl-test-suite/pull/107
- mapbox-gl-shaders: https://github.com/mapbox/mapbox-gl-shaders/pull/17
- mapbox-gl-js: https://github.com/mapbox/mapbox-gl-js/pull/2724
Part of https://github.com/mapbox/mapbox-gl-shaders/issues/1.
=> [core] Update line-pattern shader code/tests

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapview_internal.xml
=> [android] #5296 - Add a container ViewGroup for MarkerViews

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/InfoWindowActivity.java
=> InfoWindow Variable Content Layout

src/mbgl/tile/geometry_tile.cpp, src/mbgl/tile/raster_tile.cpp, src/mbgl/tile/raster_tile.hpp, src/mbgl/tile/tile.hpp, src/mbgl/tile/tile_loader.hpp, src/mbgl/tile/tile_loader_impl.hpp, src/mbgl/tile/vector_tile.cpp, src/mbgl/tile/vector_tile.hpp
I'm going to use the name `TileSource` for a base class of `VectorSource` and `RasterSource`.
=> [core] TileSource ⇢ TileLoader

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerViewOptions.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewOptions.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/CountryMarkerViewOptions.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/TextMarkerViewOptions.java
closes #5279 
cc @bleege @cammace @ivovandongen @zugaldia
=> [android] #5279 - expose MarkerView alpha

include/mbgl/util/convert.hpp, package.json, platform/node/src/node_style.hpp, src/mbgl/map/transform_state.hpp, src/mbgl/renderer/painter_background.cpp, src/mbgl/renderer/painter_circle.cpp, src/mbgl/renderer/painter_fill.cpp, src/mbgl/shader/outlinepattern_shader.hpp, src/mbgl/shader/pattern_shader.hpp, src/mbgl/sprite/sprite_atlas.hpp, src/mbgl/util/convert.cpp
This is a step towards implementing data driven fill styles.
Part of https://github.com/mapbox/mapbox-gl-shaders/issues/1.
:eyes: @jfirebaugh @kkaefer
=> [core] Separate pattern size from draw-time variables

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_animated_marker.xml
=> 5242 animate marker view

Makefile, configure, platform/qt/scripts/configure.sh, platform/qt/src/qmapboxgl.cpp
=> [Qt] Minor cleanups

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerOptions.java
=> [android]  #4761 - Create Wrappers for Cordova

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/InfoWindow.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/DynamicInfoWindowAdapterActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_infowindow_adapter_dynamic.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
Fixes #5353
@zugaldia Correct PR (hopefully), previous was based on master
=> [android] Dynamic update of InfowWindow with InfoWindowAdapter example

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
=> [android] Fix crash when MyBearingTracking mode is not NONE.

include/mbgl/map/update.hpp, src/mbgl/annotation/annotation_manager.cpp, src/mbgl/annotation/annotation_manager.hpp, src/mbgl/map/map.cpp, src/mbgl/style/style.cpp, src/mbgl/style/style.hpp, src/mbgl/tile/tile_worker.cpp, src/mbgl/tile/tile_worker.hpp, src/mbgl/tile/vector_tile_data.cpp, src/mbgl/tile/vector_tile_data.hpp, test/api/annotations.cpp
Part of #5385.
/cc: @jfirebaugh @tobrun
=> Bring optimized animated annotations to Android release branch

platform/linux/scripts/configure.sh, platform/qt/platform.gyp, platform/qt/scripts/configure.sh
=> [Qt] More cleanups

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java
=> [android] Remove unnecessary menu from Animated Marker activity

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewScaleActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_marker_view_scale.xml, platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
`MarkerViewScaleActivity` added.
Fixes #5409.
/cc: @tobrun @cammace
=> Add scaling marker activity to TestApp using the View Marker API

platform/ios/src/MGLMapboxEvents.m
Disable (the already extremely power-efficient) telemetry while the user has [Low Power Mode](https://developer.apple.com/library/ios/documentation/Performance/Conceptual/EnergyGuide-iOS/LowPowerMode.html) enabled. This feature is iOS 9+, so some availability checks must be made.
/cc @boundsj @1ec5 @frederoni
=> [ios] Disable telemetry while Low Power Mode is enabled

package.json
Ignore 'debug/overdraw' until #5435 is fixed.
:eyes: @jfirebaugh @mikemorris
=> [build] Bump mapbox-gl-test-suite@9a7de

src/mbgl/map/map.cpp, src/mbgl/style/update_parameters.hpp, src/mbgl/tile/raster_tile.hpp, test/style/source.cpp
=> [core] Remove TexturePool from style::UpdateParameters

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
=> [android] #5421 - recalculate offset with new anchor

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java
=> 5439 markers top left corner

platform/ios/src/MGLMapView.mm
Fixes #5166 
This changes the way the the calculation for the largest visual annotation representation (stored in
_unionedAnnotationRepresentationSize) is done so that it includes both images and views. The `annotationTagAtPoint` method is then able to find annotation objects that are in a query rect formed from the sizes of all manner of point annotation visual representations.
The `annotationTagAtPoint` method also gains new logic in a conditional to handle annotations backed by MGLAnnotationViews. Similarly to the image case, it filters out disabled annotations and calculates
a centered rect for the view. The hit test logic remains the same but now works correctly for the centered rects of both images and views.
This also fixes a bug where the `largestAnnotationViewSize` was always …
=> [ios] Cycle through both UIView and UIImage backed annotations

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/FeatureOverviewActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationDrawableActivity.java, platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java
=> 5450 fix locational runtime permissions

platform/android/src/jni.cpp, src/mbgl/annotation/shape_annotation_impl.cpp
Fixes #5259
Note: this is not an issue on the release branch. It doesn't need to be cherry picked.
=> [android] Fix crash adding line or polygon annotation

platform/default/mbgl/storage/offline_download.cpp, test/storage/offline_download.cpp
=> [core] Increment completedTileCount when appropriate

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java, platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
=> 5479 my location view fixes

platform/ios/src/MGLMapView.mm, platform/ios/src/MGLMapViewDelegate.h
=> [ios] fixes #5465 map view now informs about added annotation views

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java
=> Adding NaN and Infinite Location Data Checks

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
=> Removing Deprecated annotation on MapboxMap.OnMyLocationChangeListener

src/mbgl/renderer/bucket.hpp
=> Removing Extraneous Equals Sign

platform/ios/src/MGLAnnotationView.mm
Fixes #5547, introduced by a typo in #5546.
=> Fix auto-shrinking annotation views

README.md, platform/ios/docs/doc-README.md, platform/ios/docs/pod-README.md, platform/ios/src/MGLMapView.h, platform/macos/app/MapDocument.m, platform/macos/docs/doc-README.md, platform/macos/docs/pod-README.md, platform/macos/src/MGLMapView.h, platform/node/src/node_map.cpp
Depends on mapbox/mapbox-gl-style-spec#466.
=> “Mapbox GL Style Specification” → “Mapbox Style Specification”

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
Refs https://github.com/mapbox/mapbox-gl-native/issues/5075#issuecomment-221568102
=> [android] - fixes deprecation javadoc of accessToken

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
add missing javadoc to `MapboxMapOptions` related to MyLocationView customisation.
=> [android] - add javadoc to mapboxmapoptions

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java
=> [android] #5564 - fixes latitude lint range setup 

platform/android/src/run_loop.cpp, platform/android/src/run_loop_impl.hpp, platform/android/src/timer.cpp, test/util/timer.cpp
With #5456 started, we could run the basic unit tests on Android and already found some bugs fixed by this PR.
/cc @ivovandongen
=> [android] Fix bugs on low level platform abstractions

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java, platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapview_internal.xml
=> [android] #5000 - initial surface view implementation.

package.json, src/mbgl/tile/geometry_tile_data.cpp
=> [core] Re-close polygons after clipping with clipper
