mapbox/mapbox-gl-native

platform/ios/CHANGELOG.md
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLAnnotationView.mm

https://github.com/mapbox/mapbox-gl-native/pull/8308 appears to be permanently stuck as if the contributor's fork is deleted. I'm closing #8308 and re-opening it here.

Make annotation view rotation alignment configurable

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

Validate if gestures should execute

---

src/mbgl/tile/vector_tile.cpp

[`vector-tile-js`](https://github.com/mapbox/vector-tile-js/blob/7fa4d808acfb7228e29d9d931d52dbf99768f65a/lib/vectortilelayer.js#L35-L50) returns `null` instead of false, we should do the same.

Interpret missing field in vector tile values as null instead of false

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

[android] - remove upgrade runtime exceptions

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

Invoke callback if fling is valid

---

package.json
platform/node/CHANGELOG.md

Main bug fix in this release is https://github.com/mapbox/mapbox-gl-native/pull/9119.

[node] bump version

---

src/mbgl/map/transform.cpp

The isClose threshold is switched from 0.000001 pixels to 1 pixel. As a backup, it checks whether r0 and r1 are finite. It might be possible to have just the threshold check or just the finiteness check, but I don't see the harm in having both.
The `std::abs(w0 - w1) < 0.000001` special case is removed because it doesn't look like it's needed. All calculations should run fine even if `w0 == w1`. I'm fairly confident in this, but if we want to be on the safe side I can add it back in.
Finally, the point interpolation is tweaked so that at the end of the flying (when k === 1) it ends up at the exact end point. I didn't see any bugs related to this, but it seems like a good thing to have explicitly.
@jfirebaugh

fix #8300 flyTo for close points

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java

Did some test with the iOS binding to validate change from #9048. 
The requested change in https://github.com/mapbox/mapbox-gl-native/issues/8990 wasn't valid. 
Reverts #9048 and closes #8990.

[android] - remove conversion from pixels to dp

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Let me try #9098 again. I think this one is better.

[android] feature - option to disable location change animation

---

platform/glfw/glfw_view.cpp

Resizing the window, or moving it to a different screen fails after https://github.com/mapbox/mapbox-gl-native/pull/8216

GLFW window resizing fails

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/widgets/MyLocationViewTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/FeatureOverviewActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/BaseLocationActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/CustomLocationEngineActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MockLocationEngine.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationDrawableActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTintActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationToggleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_my_location_tracking.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_location_engine.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml
platform/android/MapboxGLAndroidSDKTestApp/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java
platform/android/dependencies.gradle

Follow-up https://github.com/mapbox/mapbox-gl-native/pull/9141. The CI bots didn't want to start for that external PR. 
Closes https://github.com/mapbox/mapbox-gl-native/issues/9139 and potentially https://github.com/mapbox/mapbox-gl-native/issues/8999
cc @LukasPaczos

Custom location source fix

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

update components with camera values when animating

---

include/mbgl/style/layer.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RuntimeStyleTests.java
platform/darwin/test/MGLStyleTests.mm
src/mbgl/style/style.cpp
test/style/style.test.cpp

This PR cherry picks the remaining items from the [release project](https://github.com/mapbox/mapbox-gl-native/projects/18):
- https://github.com/mapbox/mapbox-gl-native/pull/9129
- https://github.com/mapbox/mapbox-gl-native/pull/9191

Cherry picks to release branch

---

platform/android/CHANGELOG.md

Release Android v5.1.0-beta.4

---

src/mbgl/annotation/annotation_manager.cpp
src/mbgl/annotation/annotation_manager.hpp

Alternative for #9208 to make annotations thread safe for asynchronous rendering (#8820)

Mutex guard annotation manager for cross thread usage

---

include/mbgl/map/backend.hpp
platform/android/src/native_map_view.cpp
platform/default/mbgl/gl/offscreen_view.cpp
platform/glfw/glfw_view.cpp
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm
platform/qt/src/qmapboxgl.cpp
src/mbgl/gl/context.cpp
src/mbgl/gl/context.hpp
src/mbgl/gl/value.cpp
src/mbgl/gl/value.hpp
src/mbgl/map/backend.cpp
src/mbgl/util/offscreen_texture.cpp
test/util/offscreen_texture.test.cpp

When scissor test is enabled e.g. when embedding our engine on third-party platforms, the scissor test ends up polluting the rendering of offscreen textures e.g. used when rendering fill extrusion layers. This PR:
- Adds convenience methods for assuming/setting viewport values with non-zero `x` and `y` values
- Adds convenience methods for assuming/setting scissor test values
- Makes sure scissor test is disabled when using offscreen textures for fill extrusion layer

[core] Disable scissor test when using offscreen texture

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Capturing from @ivovandongen that source changes can also be triggered by data changes (eg. image source) (thus not only source attribution changes). This means that the javadoc is incorrect and needs to be altered.

[android] - correct source changed map event javadoc

---

scripts/generate-shaders.js
src/mbgl/shaders/circle.cpp
src/mbgl/shaders/line.cpp
src/mbgl/shaders/line_pattern.cpp
src/mbgl/shaders/line_sdf.cpp
src/mbgl/shaders/symbol_sdf.cpp

For `#pragma`s, don't generate varyings for attributes that aren't used by the fragment shader. Pack other varyings more tightly.
I did some hand-editing of generated shader code because gl-native is out of sync with gl-js shaders.
Fixes #9209.

[core] Reduce number of varyings to 8 or less

---

src/mbgl/gl/attribute.cpp

We have an `oldBinding` value that we use for checking whether the vertex attribute was already
bound to the current VAO, but we never set the state. Additionally, we're also checking whether
the previous state was already any binding (`optional` is set), and don't re-enable the vertex
attribute array. Additionally, we now only disable the vertex attribute array when the previous
state was in fact an array attribute. We still don't deduplicate constant `glVertexAttrib*` calls,
but that's a little trickier.

Store vertex attribute binding to prevent duplicate binds

---

src/mbgl/gl/types.hpp
src/mbgl/gl/uniform.cpp
src/mbgl/gl/uniform.hpp

Add debug-only code that verifies that the uniform types in the shader match the types that we are assuming when declaring our programs. Since there is no way to bail out of this, I added `assert`s and made it debug-only.

Verify that the active uniform types match our assumed types

---

src/mbgl/renderer/frame_history.cpp

When combined with #9185, brings FPS on the bench app to 60 on my iPhone 6 across all locations.

[core] Don't upload the FrameHistory texture in frames where it's not changing

---

platform/ios/docs/guides/Adding Points to a Map.md

The total size of the sprite sheet is no longer limited to the extent that it was before, now that #9213 has landed, fixing #3185. This change updates the guide that helps developers choose between the different annotation mechanisms, removing the sprite atlas limitation from the list of cons for MGLPointAnnotation. (In fact, this was also a limitation of the runtime styling approach, but we neglected to mention that.)
/cc @ericrwolfe @jfirebaugh

Remove mention of sprite atlas limitation from iOS points guide

---

platform/darwin/src/MGLForegroundStyleLayer.h
platform/darwin/src/MGLMultiPoint.h
platform/darwin/src/MGLShape.h
platform/darwin/src/MGLSource.h
platform/darwin/src/MGLStyleLayer.h
platform/darwin/src/MGLStyleValue.h
platform/darwin/src/MGLTileSource.h
platform/darwin/src/MGLVectorStyleLayer.h
platform/ios/src/MGLUserLocation.h

Addresses https://github.com/mapbox/mapbox-gl-native/issues/8635
cc @boundsj

[ios, macos] Revised descriptions for abstract classes

---

include/mbgl/util/constants.hpp
platform/node/test/suite_implementation.js
src/mbgl/map/map.cpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/render_style.cpp
src/mbgl/style/parser.cpp
src/mbgl/style/parser.hpp
src/mbgl/style/style.cpp
test/api/api_misuse.test.cpp

Implements automatic "smart setStyle" behavior for existing style-setting APIs: `Map::setStyleURL` and `Map::setStyleJSON`. Both of these APIs will now smoothly transition between the prior and new style (providing equivalent layers/sources/etc. use the same IDs).
Besides the obvious behavioral change, several changes are worth calling out for consideration of their downstream impact:
* Paint property mutations now transition by default over a 300ms duration. This can be overridden via `Map::setTransitionOptions` (already existed), or within the style via the [`"transition"` property](https://www.mapbox.com/mapbox-gl-js/style-spec/#root-transition) (support added in this PR). A 300ms transition was always the intended default behavior according to the style specification, and is what's …

[core] Implement "smart setStyle"

---

platform/ios/ios.xcodeproj/project.pbxproj

It's not needed for linking, but Xcode will only enable the debugger/profiler when the framework is added to the app.

iOS: add OpenGL.framework to enable the OpenGL ES debugger by default

---

include/mbgl/style/position.hpp
platform/darwin/scripts/generate-style-code.js
platform/darwin/scripts/style-spec-overrides-v8.json
platform/darwin/src/MGLLight.h
platform/darwin/src/MGLLight.h.ejs
platform/darwin/src/MGLLight.mm
platform/darwin/src/MGLLight.mm.ejs
platform/darwin/test/MGLLightTest.mm
platform/darwin/test/MGLLightTest.mm.ejs

Fixes https://github.com/mapbox/mapbox-gl-native/issues/9086

MGLLight autogenerate scripts

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Belatedly updated the iOS and macOS changelogs for iOS SDK v3.6.0-beta.3 to mention the relevant parts of #9230 and #9255.

Updated changelogs post iOS SDK v3.6.0-beta.3

---

include/mbgl/style/function/composite_function.hpp
src/mbgl/renderer/paint_property_binder.hpp
test/style/function/composite_function.test.cpp

Fixes #8460 by effectively evaluating the composite function for a given feature at both z and z + 1.
The [added integration tests](https://github.com/mapbox/mapbox-gl-js/pull/4845) are the relevant ones. I added some C++ unit tests for completeness, but they use a form of evaluation that gave the expected results even before this change.

[core] Fix composite function approximation for non-integer stops

---

src/mbgl/annotation/symbol_annotation_impl.hpp
src/mbgl/text/collision_tile.hpp

Disable misleading indentation warnings where boost is included.

---

scripts/generate-style-code.js
src/mbgl/style/layers/background_layer_properties.hpp
src/mbgl/style/layers/layer_properties.hpp.ejs
src/mbgl/style/layers/raster_layer_properties.hpp

https://github.com/mapbox/mapbox-gl-native/commit/2c6fcd9f44ff93593a3f21c9f993a1eb4b299bb4 did not add uniform generation to `generate-style-code.js`, causing `make style-code` to generate incorrect properties files.

[core] generate uniforms for DataDrivenPaintProperty

---

src/mbgl/style/sources/geojson_source.cpp
src/mbgl/style/style.cpp

Cherry-picks a33cad98557f2d15bfb578e4795b130d25a2def2 to the release branch. Fixes #9229.
I wrote (and on the master branch, will merge) an integration test for this, but it already passes because `Update::Repaint` is triggered for other reasons. @boundsj, can you please manually confirm the fix on iOS?

[core] Trigger repaint on source changes

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/FillExtrusionActivity.java
platform/android/scripts/generate-test-code.js

This PR fixes up test activity generation (see `platform/android/scripts/generate-test-code.js`).
- exclude non testable classes
- make FillExtrusionActivity conform to test activity setup

Update Activity test generation 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraUpdate.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

When running integration tests, noticed a crash on the returned camera position. 
This PR adds validation to ignore invalid camera position updates.

Validate camera position before transforming

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java

Fixes #6805 and #8798
- Adds a marker view pre draw observer (`ViewTreeObserver.OnPreDrawListener`) which invalidates marker views to ensure `convertView` width and height values are properly measured and up to date when `updateMarkerViewsPosition`.
cc/ @tobrun

[android] Fix custom marker views anchor issue

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapKeyListener.java

- Fixes trackball long press timeout calling the main thread method on a background thread.
👀 @zugaldia @tobrun

[android] Fix trackball long press timeout call issue

---

platform/android/dependencies.gradle

Fixes https://github.com/mapbox/mapbox-gl-native/issues/8939 per https://github.com/mapzen/lost/issues/213#issuecomment-309542033.
cc: @tobrun @Guardiola31337

[android] Update to LOST 3.0.1

---

platform/android/dependencies.gradle

Today we released MAS v2.1.2 https://github.com/mapbox/mapbox-java/issues/487, this fixes https://github.com/mapbox/mapbox-gl-native/issues/9288.

Update MAS version to 2.1.2

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java

Per https://github.com/mapbox/mapbox-gl-native/issues/7660#issuecomment-295353101
- Annotates Mapbox class with @UiThread to make clear that it's required to be started from the main thread as it loads the native library for connectivity change events
cc/ @tobrun

[android] Annotate Mapbox class with @UiThread

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/geometry/LatLngBoundsTest.java
platform/android/src/geometry/lat_lng_bounds.cpp

Closes #9322, PR fixes LatLngBounds conversion from java to c++.
This went unnoticed as the crash only shows at runtime due to reflection. 
To future prove this conversion, I added a regression test.

Restore LatLngBounds conversion, add regression test

---

.travis.yml

Travis rolled out [new Ubuntu Trusty 14.04 images](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch). They broke our Qt4 build with errors like:
```
CMake Error at cmake/core.cmake:1 (add_library):
Target "mbgl-core" links to target "Qt4::QtOpenGL" but the target was not
found.  Perhaps a find_package() call is missing for an IMPORTED target, or
an ALIAS target is missing?
```
This reverts to the working images until we can figure out a better solution.

[build] Unbreak Travis

---

platform/darwin/src/MGLSource.h
platform/darwin/src/MGLStyle.h
platform/darwin/src/MGLVectorStyleLayer.h

While we were making some revisions to the [product landing page](https://www.mapbox.com/ios-sdk/) a couple weeks back, it became apparent that the MGLStyle class documentation had largely remained unchanged since the days when it was primarily a way to get style URLs. The documentation comment now provides a high-level overview of the runtime styling API and its components, as well as the main workflow for using a style.
/cc @captainbarbosa @jmkiley

Rewrite MGLStyle class documentation

---

platform/darwin/src/MGLGeometry.h
platform/darwin/src/MGLLight.h
platform/darwin/src/MGLOfflinePack.h
platform/darwin/src/MGLTypes.h
platform/darwin/test/MGLLightTest.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Adds Objective-C literals for structs boxing.

Boxing ObjC structs

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

MGLMapView consults MGLMapViewDelegate about whether to zoom the map in response to a pinch gesture, but it should also account for the delegate’s response when panning the map due to the pinch’s center point wandering.
Fixes #9168.
/cc @fabian-guerra @jmkiley

Allow delegate to keep wandering pinch from panning map

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Added a blurb for #9289. Reworded a blurb. Corrected the macOS version number, which got munged in a bad merge.

Update changelogs for iOS SDK v3.6.0-rc.1

---

circle.yml

`make apackage` makes building .so files separately in previous steps obsolete.

[android] - build release package once during ci build

---

platform/ios/src/MGLScaleBar.mm

At zoom levels where the minimum 1 meter or 4 feet would be wider than the scale bar’s maximum width, the local variable holding the preferred row was left undefined. A loop that later iterated based on this row would effectively iterate infinitely until memory pressure forces the system to quit the application. This change ensures that the preferred row is always set to a real value, avoiding the infinite loop.
As you can see from this screenshot of z25.5 in Svalbard, we could probably hide the scale bar at such ridiculously high zoom levels:
Here’s the [Versailles Orangerie](https://en.wikipedia.org/wiki/Versailles_Orangerie), one of the most intricately mapped places in OpenStreetMap, as seen in Mapbox Streets:
Fixes #9359.
/cc @frederoni

Fix infinite loop zooming in past z23

---

src/mbgl/renderer/layers/render_background_layer.cpp
src/mbgl/renderer/layers/render_circle_layer.cpp
src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
src/mbgl/renderer/layers/render_fill_layer.cpp
src/mbgl/renderer/layers/render_line_layer.cpp
src/mbgl/renderer/layers/render_raster_layer.cpp
src/mbgl/renderer/layers/render_symbol_layer.cpp
src/mbgl/renderer/render_light.cpp
src/mbgl/style/properties.hpp

Fixes #9301. I opted not to implement transitioning opacity because:
* gl-js doesn't do that
* the new layers have to go through layout, so they wouldn't start rendering at the beginning of the transition anyway
* if we did that, we should also transition layers _out_, which is more difficult

[core] Don't transition new layers on a setStyle operation

---

platform/darwin/src/nsthread.mm

Gives core threads on the darwin platforms fully qualified names by adding the `com.mapbox.mbgl` prefix. This helps distinguish our threads during debugging and in crash reports. It also aligns us with platform naming conventions.
I’ve made this specific to darwin for now because I’m not certain it's a useful change for all platforms. If we wanted to add a thread name prefix on all platforms, I’m guessing we’d do it [here](https://github.com/mapbox/mapbox-gl-native/blob/c437079486b5401665df5e90929953cfbd341191/src/mbgl/util/thread.hpp#L47) — happy to make that change, if people want it.
/cc @tmpsantos @kkaefer @jfirebaugh @tobrun

[darwin] Assign threads more specific names

---

src/mbgl/map/transform.cpp
src/mbgl/map/transform_state.cpp
test/map/transform.test.cpp

Whilst `Transform::easeTo` interpolates the zoom from initial to end values (thus never breaching the end value threshold), `Transform::flyTo` has a "bounce" effect on zoom in some circumstances, by applying a formula on each frame rendering that calculates a new zoom value.
In a particular case e.g. executing `flyTo` with camera options' zoom level set to the maximum value, the zoom value sometimes goes above the maximum zoom threshold, causing the transform state to become invalid, thus causing this crash in `tileCover`:
> mbgl-glfw: ../../../src/mbgl/util/tile_cover.cpp:159: std::vector<mbgl::UnwrappedTileID>
> mbgl::util::tileCover(const mbgl::TransformState&, int32_t): Assertion `state.valid()' failed.
This PR introduces a clamping to scale boundaries in …

Transform::flyTo invalid zoom checks

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Reduces the initial recognition delay of the two-finger drag tilt gesture from ~0.068s to ~0.031s. This is accomplished by:
1. Reversing the failure relationship between the tilt and two-finger tap recognizers.
2. Actually starting the tilt gesture on `UIGestureRecognizerStateBegan`.
With the addition of 3D extrusions in v3.6.x, the tilt gesture is going to be used more often. It would be nice if we could jam this into v3.6.0, but the subsequent patch release would be fine, too.
/cc @1ec5 @fabian-guerra @boundsj

[ios] Minimize tilt gesture delay

---

src/mbgl/util/std.hpp

`vector::erase` invalidates iterators. It's not safe for `erase_if` to cache the end iterator nor increment, then erase.
Fixes #9384.

[core] Fix iterator invalidation in erase_if

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcher.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java

closes #9320 , refs #9335. This PR improves the OnCameraIdle integration. Need to do some tests around [this](https://github.com/mapbox/mapbox-gl-native/pull/9339/files#diff-dc8b8b458b4be05d4cfad1bbafea82aeR395) addition. There are some cases where it's hard to trigger a rotation due to checking that flag. Testing of this feature can be done in CameraPositionActivity.

OnCameraIdle hook into quickzoom gesture

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java

closes #9379, this PR tracks the set value of margins instead of relying on the value at that time. This is needed for a correct `MapboxMap#setPadding` integration.

Track state of initial overlain views margins

---

platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm

When redisplaying the mouse cursor after a modified drag gesture, incorporate the conversion from view coordinates to window coordinates. Previously, this code performed the conversion but threw away the results.
Also reorganized the macOS changelog a little in preparation for v0.5.0.
Fixes #8670.

Fix cursor placement after modified drag gesture

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationDrawableActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java
platform/android/dependencies.gradle

We have been having some issues with recent releases of the LOST library. To be able to ship a next final release for 5.1.0. We are downgrading back to `v1.1.1`. This version shipped as part of our 4.x series.

Downgrade location provider dependency

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties

This PR releases Android v5.1.0 to maven and updates the changelog accordingly. 
Refs https://github.com/mapbox/mapbox-gl-native/issues/9404

Release Android v5.1.0 

---

platform/qt/test/qmapboxgl.cpp

`make run-qt-test` fails for me on master:
```
[----------] 2 tests from QMapboxGLTest
[ RUN      ] QMapboxGLTest.styleJson
Assertion failed: (!size.isEmpty()), function QMapboxGL, file ../../../platform/qt/src/qmapboxgl.cpp, line 437.
make: *** [run-qt-test-*] Abort trap: 6
```
My environment:
```
11:44 $ qmake -v
QMake version 3.1
Using Qt version 5.9.0 in /usr/local/Cellar/qt/5.9.0_1/lib
```

make run-qt-test failure on macOS

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java

Closes #9419. `MarkerView` won't be invalidated if it's invisible.

[android] - invible marker views performance fix

---

src/mbgl/algorithm/generate_clip_ids.cpp
src/mbgl/algorithm/generate_clip_ids.hpp
src/mbgl/algorithm/generate_clip_ids_impl.hpp
src/mbgl/annotation/render_annotation_source.cpp
src/mbgl/annotation/render_annotation_source.hpp
src/mbgl/renderer/painter.cpp
src/mbgl/renderer/render_source.hpp
src/mbgl/renderer/render_style.cpp
src/mbgl/renderer/render_tile.hpp
src/mbgl/renderer/sources/render_geojson_source.cpp
src/mbgl/renderer/sources/render_geojson_source.hpp
src/mbgl/renderer/sources/render_image_source.hpp
src/mbgl/renderer/sources/render_raster_source.cpp
src/mbgl/renderer/sources/render_raster_source.hpp
src/mbgl/renderer/sources/render_vector_source.cpp
src/mbgl/renderer/sources/render_vector_source.hpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/renderer/tile_pyramid.hpp
test/algorithm/generate_clip_ids.test.cpp

This is a leftover for another refactor that I attempted, but I think it's useful to have it, since it removes the `std::map<>` in favor of a vector. This is possible because we don't do lookups in the `map` and don't rely on its uniqueness property.

Refactor ClipID generation

---

src/mbgl/layout/symbol_layout.hpp
src/mbgl/tile/geometry_tile_worker.cpp
src/mbgl/tile/geometry_tile_worker.hpp

Fix an oversight from #9213 / f73f45107f02f5b1d945a7a41e3e6d1e88ecf9b8.

[core] make{Glyph,Image}Atlas only once for any number of symbol layers

---

src/mbgl/renderer/bucket.hpp
src/mbgl/renderer/buckets/symbol_bucket.cpp
test/gl/bucket.test.cpp
test/src/mbgl/test/stub_geometry_tile_feature.hpp
test/util/merge_lines.test.cpp

Another spin-off from #9148, this PR adds simple bucket feature insertion tests, and also:
- Check if bucket contains data in `Bucket::needsUpload()`
- Remove redundant `GeometryCollection` param in `Bucket::addFeature()`

Bucket test updates

---

include/mbgl/style/conversion/make_property_setters.hpp
include/mbgl/style/layers/circle_layer.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Property.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
platform/android/src/style/layers/circle_layer.cpp
platform/android/src/style/layers/circle_layer.hpp
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.mm
platform/darwin/test/MGLCircleStyleLayerTests.mm
src/mbgl/programs/circle_program.hpp
src/mbgl/programs/symbol_program.hpp
src/mbgl/programs/uniforms.hpp
src/mbgl/renderer/painters/painter_circle.cpp
src/mbgl/shaders/circle.cpp
src/mbgl/style/layers/circle_layer.cpp
src/mbgl/style/layers/circle_layer_properties.hpp

Port from GL JS PR https://github.com/mapbox/mapbox-gl-js/pull/4871.
Fixes issue #9349.
This is my first time using the `generate-style-code` script. Everything that it spit out looks reasonable, but I'm not sure what extra steps I should take to test the Android/iOS code it generates. I'm not even sure what the auto-generated transition code does.
The one concern I had was that it wanted to interpret anything ending in `-alignment` as an `AlignmentType`, which allows an `auto` value. We don't have an `auto` value for `circle-pitch-alignment`, so maybe we should override that with a stricter type? On the other hand, if someone did use `auto`, the effect would end up being to use the default `viewport` value, so it wouldn't be a very surprising result. 

Implement 'circle-pitch-alignment' property

---

Makefile
cmake/node.cmake

Adds a make target for running the node benchmark script and a xcode scheme through cmake.

Add node-benchmark target and xcode scheme

---

src/mbgl/util/i18n.cpp

This change updates the script detection code to reflect changes in [Unicode 10](http://www.unicode.org/Public/10.0.0/ucd/Blocks.txt) and [UTR #50 revision 17](http://www.unicode.org/Public/vertical/revision-17/VerticalOrientation-17.html).
This is a port of mapbox/mapbox-gl-js#4919.
/cc @ChrisLoer

Update script detection for Unicode 10

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

Closes #9432, it seems that there are edge cases were the Android implementation returns null for a MotionEvent. This PR hardens integration and will perform no action when such motion event occurs.

Validate if platform doesn't return a null motion event

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/MapChangeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/VisibilityChangeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_map_visibility.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

Follow up from https://github.com/mapbox/mapbox-gl-native/pull/9412, While that PR didn't make the cut, it contained 2 useful test activities. 
Adding them as a separate PR.

[android] - add Map change & visibility test activities

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/IconManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MarkerContainer.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_check_box.xml

WIP, Closes #8159.
This PR adds hit testing to Markers and MarkerViews, we first query the map for nearby markers and on that result we perform rectangular hit testing. If we hit multiple annotation (eg. overlapping), we will make an intersection between the touch target and the bounds of the annotation to determine which annotation should be selected. This PR requires some re factoring before merging.

Hit test Marker and MarkerViews

---

src/mbgl/renderer/sources/render_geojson_source.hpp

```
==24942== Conditional jump or move depends on uninitialised value(s)
==24942==    at 0x7D943D: mbgl::RenderGeoJSONSource::update(mbgl::Immutable<mbgl::style::Source::Impl>, std::vector<mbgl::Immutable<mbgl::style::Layer::Impl>, std::allocator<mbgl::Immutable<mbgl::style::Layer::Impl> > > const&, bool, bool, mbgl::TileParameters const&) (in /home/tmpsantos/Projects/mapbox-gl-native/build/linux-x86_64/Release/mbgl-test)
==24942==    by 0x796445: mbgl::RenderStyle::update(mbgl::UpdateParameters const&) (in /home/tmpsantos/Projects/mapbox-gl-native/build/linux-x86_64/Release/mbgl-test)
==24942==    by 0x77E29D: mbgl::Map::Impl::render(mbgl::View&) (in /home/tmpsantos/Projects/mapbox-gl-native/build/linux-x86_64/Release/mbgl-test)
==24942==    by 0x77E559: mbgl::Map::Impl::renderStill() …
```

[core] Fix conditional unitialized jump on RenderGeoJSONSource

---

platform/android/config.cmake
platform/default/thread_local.cpp
platform/ios/config.cmake
platform/linux/config.cmake
platform/macos/config.cmake
platform/qt/qt.cmake
platform/qt/src/thread.cpp
platform/qt/src/thread_local.cpp
src/mbgl/util/thread_local.hpp
test/util/thread_local.test.cpp

This is important to get Mapbox GL running on Windows via the
Qt platform. We could use C++11 thread_local but sadly is not
widely supported.

[core] Do not assume POSIX threads

---

circle.yml

Follow up & revert of #8958. Final release of 5.1.0 happened.
We can start building our SNAPSHOTS back from master.

[android] - build SNAPSHOT from master

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java

It's a public method, its comment should be a Javadoc comment.

Fix javadoc comment for public setOfflineMapboxTileCountLimit method

---

platform/ios/config.cmake
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/config.cmake
platform/macos/macos.xcodeproj/project.pbxproj
scripts/config.xcconfig.in

Switches to using the more traditional cmake approach to including the polylabel library in the iOS and macOS projects.
As noted in https://github.com/mapbox/mapbox-gl-native/pull/7604#issuecomment-314081480. Originally implemented in https://github.com/mapbox/mapbox-gl-native/pull/8713.
/cc @kkaefer @fabian-guerra

[darwin] Include polylabel via cmake

---

benchmark/api/query.benchmark.cpp

For some mysterious reason GCC 5 was complaining about the implicit default
value. Passing it explicitly fixes it.

[benchmark] Fix build on GCC 5

---

platform/macos/config.cmake

We are already compiling core and tests with `-fvisibility=hidden`, but not the glfw/render/offline targets. This leads to linker warnings like this:
> Direct access in function `mbgl::Tileset const& mapbox::util::variant<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mbgl::Tileset>::get<mbgl::Tileset, (void*)0>() const` from file `.../build/macos/Debug/libmbgl-core.a(offline_download.o)` to global weak symbol `typeinfo for mapbox::util::bad_variant_access` from file `.../build/macos/mbgl.build/Debug/mbgl-glfw.build/Objects-normal/x86_64/glfw_view.o` means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

Add `-fvisibility=hidden` for all macOS targets to avoid linker warnings

---

CMakeLists.txt
src/mbgl/annotation/symbol_annotation_impl.hpp
src/mbgl/text/collision_tile.hpp

They're not implemented there.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/9197

Disable GCC-only warnings in Clang

---

circle.yml

We recently fixed the source of our flaky tests in #9198. Time to scale the amount of tests we run on CI. This PR enables testing the full `com.mapbox.mapboxsdk.testapp.style` package instead of 1 regression test. This  will help detect regressions faster with recent core changes related to async rendering.

[android] - run style instrumentation tests on CI

---

scripts/lldb-types

You can import the file with `command source scripts/lldb-types` to your current debugging session to get better type summaries.
Alternatively, you can create a `~/.lldbinit` file with 
```
command source /Users/kkaefer/Code/gl/native/scripts/lldb-types
```
(replace the path to the repository with the absolute path on your system)
This also enables the type summaries in Xcode.
Showing synthesized children/summaries for `mapbox::util::variant` is blocked by missing support for variadic template parameter packs: https://bugs.llvm.org/show_bug.cgi?id=33760

[core] add LLDB summaries for types we use commonly

---

include/mbgl/style/conversion/make_property_setters.hpp
include/mbgl/style/layers/symbol_layer.hpp
include/mbgl/util/size.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Property.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/Light.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/src/style/layers/symbol_layer.cpp
platform/android/src/style/layers/symbol_layer.hpp
platform/darwin/src/MGLSymbolStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.mm
platform/darwin/test/MGLSymbolStyleLayerTests.mm
src/mbgl/layout/symbol_layout.cpp
src/mbgl/programs/symbol_program.cpp
src/mbgl/programs/symbol_program.hpp
src/mbgl/renderer/layers/render_symbol_layer.cpp
src/mbgl/shaders/symbol_icon.cpp
src/mbgl/shaders/symbol_sdf.cpp
src/mbgl/style/layers/symbol_layer.cpp
src/mbgl/style/layers/symbol_layer_properties.hpp

This PR depends on https://github.com/mapbox/mapbox-gl-js/pull/4974 and https://github.com/mapbox/mapbox-gl-native/pull/9478 for tests. Once those go in, this will be ready -- no code changes should be necessary.
Implements 'icon-pitch-alignment' (issue #9345)
Fixes issue #9456 (map-aligned point label regression)
/cc @ansis @mollymerp

Update shaders: get 'icon-pitch-alignment' and fix for issue #9456

---

cmake/glfw.cmake
platform/linux/config.cmake
platform/macos/config.cmake

This GLFW version properly attempts to define GLAPIENTRY (if not previously defined) only _after_ including the GL headers. With this fix, we no longer need to workaround on `glfw_view.cpp` by adding `-Wno-error` as compilation parameter.

[build] Update GLFW to 2017-07-13-67c9155

---

platform/default/mbgl/storage/offline_database.cpp

Found via https://github.com/mapbox/mapbox-gl-native/issues/9499

Fix undefined access for HTTP responses that don't contain a body

---

test/algorithm/update_renderables.test.cpp

Without those, Clang crashes with `Illegal instruction: 4`
Filed with Apple as rdar://33290534

Fix Clang crash in Xcode 9 beta 2

---

test/text/quads.test.cpp

quads.test.cpp used a bin with unsupported x/y coordinates, which caused an undefined behavior warning tracked in issue #9499.
/cc @kkaefer

Fix undefined behavior warning in quads.cpp

---

platform/default/thread_local.cpp
platform/qt/src/thread_local.cpp
scripts/valgrind.sup
test/util/thread_local.test.cpp

ThreadLocal should not own the pointer it is managing because the use case
in Mapbox GL is to keep a pointer to a stack allocated object, like:
``` 
MyObject foo;
threadLocal.set(&foo);
```
To keep consistency, it is required that we clear the managed object before
ThreadLocal gets destroyed by setting it to `nullptr`.

[core] Make sure ThreadLocal will not own the pointer it is managing

---

CMakeLists.txt
Makefile
circle.yml
package.json
platform/node/CHANGELOG.md
platform/node/bitrise.yml
platform/node/scripts/after_success.sh

Follow-up to #9154 - Make node release binaries debuggable - after switching to CircleCI.
From @bsudekum original notes:
> This change makes Node release binaries a little bit more debuggable. Now when there is a crash in production, we should get more information including line numbers. There is no speed implications here, the only downside is an increase in binary size (currently, release binaries are ~2mb).
/cc @springmeyer @tmpsantos

[build] Publish node packages with RelWithDebInfo

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

This PR:
- fixes dragging while zooming issue, closes #9413
- simplifies state handling in our gesture code 
- moves telemetry event pushes to the correct place in code where the gesture is valid.
- does _not_ solve the problems of the almeros library
- does _not_ prohibit scale and rotate to execute at the same time

Rewire gesture handling and telemetry event push

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.java
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml

Follow up from external PR in https://github.com/mapbox/mapbox-gl-native/pull/9465
> Our users were complaining about location accuracy circle being present all the time, so here's a simple option to disable it for location updates with decent enough accuracy.
cc @LukasPaczos

Location accuracy threshold

---

platform/node/scripts/after_success.sh

CircleCI always sets `PUBLISH`, so we need an extra check if it is set to `true`.

[build] Fix node package publish logic

---

src/mbgl/map/transform.cpp
src/mbgl/text/collision_feature.cpp
src/mbgl/text/collision_tile.cpp
src/mbgl/util/math.hpp

Introduces a `util::division` function that allows specifying a value for the `0/0` (NaN) case.

Fix undefined behavior for division through 0

---

platform/qt/src/sqlite3.cpp
test/storage/sqlite.test.cpp

Qt doesn't throw a Exception::Code::CANTOPEN when trying to open a database
that doesn't exist without the Create flag.
Another attempt to fix #9108

[Qt] Align database creation behavior with the default implementation

---

include/mbgl/style/sources/image_source.hpp
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/AnimatedImageSourceActivity.java
platform/android/src/style/sources/image_source.cpp
platform/darwin/src/MGLImageSource.mm
platform/macos/src/NSImage+MGLAdditions.mm
src/mbgl/renderer/buckets/raster_bucket.cpp
src/mbgl/renderer/buckets/raster_bucket.hpp
src/mbgl/renderer/sources/render_image_source.cpp
src/mbgl/renderer/sources/render_image_source.hpp
src/mbgl/shaders/raster.cpp
src/mbgl/style/sources/image_source.cpp
src/mbgl/style/sources/image_source_impl.cpp
src/mbgl/style/sources/image_source_impl.hpp
src/mbgl/tile/raster_tile_worker.cpp
test/gl/bucket.test.cpp
test/style/source.test.cpp
test/tile/raster_tile.test.cpp

`ImageSource`'s runtime APIs are performing very poorly primarily due to poor management of image data. In addition, there are bottlenecks in the SDKs related to decoding the image data.
This addresses: #9304, #9070
- PremultipliedImage/UnassociatedImage: Add support for different backing storage (#9333)
- Allow `ImageSource` to use `style::image`
/cc @kkaefer @ansis

[core][ios][macos][android] Improve ImageSource performance

---

CMakeLists.txt
scripts/launch-c-xcode.in
scripts/launch-c.in
scripts/launch-cxx-xcode.in
scripts/launch-cxx.in
test/algorithm/update_renderables.test.cpp

When using Xcode installed in a non-standard location, CMake will use the wrong compiler when building the ccache launch script introduced in https://github.com/mapbox/mapbox-gl-native/pull/9399.
* Instead of picking the one for the currently enabled Xcode (activated with `xcode-select`), it'll always use `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang`
* Even when opening the generated project with another Xcode.app (e.g. with a beta version) it *still* uses the default compiler, rather than the compiler that ships with the Xcode.app that executes the build.
/cc @mapbox/ios

Xcode uses wrong compiler

---

circle.yml

Circle CI is going to remove branch filtering from jobs, and only support it via workflows.

Do not run clang-tidy on master

---

platform/android/dependencies.gradle

Bumping OkHttp dependency to avoid null pointers in Android 7.0
More information in https://github.com/square/okhttp/issues/3245.
Closes #9521

[android] - bump OkHttp dependency 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolylineActivity.java

Closes #3720, still a WIP though fully functional. 
Going to land #9424 first as it introduces a couple of refactors to related code.

add Polyline and Polygon click listeners

---

platform/qt/src/qmapboxgl_p.hpp

The Map object will call the renderer frontend on its destructor.
Fixes #9535.

[Qt] Destroy the map object before the renderer frontend

---

CMakeLists.txt
INSTALL.md

ccache support was added in https://github.com/mapbox/mapbox-gl-native/pull/9399 — this PR follows up with some helpful docs/notes:
- Prints a reminder to install ccache if it’s not found while cmake is setting up.
- Adds ccache to the core install doc as an optional dependency.
/cc @kkaefer

[build] Add ccache install reminder and docs

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/PolylineContainer.java

Trying to update non-existent polyline fix

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

This PR rewrites the way we do map initialisation. Before this PR we created the map object when the hosting MapView was inflated. This PR now postpones creating the map object until the Surface of the MapView is ready. A benefit of this is that the view will be measured by the time that MapboxMap will be created and thus removes the necessity of posting the OnMapReadyCallback invocations. 
Closes #9136

Rewire map initialisation

---

cmake/test-files.cmake
include/mbgl/map/backend.hpp
include/mbgl/map/backend_scope.hpp
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp
src/mbgl/map/backend_scope.cpp
test/renderer/backend_scope.test.cpp

Ports backend scope changes that make manual reference counting on android for backend activation/deactivation obsolete.
Fixes #9458
@zugaldia I tagged you for review as you reported #9458 and I'm not sure how to reproduce.

port backendscope changes to release branch

---

CODE-OF-CONDUCT.md
CONTRIBUTING.md
DEVELOPING.md
INSTALL.md
include/mbgl/renderer/query.hpp
include/mbgl/renderer/renderer.hpp
include/mbgl/renderer/renderer_frontend.hpp
include/mbgl/style/transition_options.hpp
platform/android/README.md
platform/linux/README.md
src/mbgl/annotation/annotation_tile.hpp
src/mbgl/renderer/render_source.hpp
src/mbgl/renderer/render_style.hpp
src/mbgl/renderer/sources/render_image_source.cpp
src/mbgl/renderer/sources/render_raster_source.cpp
src/mbgl/renderer/tile_parameters.hpp
src/mbgl/renderer/tile_pyramid.hpp
src/mbgl/renderer/update_parameters.hpp
src/mbgl/tile/geojson_tile.hpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/raster_tile.hpp
src/mbgl/tile/tile_loader.hpp
src/mbgl/tile/vector_tile.hpp

Added GCC 4.9 developing notes, including examples and workarounds of C++14 features not supported by that compiler version. A separate code of conduct makes all checks go green in https://github.com/mapbox/mapbox-gl-native/community page.

GCC 4.9 developing notes

---

src/mbgl/gl/attribute.cpp
src/mbgl/gl/attribute.hpp
src/mbgl/gl/program.hpp

Reverts eed89fcf9d099266aa793375ad63493e880f8a80, which causes issues on certain Android devices (#9473). We don't actually need this change on this branch, I brought it over only to make the subsequent commits cleanly cherry-pickable.

[core] Revert conditional attribute binding (on release branch)

---

platform/node/test/ignores.json

See https://github.com/mapbox/mapbox-gl-native/issues/9555.
/cc @nickidlugash @mollymerp

[test] Add native ignore for 'text-anchor/property-function'

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/InfoWindowManager.java

Every time we receive a region change event, we are synchronizing Android SDK view components on top of the map. With profiling of gestures in #9476, I'm noticing we are allocating iterators for InfoWindows while no InfoWindows are shown. Checking for an empty avoids creating unneeded allocations.

Avoid creating InfoWindow iterator if no InfoWindows are shown

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/IconManager.java

Follow up from https://github.com/mapbox/mapbox-gl-native/pull/9424, since we have hit testing we are allowed to increase the touch surface. 
This allows to click MarkerViews that are larger as other icons.

[android] - increase touch target to match largest Marker icon

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java

Follow up from #9424, there we consolidated select states of Marker and MarkerView. We didn't remove selecting state handling as part of the MarkerView click handler. This resulted in select and immediately deselecting the Marker and thus not showing the InfoWindow.

[android] - manage InfoWindow selection in AnnotationManager

---

Makefile
circle.yml
platform/android/MapboxGLAndroidSDK/.gitignore
platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/lint/lint-baseline-ci.xml
platform/android/MapboxGLAndroidSDKTestApp/.gitignore
platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/lint/lint-baseline-ci.xml
platform/android/MapboxGLAndroidSDKWearTestApp/.gitignore
platform/android/MapboxGLAndroidSDKWearTestApp/build.gradle
platform/android/MapboxGLAndroidSDKWearTestApp/gradle-config.gradle
platform/android/MapboxGLAndroidSDKWearTestApp/lint/lint-baseline-ci.xml
platform/android/gradle-lint.gradle

Fixes #8357 
- Adds lint using our current baseline as starting point
👀 @zugaldia @tobrun

[android] Add lint support

---

src/mbgl/gl/context.cpp

Speculative fix for #9473.
@Guardiola31337, can you test this on the Nexus 5 and Moto X?

[android] Disable program caching on Adreno 3xx, 4xx, and 5xx GPUs due to known bugs

---

platform/node/index.js
platform/node/src/node_request.cpp
platform/node/src/node_request.hpp

Fix crash on OS X node tests

---

benchmark/parse/tile_mask.benchmark.cpp
cmake/benchmark-files.cmake
cmake/benchmark.cmake
cmake/core-files.cmake
cmake/test-files.cmake
src/mbgl/algorithm/update_tile_masks.hpp
src/mbgl/gl/index_buffer.hpp
src/mbgl/gl/vertex_buffer.hpp
src/mbgl/renderer/buckets/raster_bucket.cpp
src/mbgl/renderer/buckets/raster_bucket.hpp
src/mbgl/renderer/layers/render_raster_layer.cpp
src/mbgl/renderer/render_tile.cpp
src/mbgl/renderer/render_tile.hpp
src/mbgl/renderer/sources/render_raster_source.cpp
src/mbgl/renderer/tile_mask.hpp
src/mbgl/tile/raster_tile.cpp
src/mbgl/tile/raster_tile.hpp
src/mbgl/tile/tile.hpp
src/mbgl/tile/tile_id_io.cpp
test/algorithm/update_tile_masks.test.cpp
test/gl/bucket.test.cpp

This changes our raster tile rendering to avoid rendering in the parts of a tile that have children for. It accomplishes this by generating vertex buffers that only have quads for the respective areas, rather than having one quad to fill the entire tile.
The first part of the PR refactors Vertex/Index/Segment vectors into their own `IndexedPrimitive`/`Drawable` classes. We can apply the same pattern for other buckets in a separate PR.
The algorithm works by recursively descending from the tile in question and generating a list of tiles that would cover the tile, but not any of its children.
Finally, we're computing vertex buffers with our new `IndexedPrimitive` class and store the vertex buffers in a repository object.
Remaining tasks:
Fixes …

Clip raster tiles

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/InfoWindowManager.java

Was able to hit a crash when clicking a marker and closing the Activity hosting the MapView quickly after. This PR adds a check to validate if Marker is still valid to show an InfoWindow when we get the results back from queryPointAnnotations.

Validate Marker before opening InfoWindow

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

[android] - harden click handling of shape annotations

---

include/mbgl/actor/actor.hpp
include/mbgl/actor/actor_ref.hpp
include/mbgl/actor/message.hpp
test/actor/actor.test.cpp
test/actor/actor_ref.test.cpp

Split off two additions to the Actor system from work on async rendering (#9576):
-  Add ask pattern to Actor/ActorRef to make blocking calls from one thread to the other (Similar to Akka)
- Make self reference on Actors optional so we can make arbitrary objects Actors without modifying the constructor

Actor enhancements

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/ViewPagerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/view/MapViewPager.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_viewpager.xml

refs https://github.com/mapbox/mapbox-gl-native/issues/9561#issuecomment-317653832, this PR provides a workaround for the issue shown in #9561.

Custom viewpager for horizontal swiping

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MarkerContainer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/PolygonContainer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/PolylineContainer.java

- Fixes added to map checks because [`LongSparseArray#indexOfKey`](https://developer.android.com/reference/android/util/LongSparseArray.html#indexOfKey(long)) could return a negative number when the specified key is not mapped
👀 @tobrun

[android] Fix added to map checks

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

Definitive fix for https://github.com/mapbox/mapbox-gl-native/issues/9584. When clicking the map and no shape annotations are added. We were passing in an empty array for layer id. This resulted in querying all the layer maps while we only want to query the layers with shape annotations on them.

Don't query shape annotations if none were added

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

closes #9590, this PR hooks into `onGlobalLayout` versus `onVisibilityChanged`. As noted in #9590, dynamic fragment containers as ViewPager don't call into `onVisibilityChanged`. Hooking into `onGlobalLayout` instead resolves the issue. The issue stems from #9462 where we decoupled view an map initialization.

onGlobalLayout hook for map creation

---

benchmark/api/query.benchmark.cpp
benchmark/api/render.benchmark.cpp
bin/render.cpp
include/mbgl/renderer/renderer_backend.hpp
platform/android/src/android_renderer_frontend.cpp
platform/android/src/android_renderer_frontend.hpp
platform/android/src/native_map_view.cpp
platform/darwin/src/MGLRendererFrontend.h
platform/default/mbgl/gl/headless_backend.cpp
platform/default/mbgl/renderer/async_renderer_frontend.cpp
platform/default/mbgl/renderer/async_renderer_frontend.hpp
platform/glfw/glfw_renderer_frontend.cpp
platform/glfw/glfw_view.cpp
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm
platform/node/src/node_map.cpp
platform/node/src/node_renderer_frontend.cpp
platform/node/src/node_renderer_frontend.hpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_p.hpp
platform/qt/src/qmapboxgl_renderer_frontend_p.cpp
platform/qt/src/qmapboxgl_renderer_frontend_p.hpp
src/mbgl/renderer/renderer_impl.cpp

Fixes #9572
Could alternatively be done in the renderer frontend, but that would require passing the backend to it just for cleanup.

Ensure the right context is active on map cleanup

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Partially addresses https://github.com/mapbox/mapbox-gl-native/issues/9597, where subviews of MGLMapView have their custom tint colors unnecessarily overridden. A full fix for that issue would be a breaking change, so this only attempts to fix the attribution button.
UIButton can be relied on to automatically update its tint to match its parent view, if it still inherits a tint from that parent.
This issue was brought to the fore because of the switch to UIAlertController in v3.6.0 (https://github.com/mapbox/mapbox-gl-native/pull/8373), which triggers `-tintColorDidChange` calls on presentation and dismissal.
/cc @fabian-guerra @1ec5 @boundsj @jmkiley

[ios] Don't force the attribution button tint color to update

---

platform/qt/src/sqlite3.cpp

It was overflowing due to long to int conversion inside Qt and
never being effectively set because Qt was silently ignoring
the conversion error and discarding the new value.
Fixes #9108.

[Qt] Fix database busy timeout not being set correctly

---

Makefile

This PR adds a make target for dumping system gfx system information related to the test app. This is allows to profile GPU rendering and quantify the amount of dropped frames. 
Example output:
```
Stats since: 752958278148ns
Total frames rendered: 82189
Janky frames: 35335 (42.99%)
90th percentile: 34ms
95th percentile: 42ms
99th percentile: 69ms
Number Missed Vsync: 4706
Number High input latency: 142
Number Slow UI thread: 17270
Number Slow bitmap uploads: 1542
Number Slow draw: 23342
```

Make target for dumping system gfx information

---

include/mbgl/util/string.hpp
scripts/clang-tools.sh
src/mbgl/annotation/shape_annotation_impl.hpp
src/mbgl/style/parser.cpp
src/mbgl/style/sources/geojson_source_impl.cpp
src/mbgl/text/shaping.cpp
src/mbgl/tile/geojson_tile.cpp
src/mbgl/util/dtoa.cpp
src/mbgl/util/http_header.cpp

Specifically when building Android with GCC 4.9 (which Qt still does :-/)

[core] Fix issues with the std:: namespace and old compilers

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java

Forward getMapAsync to map for fragment

---

platform/ios/CHANGELOG.md
platform/ios/scripts/package.sh

`.bcsymbolmap` files are text files with a list of symbols available in our framework, used to map recompiled bitcode to named symbols for crash reporting. These files are generated in the build process, one per device architecture, and share UUIDs with those slices/dSYMs.
These bcsymbolmap files can be included during the app archiving process and uploaded to Apple.
- Carthage ~does this automatically~. (https://github.com/Carthage/Carthage/pull/853)
- CocoaPods does not. (It’s only just now getting proper dSYM support. 😑)
- Our standalone-install [`strip-framework.sh`](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.6.0/platform/ios/framework/strip-frameworks.sh#L43) ~already supports this~. (https://github.com/realm/realm-cocoa/pull/2759)
08b963e packages these files alongside …

[build] Package bcsymbolmap files; cleanup packaging script

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java

- Fixes compass direction:
- `Transform::getCameraOptions` returns a [counterclockwise angle](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/map/camera.hpp#L30-L32) after [`transform.invalidateCameraPosition()`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/map/camera.hpp#L30-L32) which needs to be transformed to a clockwise bearing before [updating the compass](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java#L430)
Currently, the compass is pointing upside down:
👀 @tobrun

[android] Fix compass direction

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Retarget of @danielamitay’s #9595 against the current release branch, with some additional small tweaks.
/cc @fabian-guerra @1ec5

Improve zoom gesture behavior at minZoom

---

platform/ios/src/MGLMapView.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/2435
WIP: I'm stuck trying to improve the reliability of the recognizer, the reason is sometimes even when I'm dragging with two fingers in the delegate I get one touch that makes the gesture behaves oddly.

[ios] Make tilt gesture recognizer recognizable only with two horizontal fingers

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapZoomButtonController.java

in #9462 we started to make a distinction between view versus map initialization. `MapZoomButtonController` was created as part of the map initialization while it's actually a view itself. This PR also changes from inheritance to composition.

Move ZoomButtonController creation to view initalisation

---

platform/node/test/ignores.json

See https://github.com/mapbox/mapbox-gl-native/issues/9668
/cc @ChrisLoer @mollymerp

[test] Add native ignore for text-letter-spacing/property-function and zoom-and-property-function

---

cloudformation/travis.template

This PR combines the AWS keys generated for policies under `BitriseAccessKeyId` and `AccessKeyId` into a single policy.
This will allow us to keep a single set of keys on Circle CI for publishing both Android and Node binaries.
/cc @jfirebaugh @zugaldia @friedbunny

Combine AWS keys

---

scripts/generate-shaders.js
src/mbgl/shaders/circle.cpp
src/mbgl/shaders/fill.cpp
src/mbgl/shaders/fill_extrusion.cpp
src/mbgl/shaders/fill_extrusion_pattern.cpp
src/mbgl/shaders/fill_outline.cpp
src/mbgl/shaders/fill_outline_pattern.cpp
src/mbgl/shaders/fill_pattern.cpp
src/mbgl/shaders/line.cpp
src/mbgl/shaders/line_pattern.cpp
src/mbgl/shaders/line_sdf.cpp
src/mbgl/shaders/symbol_icon.cpp
src/mbgl/shaders/symbol_sdf.cpp

We moved the `#pragma` ⇢ `#ifndef` logic into gl-js in https://github.com/mapbox/mapbox-gl-js/commit/e93db1b4a601610695c0a0bad360f0d8f06cdb3b; take advantage of that.

[core] Simplify generate-shaders.js

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm

Added a new camera method that takes `edgePadding` as a parameter to overcome the default insets `contentInsets` which insets the ornaments like compass and attribution.

[ios] Expose setCamera with padding

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/DynamicInfoWindowAdapterActivity.java

This PR fixes the example of a InfoWindowAdapter by posting the update of InfoWindow. 
Don't feel that this fix should be added to the SDK since this is a custom InfoWindowAdapter implementation (this issue doesn't happen with default implementation).

post updating InfoWindow update for InfoWindowAdapter

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

- Fix formatting zoom position `DebugModeActivity` crash:
`java.util.IllegalFormatConversionException: %d can't format java.lang.Double arguments`
👀 @tobrun

[android] Fix formatting zoom position DebugModeActivity crash

---

include/mbgl/actor/actor.hpp
test/actor/actor.test.cpp

Not in use at the moment, was causing a compiler error on
Apple LLVM version 8.0.0 (clang-800.0.42.1).
```
src/mbgl/sprite/sprite_loader.cpp:25:11: error: call to constructor of
'Actor<mbgl::SpriteLoaderWorker>' is ambiguous
```

[core] Removed unused constructor

---

include/mbgl/actor/actor.hpp
test/actor/actor.test.cpp

In #9591 we added a way to construct Actors from arbitrary objects (without requiring modifying the constructor(s)). This broke on Apple clang < 8.2 which is needed for Qt and got reversed in #9720.
This PR re-introduces the same construct with a slightly different syntax on the templates which works with older apple clang versions as well.

Make actor self reference optional - again

---

CMakeLists.txt

This version builds on Android + GCC.

[core] Bump vector-tile to v1.0.0-rc7

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLFaux3DUserLocationAnnotationView.m

The scale of the horizontal accuracy indicator was off by approximately +25% (i.e., it was larger, telling the user it was less accurate that it should have), depending on latitude.
/cc @boundsj @fabian-guerra

[ios] Fix user location accuracy ring inaccuracy

---

include/mbgl/util/constants.hpp
package.json
platform/node/test/ignores.json
scripts/generate-shaders.js
src/mbgl/programs/attributes.hpp
src/mbgl/programs/line_program.cpp
src/mbgl/programs/line_program.hpp
src/mbgl/renderer/buckets/line_bucket.cpp
src/mbgl/shaders/line.cpp
src/mbgl/shaders/line_pattern.cpp
src/mbgl/shaders/line_sdf.cpp

Broadcom GPUs don't cope well with using the least significant bit for this.
Fixes #7583.

[core] Use separate attribute components for line normals

---

platform/default/mbgl/gl/headless_backend.cpp

Fixes `headless_backend.cpp:14:37: Declaration shadows a field of 'mbgl::HeadlessBackend'` on `Apple LLVM version 8.0.0 (clang-800.0.42.1)`

Fix shadowing argument on apple clang 8.0

---

cmake/core-files.cmake
include/mbgl/actor/scheduler.hpp
include/mbgl/util/run_loop.hpp
platform/android/src/file_source.cpp
platform/android/src/run_loop.cpp
platform/darwin/src/MGLOfflineStorage.mm
platform/darwin/src/run_loop.cpp
platform/default/online_file_source.cpp
platform/default/run_loop.cpp
platform/default/thread_local.cpp
platform/qt/src/run_loop.cpp
platform/qt/src/thread_local.cpp
src/mbgl/actor/scheduler.cpp
src/mbgl/sprite/sprite_loader.cpp
src/mbgl/storage/file_source_request.cpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/raster_tile.cpp

Extracted the current `Scheduler` part of #9611 as requested:
This PR adds an abstraction on top of the RunLoop so that we can Schedule work on arbitrary schedulers. This is important for asynchronous rendering where we are dealing with threads without a runloop that need to defer scheduling of additional work to another thread scheduler and/or use another form of scheduling than a RunLoop (see #9576).
In certain places we will still work with the `RunLoop` directly where it's needed (`OnlineFileSource`, `AsyncTask`)

Current Scheduler

---

platform/android/MapboxGLAndroidSDK/build.gradle

This allows to build a different architecture then the default for a device, for example armeabi-v7a instead of arm64-v8a (which allows for better stack traces.
Set in compiler > command-line options: -Pmapbox.abis=...

Allow overriding abi from IDE

---

platform/darwin/src/MGLPolyline.h
platform/darwin/test/MGLDocumentationExampleTests.swift

Adds additional context and a small example demonstrating how to create a line that crosses the antimeridian / international date line:

[ios] Add additional documentation when working with antimeridian crossings

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/GeoJsonSourceTests.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxSymbolCountActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/DataDrivenStyleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/StyleFileActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/ResourceUtils.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_style_file.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/raw/sat_style.json
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/strings.xml

closes #8347, additionally this PR fixes: 
- add example for setStyleJson to local file style example
- add example for getStyleJson in debug mode activity
- correct exception forwarding for timber
- formatting issue with doubles
- corrected placement of bottomsheet activity category

Expose setStyleJson and getStyleJson

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Closes #9745, as noted in issue and shown in [chromium](https://src.chromium.org/viewvc/chrome/trunk/src/content/public/android/java/src/org/chromium/content/browser/DeviceMotionAndOrientation.java?pathrev=246398) tracker. A couple of 4.3 Samsung devices throw an exception when the rotation vector size is larger as 4. This PR provides compatibility those devices.
Haven't been able to verify this issue myself, default implementation still works.

Compability for Samsung devices forcing 3-4 array vector length

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/IconManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/IconManagerResolver.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/annotations/IconTest.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

Optimise icon management

---

include/mbgl/style/style.hpp
platform/ios/src/MGLMapView.mm
src/mbgl/map/map.cpp
src/mbgl/style/style.cpp
src/mbgl/style/style_impl.cpp
src/mbgl/style/style_impl.hpp
test/fixtures/api/empty-zoomed.json
test/map/map.test.cpp
test/style/style.test.cpp

Spin-off from https://github.com/mapbox/mapbox-gl-native/pull/9689. We were not resetting `cameraMutated` back to false, which was causing the consecutive loaded styles to not use their default camera (zoom, pitch, bearing, coordinates) values.

[core] Added Style::getDefaultCamera()

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java

closes #7155, validated that linked issues in #7155 didn't show. 
@zugaldia do we want to include this in the next patch release?

Restore max zoom to 25.5

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java

This PR re-adds `getProjectedMetersForLatLng` & `getLatLngForProjectedMeters`.
Not sure when/why it was removed in the first place.

Readd projectedMeters

---

circle.yml

Been hitting firebase timeouts on an average of 1 out of 5 CI builds yesterday. I initially punted this on some infrastructure issue on Firebase but since I'm hitting this again today I'm increasing the timeout from 15 to 20 minutes (afaik we aren't the slowest build on this repo, this makes the increase is justifiable).

Increase firebase timeout for CI testing

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.java

This PR deprecates using MyLocationView and recommends switching to the [LocationLayer](https://www.mapbox.com/android-docs/plugins/overview/location-layer/) plugin instead. This will allow users to migrate to this newer API while we can remove integration in follow up releases. 
Deprecation has been added to all public API methods and classes that can be considered part of the public API that have a direct relation to MyLocationView. 
cc @cammace

Deprecate MyLocationView in favor of LocationLayer plugin

---

cmake/benchmark.cmake
cmake/core.cmake
cmake/glfw.cmake
cmake/mbgl.cmake
cmake/node.cmake
cmake/render.cmake
cmake/test.cmake

Some of Xcode's project defaults cause some of our CXX flags to be overridden (e.g. `-Wno-unused-variable`, which unsets `-Wunused-variable` that should be included in `-Wall`).  The result is that building locally, it's easy to miss errors that then cause CI failures.
This change initializes those Xcode settings to be consistent with the CXX flags we're using.

[core] Initialize Xcode project build settings

---

Makefile

This PR introduces a new make target that wraps checkstyle and lint. This allows to execute one make target instead of 3 before pushing a PR to this repo. I verified that if one target fails, it stops execution of the other targets.

make android-check

---

platform/android/README.md

This PR adds 2 sections to the project `README.md`:
- section on setting up checkstyle 
- section on resolving native crashes on ndk-stack
for both I'm linking the relevant wiki page.
All remaining actions for #8390 have been performed, closes #8390.

Update readme with checkstyle and ndk-stack

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java

closes #9687, this PR makes sure that the LatLngBounds returned by VisibleRegion complies to:
```
The smallest bounding box that includes the visible region defined in this class.
```
To make this possible I had to introduce `LatLngBounds.from`, this method was required to bypass bounds recalculation used in normal circumstances. This method also allows end developers to overwrite default LatLngBounds behaviour.
Adding this to the 5.1.3 milestone as implementation wasn't complying to the javadoc. 
cc @zugaldia

Smallest LatLngBounds when visible region crosses dateline

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MarkerContainer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/PolygonContainer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/PolylineContainer.java

Avoid IndexOutOfBoundsException when destroying map object

---

platform/darwin/src/MGLSource.mm
platform/darwin/src/MGLSource_Private.h
platform/darwin/src/MGLStyle.mm
platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

[ios, macos] Fix querying features returning nil when features available.

---

include/mbgl/util/constants.hpp
src/mbgl/programs/attributes.hpp
src/mbgl/programs/line_program.cpp
src/mbgl/programs/line_program.hpp
src/mbgl/renderer/line_bucket.cpp
src/mbgl/shaders/line.cpp
src/mbgl/shaders/line_pattern.cpp
src/mbgl/shaders/line_sdf.cpp

Selective cherry pick of 822df3dd514ec3d05f876e6746cb8ba6348ac89d, to fix #7583 for 5.1.3.

[core] Use separate attribute component for line normals

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/ImageTest.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

Style image accessor

---

platform/glfw/main.cpp

Since we don't have any options with non-null flags we don't need to
handle the case where getopt_long returns 0.
The case that handled 0 was susceptible to switch fall-through and made
the code not compile with -Werror=implicit-fallthrough=.

[glfw] Getopt: Don't handle 0 value

---

platform/node/test/ignores.json
src/mbgl/text/glyph.hpp
src/mbgl/text/quads.cpp
src/mbgl/text/shaping.cpp
test/text/quads.test.cpp

Fixes issue #9768.
Port of GL JS PR https://github.com/mapbox/mapbox-gl-js/pull/5100.
Submodule points to the GL JS PR right now, after merging I'll update it to point to master.
/cc @1ec5

[core] Correct x-offset introduced by vertical glyph rotation

---

platform/android/README.md
platform/android/tests/docs/UI_TESTS.md
platform/android/tests/docs/UNIT_TESTS.md

I noticed that the build badge on the Android README file was outdated. I took the opportunity to update a couple more things.

Update docs replacing Bitrise mentions with CircleCI

---

platform/ios/src/MGLMapView.h

Addresses this @1ec5 comment from https://github.com/mapbox/mapbox-gl-native/pull/9540#pullrequestreview-50879870:
> We should definitely warn in the feature querying documentation that those methods may return annotations as features – the other way around – but those annotations-as-features aren’t object-equal to the ones that were added to the map. So we should recommend against using feature querying to get annotations.
Also reorders `visibleAnnotations` to be immediately above `visibleAnnotationsInRect:`.

[ios] Document annotations-as-features limitations w/feature querying

---

include/mbgl/util/constants.hpp
include/mbgl/util/tileset.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/macos/src/MGLMapView.h
src/mbgl/annotation/render_annotation_source.cpp
src/mbgl/map/transform_state.hpp

Closes #8318.
Now that #7155 has been addressed, this change can go in with the caveat that we still have a related open issue: #9820

Set Default MaxZoom to 22

---

platform/android/CHANGELOG.md
platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/macos/CHANGELOG.md
platform/node/CHANGELOG.md

Update iOS documentation and use DEFAULT_MAX_ZOOM constant. 
+CHANGELOGs

Default max zoom 22

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Fixes #9822, significantly reducing CPU usage during user heading tracking mode.
In #7716, we started calling `layoutSubviews` more often. If the compass were visible, this would then call `updateHeadingForDeviceOrientation`, which would set `CLLocationManager.headingOrientation`.
Even if there is no actual change in its value, setting `CLLocationManager.headingOrientation` triggers a new heading update, which in turn caused us to update the user location annotation and `layoutSubviews` again. This effectively disabled the heading filter and would continue until heading tracking mode was disabled.
/cc @frederoni @fabian-guerra @1ec5

[ios] Fix heading update loop

---

platform/node/test/ignores.json
src/mbgl/renderer/image_manager.cpp
src/mbgl/renderer/image_manager.hpp
src/mbgl/style/image_impl.hpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/geometry_tile_worker.cpp
src/mbgl/tile/geometry_tile_worker.hpp
test/renderer/image_manager.test.cpp

This PR:
- reverts the `GeometryTilerWorker` change from #9739, and:
- Modifies the logic from `ImageManager` to notify its requestors only when all image dependencies are met.
This causes `API.RecycleMapUpdateImages` to pass without cd8eb13ba2d8b65f6cac12a36e0586abc56fcb9f.

Ensure GeometryTile::pending state is only false in the last placement attempt

---

platform/default/default_file_source.cpp

Sometimes, initialization can take hundreds of milliseconds, in particular when the database doesn't exist yet, or when the app/device is doing a lot of I/O already. Instead of synchronously initializing the OfflineDatabase objects, we're now asynchronously initializing the object through a self-sent message that by virtue of being the first message for this actor guarantees that the object is there when it's needed by other member functions.
For completely fresh app start with no previous database, I'm seeing the synchronous initialization time go down from ~200ms to ~1ms. Of course, the work still needs to happen, but instead it'll only block the `DefaultFileSource::Impl` thread rather than the main thread that initializes the `DefaultFileSource`.
General longer term fix is tracked in …

[core] initialize OfflineDatabase asynchronously in DefaultFileSource

---

CMakeLists.txt
platform/ios/scripts/package.sh
src/mbgl/annotation/symbol_annotation_impl.hpp
src/mbgl/text/collision_tile.hpp

Cherry-picks #9463 to the release branch, so that we can compile with Xcode 9.
Also adds a simple echo of the current Xcode version to the packaging script, so we can double-check that we’re on the expected version.
/cc @fabian-guerra @kkaefer

Cherry-pick: Disable GCC-only warnings in Clang

---

platform/ios/CHANGELOG.md
platform/ios/app/Info.plist
platform/ios/src/MGLMapView.mm

Adds support for iOS 11’s `NSLocationAlwaysAndWhenInUseUsageDescription` key and new location permission behavior. Our SDK’s behavior remains unchanged in older iOS versions.
In apps compiled with the iOS 11 SDK:
- `NSLocationAlwaysUsageDescription` is ignored.
- `NSLocationWhenInUseUsageDescription` is required, even if `NSLocationAlwaysAndWhenInUseUsageDescription` is set.
If an app can ask for `always`, we do that. This may not be desirable for some use cases, in which case the developer should request location authorization themselves before enabling any Mapbox features that require it.
[Here’s a nice writeup of the iOS 11 changes generally.](https://mackuba.eu/2017/07/13/changes-to-location-tracking-in-ios-11/)
/cc @boundsj @1ec5 @fabian-guerra

[ios] Support iOS 11 location usage descriptions

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLUserLocation.h
platform/ios/src/MGLUserLocation.m

The documentation for the `location` property states that "This property contains `nil` if the map view is not currently showing the user location or if the user’s location has not yet been determined." The iOS SDK presently returns a garbage value, which has some rather annoying consequences when the value should logically be nullable. This change should rectify the issue.

[ios] Set location to nil until the user's location is determined

---

Makefile
benchmark/function/camera_function.benchmark.cpp
benchmark/function/composite_function.benchmark.cpp
benchmark/function/source_function.benchmark.cpp
benchmark/src/mbgl/benchmark/stub_geometry_tile_feature.hpp
cmake/benchmark-files.cmake
platform/linux/config.cmake
platform/macos/config.cmake

Benchmarks for "parsing" (converting from JSON) and evaluating each type of DDS function.  
Example results:
```
---------------------------------------------------------------------
Benchmark                              Time           CPU Iterations
---------------------------------------------------------------------
Parse_CameraFunction/1              5912 ns       5884 ns     118763 1
Parse_CameraFunction/2              7563 ns       7526 ns     100021 2
Parse_CameraFunction/4             10579 ns      10568 ns      65460 4
Parse_CameraFunction/6             14101 ns      14078 ns      46792 6
Parse_CameraFunction/8             18148 ns      18129 ns      38659 8
Parse_CameraFunction/10            21299 ns      21260 ns      32044 10
Parse_CameraFunction/12            25631 ns …
```

Add benchmarks for parsing and evaluating style functions

---

src/mbgl/renderer/sources/render_geojson_source.cpp

In some circumstances, two different objects might get the same memory address if the former has been deleted before the latter gets constructed. Thus, we cannot rely solely on pointer comparsion when checking whether to update the tile data in `RenderGeoJSONSource::tylePiramid`.
Fixes #9868.

Clear RenderGeoJSONSource tilePyramid if no data is available

---

src/mbgl/style/style_impl.cpp

Move last bits of core changes from https://github.com/mapbox/mapbox-gl-native/pull/9689 into a separate PR.
Two important changes included:
1) When parsing a style, there are lots of intermediary `onUpdate` calls triggered e.g. when adding a source and/or layer that could be safely avoided.
2) In still mode, we don't need to run intermediary render calls while the style is incomplete (loading). This also saves a lot of time, reducing the amount of render calls to ~1 in most cases.

Still mode optimizations

---

platform/node/test/ignores.json

Updates gl-js to https://github.com/mapbox/mapbox-gl-js/pull/5101 and ignores that test, pending https://github.com/mapbox/mapbox-gl-native/issues/9894.

Update gl-js SHA + ignore fill-extrusion-multiple test

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.h

Fixes https://github.com/mapbox/mapbox-gl-native/issues/9475

[ios, macos] Make minimumZoomLevel and maximumZoomLevel IBInspectable.

---

platform/ios/src/MGLMapView.mm

Follows up on #9639, which leaves `MGLUserLocation.location` as `nil` until it’s initialized with a real value.
After that change, if a developer set the tracking mode to `MGLUserTrackingModeFollowWithHeading` while `location` was `nil`, an exception for trying to insert `nil` into an array was thrown.
/cc @1ec5 @fabian-guerra

[ios] Guard against nil user location when setting tracking mode

---

Makefile

- Makes the `android-release-all` build batched
👀 @ivovandongen @brunoabinader @tmpsantos

[android] Make the android release all build batched

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegionStatus.java

Fixes #9908 
- ~~Prevents calling `observer->statusChanged(status);` when the download is deactivated which caused two calls to [`onStatusChanged`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java#L258) making [`status.isComplete()`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java#L264) `true` twice as well.~~
- Fixes `OfflineRegionStatus#isComplete`:
- A download is complete when `completedResourceCount` and `requiredResourceCount` match and the `downloadState` is `OfflineRegion.STATE_INACTIVE` which prevents reporting _is …

[android] Fix is download complete

---

src/mbgl/programs/attributes.hpp
src/mbgl/programs/line_program.cpp
src/mbgl/programs/line_program.hpp
src/mbgl/shaders/line.cpp
src/mbgl/shaders/line_pattern.cpp
src/mbgl/shaders/line_sdf.cpp

10 byte vertices are heavily penalized by common GL implementations.
Fixes #9912

[core] Align line vertex to 4-byte boundary

---

include/mbgl/storage/offline.hpp
include/mbgl/util/projection.hpp
platform/default/mbgl/storage/offline.cpp
platform/default/mbgl/storage/offline_download.cpp
src/mbgl/util/tile_cover.cpp
src/mbgl/util/tile_cover.hpp
test/storage/offline.test.cpp
test/util/tile_cover.test.cpp

Closes #9675 
Implement a separate `util::tileCount()` method for computing the number of tiles that need to be downloaded for offline packs.
The time for computing tile count for a bounding box around SF went from *12070 ms* to *1 ms*. 
The failed attempts include: 
* Running `tileCover` on the max zoom, and getting parents of those tiles up to min zoom. I was surprised by the cost of `boost::hash_combine` which made this more expensive than running `tileCover` for every zoom level.
* Computing the number of tiles needed at each zoom level based on `LatLng` extents of the bounding box vs `LatLng` extents of a tile. This approached had way better performance but suffered from floating point errors due to the precision of `LatLng` for high zoom levels. 
Thanks to @jfirebaugh for pointing …

[core] Fast tileCount with help from @mapbox/sphericalmercator module

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QueryRenderedFeaturesBoxHighlightActivity.java

Fixes a crash due to the fact that sources can no longer be removed when in use and this example tries to add a duplicate source right after.

Test app - fix highlight buildings example

---

src/mbgl/gl/context.cpp
src/mbgl/gl/context.hpp
src/mbgl/gl/value.cpp
src/mbgl/gl/value.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/util/offscreen_texture.cpp

When a texture is deleted, it is as if all texture units to which that texture object is bound are rebound to texture object zero. Therefore it's the _bindings_ that need to be dirtied, not the active texture unit.
To reduce the chances of this sort of mistake happening again, rename ActiveTexture → ActiveTextureUnit for clarity.

[core] Dirty the correct state when a texture is deleted

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Follow up from external PR in https://github.com/mapbox/mapbox-gl-native/pull/9874 to allow CI to execute. 
cc @robindarby

Clear out mapCallback's OnMapReadyCallbacks on onDestroy

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java

closes #9953, this PR validates if a point added to the LatLngBounds builder hasn't been added before. Atm a developer can create a bounds from one point by passing in the same point twice.

avoid adding duplicate points to bounds

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/app/Main.storyboard
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLFaux3DUserLocationAnnotationView.h
platform/ios/src/MGLFaux3DUserLocationAnnotationView.m
platform/ios/src/MGLMapView+IBAdditions.h
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLUserLocationHeadingArrowLayer.h
platform/ios/src/MGLUserLocationHeadingArrowLayer.m
platform/ios/src/MGLUserLocationHeadingBeamLayer.h
platform/ios/src/MGLUserLocationHeadingBeamLayer.m
platform/ios/src/MGLUserLocationHeadingIndicator.h

This is an WIP towards fixing #5523, adding a permanent user heading indicator (visible outside of heading tracking mode) and refactoring the user location annotation a bit.
/cc @1ec5 @fabian-guerra @jmkiley

[ios] Add permanent user heading indicator

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/IconManager.java

Closes #9936, regression from https://github.com/mapbox/mapbox-gl-native/pull/9643. 
In the mentioned PR, I assumed it was save to recycle bitmaps when no longer in use but since the android resources system caches resources, we aren't allowed to make that assumption. From this PR forward it will be the end-users responsibility to recycle bitmaps if they want to free memory.

Don't recycle bitmap for icon reuse.

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

This adds entries for work done on the master branch since v3.6.0 of our iOS Maps SDK that was not included in any of the 3.6.x patch releases.

Update iOS and macOS changelogs

---

platform/ios/src/MGLMapView.mm

I set `accessibilityIgnoresInvertColors` for the views so that they can be overridden as needed.
Addresses https://github.com/mapbox/mapbox-gl-native/issues/9859
cc @friedbunny

[ios] Ignore Smart Invert

---

include/mbgl/util/image.hpp
platform/node/test/ignores.json
src/mbgl/renderer/image_manager.cpp

Recreating the `atlasImage` object ensures no pattern leftovers are redrawn.
Fixes #9976.
Depends on https://github.com/mapbox/mapbox-gl-js/pull/5281.
(If #9905 is merged first, then the entry in ```ignores.json``` can be removed).

[core] Clear atlasImage rect for a removed pattern

---

platform/node/test/render.test.js

Removes duplicated code in GL Native that handles process arguments for ```render.test.js```.
Depends on https://github.com/mapbox/mapbox-gl-js/pull/5280.

[node] Reflect GL JS changes in render.test.js

---

platform/node/test/ignores.json
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/renderer/tile_pyramid.hpp

Imagine the following scenario:
1. A map is created with a given vector source `source`, layer `foo` and LatLngZoom position **1**.
Render occurs: A render tile for the tile coordinate corresponding to position 1 is created, passing layer `foo` via [tile.setLayers](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/tile_pyramid.cpp#L143).
2. The map now goes to position **2**, far enough to be outside of the render source's tile pyramid. Also, a new layer `bar` is added to the style.
Render occurs: A render tile for the tile coordinate corresponding to position **2** is created.
3. The map now goes back to position **1**.
Render occurs: The previously cached/retained render tile generated for position **1** is reused, and no relayout is made because there were …

[core] Relayout tiles cherry-picked from the cache

---

platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/build.gradle
platform/android/dependencies.gradle

This PR bumps the external dependencies used in the Android project to the latest stable version.

Bump external dependencies

---

platform/android/MapboxGLAndroidSDK/proguard-rules.pro

This PR solves the issue locally by applying the fixes from https://github.com/square/okhttp/pull/3354. I'm targetting the release branch directly as master will be upgraded to OkHttp 3.9.0 (which includes upstream PR mentioned above).

Bump proguard config for OkHttp 3.8.0

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java

Closes #9858, this PR hardens disallowing calling delete twice. 
Note that this is a workaround untill https://github.com/mapbox/mapbox-gl-native/issues/8917 is resolved.

Harden offline region deletion

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java

Follow up from external PR in #9862 to allow CI to execute.
cc @rjuszczyk

Do not check connection if local request

---

.tx/config

A bogus source file path added in #9945 was causing contention between two resources. As a consequence, Transifex spammed the project’s watchers daily about changes that didn’t occur.

Can spam coming from Transifex

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_debug_mode.xml

Inspired by the side view in the macOS test app, this PR adds showing a list of loaded layers to the debug activity. This allows to "debug" a style by toggling the visibility of them.

Add style inspection to debug activity

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/ZoomFunctionSymbolLayerActivity.java

refs #9975, this PR updates our existing SymbolLayer example that changes the iconImage with a zoom function with the ability of having a selected state when clicked (this will grow the icon size).

Update zoom function example with selected state

---

README.md

Updated the readme to acknowledge Mapbox’s official support for React Native. For context, we originally held off from making this claim in #6696 because RNMBGL wasn’t officially supported. However, as of mapbox/react-native-mapbox-gl#618, we’re going to develop the project as an official Mapbox product.
/cc @nitaliano @bsudekum

Mapbox develops React Native Mapbox GL

---

platform/ios/src/MGLMapView.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/9941
This essentially reverts https://github.com/mapbox/mapbox-gl-native/pull/7716 in favor of a constraint system for laying out MGLMapViews's ornamental views that is very similar to the one originally implemented in https://github.com/mapbox/mapbox-gl-native/pull/1328 that fixed https://github.com/mapbox/mapbox-gl-native/issues/1327
It attempts to mix in the things we learned along the way in:
https://github.com/mapbox/mapbox-gl-native/issues/3697
https://github.com/mapbox/mapbox-gl-native/pull/6776
https://github.com/mapbox/mapbox-gl-native/issues/6954
https://github.com/mapbox/mapbox-gl-native/pull/7084
This includes respecting content insets when the constraints are created.
While I was there, I went ahead and added …

Revert KVO triggered manual layout of map ornaments 

---

src/mbgl/map/zoom_history.hpp
src/mbgl/renderer/renderer_impl.cpp
test/api/zoom_history.cpp

```
$ node platform/node/test/render.test.js --recycle-map \
"line-dasharray/slant" \
"line-dasharray/literal--line-width-composite-function"
* passed line-dasharray slant
* failed line-dasharray literal--line-width-composite-function
1 passed (50.0%)
1 failed (50.0%)
```
| expected | actual | diff |
| -- | -- | -- |
| ![expected](https://user-images.githubusercontent.com/76133/29885386-441976aa-8dbf-11e7-96cf-3fb2bb6b6999.png) | ![actual](https://user-images.githubusercontent.com/76133/29885388-491ed74e-8dbf-11e7-8533-f469bcd97fa8.png) | ![diff](https://user-images.githubusercontent.com/76133/29885396-500b38fe-8dbf-11e7-911a-fe9b160a92a4.png) |
This is an edge case from the issue reported in https://github.com/mapbox/mapbox-gl-native/pull/9760. When switching from a higher zoom level to …

[core] Reset zoom history state in still mode

---

platform/darwin/src/MGLStyle.h
platform/darwin/src/MGLStyle.mm
platform/darwin/test/MGLStyleTests.mm
platform/default/mbgl/util/default_styles.hpp
platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/macos/CHANGELOG.md
platform/macos/app/MapDocument.m

Deprecates styles according to the latest spec.

[ios, macos] Deprecate trafficDayStyleURL and trafficNightStyleURL

---

platform/node/src/node_map.cpp
platform/node/src/node_map.hpp
platform/node/test/js/map.test.js
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp
src/mbgl/renderer/sources/render_geojson_source.cpp

Scale retained tile IDs to either the transform zoom or maximum zoom allowed by GeoJSON-VT if the current tile ID zoom is higher than the maximum zoom allowed by GeoJSON-VT when updating GeoJSON render sources.
This avoids situations where e.g. an updated GeoJSON source, which now has a maxZoom set to 16, calls for obtaining tiles from its GeoJSON-VT counterpart using the previous zoom level 18: it causes GeoJSON-VT to [throw](https://github.com/mapbox/geojson-vt-cpp/blob/master/include/mapbox/geojsonvt.hpp#L89).
Also adds `removeSource` as part of our Node bindings - used by the added integration test ```regressions/mapbox-gl-native#9979``` to verify.
Depends on https://github.com/mapbox/mapbox-gl-js/pull/5291.
Fixes #9979.

[core] Bypass GeoJSON tile data update if tileID zoom is above source's maxZoom

---

platform/ios/src/MGLMapView.mm

Otherwise it errors with, `cannot initialize a variable of type 'BOOL' (aka 'signed char') with an rvalue of type 'id _Nullable’`.
This change doesn't seem like it should be necessary and, indeed, this error is intermittent and only appears on Release builds. Potentially related to trying to use Xcode 8 after Xcode 9 has futzed with the system or project? 😬
This should have started happening immediately after #9869, but it only really reared its head today.
/cc @fabian-guerra @1ec5

[ios] Explicitly return a BOOL value for nullable dict keys

---

src/mbgl/text/placement_config.hpp

Fixes issue #9996 
Port of GL-JS https://github.com/mapbox/mapbox-gl-js/pull/5284
This PR changes the "redo placement" logic to avoid triggering placement when the zoom level changes but (1) the pitch is relatively low (under 25 degrees), and (2) other transform parameters are unchanged.
/cc @jfirebaugh @ansis

[core] Don't redo placement for zoom changes at low pitch.

---

Makefile

Ensures targets run whether the app was installed before on the device or not when running commands like `make run-android-arm-v7`

Ignore failed uninstalls

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java

- Fixes #9998 
- Hooks camera events into `CompassView`
- Moves `CompassView` `OnClickListener` into `MapView`
👀 @tobrun

[android] Hook camera events into compass

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java

Follow up from #9748, noticed that we weren't setting ErrorHandler as part of `MapSnapshotter#start`. Which resulted in not invoking the error handler when an error occurred.  Additionally removed the obsolete static keyword on the interface definition of ErrorHandler.

Set error handler when starting snapshotter

---

src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/geometry_tile_worker.cpp
src/mbgl/tile/raster_tile.cpp
src/mbgl/tile/raster_tile.hpp
src/mbgl/tile/raster_tile_worker.cpp
src/mbgl/tile/raster_tile_worker.hpp
test/tile/annotation_tile.test.cpp
test/tile/geojson_tile.test.cpp
test/tile/raster_tile.test.cpp
test/tile/vector_tile.test.cpp

Since 9a9408e8111bcdcd0fcb9a93112d61ab8fce0601, we marked tiles as non-renderable if an error occured. This lead to situations where a tile was loaded + parsed successfully, then a revalidation attempt occured (e.g. because the resource was stale) which failed. In this case, we used to mark the tile as non-renderable although we could've used the perfectly parsed (stale) resource.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/9563 and https://github.com/mapbox/mapbox-gl-native/issues/9705
This needs porting to our release branch.

Continue rendering tile despite errors

---

src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/geometry_tile_worker.cpp
src/mbgl/tile/raster_tile.cpp
src/mbgl/tile/raster_tile.hpp
src/mbgl/tile/raster_tile_worker.cpp
src/mbgl/tile/raster_tile_worker.hpp
test/tile/annotation_tile.test.cpp
test/tile/geojson_tile.test.cpp
test/tile/raster_tile.test.cpp
test/tile/vector_tile.test.cpp

port of https://github.com/mapbox/mapbox-gl-native/pull/10011 to the release branch.

[release branch] Continue rendering tile despite errors

---

platform/glfw/main.cpp

I'm frequently trying to use this to load specific styles, but it breaks when unconditionally prefixed with `asset://`.

[glfw] allow loading mapbox:// style URLs via CLI

---

include/mbgl/renderer/renderer_backend.hpp
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp
platform/default/mbgl/gl/headless_backend.cpp
platform/default/mbgl/gl/headless_backend.hpp
platform/glfw/glfw_view.hpp
platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm
platform/node/test/ignores.json
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_p.hpp
src/mbgl/gl/context.cpp
src/mbgl/gl/context.hpp
src/mbgl/gl/renderbuffer.hpp
src/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
src/mbgl/renderer/layers/render_fill_extrusion_layer.hpp
src/mbgl/renderer/paint_parameters.cpp
src/mbgl/renderer/paint_parameters.hpp
src/mbgl/renderer/render_pass.hpp
src/mbgl/renderer/render_static_data.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/util/offscreen_texture.cpp
src/mbgl/util/offscreen_texture.hpp
test/renderer/backend_scope.test.cpp

Port of https://github.com/mapbox/mapbox-gl-js/pull/5101: 
* Optimizes render order by rendering all fill-extrusion textures first, so that we don't have to restore any framebuffer contents (fixes #9286)
* Preserves depth buffer contents between different fill-extrusion layers in the same render pass so that multiple fill-extrusion layers can be rendered on the same map (ref https://github.com/mapbox/mapbox-gl-js/issues/4134)
Also fixes https://github.com/mapbox/mapbox-gl-native/issues/9978 (I think)…

Preserve depth buffer between 3D layers + optimize render order

---

Makefile

Enables shuffling render tests when recycling the map object.
I've let it running continuously throughout the last weekend using the following command without any additional issues found:
```
$ true; while [ $? -eq 0 ]; do node platform/node/test/render.test.js --recycle-map --shuffle; done
```
So far we've solved all of the bugs (and bugfixes) found while running this technique. https://github.com/mapbox/mapbox-gl-native/issues/9978 is the last one open, which is fixed in https://github.com/mapbox/mapbox-gl-native/pull/9931.
Depends on: https://github.com/mapbox/mapbox-gl-native/pull/9931.

[build] Shuffle render tests in 'test-node-recycle-map' target

---

include/mbgl/storage/default_file_source.hpp
include/mbgl/storage/online_file_source.hpp
platform/default/default_file_source.cpp
platform/default/online_file_source.cpp
platform/glfw/glfw_view.cpp
platform/glfw/glfw_view.hpp
platform/glfw/main.cpp
platform/glfw/settings_json.cpp
platform/glfw/settings_json.hpp

During testing of https://github.com/mapbox/mapbox-gl-native/pull/10011, I heavily used this modification to the `OnlineFileSource` and GLFW, which made testing offline behavior much easier since I didn't have to toggle wifi, or use tools like Little Snitch to block application connectivity.

[test/glfw] Add ability to take application offline

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/almeros/android/multitouch/gesturedetectors/TwoFingerGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

This PR reworks our rotation gesture handling to not execute when pinch zooming is occurring. 
This UX matches what other map applications are doing atm.

Disable rotation gesture when pinch zooming

---

circle.yml

This PR changes CircleCI to use the [resource class](https://circleci.com/docs/2.0/configuration-reference/#resource_class) configuration. This change was suggested by Circle-CI support to work around the out of memory issues we have been seeing. For now I have configured the android jobs to use the large value (8 GB) instead of the default medium (4 GB).
cc @brunoabinader

Use resource_class large on Circle-CI 

---

platform/default/default_file_source.cpp
src/mbgl/tile/tile_loader_impl.hpp
test/storage/default_file_source.test.cpp

In https://github.com/mapbox/mapbox-gl-native/pull/9670, we implemented support for the `Cache-Control: must-revalidate` header. While we now respect this header and don't show resources that are stale and have this header set, the **optional** cache request never completes. This means we're also never going to try to actually get a fresh tile and just never show this tile anymore.
This commit fixes this by responding with a Not Found error when the resource is unusable (= stale and has must-revalidate set). Since we actually still have the data (but can't use it due to caching rules), we're responding with the data as well. To avoid a second cache hit, `tile_loader_impl.hpp` now passes on the data from the Optional to the Required request so that it can be reused when we get a 304 Not …

[core] fix loading of stale must-revalidate resources

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec

Podspec bump to v3.6.4 and changelog entry.

[ios] Bump podspec to 3.6.4

---

platform/macos/CHANGELOG.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec

Updated the macOS SDK changelog to match iOS SDK v3.6.4 changelog and prepared the macOS SDK podspecs for v0.5.1.

macOS SDK v0.5.1

---

platform/android/CHANGELOG.md

This PR updates the changelog with items that are going to be included in the 5.1.4 release. From this release forward, updating the changelog will be done targeting master and afterwards will be cherry-picked to the release branch. Reasoning is that we had some complaints about not having the document on master reflecting the latest state.

Changelog for 5.1.4 release.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraAnimatorActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/drawable/ic_play_arrow_black_24dp.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_camera_animator.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml

Closes #8175, Refs #9808, this PR adds a simple camera API on MapboxMap that can be used in combination with Android SDK animators to perform animations as shown in https://github.com/mapbox/mapbox-gl-native/issues/9808#issuecomment-324274671.

API for platform side animations

---

circle.yml
platform/android/MapboxGLAndroidSDK/gradle.properties

This PR enables building snapshots again for the 5.2.0 release.
Closes #9852

Add beta to snapshot version

---

platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml

This PR fixes the issue that you can see the logo & attribution icon initialized in the top left corner and afterwards seeing it move to the expected location. Hiding these views on initialization solves the issue. 
See difference in gifs below:
After:
Before:

Hide overlain views on initalisation

---

cmake/core-files.cmake
include/mbgl/tile/tile_id.hpp
src/mbgl/tile/tile_id_hash.cpp

Promoting the *`TileID` classes to a public header in core, and moving the hashing functions to a separate private header.

[core] Move *TileID hashing to separate header

---

platform/ios/DEVELOPING.md
platform/ios/bitrise.yml

ios-sim is not being used anymore.
@friedbunny @fabian-guerra

Remove ios-sim

---

platform/ios/src/MGLFaux3DUserLocationAnnotationView.h
platform/ios/src/MGLFaux3DUserLocationAnnotationView.m

#9886 moved these constant declarations to a header file, but they should’ve been `extern`ed and defined in the original implementation file. Otherwise, the linker could end up seeing duplicate symbols. I’m not sure why this hasn’t been failing the iOS builds, but it ended up failing tvOS builds in #9319 when I tried to include this header in the tvOS SDK.

Define user dot constants in implementation file

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineTilePyramidRegionDefinition.java

Closes #9872, this PR makes OfflineTilePyramidRegionDefinition parceable. This allows the class to be used as part of intent communication. I'm needing this feature downstream in the [offline plugin](https://github.com/mapbox/mapbox-plugins-android/pull/72) where I need to pass this information to a service.

Make OfflineTilePyramidRegionDefinition parceable

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Fixes #9455 by no longer disabling user tracking when selecting an annotation. This supersedes #9663.
/cc @1ec5 @fabian-guerra @boundsj

[ios] Don't disable user tracking when selecting an annotation

---

circle.yml

Ref: https://discuss.circleci.com/t/use-the-arch-cache-template-key-if-you-rely-on-cached-compiled-binary-dependencies/16129

[build] Use the 'arch' cache template key

---

platform/macos/app/Base.lproj/MainMenu.xib
platform/macos/app/MapDocument.m

I finally found a reliable way to convert from file extensions to UTIs to `NSBitmapImageFileType`s. This change allows files to be saved in any of the supported bitmap image formats, not only TIFF.
The save panel starts out with the name of the style as the file name. It restricts the allowed file types, so that if you enter an extension of .pdf, you’re prompted to add .png to the file name. Finally, the menu item has been renamed to Export Image, which is more consistent with other Mac applications.
/cc @fabian-guerra @ivovandongen

Save snapshots in correct format

---

platform/ios/framework/Settings.bundle/zh-Hant.lproj/Root.strings

Updated the Traditional Chinese translation of Mapbox Telemetry strings in the iOS SDK’s provided Settings bundle based on Transifex.
/cc @lily-chai @friedbunny

Update Traditional Chinese localization

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm

Fixes #9024 by exposing `-[MGLMapView showAttribution]` as an `IBAction`.
Also removes the deprecated/non-functional style class methods (#8953) from jazzy docs.
- Maybe `-showAttribution` should be split out of the “Configuring the Map’s Appearance” category.
- Is this enough detail or should it explain more what attribution/telemetry is?
/cc @1ec5 @fabian-guerra

[ios] Expose -showAttribution publicly as an IBAction

---

platform/darwin/src/NSString+MGLAdditions.m
platform/darwin/test/MGLNSStringAdditionsTests.m
platform/darwin/test/MGLSDKTestHelpers.swift
platform/darwin/test/MGLStyleValueTests.swift
platform/ios/DEVELOPING.md
platform/ios/bitrise.yml

Fixes compilation for Xcode 9
- Replaced deprecated method
- Obj-C method description name is optional in Swift as of Xcode 9.
- Stricter indirect values (Color.getRed:green:blue)
@kkaefer @boundsj 👀

[ios] Various Xcode 9 fixes

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/ZoomFunctionSymbolLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_symbols.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/actions.xml

This PR updates our SymbolLayer example with updating the symbol location.

Update symbol layer example with location

---

platform/darwin/src/MGLMapSnapshotter.h
platform/darwin/src/MGLMapSnapshotter.mm
platform/darwin/src/MGLTypes.h
platform/ios/app/MBXSnapshotsViewController.m
platform/ios/src/UIImage+MGLAdditions.h
platform/ios/src/UIImage+MGLAdditions.mm
platform/macos/app/Base.lproj/MainMenu.xib
platform/macos/app/MapDocument.m

Fixes https://github.com/mapbox/mapbox-gl-native/issues/9920

[ios, macos] Improve snap shotter documentation.

---

cmake/core-files.cmake
src/mbgl/layout/symbol_instance.cpp
src/mbgl/layout/symbol_instance.hpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/style/style_impl.hpp
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/cross_tile_symbol_index.hpp

This ports `SymbolOpacityIndex` from -js.
It compiles but hasn't been tested. @ChrisLoer

add SymbolOpacityIndex

---

cmake/core-files.cmake
src/mbgl/renderer/placement_state.cpp
src/mbgl/renderer/placement_state.hpp
src/mbgl/renderer/render_layer.hpp
src/mbgl/tile/tile.hpp

This ports the basic structure of `placement.js` to a `PlacementState` class, intended for use by the renderer. The renderer will be responsible for regenerating the `PlacementState` whenever the order changes. There's a design smell there -- maybe this could be changed so that `PlacementState` keeps track of order diffing itself so that there's less risk of invalid indices?
This compiles, but other than that there's no testing. It uses placeholder interfaces for `CollisionIndex` as well as new `placeLayer` and `commitPlacement` methods on `Tile`.
/cc @ansis

Initial implementation of "PlacementState"

---

platform/darwin/src/MGLMapSnapshotter.mm

Fixes #10089
Fixes the scale of the snapshot on iOS by letting CGImage resize the output.
~~Snapshotting on macOS already works as intended.~~
@1ec5 👀 
@fabian-guerra feel free to cherry-pick this into https://github.com/mapbox/mapbox-gl-native/pull/10020

[ios, macos] Fix snapshot scale

---

circle.yml

Now that we have a `release-agua` branch for the upcoming mobile SDK releases, we should start building the Android snapshots from this branch (when a PR is merged to the branch).

Build nightly builds from release-agua

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcher.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcherTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java

Closes #9917. This PR solves the issue that multiple plugins could register for camera change events without blocking the end user to register for these events.

Allow multiple listeners for camera events, deprecate old API

---

platform/darwin/src/MGLImageSource.h

I added a code snippet that shows to use the source to create a style layer. The nature of `MGLImageSource` seems to make the relationship between source and layer a little more confusing, so additional clarification may be necessary.
Addresses https://github.com/mapbox/mapbox-gl-native/issues/10148

[ios, macos] Edited MGLImageSource sample code

---

platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_p.hpp

Adds resource transform API to Qt platform. This PR adds functionality missing on Qt. By providing callback function, user can transform requested URL on Qt platform as well.
This PR fixes https://github.com/mapbox/mapbox-gl-native/issues/10130

[qt] add ResourceTransform API

---

src/mbgl/text/glyph_manager.cpp
src/mbgl/text/glyph_manager.hpp
test/src/mbgl/test/stub_file_source.cpp
test/src/mbgl/test/stub_file_source.hpp
test/text/glyph_loader.test.cpp

If the file source request happens immediately (e.g. when obtaining from a memory cache), then the glyph manager response processing happens _before_ the glyph requestors map gets updated, causing the notification to never happen in such cases.

[core] Update glyph requestors _before_ requesting from file source

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/almeros/android/multitouch/gesturedetectors/TwoFingerGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

follow up from #10026, closes #10102.

Fine tune gesture zoom & rotation

---

include/mbgl/map/map.hpp
include/mbgl/util/geometry.hpp
platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp
platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.h
platform/macos/src/MGLMapView.mm
src/mbgl/map/map.cpp
test/map/map.test.cpp

Closes #9809 
Implement a `Map:: cameraForLatLngs` variant that allows specifying a heading and returns `CameraOptions` with `zoom`, `center`, and `angle`.

[core][macOS] Compute camera center and zoom for geometry with fixed heading

---

include/mbgl/map/map.hpp
include/mbgl/util/geometry.hpp
platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp
platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.h
platform/macos/src/MGLMapView.mm
src/mbgl/map/map.cpp
test/map/map.test.cpp

Cherry pick changes from #10107 for #9809

Cherry pick #10107: Map::cameraForGeometry()

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Noticed that on a Chromebook, there are situations the mouse is hovering while the map isn't created yet.

Hold off handling hover events untill map has been created

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

This PR removes redundant calls to `terminateContext` and `terminateDisplay`. These methods are already called as part of the destructor of map object, we don't need to call them as part of `MapView#onDestroy`. I'm patching this up on the `release-ios-v3.6.0-android-v5.1.0` branch so we can  ship this in a patch release.
cc @brunoabinader

Remove obsolete terminate context/display calls

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/LibraryLoader.java

This PR reverts the changes from https://github.com/mapbox/mapbox-gl-native/pull/10154 while adding an `UnsatisfiedLinkError` safeguard.

[android] Revert native loading behavior

---

.gitmodules
platform/ios/CHANGELOG.md
platform/ios/src/MGLCompactCalloutView.h
platform/ios/src/MGLMapView.mm
platform/ios/vendor/SMCalloutView/SMCalloutView.h
platform/ios/vendor/SMCalloutView/SMCalloutView.m

Fixes #1757 by renaming our copy of `SMCalloutView` to `MGLSMCalloutView` (because we already have `MGLCalloutView`). Switches from using a submodule to directly-committed files.
/cc @1ec5 @boundsj @fabian-guerra

[ios] Rename SMCalloutView and stop using submodule

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraAnimatorActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_camera_animator.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_animator.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/actions.xml

This PR adds a couple of examples around using animators and interpolators. 

Add interpolator examples

---

platform/node/test/ignores.json

render-tests/regressions/mapbox-gl-js#5370 depends on expression syntax.

Add ignore for expression-based regression test

---

Makefile

This PR reintroduces the make target for ndk-stack. I was spending a lot of time looking up the specific command when running into a native crash. This was initially removed with integrating c++ build into android studio. Two targets were added, one abi specific, the other defaults to arm-v7.

add make target for ndk-stack

---

platform/node/test/ignores.json

My bad for not catching this in https://github.com/mapbox/mapbox-gl-native/commit/057cc80fc45758e89bfa08eb1ce0df487dc002a6 🤕 — other ignored render tests with expressions are static styles, so their validation errors are caught in Warning events. This particular regression test uses runtime styling, [so its validation error throws](https://github.com/mapbox/mapbox-gl-native/blob/8bccf657e9cecb58d5b349dac48c0a50db813e91/platform/node/src/node_map.cpp#L746), and the test run quits.

Skip expression-based runtime styling test

---

include/mbgl/map/map.hpp
package.json
platform/glfw/settings_json.hpp
platform/node/src/node_map.cpp
platform/node/src/node_map.hpp
platform/node/test/ignores.json
platform/node/test/js/map.test.js
src/mbgl/map/map.cpp
src/mbgl/map/transform.cpp
src/mbgl/map/transform.hpp
src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp

* Adds support in core for axonometric rendering for 3D layers. New API surface:
* `void Map::setAxonometric(bool)`
* `bool Map::getAxonometric() const`
* `void Map::setXSkew(double)`
* `double Map::getXSkew() const`
* `void Map::setYSkew(double)`
* `double Map::getYSkew() const`
* Adds platform support for axonometric _only for node_ for the time being: this clears the way to use fill-extrusion layers in fallback maps. We may add bindings for other platforms + gl-js later. New node map arguments are
* `axonometric: boolean`
* `skew: [number, number]`
Presently the default for `skew` if `axonometric = true` and `skew` is unspecified is [0, 1]. This is what lower Manhattan looks like with [0, 1]:
[Here](https://www.mapbox.com/bites/00358/#15.95/40.7074/-74.0108) is a quick demo where you …

[core, node] Support axonometric rendering

---

platform/darwin/src/MGLMapSnapshotter.h

Fixed a warning issued by check-public-symbols.js in MGLMapSnapshotOptions due to the `MGL_EXPORT` keyword appearing before the documentation comment. This warning fails `make xdeploy` (but not `make ideploy` because that target doesn’t check for public symbols):
```
* Checking that all public symbols are exported…
- missing symbol export for class MGLMapSnapshotOptions in platform/darwin/src/MGLMapSnapshotter.h:12:12
make[1]: *** [xpackage] Error 1
make: *** [xdeploy] Error 2
```
Also copyedited a couple comments in the same header.
/cc @kkaefer @friedbunny

Fix symbol export warning

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java
platform/android/src/file_source.cpp
platform/android/src/file_source.hpp

closes #9965,
This PR integrates with FileSource pause/resume when the app state changes (foreground vs background). I'm currently looking into counting ongoing filesource interactions for two reasons:
- we need to be able to do offline downloads in the background and don't stop them when the app is backgrounded.
- we need to support showing multiple maps in one Activity/Fragment, we aren't allows to call pause redundantly.

add FileSource pause/resume 

---

src/mbgl/algorithm/generate_clip_ids_impl.hpp
src/mbgl/renderer/render_tile.hpp
src/mbgl/renderer/renderer_impl.cpp
test/algorithm/generate_clip_ids.test.cpp

When generating clip IDs for our stencil buffer based clipping approach, we are currently looking at the *tiles* of a particular source. Instead, we should only consider layers that actually need clipping (lines, fills, extrusions) rather than blindly generating clip IDs for every tile.
An example: A vector tile source is only used in symbol layers (which don't require clipping). Since we're currently generating clip IDs for all tiles in a *geometry source* (but not a raster source), we'd still generate clip IDs for these tiles even though they're never used.

Determine need for clip ID based on actual layers/tiles

---

src/mbgl/storage/resource.cpp
test/storage/resource.test.cpp

Fixes #10201 by correctly parsing the sprite URL, and attaching the query string to the end.
/cc @caneroj1

Correctly alter sprite URLs

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcher.java

This PR is a follow up to #9917, we weren't correctly integrating the new move/idle listeners list as they could be invoked when the state didn't allow this (being idle).

Execute callbacks only when not idle

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

closes #10022 + makes MapZoomButtonListener a static inner class.

Wire up MapZoomButtonController with camera change events

---

platform/darwin/src/NSString+MGLAdditions.m
platform/darwin/test/MGLNSStringAdditionsTests.m
platform/darwin/test/MGLSDKTestHelpers.swift
platform/darwin/test/MGLStyleValueTests.swift
platform/ios/DEVELOPING.md
platform/ios/bitrise.yml

Backports (cherry-picks) #10055 and #10070 to the `release-ios-v3.6.0-android-v5.1.0` branch so that potential patch releases will have passing tests.
/cc @kkaefer @frederoni

[ios] Backport Xcode 9 & build fixes to v3.6.x release branch

---

src/mbgl/storage/resource.cpp
test/storage/resource.test.cpp

Backport https://github.com/mapbox/mapbox-gl-native/pull/10213 to iOS 3.6/Android 5.1.

Backport: Correctly alter sprite URLs

---

include/mbgl/renderer/renderer.hpp
platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm
src/mbgl/annotation/annotation_manager.cpp
src/mbgl/annotation/annotation_manager.hpp
src/mbgl/annotation/shape_annotation_impl.cpp
src/mbgl/renderer/renderer.cpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp

WIP fixes #2082 
I modified the initial implementation from https://github.com/mapbox/mapbox-gl-native/pull/9755 to support callouts and reuse our current API.
Next steps:
This is how it looks.

[ios, macos] Add selection support to MGLMultiPoint annotations.

---

platform/ios/bitrise.yml

Fixes the [broken iOS nightly build on Bitrise](https://www.bitrise.io/build/ef5156406583d122). Companion to #10231 on `release-agua`.
```
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise565838807/step_src/._script_cont: line 2: apt-get: command not found
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise565838807/step_src/._script_cont: line 3: pip: command not found
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Configure AWS-CLI (exit code: 127)
```
/cc @kkaefer

[ios, build] Fix nightly build on bitrise by installing pip

---

platform/ios/bitrise.yml

For whatever reason, Bitrise no longer has pip installed automatically on their macOS stacks, so it has become necessary to do it ourselves. This fixes the tag deployment — I’ll do another PR to fix the nightly on the master branch → https://github.com/mapbox/mapbox-gl-native/pull/10232.
/cc @kkaefer @fabian-guerra

[ios, build] Force Bitrise to install pip for tag-based deployment

---

platform/android/CHANGELOG.md

- Addresses #10239
👀 @tobrun @zugaldia @lilykaiser

Release Android v5.2.0 beta.2

---

platform/darwin/src/MGLGeometry.mm
platform/darwin/src/MGLGeometry_Private.h
platform/ios/CHANGELOG.md
platform/ios/src/MGLFaux3DUserLocationAnnotationView.m
platform/ios/src/MGLMapView.mm
platform/ios/src/MGLScaleBar.mm

Fixes #10119 by rounding view anchor points so that annotation views are not being drawn across pixel boundaries. This change impacts how all view annotations are drawn, including the user location annotation, regular view annotations, and also callout views.
In most cases, the misalignment was being introduced by [`-convertCoordinate:toPointToView:`](https://www.mapbox.com/ios-sdk/api/3.6.4/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)convertCoordinate:toPointToView:), which converts from geographic coordinates to screen points, but with floating point precision. This PR leaves the precision of that method intact, but rounds the returned point value to the nearest pixel before we use it to place the view.
Note that `MGLPointRounded()` will round to pixels and not necessarily points …

[ios] Avoid drawing view annotations across pixel boundaries

---

src/mbgl/annotation/render_annotation_source.cpp

We're currently generating annotation tiles all the way up to z22: https://github.com/mapbox/mapbox-gl-native/blob/2166b8577b4bd2812d504ceb31b6c2af243de8f5/src/mbgl/annotation/render_annotation_source.cpp#L41
In most cases, however, it's unnecessary to regenerate the tiles for higher zoom levels. We should limit the tiles to z16 to match the tile level most vector tilesets use as well.

Limit annotation tiles to z16

---

package.json
platform/node/CHANGELOG.md
platform/node/src/node_map.cpp

Ref: https://github.com/mapbox/mapbox-gl-native/issues/10243
- Fixes an issue that causes memory leaks when not deleting the frontend object in `NodeMap::release()`
- Fixes a crash in Earcut: `mapbox/earcut.hpp#54`

[node] Release v3.5.8

---

src/mbgl/annotation/render_annotation_source.cpp

Backport https://github.com/mapbox/mapbox-gl-native/pull/10197 to Agua.

Backport: limit annotation tile source to z16

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLScaleBar.mm

Fixes #10225 by checking to see if [`UIView.semanticContentAttribute`](https://developer.apple.com/documentation/uikit/uiview/1622461-semanticcontentattribute) is available before using it in `-[MGLScaleBar usesRightToLeftLayout]`. This now falls back to [`UIApplication.userInterfaceLayoutDirection`](https://developer.apple.com/documentation/uikit/uiapplication/1623025-userinterfacelayoutdirection) in iOS 8.
Also fixes an issue in iosapp where `-[UIFont monospacedDigitSystemFontOfSize:weight:]` wasn’t available in iOS 8.
/cc @frederoni @fabian-guerra

 [ios] Fix iOS 8 incompatibility in scale bar RTL check

---

cmake/test-files.cmake
src/mbgl/geometry/feature_index.cpp
src/mbgl/util/grid_index.cpp
src/mbgl/util/grid_index.hpp
test/tile/annotation_tile.test.cpp
test/util/grid_index.test.cpp

`CollisionIndex` is currently using `boost::rtree` in combination with a query refinement to handle circle geometries. This PR ports the circle geometry logic from gl js. Using a dedicated circle/box implementation may yield performance wins -- once we have the collision code running, we can try swapping this out.
/cc @ansis

Port circle grid-index circle support to native

---

src/mbgl/style/style_impl.cpp

Fixes #10160.
I was unable to write a regression test that would have caught this bug -- the render test harness does a number of actions that trigger `onUpdate` and therefore hide the effect of a missed update.

[core] Add layer before notifying observer

---

package.json
src/mbgl/layout/symbol_layout.cpp
src/mbgl/programs/attributes.hpp
src/mbgl/programs/collision_box_program.cpp
src/mbgl/programs/collision_box_program.hpp
src/mbgl/renderer/buckets/symbol_bucket.cpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/renderer/layers/render_symbol_layer.cpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/shaders/collision_box.cpp
src/mbgl/shaders/collision_circle.cpp
src/mbgl/shaders/collision_circle.hpp
src/mbgl/text/placement.cpp

This just gets the collision boxes drawing again. The dynamically updated buffer still isn't all the way hooked up so you can't tell what's being marked collided yet. Nothing for circles yet either.
/cc @ansis

[WIP] Start collision debug boxes

---

Makefile
circle.yml
platform/ios/bitrise.yml
platform/macos/bitrise.yml

Follows up on #8551 & #9051 and adds iOS & macOS tests to CircleCI. A new branch takes about 8-9 minutes to finish running these tests, while a cached build can take 4-5 minutes. ~This does not yet replace Bitrise and these builds will not be marked `required`~, but that’s the end goal after some period of validation.
Adds ~three~ four builds, currently all using Xcode 9.0.x and iOS 11.x/macOS 10.13.x:
- `ios-debug`: Debug build that runs unit tests on a single iPhone 7 simulator. Replaces the [Bitrise iOS build](https://www.bitrise.io/app/7514e4cf3da2cc57#/builds).
- `ios-sanitize-address`: Same, but with the [address sanitizer](https://developer.apple.com/documentation/code_diagnostics/address_sanitizer) enabled. Fairly slow and [currently times out a few …

[ios, macos, build] Add CircleCI iOS & macOS builds

---

src/mbgl/text/collision_feature.hpp
src/mbgl/text/collision_index.cpp
src/mbgl/text/collision_index.hpp
src/mbgl/util/grid_index.cpp
src/mbgl/util/grid_index.hpp

- Stops crash on inserting line labels
- Breaks queryRenderedSymbols for now.
[skip ci]
/cc @ansis

Move CollisionIndex to use GridIndex instead of boost::rtree.

---

platform/ios/src/MGLMapView.mm
platform/ios/src/MGLScaleBar.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10266
Invalidating the intrinsic content size was causing MGLMapView's `layoutSubviews` method to be called which called into `_mbglMap->setSize()` that called `mbgl::map::onUpdate()` that triggered (with the new-ish [async rendering updates](https://github.com/mapbox/mapbox-gl-native/commit/b6d56ad634e2b3048e97bedd9f674aa4ec975453)) a call to `rendererFrontend.update()` that caused a camera update that then kicked off the whole process again. 
From what I can tell, this means that in addition to the normal rendering updates, this loop created many many more additional updates and appears to slow the entire animation / gesture down (I think mostly due to transition cancellations).
The change in …

Move scale bar size invalidation

---

platform/ios/src/MGLMapView.mm
platform/ios/src/MGLScaleBar.mm

Cherry picks https://github.com/mapbox/mapbox-gl-native/pull/10277 to the release branch to fix https://github.com/mapbox/mapbox-gl-native/issues/10266 for v3.7.0

Cherry pick 10277 to release-agua

---

cmake/core-files.cmake
src/mbgl/layout/symbol_instance.cpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/programs/collision_box_program.hpp
src/mbgl/programs/programs.hpp
src/mbgl/renderer/buckets/symbol_bucket.cpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/renderer/layers/render_symbol_layer.cpp
src/mbgl/text/collision_feature.cpp
src/mbgl/text/collision_feature.hpp
src/mbgl/text/placement.cpp

- Naive copy-pasting of collision box code: should factor out more of the commonalities
- "Used circle" logic seems to be working correctly
- Rendering seems to break if there are too many circles (probably something to do with segment logic?)
[skip ci]
/cc @ansis

Initial implementation of debug collision circles

---

src/mbgl/programs/collision_box_program.hpp
src/mbgl/programs/symbol_program.cpp
src/mbgl/programs/symbol_program.hpp
src/mbgl/renderer/layers/render_symbol_layer.cpp
src/mbgl/renderer/paint_parameters.cpp
src/mbgl/renderer/paint_parameters.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp

Box collisions are starting to look pretty good.
Circle collisions still look messed up:
- Some line labels don't seem to have matching collision circles
- Doesn't look like the right labels are getting marked as collided
On the plus side:
- Collision circle colors match whether the label shows
- Collision circle fading based on projected label size seems to be working as expected
Fade animations are working as long as you keep the map rendering.
/cc @ansis

Start collision fading

---

src/mbgl/gl/context.cpp

Changes in the way we use vertex buffers introduced in #9009 causes crashes on usage of glBuffer(Sub)Data. This affects line placed text.
Relevant issues:
- Fixes #10152
- Fixes #10151
- Fixes #10150
- Fixes #9935
closes #10233

Blacklist VAO usage on adreno 3xx

---

src/mbgl/tile/geojson_tile.cpp

Check if `getData()` is a valid pointer before proceeding in `GeoJSONTile::querySourceFeatures`.
Initially proposed by @kkaefer.

[core] fix crash when querying GeoJSON tiles

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ColorUtils.java
platform/android/MapboxGLAndroidSDK/src/main/res/values/styles.xml
platform/android/MapboxGLAndroidSDKTestApp/build.gradle
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java
platform/android/dependencies.gradle

This PR moves some dependencies out of the SDK that are only necessary for the Test App.

[android] Reorganize dependencies

---

src/mbgl/text/collision_index.cpp
src/mbgl/util/grid_index.cpp
src/mbgl/util/grid_index.hpp

Flip a boolean to make line label detection work.
Fix a smaller problem in grid index -- queries that are entirely outside the range of the grid should be ignored instead of running geometry tests for all the cells along the borders of the index.
/cc @ansis

Start collision line labels

---

src/mbgl/layout/symbol_layout.cpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/text/collision_feature.hpp
src/mbgl/text/collision_index.cpp

Collision circles should now agree with labels pretty well even in pitched views. @ansis

Hook up tile distance calculation.

---

src/mbgl/renderer/renderer_impl.cpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp

The first commit fixes the occasional flickering of hidden labels.
The second commit fixes collisions in overscaled tiles.
@ChrisLoer

fix collisions for overscaled tiles, and flickering

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MarkerContainer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/ShapeAnnotationContainer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/ShapeAnnotations.java
platform/android/src/android_renderer_frontend.cpp
platform/android/src/android_renderer_frontend.hpp
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

Closes #10234, refs https://github.com/mapbox/mapbox-gl-native/pull/9984 and https://github.com/mapbox/mapbox-gl-native/pull/9443.
This moves the logic as shown in #9984 to core.

Move shape annotation click handling to core

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

With migration to GLSurfaceView we are also waiting for the view to be measured before creating the map object. It's possible that the user destroys the map before the map was fully created. With current codebase this can result in a crash. 
cc @danesfeder

Don't save state if map hasn't been initialised

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/almeros/android/multitouch/gesturedetectors/TwoFingerGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

This PR builds further and fine tunes the integration from #10110.
cc @rooholam

Add velocity to gestures / port animations to SDK animators

---

include/mbgl/util/geo.hpp
test/util/geo.test.cpp

Implement a `LatLngBounds` containment comparison.

[core] LatLngBounds::contains(const LatLngBounds&)

---

include/mbgl/util/projection.hpp
src/mbgl/util/tile_cover.cpp

Needed by Qt builds on Android. These functions are not on the `std::` namespace there.

[gcc4.9] Keep compatibility with GCC + Android

---

platform/qt/mbgl/gl/gl_impl.hpp

When building for certain platforms, don't redefine OpenGL constants
we use.

[qt] Fix build on some archs

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java

Make sure camera position gets updated in onFinish() callback after camera.move

---

src/mbgl/gl/context.cpp
src/mbgl/gl/context.hpp
src/mbgl/gl/index_buffer.hpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/renderer/buckets/symbol_bucket.cpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/text/placement.cpp

Initial implementation of foreground symbol sorting. Based on `start-collision-query` because otherwise I'd have to deal with `SymbolBucket` collisions.
Only tested using "Blanket map with pins" feature (i.e. only tested with icon sorting)
@ansis

Starting on sorting.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Image.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java
platform/android/config.cmake
platform/android/src/jni.cpp
platform/android/src/map/image.cpp
platform/android/src/map/image.hpp
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

Closes #10249, Revisited #10276 by:
- moving the conversion of bitmap -> bytes to an asynctask
- creation/rendering of a View to a bitmap to an asynctask

MapboxMap#AddImages

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapTest.java

Cherry-pick of https://github.com/mapbox/mapbox-gl-native/pull/10321 & https://github.com/mapbox/mapbox-gl-native/pull/10338

Cherry pick IAE to release-agua

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshot.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java
platform/android/src/snapshotter/map_snapshot.cpp
platform/android/src/snapshotter/map_snapshot.hpp
platform/android/src/snapshotter/map_snapshotter.cpp
platform/android/src/snapshotter/map_snapshotter.hpp

Closes #10081, currently targets #10163 but can be retargeted.

Make MapSnapshot logo optional

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnaphotUtil.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java

closes #10036, currently targets #10163 but can be retargeted.

Resize logo based on snapshot size

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10229

[ios, macos] Center shape annotation's callout when offscreen.

---

platform/android/MapboxGLAndroidSDK/src/main/AndroidManifest.xml

android.hardware.location.gps feature should not be required

---

src/mbgl/gl/context.cpp
src/mbgl/gl/context.hpp
src/mbgl/renderer/renderer_impl.cpp

As mentioned by @paoletto in https://github.com/mapbox/mapbox-gl-native/pull/10329#issuecomment-341158497, it turns out we don't need to clear the color buffers _at all_ (including alpha channel) in shared context mode.
This partially reverts commit e350ef37fe68312c4b5fb03b289a90c0bdda4f03.
Ref: https://github.com/mapbox/mapbox-gl-native/pull/10329

Revert "[core] Expose ColorMask in gl::Context::clear()"

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java

This PR iterates on https://github.com/mapbox/mapbox-gl-native/pull/10312 by:
- only allow logo downscaling (prevent pixelated bloated logo)
- correct calculation of the positioning of the logo on the snapshot

Revisit logo resize

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/GLSurfaceViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/egl/EGLConfigChooser.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/egl/EGLConfigException.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRenderThread.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewAnimationActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewDebugModeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewResizeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_textureview_animate.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_textureview_debug_mode.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_textureview_resize.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/categories.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml

Brings back the (deprecated) `TextureView` option, removed in #9576. Built on top of the a-synchronous rendering with a dedicated render thread to unblock the main thread as much as possible.
TODO:

Asynchronous TextureView

---

src/mbgl/layout/symbol_instance.cpp
src/mbgl/layout/symbol_instance.hpp
src/mbgl/renderer/buckets/symbol_bucket.hpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/cross_tile_symbol_index.hpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp

The `CrossTileSymbolIndex` assigns an id that is shared by similar symbols in different tiles. For example, a symbol for `Berlin` in two tiles would have the same ID. This lets us fade symbols across tile boundaries and will also let us apply old placements to newly loaded tiles.
---
@ChrisLoer 
This diffs each layer's current renderTiles internally and updates the index by adding/removing tiles. Removing is currently disabled because it makes the zoom flickering problem worse.

fade symbols across tiles

---

platform/node/test/ignores.json
src/mbgl/layout/symbol_instance.cpp
src/mbgl/layout/symbol_instance.hpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/text/collision_feature.cpp
src/mbgl/text/collision_feature.hpp
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/placement.cpp

On top of adding the overscaling logic to `CollisionFeature`, I had to correct `textPixelRatio` not to include the (superfluous) overscaling factor.
@ansis

Start collision overscaling

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java

closes #10303.This PR works around an Android O bug related to okhttp. Once this is merged a follow up ticket should be created removing the workaround when a new version of okhttp has landed (atm no eta).

Workaround okhttp bug on Android Oreo

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/GLSurfaceViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/egl/EGLConfigChooser.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/egl/EGLConfigException.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRenderThread.java
platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewAnimationActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewDebugModeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/textureview/TextureViewResizeActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_textureview_animate.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_textureview_debug_mode.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_textureview_resize.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/categories.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml

@ivovandongen I went ahead and cherry picked your TextureView commits from https://github.com/mapbox/mapbox-gl-native/pull/10334 to the release branch. I'm using this branch as a base to do some AWS device farm tests.

Cherry pick TextureView

---

src/mbgl/layout/symbol_layout.cpp
src/mbgl/text/placement.cpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/tile.hpp

The problem was that we were creating boxes in the symbol buffer areas and they weren't getting their colors updated. The fix is to avoid creating/updating boxes outside of the tile boundaries (this might need revisiting for api-gl if we need to support debug boxes there).
Also removed placeholder code in `Tile` that ended up not being used.
/cc @ansis @jfirebaugh

Fix coloring for debug collision boxes

---

src/mbgl/renderer/renderer_impl.cpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp

This throttles symbol placement to once every 300ms.
Whenever a new tile is loaded it applies the previous slightly-stale Placement to the new buckets.
@ChrisLoer

throttle symbol placement

---

platform/darwin/src/MGLGeometry.mm
platform/darwin/src/MGLGeometry_Private.h
platform/darwin/src/MGLStyle.mm
platform/darwin/src/MGLStyle_Private.h
platform/ios/CHANGELOG.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/Base.lproj/Localizable.strings
platform/ios/resources/en.lproj/Localizable.stringsdict
platform/ios/src/MGLMapAccessibilityElement.h
platform/ios/src/MGLMapAccessibilityElement.m
platform/ios/src/MGLMapAccessibilityElement.mm
platform/ios/src/MGLMapView.mm
platform/ios/test/MGLMapAccessibilityElementTests.m
platform/macos/macos.xcodeproj/project.pbxproj

After zooming in or out using VoiceOver’s one-finger upward or downward swipe gestures, MGLMapView now summarize the visible places and roads in addition to announcing the new zoom level. The places and roads are all part of the list of accessibility elements within the map view’s container, so the user can now navigate among these features to get a better sense of the map’s contents.
_“Café du Monde: cafe”_
_“Orleans Ave: divided road, northwest to southeast”_
_“Denali: mountain, 20,313 feet”_
These features work in any style that uses the Mapbox Streets source in at least one layer, and it’s mostly localizable (although some parts of the readout are dependent on open-ended OpenStreetMap tags, which are in English). For screen recordings of these features, see [this blog …

Make places and roads accessible to VoiceOver

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/EmptyLocationSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/MapboxTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MockLocationEngine.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationDrawableActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation/MyLocationTrackingModeActivity.java
platform/android/dependencies.gradle

- Reverts adding `mapbox-android-core` dependency 👀 #10354 
@zugaldia @tobrun

[android] Revert adding mapbox-android-core dependency (#10354)

---

platform/android/README.md

Update to the dependencies section of our getting started guide. Restructured parts of the document. Moved non-contributing information to a section called additional resources.
cc @zugaldia

Update installing dependencies doc

---

src/mbgl/layout/symbol_instance.cpp
src/mbgl/layout/symbol_instance.hpp
src/mbgl/layout/symbol_layout.cpp
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp

Only create `SymbolInstance`s for symbols within tile boundaries. This let's us drop all the boundary-checking logic from everywhere else. Later on we'll need to properly set `bool singleTileMode = true` for api-gl in single-tile mode.
@ChrisLoer

drop symbols outside of tile boundaries

---

Makefile
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/AnnotationManagerTest.java

The java unit tests were broken, CI didn't notice as we were trying to build the unit tests from the testapp while they are now found in the SDK. This PR updates the make target and fixes the broken tests.

Fix broken android unit tests, update test make target to SDK

---

src/mbgl/text/glyph.hpp
src/mbgl/text/shaping.cpp

Three render tests were failing because `Shaping` in -js uses floats while `Shaping` in -native uses integers. This fixes the tests by switching to floats in -native. Should we just round in -js instead?
@ChrisLoer 
The tests that were failing because of this difference:
- runtime-styling/set-style-glyphs
- text-font/chinese
- text-visibility/visible

fix three render tests

---

src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/tile.hpp

- Don't render tiles that don't have a symbol layer
- Remove unused tiles/bucket from the cross tile symbol index
- Clear cached "crossTileIDs" from symbol buckets that are removed from the symbol index
Local test situation:
- 6 render failures
- 2 query failures
- 2 unit test failures in Annotations -- these are recent and I'm going to look into them, but I don't think they're caused by this PR.
/cc @ansis @jfirebaugh

Switch to "one-phase" tile loading

---

src/mbgl/gl/context.cpp

Fixes the native equivalent of gl-js issue #5620.
/cc @jfirebaugh @ansis

Unbind VAO before binding a GL_ELEMENT_ARRAY_BUFFER.

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterMarkerActivity.java

The reference to the MapSnapshotter needs to be held for the duration of the snapshot, otherwise it might be GC'd
Fixes #10351

Fix map snapshotter marker example

---

platform/android/src/map_renderer.cpp
platform/android/src/map_renderer_runnable.cpp
platform/android/src/map_renderer_runnable.hpp

Apparently on some devices the weak reference table is limited (numbers around 52000). Even though we don't use that many weak references, when GC is not called for a while they can stack up and a crash will occur before the GC has had the time to clear the references. 
The C++ peer now holds on to a global ref (strong) which can be obtained to queue the java peer and then release automatically so that the GC can take over after the runnable has been executed.
Fixes #10301

MapRendererRunnable - avoid weak reference table overflow

---

.ycm_extra_conf.py
platform/qt/src/http_file_source.cpp
platform/qt/src/http_request.cpp
platform/qt/src/http_request.hpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/sqlite3.cpp

- Cleanup & refactor `QSqlDatabase` usage in the Qt SQLite implementation.
- Fixes an issue in Qt's `HTTPRequest` implementation that causes data corruption when two or more HTTPRequest are pending on the same network reply - the first one gets the data while the following ones gets empty data because `QNetworkReply::readAll()` erases the contents of the data reply.
Fixes #10413.

Qt QSQLite + HTTPRequest updates

---

platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapView.mm

Addresses https://github.com/mapbox/mapbox-gl-native/issues/10010

[ios] Silence smart invert warnings

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterMarkerActivity.java
platform/android/src/map_renderer.cpp
platform/android/src/map_renderer_runnable.cpp
platform/android/src/map_renderer_runnable.hpp

This PR cherry picks a couple of commits to the release branch.
- https://github.com/mapbox/mapbox-gl-native/commit/43f89d6b6a040fea97a882ca620ca7c890afd364
- https://github.com/mapbox/mapbox-gl-native/commit/c30161e4c8d7cbc95b84f1b8dea8f5c7abe242a2
👀 @tobrun @ivovandongen

[android] Cherry picks to agua

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/BulkMarkerActivity.java

For the 5.2.0 release, we are testing with [monkey](https://developer.android.com/studio/test/monkey.htmll) to find edge case crashes. This PR addresses those kind of crashes, most of them are found on the test app, a couple originate from the SDK. Closes #10429. Closes #10434. Refs #10439.

Monkey crashes

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

closes #10390, while the exception in related issue shouldn't happen with normal usage, it can occur with rolling your own selection mechanism. This PR hardens those executions.

Harden deselection mechanism for markers

---

platform/darwin/src/MGLMapSnapshotter.h

Update MGLMapSnapshotter docs

---

platform/node/test/ignores.json
src/mbgl/text/collision_index.cpp
src/mbgl/text/collision_index.hpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp
src/mbgl/util/grid_index.cpp

Don't mark items that are outside the collision grid range as placed.
Requires new ignore because GL JS issue #5654 allows insertion of symbols outside the CollisionIndex range, and those symbols can cascade in to affect items within the viewport.
/cc @ansis @jfirebaugh

Skip fade animation for placed symbols that are currently offscreen.

---

src/mbgl/renderer/renderer_impl.cpp

This fixes placement priority by putting child tiles ahead of parent tiles. -js already does this.
There is a second, slightly related problem that remains unfixed: for areas covered by both parent and child tiles it tries placing symbols from both tiles. This means the duplicate road labels in the parent tile still have priority over labels in some other layers in the child tiles.

sort child symbol tiles before parent symbol tiles

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10391

[ios] Fix toCamera.centerCoordinate in shouldChangeFromCamera 

---

platform/macos/ExportOptions.plist
platform/macos/scripts/deploy-packages.sh
platform/macos/scripts/package.sh

This PR automates the following steps in [the macOS SDK release process](https://github.com/mapbox/mapbox-gl-native/wiki/Releasing-the-Mapbox-macOS-SDK):
> 6. Optionally, build Mapbox GL.app:
>    1. Run make xproj and switch to the macosapp scheme.
>    1. Go to Product ‣ Archive.
>    1. After macosapp finishes archiving, go to the Archives tab of the Organizer window. Select the macosapp archive, then click Export in the right sidebar.
>    1. In the sheet that appears, select “Export a Developer ID–signed Application”.
>    1. Zip up the exported .app and attach it to the release draft.
All in all:

Deploy macosapp as part of releases

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/BulkMarkerActivity.java

- This PR cherry picks a47f8245dacffad2b7f8f71a38b7eb41ee28b0b5 to the release branch.
👀 @osana @tobrun @danesfeder

[android] Monkey crashes cherry pick #10440

---

src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/text/placement.cpp
src/mbgl/text/placement.hpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/tile.hpp

This is a proof-of-concept of doing symbol cross fading by holding on to render tiles until after their symbols have had a chance to fade out. It doesn't take care of issues like avoiding over-draw of non-symbol layers, but it's enough to get a feel for how it might work.
I think it looks fairly promising, although it'll introduce enough complications (questions like: how many of these "hold for fading" tiles will you hold on to during rapid pan/fade operations?) that I'd prefer to push it to a follow-up PR after `viewport-collision` merges, if possible.
**This PR: cross fading**
**Master: instant switch**
/cc @ansis @jfirebaugh @kkaefer  @nickidlugash

viewport-collision: symbol cross-fading

---

platform/ios/src/MGLFaux3DUserLocationAnnotationView.m

Fixes #10471, where the user puck’s stroke’s color wasn’t updating when the tint color changed. Didn’t update the changelog, as this minor issue was introduced during the 3.7.0 pre-release cycle.
/cc @fabian-guerra @suryu

[ios] Update puck arrow stroke color when tint changes

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Updated comment to reflect that MapView's lifecycle callback in a fragment should be called from onDestroyView rather than from onDestroy. This is consistent with that MapFragment is doing.

[android] Update comment from onDestroy to onDestroyView

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewMapRenderer.java

Enables rendering when the app is paused. This ensures that the app continues to render in split-mode.

[android] Enable map rendering when app is paused

---

circle.yml

Default timeout is 10 minutes, [but suddenly we're exceeding that](https://circleci.com/gh/mapbox/mapbox-gl-native/40615) on `release-agua`:
```
Running Clang checks... (this might take a while)
Makefile:360: recipe for target 'check' failed
make: *** [check] Terminated
Too long with no output (exceeded 10m0s)
```
This takes about 8 minutes to run (and succeed) locally on my machine.
/cc @brunoabinader @kkaefer @fabian-guerra

[build] Set clang-tidy timeout to 20 minutes

---

circle.yml
platform/qt/bitrise-qt4.yml
platform/qt/bitrise-qt5.yml

[build] Added CircleCI macos-debug-qt5 job

---

platform/node/bitrise.yml

Fixes Node Bitrise failures [like this one](https://www.bitrise.io/build/02707f9c31deb838) when a tag is pushed but doesn’t conform to `node-v*`.
/cc @Guardiola31337 @fabian-guerra

[node, build] Don't fail on non-node tags

---

platform/ios/src/MGLMapView.mm

Now that the layout of ornaments is based on constraints (as of #9995), updating the content inset should flag that the constraints need updating.
@boundsj @fabian-guerra @1ec5 👀

[ios] Update constraints when updating content inset

---

circle.yml
platform/qt/bitrise-qt4.yml
platform/qt/bitrise-qt5.yml

Brings #10505 to `release-agua`. Replaces the Bitrise macOS Qt builds with a faster one on CircleCI.
/cc @brunoabinader @kkaefer

Cherry-pick: [build] Added CircleCI macos-debug-qt5 job

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java

Activate filesource to list offline regions

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Icon.java

This PR patches up the getBitmap call on Icon to avoid throwing a nullpointer when using the deprecated MarkerView api. Closes https://github.com/mapbox/mapbox-gl-native/issues/10507.

Harden MarkerView integration by checking for null bitmap

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/dependencies.gradle

closes #10369, removing code block refs #10366.

Bump OkHttp - remove Android Oreo crash workaround

---

circle.yml

Move our build images to refreshed images built with our new automated Docker image build flow in https://github.com/mapbox/mbgl-ci-images/pull/9.

Refresh Circle CI docker images

---

platform/android/src/run_loop.cpp
platform/darwin/src/run_loop.cpp
platform/default/run_loop.cpp
platform/qt/src/run_loop.cpp

See https://github.com/mapbox/mapbox-gl-native/issues/9620#issuecomment-346469961
Because a message we queue from the foreground may cause the background to complete, exit, and tear down the AsyncTask, we have to block queue processing until we've finished our call to AsyncTask::send().
Broadening the scope of a mutex is scary, but I audited the code of our four implementations of AsyncTask and I don't see any way this could cause a deadlock.
If we wanted to keep the scope of the mutex as limited as possible, we could move the mutex scope-broadening to `RunLoop::stop()`, with a custom implementation that bypasses `invoke`/`push`, but I'm not sure it would be worth the extra complexity. I suppose the scenario to worry about is that since we're holding the mutex while we call `async->send` …

[core, ios, qt, android] Close race condition in RunLoop (issue #9620)

---

platform/darwin/mbgl/util/image+MGLAdditions.hpp
platform/darwin/src/image.mm
platform/ios/src/UIImage+MGLAdditions.mm
platform/macos/src/NSImage+MGLAdditions.mm

Renaming `CGImageFromMGLPremultipliedImage()` to `CGImageCreateWithMGLPremultipliedImage()` follows [Cocoa naming conventions](https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-SW3), allowing the static analyzer to infer the correct memory management and removing a few warnings.

[darwin, ios] Renames CGImage creation function to imply +1 retain count

---

platform/darwin/src/MGLMapSnapshotter.mm

[darwin] Fixes CGImageRef leak when creating a map snapshot

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Renamed branch from https://github.com/mapbox/mapbox-gl-native/pull/10576 so that CI passes.
- Fixes #10527 
👀 @tobrun @zugaldia @osana

[android] Pre 19 issue with 5.2.0 SDK

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/attribution/AttributionMeasure.java

Attribution anchor point calculation fix for short text with full logo on a MapSnapshot.

Attribution anchor point calculation fix

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcher.java

Refs #10482, replaces #10482 by using a concurrent list instead of synchronising each integration ourselves. cc @yperess

Use concurrent lists for camera change listeners

---

src/mbgl/layout/symbol_projection.hpp

Fails on Qt CI:
https://codereview.qt-project.org/#/c/211971/
```
In file included from src/mbgl/layout/symbol_projection.cpp:1:
In file included from src/mbgl/layout/symbol_projection.hpp:3:
In file included from src/mbgl/util/mat4.hpp:25:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/array:106:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:264:58: error: no matching constructor for initialization of 'mbgl::PlacedGlyph'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:2348:38: note: in instantiation of member function 'std::__1::pair<mbgl::PlacedGlyph, …
```

[build] Clang-3.8: Explicit mbgl::PlacedGlyph default+copy+move ctor

---

CMakeLists.txt
circle.yml
cmake/benchmark.cmake
cmake/core.cmake
cmake/filesource.cmake
cmake/glfw.cmake
cmake/loop-darwin.cmake
cmake/loop-uv.cmake
cmake/node.cmake
cmake/offline.cmake
cmake/render.cmake
cmake/test.cmake
include/mbgl/style/conversion.hpp
platform/android/config.cmake
platform/ios/config.cmake
platform/linux/config.cmake
platform/macos/config.cmake
platform/qt/qt.cmake
src/parsedate/parsedate.c

Enables `-fvisibility=hidden` for iOS and Linux, and adds [a workaround for GCC 6.3-7.1](https://github.com/mapbox/mapbox-gl-native/pull/10499). Also changes a Clang 3.9 build to a GCC 6 build.

[build] standardize on -fvisibility=hidden for all targets

---

include/mbgl/renderer/renderer.hpp
platform/darwin/src/CFHandle.hpp
platform/darwin/src/image.mm
platform/darwin/src/local_glyph_rasterizer.mm
platform/default/local_glyph_rasterizer.cpp
platform/ios/config.cmake
platform/macos/config.cmake
platform/macos/src/MGLMapView.mm
src/mbgl/renderer/renderer.cpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp
src/mbgl/text/glyph_manager.hpp
src/mbgl/text/local_glyph_rasterizer.hpp
src/mbgl/util/i18n.cpp
src/mbgl/util/i18n.hpp
test/text/glyph_manager.test.cpp

This is an experiment in rasterizing glyphs locally using `CTLineCreateWithAttributedString`, for use with TinySDF.
The basics seem to work. Look at render test failures on macos or ios to see the appearance of the locally rendered glyphs.
The guess-based glyph metrics I copied over from the JS implementation don't seem to be quite right. Instead of trying to work out a better guess, I'll look into just getting the metrics directly from CoreText.
There are several TODOs before this is ready for production:
/cc @1ec5 @boundsj

[ios] POC: implementation of a CoreText-based LocalGlyphRasterizer

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Refs https://github.com/mapbox/mapbox-navigation-android/issues/503

handle destroy activity as part of theme switching

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10523

[ios, macos] Fix an issue that triggers didSelectAnnotations

---

platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm

Only the logo view’s baseline is aligned to the attribution view’s baseline; the X-height doesn’t need to be aligned. Previously, macOS ignored the X-height constraint inferred from the alignment rect, but now it honors it in addition to the baseline.
Fixes #10475.
/cc @fabian-guerra @friedbunny

Fix logo view distortion on macOS High Sierra

---

platform/ios/src/MGLMapView.mm
platform/macos/src/MGLMapView.mm

Adding a MGLIdeographicFontFamilyName to the containing app's Info.plist
will result in CJK glyphs being rasterized on demand (#10522)
I'm not really sure how we want to thread this info in, so this is partly a request for comment on the approach. Ultimately it may make sense to have this info live on the style somehow but obviously that would entail much broader scope. This may meet our needs for the time being.
cc/ @ChrisLoer @1ec5 @boundsj

[ios, macos] Adds support for specifying an ideographic font family name

---

Makefile
circle.yml

Simple `plutil -lint` on the important plists in our iOS and macOS SDKs.
/cc @1ec5

[build] Lint iOS and macOS plists on CI

---

Makefile
platform/android/MapboxGLAndroidSDK/gradle-publish.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/Compare.java

- Removes unnecessary `jar` generation from `gradle-publish.gradle`
- Adds `run-android-upload-archives-local` to `Makefile`
- Fixes Javadoc `error: malformed HTML` in `Compare.java`
In the next release, developers will be able to include the SDK as follows:
```groovy
dependencies {
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:{{ VERSION_ANDROID_SDK }}'
}
```
No need to include `@aar` and `transitive = true` anymore 🎉
👀 @tobrun @langsmith

[android] Remove unnecessary jar generation from gradle-publish.gradle

---

src/mbgl/text/placement.cpp

How did this ever work without duplicate symbols?

Don't include .cpp file

---

platform/darwin/src/MGLRendererConfiguration.h
platform/darwin/src/MGLRendererConfiguration.mm
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/src/MGLMapView.mm

Instructions for enabling client-side rendering of CJK glyphs live in
this header, and this class provides the rest of the values needed for
instantiating the renderer on iOS and macOS.
The underlying mechanism for specifying the local font family to use remains unchanged, but hopefully this is a decent starting place if we want to add more options down the road.
cc/ @1ec5 @ChrisLoer

[darwin, ios, macos] Introduces an MGLRendererConfiguration class

---

platform/ios/jazzy.yml
platform/macos/jazzy.yml

Finishes #10212, closes #10121.
Rather than fiddle with the external branch from #10212, I’ve created a new branch/PR with a squashed and updated commit. Apologies for spreading this into a third issue.
/cc @jmkiley @1ec5 @jcfausto

Fix-up: [ios, macos] Snapshot classes added to jazzy

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
platform/android/src/file_source.cpp
platform/android/src/file_source.hpp
platform/android/src/snapshotter/map_snapshotter.cpp
platform/android/src/snapshotter/map_snapshotter.hpp

This PR fixes the bug of the MapSnapshot occasionally not showing up.

add FileSource activation/deactivation to MapSnapshotter

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Icon.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcher.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewMapRenderer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
platform/android/src/file_source.cpp
platform/android/src/file_source.hpp
platform/android/src/run_loop.cpp
platform/android/src/snapshotter/map_snapshotter.cpp
platform/android/src/snapshotter/map_snapshotter.hpp
platform/darwin/src/run_loop.cpp
platform/default/run_loop.cpp
platform/qt/src/run_loop.cpp

This PR cherry picks latest changes from master to the agua release branch:
- https://github.com/mapbox/mapbox-gl-native/pull/10509
- https://github.com/mapbox/mapbox-gl-native/pull/10531
- https://github.com/mapbox/mapbox-gl-native/pull/10532
- https://github.com/mapbox/mapbox-gl-native/pull/10542
- https://github.com/mapbox/mapbox-gl-native/pull/10589
Before merging we need to validate the following:

Cherry-pick to release agua

---

circle.yml
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/dependencies.gradle

With this PR, we are starting to build snapshot builds for the Android SDK. This allows developers to test out custom sources and the upcoming font and expressions work.

Build boba snapshots from master

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CustomGeometrySource.java
src/mbgl/style/custom_tile_loader.cpp
src/mbgl/style/custom_tile_loader.hpp
src/mbgl/style/sources/custom_geometry_source.cpp
src/mbgl/tile/custom_geometry_tile.cpp
src/mbgl/tile/custom_geometry_tile.hpp

`CustomGeometrySource::invalidateRegion` and `CustomGeometrySource::invalidateTile` clear the existing tile contents as part of the invalidation, causing the tile to flash before the new content is laid out. The flash can be longer on slower devices.
https://github.com/mapbox/mapbox-gl-native/blob/8757164ac8f2b033b2b12d4baf075ed18cfeb2b4/src/mbgl/style/custom_tile_loader.cpp#L72
This PR introduces two changes to fix this:
- Hold an `ActorRef<CustomGeometryTile>` to allow calling multiple class methods.
- Marks the `CustomGeometryTile` as stale, requiring that it fetch new data the next time it is being used for rendering.
I'm using `Tile::setNecessity()` as a proxy for determiningg when a tile is being added to a pyramid's render tiles list. Ideally, there'd be a more explicit …

CustomGeometrySource shouldn't flash when invalidating region/tile

---

include/mbgl/util/geo.hpp
src/mbgl/style/custom_tile_loader.cpp
test/util/geo.test.cpp

Fixes #10622.
For custom sources, the `CustomTileLoader::invalidateRegion()` method invalidates all tiles that contain or intersect the provided `LatLngBounds`, using `CanonicalTileID`s. 
The input `bounds` may be wrapped when crossing the antimeridian or when working with wrapped worlds. 
Add `LatLng::WrapMode` as a  parameter to `LatLngBounds::contains()` and `LatLngBounds::intersects()` for comparing bounds in a canonical space.

[core] Add support for wrapped LatLngBounds

---

src/mbgl/gl/color_mode.hpp

`srcFactor` in a Replace operation should be `ZERO`, not `ONE` (would not affect present refactoring results, but this would have affected e.g. heatmap implementation cc @mourner — I noticed in gl-js heatmaps use `blendFunc(ONE, ONE)` + `blend(true)`)

Correct ColorMode::Replace

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

Post animation callback instead of animation itself

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

We have heard about reports that users where able to perform a zoom in gesture while they were pinching out. Some debugging has shown that we weren't correctly creating the wasZoomingIn flag. Instead of checking against `>=` we should have checked against `>` instead.

Fix scale gesture

---

src/mbgl/style/expression/compound_expression.cpp

Replaced manual, per-character upper- and lowercasing code with calls to platform-specific code that affects a wider range of characters. This appears to be more or less consistent with [the behavior in GL JS](https://github.com/mapbox/mapbox-gl-js/blob/537e4dd1bb7d0fcc66062752140bddb775bf1c73/src/style-spec/expression/definitions/index.js#L389-L398).
Fixes #10699.
/cc @anandthakker @tmpsantos

Migrate upcase, downcase to platform code

---

circle.yml
platform/android/dependencies.gradle

This PR updates the CI images to the latest image from https://github.com/mapbox/mbgl-ci-images/pull/14:
- update ndk16 to ndk16b
- update 27.0.1 android build tools to 27.0.2
- update build tools 25.0.2 to 25.0.3

Update CI images

---

Makefile
circle.yml

The current exposed `make android-ui-test-%s` that is responsible for generating 2 apks (one for the test app and one for the instrumented tests) only exposes building for a specific ABI. This PR allows building the tests for all ABI's with `make android-ui-test`. This is usefull when running tests on cloud device farms. Additionally this PR cleans up the Makefile by removing 2 deprecated targets + cleans up the circle config by replacing 3 steps by one that does the same.

Update instrumented make target

---

bin/offline.cpp
bin/render.cpp
cmake/glfw.cmake
cmake/offline.cmake
cmake/render.cmake
platform/glfw/main.cpp
platform/linux/config.cmake
platform/macos/config.cmake

Replaces boost's libprogram_options with Args header-only library for parsing CLI arguments. This simplifies the introduction of clang-3.8 + libc++ in our CI infrastructure and replaces a somewhat heavyweight dependency with a lighter one.
Ref: #10653

[build] Replace boost_libprogram_options with args

---

platform/android/MapboxGLAndroidSDK/src/main/res/values-es/strings.xml
platform/android/MapboxGLAndroidSDK/src/main/res/values-vi/strings.xml

Updated the Android map SDK’s Spanish and Vietnamese translations, including translations of “Mapbox Maps SDK for Android”.
/cc @langsmith

Update Spanish, Vietnamese translations

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java

This PR optimises showing a Map inside a fragment by hiding the surface on startup and only making it visible when the map is ready. Additionally this PR also allows to use multiple subscribers for OnMapReady events.

Remove fragment flash

---

platform/android/MapboxGLAndroidSDK/gradle-checkstyle.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Layer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Property.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/DataDrivenStyleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_data_driven_style.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_generator_symbol.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/actions.xml

This PR adds binding integration for expressions from https://github.com/mapbox/mapbox-gl-native/pull/9439 
```java
mapboxMap.addLayer(new SymbolLayer(LAYER_ID, SOURCE_ID)
.withProperties(
// icon configuration
iconImage(get(FEATURE_ID)),
iconAllowOverlap(false),
iconSize(
division(get(FEATURE_RANK), 2)
),
iconAnchor(ICON_ANCHOR_BOTTOM),
// text field configuration
textField(
concat(
upcase("a "),
get(FEATURE_TYPE),
downcase(" IN "),
get(FEATURE_REGION)
)
),
textSize(
product(get(FEATURE_RANK), pi())
),
textAnchor(TEXT_ANCHOR_TOP)
)
);
```
Closes #9803 
cc @mapbox/android @anandthakker

Expressions

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java

This catches the occurrence mentioned in #10636 and returns the default icon instead.
closes #10636

CompassView decode crash

---

circle.yml

When rebasing patches in https://github.com/mapbox/mapbox-gl-native/pull/10653, the `linux-clang-3.8-libcxx-debug` CI job docker image ended up unchanged. Clang 3.8 does not properly link with GCC-originated `benchmark` and `gtest`, giving errors like:
```
undefined reference to `std::ios_base::Init::Init()'
```
I've tried compiling `benchmark` using C++11 ABI w/o success (same goes for gtest). This is the reason why I ended up removing these steps from the build - as the most important aspect of this CI job, is to have the core source built anyways.

[build] Forgot to update CI image to linux-clang-3.8-libcxx

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Update the Javadoc to reflect the current implementation on [`DoubleMapActivity`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DoubleMapActivity.java).

[android] Update lifecycle documentation for Fragments

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java

I am not sure if we can change the API for union() to be consistent with the rest of LatLngBounds class. 
union(LatLngBounds) renamed the variables to reflect what is being passed. Lon and lat were switched.

Inconsistent parameters to LatLngBounds.union

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/text/LocalGlyphRasterizer.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_local_glyph.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml

Added reference to `/system/etc/fonts.xml` to javadoc, to better explain what the font-family parameter actually does. Stop using "Droid Sans" in the test example because it was misleading -- it wasn't actually in the default font list for any of the devices we had, so instead it was loading the default font. Instead, we use "sans-serif", which will probably load the same font, but using the right nomenclature.
Also fix to broken javadoc links to Bitmap.
/cc @lilykaiser @zugaldia @ivovandongen @Guardiola31337

[android] Tweak TinySDF docs to better describe font-family behavior.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapTouchListenersTest.java

Cherry picks https://github.com/mapbox/mapbox-gl-native/pull/10696.

Map touch listeners API based on lists (cherry pick #10696) 

---

platform/darwin/src/MGLMapSnapshotter.h
platform/darwin/src/MGLMapSnapshotter.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10435

[ios, macos] Remove duplicated variables in MGLMapSnapshotter

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/BitmapUtils.java

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10761.
When getting `Bitmap` from `Drawable`, that's not `BitmapDrawable`, we were manipulating this `Drawable` object's bounds [here](https://github.com/mapbox/mapbox-gl-native/blob/de5357c95f1158d610a958bb0d40029fc73629d7/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/BitmapUtils.java#L67). This occurred when `onSaveInstanceState` was called and was overwritten again in favor of right values in `OnRestoreInstanceState`. However, above issue was present because when we minimize the app activity's `onSaveInstanceState` is called, but `OnCreate` is not, which results in SDK's `OnRestoreInstanceState` not being called.
Anyway, using copied `Drawable` to draw on canvas resolves the issue.

Getting bitmap from drawable fix

---

platform/node/test/ignores.json
src/mbgl/programs/attributes.hpp
src/mbgl/programs/fill_extrusion_program.hpp
src/mbgl/renderer/buckets/fill_extrusion_bucket.cpp
src/mbgl/shaders/debug.cpp
src/mbgl/shaders/fill_extrusion.cpp
src/mbgl/shaders/fill_extrusion_pattern.cpp

Fixes https://github.com/mapbox/mapbox-gl-js/issues/5863 (gl-js counterpart in https://github.com/mapbox/mapbox-gl-js/pull/5895) and updates gl-js submodule to pull in shader changes.

[core] Better align fill-extrusion vertex layout

---

platform/node/test/ignores.json

Broke the build on the last merge because I squashed the relevant gl-js SHA 🤕

Update mapbox-gl-js SHA

---

platform/darwin/src/MGLOpenGLStyleLayer.mm
platform/darwin/src/MGLStyle.mm
platform/darwin/src/MGLStyle_Private.h
src/mbgl/renderer/layers/render_custom_layer.cpp
src/mbgl/renderer/layers/render_custom_layer.hpp

Fixes #10755 
In core, with style diffing a `RenderCustomLayer` instance is reused if the new style has a `CustomLayer` with the same identifier as the previous style. This was not handled correctly in `RenderCustomLayer`. When the `impl` or `context` for the layer is changed, it should invoke the `CustomLayerDeinitializeFunction` callback.
Changes to core GL for asynchronous rendering changed when the `mbgl::style::CustomLayer`'s `CustomLayerDeinitializeFunction` callback method is invoked. This resulted in the `MGLOpenGLStyleLayer` releasing itself early when removed from the owning style:
https://github.com/mapbox/mapbox-gl-native/blob/920057c9d6285fc30f4155a505e2bf15143e3842/platform/darwin/src/MGLOpenGLStyleLayer.mm#L114-L121
When `MGLFinishCustomStyleLayer` is called on a subsequent …

Fix CustomLayer context retain count

---

platform/ios/CHANGELOG.md
platform/ios/INSTALL.md
platform/ios/scripts/metrics.sh
platform/ios/scripts/package.sh
platform/ios/scripts/validate-framework-zip.sh
scripts/publish_binary_size.sh

Removes support for 32-bit simulators (`i386`), such as the iPhone 5 and iPad 2. This does not affect device support — 32-bit devices are still supported via the `armv7` architecture.
This reduces the packaged size of our framework and dSYM by ~25%. This change does not affect the size of apps that integrate our SDK, as simulator architectures aren’t included in shipping apps.
For now, this does not change any Xcode project or mason settings, which allows iosapp to still run in 32-bit simulators. If you need to test using an older form factor using the packaged framework, try using the iPhone 5s, iPad Air, or iPad Mini 2 simulators.
/cc @1ec5 @akitchen @fabian-guerra

[ios, build] Stop packaging i386 simulator arch

---

platform/ios/src/MGLMapView.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/10773
https://github.com/mapbox/mapbox-gl-native/blob/8e69a35d758d4fa632ed153590ae56c976269b76/platform/ios/src/MGLMapView.mm#L743-L750
`constant:5.0 + self.contentInset.top` caused add twice the navigation bar height.

[ios] Fix ornament constrains on iOS 10

---

platform/darwin/src/MGLImageSource.h
platform/darwin/src/MGLMapSnapshotter.h
platform/darwin/test/MGLDocumentationExampleTests.swift

Fixed a crash in MGLDocumentationExampleTests caused by an asynchronous snapshot call that the test wasn’t waiting on, compounded by the use of a style that requires an access token (as opposed to the `one-liner` style that uses no remote resources). Employed some weird-looking Swiftisms to fulfill expectations without making the example code look weird.
Running `make darwin-update-examples` also caught a change to the MGLImageSource example that wasn’t reflected in MGLImageSource.h.
Fixes #10641.
/cc @akitchen @friedbunny

Fix MGLMapSnapshotter test crash

---

platform/ios/src/MGLMapView.h

Adds documentation to clarify how to use coordinate bounds that cross the anti-meridian.

[ios, macos] Fix visible coordinates when boundaries cross international datelline

---

platform/ios/CHANGELOG.md
platform/ios/INSTALL.md
platform/ios/scripts/package.sh

Partially revert #10772, as removing i386 from the framework was deemed too breaking of a change for a semver minor release. This builds and adds i386 everywhere (as before), but later explicitly strips i386 from the dSYM to reduce its file size.
We’ll likely remove i386 entirely in the next semver major release of this SDK.
/cc @akitchen @fabian-guerra

[ios] Re-add i386 slice to framework; strip from dSYM

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngTest.java

LatLng.wrap should wrap multiples of max value to max
closes #10767

LatLng.wrap should return a new instance of LatLng

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec

Updated the CocoaPods podspecs for Mapbox Maps SDK for macOS v0.6.0. Corrected the macOS changelog to remove v0.6.1, which isn’t being released yet.
/cc @fabian-guerra @friedbunny

Mapbox Maps SDK for macOS v0.6.0

---

platform/ios/DEVELOPING.md
platform/ios/INSTALL.md

Update iOS custom build/install docs on GitHub to make clear the requirement for Xcode 9, which came about in #10452.
/cc @jmkiley @akitchen @1ec5

[ios] Update custom install docs for Xcode 9.1

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Follow up from https://github.com/mapbox/mapbox-gl-native/pull/10804.
Fixes #10563.
cc @hashfunction

Hardening map destruction

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/maps/OrientationTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/action/OrientationChangeAction.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/BaseActivityTest.java

This PR adds a integration test that validates possible regressions related to orientation changes. Haven't been able to reproduce the crashes for which this test was created though I feel this would be a great addition to our test suite. 
cc @LukasPaczos

Add orientation change regression test

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/GeometryConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java

 add max & min latitude and longitude constants to maps sdk

---

src/mbgl/annotation/annotation_manager.cpp
src/mbgl/annotation/annotation_manager.hpp
src/mbgl/annotation/fill_annotation_impl.cpp
src/mbgl/annotation/fill_annotation_impl.hpp
src/mbgl/annotation/line_annotation_impl.cpp
src/mbgl/annotation/line_annotation_impl.hpp
src/mbgl/annotation/shape_annotation_impl.cpp
src/mbgl/annotation/shape_annotation_impl.hpp
src/mbgl/map/map.cpp
test/api/annotations.test.cpp

Instead, geometry generation via GeoJSONVT is now bound to the hardcoded limit of the annotation tile source https://github.com/mapbox/mapbox-gl-native/blob/28a21f3b0bb118224dcbe87b017ce74b7a7fab11/src/mbgl/annotation/render_annotation_source.cpp#L41-L43
Fixes https://github.com/mapbox/mapbox-gl-native/issues/10177

Don't tie Annotation geometries to Map maxzoom

---

src/mbgl/annotation/annotation_manager.cpp
src/mbgl/annotation/annotation_manager.hpp
src/mbgl/annotation/fill_annotation_impl.cpp
src/mbgl/annotation/fill_annotation_impl.hpp
src/mbgl/annotation/line_annotation_impl.cpp
src/mbgl/annotation/line_annotation_impl.hpp
src/mbgl/annotation/shape_annotation_impl.cpp
src/mbgl/annotation/shape_annotation_impl.hpp
src/mbgl/map/map.cpp
test/api/annotations.test.cpp

Backporting https://github.com/mapbox/mapbox-gl-native/pull/10791, which fixes #10177

Backport: Don't tie Annotation geometries to Map maxzoom

---

platform/ios/app/Info.plist
platform/ios/docs/guides/Info.plist Keys.md
platform/macos/app/Info.plist
platform/macos/docs/guides/Info.plist Keys.md

Also updates the font to use for rendering CJK ideographs in our sample
apps to `PingFang TC`, as simply specifying `PingFang` was always
triggering iOS's font fallback behavior.
[Fixes #10675]

[ios, macos] Updates documentation to describe font fallback on iOS 8

---

src/mbgl/renderer/tile_pyramid.cpp

Follow up to #7741, we should revisit this feature proposed by @tmpsantos now that #7026 is fixed.

[core] Allow prefetching tiles for all source types

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/LibraryLoader.java

Follow up from https://github.com/mapbox/mapbox-gl-native/pull/10732: 
>Allows API callers to set their own native library loader.
For example, can use https://github.com/facebook/SoLoader
cc @jaegs

Support custom library loader

---

platform/darwin/src/CFHandle.hpp
platform/darwin/src/MGLRendererConfiguration.h
platform/darwin/src/MGLRendererConfiguration.mm
platform/darwin/src/image.mm
platform/darwin/src/local_glyph_rasterizer.mm
platform/ios/app/Info.plist
platform/ios/config.cmake
platform/ios/docs/guides/Info.plist Keys.md
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView.mm
platform/macos/app/Info.plist
platform/macos/config.cmake
platform/macos/docs/guides/Info.plist Keys.md
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/src/MGLMapView.mm

Cherry picks the iOS/macOS code from https://github.com/mapbox/mapbox-gl-native/pull/10522 into `release-agua`

Cherry picks client-side rendering of CJK glyphs into release-agua

---

LICENSE.md
platform/android/MapboxGLAndroidSDK/gradle-javadoc.gradle
platform/ios/app/Info.plist
platform/ios/benchmark/Info.plist
platform/ios/jazzy.yml
platform/ios/uitest/LaunchScreen.xib
platform/macos/jazzy.yml
test/src/app-info.plist

2018 equivalent PR of https://github.com/mapbox/mapbox-gl-native/pull/7595 and https://github.com/mapbox/mapbox-gl-native/pull/3439. This PR updates our licenses to reflect the new year. 
@brunoabinader @tmpsantos do we need to update anything on the qt side?

Happy new year!

---

platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/offline/OfflineUtilsTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/BulkMarkerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/GeoParseUtil.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/utils/OfflineUtils.java

Closes #10762. If possible, I replaced json parsing with GeoJSON models, for other cases I opted for using GSON instead of the json.org models.
cc @zugaldia

Replace low level json parsing

---

platform/node/test/ignores.json
src/mbgl/shaders/collision_circle.cpp
src/mbgl/text/collision_index.cpp
src/mbgl/text/placement.cpp

Fixes issue #10794.
Port of fix to https://github.com/mapbox/mapbox-gl-js/issues/5911.
Add native ignore for tilejson-bounds.
I'm mainly relying on the two new regression tests for GL JS issue #5911, but I also did some quick manual testing using the macosapp, looking at the scene in the original issue, as well as overscaled tiles.
/cc @ansis @asheemmamoowala

Fix distant collision perspective ratios (#10794).

---

src/mbgl/renderer/tile_pyramid.cpp

fix #10833
This reverts a regression in ed5438fc21672e838947c06669dd44051ce24c81 which set `tileZoom = idealZoom` for all types of tiles.
The second change makes it so that panTiles get loaded only if they have a lower *data zoom* (only if they cover a larger area). This avoids reloading the same data tile as a `panTile` for an overscaled tile.
@brunoabinader does the `if (panZoom < idealZoom) {` make sense here?
cc @ChrisLoer

[core] fix loading overscaled tiles

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/egl/EGLConfigChooser.java

Closes #10685. When we migrated to GlSurfaceView, the EglConfig configuration did not take in account Genymotion virtual machines. 

Support Genymotion

---

cmake/core-files.cmake
cmake/test-files.cmake
include/mbgl/util/geo.hpp
include/mbgl/util/projection.hpp
include/mbgl/util/tileset.hpp
platform/node/test/ignores.json
src/mbgl/algorithm/update_renderables.hpp
src/mbgl/annotation/render_annotation_source.cpp
src/mbgl/renderer/sources/render_custom_geometry_source.cpp
src/mbgl/renderer/sources/render_geojson_source.cpp
src/mbgl/renderer/sources/render_raster_source.cpp
src/mbgl/renderer/sources/render_vector_source.cpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/renderer/tile_pyramid.hpp
src/mbgl/style/conversion/tileset.cpp
src/mbgl/style/custom_tile_loader.cpp
src/mbgl/util/geo.cpp
src/mbgl/util/tile_range.hpp
test/style/conversion/tileset.test.cpp
test/util/tile_range.test.cpp

Closes #5394.
Prevent tiles outside of `TileJSON.bounds` from being created in `TilePyramid::update`.

Support TileJSON bounds property

---

platform/ios/CHANGELOG.md
platform/macos/CHANGELOG.md

Added blurbs for #10791 (via #10818), #10522 (via #10817), and #10803 to the iOS and macOS changelogs.

Update iOS, macOS changelogs for v3.7.3/v0.6.1

---

platform/qt/config.cmake
test/storage/offline_database.test.cpp

Remove dead code (`FileLock` class) and replaces raw SQLite 3 functions with our own wrapper. This frees the Qt port from requiring SQLite3 as a dependency (provided via Qt already).
Fixes #10670.

[test] Only use our SQLite3 wrapper in tests

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/BackgroundLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CircleLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillExtrusionLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/FillLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/LineLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/RasterLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/BackgroundLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/CircleLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillExtrusionLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/FillLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LightTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LineLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/RasterLayerTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/SymbolLayerTest.java
platform/android/src/style/layers/raster_layer.cpp
platform/android/src/style/layers/raster_layer.hpp

Closes https://github.com/mapbox/mapbox-gl-native/issues/10846.
This PR fixes up the generated code by:
- removal of the automatic lamba refactor from https://github.com/mapbox/mapbox-gl-native/pull/10549
- use US local during code generation https://github.com/mapbox/mapbox-gl-native/pull/10810

Fix code generation

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUtil.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/LatLngBoundsActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java

closes https://github.com/mapbox/mapbox-gl-native/issues/10825.
cc @danswick

Log failed http request url

---

src/mbgl/gl/context.cpp

Speculative fix for https://github.com/mapbox/mapbox-gl-native/issues/10704
/cc @tobrun @cmxyzx

Blacklist binary program loading for Vivante GC4000 GPUs

---

src/mbgl/gl/context.cpp

Backport https://github.com/mapbox/mapbox-gl-native/pull/10862 to Agua.
/cc @tobrun

Backport: Blacklist binary program loading for Vivante GC4000 GPUs

---

cmake/core-files.cmake
src/mbgl/programs/attributes.hpp
src/mbgl/programs/background_program.cpp
src/mbgl/programs/background_program.hpp
src/mbgl/programs/clipping_mask_program.hpp
src/mbgl/programs/programs.hpp
src/mbgl/renderer/layers/render_background_layer.cpp
src/mbgl/renderer/render_static_data.cpp
src/mbgl/renderer/render_static_data.hpp
src/mbgl/renderer/render_tile.cpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/sources/render_image_source.cpp
src/mbgl/shaders/background.cpp
src/mbgl/shaders/background.hpp
src/mbgl/shaders/background_pattern.cpp
src/mbgl/shaders/background_pattern.hpp
src/mbgl/shaders/clipping_mask.cpp
src/mbgl/shaders/clipping_mask.hpp

Uses separate background, background-pattern and clipping masks shaders.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/10863.
Port of https://github.com/mapbox/mapbox-gl-js/pull/5965.

Use separate shaders for background and clipping

---

include/mbgl/style/expression/parsing_context.hpp
platform/node/test/ignores.json
src/mbgl/style/expression/coalesce.cpp
src/mbgl/style/expression/parsing_context.cpp

Fixes #10588, porting https://github.com/mapbox/mapbox-gl-js/pull/5765. Depends on #10860.

Omit inferred type annotations for 'coalesce' arguments

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java

A user reached out about the change introduced in https://github.com/mapbox/mapbox-gl-native/pull/10664. When an animation is started while another is ongoing, the onCancel callback of the newer animation will be invoked instead of the callback of the old animation.

Use the correct cancelable callback after posting cancel

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUtil.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/egl/EGLConfigChooser.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/BitmapUtils.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/LatLngBoundsActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java

Cherry pick for v5.3.1

---

platform/ios/ios.xcodeproj/project.pbxproj

Adds static target membership to headers that weren’t members, but were already members of the dynamic target. 
I don’t anticipate this having any effect on the build, as I’m guessing these files were already being included in the static target and just weren’t technically members.
Prompted by @1ec5 in https://github.com/mapbox/mapbox-gl-native/pull/10820#issuecomment-355622774.

[ios] Make all headers members of both dynamic and static targets

---

platform/node/test/ignores.json
src/mbgl/renderer/buckets/circle_bucket.cpp
src/mbgl/renderer/layers/render_circle_layer.cpp

Fixes #10307, porting https://github.com/mapbox/mapbox-gl-js/pull/5514.

Account for circle-stroke-width in queryRenderedFeatures

---

platform/darwin/src/MGLVectorSource_Private.h
platform/darwin/src/NSString+MGLAdditions.h
platform/darwin/src/NSString+MGLAdditions.m
platform/darwin/test/MGLNSStringAdditionsTests.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapAccessibilityElement.mm
platform/ios/src/NSOrthography+MGLAdditions.h
platform/ios/src/NSOrthography+MGLAdditions.m
platform/ios/test/MGLMapAccessibilityElementTests.m
platform/ios/test/MGLNSOrthographyAdditionsTests.m

- Fixed pre-iOS 11 compatibility — this now works back to iOS 9 and the test now passes back to iOS 8, unblocking #10742.
- Expanded accessibility label transliteration to all supported Mapbox Streets languages.
This was prompted by:
- [`+[NSOrthography defaultOrthographyForLanguage:]`](https://developer.apple.com/documentation/foundation/nsorthography/2875843-defaultorthographyforlanguage?language=objc) is only available on iOS 11 or newer, making it necessary to create a compatibility shim to get the dominant script for a given language.
- `NSStringTransform` is only available on iOS 9 or newer.
- `NSStringTransform` can also transliterate to other languages we support (e.g., latin → cyrillic).
/cc @1ec5 @akitchen

[ios] Fix and expand accessibility label transliteration

---

circle.yml

Updates all macOS-based CircleCI builds to Xcode 9.2 (from 9.0). Should unblock #10873.
/cc @akitchen @brunoabinader

[build] Update to Xcode 9.2 on CircleCI

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java

Add filesource activation/deactivation to OfflineRegion 

---

circle.yml

Capturing from #10883 that the Firebase step is increasing our CI execution time when it's not being able to assign us a device. The device under test atm is a Motorola Nexus 6 from 2014, to increase reliability I'm suggesting to change it to a Google Pixel running Android 8.0.

Change device under test to Pixel

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java

This PR retains the configuration for user provided focal point and deselect markers on tap.
Closes https://github.com/mapbox/mapbox-gl-native/issues/10907.

Retain configuration 

---

CMakeLists.txt

Backport of https://github.com/mapbox/mapbox-gl-native/pull/10898

Backport: Update vector-tile dependency to 1.0.1

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Up until this point, we were overwriting user-set focal point when camera's tilt was changed and location tracking was enabled. Since I'm not seeing any `MyLocationView` regressions after introducing these changes, I'm just removing the responsible call.

Do not overwrite user-set focal point when tracking location

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcher.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/10923. This PR cleans up overwritten changes from https://github.com/mapbox/mapbox-gl-native/pull/10690 and adds a right invocation of camera callbacks for velocity initiated movements (rotate and scale).
Changes in this PR are temporary workarounds for our gestures handling implementation until https://github.com/mapbox/mapbox-gl-native/issues/10016 lands.

Camera callbacks for velocity animated movements

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/10915:

Replace Mapzen vector source example with Mapillary

---

platform/macos/CHANGELOG.md
platform/macos/Mapbox-macOS-SDK-symbols.podspec
platform/macos/Mapbox-macOS-SDK.podspec

Updated CocoaPods podspecs for Mapbox Maps SDK for macOS v0.6.1.
/cc @fabian-guerra @friedbunny

Mapbox Maps SDK for macOS v0.6.1

---

platform/ios/ios.xcodeproj/project.pbxproj

Since https://github.com/mapbox/mapbox-gl-native/commit/a71868fc8d68fec0b34988d90ef1165c0c87d1db we have been referencing reachability in `mbgl/storage`. This just removes an extra, unused, and incorrect reference in the project file that I noticed while working on something else.

Remove unused reference to reachability

---

src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/cross_tile_symbol_index.hpp
test/text/cross_tile_symbol_index.test.cpp

Port of GL JS PR https://github.com/mapbox/mapbox-gl-js/pull/5994.
Fixes issue #10844, which would allow multiple symbols in a tile to share the same crossTileID as one of their duplicate parent-tile symbols. Once the symbols shared a crossTileID, they would permanently remain "duplicates" of each other, even after increasing zoom level allowed the CrossTileSymbolIndex to distinguish between them.
I've manually tested this with the reuse queue heads-up display. The behavior with "Add 100 views" is that when you first add them, the "queue" count goes to 100, and then next time the map renders the "visible" count updates to 100. Is that the expected behavior? With "Add 10000 views", it shows 9089, visible -- so definitely progress from the earlier behavior, but I take it we're expecting …

[core] Prevent symbols at the same zoom from sharing a crossTileID.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java

Closes #10932, this PR allows the Android SDK to have parity with the iOS SDK in terms of showing the attribution dialog on demand. On top of this, custom instances of AttributionDialogManager can be created and hooked into the attribution click with: 
```java
findViewById(R.id.attributionView).setOnClickListener(yourAwesomeAttribtionManager);
```
This allows to override the protected `showAttributionDialog` and provide a custom implementation.

Expose attribution manager as public API

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUtil.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java

Capturing from an end user that they need to be able to add [Interceptors](https://github.com/square/okhttp/wiki/Interceptors) to requests made by the SDK. To also improve integration for issues as #9640 it makes more sense allow setting an external OkHttpClient instead of exposing the existing one (eg. SSLSocketFactory can only be added as part of the builder).

Allow changing the used OkHttpClient

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLAnnotationView.h
platform/ios/src/MGLAnnotationView.mm

Skips 3D transform (pitch scaling) logic if an `MGLAnnotationView` with `scalesWithViewingDistance = YES` is being shown on an unpitched map.
This change yields a modest 5-10% reduction in the amount of time spent updating view annotation positions in such cases. Since `scalesWithViewingDistance` is enabled by default, this seems worthwhile.
_Moving around an unpitched map, post-optimization._
/cc @boundsj @1ec5

[ios] Optimize MGLAnnotationView scale transform when not pitched

---

src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/tile.hpp

Fixes issue #10778, in which mismatch between FeatureIndex and CollisionIndex could lead to inconsistent results or even invalid array access.
The expected behavior after this change is that the FeatureIndexes used by `queryRenderedFeatures` will only update at the same time placement finishes and the CollisionIndex is updated. This means the results will always be valid, and there shouldn't be any "flickering" in which a symbol disappears from query results in between the time a tile updates and the time the next placement happens. For non-symbol features, this change _opens_ a gap between when they start being rendered (as soon as the tile loads) and when they show up in query results (when placement happens).
This approach relies on placement happening all at once, so we can't port it …

[core] Synchronize state of CollisionIndex and FeatureIndexes.

---

platform/ios/CHANGELOG.md
platform/ios/INSTALL.md
platform/ios/scripts/package.sh

Follows up on #10781 and completely removes support for 32-bit simulators on iOS (as originally proposed in #10772).

[ios] Remove support for 32-bit simulators (i386)

---

src/mbgl/renderer/renderer_impl.cpp
src/mbgl/text/cross_tile_symbol_index.cpp
src/mbgl/text/cross_tile_symbol_index.hpp

Fixes issue #10939 -- removed layers would leak entries in the CrossTileSymbolIndex.
Native analog of https://github.com/mapbox/mapbox-gl-js/pull/6016. The behavior ends up being a little bit different on native because layers get removed from the `order` whenever they're not being rendered (even though they're still part of the style). That means that if you, say, cross to a zoom level where a layer isn't visible, `addLayer` won't get called for that layer, and thus `removeStaleBuckets` won't get called either, and you'll leave behind stale entries. I don't think those stale entries will cause a problem because you're guaranteed that none of the `crossTileIDs` will be in use (and thus it's OK to re-use the IDs when that layer becomes visible again). However, I think the new behavior of …

Prune unused layers from CrossTileSymbolIndex

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/src/main/res/values-he/strings.xml
platform/darwin/resources/he.lproj/Foundation.strings
platform/ios/CHANGELOG.md
platform/ios/framework/Settings.bundle/he.lproj/Root.strings
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/resources/he.lproj/Localizable.strings
platform/macos/CHANGELOG.md
platform/macos/macos.xcodeproj/project.pbxproj
platform/macos/sdk/he.lproj/Localizable.strings

Added a new Hebrew localization of the Android, iOS, and macOS map SDKs from Transifex. The localization isn’t quite 100% complete, but it has passed the 80% threshold for inclusion in this project.
I followed [these instructions](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#adding-a-localization) to add the localization, then added a blurb to each of the changelogs, since it’s a significant enhancement. I kept these changes separate from #10966 because they aren’t quite as straightforward as updating existing translations.
/cc @fabian-guerra @tobrun @akitchen

Add Hebrew localization

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java

A user reported that they were able to get a null Call object when there is no internet connection. Haven't been able to produce the crash though the fix in this PR hardens that part of the codebase.

handle null call instances in HttpRequest

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequestUtil.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/CameraChangeDispatcher.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxEventWrapper.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/DebugModeActivity.java

This PR cherry-picks all the 5.3.2 changes from master to the release branch:
```markdown
- Validate Surface creation before destroying [#10890](https://github.com/mapbox/mapbox-gl-native/pull/10890)
- Add filesource activation ot OfflineRegion [#10904](https://github.com/mapbox/mapbox-gl-native/pull/10904)
- Save configuration of UiSettings [#10908](https://github.com/mapbox/mapbox-gl-native/pull/10908)
- Do not overwrite user-set focal point [#10910](https://github.com/mapbox/mapbox-gl-native/pull/10910)
- Camera callbacks for velocity animated movements [#10925](https://github.com/mapbox/mapbox-gl-native/pull/10925)
- Allow changing the used OkHttpClient [#10948](https://github.com/mapbox/mapbox-gl-native/pull/10948)
- Validate zoom level before creating telemetry event …
```

Cherry pick v5.3.2 changes

---

src/mbgl/style/conversion/layer.cpp
test/fixtures/style_parser/paint-nonobject.info.json
test/fixtures/style_parser/paint-nonobject.style.json

Fixes crash reported in #10226.

Fix style parsing crash when a layer's paint property is not an object

---

include/mbgl/style/conversion/layer.hpp
test/fixtures/style_parser/paint-nonobject.info.json
test/fixtures/style_parser/paint-nonobject.style.json

Fixes crash reported in #10226. Backport of https://github.com/mapbox/mapbox-gl-native/pull/11001

Backport: Fix style parsing crash when a layer's paint property is not an object

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Refs https://github.com/mapbox/mapbox-gl-native/pull/10811#discussion_r163515327

Rename initRenderSurface to onSurfaceCreated

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java

Noticed a regression that a handler can't be created on a thread that hasn't called Looper.prepare. Using the main thread Looper resolves this.

Create Handler using the main thread looper

---

platform/darwin/scripts/generate-style-code.js

This Darwin-specific override, which suppresses heatmap layer code from being generated, was added in #10726 but has been superseded by #10937.
/cc @kkaefer

Remove heatmap layer suppression from Darwin code generator

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java

The use of varargs parameters in the Expressions.java can lead to compiler warnings as:
We can ignore these warnings with annotating the method with `@SafeVarArgs` since  we don't perform potentially unsafe operations on its varargs parameter.

Add SafeVarargs to Expression methods

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HillshadeLayer.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/HillshadeLayerTest.java
platform/android/src/style/layers/hillshade_layer.cpp
platform/android/src/style/layers/hillshade_layer.hpp
platform/darwin/src/MGLHillshadeStyleLayer.h
platform/darwin/src/MGLHillshadeStyleLayer.mm
platform/darwin/test/MGLHillshadeStyleLayerTests.mm
platform/node/test/ignores.json
scripts/generate-shaders.js

* disables transition render test (transitions are not supported with Still image rendering in Node.js) (https://github.com/mapbox/mapbox-gl-native/issues/10619)
* removes support for hillshade-illumniation-direction-transition (https://github.com/mapbox/mapbox-gl-js/issues/5934)

[core] update mapbox-gl-js submodule pin

---

platform/node/src/node_map.cpp
platform/node/src/node_map.hpp
platform/node/test/js/map.test.js
platform/node/test/suite_implementation.js

I worked on fixing a failing regression test in gl-js master (`regressions/mapbox-gl-js#5982`), but eventually noticed that we need https://github.com/mapbox/mapbox-gl-native/issues/10619 in order to test transitions. Meanwhile, this is the `setLight` code that exposes light manipulation in Node.js and to the test harness.

[node] add setLight support

---

src/mbgl/map/transform_state.cpp
src/mbgl/map/transform_state.hpp
src/mbgl/renderer/layers/render_raster_layer.cpp
src/mbgl/renderer/paint_parameters.cpp
src/mbgl/renderer/paint_parameters.hpp
src/mbgl/renderer/sources/render_image_source.cpp

Port https://github.com/mapbox/mapbox-gl-js/pull/6026

Align projection matrix to pixel grids to draw crisp raster tiles

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java

Expression#toString()

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterMarkerActivity.java

When validating if https://github.com/mapbox/mapbox-gl-native/issues/11003 is applicable for Android. I noticed that the marker wasn't really centring when I was expecting it to. To test I used the following [location](https://www.openstreetmap.org/query?lat=52.51450&lon=13.35012#map=19/52.51450/13.35012) from Openstreetmap.

Correct marker location when using Snapshot#pixelForLatLng

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/RasterDemSource.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/HillshadeLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_hillshade_layer.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml
platform/android/config.cmake
platform/android/src/style/sources/raster_dem_source.cpp
platform/android/src/style/sources/raster_dem_source.hpp
platform/android/src/style/sources/source.cpp

closes #11025, this PR adds binding integration for RasterDEMSource + example:
Todo:

add binding integration for RasterDEMSource

---

platform/darwin/src/MGLMapSnapshotter.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11003.

[ios, macos] Fix MGLMapSnapshotter pointForCoordinate returns a scaled point.

---

platform/default/asset_file_source.cpp
platform/default/default_file_source.cpp
platform/default/local_file_source.cpp
src/mbgl/storage/asset_file_source.hpp
test/storage/asset_file_source.test.cpp
test/storage/local_file_source.test.cpp

This is more of a cleanup commit that unifies the implementations and hardens the functionality (by returning an error when attempting to make a request with a URL that doesn't start with the correct scheme rather than failing later down the road).

Align implementations of LocalFileSource and AssetFileSource

---

src/mbgl/style/parser.cpp
test/fixtures/style_parser/font_stacks.json
test/style/style_parser.test.cpp

When a `SymbolLayer` doesn't have a `text-font` defined, we automatically add Open Sans/Arial Unicode MS. However, when the `SymbolLayer` is only used for rendering icons, it doesn't have `text-field` defined either. In those cases, we still force downloading Open Sans/Arial Unicode MS during offline pack creation. If the user doesn't use this font, this change should save ~15MB and a few seconds in download time.

Don't force downloading of Open Sans fonts

---

platform/ios/src/MGLMapView.mm

[ios] Fix image property of MGLAnnotationImage does not update.

---

platform/android/CHANGELOG.md

Changelog for v6.0.0-beta.1

---

platform/android/MapboxGLAndroidSDK/gradle.properties

Yesterday we created the `release-boba` branch from master, both that branch as master are configured to build a 6.0.0-SNAPSHOT when a merge occurs. This PR updates the master configuration to 7.0.0-SNAPSHOT to avoid having 2 branches building the same snapshot version.

Bump snapshot version on master to 7.0.0-SNAPSHOT

---

appveyor.yml

AppVeyor CI is only started atm when a PR is aimed at master. Now that we have a new release branch (release-boba) we are noticing that the CI bot is not running, removing the whitelist from the configuration should solve this. More info [here](https://www.appveyor.com/docs/branches/#white--and-blacklisting).

AppVeyor should build all branches

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/scripts/generate-style-code.js
platform/darwin/src/MGLBackgroundStyleLayer.h
platform/darwin/src/MGLCircleStyleLayer.h
platform/darwin/src/MGLFillExtrusionStyleLayer.h
platform/darwin/src/MGLFillStyleLayer.h
platform/darwin/src/MGLHillshadeStyleLayer.h
platform/darwin/src/MGLLight.h
platform/darwin/src/MGLLineStyleLayer.h
platform/darwin/src/MGLRasterStyleLayer.h
platform/darwin/src/MGLSymbolStyleLayer.h
platform/ios/docs/guides/For Style Authors.md

Added minimum and maximum values to the documentation of numerically bounded style layer properties.
Fixes #10128.

Document ranges of style properties

---

circle.yml
platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDKTestApp/build.gradle

Refs #11060, cherry picks #11061

Release android v6.0.0-beta.1

---

appveyor.yml

Bringing in the same changes as https://github.com/mapbox/mapbox-gl-native/pull/11067. Doing this now on master before we would hit the same issue with new branches as we had with release-boba.

Change AppVeyor config on master

---

platform/ios/ios.xcodeproj/project.pbxproj

#10726 made NSExpression+MGLAdditions.h public in the macOS project but not the iOS project. It also included the file in the iOS SDK’s umbrella header, so I’m concerned there may be some breakage in v4.0.0-beta.1 due to the umbrella header including a nonexistent file.
#5942 would head off problems like this by making all the targets available for selection when adding the file to an Xcode project.
/cc @friedbunny @fabian-guerra

Make NSExpression+MGLAdditions.h public

---

src/mbgl/gl/context.cpp

Capturing from @kkaefer in https://github.com/mapbox/mapbox-navigation-android/issues/534#issuecomment-360329978 that we should try blacklisting Adreno 2xx GPU for VAO support to potentially resolve the crash mentioned in the upstream ticket.

Blacklist adreno 2xx for VAO support

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Closes #11103, This PR avoids calling into `NativeMapView#onLowMemory` when the map isn't fully created yet. This can occur on low memory devices (eg. Android Wearables) when the map is being underway of being created.

Don't invoke onLowMemory when map isn't ready

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyBearingTracking.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java

Follow up on external PR in #11050

Implement new bearingTrackingMode GPS_NORTH_FACING

---

circle.yml
platform/android/scripts/exclude-activity-gen.json

Been monitoring firebase test lab output for #10998. If the firebase step fails it often fails on the same test cases. For now I blacklisted these tests from being generated. Additionally I disabled downloading the results directly to Circle-CI (see https://github.com/mapbox/mapbox-gl-native/issues/10998#issuecomment-361921952).

Blacklist flaky tests & disable download results

---

src/mbgl/renderer/sources/render_raster_dem_source.cpp
src/mbgl/renderer/sources/render_raster_dem_source.hpp
src/mbgl/renderer/sources/render_raster_source.cpp
src/mbgl/renderer/sources/render_raster_source.hpp
src/mbgl/renderer/sources/render_vector_source.cpp
src/mbgl/renderer/sources/render_vector_source.hpp

Closes #10880.
Render sources were resetting the tile pyramid only if the tileset URL templates changed. When recycling maps, a change to `Tileset::bounds` is ignored and previously cached tiles outside the bounds are reused.
Tested with multiple (previously failing) seeds: `v0ZfOIRpA4`, `wTv2gAE0hK` and `tRIdKgDdQD`

Reset tileset-based render sources when any tileset properties changed.

---

src/mbgl/layout/symbol_projection.cpp

Fixes issue #10956.
We could make a rather boring render regression test for this by creating a line label with one 0x0 glyph in it, but not sure it would be that valuable... Do we often make render tests that try to trigger crashes?
/cc @ansis @tobrun

[core] Don't crash on line labels with 0 glyphs.

---

include/mbgl/util/run_loop.hpp
include/mbgl/util/thread.hpp
platform/android/src/run_loop.cpp
platform/darwin/src/run_loop.cpp
platform/default/run_loop.cpp
platform/qt/src/run_loop.cpp
test/util/run_loop.test.cpp

Alternative implementation of https://github.com/mapbox/mapbox-gl-native/pull/10174 that continues to use the existing model, and just prioritizes `pause()` calls by adding them to the front of the queue to address @jfirebaugh's concerns in https://github.com/mapbox/mapbox-gl-native/pull/10174#pullrequestreview-68377496
Implements part 1 of https://github.com/mapbox/mapbox-gl-native/issues/10031

Prioritize thread pause()/resume() calls (Take #2)

---

include/mbgl/style/heatmap_color_property_value.hpp
platform/darwin/scripts/generate-style-code.js
platform/darwin/scripts/style-spec-overrides-v8.json
platform/darwin/src/MGLHeatmapStyleLayer.h
platform/darwin/src/MGLHeatmapStyleLayer.mm
platform/darwin/src/MGLStyleLayer.mm.ejs
platform/darwin/src/MGLStyleValue_Private.h
platform/darwin/test/MGLHeatmapColorTests.mm
platform/darwin/test/MGLStyleLayerTests.mm.ejs
platform/ios/ios.xcodeproj/project.pbxproj
platform/macos/macos.xcodeproj/project.pbxproj

Because `heatmap-color` must be an expression depending only on the `["heatmap-density"]` (`$heatmapDensity`) variable, it's represented in core using a specialized `HeatmapColorPropertyValue` class rather than `PropertyValue<T>` or `DataDrivenPropertyValue<T>`. This change updates the darwin codegen to reflect that.

Specialize codegen for heatmap-color property

---

include/mbgl/style/conversion/custom_geometry_source_options.hpp
include/mbgl/style/sources/custom_geometry_source.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CustomGeometrySource.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/CustomGeometrySourceOptions.java
platform/android/src/style/sources/custom_geometry_source.cpp
platform/darwin/src/MGLAbstractShapeSource.h
platform/darwin/src/MGLAbstractShapeSource.mm
platform/macos/app/MapDocument.m
src/mbgl/tile/custom_geometry_tile.cpp

Closes #10965.
Allow `CustomGeometrySource` data providers to pass in geometry with wrapped coordinates and/or geometry that needs to be clipped to tile boundaries. These options disabled by default and should only be enabled when the source data requires it.

Options to wrap/clip CustomGeometrySource data

---

platform/darwin/src/MGLAbstractShapeSource.h
platform/darwin/src/MGLAbstractShapeSource.mm
platform/macos/app/MapDocument.m

This is a followup to #11041 that renames `MGLShapeSourceOptionWrapCoordinates` to `MGLShapeSourceOptionWrapsCoordinates` and `MGLShapeSourceOptionClipCoordinates` to `MGLShapeSourceOptionClipsCoordinates`, since options are typically named declaratively rather than imperatively. The documentation comments for these options have also been copyedited, in part to use the Objective-C Boolean values.
/cc @asheemmamoowala @julianrex

Copyedit computed source wrapping options

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

closes #11126 
@LukasPaczos how do you feel about the proposed approach?
Other solution would be to keep state and do a cleanup as part of onDestroy.

MapView weak reference in global layout listener

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml

This PR solves a very strange bug with activity recreation and fragments:
> Debugging shows when you recreate the activity, I'm seeing 2 fragments being recreated and both share the same SurfaceView which results in the `setRenderer has already been called for this instance` exception. This should not happen as they both do layout inflation on their own. Creating the SurfaceView programmatically resolves the issue though can't really explain why both fragments share the same SurfaceView. 
Closes #11121

Programmatically create GlSurfaceView

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/src/MGLTileSource.h
platform/darwin/src/MGLTileSource.mm
platform/darwin/test/MGLTileSetTests.mm
platform/ios/CHANGELOG.md
platform/ios/docs/guides/For Style Authors.md
platform/macos/CHANGELOG.md
platform/macos/docs/guides/For Style Authors.md

Added an `MGLTileSourceOptionCoordinateBounds` option for use with MGLTileSource.
Fixes #11058. Depends on #10701, which landed in master after release-agua branched but before release-boba branched.
/cc @asheemmamoowala

Add option to restrict tile source to bounds

---

cmake/core-files.cmake
cmake/test-files.cmake
include/mbgl/style/conversion/tileset.hpp
include/mbgl/util/geo.hpp
include/mbgl/util/projection.hpp
include/mbgl/util/tileset.hpp
platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/src/MGLTileSource.h
platform/darwin/src/MGLTileSource.mm
platform/darwin/test/MGLTileSetTests.mm
platform/ios/CHANGELOG.md
platform/ios/docs/guides/For Style Authors.md
platform/macos/CHANGELOG.md
platform/macos/docs/guides/For Style Authors.md
src/mbgl/algorithm/update_renderables.hpp
src/mbgl/annotation/render_annotation_source.cpp
src/mbgl/renderer/sources/render_geojson_source.cpp
src/mbgl/renderer/sources/render_raster_source.cpp
src/mbgl/renderer/sources/render_raster_source.hpp
src/mbgl/renderer/sources/render_vector_source.cpp
src/mbgl/renderer/sources/render_vector_source.hpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/renderer/tile_pyramid.hpp
src/mbgl/style/conversion/tileset.cpp
src/mbgl/util/geo.cpp
src/mbgl/util/tile_range.hpp
test/style/conversion/tileset.test.cpp
test/util/tile_range.test.cpp

Cherry-pick TileJSON bounds support to the release-agua branch.

Cherry-pick TileJSON bounds support for agua patch 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewRenderThread.java

This PR decouples surface recreation from View resizing. This resolves the crash shown in #10983 and doesn't impact surface destruction that occurs as part of background/foregrounding the application. This branch was tested on a Samsung S8, J3  and a Google Pixel but considering we might include this in a patch release, we need thorough testing with AWS device farm. 
Closes #10983

Don't recreate TextureView surface as part of view resize

---

platform/android/CHANGELOG.md
platform/android/MapboxGLAndroidSDK/gradle.properties
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java

Refs #11162, this PR releases the v5.4.1 of the SDK, additionally it cherry-picks https://github.com/mapbox/mapbox-gl-native/pull/11163/commits/18eebcc47752d02f72b131682a08cc3cebd8fb08 and https://github.com/mapbox/mapbox-gl-native/pull/11109/commits/013965890b82cf67fb4a10ebbeb0eae8d84006b4. Other changes for this release were already on `release-agua`, note that these need to be cherry-picked to release-boba.

Release android v5.4.1

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java
platform/android/src/bitmap.cpp
platform/android/src/bitmap.hpp
platform/android/src/native_map_view.cpp
platform/android/src/native_map_view.hpp

Follow up from external PR in https://github.com/mapbox/mapbox-gl-native/pull/11000. Capturing from @ivovandongen that the config validation part should be re-added:
```java
// Check/correct config
if (image.getConfig() != Bitmap.Config.ARGB_8888) {
image = image.copy(Bitmap.Config.ARGB_8888, false);
}
```
cc @jaegs

NativeMapView.addImage without copying bitmap into Java

---

INSTALL.md

While setting up `mapbox-gl-native` locally, I made some updates and simplifications to `INSTALL.md`
- I moved "Getting the source" after "Installing dependencies" because some users may not have `git` installed initially
- I split the "Installing dependencies" section into two, with simple platform-specific instructions in each.
- I removed some useful but extraneous information from this file. (I may not be the best judge of what's extraneous, please share your thoughts)
- I fixed some link text in the "Setting up a development environment & building" section (iOS -> macOS)

Update & simplify INSTALL.md

---

platform/darwin/src/MGLMapSnapshotter.mm
platform/ios/app/MBXSnapshotsViewController.m

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11117
WIP

[ios, macos] Fix memory leaks in MGLMapSnapshotter.

---

src/mbgl/style/conversion/tileset.cpp
test/style/conversion/tileset.test.cpp

TileJSON spec allows Bounds to be inclusive of world extents [-180 -90, 18, 90]

TileJSON Bounds allows values inclusive of world extents

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

setLatLng constrained documentation + expose LatLngZoom

---

platform/android/MapboxGLAndroidSDK/build.gradle
platform/android/MapboxGLAndroidSDK/proguard-rules.pro

We were still using a compileOnly dependency on lost. This PR removes it from the SDK.

Remove lost dependency from SDK

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/CompassView.java

This PR reverts using ImageView instead of AppCompatImageView. While it's best practice to use AppCompatImageViews for custom views (to enable automatic tinting). It also requires adding the design/appcompat library to the end user application. Often for customers in cn, this was perceived as an issue. To me the customer requests outways the functionality of automatic tinting (eg. attribution icon). In https://github.com/mapbox/mapbox-gl-native/pull/10268 we addressed his by moving to ImageView instead.

Revert to ImageView

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java

With https://github.com/mapbox/mapbox-gl-native/pull/9771 we deprecated MyLocationView and other location related APIs. We seem to have forgotten to deprecate the `LocationSource` found in `Mapbox.java`

Deprecate Mapbox locationengine

---

platform/android/CHANGELOG.md

Release Android v6.0.0-beta.2

---

platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/HeatmapLayerActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_heatmaplayer.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/descriptions.xml
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/values/titles.xml

This PR adds the [gl-js](https://www.mapbox.com/mapbox-gl-js/example/heatmap-layer/) equivalent example to the android test app. 
This PR could benefit from https://github.com/mapbox/mapbox-gl-native/issues/11172 & https://github.com/mapbox/mapbox-gl-native/issues/11174

Add HeatmapLayer example

---

include/mbgl/renderer/renderer.hpp
platform/android/src/android_renderer_frontend.cpp
platform/android/src/android_renderer_frontend.hpp
platform/android/src/native_map_view.cpp
platform/darwin/src/MGLRendererFrontend.h
platform/ios/src/MGLMapView.mm
src/mbgl/annotation/render_annotation_source.cpp
src/mbgl/annotation/render_annotation_source.hpp
src/mbgl/renderer/render_source.hpp
src/mbgl/renderer/renderer.cpp
src/mbgl/renderer/renderer_impl.cpp
src/mbgl/renderer/renderer_impl.hpp
src/mbgl/renderer/sources/render_custom_geometry_source.cpp
src/mbgl/renderer/sources/render_custom_geometry_source.hpp
src/mbgl/renderer/sources/render_geojson_source.cpp
src/mbgl/renderer/sources/render_geojson_source.hpp
src/mbgl/renderer/sources/render_image_source.hpp
src/mbgl/renderer/sources/render_raster_dem_source.cpp
src/mbgl/renderer/sources/render_raster_dem_source.hpp
src/mbgl/renderer/sources/render_raster_source.cpp
src/mbgl/renderer/sources/render_raster_source.hpp
src/mbgl/renderer/sources/render_vector_source.cpp
src/mbgl/renderer/sources/render_vector_source.hpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/renderer/tile_pyramid.hpp

The iOS SDK (https://github.com/mapbox/mapbox-gl-native/issues/9203) and the Nav SDK (https://github.com/mapbox/mapbox-navigation-ios/issues/963) both have issues tied to mbgl holding onto too much memory while in the background, causing iOS to kill the app. This PR tries to make some simple changes to ameliorate the situation:
- https://github.com/mapbox/mapbox-gl-native/commit/b4fb4f6cc4e5edeaa6538250f3b81f92f53bf529 fixes a simple bug in our `onLowMemory` implementation that would prevent us from releasing abandoned buffers after clearing the in memory tile cache.
- https://github.com/mapbox/mapbox-gl-native/commit/52957fd8c47c4016231839631b4b8a76a76b73f9 modifies the iOS SDK to always clear the tile cache on entering the background state. We need to clear the cache when we enter the …

[core,ios] Release more memory on entering background

---

include/mbgl/util/tileset.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HillshadeLayer.java
src/mbgl/geometry/dem_data.cpp
src/mbgl/geometry/dem_data.hpp
src/mbgl/renderer/buckets/hillshade_bucket.cpp
src/mbgl/renderer/buckets/hillshade_bucket.hpp
src/mbgl/style/conversion/tileset.cpp
src/mbgl/tile/raster_dem_tile.cpp
src/mbgl/tile/raster_dem_tile.hpp
src/mbgl/tile/raster_dem_tile_worker.cpp
src/mbgl/tile/raster_dem_tile_worker.hpp
test/geometry/dem_data.test.cpp
test/tile/raster_dem_tile.test.cpp

port of https://github.com/mapbox/mapbox-gl-js/pull/6110 adding support for mapzen terrarium encoded dem RGB tiles.
ended up `#include`ing `Tileset` all over the place because it seemed like the place we store top-level source keys like `encoding`, but not sure this is the best approach – happy to hear suggestions of alternatives.
closes #11204

[core] add support for mapzen terrarium

---

src/mbgl/text/placement.cpp

fix https://github.com/mapbox/mapbox-gl-native/issues/11104
@ChrisLoer is this the fix that you tested?

[core] fix opacity of duplicate labels with -allow-overlap: true

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/GeometryConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java

LatLngBounds did not have an option to specify going over date line bounds.
Stilll need to fix Builder.build() method which should calculate shortest span as new pointe is considered.

 bounds can go over the antimeridian / date line.

---

platform/darwin/test/MGLCoordinateFormatterTests.m
platform/darwin/test/MGLDocumentationExampleTests.swift
platform/darwin/test/MGLExpressionTests.mm
platform/darwin/test/MGLFeatureTests.mm
platform/ios/test/MGLMapViewLayoutTests.m

Fixes a couple build warnings and compatibility issues — see commit messages for the text of the warnings. 
There’s still one broken test on iOS 8 in [`-[MGLExpressionTests testConditionalExpressionObject]`](https://github.com/mapbox/mapbox-gl-native/blob/44ca0a5ec4979138514e8dda10dd1b1173dd0db1/platform/darwin/test/MGLExpressionTests.mm#L575-L594), which will eventually be addressed by https://github.com/mapbox/mapbox-gl-native/issues/11007.
Unblocks https://github.com/mapbox/mapbox-gl-native/pull/10742.
/cc @1ec5 @fabian-guerra @akitchen

[ios] Various test and warning fixes for backwards compatibility

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java

fixed visibleRegion.latlngBounds for rotated map
closes #11137

[android] incorrect latlngBounds in the VisibleRegion when map is rotated

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm

Fixes #11225, expediently. See https://github.com/mapbox/mapbox-gl-native/issues/11225#issuecomment-366386215 for an explanation of the loop mechanism.
While this removes our observer on `UIApplicationWillResignActiveNotification` for now, we should look at whether or not it should be re-added and `sleepGL:`/`wakeGL:` adapted for it.
/cc @julianrex @1ec5 @lilykaiser @akitchen

[ios] Fix loop when first asking for location permission

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java

smallest bounding box for 4 points cannot
be created using LatLngBounds.fromLatLngs()
as the order matters in that method and that does not work for rotated map

[android] fixed LatLngBounds returned by VisibleRegion when map is rotated

---

src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/util/tile_range.hpp
test/util/tile_range.test.cpp

Closes #11213.
Closes #11209.
While panning, tiles may be pre-fetched at a lower zoom level than the current zoom. The `TileRange` class and its use in `TilePyramid` incorrectly assumed that all tiles created are at a single fixed zoom level. 
This PR allows a single instance of `TileRange` to be used in `TilePyramid` with a range of tile zooms, to support loading parent tiles for pre-fetching. I updated the tile range checking to be inclusive of min and max to support the case where the tile range narrows to a single value for lower zoom levels.

[core] Support a range of zooms in TileRange

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/ios/src/MGLMapView.mm

Brings into `master` the relatively simple `ios-v3.7.5` release. At least one of these commits will also need to be cherry-picked into `release-boba`.

Merge ios-v3.7.5 to master

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Events.java

This pr fixes a misspelling that I saw the other day and merges changes into the boba release branch.

Android events initialization method name typo fix

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/11238, this PR hardens the integration by checking if the hosting activity isn't finishing following the advice from this [SO](https://stackoverflow.com/a/18665887)-post.

Check if Activity isn't finishing before showing dialog

---

platform/darwin/test/MGLCoordinateFormatterTests.m
platform/darwin/test/MGLDocumentationExampleTests.swift
platform/darwin/test/MGLExpressionTests.mm
platform/darwin/test/MGLFeatureTests.mm
platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm
platform/ios/test/MGLMapViewLayoutTests.m
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/util/tile_range.hpp
test/util/tile_range.test.cpp

Cherry-picks some recent changes from `master` to `release-boba`:
- #11196 — iOS testing compatibility improvements.
- #11229 — Fix for location permission loop (from `ios-v3.7.5`).
- #11227 — Tile prefetching fixes.
/cc @asheemmamoowala @fabian-guerra

Cherry-pick master changes into release-boba (mid-February edition)

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.h
platform/macos/src/MGLMapView.mm

The `-[MGLMapView convertRect:toCoordinateBoundsFromView:]` method and the `MGLMapView.visibleCoordinateBounds` property’s getter now indicate that the coordinate bounds straddles the antimeridian by extending one side beyond ±180° longitude. This behavior is consistent with how the SDK interprets polyline and polygon coordinates. However, it represents a backwards-incompatible change, inasmuch as developers may have relied on the previous behavior of returning a bounds that starts and ends at the antimeridian.
Fixes #4664.
/cc @jmkiley @fabian-guerra @brunoabinader

Unwrap coordinate bounds

---

platform/node/test/ignores.json
src/mbgl/text/placement.cpp

port of https://github.com/mapbox/mapbox-gl-js/pull/6164

[core] don't hide icons if text is an empty string

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/ImageSource.java
platform/android/src/style/sources/image_source.cpp
platform/android/src/style/sources/image_source.hpp

Expose ImageSource coordinates setter

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/attribution/package-info.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/egl/package-info.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/package-info.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/package-info.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/package-info.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineTilePyramidRegionDefinition.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/package-info.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/package-info.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/functions/CameraFunction.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/functions/Function.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/Light.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/light/Position.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/text/package-info.java
platform/android/scripts/generate-style-code.js

Closes #11260 
Closes #11088 
cc @ChrisLoer

Fix UTF-8 encoding, add missing package-info.java files

---

src/mbgl/renderer/layers/render_heatmap_layer.cpp

Fixes issue #11228.
I couldn't think of any good way to exercise this functionality within our current test-harness, but I did test it manually using the "run these two tests one after the other using a sanitizer build" approach that I used to reproduce the bug in the first place.
@fabian-guerra We probably want to CP this into boba as well. It's probably not the worst bug (should only affect heatmap rendering on resizing viewports on devices that don't support half-float textures), but better never to release it in the first place.
/cc @mourner @brunoabinader

[core] Don't reuse heatmap render texture on viewport resize.

---

platform/android/src/example_custom_layer.cpp
src/mbgl/gl/context.cpp
src/mbgl/renderer/layers/render_custom_layer.cpp

Fixes #8448 
Fixes two issues reported in #8448:
- VAO usage blacklisted on mali-720 to fix https://github.com/mapbox/mapbox-gl-native/issues/8448#issuecomment-313668245 specifically
- Incorrect fragment shader code. Only breaks on older phones it seems
The issues where obscured by the fact that we don't have error checking in the custom layer functions (as it is external code). Any subsequent opengl operation would fail, hinting at unrelated points in the code. This pr adds some checks on calling into the custom layer code to render_custom_layer to makes sure these things are easier to catch. 
Also added error checking code to the example custom layer to make debugging easier in the future.

Custom layer fixes

---

src/mbgl/style/style_impl.cpp
test/map/map.test.cpp

When we load a stale style from cache, and the user immediately starts mutating it, we should continue loading the style so that we'll get a fresh copy of the data into our cache and avoid perpetually showing the stale style.

Continue loading style even if we mutate it

---

src/mbgl/style/style_impl.cpp
test/map/map.test.cpp

Backport: Continue loading style even if we mutate it

---

platform/node/src/node_map.cpp

Avoids a potential crash if garbage collection happens in the middle of a call to NodeMap::request from a map that's eligible for GC.
Fixes issue #11281
I tried to do a scan of other `NodeMap` methods to find others susceptible to the same problem, and I also tried to audit the returned `NodeAsyncRequest` to make sure it never executed invalid code -- but it would be nice to have other eyes on that.
I tested the change with my local reproduction case which depended on inserting a delay into the response to the `render reports an error when the request function responds with an error` test and then doing 5000 v8 heap allocations at the beginning of `NodeMap::request`. I was also using node 4 since that's what failed on the server originally. One concern is that the repro case was not 100% …

[core, node] Hold on to map handle during NodeMap::request

---

platform/qt/src/qmapboxgl_map_observer.cpp

Probably caused by a typo when refactoring the asynchronous rendering.

[qt] Fix wrong signal being emitted

---

src/mbgl/util/tiny_sdf.cpp

Android uses and old libc when building with GCC 4.9 and some math functions are not on std::.

[core] Fix build with Qt + Android + GCC 4.9

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java

This PR reworks the expression API to remove the generic type (for context, see https://github.com/mapbox/mapbox-gl-native/pull/11028).

Rework expression api

---

package.json

Alternative fix to #11288, until we figure out a proper async_hooks implementation.
/cc @jfirebaugh @brunoabinader

[core,node] Pin 'nan' to ~2.8 to avoid Callback::Call deprecation.

---

platform/darwin/docs/guides/For Style Authors.md.ejs
platform/darwin/src/MGLTileSource.h
platform/darwin/src/MGLTileSource.mm
platform/darwin/test/MGLTileSetTests.mm
platform/ios/docs/guides/For Style Authors.md
platform/macos/docs/guides/For Style Authors.md

part of #11224 
@1ec5 I didn't end up following your instructions exactly because `encoding` is not a constructor option for RasterDEMTileset but rather an option on the base `Tileset` class so I didn't understand how to add the option handling further down in the source inheritance – but maybe I'm doing something wrong 😅

add tileset encoding option to darwin sources

---

platform/node/src/node_map.cpp
src/mbgl/renderer/layers/render_heatmap_layer.cpp

Get fixes to #11281 and #11228 onto `master` early so we stop getting CI failures.
/cc @brunoabinader @jfirebaugh

Cherry pick CI fixes from boba to master

---

platform/ios/Integration Tests/MBGLIntegrationTests.m

Added a few more integration tests for custom layer. 
The `testOpenGLLayerDoesNotLeakWhenRemovedFromStyle` test fails, highlighting the issue mentioned in [#11291(comment)](https://github.com/mapbox/mapbox-gl-native/pull/11291#discussion_r170701409)
cc @akitchen @julianrex

[ios] More Custom layer integration tests

---

platform/default/mbgl/storage/offline_database.cpp

Adds a space between `?1` and `WHERE` in the SQL query from `OfflineDatabase::updateMetadata`. Qt's SQLite driver is unable to parse it properly, bailing out instead:
> near "id": syntax error Unable to execute statement
Fixes #11295.

[core] Add space in OfflineDatabase::updateMetadata SQL query

---

INSTALL.md
README.md
platform/qt/README.md
platform/qt/config.qdocconf
platform/qt/src/qmapbox.cpp
platform/qt/src/qmapboxgl.cpp

Rename Mapbox Qt SDK to **Mapbox Maps SDK for Qt**.

[qt] Rename Qt SDK to 'Mapbox Maps SDK for Qt'

---

platform/darwin/src/headless_backend_eagl.mm

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11117 remaining leak.

[ios, macos] Fix a memory leak when creating an EAGLContext in MGLMaSnapshotter

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/GeometryConstants.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java

This is a cherry-pick of #10892

[android] bounds can go over the antimeridian / date line.

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLUserLocationHeadingArrowLayer.m

Fixes #10028. Made the heading indicator arrow 25% larger — this is a simple fix and is as large as the current implementation can go without obvious visual artifacts.

[ios] Improved heading indicator arrow visibility

---

README.md

The old URL has become an unhelpful redirect to the plugin marketplace’s homepage.

Update link to NativeScript plugin

---

platform/ios/CHANGELOG.md

@friedbunny pointed out this should have gone in with #11197, which made it into the last `release-boba` merge.

[ios] Add "clear tile cache on entering background" to changelog

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/app/Main.storyboard
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm

This is an embellishment, brought about by the fact that I have a phone that supports it now. 😉
- Adds light haptic feedback when a user rotates the compass to/across due north.
- Acts as a hint to users that they’ve found north/0°.
- Requires iOS 10+ and a device that supports haptic feedback (iPhone 7 or newer).
- Does not play haptics when the compass auto-snaps back, as that seemed too distracting/disconnected. Could reinvestigate, if folks thought that’d be worthwhile.
- Adds `MGLMapView.hapticFeedbackEnabled`, enabled by default.
- Makes iosapp’s zoom/tilt/rotation HUD persistent across launches and repositions it to the top-left.
/cc @fabian-guerra @akitchen @1ec5

 [ios] Provide haptic feedback when user rotates to due north

---

platform/android/gradle/dependencies.gradle

Bumping version to eliminate bug from https://github.com/mapbox/mapbox-gestures-android/issues/17.

Bumping new gestures library snaphost version

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/HeatmapLayer.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/HeatmapLayerActivity.java
platform/android/scripts/generate-style-code.js
platform/android/src/style/conversion/property_value.hpp
platform/android/src/style/layers/heatmap_layer.cpp
platform/android/src/style/layers/heatmap_layer.hpp
platform/android/src/style/layers/layer.cpp.ejs

This PR adds heatmap color support to the android binding:
@ivovandongen to make this conversion possible I had to add support for the custom `mbgl::style::HeatmapColorPropertyValue`. Is `property_value.hpp` the correct place to do this? 
Closes #11172 
cc @mourner @anandthakker

Add heatmap color property

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/TileSet.java

remaining tail work from #11224 
basically just guessed here, so if there's more to be done please let me know @tobrun

[android] add support for mapzen terrarium raster-dem encoding

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java

This PR replaces the native crash that occurs when creating a snapshot with width or height 0 with an IllegalArgumentException. 

Validate width/height aren't 0 for snapshot

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/snapshotter/MapSnapshotter.java

When creating a Snapshotter through the options class, we were forcing the usage of int while the device destiny can be exposed as a decimal. This PR changes the pixelRatio to float in the options class (no other changes required as float was already used for the actual initialisation).

Use float for pixelratio when creating a snapshotter

---

platform/android/src/map/image.cpp

Capturing from @kkaefer that we were missing a DeleteLocalRef in our image conversion code.

Delete local ref pixel buffers when converting Image.java

---

platform/default/mbgl/storage/offline_database.cpp
platform/default/mbgl/storage/offline_database.hpp
platform/default/sqlite3.cpp
platform/default/sqlite3.hpp
platform/qt/src/sqlite3.cpp
test/storage/offline_database.test.cpp
test/storage/sqlite.test.cpp

Moves the Query/Statement separation from implementation code into the abstract interface and exposes SQLite error codes as enums in the header.

SQLite refactor

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/ios.xcodeproj/project.pbxproj
platform/ios/src/MGLMapView+IBAdditions.h
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/ios/test/MGLMapViewLayoutTests.m
platform/ios/test/MGLMapViewScaleBarTests.m

- Adds `MGLMapView.showsScale` as the recommended way to show the scale bar.
- Adds `IBInspectable` for scale bar visibility.
- Fixes #11302, where the scale bar was not visible until a camera change event. _See note about `scaleBar.hidden` below._
- Includes _two_ changelog entries, because I couldn’t see a concise way to combine the new property with the bug fix.
This isn’t technically breaking — setting `MGLMapView.scaleBar.hidden = NO` will still work, but is no longer the recommended approach.
Setting the scale bar view’s `hidden` property at initialization will now properly show that view when the map loads (because of the new `updateScaleBar` call in `cameraDidChangeAnimated:`), but setting this property later will still cause it not to be visible until a camera event occurs. The …

[ios] Add MGLMapView.showsScale to control scale bar visibility

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapKeyListener.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Transform.java

Rework internal zoomIn/zoomOut to use ValueAnimators

---

platform/android/gradle/gradle-javadoc.gradle

Closes https://github.com/mapbox/mapbox-gl-native/issues/11311
This PR updates our javadoc configuration to be compatible with newer gradle/AS versions. The reason why this broke was the usage of `files()` in our custom gradle javadoc task (see more information about this issue [here](https://issuetracker.google.com/issues/67482030)). Replacing our old config with `variant.javaCompile.source` resolves the issue:
While at it, I also updated the title of the docs to reflect the `Mapbox Maps SDK for Android` naming convention + removed references to the almeros library.

Update javadoc configuration

---

platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapboxgl.cpp
platform/qt/src/qmapboxgl_map_observer.cpp
platform/qt/src/qmapboxgl_map_observer.hpp

Expose `mapLoadingFailed` signal, forwarding the error reason from within the `std::exception_ptr` from MapObserver's `onDidFailLoadingMap`.

[Qt] Expose mapLoadingFailed signal

---

src/mbgl/util/compression.cpp

MinGW ships with zlib headers. No need to use the Qt built-in zlib.

[qt] Fix Qt build on MinGW

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java
platform/android/src/http_file_source.cpp

Closes https://github.com/mapbox/mapbox-gl-native/issues/11412

null check body on http request, cleanup code

---

include/mbgl/style/conversion/tileset.hpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/util/tile_range.hpp
test/style/conversion/tileset.test.cpp
test/util/tile_range.test.cpp

Fixes #11411.
Also cherry-picked #11227, to address #11213 and #11209 for agua.
In mapbox-gl-js, TileJSON bounds longitudes are clamped to [-180,180]. Existing styles benefitted from this clamping when their bounds were outside this range. 
(For example `[-179.9999893871037, -89.99993255000595, 180.00000000000006, 90]`)
In mapbox-gl-native, these longitude values are wrapped to:`[179.9999893871037, -179.99999999999994]`), resulting in bounds with a skinny horizontal extent.
Changed the TileJSON conversion to clamp the bounds, to provide results consistent with mapbox-gl-js.

[agua] Clamp TileJSON bounds

---

src/mbgl/style/conversion/tileset.cpp
test/style/conversion/tileset.test.cpp

Fixes #11411.
In mapbox-gl-js, TileJSON bounds longitudes are clamped to `[-180,180]`. Existing styles benefitted from this clamping when their bounds were outside this range.
(For example `[-179.9999893871037, -89.99993255000595, 180.00000000000006, 90]`)
In mapbox-gl-native, these longitude values are wrapped to:`[179.9999893871037, -179.99999999999994]`, resulting in bounds with a skinny horizontal extent.
Changed the TileJSON conversion to clamp the bounds, to provide results consistent with mapbox-gl-js.

[boba] Clamp TileJSON bounds

---

platform/android/MapboxGLAndroidSDK/proguard-rules.pro
platform/android/MapboxGLAndroidSDK/src/main/AndroidManifest.xml

Closes https://github.com/mapbox/mapbox-gl-native/issues/11417, we can revisit the config once telemetry has configured proguard on their end.  
cc @electrostat

Revisit proguard configuration for release-boba

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXViewController.m
platform/ios/src/MGLMapView.mm

Fixes #11422, where the pinch gesture could drift beyond the bounds imposed by `-[MGLMapViewDelegate mapView:shouldChangeFromCamera:toCamera:]`.
This doesn’t add a unit test, but does add a debug option to iosapp.
/cc @julianrex @fabian-guerra @lilykaiser

 [ios] Fix pinch drift ignoring delegate camera change response

---

platform/ios/CHANGELOG.md
platform/ios/src/MGLMapView.mm
platform/macos/CHANGELOG.md
platform/macos/src/MGLMapView.mm

A copy of PR https://github.com/mapbox/mapbox-gl-native/pull/11168  and added fix for macOS.

[ios, macos] Fix an issue where a wrong annotation may selected if annotations were set close together

---

src/mbgl/map/map.cpp
src/mbgl/renderer/renderer_impl.cpp

No longer sends a update message to the render frontend when rendering in still mode only to shortcut it in the renderer. This prevents unneeded render passes in qt.

Prevent render thread from waking up unneeded on still rendering

---

circle.yml
platform/android/MapboxGLAndroidSDKTestApp/build.gradle

We are constantly encountering issues with dependencies and some of them come in form of `proguard` throwing missing packages warnings when different versions of the same library, containing major differences which we depend on transitively, clash (ex. https://github.com/mapbox/mapbox-gl-native/issues/11417), resulting in users not being able to release their apps with `proguard` enabled.
To quickly catch those types of regressions we can schedule Test App's release build within CircleCI `android-release-all` job. Time-cost of this additional step is barely a couple of seconds.
If this PR is accepted we should hold off on merging until fix for https://github.com/mapbox/mapbox-gl-native/issues/11417 lands, otherwise, all builds will start to fail.
/cc @kkaefer

Building release version of Test App in CI workflow

---

platform/node/test/ignores.json
src/mbgl/shaders/line_pattern.cpp
src/mbgl/style/conversion/stringify.hpp
test/style/conversion/stringify.test.cpp

Fixes #11451, while not attempting to handle the corner case where two layers are alike in all ref properties except for function `default`s.

[core] Stringify expression syntax, not function syntax

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java

This PR fixes `TWO_FINGER_TAP` event from [here](https://github.com/mapbox/mapbox-gl-native/pull/11221/files#diff-dc8b8b458b4be05d4cfad1bbafea82aeL195) that wasn't properly ported to the new gestures handling implementation.

Bringing back missing two-tap telemetry event

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java

Closes #11421, this PR adds correct integration for `literal(Object[])`:
Not commited but a small end-to-end test with:
```
Object[] objectArray = new Object[]{1, "hello"};
Expression textFieldExpression =  Expression.toString(length(literal(objectArray)));
```
Results in showing 2 as symbol text in:

Array expression literal

---

platform/android/config.cmake
platform/android/src/geojson/conversion/feature.hpp
platform/android/src/geojson/conversion/geometry.hpp
platform/android/src/geojson/geometry.cpp
platform/android/src/geojson/geometry.hpp
platform/android/src/geojson/geometry_collection.cpp
platform/android/src/geojson/geometry_collection.hpp
platform/android/src/geojson/line_string.cpp
platform/android/src/geojson/line_string.hpp
platform/android/src/geojson/multi_line_string.cpp
platform/android/src/geojson/multi_line_string.hpp
platform/android/src/geojson/multi_point.cpp
platform/android/src/geojson/multi_point.hpp
platform/android/src/geojson/multi_polygon.cpp
platform/android/src/geojson/multi_polygon.hpp
platform/android/src/geojson/point.cpp
platform/android/src/geojson/point.hpp
platform/android/src/geojson/polygon.cpp
platform/android/src/geojson/polygon.hpp
platform/android/src/geojson/util.hpp
platform/android/src/java/util.cpp
platform/android/src/java/util.hpp
platform/android/src/jni.cpp

Fixes #11212
Depends on #11468

Rework jni geojson bindings

---

platform/android/src/file_source.cpp

closes https://github.com/mapbox/mapbox-gl-native/issues/11473

Verify optional before accessing its value

---

platform/node/test/ignores.json
src/mbgl/text/placement.cpp

Fixes https://github.com/mapbox/mapbox-gl-native/issues/11344. This has been lingering for a while and just (slightly) bit me when I was expecting it to be in boba.
This is the native equivalent of https://github.com/mapbox/mapbox-gl-js/issues/6160 -- not a major bug but something we want to get in nonetheless.
This isn't too late for the next beta of iOS and Android?
/cc @ansis @jfirebaugh @tobrun @friedbunny

CP master->boba: [core] don't hide icons if text is an empty string

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/GestureDetectorActivity.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_gestures.xml
platform/android/gradle/dependencies.gradle

Bumped gestures library version to the first stable release.
This update includes crucial changes like https://github.com/mapbox/mapbox-gestures-android/pull/23 which fixes https://github.com/mapbox/mapbox-gl-native/issues/11441.

Bumped gestures library version to 0.1.0

---

platform/darwin/src/MGLPointAnnotation.h
platform/darwin/src/MGLPointCollection.h
platform/darwin/src/MGLPolygon.h
platform/darwin/src/MGLPolyline.h
platform/darwin/src/MGLShape.h
platform/darwin/src/MGLShapeCollection.h

Documents to use a `MGLFeature` in order to access the attributes of a shape.
Partially addresses #11287

Document to use subclasses of MGLFeature to access attributes

---

platform/ios/CHANGELOG.md
platform/ios/app/MBXCustomCalloutView.m
platform/ios/app/MBXViewController.m
platform/ios/src/MGLCalloutView.h
platform/ios/src/MGLMapView.h
platform/ios/src/MGLMapView.mm
platform/ios/test/MGLAnnotationViewTests.m
platform/ios/vendor/SMCalloutView/SMCalloutView.h
platform/ios/vendor/SMCalloutView/SMCalloutView.m
platform/macos/CHANGELOG.md
platform/macos/app/Base.lproj/MainMenu.xib
platform/macos/app/MapDocument.m
platform/macos/src/MGLMapView.h
platform/macos/src/MGLMapView.mm

See #3249.
If `-[MGLMapView selectAnnotation:animated:]` is called with `animated: YES`,  an offscreen annotation (and its callout) are moved to be just on screen. On-screen annotations are not moved.
If `animated` is `NO` then the annotation is not moved on screen.
This requires #9790 (selecting offscreen annotations)

-[MGLMapView selectAnnotation:animated:] pans map to fit callout view

---

src/mbgl/shaders/collision_box.cpp
src/mbgl/shaders/symbol_icon.cpp
src/mbgl/shaders/symbol_sdf.cpp

Clamps perspective ratios in shaders.
Fixes issue #11487.
Port of GL JS PR #6365.
/cc @ansis @jfirebaugh @malwoodsantoro @friedbunny @tobrun

[core] Avoid flashing on pitched overzoomed tiles.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java

This PR boxes primitive arrays to Object[] to get a correct literal array expression conversion. 
Closes #11498

Literal array conversion of primitive arrays

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java

Refs https://github.com/mapbox/mapbox-gl-native/issues/11498, in particular:
> Expression.step requires three parameters(input expression stops) but documentation doesn't provide description for second parameter
FWIW, we will be adding code examples later as part of https://github.com/mapbox/mapbox-gl-native/issues/11159
cc @sigis151

Make default output from step more descriptive

---

src/mbgl/programs/symbol_program.hpp
src/mbgl/shaders/symbol_icon.cpp
src/mbgl/shaders/symbol_sdf.cpp

Fixes issue #11507.
Port of GL JS PR #6375.
/cc @tobrun @friedbunny @mollymerp @ansis @bsudekum

[core] Double maximum label width by reducing glyph precision.

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Telemetry.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/11493

Expose public API Telemetry

---

include/mbgl/style/data_driven_property_value.hpp
include/mbgl/style/function/camera_function.hpp
include/mbgl/style/function/composite_function.hpp
include/mbgl/style/function/source_function.hpp
platform/node/test/ignores.json
src/mbgl/layout/symbol_layout.cpp

Fixes #10399.
I opted for a fix equivalent to the current approach in gl-js, rather than the approach outlined in https://github.com/mapbox/mapbox-gl-native/issues/10399#issuecomment-342369415. We should refactor to the latter on `master`, but after getting started on it I think it's more involved than we want for boba.

[core] Don't resolve tokens after evaluating a text-field or icon-image expression

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/DataDrivenStyleActivity.java

Closes https://github.com/mapbox/mapbox-gl-native/issues/11502

Convert Android int colors with to-color expression

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/StyleLoaderTest.java

Cherry pick from `release-agua` to `release-boba`, refs https://github.com/mapbox/mapbox-gl-native/pull/11519

Prevent default style reload when string style json was set 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/StyleLoaderTest.java

Prevent default style reload when string style json was set

---

platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/src/NSPredicate+MGLAdditions.h
platform/darwin/src/NSPredicate+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm

[ios, macos] Change the format for case expressions to a flat structure.

---

platform/android/CHANGELOG.md

This PR cherry-picks v5.5.1 changelog update from release-agua to release-boba (will end up in master after merging the release branch back).

Cherry pick v5.5.1 changelog

---

Makefile
circle.yml

Pulls out the immediately viable parts of #10742.
- Adds `ios-sanitize`, which runs both the thread and [undefined behavior sanitizers](https://developer.apple.com/documentation/code_diagnostics/undefined_behavior_sanitizer). Replaces the current `ios-sanitize-thread` build.
- Adds `ios-static-analyzer` — fixes #1549.
- Saves raw Xcode build logs to `build/xcodebuild-YYYY-MM-DD-HMS.log`, which CircleCI then keeps around as build artifacts. Useful for times when xcpretty might obscure a failure.

[build] Run more sanitizers/analyzers on iOS/macOS CI; save Xcode logs

---

platform/android/gradle/dependencies.gradle

Bumping telemetry library to `3.0.0-beta.3`.

Telemetry library 3.0.0-beta.3

---

platform/android/gradle/dependencies.gradle

Bumping gestures library to `v0.2.0`.
This change includes a fix for the minimum required span to register a scale gesture. See https://github.com/mapbox/mapbox-gestures-android/pull/30.

Gestures library v0.2.0

---

bin/offline.cpp

This allows us to run mbgl-offline against `api.mapbox.cn` as well as the default `api.mapbox.com`.
/cc @jfirebaugh @m-stephen

[core] Add 'apiBaseURL' argument to mbgl-offline util.

---

platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/src/NSExpression+MGLPrivateAdditions.h
platform/darwin/test/MGLExpressionTests.mm

[ios, macos] Add lookup and feature operators.

---

src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp

This PR contains two fixes for issue #11538.
The first fix closes a logic error that would prevent the `GeometryTile` "data" member from updating if the data went from non-null to null. This could allow the tile to have an empty `FeatureIndex` with non-empty data (since it would keep the previous non-null data). This could lead to an out of bounds exception being thrown here:
https://github.com/mapbox/mapbox-gl-native/blob/553efa38e3591ce62863d4d74222710f8e3c2337/src/mbgl/geometry/feature_index.cpp#L109
The crash that would be generated doesn't match the stack trace reported in #11538, but it would be likely to happen in the same sort of stress case (quickly adding and removing annotations).
The second fix closes a race condition in which the `FeatureIndex`/`GeometryTileData` received in …

[core] Fix issue #11538 (race condition crash for heavily modified annotations)

---

include/mbgl/util/color.hpp
src/mbgl/style/expression/compound_expression.cpp
src/mbgl/style/expression/interpolate.cpp
src/mbgl/style/expression/value.cpp
src/mbgl/util/color.cpp
test/style/conversion/stringify.test.cpp

Backport of #11564 and mapbox/mapbox-gl-js#6388 to the release-boba branch.
Unblocks #11389. Depends on mapbox/mapbox-gl-js#6427.
/cc @ChrisLoer @anandthakker

Round-trip linear interpolators (release-boba)

---

platform/darwin/docs/guides/Predicates and Expressions.md

Follow-up to #11472.
- Code ticks within HTML tables do not convert to code blocks.
- Pipes within Markdown tables are interpreted as new columns, even within ticks.
/cc @1ec5 @fabian-guerra @jmkiley @captainbarbosa

[ios, docs] Fix formatting in Predicates & Expressions guide

---

platform/darwin/src/MGLStyleValue.mm
platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLCircleStyleLayerTests.mm
platform/darwin/test/MGLExpressionTests.mm
platform/darwin/test/MGLFillExtrusionStyleLayerTests.mm
platform/darwin/test/MGLFillStyleLayerTests.mm
platform/darwin/test/MGLHeatmapColorTests.mm
platform/darwin/test/MGLHeatmapStyleLayerTests.mm
platform/darwin/test/MGLLineStyleLayerTests.mm
platform/darwin/test/MGLStyleLayerTests.mm.ejs
platform/darwin/test/MGLSymbolStyleLayerTests.mm
platform/ios/src/UIColor+MGLAdditions.h
platform/ios/src/UIColor+MGLAdditions.mm
platform/macos/src/NSColor+MGLAdditions.h
platform/macos/src/NSColor+MGLAdditions.mm

Piggy-back on #11156 to more robustly and succintly convert `mbgl::style::expression::Expression`s to JSON-style Foundation objects. ~~Before merging this PR, I might consider merging `MGLJSONObjectFromMBGLValue()` with `ValueEvaluator`.~~
Fixes #11254. Depends on #11391 and #11565.
/cc @anandthakker

Eviscerate mbgl expression to Foundation JSON object conversion

---

circle.yml
platform/darwin/src/MGLPolyline.mm

Fixes #10741, which allows us to enable the dormant `ios-sanitize-address` build on CircleCI.
/cc @1ec5 @akitchen @fabian-guerra @julianrex

[ios, build] Fix heap buffer overflow and enable asan build on CircleCI

---

src/mbgl/geometry/feature_index.cpp
src/mbgl/geometry/feature_index.hpp
src/mbgl/tile/geometry_tile.cpp
src/mbgl/tile/geometry_tile.hpp
src/mbgl/tile/geometry_tile_worker.cpp
src/mbgl/tile/geometry_tile_worker.hpp
test/tile/vector_tile.test.cpp

This is an alternative to PR #11570 as a fix for issue #11538.
It's a more complicated change than #11570, but it addresses some of the root cause by removing unnecessary intermediate state from `GeometryTile` (we wanted to make these changes already: tracked as issue #10457). I used @friedbunny's repro branch to verify that it fixes #11538.
While `GeometryTile` gets simpler because it no longer maintains a half-loaded (everything but symbol buckets) state, some of the complexity moves to `GeometryTileWorker` because it becomes responsible for holding on to the `featureIndex` and `nonSymbolBuckets` in the period between `parse()` and `performSymbolLayout()`.
This PR brings us a little closer to the JS behavior, but native is still significantly more complicated. The primary reason is that …

[core] Convert GeometryTileWorker to "one-phase" loading

---

include/mbgl/renderer/renderer_backend.hpp
include/mbgl/style/layers/custom_layer.hpp
platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/CustomLayer.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/customlayer/CustomLayerActivity.java
platform/android/src/example_custom_layer.cpp
platform/android/src/style/layers/custom_layer.cpp
platform/android/src/style/layers/custom_layer.hpp
platform/darwin/src/MGLOpenGLStyleLayer.mm
platform/darwin/src/MGLStyle.mm
platform/darwin/src/MGLStyle_Private.h
platform/ios/Integration Tests/MBGLIntegrationTests.m
platform/qt/include/qmapbox.hpp
platform/qt/include/qmapboxgl.hpp
platform/qt/src/qmapbox.cpp
platform/qt/src/qmapboxgl.cpp
src/mbgl/renderer/layers/render_custom_layer.cpp
src/mbgl/renderer/layers/render_custom_layer.hpp
src/mbgl/style/layers/custom_layer.cpp
src/mbgl/style/layers/custom_layer_impl.cpp
src/mbgl/style/layers/custom_layer_impl.hpp
test/api/custom_layer.test.cpp

Fixes #11143.
Fixes #10771.
`CustomLayer`s are a special class of style layer where the core API delegates rendering of the layer to external code. 
With the change to asynchronous rendering, the `RenderCustomLayer` may call out to the external code to initialize, render, or clean-up outside of the `CustomLayer`'s lifecycle. For example, a custom layer added to the current map style, followed by a different style being set on the map.
In addition to #11143, a number of other issues related to custom layers have been opened/addressed recently: #10771, #10755, #10765, #11343. 
The existing API using a`void *` context object and function pointers, doesn't provide any lifecycle information. The context object needs to exist for the lifetime of the `CustomLayer` (`CustomLayer::Impl` to be more …

Use a host interface for CustomLayer instead of function pointers

---

platform/ios/CHANGELOG.md
platform/ios/Mapbox-iOS-SDK-nightly-dynamic.podspec
platform/ios/Mapbox-iOS-SDK-symbols.podspec
platform/ios/Mapbox-iOS-SDK.podspec
platform/macos/CHANGELOG.md

Added changelog entries for #11206, #11488, #11508, and #11551.
/cc @1ec5 @julianrex @fabian-guerra @lilykaiser

[ios] Release ios-v4.0.0-beta.3

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java

This PR catches the common pitfall of using a PropertyValue inside an expression. This typically occurs  when  a user migrates from the old dds approach to the new expression syntax. 
closes #11572

Throw exception when converting PropertyValue with an expression 

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java

Refs. https://github.com/mapbox/mapbox-gl-native/issues/11577.
Even though the bug is already fixed on `release-boba` thanks to the removal of the `TrackingSettings` we can future-proof by invalidating the camera position before delivering the `onMapReady` callback.

Invalidate camera position before delivering onMapReady

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/LightTest.java
platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/light.junit.ejs
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java

When reworking our DDS examples to the new API, we noticed that the current convenience methods of logical conditions of something as `eq(String, String)` didn't make much sense. This is because IRL you will use at least one expression in there. This PR addresses this by change the syntax to use one epxresssion and one literal value.

Rework logical condition convenience expressions 

---

platform/android/gradle/dependencies.gradle

Closes #11554.
/cc @electrostat

Bumped telemetry library version to 3.0.0-beta.4

---

platform/android/CHANGELOG.md

CPs changelogs for `5.5.1`, `6.0.0-beta.5` and `6.0.0-beta.6` to master.
Refs. https://github.com/mapbox/mapbox-gl-native/issues/11525, https://github.com/mapbox/mapbox-gl-native/issues/11536, https://github.com/mapbox/mapbox-gl-native/issues/11591.

CP missing changelog entries to master

---

platform/android/MapboxGLAndroidSDK/proguard-rules.pro
platform/android/gradle/dependencies.gradle

addresses https://github.com/mapbox/mapbox-java/issues/783

[android] updated mapbox-sdk-services to 3.0.1

---

include/mbgl/style/layers/custom_layer.hpp
platform/darwin/src/MGLGeometry.h
platform/darwin/src/MGLGeometry.mm
platform/darwin/src/MGLOpenGLStyleLayer.h
platform/darwin/src/MGLOpenGLStyleLayer.mm
platform/darwin/src/NSValue+MGLAdditions.h
platform/darwin/src/NSValue+MGLAdditions.m
platform/darwin/test/MGLGeometryTests.mm
src/mbgl/renderer/layers/render_custom_layer.cpp

When working with `CustomLayer` or `MGLOpenGLStyleLayer` the render parameters do not include a projection matrix. While each point could be converted from `LatLng` to screen coordinates using `pixelForLatLng()`, this is inefficient for a large number of points and for points that are outside the screen bounds in pitched views.

Add Projection matrix to the CustomLayer render parameters

---

src/mbgl/gl/program.hpp

CP 11538 to release-boba

---

platform/darwin/src/NSExpression+MGLAdditions.mm
platform/darwin/test/MGLExpressionTests.mm

An argument to a `case` expression is a conditional or value depending on its index, not its data type. Also added support for `valueForKey:`, which is a common alternative to `valueForKeyPath:`, inside function expressions.
Fixes #11613.

Distinguish between conditionals and expressions in case expressions

---

platform/android/src/image.cpp
platform/android/src/text/local_glyph_rasterizer.cpp

A few more instances where JNI local references can be cleared earlier.

Android - release local refs

---

platform/android/src/offline/offline_manager.cpp
platform/android/src/offline/offline_region.cpp
platform/android/src/snapshotter/map_snapshotter.cpp

WIP, going over the project to spot missing DeleteLocalRefs.

Add missing jni::DeleteLocalRef

---

include/mbgl/style/conversion/data_driven_property_value.hpp
include/mbgl/style/expression/let.hpp
platform/node/test/ignores.json
src/mbgl/style/expression/parsing_context.cpp

Fix style parsing bug for constant expressions

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java
platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/imagegenerator/SnapshotActivity.java
platform/android/src/map_renderer.cpp
platform/android/src/map_renderer.hpp
platform/android/src/native_map_view.hpp

This PR adds null checking to the java peer before calling into a NativeMapView callback. 
With the `Mapbox#snapshot` api I was able to reproduce:
> JNI DETECTED ERROR IN APPLICATION: can't call void com.mapbox.mapboxsdk.maps.NativeMapView.onSnapshotReady(android.graphics.Bitmap) on null object
When requesting a snapshot as part of Activity#onPause:
```java
@Override
protected void onPause() {
super.onPause();
mapboxMap.snapshot(new MapboxMap.SnapshotReadyCallback() {
@Override
public void onSnapshotReady(Bitmap snapshot) {
Timber.e("snapshot ready");
}
});
mapView.onPause();
}
```
This could potentially explain crashes as https://github.com/mapbox/mapbox-gl-native/issues/11268.

Null java peer callback

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java

WIP, this PR adds inline expression code examples to the javadoc.
closes #11159

Add javadoc code examples

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java

closes https://github.com/mapbox/mapbox-gl-native/issues/11640

Convenience step expression

---

platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java
platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/geometry/LatLngBoundsTest.java

LatLngBounds were not build correctly when points with
same longitudes were added first.
closes #11629

[android] LatLngBounds were not build correctly when lon was the same

---

README.md
circle.yml

Bumps to Xcode 9.3 on CircleCI, which became available today. The [container’s](https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-405/index.html) version of macOS has also been updated to 10.13.3 (High Sierra) from 10.12.6 (~Low~ Sierra), so there could be some teething pains to work out before merging.

[build, ios] Bump CircleCI builds to Xcode 9.3
